export type AutonomyReadinessErrorCode =
  | "AUTONOMY_LEVEL_INVALID"
  | "AUTONOMY_SCOPE_EXCEEDED"
  | "AUTONOMY_GOVERNANCE_UNBOUND"
  | "AUTONOMY_REPLAY_UNBOUND"
  | "AUTONOMY_SNAPSHOT_UNBOUND"
  | "AUTONOMY_DISPUTED"
  | "AUTONOMY_EXECUTION_FORBIDDEN"
  | "AUTONOMY_ORCHESTRATION_FORBIDDEN"
  | "AUTONOMY_SELF_AUTHORIZATION_FORBIDDEN"
  | "AUTONOMY_CAPABILITY_DRIFT"
  | "AUTONOMY_UNKNOWN_AUTHORITY"
  | "AUTONOMY_FORBIDDEN";

export type AutonomyReadinessError = Readonly<{
  code: AutonomyReadinessErrorCode;
  message: string;
  path?: string;
}>;
