import { getSessionUser } from "@/src/lib/auth";
import { AppError } from "@/src/server/api/errors";
import { apiError, apiSuccess } from "@/src/server/api/response";
import { requireWorkspaceManager } from "@/src/server/auth/permissions";
import { EvaluationArtifactService, PrismaEvaluationArtifactRepository, PrismaLearningAuditLedger } from "@/services/learning-constitution";
import type { CompetenceEvaluationRubric, Evaluation } from "@/types/learning-constitution";
export const dynamic = "force-dynamic";
const userFor = async () => { const user = await getSessionUser(); if (!user) throw new AppError(401, "unauthorized", "Authentication required."); if (!user.workspaceId || user.workspaceId === "default") throw new AppError(403, "workspace_required", "Workspace membership is required."); await requireWorkspaceManager({ userId: user.id, userRole: user.role, workspaceId: user.workspaceId }); return user; };
export async function GET() { try { const user = await userFor(); const artifacts = await new PrismaEvaluationArtifactRepository(user.workspaceId!).listWorkspaceArtifacts(); return apiSuccess({ evaluations: artifacts.filter((artifact) => artifact.artifactType === "EVALUATION").map((artifact) => artifact.payload as Evaluation) }); } catch (error) { return apiError(error, "Unable to load evaluations."); } }
export async function POST(request: Request) { try { const user = await userFor(); const body = await request.json() as { evaluation?: Evaluation; rubric?: CompetenceEvaluationRubric }; if (!body.evaluation || !body.rubric) throw new AppError(400, "evaluation_invalid", "An evaluation and matching rubric are required."); const now = new Date().toISOString(); const evaluation: Evaluation = { ...body.evaluation, createdAt: now, evaluator: { ...body.evaluation.evaluator, actor: { actorId: `user:${user.id}`, actorType: "HUMAN" }, independent: true } }; const service = new EvaluationArtifactService(new PrismaEvaluationArtifactRepository(user.workspaceId!), new PrismaLearningAuditLedger(user.workspaceId!)); const lifecycle = await service.initialize(evaluation, body.rubric, user.workspaceId!, `evaluation:${evaluation.evaluationId}`); return apiSuccess({ evaluation, lifecycle }, { status: 201 }); } catch (error) { return apiError(error, "Unable to create evaluation."); } }
