import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runIdentityCore, validateIdentityCore } from "@/services/identity-core";
import type { IdentityFullBundle, IdentityFullDecision, IdentityFullFailure, IdentityFullInput, IdentityFullResult, IdentityFullScenario, IdentityFullValidation } from "@/types/identity-full";

const VERSION = "identity-full/w1.1b" as const;
const IDENTIFIER = "IdentityFull" as const;
let identityCoreBaseline: ReturnType<typeof runIdentityCore> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly IdentityFullFailure[], failure: IdentityFullFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: IdentityFullScenario): IdentityFullFailure | undefined { return scenario === "BASELINE" || scenario === "READY_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly IdentityFullFailure[], scenario: IdentityFullScenario): IdentityFullDecision {
  if (has(failures, "W1_1A_IDENTITY_CORE_INVALID") || has(failures, "SESSION_TENANT_ISOLATION_VIOLATED") || has(failures, "RECOVERY_AUTHORIZATION_FAILED") || has(failures, "RECOVERY_CRYPTOGRAPHIC_VERIFICATION_FAILED") || has(failures, "DELEGATION_SCOPE_VIOLATED") || has(failures, "FEDERATION_TRUST_RELATIONSHIP_INVALID") || has(failures, "IDENTITY_EVIDENCE_NOT_IMMUTABLE") || has(failures, "IDENTITY_EVIDENCE_NOT_SIGNED") || has(failures, "IDENTITY_EVIDENCE_NOT_REPLAYABLE")) return "FAIL_CLOSED";
  if (has(failures, "STORAGE_FULL_MISSING") || has(failures, "SECURITY_FULL_MISSING") || has(failures, "MESSAGING_CORE_MISSING") || has(failures, "REGISTRY_CORE_MISSING") || has(failures, "OBSERVABILITY_PLATFORM_MISSING") || has(failures, "IDENTITY_INFRASTRUCTURE_GATE_FAILED")) return "NOT_READY";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_READY";
  if (scenario === "READY_WITH_OBSERVATIONS") return "READY_WITH_OBSERVATIONS";
  return "IDENTITY_INFRASTRUCTURE_READY";
}
function resultReplayHash(result: Omit<IdentityFullResult, "replay_hash" | "integrity_hash">): string { return hash({ sessions: result.sessions.integrity_hash, credentials: result.credentials.integrity_hash, recovery: result.recovery.integrity_hash, suspension: result.suspension.integrity_hash, delegation: result.delegation.integrity_hash, federation: result.federation.integrity_hash, evidence: result.evidence.integrity_hash, qualification: result.qualification.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<IdentityFullResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runIdentityFull(input: IdentityFullInput = {}): IdentityFullResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<IdentityFullFailure>(direct ? [direct] : []);
  identityCoreBaseline ??= runIdentityCore();
  const coreInvalid = !validateIdentityCore(identityCoreBaseline).valid || has(scenarioFailures, "W1_1A_IDENTITY_CORE_INVALID");
  const failures = freezeArray([...new Set([...scenarioFailures, ...(coreInvalid ? ["W1_1A_IDENTITY_CORE_INVALID" as const] : [])])]);
  const entryOk = !coreInvalid && !has(failures, "STORAGE_FULL_MISSING") && !has(failures, "SECURITY_FULL_MISSING") && !has(failures, "MESSAGING_CORE_MISSING") && !has(failures, "REGISTRY_CORE_MISSING") && !has(failures, "OBSERVABILITY_PLATFORM_MISSING");
  const sessionsOk = !has(failures, "SESSION_MANAGEMENT_MISSING") && !has(failures, "SESSION_EXPIRATION_INVALID") && !has(failures, "SESSION_RENEWAL_FAILED") && !has(failures, "SESSION_REVOCATION_FAILED") && !has(failures, "MULTI_DEVICE_SESSIONS_INVALID") && !has(failures, "SESSION_TENANT_ISOLATION_VIOLATED");
  const credentialsOk = !has(failures, "CREDENTIAL_LIFECYCLE_MISSING") && !has(failures, "CREDENTIAL_ROTATION_FAILED") && !has(failures, "CREDENTIAL_REVOCATION_FAILED") && !has(failures, "KEY_ROLLOVER_FAILED") && !has(failures, "PASSWORD_POLICY_MISSING") && !has(failures, "MFA_ENROLLMENT_FAILED");
  const recoveryOk = !has(failures, "IDENTITY_RECOVERY_MISSING") && !has(failures, "RECOVERY_AUTHORIZATION_FAILED") && !has(failures, "RECOVERY_GOVERNANCE_APPROVAL_MISSING") && !has(failures, "RECOVERY_CRYPTOGRAPHIC_VERIFICATION_FAILED");
  const suspensionOk = !has(failures, "IDENTITY_SUSPENSION_MISSING") && !has(failures, "SUSPENSION_AUDIT_INCOMPLETE") && !has(failures, "RESTORATION_FLOW_INVALID");
  const delegationOk = !has(failures, "DELEGATED_AUTHORIZATION_MISSING") && !has(failures, "DELEGATION_SCOPE_VIOLATED") && !has(failures, "DELEGATION_EXPIRATION_INVALID") && !has(failures, "DELEGATION_REVOCATION_FAILED") && !has(failures, "DELEGATION_CHAIN_INVALID");
  const federationOk = !has(failures, "FEDERATION_INTERFACES_MISSING") && !has(failures, "FEDERATION_TRUST_RELATIONSHIP_INVALID") && !has(failures, "EXTERNAL_IDENTITY_MAPPING_FAILED") && !has(failures, "FEDERATION_POLICY_ENFORCEMENT_FAILED");
  const evidenceOk = !has(failures, "IDENTITY_EVIDENCE_INCOMPLETE") && !has(failures, "IDENTITY_EVIDENCE_NOT_IMMUTABLE") && !has(failures, "IDENTITY_EVIDENCE_NOT_SIGNED") && !has(failures, "IDENTITY_EVIDENCE_NOT_REPLAYABLE") && !has(failures, "IDENTITY_EVIDENCE_NOT_SEARCHABLE");
  const qualificationOk = !has(failures, "FUNCTIONAL_QUALIFICATION_FAILED") && !has(failures, "SECURITY_QUALIFICATION_FAILED") && !has(failures, "OPERATIONAL_QUALIFICATION_FAILED") && !has(failures, "GOVERNANCE_QUALIFICATION_FAILED") && !has(failures, "IDENTITY_INFRASTRUCTURE_GATE_FAILED");
  const decision = decisionFor(failures, scenario);
  const sessions = nested({ service_id: sessionsOk ? `service:w1.1b:sessions:${input.seed ?? "canonical"}` : "", session_registry: sessionsOk ? freezeArray(["session:platform:primary", "session:tenant:alpha", "session:tenant:beta"]) : freezeArray<string>([]), session_tokens: sessionsOk, deterministic_expiration: sessionsOk, renewal: sessionsOk, revocation: sessionsOk, multi_device_sessions: sessionsOk, tenant_isolation: sessionsOk, audit_recorded: sessionsOk });
  const credentials = nested({ registry_id: credentialsOk ? "registry:w1.1b:credentials" : "", issuance: credentialsOk, rotation: credentialsOk, renewal: credentialsOk, expiration: credentialsOk, revocation: credentialsOk, key_rollovers: credentialsOk, password_policies: credentialsOk, mfa_enrollment: credentialsOk, credential_types: credentialsOk ? freezeArray(["certificate", "api", "user", "service", "workload"]) : freezeArray<string>([]) });
  const recovery = nested({ ledger_id: recoveryOk ? "ledger:w1.1b:recovery" : "", recovery_requests: recoveryOk, recovery_validation: recoveryOk, recovery_authorization: recoveryOk, multi_step_recovery: recoveryOk, emergency_recovery: recoveryOk, operator_approval: recoveryOk, governance_approval: recoveryOk, cryptographic_verification: recoveryOk, evidence_recorded: recoveryOk });
  const suspension = nested({ ledger_id: suspensionOk ? "ledger:w1.1b:suspension" : "", user_suspension: suspensionOk, service_suspension: suspensionOk, tenant_suspension: suspensionOk, namespace_suspension: suspensionOk, temporary_lock: suspensionOk, permanent_disable: suspensionOk, restoration: suspensionOk, suspension_history: suspensionOk });
  const delegation = nested({ registry_id: delegationOk ? "registry:w1.1b:delegation" : "", delegation_policies: delegationOk, delegation_tokens: delegationOk, scope_restrictions: delegationOk, time_limits: delegationOk, delegation_chains: delegationOk, revocation: delegationOk, evidence_recorded: delegationOk });
  const federation = nested({ registry_id: federationOk ? "registry:w1.1b:federation" : "", federation_gateway: federationOk, trust_relationships: federationOk, external_identity_mapping: federationOk, identity_translation: federationOk, federation_policies: federationOk, federation_audit: federationOk, protocols: federationOk ? freezeArray(["SAML", "OAuth", "OpenID Connect", "External PKI"]) : freezeArray<string>([]) });
  const evidence = nested({ ledger_id: evidenceOk ? "ledger:w1.1b:identity-evidence" : "", records: evidenceOk ? freezeArray(["evidence:authentication", "evidence:authorization", "evidence:recovery", "evidence:suspension", "evidence:delegation", "evidence:federation", "evidence:credential", "evidence:session"]) : freezeArray<string>([]), authentication: evidenceOk, authorization: evidenceOk, recovery: evidenceOk, suspension: evidenceOk, delegation: evidenceOk, federation: evidenceOk, credential_events: evidenceOk, session_events: evidenceOk, immutable: evidenceOk, signed: evidenceOk, timestamped: evidenceOk, replayable: evidenceOk, searchable: evidenceOk });
  const qualification = nested({ report_id: qualificationOk ? "report:w1.1b:identity-qualification" : "", functional: qualificationOk && sessionsOk && credentialsOk && recoveryOk && suspensionOk && delegationOk && federationOk, security: qualificationOk && credentialsOk && delegationOk && evidenceOk, operational: qualificationOk && entryOk, governance: qualificationOk && evidenceOk, certification_package: qualificationOk ? "package:w1.1b:identity-certification" : "", readiness_assessment: qualificationOk ? "assessment:w1.1b:identity-readiness" : "", qualification_evidence: qualificationOk ? freezeArray([evidence.ledger_id, sessions.service_id, credentials.registry_id]) : freezeArray<string>([]), infrastructure_gate_passed: qualificationOk && entryOk && evidenceOk });
  const readiness = nested({ readiness_id: "W1.1B-IDENTITY-FULL-READINESS-001", decision, phase_ready: decision === "IDENTITY_INFRASTRUCTURE_READY" || decision === "READY_WITH_OBSERVATIONS", entry_criteria_ready: entryOk, sessions_ready: sessionsOk, credentials_ready: credentialsOk, recovery_ready: recoveryOk, suspension_ready: suspensionOk, delegation_ready: delegationOk, federation_ready: federationOk, evidence_ready: evidenceOk, qualification_ready: qualification.infrastructure_gate_passed, failures });
  const base: Omit<IdentityFullResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, identity_core_ref: "identity-core/w1.1a", sessions, credentials, recovery, suspension, delegation, federation, evidence, qualification, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateIdentityFull(result?: IdentityFullResult): IdentityFullValidation {
  if (!result) return nested({ valid: false, decision: "NOT_READY" as const, replay_hash_valid: false, integrity_hash_valid: false, sessions_valid: false, credentials_valid: false, recovery_valid: false, suspension_valid: false, delegation_valid: false, federation_valid: false, evidence_valid: false, qualification_valid: false, readiness_valid: false, failures: freezeArray(["SESSION_MANAGEMENT_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const sessions_valid = verifyHashed(result.sessions) && result.sessions.session_registry.length >= 3 && result.sessions.deterministic_expiration && result.sessions.revocation && result.sessions.tenant_isolation;
  const credentials_valid = verifyHashed(result.credentials) && result.credentials.credential_types.length === 5 && result.credentials.rotation && result.credentials.revocation && result.credentials.mfa_enrollment;
  const recovery_valid = verifyHashed(result.recovery) && result.recovery.recovery_authorization && result.recovery.governance_approval && result.recovery.cryptographic_verification;
  const suspension_valid = verifyHashed(result.suspension) && result.suspension.user_suspension && result.suspension.tenant_suspension && result.suspension.restoration && result.suspension.suspension_history;
  const delegation_valid = verifyHashed(result.delegation) && result.delegation.scope_restrictions && result.delegation.time_limits && result.delegation.revocation && result.delegation.delegation_chains;
  const federation_valid = verifyHashed(result.federation) && result.federation.protocols.length === 4 && result.federation.trust_relationships && result.federation.federation_policies;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.records.length >= 8 && result.evidence.immutable && result.evidence.signed && result.evidence.replayable && result.evidence.searchable;
  const qualification_valid = verifyHashed(result.qualification) && result.qualification.functional && result.qualification.security && result.qualification.operational && result.qualification.governance && result.qualification.infrastructure_gate_passed;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && sessions_valid && credentials_valid && recovery_valid && suspension_valid && delegation_valid && federation_valid && evidence_valid && qualification_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, sessions_valid, credentials_valid, recovery_valid, suspension_valid, delegation_valid, federation_valid, evidence_valid, qualification_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayIdentityFull(result = runIdentityFull()): boolean { const scenario = result.readiness.decision === "READY_WITH_OBSERVATIONS" ? { scenario: "READY_WITH_OBSERVATIONS" as const } : {}; const replayed = runIdentityFull(scenario); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateIdentityFull(result).valid; }
export function getIdentityFullBundle(): IdentityFullBundle { const result = runIdentityFull(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_session_management: true, owns_credential_lifecycle: true, owns_identity_recovery: true, owns_identity_suspension: true, owns_delegated_authorization: true, owns_federation_interfaces: true, owns_identity_evidence: true, owns_identity_qualification: true }), result, validation: validateIdentityFull(result) }); }
export const IdentityFullService = Object.freeze({ run: runIdentityFull, validate: validateIdentityFull, replay: replayIdentityFull });
