export const REGISTRY_TRUST_ERROR_CODES = {
  REGISTRY_SIGNATURE_MISSING: "REGISTRY_SIGNATURE_MISSING",
  REGISTRY_SIGNATURE_INVALID: "REGISTRY_SIGNATURE_INVALID",
  REGISTRY_SIGNATURE_HASH_MISMATCH: "REGISTRY_SIGNATURE_HASH_MISMATCH",
  REGISTRY_SIGNER_UNKNOWN: "REGISTRY_SIGNER_UNKNOWN",
  REGISTRY_SIGNER_REVOKED: "REGISTRY_SIGNER_REVOKED",
  REGISTRY_SIGNING_KEY_UNKNOWN: "REGISTRY_SIGNING_KEY_UNKNOWN",
  REGISTRY_SIGNING_AUTHORITY_INVALID: "REGISTRY_SIGNING_AUTHORITY_INVALID",
  REGISTRY_PROVENANCE_MISSING: "REGISTRY_PROVENANCE_MISSING",
  REGISTRY_PROVENANCE_INVALID: "REGISTRY_PROVENANCE_INVALID",
  REGISTRY_PROVENANCE_HASH_MISMATCH: "REGISTRY_PROVENANCE_HASH_MISMATCH",
  REGISTRY_PROMOTION_STAGE_INVALID: "REGISTRY_PROMOTION_STAGE_INVALID",
  REGISTRY_PROMOTION_PATH_INVALID: "REGISTRY_PROMOTION_PATH_INVALID",
  REGISTRY_APPROVAL_CHAIN_MISSING: "REGISTRY_APPROVAL_CHAIN_MISSING",
  REGISTRY_GOVERNANCE_SNAPSHOT_MISSING: "REGISTRY_GOVERNANCE_SNAPSHOT_MISSING",
  REGISTRY_TRUST_FAILURE: "REGISTRY_TRUST_FAILURE",
  EXECUTION_BLOCKED_UNTRUSTED_REGISTRY: "EXECUTION_BLOCKED_UNTRUSTED_REGISTRY",
} as const;

export type RegistryTrustErrorCode =
  typeof REGISTRY_TRUST_ERROR_CODES[keyof typeof REGISTRY_TRUST_ERROR_CODES];

export type RegistrySnapshotSignature = Readonly<{
  snapshotId: string;
  registrySnapshotHash: string;
  signature: string;
  signedBy: string;
  signingKeyId: string;
  signedAt: string;
}>;

export type RegistrySignatureVerificationFailure = Readonly<{
  code: RegistryTrustErrorCode;
  message: string;
  path?: string;
  expected?: unknown;
  actual?: unknown;
}>;

export type RegistrySignatureVerificationResult = Readonly<{
  ok: boolean;
  snapshotId?: string;
  registrySnapshotHash?: string;
  failures: readonly RegistrySignatureVerificationFailure[];
}>;

