import { runApex, validateApex } from "@/services/apex";
import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runWaveFiveAurora, validateWaveFiveAurora } from "@/services/wave-five-aurora";
import type { WaveFiveApexBundle, WaveFiveApexDecision, WaveFiveApexFailure, WaveFiveApexInput, WaveFiveApexResult, WaveFiveApexScenario, WaveFiveApexValidation } from "@/types/wave-five-apex";

const VERSION = "wave-five-apex/w5.13" as const;
const IDENTIFIER = "WaveFiveApex" as const;
const UPSTREAM_REFS = Object.freeze(["apex/v4.16", "wave-five-aurora/w5.12", "wave-five-learning-stevn/w5.11", "wave-five-writing-publisher-os/w5.10", "wave-five-research/w5.9", "wave-five-health/w5.8", "wave-five-finance/w5.7", "wave-five-tasks-commitments/w5.5", "wave-five-calendar-time/w5.4", "wave-five-personal-knowledge/w5.3", "wave-five-unified-personal-context/w5.2"]);
const PROVIDES = Object.freeze(["performance-dashboard", "habit-analytics", "personal-reviews", "experiment-registry", "outcome-intelligence", "goal-intelligence", "pattern-discovery", "optimization-recommendations"]);
let apex = runApex();
let aurora = runWaveFiveAurora();

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly WaveFiveApexFailure[], failure: WaveFiveApexFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: WaveFiveApexScenario): WaveFiveApexFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly WaveFiveApexFailure[], scenario?: WaveFiveApexScenario): WaveFiveApexDecision {
  const notQualified = new Set<WaveFiveApexFailure>(["APEX_APPLICATION_INVALID", "W5_AURORA_INVALID", "TREND_DETECTION_NONDETERMINISTIC", "PERFORMANCE_HISTORY_MUTABLE", "HABIT_CORRELATION_NONDETERMINISTIC", "REVIEW_GENERATION_NONDETERMINISTIC", "EXPERIMENT_LIFECYCLE_INVALID", "EXPERIMENT_REPLAY_UNSUPPORTED", "OUTCOME_ATTRIBUTION_INVALID", "OUTCOME_RECOMMENDATIONS_NOT_EXPLAINABLE", "RECOMMENDATIONS_NOT_ADVISORY", "AUTONOMOUS_BEHAVIORAL_CHANGE_EXECUTED", "HUMAN_APPROVAL_BYPASSED", "COMPLETION_FORECASTING_NONDETERMINISTIC", "CORRELATIONS_NONREPRODUCIBLE", "PRIVACY_BOUNDARY_BREACH", "TENANT_ISOLATION_BREACH", "EVIDENCE_LINEAGE_INCOMPLETE", "CALCULATION_METHOD_MISSING", "APEX_EVIDENCE_MUTABLE", "APEX_REPLAY_DIVERGED", "POLICY_COMPLIANCE_BYPASSED", "DATA_OWNERSHIP_INVALID"]);
  if (failures.some((failure) => notQualified.has(failure))) return "NOT_QUALIFIED";
  if (has(failures, "APEX_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_QUALIFIED";
  return "QUALIFIED";
}
function resultReplayHash(result: Omit<WaveFiveApexResult, "replay_hash" | "integrity_hash">): string { return hash({ performance: result.performance_measurement.integrity_hash, dashboard: result.dashboard_habits.integrity_hash, reviews: result.reviews_experiments.integrity_hash, outcome: result.outcome_intelligence.integrity_hash, goal: result.goal_patterns_correlation.integrity_hash, evidence: result.evidence_governance.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<WaveFiveApexResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runWaveFiveApex(input: WaveFiveApexInput = {}): WaveFiveApexResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  apex = runApex();
  aurora = runWaveFiveAurora();
  const failures = freezeArray([...new Set([...(direct ? [direct] : []), ...(!validateApex(apex).valid ? ["APEX_APPLICATION_INVALID" as const] : []), ...(!validateWaveFiveAurora(aurora).valid ? ["W5_AURORA_INVALID" as const] : [])])]);
  const performanceOk = !has(failures, "PERFORMANCE_MEASUREMENT_MISSING") && !has(failures, "PERFORMANCE_METRICS_INVALID") && !has(failures, "BASELINES_MISSING") && !has(failures, "TREND_DETECTION_NONDETERMINISTIC") && !has(failures, "PERFORMANCE_HISTORY_MUTABLE");
  const dashboardHabitsOk = !has(failures, "PERFORMANCE_DASHBOARD_MISSING") && !has(failures, "DASHBOARD_EVIDENCE_MISSING") && !has(failures, "DASHBOARD_DRILLDOWN_MISSING") && !has(failures, "HISTORICAL_COMPARISONS_INVALID") && !has(failures, "HABIT_ANALYTICS_MISSING") && !has(failures, "HABIT_TRACKING_INVALID") && !has(failures, "HABIT_CORRELATION_NONDETERMINISTIC") && !has(failures, "PATTERN_DETECTION_INVALID");
  const reviewsExperimentsOk = !has(failures, "PERSONAL_REVIEWS_MISSING") && !has(failures, "REVIEW_CADENCE_INCOMPLETE") && !has(failures, "REVIEW_EVIDENCE_MISSING") && !has(failures, "REVIEW_GENERATION_NONDETERMINISTIC") && !has(failures, "EXPERIMENT_REGISTRY_MISSING") && !has(failures, "EXPERIMENT_LIFECYCLE_INVALID") && !has(failures, "EXPERIMENT_EVIDENCE_MISSING") && !has(failures, "EXPERIMENT_REPLAY_UNSUPPORTED");
  const outcomeOk = !has(failures, "OUTCOME_INTELLIGENCE_MISSING") && !has(failures, "OUTCOME_ATTRIBUTION_INVALID") && !has(failures, "OUTCOME_RECOMMENDATIONS_NOT_EXPLAINABLE") && !has(failures, "LONGITUDINAL_ANALYSIS_INVALID") && !has(failures, "RECOMMENDATION_ENGINE_MISSING") && !has(failures, "RECOMMENDATIONS_NOT_ADVISORY") && !has(failures, "AUTONOMOUS_BEHAVIORAL_CHANGE_EXECUTED") && !has(failures, "HUMAN_APPROVAL_BYPASSED") && !has(failures, "RECOMMENDATION_EVIDENCE_MISSING") && !has(failures, "CONFIDENCE_SCORES_MISSING");
  const goalOk = !has(failures, "GOAL_OPTIMIZATION_MISSING") && !has(failures, "BOTTLENECK_DETECTION_INVALID") && !has(failures, "COMPLETION_FORECASTING_NONDETERMINISTIC") && !has(failures, "CROSS_DOMAIN_CORRELATION_MISSING") && !has(failures, "CORRELATIONS_NONREPRODUCIBLE") && !has(failures, "PRIVACY_BOUNDARY_BREACH") && !has(failures, "TENANT_ISOLATION_BREACH");
  const evidenceOk = !has(failures, "EVIDENCE_INTEGRATION_MISSING") && !has(failures, "EVIDENCE_LINEAGE_INCOMPLETE") && !has(failures, "CALCULATION_METHOD_MISSING") && !has(failures, "APEX_EVIDENCE_MUTABLE") && !has(failures, "AUDIT_TRAIL_MISSING") && !has(failures, "APEX_REPLAY_DIVERGED") && !has(failures, "GOVERNANCE_VALIDATION_MISSING") && !has(failures, "POLICY_COMPLIANCE_BYPASSED") && !has(failures, "CATA_TRUST_EVALUATION_MISSING") && !has(failures, "DATA_OWNERSHIP_INVALID");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "QUALIFIED";
  const performance_measurement = nested({ measurement_id: performanceOk ? "W5.13-PERFORMANCE-MEASUREMENT-001" : "", performance_areas: performanceOk, performance_metrics: performanceOk, kpi_definitions: performanceOk, baseline_measurements: performanceOk, trend_detection: performanceOk, progress_evaluation: performanceOk, performance_history: performanceOk, consistent_measurement: performanceOk, deterministic_calculations: performanceOk, immutable_history: performanceOk });
  const dashboard_habits = nested({ dashboard_habits_id: dashboardHabitsOk ? "W5.13-DASHBOARD-HABITS-001" : "", daily_overview: dashboardHabitsOk, weekly_summary: dashboardHabitsOk, monthly_performance: dashboardHabitsOk, goal_progress: dashboardHabitsOk, productivity_trends: dashboardHabitsOk, wellness_indicators: dashboardHabitsOk, learning_progress: dashboardHabitsOk, financial_progress: dashboardHabitsOk, mission_progress: dashboardHabitsOk, configurable_widgets: dashboardHabitsOk, drill_down_analysis: dashboardHabitsOk, historical_comparisons: dashboardHabitsOk, evidence_navigation: dashboardHabitsOk, habit_registry: dashboardHabitsOk, habit_tracking: dashboardHabitsOk, completion_rates: dashboardHabitsOk, consistency_analysis: dashboardHabitsOk, habit_strength: dashboardHabitsOk, streak_analysis: dashboardHabitsOk, habit_correlation: dashboardHabitsOk, positive_habit_detection: dashboardHabitsOk, negative_pattern_detection: dashboardHabitsOk, long_term_consistency: dashboardHabitsOk, seasonality: dashboardHabitsOk, improvement_scoring: dashboardHabitsOk, deterministic_analytics: dashboardHabitsOk });
  const reviews_experiments = nested({ reviews_experiments_id: reviewsExperimentsOk ? "W5.13-REVIEWS-EXPERIMENTS-001" : "", daily_review: reviewsExperimentsOk, weekly_review: reviewsExperimentsOk, monthly_review: reviewsExperimentsOk, quarterly_review: reviewsExperimentsOk, annual_review: reviewsExperimentsOk, mission_review: reviewsExperimentsOk, achievements: reviewsExperimentsOk, completed_commitments: reviewsExperimentsOk, unfinished_work: reviewsExperimentsOk, lessons_learned: reviewsExperimentsOk, emerging_patterns: reviewsExperimentsOk, opportunity_identification: reviewsExperimentsOk, recommended_improvements: reviewsExperimentsOk, experiment_registry: reviewsExperimentsOk, hypotheses: reviewsExperimentsOk, objectives: reviewsExperimentsOk, durations: reviewsExperimentsOk, measurements: reviewsExperimentsOk, success_criteria: reviewsExperimentsOk, experiment_evidence: reviewsExperimentsOk, outcomes: reviewsExperimentsOk, experiment_lessons: reviewsExperimentsOk, templates: reviewsExperimentsOk, lifecycle_management: reviewsExperimentsOk, comparison_reports: reviewsExperimentsOk, experiment_history: reviewsExperimentsOk, replay_support: reviewsExperimentsOk });
  const outcome_intelligence = nested({ outcome_id: outcomeOk ? "W5.13-OUTCOME-INTELLIGENCE-001" : "", outcome_evaluation: outcomeOk, success_attribution: outcomeOk, pattern_discovery: outcomeOk, improvement_identification: outcomeOk, longitudinal_analysis: outcomeOk, opportunity_ranking: outcomeOk, recommendation_generation: outcomeOk, productivity_recommendations: outcomeOk, focus_recommendations: outcomeOk, health_recommendations: outcomeOk, learning_recommendations: outcomeOk, finance_recommendations: outcomeOk, writing_recommendations: outcomeOk, project_recommendations: outcomeOk, habit_recommendations: outcomeOk, mission_recommendations: outcomeOk, evidence_backed: outcomeOk, explainable: outcomeOk, confidence_scored: outcomeOk, non_autonomous: outcomeOk, advisory_only: outcomeOk });
  const goal_patterns_correlation = nested({ goal_patterns_correlation_id: goalOk ? "W5.13-GOAL-PATTERNS-CORRELATION-001" : "", goal_progress_analysis: goalOk, bottleneck_detection: goalOk, momentum_analysis: goalOk, completion_forecasting: goalOk, improvement_suggestions: goalOk, productivity_peaks: goalOk, burnout_indicators: goalOk, successful_routines: goalOk, ineffective_habits: goalOk, mission_acceleration_periods: goalOk, optimal_work_windows: goalOk, supporting_evidence: goalOk, confidence: goalOk, explanation: goalOk, historical_validation: goalOk, health_productivity: goalOk, learning_mission_success: goalOk, writing_knowledge_growth: goalOk, finance_goal_progress: goalOk, calendar_stress: goalOk, habits_performance: goalOk, projects_outcomes: goalOk, mission_overall_improvement: goalOk, correlations_reproducible: goalOk, privacy_preserving: goalOk });
  const evidence_governance = nested({ evidence_governance_id: evidenceOk ? "W5.13-EVIDENCE-GOVERNANCE-001" : "", evidence_sources: evidenceOk, confidence_records: evidenceOk, lineage: evidenceOk, timestamps: evidenceOk, calculation_methods: evidenceOk, supporting_records: evidenceOk, audit_trail: evidenceOk, immutable_evidence: evidenceOk, replay_compatible: evidenceOk, recommendation_admissibility: evidenceOk, privacy: evidenceOk, policy_compliance: evidenceOk, data_ownership: evidenceOk, explainability: evidenceOk, evidence_integrity: evidenceOk, cata_trust_evaluation: evidenceOk, constitutional_governance: evidenceOk, human_decision_authority: evidenceOk });
  const readiness = nested({ readiness_id: "W5.13-APEX-READINESS-001", decision, phase_ready: qualified, apex_application_ready: !has(failures, "APEX_APPLICATION_INVALID"), aurora_ready: !has(failures, "W5_AURORA_INVALID"), performance_measured_consistently: performanceOk, dashboard_evidence_backed: dashboardHabitsOk, habit_analytics_deterministic: dashboardHabitsOk, reviews_generated_for_all_cycles: reviewsExperimentsOk, experiment_registry_replayable: reviewsExperimentsOk, outcome_intelligence_explainable: outcomeOk, correlations_reproducible_privacy_preserving: goalOk, recommendations_advisory_only: outcomeOk, governance_and_cata_enforced: evidenceOk, evidence_lineage_immutable: evidenceOk, replay_auditable: evidenceOk, failures });
  const base: Omit<WaveFiveApexResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, apex_application_ref: "apex/v4.16", upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id: input.tenant_id ?? apex.foundation.tenant_id, principal_id: input.principal_id ?? "principal:w5.13:optimizer", performance_measurement, dashboard_habits, reviews_experiments, outcome_intelligence, goal_patterns_correlation, evidence_governance, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateWaveFiveApex(result?: WaveFiveApexResult): WaveFiveApexValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, performance_measurement_valid: false, dashboard_habits_valid: false, reviews_experiments_valid: false, outcome_intelligence_valid: false, goal_patterns_correlation_valid: false, evidence_governance_valid: false, readiness_valid: false, failures: freezeArray(["PERFORMANCE_MEASUREMENT_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const performance_measurement_valid = verifyHashed(result.performance_measurement) && result.performance_measurement.consistent_measurement && result.performance_measurement.deterministic_calculations && result.performance_measurement.immutable_history;
  const dashboard_habits_valid = verifyHashed(result.dashboard_habits) && result.dashboard_habits.evidence_navigation && result.dashboard_habits.habit_correlation && result.dashboard_habits.deterministic_analytics;
  const reviews_experiments_valid = verifyHashed(result.reviews_experiments) && result.reviews_experiments.daily_review && result.reviews_experiments.annual_review && result.reviews_experiments.experiment_registry && result.reviews_experiments.lifecycle_management && result.reviews_experiments.replay_support;
  const outcome_intelligence_valid = verifyHashed(result.outcome_intelligence) && result.outcome_intelligence.outcome_evaluation && result.outcome_intelligence.explainable && result.outcome_intelligence.confidence_scored && result.outcome_intelligence.non_autonomous && result.outcome_intelligence.advisory_only;
  const goal_patterns_correlation_valid = verifyHashed(result.goal_patterns_correlation) && result.goal_patterns_correlation.completion_forecasting && result.goal_patterns_correlation.supporting_evidence && result.goal_patterns_correlation.correlations_reproducible && result.goal_patterns_correlation.privacy_preserving;
  const evidence_governance_valid = verifyHashed(result.evidence_governance) && result.evidence_governance.lineage && result.evidence_governance.calculation_methods && result.evidence_governance.immutable_evidence && result.evidence_governance.replay_compatible && result.evidence_governance.cata_trust_evaluation && result.evidence_governance.human_decision_authority;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.apex_application_ready && result.readiness.aurora_ready && result.readiness.recommendations_advisory_only && result.readiness.governance_and_cata_enforced && result.readiness.evidence_lineage_immutable && result.readiness.replay_auditable && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && performance_measurement_valid && dashboard_habits_valid && reviews_experiments_valid && outcome_intelligence_valid && goal_patterns_correlation_valid && evidence_governance_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, performance_measurement_valid, dashboard_habits_valid, reviews_experiments_valid, outcome_intelligence_valid, goal_patterns_correlation_valid, evidence_governance_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayWaveFiveApex(result = runWaveFiveApex()): boolean { const replayed = runWaveFiveApex(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateWaveFiveApex(result).valid; }
export function getWaveFiveApexBundle(): WaveFiveApexBundle { const result = runWaveFiveApex(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, advisory_only_recommendations: true, human_decision_authority_required: true, deterministic_calculations_required: true, evidence_backed_insights_required: true, privacy_first_required: true, autonomous_behavioral_change_prohibited: true, immutable_outcome_history_required: true, replay_required: true, qualification_gate: "W5.13 APEX Personal Performance Qualification Gate" }), result, validation: validateWaveFiveApex(result) }); }
export const WaveFiveApexService = Object.freeze({ run: runWaveFiveApex, validate: validateWaveFiveApex, replay: replayWaveFiveApex });
