import { randomUUID } from "node:crypto";
import { z } from "zod";
import { getSessionUser } from "@/src/lib/auth";
import { AppError } from "@/src/server/api/errors";
import { apiError, apiSuccess } from "@/src/server/api/response";
import { requireWorkspaceManager } from "@/src/server/auth/permissions";
import { ObjectiveProfileService, PrismaLearningAuditLedger, PrismaStrategyRegistryRepository, StrategySelectionRecordService } from "@/services/learning-constitution";
export const dynamic = "force-dynamic";
const type = z.enum(["FACTUAL", "CONCEPTUAL", "PROCEDURAL", "DIAGNOSTIC", "DECISION_JUDGMENT", "PRINCIPLE", "DISCRIMINATION", "PROBLEM_SOLVING", "CREATIVE", "METACOGNITIVE"]);
const intake = z.object({ objectiveId: z.string().min(1).max(200), domain: z.string().min(1).max(120), primaryType: type.nullable(), typeConfidence: z.number().min(0).max(1), secondaryTypes: z.array(type).max(9), currentMastery: z.enum(["NOVICE", "DEVELOPING", "COMPETENT", "ADVANCED", "MASTERED"]), targetMastery: z.enum(["NOVICE", "DEVELOPING", "COMPETENT", "ADVANCED", "MASTERED"]), risk: z.enum(["LOW", "MEDIUM", "HIGH", "SECURITY_CRITICAL"]), transferRequirement: z.enum(["LOW", "MEDIUM", "HIGH"]), retentionRequirement: z.enum(["LOW", "MEDIUM", "HIGH"]), prerequisites: z.array(z.string().min(1).max(160)).max(100).default([]), knowledgeGapIds: z.array(z.string().min(1).max(160)).max(100).default([]), constraints: z.array(z.string().min(1).max(160)).max(100).default([]), classifierVersion: z.string().min(1).max(120).default("objective-intake@1") });
/** Protected read-only strategy-decision inspection; no plan, lease, strategy mutation, or execution endpoint exists here. */
export async function GET() { try { const user = await getSessionUser(); if (!user) throw new AppError(401, "unauthorized", "Authentication required."); if (!user.workspaceId || user.workspaceId === "default") throw new AppError(403, "workspace_required", "Workspace membership is required."); await requireWorkspaceManager({ userId: user.id, userRole: user.role, workspaceId: user.workspaceId }); const artifacts = await new PrismaStrategyRegistryRepository(user.workspaceId).listWorkspaceArtifacts(); return apiSuccess({ decisions: artifacts.filter((item) => item.artifactType === "SELECTION_DECISION"), rankings: artifacts.filter((item) => item.artifactType === "RANKING"), objectiveProfiles: artifacts.filter((item) => item.artifactType === "OBJECTIVE_PROFILE"), phase40Selections: artifacts.filter((item) => item.artifactType === "PHASE40_SELECTION"), overrides: artifacts.filter((item) => item.artifactType === "SELECTION_OVERRIDE"), reselections: artifacts.filter((item) => item.artifactType === "STRATEGY_RESELECTION") }); } catch (error) { return apiError(error, "Unable to load strategy selection artifacts."); } }

/** Creates only an immutable objective-profile input. Selecting, planning, and execution remain separate governed operations. */
export async function POST(request: Request) { try { const user = await getSessionUser(); if (!user) throw new AppError(401, "unauthorized", "Authentication required."); if (!user.workspaceId || user.workspaceId === "default") throw new AppError(403, "workspace_required", "Workspace membership is required."); await requireWorkspaceManager({ userId: user.id, userRole: user.role, workspaceId: user.workspaceId }); const body = intake.parse(await request.json()); const createdAt = new Date().toISOString(); const profile = new ObjectiveProfileService().analyze({ profileId: `LOP-${randomUUID()}`, ...body, createdAt }); const actor = { actorId: `human:${user.id}`, actorType: "HUMAN" as const }; await new StrategySelectionRecordService(new PrismaStrategyRegistryRepository(user.workspaceId), new PrismaLearningAuditLedger(user.workspaceId)).profile(profile, user.workspaceId, actor, `objective-profile:${profile.profileId}`); return apiSuccess({ profile, next: "Profile recorded. A separate governed selection command must retrieve strategies and Phase 39 evidence before it can recommend a plan." }, { status: 201 }); } catch (error) { return apiError(error, "Unable to create learning objective profile."); } }
