export const TIMELINE_ERRORS = {
  BLOCKED_UNSAFE_RECOVERY_TIMELINE: "BLOCKED_UNSAFE_RECOVERY_TIMELINE",
} as const;

export const TIMELINE_WARNINGS = {
  MISSING_EXECUTION: "MISSING_EXECUTION",
  MISSING_LEDGER: "MISSING_LEDGER",
  MISSING_CRITICAL_TRANSITIONS: "MISSING_CRITICAL_TRANSITIONS",
  TIMELINE_STATE_MISMATCH: "TIMELINE_STATE_MISMATCH",
} as const;
