import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runAgentRegistry, validateAgentRegistry } from "@/services/agent-registry";
import { runCafConstitutionalFoundation, validateCafConstitutionalFoundation } from "@/services/caf-constitutional-foundation";
import type { AgentLifecycleState, LifecycleEngineBundle, LifecycleEngineDecision, LifecycleEngineFailure, LifecycleEngineInput, LifecycleEngineResult, LifecycleEngineScenario, LifecycleEngineValidation, RuntimeLifecycleState, TransitionOutcome } from "@/types/lifecycle-engine";

const VERSION = "lifecycle-engine/w2.2" as const;
const IDENTIFIER = "LifecycleEngine" as const;
const AGENT_STATES = Object.freeze<AgentLifecycleState[]>(["REGISTERED", "VALIDATING", "INACTIVE", "ACTIVE", "SUSPENDED", "RECOVERING", "RESTRICTED", "RETIRING", "RETIRED", "REVOKED"]);
const RUNTIME_STATES = Object.freeze<RuntimeLifecycleState[]>(["REQUESTED", "PROVISIONING", "INITIALIZING", "READY", "RUNNING", "DEGRADED", "QUIESCING", "SUSPENDING", "SUSPENDED", "RECOVERING", "STOPPING", "STOPPED", "FAILED", "QUARANTINED", "TERMINATED", "REVOKED"]);
const OUTCOMES = Object.freeze<TransitionOutcome[]>(["APPROVED", "APPROVED_WITH_RESTRICTIONS", "DENIED", "ESCALATION_REQUIRED", "STALE_REQUEST", "CONFLICT", "FAIL_CLOSED"]);
let constitutionBaseline: ReturnType<typeof runCafConstitutionalFoundation> | undefined;
let agentRegistryBaseline: ReturnType<typeof runAgentRegistry> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly LifecycleEngineFailure[], failure: LifecycleEngineFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: LifecycleEngineScenario): LifecycleEngineFailure | undefined { return scenario === "BASELINE" || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly LifecycleEngineFailure[], scenario: LifecycleEngineScenario): LifecycleEngineDecision {
  if (has(failures, "W2_0_CAF_CONSTITUTION_INVALID") || has(failures, "W2_1_AGENT_REGISTRY_INVALID") || has(failures, "RUNTIME_NOT_AUTHORITATIVE") || has(failures, "EXECUTION_OUTSIDE_PERMITTED_STATE") || has(failures, "INVALID_TRANSITIONS_ALLOWED") || has(failures, "TERMINAL_STATE_EXIT_ALLOWED") || has(failures, "CONCURRENCY_CONTROL_FAILED") || has(failures, "SUSPENSION_PROPAGATION_FAILED") || has(failures, "REVOCATION_PROPAGATION_FAILED") || has(failures, "RETIREMENT_ACTIVE_RUNTIME_ALLOWED") || has(failures, "MISSING_PREREQUISITES_NOT_FAIL_CLOSED") || has(failures, "STALE_REQUEST_MUTATED_STATE") || has(failures, "HEALTH_AUTHORIZES_EXECUTION") || has(failures, "RECOVERY_BYPASSES_REVOCATION") || has(failures, "SUSPENSION_UNAUTHORIZED_CONTINUATION") || has(failures, "LIFECYCLE_HISTORY_NOT_IMMUTABLE") || has(failures, "LIFECYCLE_REPLAY_DIVERGENCE") || has(failures, "TENANT_ISOLATION_FAILED") || has(failures, "ORCHESTRATOR_INTEGRATION_INVALID") || has(failures, "REGISTRY_PROJECTION_AUTHORITATIVE")) return "FAIL_CLOSED";
  if (has(failures, "LIFECYCLE_QUALIFICATION_GATE_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP" || scenario === "QUALIFIED_WITH_OBSERVATIONS") return "CONDITIONALLY_QUALIFIED";
  return "W2_2_LIFECYCLE_ENGINE_QUALIFIED";
}
function resultReplayHash(result: Omit<LifecycleEngineResult, "replay_hash" | "integrity_hash">): string { return hash({ domain: result.domain_model.integrity_hash, runtime: result.runtime_state_machine.integrity_hash, agent: result.agent_lifecycle.integrity_hash, coupling: result.coupling.integrity_hash, transition: result.transition_validation.integrity_hash, health: result.health_service.integrity_hash, managers: result.recovery_suspension_retirement_revocation.integrity_hash, history: result.history_replay.integrity_hash, apis: result.apis_observability.integrity_hash, evidence: result.evidence.integrity_hash, qualification: result.qualification.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<LifecycleEngineResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runLifecycleEngine(input: LifecycleEngineInput = {}): LifecycleEngineResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<LifecycleEngineFailure>(direct ? [direct] : []);
  constitutionBaseline ??= runCafConstitutionalFoundation();
  agentRegistryBaseline ??= runAgentRegistry();
  const constitutionInvalid = !validateCafConstitutionalFoundation(constitutionBaseline).valid || has(scenarioFailures, "W2_0_CAF_CONSTITUTION_INVALID");
  const agentRegistryInvalid = !validateAgentRegistry(agentRegistryBaseline).valid || has(scenarioFailures, "W2_1_AGENT_REGISTRY_INVALID");
  const failures = freezeArray([...new Set([...scenarioFailures, ...(constitutionInvalid ? ["W2_0_CAF_CONSTITUTION_INVALID" as const] : []), ...(agentRegistryInvalid ? ["W2_1_AGENT_REGISTRY_INVALID" as const] : [])])]);
  const domainOk = !has(failures, "LIFECYCLE_DOMAIN_MODEL_MISSING") && !has(failures, "STATE_VERSIONING_MISSING") && !has(failures, "IDEMPOTENCY_MISSING");
  const runtimeOk = !has(failures, "RUNTIME_STATE_MACHINE_MISSING") && !has(failures, "RUNTIME_NOT_AUTHORITATIVE") && !has(failures, "EXECUTION_OUTSIDE_PERMITTED_STATE") && !has(failures, "INVALID_TRANSITIONS_ALLOWED") && !has(failures, "TERMINAL_STATE_EXIT_ALLOWED");
  const agentOk = !has(failures, "AGENT_STATE_MACHINE_MISSING");
  const couplingOk = !has(failures, "LIFECYCLE_COUPLING_MISSING") && !has(failures, "SUSPENSION_PROPAGATION_FAILED") && !has(failures, "REVOCATION_PROPAGATION_FAILED") && !has(failures, "RETIREMENT_ACTIVE_RUNTIME_ALLOWED");
  const transitionOk = !has(failures, "TRANSITION_VALIDATION_MISSING") && !has(failures, "MISSING_PREREQUISITES_NOT_FAIL_CLOSED") && !has(failures, "STALE_REQUEST_MUTATED_STATE") && !has(failures, "CONCURRENCY_CONTROL_FAILED");
  const healthOk = !has(failures, "HEALTH_SERVICE_MISSING") && !has(failures, "HEALTH_AUTHORIZES_EXECUTION") && !has(failures, "STALE_HEALTH_NOT_DETECTED");
  const managersOk = !has(failures, "RECOVERY_MANAGER_MISSING") && !has(failures, "RECOVERY_BYPASSES_REVOCATION") && !has(failures, "RECOVERY_UNBOUNDED") && !has(failures, "SUSPENSION_MANAGER_MISSING") && !has(failures, "SUSPENSION_UNAUTHORIZED_CONTINUATION") && !has(failures, "RETIREMENT_MANAGER_MISSING") && !has(failures, "REVOCATION_ENFORCEMENT_MISSING");
  const historyOk = !has(failures, "LIFECYCLE_HISTORY_MISSING") && !has(failures, "LIFECYCLE_HISTORY_NOT_IMMUTABLE") && !has(failures, "LIFECYCLE_REPLAY_DIVERGENCE");
  const apiOk = !has(failures, "ORCHESTRATOR_INTEGRATION_INVALID") && !has(failures, "REGISTRY_PROJECTION_AUTHORITATIVE") && !has(failures, "OBSERVABILITY_MISSING");
  const evidenceOk = !has(failures, "LIFECYCLE_EVIDENCE_MISSING") && !has(failures, "LIFECYCLE_HISTORY_NOT_IMMUTABLE");
  const tenantOk = !has(failures, "TENANT_ISOLATION_FAILED");
  const gateOk = !has(failures, "LIFECYCLE_QUALIFICATION_GATE_FAILED");
  const decision = decisionFor(failures, scenario);
  const qualified = decision === "W2_2_LIFECYCLE_ENGINE_QUALIFIED";
  const domain_model = nested({ model_id: domainOk ? `model:w2.2:lifecycle-domain:${input.seed ?? "canonical"}` : "", agent_states: domainOk ? freezeArray(AGENT_STATES) : freezeArray<AgentLifecycleState>([]), runtime_states: domainOk ? freezeArray(RUNTIME_STATES) : freezeArray<RuntimeLifecycleState>([]), transition_definitions: domainOk, state_version_model: domainOk, reason_code_registry: domainOk, command_model: domainOk, event_model: domainOk, restriction_model: domainOk });
  const runtime_state_machine = nested({ machine_id: runtimeOk ? "machine:w2.2:runtime-instance" : "", authoritative_execution_control: runtimeOk, execution_enabled_states: runtimeOk ? freezeArray<RuntimeLifecycleState>(["RUNNING"]) : freezeArray<RuntimeLifecycleState>([]), degraded_requires_signed_policy: runtimeOk, illegal_transitions_rejected: runtimeOk, terminal_state_enforcement: runtimeOk, state_survives_restart: runtimeOk, process_status_not_authoritative: runtimeOk });
  const agent_lifecycle = nested({ machine_id: agentOk ? "machine:w2.2:agent-lifecycle" : "", agent_lifecycle_states: agentOk ? freezeArray(AGENT_STATES) : freezeArray<AgentLifecycleState>([]), version_scoped_controls: agentOk, new_runtime_eligibility_control: agentOk, terminal_behavior_validated: agentOk, registry_projection_synchronized: agentOk, revocation_terminal: agentOk });
  const coupling = nested({ service_id: couplingOk ? "service:w2.2:lifecycle-coupling" : "", agent_to_runtime_propagation: couplingOk, runtime_to_agent_escalation: couplingOk, suspension_propagation: couplingOk, revocation_propagation: couplingOk, retirement_zero_active_runtime_check: couplingOk, partial_propagation_detection: couplingOk, coupling_evidence: couplingOk, deterministic: couplingOk });
  const transition_validation = nested({ service_id: transitionOk ? "service:w2.2:transition-validation" : "", validates_source_target: transitionOk, validates_principal_scope: transitionOk, validates_authority_policy_safety: transitionOk, validates_trust_certification_operator: transitionOk, validates_idempotency: transitionOk, optimistic_concurrency: transitionOk, atomic_commitment: transitionOk, outcomes: transitionOk ? freezeArray(OUTCOMES) : freezeArray<TransitionOutcome>([]), missing_prerequisites_fail_closed: transitionOk });
  const health_service = nested({ service_id: healthOk ? "service:w2.2:lifecycle-health" : "", agent_health: healthOk, runtime_health: healthOk, health_dimensions: healthOk ? freezeArray(["process", "runtime_responsiveness", "dependency", "configuration", "identity_credential", "authorization", "storage", "messaging", "registry", "memory", "planning", "policy_gate", "safety_gate", "authority_validator", "trust", "certification", "resources", "latency", "errors", "retry", "dead_letter", "state_divergence", "evidence_pipeline", "tenant_isolation"]) : freezeArray<string>([]), stale_observation_detection: healthOk, critical_health_fail_closed: healthOk, recommendations_only: healthOk, tenant_isolation: healthOk });
  const recovery_suspension_retirement_revocation = nested({ manager_id: managersOk ? "manager:w2.2:lifecycle-controls" : "", bounded_recovery: managersOk, checkpoint_recovery: managersOk, replay_recovery: managersOk, recovery_restrictions: managersOk, suspension_directives: managersOk, emergency_suspension: managersOk, retirement_planning: managersOk, runtime_draining: managersOk, revocation_commands: managersOk, credential_invalidation: managersOk, revocation_overrides_recovery: managersOk });
  const history_replay = nested({ store_id: historyOk ? "store:w2.2:lifecycle-history" : "", append_only_history: historyOk, hash_chaining: historyOk, ordered_per_subject: historyOk, tenant_scoped: historyOk, queryable: historyOk, replayable: historyOk, state_reconstruction: historyOk, divergence_detection: historyOk, mutation_detectable: historyOk });
  const apis_observability = nested({ api_id: apiOk ? "api:w2.2:lifecycle" : "", command_api: apiOk, query_api: apiOk, decision_api: apiOk, event_api: apiOk, registry_projection_non_authoritative: apiOk, orchestrator_verification: apiOk, metrics: apiOk ? freezeArray(["transition_counts", "transition_latency", "denied_transitions", "failed_transitions", "stale_requests", "lifecycle_conflicts", "runtime_time_in_state", "recovery_attempts", "suspension_latency", "revocation_latency", "quarantined_instances", "invariant_violations"]) : freezeArray<string>([]), dashboards: apiOk ? freezeArray(["agent_lifecycle", "runtime_lifecycle", "agent_health", "recovery", "suspension_revocation", "lifecycle_integrity"]) : freezeArray<string>([]) });
  const evidence = nested({ ledger_id: evidenceOk ? "ledger:w2.2:lifecycle-evidence" : "", records: evidenceOk ? freezeArray(["lifecycle:transition", "lifecycle:history", "lifecycle:coupling", "lifecycle:health", "lifecycle:recovery", "lifecycle:suspension", "lifecycle:retirement", "lifecycle:revocation", "lifecycle:replay"]) : freezeArray<string>([]), transition_evidence: evidenceOk, history_evidence: evidenceOk, coupling_evidence: evidenceOk, health_evidence: evidenceOk, recovery_evidence: evidenceOk, suspension_evidence: evidenceOk, retirement_evidence: evidenceOk, revocation_evidence: evidenceOk, replay_evidence: evidenceOk, immutable: evidenceOk });
  const qualification = nested({ report_id: gateOk ? "report:w2.2:lifecycle-qualification" : "", authoritative_execution_control: qualified, state_machine_completeness: qualified, transition_integrity: qualified, coupling_validated: qualified, execution_eligibility_enforced: qualified, health_correctness: qualified, recovery_correctness: qualified, suspension_enforcement: qualified, retirement_correctness: qualified, revocation_enforcement: qualified, tenant_isolation: qualified, concurrency_safety: qualified, immutable_history: qualified, deterministic_replay: qualified, operational_readiness: qualified, evidence_completeness: qualified, gate_decision: decision });
  const readiness = nested({ readiness_id: "W2.2-LIFECYCLE-ENGINE-READINESS-001", decision, phase_ready: qualified, constitution_ready: !constitutionInvalid, agent_registry_ready: !agentRegistryInvalid, domain_model_ready: domainOk, runtime_machine_ready: runtimeOk, agent_machine_ready: agentOk, coupling_ready: couplingOk, transition_validation_ready: transitionOk, health_ready: healthOk, managers_ready: managersOk, history_replay_ready: historyOk, api_observability_ready: apiOk, evidence_ready: evidenceOk, qualification_ready: qualified && tenantOk, failures });
  const base: Omit<LifecycleEngineResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, caf_constitution_ref: "caf-constitutional-foundation/w2.0", agent_registry_ref: "agent-registry/w2.1", domain_model, runtime_state_machine, agent_lifecycle, coupling, transition_validation, health_service, recovery_suspension_retirement_revocation, history_replay, apis_observability, evidence, qualification, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateLifecycleEngine(result?: LifecycleEngineResult): LifecycleEngineValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, domain_model_valid: false, runtime_machine_valid: false, agent_machine_valid: false, coupling_valid: false, transition_validation_valid: false, health_valid: false, managers_valid: false, history_replay_valid: false, api_observability_valid: false, evidence_valid: false, qualification_valid: false, readiness_valid: false, failures: freezeArray(["LIFECYCLE_DOMAIN_MODEL_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const domain_model_valid = verifyHashed(result.domain_model) && result.domain_model.agent_states.length === 10 && result.domain_model.runtime_states.length === 16 && result.domain_model.state_version_model;
  const runtime_machine_valid = verifyHashed(result.runtime_state_machine) && result.runtime_state_machine.authoritative_execution_control && result.runtime_state_machine.execution_enabled_states.join() === "RUNNING" && result.runtime_state_machine.process_status_not_authoritative;
  const agent_machine_valid = verifyHashed(result.agent_lifecycle) && result.agent_lifecycle.agent_lifecycle_states.length === 10 && result.agent_lifecycle.new_runtime_eligibility_control && result.agent_lifecycle.revocation_terminal;
  const coupling_valid = verifyHashed(result.coupling) && result.coupling.suspension_propagation && result.coupling.revocation_propagation && result.coupling.retirement_zero_active_runtime_check;
  const transition_validation_valid = verifyHashed(result.transition_validation) && result.transition_validation.outcomes.length === 7 && result.transition_validation.optimistic_concurrency && result.transition_validation.missing_prerequisites_fail_closed;
  const health_valid = verifyHashed(result.health_service) && result.health_service.health_dimensions.length >= 24 && result.health_service.recommendations_only && result.health_service.critical_health_fail_closed;
  const managers_valid = verifyHashed(result.recovery_suspension_retirement_revocation) && result.recovery_suspension_retirement_revocation.bounded_recovery && result.recovery_suspension_retirement_revocation.revocation_overrides_recovery;
  const history_replay_valid = verifyHashed(result.history_replay) && result.history_replay.append_only_history && result.history_replay.state_reconstruction && result.history_replay.divergence_detection;
  const api_observability_valid = verifyHashed(result.apis_observability) && result.apis_observability.command_api && result.apis_observability.registry_projection_non_authoritative && result.apis_observability.orchestrator_verification;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.records.length >= 9 && result.evidence.immutable && result.evidence.replay_evidence;
  const qualification_valid = verifyHashed(result.qualification) && result.qualification.authoritative_execution_control && result.qualification.deterministic_replay && result.qualification.gate_decision === "W2_2_LIFECYCLE_ENGINE_QUALIFIED";
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && domain_model_valid && runtime_machine_valid && agent_machine_valid && coupling_valid && transition_validation_valid && health_valid && managers_valid && history_replay_valid && api_observability_valid && evidence_valid && qualification_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, domain_model_valid, runtime_machine_valid, agent_machine_valid, coupling_valid, transition_validation_valid, health_valid, managers_valid, history_replay_valid, api_observability_valid, evidence_valid, qualification_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayLifecycleEngine(result = runLifecycleEngine()): boolean { const replayed = runLifecycleEngine(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateLifecycleEngine(result).valid; }
export function getLifecycleEngineBundle(): LifecycleEngineBundle { const result = runLifecycleEngine(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_agent_lifecycle: true, owns_runtime_instance_lifecycle: true, owns_transition_validation: true, owns_lifecycle_coupling: true, owns_health_services: true, owns_recovery_suspension_retirement_revocation: true, owns_lifecycle_history: true, owns_lifecycle_replay: true, owns_lifecycle_apis: true, qualification_gate: "Lifecycle Infrastructure Qualification Gate" }), result, validation: validateLifecycleEngine(result) }); }
export const LifecycleEngineService = Object.freeze({ run: runLifecycleEngine, validate: validateLifecycleEngine, replay: replayLifecycleEngine });
