import Link from "next/link";
import { requireSessionUser } from "@/src/lib/auth";
import { requireWorkspaceManager } from "@/src/server/auth/permissions";
import { PrismaEvaluationArtifactRepository } from "@/services/learning-constitution";
import type { Evaluation, EvaluationCompetenceAssessment, EvaluationFailure, EvaluationLifecycleEvent, EvaluationScore, EvaluationValidity } from "@/types/learning-constitution";

export const dynamic = "force-dynamic";
const percent = (value: number | null | undefined) => value === null || value === undefined ? "—" : `${Math.round(value * 100)}%`;

export default async function EvaluationsPage() {
  const user = await requireSessionUser();
  if (!user.workspaceId || user.workspaceId === "default") return <main className="p-6">Workspace membership required.</main>;
  await requireWorkspaceManager({ userId: user.id, userRole: user.role, workspaceId: user.workspaceId });
  const artifacts = await new PrismaEvaluationArtifactRepository(user.workspaceId).listWorkspaceArtifacts();
  const evaluations = artifacts.filter((artifact) => artifact.artifactType === "EVALUATION").map((artifact) => artifact.payload as Evaluation);
  const assessments = artifacts.filter((artifact) => artifact.artifactType === "ASSESSMENT").map((artifact) => artifact.payload as EvaluationCompetenceAssessment);
  const assessmentBySkill = new Map(assessments.map((assessment) => [assessment.skillId, assessment]));
  const evidenceCount = artifacts.filter((artifact) => artifact.artifactType === "EVIDENCE").length;
  return <main className="mx-auto max-w-5xl space-y-6 p-6"><header><p className="text-sm font-medium uppercase tracking-wide text-violet-700">Noesis · Phase 21</p><h1 className="text-2xl font-semibold">Evaluation Engine</h1><p className="mt-1 text-sm text-slate-600">Competence is derived from independently evaluated, valid performance evidence—not a claimed capability or a single success.</p></header>
    <section className="grid gap-4 md:grid-cols-3"><article className="rounded border p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Evaluations</p><p className="mt-1 text-2xl font-semibold">{evaluations.length}</p></article><article className="rounded border p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Retained evidence</p><p className="mt-1 text-2xl font-semibold">{evidenceCount}</p></article><article className="rounded border p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Boundary</p><p className="mt-1 text-sm">Evidence only · governed mastery review</p></article></section>
    <section className="rounded border p-4"><h2 className="font-medium">Competence assessments</h2>{assessments.length ? <ul className="mt-3 space-y-3">{assessments.slice().reverse().map((assessment) => <li key={assessment.assessmentId} className="rounded border border-slate-200 p-3"><div className="flex flex-wrap justify-between gap-2"><p className="font-medium">{assessment.skillId}</p><span className="font-mono text-xs">{assessment.status}</span></div><p className="mt-1 text-sm text-slate-600">{assessment.eligibleForMasteryReview ? "Evidence supports human-governed mastery review." : assessment.reasons.join(" ")}</p><p className="mt-2 text-xs text-slate-500">Supporting evidence: {assessment.supportingEvidenceIds.length} · current result has no direct mastery effect.</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-600">No competence assessments have been derived yet.</p>}</section>
    <section className="rounded border p-4"><h2 className="font-medium">Evaluation history</h2>{evaluations.length ? <ul className="mt-3 space-y-4">{evaluations.slice().reverse().map((evaluation) => { const score = artifacts.find((artifact) => artifact.artifactType === "SCORE" && artifact.subjectId === evaluation.evaluationId)?.payload as EvaluationScore | undefined; const validity = artifacts.find((artifact) => artifact.artifactType === "VALIDITY" && artifact.subjectId === evaluation.evaluationId)?.payload as EvaluationValidity | undefined; const lifecycle = artifacts.filter((artifact) => artifact.artifactType === "LIFECYCLE" && artifact.subjectId === evaluation.evaluationId).map((artifact) => artifact.payload as EvaluationLifecycleEvent).at(-1); const failures = artifacts.filter((artifact) => artifact.artifactType === "FAILURE" && artifact.subjectId === evaluation.evaluationId).map((artifact) => artifact.payload as EvaluationFailure); const assessment = assessmentBySkill.get(evaluation.skillId); return <li key={evaluation.evaluationId} className="rounded border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{evaluation.skillId} · {evaluation.evaluationType}</p><p className="mt-1 text-sm text-slate-600">{evaluation.exerciseIds.length} exercise{evaluation.exerciseIds.length === 1 ? "" : "s"} · difficulty {percent(evaluation.difficulty)} · evaluator {evaluation.evaluator.type}</p></div><div className="text-right font-mono text-xs"><p>{lifecycle?.nextState ?? "CREATED"}</p><p className={validity?.status === "VALID" ? "text-emerald-700" : validity?.status === "INVALID" ? "text-rose-700" : "text-slate-500"}>{validity?.status ?? "UNSCORED"}</p></div></div>{score ? <div className="mt-3 grid grid-cols-2 gap-x-4 gap-y-1 text-sm md:grid-cols-4"><p>Overall <strong>{percent(score.overallScore)}</strong></p><p>Correctness {percent(score.dimensionScores.CORRECTNESS)}</p><p>Generalization {percent(score.dimensionScores.GENERALIZATION)}</p><p>Boundary {percent(score.dimensionScores.BOUNDARY_RECOGNITION)}</p><p>Exceptions {percent(score.dimensionScores.EXCEPTION_HANDLING)}</p><p>Consistency {percent(score.dimensionScores.CONSISTENCY)}</p><p>Calibration {percent(score.dimensionScores.CALIBRATION)}</p><p>Outcome <strong>{score.outcome}</strong></p></div> : <p className="mt-3 text-sm text-slate-600">Awaiting independent scoring.</p>}{failures.length ? <p className="mt-3 text-sm text-amber-800">Failures: {failures.map((failure) => `${failure.dimension} (${failure.category})`).join(", ")}</p> : null}{assessment ? <p className="mt-3 text-xs text-slate-500">Latest assessment: {assessment.status} · {assessment.supportingEvidenceIds.length} retained evidence items.</p> : null}</li>; })}</ul> : <p className="mt-3 text-sm text-slate-600">No evaluations have been created. Use the protected Evaluation API to initialize a frozen-context evaluation.</p>}</section>
    <p className="text-sm"><Link className="text-violet-700 underline" href="/learning/practice">View Practice Engine</Link> · <Link className="text-violet-700 underline" href="/learning/skills">View Skill Registry</Link> · <Link className="text-violet-700 underline" href="/learning/graph">Inspect Skill Graph</Link></p>
  </main>;
}
