import { NuruRoadmapRealityLifecycle } from "./roadmap-reality-lifecycle";

export default function NuruRoadmapRealityPage() { return <NuruRoadmapRealityLifecycle />; }

/*

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, BadgeCheck, CircleDashed, RefreshCw, TriangleAlert } from "lucide-react";
import "../nuru.css";

type Requirement = { id: string; project: string; title: string; implementationStatus: string; testRefs: string[]; implementationRefs: string[] };
type BuildPackage = { id: string; requirementIds: string[]; status: string; objective: string };
type Ledger = { id: string; buildPackageId: string; qualificationStatus: string; testsExecuted: string[]; knownLimitations: string[]; createdAt: string };
type Finding = { code: string; severity: "ERROR" | "WARNING"; recordId: string; message: string };
type Reality = Requirement & { state: "PLANNED" | "IN_PROGRESS" | "IMPLEMENTED" | "QUALIFIED" | "BLOCKED"; packages: BuildPackage[]; evidence: Ledger[]; findings: Finding[] };

export default function NuruRoadmapRealityPage() {
  const [requirements, setRequirements] = useState<Requirement[]>([]); const [packages, setPackages] = useState<BuildPackage[]>([]); const [ledger, setLedger] = useState<Ledger[]>([]); const [findings, setFindings] = useState<Finding[]>([]); const [message, setMessage] = useState("Loading roadmap reality…");
  const load = useCallback(async () => { try { const [requirementsResponse, packagesResponse, ledgerResponse, guardrailResponse] = await Promise.all([fetch("/api/nuru/project-requirements", { cache: "no-store" }), fetch("/api/nuru/codex-build-packages", { cache: "no-store" }), fetch("/api/nuru/implementation-ledger", { cache: "no-store" }), fetch("/api/nuru/architecture-guardrails", { cache: "no-store" })]); const requirementsBody = await requirementsResponse.json(); const packagesBody = await packagesResponse.json(); const ledgerBody = await ledgerResponse.json(); const guardrailBody = await guardrailResponse.json(); if (!requirementsResponse.ok || !requirementsBody.ok || !packagesResponse.ok || !packagesBody.ok || !ledgerResponse.ok || !ledgerBody.ok || !guardrailResponse.ok || !guardrailBody.ok) throw new Error("Nuru couldn’t load roadmap reality."); setRequirements(requirementsBody.data.requirements); setPackages(packagesBody.data.packages); setLedger(ledgerBody.data.entries); setFindings(guardrailBody.data.findings); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Nuru couldn’t load roadmap reality."); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const reality = useMemo<Reality[]>(() => requirements.map((requirement) => { const linkedPackages = packages.filter((item) => item.requirementIds.includes(requirement.id)); const evidence = ledger.filter((entry) => linkedPackages.some((item) => item.id === entry.buildPackageId)); const relatedFindings = findings.filter((finding) => [requirement.id, ...linkedPackages.map((item) => item.id), ...evidence.map((item) => item.id)].includes(finding.recordId)); const states = evidence.map((entry) => entry.qualificationStatus); const state = relatedFindings.some((finding) => finding.severity === "ERROR") ? "BLOCKED" : states.includes("QUALIFIED") ? "QUALIFIED" : states.includes("BLOCKED") || states.includes("FAILED") ? "BLOCKED" : requirement.implementationStatus === "IMPLEMENTED" || requirement.implementationStatus === "QUALIFIED" ? "IMPLEMENTED" : linkedPackages.some((item) => item.status === "IN_PROGRESS") ? "IN_PROGRESS" : "PLANNED"; return { ...requirement, packages: linkedPackages, evidence, findings: relatedFindings, state }; }), [requirements, packages, ledger, findings]);
  const totals = useMemo(() => Object.fromEntries(["PLANNED", "IN_PROGRESS", "IMPLEMENTED", "QUALIFIED", "BLOCKED"].map((state) => [state, reality.filter((item) => item.state === state).length])), [reality]);
  return <main className="nuru-shell reality-shell"><header className="nuru-nav"><Link className="nuru-brand" href="/nuru"><span>NURU</span><small>Discover a deeper world</small></Link><nav><Link href="/nuru/requirements">Requirements</Link><Link href="/nuru/build-packages">Build packages</Link><Link href="/nuru/implementation-ledger">Implementation ledger</Link><Link className="active" href="/nuru/roadmap-reality">Roadmap reality</Link></nav></header><section className="reality-hero"><Link className="back-link" href="/nuru/implementation-ledger"><ArrowLeft size={15} /> Implementation ledger</Link><p className="eyebrow"><BadgeCheck size={16} /> Evidence-backed delivery</p><h1>Roadmap Reality</h1><p>State is derived from governed requirements, build packages, execution evidence, and architecture guardrails.</p></section><section className="reality-content"><header className="vault-section-header"><div><p className="eyebrow">Capability status</p><h2>What is actually ready</h2></div><button className="quiet-button" onClick={() => void load()}><RefreshCw size={15} /> Refresh</button></header><div className="reality-totals">{Object.entries(totals).map(([state, count]) => <article key={state}><small>{state.replaceAll("_", " ")}</small><b>{count}</b></article>)}</div>{reality.length ? <div className="reality-list">{reality.map((item) => <article key={item.id} className={item.state.toLowerCase()}><header><p className="eyebrow">{item.project}</p><span>{item.state.replaceAll("_", " ")}</span></header><h2>{item.title}</h2><div><span><b>Requirement evidence</b>{item.implementationRefs.length} implementation · {item.testRefs.length} test references</span><span><b>Build packages</b>{item.packages.length ? item.packages.map((entry) => entry.objective).join(" · ") : "None recorded"}</span><span><b>Qualification evidence</b>{item.evidence.length ? item.evidence.map((entry) => `${entry.qualificationStatus} · ${entry.testsExecuted.length} tests`).join(" · ") : "None recorded"}</span></div>{item.findings.length > 0 && <small className="reality-warning"><TriangleAlert size={13} /> {item.findings.map((finding) => `${finding.severity}: ${finding.message}`).join(" · ")}</small>}{item.state === "BLOCKED" && item.findings.length === 0 && <small className="reality-warning"><TriangleAlert size={13} /> {item.evidence.flatMap((entry) => entry.knownLimitations).join(" · ") || "Execution evidence is blocked or failed."}</small>}</article>)}</div> : !message && <div className="vault-empty"><CircleDashed size={26} /><h2>No governed requirements yet</h2><p>Roadmap Reality begins when a current requirement has been recorded.</p></div>}{message && <p className="vault-message" role="status">{message}</p>}</section></main>;
}
*/
