"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { BadgeCheck } from "lucide-react";
import "../nuru.css";
type Requirement = { id: string; title: string; project: string; implementationStatus: string };
type Package = { id: string; requirementIds: string[] };
type Execution = { buildPackageId: string; branch: string };
type Ledger = { buildPackageId: string; qualificationStatus: string };
export function NuruRoadmapRealityLifecycle() { const [rows, setRows] = useState<Array<Requirement & { state: string; detail: string }>>([]); const [message, setMessage] = useState("Loading roadmap reality…"); useEffect(() => { const timer = window.setTimeout(() => { void Promise.all([fetch("/api/nuru/project-requirements"), fetch("/api/nuru/codex-build-packages"), fetch("/api/nuru/codex-execution-events"), fetch("/api/nuru/implementation-ledger")]).then(async ([requirementsResponse, packagesResponse, eventsResponse, ledgerResponse]) => { const requirements = await requirementsResponse.json(); const packages = await packagesResponse.json(); const events = await eventsResponse.json(); const ledger = await ledgerResponse.json(); const packageRows = packages.data?.packages as Package[] ?? []; const executions = events.data?.events as Execution[] ?? []; const evidence = ledger.data?.entries as Ledger[] ?? []; setRows((requirements.data?.requirements as Requirement[] ?? []).map((requirement) => { const linked = packageRows.filter((item) => item.requirementIds.includes(requirement.id)); const ledgerEntry = evidence.find((entry) => linked.some((item) => item.id === entry.buildPackageId)); const execution = executions.find((entry) => linked.some((item) => item.id === entry.buildPackageId)); const state = ledgerEntry?.qualificationStatus === "QUALIFIED" ? "QUALIFIED" : ledgerEntry?.qualificationStatus === "BLOCKED" || ledgerEntry?.qualificationStatus === "FAILED" ? "BLOCKED" : execution ? "IN PROGRESS" : requirement.implementationStatus.replaceAll("_", " "); return { ...requirement, state, detail: execution ? `Active branch: ${execution.branch}` : ledgerEntry ? `Implementation evidence: ${ledgerEntry.qualificationStatus}` : "No execution event recorded." }; })); setMessage(""); }).catch(() => setMessage("Nuru couldn’t load roadmap reality.")); }, 0); return () => window.clearTimeout(timer); }, []); return <main className="nuru-shell reality-shell"><header className="nuru-nav"><Link className="nuru-brand" href="/nuru"><span>NURU</span><small>Discover a deeper world</small></Link><nav><Link href="/nuru/build-packages">Build packages</Link><Link href="/nuru/implementation-ledger">Implementation ledger</Link><Link className="active" href="/nuru/roadmap-reality">Roadmap reality</Link></nav></header><section className="reality-hero"><p className="eyebrow"><BadgeCheck size={16} /> Evidence-backed delivery</p><h1>Roadmap Reality</h1><p>Active execution comes from retained Start Work events; qualification comes from implementation evidence.</p></section><section className="reality-content"><div className="reality-list">{rows.map((row) => <article key={row.id} className={row.state.toLowerCase().replaceAll(" ", "-")}><header><p className="eyebrow">{row.project}</p><span>{row.state}</span></header><h2>{row.title}</h2><p>{row.detail}</p></article>)}</div>{message && <p className="vault-message">{message}</p>}</section></main>; }
