version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: /services/api
    schedule:
      interval: weekly
    groups:
      dotnet-dependencies:
        patterns:
          - '*'
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      container-images:
        patterns:
          - '*'
    open-pull-requests-limit: 5
