export type ConstitutionalGovernanceErrorCode =
  | "CONSTITUTIONAL_REPO_CONTEXT_MISSING"
  | "CONSTITUTIONAL_AUTHORITY_INVALID"
  | "CONSTITUTIONAL_POLICY_MISSING"
  | "CONSTITUTIONAL_SCOPE_DENIED"
  | "REPLAY_AUTHORITY_DENIED"
  | "REPLAY_MUTATION_ATTEMPT"
  | "SNAPSHOT_ACCESS_DENIED"
  | "SNAPSHOT_MUTATION_FORBIDDEN"
  | "SIMULATION_SCOPE_INVALID"
  | "SIMULATION_EXECUTION_FORBIDDEN"
  | "RECOVERY_AUTHORITY_REQUIRED"
  | "AUTONOMOUS_RECOVERY_FORBIDDEN"
  | "ESCALATION_AUTHORITY_INVALID"
  | "AUTONOMY_SCOPE_EXCEEDED"
  | "AUTONOMY_SELF_AUTHORIZATION_FORBIDDEN"
  | "GOVERNANCE_BYPASS_ATTEMPT"
  | "CONSTITUTIONAL_LINEAGE_DISPUTED";

export type ConstitutionalGovernanceError = Readonly<{
  code: ConstitutionalGovernanceErrorCode;
  message: string;
  path?: string;
}>;
