import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runConstitutionalComplianceGate, validateConstitutionalComplianceGate } from "@/services/trust-constitutional-compliance-gate";
import { runTrustCertificationStageEleven, validateTrustCertificationStageEleven } from "@/services/trust-certification-stage-eleven";
import { runTrustContinuousMonitoringStageEight, validateTrustContinuousMonitoringStageEight } from "@/services/trust-continuous-monitoring-stage-eight";
import { runTrustDriftDetectionStageNine, validateTrustDriftDetectionStageNine } from "@/services/trust-drift-detection-stage-nine";
import { runTrustExplainabilityStageSix, validateTrustExplainabilityStageSix } from "@/services/trust-explainability-stage-six";
import { runTrustFederationStageTwelve, validateTrustFederationStageTwelve } from "@/services/trust-federation-stage-twelve";
import { runTrustFoundationStageOne, validateTrustFoundationStageOne } from "@/services/trust-foundation-stage-one";
import { runTrustHumanOversightStageSeven, validateTrustHumanOversightStageSeven } from "@/services/trust-human-oversight-stage-seven";
import { runTrustIndependentEvaluation, validateTrustIndependentEvaluation } from "@/services/trust-independent-evaluation";
import { runTrustRecoveryRevocationStageTen, validateTrustRecoveryRevocationStageTen } from "@/services/trust-recovery-revocation-stage-ten";
import { runTrustRegistryDomains, validateTrustRegistryDomains } from "@/services/trust-registry-domains";
import { runTrustResolutionEngine, validateTrustResolutionEngine } from "@/services/trust-resolution-engine";
import type { ProgramQualificationArea, ProgramQualificationDecision, TrustProgramQualificationBundle, TrustProgramQualificationFailure, TrustProgramQualificationInput, TrustProgramQualificationResult, TrustProgramQualificationScenario, TrustProgramQualificationValidation } from "@/types/trust-program-qualification-stage-thirteen";

const VERSION = "trust-program-qualification-stage-thirteen/stage-13" as const;
const IDENTIFIER = "TrustProgramQualificationStageThirteen" as const;
const AREAS = Object.freeze<ProgramQualificationArea[]>(["CONSTITUTIONAL_COMPLIANCE", "TRUST_DETERMINISM", "RESOLUTION", "EXPLAINABILITY", "HUMAN_OVERSIGHT", "CONTINUOUS_MONITORING", "DRIFT_DETECTION", "RECOVERY", "CERTIFICATION", "FEDERATION", "REPLAY", "EVIDENCE_INTEGRITY", "IMMUTABLE_LINEAGE", "TENANT_ISOLATION", "CONSTITUTIONAL_INVARIANTS"]);
const UPSTREAM_REFS = Object.freeze(["trust-foundation-stage-one/stage-1", "trust-constitutional-compliance-gate/stage-2", "trust-registry-domains/stage-3", "trust-independent-evaluation/stage-4", "trust-resolution-engine/stage-5", "trust-explainability-stage-six/stage-6", "trust-human-oversight-stage-seven/stage-7", "trust-continuous-monitoring-stage-eight/stage-8", "trust-drift-detection-stage-nine/stage-9", "trust-recovery-revocation-stage-ten/stage-10", "trust-certification-stage-eleven/stage-11", "trust-federation-stage-twelve/stage-12"]);
const PROVIDES = Object.freeze(["program-qualification-report", "qualification-evidence-ledger", "qualification-decision", "trust-readiness-assessment", "constitutional-compliance-report", "deterministic-replay-report", "evidence-integrity-report", "trust-qualification-dashboard", "final-qualification-evidence-package"]);
let baselines: ReturnType<typeof makeBaselines> | undefined;

function makeBaselines() { return { foundation: runTrustFoundationStageOne(), gate: runConstitutionalComplianceGate(), registry: runTrustRegistryDomains(), evaluation: runTrustIndependentEvaluation(), resolution: runTrustResolutionEngine(), explainability: runTrustExplainabilityStageSix(), oversight: runTrustHumanOversightStageSeven(), monitoring: runTrustContinuousMonitoringStageEight(), drift: runTrustDriftDetectionStageNine(), recovery: runTrustRecoveryRevocationStageTen(), certification: runTrustCertificationStageEleven(), federation: runTrustFederationStageTwelve() }; }
function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly TrustProgramQualificationFailure[], failure: TrustProgramQualificationFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustProgramQualificationScenario): TrustProgramQualificationFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly TrustProgramQualificationFailure[], scenario?: TrustProgramQualificationScenario): ProgramQualificationDecision {
  const failClosed = new Set<TrustProgramQualificationFailure>(["STAGE_1_TRUST_FOUNDATION_INVALID", "STAGE_2_CONSTITUTIONAL_GATE_INVALID", "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID", "STAGE_4_INDEPENDENT_EVALUATION_INVALID", "STAGE_5_TRUST_RESOLUTION_INVALID", "STAGE_6_EXPLAINABILITY_INVALID", "STAGE_7_HUMAN_OVERSIGHT_INVALID", "STAGE_8_CONTINUOUS_MONITORING_INVALID", "STAGE_9_DRIFT_DETECTION_INVALID", "STAGE_10_RECOVERY_REVOCATION_INVALID", "STAGE_11_TRUST_CERTIFICATION_INVALID", "STAGE_12_TRUST_FEDERATION_INVALID", "CONSTITUTIONAL_BYPASS_DETECTED", "NONDETERMINISTIC_TRUST_DECISION_DETECTED", "UNREPLAYABLE_DECISION_DETECTED", "MUTABLE_EVIDENCE_DETECTED", "INCOMPLETE_LINEAGE_DETECTED", "TENANT_ISOLATION_BREACH_DETECTED", "HIGH_OR_CRITICAL_FINDINGS_OPEN", "FINAL_AUTHORITY_NOT_ISSUED", "PROGRAM_QUALIFICATION_REPLAY_DIVERGED"]);
  if (failures.some((failure) => failClosed.has(failure))) return "FAIL_CLOSED";
  if (has(failures, "TRUST_PROGRAM_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP" || scenario === "QUALIFIED_WITH_OBSERVATIONS") return "CONDITIONALLY_QUALIFIED";
  return "QUALIFIED";
}
function resultReplayHash(result: Omit<TrustProgramQualificationResult, "replay_hash" | "integrity_hash">): string { return hash({ matrix: result.matrix.integrity_hash, evidence: result.evidence.integrity_hash, replay: result.replay.integrity_hash, lineage: result.lineage.integrity_hash, isolation: result.isolation.integrity_hash, findings: result.findings.integrity_hash, authority: result.authority.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<TrustProgramQualificationResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runTrustProgramQualificationStageThirteen(input: TrustProgramQualificationInput = {}): TrustProgramQualificationResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  const scenarioFailures = freezeArray<TrustProgramQualificationFailure>(direct ? [direct] : []);
  baselines ??= makeBaselines();
  const failures = freezeArray([...new Set([...scenarioFailures, ...(!validateTrustFoundationStageOne(baselines.foundation).valid ? ["STAGE_1_TRUST_FOUNDATION_INVALID" as const] : []), ...(!validateConstitutionalComplianceGate(baselines.gate).valid ? ["STAGE_2_CONSTITUTIONAL_GATE_INVALID" as const] : []), ...(!validateTrustRegistryDomains(baselines.registry).valid ? ["STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" as const] : []), ...(!validateTrustIndependentEvaluation(baselines.evaluation).valid ? ["STAGE_4_INDEPENDENT_EVALUATION_INVALID" as const] : []), ...(!validateTrustResolutionEngine(baselines.resolution).valid ? ["STAGE_5_TRUST_RESOLUTION_INVALID" as const] : []), ...(!validateTrustExplainabilityStageSix(baselines.explainability).valid ? ["STAGE_6_EXPLAINABILITY_INVALID" as const] : []), ...(!validateTrustHumanOversightStageSeven(baselines.oversight).valid ? ["STAGE_7_HUMAN_OVERSIGHT_INVALID" as const] : []), ...(!validateTrustContinuousMonitoringStageEight(baselines.monitoring).valid ? ["STAGE_8_CONTINUOUS_MONITORING_INVALID" as const] : []), ...(!validateTrustDriftDetectionStageNine(baselines.drift).valid ? ["STAGE_9_DRIFT_DETECTION_INVALID" as const] : []), ...(!validateTrustRecoveryRevocationStageTen(baselines.recovery).valid ? ["STAGE_10_RECOVERY_REVOCATION_INVALID" as const] : []), ...(!validateTrustCertificationStageEleven(baselines.certification).valid ? ["STAGE_11_TRUST_CERTIFICATION_INVALID" as const] : []), ...(!validateTrustFederationStageTwelve(baselines.federation).valid ? ["STAGE_12_TRUST_FEDERATION_INVALID" as const] : [])])]);
  const matrixOk = !has(failures, "CONSTITUTIONAL_COMPLIANCE_UNVERIFIED") && !has(failures, "TRUST_DETERMINISM_UNVERIFIED") && !has(failures, "RESOLUTION_CORRECTNESS_UNVERIFIED") && !has(failures, "EXPLAINABILITY_INCOMPLETE") && !has(failures, "HUMAN_OVERSIGHT_UNQUALIFIED") && !has(failures, "CONTINUOUS_MONITORING_UNQUALIFIED") && !has(failures, "DRIFT_DETECTION_UNQUALIFIED") && !has(failures, "RECOVERY_REVOCATION_UNQUALIFIED") && !has(failures, "TRUST_CERTIFICATION_UNQUALIFIED") && !has(failures, "TRUST_FEDERATION_UNQUALIFIED") && !has(failures, "REPLAY_QUALIFICATION_UNVERIFIED") && !has(failures, "EVIDENCE_INTEGRITY_UNVERIFIED") && !has(failures, "IMMUTABLE_LINEAGE_UNVERIFIED") && !has(failures, "TENANT_ISOLATION_UNVERIFIED") && !has(failures, "CONSTITUTIONAL_INVARIANTS_UNVERIFIED");
  const evidenceOk = !has(failures, "PROGRAM_QUALIFICATION_REPORT_MISSING") && !has(failures, "QUALIFICATION_EVIDENCE_LEDGER_MISSING") && !has(failures, "TRUST_READINESS_ASSESSMENT_MISSING") && !has(failures, "FINAL_EVIDENCE_PACKAGE_MISSING") && !has(failures, "QUALIFICATION_DASHBOARD_MISSING") && !has(failures, "MUTABLE_EVIDENCE_DETECTED");
  const replayOk = !has(failures, "UNREPLAYABLE_DECISION_DETECTED") && !has(failures, "PROGRAM_QUALIFICATION_REPLAY_DIVERGED");
  const lineageOk = !has(failures, "INCOMPLETE_LINEAGE_DETECTED") && !has(failures, "IMMUTABLE_LINEAGE_UNVERIFIED");
  const isolationOk = !has(failures, "TENANT_ISOLATION_BREACH_DETECTED") && !has(failures, "TENANT_ISOLATION_UNVERIFIED");
  const findingsOk = !has(failures, "HIGH_OR_CRITICAL_FINDINGS_OPEN");
  const authorityOk = !has(failures, "FINAL_AUTHORITY_NOT_ISSUED");
  const noBypass = !has(failures, "CONSTITUTIONAL_BYPASS_DETECTED");
  const deterministic = !has(failures, "NONDETERMINISTIC_TRUST_DECISION_DETECTED");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "QUALIFIED";
  const tenant_id = input.tenant_id ?? baselines.federation.tenant_id;
  const qualification_id = input.qualification_id ?? `trust-program-qualification:stage-13:${input.seed ?? "canonical"}`;
  const matrix = nested({ matrix_id: matrixOk ? "matrix:stage-13:program" : "", areas: freezeArray(AREAS), constitutional_compliance: matrixOk && noBypass, trust_determinism: matrixOk && deterministic, resolution_correctness: matrixOk, explainability: matrixOk, human_oversight: matrixOk, continuous_monitoring: matrixOk, drift_detection: matrixOk, recovery_revocation: matrixOk, trust_certification: matrixOk, trust_federation: matrixOk, replay: matrixOk && replayOk, evidence_integrity: matrixOk && evidenceOk, immutable_lineage: matrixOk && lineageOk, tenant_isolation: matrixOk && isolationOk, constitutional_invariants: matrixOk && noBypass });
  const evidence = nested({ evidence_id: evidenceOk ? "evidence:stage-13:program" : "", program_qualification_report: evidenceOk, qualification_evidence_ledger: evidenceOk, qualification_decision: evidenceOk, trust_readiness_assessment: evidenceOk, constitutional_compliance_report: evidenceOk, deterministic_replay_report: evidenceOk && replayOk, evidence_integrity_report: evidenceOk, trust_qualification_dashboard: evidenceOk, final_qualification_evidence_package: evidenceOk, immutable: evidenceOk, complete: evidenceOk, replayable: evidenceOk && replayOk });
  const replay = nested({ replay_id: replayOk ? "replay:stage-13:program" : "", decision_replay: replayOk, constitutional_replay: replayOk, evidence_replay: replayOk, oversight_replay: replayOk, monitoring_replay: replayOk, certification_replay: replayOk, federation_replay: replayOk, identical_outcomes: replayOk, identical_evidence: replayOk && evidenceOk, identical_lineage: replayOk && lineageOk });
  const lineage = nested({ lineage_id: lineageOk ? "lineage:stage-13:program" : "", decision_lineage: lineageOk, standing_lineage: lineageOk, evidence_lineage: lineageOk, oversight_lineage: lineageOk, certification_lineage: lineageOk, federation_lineage: lineageOk, immutable_lineage: lineageOk, complete_lineage: lineageOk, queryable_lineage: lineageOk });
  const isolation = nested({ isolation_id: isolationOk ? "isolation:stage-13:tenant" : "", domain_isolation: isolationOk, tenant_boundaries: isolationOk, cross_domain_enforcement: isolationOk, federation_boundaries: isolationOk, trust_registry_isolation: isolationOk, evidence_isolation: isolationOk, no_cross_tenant_leakage: isolationOk, isolation_validated: isolationOk });
  const findings = nested({ findings_id: "findings:stage-13:program", highest_severity: findingsOk ? "NONE" as const : "CRITICAL" as const, critical_findings_open: findingsOk ? 0 : 1, high_findings_open: 0, medium_findings_open: 0, low_findings_open: 0, unresolved_constitutional_findings: findingsOk ? 0 : 1, unresolved_governance_findings: 0, unresolved_replay_findings: replayOk ? 0 : 1, unresolved_evidence_findings: evidenceOk ? 0 : 1, unresolved_trust_integrity_findings: findingsOk ? 0 : 1, no_blocking_findings: findingsOk });
  const authority = nested({ authority_id: authorityOk ? "authority:stage-13:cata" : "", final_decision: decision, cata_trust_framework_qualified: qualified, constitutional_trust_authority_for_proprium: qualified, constitutional_trust_authority_for_civitas: qualified, autonomous_trust_governance_ready: qualified, formal_authority_issued: authorityOk && qualified, effective_authority: authorityOk && qualified });
  const readiness = nested({ readiness_id: "STAGE-13-PROGRAM-QUALIFICATION-READINESS-001", decision, phase_ready: qualified, upstream_ready: failures.every((failure) => !failure.startsWith("STAGE_")), matrix_ready: matrixOk, evidence_ready: evidenceOk, replay_ready: replayOk, lineage_ready: lineageOk, isolation_ready: isolationOk, findings_clear: findingsOk, authority_ready: authorityOk, constitutional_supremacy: noBypass, deterministic_trust: deterministic, evidence_based_qualification: evidenceOk, replayability: replayOk, explainability: matrix.explainability, tenant_isolation: isolationOk, no_bypass: noBypass, no_high_or_critical_findings: findingsOk, formally_qualified: qualified, failures });
  const base: Omit<TrustProgramQualificationResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id, qualification_id, matrix, evidence, replay, lineage, isolation, findings, authority, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustProgramQualificationStageThirteen(result?: TrustProgramQualificationResult): TrustProgramQualificationValidation {
  if (!result) return nested({ valid: false, decision: "FAIL_CLOSED" as const, replay_hash_valid: false, integrity_hash_valid: false, matrix_valid: false, evidence_valid: false, replay_valid: false, lineage_valid: false, isolation_valid: false, findings_valid: false, authority_valid: false, readiness_valid: false, failures: freezeArray(["PROGRAM_QUALIFICATION_REPORT_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const matrix_valid = verifyHashed(result.matrix) && result.matrix.areas.length === 15 && result.matrix.constitutional_compliance && result.matrix.trust_determinism && result.matrix.constitutional_invariants;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.program_qualification_report && result.evidence.qualification_evidence_ledger && result.evidence.final_qualification_evidence_package && result.evidence.immutable && result.evidence.complete;
  const replay_valid = verifyHashed(result.replay) && result.replay.decision_replay && result.replay.certification_replay && result.replay.federation_replay && result.replay.identical_outcomes;
  const lineage_valid = verifyHashed(result.lineage) && result.lineage.decision_lineage && result.lineage.certification_lineage && result.lineage.federation_lineage && result.lineage.immutable_lineage && result.lineage.complete_lineage;
  const isolation_valid = verifyHashed(result.isolation) && result.isolation.domain_isolation && result.isolation.tenant_boundaries && result.isolation.federation_boundaries && result.isolation.no_cross_tenant_leakage;
  const findings_valid = verifyHashed(result.findings) && result.findings.highest_severity === "NONE" && result.findings.critical_findings_open === 0 && result.findings.high_findings_open === 0 && result.findings.no_blocking_findings;
  const authority_valid = verifyHashed(result.authority) && result.authority.final_decision === "QUALIFIED" && result.authority.cata_trust_framework_qualified && result.authority.formal_authority_issued;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.upstream_ready && result.readiness.constitutional_supremacy && result.readiness.deterministic_trust && result.readiness.evidence_based_qualification && result.readiness.replayability && result.readiness.tenant_isolation && result.readiness.no_high_or_critical_findings && result.readiness.formally_qualified && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && matrix_valid && evidence_valid && replay_valid && lineage_valid && isolation_valid && findings_valid && authority_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, matrix_valid, evidence_valid, replay_valid, lineage_valid, isolation_valid, findings_valid, authority_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayTrustProgramQualificationStageThirteen(result = runTrustProgramQualificationStageThirteen()): boolean { const replayed = runTrustProgramQualificationStageThirteen(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustProgramQualificationStageThirteen(result).valid; }
export function getTrustProgramQualificationStageThirteenBundle(): TrustProgramQualificationBundle { const result = runTrustProgramQualificationStageThirteen(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, final_constitutional_qualification_gate: true, cata_authority_requires_qualified_decision: true, no_component_may_rely_before_qualification: true, immutable_evidence_required: true, deterministic_replay_required: true, no_high_or_critical_findings_allowed: true, qualification_gate: "Stage 13 Program Qualification Gate" }), result, validation: validateTrustProgramQualificationStageThirteen(result) }); }
export const TrustProgramQualificationStageThirteenService = Object.freeze({ run: runTrustProgramQualificationStageThirteen, validate: validateTrustProgramQualificationStageThirteen, replay: replayTrustProgramQualificationStageThirteen });
