import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runProvingSyntheticDataDigitalTwinGeneration, validateProvingSyntheticDataDigitalTwinGeneration } from "@/services/proving-synthetic-data-digital-twin-generation";
import type { SimulationFrameworkBundle, SimulationFrameworkFailure, SimulationFrameworkInput, SimulationFrameworkOutcome, SimulationFrameworkResult, SimulationFrameworkScenario, SimulationFrameworkValidation } from "@/types/proving-simulation-framework";

const VERSION = "proving-simulation-framework/v6.5" as const;
const IDENTIFIER = "ProvingSimulationFramework" as const;
const NOW = "2026-07-19T00:00:00.000Z";
let syntheticBaseline: ReturnType<typeof runProvingSyntheticDataDigitalTwinGeneration> | undefined;
function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly SimulationFrameworkFailure[], failure: SimulationFrameworkFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: SimulationFrameworkScenario): SimulationFrameworkFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function outcome(failures: readonly SimulationFrameworkFailure[]): SimulationFrameworkOutcome { return has(failures, "GOVERNANCE_REVIEW_REQUIRED") ? "REQUIRES_GOVERNANCE_REVIEW" : failures.length ? "FAIL" : "PASS"; }
function resultReplayHash(result: Omit<SimulationFrameworkResult, "replay_hash" | "integrity_hash">): string { return hash({ architecture: result.architecture.integrity_hash, simulation: result.simulation.integrity_hash, execution: result.execution.integrity_hash, engine: result.engine.integrity_hash, services: result.runtime_services.integrity_hash, state: result.state_registry.integrity_hash, failure: result.failure_injection.integrity_hash, metrics: result.metrics.integrity_hash, report: result.report.integrity_hash, evidence: result.evidence.integrity_hash, gates: result.gates.integrity_hash, boundaries: result.boundaries.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<SimulationFrameworkResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.readiness.outcome, replay_hash: result.replay_hash }); }

export function runProvingSimulationFramework(input: SimulationFrameworkInput = {}): SimulationFrameworkResult {
  const direct = scenarioFailure(input.scenario ?? "BASELINE");
  const scenarioFailures = freezeArray<SimulationFrameworkFailure>(direct ? [direct] : []);
  syntheticBaseline ??= runProvingSyntheticDataDigitalTwinGeneration();
  const dependencyFailures = freezeArray<SimulationFrameworkFailure>(!validateProvingSyntheticDataDigitalTwinGeneration(syntheticBaseline).valid || has(scenarioFailures, "P6_4_SYNTHETIC_GENERATION_INVALID") ? ["P6_4_SYNTHETIC_GENERATION_INVALID"] : []);
  const failures = freezeArray([...new Set([...scenarioFailures, ...dependencyFailures])]);
  const seed = input.seed ?? "seed:p6.5:simulation";
  const architectureOk = !has(failures, "SIMULATION_ARCHITECTURE_MISSING");
  const engineOk = !has(failures, "DETERMINISTIC_ENGINE_MISSING") && !has(failures, "DETERMINISTIC_EXECUTION_FAILED");
  const eventOk = !has(failures, "EVENT_SIMULATION_MISSING") && !has(failures, "EVENT_ORDER_NONDETERMINISTIC");
  const operationalOk = !has(failures, "OPERATIONAL_SIMULATION_MISSING");
  const missionOk = !has(failures, "MISSION_SIMULATION_MISSING");
  const replayOk = !has(failures, "REPLAY_SIMULATION_MISSING") && !has(failures, "REPLAY_FIDELITY_FAILED");
  const timeOk = !has(failures, "TIME_SERVICE_MISSING") && !has(failures, "TIME_NONDETERMINISTIC") && !has(failures, "VIRTUAL_TIME_NONDETERMINISTIC");
  const schedulerOk = !has(failures, "SCHEDULER_SERVICE_MISSING") && !has(failures, "SCHEDULER_DECISION_NONDETERMINISTIC");
  const stateOk = !has(failures, "STATE_REGISTRY_MISSING") && !has(failures, "STATE_RECOVERY_FAILED") && !has(failures, "STATE_TRANSITION_NONDETERMINISTIC");
  const failureOk = !has(failures, "FAILURE_INJECTION_MISSING");
  const metricsOk = !has(failures, "METRICS_COLLECTION_MISSING");
  const reportOk = !has(failures, "SIMULATION_REPORTING_MISSING");
  const evidenceOk = !has(failures, "EVIDENCE_GENERATION_MISSING") && !has(failures, "EVIDENCE_INCOMPLETE") && !has(failures, "GENERATED_EVIDENCE_NONDETERMINISTIC");
  const isolationOk = !has(failures, "SIMULATION_ISOLATION_FAILED") && !has(failures, "PRODUCTION_TENANT_MODIFIED") && !has(failures, "PRODUCTION_IDENTITY_MODIFIED") && !has(failures, "PRODUCTION_REGISTRY_MODIFIED") && !has(failures, "PRODUCTION_EVIDENCE_MODIFIED") && !has(failures, "PRODUCTION_TRUST_DECISION_MODIFIED") && !has(failures, "LIVE_OPERATIONAL_EXECUTION_ATTEMPTED");
  const deterministicOk = engineOk && eventOk && schedulerOk && timeOk && !has(failures, "EXECUTION_ORDER_NONDETERMINISTIC") && !has(failures, "SERVICE_INTERACTION_NONDETERMINISTIC");
  const architecture = nested({ architecture_id: "architecture:p6.5:simulation", simulation_services: architectureOk, simulation_lifecycle: architectureOk, execution_topology: architectureOk, orchestration: architectureOk, execution_pipelines: architectureOk, service_model: architectureOk, execution_model: architectureOk, isolated_proving_only: isolationOk });
  const simulation = nested({ simulation_id: "simulation:p6.5:canonical", simulation_type: "DETERMINISTIC" as const, scenario_id: syntheticBaseline.composition.scenarios[0] ?? "scenario:p6.5", environment_id: syntheticBaseline.composition.environment_id, digital_twin_id: syntheticBaseline.digital_twins.twin_id, mission_id: syntheticBaseline.missions.catalog_id, status: "COMPLETED" as const, configuration: "config:p6.5:deterministic", seed, created_time: NOW });
  const executionOrder = deterministicOk ? freezeArray(["load-inputs", "initialize-state", "process-events", "collect-metrics", "emit-evidence"]) : freezeArray(["load-inputs", "process-events", "initialize-state"]);
  const eventOrder = eventOk ? freezeArray(["event:tenant", "event:mission", "event:infrastructure", "event:evidence"]) : freezeArray(["event:mission", "event:tenant"]);
  const virtualTime = timeOk ? freezeArray([0, 10, 20, 30, 40]) : freezeArray([0, 7, 19, 41]);
  const execution = nested({ execution_id: "execution:p6.5:canonical", simulation_id: simulation.simulation_id, start_time: NOW, end_time: "2026-07-19T00:05:00.000Z", engine_version: "simulation-engine/v6.5", scheduler_version: "scheduler/v6.5", dataset_version: "synthetic-data:p6.4:catalog@1", result: deterministicOk && isolationOk ? "SUCCESS" as const : "FAILED" as const, replay_id: replayOk ? "replay:p6.5:canonical" : "", execution_order: executionOrder, event_order: eventOrder, scheduler_decisions: schedulerOk ? freezeArray(["priority:mission", "queue:event", "checkpoint:state"]) : freezeArray<string>([]), virtual_time_progression: virtualTime, service_interactions: !has(failures, "SERVICE_INTERACTION_NONDETERMINISTIC") ? freezeArray(["policy-service", "evidence-service", "replay-service"]) : freezeArray(["evidence-service", "policy-service"]), state_transitions: stateOk ? freezeArray(["DEFINED", "CONFIGURED", "VALIDATED", "READY", "EXECUTING", "COMPLETED"]) : freezeArray<string>([]), generated_evidence: evidenceOk ? freezeArray(["evidence:p6.5:simulation"]) : freezeArray<string>([]) });
  const engine = nested({ engine_id: engineOk ? "engine:p6.5:deterministic" : "", deterministic_scheduler: schedulerOk, execution_ordering: deterministicOk, deterministic_clocks: timeOk, deterministic_event_processing: eventOk, repeatable_execution: deterministicOk, event_simulation: eventOk, operational_simulation: operationalOk, mission_simulation: missionOk, replay_simulation: replayOk });
  const runtime_services = nested({ services_id: "services:p6.5:runtime", time_service: timeOk, scheduler_service: schedulerOk, state_registry: stateOk, failure_injection: failureOk, metrics_collection: metricsOk, reporting: reportOk, evidence_generation: evidenceOk });
  const state_registry = nested({ registry_id: stateOk ? "state:p6.5:registry" : "", simulation_state: stateOk, checkpoints: stateOk ? freezeArray(["checkpoint:p6.5:initial", "checkpoint:p6.5:post-events"]) : freezeArray<string>([]), snapshots: stateOk ? freezeArray(["snapshot:p6.5:complete"]) : freezeArray<string>([]), rollback_points: stateOk ? freezeArray(["rollback:p6.5:pre-failure"]) : freezeArray<string>([]), restoration_reproducible: stateOk });
  const failure_injection = nested({ library_id: failureOk ? "failure-injection:p6.5" : "", infrastructure_faults: failureOk, service_failures: failureOk, network_failures: failureOk, resource_exhaustion: failureOk, dependency_failures: failureOk, controlled: failureOk });
  const metrics = nested({ metrics_id: metricsOk ? "metrics:p6.5" : "", latency: metricsOk ? 42 : 0, throughput: metricsOk ? 1200 : 0, resource_utilization: metricsOk ? 0.62 : 0, event_counts: metricsOk ? eventOrder.length : 0, execution_statistics: metricsOk ? freezeArray(["events:4", "checkpoints:2", "reports:1"]) : freezeArray<string>([]), deterministic: metricsOk && deterministicOk });
  const report = nested({ report_id: reportOk ? "report:p6.5:simulation" : "", execution_id: execution.execution_id, summary: reportOk ? "Deterministic isolated proving simulation completed." : "", metrics: metrics.metrics_id ? freezeArray([metrics.metrics_id]) : freezeArray<string>([]), findings: reportOk ? freezeArray(["no-divergence", "isolation-preserved", "evidence-complete"]) : freezeArray<string>([]), divergence_summary: replayOk ? "No replay divergence detected." : "Replay divergence detected.", recommendations: reportOk ? freezeArray(["promote evidence to validation framework"]) : freezeArray<string>([]) });
  const evidence = nested({ evidence_id: evidenceOk ? "evidence:p6.5:simulation" : "", execution_id: execution.execution_id, replay_hash: replayOk ? hash(execution) : "", environment_hash: hash(syntheticBaseline.composition), dataset_hash: hash(syntheticBaseline.datasets), digital_twin_hash: hash(syntheticBaseline.digital_twins), policy_hash: "policy-hash:p6.5", signature: evidenceOk ? "signature:p6.5:simulation" : "", scenario_ref: simulation.scenario_id, environment_ref: simulation.environment_id, digital_twin_ref: simulation.digital_twin_id, dataset_refs: freezeArray([syntheticBaseline.datasets.catalog_id]), software_versions: freezeArray([execution.engine_version, execution.scheduler_version]), timing_model: timeOk ? "virtual-time:v6.5" : "", random_seed: seed, configuration_ref: simulation.configuration, generated_events: eventOrder, outputs: evidenceOk ? freezeArray(["output:p6.5:simulation"]) : freezeArray<string>([]), metric_refs: metrics.metrics_id ? freezeArray([metrics.metrics_id]) : freezeArray<string>([]), report_refs: report.report_id ? freezeArray([report.report_id]) : freezeArray<string>([]), immutable: evidenceOk });
  const gates = nested({ gate_id: "P6.5-GATES", deterministic_execution: deterministicOk, replay_fidelity: replayOk && execution.replay_id.length > 0, simulation_isolation: isolationOk, evidence_completeness: evidenceOk && evidence.report_refs.length > 0 && evidence.generated_events.length > 0, time_determinism: timeOk && virtualTime.join(",") === "0,10,20,30,40", state_recovery: stateOk && state_registry.restoration_reproducible, passed: deterministicOk && replayOk && isolationOk && evidenceOk && timeOk && stateOk });
  const boundaries = nested({ boundary_id: "boundaries:p6.5", modifies_production_tenants: false as const, modifies_production_identities: false as const, modifies_production_registries: false as const, modifies_production_evidence: false as const, modifies_production_trust_decisions: false as const, performs_live_operational_execution: false as const });
  const derivedFailures = freezeArray([...new Set([...failures, ...(!architectureOk ? ["SIMULATION_ARCHITECTURE_MISSING" as const] : []), ...(!engineOk ? ["DETERMINISTIC_ENGINE_MISSING" as const] : []), ...(!eventOk ? ["EVENT_SIMULATION_MISSING" as const] : []), ...(!operationalOk ? ["OPERATIONAL_SIMULATION_MISSING" as const] : []), ...(!missionOk ? ["MISSION_SIMULATION_MISSING" as const] : []), ...(!replayOk ? ["REPLAY_SIMULATION_MISSING" as const] : []), ...(!timeOk ? ["TIME_SERVICE_MISSING" as const] : []), ...(!schedulerOk ? ["SCHEDULER_SERVICE_MISSING" as const] : []), ...(!stateOk ? ["STATE_REGISTRY_MISSING" as const] : []), ...(!failureOk ? ["FAILURE_INJECTION_MISSING" as const] : []), ...(!metricsOk ? ["METRICS_COLLECTION_MISSING" as const] : []), ...(!reportOk ? ["SIMULATION_REPORTING_MISSING" as const] : []), ...(!evidenceOk ? ["EVIDENCE_GENERATION_MISSING" as const] : []), ...(!isolationOk ? ["SIMULATION_ISOLATION_FAILED" as const] : []), ...(!gates.passed ? ["DETERMINISTIC_EXECUTION_FAILED" as const] : [])])]);
  const readiness = nested({ readiness_id: "P6.5-SIMULATION-FRAMEWORK-READINESS-001", outcome: outcome(derivedFailures), phase_ready: outcome(derivedFailures) === "PASS", architecture_ready: architectureOk, engine_ready: engineOk, event_ready: eventOk, operational_ready: operationalOk, mission_ready: missionOk, replay_ready: replayOk, time_ready: timeOk, scheduler_ready: schedulerOk, state_ready: stateOk, failure_injection_ready: failureOk, metrics_ready: metricsOk, reports_ready: reportOk, evidence_ready: evidenceOk, gates_passed: gates.passed, isolation_respected: isolationOk, failures: derivedFailures });
  const base: Omit<SimulationFrameworkResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, synthetic_generation_ref: "proving-synthetic-data-digital-twin-generation/v6.4", architecture, simulation, execution, engine, runtime_services, state_registry, failure_injection, metrics, report, evidence, gates, boundaries, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateProvingSimulationFramework(result?: SimulationFrameworkResult): SimulationFrameworkValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, architecture_valid: false, simulation_valid: false, execution_valid: false, engine_valid: false, services_valid: false, state_valid: false, failure_injection_valid: false, metrics_valid: false, report_valid: false, evidence_valid: false, gates_valid: false, boundaries_valid: false, readiness_valid: false, failures: freezeArray(["SIMULATION_ARCHITECTURE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const architecture_valid = verifyHashed(result.architecture) && result.architecture.isolated_proving_only && result.architecture.execution_pipelines;
  const simulation_valid = verifyHashed(result.simulation) && result.simulation.simulation_id.length > 0 && result.simulation.status === "COMPLETED" && result.simulation.seed.length > 0;
  const execution_valid = verifyHashed(result.execution) && result.execution.result === "SUCCESS" && result.execution.execution_order.length === 5 && result.execution.replay_id.length > 0;
  const engine_valid = verifyHashed(result.engine) && result.engine.deterministic_scheduler && result.engine.event_simulation && result.engine.operational_simulation && result.engine.mission_simulation && result.engine.replay_simulation;
  const services_valid = verifyHashed(result.runtime_services) && Object.entries(result.runtime_services).filter(([key, value]) => key !== "services_id" && key !== "integrity_hash" && value === false).length === 0;
  const state_valid = verifyHashed(result.state_registry) && result.state_registry.checkpoints.length > 0 && result.state_registry.restoration_reproducible;
  const failure_injection_valid = verifyHashed(result.failure_injection) && result.failure_injection.controlled && result.failure_injection.dependency_failures;
  const metrics_valid = verifyHashed(result.metrics) && result.metrics.deterministic && result.metrics.event_counts > 0;
  const report_valid = verifyHashed(result.report) && result.report.report_id.length > 0 && result.report.findings.length > 0;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.evidence_id.length > 0 && result.evidence.immutable && result.evidence.generated_events.length > 0 && result.evidence.report_refs.length > 0;
  const gates_valid = verifyHashed(result.gates) && result.gates.passed && result.gates.deterministic_execution && result.gates.replay_fidelity && result.gates.simulation_isolation && result.gates.evidence_completeness && result.gates.time_determinism && result.gates.state_recovery;
  const boundaries_valid = verifyHashed(result.boundaries) && !result.boundaries.modifies_production_tenants && !result.boundaries.modifies_production_trust_decisions && !result.boundaries.performs_live_operational_execution;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.outcome === "PASS" && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && architecture_valid && simulation_valid && execution_valid && engine_valid && services_valid && state_valid && failure_injection_valid && metrics_valid && report_valid && evidence_valid && gates_valid && boundaries_valid && readiness_valid;
  return nested({ valid, outcome: result.readiness.outcome, replay_hash_valid, integrity_hash_valid, architecture_valid, simulation_valid, execution_valid, engine_valid, services_valid, state_valid, failure_injection_valid, metrics_valid, report_valid, evidence_valid, gates_valid, boundaries_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayProvingSimulationFramework(result = runProvingSimulationFramework()): boolean { const replayed = runProvingSimulationFramework({ seed: result.simulation.seed }); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateProvingSimulationFramework(result).valid; }
export function getProvingSimulationFrameworkBundle(): SimulationFrameworkBundle { const result = runProvingSimulationFramework(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_deterministic_simulation: true, owns_event_simulation: true, owns_operational_simulation: true, owns_mission_simulation: true, owns_replay_simulation: true, performs_live_operational_execution: false, modifies_production_systems: false }), result, validation: validateProvingSimulationFramework(result) }); }
export const ProvingSimulationFrameworkService = Object.freeze({ run: runProvingSimulationFramework, validate: validateProvingSimulationFramework, replay: replayProvingSimulationFramework });
