import { randomUUID } from "node:crypto";
import { z } from "zod";
import { getSessionUser } from "@/src/lib/auth";
import { AppError } from "@/src/server/api/errors";
import { apiError, apiSuccess } from "@/src/server/api/response";
import { requireWorkspaceManager } from "@/src/server/auth/permissions";
import { PrismaLearningAuditLedger, PrismaStrategyRegistryRepository, StrategyCurriculumProposalService, StrategySelectionRecordService } from "@/services/learning-constitution";
import type { LearningObjectiveProfile, StrategySelectionRecord } from "@/types/learning-constitution";
export const dynamic = "force-dynamic";
const bodySchema = z.object({ selectionId: z.string().min(1).max(200), goal: z.string().min(1).max(1000) });
/** Proposes the Phase 40 handoff to the Curriculum Planner; approval and execution remain separate lifecycle operations. */
export async function POST(request: Request) { try { const user = await getSessionUser(); if (!user) throw new AppError(401, "unauthorized", "Authentication required."); if (!user.workspaceId || user.workspaceId === "default") throw new AppError(403, "workspace_required", "Workspace membership is required."); await requireWorkspaceManager({ userId: user.id, userRole: user.role, workspaceId: user.workspaceId }); const body = bodySchema.parse(await request.json()); const repository = new PrismaStrategyRegistryRepository(user.workspaceId); const artifacts = await repository.listWorkspaceArtifacts(); const selectionArtifact = artifacts.find((item) => item.artifactType === "PHASE40_SELECTION" && (item.payload as StrategySelectionRecord).selectionId === body.selectionId); if (!selectionArtifact) throw new AppError(404, "selection_not_found", "Strategy selection not found."); const selection = selectionArtifact.payload as StrategySelectionRecord; const objectiveArtifact = artifacts.find((item) => item.artifactType === "OBJECTIVE_PROFILE" && (item.payload as LearningObjectiveProfile).profileId === selection.objectiveProfileId); if (!objectiveArtifact) throw new AppError(409, "selection_lineage_incomplete", "Selection objective profile is unavailable."); const proposal = new StrategyCurriculumProposalService().propose({ proposalId: `SCP-${randomUUID()}`, selection, objective: objectiveArtifact.payload as LearningObjectiveProfile, goal: body.goal, createdAt: new Date().toISOString() }); const actor = { actorId: `human:${user.id}`, actorType: "HUMAN" as const }; await new StrategySelectionRecordService(repository, new PrismaLearningAuditLedger(user.workspaceId)).curriculumProposal(proposal, user.workspaceId, actor, `strategy-curriculum-proposal:${proposal.proposalId}`); return apiSuccess({ proposal, next: "Proposal recorded. Human approval must create the applicable Phase 26 proposal and Phase 28 lease before a curriculum can execute." }, { status: 201 }); } catch (error) { return apiError(error, "Unable to create a strategy curriculum proposal."); } }
