import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runConstitutionalComplianceGate, validateConstitutionalComplianceGate } from "@/services/trust-constitutional-compliance-gate";
import { runTrustCertificationStageEleven, validateTrustCertificationStageEleven } from "@/services/trust-certification-stage-eleven";
import { runTrustContinuousMonitoringStageEight, validateTrustContinuousMonitoringStageEight } from "@/services/trust-continuous-monitoring-stage-eight";
import { runTrustDriftDetectionStageNine, validateTrustDriftDetectionStageNine } from "@/services/trust-drift-detection-stage-nine";
import { runTrustExplainabilityStageSix, validateTrustExplainabilityStageSix } from "@/services/trust-explainability-stage-six";
import { runTrustFoundationStageOne, validateTrustFoundationStageOne } from "@/services/trust-foundation-stage-one";
import { runTrustHumanOversightStageSeven, validateTrustHumanOversightStageSeven } from "@/services/trust-human-oversight-stage-seven";
import { runTrustIndependentEvaluation, validateTrustIndependentEvaluation } from "@/services/trust-independent-evaluation";
import { runTrustRecoveryRevocationStageTen, validateTrustRecoveryRevocationStageTen } from "@/services/trust-recovery-revocation-stage-ten";
import { runTrustRegistryDomains, validateTrustRegistryDomains } from "@/services/trust-registry-domains";
import { runTrustResolutionEngine, validateTrustResolutionEngine } from "@/services/trust-resolution-engine";
import type { FederationExchange, FederationRelationship, TrustFederationBundle, TrustFederationDecision, TrustFederationFailure, TrustFederationInput, TrustFederationResult, TrustFederationScenario, TrustFederationValidation } from "@/types/trust-federation-stage-twelve";

const VERSION = "trust-federation-stage-twelve/stage-12" as const;
const IDENTIFIER = "TrustFederationStageTwelve" as const;
const RELATIONSHIPS = Object.freeze<FederationRelationship[]>(["TENANT", "ORGANIZATION", "ECOSYSTEM"]);
const EXCHANGES = Object.freeze<FederationExchange[]>(["TRUST_ASSERTION", "EVIDENCE_PACKAGE", "CERTIFICATION_RECORD", "REVOCATION_NOTICE", "MONITORING_SIGNAL"]);
const UPSTREAM_REFS = Object.freeze(["trust-foundation-stage-one/stage-1", "trust-constitutional-compliance-gate/stage-2", "trust-registry-domains/stage-3", "trust-independent-evaluation/stage-4", "trust-resolution-engine/stage-5", "trust-explainability-stage-six/stage-6", "trust-human-oversight-stage-seven/stage-7", "trust-continuous-monitoring-stage-eight/stage-8", "trust-drift-detection-stage-nine/stage-9", "trust-recovery-revocation-stage-ten/stage-10", "trust-certification-stage-eleven/stage-11"]);
const PROVIDES = Object.freeze(["trust-federation-service", "cross-tenant-verification-engine", "federation-policy-engine", "boundary-enforcement-engine", "federation-monitoring-service", "federation-evidence-service", "federation-registry"]);
let baselines: ReturnType<typeof makeBaselines> | undefined;

function makeBaselines() { return { foundation: runTrustFoundationStageOne(), gate: runConstitutionalComplianceGate(), registry: runTrustRegistryDomains(), evaluation: runTrustIndependentEvaluation(), resolution: runTrustResolutionEngine(), explainability: runTrustExplainabilityStageSix(), oversight: runTrustHumanOversightStageSeven(), monitoring: runTrustContinuousMonitoringStageEight(), drift: runTrustDriftDetectionStageNine(), recovery: runTrustRecoveryRevocationStageTen(), certification: runTrustCertificationStageEleven() }; }
function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly TrustFederationFailure[], failure: TrustFederationFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustFederationScenario): TrustFederationFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly TrustFederationFailure[], scenario?: TrustFederationScenario): TrustFederationDecision {
  const failClosed = new Set<TrustFederationFailure>(["STAGE_1_TRUST_FOUNDATION_INVALID", "STAGE_2_CONSTITUTIONAL_GATE_INVALID", "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID", "STAGE_4_INDEPENDENT_EVALUATION_INVALID", "STAGE_5_TRUST_RESOLUTION_INVALID", "STAGE_6_EXPLAINABILITY_INVALID", "STAGE_7_HUMAN_OVERSIGHT_INVALID", "STAGE_8_CONTINUOUS_MONITORING_INVALID", "STAGE_9_DRIFT_DETECTION_INVALID", "STAGE_10_RECOVERY_REVOCATION_INVALID", "STAGE_11_TRUST_CERTIFICATION_INVALID", "FEDERATION_BYPASSED_CONSTITUTIONAL_EVALUATION", "REMOTE_ASSERTION_TREATED_AS_DECISION", "TENANT_ISOLATION_COMPROMISED", "UNAUTHORIZED_TRUST_PROPAGATION", "TENANT_DATA_LEAKAGE", "POLICY_BYPASS", "AUTHORITY_INHERITANCE_ALLOWED", "STANDING_INHERITANCE_ALLOWED", "FEDERATION_EVIDENCE_MUTABLE", "FEDERATION_REPLAY_DIVERGED"]);
  if (failures.some((failure) => failClosed.has(failure))) return "FAIL_CLOSED";
  if (has(failures, "TRUST_FEDERATION_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP" || scenario === "QUALIFIED_WITH_OBSERVATIONS") return "CONDITIONALLY_QUALIFIED";
  return "TRUST_FEDERATION_QUALIFIED";
}
function resultReplayHash(result: Omit<TrustFederationResult, "replay_hash" | "integrity_hash">): string { return hash({ contracts: result.contracts.integrity_hash, verification: result.verification.integrity_hash, evidence: result.evidence.integrity_hash, policies: result.policies.integrity_hash, boundary: result.boundary.integrity_hash, monitoring: result.monitoring.integrity_hash, registry: result.registry.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<TrustFederationResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runTrustFederationStageTwelve(input: TrustFederationInput = {}): TrustFederationResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  const scenarioFailures = freezeArray<TrustFederationFailure>(direct ? [direct] : []);
  baselines ??= makeBaselines();
  const failures = freezeArray([...new Set([...scenarioFailures, ...(!validateTrustFoundationStageOne(baselines.foundation).valid ? ["STAGE_1_TRUST_FOUNDATION_INVALID" as const] : []), ...(!validateConstitutionalComplianceGate(baselines.gate).valid ? ["STAGE_2_CONSTITUTIONAL_GATE_INVALID" as const] : []), ...(!validateTrustRegistryDomains(baselines.registry).valid ? ["STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" as const] : []), ...(!validateTrustIndependentEvaluation(baselines.evaluation).valid ? ["STAGE_4_INDEPENDENT_EVALUATION_INVALID" as const] : []), ...(!validateTrustResolutionEngine(baselines.resolution).valid ? ["STAGE_5_TRUST_RESOLUTION_INVALID" as const] : []), ...(!validateTrustExplainabilityStageSix(baselines.explainability).valid ? ["STAGE_6_EXPLAINABILITY_INVALID" as const] : []), ...(!validateTrustHumanOversightStageSeven(baselines.oversight).valid ? ["STAGE_7_HUMAN_OVERSIGHT_INVALID" as const] : []), ...(!validateTrustContinuousMonitoringStageEight(baselines.monitoring).valid ? ["STAGE_8_CONTINUOUS_MONITORING_INVALID" as const] : []), ...(!validateTrustDriftDetectionStageNine(baselines.drift).valid ? ["STAGE_9_DRIFT_DETECTION_INVALID" as const] : []), ...(!validateTrustRecoveryRevocationStageTen(baselines.recovery).valid ? ["STAGE_10_RECOVERY_REVOCATION_INVALID" as const] : []), ...(!validateTrustCertificationStageEleven(baselines.certification).valid ? ["STAGE_11_TRUST_CERTIFICATION_INVALID" as const] : [])])]);
  const contractsOk = !has(failures, "FEDERATION_CONTRACT_MODEL_MISSING") && !has(failures, "TRUST_EXCHANGE_CONTRACTS_MISSING") && !has(failures, "FEDERATION_PROTOCOLS_MISSING") && !has(failures, "TRUST_ASSERTION_CONTRACTS_MISSING") && !has(failures, "EVIDENCE_EXCHANGE_CONTRACTS_MISSING") && !has(failures, "CONTRACT_VERSIONING_MISSING") && !has(failures, "COMPATIBILITY_RULES_MISSING") && !has(failures, "CAPABILITY_NEGOTIATION_MISSING") && !has(failures, "CONTRACT_VALIDATION_MISSING") && !has(failures, "CONTRACT_GOVERNANCE_MISSING");
  const verificationOk = !has(failures, "REMOTE_TRUST_VERIFICATION_MISSING") && !has(failures, "TRUST_ASSERTION_VALIDATION_MISSING") && !has(failures, "IDENTITY_VERIFICATION_MISSING") && !has(failures, "EVIDENCE_VERIFICATION_MISSING") && !has(failures, "SIGNATURE_VALIDATION_MISSING") && !has(failures, "CERTIFICATE_VALIDATION_MISSING") && !has(failures, "STANDING_VERIFICATION_MISSING") && !has(failures, "RESTRICTION_VERIFICATION_MISSING") && !has(failures, "TRUST_FRESHNESS_VALIDATION_MISSING") && !has(failures, "VERIFICATION_REPLAY_MISSING") && !has(failures, "REMOTE_ASSERTION_TREATED_AS_DECISION");
  const evidenceOk = !has(failures, "FEDERATION_EVIDENCE_CAPTURE_MISSING") && !has(failures, "TRUST_EXCHANGE_EVIDENCE_MISSING") && !has(failures, "VERIFICATION_EVIDENCE_MISSING") && !has(failures, "CONTRACT_EVIDENCE_MISSING") && !has(failures, "BOUNDARY_EVIDENCE_MISSING") && !has(failures, "FEDERATION_AUDIT_RECORDS_MISSING") && !has(failures, "REPLAY_EVIDENCE_MISSING") && !has(failures, "SIGNATURE_EVIDENCE_MISSING") && !has(failures, "EVIDENCE_PACKAGING_MISSING") && !has(failures, "EVIDENCE_LINEAGE_MISSING") && !has(failures, "FEDERATION_EVIDENCE_MUTABLE");
  const policiesOk = !has(failures, "FEDERATION_AUTHORIZATION_POLICIES_MISSING") && !has(failures, "ALLOWED_RELATIONSHIPS_MISSING") && !has(failures, "RESTRICTED_RELATIONSHIPS_MISSING") && !has(failures, "TRUST_IMPORT_POLICIES_MISSING") && !has(failures, "TRUST_EXPORT_POLICIES_MISSING") && !has(failures, "POLICY_VERSIONING_MISSING") && !has(failures, "FEDERATION_APPROVAL_RULES_MISSING") && !has(failures, "FEDERATION_REVOCATION_POLICIES_MISSING") && !has(failures, "FEDERATION_GOVERNANCE_RULES_MISSING") && !has(failures, "POLICY_VALIDATION_MISSING") && !has(failures, "POLICY_BYPASS");
  const boundaryOk = !has(failures, "TENANT_BOUNDARY_ENFORCEMENT_MISSING") && !has(failures, "DOMAIN_ISOLATION_MISSING") && !has(failures, "ORGANIZATIONAL_ISOLATION_MISSING") && !has(failures, "TRUST_BOUNDARY_VALIDATION_MISSING") && !has(failures, "UNAUTHORIZED_ACCESS_PREVENTION_MISSING") && !has(failures, "FEDERATION_RESTRICTIONS_MISSING") && !has(failures, "DATA_ISOLATION_MISSING") && !has(failures, "CROSS_BOUNDARY_VALIDATION_MISSING") && !has(failures, "FAIL_CLOSED_ENFORCEMENT_MISSING") && !has(failures, "BOUNDARY_AUDITING_MISSING") && !has(failures, "TENANT_ISOLATION_COMPROMISED") && !has(failures, "UNAUTHORIZED_TRUST_PROPAGATION") && !has(failures, "TENANT_DATA_LEAKAGE") && !has(failures, "AUTHORITY_INHERITANCE_ALLOWED") && !has(failures, "STANDING_INHERITANCE_ALLOWED");
  const monitoringOk = !has(failures, "FEDERATION_HEALTH_MONITORING_MISSING") && !has(failures, "CONTRACT_MONITORING_MISSING") && !has(failures, "VERIFICATION_MONITORING_MISSING") && !has(failures, "FEDERATION_PERFORMANCE_MISSING") && !has(failures, "FEDERATION_ERRORS_MISSING") && !has(failures, "FEDERATION_DRIFT_DETECTION_MISSING") && !has(failures, "CONTRACT_EXPIRATION_MONITORING_MISSING") && !has(failures, "POLICY_COMPLIANCE_MONITORING_MISSING") && !has(failures, "FEDERATION_ALERTS_MISSING") && !has(failures, "FEDERATION_METRICS_MISSING");
  const governanceOk = !has(failures, "FEDERATION_BYPASSED_CONSTITUTIONAL_EVALUATION");
  const replayOk = !has(failures, "FEDERATION_REPLAY_DIVERGED");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "TRUST_FEDERATION_QUALIFIED";
  const tenant_id = input.tenant_id ?? baselines.certification.tenant_id;
  const federation_id = input.federation_id ?? `trust-federation:stage-12:${input.seed ?? "canonical"}`;
  const contracts = nested({ contract_id: contractsOk ? "contracts:stage-12:federation" : "", federation_contract_model: contractsOk, trust_exchange_contracts: contractsOk, federation_protocol_definitions: contractsOk, trust_assertion_contracts: contractsOk, evidence_exchange_contracts: contractsOk, contract_versioning: contractsOk, compatibility_rules: contractsOk, capability_negotiation: contractsOk, contract_validation: contractsOk, contract_governance: contractsOk });
  const verification = nested({ verification_id: verificationOk ? "verification:stage-12:cross-tenant" : "", remote_trust_verification: verificationOk, trust_assertion_validation: verificationOk, identity_verification: verificationOk, evidence_verification: verificationOk, signature_validation: verificationOk, certificate_validation: verificationOk, standing_verification: verificationOk, restriction_verification: verificationOk, trust_freshness_validation: verificationOk, replay_validation: verificationOk && replayOk, remote_assertions_are_evidence_only: verificationOk, local_evaluation_required: verificationOk && governanceOk });
  const evidence = nested({ evidence_id: evidenceOk ? "evidence:stage-12:federation" : "", federation_evidence_capture: evidenceOk, trust_exchange_evidence: evidenceOk, verification_evidence: evidenceOk, contract_evidence: evidenceOk, boundary_evidence: evidenceOk, federation_audit_records: evidenceOk, replay_evidence: evidenceOk && replayOk, signature_evidence: evidenceOk, evidence_packaging: evidenceOk, evidence_lineage: evidenceOk, immutable: evidenceOk });
  const policies = nested({ policy_id: policiesOk ? "policies:stage-12:federation" : "", federation_authorization_policies: policiesOk, allowed_relationships: policiesOk, restricted_relationships: policiesOk, trust_import_policies: policiesOk, trust_export_policies: policiesOk, policy_versioning: policiesOk, federation_approval_rules: policiesOk, federation_revocation_policies: policiesOk, federation_governance_rules: policiesOk, policy_validation: policiesOk, governs_every_exchange: policiesOk });
  const boundary = nested({ boundary_id: boundaryOk ? "boundary:stage-12:federation" : "", tenant_boundary_enforcement: boundaryOk, domain_isolation: boundaryOk, organizational_isolation: boundaryOk, trust_boundary_validation: boundaryOk, unauthorized_access_prevention: boundaryOk, federation_restrictions: boundaryOk, data_isolation: boundaryOk, cross_boundary_validation: boundaryOk, fail_closed_enforcement: boundaryOk, boundary_auditing: boundaryOk, tenant_sovereignty_preserved: boundaryOk });
  const monitoring = nested({ monitoring_id: monitoringOk ? "monitoring:stage-12:federation" : "", federation_health_monitoring: monitoringOk, contract_monitoring: monitoringOk, verification_monitoring: monitoringOk, federation_performance: monitoringOk, federation_errors: monitoringOk, trust_drift_detection: monitoringOk, contract_expiration_monitoring: monitoringOk, policy_compliance_monitoring: monitoringOk, federation_alerts: monitoringOk, federation_metrics: monitoringOk, deterministic_alerts: monitoringOk });
  const registry = nested({ registry_id: "registry:stage-12:federation", federation_registry: contractsOk && policiesOk, federation_contract_registry: contractsOk, federation_policy_registry: policiesOk, verification_registry: verificationOk, federation_evidence_registry: evidenceOk, relationship_types: freezeArray(RELATIONSHIPS), exchange_types: freezeArray(EXCHANGES), searchable: contractsOk && policiesOk, replayable: replayOk, lineage_aware: evidenceOk });
  const readiness = nested({ readiness_id: "STAGE-12-TRUST-FEDERATION-READINESS-001", decision, phase_ready: qualified, upstream_ready: failures.every((failure) => !failure.startsWith("STAGE_")), contracts_ready: contractsOk, verification_ready: verificationOk, evidence_ready: evidenceOk, policies_ready: policiesOk, boundary_ready: boundaryOk, monitoring_ready: monitoringOk, registry_ready: contractsOk && policiesOk && verificationOk && evidenceOk, constitutional_supremacy: governanceOk, tenant_sovereignty: boundaryOk, independent_evaluation: verificationOk, least_trust: policiesOk, boundary_preservation: boundaryOk, deterministic_federation: replayOk && verificationOk, immutable_evidence: evidenceOk, fail_closed: boundaryOk && policiesOk, certification_ready: contractsOk && verificationOk && evidenceOk && policiesOk && boundaryOk && monitoringOk && replayOk, failures });
  const base: Omit<TrustFederationResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id, federation_id, contracts, verification, evidence, policies, boundary, monitoring, registry, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustFederationStageTwelve(result?: TrustFederationResult): TrustFederationValidation {
  if (!result) return nested({ valid: false, decision: "FAIL_CLOSED" as const, replay_hash_valid: false, integrity_hash_valid: false, contracts_valid: false, verification_valid: false, evidence_valid: false, policies_valid: false, boundary_valid: false, monitoring_valid: false, registry_valid: false, readiness_valid: false, failures: freezeArray(["FEDERATION_CONTRACT_MODEL_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const contracts_valid = verifyHashed(result.contracts) && result.contracts.federation_contract_model && result.contracts.contract_validation && result.contracts.contract_governance;
  const verification_valid = verifyHashed(result.verification) && result.verification.remote_trust_verification && result.verification.identity_verification && result.verification.evidence_verification && result.verification.remote_assertions_are_evidence_only && result.verification.local_evaluation_required;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.federation_evidence_capture && result.evidence.verification_evidence && result.evidence.evidence_lineage && result.evidence.immutable;
  const policies_valid = verifyHashed(result.policies) && result.policies.federation_authorization_policies && result.policies.trust_import_policies && result.policies.trust_export_policies && result.policies.governs_every_exchange;
  const boundary_valid = verifyHashed(result.boundary) && result.boundary.tenant_boundary_enforcement && result.boundary.data_isolation && result.boundary.fail_closed_enforcement && result.boundary.tenant_sovereignty_preserved;
  const monitoring_valid = verifyHashed(result.monitoring) && result.monitoring.federation_health_monitoring && result.monitoring.policy_compliance_monitoring && result.monitoring.federation_alerts && result.monitoring.deterministic_alerts;
  const registry_valid = verifyHashed(result.registry) && result.registry.relationship_types.length === 3 && result.registry.exchange_types.length === 5 && result.registry.replayable && result.registry.lineage_aware;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.constitutional_supremacy && result.readiness.tenant_sovereignty && result.readiness.independent_evaluation && result.readiness.least_trust && result.readiness.boundary_preservation && result.readiness.deterministic_federation && result.readiness.immutable_evidence && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && contracts_valid && verification_valid && evidence_valid && policies_valid && boundary_valid && monitoring_valid && registry_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, contracts_valid, verification_valid, evidence_valid, policies_valid, boundary_valid, monitoring_valid, registry_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayTrustFederationStageTwelve(result = runTrustFederationStageTwelve()): boolean { const replayed = runTrustFederationStageTwelve(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustFederationStageTwelve(result).valid; }
export function getTrustFederationStageTwelveBundle(): TrustFederationBundle { const result = runTrustFederationStageTwelve(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, constitutional_supremacy: true, tenant_sovereignty_required: true, remote_assertions_are_evidence_not_decisions: true, least_trust_required: true, tenant_isolation_required: true, deterministic_replay_required: true, qualification_gate: "Stage 12 Trust Federation Qualification Gate" }), result, validation: validateTrustFederationStageTwelve(result) }); }
export const TrustFederationStageTwelveService = Object.freeze({ run: runTrustFederationStageTwelve, validate: validateTrustFederationStageTwelve, replay: replayTrustFederationStageTwelve });
