substitutions:
  _REGION: us-east1
  _REPOSITORY: nuru
  _SERVICE: nuru

steps:
  - id: build-web
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=Dockerfile.staging
      - --target=web
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
      - .

  - id: build-migrations
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=Dockerfile.staging
      - --target=migrate
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}-migrate:$BUILD_ID
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}-migrate:$BUILD_ID
