export const STARTUP_ERROR_CODES = {
  ENV_DATABASE_URL_MISSING: "ENV_DATABASE_URL_MISSING",
  ENV_NODE_ENV_INVALID: "ENV_NODE_ENV_INVALID",
  ENV_TENANT_MODE_INVALID: "ENV_TENANT_MODE_INVALID",
  ENV_LOCK_LEASE_INVALID: "ENV_LOCK_LEASE_INVALID",
  ENV_BACKUP_PATH_REQUIRED: "ENV_BACKUP_PATH_REQUIRED",
  ENV_AUTH_SECRET_INVALID: "ENV_AUTH_SECRET_INVALID",
  ENV_SECURITY_MODE_DISABLED: "ENV_SECURITY_MODE_DISABLED",
  ENV_ADMIN_SECRET_UNSAFE: "ENV_ADMIN_SECRET_UNSAFE",
  ENV_UNKNOWN_KEY: "ENV_UNKNOWN_KEY",
  STARTUP_DB_UNREACHABLE: "STARTUP_DB_UNREACHABLE",
  STARTUP_MIGRATION_INCOMPATIBLE: "STARTUP_MIGRATION_INCOMPATIBLE",
  STARTUP_OBSERVABILITY_UNAVAILABLE: "STARTUP_OBSERVABILITY_UNAVAILABLE",
  STARTUP_CONTINUITY_UNVERIFIED: "STARTUP_CONTINUITY_UNVERIFIED",
  STARTUP_RESTORE_SIMULATION_FAILED: "STARTUP_RESTORE_SIMULATION_FAILED",
  STARTUP_SNAPSHOT_INVALID: "STARTUP_SNAPSHOT_INVALID",
  STARTUP_LEDGER_CONTINUITY_FAILED: "STARTUP_LEDGER_CONTINUITY_FAILED",
  STARTUP_REPLAY_UNCERTAIN: "STARTUP_REPLAY_UNCERTAIN",
  STARTUP_TENANT_CONTINUITY_MISMATCH: "STARTUP_TENANT_CONTINUITY_MISMATCH",
  STARTUP_RECOVERY_READINESS_DENIED: "STARTUP_RECOVERY_READINESS_DENIED",
} as const;

export type StartupErrorCode = (typeof STARTUP_ERROR_CODES)[keyof typeof STARTUP_ERROR_CODES];
