import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runConstitutionalComplianceGate, validateConstitutionalComplianceGate } from "@/services/trust-constitutional-compliance-gate";
import { runTrustExplainabilityStageSix, validateTrustExplainabilityStageSix } from "@/services/trust-explainability-stage-six";
import { runTrustFoundationStageOne, validateTrustFoundationStageOne } from "@/services/trust-foundation-stage-one";
import { runTrustIndependentEvaluation, validateTrustIndependentEvaluation } from "@/services/trust-independent-evaluation";
import { runTrustRegistryDomains, validateTrustRegistryDomains } from "@/services/trust-registry-domains";
import { runTrustResolutionEngine, validateTrustResolutionEngine } from "@/services/trust-resolution-engine";
import type { OversightDisposition, OversightLifecycleState, TrustHumanOversightBundle, TrustHumanOversightDecision, TrustHumanOversightFailure, TrustHumanOversightInput, TrustHumanOversightResult, TrustHumanOversightScenario, TrustHumanOversightValidation } from "@/types/trust-human-oversight-stage-seven";

const VERSION = "trust-human-oversight-stage-seven/stage-7" as const;
const IDENTIFIER = "TrustHumanOversightStageSeven" as const;
const STATES = Object.freeze<OversightLifecycleState[]>(["PENDING", "UNDER_REVIEW", "INFORMATION_REQUESTED", "RESOLVED", "CANCELLED", "SUPERSEDED"]);
const DISPOSITIONS = Object.freeze<OversightDisposition[]>(["ALLOW", "ALLOW_WITH_RESTRICTIONS", "DENY", "CANCELLED", "SUPERSEDED"]);
const UPSTREAM_REFS = Object.freeze(["trust-foundation-stage-one/stage-1", "trust-constitutional-compliance-gate/stage-2", "trust-registry-domains/stage-3", "trust-independent-evaluation/stage-4", "trust-resolution-engine/stage-5", "trust-explainability-stage-six/stage-6"]);
const PROVIDES = Object.freeze(["oversight-decisions", "oversight-evidence", "decision-lineage", "review-lifecycle-events", "trust-decision-records", "certification-evidence"]);
let baselines: ReturnType<typeof makeBaselines> | undefined;

function makeBaselines() { return { foundation: runTrustFoundationStageOne(), gate: runConstitutionalComplianceGate(), registry: runTrustRegistryDomains(), evaluation: runTrustIndependentEvaluation(), resolution: runTrustResolutionEngine(), explainability: runTrustExplainabilityStageSix() }; }
function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly TrustHumanOversightFailure[], failure: TrustHumanOversightFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustHumanOversightScenario): TrustHumanOversightFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly TrustHumanOversightFailure[], scenario?: TrustHumanOversightScenario): TrustHumanOversightDecision {
  const failClosed = new Set<TrustHumanOversightFailure>(["STAGE_1_TRUST_FOUNDATION_INVALID", "STAGE_2_CONSTITUTIONAL_GATE_INVALID", "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID", "STAGE_4_INDEPENDENT_EVALUATION_INVALID", "STAGE_5_TRUST_RESOLUTION_INVALID", "STAGE_6_EXPLAINABILITY_INVALID", "MULTIPLE_QUEUES_ASSIGNED", "INVALID_LIFECYCLE_STATE_ALLOWED", "DECISION_RECORD_MUTABLE", "CONSTITUTIONAL_DENY_OVERRIDDEN", "FAIL_CLOSED_OVERRIDDEN", "RESTRICTIONS_BYPASSED", "EVIDENCE_HASH_INVALID", "LINEAGE_NOT_TRACEABLE", "OVERSIGHT_BYPASSED_AUTOMATED_EVALUATION", "HISTORICAL_DECISION_REWRITTEN", "EVIDENCE_REMOVED"]);
  if (failures.some((failure) => failClosed.has(failure))) return "FAIL_CLOSED";
  if (has(failures, "HUMAN_OVERSIGHT_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP" || scenario === "QUALIFIED_WITH_OBSERVATIONS") return "CONDITIONALLY_QUALIFIED";
  return "HUMAN_OVERSIGHT_QUALIFIED";
}
function resultReplayHash(result: Omit<TrustHumanOversightResult, "replay_hash" | "integrity_hash">): string { return hash({ queue: result.queue.integrity_hash, workflow: result.workflow.integrity_hash, lifecycle: result.lifecycle.integrity_hash, decision_record: result.decision_record.integrity_hash, resolution: result.resolution.integrity_hash, evidence: result.evidence.integrity_hash, lineage: result.lineage.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<TrustHumanOversightResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runTrustHumanOversightStageSeven(input: TrustHumanOversightInput = {}): TrustHumanOversightResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  const scenarioFailures = freezeArray<TrustHumanOversightFailure>(direct ? [direct] : []);
  baselines ??= makeBaselines();
  const failures = freezeArray([...new Set([...scenarioFailures, ...(!validateTrustFoundationStageOne(baselines.foundation).valid ? ["STAGE_1_TRUST_FOUNDATION_INVALID" as const] : []), ...(!validateConstitutionalComplianceGate(baselines.gate).valid ? ["STAGE_2_CONSTITUTIONAL_GATE_INVALID" as const] : []), ...(!validateTrustRegistryDomains(baselines.registry).valid ? ["STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" as const] : []), ...(!validateTrustIndependentEvaluation(baselines.evaluation).valid ? ["STAGE_4_INDEPENDENT_EVALUATION_INVALID" as const] : []), ...(!validateTrustResolutionEngine(baselines.resolution).valid ? ["STAGE_5_TRUST_RESOLUTION_INVALID" as const] : []), ...(!validateTrustExplainabilityStageSix(baselines.explainability).valid ? ["STAGE_6_EXPLAINABILITY_INVALID" as const] : [])])]);
  const queueOk = !has(failures, "OVERSIGHT_QUEUE_MISSING") && !has(failures, "QUEUE_PRIORITIZATION_MISSING") && !has(failures, "ROUTING_RULES_MISSING") && !has(failures, "REVIEWER_ASSIGNMENT_MISSING") && !has(failures, "QUEUE_TENANT_ISOLATION_MISSING") && !has(failures, "QUEUE_REPLAY_MISSING") && !has(failures, "QUEUE_AUDIT_MISSING") && !has(failures, "MULTIPLE_QUEUES_ASSIGNED");
  const workflowOk = !has(failures, "OVERSIGHT_WORKFLOW_MISSING") && !has(failures, "REVIEW_TASKS_MISSING") && !has(failures, "EVIDENCE_REVIEW_MISSING") && !has(failures, "RESTRICTION_REVIEW_MISSING") && !has(failures, "CONSTITUTIONAL_REVIEW_MISSING") && !has(failures, "REVIEW_COMPLETION_MISSING") && !has(failures, "WORKFLOW_REPLAY_MISSING");
  const lifecycleOk = !has(failures, "REVIEW_LIFECYCLE_MISSING") && !has(failures, "STATE_MACHINE_MISSING") && !has(failures, "TRANSITION_VALIDATION_MISSING") && !has(failures, "INVALID_LIFECYCLE_STATE_ALLOWED") && !has(failures, "LIFECYCLE_HISTORY_MISSING") && !has(failures, "LIFECYCLE_REPLAY_MISSING");
  const decisionOk = !has(failures, "DECISION_RECORDING_MISSING") && !has(failures, "REVIEWER_IDENTITY_MISSING") && !has(failures, "DECISION_SIGNATURE_MISSING") && !has(failures, "DECISION_RECORD_MUTABLE") && !has(failures, "DISPOSITION_RECORDING_MISSING");
  const resolutionOk = !has(failures, "ESCALATION_RESOLUTION_MISSING") && !has(failures, "DISPOSITION_VALIDATION_MISSING") && !has(failures, "RESTRICTION_VALIDATION_MISSING") && !has(failures, "STANDING_VALIDATION_MISSING") && !has(failures, "CONSTITUTIONAL_VALIDATION_MISSING") && !has(failures, "CONSTITUTIONAL_DENY_OVERRIDDEN") && !has(failures, "FAIL_CLOSED_OVERRIDDEN") && !has(failures, "RESTRICTIONS_BYPASSED");
  const evidenceOk = !has(failures, "OVERSIGHT_EVIDENCE_MISSING") && !has(failures, "REVIEWER_EVIDENCE_MISSING") && !has(failures, "WORKFLOW_EVIDENCE_MISSING") && !has(failures, "TIMELINE_EVIDENCE_MISSING") && !has(failures, "EVIDENCE_HASH_INVALID") && !has(failures, "EVIDENCE_REPLAY_MISSING") && !has(failures, "EVIDENCE_REMOVED");
  const lineageOk = !has(failures, "DECISION_LINEAGE_MISSING") && !has(failures, "ESCALATION_LINEAGE_MISSING") && !has(failures, "REVIEW_LINEAGE_MISSING") && !has(failures, "CONSTITUTIONAL_REFERENCES_MISSING") && !has(failures, "TRUST_REFERENCES_MISSING") && !has(failures, "LINEAGE_NOT_TRACEABLE") && !has(failures, "HISTORICAL_DECISION_REWRITTEN");
  const processOk = !has(failures, "OVERSIGHT_BYPASSED_AUTOMATED_EVALUATION");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "HUMAN_OVERSIGHT_QUALIFIED";
  const tenant_id = input.tenant_id ?? baselines.explainability.tenant_id;
  const oversight_id = input.oversight_id ?? `human-oversight:stage-7:${input.seed ?? "canonical"}`;
  const queue = nested({ queue_id: queueOk ? "queue:stage-7:oversight" : "", receives_escalate_decisions: queueOk, exactly_one_queue: queueOk, queue_prioritization: queueOk, routing_rules: queueOk, reviewer_assignment: queueOk, tenant_isolation: queueOk, queue_replay: queueOk, queue_recovery: queueOk, queue_audit: queueOk, ordering_maintained: queueOk, ownership_tracked: queueOk });
  const workflow = nested({ workflow_id: workflowOk ? "workflow:stage-7:oversight" : "", review_workflow: workflowOk, review_tasks: workflowOk, evidence_review: workflowOk, restriction_review: workflowOk, constitutional_review: workflowOk, decision_preparation: workflowOk, review_completion: workflowOk, workflow_recovery: workflowOk, required_steps_enforced: workflowOk, deterministic: workflowOk, replay_verified: workflowOk });
  const lifecycle = nested({ lifecycle_id: lifecycleOk ? "lifecycle:stage-7:review" : "", states: lifecycleOk ? freezeArray(STATES) : freezeArray<OversightLifecycleState>([]), state_machine: lifecycleOk, transition_validation: lifecycleOk, lifecycle_events: lifecycleOk, timeout_handling: lifecycleOk, expiration: lifecycleOk, lifecycle_recovery: lifecycleOk, lifecycle_history: lifecycleOk, invalid_states_prevented: lifecycleOk, replay_identical: lifecycleOk });
  const decision_record = nested({ decision_id: decisionOk ? "decision:stage-7:oversight" : "", dispositions: decisionOk ? freezeArray(DISPOSITIONS) : freezeArray<OversightDisposition>([]), disposition_recording: decisionOk, reviewer_identity: decisionOk, decision_timestamp: decisionOk, decision_metadata: decisionOk, restriction_recording: decisionOk, approval_conditions: decisionOk, decision_signatures: decisionOk, immutable_records: decisionOk, replay_support: decisionOk });
  const resolution = nested({ resolution_id: resolutionOk ? "resolution:stage-7:oversight" : "", resolution_logic: resolutionOk, disposition_validation: resolutionOk, restriction_validation: resolutionOk, standing_validation: resolutionOk, constitutional_validation: resolutionOk, resolution_evidence: resolutionOk, resolution_lineage: resolutionOk, authority_verified: resolutionOk, deny_not_relaxed: resolutionOk, fail_closed_not_overridden: resolutionOk, restrictions_preserved: resolutionOk, deterministic_outcomes: resolutionOk });
  const evidence = nested({ evidence_id: evidenceOk ? "evidence:stage-7:oversight" : "", oversight_evidence: evidenceOk, reviewer_evidence: evidenceOk, decision_evidence: evidenceOk, workflow_evidence: evidenceOk, timeline_evidence: evidenceOk, immutable_storage: evidenceOk, evidence_hashing: evidenceOk, evidence_replay: evidenceOk, certification_ready: evidenceOk });
  const lineage = nested({ lineage_id: lineageOk ? "lineage:stage-7:oversight" : "", decision_lineage_graph: lineageOk, escalation_lineage: lineageOk, review_lineage: lineageOk, evidence_relationships: lineageOk, decision_relationships: lineageOk, constitutional_references: lineageOk, trust_references: lineageOk, replay_relationships: lineageOk, complete_lineage: lineageOk, traceability_validated: lineageOk });
  const readiness = nested({ readiness_id: "STAGE-7-HUMAN-OVERSIGHT-READINESS-001", decision, phase_ready: qualified, upstream_ready: failures.every((failure) => !failure.startsWith("STAGE_")), queue_ready: queueOk, workflow_ready: workflowOk, lifecycle_ready: lifecycleOk, decision_recording_ready: decisionOk, resolution_ready: resolutionOk, evidence_ready: evidenceOk, lineage_ready: lineageOk, deterministic_routing: queueOk, reviewer_assignment_validated: queueOk, lifecycle_transitions_validated: lifecycleOk, constitutional_limits_preserved: resolutionOk && processOk, no_constitutional_override: resolutionOk, immutable_evidence: evidenceOk, replayable: queueOk && workflowOk && lifecycleOk && evidenceOk && lineageOk, explainable: processOk, certification_ready: evidenceOk && lineageOk, failures });
  const base: Omit<TrustHumanOversightResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id, oversight_id, queue, workflow, lifecycle, decision_record, resolution, evidence, lineage, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustHumanOversightStageSeven(result?: TrustHumanOversightResult): TrustHumanOversightValidation {
  if (!result) return nested({ valid: false, decision: "FAIL_CLOSED" as const, replay_hash_valid: false, integrity_hash_valid: false, queue_valid: false, workflow_valid: false, lifecycle_valid: false, decision_record_valid: false, resolution_valid: false, evidence_valid: false, lineage_valid: false, readiness_valid: false, failures: freezeArray(["OVERSIGHT_QUEUE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const queue_valid = verifyHashed(result.queue) && result.queue.receives_escalate_decisions && result.queue.exactly_one_queue && result.queue.reviewer_assignment && result.queue.tenant_isolation && result.queue.queue_replay;
  const workflow_valid = verifyHashed(result.workflow) && result.workflow.evidence_review && result.workflow.restriction_review && result.workflow.constitutional_review && result.workflow.required_steps_enforced && result.workflow.replay_verified;
  const lifecycle_valid = verifyHashed(result.lifecycle) && result.lifecycle.states.length === 6 && result.lifecycle.transition_validation && result.lifecycle.invalid_states_prevented && result.lifecycle.replay_identical;
  const decision_record_valid = verifyHashed(result.decision_record) && result.decision_record.dispositions.length === 5 && result.decision_record.reviewer_identity && result.decision_record.decision_signatures && result.decision_record.immutable_records;
  const resolution_valid = verifyHashed(result.resolution) && result.resolution.authority_verified && result.resolution.deny_not_relaxed && result.resolution.fail_closed_not_overridden && result.resolution.restrictions_preserved && result.resolution.deterministic_outcomes;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.oversight_evidence && result.evidence.reviewer_evidence && result.evidence.workflow_evidence && result.evidence.immutable_storage && result.evidence.evidence_replay;
  const lineage_valid = verifyHashed(result.lineage) && result.lineage.decision_lineage_graph && result.lineage.escalation_lineage && result.lineage.review_lineage && result.lineage.complete_lineage && result.lineage.traceability_validated;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.deterministic_routing && result.readiness.reviewer_assignment_validated && result.readiness.lifecycle_transitions_validated && result.readiness.no_constitutional_override && result.readiness.immutable_evidence && result.readiness.replayable && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && queue_valid && workflow_valid && lifecycle_valid && decision_record_valid && resolution_valid && evidence_valid && lineage_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, queue_valid, workflow_valid, lifecycle_valid, decision_record_valid, resolution_valid, evidence_valid, lineage_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayTrustHumanOversightStageSeven(result = runTrustHumanOversightStageSeven()): boolean { const replayed = runTrustHumanOversightStageSeven(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustHumanOversightStageSeven(result).valid; }
export function getTrustHumanOversightStageSevenBundle(): TrustHumanOversightBundle { const result = runTrustHumanOversightStageSeven(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, constitutional_authority: true, only_after_automated_trust_pipeline: true, cannot_override_deny_or_fail_closed: true, immutable_evidence_required: true, deterministic_replay_required: true, complete_lineage_required: true, qualification_gate: "Stage 7 Human Oversight Qualification Gate" }), result, validation: validateTrustHumanOversightStageSeven(result) }); }
export const TrustHumanOversightStageSevenService = Object.freeze({ run: runTrustHumanOversightStageSeven, validate: validateTrustHumanOversightStageSeven, replay: replayTrustHumanOversightStageSeven });
