import { runAgentRegistry, validateAgentRegistry } from "@/services/agent-registry";
import { runCafConstitutionalFoundation, validateCafConstitutionalFoundation } from "@/services/caf-constitutional-foundation";
import { runCapabilityRegistry, validateCapabilityRegistry } from "@/services/capability-registry";
import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runLifecycleEngine, validateLifecycleEngine } from "@/services/lifecycle-engine";
import { runSkillRegistry, validateSkillRegistry } from "@/services/skill-registry";
import type { AuthorityDisposition, AuthorityProfileKind, AuthorityValidatorBundle, AuthorityValidatorDecision, AuthorityValidatorFailure, AuthorityValidatorInput, AuthorityValidatorResult, AuthorityValidatorScenario, AuthorityValidatorValidation, DelegationKind } from "@/types/authority-validator";

const VERSION = "authority-validator/w2.5" as const;
const IDENTIFIER = "AuthorityValidator" as const;
const PROFILE_KINDS = Object.freeze<AuthorityProfileKind[]>(["Agent", "Operator", "Tenant", "Organization", "Runtime", "Service", "Workflow", "Capability", "Skill", "Administrative"]);
const DELEGATION_KINDS = Object.freeze<DelegationKind[]>(["Temporary", "Permanent", "Scoped", "Conditional", "Hierarchical", "Tenant", "Workflow", "Runtime"]);
const DISPOSITIONS = Object.freeze<AuthorityDisposition[]>(["AUTHORIZED", "AUTHORIZED_WITH_RESTRICTIONS", "DELEGATED", "DENIED", "REQUIRES_OPERATOR", "REQUIRES_POLICY", "REQUIRES_CERTIFICATION", "SUSPENDED", "REVOKED", "UNKNOWN"]);
let constitutionBaseline: ReturnType<typeof runCafConstitutionalFoundation> | undefined;
let agentRegistryBaseline: ReturnType<typeof runAgentRegistry> | undefined;
let lifecycleBaseline: ReturnType<typeof runLifecycleEngine> | undefined;
let capabilityRegistryBaseline: ReturnType<typeof runCapabilityRegistry> | undefined;
let skillRegistryBaseline: ReturnType<typeof runSkillRegistry> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly AuthorityValidatorFailure[], failure: AuthorityValidatorFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: AuthorityValidatorScenario): AuthorityValidatorFailure | undefined { return scenario === "BASELINE" || scenario === "OPERATIONAL_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly AuthorityValidatorFailure[], scenario: AuthorityValidatorScenario): AuthorityValidatorDecision {
  if (has(failures, "W2_0_CAF_CONSTITUTION_INVALID") || has(failures, "W2_1_AGENT_REGISTRY_INVALID") || has(failures, "W2_2_LIFECYCLE_ENGINE_INVALID") || has(failures, "W2_3_CAPABILITY_REGISTRY_INVALID") || has(failures, "W2_4_SKILL_REGISTRY_INVALID") || has(failures, "AUTHORITY_PROFILE_SCOPE_INVALID") || has(failures, "AUTHORITY_PROFILE_OWNERSHIP_AMBIGUOUS") || has(failures, "UNSCOPED_DELEGATION_ALLOWED") || has(failures, "EXPIRED_DELEGATION_ALLOWED") || has(failures, "REVOKED_DELEGATION_ALLOWED") || has(failures, "AUTHORITY_DECISION_NON_DETERMINISTIC") || has(failures, "AUTHORITY_CONFLICT_UNRESOLVED") || has(failures, "TENANT_BOUNDARY_BYPASSED") || has(failures, "NAMESPACE_VALIDATION_FAILED") || has(failures, "LIFECYCLE_VALIDATION_FAILED") || has(failures, "CERTIFICATION_VALIDATION_FAILED") || has(failures, "RESTRICTIONS_NOT_ENFORCED") || has(failures, "POLICY_PREREQUISITES_SKIPPED") || has(failures, "SAFETY_PREREQUISITES_SKIPPED") || has(failures, "UNKNOWN_DISPOSITION_ALLOWED") || has(failures, "ENFORCEMENT_SEQUENCE_INVALID") || has(failures, "AUTHORITY_EVIDENCE_NOT_IMMUTABLE") || has(failures, "AUTHORITY_REPLAY_INVALID")) return "FAIL_CLOSED";
  if (has(failures, "AUTHORITY_VALIDATOR_OPERATIONAL_GATE_FAILED")) return "NOT_OPERATIONAL";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP" || scenario === "OPERATIONAL_WITH_OBSERVATIONS") return "CONDITIONALLY_OPERATIONAL";
  return "AUTHORITY_VALIDATOR_OPERATIONAL";
}
function resultReplayHash(result: Omit<AuthorityValidatorResult, "replay_hash" | "integrity_hash">): string { return hash({ profiles: result.profiles.integrity_hash, delegation: result.delegation.integrity_hash, evaluation: result.evaluation.integrity_hash, restrictions: result.restrictions.integrity_hash, disposition: result.disposition_mapping.integrity_hash, registry: result.registry.integrity_hash, decisions: result.decisions.integrity_hash, apis: result.apis.integrity_hash, evidence: result.evidence.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<AuthorityValidatorResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runAuthorityValidator(input: AuthorityValidatorInput = {}): AuthorityValidatorResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<AuthorityValidatorFailure>(direct ? [direct] : []);
  constitutionBaseline ??= runCafConstitutionalFoundation();
  agentRegistryBaseline ??= runAgentRegistry();
  lifecycleBaseline ??= runLifecycleEngine();
  capabilityRegistryBaseline ??= runCapabilityRegistry();
  skillRegistryBaseline ??= runSkillRegistry();
  const constitutionInvalid = !validateCafConstitutionalFoundation(constitutionBaseline).valid || has(scenarioFailures, "W2_0_CAF_CONSTITUTION_INVALID");
  const agentRegistryInvalid = !validateAgentRegistry(agentRegistryBaseline).valid || has(scenarioFailures, "W2_1_AGENT_REGISTRY_INVALID");
  const lifecycleInvalid = !validateLifecycleEngine(lifecycleBaseline).valid || has(scenarioFailures, "W2_2_LIFECYCLE_ENGINE_INVALID");
  const capabilityRegistryInvalid = !validateCapabilityRegistry(capabilityRegistryBaseline).valid || has(scenarioFailures, "W2_3_CAPABILITY_REGISTRY_INVALID");
  const skillRegistryInvalid = !validateSkillRegistry(skillRegistryBaseline).valid || has(scenarioFailures, "W2_4_SKILL_REGISTRY_INVALID");
  const failures = freezeArray([...new Set([...scenarioFailures, ...(constitutionInvalid ? ["W2_0_CAF_CONSTITUTION_INVALID" as const] : []), ...(agentRegistryInvalid ? ["W2_1_AGENT_REGISTRY_INVALID" as const] : []), ...(lifecycleInvalid ? ["W2_2_LIFECYCLE_ENGINE_INVALID" as const] : []), ...(capabilityRegistryInvalid ? ["W2_3_CAPABILITY_REGISTRY_INVALID" as const] : []), ...(skillRegistryInvalid ? ["W2_4_SKILL_REGISTRY_INVALID" as const] : [])])]);
  const profilesOk = !has(failures, "AUTHORITY_PROFILES_MISSING") && !has(failures, "AUTHORITY_PROFILE_SCOPE_INVALID") && !has(failures, "AUTHORITY_PROFILE_OWNERSHIP_AMBIGUOUS") && !has(failures, "AUTHORITY_PROFILE_CERTIFICATION_MISSING");
  const delegationOk = !has(failures, "DELEGATION_ENGINE_MISSING") && !has(failures, "UNSCOPED_DELEGATION_ALLOWED") && !has(failures, "EXPIRED_DELEGATION_ALLOWED") && !has(failures, "REVOKED_DELEGATION_ALLOWED") && !has(failures, "DELEGATION_EVIDENCE_MISSING");
  const evaluationOk = !has(failures, "AUTHORITY_EVALUATION_ENGINE_MISSING") && !has(failures, "AUTHORITY_DECISION_NON_DETERMINISTIC") && !has(failures, "AUTHORITY_CONFLICT_UNRESOLVED") && !has(failures, "TENANT_BOUNDARY_BYPASSED") && !has(failures, "NAMESPACE_VALIDATION_FAILED") && !has(failures, "LIFECYCLE_VALIDATION_FAILED") && !has(failures, "CERTIFICATION_VALIDATION_FAILED");
  const restrictionsOk = !has(failures, "RESTRICTION_MODEL_MISSING") && !has(failures, "RESTRICTIONS_NOT_ENFORCED") && !has(failures, "POLICY_PREREQUISITES_SKIPPED") && !has(failures, "SAFETY_PREREQUISITES_SKIPPED");
  const dispositionOk = !has(failures, "DISPOSITION_MAPPING_MISSING") && !has(failures, "UNKNOWN_DISPOSITION_ALLOWED");
  const registryOk = !has(failures, "AUTHORITY_REGISTRY_MISSING");
  const apisOk = !has(failures, "AUTHORITY_API_MISSING") && !has(failures, "DELEGATION_API_MISSING") && !has(failures, "RESTRICTION_API_MISSING") && !has(failures, "DECISION_API_MISSING");
  const evidenceOk = !has(failures, "AUTHORITY_EVIDENCE_MISSING") && !has(failures, "AUTHORITY_EVIDENCE_NOT_IMMUTABLE") && !has(failures, "AUTHORITY_REPLAY_INVALID");
  const sequenceOk = !has(failures, "ENFORCEMENT_SEQUENCE_INVALID");
  const decision = decisionFor(failures, scenario);
  const operational = decision === "AUTHORITY_VALIDATOR_OPERATIONAL";
  const profiles = nested({ registry_id: profilesOk ? `registry:w2.5:authority-profiles:${input.seed ?? "canonical"}` : "", profile_kinds: profilesOk ? freezeArray(PROFILE_KINDS) : freezeArray<AuthorityProfileKind>([]), authority_scope: profilesOk, authority_level: profilesOk, ownership: profilesOk, jurisdiction: profilesOk, inherited_authority: profilesOk, delegated_authority_eligibility: profilesOk, restrictions: profilesOk, expiration_rules: profilesOk, certification_requirements: profilesOk });
  const delegation = nested({ engine_id: delegationOk ? "engine:w2.5:delegated-authority" : "", delegation_kinds: delegationOk ? freezeArray(DELEGATION_KINDS) : freezeArray<DelegationKind>([]), issuer: delegationOk, recipient: delegationOk, authority_scope: delegationOk, duration: delegationOk, limitations: delegationOk, revocation: delegationOk, evidence: delegationOk, approval_history: delegationOk, constitutional_constraints: delegationOk });
  const evaluation = nested({ engine_id: evaluationOk ? "engine:w2.5:authority-evaluation" : "", requester: evaluationOk, authority_profile: evaluationOk, delegated_authority: evaluationOk, capability_ownership: evaluationOk, skill_ownership: evaluationOk, lifecycle_state: evaluationOk, tenant_boundary: evaluationOk, namespace: evaluationOk, constitutional_constraints: evaluationOk, runtime_eligibility: evaluationOk, certification_status: evaluationOk, conflict_resolution: evaluationOk, deterministic_results: evaluationOk });
  const restrictions = nested({ model_id: restrictionsOk ? "model:w2.5:authority-restrictions" : "", tenant_restrictions: restrictionsOk, organization_restrictions: restrictionsOk, jurisdiction_restrictions: restrictionsOk, capability_restrictions: restrictionsOk, skill_restrictions: restrictionsOk, lifecycle_restrictions: restrictionsOk, runtime_restrictions: restrictionsOk, certification_restrictions: restrictionsOk, policy_prerequisites: restrictionsOk, safety_prerequisites: restrictionsOk, before_execution_authorization: restrictionsOk });
  const disposition_mapping = nested({ table_id: dispositionOk ? "table:w2.5:authority-dispositions" : "", dispositions: dispositionOk ? freezeArray(DISPOSITIONS) : freezeArray<AuthorityDisposition>([]), authority_state: dispositionOk, restriction_state: dispositionOk, delegation_state: dispositionOk, lifecycle_state: dispositionOk, canonical_mapping: dispositionOk, platform_standard: dispositionOk, unknown_rejected: dispositionOk });
  const registry = nested({ service_id: registryOk ? "service:w2.5:authority-registry" : "", authority_profiles: registryOk, delegation_records: registryOk, authority_hierarchy: registryOk, restriction_definitions: registryOk, constitutional_mappings: registryOk, evidence_references: registryOk, historical_decisions: registryOk, queryable: registryOk });
  const decisions = nested({ engine_id: evaluationOk && dispositionOk && evidenceOk ? "engine:w2.5:authority-decisions" : "", validate_authority: evaluationOk, validate_delegation: delegationOk, resolve_authority: evaluationOk, evaluate_restrictions: restrictionsOk, produce_decision: evaluationOk && dispositionOk, decision_identifier: evaluationOk, requester: evaluationOk, requested_action: evaluationOk, evaluated_authority: evaluationOk, restrictions_applied: restrictionsOk, delegated_authority_used: delegationOk, disposition: operational ? "AUTHORIZED" as const : "DENIED" as const, reasoning: evaluationOk, timestamp: evaluationOk, evidence_reference: evidenceOk, deterministic_decision: evaluationOk });
  const apis = nested({ api_id: apisOk ? "api:w2.5:authority-validator" : "", validate_authority: apisOk, evaluate_authority: apisOk, resolve_authority: apisOk, list_authority_profiles: apisOk, query_authority: apisOk, grant_delegation: apisOk, revoke_delegation: apisOk, validate_delegation: apisOk, list_delegations: apisOk, evaluate_restrictions: apisOk, query_restrictions: apisOk, list_restriction_policies: apisOk, retrieve_decision: apisOk, replay_decision: apisOk, verify_decision: apisOk, stable: apisOk });
  const evidence = nested({ ledger_id: evidenceOk ? "ledger:w2.5:authority-evidence" : "", records: evidenceOk ? freezeArray(["authority:evaluation", "authority:delegation", "authority:restriction", "authority:constitutional-decision", "authority:decision-history", "authority:lineage", "authority:replay"]) : freezeArray<string>([]), authority_evaluations: evidenceOk, delegation_evidence: evidenceOk, restriction_evaluations: evidenceOk, constitutional_decisions: evidenceOk, decision_history: evidenceOk, authority_lineage: evidenceOk, decision_replay_evidence: evidenceOk, immutable: evidenceOk, replayable: evidenceOk });
  const readiness = nested({ readiness_id: "W2.5-AUTHORITY-VALIDATOR-READINESS-001", decision, phase_ready: operational, constitution_ready: !constitutionInvalid, agent_registry_ready: !agentRegistryInvalid, lifecycle_engine_ready: !lifecycleInvalid, capability_registry_ready: !capabilityRegistryInvalid, skill_registry_ready: !skillRegistryInvalid, profiles_ready: profilesOk, delegation_ready: delegationOk, evaluation_ready: evaluationOk, restrictions_ready: restrictionsOk, disposition_mapping_ready: dispositionOk, registry_ready: registryOk, decisions_ready: evaluationOk && dispositionOk && evidenceOk, apis_ready: apisOk, evidence_ready: evidenceOk, enforcement_sequence: "Authority -> Policy -> Safety -> Operator" as const, authority_precedes_policy_safety_operator: sequenceOk, failures });
  const base: Omit<AuthorityValidatorResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, caf_constitution_ref: "caf-constitutional-foundation/w2.0", agent_registry_ref: "agent-registry/w2.1", lifecycle_engine_ref: "lifecycle-engine/w2.2", capability_registry_ref: "capability-registry/w2.3", skill_registry_ref: "skill-registry/w2.4", profiles, delegation, evaluation, restrictions, disposition_mapping, registry, decisions, apis, evidence, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateAuthorityValidator(result?: AuthorityValidatorResult): AuthorityValidatorValidation {
  if (!result) return nested({ valid: false, decision: "NOT_OPERATIONAL" as const, replay_hash_valid: false, integrity_hash_valid: false, profiles_valid: false, delegation_valid: false, evaluation_valid: false, restrictions_valid: false, disposition_mapping_valid: false, registry_valid: false, decisions_valid: false, apis_valid: false, evidence_valid: false, readiness_valid: false, failures: freezeArray(["AUTHORITY_PROFILES_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const profiles_valid = verifyHashed(result.profiles) && result.profiles.profile_kinds.length === 10 && result.profiles.authority_scope && result.profiles.certification_requirements;
  const delegation_valid = verifyHashed(result.delegation) && result.delegation.delegation_kinds.length === 8 && result.delegation.revocation && result.delegation.constitutional_constraints;
  const evaluation_valid = verifyHashed(result.evaluation) && result.evaluation.requester && result.evaluation.tenant_boundary && result.evaluation.conflict_resolution && result.evaluation.deterministic_results;
  const restrictions_valid = verifyHashed(result.restrictions) && result.restrictions.tenant_restrictions && result.restrictions.policy_prerequisites && result.restrictions.safety_prerequisites && result.restrictions.before_execution_authorization;
  const disposition_mapping_valid = verifyHashed(result.disposition_mapping) && result.disposition_mapping.dispositions.length === 10 && result.disposition_mapping.canonical_mapping && result.disposition_mapping.unknown_rejected;
  const registry_valid = verifyHashed(result.registry) && result.registry.authority_profiles && result.registry.delegation_records && result.registry.historical_decisions;
  const decisions_valid = verifyHashed(result.decisions) && result.decisions.validate_authority && result.decisions.evaluate_restrictions && result.decisions.deterministic_decision && result.decisions.disposition === "AUTHORIZED";
  const apis_valid = verifyHashed(result.apis) && result.apis.validate_authority && result.apis.grant_delegation && result.apis.evaluate_restrictions && result.apis.verify_decision && result.apis.stable;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.records.length >= 7 && result.evidence.immutable && result.evidence.replayable;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.authority_precedes_policy_safety_operator && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && profiles_valid && delegation_valid && evaluation_valid && restrictions_valid && disposition_mapping_valid && registry_valid && decisions_valid && apis_valid && evidence_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, profiles_valid, delegation_valid, evaluation_valid, restrictions_valid, disposition_mapping_valid, registry_valid, decisions_valid, apis_valid, evidence_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayAuthorityValidator(result = runAuthorityValidator()): boolean { const replayed = runAuthorityValidator(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateAuthorityValidator(result).valid; }
export function getAuthorityValidatorBundle(): AuthorityValidatorBundle { const result = runAuthorityValidator(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_authority_profiles: true, owns_delegated_authority: true, owns_authority_evaluation: true, owns_restriction_evaluation: true, owns_disposition_mapping: true, owns_authority_registry: true, owns_authority_decisions: true, owns_authority_apis: true, owns_authority_evidence: true, enforcement_sequence: "Authority -> Policy -> Safety -> Operator", operational_gate: "Authority Validator Operational Gate" }), result, validation: validateAuthorityValidator(result) }); }
export const AuthorityValidatorService = Object.freeze({ run: runAuthorityValidator, validate: validateAuthorityValidator, replay: replayAuthorityValidator });
