export type ConstitutionalReplayErrorCode =
  | "CONSTITUTIONAL_REPLAY_VALIDATOR_MISMATCH"
  | "CONSTITUTIONAL_REPLAY_GOVERNANCE_DRIFT"
  | "CONSTITUTIONAL_REPLAY_TOPOLOGY_DRIFT"
  | "CONSTITUTIONAL_REPLAY_EVIDENCE_CORRUPTION"
  | "CONSTITUTIONAL_REPLAY_LINEAGE_BREAK"
  | "CONSTITUTIONAL_REPLAY_RUNTIME_CONTAMINATION"
  | "CONSTITUTIONAL_REPLAY_SYNTHETIC_CONTINUITY"
  | "CONSTITUTIONAL_REPLAY_ISOLATION_VIOLATION"
  | "CONSTITUTIONAL_REPLAY_REPAIR_ATTEMPT"
  | "CONSTITUTIONAL_REPLAY_HIDDEN_ORCHESTRATION"
  | "CONSTITUTIONAL_REPLAY_CURRENT_STATE_SUBSTITUTION"
  | "CONSTITUTIONAL_REPLAY_FAIL_CLOSED";

export type ConstitutionalReplayError = Readonly<{
  code: ConstitutionalReplayErrorCode;
  message: string;
  path?: string;
}>;
