import { describe, expect, it } from "vitest";
import { AdversarialAttackSelector, AdversarialExaminerDiversityService, AdversarialExaminerService, AdversarialFindingRouter, AdversarialTestChallengeService } from "@/services/learning-constitution";
import type { AdversarialExaminationArtifactRecord, AdversarialExaminationArtifactStore } from "@/types/learning-constitution";

const at = "2026-09-03T19:00:00.000Z";
const actor = { actorId: "agent:examiner", actorType: "AGENT" as const };
const store = (): AdversarialExaminationArtifactStore => { const records: AdversarialExaminationArtifactRecord[] = []; return { append: async (record) => { records.push(record); return record; }, listArtifacts: async (subjectId) => records.filter((record) => record.subjectId === subjectId), listWorkspaceArtifacts: async () => records }; };
const lease = { leaseId: "LEASE-32", proposalId: "P-32", approvalId: "A-32", scope: "SYSTEM_DESIGN", method: "TARGETED_EVALUATION" as const, maximumQuestions: 0, issuedBy: { actorId: "human:teacher", actorType: "HUMAN" as const }, issuedAt: at, expiresAt: "2026-09-04T19:00:00.000Z", status: "ACTIVE" as const };
const exam = { examId: "EXAM-32", curriculumId: "CUR-32", lease, skillId: "SK-32", competencyClaimId: "MC-32", maximumTests: 3, testsUsed: 0, status: "ACTIVE" as const, examinerContextHash: "examiner-context", learnerContextHash: "learner-context", startedAt: at, createdBy: actor, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const };
const hypothesis = { hypothesisId: "H-32", skillId: exam.skillId, competencyClaimId: exam.competencyClaimId, suspectedMechanism: "Surface pattern matching", boundary: "Implicit prerequisites", expectedFailureSignal: "Incorrect ordering", createdBy: actor, createdAt: at, immutable: true as const, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const };
const test = { testId: "TEST-32", examId: exam.examId, attackType: "CHANGED_ASSUMPTION" as const, hypothesisId: hypothesis.hypothesisId, scenario: "Visible adversarial scenario", constraints: ["Explain assumptions"], targetDimensions: ["BOUNDARY_RECOGNITION"], learnerContextHash: exam.learnerContextHash, examinerContextHash: exam.examinerContextHash, rubricId: "RUBRIC-32", integrity: "VALID" as const, createdAt: at, immutable: true as const, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const };
const rubric = { rubricId: test.rubricId, testId: test.testId, hiddenDifference: "Prerequisite missing", expectedReasoning: ["Identify missing prerequisite"], plausibleWrongSolutions: ["Apply normal rule"], scoringCriteria: ["Boundary recognized"], isolation: "INDEPENDENT" as const, revealedAt: null, immutable: true as const, examinerOnly: true as const, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const };

describe("Phase 32 adversarial examiner", () => {
  it("requires evaluation authority, explicit hypothesis, and sealed learner/examiner separation", async () => { const service = new AdversarialExaminerService(store()); await expect(service.start({ ...exam, lease: { ...lease, method: "PRACTICE_SEQUENCE" } }, at)).rejects.toThrow("TARGETED_EVALUATION"); await service.start(exam, at); await expect(service.registerHypothesis({ ...hypothesis, boundary: "" })).rejects.toThrow("falsifiable"); await service.registerHypothesis(hypothesis); await expect(service.freeze({ ...test, learnerContextHash: exam.examinerContextHash }, rubric, exam, at)).rejects.toThrow("frozen learner scenario"); await expect(service.freeze(test, rubric, exam, at)).resolves.toMatchObject({ test: { testId: test.testId } }); });
  it("downgrades exposed tests and keeps mastery reassessment review-only", async () => { const service = new AdversarialExaminerService(store()); const attempt = { attemptId: "AT-32", testId: test.testId, learnerContextHash: test.learnerContextHash, response: "answer", confidence: .99, committedAt: at, hiddenMaterialExposedBeforeCommit: true, committedBy: actor, immutable: true as const }; expect(await service.commit(attempt, test, rubric)).toMatchObject({ evaluationPermitted: false }); const finding = { findingId: "F-32", testId: test.testId, attemptId: attempt.attemptId, outcome: "CATASTROPHIC_FAILURE" as const, failureClasses: ["BOUNDARY_FAILURE"], diagnosticRationale: "High-confidence boundary error.", confidenceCalibrationConcern: true, challengeStatus: "NONE" as const, evaluatorIndependent: true, createdAt: at, immutable: true as const, durableKnowledgeEffect: "NONE" as const, executionPermissionGranted: false as const }; expect(await service.recordFinding(finding, test, attempt, rubric, exam.skillId, false)).toMatchObject({ evidenceQuality: "INVALID", skillRegistryEffect: "EVIDENCE_ONLY", durableKnowledgeEffect: "NONE" }); await expect(service.recommendReassessment({ recommendationId: "R-32", skillId: exam.skillId, competencyClaimId: exam.competencyClaimId, action: "SUSPEND_MASTERY", scope: ["implicit prerequisites"], basisFindingIds: [finding.findingId], requiresReview: true, createdAt: at, createdBy: actor, executionPermissionGranted: false, durableKnowledgeEffect: "NONE" })).resolves.toMatchObject({ requiresReview: true, action: "SUSPEND_MASTERY" }); });
  it("varies attack families and lets the learner challenge a bad test without accepting examiner infallibility", async () => { expect(new AdversarialAttackSelector().select([hypothesis], [{ testId: "OLD", attackType: "CHANGED_ASSUMPTION", boundary: "different boundary", structuralFingerprint: "old", outcome: "ROBUST_PASS" }])).toMatchObject({ hypothesisId: hypothesis.hypothesisId, informationGain: "HIGH", selectionEffect: "RECOMMENDATION_ONLY" }); expect(new AdversarialExaminerDiversityService().assess({ attackType: "CHANGED_ASSUMPTION", boundary: hypothesis.boundary, structuralFingerprint: "same" }, [1, 2].map((id) => ({ testId: `OLD-${id}`, attackType: "CHANGED_ASSUMPTION" as const, boundary: hypothesis.boundary, structuralFingerprint: "same", outcome: "ROBUST_PASS" as const })))).toMatchObject({ diverse: false, recommendation: "CHANGE_ATTACK_FAMILY" }); const service = new AdversarialTestChallengeService(store()); const challenge = { challengeId: "C-32", testId: test.testId, kind: "CHALLENGE_CONTRADICTION" as const, rationale: "The hidden premise contradicts the provided evidence.", status: "CHALLENGED" as const, createdAt: at, createdBy: actor, immutable: true as const, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const }; await service.submit(challenge); await expect(service.resolve(challenge, "INVALIDATED", at, actor)).resolves.toMatchObject({ status: "INVALIDATED" }); });
  it("routes evidence to reflection or review without automatically changing competence", () => { const base = { findingId: "F-ROUTE", testId: test.testId, attemptId: "A", failureClasses: ["BOUNDARY_FAILURE"], diagnosticRationale: "diagnostic", confidenceCalibrationConcern: false, challengeStatus: "NONE" as const, evaluatorIndependent: true, createdAt: at, immutable: true as const, durableKnowledgeEffect: "NONE" as const, executionPermissionGranted: false as const }; expect(new AdversarialFindingRouter().route({ ...base, outcome: "PARTIAL_FAILURE" })).toMatchObject({ route: "REFLECTION", durableKnowledgeEffect: "NONE" }); expect(new AdversarialFindingRouter().route({ ...base, outcome: "CATASTROPHIC_FAILURE" })).toMatchObject({ route: "MASTERY_REASSESSMENT" }); expect(new AdversarialFindingRouter().route({ ...base, outcome: "CATASTROPHIC_FAILURE", challengeStatus: "INVALIDATED" })).toMatchObject({ route: "NO_ACTION" }); });
});
