import { describe, expect, it } from "vitest";
import { CapabilityAuthorizationService, CapabilityGrantLifecycleService, CapabilityPreflightAuditService, CapabilityPreflightService, InMemoryLearningAuditLedger, LearningCapabilityBoundaryService } from "@/services/learning-constitution";
import type { CapabilityArtifactRecord, CapabilityArtifactStore, CapabilityRequest } from "@/types/learning-constitution";

const at = "2026-09-03T20:00:00.000Z";
const agent = { actorId: "agent:noesis", actorType: "AGENT" as const };
const human = { actorId: "human:owner", actorType: "HUMAN" as const };
const store = (): CapabilityArtifactStore => { const records: CapabilityArtifactRecord[] = []; return { append: async (artifact) => { records.push(artifact); return artifact; }, listArtifacts: async (subjectId) => records.filter((artifact) => artifact.subjectId === subjectId), listWorkspaceArtifacts: async () => records }; };
const request = (): CapabilityRequest => ({ requestId: "CR-35", actor: agent, capability: "REPOSITORY_CHANGE", operations: ["MODIFY_FILE"], resourceId: "repo:noesis", scope: ["src/noesis"], purpose: "Implement approved task.", relatedTaskId: "TASK-35", supportingCertificationIds: ["SK-CERTIFIED"], requestedDurationMinutes: 60, riskClass: "MODERATE", constraints: ["No secrets"], status: "REQUESTED", createdAt: at, immutable: true, learningEvidenceOnly: true, executionPermissionGranted: false });

describe("Phase 35 capability boundary", () => {
  it("blocks even certified learning evidence until a separate distinct-human authorization exists", async () => { const artifacts = store(); const service = new CapabilityAuthorizationService(artifacts); const preflight = new CapabilityPreflightService(); const capabilityRequest = request(); await service.request(capabilityRequest); expect(preflight.check({ actor: agent, capability: capabilityRequest.capability, operation: "MODIFY_FILE", resourceId: "repo:noesis", scope: "src/noesis", satisfiedConstraints: ["No secrets"], requestedAt: at, availableTool: true }, [])).toMatchObject({ authorized: false, reason: "NO_GRANT" }); await expect(service.approve({ grantId: "CG-SELF", request: capabilityRequest, grantedBy: agent, grantedAt: at, expiresAt: "2026-09-03T21:00:00.000Z" })).rejects.toThrow("distinct human"); const grant = await service.approve({ grantId: "CG-35", request: capabilityRequest, grantedBy: human, grantedAt: at, expiresAt: "2026-09-03T21:00:00.000Z" }); expect(preflight.check({ actor: agent, capability: grant.capability, operation: "MODIFY_FILE", resourceId: "repo:noesis", scope: "src/noesis", satisfiedConstraints: ["No secrets"], requestedAt: at, availableTool: true }, [grant])).toMatchObject({ authorized: true, executionPermissionGranted: true }); });
  it("fails closed on operation, expiry, constraints, and every learning-domain authority mutation", async () => { const artifacts = store(); const grant = await new CapabilityAuthorizationService(artifacts).approve({ grantId: "CG-35", request: request(), grantedBy: human, grantedAt: at, expiresAt: "2026-09-03T21:00:00.000Z" }); const preflight = new CapabilityPreflightService(); const base = { actor: agent, capability: grant.capability, resourceId: grant.resourceId, scope: "src/noesis", satisfiedConstraints: ["No secrets"], requestedAt: at, availableTool: true }; expect(preflight.check({ ...base, operation: "DELETE_REPOSITORY" }, [grant])).toMatchObject({ authorized: false, reason: "OPERATION_OUT_OF_SCOPE" }); expect(preflight.check({ ...base, operation: "MODIFY_FILE", requestedAt: "2026-09-03T22:00:00.000Z" }, [grant])).toMatchObject({ authorized: false, reason: "EXPIRED" }); expect(preflight.check({ ...base, operation: "MODIFY_FILE", satisfiedConstraints: [] }, [grant])).toMatchObject({ authorized: false, reason: "CONSTRAINT_UNSATISFIED" }); expect(new LearningCapabilityBoundaryService().rejectAuthorityMutation({ source: "CERTIFICATION", requestedEffect: "CREATE_GRANT" })).toMatchObject({ blocked: true, reason: "LEARNING_CANNOT_MUTATE_AUTHORIZATION" }); });
  it("treats revocation as final and rejects renewal as an implicit reactivation", async () => { const artifacts = store(); const grant = await new CapabilityAuthorizationService(artifacts).approve({ grantId: "CG-REVOKE", request: request(), grantedBy: human, grantedAt: at, expiresAt: "2026-09-03T21:00:00.000Z" }); const lifecycle = await new CapabilityGrantLifecycleService(artifacts).transition({ eventId: "REVOKE-35", grant, to: "REVOKED", reason: "Owner revoked access.", actor: human, occurredAt: at }); expect(new CapabilityPreflightService().check({ actor: agent, capability: grant.capability, operation: "MODIFY_FILE", resourceId: grant.resourceId, scope: "src/noesis", satisfiedConstraints: ["No secrets"], requestedAt: at, availableTool: true }, [grant], [lifecycle])).toMatchObject({ authorized: false, reason: "REVOKED" }); expect(() => new CapabilityGrantLifecycleService(artifacts).renew()).toThrow("new separately authorized request"); });
  it("audits every preflight result, including blocked scope violations", async () => { const ledger = new InMemoryLearningAuditLedger(); const boundary = new CapabilityPreflightService(); const preflight = { actor: agent, capability: "REPOSITORY_CHANGE", operation: "DELETE_REPOSITORY", resourceId: "repo:noesis", scope: "src/noesis", satisfiedConstraints: [], requestedAt: at, availableTool: true }; const result = boundary.check(preflight, []); await new CapabilityPreflightAuditService(ledger).record({ eventId: "AUDIT-35", workspaceId: "workspace-35", request: preflight, result, correlationId: "capability-test" }); expect((await ledger.list("workspace-35")).map((entry) => entry.event.eventType)).toEqual(["CAPABILITY_BLOCKED"]); });
  it("blocks adversarial authority escalation claims and all learning-subsystem bypass routes", () => { const boundary = new CapabilityPreflightService(); const claims = ["certified", "retained", "tool available", "emergency", "owner unavailable", "authorized yesterday", "necessary to prevent failure"]; for (const _claim of claims) expect(boundary.check({ actor: agent, capability: "SYSTEM_ADMINISTRATION", operation: "CHANGE_PERMISSIONS", resourceId: "repo:noesis", scope: "permissions", satisfiedConstraints: [], requestedAt: at, availableTool: true }, [])).toMatchObject({ authorized: false, reason: "NO_GRANT" }); for (const source of ["LEARNING", "PRACTICE", "EVALUATION", "RETENTION", "ADVERSARIAL", "SKILL_DISCOVERY", "CERTIFICATION"] as const) expect(new LearningCapabilityBoundaryService().rejectAuthorityMutation({ source, requestedEffect: "CREATE_GRANT" })).toMatchObject({ blocked: true, executionPermissionGranted: false }); });
});
