import { describe, expect, it } from "vitest";
import { buildCurriculumPlan } from "@/services/learning-constitution/curriculumPlanner";
import { LINUX_SKILL_GRAPH } from "@/services/learning-constitution/linuxSkillGraphSeed";

const input = (overrides = {}) => ({ learner_id: "learner", goal: { skill_id: "linux.systemd.troubleshooting", free_text: "Diagnose systemd service failures" }, skill_graph: LINUX_SKILL_GRAPH, assessment_results: [{ id: "assessment-1", skill_id: "linux.systemd.journald", completed_at: "2026-08-21T00:00:00.000Z", score: .3, competencies: {}, evidence_ids: ["e-journal"] }, { id: "assessment-2", skill_id: "linux.systemd.dependencies", completed_at: "2026-08-21T00:00:00.000Z", score: .25, competencies: {}, evidence_ids: ["e-dependencies"] }], learning_history: [], constraints: {}, skill_states: [{ skill_id: "linux.systemd.units", mastery: .9, confidence: .9, retention_score: .9, last_evaluated: "2026-08-20T00:00:00.000Z", evidence_ids: ["e-units"] }], ...overrides });
describe("buildCurriculumPlan", () => {
  it("orders weak prerequisites and never assigns a strong one", () => { const plan = buildCurriculumPlan(input(), "2026-08-21T00:00:00.000Z"); expect(plan.lessons.map((lesson) => lesson.target_skill_id)).toEqual(["linux.systemd.dependencies", "linux.systemd.journald", "linux.systemd.troubleshooting"]); expect(plan.lessons.every((lesson) => lesson.why_this_lesson && lesson.next_step)).toBe(true); expect(plan.lessons.filter((lesson) => lesson.activity_type !== "REASSESSMENT").every((lesson) => lesson.evidence_references.length > 0)).toBe(true); expect(plan.lessons.at(-1)).toMatchObject({ activity_type: "REASSESSMENT", next_step: "Review linux.systemd.troubleshooting results" }); });
  it("uses a diagnostic when evidence is sparse and is repeatable", () => { const sparse = input({ assessment_results: [], skill_states: [] }); const first = buildCurriculumPlan(sparse, "2026-08-21T00:00:00.000Z"); const second = buildCurriculumPlan(sparse, "2026-08-21T00:00:00.000Z"); expect(first.status).toBe("INSUFFICIENT_EVIDENCE"); expect(first).toEqual(second); expect(first.lessons[0].activity_type).toBe("DIAGNOSTIC"); });
  it("excludes explicitly excluded topics and reports constraints", () => { const plan = buildCurriculumPlan(input({ constraints: { excluded_topics: ["linux.systemd.journald"], available_minutes_per_week: 20 } }), "2026-08-21T00:00:00.000Z"); expect(plan.lessons.some((lesson) => lesson.target_skill_id === "linux.systemd.journald")).toBe(false); expect(plan.status).toBe("CONSTRAINED"); });
  it("does not assign an unrelated weak skill", () => { const base = input(); const plan = buildCurriculumPlan({ ...base, assessment_results: [...base.assessment_results, { id: "assessment-networking", skill_id: "linux.networking", completed_at: "2026-08-21T00:00:00.000Z", score: .1, competencies: {}, evidence_ids: ["e-networking"] }] }, "2026-08-21T00:00:00.000Z"); expect(plan.lessons.some((lesson) => lesson.target_skill_id === "linux.networking")).toBe(false); });
  it("uses a diagnostic for conflicting assessment and learner-state evidence", () => { const plan = buildCurriculumPlan(input({ goal: { skill_id: "linux.systemd.journald", free_text: "Read systemd logs" }, assessment_results: [{ id: "assessment-journald", skill_id: "linux.systemd.journald", completed_at: "2026-08-21T00:00:00.000Z", score: .2, competencies: {}, evidence_ids: ["e-assessment"] }], skill_states: [{ skill_id: "linux.systemd.journald", mastery: .95, confidence: .95, retention_score: .95, last_evaluated: "2026-08-20T00:00:00.000Z", evidence_ids: ["e-state"] }] }), "2026-08-21T00:00:00.000Z"); expect(plan.status).toBe("INSUFFICIENT_EVIDENCE"); expect(plan.lessons[0]).toMatchObject({ activity_type: "DIAGNOSTIC", evidence_references: expect.arrayContaining(["e-assessment", "e-state"]) }); });
  it("treats repeated failed attempts as an evidence-backed gap", () => { const plan = buildCurriculumPlan(input({ goal: { skill_id: "linux.systemd.journald", free_text: "Read systemd logs" }, assessment_results: [{ id: "assessment-journald", skill_id: "linux.systemd.journald", completed_at: "2026-08-21T00:00:00.000Z", score: .9, competencies: {}, evidence_ids: ["e-assessment"] }], skill_states: [{ skill_id: "linux.systemd.journald", mastery: .9, confidence: .9, retention_score: .9, last_evaluated: "2026-08-20T00:00:00.000Z", evidence_ids: ["e-state"] }], learning_history: [{ skill_id: "linux.systemd.journald", event: "FAILED", occurred_at: "2026-08-18T00:00:00.000Z" }, { skill_id: "linux.systemd.journald", event: "FAILED", occurred_at: "2026-08-19T00:00:00.000Z" }] }), "2026-08-21T00:00:00.000Z"); expect(plan.lessons[0]).toMatchObject({ target_skill_id: "linux.systemd.journald", activity_type: "GUIDED_PRACTICE" }); });
  it("returns a minimum viable sequence and transparent deferral when time is insufficient", () => { const plan = buildCurriculumPlan(input({ constraints: { available_minutes_per_week: 20 } }), "2026-08-21T00:00:00.000Z"); expect(plan.status).toBe("CONSTRAINED"); expect(plan.lessons.reduce((total, lesson) => total + lesson.estimated_minutes, 0)).toBeLessThanOrEqual(20); expect(plan.assumptions).toContain("Some lessons were deferred to honor the stated time or topic constraints."); });
  it("recalculates away obsolete remediation when a later assessment is strong", () => { const weakPlan = buildCurriculumPlan(input({ goal: { skill_id: "linux.systemd.journald", free_text: "Read systemd logs" }, assessment_results: [{ id: "assessment-weak", skill_id: "linux.systemd.journald", completed_at: "2026-08-21T00:00:00.000Z", score: .2, competencies: {}, evidence_ids: ["e-weak"] }], skill_states: [] }), "2026-08-21T00:00:00.000Z"); const refreshedPlan = buildCurriculumPlan(input({ goal: { skill_id: "linux.systemd.journald", free_text: "Read systemd logs" }, assessment_results: [{ id: "assessment-strong", skill_id: "linux.systemd.journald", completed_at: "2026-08-22T00:00:00.000Z", score: .95, competencies: {}, evidence_ids: ["e-strong"] }], skill_states: [{ skill_id: "linux.systemd.journald", mastery: .95, confidence: .95, retention_score: .95, last_evaluated: "2026-08-22T00:00:00.000Z", evidence_ids: ["e-strong"] }] }), "2026-08-22T00:00:00.000Z"); expect(weakPlan.lessons.some((lesson) => lesson.activity_type === "GUIDED_PRACTICE")).toBe(true); expect(refreshedPlan.lessons).toEqual([expect.objectContaining({ activity_type: "REASSESSMENT" })]); });
});
