import { describe, expect, it } from "vitest";
import { DecisionPredictionScoringService, DecisionPredictionService, InMemoryLearningAuditLedger } from "@/services/learning-constitution";
import type { DecisionPredictionArtifactRecord, DecisionPredictionArtifactStore, DecisionPredictionEvidence, DecisionPredictionOption } from "@/types/learning-constitution";
const at = "2026-09-02T20:00:00.000Z"; const agent = { actorId: "agent:noesis", actorType: "AGENT" as const }; const options: DecisionPredictionOption[] = [{ optionId: "A", label: "Shared database", description: "Direct shared access." }, { optionId: "B", label: "Service boundary", description: "Service-mediated access." }]; const store = (): DecisionPredictionArtifactStore => { const records: DecisionPredictionArtifactRecord[] = []; return { append: async (record) => { records.push(record); return record; }, listArtifacts: async (id) => records.filter((record) => record.subjectId === id), listWorkspaceArtifacts: async () => records }; };
const evidence = (): DecisionPredictionEvidence[] => [{ evidenceId: "D-1", sourceType: "HUMAN_DECISION", sourceId: "D-1", optionId: "B", supports: true, authorityWeight: 1, contextualRelevance: 0.95, recency: 0.9, consistency: 0.9, scopeCompatibility: 0.95, summary: "Similar human decision." }, { evidenceId: "P-1", sourceType: "APPROVED_PRINCIPLE", sourceId: "P-1", optionId: "B", supports: true, authorityWeight: 1, contextualRelevance: 0.85, recency: 0.8, consistency: 0.9, scopeCompatibility: 0.9, summary: "Applicable principle." }];
describe("Phase 24 decision prediction foundation", () => {
  it("creates an immutable agent-inference prediction with diverse human evidence and surfaced differences", async () => {
    const score = new DecisionPredictionScoringService().score(options, evidence()); expect(score.status).toBe("PREDICTION_NOT_HUMAN_INSTRUCTION"); const prediction = { predictionId: "DP-1", question: "How would my teacher design this data boundary?", context: "A service handles customer data.", options, recommendedOptionId: score.recommendedOptionId, evidence: evidence(), similarities: ["Persistent data and service boundary."], importantDifferences: [{ differenceId: "DIFF-1", description: "This system is multi-tenant; precedent was internal-only.", affectedEvidenceIds: ["D-1"], impact: "HIGH" as const, unresolved: true }], reasoningSummary: "Human decision and approved principle favor a service-mediated boundary, subject to the multi-tenant difference.", evidenceStrength: score.evidenceStrength, confidence: score.confidence, uncertaintyFactors: ["Multi-tenant isolation was not in the prior decision."], status: score.status, authority: "AGENT_INFERENCE" as const, humanInstruction: false as const, humanApproved: false as const, mayCreateDirective: false as const, createdBy: agent, createdAt: at, durableKnowledgeEffect: "NONE" as const, executionPermissionGranted: false as const }; const audit = new InMemoryLearningAuditLedger(); await new DecisionPredictionService(store(), audit).create(prediction, "workspace:24", "prediction:1"); expect((await audit.list("workspace:24"))[0]?.event.payload).toMatchObject({ authority: "AGENT_INFERENCE", humanInstruction: false, mayCreateDirective: false });
  });
  it("abstains without directly relevant, diverse human evidence and forbids predictions as evidence", () => {
    const weak: DecisionPredictionEvidence[] = [{ evidenceId: "E-1", sourceType: "EXAMPLE", sourceId: "EX-1", optionId: "A", supports: true, authorityWeight: 1, contextualRelevance: 0.5, recency: 0.5, consistency: 0.5, scopeCompatibility: 0.5, summary: "Weak example." }]; expect(new DecisionPredictionScoringService().score(options, weak)).toMatchObject({ status: "INSUFFICIENT_EVIDENCE", recommendedOptionId: null }); expect(() => new DecisionPredictionScoringService().score(options, [{ ...weak[0]!, sourceType: "DECISION_PREDICTION" as never }])).toThrow("prediction evidence");
  });
});
