import { describe, expect, it } from "vitest";
import { EvaluationCompetenceAssessmentService } from "@/services/learning-constitution";
import type { CompetenceEvaluationRubric, Evaluation, EvaluationAnalysis, EvaluationEvidence, EvaluationScore, EvaluationValidity } from "@/types/learning-constitution";

const actor = { actorId: "human:teacher", actorType: "HUMAN" as const }; const stamp = "2026-09-02T04:00:00.000Z";
const dimensions = { CORRECTNESS: 0.9, APPLICATION: 0.85, GENERALIZATION: 0.8, BOUNDARY_RECOGNITION: 0.85, EXCEPTION_HANDLING: 0.75, CONSISTENCY: 0.85, CALIBRATION: 0.8 } as const;
const rubric: CompetenceEvaluationRubric = { rubricId: "ER-1", skillId: "SK-ROADMAP", version: "1", dimensionThresholds: dimensions, criticalDimensions: ["CORRECTNESS", "BOUNDARY_RECOGNITION"], requiredEvaluationTypes: ["TRANSFER", "BOUNDARY"], createdBy: actor, createdAt: stamp };
const analysis = (overrides: Partial<EvaluationAnalysis> = {}): EvaluationAnalysis => ({ analysisId: "EA-1", skillId: rubric.skillId, calibration: { sampleSize: 3, meanConfidence: 0.9, meanObservedScore: 0.9, meanAbsoluteError: 0, state: "WELL_CALIBRATED" }, consistency: { sampleSize: 3, meanScore: 0.9, scoreRange: 0.05, contextCount: 3, difficultyRange: 0.2, state: "CONSISTENT" }, transfer: { EXACT: { sampleSize: 0, meanScore: null }, MODIFIED: { sampleSize: 0, meanScore: null }, NOVEL: { sampleSize: 1, meanScore: 0.9 }, AMBIGUOUS: { sampleSize: 0, meanScore: null }, EDGE: { sampleSize: 1, meanScore: 0.9 }, ADVERSARIAL: { sampleSize: 0, meanScore: null } }, lastValidEvidenceAt: stamp, recency: "CURRENT", analyzedAt: stamp, masteryEffect: "NONE", durableKnowledgeEffect: "NONE", executionPermissionGranted: false, ...overrides });
const record = (id: string, type: Evaluation["evaluationType"], correctness = 0.95) => { const evaluation: Evaluation = { evaluationId: id, skillId: rubric.skillId, evaluationType: type, trigger: "PRACTICE_ENGINE", difficulty: 0.7, exerciseIds: [`PE:${id}`], expectedBehavior: [], actualBehavior: [], context: { contextId: `EC:${id}`, allowedKnowledgeIds: [], hiddenReferenceIds: [], availableTools: [], providedHints: [], exposedExampleIds: [], environmentalConditions: [], frozenAt: stamp }, rubricId: rubric.rubricId, rubricVersion: rubric.version, evaluator: { type: "DETERMINISTIC_EVALUATOR", actor, version: "1", independent: true }, createdAt: stamp }; const score: EvaluationScore = { scoreId: `ES:${id}`, evaluationId: id, dimensionScores: { ...dimensions, CORRECTNESS: correctness }, overallScore: 0.9, outcome: "PASS", scoredAt: stamp }; const validity: EvaluationValidity = { validityId: `EV:${id}`, evaluationId: id, status: "VALID", reasonCodes: [], checkedAt: stamp }; const evidence: EvaluationEvidence = { evidenceId: `EE:${id}`, evaluationId: id, skillId: rubric.skillId, exerciseIds: evaluation.exerciseIds, responseIds: [], scoreId: score.scoreId, validityId: validity.validityId, evaluator: evaluation.evaluator, createdAt: stamp, skillRegistryEffect: "EVIDENCE_ONLY", durableKnowledgeEffect: "NONE", executionPermissionGranted: false }; return { evaluation, score, validity, evidence }; };

describe("Phase 21 explainable competence assessment", () => {
  it("makes mastery review eligible only from sufficient, valid, current, rubric-complete evidence", () => {
    const result = new EvaluationCompetenceAssessmentService().assess({ assessmentId: "CA-1", skillId: rubric.skillId, rubric, analysis: analysis(), evaluations: [record("1", "TRANSFER"), record("2", "BOUNDARY"), record("3", "TRANSFER")], analyzedAt: stamp });
    expect(result).toMatchObject({ status: "MASTERY_CANDIDATE", eligibleForMasteryReview: true, supportingEvidenceIds: ["EE:1", "EE:2", "EE:3"], masteryEffect: "NONE" });
  });
  it("explains why a critical gap, missing type, or stale evidence cannot establish mastery", () => {
    const result = new EvaluationCompetenceAssessmentService().assess({ assessmentId: "CA-2", skillId: rubric.skillId, rubric, analysis: analysis({ recency: "STALE" }), evaluations: [record("1", "TRANSFER", 0.2), { ...record("bad", "TRANSFER"), validity: { ...record("bad", "TRANSFER").validity, status: "INVALID" } }], analyzedAt: stamp });
    expect(result).toMatchObject({ status: "REVALIDATION_REQUIRED", eligibleForMasteryReview: false, requiredEvaluationTypesMissing: ["BOUNDARY"] });
    expect(result.reasons.join(" ")).toContain("CORRECTNESS");
  });
});
