import { describe, expect, it } from "vitest";
import { ConservativeSkillValidator, EvaluationPracticeReferralService, EvaluationSkillRegistryBridgeService, InMemoryLearningAuditLedger, SkillCandidateService } from "@/services/learning-constitution";
import type { Evaluation, EvaluationEvidence, EvaluationFailure, EvaluationScore, EvaluationValidity, SkillArtifactRecord, SkillArtifactStore, SkillCandidate, SkillDependency, SkillRegistryEntry } from "@/types/learning-constitution";

const actor = { actorId: "human:teacher", actorType: "HUMAN" as const }; const stamp = "2026-09-02T03:00:00.000Z";
const skill = (skillId: string): SkillCandidate => ({ skillId, name: skillId, description: "Bridge skill", domain: "Planning", skillType: "ATOMIC", scope: [{ type: "PROJECT", id: "noesis" }], prerequisiteSkillIds: [], procedureIds: [], principleIds: [], evidence: [], mastery: null, confidence: "UNKNOWN", status: "UNDEMONSTRATED", limitations: [], failureModes: [], createdBy: actor, createdAt: stamp, immutable: true, capabilityClaim: false, executionPermissionGranted: false });
const evaluation: Evaluation = { evaluationId: "EVAL-1", skillId: "SK-ROADMAP", evaluationType: "TRANSFER", trigger: "PRACTICE_ENGINE", difficulty: 0.7, exerciseIds: ["PE-1"], expectedBehavior: [], actualBehavior: [], context: { contextId: "EC-1", allowedKnowledgeIds: [], hiddenReferenceIds: [], availableTools: [], providedHints: [], exposedExampleIds: [], environmentalConditions: [], frozenAt: stamp }, rubricId: "ER-1", rubricVersion: "1", evaluator: { type: "DETERMINISTIC_EVALUATOR", actor, version: "1", independent: true }, createdAt: stamp };
const score: EvaluationScore = { scoreId: "ES-1", evaluationId: evaluation.evaluationId, dimensionScores: { CORRECTNESS: 0.9, APPLICATION: 0.9, GENERALIZATION: 0.8, BOUNDARY_RECOGNITION: 0.9, EXCEPTION_HANDLING: 0.8, CONSISTENCY: 0.8, CALIBRATION: 0.8 }, overallScore: 0.85, outcome: "PASS", scoredAt: stamp };
const validity: EvaluationValidity = { validityId: "EV-1", evaluationId: evaluation.evaluationId, status: "VALID", reasonCodes: ["EVALUATION_VALID"], checkedAt: stamp };
const evidence: EvaluationEvidence = { evidenceId: "EE-1", evaluationId: evaluation.evaluationId, skillId: evaluation.skillId, exerciseIds: evaluation.exerciseIds, responseIds: ["RESP-1"], scoreId: score.scoreId, validityId: validity.validityId, evaluator: evaluation.evaluator, createdAt: stamp, skillRegistryEffect: "EVIDENCE_ONLY", durableKnowledgeEffect: "NONE", executionPermissionGranted: false };
const store = (): SkillArtifactStore & { all: () => readonly SkillArtifactRecord[] } => { const records: SkillArtifactRecord[] = []; return { append: async (record) => { records.push(record); return record; }, listArtifacts: async (subjectId) => records.filter((record) => record.subjectId === subjectId), all: () => records }; };
const entry = (candidate: SkillCandidate, mastery: number): SkillRegistryEntry => ({ skill: { ...candidate, mastery }, status: "VALIDATED", activeEvidenceCount: 1, revokedEvidenceCount: 0, evaluationCount: 2, assessment: { observedScore: mastery, estimatedMastery: mastery, confidence: "LOW", eligibleForProvisional: true, rationale: [], executionPermissionGranted: false }, lastReviewedAt: null, executionPermissionGranted: false });

describe("Phase 21 evaluation learning bridge", () => {
  it("publishes only valid independent evidence to an existing Skill Registry candidate", async () => {
    const artifacts = store(); const audit = new InMemoryLearningAuditLedger(); await new SkillCandidateService(new ConservativeSkillValidator(), artifacts).submit(skill(evaluation.skillId));
    await expect(new EvaluationSkillRegistryBridgeService(artifacts, audit).attach({ evaluation, score, validity, evidence, workspaceId: "workspace:1", correlationId: "eval:1" })).resolves.toMatchObject({ outcome: "SUCCESS", skillId: evaluation.skillId });
    expect(artifacts.all().map((record) => record.artifactType)).toEqual(["CANDIDATE", "EVIDENCE"]);
    await expect(new EvaluationSkillRegistryBridgeService(artifacts).attach({ evaluation, score, validity: { ...validity, status: "INVALID" }, evidence, workspaceId: "workspace:1", correlationId: "eval:invalid" })).rejects.toThrow("only valid");
  });
  it("refers only validated dependency failures to the weakest prerequisite's practice path", () => {
    const prerequisite = skill("SK-DEPENDENCY"); const edge: SkillDependency = { dependencyId: "SD-1", prerequisite: { skillId: prerequisite.skillId }, dependent: { skillId: evaluation.skillId }, relationshipType: "PREREQUISITE", strength: 0.9, requiredMasteryThreshold: 70, evidenceIds: ["EV-1"], provenance: { provenanceIds: ["PR-1"], assertedBy: actor, assertedAt: stamp }, lifecycle: "ACTIVE", graphVersionId: "SG-1", rationale: "Required." }; const failure: EvaluationFailure = { failureId: "EF-1", evaluationId: evaluation.evaluationId, dimension: "APPLICATION", category: "DEPENDENCY_FAILURE", relatedSkillId: prerequisite.skillId, rationale: "Dependency sequencing failed.", createdAt: stamp };
    expect(new EvaluationPracticeReferralService().refer({ evaluation, validity, failure, dependencies: [edge], registryEntries: new Map([[evaluation.skillId, entry(skill(evaluation.skillId), 80)], [prerequisite.skillId, entry(prerequisite, 50)]]) })).toMatchObject({ recommendedSkillId: prerequisite.skillId, transferLevel: "EXACT", source: "PREREQUISITE_REMEDIATION" });
    expect(new EvaluationPracticeReferralService().refer({ evaluation, validity: { ...validity, status: "INVALID" }, failure, dependencies: [edge], registryEntries: new Map() })).toBeNull();
  });
});
