import { describe, expect, it } from "vitest";
import { InMemoryLearningAuditLedger, KnowledgeGapArtifactService, KnowledgeGapDetector } from "@/services/learning-constitution";
import type { KnowledgeGapArtifactRecord, KnowledgeGapArtifactStore, KnowledgeRequirement } from "@/types/learning-constitution";
const at = "2026-09-02T23:30:00.000Z"; const agent = { actorId: "agent:noesis", actorType: "AGENT" as const }; const store = (): KnowledgeGapArtifactStore => { const records: KnowledgeGapArtifactRecord[] = []; return { append: async (record) => { records.push(record); return record; }, listArtifacts: async (id) => records.filter((record) => record.subjectId === id), listWorkspaceArtifacts: async () => records }; }; const requirement: KnowledgeRequirement = { requirementId: "RK-1", subject: "System-design approach", requiredDimensions: ["isolation", "cost"], scope: "GENERAL", requiredFor: "DECISION_PREDICTION", importance: "HIGH" }; const assess = (evidence: Parameters<KnowledgeGapDetector["assess"]>[0]["evidence"], retrievalStatus: "COMPLETE" | "INCOMPLETE" = "COMPLETE") => new KnowledgeGapDetector().assess({ gapId: `G-${evidence.length}-${retrievalStatus}`, requirement, evidence, retrievalStatus, blocking: true, createdBy: agent, createdAt: at });
describe("Phase 25 knowledge-gap detection", () => {
  it("keeps unknown distinct from incomplete retrieval and from a low confidence inference", () => { const gap = assess([], "INCOMPLETE"); expect(gap).toMatchObject({ currentState: "UNKNOWN", retrievalStatus: "INCOMPLETE", confidence: null, resolutionStrategy: "RETRIEVE_MORE_EVIDENCE" }); });
  it("represents partial, uncertain, conflicting, and untested knowledge as different mechanical states", () => { const partial = assess([{ evidenceId: "E-1", dimension: "isolation", established: true, conflicting: false, interpretationCertain: true, validatedInScope: true, sourceId: "P-1", summary: "Known." }]); const uncertain = assess([{ evidenceId: "E-1", dimension: "isolation", established: true, conflicting: false, interpretationCertain: false, validatedInScope: true, sourceId: "P-1", summary: "Ambiguous." }, { evidenceId: "E-2", dimension: "cost", established: true, conflicting: false, interpretationCertain: true, validatedInScope: true, sourceId: "P-2", summary: "Known." }]); const conflicting = assess([{ evidenceId: "E-1", dimension: "isolation", established: true, conflicting: true, interpretationCertain: true, validatedInScope: true, sourceId: "P-1", summary: "Conflict." }]); const untested = assess([{ evidenceId: "E-1", dimension: "isolation", established: true, conflicting: false, interpretationCertain: true, validatedInScope: false, sourceId: "P-1", summary: "Known." }, { evidenceId: "E-2", dimension: "cost", established: true, conflicting: false, interpretationCertain: true, validatedInScope: false, sourceId: "P-2", summary: "Known." }]); expect(partial.currentState).toBe("PARTIALLY_KNOWN"); expect(uncertain.currentState).toBe("UNCERTAIN"); expect(conflicting).toMatchObject({ currentState: "CONFLICTING", resolutionStrategy: "INVOKE_CONFLICT_ENGINE" }); expect(untested).toMatchObject({ currentState: "UNTESTED", resolutionStrategy: "GENERATE_PRACTICE" }); });
  it("records first-class gap and lifecycle facts without creating durable knowledge", async () => { const gap = assess([]); const audit = new InMemoryLearningAuditLedger(); await new KnowledgeGapArtifactService(store(), audit).create(gap, "workspace:25", "gap:1"); expect((await audit.list("workspace:25")).map((entry) => entry.event.eventType)).toEqual(["KNOWLEDGE_GAP_DETECTED"]); expect(gap).toMatchObject({ durableKnowledgeEffect: "NONE", executionPermissionGranted: false }); });
});
