import { describe, expect, it } from "vitest";
import { InMemoryLearningAuditLedger, KnowledgeGapArtifactService, KnowledgeGapDecisionPredictionIntegrationService, KnowledgeGapDetector, KnowledgeGapPriorityService, KnowledgeGapSocraticIntegrationService } from "@/services/learning-constitution";
import type { KnowledgeGapArtifactRecord, KnowledgeGapArtifactStore, KnowledgeRequirement } from "@/types/learning-constitution";
const at = "2026-09-03T00:00:00.000Z"; const agent = { actorId: "agent:noesis", actorType: "AGENT" as const }; const store = (): KnowledgeGapArtifactStore => { const records: KnowledgeGapArtifactRecord[] = []; return { append: async (record) => { records.push(record); return record; }, listArtifacts: async (id) => records.filter((record) => record.subjectId === id), listWorkspaceArtifacts: async () => records }; }; const requirement = (id: string, importance: KnowledgeRequirement["importance"]): KnowledgeRequirement => ({ requirementId: id, subject: id, requiredDimensions: ["dimension"], scope: "GENERAL", requiredFor: "DECISION_PREDICTION", importance }); const gap = (id: string, importance: KnowledgeRequirement["importance"], blocking: boolean) => new KnowledgeGapDetector().assess({ gapId: id, requirement: requirement(id, importance), evidence: [], retrievalStatus: "COMPLETE", blocking, createdBy: agent, createdAt: at });
describe("Phase 25 materiality and integration", () => {
  it("prioritizes critical blocking gaps and uses them as the sole Socratic target", () => { const low = gap("G-low", "LOW", false); const critical = gap("G-critical", "CRITICAL", true); expect(new KnowledgeGapPriorityService().prioritize([low, critical]).map((item) => item.gapId)).toEqual(["G-critical", "G-low"]); expect(new KnowledgeGapSocraticIntegrationService().nextTarget([low, critical])?.gapId).toBe("G-critical"); });
  it("blocks decision prediction for material gaps but exposes non-blocking gaps as limitations", () => { const blocking = gap("G-block", "HIGH", true); const minor = gap("G-minor", "LOW", false); expect(new KnowledgeGapDecisionPredictionIntegrationService().eligibility([minor])).toMatchObject({ eligible: true, status: "PROCEED_WITH_EXPOSED_LIMITATIONS", limitationGapIds: ["G-minor"] }); expect(new KnowledgeGapDecisionPredictionIntegrationService().eligibility([minor, blocking])).toMatchObject({ eligible: false, status: "BLOCKED_BY_KNOWLEDGE_GAP", blockingGapIds: ["G-block"] }); });
  it("reopens a resolved gap as an immutable non-known reassessment when evidence destabilizes it", async () => { const resolved = { ...new KnowledgeGapDetector().assess({ gapId: "G-reopen", requirement: requirement("R", "HIGH"), evidence: [{ evidenceId: "E", dimension: "dimension", established: true, conflicting: false, interpretationCertain: true, validatedInScope: true, sourceId: "P", summary: "Known." }], retrievalStatus: "COMPLETE", blocking: true, createdBy: agent, createdAt: at }), status: "RESOLVED" as const }; const reopened = { ...resolved, currentState: "CONFLICTING" as const, conflictingEvidenceIds: ["E-conflict"], status: "REOPENED" as const, lastEvaluatedAt: "2026-09-03T01:00:00.000Z" }; const audit = new InMemoryLearningAuditLedger(); await new KnowledgeGapArtifactService(store(), audit).reopen(resolved, reopened, "New evidence conflicts with the established record.", "workspace:25", "gap:reopen"); expect((await audit.list("workspace:25")).map((entry) => entry.event.eventType)).toEqual(["KNOWLEDGE_GAP_REOPENED"]); });
});
