import { describe, expect, it } from "vitest";
import { AdversarialExaminationAuditService, AdversarialExaminerService, AdversarialFindingRouter, InMemoryLearningAuditLedger } from "@/services/learning-constitution";
import type { AdversarialExaminationArtifactRecord, AdversarialExaminationArtifactStore } from "@/types/learning-constitution";

const at = "2026-09-03T20:00:00.000Z";
const examiner = { actorId: "agent:examiner", actorType: "AGENT" as const };
const store = (): AdversarialExaminationArtifactStore => { const records: AdversarialExaminationArtifactRecord[] = []; return { append: async (record) => { records.push(record); return record; }, listArtifacts: async (subjectId) => records.filter((record) => record.subjectId === subjectId), listWorkspaceArtifacts: async () => records }; };

describe("Phase 32 integrated acceptance", () => {
  it("exposes a brittle mastery claim with an unseen changed-assumption test without turning examiner failure into an automatic correction", async () => {
    const artifacts = store(); const lease = { leaseId: "LEASE-EXIT", proposalId: "PROP-EXIT", approvalId: "APPROVAL-EXIT", scope: "SYSTEM_DESIGN", method: "TARGETED_EVALUATION" as const, maximumQuestions: 0, issuedBy: { actorId: "human:teacher", actorType: "HUMAN" as const }, issuedAt: at, expiresAt: "2026-09-04T20:00:00.000Z", status: "ACTIVE" as const };
    const exam = { examId: "EXAM-EXIT", curriculumId: "CUR-EXIT", lease, skillId: "SK-EXIT", competencyClaimId: "MASTERY-EXIT", maximumTests: 2, testsUsed: 0, status: "ACTIVE" as const, examinerContextHash: "examiner-hash", learnerContextHash: "learner-hash", startedAt: at, createdBy: examiner, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const };
    const hypothesis = { hypothesisId: "H-EXIT", skillId: exam.skillId, competencyClaimId: exam.competencyClaimId, suspectedMechanism: "The learner applies a familiar rule without testing an implicit prerequisite.", boundary: "Implicit prerequisite absent", expectedFailureSignal: "Uses the normal solution despite changed assumption.", createdBy: examiner, createdAt: at, immutable: true as const, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const };
    const test = { testId: "TEST-EXIT", examId: exam.examId, attackType: "CHANGED_ASSUMPTION" as const, hypothesisId: hypothesis.hypothesisId, scenario: "A familiar architecture scenario with one unstated prerequisite removed.", constraints: ["State whether more evidence is required."], targetDimensions: ["BOUNDARY_RECOGNITION"], learnerContextHash: exam.learnerContextHash, examinerContextHash: exam.examinerContextHash, rubricId: "RUBRIC-EXIT", integrity: "VALID" as const, createdAt: at, immutable: true as const, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const };
    const rubric = { rubricId: test.rubricId, testId: test.testId, hiddenDifference: "Required prerequisite is absent.", expectedReasoning: ["Reject blind reuse of the familiar rule."], plausibleWrongSolutions: ["Apply the familiar rule."], scoringCriteria: ["Detect changed assumption"], isolation: "INDEPENDENT" as const, revealedAt: null, immutable: true as const, examinerOnly: true as const, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const };
    const service = new AdversarialExaminerService(artifacts); await service.start(exam, at); await service.registerHypothesis(hypothesis); await service.freeze(test, rubric, exam, at); const attempt = { attemptId: "ATTEMPT-EXIT", testId: test.testId, learnerContextHash: test.learnerContextHash, response: "Apply the familiar rule.", confidence: .98, committedAt: at, hiddenMaterialExposedBeforeCommit: false, committedBy: examiner, immutable: true as const }; expect(await service.commit(attempt, test, rubric)).toMatchObject({ evaluationPermitted: true }); const finding = { findingId: "FINDING-EXIT", testId: test.testId, attemptId: attempt.attemptId, outcome: "SYSTEMATIC_FAILURE" as const, failureClasses: ["BOUNDARY_FAILURE", "CALIBRATION_FAILURE"], diagnosticRationale: "The learner missed the hidden prerequisite while highly confident.", confidenceCalibrationConcern: true, challengeStatus: "NONE" as const, evaluatorIndependent: true, createdAt: at, immutable: true as const, durableKnowledgeEffect: "NONE" as const, executionPermissionGranted: false as const }; const evidence = await service.recordFinding(finding, test, attempt, rubric, exam.skillId, false); expect(evidence).toMatchObject({ evidenceQuality: "HIGH", skillRegistryEffect: "EVIDENCE_ONLY", durableKnowledgeEffect: "NONE", executionPermissionGranted: false }); expect(new AdversarialFindingRouter().route(finding)).toMatchObject({ route: "MASTERY_REASSESSMENT" }); const recommendation = await service.recommendReassessment({ recommendationId: "REASSESS-EXIT", skillId: exam.skillId, competencyClaimId: exam.competencyClaimId, action: "SUSPEND_MASTERY", scope: ["implicit prerequisites"], basisFindingIds: [finding.findingId], requiresReview: true, createdAt: at, createdBy: examiner, executionPermissionGranted: false, durableKnowledgeEffect: "NONE" }); expect(recommendation).toMatchObject({ requiresReview: true, action: "SUSPEND_MASTERY", durableKnowledgeEffect: "NONE" }); const audit = new InMemoryLearningAuditLedger(); await new AdversarialExaminationAuditService(audit).record({ eventId: "AUDIT-EXIT", eventType: "MASTERY_CHALLENGED", workspaceId: "workspace:32", examId: exam.examId, occurredAt: at, actor: examiner, correlationId: "phase32", skillId: exam.skillId, testId: test.testId, findingId: finding.findingId, payload: { outcome: finding.outcome } }); expect((await audit.list("workspace:32")).map((entry) => entry.event.eventType)).toContain("MASTERY_CHALLENGED"); expect((await artifacts.listWorkspaceArtifacts()).map((artifact) => artifact.artifactType)).toEqual(expect.arrayContaining(["EXAM", "HYPOTHESIS", "TEST", "RUBRIC", "ATTEMPT", "FINDING", "EVIDENCE", "REASSESSMENT"]));
  });
});
