import { describe, expect, it } from "vitest";
import { AutonomousPracticeAuditService, AutonomousPracticeController, AutonomousPracticeFailureRouter, AutonomousPracticeIntegrityService, InMemoryLearningAuditLedger } from "@/services/learning-constitution";
import type { AutonomousPracticeArtifactRecord, AutonomousPracticeArtifactStore } from "@/types/learning-constitution";

const at = "2026-09-03T18:00:00.000Z";
const agent = { actorId: "agent:noesis", actorType: "AGENT" as const };
const store = (): AutonomousPracticeArtifactStore => { const records: AutonomousPracticeArtifactRecord[] = []; return { append: async (record) => { records.push(record); return record; }, listArtifacts: async (subjectId) => records.filter((record) => record.subjectId === subjectId), listWorkspaceArtifacts: async () => records }; };

describe("Phase 31 integrated acceptance", () => {
  it("runs a lease-bounded isolated practice attempt, preserves evidence-only status, and suspends conflicted material", async () => {
    const artifacts = store(); const lease = { leaseId: "LEASE-EXIT", proposalId: "PROPOSAL-EXIT", approvalId: "APPROVAL-EXIT", scope: "SYSTEM_DESIGN", method: "PRACTICE_SEQUENCE" as const, maximumQuestions: 0, issuedBy: { actorId: "human:teacher", actorType: "HUMAN" as const }, issuedAt: at, expiresAt: "2026-09-04T18:00:00.000Z", status: "ACTIVE" as const };
    const session = { sessionId: "APS-EXIT", curriculumId: "CUR-EXIT", lease, skillId: "SK-EXIT", targetDimensions: ["APPLICATION"], maximumExercises: 2, exercisesUsed: 0, status: "ACTIVE" as const, startedAt: at, haltedAt: null, haltReason: null, createdBy: agent, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const };
    const snapshot = { snapshotId: "SNAP-EXIT", sessionId: session.sessionId, practiceExerciseId: "PX-EXIT", skillId: session.skillId, difficulty: .5, transferLevel: "NOVEL" as const, knowledgeBasisIds: ["P-EXIT"], learnerContextHash: "learner-context", evaluatorContextHash: "evaluator-context", answerKeyId: "AK-EXIT", answerKeyHash: "sealed-key-hash", integrityStatus: "VALID" as const, createdAt: at, immutable: true as const, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const };
    const key = { answerKeyId: "AK-EXIT", snapshotId: snapshot.snapshotId, expectedResult: "hidden", rubric: ["hidden"], acceptableVariations: ["hidden"], commonErrors: ["hidden"], isolation: "INDEPENDENT" as const, sealedAt: at, revealedAt: null, immutable: true as const, evaluatorOnly: true as const, executionPermissionGranted: false as const, durableKnowledgeEffect: "NONE" as const };
    const controller = new AutonomousPracticeController(artifacts); await controller.start(session, at); await controller.freeze(snapshot, key, session, at); const attempt = { attemptId: "AT-EXIT", snapshotId: snapshot.snapshotId, learnerContextHash: snapshot.learnerContextHash, response: "learner response", committedAt: at, answerExposureBeforeCommit: false, committedBy: agent, immutable: true as const }; expect(await controller.commitAttempt(attempt, snapshot, key)).toMatchObject({ evaluationPermitted: true }); const evidence = await controller.recordEvidence({ evidenceId: "EV-EXIT", session, snapshot, attempt, key, outcome: "PASS", evaluatorIndependent: true, practiceEvidenceStrength: "STRONG", createdAt: at }); expect(evidence).toMatchObject({ evidenceQuality: "HIGH", skillRegistryEffect: "EVIDENCE_ONLY", durableKnowledgeEffect: "NONE", executionPermissionGranted: false }); expect(new AutonomousPracticeFailureRouter().route({ outcome: "FAIL", failureTypes: ["APPLICATION_FAILURE"], integrityStatus: "VALID" })).toMatchObject({ route: "REFLECTION" }); await new AutonomousPracticeIntegrityService(artifacts).invalidateForConflict({ sessionId: session.sessionId, snapshotId: snapshot.snapshotId, conflictIds: ["CONFLICT-EXIT"], reason: "New conflicting evidence.", occurredAt: at }); const audit = new InMemoryLearningAuditLedger(); await new AutonomousPracticeAuditService(audit).record({ eventId: "AUDIT-EXIT", eventType: "PRACTICE_EVIDENCE_SUBMITTED", workspaceId: "workspace:31", sessionId: session.sessionId, occurredAt: at, actor: agent, correlationId: "phase31", snapshotId: snapshot.snapshotId, payload: { evidenceId: evidence.evidenceId } }); expect((await audit.list("workspace:31")).map((entry) => entry.event.eventType)).toContain("PRACTICE_EVIDENCE_SUBMITTED"); expect((await artifacts.listWorkspaceArtifacts()).map((artifact) => artifact.artifactType)).toEqual(expect.arrayContaining(["SESSION", "EXERCISE_SNAPSHOT", "SEALED_ANSWER_KEY", "ATTEMPT", "EVIDENCE", "INTEGRITY_EVENT"]));
  });
});
