import { describe, expect, it } from "vitest";
import { EvaluationReflectionEvidenceCollector, InMemoryLearningAuditLedger, ReflectionArtifactService, ReflectionCandidateCauseGenerator, ReflectionFailureLocalizationService, ReflectionHistoryAnalyticsService, ReflectionPrerequisiteDiagnosisService, ReflectionRemediationExecutionService, ReflectionRemediationPlanner } from "@/services/learning-constitution";
import type { EvaluationArtifactRecord, EvaluationArtifactStore, EvaluationFailure, PracticeArtifactRecord, PracticeArtifactStore, ReflectionArtifactRecord, ReflectionArtifactStore, SkillCandidate, SkillDependency, SkillRegistryEntry } from "@/types/learning-constitution";

const actor = { actorId: "human:teacher", actorType: "HUMAN" as const }; const stamp = "2026-09-02T12:00:00.000Z";
const score = (evaluationId: string, outcome: "PASS" | "FAIL") => ({ scoreId: `ES:${evaluationId}`, evaluationId, dimensionScores: { CORRECTNESS: outcome === "PASS" ? 0.9 : 0.6, APPLICATION: outcome === "PASS" ? 0.9 : 0.2, GENERALIZATION: 0.8, BOUNDARY_RECOGNITION: 0.9, EXCEPTION_HANDLING: 0.8, CONSISTENCY: 0.8, CALIBRATION: 0.8 }, overallScore: outcome === "PASS" ? 0.88 : 0.45, outcome, scoredAt: stamp } as const);
const evaluations = (): EvaluationArtifactStore => { const failure: EvaluationFailure = { failureId: "EF-1", evaluationId: "EVAL-FAIL", dimension: "APPLICATION", category: "DEPENDENCY_FAILURE", rationale: "Dependency analysis was not retrieved.", createdAt: stamp }; const records: EvaluationArtifactRecord[] = ["EVAL-FAIL", "EVAL-RETEST"].flatMap((id) => [{ artifactId: `SCORE:${id}`, artifactType: "SCORE" as const, subjectId: id, payload: score(id, id === "EVAL-FAIL" ? "FAIL" : "PASS"), createdAt: stamp }, { artifactId: `VALIDITY:${id}`, artifactType: "VALIDITY" as const, subjectId: id, payload: { validityId: `EV:${id}`, evaluationId: id, status: "VALID" as const, reasonCodes: [], checkedAt: stamp }, createdAt: stamp }]); records.push({ artifactId: "FAILURE:EVAL-FAIL", artifactType: "FAILURE", subjectId: "EVAL-FAIL", payload: failure, createdAt: stamp }); return { append: async (record) => { records.push(record); return record; }, listArtifacts: async (subjectId) => records.filter((record) => record.subjectId === subjectId), listWorkspaceArtifacts: async () => records }; };
const reflections = (): ReflectionArtifactStore => { const records: ReflectionArtifactRecord[] = []; return { append: async (record) => { const prior = records.find((item) => item.artifactId === record.artifactId); if (prior) return prior; records.push(record); return record; }, listArtifacts: async (subjectId) => records.filter((record) => record.subjectId === subjectId), listWorkspaceArtifacts: async () => records }; };
const practices = (): PracticeArtifactStore => ({ append: async (record) => record, listArtifacts: async () => [], listWorkspaceArtifacts: async () => [{ artifactId: "PRACTICE_EXERCISE:PE-DEPENDENCY", artifactType: "EXERCISE", subjectId: "PE-DEPENDENCY", payload: { exerciseId: "PE-DEPENDENCY", targetSkillIds: ["SK-DEPENDENCY"] }, createdAt: stamp } as PracticeArtifactRecord] });
const skill = (skillId: string, mastery: number): SkillCandidate => ({ skillId, name: skillId, description: "Exit scenario", domain: "Planning", skillType: "ATOMIC", scope: [{ type: "PROJECT", id: "noesis" }], prerequisiteSkillIds: [], procedureIds: [], principleIds: [], evidence: [], mastery, confidence: "LOW", status: "UNDEMONSTRATED", limitations: [], failureModes: [], createdBy: actor, createdAt: stamp, immutable: true, capabilityClaim: false, executionPermissionGranted: false });
const entry = (candidate: SkillCandidate): SkillRegistryEntry => ({ skill: candidate, status: "VALIDATED", activeEvidenceCount: 1, revokedEvidenceCount: 0, evaluationCount: 2, assessment: { observedScore: candidate.mastery, estimatedMastery: candidate.mastery, confidence: "LOW", eligibleForProvisional: true, rationale: [], executionPermissionGranted: false }, lastReviewedAt: null, executionPermissionGranted: false });

describe("Phase 22 integrated exit scenario", () => {
  it("localizes a failure, repairs only its weak prerequisite, retains the trail, and resolves after reevaluation", async () => {
    const evaluationStore = evaluations(); const reflectionStore = reflections(); const audit = new InMemoryLearningAuditLedger(); const collected = await new EvaluationReflectionEvidenceCollector(evaluationStore).collect("EVAL-FAIL"); const localized = new ReflectionFailureLocalizationService().localize(collected.failures); expect(localized).toMatchObject({ failureType: "PREREQUISITE_GAP", location: "RETRIEVE_KNOWLEDGE" });
    const reflection = { reflectionId: "RF-EXIT", trigger: "EVALUATION_FAILURE" as const, evaluationId: "EVAL-FAIL", skillId: "SK-ROADMAP", expectedOutcome: "Identify dependency order.", observedOutcome: "Dependency was missed.", failureType: localized.failureType, failureLocation: localized.location, relevantKnowledgeIds: [], relevantPrincipleIds: [], relevantProcedureIds: [], relevantExampleIds: [], relevantExceptionIds: [], prerequisiteSkillIds: ["SK-DEPENDENCY"], status: "OPEN" as const, createdBy: actor, createdAt: stamp, resolvedAt: null, masteryEffect: "NONE" as const, durableKnowledgeEffect: "NONE" as const, executionPermissionGranted: false as const }; const service = new ReflectionArtifactService(reflectionStore, audit); await service.createCase(reflection, "workspace:22", "reflection:exit"); await service.transition(reflection.reflectionId, "OPEN", "DIAGNOSING", actor, stamp, "Collecting evaluation evidence.", "workspace:22", "reflection:exit"); await service.recordEvidence(reflection.reflectionId, collected.evidence);
    const candidate = new ReflectionCandidateCauseGenerator().generate({ causeId: "RC-EXIT", reflection, evidence: collected.evidence, createdAt: stamp }); await service.addCandidateCause(candidate); const dependency: SkillDependency = { dependencyId: "SD-1", prerequisite: { skillId: "SK-DEPENDENCY" }, dependent: { skillId: "SK-ROADMAP" }, relationshipType: "PREREQUISITE", strength: 0.9, requiredMasteryThreshold: 70, evidenceIds: ["EV-1"], provenance: { provenanceIds: ["PR-1"], assertedBy: actor, assertedAt: stamp }, lifecycle: "ACTIVE", graphVersionId: "SG-1", rationale: "Required." }; const diagnosis = new ReflectionPrerequisiteDiagnosisService().diagnose({ reflection, dependencies: [dependency], registryEntries: new Map([["SK-ROADMAP", entry(skill("SK-ROADMAP", 82))], ["SK-DEPENDENCY", entry(skill("SK-DEPENDENCY", 52))]]), evidenceIds: candidate.supportingEvidenceIds }); expect(diagnosis).toMatchObject({ status: "RECOMMENDED", targetSkillId: "SK-DEPENDENCY" });
    const selected = { reflectionId: reflection.reflectionId, causeId: candidate.causeId, failureType: candidate.failureType, confidence: candidate.confidence, selectionReason: "Evaluation and prerequisite evidence agree.", selectedBy: actor, selectedAt: stamp, status: "SELECTED" as const }; await service.selectCause(selected, "workspace:22", "reflection:exit"); await service.transition(reflection.reflectionId, "DIAGNOSING", "CAUSE_IDENTIFIED", actor, stamp, "Cause selected.", "workspace:22", "reflection:exit"); const plan = new ReflectionRemediationPlanner().plan({ planId: "RP-EXIT", reflection, selected, prerequisite: diagnosis, createdAt: stamp }); await service.recordRemediationPlan(plan, "workspace:22", "reflection:exit");
    const execution = new ReflectionRemediationExecutionService(reflectionStore, practices(), evaluationStore); await execution.activate({ activationId: "RA-EXIT", planId: plan.planId, reflectionId: reflection.reflectionId, practiceExerciseIds: ["PE-DEPENDENCY"], activatedBy: actor, activatedAt: stamp }); const reevaluation = await execution.linkReevaluation({ reevaluationId: "RR-EXIT", reflectionId: reflection.reflectionId, planId: plan.planId, originalEvaluationId: reflection.evaluationId, reevaluationEvaluationId: "EVAL-RETEST", completedAt: stamp, completedBy: actor }); expect(reevaluation).toMatchObject({ outcome: "PASS" }); await service.transition(reflection.reflectionId, "CAUSE_IDENTIFIED", "REMEDIATION_PLANNED", actor, stamp, "Focused plan created.", "workspace:22", "reflection:exit"); await service.transition(reflection.reflectionId, "REMEDIATION_PLANNED", "REMEDIATION_ACTIVE", actor, stamp, "Practice activated.", "workspace:22", "reflection:exit"); await service.transition(reflection.reflectionId, "REMEDIATION_ACTIVE", "REEVALUATION_PENDING", actor, stamp, "Awaiting reevaluation.", "workspace:22", "reflection:exit"); await service.transition(reflection.reflectionId, "REEVALUATION_PENDING", "RESOLVED", actor, stamp, "Reevaluation passed.", "workspace:22", "reflection:exit");
    const profile = await new ReflectionHistoryAnalyticsService(reflectionStore).profile({ profileId: "RFP-EXIT", skillId: reflection.skillId, analyzedAt: stamp, recurrenceThreshold: 2 }); expect(profile).toMatchObject({ totalCases: 1, recurringFailureTypes: [], masteryEffect: "NONE", durableKnowledgeEffect: "NONE" }); expect((await audit.list("workspace:22")).map((entry) => entry.event.eventType)).toEqual(expect.arrayContaining(["REFLECTION_CASE_CREATED", "REFLECTION_CAUSE_IDENTIFIED", "REFLECTION_REMEDIATION_PLANNED"]));
  });
});
