import { describe, expect, it } from "vitest";
import { StrategyEligibilityService, StrategyExperimentService, StrategyPerformanceService, StrategyRecommendationService, StrategyRegistryService, StrategyRunManager } from "@/services/learning-constitution";
import type { StrategyDefinition, StrategyRegistryArtifact, StrategyRegistryStore, StrategyRun } from "@/types/learning-constitution";

const at = "2026-09-04T06:00:00.000Z";
const human = { actorId: "human:governor", actorType: "HUMAN" as const };
const independent = { actorId: "agent:independent-evaluator", actorType: "AGENT" as const };
const memory = (): StrategyRegistryStore => { const records: StrategyRegistryArtifact[] = []; return { append: async (item) => { const found = records.find((record) => record.artifactId === item.artifactId); if (found) return found; records.push(item); return item; }, listArtifacts: async (id) => records.filter((record) => record.subjectId === id), listWorkspaceArtifacts: async () => records }; };

describe("Phase 37 acceptance: governed strategy evolution", () => {
  it("keeps an evidence-informed learning strategy reviewable, bounded, and non-authoritative throughout", async () => {
    const strategy: StrategyDefinition = { strategyId: "S-ACCEPT-37", name: "Progressive adversarial practice", version: 1, lifecycle: "HYPOTHESIS", purpose: ["PRACTICE", "EVALUATION"], applicableContexts: ["REASONING"], prerequisites: ["BASIC_CONCEPT"], steps: [{ ordinal: 1, primitive: "WORKED_EXAMPLE" }, { ordinal: 2, primitive: "NOVEL_PRACTICE", adaptiveBranch: { condition: "PREREQUISITE_FAILURE", targetOrdinal: 3 } }, { ordinal: 3, primitive: "REMEDIATION" }], parameters: [{ name: "tokenBudget", value: 1000, required: true }], stopConditions: ["MAX_ATTEMPTS", "LEASE_EXPIRED"], parentVersionId: null, evidenceIds: ["PROFILE-ACCEPT-37"], knownExceptions: [], createdBy: human, createdAt: at, learningEffect: "NONE", authorityEffect: "UNCHANGED", executionPermissionGranted: false };
    const registry = new StrategyRegistryService(memory()); await registry.register(strategy);
    const active = { ...strategy, lifecycle: "ACTIVE" as const };
    const eligibility = new StrategyEligibilityService().assess({ strategy: active, context: "REASONING", establishedPrerequisites: ["BASIC_CONCEPT"], budget: { timeMinutes: 45, tokenBudget: 2000, teacherAvailability: "LOW", risk: "MEDIUM", requiredRetention: "HIGH" }, requiredResources: [], availableResources: [] });
    const recommendation = new StrategyRecommendationService().recommend({ recommendationId: "REC-ACCEPT-37", objectiveId: "LO-ACCEPT-37", candidates: [{ strategy: active, eligibility, observedEvidenceState: "EMERGING_PATTERN", observedStrengths: ["Observed transfer signal"], knownCosts: ["Token cost"] }], createdAt: at });
    const run: StrategyRun = { runId: "RUN-ACCEPT-37", strategyId: active.strategyId, strategyVersion: 1, objectiveId: recommendation.objectiveId, approvedPlanId: "PLAN-ACCEPT-37", lease: { leaseId: "LEASE-ACCEPT-37", proposalId: "PROPOSAL-37", approvalId: "APPROVAL-37", scope: "skill:reasoning", method: "PRACTICE_SEQUENCE", maximumQuestions: 5, issuedBy: human, issuedAt: at, expiresAt: "2026-09-05T06:00:00.000Z", status: "ACTIVE" }, scope: "skill:reasoning", maxAttempts: 2, maxQuestions: 5, timeBudgetMinutes: 45, tokenBudget: 1000, attemptsUsed: 0, questionsUsed: 0, tokensUsed: 0, status: "READY", stopReason: null, startedAt: at, completedAt: null, adaptiveBranchHistory: [], durableKnowledgeEffect: "NONE", authorityEffect: "UNCHANGED", executionPermissionGranted: false };
    const started = new StrategyRunManager().start(run, at);
    const performance = new StrategyPerformanceService(); const measurement = { runId: started.runId, strategyId: started.strategyId, context: "REASONING" as const, immediateGain: 30, retention: 40, generalization: 45, boundaryRecognition: 70, adversarialPerformance: 50, correctionCount: 2, humanInterventionCount: 1, tokenCost: 400, timeMinutes: 25, valid: true, observedAt: at };
    const profile = performance.profile({ profileId: "PROFILE-ACCEPT-37", strategyId: started.strategyId, context: "REASONING", measurements: [measurement, { ...measurement, runId: "RUN-38" }, { ...measurement, runId: "RUN-39" }], createdAt: at });
    const failure = performance.detect({ failureId: "FAIL-ACCEPT-37", measurement, evidenceIds: [profile.profileId], createdAt: at })!;
    const experiments = new StrategyExperimentService(); const hypothesis = experiments.hypothesize({ hypothesisId: "HYP-ACCEPT-37", strategyId: active.strategyId, proposedChange: "Add a second adversarial test.", profiles: [profile], createdAt: at });
    const experiment = { experimentId: "EXP-ACCEPT-37", hypothesisId: hypothesis.hypothesisId, controlStrategyId: active.strategyId, variantStrategyId: "S-ACCEPT-37X", metrics: ["IMMEDIATE_GAIN", "RETENTION", "ADVERSARIAL_PERFORMANCE"] as const, independentEvaluatorId: independent.actorId, status: "COMPLETED" as const, approvedBy: human, createdAt: at, executionPermissionGranted: false as const, authorityEffect: "UNCHANGED" as const };
    const evaluation = experiments.evaluate({ evaluationId: "EVAL-ACCEPT-37", experiment, evaluator: independent, result: "SUPPORTS_VARIANT", retentionMeasured: true, adversarialReviewPassed: true, limitations: ["Small sample."], completedAt: at });
    const decision = experiments.decide({ decisionId: "DECISION-ACCEPT-37", strategyId: active.strategyId, version: 2, decision: "APPROVE", evaluation, evidenceIds: [hypothesis.hypothesisId, experiment.experimentId, evaluation.evaluationId], decidedBy: human, reason: "Governed review passed.", decidedAt: at });
    expect({ recommendation, started, failure, hypothesis, evaluation, decision }).toMatchObject({ recommendation: { status: "AWAITING_APPROVAL", autonomousPlanChangeAuthorized: false, executionPermissionGranted: false }, started: { authorityEffect: "UNCHANGED", executionPermissionGranted: false }, failure: { status: "REQUIRES_REVIEW", recommendationOnly: true }, hypothesis: { requiresGovernedReview: true, autonomousAdoptionAuthorized: false }, evaluation: { independent: true, authorityEffect: "UNCHANGED" }, decision: { createsExecutionPermission: false, authorityEffect: "UNCHANGED" } });
  });
});
