import { describe, expect, it } from "vitest";
import { SkillBottleneckDetectionService, SkillCandidateService, SkillDependencyAdmissionService, SkillEvaluationService, SkillGraphInspectionService, SkillGraphProjectionService, SkillReadinessService, SkillRegistryProjectionService, SkillRemediationPlanBuilder, SkillRemediationPlanService, ConservativeSkillValidator } from "@/services/learning-constitution";
import type { GateDecision, SkillArtifactRecord, SkillArtifactStore, SkillCandidate, SkillDependency, SkillGraphArtifactRecord, SkillGraphArtifactStore } from "@/types/learning-constitution";

const actor = { actorId: "human:teacher", actorType: "HUMAN" as const };
const timestamp = "2026-09-01T00:00:00.000Z";
const gate = (candidateId: string): GateDecision => ({ evaluationId: `gate:${candidateId}`, candidateId, outcome: "ACCEPT", reasonCodes: [], checks: [], inputFingerprint: `fingerprint:${candidateId}`, context: { gateVersion: "9", constitutionVersion: "1", taxonomyVersion: "1", authorityPolicyVersion: "1", validationPolicyVersion: "1", conflictEngineVersion: "1", registryVersion: "18", learningIntent: "APPROVED", decisionActorId: actor.actorId }, authorityEffect: "UNCHANGED", executionPermissionGranted: false });
const skill = (skillId: string): SkillCandidate => ({ skillId, name: skillId, description: "Phase 19 exit capability", domain: "Planning", skillType: "ATOMIC", scope: [{ type: "PROJECT", id: "noesis" }], prerequisiteSkillIds: [], procedureIds: [], principleIds: [], evidence: [{ evidenceId: `EV-CANDIDATE:${skillId}`, skillId, outcome: "SUCCESS", assistance: "INDEPENDENT", context: "controlled evaluation", provenanceId: `PR:${skillId}`, observedAt: timestamp, revoked: false }], mastery: null, confidence: "UNKNOWN", status: "UNDEMONSTRATED", limitations: [], failureModes: [], createdBy: actor, createdAt: timestamp, immutable: true, capabilityClaim: false, executionPermissionGranted: false });
const dependency = (dependencyId: string, prerequisite: string, dependent: string, graphVersionId: string): SkillDependency => ({ dependencyId, prerequisite: { skillId: prerequisite }, dependent: { skillId: dependent }, relationshipType: "PREREQUISITE", strength: 0.9, requiredMasteryThreshold: 70, evidenceIds: [`EV:${dependencyId}`], provenance: { provenanceIds: [`PR:${dependencyId}`], assertedBy: actor, assertedAt: timestamp }, lifecycle: "CANDIDATE", graphVersionId, rationale: "Validated Phase 19 exit dependency." });
const artifactStore = (): SkillArtifactStore => { const records: SkillArtifactRecord[] = []; return { append: async (record) => { const replay = records.find((item) => item.artifactId === record.artifactId); if (replay) return replay; records.push(record); return record; }, listArtifacts: async (skillId) => records.filter((record) => record.subjectId === skillId), listWorkspaceArtifacts: async () => [...records] }; };
const graphStore = (): SkillGraphArtifactStore => { const records: SkillGraphArtifactRecord[] = []; return { append: async (record) => { const replay = records.find((item) => item.artifactId === record.artifactId); if (replay) return replay; records.push(record); return record; }, listWorkspaceArtifacts: async () => [...records] }; };

describe("Phase 19 integrated exit scenario", () => {
  it("localizes Dependency Analysis, remediates it, and makes Architecture Roadmap Planning ready without manufacturing mastery", async () => {
    const artifacts = artifactStore(); const graphArtifacts = graphStore();
    const candidates = new SkillCandidateService(new ConservativeSkillValidator(), artifacts);
    const evaluations = new SkillEvaluationService(artifacts);
    const skillIds = ["SK-REQUIREMENT-ANALYSIS", "SK-PROBLEM-DECOMPOSITION", "SK-DEPENDENCY-ANALYSIS", "SK-ESTIMATION", "SK-ARCHITECTURE-COMPREHENSION", "SK-ROADMAP-PLANNING", "SK-ARCHITECTURE-ROADMAP-PLANNING"];
    for (const skillId of skillIds) await candidates.submit(skill(skillId));
    const recordPair = async (skillId: string, score: number, prefix = "baseline") => { await evaluations.record({ evaluationId: `${prefix}:1:${skillId}`, skillId, score, evaluator: actor, evidenceIds: [`EV:${prefix}:1:${skillId}`], createdAt: timestamp, immutable: true }); await evaluations.record({ evaluationId: `${prefix}:2:${skillId}`, skillId, score, evaluator: actor, evidenceIds: [`EV:${prefix}:2:${skillId}`], createdAt: timestamp, immutable: true }); };
    await recordPair("SK-REQUIREMENT-ANALYSIS", 91); await recordPair("SK-PROBLEM-DECOMPOSITION", 87); await recordPair("SK-DEPENDENCY-ANALYSIS", 58); await recordPair("SK-ESTIMATION", 84); await recordPair("SK-ARCHITECTURE-COMPREHENSION", 88); await recordPair("SK-ROADMAP-PLANNING", 82);
    await evaluations.record({ evaluationId: "failure:architecture-roadmap", skillId: "SK-ARCHITECTURE-ROADMAP-PLANNING", score: 40, evaluator: actor, evidenceIds: ["EV-FAILURE:ARCHITECTURE-ROADMAP"], createdAt: timestamp, immutable: true });
    const admit = new SkillDependencyAdmissionService(graphArtifacts);
    const edges = [dependency("SD-1", "SK-REQUIREMENT-ANALYSIS", "SK-PROBLEM-DECOMPOSITION", "SG-V1"), dependency("SD-2", "SK-PROBLEM-DECOMPOSITION", "SK-DEPENDENCY-ANALYSIS", "SG-V2"), dependency("SD-3", "SK-DEPENDENCY-ANALYSIS", "SK-ROADMAP-PLANNING", "SG-V3"), dependency("SD-4", "SK-ESTIMATION", "SK-ROADMAP-PLANNING", "SG-V4"), dependency("SD-5", "SK-ROADMAP-PLANNING", "SK-ARCHITECTURE-ROADMAP-PLANNING", "SG-V5"), dependency("SD-6", "SK-ARCHITECTURE-COMPREHENSION", "SK-ARCHITECTURE-ROADMAP-PLANNING", "SG-V6")];
    for (const edge of edges) await admit.admit({ dependency: edge, gateDecision: gate(edge.dependencyId), workspaceId: "workspace:exit", correlationId: edge.dependencyId, changeReason: "Phase 19 exit scenario." });
    const registry = new SkillRegistryProjectionService(artifacts); const entries = await registry.list(skillIds); const entryMap = new Map(entries.map((entry) => [entry.skill.skillId, entry])); const projection = await new SkillGraphProjectionService(graphArtifacts).get();
    expect(new SkillReadinessService().assess({ skillId: "SK-ARCHITECTURE-ROADMAP-PLANNING", dependencies: projection.dependencies, registryEntries: entryMap })).toMatchObject({ state: "LOCKED", blocked: true });
    const diagnosis = new SkillBottleneckDetectionService().diagnose({ targetSkillId: "SK-ARCHITECTURE-ROADMAP-PLANNING", dependencies: projection.dependencies, registryEntries: entryMap, failedEvaluationEvidenceIds: ["EV-FAILURE:ARCHITECTURE-ROADMAP"] });
    expect(diagnosis).toMatchObject({ status: "RECOMMENDATION", hypotheses: [expect.objectContaining({ prerequisiteSkillId: "SK-DEPENDENCY-ANALYSIS", dependencyId: "SD-3" })] });
    const plan = new SkillRemediationPlanBuilder().build({ planId: "RP-EXIT-1", diagnosis, graphVersionId: "SG-V6", procedureIds: ["PX-DEPENDENCY-PRACTICE"], exampleIds: ["EX-DEPENDENCY-1"], createdBy: actor, createdAt: timestamp });
    const remediation = new SkillRemediationPlanService(graphArtifacts); await remediation.create(plan, "workspace:exit", "RP-EXIT-1"); await remediation.activate({ planId: plan.planId, actor, activatedAt: "2026-09-01T00:01:00.000Z" }, "workspace:exit", "RP-EXIT-1");
    await recordPair("SK-DEPENDENCY-ANALYSIS", 82, "remediation"); await recordPair("SK-ROADMAP-PLANNING", 85, "retest"); await recordPair("SK-ARCHITECTURE-ROADMAP-PLANNING", 82, "retest");
    const updatedEntries = new Map((await registry.list(skillIds)).map((entry) => [entry.skill.skillId, entry]));
    expect(new SkillReadinessService().assess({ skillId: "SK-ARCHITECTURE-ROADMAP-PLANNING", dependencies: projection.dependencies, registryEntries: updatedEntries })).toMatchObject({ state: "READY", blocked: false });
    expect(new SkillGraphInspectionService().inspect({ targetSkillId: "SK-ARCHITECTURE-ROADMAP-PLANNING", projection: await new SkillGraphProjectionService(graphArtifacts).get(), registryEntries: updatedEntries, artifacts: await graphArtifacts.listWorkspaceArtifacts() })).toMatchObject({ remediationPlans: [expect.objectContaining({ planId: "RP-EXIT-1" })], versions: expect.arrayContaining([expect.objectContaining({ graphVersionId: "SG-V6" })]) });
  });
});
