import { describe, expect, it } from "vitest";
import { InMemoryLearningAuditLedger, SocraticKnowledgeMapBuilder, SocraticKnowledgeRetrievalService, SocraticLearningPipelineHandoffService, SocraticQuestionIntelligenceService, SocraticSessionService, SocraticValidationService, SocraticWorkingModelService } from "@/services/learning-constitution";
import type { LearningObjective, SocraticArtifactRecord, SocraticArtifactStore, SocraticKnowledgeSource, SocraticSession } from "@/types/learning-constitution";
const at = "2026-09-02T19:00:00.000Z"; const human = { actorId: "human:teacher", actorType: "HUMAN" as const }; const store = (): SocraticArtifactStore => { const records: SocraticArtifactRecord[] = []; return { append: async (record) => { records.push(record); return record; }, listArtifacts: async (id) => records.filter((record) => record.subjectId === id), listWorkspaceArtifacts: async () => records }; };
describe("Phase 23 integrated acceptance", () => {
  it("retrieves prior knowledge, asks one discriminating question, updates a provisional model, validates it, and submits only to the gate", async () => {
    const objective: LearningObjective = { objectiveId: "LO-EXIT", objective: "Learn how the human approaches system design.", teacher: human, scope: "GENERAL", scopeId: null, desiredDepth: "HIGH", successCriteria: ["Identify tradeoffs", "Predict a novel decision"], status: "ACTIVE", createdBy: human, createdAt: at, durableKnowledgeEffect: "NONE", executionPermissionGranted: false }; const source: SocraticKnowledgeSource = { retrieve: async () => [{ observationId: "D-1", sourceType: "DECISION", sourceId: "D-1", scope: "GENERAL", summary: "The human separates components for failure isolation.", confidence: 0.8, createdAt: at }] }; const observations = await new SocraticKnowledgeRetrievalService([source]).retrieve(objective); const map = new SocraticKnowledgeMapBuilder().build({ mapId: "KM-EXIT-1", objective, dimensions: ["Failure isolation", "Operational simplicity"], observations, createdAt: at }); expect(map.nodes.map((node) => node.state)).toEqual(["INFERRED", "UNKNOWN"]);
    const session: SocraticSession = { sessionId: "SS-EXIT", objectiveId: objective.objectiveId, status: "ACTIVE", knowledgeMapId: map.mapId, questionBudget: { preferred: 3, maximum: 5 }, questionsAsked: [], uncertaintyBefore: 0.75, uncertaintyCurrent: 0.75, informationGain: 0, createdBy: human, createdAt: at, durableLearningStatus: "NOT_YET_EVALUATED", durableKnowledgeEffect: "NONE", executionPermissionGranted: false }; const audit = new InMemoryLearningAuditLedger(); await new SocraticSessionService(store(), audit).start({ objective, knowledgeMap: map, session, workspaceId: "workspace:23", correlationId: "socratic:exit" }); const intelligence = new SocraticQuestionIntelligenceService(); const candidate = intelligence.score({ candidateId: "QC-EXIT", sessionId: session.sessionId, question: "If separation improved isolation but doubled operational complexity, what would determine your choice?", questionType: "COUNTERFACTUAL", targetNodeIds: [map.nodes[0]!.nodeId, map.nodes[1]!.nodeId], hypothesisIds: ["H-EXIT-1", "H-EXIT-2"], uncertaintyReduction: 0.92, objectiveRelevance: 0.96, hypothesisSeparation: 0.9, reuseValue: 0.8, humanEffort: "MODERATE", createdAt: at }); const question = intelligence.select([candidate], 0, 5, human, at); expect(question.questionBudgetPosition).toBe(1);
    const answer = { answerId: "HA-EXIT", sessionId: session.sessionId, questionId: question.questionId, answer: "Keep it together unless separation solves a concrete isolation or security problem.", answeredBy: human, answeredAt: at, workingModelOnly: true as const, durableKnowledgeEffect: "NONE" as const, executionPermissionGranted: false as const }; const revised = new SocraticWorkingModelService().update({ updateId: "WM-EXIT", nextMapId: "KM-EXIT-2", map, answer, targetNodeIds: [map.nodes[0]!.nodeId, map.nodes[1]!.nodeId], createdAt: at }); expect(revised.map.workingModelOnly).toBe(true); const validation = new SocraticValidationService(); const prediction = validation.createPrediction({ predictionId: "PV-EXIT", sessionId: session.sessionId, scenario: "A small app has no concrete isolation need but could be split for theoretical scale.", predictedJudgment: "Keep it together for now.", rationale: "The answer conditioned separation on a real isolation or security benefit.", supportingHypothesisIds: ["H-EXIT-1"], boundaryStatement: "Separate when security or failure isolation is concretely required.", createdBy: human, createdAt: at, workingModelOnly: true }); const review = { reviewId: "PR-EXIT", predictionId: prediction.predictionId, outcome: "CONFIRMED" as const, feedback: "Accurate.", reviewedBy: human, reviewedAt: at, workingModelOnly: true as const }; const handoff = validation.createTeachBackHandoff({ handoffId: "TH-EXIT", sessionId: session.sessionId, objective, lesson: "Prefer separation only for concrete operational value.", scope: "General system design", sourceExamples: [prediction.scenario], actor: human, createdAt: at }); const submission = await new SocraticLearningPipelineHandoffService(store(), audit).submit({ submission: { submissionId: "CS-EXIT", sessionId: session.sessionId, candidateId: "CK-EXIT", claim: "Separate components only when practical isolation, security, or operational value justifies it.", sourceAnswerIds: [answer.answerId], hypothesisIds: ["H-EXIT-1"], predictionReviewId: review.reviewId, teachBackHandoffId: handoff.handoffId, submittedBy: human, submittedAt: at, status: "GATE_SUBMISSION_REQUIRED", durableKnowledgeEffect: "NONE", executionPermissionGranted: false }, predictionReview: review, handoff, workspaceId: "workspace:23", correlationId: "socratic:exit" }); expect(submission).toMatchObject({ status: "GATE_SUBMISSION_REQUIRED", durableKnowledgeEffect: "NONE" }); expect((await audit.list("workspace:23")).map((entry) => entry.event.eventType)).toContain("CANDIDATE_KNOWLEDGE_SUBMITTED");
  });
});
