import { describe, expect, it } from "vitest";
import { ConservativePreferenceValidator, InMemoryLearningAuditLedger, PreferenceCandidateService, PreferenceHumanReviewService, PreferenceIntegrationService, PreferenceInterpretationService, PreferenceLifecycleService, PreferenceReinforcementService, PreferenceResolverService } from "@/services/learning-constitution";
import type { PreferenceCandidate } from "@/types/learning-constitution";
const now = "2026-09-01T00:00:00.000Z"; const actor = { actorId: "human:george", actorType: "HUMAN" as const };
const candidate = (overrides: Partial<PreferenceCandidate> = {}): PreferenceCandidate => ({ preferenceId: "pref:1", ownerId: "user:george", subject: "implementation plans", preferredOption: "concise plans", polarity: "PREFER", scope: [{ type: "PROJECT", id: "noesis" }], strength: "STRONG", evidence: [{ evidenceId: "evidence:1", kind: "EXPLICIT_STATEMENT", provenanceId: "teaching:1", observedAt: now, weight: 1 }], lastReinforcedAt: now, exceptions: [], confidence: 0.9, provenanceIds: ["teaching:1"], authority: "HUMAN_PREFERENCE", status: "CANDIDATE", universalClaim: false, directiveClaim: false, principleClaim: false, createdBy: actor, createdAt: now, immutable: true, executionPermissionGranted: false, ...overrides });
describe("Phase 16 preference anti-overgeneralization boundary", () => {
  it("accepts a supported, owner-scoped preference without granting authority", async () => { const audit = new InMemoryLearningAuditLedger(); await expect(new PreferenceCandidateService(new ConservativePreferenceValidator(), audit).assess(candidate(), "workspace:1", "pref:1")).resolves.toMatchObject({ status: "VALID", authorityEffect: "UNCHANGED", executionPermissionGranted: false }); expect((await audit.list("workspace:1"))[0]?.event.eventType).toBe("PREFERENCE_CANDIDATE_CREATED"); });
  it("rejects preference language that claims a directive, principle, or universal rule", () => { expect(new ConservativePreferenceValidator().validate(candidate({ universalClaim: true, directiveClaim: true, principleClaim: true }))).toMatchObject({ status: "REJECT", reasonCodes: expect.arrayContaining(["PREFERENCE_CLAIMS_UNIVERSAL_RULE", "PREFERENCE_CLAIMS_DIRECTIVE", "PREFERENCE_CLAIMS_PRINCIPLE"]) }); });
  it("defers global scope rather than allowing mandatory to become universal", () => { expect(new ConservativePreferenceValidator().validate(candidate({ strength: "MANDATORY", scope: [{ type: "GLOBAL" }] }))).toMatchObject({ status: "DEFER", reasonCodes: ["SCOPE_EXPANSION"] }); });
  it("distinguishes scoped preference language from a direct instruction", () => { const interpreter = new PreferenceInterpretationService(); const input = { interpretationId: "i:1", ownerId: "user:george", activeScopes: [{ type: "PROJECT", id: "noesis" }] as const, provenanceId: "teaching:1", actor, occurredAt: now }; expect(interpreter.interpret({ ...input, statement: "I generally prefer concise plans." })).toMatchObject({ classification: "PREFERENCE", strength: "NORMAL", scope: [{ type: "PROJECT", id: "noesis" }] }); expect(interpreter.interpret({ ...input, statement: "Build this service in Python." })).toMatchObject({ classification: "DIRECTIVE", candidate: undefined }); });
  it("defers an apparent preference with no concrete scope", () => { expect(new PreferenceInterpretationService().interpret({ interpretationId: "i:2", statement: "I like dark interfaces.", ownerId: "user:george", activeScopes: [], provenanceId: "teaching:2", actor, occurredAt: now })).toMatchObject({ classification: "UNRESOLVED", strength: "WEAK", reasonCodes: ["SCOPE_UNRESOLVED"] }); });
  it("applies the most specific preference but yields to directives and exceptions", () => { const resolver = new PreferenceResolverService(); const general = { preferenceId: "pref:general", candidate: candidate({ scope: [{ type: "USER", id: "george" }], preferredOption: "concise answers", strength: "STRONG" }), status: "ACTIVE" as const, activatedAt: now }; const project = { preferenceId: "pref:project", candidate: candidate({ preferenceId: "pref:project-candidate", scope: [{ type: "USER", id: "george" }, { type: "PROJECT", id: "noesis" }], preferredOption: "detailed architecture plans", strength: "NORMAL" }), status: "ACTIVE" as const, activatedAt: now }; const input = { ownerId: "user:george", activeScopes: [{ type: "USER", id: "george" }, { type: "PROJECT", id: "noesis" }] as const, preferences: [general, project], applicableExceptionIds: [] }; expect(resolver.resolve(input)).toMatchObject({ status: "APPLIED", preferenceId: "pref:project" }); expect(resolver.resolve({ ...input, explicitHumanDirective: "Use a one-line summary." })).toMatchObject({ status: "BYPASSED", reason: "EXPLICIT_DIRECTIVE" }); });
  it("reinforces within scope but defers an attempted scope expansion", async () => { const artifacts: any[] = []; const store = { append: async (item: any) => { artifacts.push(item); return item; }, listArtifacts: async () => [] }; const preference = { preferenceId: "pref:active", candidate: candidate({ preferenceId: "pref:active", confidence: 0.85 }), status: "ACTIVE" as const, activatedAt: now }; const reinforcement = { reinforcementId: "r:1", preferenceId: "pref:active", evidence: { evidenceId: "e:2", kind: "CORRECTION" as const, provenanceId: "correction:1", observedAt: now, weight: 1 }, observedScope: [{ type: "PROJECT", id: "noesis" }] as const, actor, observedAt: now, immutable: true as const }; const service = new PreferenceReinforcementService(store); await expect(service.record(preference, reinforcement, "workspace:1", "r:1")).resolves.toMatchObject({ status: "RECORDED", nextStrength: "EXPLICIT" }); await expect(service.record(preference, { ...reinforcement, reinforcementId: "r:2", observedScope: [{ type: "WORKSPACE", id: "all" }] }, "workspace:1", "r:2")).resolves.toMatchObject({ status: "DEFERRED", reason: "SCOPE_EXPANSION_REQUIRES_REVIEW" }); expect(artifacts).toHaveLength(1); });
  it("records human-only scope correction and supersession as immutable lifecycle evidence", async () => { const artifacts: any[] = []; const store = { append: async (item: any) => { artifacts.push(item); return item; }, listArtifacts: async () => [] }; const service = new PreferenceLifecycleService(store); await expect(service.record({ decisionId: "l:1", preferenceId: "pref:1", action: "NARROW_SCOPE", actor, reason: "Only for Noesis.", narrowedScope: [{ type: "PROJECT", id: "noesis" }], decidedAt: now, immutable: true, executionPermissionGranted: false }, "workspace:1", "l:1")).resolves.toMatchObject({ persistenceEffect: "CREATED" }); await expect(service.record({ decisionId: "l:2", preferenceId: "pref:1", action: "SUPERSEDE", actor, reason: "Use the newer preference.", successorPreferenceId: "pref:2", decidedAt: now, immutable: true, executionPermissionGranted: false }, "workspace:1", "l:2")).resolves.toMatchObject({ authorityEffect: "UNCHANGED" }); expect(artifacts.map((item) => item.artifactType)).toEqual(["LIFECYCLE", "LIFECYCLE"]); });
  it("requires teach-back for significant preferences and maps scope corrections to repair plans", () => { const preference = candidate({ preferenceId: "pref:important", strength: "STRONG" }); const service = new PreferenceIntegrationService(); expect(service.planTeachBack(preference)).toMatchObject({ requirement: "REQUIRED", executionPermissionGranted: false }); expect(service.planCorrectionRepair(preference, { correctionId: "c:1", sourceEventId: "event:1", sourceText: "No, I meant only for this project, not everything.", targetCandidateIds: ["pref:important"], explicitness: "EXPLICIT", confidence: 1, actor, timestamp: now, processingStatus: "DETECTED", immutable: true })).toMatchObject({ action: "NARROW_SCOPE", authorityEffect: "UNCHANGED" }); });
  it("requires human review before a valid preference becomes active guidance", async () => { const artifacts: any[] = []; const store = { append: async (item: any) => { artifacts.push(item); return item; }, listArtifacts: async () => [] }; const result = await new PreferenceHumanReviewService(new ConservativePreferenceValidator(), store).record({ reviewId: "review:1", preferenceId: "pref:1", action: "ACTIVATE", actor, note: "Confirmed for Noesis.", reviewedAt: now, immutable: true }, candidate(), "workspace:1", "review:1"); expect(result.active).toMatchObject({ status: "ACTIVE", preferenceId: "pref:1" }); expect(artifacts).toHaveLength(2); });
});
