import { describe, expect, it } from "vitest";
import { ConservativeProcedureCompletenessValidator, InMemoryLearningAuditLedger, InMemoryProcedureExecutionLedger, InMemoryProcedureHumanReviewRepository, InMemoryProcedureRegistry, ProcedureCandidateService, ProcedureExecutionLifecycleService, ProcedureHumanReviewService, ProcedurePromotionService, ProcedureRegistryService, ProcedureSimulationService, StructuralProcedureTeachBackEvaluator } from "@/services/learning-constitution";
import type { DurableLearningGateRequest, HumanAuthorizedProcedure, KnowledgeAdmissionRequest, ProcedureCandidateInput, ProcedureTeachBack } from "@/types/learning-constitution";

const now = "2026-09-01T00:00:00.000Z"; const actor = { actorId: "agent:noesis", actorType: "AGENT" as const };
const states = (state: "KNOWN" | "NOT_APPLICABLE" | "UNKNOWN") => ({ INPUTS: state, PRECONDITIONS: state, STEPS: state, DECISION_POINTS: state, EXPECTED_OUTPUTS: state, FAILURE_CONDITIONS: state, RECOVERY: state, VERIFICATION: state, EXCEPTIONS: state } as const);
const base: ProcedureCandidateInput = { procedureId: "procedure:1", version: 1, name: "Promote durable knowledge", purpose: "Commit validated knowledge safely.", scope: { type: "PROJECT", id: "noesis" }, inputs: [{ inputId: "input:1", name: "candidate", kind: "REQUIRED", derivable: false }], preconditions: ["candidate is approved"], steps: [{ stepId: "step:1", action: "Evaluate learning gate.", requires: ["candidate"], produces: ["gate decision"], provenance: { source: "HUMAN_TAUGHT", sourceId: "teaching:1" } }], decisionPoints: [], expectedOutputs: ["durable knowledge record"], failureConditions: [], recovery: [], verification: [{ verificationId: "verify:1", test: "Record exists in durable registry.", required: true, provenanceId: "teaching:1" }], exceptions: [], fieldStates: states("UNKNOWN"), teachingEventId: "teaching:1", createdBy: actor, createdAt: now };

describe("Phase 14 procedure candidates", () => {
  it("keeps missing procedural information incomplete rather than inventing it", async () => {
    const audit = new InMemoryLearningAuditLedger(); const result = await new ProcedureCandidateService(new ConservativeProcedureCompletenessValidator(), audit).create(base, "workspace:1", "procedure:1");
    expect(result).toMatchObject({ candidate: { status: "INCOMPLETE", authority: "AGENT_INFERRED", executionPermissionGranted: false }, completeness: { status: "INCOMPLETE", missingFields: expect.arrayContaining(["PRECONDITIONS", "VERIFICATION"]) } });
    await expect(audit.list("workspace:1")).resolves.toEqual(expect.arrayContaining([expect.objectContaining({ event: expect.objectContaining({ eventType: "PROCEDURE_CANDIDATE_CREATED" }) })]));
  });
  it("creates a complete candidate only with explicit field declarations and step provenance", async () => {
    const complete = { ...base, fieldStates: { INPUTS: "KNOWN", PRECONDITIONS: "KNOWN", STEPS: "KNOWN", DECISION_POINTS: "NOT_APPLICABLE", EXPECTED_OUTPUTS: "KNOWN", FAILURE_CONDITIONS: "NOT_APPLICABLE", RECOVERY: "NOT_APPLICABLE", VERIFICATION: "KNOWN", EXCEPTIONS: "NOT_APPLICABLE" } as const };
    await expect(new ProcedureCandidateService(new ConservativeProcedureCompletenessValidator()).create(complete, "workspace:1", "procedure:1")).resolves.toMatchObject({ candidate: { status: "CANDIDATE", authority: "AGENT_INFERRED", executionPermissionGranted: false }, completeness: { status: "COMPLETE" } });
  });
  it("uses procedure teach-back as comprehension evidence and requires uncertainty for incomplete procedures", async () => {
    const { candidate } = await new ProcedureCandidateService(new ConservativeProcedureCompletenessValidator()).create(base, "workspace:1", "procedure:1");
    const teachBack: ProcedureTeachBack = { teachBackId: "procedure-teach-back:1", procedureId: candidate.procedureId, purpose: candidate.purpose, inputs: ["candidate"], preconditions: ["candidate is approved"], steps: ["Evaluate learning gate."], decisions: [], expectedOutputs: ["durable knowledge record"], failures: [], recovery: [], verification: ["Record exists in durable registry."], exceptions: [], uncertainties: ["Decision points and recovery were not taught."], generatedBy: actor, generatedAt: now, immutable: true };
    expect(new StructuralProcedureTeachBackEvaluator().evaluate(teachBack, candidate)).toMatchObject({ outcome: "PASS", authorityEffect: "UNCHANGED", executionPermissionGranted: false });
    expect(new StructuralProcedureTeachBackEvaluator().evaluate({ ...teachBack, uncertainties: [] }, candidate)).toMatchObject({ outcome: "CLARIFICATION_REQUIRED", findings: expect.arrayContaining(["INCOMPLETE_PROCEDURE_UNCERTAINTY_MISSING"]) });
  });
  it("requires human review for a complete candidate and never grants execution authority", async () => {
    const complete = { ...base, fieldStates: { INPUTS: "KNOWN", PRECONDITIONS: "KNOWN", STEPS: "KNOWN", DECISION_POINTS: "NOT_APPLICABLE", EXPECTED_OUTPUTS: "KNOWN", FAILURE_CONDITIONS: "NOT_APPLICABLE", RECOVERY: "NOT_APPLICABLE", VERIFICATION: "KNOWN", EXCEPTIONS: "NOT_APPLICABLE" } as const };
    const { candidate } = await new ProcedureCandidateService(new ConservativeProcedureCompletenessValidator()).create(complete, "workspace:1", "procedure:1"); const service = new ProcedureHumanReviewService(new InMemoryProcedureHumanReviewRepository());
    const result = await service.record({ review: { reviewId: "procedure-review:1", procedureId: candidate.procedureId, action: "APPROVE", actor: { actorId: "user:teacher", actorType: "HUMAN" }, note: "Approved procedure definition.", reviewedAt: now, immutable: true }, candidate }, "workspace:1", "procedure-review:1");
    expect(result.authorized).toMatchObject({ authority: "HUMAN_DIRECTIVE", status: "PENDING_CONFLICT_AND_GATE", executionPermissionGranted: false });
    await expect(service.record({ review: { reviewId: "procedure-review:2", procedureId: candidate.procedureId, action: "APPROVE", actor, note: "No.", reviewedAt: now, immutable: true }, candidate }, "workspace:1", "procedure-review:2")).rejects.toThrow("human actor");
  });
  it("binds procedure promotion to the exact reviewed procedure and keeps deferred results non-executable", async () => {
    const complete = { ...base, fieldStates: { INPUTS: "KNOWN", PRECONDITIONS: "KNOWN", STEPS: "KNOWN", DECISION_POINTS: "NOT_APPLICABLE", EXPECTED_OUTPUTS: "KNOWN", FAILURE_CONDITIONS: "NOT_APPLICABLE", RECOVERY: "NOT_APPLICABLE", VERIFICATION: "KNOWN", EXCEPTIONS: "NOT_APPLICABLE" } as const };
    const { candidate } = await new ProcedureCandidateService(new ConservativeProcedureCompletenessValidator()).create(complete, "workspace:1", "procedure:1"); const authorized: HumanAuthorizedProcedure = { authorizedProcedureId: "authorized-procedure:1", procedureId: candidate.procedureId, reviewId: "review:1", procedure: candidate, authority: "HUMAN_DIRECTIVE", status: "PENDING_CONFLICT_AND_GATE", authorizedBy: { actorId: "user:teacher", actorType: "HUMAN" }, authorizedAt: now, immutable: true, executionPermissionGranted: false };
    await expect(new ProcedurePromotionService({ promote: async () => ({ status: "COMMITTED" as const, persistenceEffect: "CREATED" as const }) }).promote({ authorized, gateRequest: {} as DurableLearningGateRequest, admission: {} as KnowledgeAdmissionRequest, workspaceId: "workspace:1", correlationId: "procedure:1" })).resolves.toMatchObject({ status: "BLOCKED", persistenceEffect: "NONE" });
    const gateRequest = { candidate: { candidateId: authorized.authorizedProcedureId, classification: "PROCEDURE", content: candidate.name } } as DurableLearningGateRequest; const admission = { candidate: gateRequest.candidate } as KnowledgeAdmissionRequest;
    await expect(new ProcedurePromotionService({ promote: async () => ({ status: "DEFERRED" as const, persistenceEffect: "NONE" as const }) }).promote({ authorized, gateRequest, admission, workspaceId: "workspace:1", correlationId: "procedure:1" })).resolves.toMatchObject({ status: "DEFERRED", executionPermissionGranted: false });
  });
  it("registers a versioned procedure and dry-runs without executing steps", async () => {
    const complete = { ...base, fieldStates: { INPUTS: "KNOWN", PRECONDITIONS: "KNOWN", STEPS: "KNOWN", DECISION_POINTS: "NOT_APPLICABLE", EXPECTED_OUTPUTS: "KNOWN", FAILURE_CONDITIONS: "NOT_APPLICABLE", RECOVERY: "NOT_APPLICABLE", VERIFICATION: "KNOWN", EXCEPTIONS: "NOT_APPLICABLE" } as const }; const { candidate } = await new ProcedureCandidateService(new ConservativeProcedureCompletenessValidator()).create(complete, "workspace:1", "procedure:1");
    const authorized: HumanAuthorizedProcedure = { authorizedProcedureId: "authorized-procedure:2", procedureId: candidate.procedureId, reviewId: "review:2", procedure: candidate, authority: "HUMAN_DIRECTIVE", status: "PENDING_CONFLICT_AND_GATE", authorizedBy: { actorId: "user:teacher", actorType: "HUMAN" }, authorizedAt: now, immutable: true, executionPermissionGranted: false }; const registry = new InMemoryProcedureRegistry();
    const durable = await new ProcedureRegistryService(registry).register({ durableProcedureId: "durable-procedure:1", durableKnowledgeId: "knowledge:procedure:1", authorized, createdAt: now }, "workspace:1", "procedure:1");
    await expect(new ProcedureSimulationService().simulate(durable, { inputs: { "input:1": "candidate" }, satisfiedPreconditions: ["candidate is approved"] }, "workspace:1", actor, "simulation:1")).resolves.toMatchObject({ status: "READY_FOR_AUTHORIZED_EXECUTION", simulated: true, executionPermissionGranted: false, plannedStepIds: ["step:1"] });
    await expect(new ProcedureSimulationService().simulate(durable, { inputs: {}, satisfiedPreconditions: [] }, "workspace:1", actor, "simulation:2")).resolves.toMatchObject({ status: "DEFERRED", missingInputs: ["input:1"], failedPreconditions: ["candidate is approved"] });
  });
  it("requires separate execution authority and records lifecycle evidence without performing actions", async () => {
    const ledger = new InMemoryProcedureExecutionLedger(); const service = new ProcedureExecutionLifecycleService(ledger); const durable = { durableProcedureId: "durable-procedure:2" } as never; const ready = { durableProcedureId: "durable-procedure:2", status: "READY_FOR_AUTHORIZED_EXECUTION" } as never;
    await expect(service.start({ executionId: "execution:1", procedure: durable, simulation: ready, authorization: { authorizationId: "auth:1", procedureId: "durable-procedure:2", actor, granted: false, grantedAt: now }, workspaceId: "workspace:1", correlationId: "execution:1", now })).resolves.toMatchObject({ status: "BLOCKED", reason: "EXECUTION_AUTHORIZATION_REQUIRED", executionPermissionGranted: false });
    await expect(service.start({ executionId: "execution:1", procedure: durable, simulation: ready, authorization: { authorizationId: "auth:2", procedureId: "durable-procedure:2", actor, granted: true, grantedAt: now }, workspaceId: "workspace:1", correlationId: "execution:1", now })).resolves.toMatchObject({ status: "STARTED", executionPermissionGranted: false });
    await service.completeStep("execution:1", "step:1", now, "workspace:1", actor, "execution:1"); await service.verify("execution:1", "verify:1", true, now, "workspace:1", actor, "execution:1");
    await expect(ledger.list("execution:1")).resolves.toEqual(expect.arrayContaining([expect.objectContaining({ type: "STARTED" }), expect.objectContaining({ type: "STEP_COMPLETED" }), expect.objectContaining({ type: "VERIFICATION_PASSED" })]));
  });
  it("passes the Phase 14 acceptance path without conflating learned procedure with execution permission", async () => {
    const complete = { ...base, procedureId: "procedure:acceptance", fieldStates: { INPUTS: "KNOWN", PRECONDITIONS: "KNOWN", STEPS: "KNOWN", DECISION_POINTS: "NOT_APPLICABLE", EXPECTED_OUTPUTS: "KNOWN", FAILURE_CONDITIONS: "NOT_APPLICABLE", RECOVERY: "NOT_APPLICABLE", VERIFICATION: "KNOWN", EXCEPTIONS: "NOT_APPLICABLE" } as const };
    const candidateService = new ProcedureCandidateService(new ConservativeProcedureCompletenessValidator()); const { candidate, completeness } = await candidateService.create(complete, "workspace:1", "acceptance:1");
    expect(completeness.status).toBe("COMPLETE");
    const teachBack: ProcedureTeachBack = { teachBackId: "procedure-teach-back:acceptance", procedureId: candidate.procedureId, purpose: candidate.purpose, inputs: ["candidate"], preconditions: candidate.preconditions, steps: candidate.steps.map((step) => step.action), decisions: [], expectedOutputs: candidate.expectedOutputs, failures: [], recovery: [], verification: candidate.verification.map((item) => item.test), exceptions: [], uncertainties: [], generatedBy: actor, generatedAt: now, immutable: true };
    expect(new StructuralProcedureTeachBackEvaluator().evaluate(teachBack, candidate).outcome).toBe("PASS");
    const reviewed = await new ProcedureHumanReviewService(new InMemoryProcedureHumanReviewRepository()).record({ review: { reviewId: "procedure-review:acceptance", procedureId: candidate.procedureId, action: "APPROVE", actor: { actorId: "user:teacher", actorType: "HUMAN" }, note: "Approved.", reviewedAt: now, immutable: true }, candidate }, "workspace:1", "acceptance:1"); const authorized = reviewed.authorized!;
    const gateRequest = { candidate: { candidateId: authorized.authorizedProcedureId, classification: "PROCEDURE", content: candidate.name } } as DurableLearningGateRequest; const admission = { candidate: gateRequest.candidate } as KnowledgeAdmissionRequest;
    await expect(new ProcedurePromotionService({ promote: async () => ({ status: "COMMITTED" as const, persistenceEffect: "CREATED" as const }) }).promote({ authorized, gateRequest, admission, workspaceId: "workspace:1", correlationId: "acceptance:1" })).resolves.toMatchObject({ status: "COMMITTED" });
    const durable = await new ProcedureRegistryService(new InMemoryProcedureRegistry()).register({ durableProcedureId: "durable-procedure:acceptance", durableKnowledgeId: "knowledge:procedure:acceptance", authorized, createdAt: now }, "workspace:1", "acceptance:1"); const simulation = await new ProcedureSimulationService().simulate(durable, { inputs: { "input:1": "candidate" }, satisfiedPreconditions: candidate.preconditions }, "workspace:1", actor, "acceptance:simulation");
    expect(simulation).toMatchObject({ status: "READY_FOR_AUTHORIZED_EXECUTION", executionPermissionGranted: false });
    const lifecycle = new ProcedureExecutionLifecycleService(new InMemoryProcedureExecutionLedger());
    await expect(lifecycle.start({ executionId: "execution:acceptance", procedure: durable, simulation, authorization: { authorizationId: "execution-auth:acceptance", procedureId: durable.durableProcedureId, actor: { actorId: "user:teacher", actorType: "HUMAN" }, granted: true, grantedAt: now }, workspaceId: "workspace:1", correlationId: "acceptance:execution", now })).resolves.toMatchObject({ status: "STARTED", executionPermissionGranted: false });
  });
});
