import { describe, expect, it } from "vitest";
import { ReflectionRemediationExecutionService } from "@/services/learning-constitution";
import type { EvaluationArtifactRecord, EvaluationArtifactStore, PracticeArtifactRecord, PracticeArtifactStore, ReflectionArtifactRecord, ReflectionArtifactStore, ReflectionRemediationPlan } from "@/types/learning-constitution";
const actor = { actorId: "human:teacher", actorType: "HUMAN" as const }; const stamp = "2026-09-02T10:00:00.000Z";
const plan: ReflectionRemediationPlan = { planId: "RP-1", reflectionId: "RF-1", selectedCauseId: "RC-1", targetSkillId: "SK-DEPENDENCY", targetKnowledgeId: null, targetPrincipleId: null, targetProcedureId: null, targetExceptionId: null, intervention: "PREREQUISITE_PRACTICE", objective: "Repair dependency analysis.", practiceTransferLevels: ["EXACT"], successCriteria: ["pass"], reevaluationStrategy: "ORIGINAL_EVALUATION", maximumAttempts: 2, escalationConditions: ["Repeated failure."], status: "PROPOSED", createdBy: actor, createdAt: stamp, masteryEffect: "NONE", durableKnowledgeEffect: "NONE", executionPermissionGranted: false };
const reflections = (): ReflectionArtifactStore => { const records: ReflectionArtifactRecord[] = [{ artifactId: "PLAN:1", artifactType: "REMEDIATION_PLAN", subjectId: "RF-1", payload: plan, createdAt: stamp }]; return { append: async (record) => { records.push(record); return record; }, listArtifacts: async (subjectId) => records.filter((record) => record.subjectId === subjectId), listWorkspaceArtifacts: async () => records }; };
const practices = (): PracticeArtifactStore => ({ append: async (record) => record, listArtifacts: async () => [], listWorkspaceArtifacts: async () => [{ artifactId: "PE-1", artifactType: "EXERCISE", subjectId: "PE-1", payload: { exerciseId: "PE-1", targetSkillIds: ["SK-DEPENDENCY"] }, createdAt: stamp } as PracticeArtifactRecord] });
const evaluations = (): EvaluationArtifactStore => ({ append: async (record) => record, listArtifacts: async () => [], listWorkspaceArtifacts: async () => [{ artifactId: "ES-1", artifactType: "SCORE", subjectId: "EVAL-RETEST", payload: { scoreId: "ES-1", evaluationId: "EVAL-RETEST", outcome: "PASS" }, createdAt: stamp } as EvaluationArtifactRecord] });
describe("Phase 22 remediation execution", () => { it("links focused practice to a successful reevaluation and bounds escalation", async () => { const service = new ReflectionRemediationExecutionService(reflections(), practices(), evaluations()); await expect(service.activate({ activationId: "RA-1", planId: plan.planId, reflectionId: plan.reflectionId, practiceExerciseIds: ["PE-1"], activatedBy: actor, activatedAt: stamp })).resolves.toMatchObject({ planId: plan.planId }); await expect(service.linkReevaluation({ reevaluationId: "RR-1", reflectionId: plan.reflectionId, planId: plan.planId, originalEvaluationId: "EVAL-ORIGINAL", reevaluationEvaluationId: "EVAL-RETEST", completedAt: stamp, completedBy: actor })).resolves.toMatchObject({ outcome: "PASS" }); }); });
