import { describe, expect, it } from "vitest";
import { ReflectionCandidateCauseGenerator, ReflectionPrerequisiteDiagnosisService } from "@/services/learning-constitution";
import type { ReflectionCase, SkillCandidate, SkillDependency, SkillRegistryEntry } from "@/types/learning-constitution";
const actor = { actorId: "human:teacher", actorType: "HUMAN" as const }; const stamp = "2026-09-02T08:00:00.000Z";
const reflection: ReflectionCase = { reflectionId: "RF-PREREQ", trigger: "EVALUATION_FAILURE", evaluationId: "EVAL-1", skillId: "SK-ROADMAP", expectedOutcome: "Correct dependency ordering.", observedOutcome: "Dependency was missed.", failureType: "PREREQUISITE_GAP", failureLocation: "RETRIEVE_KNOWLEDGE", relevantKnowledgeIds: [], relevantPrincipleIds: [], relevantProcedureIds: [], relevantExampleIds: [], relevantExceptionIds: [], prerequisiteSkillIds: ["SK-DEPENDENCY"], status: "DIAGNOSING", createdBy: actor, createdAt: stamp, resolvedAt: null, masteryEffect: "NONE", durableKnowledgeEffect: "NONE", executionPermissionGranted: false };
const skill = (skillId: string, mastery: number): SkillCandidate => ({ skillId, name: skillId, description: "Test", domain: "Planning", skillType: "ATOMIC", scope: [{ type: "PROJECT", id: "noesis" }], prerequisiteSkillIds: [], procedureIds: [], principleIds: [], evidence: [], mastery, confidence: "LOW", status: "UNDEMONSTRATED", limitations: [], failureModes: [], createdBy: actor, createdAt: stamp, immutable: true, capabilityClaim: false, executionPermissionGranted: false });
const entry = (candidate: SkillCandidate): SkillRegistryEntry => ({ skill: candidate, status: "VALIDATED", activeEvidenceCount: 1, revokedEvidenceCount: 0, evaluationCount: 2, assessment: { observedScore: candidate.mastery, estimatedMastery: candidate.mastery, confidence: "LOW", eligibleForProvisional: true, rationale: [], executionPermissionGranted: false }, lastReviewedAt: null, executionPermissionGranted: false });
const dependency: SkillDependency = { dependencyId: "SD-1", prerequisite: { skillId: "SK-DEPENDENCY" }, dependent: { skillId: "SK-ROADMAP" }, relationshipType: "PREREQUISITE", strength: 0.9, requiredMasteryThreshold: 70, evidenceIds: ["EV-1"], provenance: { provenanceIds: ["PR-1"], assertedBy: actor, assertedAt: stamp }, lifecycle: "ACTIVE", graphVersionId: "SG-1", rationale: "Required." };
describe("Phase 22 candidate and prerequisite diagnosis", () => {
  it("keeps an evidence-backed candidate provisional and recommends only the weak prerequisite", () => { const candidate = new ReflectionCandidateCauseGenerator().generate({ causeId: "RC-1", reflection, evidence: [{ evidenceId: "EE-1", sourceType: "EVALUATION", sourceId: "EVAL-1", supports: true, note: "Dependency failure." }], createdAt: stamp }); expect(candidate).toMatchObject({ failureType: "PREREQUISITE_GAP", confidence: 0.6 }); expect(new ReflectionPrerequisiteDiagnosisService().diagnose({ reflection, dependencies: [dependency], registryEntries: new Map([["SK-ROADMAP", entry(skill("SK-ROADMAP", 82))], ["SK-DEPENDENCY", entry(skill("SK-DEPENDENCY", 52))]]), evidenceIds: candidate.supportingEvidenceIds })).toMatchObject({ status: "RECOMMENDED", targetSkillId: "SK-DEPENDENCY", dependencyId: "SD-1" }); });
  it("returns UNKNOWN and refuses prerequisite blame when evidence is absent", () => { expect(new ReflectionCandidateCauseGenerator().generate({ causeId: "RC-UNKNOWN", reflection, evidence: [], createdAt: stamp })).toMatchObject({ failureType: "UNKNOWN", confidence: 0 }); expect(new ReflectionPrerequisiteDiagnosisService().diagnose({ reflection, dependencies: [], registryEntries: new Map(), evidenceIds: [] })).toMatchObject({ status: "INSUFFICIENT_EVIDENCE", targetSkillId: null }); });
});
