import { describe, expect, it } from "vitest";
import { InMemoryLearningAuditLedger, ReflectionArtifactService } from "@/services/learning-constitution";
import type { ReflectionArtifactRecord, ReflectionArtifactStore, ReflectionCase } from "@/types/learning-constitution";

const actor = { actorId: "human:teacher", actorType: "HUMAN" as const }; const stamp = "2026-09-02T06:00:00.000Z";
const reflection: ReflectionCase = { reflectionId: "RF-1", trigger: "EVALUATION_FAILURE", evaluationId: "EVAL-1", skillId: "SK-ROADMAP", attemptId: "PA-1", expectedOutcome: "Recognize the dependency boundary.", observedOutcome: "Applied ordering to independent tasks.", failureType: "BOUNDARY_RECOGNITION_ERROR", failureLocation: "CHECK_APPLICABILITY", relevantKnowledgeIds: ["K-1"], relevantPrincipleIds: ["P-1"], relevantProcedureIds: [], relevantExampleIds: [], relevantExceptionIds: [], prerequisiteSkillIds: ["SK-DEPENDENCY"], status: "OPEN", createdBy: actor, createdAt: stamp, resolvedAt: null, masteryEffect: "NONE", durableKnowledgeEffect: "NONE", executionPermissionGranted: false };
const store = (): ReflectionArtifactStore => { const records: ReflectionArtifactRecord[] = []; return { append: async (record) => { const previous = records.find((item) => item.artifactId === record.artifactId); if (previous) return previous; records.push(record); return record; }, listArtifacts: async (subjectId) => records.filter((record) => record.subjectId === subjectId), listWorkspaceArtifacts: async () => [...records] }; };

describe("Phase 22 reflection foundation", () => {
  it("retains evidence-backed competing causes and allows explicit uncertainty instead of inventing a diagnosis", async () => {
    const artifacts = store(); const audit = new InMemoryLearningAuditLedger(); const service = new ReflectionArtifactService(artifacts, audit); await service.createCase(reflection, "workspace:1", "reflection:1"); await service.transition(reflection.reflectionId, "OPEN", "DIAGNOSING", actor, stamp, "Collecting evidence.", "workspace:1", "reflection:1"); await service.recordEvidence(reflection.reflectionId, [{ evidenceId: "EE-1", sourceType: "EVALUATION", sourceId: reflection.evaluationId, supports: true, note: "Boundary score was below threshold." }]);
    await expect(service.addCandidateCause({ causeId: "RC-UNSUPPORTED", reflectionId: reflection.reflectionId, failureType: "BOUNDARY_RECOGNITION_ERROR", location: "CHECK_APPLICABILITY", supportingEvidenceIds: [], contradictingEvidenceIds: [], confidence: 0.8, rationale: "Unsupported assertion.", requiredVerification: [], createdBy: actor, createdAt: stamp })).rejects.toThrow("supporting evidence");
    await service.addCandidateCause({ causeId: "RC-1", reflectionId: reflection.reflectionId, failureType: "BOUNDARY_RECOGNITION_ERROR", location: "CHECK_APPLICABILITY", supportingEvidenceIds: ["EE-1"], contradictingEvidenceIds: [], confidence: 0.72, rationale: "Applicability was not checked.", requiredVerification: ["Use a counterexample exercise."], createdBy: actor, createdAt: stamp });
    await expect(service.selectCause({ reflectionId: reflection.reflectionId, causeId: "RC-1", failureType: "BOUNDARY_RECOGNITION_ERROR", confidence: 0.72, selectionReason: "Direct evaluation evidence supports it.", selectedBy: actor, selectedAt: stamp, status: "SELECTED" }, "workspace:1", "reflection:1")).resolves.toMatchObject({ status: "SELECTED" });
    await expect(service.selectCause({ reflectionId: "RF-UNKNOWN", causeId: null, failureType: "UNKNOWN", confidence: 0, selectionReason: "Evidence does not distinguish the causes.", selectedBy: actor, selectedAt: stamp, status: "UNKNOWN" }, "workspace:1", "reflection:unknown")).resolves.toMatchObject({ status: "UNKNOWN", causeId: null });
    expect((await audit.list("workspace:1")).map((entry) => entry.event.eventType)).toEqual(expect.arrayContaining(["REFLECTION_CASE_CREATED", "REFLECTION_CAUSE_IDENTIFIED"]));
  });
});
