import { describe, expect, it } from "vitest";
import { CandidateSkillGraphPlacementService, SkillDiscoveryComparisonService, SkillDiscoveryHandoffService, SkillDiscoveryHumanReviewService, SkillDiscoveryPatternDetector, SkillDiscoveryService } from "@/services/learning-constitution";
import type { DiscoveredSkillCandidate, SkillDiscoveryArtifactRecord, SkillDiscoveryArtifactStore, SkillDiscoveryEpisode } from "@/types/learning-constitution";

const at = "2026-09-03T20:00:00.000Z";
const actor = { actorId: "agent:discovery", actorType: "AGENT" as const };
const store = (): SkillDiscoveryArtifactStore => { const records: SkillDiscoveryArtifactRecord[] = []; return { append: async (artifact) => { records.push(artifact); return artifact; }, listArtifacts: async (subjectId) => records.filter((artifact) => artifact.subjectId === subjectId), listWorkspaceArtifacts: async () => records }; };
const episode = (id: string, context: string): SkillDiscoveryEpisode => ({ episodeId: id, source: "EVALUATION", sourceId: `evaluation:${id}`, behavioralFingerprint: "constraint-detection", contextFingerprint: context, outcome: "SUCCESS", independent: true, safeForDiscovery: true, observedAt: at, immutable: true });
const candidate = (overrides: Partial<DiscoveredSkillCandidate> = {}): DiscoveredSkillCandidate => ({ candidateSkillId: "CS-34", definitionVersion: 1, name: "Constraint detection", description: "Detect architecture constraints.", purpose: "Expose material constraints.", expectedCapability: "Identify constraints before design.", boundaries: ["Architecture decisions"], nonExamples: ["Merely restating requirements"], failureConditions: ["Misses material dependency"], evaluationRequirements: ["Novel independent scenario"], proposedSkillType: "ATOMIC", observedEpisodeIds: ["E1", "E2", "E3"], relatedSkillIds: ["SK-REQ"], proposedPrerequisiteSkillIds: ["SK-REQ"], discoveryConfidence: .8, comparison: "POSSIBLE_NEW_SKILL", lifecycle: "CANDIDATE", competencyStatus: "UNTESTED", certificationStatus: "NOT_CERTIFIED", expiresAt: "2026-10-03T20:00:00.000Z", createdBy: actor, createdAt: at, immutable: true, registryWriteAuthorized: false, executionPermissionGranted: false, durableKnowledgeEffect: "NONE", ...overrides });

describe("Phase 34 skill discovery foundation", () => {
  it("requires recurring, diverse independent behavior while preserving the certification firewall", async () => { const artifacts = store(); const service = new SkillDiscoveryService(artifacts); const episodes = [episode("E1", "project-a"), episode("E2", "project-b"), episode("E3", "project-b")]; for (const item of episodes) await service.recordEpisode(item); await expect(service.propose({ candidate: candidate(), episodes, budget: { maximumCandidates: 2, windowHours: 24 } })).resolves.toMatchObject({ competencyStatus: "UNTESTED", certificationStatus: "NOT_CERTIFIED", registryWriteAuthorized: false }); });
  it("rejects one-context repetition and any attempted discovery-to-registry shortcut", async () => { const service = new SkillDiscoveryService(store()); const repeated = [episode("E1", "same"), episode("E2", "same"), episode("E3", "same")]; await expect(service.propose({ candidate: candidate(), episodes: repeated, budget: { maximumCandidates: 2, windowHours: 24 } })).rejects.toThrow("two contexts"); await expect(service.propose({ candidate: candidate({ registryWriteAuthorized: true }), episodes: [episode("E1", "a"), episode("E2", "b"), episode("E3", "c")], budget: { maximumCandidates: 2, windowHours: 24 } })).rejects.toThrow("untested"); });
  it("expires unattended candidates without certifying them", async () => { const service = new SkillDiscoveryService(store()); await expect(service.expire({ candidate: candidate(), now: "2026-10-04T20:00:00.000Z" })).resolves.toMatchObject({ lifecycle: "EXPIRED", certificationStatus: "NOT_CERTIFIED" }); });
});

describe("Phase 34 recurrence and novelty comparison", () => {
  const registryEntry = (skillId: string, name: string, description: string) => ({ skill: { skillId, name, description, domain: "Architecture", skillType: "ATOMIC" as const, scope: [], prerequisiteSkillIds: [], procedureIds: [], principleIds: [], evidence: [], mastery: null, confidence: "UNKNOWN" as const, status: "UNDEMONSTRATED" as const, limitations: [], failureModes: [], createdBy: actor, createdAt: at, immutable: true as const, capabilityClaim: false as const, executionPermissionGranted: false as const }, status: "UNDEMONSTRATED" as const, activeEvidenceCount: 0, revokedEvidenceCount: 0, evaluationCount: 0, assessment: { observedScore: null, estimatedMastery: null, confidence: "UNKNOWN" as const, eligibleForProvisional: false, rationale: [], executionPermissionGranted: false as const }, lastReviewedAt: null, executionPermissionGranted: false as const });
  it("clusters recurrence while preserving contradictory failure evidence", () => { const pattern = new SkillDiscoveryPatternDetector().detect([episode("E1", "a"), episode("E2", "b"), episode("E3", "b"), { ...episode("E4", "c"), outcome: "FAILURE" as const }])[0]; expect(pattern).toMatchObject({ recurrenceEligible: true, independentSuccesses: 3, failedEpisodeIds: ["E4"] }); });
  it("abstains on ambiguous overlap and identifies graph-supported compositions", () => { const pattern = new SkillDiscoveryPatternDetector().detect([episode("E1", "a"), episode("E2", "b"), episode("E3", "c")])[0]; const first = registryEntry("SK-REQ", "Constraint analysis", "Identify architecture constraints before design"); const second = registryEntry("SK-DEP", "Dependency analysis", "Identify dependencies"); const service = new SkillDiscoveryComparisonService(); expect(service.compare({ candidate: candidate({ relatedSkillIds: [first.skill.skillId, second.skill.skillId] }), pattern, registryEntries: [first, second], graph: { dependencies: [{ dependencyId: "D", prerequisite: { skillId: first.skill.skillId }, dependent: { skillId: second.skill.skillId }, relationshipType: "RELATED", strength: .5, requiredMasteryThreshold: null, evidenceIds: [], provenance: { provenanceIds: [], assertedBy: actor, assertedAt: at }, lifecycle: "ACTIVE", graphVersionId: "G", rationale: "related" }], latestVersion: null } })).toMatchObject({ outcome: "COMPOSITION_OF_EXISTING_SKILLS", registryEffect: "NONE" }); expect(service.compare({ candidate: candidate({ name: "Constraint analysis", description: "Identify architecture constraints before design plus boundary", relatedSkillIds: [] }), pattern, registryEntries: [first], graph: { dependencies: [], latestVersion: null } })).toMatchObject({ outcome: "UNCERTAIN_NEEDS_HUMAN_BOUNDARY_REVIEW" }); });
});

describe("Phase 34 human review and graph proposals", () => {
  it("requires a human decision and leaves accepted candidates untested and uncertified", async () => { const service = new SkillDiscoveryHumanReviewService(store()); await expect(service.review({ candidate: candidate(), review: { reviewId: "R-34", candidateSkillId: "CS-34", definitionVersion: 1, action: "ACCEPT_FOR_EVALUATION", targetCandidateOrSkillId: null, rationale: "Test the distinct proposed boundary.", decidedBy: { actorId: "human:teacher", actorType: "HUMAN" }, decidedAt: at, immutable: true, registryWriteAuthorized: false, certificationStatus: "NOT_CERTIFIED" } })).resolves.toMatchObject({ lifecycle: "ACCEPTED_FOR_EVALUATION", certificationStatus: "NOT_CERTIFIED", registryWriteAuthorized: false }); });
  it("versions definition changes and proposes but never writes a graph placement", async () => { const artifacts = store(); const review = new SkillDiscoveryHumanReviewService(artifacts); const revised = await review.revise({ prior: candidate(), revised: candidate({ definitionVersion: 2, lifecycle: "UNDER_REVIEW", createdAt: "2026-09-04T20:00:00.000Z" }), action: "NARROW" }); const accepted = { ...revised, lifecycle: "ACCEPTED_FOR_EVALUATION" as const }; const graph = { dependencies: [{ dependencyId: "D", prerequisite: { skillId: "SK-REQ" }, dependent: { skillId: "SK-DEP" }, relationshipType: "RELATED" as const, strength: .5, requiredMasteryThreshold: null, evidenceIds: [], provenance: { provenanceIds: [], assertedBy: actor, assertedAt: at }, lifecycle: "ACTIVE" as const, graphVersionId: "G", rationale: "related" }], latestVersion: null }; await expect(new CandidateSkillGraphPlacementService(artifacts).propose({ candidate: accepted, graph, placement: { proposalId: "GP-34", candidateSkillId: accepted.candidateSkillId, definitionVersion: accepted.definitionVersion, prerequisiteSkillIds: ["SK-REQ"], relatedSkillIds: ["SK-DEP"], proposedDependentSkillIds: [], graphVersionId: "G", rationale: "Proposed placement for evaluation.", status: "PROPOSED", graphWriteAuthorized: false, executionPermissionGranted: false, durableKnowledgeEffect: "NONE", createdAt: at, createdBy: actor } })).resolves.toMatchObject({ graphWriteAuthorized: false, status: "PROPOSED" }); });
});

describe("Phase 34 governed evaluation handoff", () => {
  it("requires matching human acceptance and only proposes the existing governed evaluation sequence", async () => { const artifacts = store(); const reviewService = new SkillDiscoveryHumanReviewService(artifacts); const accepted = { ...candidate(), lifecycle: "ACCEPTED_FOR_EVALUATION" as const }; await reviewService.review({ candidate: candidate(), review: { reviewId: "R-HANDOFF", candidateSkillId: accepted.candidateSkillId, definitionVersion: accepted.definitionVersion, action: "ACCEPT_FOR_EVALUATION", targetCandidateOrSkillId: null, rationale: "Proceed to governed evaluation.", decidedBy: { actorId: "human:teacher", actorType: "HUMAN" }, decidedAt: at, immutable: true, registryWriteAuthorized: false, certificationStatus: "NOT_CERTIFIED" } }); await expect(new SkillDiscoveryHandoffService(artifacts).requestEvaluation({ requestId: "REQ-34", candidate: accepted })).resolves.toMatchObject({ status: "PROPOSED", requiredStages: ["PRACTICE", "EVALUATION", "ADVERSARIAL_EXAMINATION", "RETENTION"], certificationStatus: "NOT_CERTIFIED", registryWriteAuthorized: false, executionPermissionGranted: false }); });
});
