import { describe, expect, it } from "vitest";
import { InMemoryLearningAuditLedger, SocraticValidationArtifactService, SocraticValidationService } from "@/services/learning-constitution";
import type { LearningObjective, SocraticArtifactRecord, SocraticArtifactStore } from "@/types/learning-constitution";

const at = "2026-09-02T17:00:00.000Z"; const actor = { actorId: "human:teacher", actorType: "HUMAN" as const }; const store = (): SocraticArtifactStore => { const records: SocraticArtifactRecord[] = []; return { append: async (record) => { records.push(record); return record; }, listArtifacts: async (id) => records.filter((record) => record.subjectId === id), listWorkspaceArtifacts: async () => records }; };
const objective: LearningObjective = { objectiveId: "LO-V", objective: "Learn design approach.", teacher: actor, scope: "GENERAL", scopeId: null, desiredDepth: "HIGH", successCriteria: ["Predict judgment"], status: "ACTIVE", createdBy: actor, createdAt: at, durableKnowledgeEffect: "NONE", executionPermissionGranted: false };
describe("Phase 23E Socratic validation", () => {
  it("records a confirmed prediction and sends its Teach-Back only through the controlled gate handoff", async () => {
    const validation = new SocraticValidationService(); const prediction = validation.createPrediction({ predictionId: "PV-1", sessionId: "SS-V", scenario: "A small app could split persistence into another service but has no isolation need.", predictedJudgment: "Keep it together until a concrete need arises.", rationale: "The working model prioritizes practical isolation over architectural purity.", supportingHypothesisIds: ["H-1"], boundaryStatement: "This does not apply when a security or failure boundary requires separation.", createdBy: actor, createdAt: at, workingModelOnly: true }); const review = { reviewId: "PR-1", predictionId: prediction.predictionId, outcome: "CONFIRMED" as const, feedback: "Accurate.", reviewedBy: actor, reviewedAt: at, workingModelOnly: true as const }; const handoff = validation.createTeachBackHandoff({ handoffId: "TH-1", sessionId: "SS-V", objective, lesson: "Separate components for concrete operational value, not purity.", scope: "General system-design decisions", sourceExamples: [prediction.scenario], actor, createdAt: at });
    expect(handoff).toMatchObject({ durableLearningAuthorization: "GATE_REQUIRED", workingModelOnly: true }); const audit = new InMemoryLearningAuditLedger(); await new SocraticValidationArtifactService(store(), audit).record({ prediction, review, handoff, replan: null, workspaceId: "workspace:23", correlationId: "socratic:validation" }); expect((await audit.list("workspace:23")).map((entry) => entry.event.eventType)).toEqual(["PREDICTIVE_VALIDATION_STARTED", "PREDICTION_CONFIRMED", "TEACH_BACK_REQUESTED"]);
  });
  it("turns a correction into a focused boundary replan instead of restarting the interview", () => {
    const validation = new SocraticValidationService(); const replan = validation.correctionReplan({ replanId: "CR-1", sessionId: "SS-V", review: { reviewId: "PR-2", predictionId: "PV-2", outcome: "CORRECTED", feedback: "That changes when the deployment context is regulated.", reviewedBy: actor, reviewedAt: at, workingModelOnly: true }, affectedHypothesisIds: ["H-2"], createdAt: at }); expect(replan).toMatchObject({ recommendedQuestionType: "BOUNDARY", affectedHypothesisIds: ["H-2"] });
  });
});
