import { describe, expect, it } from "vitest";
import { InMemoryLearningAuditLedger, SocraticAdaptiveArtifactService, SocraticAnswerInterpretationService, SocraticSaturationService, SocraticUncertaintyService, SocraticWorkingModelService } from "@/services/learning-constitution";
import type { SocraticArtifactRecord, SocraticArtifactStore, SocraticKnowledgeMap, SocraticSelectedQuestion, SocraticSession } from "@/types/learning-constitution";

const at = "2026-09-02T16:00:00.000Z"; const actor = { actorId: "human:teacher", actorType: "HUMAN" as const }; const store = (): SocraticArtifactStore => { const items: SocraticArtifactRecord[] = []; return { append: async (item) => { items.push(item); return item; }, listArtifacts: async (id) => items.filter((item) => item.subjectId === id), listWorkspaceArtifacts: async () => items }; };
const map: SocraticKnowledgeMap = { mapId: "KM-A1", objectiveId: "LO-A", sourceObservationIds: [], createdAt: at, workingModelOnly: true, nodes: [{ nodeId: "N-A", label: "Operational simplicity", state: "UNKNOWN", confidence: 0, observationIds: [], rationale: "Gap." }] };
const question: SocraticSelectedQuestion = { questionId: "SQ-A", sessionId: "SS-A", candidateId: "QC-A", question: "If separation improved isolation but doubled operational complexity, what would determine your choice?", questionType: "COUNTERFACTUAL", selectedAt: at, selectedBy: actor, questionBudgetPosition: 1, workingModelOnly: true };
describe("Phase 23D adaptive interview loop", () => {
  it("records one human answer, updates only the provisional model, and replans rather than assuming durable knowledge", async () => {
    const answer = { answerId: "HA-A", sessionId: "SS-A", questionId: question.questionId, answer: "I usually prefer separation only when it solves a concrete isolation problem, but not for architectural purity.", answeredBy: actor, answeredAt: at, workingModelOnly: true as const, durableKnowledgeEffect: "NONE" as const, executionPermissionGranted: false as const }; const extractions = new SocraticAnswerInterpretationService().interpret(answer); expect(extractions.map((item) => item.kind)).toEqual(expect.arrayContaining(["EXPLICIT_CLAIM", "PREFERENCE", "EXCEPTION"])); const revised = new SocraticWorkingModelService().update({ updateId: "WM-A", nextMapId: "KM-A2", map, answer, targetNodeIds: ["N-A"], createdAt: at }); expect(revised.map.nodes[0]).toMatchObject({ state: "PARTIALLY_KNOWN", confidence: 0.65 });
    const session: SocraticSession = { sessionId: "SS-A", objectiveId: "LO-A", status: "ACTIVE", knowledgeMapId: map.mapId, questionBudget: { preferred: 3, maximum: 5 }, questionsAsked: [question.questionId], uncertaintyBefore: 1, uncertaintyCurrent: 0.35, informationGain: 0.65, createdBy: actor, createdAt: at, durableLearningStatus: "NOT_YET_EVALUATED", durableKnowledgeEffect: "NONE", executionPermissionGranted: false }; const gaps = new SocraticUncertaintyService().identifyGaps({ sessionId: session.sessionId, map: revised.map, objectiveRelevanceByNodeId: { "N-A": 0.9 }, createdAt: at }); const saturation = new SocraticSaturationService().decide({ session, gaps, marginalInformationGainThreshold: 0.15 }); expect(saturation).toMatchObject({ saturated: false, reason: "MORE_QUESTIONS_REQUIRED" }); const audit = new InMemoryLearningAuditLedger(); await new SocraticAdaptiveArtifactService(store(), audit).recordAnswerAndUpdate({ question, answer, extractions, map: revised.map, update: revised.update, saturation, workspaceId: "workspace:23", correlationId: "socratic:adaptive" }); expect((await audit.list("workspace:23")).map((entry) => entry.event.eventType)).toEqual(["QUESTION_ASKED", "HUMAN_ANSWER_RECEIVED", "WORKING_MODEL_UPDATED"]);
  });
  it("stops when the question budget is exhausted", () => { const session: SocraticSession = { sessionId: "SS-stop", objectiveId: "LO-A", status: "ACTIVE", knowledgeMapId: "KM-A", questionBudget: { preferred: 1, maximum: 1 }, questionsAsked: ["SQ-A"], uncertaintyBefore: 1, uncertaintyCurrent: 0.6, informationGain: 0.4, createdBy: actor, createdAt: at, durableLearningStatus: "NOT_YET_EVALUATED", durableKnowledgeEffect: "NONE", executionPermissionGranted: false }; expect(new SocraticSaturationService().decide({ session, gaps: [], marginalInformationGainThreshold: 0.2 })).toMatchObject({ saturated: true, reason: "QUESTION_BUDGET_EXHAUSTED" }); });
});
