import { describe, expect, it } from "vitest";
import { ClaimGranularityGuard, SourceCriticismEngine, SourceCriticismGateAdvisor, SourceCriticismKnowledgeGapIntegrationService } from "@/services/learning-constitution";
import type { ClaimEvidenceLink, SourceAssessment, SourceDependency } from "@/types/learning-constitution";

const at = "2026-09-03T13:00:00.000Z";
const actor = { actorId: "agent:noesis", actorType: "AGENT" as const };
const assessment = (sourceId: string, strength: SourceAssessment["strength"] = "STRONG", scopeMatch: SourceAssessment["scopeMatch"] = "EXACT"): SourceAssessment => ({ assessmentId: `A:${sourceId}`, sourceId, claimId: "CLAIM-29", authority: "OFFICIAL_AUTHORITY", authorityRationale: "Authority is relevant to this claim.", directness: "DIRECT_PRIMARY", volatility: "FAST_CHANGING", recencyAppropriate: true, relevance: "DIRECTLY_RELEVANT", scopeMatch, corroboration: "NONE", conflictIds: [], strength, limitations: [], assessedBy: actor, assessedAt: at, supersedesAssessmentId: null, immutable: true });
const link = (sourceId: string, relation: ClaimEvidenceLink["relation"] = "SUPPORTS"): ClaimEvidenceLink => ({ linkId: `L:${sourceId}`, claimId: "CLAIM-29", sourceId, relation, relevance: "DIRECTLY_RELEVANT", directness: "DIRECT_PRIMARY", scopeMatch: "EXACT", interpretation: "Claim-specific interpretation.", evidenceIds: ["E-29"], createdAt: at, createdBy: actor, immutable: true });
const dependency = (downstreamSourceId: string, upstreamSourceId: string): SourceDependency => ({ dependencyId: `D:${downstreamSourceId}:${upstreamSourceId}`, downstreamSourceId, upstreamSourceId, kind: "CITES", evidence: ["citation"], discoveredAt: at, discoveredBy: actor, immutable: true });

describe("Phase 29 source criticism", () => {
  it("resists citation democracy when many publications derive from one origin", () => { const sources = Array.from({ length: 10 }, (_, index) => `BLOG-${index}`); const decision = new SourceCriticismEngine().assess({ claimId: "CLAIM-29", assessments: sources.map((id) => assessment(id, "WEAK")), links: sources.map((id) => link(id)), dependencies: sources.map((id) => dependency(id, "ARTICLE-ROOT")), burden: "NORMAL" }); expect(decision.majorityGuard).toMatchObject({ triggered: true, publicationCount: 10, independentOriginCount: 1 }); expect(decision.status).toBe("INSUFFICIENT_EVIDENCE"); });
  it("excludes evidence whose scope cannot justify the claim", () => { const decision = new SourceCriticismEngine().assess({ claimId: "CLAIM-29", assessments: [assessment("PROJECT-A", "VERY_STRONG", "OUT_OF_SCOPE")], links: [link("PROJECT-A")], dependencies: [], burden: "LOW" }); expect(decision).toMatchObject({ status: "INSUFFICIENT_EVIDENCE", excludedOutOfScopeSourceIds: ["PROJECT-A"] }); });
  it("detects circular sourcing rather than mistaking it for corroboration", () => { const decision = new SourceCriticismEngine().assess({ claimId: "CLAIM-29", assessments: [assessment("A"), assessment("B"), assessment("C")], links: [link("A"), link("B"), link("C")], dependencies: [dependency("A", "B"), dependency("B", "C"), dependency("C", "A")], burden: "NORMAL" }); expect(decision.circularSourceIds).toEqual(expect.arrayContaining(["A", "B", "C"])); expect(decision.status).toBe("INSUFFICIENT_EVIDENCE"); });
  it("routes a meaningful competing structure to conflict analysis instead of source-count voting", () => { const decision = new SourceCriticismEngine().assess({ claimId: "CLAIM-29", assessments: [assessment("CURRENT-OFFICIAL", "STRONG"), assessment("OLDER-OFFICIAL", "STRONG")], links: [link("CURRENT-OFFICIAL"), link("OLDER-OFFICIAL", "CONTRADICTS")], dependencies: [], burden: "NORMAL" }); expect(decision).toMatchObject({ status: "CONFLICTING", recommendedAction: "INVOKE_CONFLICT_ENGINE" }); });
  it("does not let an outdated source satisfy a fast-changing claim", () => { const stale = { ...assessment("OLD-OFFICIAL", "VERY_STRONG"), recencyAppropriate: false }; const decision = new SourceCriticismEngine().assess({ claimId: "CLAIM-29", assessments: [stale], links: [link("OLD-OFFICIAL")], dependencies: [], burden: "NORMAL" }); expect(decision).toMatchObject({ status: "INSUFFICIENT_EVIDENCE", excludedStaleSourceIds: ["OLD-OFFICIAL"] }); });
  it("blocks scope inflation and converts inadequate evidence into a Phase 25-compatible gap signal", () => { expect(new ClaimGranularityGuard().evaluate({ observedScope: ["PROJECT_A"], proposedScope: ["PROJECT_A", "ALL_PROJECTS"], unsupportedExpansion: [], causalStepsBeyondObservation: 0 })).toMatchObject({ allowed: false, disposition: "NARROW_SCOPE" }); const decision = new SourceCriticismEngine().assess({ claimId: "CLAIM-29", assessments: [assessment("WEAK", "WEAK")], links: [link("WEAK")], dependencies: [], burden: "NORMAL" }); expect(new SourceCriticismGateAdvisor().advise(decision)).toMatchObject({ disposition: "DEFER", reason: "SOURCE_INSUFFICIENT" }); expect(new SourceCriticismKnowledgeGapIntegrationService().toEvidence({ evidenceId: "E-GAP", dimension: "authority", decision })).toMatchObject({ established: false, sourceId: "source-criticism:CLAIM-29" }); });
});
