import { describe, expect, it } from "vitest";
import { StrategyRegistryService } from "@/services/learning-constitution";
import type { StrategyDefinition, StrategyRegistryArtifact, StrategyRegistryStore } from "@/types/learning-constitution";

const at = "2026-09-03T23:00:00.000Z";
const agent = { actorId: "agent:noesis", actorType: "AGENT" as const };
const human = { actorId: "user:teacher", actorType: "HUMAN" as const };
const store = (): StrategyRegistryStore => { const items: StrategyRegistryArtifact[] = []; return { append: async (item) => { const existing = items.find((candidate) => candidate.artifactId === item.artifactId); if (existing) return existing; items.push(item); return item; }, listArtifacts: async (id) => items.filter((item) => item.subjectId === id), listWorkspaceArtifacts: async () => items }; };
const definition = (): StrategyDefinition => ({ strategyId: "S-037", name: "Progressive Scaffolding", version: 1, lifecycle: "HYPOTHESIS", purpose: ["PRACTICE"], applicableContexts: ["PROCEDURAL", "COMPLEX_SKILL"], prerequisites: ["BASIC_CONCEPT"], steps: [{ ordinal: 1, primitive: "WORKED_EXAMPLE" }, { ordinal: 2, primitive: "GUIDED_PRACTICE" }, { ordinal: 3, primitive: "NOVEL_PRACTICE" }], parameters: [{ name: "guidedExercises", value: 2, minimum: 1, maximum: 5, required: true }], stopConditions: ["OBJECTIVE_SATISFIED", "MAX_ATTEMPTS", "LEASE_EXPIRED"], parentVersionId: null, evidenceIds: ["TREND-36"], knownExceptions: ["Not appropriate for trivial factual recall."], createdBy: agent, createdAt: at, learningEffect: "NONE", authorityEffect: "UNCHANGED", executionPermissionGranted: false });

describe("Phase 37 strategy registry foundation", () => {
  it("stores structured strategy hypotheses as non-authoritative, reusable records", async () => { const artifacts = store(); const service = new StrategyRegistryService(artifacts); const strategy = await service.register(definition()); expect(strategy.steps.map((step) => step.primitive)).toEqual(["WORKED_EXAMPLE", "GUIDED_PRACTICE", "NOVEL_PRACTICE"]); expect(await artifacts.listArtifacts(strategy.strategyId)).toHaveLength(1); expect(strategy).toMatchObject({ lifecycle: "HYPOTHESIS", learningEffect: "NONE", authorityEffect: "UNCHANGED", executionPermissionGranted: false }); });
  it("prevents autonomous approval or activation", async () => { const service = new StrategyRegistryService(store()); const strategy = definition(); await expect(service.transition({ eventId: "E-APPROVE", strategy: { ...strategy, lifecycle: "VALIDATED" }, to: "APPROVED", reason: "Evidence review passed.", actor: agent, occurredAt: at })).rejects.toThrow("only a human governor"); await expect(service.transition({ eventId: "E-ACTIVE", strategy: { ...strategy, lifecycle: "APPROVED" }, to: "ACTIVE", reason: "Governed activation.", actor: human, occurredAt: at })).resolves.toMatchObject({ from: "APPROVED", to: "ACTIVE", immutable: true, executionPermissionGranted: false, authorityEffect: "UNCHANGED" }); });
  it("rejects invalid lifecycle jumps and malformed strategy architecture", async () => { const service = new StrategyRegistryService(store()); await expect(service.transition({ eventId: "E-JUMP", strategy: definition(), to: "ACTIVE", reason: "Skip review.", actor: human, occurredAt: at })).rejects.toThrow("invalid strategy lifecycle transition"); await expect(service.register({ ...definition(), steps: [{ ordinal: 0, primitive: "EXPLAIN" }] })).rejects.toThrow("strategy steps and parameters"); });
});
