import { describe, expect, it } from "vitest";
import { StrategyEligibilityService, StrategyRecommendationService } from "@/services/learning-constitution";
import type { StrategyDefinition, StrategyEligibility } from "@/types/learning-constitution";

const at = "2026-09-04T00:00:00.000Z"; const actor = { actorId: "human:teacher", actorType: "HUMAN" as const };
const strategy = (id: string, lifecycle: StrategyDefinition["lifecycle"] = "ACTIVE", parameters: StrategyDefinition["parameters"] = []): StrategyDefinition => ({ strategyId: id, name: `Strategy ${id}`, version: 1, lifecycle, purpose: ["PRACTICE"], applicableContexts: ["PROCEDURAL"], prerequisites: ["BASIC"], steps: [{ ordinal: 1, primitive: "WORKED_EXAMPLE" }], parameters, stopConditions: ["MAX_ATTEMPTS"], parentVersionId: null, evidenceIds: [], knownExceptions: [], createdBy: actor, createdAt: at, learningEffect: "NONE", authorityEffect: "UNCHANGED", executionPermissionGranted: false });
const budget = { timeMinutes: 45, tokenBudget: 30000, teacherAvailability: "LOW" as const, risk: "MEDIUM" as const, requiredRetention: "HIGH" as const };
describe("Phase 37 strategy eligibility and recommendations", () => {
  it("filters context, prerequisite, budget, and lifecycle failures before ranking", () => { const service = new StrategyEligibilityService(); expect(service.assess({ strategy: strategy("S-BAD", "HYPOTHESIS", [{ name: "tokenBudget", value: 40000, required: false }]), context: "PROCEDURAL", establishedPrerequisites: [], budget, requiredResources: ["R1"], availableResources: [] })).toMatchObject({ eligible: false, reasons: expect.arrayContaining(["STRATEGY_NOT_ACTIVE", "PREREQUISITES_UNMET", "RESOURCES_UNAVAILABLE", "BUDGET_OR_TEACHER_CONSTRAINT"]), projectionOnly: true, executionPermissionGranted: false }); });
  it("explains the selected eligible strategy while preserving approval and execution boundaries", () => { const eligibility: StrategyEligibility = new StrategyEligibilityService().assess({ strategy: strategy("S-GOOD"), context: "PROCEDURAL", establishedPrerequisites: ["BASIC"], budget, requiredResources: [], availableResources: [] }); const result = new StrategyRecommendationService().recommend({ recommendationId: "REC-37", objectiveId: "LO-37", candidates: [{ strategy: strategy("S-GOOD"), eligibility, observedEvidenceState: "SUPPORTED_PATTERN", observedStrengths: ["Strong delayed retention"], knownCosts: ["More time than direct instruction"] }], createdAt: at }); expect(result).toMatchObject({ selectedStrategyId: "S-GOOD", status: "AWAITING_APPROVAL", recommendationOnly: true, autonomousPlanChangeAuthorized: false, executionPermissionGranted: false, authorityEffect: "UNCHANGED" }); expect(result.explanation.join(" ")).toContain("approved learning plan"); });
});
