import { describe, expect, it } from "vitest";
import { InMemoryLearningAuditLedger, StrategyApprovalBridgeService } from "@/services/learning-constitution";
import type { SelfDirectedLearningArtifactRecord, SelfDirectedLearningArtifactStore } from "@/types/learning-constitution";
const at = "2026-09-04T21:00:00.000Z"; const actor = { actorId: "human:teacher", actorType: "HUMAN" as const };
const store = (): SelfDirectedLearningArtifactStore => { const rows: SelfDirectedLearningArtifactRecord[] = []; return { append: async (item) => { rows.push(item); return item; }, listArtifacts: async (id) => rows.filter((item) => item.subjectId === id), listWorkspaceArtifacts: async () => rows }; };
const objective = { profileId: "OBJ", objectiveId: "LO", domain: "Security", primaryType: "DIAGNOSTIC" as const, typeConfidence: .9, secondaryTypes: [], currentMastery: "COMPETENT" as const, targetMastery: "ADVANCED" as const, risk: "HIGH" as const, transferRequirement: "HIGH" as const, retentionRequirement: "HIGH" as const, prerequisites: [], knowledgeGapIds: ["GAP-1"], constraints: [], classifierVersion: "v1", createdAt: at, immutable: true as const };
const selection = { selectionId: "SEL", requestId: "REQ", objectiveProfileId: "OBJ", selectedStrategyId: "S-1", mode: "EXPLOIT" as const, status: "RECOMMENDED" as const, scores: [], rationale: [], policyVersion: "p1", classifierVersion: "v1", registryVersion: "r1", evidenceSnapshotId: "e1", createdAt: at, immutable: true as const, recommendationOnly: true as const, executionPermissionGranted: false as const, authorityEffect: "UNCHANGED" as const };
const proposal = { proposalId: "SCP", selectionId: "SEL", objectiveProfileId: "OBJ", objectiveId: "LO", goal: "Diagnose failures", strategyIds: ["S-1"], requiredEvaluationDimensions: ["IMMEDIATE", "TRANSFER", "RETENTION"] as const, status: "AWAITING_HUMAN_APPROVAL" as const, createdAt: at, immutable: true as const, executionAuthorized: false as const, requiresExecutionLease: true as const, authorityEffect: "UNCHANGED" as const };
describe("Phase 40 human approval bridge", () => { it("creates the existing governed proposal and matching human-issued lease", async () => { const artifacts = store(); const result = await new StrategyApprovalBridgeService(artifacts, new InMemoryLearningAuditLedger()).approve({ bridgeId: "BRIDGE", proposal, selection, objective, actor, maximumQuestions: 5, estimatedQuestions: 3, estimatedMinutes: 30, expiresAt: "2026-09-05T21:00:00.000Z", currentState: "UNKNOWN", impact: "HIGH", createdAt: at, workspaceId: "workspace", correlationId: "corr" }); expect(result).toMatchObject({ bridge: { executionAuthorized: true, immutable: true }, lease: { status: "ACTIVE", method: "TARGETED_EVALUATION" } }); expect((await artifacts.listWorkspaceArtifacts()).map((item) => item.artifactType)).toEqual(["OPPORTUNITY", "PROPOSAL", "APPROVAL", "LEASE"]); }); it("requires a linked gap before approval", async () => { await expect(new StrategyApprovalBridgeService(store()).approve({ bridgeId: "bad", proposal, selection, objective: { ...objective, knowledgeGapIds: [] }, actor, maximumQuestions: 5, estimatedQuestions: 3, estimatedMinutes: 30, expiresAt: "2026-09-05T21:00:00.000Z", currentState: "UNKNOWN", impact: "HIGH", createdAt: at, workspaceId: "workspace", correlationId: "corr" })).rejects.toThrow("linked knowledge gap"); }); });
