export type AutonomyAuditEpisodeErrorCode =
  | "AUTONOMY_AUDIT_EPISODE_INVALID"
  | "AUTONOMY_REPLAY_MISMATCH"
  | "AUTONOMY_EVIDENCE_MISSING"
  | "AUTONOMY_POLICY_REFERENCE_INVALID"
  | "AUTONOMY_TIMESTAMP_VIOLATION"
  | "AUTONOMY_RECOMMENDATION_REPLAY_FAILED"
  | "AUTONOMY_OPERATOR_LINEAGE_INVALID"
  | "AUTONOMY_APPROVAL_BINDING_INVALID"
  | "AUTONOMY_RISK_RECONSTRUCTION_FAILED"
  | "AUTONOMY_GOVERNANCE_LINK_MISSING";

export type AutonomyAuditEpisodeError = Readonly<{
  code: AutonomyAuditEpisodeErrorCode;
  message: string;
  path?: string;
}>;
