import Link from "next/link";
import { requireSessionUser } from "@/src/lib/auth";
import { requireWorkspaceManager } from "@/src/server/auth/permissions";
import { PrismaStrategyRegistryRepository } from "@/services/learning-constitution";
import type { RegistryStrategyHypothesis, StrategyDefinition, StrategyExperiment, StrategyGovernanceDecision } from "@/types/learning-constitution";

export const dynamic = "force-dynamic";

/** Read-only registry inspection. Nothing on this page can create, select, approve, activate, execute, or roll back a strategy. */
export default async function StrategyRegistryPage() {
  const user = await requireSessionUser();
  if (!user.workspaceId || user.workspaceId === "default") return <main className="p-6">Workspace membership required.</main>;
  await requireWorkspaceManager({ userId: user.id, userRole: user.role, workspaceId: user.workspaceId });
  const artifacts = await new PrismaStrategyRegistryRepository(user.workspaceId).listWorkspaceArtifacts();
  const strategies = artifacts.filter((item) => item.artifactType === "STRATEGY").map((item) => item.payload as StrategyDefinition);
  const hypotheses = artifacts.filter((item) => item.artifactType === "HYPOTHESIS").map((item) => item.payload as RegistryStrategyHypothesis);
  const experiments = artifacts.filter((item) => item.artifactType === "EXPERIMENT").map((item) => item.payload as StrategyExperiment);
  const decisions = artifacts.filter((item) => item.artifactType === "GOVERNANCE_DECISION").map((item) => item.payload as StrategyGovernanceDecision);
  const active = strategies.filter((strategy) => strategy.lifecycle === "ACTIVE").length;
  return <main className="mx-auto max-w-5xl space-y-6 p-6"><header><p className="text-sm font-medium uppercase tracking-wide text-violet-700">Noesis · Phase 37</p><h1 className="text-2xl font-semibold">Strategy Registry</h1><p className="mt-1 text-sm text-slate-600">Governed learning methods are transparent, versioned objects. Registry evidence informs review; it does not authorize execution or change the Learning Constitution.</p></header><section className="grid gap-4 md:grid-cols-4"><Metric label="Registry versions" value={strategies.length} /><Metric label="Active" value={active} /><Metric label="Hypotheses" value={hypotheses.length} /><Metric label="Experiments" value={experiments.length} /></section><section className="rounded border p-4"><h2 className="font-medium">Strategy definitions</h2>{strategies.length ? <ul className="mt-3 space-y-3">{strategies.slice().reverse().map((strategy) => <li key={`${strategy.strategyId}:${strategy.version}`} className="rounded border border-slate-200 p-3"><p className="font-medium">{strategy.strategyId} v{strategy.version} · {strategy.name} <span className="font-mono text-xs">{strategy.lifecycle}</span></p><p className="mt-1 text-sm text-slate-600">{strategy.applicableContexts.join(" · ")} · {strategy.steps.map((step) => step.primitive).join(" → ")}</p><p className="mt-1 text-xs text-slate-500">{strategy.evidenceIds.length} evidence references · {strategy.knownExceptions.length} known exceptions · execution permission: none</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-600">No governed strategy definitions have been registered.</p>}</section><section className="grid gap-4 md:grid-cols-2"><ArtifactList title="Proposed hypotheses" items={hypotheses.map((item) => ({ id: item.hypothesisId, label: `${item.strategyId} · ${item.evidenceState}`, detail: item.proposedChange }))} /><ArtifactList title="Governance decisions" items={decisions.map((item) => ({ id: item.decisionId, label: `${item.strategyId} v${item.version} · ${item.decision}`, detail: item.reason }))} /></section><p className="text-sm"><Link className="text-violet-700 underline" href="/learning/analytics">Learning Analytics</Link> · <Link className="text-violet-700 underline" href="/learning/retention">Retention Engine</Link> · <Link className="text-violet-700 underline" href="/learning/capabilities">Capability Boundary</Link></p></main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <article className="rounded border p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></article>; }
function ArtifactList({ title, items }: { title: string; items: readonly { id: string; label: string; detail: string }[] }) { return <section className="rounded border p-4"><h2 className="font-medium">{title}</h2>{items.length ? <ul className="mt-3 space-y-2">{items.slice().reverse().map((item) => <li key={item.id} className="rounded border border-slate-200 p-3"><p className="text-sm font-medium">{item.label}</p><p className="mt-1 text-xs text-slate-600">{item.detail}</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-600">None recorded.</p>}</section>; }
