import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runWaveFiveTasksCommitments, validateWaveFiveTasksCommitments } from "@/services/wave-five-tasks-commitments";
import type { WaveFiveHealthBundle, WaveFiveHealthDecision, WaveFiveHealthFailure, WaveFiveHealthInput, WaveFiveHealthResult, WaveFiveHealthScenario, WaveFiveHealthValidation } from "@/types/wave-five-health";

const VERSION = "wave-five-health/w5.8" as const;
const IDENTIFIER = "WaveFiveHealth" as const;
const UPSTREAM_REFS = Object.freeze(["wave-five-tasks-commitments/w5.5", "wave-five-calendar-time/w5.4", "wave-five-personal-knowledge/w5.3", "wave-five-unified-personal-context/w5.2", "wave-five-application-platform/w5.1"]);
const PROVIDES = Object.freeze(["health-service", "health-registry", "wellness-tracking-engine", "recommendation-engine", "goal-management-service", "health-dashboard", "escalation-service", "health-evidence-registry", "health-apis", "health-governance-policies"]);
let tasks = runWaveFiveTasksCommitments();

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly WaveFiveHealthFailure[], failure: WaveFiveHealthFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: WaveFiveHealthScenario): WaveFiveHealthFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly WaveFiveHealthFailure[], scenario?: WaveFiveHealthScenario): WaveFiveHealthDecision {
  const notQualified = new Set<WaveFiveHealthFailure>(["W5_TASKS_COMMITMENTS_INVALID", "HEALTH_IDENTITY_NONDETERMINISTIC", "WELLNESS_HISTORY_NONDETERMINISTIC", "GOAL_PROGRESS_NONDETERMINISTIC", "RECOMMENDATIONS_NOT_EXPLAINABLE", "RECOMMENDATIONS_NOT_EVIDENCE_BACKED", "ESCALATION_NONDETERMINISTIC", "CONSENT_NOT_ENFORCED", "PRIVACY_CONTROLS_MISSING", "ACCESS_CONTROL_MISSING", "AUDIT_LINEAGE_INCOMPLETE", "TENANT_ISOLATION_BREACH", "HEALTH_EVIDENCE_MUTABLE", "REPLAY_DIVERGED", "DIAGNOSTIC_BEHAVIOR_DETECTED", "TREATMENT_BEHAVIOR_DETECTED", "PRESCRIPTION_BEHAVIOR_DETECTED", "MEDICAL_DECISION_BEHAVIOR_DETECTED", "EMERGENCY_DETERMINATION_DETECTED", "MEDICAL_CERTAINTY_CLAIMED"]);
  if (failures.some((failure) => notQualified.has(failure))) return "NOT_QUALIFIED";
  if (has(failures, "HEALTH_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_QUALIFIED";
  return "QUALIFIED";
}
function resultReplayHash(result: Omit<WaveFiveHealthResult, "replay_hash" | "integrity_hash">): string { return hash({ profile: result.profile.integrity_hash, tracking: result.tracking.integrity_hash, dashboard: result.dashboard.integrity_hash, goals: result.goals.integrity_hash, recommendations: result.recommendations.integrity_hash, escalation: result.escalation.integrity_hash, evidence_governance: result.evidence_governance.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<WaveFiveHealthResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runWaveFiveHealth(input: WaveFiveHealthInput = {}): WaveFiveHealthResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  tasks = runWaveFiveTasksCommitments();
  const failures = freezeArray([...new Set([...(direct ? [direct] : []), ...(!validateWaveFiveTasksCommitments(tasks).valid ? ["W5_TASKS_COMMITMENTS_INVALID" as const] : [])])]);
  const profileOk = !has(failures, "HEALTH_PROFILE_MISSING") && !has(failures, "HEALTH_PROFILE_LINEAGE_INCOMPLETE") && !has(failures, "HEALTH_PROFILE_VERSIONING_MISSING") && !has(failures, "HEALTH_IDENTITY_NONDETERMINISTIC");
  const trackingOk = !has(failures, "WELLNESS_TRACKING_MISSING") && !has(failures, "WELLNESS_HISTORY_NONDETERMINISTIC") && !has(failures, "WELLNESS_TRENDS_INVALID") && !has(failures, "MEASUREMENT_EVIDENCE_MISSING");
  const dashboardOk = !has(failures, "HEALTH_DASHBOARD_MISSING") && !has(failures, "DASHBOARD_EVIDENCE_NAVIGATION_MISSING") && !has(failures, "DASHBOARD_TRENDS_INVALID");
  const goalsOk = !has(failures, "HEALTH_GOALS_MISSING") && !has(failures, "GOAL_PROGRESS_NONDETERMINISTIC") && !has(failures, "GOAL_REVIEWS_NOT_EVIDENCE_BACKED");
  const recsOk = !has(failures, "RECOMMENDATION_ENGINE_MISSING") && !has(failures, "RECOMMENDATIONS_NOT_EXPLAINABLE") && !has(failures, "RECOMMENDATIONS_NOT_EVIDENCE_BACKED") && !has(failures, "RECOMMENDATION_CONFIDENCE_MISSING") && !has(failures, "DIAGNOSTIC_BEHAVIOR_DETECTED") && !has(failures, "TREATMENT_BEHAVIOR_DETECTED") && !has(failures, "PRESCRIPTION_BEHAVIOR_DETECTED") && !has(failures, "MEDICAL_DECISION_BEHAVIOR_DETECTED") && !has(failures, "MEDICAL_CERTAINTY_CLAIMED");
  const escalationOk = !has(failures, "ESCALATION_FRAMEWORK_MISSING") && !has(failures, "ESCALATION_NONDETERMINISTIC") && !has(failures, "ESCALATION_EVIDENCE_MISSING") && !has(failures, "ESCALATION_HISTORY_MISSING") && !has(failures, "EMERGENCY_DETERMINATION_DETECTED");
  const evidenceOk = !has(failures, "HEALTH_EVIDENCE_INTEGRATION_MISSING") && !has(failures, "EVIDENCE_INGESTION_NONDETERMINISTIC") && !has(failures, "SOURCE_PROVENANCE_MISSING") && !has(failures, "EVIDENCE_NORMALIZATION_INVALID") && !has(failures, "HEALTH_GOVERNANCE_MISSING") && !has(failures, "CONSENT_NOT_ENFORCED") && !has(failures, "PRIVACY_CONTROLS_MISSING") && !has(failures, "ACCESS_CONTROL_MISSING") && !has(failures, "AUDIT_LINEAGE_INCOMPLETE") && !has(failures, "TENANT_ISOLATION_BREACH") && !has(failures, "HEALTH_EVIDENCE_MUTABLE") && !has(failures, "REPLAY_DIVERGED");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "QUALIFIED";
  const profile = nested({ profile_id: input.health_profile_id ?? (profileOk ? "health-profile:w5.8:canonical" : ""), health_identity: profileOk, demographics: profileOk, wellness_preferences: profileOk, lifestyle_profile: profileOk, medical_information_references: profileOk, allergies: profileOk, medications_reference: profileOk, health_history_references: profileOk, care_team_references: profileOk, health_metadata: profileOk, canonical_health_record: profileOk, profile_versioning: profileOk, evidence_linkage: profileOk, immutable_lineage: profileOk, identity_deterministic: profileOk });
  const tracking = nested({ tracking_id: trackingOk ? "W5.8-WELLNESS-TRACKING-001" : "", weight_tracking: trackingOk, nutrition_tracking: trackingOk, activity_tracking: trackingOk, sleep_tracking: trackingOk, hydration_tracking: trackingOk, mood_tracking: trackingOk, stress_tracking: trackingOk, habit_tracking: trackingOk, wellness_journals: trackingOk, measurement_history: trackingOk, longitudinal_tracking: trackingOk, trend_generation: trackingOk, evidence_capture: trackingOk, historical_comparisons: trackingOk, deterministic_history: trackingOk });
  const dashboard = nested({ dashboard_id: dashboardOk ? "W5.8-HEALTH-DASHBOARD-001" : "", wellness_summary: dashboardOk, progress_dashboard: dashboardOk, goal_progress: dashboardOk, habit_dashboard: dashboardOk, trend_analysis: dashboardOk, risk_indicators: dashboardOk, wellness_timeline: dashboardOk, achievement_history: dashboardOk, unified_health_view: dashboardOk, historical_visualization: dashboardOk, progress_reporting: dashboardOk, evidence_navigation: dashboardOk, trends_validated: dashboardOk });
  const goals = nested({ goals_id: goalsOk ? "W5.8-HEALTH-GOALS-001" : "", goal_registry: goalsOk, goal_planning: goalsOk, milestones: goalsOk, progress_monitoring: goalsOk, goal_reviews: goalsOk, goal_adjustments: goalsOk, habit_goals: goalsOk, wellness_targets: goalsOk, measurable_goals: goalsOk, deterministic_progress_calculation: goalsOk, milestone_evaluation: goalsOk, evidence_backed_reviews: goalsOk });
  const recommendations = nested({ recommendation_id: recsOk ? "W5.8-WELLNESS-RECOMMENDATIONS-001" : "", wellness_guidance: recsOk, nutrition_suggestions: recsOk, activity_suggestions: recsOk, recovery_suggestions: recsOk, habit_recommendations: recsOk, educational_guidance: recsOk, evidence_mapping: recsOk, recommendation_history: recsOk, advisory_only: recsOk, explainable_outputs: recsOk, confidence_reporting: recsOk, constitutional_safeguards: recsOk, no_diagnosis: recsOk, no_treatment: recsOk, no_prescription: recsOk, no_medical_decision: recsOk, no_medical_certainty: recsOk });
  const escalation = nested({ escalation_id: escalationOk ? "W5.8-HEALTH-ESCALATION-001" : "", risk_thresholds: escalationOk, escalation_rules: escalationOk, warning_detection: escalationOk, emergency_recommendation_rules: escalationOk, healthcare_referral_guidance: escalationOk, escalation_evidence: escalationOk, escalation_history: escalationOk, deterministic_escalation: escalationOk, evidence_backed_alerts: escalationOk, operator_visibility: escalationOk, constitutional_restrictions: escalationOk, no_emergency_determination: escalationOk });
  const evidence_governance = nested({ evidence_id: evidenceOk ? "W5.8-HEALTH-EVIDENCE-GOVERNANCE-001" : "", wearable_integration: evidenceOk, manual_entry: evidenceOk, imported_health_records: evidenceOk, nutrition_sources: evidenceOk, activity_sources: evidenceOk, sleep_sources: evidenceOk, device_metadata: evidenceOk, evidence_validation: evidenceOk, source_attribution: evidenceOk, provenance: evidenceOk, deterministic_ingestion: evidenceOk, evidence_normalization: evidenceOk, consent_management: evidenceOk, privacy_policies: evidenceOk, access_policies: evidenceOk, data_retention: evidenceOk, health_audit: evidenceOk, constitutional_rules: evidenceOk, compliance_validation: evidenceOk, encryption: evidenceOk, access_control: evidenceOk, audit_lineage: evidenceOk, tenant_isolation: evidenceOk, immutable_evidence: evidenceOk });
  const readiness = nested({ readiness_id: "W5.8-HEALTH-READINESS-001", decision, phase_ready: qualified, upstream_ready: !has(failures, "W5_TASKS_COMMITMENTS_INVALID"), profile_ready: profileOk, tracking_ready: trackingOk, dashboard_ready: dashboardOk, goals_ready: goalsOk, recommendations_ready: recsOk, escalation_ready: escalationOk, evidence_governance_ready: evidenceOk, health_profile_operational: profileOk, wellness_tracking_deterministic: trackingOk, health_dashboard_unified: dashboardOk, health_goals_measurable: goalsOk, recommendations_explainable_evidence_backed: recsOk, escalation_deterministic_immutable: escalationOk && evidenceOk, consent_privacy_audit_governed: evidenceOk, evidence_lineage_complete: profileOk && trackingOk && evidenceOk, replay_identical_recommendations: recsOk && evidenceOk, advisory_only_verified: recsOk, diagnosis_treatment_prescription_prohibited: recsOk && escalationOk, failures });
  const base: Omit<WaveFiveHealthResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id: input.tenant_id ?? tasks.tenant_id, principal_id: input.principal_id ?? tasks.principal_id, health_profile_id: profile.profile_id, profile, tracking, dashboard, goals, recommendations, escalation, evidence_governance, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateWaveFiveHealth(result?: WaveFiveHealthResult): WaveFiveHealthValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, profile_valid: false, tracking_valid: false, dashboard_valid: false, goals_valid: false, recommendations_valid: false, escalation_valid: false, evidence_governance_valid: false, readiness_valid: false, failures: freezeArray(["HEALTH_PROFILE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const profile_valid = verifyHashed(result.profile) && result.profile.canonical_health_record && result.profile.profile_versioning && result.profile.immutable_lineage && result.profile.identity_deterministic;
  const tracking_valid = verifyHashed(result.tracking) && result.tracking.longitudinal_tracking && result.tracking.trend_generation && result.tracking.evidence_capture && result.tracking.deterministic_history;
  const dashboard_valid = verifyHashed(result.dashboard) && result.dashboard.unified_health_view && result.dashboard.progress_reporting && result.dashboard.evidence_navigation && result.dashboard.trends_validated;
  const goals_valid = verifyHashed(result.goals) && result.goals.measurable_goals && result.goals.deterministic_progress_calculation && result.goals.milestone_evaluation && result.goals.evidence_backed_reviews;
  const recommendations_valid = verifyHashed(result.recommendations) && result.recommendations.advisory_only && result.recommendations.explainable_outputs && result.recommendations.confidence_reporting && result.recommendations.no_diagnosis && result.recommendations.no_treatment && result.recommendations.no_prescription && result.recommendations.no_medical_decision && result.recommendations.no_medical_certainty;
  const escalation_valid = verifyHashed(result.escalation) && result.escalation.deterministic_escalation && result.escalation.evidence_backed_alerts && result.escalation.constitutional_restrictions && result.escalation.no_emergency_determination;
  const evidence_governance_valid = verifyHashed(result.evidence_governance) && result.evidence_governance.provenance && result.evidence_governance.deterministic_ingestion && result.evidence_governance.consent_management && result.evidence_governance.encryption && result.evidence_governance.access_control && result.evidence_governance.audit_lineage && result.evidence_governance.tenant_isolation && result.evidence_governance.immutable_evidence;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.advisory_only_verified && result.readiness.diagnosis_treatment_prescription_prohibited && result.readiness.consent_privacy_audit_governed && result.readiness.replay_identical_recommendations && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && profile_valid && tracking_valid && dashboard_valid && goals_valid && recommendations_valid && escalation_valid && evidence_governance_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, profile_valid, tracking_valid, dashboard_valid, goals_valid, recommendations_valid, escalation_valid, evidence_governance_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayWaveFiveHealth(result = runWaveFiveHealth()): boolean { const replayed = runWaveFiveHealth(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateWaveFiveHealth(result).valid; }
export function getWaveFiveHealthBundle(): WaveFiveHealthBundle { const result = runWaveFiveHealth(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, health_guidance_advisory_only: true, diagnosis_prohibited: true, treatment_prescription_prohibited: true, human_medical_authority_preserved: true, evidence_explainability_required: true, privacy_consent_audit_required: true, qualification_gate: "W5.8 Health Qualification Gate" }), result, validation: validateWaveFiveHealth(result) }); }
export const WaveFiveHealthService = Object.freeze({ run: runWaveFiveHealth, validate: validateWaveFiveHealth, replay: replayWaveFiveHealth });
