export type CorrelationErrorCode =
  | "PHASE_4_6B_CORRELATION_INPUT_MISSING"
  | "PHASE_4_6B_CORRELATION_AMBIGUOUS_TOPOLOGY"
  | "PHASE_4_6B_CORRELATION_RECURSIVE_GRAPH"
  | "PHASE_4_6B_CORRELATION_TRANSITIVE_INFERENCE_REJECTED"
  | "PHASE_4_6B_CORRELATION_APPROVAL_INHERITANCE_REJECTED"
  | "PHASE_4_6B_CORRELATION_EXECUTION_LEAKAGE_REJECTED"
  | "PHASE_4_6B_CORRELATION_ORCHESTRATION_LEAKAGE_REJECTED"
  | "PHASE_4_6B_CORRELATION_WORKFLOW_SYNTHESIS_REJECTED"
  | "PHASE_4_6B_CORRELATION_DISPATCH_INFERENCE_REJECTED"
  | "PHASE_4_6B_CORRELATION_SCHEDULING_INFERENCE_REJECTED"
  | "PHASE_4_6B_CORRELATION_RUNTIME_MUTATION_REJECTED"
  | "PHASE_4_6B_CORRELATION_CAPABILITY_EXPANSION_REJECTED"
  | "PHASE_4_6B_CORRELATION_REPLAY_BINDING_MISSING"
  | "PHASE_4_6B_CORRELATION_REPLAY_MISMATCH"
  | "PHASE_4_6B_CORRELATION_GOVERNANCE_MISMATCH"
  | "PHASE_4_6B_CORRELATION_READINESS_MISMATCH"
  | "PHASE_4_6B_CORRELATION_CONFIDENCE_MUTATION_REJECTED"
  | "PHASE_4_6B_CORRELATION_ESCALATION_AUTHORITY_REJECTED"
  | "PHASE_4_6B_CORRELATION_NON_DETERMINISTIC_OUTPUT";

export interface IntentCorrelationError {
  code: CorrelationErrorCode;
  message: string;
  path?: string;
}
