import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runProvingCrossProgramIntegrationValidation, validateProvingCrossProgramIntegrationValidation } from "@/services/proving-cross-program-integration-validation";
import type { ExerciseCategory, ExerciseFrameworkReport, ExerciseLifecycleState, OperationalExerciseBundle, OperationalExerciseFailure, OperationalExerciseInput, OperationalExerciseResult, OperationalExerciseScenario, OperationalExerciseValidation, ReadinessDimension } from "@/types/proving-operational-exercise-framework";

const VERSION = "proving-operational-exercise-framework/v6.11" as const;
const IDENTIFIER = "ProvingOperationalExerciseFramework" as const;
const LIFECYCLE = Object.freeze<ExerciseLifecycleState[]>(["DRAFT", "APPROVED", "PROVISIONED", "PREPARED", "EXECUTING", "COMPLETED", "EVALUATED", "REPORTED", "ARCHIVED"]);
const CATEGORIES = Object.freeze<ExerciseCategory[]>(["TABLETOP", "MISSION_REHEARSAL", "OPERATOR_DRILL", "GOVERNANCE_EXERCISE", "EMERGENCY_SIMULATION"]);
const DIMENSIONS = Object.freeze<ReadinessDimension[]>(["OPERATIONAL", "GOVERNANCE", "MISSION", "TRUST", "COORDINATION", "PROCEDURAL", "RESILIENCE", "ECOSYSTEM"]);
let integrationBaseline: ReturnType<typeof runProvingCrossProgramIntegrationValidation> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly OperationalExerciseFailure[], failure: OperationalExerciseFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: OperationalExerciseScenario): OperationalExerciseFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function outcome(failures: readonly OperationalExerciseFailure[]) { if (has(failures, "GOVERNANCE_REVIEW_REQUIRED")) return "REQUIRES_REVIEW" as const; return failures.length ? "FAIL" as const : "PASS" as const; }
function refs(ok: boolean, name: string): readonly string[] { return ok ? freezeArray([`evidence:p6.11:${name}`]) : freezeArray<string>([]); }
function frameworkReport(category: ExerciseCategory, ok: boolean, evidenceOk: boolean): ExerciseFrameworkReport {
  const label = category.toLowerCase().replace("_", "-");
  return nested({ report_id: ok ? `report:p6.11:${label}` : "", category, supported: ok, validates: ok ? freezeArray(["governance decisions", "operator workflow", "coordination", "readiness"]) : freezeArray<string>([]), findings: ok ? freezeArray(["validated"]) : freezeArray(["framework incomplete"]), evidence_refs: refs(evidenceOk, label) });
}
function resultReplayHash(result: Omit<OperationalExerciseResult, "replay_hash" | "integrity_hash">): string { return hash({ architecture: result.architecture.integrity_hash, registry: result.registry.integrity_hash, tabletop: result.tabletop_report.integrity_hash, mission: result.mission_rehearsal_report.integrity_hash, operator: result.operator_drill_report.integrity_hash, governance: result.governance_exercise_report.integrity_hash, emergency: result.emergency_simulation_report.integrity_hash, execution: result.execution.integrity_hash, evaluation: result.evaluation.integrity_hash, metrics: result.readiness_metrics.integrity_hash, evidence: result.evidence.integrity_hash, reporting: result.reporting.integrity_hash, gates: result.gates.integrity_hash, boundaries: result.boundaries.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<OperationalExerciseResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.readiness.outcome, replay_hash: result.replay_hash }); }

export function runProvingOperationalExerciseFramework(input: OperationalExerciseInput = {}): OperationalExerciseResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<OperationalExerciseFailure>(direct ? [direct] : []);
  integrationBaseline ??= runProvingCrossProgramIntegrationValidation();
  const integrationInvalid = !validateProvingCrossProgramIntegrationValidation(integrationBaseline).valid || has(scenarioFailures, "P6_10_INTEGRATION_VALIDATION_INVALID");
  const failures = freezeArray([...new Set([...scenarioFailures, ...(integrationInvalid ? ["P6_10_INTEGRATION_VALIDATION_INVALID" as const] : [])])]);
  const architectureOk = !has(failures, "EXERCISE_ARCHITECTURE_MISSING");
  const registryOk = !has(failures, "EXERCISE_REGISTRY_MISSING") && !has(failures, "EXERCISE_NOT_APPROVED");
  const tabletopOk = !has(failures, "TABLETOP_FRAMEWORK_MISSING");
  const missionOk = !has(failures, "MISSION_REHEARSAL_FRAMEWORK_MISSING");
  const operatorOk = !has(failures, "OPERATOR_DRILL_FRAMEWORK_MISSING");
  const governanceExerciseOk = !has(failures, "GOVERNANCE_EXERCISE_FRAMEWORK_MISSING");
  const emergencyOk = !has(failures, "EMERGENCY_SIMULATION_FRAMEWORK_MISSING");
  const executionOk = !has(failures, "EXECUTION_ENGINE_MISSING") && !has(failures, "EXERCISE_EXECUTION_NONDETERMINISTIC") && !has(failures, "PARTICIPANT_COORDINATION_FAILED") && !has(failures, "ENVIRONMENT_PROVISIONING_FAILED") && !has(failures, "EVENT_SYNCHRONIZATION_FAILED");
  const evaluationOk = !has(failures, "OPERATIONAL_EVALUATION_MISSING") && !has(failures, "OBJECTIVE_COMPLETION_FAILED") && !has(failures, "PROCEDURAL_COMPLIANCE_FAILED") && !has(failures, "MISSION_SUCCESS_FAILED") && !has(failures, "GOVERNANCE_CORRECTNESS_FAILED") && !has(failures, "OPERATOR_EFFECTIVENESS_FAILED") && !has(failures, "COORDINATION_QUALITY_FAILED");
  const metricsOk = !has(failures, "READINESS_METRICS_MISSING") && !has(failures, "READINESS_METRICS_NOT_REPRODUCIBLE");
  const evidenceOk = !has(failures, "EVIDENCE_COLLECTION_MISSING") && !has(failures, "EXERCISE_EVIDENCE_MUTATED") && !has(failures, "EXERCISE_LINEAGE_INCOMPLETE");
  const replayOk = !has(failures, "REPLAY_VALIDATION_FAILED") && !integrationInvalid;
  const reportingOk = !has(failures, "REPORTING_FRAMEWORK_MISSING") && !has(failures, "REPORT_GENERATION_FAILED") && !has(failures, "IMPROVEMENT_RECOMMENDATIONS_MISSING");
  const boundariesOk = !has(failures, "SIMULATION_ENGINE_OWNERSHIP_VIOLATION") && !has(failures, "REPLAY_VALIDATION_OWNERSHIP_VIOLATION") && !has(failures, "ADVERSARIAL_TESTING_OWNERSHIP_VIOLATION") && !has(failures, "RESILIENCE_VALIDATION_OWNERSHIP_VIOLATION") && !has(failures, "PERFORMANCE_TESTING_OWNERSHIP_VIOLATION") && !has(failures, "CROSS_PROGRAM_INTEGRATION_OWNERSHIP_VIOLATION") && !has(failures, "PRODUCTION_OPERATIONS_OWNERSHIP_VIOLATION") && !has(failures, "OPERATOR_CERTIFICATION_ATTEMPTED") && !has(failures, "TRUST_EVALUATION_ATTEMPTED") && !has(failures, "APPLICATION_GOVERNANCE_ATTEMPTED");
  const allCategoriesOk = tabletopOk && missionOk && operatorOk && governanceExerciseOk && emergencyOk;
  const architecture = nested({ architecture_id: architectureOk ? `architecture:p6.11:${input.seed ?? "canonical"}` : "", lifecycle: architectureOk ? LIFECYCLE : freezeArray<ExerciseLifecycleState>([]), execution_architecture: architectureOk, participant_coordination: architectureOk && executionOk, evidence_collection: architectureOk && evidenceOk, exercise_governance: architectureOk && governanceExerciseOk, reporting_pipeline: architectureOk && reportingOk, deterministic: architectureOk && executionOk && replayOk });
  const registry = nested({ registry_id: registryOk ? "registry:p6.11:exercises" : "", categories: registryOk ? CATEGORIES : freezeArray<ExerciseCategory>([]), definitions: registryOk ? freezeArray(["exercise:tabletop", "exercise:mission-rehearsal", "exercise:operator-drill", "exercise:governance", "exercise:emergency"]) : freezeArray<string>([]), objectives: registryOk ? freezeArray(["validate readiness", "exercise governance", "measure coordination"]) : freezeArray<string>([]), prerequisites: registryOk ? freezeArray([integrationBaseline.compatibility_matrix.matrix_id]) : freezeArray<string>([]), participants: registryOk ? freezeArray(["operator:primary", "governance:authority", "application:mission", "platform:services"]) : freezeArray<string>([]), approval_status: registryOk ? "APPROVED" as const : "BLOCKED" as const, execution_history: registryOk ? freezeArray(["execution:p6.11:baseline"]) : freezeArray<string>([]), evidence_lineage: registryOk && evidenceOk ? freezeArray(["evidence:p6.11:exercise"]) : freezeArray<string>([]) });
  const tabletop_report = frameworkReport("TABLETOP", tabletopOk, evidenceOk);
  const mission_rehearsal_report = frameworkReport("MISSION_REHEARSAL", missionOk, evidenceOk);
  const operator_drill_report = frameworkReport("OPERATOR_DRILL", operatorOk, evidenceOk);
  const governance_exercise_report = frameworkReport("GOVERNANCE_EXERCISE", governanceExerciseOk, evidenceOk);
  const emergency_simulation_report = frameworkReport("EMERGENCY_SIMULATION", emergencyOk, evidenceOk);
  const execution = nested({ execution_id: executionOk ? "execution:p6.11:baseline" : "", initialized: executionOk, environments_provisioned: executionOk, participants_assigned: executionOk, events_synchronized: executionOk, evidence_collected: executionOk && evidenceOk, progress_monitored: executionOk, finalized: executionOk, deterministic: executionOk && replayOk, execution_logs: executionOk ? freezeArray(["log:init", "log:provision", "log:execute", "log:finalize"]) : freezeArray<string>([]), timeline_evidence: executionOk && evidenceOk ? freezeArray(["timeline:p6.11:baseline"]) : freezeArray<string>([]) });
  const evaluation = nested({ evaluation_id: evaluationOk ? "evaluation:p6.11:operational" : "", objective_completion: evaluationOk, procedural_compliance: evaluationOk, mission_success: evaluationOk, governance_correctness: evaluationOk, operator_effectiveness: evaluationOk, coordination_quality: evaluationOk, findings: evaluationOk ? freezeArray(["finding:ready", "finding:governance-workflow-valid", "finding:coordination-valid"]) : freezeArray<string>([]), readiness_score: evaluationOk ? 96 : 40 });
  const readiness_metrics = nested({ metrics_id: metricsOk ? "metrics:p6.11:readiness" : "", dimensions: metricsOk ? DIMENSIONS : freezeArray<ReadinessDimension>([]), operator_readiness: metricsOk ? 95 : 0, governance_readiness: metricsOk ? 97 : 0, application_readiness: metricsOk ? 94 : 0, ecosystem_readiness: metricsOk ? 96 : 0, trust_readiness: metricsOk ? 95 : 0, operational_maturity: metricsOk ? 93 : 0, trend_analysis: metricsOk ? freezeArray(["trend:readiness-stable", "trend:coordination-improving"]) : freezeArray<string>([]), reproducible: metricsOk });
  const evidence = nested({ evidence_id: evidenceOk ? "evidence:p6.11:exercise" : "", scenario: "scenario:p6.11:operational-readiness", participants: registry.participants, objectives: registry.objectives, timeline: execution.timeline_evidence, decisions: evidenceOk ? freezeArray(["decision:governance-approval", "decision:operator-action"]) : freezeArray<string>([]), governance_actions: evidenceOk ? freezeArray(["governance:review", "governance:escalation-check"]) : freezeArray<string>([]), replay_references: evidenceOk && replayOk ? freezeArray(["proving-replay-validation-framework/v6.6", integrationBaseline.replay_report.report_id]) : freezeArray<string>([]), audit_records: evidenceOk ? freezeArray(["audit:p6.11:exercise"]) : freezeArray<string>([]), metrics: evidenceOk ? freezeArray([readiness_metrics.metrics_id]) : freezeArray<string>([]), findings: evidenceOk ? evaluation.findings : freezeArray<string>([]), recommendations: evidenceOk && reportingOk ? freezeArray(["recommendation:continue-drills", "recommendation:refresh-tabletop-quarterly"]) : freezeArray<string>([]), immutable: evidenceOk, lineage_complete: evidenceOk, replayable: evidenceOk && replayOk });
  const reporting = nested({ reporting_id: reportingOk ? "reporting:p6.11" : "", exercise_reports: reportingOk ? freezeArray([tabletop_report.report_id, mission_rehearsal_report.report_id, operator_drill_report.report_id, governance_exercise_report.report_id, emergency_simulation_report.report_id]) : freezeArray<string>([]), operational_findings: reportingOk ? evaluation.findings : freezeArray<string>([]), readiness_metrics: reportingOk ? freezeArray([readiness_metrics.metrics_id]) : freezeArray<string>([]), executive_summaries: reportingOk ? freezeArray(["summary:p6.11:executive"]) : freezeArray<string>([]), improvement_recommendations: reportingOk ? evidence.recommendations : freezeArray<string>([]), generated: reportingOk });
  const gates = nested({ gate_id: "P6.11-GATES", architecture_gate: architectureOk, registry_gate: registryOk, category_support_gate: allCategoriesOk, execution_gate: executionOk, evaluation_gate: evaluationOk, metrics_gate: metricsOk, evidence_gate: evidenceOk, reporting_gate: reportingOk, replay_gate: replayOk, boundaries_gate: boundariesOk, passed: false });
  const finalGates = nested({ ...gates, passed: gates.architecture_gate && gates.registry_gate && gates.category_support_gate && gates.execution_gate && gates.evaluation_gate && gates.metrics_gate && gates.evidence_gate && gates.reporting_gate && gates.replay_gate && gates.boundaries_gate });
  const boundaries = nested({ boundary_id: "boundaries:p6.11", owns_simulation_engine: false as const, owns_replay_validation: false as const, owns_adversarial_testing: false as const, owns_resilience_validation: false as const, owns_performance_testing: false as const, owns_cross_program_integration: false as const, owns_production_operations: false as const, owns_operator_certification: false as const, owns_trust_evaluation: false as const, owns_application_governance: false as const });
  const derivedFailures = freezeArray([...new Set([...failures, ...(!architectureOk ? ["EXERCISE_ARCHITECTURE_MISSING" as const] : []), ...(!registryOk ? ["EXERCISE_REGISTRY_MISSING" as const] : []), ...(!tabletopOk ? ["TABLETOP_FRAMEWORK_MISSING" as const] : []), ...(!missionOk ? ["MISSION_REHEARSAL_FRAMEWORK_MISSING" as const] : []), ...(!operatorOk ? ["OPERATOR_DRILL_FRAMEWORK_MISSING" as const] : []), ...(!governanceExerciseOk ? ["GOVERNANCE_EXERCISE_FRAMEWORK_MISSING" as const] : []), ...(!emergencyOk ? ["EMERGENCY_SIMULATION_FRAMEWORK_MISSING" as const] : []), ...(!executionOk ? ["EXECUTION_ENGINE_MISSING" as const] : []), ...(!evaluationOk ? ["OPERATIONAL_EVALUATION_MISSING" as const] : []), ...(!metricsOk ? ["READINESS_METRICS_MISSING" as const] : []), ...(!evidenceOk ? ["EVIDENCE_COLLECTION_MISSING" as const] : []), ...(!replayOk ? ["REPLAY_VALIDATION_FAILED" as const] : []), ...(!reportingOk ? ["REPORTING_FRAMEWORK_MISSING" as const] : []), ...(!boundariesOk ? ["SIMULATION_ENGINE_OWNERSHIP_VIOLATION" as const] : [])])]);
  const finalOutcome = outcome(derivedFailures);
  const readiness = nested({ readiness_id: "P6.11-OPERATIONAL-EXERCISE-READINESS-001", outcome: finalOutcome, phase_ready: finalOutcome === "PASS", architecture_ready: architectureOk, registry_ready: registryOk, tabletop_ready: tabletopOk, mission_rehearsal_ready: missionOk, operator_drill_ready: operatorOk, governance_exercise_ready: governanceExerciseOk, emergency_simulation_ready: emergencyOk, execution_ready: executionOk, evaluation_ready: evaluationOk, metrics_ready: metricsOk, evidence_ready: evidenceOk, reporting_ready: reportingOk, gates_passed: finalGates.passed, boundaries_respected: boundariesOk, failures: derivedFailures });
  const base: Omit<OperationalExerciseResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, integration_validation_ref: "proving-cross-program-integration-validation/v6.10", architecture, registry, tabletop_report, mission_rehearsal_report, operator_drill_report, governance_exercise_report, emergency_simulation_report, execution, evaluation, readiness_metrics, evidence, reporting, gates: finalGates, boundaries, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateProvingOperationalExerciseFramework(result?: OperationalExerciseResult): OperationalExerciseValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, architecture_valid: false, registry_valid: false, tabletop_valid: false, mission_rehearsal_valid: false, operator_drill_valid: false, governance_exercise_valid: false, emergency_simulation_valid: false, execution_valid: false, evaluation_valid: false, metrics_valid: false, evidence_valid: false, reporting_valid: false, gates_valid: false, boundaries_valid: false, readiness_valid: false, failures: freezeArray(["EXERCISE_ARCHITECTURE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const architecture_valid = verifyHashed(result.architecture) && result.architecture.lifecycle.length === LIFECYCLE.length && result.architecture.deterministic;
  const registry_valid = verifyHashed(result.registry) && result.registry.categories.length === CATEGORIES.length && result.registry.approval_status === "APPROVED";
  const reportValid = (report: ExerciseFrameworkReport) => verifyHashed(report) && report.supported && report.evidence_refs.length > 0;
  const tabletop_valid = reportValid(result.tabletop_report);
  const mission_rehearsal_valid = reportValid(result.mission_rehearsal_report);
  const operator_drill_valid = reportValid(result.operator_drill_report);
  const governance_exercise_valid = reportValid(result.governance_exercise_report);
  const emergency_simulation_valid = reportValid(result.emergency_simulation_report);
  const execution_valid = verifyHashed(result.execution) && result.execution.deterministic && result.execution.finalized && result.execution.timeline_evidence.length > 0;
  const evaluation_valid = verifyHashed(result.evaluation) && result.evaluation.objective_completion && result.evaluation.governance_correctness && result.evaluation.readiness_score >= 90;
  const metrics_valid = verifyHashed(result.readiness_metrics) && result.readiness_metrics.dimensions.length === DIMENSIONS.length && result.readiness_metrics.reproducible;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.immutable && result.evidence.lineage_complete && result.evidence.replayable;
  const reporting_valid = verifyHashed(result.reporting) && result.reporting.generated && result.reporting.improvement_recommendations.length > 0;
  const gates_valid = verifyHashed(result.gates) && result.gates.passed;
  const boundaries_valid = verifyHashed(result.boundaries) && !result.boundaries.owns_simulation_engine && !result.boundaries.owns_replay_validation && !result.boundaries.owns_adversarial_testing && !result.boundaries.owns_resilience_validation && !result.boundaries.owns_performance_testing && !result.boundaries.owns_cross_program_integration && !result.boundaries.owns_production_operations && !result.boundaries.owns_operator_certification && !result.boundaries.owns_trust_evaluation && !result.boundaries.owns_application_governance;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && architecture_valid && registry_valid && tabletop_valid && mission_rehearsal_valid && operator_drill_valid && governance_exercise_valid && emergency_simulation_valid && execution_valid && evaluation_valid && metrics_valid && evidence_valid && reporting_valid && gates_valid && boundaries_valid && readiness_valid;
  return nested({ valid, outcome: result.readiness.outcome, replay_hash_valid, integrity_hash_valid, architecture_valid, registry_valid, tabletop_valid, mission_rehearsal_valid, operator_drill_valid, governance_exercise_valid, emergency_simulation_valid, execution_valid, evaluation_valid, metrics_valid, evidence_valid, reporting_valid, gates_valid, boundaries_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayProvingOperationalExerciseFramework(result = runProvingOperationalExerciseFramework()): boolean { const replayed = runProvingOperationalExerciseFramework(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateProvingOperationalExerciseFramework(result).valid; }
export function getProvingOperationalExerciseFrameworkBundle(): OperationalExerciseBundle { const result = runProvingOperationalExerciseFramework(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_tabletop_exercises: true, owns_mission_rehearsals: true, owns_operator_drills: true, owns_governance_exercises: true, owns_emergency_simulations: true, owns_simulation_engine: false, owns_replay_validation: false, owns_adversarial_testing: false, owns_resilience_validation: false, owns_performance_testing: false, owns_cross_program_integration: false, owns_production_operations: false, owns_operator_certification: false, owns_trust_evaluation: false, owns_application_governance: false }), result, validation: validateProvingOperationalExerciseFramework(result) }); }
export const ProvingOperationalExerciseFrameworkService = Object.freeze({ run: runProvingOperationalExerciseFramework, validate: validateProvingOperationalExerciseFramework, replay: replayProvingOperationalExerciseFramework });
