import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runProvingProgramQualification, validateProvingProgramQualification } from "@/services/proving-program-qualification";
import { runWaveFiveApex, validateWaveFiveApex } from "@/services/wave-five-apex";
import type { WaveFiveProvingGroundBundle, WaveFiveProvingGroundDecision, WaveFiveProvingGroundFailure, WaveFiveProvingGroundInput, WaveFiveProvingGroundResult, WaveFiveProvingGroundScenario, WaveFiveProvingGroundValidation } from "@/types/wave-five-proprium-proving-ground";

const VERSION = "wave-five-proprium-proving-ground/w5.14" as const;
const IDENTIFIER = "WaveFivePropriumProvingGround" as const;
const UPSTREAM_REFS = Object.freeze(["proving-program-qualification/v6.18", "wave-five-apex/w5.13", "wave-five-aurora/w5.12", "wave-five-learning-stevn/w5.11", "wave-five-writing-publisher-os/w5.10", "wave-five-research/w5.9", "wave-five-health/w5.8", "wave-five-finance/w5.7", "wave-five-tasks-commitments/w5.5", "wave-five-calendar-time/w5.4", "wave-five-personal-knowledge/w5.3", "wave-five-unified-personal-context/w5.2", "wave-five-application-platform/w5.1"]);
const PROVIDES = Object.freeze(["sandboxed-runtime", "synthetic-data-engine", "simulation-engine", "failure-injection-framework", "replay-validation-service", "promotion-evidence-service", "scenario-registry", "validation-dashboard"]);
let proving = runProvingProgramQualification();
let apex = runWaveFiveApex();

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly WaveFiveProvingGroundFailure[], failure: WaveFiveProvingGroundFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: WaveFiveProvingGroundScenario): WaveFiveProvingGroundFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly WaveFiveProvingGroundFailure[], scenario?: WaveFiveProvingGroundScenario): WaveFiveProvingGroundDecision {
  const notQualified = new Set<WaveFiveProvingGroundFailure>(["P6_PROVING_PROGRAM_INVALID", "W5_APEX_INVALID", "SANDBOX_ISOLATION_INVALID", "SANDBOX_EXECUTION_NONDETERMINISTIC", "SYNTHETIC_DATA_NONREPRODUCIBLE", "SYNTHETIC_DATA_PRIVACY_BREACH", "SIMULATION_NONREPEATABLE", "FAILURE_INJECTION_UNCONTROLLED", "REPLAY_ENGINE_DUPLICATED", "REPLAY_DIVERGENCE_UNEXPLAINED", "PROMOTION_EVIDENCE_MUTABLE", "PROMOTION_RECOMMENDATION_NOT_ADVISORY", "DEPLOYMENT_ORCHESTRATION_ASSUMED", "RELEASE_ROUTING_ASSUMED", "PRODUCTION_ROUTING_ASSUMED", "PBG_RESPONSIBILITY_ASSUMED", "TEST_LINEAGE_INCOMPLETE", "IMMUTABLE_VALIDATION_EVIDENCE_MISSING", "TESTING_OWNERSHIP_NOT_AUTHORITATIVE", "TENANT_ISOLATION_BREACH"]);
  if (failures.some((failure) => notQualified.has(failure))) return "NOT_QUALIFIED";
  if (has(failures, "PROVING_GROUND_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_QUALIFIED";
  return "QUALIFIED";
}
function resultReplayHash(result: Omit<WaveFiveProvingGroundResult, "replay_hash" | "integrity_hash">): string { return hash({ sandbox: result.sandbox.integrity_hash, synthetic: result.synthetic_simulation.integrity_hash, failure: result.failure_replay.integrity_hash, promotion: result.promotion_evidence.integrity_hash, registry: result.registry_dashboard.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<WaveFiveProvingGroundResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runWaveFiveProvingGround(input: WaveFiveProvingGroundInput = {}): WaveFiveProvingGroundResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  proving = runProvingProgramQualification();
  apex = runWaveFiveApex();
  const failures = freezeArray([...new Set([...(direct ? [direct] : []), ...(!validateProvingProgramQualification(proving).valid ? ["P6_PROVING_PROGRAM_INVALID" as const] : []), ...(!validateWaveFiveApex(apex).valid ? ["W5_APEX_INVALID" as const] : [])])]);
  const sandboxOk = !has(failures, "SANDBOX_RUNTIME_MISSING") && !has(failures, "SANDBOX_ISOLATION_INVALID") && !has(failures, "SANDBOX_EXECUTION_NONDETERMINISTIC") && !has(failures, "RUNTIME_LIFECYCLE_INVALID") && !has(failures, "DISPOSABLE_RUNTIME_MISSING") && !has(failures, "TENANT_ISOLATION_BREACH");
  const syntheticSimulationOk = !has(failures, "SYNTHETIC_DATA_ENGINE_MISSING") && !has(failures, "SYNTHETIC_DATA_NONREPRODUCIBLE") && !has(failures, "SYNTHETIC_DATA_PRIVACY_BREACH") && !has(failures, "SEEDED_RANDOMNESS_MISSING") && !has(failures, "SCALE_CONFIGURATION_MISSING") && !has(failures, "SIMULATION_ENGINE_MISSING") && !has(failures, "SIMULATION_NONREPEATABLE") && !has(failures, "ACCELERATED_TIME_INVALID") && !has(failures, "BRANCHING_SCENARIOS_MISSING") && !has(failures, "SCENARIO_COMPARISON_MISSING");
  const failureReplayOk = !has(failures, "FAILURE_INJECTION_MISSING") && !has(failures, "FAILURE_INJECTION_UNCONTROLLED") && !has(failures, "RESILIENCE_EVIDENCE_MISSING") && !has(failures, "RECOVERY_EVIDENCE_MISSING") && !has(failures, "FAILURE_LINEAGE_MISSING") && !has(failures, "REPLAY_VALIDATION_MISSING") && !has(failures, "REPLAY_ENGINE_DUPLICATED") && !has(failures, "REPLAY_DIVERGENCE_UNEXPLAINED") && !has(failures, "BEHAVIORAL_VALIDATION_MISSING") && !has(failures, "EVIDENCE_VERIFICATION_MISSING");
  const promotionOk = !has(failures, "PROMOTION_EVIDENCE_MISSING") && !has(failures, "PROMOTION_EVIDENCE_MUTABLE") && !has(failures, "PROMOTION_RECOMMENDATION_NOT_ADVISORY") && !has(failures, "DEPLOYMENT_ORCHESTRATION_ASSUMED") && !has(failures, "RELEASE_ROUTING_ASSUMED") && !has(failures, "PRODUCTION_ROUTING_ASSUMED") && !has(failures, "PBG_RESPONSIBILITY_ASSUMED");
  const registryOk = !has(failures, "SCENARIO_REGISTRY_MISSING") && !has(failures, "VALIDATION_DASHBOARD_MISSING") && !has(failures, "TEST_LINEAGE_INCOMPLETE") && !has(failures, "IMMUTABLE_VALIDATION_EVIDENCE_MISSING") && !has(failures, "TESTING_OWNERSHIP_NOT_AUTHORITATIVE");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "QUALIFIED";
  const sandbox = nested({ sandbox_id: sandboxOk ? "W5.14-SANDBOX-RUNTIME-001" : "", application_validation: sandboxOk, capability_testing: sandboxOk, integration_testing: sandboxOk, workflow_execution: sandboxOk, runtime_verification: sandboxOk, policy_validation: sandboxOk, tenant_isolation: sandboxOk, deterministic_execution: sandboxOk, repeatable_environments: sandboxOk, disposable_runtimes: sandboxOk, environment_provisioning: sandboxOk, runtime_lifecycle: sandboxOk, cleanup: sandboxOk, execution_metadata: sandboxOk });
  const synthetic_simulation = nested({ synthetic_simulation_id: syntheticSimulationOk ? "W5.14-SYNTHETIC-SIMULATION-001" : "", synthetic_users: syntheticSimulationOk, synthetic_organizations: syntheticSimulationOk, synthetic_missions: syntheticSimulationOk, synthetic_projects: syntheticSimulationOk, synthetic_calendars: syntheticSimulationOk, synthetic_financial_data: syntheticSimulationOk, synthetic_health_data: syntheticSimulationOk, synthetic_knowledge: syntheticSimulationOk, synthetic_communication: syntheticSimulationOk, synthetic_activity_streams: syntheticSimulationOk, privacy_preserving_generation: syntheticSimulationOk, deterministic_datasets: syntheticSimulationOk, configurable_scale: syntheticSimulationOk, repeatable_generation: syntheticSimulationOk, seeded_randomness: syntheticSimulationOk, user_behavior: syntheticSimulationOk, workflow_execution: syntheticSimulationOk, mission_progression: syntheticSimulationOk, scheduling: syntheticSimulationOk, planning: syntheticSimulationOk, collaboration: syntheticSimulationOk, approvals: syntheticSimulationOk, governance_events: syntheticSimulationOk, trust_decisions: syntheticSimulationOk, application_interactions: syntheticSimulationOk, deterministic_simulation: syntheticSimulationOk, accelerated_time: syntheticSimulationOk, branching_scenarios: syntheticSimulationOk, scenario_comparison: syntheticSimulationOk });
  const failure_replay = nested({ failure_replay_id: failureReplayOk ? "W5.14-FAILURE-REPLAY-001" : "", service_failures: failureReplayOk, timeout_conditions: failureReplayOk, degraded_dependencies: failureReplayOk, messaging_failures: failureReplayOk, storage_failures: failureReplayOk, authentication_failures: failureReplayOk, authorization_failures: failureReplayOk, network_interruption: failureReplayOk, policy_violations: failureReplayOk, invalid_inputs: failureReplayOk, resource_exhaustion: failureReplayOk, controlled_injection: failureReplayOk, resilience_evidence: failureReplayOk, recovery_evidence: failureReplayOk, failure_lineage: failureReplayOk, replay_verification: failureReplayOk, replay_comparison: failureReplayOk, divergence_detection: failureReplayOk, behavioral_validation: failureReplayOk, workflow_validation: failureReplayOk, mission_validation: failureReplayOk, evidence_verification: failureReplayOk, consumes_existing_replay: failureReplayOk, no_new_replay_engine: failureReplayOk });
  const promotion_evidence = nested({ promotion_id: promotionOk ? "W5.14-PROMOTION-EVIDENCE-001" : "", functional_validation: promotionOk, regression_validation: promotionOk, governance_validation: promotionOk, constitutional_validation: promotionOk, replay_validation: promotionOk, performance_validation: promotionOk, resilience_validation: promotionOk, security_validation: promotionOk, dependency_validation: promotionOk, evidence_aggregation: promotionOk, readiness_scoring: promotionOk, validation_summaries: promotionOk, promotion_packages: promotionOk, immutable_evidence: promotionOk, traceable: promotionOk, advisory_only: promotionOk, no_deployment_orchestration: promotionOk, no_release_routing: promotionOk, no_production_routing: promotionOk, no_pbg_ownership: promotionOk });
  const registry_dashboard = nested({ registry_dashboard_id: registryOk ? "W5.14-REGISTRY-DASHBOARD-001" : "", sandbox_environment_model: registryOk, simulation_scenario_model: registryOk, failure_injection_event_model: registryOk, promotion_evidence_package_model: registryOk, scenario_registry: registryOk, validation_dashboard: registryOk, promotion_readiness_reports: registryOk, validation_reports: registryOk, replay_validation_reports: registryOk, simulation_reports: registryOk, failure_reports: registryOk, complete_testing_lineage: registryOk, immutable_validation_evidence: registryOk, testing_authority_owned: registryOk });
  const readiness = nested({ readiness_id: "W5.14-PROVING-GROUND-READINESS-001", decision, phase_ready: qualified, p6_proving_ready: !has(failures, "P6_PROVING_PROGRAM_INVALID"), apex_ready: !has(failures, "W5_APEX_INVALID"), sandboxed_runtimes_deterministic: sandboxOk, synthetic_datasets_reproducible_private: syntheticSimulationOk, simulations_repeatable: syntheticSimulationOk, failure_injection_validates_resilience: failureReplayOk, replay_validation_confirms_determinism: failureReplayOk, promotion_evidence_complete_immutable_traceable: promotionOk, every_test_linked_to_lineage: registryOk, testing_ownership_authoritative: registryOk, no_pbg_responsibility_assumed: promotionOk, promotion_recommendations_advisory: promotionOk, failures });
  const base: Omit<WaveFiveProvingGroundResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, proving_program_ref: "proving-program-qualification/v6.18", upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id: input.tenant_id ?? apex.tenant_id, principal_id: input.principal_id ?? "principal:w5.14:proving-operator", sandbox, synthetic_simulation, failure_replay, promotion_evidence, registry_dashboard, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateWaveFiveProvingGround(result?: WaveFiveProvingGroundResult): WaveFiveProvingGroundValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, sandbox_valid: false, synthetic_simulation_valid: false, failure_replay_valid: false, promotion_evidence_valid: false, registry_dashboard_valid: false, readiness_valid: false, failures: freezeArray(["SANDBOX_RUNTIME_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const sandbox_valid = verifyHashed(result.sandbox) && result.sandbox.tenant_isolation && result.sandbox.deterministic_execution && result.sandbox.disposable_runtimes;
  const synthetic_simulation_valid = verifyHashed(result.synthetic_simulation) && result.synthetic_simulation.privacy_preserving_generation && result.synthetic_simulation.deterministic_datasets && result.synthetic_simulation.seeded_randomness && result.synthetic_simulation.deterministic_simulation && result.synthetic_simulation.scenario_comparison;
  const failure_replay_valid = verifyHashed(result.failure_replay) && result.failure_replay.controlled_injection && result.failure_replay.resilience_evidence && result.failure_replay.recovery_evidence && result.failure_replay.consumes_existing_replay && result.failure_replay.no_new_replay_engine;
  const promotion_evidence_valid = verifyHashed(result.promotion_evidence) && result.promotion_evidence.immutable_evidence && result.promotion_evidence.traceable && result.promotion_evidence.advisory_only && result.promotion_evidence.no_pbg_ownership && result.promotion_evidence.no_deployment_orchestration;
  const registry_dashboard_valid = verifyHashed(result.registry_dashboard) && result.registry_dashboard.scenario_registry && result.registry_dashboard.validation_dashboard && result.registry_dashboard.complete_testing_lineage && result.registry_dashboard.immutable_validation_evidence && result.registry_dashboard.testing_authority_owned;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.p6_proving_ready && result.readiness.apex_ready && result.readiness.no_pbg_responsibility_assumed && result.readiness.promotion_recommendations_advisory && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && sandbox_valid && synthetic_simulation_valid && failure_replay_valid && promotion_evidence_valid && registry_dashboard_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, sandbox_valid, synthetic_simulation_valid, failure_replay_valid, promotion_evidence_valid, registry_dashboard_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayWaveFiveProvingGround(result = runWaveFiveProvingGround()): boolean { const replayed = runWaveFiveProvingGround(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateWaveFiveProvingGround(result).valid; }
export function getWaveFiveProvingGroundBundle(): WaveFiveProvingGroundBundle { const result = runWaveFiveProvingGround(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_proprium_testing: true, deterministic_validation_required: true, synthetic_data_privacy_required: true, replay_validation_consumes_existing_platform: true, promotion_evidence_advisory_only: true, pbg_ownership_prohibited: true, deployment_orchestration_prohibited: true, immutable_validation_evidence_required: true, qualification_gate: "W5.14 Proprium Proving Ground Qualification Gate" }), result, validation: validateWaveFiveProvingGround(result) }); }
export const WaveFiveProvingGroundService = Object.freeze({ run: runWaveFiveProvingGround, validate: validateWaveFiveProvingGround, replay: replayWaveFiveProvingGround });
