export type ProposalLifecycleErrorCode =
  | "PROPOSAL_SCHEMA_INVALID"
  | "PROPOSAL_STATE_TRANSITION_INVALID"
  | "PROPOSAL_LINEAGE_MISSING"
  | "PROPOSAL_GOVERNANCE_BINDING_MISSING"
  | "PROPOSAL_SAFE_ACTION_MISSING"
  | "PROPOSAL_SAFE_ACTION_FORBIDDEN"
  | "PROPOSAL_APPROVAL_REQUIRED"
  | "PROPOSAL_APPROVAL_EXPIRED"
  | "PROPOSAL_REVOKED"
  | "PROPOSAL_ARCHIVED_IMMUTABLE"
  | "PROPOSAL_REPLAY_MISMATCH"
  | "PROPOSAL_FUTURE_BOUND_ESCALATION"
  | "PROPOSAL_EXECUTION_FORBIDDEN"
  | "PROPOSAL_RUNTIME_BRIDGE_FORBIDDEN"
  | "PROPOSAL_AUTHORITY_INFLATION"
  | "PROPOSAL_EXECUTION_METADATA_FORBIDDEN";

export type ProposalLifecycleError = Readonly<{
  code: ProposalLifecycleErrorCode;
  message: string;
  path?: string;
}>;
