export const PROPOSAL_INTEGRITY_ERROR_CODES = [
  "PROPOSAL_SCHEMA_INVALID",
  "PROPOSAL_EXECUTION_SEMANTICS_DETECTED",
  "PROPOSAL_AUTHORITY_EXPANSION_DETECTED",
  "PROPOSAL_GOVERNANCE_SNAPSHOT_MISSING",
  "PROPOSAL_REPLAY_SNAPSHOT_MISSING",
  "PROPOSAL_APPROVAL_DEPENDENCY_INVALID",
  "PROPOSAL_LINEAGE_HASH_MISMATCH",
  "PROPOSAL_REPLAY_HASH_MISMATCH",
  "PROPOSAL_AUDIT_HASH_MISMATCH",
  "PROPOSAL_EXECUTION_AUTHORIZATION_NOT_FALSE",
  "PROPOSAL_MUTATION_AFTER_SEAL_BLOCKED",
  "PROPOSAL_REPLAY_DRIFT_DETECTED",
  "PROPOSAL_GOVERNANCE_DRIFT_DETECTED",
  "PROPOSAL_SYNTHETIC_ANCESTRY_DETECTED",
  "PROPOSAL_RUNTIME_LINKAGE_DETECTED",
  "PROPOSAL_ORCHESTRATION_LINKAGE_DETECTED",
  "PROPOSAL_SCHEDULER_LINKAGE_DETECTED",
] as const;

export type ProposalIntegrityErrorCode = (typeof PROPOSAL_INTEGRITY_ERROR_CODES)[number];
