import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import type { BootstrapBundle, BootstrapDecision, BootstrapFailure, BootstrapInput, BootstrapPermission, BootstrapResult, BootstrapRole, BootstrapScenario, BootstrapValidation } from "@/types/platform-bootstrap-authority";

const VERSION = "platform-bootstrap-authority/w1.0" as const;
const IDENTIFIER = "PlatformBootstrapAuthority" as const;
const ROLES = Object.freeze<BootstrapRole[]>(["BOOTSTRAP_ADMINISTRATOR", "BOOTSTRAP_OPERATOR", "CRYPTOGRAPHIC_CUSTODIAN"]);
const PERMISSIONS = Object.freeze<BootstrapPermission[]>(["INITIALIZE_PLATFORM", "MANAGE_BOOTSTRAP_IDENTITY", "ISSUE_BOOTSTRAP_CERTIFICATES", "GRANT_BOOTSTRAP_PERMISSIONS", "CREATE_BOOTSTRAP_TENANT", "MANAGE_BOOTSTRAP_NAMESPACE", "WRITE_BOOTSTRAP_AUDIT", "PROTECT_ROOT_KEYS", "APPROVE_BOOTSTRAP_RECOVERY"]);

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly BootstrapFailure[], failure: BootstrapFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: BootstrapScenario): BootstrapFailure | undefined { return scenario === "BASELINE" || scenario === "READY_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly BootstrapFailure[], scenario: BootstrapScenario): BootstrapDecision {
  if (has(failures, "OFFLINE_ROOT_OF_TRUST_MISSING") || has(failures, "ROOT_KEYS_NOT_GENERATED") || has(failures, "ROOT_KEYS_NOT_IMMUTABLE") || has(failures, "BOOTSTRAP_AUTHORIZATION_MISSING") || has(failures, "AUTHORIZATION_DECISION_NON_DETERMINISTIC") || has(failures, "AUDIT_LEDGER_NOT_IMMUTABLE") || has(failures, "BOOTSTRAP_CREDENTIALS_UNSECURED") || has(failures, "PRIVATE_KEYS_UNPROTECTED") || has(failures, "BOOTSTRAP_EVIDENCE_NOT_IMMUTABLE")) return "FAIL_CLOSED";
  if (has(failures, "LAYER_0_CONSTITUTIONAL_FRAMEWORK_MISSING") || has(failures, "CAPABILITY_ATLAS_MISSING") || has(failures, "PLATFORM_GOVERNANCE_STANDARDS_MISSING") || has(failures, "BOOTSTRAP_QUALIFICATION_GATE_FAILED")) return "NOT_READY";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_READY";
  if (scenario === "READY_WITH_OBSERVATIONS") return "READY_WITH_OBSERVATIONS";
  return "BOOTSTRAP_READY";
}
function resultReplayHash(result: Omit<BootstrapResult, "replay_hash" | "integrity_hash">): string { return hash({ architecture: result.architecture.integrity_hash, root: result.root_of_trust.integrity_hash, ca: result.certificate_authority.integrity_hash, identity: result.identity_registry.integrity_hash, authorization: result.authorization.integrity_hash, roles: result.role_permission_matrix.integrity_hash, namespace: result.namespace_registry.integrity_hash, tenant: result.tenant.integrity_hash, audit: result.audit_ledger.integrity_hash, security: result.security_report.integrity_hash, validation: result.validation_report.integrity_hash, qualification: result.qualification_report.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<BootstrapResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runPlatformBootstrapAuthority(input: BootstrapInput = {}): BootstrapResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const failures = freezeArray<BootstrapFailure>(direct ? [direct] : []);
  const architectureOk = !has(failures, "BOOTSTRAP_ARCHITECTURE_MISSING") && !has(failures, "BOOTSTRAP_LIFECYCLE_INCOMPLETE") && !has(failures, "BOOTSTRAP_AUTHORITY_MODEL_INVALID");
  const rootOk = !has(failures, "OFFLINE_ROOT_OF_TRUST_MISSING") && !has(failures, "ROOT_KEYS_NOT_GENERATED") && !has(failures, "ROOT_KEYS_NOT_IMMUTABLE") && !has(failures, "KEY_CEREMONY_RECORDS_MISSING") && !has(failures, "RECOVERY_PROCEDURES_MISSING");
  const caOk = !has(failures, "BOOTSTRAP_CA_MISSING") && !has(failures, "BOOTSTRAP_CERTIFICATE_POLICY_MISSING") && !has(failures, "CERTIFICATE_LIFECYCLE_INVALID");
  const identityOk = !has(failures, "BOOTSTRAP_IDENTITY_MISSING") && !has(failures, "BOOTSTRAP_PRINCIPAL_RECORDS_MISSING") && !has(failures, "IDENTITY_VALIDATION_FAILED");
  const authorizationOk = !has(failures, "BOOTSTRAP_AUTHORIZATION_MISSING") && !has(failures, "AUTHORIZATION_POLICY_MISSING") && !has(failures, "AUTHORIZATION_DECISION_NON_DETERMINISTIC");
  const rolesOk = !has(failures, "ROLE_PERMISSION_MATRIX_INCOMPLETE") && !has(failures, "PERMISSION_GRANTS_INVALID");
  const namespaceOk = !has(failures, "BOOTSTRAP_NAMESPACE_MISSING") && !has(failures, "NAMESPACE_OWNERSHIP_INVALID");
  const tenantOk = !has(failures, "BOOTSTRAP_TENANT_MISSING") && !has(failures, "TENANT_BOUNDARY_INVALID");
  const auditOk = !has(failures, "AUDIT_LEDGER_MISSING") && !has(failures, "AUDIT_RECORDS_INCOMPLETE") && !has(failures, "AUDIT_LEDGER_NOT_IMMUTABLE");
  const securityOk = !has(failures, "BOOTSTRAP_CREDENTIALS_UNSECURED") && !has(failures, "PRIVATE_KEYS_UNPROTECTED") && !has(failures, "MULTI_PARTY_AUTHORIZATION_MISSING") && !has(failures, "BACKUP_MATERIAL_UNSECURED");
  const validationOk = !has(failures, "BOOTSTRAP_VALIDATION_FAILED") && !has(failures, "BOOTSTRAP_EVIDENCE_NOT_IMMUTABLE");
  const dependenciesOk = !has(failures, "LAYER_0_CONSTITUTIONAL_FRAMEWORK_MISSING") && !has(failures, "CAPABILITY_ATLAS_MISSING") && !has(failures, "PLATFORM_GOVERNANCE_STANDARDS_MISSING");
  const decision = decisionFor(failures, scenario);
  const architecture = nested({ architecture_id: architectureOk ? `architecture:w1.0:bootstrap:${input.seed ?? "canonical"}` : "", lifecycle_defined: architectureOk, boundaries_defined: architectureOk, authority_model_defined: architectureOk, trust_initialization_flow_defined: architectureOk, operating_procedures_defined: architectureOk });
  const root_of_trust = nested({ root_id: rootOk ? "root:w1.0:offline-trust" : "", offline_root_keys: rootOk ? freezeArray(["root-key:w1.0:primary", "root-key:w1.0:recovery"]) : freezeArray<string>([]), hardware_storage_secured: rootOk, key_ceremony_recorded: rootOk, root_certificate_established: rootOk, recovery_procedures_validated: rootOk, immutable: rootOk });
  const certificate_authority = nested({ ca_id: caOk ? "ca:w1.0:bootstrap" : "", authority_operational: caOk, bootstrap_certificates: caOk ? freezeArray(["cert:w1.0:authority", "cert:w1.0:administrator", "cert:w1.0:service"]) : freezeArray<string>([]), certificate_policy_defined: caOk, revocation_process_defined: caOk, certificate_lifecycle_defined: caOk });
  const identity_registry = nested({ registry_id: identityOk ? "registry:w1.0:identity" : "", authority_identity: identityOk ? "identity:w1.0:authority" : "", administrator_identity: identityOk ? "identity:w1.0:administrator" : "", service_identities: identityOk ? freezeArray(["identity:w1.0:authorization-service", "identity:w1.0:audit-service", "identity:w1.0:certificate-service"]) : freezeArray<string>([]), principals_registered: identityOk, identities_validated: identityOk });
  const authorization = nested({ policy_id: authorizationOk ? "policy:w1.0:authorization" : "", authorization_model_defined: authorizationOk, permission_hierarchy_defined: authorizationOk, evaluator_operational: authorizationOk, deterministic_decisions: authorizationOk, decisions: authorizationOk ? freezeArray(["decision:w1.0:initialize-platform", "decision:w1.0:issue-bootstrap-certificate", "decision:w1.0:create-bootstrap-tenant"]) : freezeArray<string>([]) });
  const role_permission_matrix = nested({ matrix_id: rolesOk ? "matrix:w1.0:roles-permissions" : "", roles: rolesOk ? ROLES : freezeArray<BootstrapRole>([]), permissions: rolesOk ? PERMISSIONS : freezeArray<BootstrapPermission>([]), permission_grants: rolesOk ? freezeArray(ROLES.flatMap((role) => PERMISSIONS.map((permission) => `${role}:${permission}`))) : freezeArray<string>([]), grants_validated: rolesOk, matrix_complete: rolesOk });
  const namespace_registry = nested({ registry_id: namespaceOk ? "registry:w1.0:namespace" : "", bootstrap_namespace: namespaceOk ? "civitas.bootstrap" : "", reserved_namespaces: namespaceOk ? freezeArray(["civitas.platform", "civitas.governance", "civitas.identity", "civitas.audit"]) : freezeArray<string>([]), ownership_established: namespaceOk, namespace_authority_registered: namespaceOk });
  const tenant = nested({ tenant_id: tenantOk ? "tenant:w1.0:bootstrap" : "", authority_assigned: tenantOk, ownership_configured: tenantOk, tenant_isolation_established: tenantOk, tenant_boundaries_validated: tenantOk });
  const audit_ledger = nested({ ledger_id: auditOk ? "ledger:w1.0:bootstrap-audit" : "", records: auditOk ? freezeArray(["audit:w1.0:root-key-ceremony", "audit:w1.0:certificate-issued", "audit:w1.0:identity-created", "audit:w1.0:authorization-decision", "audit:w1.0:tenant-created", "audit:w1.0:namespace-created"]) : freezeArray<string>([]), cryptographic_operations_recorded: auditOk, authorization_decisions_recorded: auditOk, identities_recorded: auditOk, certificates_recorded: auditOk, immutable: auditOk });
  const security_report = nested({ report_id: securityOk ? "report:w1.0:bootstrap-security" : "", private_keys_secured: securityOk, credentials_protected: securityOk, multi_party_authorization_enabled: securityOk, backup_material_secured: securityOk, credential_storage_validated: securityOk });
  const validation_report = nested({ report_id: validationOk ? "report:w1.0:bootstrap-validation" : "", authority_verified: validationOk && architectureOk, certificates_verified: validationOk && caOk, permissions_verified: validationOk && authorizationOk && rolesOk, identities_verified: validationOk && identityOk, audit_complete: validationOk && auditOk, evidence_immutable: validationOk && auditOk && rootOk });
  const qualificationOk = dependenciesOk && architectureOk && rootOk && caOk && identityOk && authorizationOk && rolesOk && namespaceOk && tenantOk && auditOk && securityOk && validationOk && !has(failures, "BOOTSTRAP_QUALIFICATION_GATE_FAILED");
  const qualification_report = nested({ report_id: qualificationOk ? "report:w1.0:bootstrap-qualification" : "", root_trust_ready: rootOk, authority_operational: architectureOk, identity_ready: identityOk, authorization_ready: authorizationOk, namespace_ready: namespaceOk, tenant_ready: tenantOk, ca_ready: caOk, audit_ready: auditOk, security_ready: securityOk, qualification_gate_passed: qualificationOk });
  const readiness = nested({ readiness_id: "W1.0-BOOTSTRAP-AUTHORITY-READINESS-001", decision, phase_ready: decision === "BOOTSTRAP_READY" || decision === "READY_WITH_OBSERVATIONS", architecture_ready: architectureOk, root_trust_ready: rootOk, ca_ready: caOk, identity_ready: identityOk, authorization_ready: authorizationOk, roles_ready: rolesOk, namespace_ready: namespaceOk, tenant_ready: tenantOk, audit_ready: auditOk, security_ready: securityOk, validation_ready: validationOk, qualification_ready: qualificationOk, failures });
  const base: Omit<BootstrapResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, architecture, root_of_trust, certificate_authority, identity_registry, authorization, role_permission_matrix, namespace_registry, tenant, audit_ledger, security_report, validation_report, qualification_report, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validatePlatformBootstrapAuthority(result?: BootstrapResult): BootstrapValidation {
  if (!result) return nested({ valid: false, decision: "NOT_READY" as const, replay_hash_valid: false, integrity_hash_valid: false, architecture_valid: false, root_trust_valid: false, ca_valid: false, identity_valid: false, authorization_valid: false, roles_valid: false, namespace_valid: false, tenant_valid: false, audit_valid: false, security_valid: false, validation_report_valid: false, qualification_valid: false, readiness_valid: false, failures: freezeArray(["BOOTSTRAP_ARCHITECTURE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const architecture_valid = verifyHashed(result.architecture) && result.architecture.lifecycle_defined && result.architecture.authority_model_defined;
  const root_trust_valid = verifyHashed(result.root_of_trust) && result.root_of_trust.offline_root_keys.length >= 2 && result.root_of_trust.root_certificate_established && result.root_of_trust.immutable;
  const ca_valid = verifyHashed(result.certificate_authority) && result.certificate_authority.authority_operational && result.certificate_authority.certificate_policy_defined && result.certificate_authority.bootstrap_certificates.length >= 3;
  const identity_valid = verifyHashed(result.identity_registry) && result.identity_registry.authority_identity.length > 0 && result.identity_registry.service_identities.length >= 3 && result.identity_registry.identities_validated;
  const authorization_valid = verifyHashed(result.authorization) && result.authorization.evaluator_operational && result.authorization.deterministic_decisions && result.authorization.decisions.length >= 3;
  const roles_valid = verifyHashed(result.role_permission_matrix) && result.role_permission_matrix.roles.length === ROLES.length && result.role_permission_matrix.permissions.length === PERMISSIONS.length && result.role_permission_matrix.grants_validated;
  const namespace_valid = verifyHashed(result.namespace_registry) && result.namespace_registry.bootstrap_namespace === "civitas.bootstrap" && result.namespace_registry.ownership_established;
  const tenant_valid = verifyHashed(result.tenant) && result.tenant.authority_assigned && result.tenant.tenant_isolation_established && result.tenant.tenant_boundaries_validated;
  const audit_valid = verifyHashed(result.audit_ledger) && result.audit_ledger.records.length >= 6 && result.audit_ledger.cryptographic_operations_recorded && result.audit_ledger.authorization_decisions_recorded && result.audit_ledger.immutable;
  const security_valid = verifyHashed(result.security_report) && result.security_report.private_keys_secured && result.security_report.credentials_protected && result.security_report.multi_party_authorization_enabled;
  const validation_report_valid = verifyHashed(result.validation_report) && result.validation_report.authority_verified && result.validation_report.certificates_verified && result.validation_report.permissions_verified && result.validation_report.evidence_immutable;
  const qualification_valid = verifyHashed(result.qualification_report) && result.qualification_report.qualification_gate_passed;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && architecture_valid && root_trust_valid && ca_valid && identity_valid && authorization_valid && roles_valid && namespace_valid && tenant_valid && audit_valid && security_valid && validation_report_valid && qualification_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, architecture_valid, root_trust_valid, ca_valid, identity_valid, authorization_valid, roles_valid, namespace_valid, tenant_valid, audit_valid, security_valid, validation_report_valid, qualification_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayPlatformBootstrapAuthority(result = runPlatformBootstrapAuthority()): boolean { const scenario = result.readiness.decision === "READY_WITH_OBSERVATIONS" ? { scenario: "READY_WITH_OBSERVATIONS" as const } : {}; const replayed = runPlatformBootstrapAuthority(scenario); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validatePlatformBootstrapAuthority(result).valid; }
export function getPlatformBootstrapAuthorityBundle(): BootstrapBundle { const result = runPlatformBootstrapAuthority(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_offline_root_of_trust: true, owns_bootstrap_authority: true, owns_bootstrap_identity: true, owns_bootstrap_authorization: true, owns_bootstrap_tenant: true, owns_bootstrap_namespace: true, owns_bootstrap_audit_ledger: true }), result, validation: validatePlatformBootstrapAuthority(result) }); }
export const PlatformBootstrapAuthorityService = Object.freeze({ run: runPlatformBootstrapAuthority, validate: validatePlatformBootstrapAuthority, replay: replayPlatformBootstrapAuthority });
