export type HumanCoordinationOverrideErrorCode =
  | "HUMAN_COORDINATION_OVERRIDE_UNAUTHORIZED"
  | "HUMAN_COORDINATION_OVERRIDE_GOVERNANCE_MISMATCH"
  | "HUMAN_COORDINATION_OVERRIDE_REPLAY_AMBIGUITY"
  | "HUMAN_COORDINATION_OVERRIDE_REPLAY_INCONSISTENCY"
  | "HUMAN_COORDINATION_OVERRIDE_LINEAGE_CORRUPTION"
  | "HUMAN_COORDINATION_OVERRIDE_HIDDEN_CONTINUATION"
  | "HUMAN_COORDINATION_OVERRIDE_ROUTING_RESTORATION"
  | "HUMAN_COORDINATION_OVERRIDE_CONTAINMENT_BYPASS"
  | "HUMAN_COORDINATION_OVERRIDE_RECURSIVE_MARKER"
  | "HUMAN_COORDINATION_OVERRIDE_EXECUTION_FORBIDDEN"
  | "HUMAN_COORDINATION_OVERRIDE_ORCHESTRATION_FORBIDDEN"
  | "HUMAN_COORDINATION_OVERRIDE_RUNTIME_MUTATION"
  | "HUMAN_COORDINATION_OVERRIDE_GOVERNANCE_MUTATION"
  | "HUMAN_COORDINATION_OVERRIDE_AUTHORITY_INHERITANCE"
  | "HUMAN_COORDINATION_OVERRIDE_TOPOLOGY_SYNTHESIS"
  | "HUMAN_COORDINATION_OVERRIDE_REPLAY_REPAIR"
  | "HUMAN_COORDINATION_OVERRIDE_ESCALATION_SUPPRESSION"
  | "HUMAN_COORDINATION_OVERRIDE_MISSING_LINEAGE";

export type HumanCoordinationOverrideError = Readonly<{
  code: HumanCoordinationOverrideErrorCode;
  message: string;
  path?: string;
}>;
