import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runProvingReplayValidationFramework, validateProvingReplayValidationFramework } from "@/services/proving-replay-validation-framework";
import type { AdversarialBundle, AdversarialFailure, AdversarialInput, AdversarialOutcome, AdversarialResult, AdversarialScenario, AdversarialValidation, AdversarialValidationReport, AttackScenarioType, AttackType } from "@/types/proving-adversarial-testing-framework";

const VERSION = "proving-adversarial-testing-framework/v6.7" as const;
const IDENTIFIER = "ProvingAdversarialTestingFramework" as const;
const ATTACKS = Object.freeze<AttackType[]>(["AUTHENTICATION", "AUTHORIZATION", "IDENTITY_SPOOFING", "PRIVILEGE_ESCALATION", "REPLAY_ATTACK", "POLICY_BYPASS", "AUTHORITY_ABUSE", "MALFORMED_REQUEST", "RACE_CONDITION", "TIMING_ATTACK", "DEPENDENCY_FAILURE", "CONFIGURATION_CORRUPTION", "TENANT_BOUNDARY_VIOLATION", "EVENT_ORDERING", "EVIDENCE_TAMPERING", "REPLAY_DIVERGENCE"]);
const SCENARIO_TYPES = Object.freeze<AttackScenarioType[]>(["SINGLE", "CHAINED", "COORDINATED", "CAMPAIGN", "ADAPTIVE", "INSIDER", "EXTERNAL"]);
let replayBaseline: ReturnType<typeof runProvingReplayValidationFramework> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly AdversarialFailure[], failure: AdversarialFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: AdversarialScenario): AdversarialFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function outcome(failures: readonly AdversarialFailure[]): AdversarialOutcome { if (has(failures, "GOVERNANCE_REVIEW_REQUIRED")) return "REQUIRES_GOVERNANCE_REVIEW"; return failures.length ? "FAIL" : "PASS"; }
function report(category: AdversarialValidationReport["category"], ok: boolean, evidence: boolean): AdversarialValidationReport {
  const label = category.toLowerCase();
  return nested({ report_id: ok ? `report:p6.7:${label}` : "", category, scenarios: ok ? freezeArray([`scenario:${label}:baseline`, `scenario:${label}:adversarial`]) : freezeArray<string>([]), expected_outcomes: ok ? freezeArray(["attack contained", "governance preserved", "evidence recorded"]) : freezeArray<string>([]), findings: ok ? freezeArray(["validated"]) : freezeArray(["validation incomplete"]), fail_closed: ok, evidence_refs: evidence ? freezeArray([`evidence:p6.7:${label}`]) : freezeArray<string>([]) });
}
function resultReplayHash(result: Omit<AdversarialResult, "replay_hash" | "integrity_hash">): string { return hash({ architecture: result.architecture.integrity_hash, attack_catalog: result.attack_catalog.integrity_hash, attack_scenarios: result.attack_scenarios.integrity_hash, fault_injection: result.fault_injection.integrity_hash, reports: [result.misuse_report.integrity_hash, result.abuse_report.integrity_hash, result.governance_report.integrity_hash, result.isolation_report.integrity_hash, result.replay_attack_report.integrity_hash, result.recovery_report.integrity_hash], analytics: result.analytics.integrity_hash, evidence: result.evidence_package.integrity_hash, gates: result.gates.integrity_hash, invariants: result.invariants.integrity_hash, boundaries: result.boundaries.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<AdversarialResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.readiness.outcome, replay_hash: result.replay_hash }); }

export function runProvingAdversarialTestingFramework(input: AdversarialInput = {}): AdversarialResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<AdversarialFailure>(direct ? [direct] : []);
  replayBaseline ??= runProvingReplayValidationFramework();
  const replayDependencyInvalid = !validateProvingReplayValidationFramework(replayBaseline).valid || has(scenarioFailures, "P6_6_REPLAY_VALIDATION_INVALID");
  const dependencyFailures = freezeArray<AdversarialFailure>(replayDependencyInvalid ? ["P6_6_REPLAY_VALIDATION_INVALID"] : []);
  const failures = freezeArray([...new Set([...scenarioFailures, ...dependencyFailures])]);
  const architectureOk = !has(failures, "ADVERSARIAL_ARCHITECTURE_MISSING");
  const catalogOk = !has(failures, "ATTACK_CATALOG_MISSING") && !has(failures, "ATTACK_COVERAGE_INCOMPLETE");
  const scenarioOk = !has(failures, "ATTACK_SCENARIO_GENERATION_MISSING");
  const faultOk = !has(failures, "FAULT_INJECTION_MISSING") && !has(failures, "FAULT_INJECTION_NONDETERMINISTIC");
  const misuseOk = !has(failures, "MISUSE_TESTING_MISSING");
  const abuseOk = !has(failures, "ABUSE_VALIDATION_MISSING");
  const governanceOk = !has(failures, "GOVERNANCE_ATTACK_VALIDATION_MISSING") && !has(failures, "GOVERNANCE_FAIL_CLOSED_FAILED") && !has(failures, "UNAUTHORIZED_EXECUTION_NOT_BLOCKED") && !has(failures, "AUTHORITY_PRESERVATION_FAILED") && !has(failures, "POLICY_PRESERVATION_FAILED") && !has(failures, "SAFETY_PRESERVATION_FAILED");
  const isolationOk = !has(failures, "IDENTITY_TENANT_ATTACK_VALIDATION_MISSING") && !has(failures, "TENANT_ISOLATION_VIOLATED");
  const replayOk = !has(failures, "REPLAY_ADVERSARIAL_VALIDATION_MISSING") && !has(failures, "REPLAY_EQUIVALENCE_FAILED") && !has(failures, "REPLAY_DIVERGENCE_UNCLASSIFIED") && !replayDependencyInvalid;
  const recoveryOk = !has(failures, "RECOVERY_VALIDATION_MISSING") && !has(failures, "RECOVERY_CONTAINMENT_FAILED") && !has(failures, "RESTORATION_VALIDATION_FAILED");
  const analyticsOk = !has(failures, "ADVERSARIAL_ANALYTICS_MISSING");
  const evidenceOk = !has(failures, "CERTIFICATION_EVIDENCE_MISSING") && !has(failures, "EVIDENCE_INTEGRITY_FAILED") && !has(failures, "EVIDENCE_LINEAGE_INCOMPLETE") && !has(failures, "CERTIFICATION_PACKAGE_MISSING");
  const deterministicOk = !has(failures, "DETERMINISTIC_ADVERSARIAL_EXECUTION_FAILED") && faultOk;
  const containmentOk = !has(failures, "NON_PRODUCTION_CONTAINMENT_FAILED");
  const boundariesOk = !has(failures, "PRODUCTION_SECURITY_MONITORING_OWNERSHIP_VIOLATION") && !has(failures, "RUNTIME_INCIDENT_RESPONSE_OWNERSHIP_VIOLATION") && !has(failures, "TRUST_EVALUATION_ATTEMPTED") && !has(failures, "SAFETY_QUALIFICATION_ATTEMPTED") && !has(failures, "REPLAY_ENGINE_IMPLEMENTATION_ATTEMPTED") && !has(failures, "SIMULATION_ENGINE_IMPLEMENTATION_ATTEMPTED");
  const architecture = nested({ architecture_id: architectureOk ? "architecture:p6.7:adversarial-testing" : "", architecture_model: architectureOk, execution_model: architectureOk && deterministicOk, testing_services: architectureOk, attack_pipeline: architectureOk && catalogOk && scenarioOk, deterministic: deterministicOk, dependency_validation: replayOk });
  const attack_catalog = nested({ catalog_id: catalogOk ? "catalog:p6.7:attacks" : "", attacks: catalogOk ? ATTACKS : freezeArray<AttackType>([]), metadata_complete: catalogOk, classification_complete: catalogOk, identity_attacks: catalogOk, governance_attacks: catalogOk, policy_attacks: catalogOk, replay_attacks: catalogOk, infrastructure_attacks: catalogOk, tenant_attacks: catalogOk });
  const attack_scenarios = nested({ scenario_set_id: scenarioOk ? `scenarios:p6.7:${input.seed ?? "canonical"}` : "", supported_types: scenarioOk ? SCENARIO_TYPES : freezeArray<AttackScenarioType>([]), campaign_definitions: scenarioOk ? freezeArray(["credential-boundary-campaign", "policy-bypass-chain", "replay-divergence-campaign", "tenant-isolation-campaign"]) : freezeArray<string>([]), deterministic_generation: scenarioOk && deterministicOk });
  const fault_injection = nested({ plan_id: faultOk ? "fault-plan:p6.7:deterministic" : "", service_failures: faultOk, node_failures: faultOk, network_latency: faultOk, packet_loss: faultOk, storage_corruption: faultOk, configuration_corruption: faultOk, dependency_failure: faultOk, api_failure: faultOk, timeout: faultOk, event_duplication: faultOk, event_omission: faultOk, ordering_faults: faultOk, deterministic: deterministicOk, replay_compatible: replayOk, execution_logs: faultOk ? freezeArray(["fault:service", "fault:network", "fault:storage", "fault:event-ordering"]) : freezeArray<string>([]) });
  const misuse_report = report("MISUSE", misuseOk && governanceOk, evidenceOk);
  const abuse_report = report("ABUSE", abuseOk && governanceOk, evidenceOk);
  const governance_report = report("GOVERNANCE", governanceOk, evidenceOk);
  const isolation_report = report("ISOLATION", isolationOk, evidenceOk);
  const replay_attack_report = report("REPLAY", replayOk, evidenceOk);
  const recovery_report = report("RECOVERY", recoveryOk, evidenceOk);
  const analytics = nested({ analytics_id: analyticsOk ? "analytics:p6.7:adversarial" : "", attack_success: failures.length, attack_failure: ATTACKS.length - failures.length, governance_intervention: governanceOk ? 3 : 0, replay_stability: replayOk ? 100 : 40, recovery_effectiveness: recoveryOk ? 100 : 30, resilience_score: analyticsOk && governanceOk && isolationOk && replayOk && recoveryOk ? 97 : 50, trend_reports: analyticsOk ? freezeArray(["trend:campaign-resilience", "trend:fault-tolerance", "trend:governance-containment"]) : freezeArray<string>([]) });
  const evidence_package = nested({ package_id: evidenceOk ? "evidence:p6.7:certification" : "", attack_evidence: evidenceOk ? freezeArray([misuse_report.report_id, abuse_report.report_id, governance_report.report_id, isolation_report.report_id]) : freezeArray<string>([]), fault_evidence: evidenceOk ? fault_injection.execution_logs : freezeArray<string>([]), replay_evidence: evidenceOk ? freezeArray([replay_attack_report.report_id, replayBaseline.evidence_registry.registry_id]) : freezeArray<string>([]), recovery_evidence: evidenceOk ? freezeArray([recovery_report.report_id]) : freezeArray<string>([]), governance_evidence: evidenceOk ? freezeArray([governance_report.report_id]) : freezeArray<string>([]), immutable: evidenceOk, lineage_complete: evidenceOk, certification_ready: evidenceOk });
  const gates = nested({ gate_id: "P6.7-GATES", architecture_verification: architectureOk && deterministicOk, attack_coverage: catalogOk, fault_injection: faultOk && deterministicOk && replayOk, misuse_verification: misuseOk && governanceOk, abuse_validation: abuseOk && governanceOk, governance_validation: governanceOk, replay_validation: replayOk, recovery_verification: recoveryOk, evidence_verification: evidenceOk, phase_certification: architectureOk && catalogOk && scenarioOk && faultOk && misuseOk && abuseOk && governanceOk && isolationOk && replayOk && recoveryOk && analyticsOk && evidenceOk && deterministicOk && containmentOk && boundariesOk, passed: false });
  const finalGates = nested({ ...gates, phase_certification: gates.phase_certification, passed: gates.architecture_verification && gates.attack_coverage && gates.fault_injection && gates.misuse_verification && gates.abuse_validation && gates.governance_validation && gates.replay_validation && gates.recovery_verification && gates.evidence_verification && gates.phase_certification });
  const invariants = nested({ deterministic_execution: deterministicOk, fail_closed_governance: governanceOk, tenant_isolation: isolationOk, evidence_integrity: evidenceOk, replay_equivalence: replayOk, non_production_containment: containmentOk });
  const boundaries = nested({ boundary_id: "boundaries:p6.7", owns_production_security_monitoring: false as const, owns_runtime_incident_response: false as const, owns_trust_evaluation: false as const, owns_safety_qualification: false as const, owns_replay_engine_implementation: false as const, owns_simulation_engine: false as const });
  const derivedFailures = freezeArray([...new Set([...failures, ...(!architectureOk ? ["ADVERSARIAL_ARCHITECTURE_MISSING" as const] : []), ...(!catalogOk ? ["ATTACK_CATALOG_MISSING" as const] : []), ...(!scenarioOk ? ["ATTACK_SCENARIO_GENERATION_MISSING" as const] : []), ...(!faultOk ? ["FAULT_INJECTION_MISSING" as const] : []), ...(!misuseOk ? ["MISUSE_TESTING_MISSING" as const] : []), ...(!abuseOk ? ["ABUSE_VALIDATION_MISSING" as const] : []), ...(!governanceOk ? ["GOVERNANCE_ATTACK_VALIDATION_MISSING" as const] : []), ...(!isolationOk ? ["IDENTITY_TENANT_ATTACK_VALIDATION_MISSING" as const] : []), ...(!replayOk ? ["REPLAY_ADVERSARIAL_VALIDATION_MISSING" as const] : []), ...(!recoveryOk ? ["RECOVERY_VALIDATION_MISSING" as const] : []), ...(!analyticsOk ? ["ADVERSARIAL_ANALYTICS_MISSING" as const] : []), ...(!evidenceOk ? ["CERTIFICATION_EVIDENCE_MISSING" as const] : []), ...(!deterministicOk ? ["DETERMINISTIC_ADVERSARIAL_EXECUTION_FAILED" as const] : []), ...(!containmentOk ? ["NON_PRODUCTION_CONTAINMENT_FAILED" as const] : []), ...(!boundariesOk ? ["PRODUCTION_SECURITY_MONITORING_OWNERSHIP_VIOLATION" as const] : [])])]);
  const finalOutcome = outcome(derivedFailures);
  const readiness = nested({ readiness_id: "P6.7-ADVERSARIAL-TESTING-READINESS-001", outcome: finalOutcome, phase_ready: finalOutcome === "PASS", architecture_ready: architectureOk, attack_catalog_ready: catalogOk, attack_scenarios_ready: scenarioOk, fault_injection_ready: faultOk, misuse_ready: misuseOk, abuse_ready: abuseOk, governance_ready: governanceOk, isolation_ready: isolationOk, replay_ready: replayOk, recovery_ready: recoveryOk, analytics_ready: analyticsOk, evidence_ready: evidenceOk, gates_passed: finalGates.passed, invariants_satisfied: deterministicOk && governanceOk && isolationOk && evidenceOk && replayOk && containmentOk, boundaries_respected: boundariesOk, failures: derivedFailures });
  const base: Omit<AdversarialResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, replay_validation_ref: "proving-replay-validation-framework/v6.6", architecture, attack_catalog, attack_scenarios, fault_injection, misuse_report, abuse_report, governance_report, isolation_report, replay_attack_report, recovery_report, analytics, evidence_package, gates: finalGates, invariants, boundaries, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateProvingAdversarialTestingFramework(result?: AdversarialResult): AdversarialValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, architecture_valid: false, attack_catalog_valid: false, attack_scenarios_valid: false, fault_injection_valid: false, misuse_valid: false, abuse_valid: false, governance_valid: false, isolation_valid: false, replay_valid: false, recovery_valid: false, analytics_valid: false, evidence_valid: false, gates_valid: false, invariants_valid: false, boundaries_valid: false, readiness_valid: false, failures: freezeArray(["ADVERSARIAL_ARCHITECTURE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const architecture_valid = verifyHashed(result.architecture) && result.architecture.architecture_model && result.architecture.attack_pipeline && result.architecture.deterministic && result.architecture.dependency_validation;
  const attack_catalog_valid = verifyHashed(result.attack_catalog) && result.attack_catalog.attacks.length === ATTACKS.length && result.attack_catalog.metadata_complete && result.attack_catalog.classification_complete && result.attack_catalog.tenant_attacks;
  const attack_scenarios_valid = verifyHashed(result.attack_scenarios) && result.attack_scenarios.supported_types.length === SCENARIO_TYPES.length && result.attack_scenarios.deterministic_generation;
  const fault_injection_valid = verifyHashed(result.fault_injection) && result.fault_injection.deterministic && result.fault_injection.replay_compatible && result.fault_injection.execution_logs.length > 0;
  const reportValid = (reportValue: AdversarialValidationReport) => verifyHashed(reportValue) && reportValue.fail_closed && reportValue.evidence_refs.length > 0 && reportValue.scenarios.length > 0;
  const misuse_valid = reportValid(result.misuse_report);
  const abuse_valid = reportValid(result.abuse_report);
  const governance_valid = reportValid(result.governance_report);
  const isolation_valid = reportValid(result.isolation_report);
  const replay_valid = reportValid(result.replay_attack_report);
  const recovery_valid = reportValid(result.recovery_report);
  const analytics_valid = verifyHashed(result.analytics) && result.analytics.resilience_score >= 90 && result.analytics.trend_reports.length > 0;
  const evidence_valid = verifyHashed(result.evidence_package) && result.evidence_package.immutable && result.evidence_package.lineage_complete && result.evidence_package.certification_ready;
  const gates_valid = verifyHashed(result.gates) && result.gates.passed;
  const invariants_valid = verifyHashed(result.invariants) && result.invariants.deterministic_execution && result.invariants.fail_closed_governance && result.invariants.tenant_isolation && result.invariants.evidence_integrity && result.invariants.replay_equivalence && result.invariants.non_production_containment;
  const boundaries_valid = verifyHashed(result.boundaries) && !result.boundaries.owns_production_security_monitoring && !result.boundaries.owns_runtime_incident_response && !result.boundaries.owns_trust_evaluation && !result.boundaries.owns_safety_qualification && !result.boundaries.owns_replay_engine_implementation && !result.boundaries.owns_simulation_engine;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && architecture_valid && attack_catalog_valid && attack_scenarios_valid && fault_injection_valid && misuse_valid && abuse_valid && governance_valid && isolation_valid && replay_valid && recovery_valid && analytics_valid && evidence_valid && gates_valid && invariants_valid && boundaries_valid && readiness_valid;
  return nested({ valid, outcome: result.readiness.outcome, replay_hash_valid, integrity_hash_valid, architecture_valid, attack_catalog_valid, attack_scenarios_valid, fault_injection_valid, misuse_valid, abuse_valid, governance_valid, isolation_valid, replay_valid, recovery_valid, analytics_valid, evidence_valid, gates_valid, invariants_valid, boundaries_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayProvingAdversarialTestingFramework(result = runProvingAdversarialTestingFramework()): boolean { const replayed = runProvingAdversarialTestingFramework(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateProvingAdversarialTestingFramework(result).valid; }
export function getProvingAdversarialTestingFrameworkBundle(): AdversarialBundle { const result = runProvingAdversarialTestingFramework(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_adversarial_testing: true, owns_attack_simulation: true, owns_fault_injection: true, owns_misuse_testing: true, owns_abuse_validation: true, owns_production_security_monitoring: false, owns_runtime_incident_response: false, owns_trust_evaluation: false, owns_safety_qualification: false, owns_replay_engine_implementation: false, owns_simulation_engine: false }), result, validation: validateProvingAdversarialTestingFramework(result) }); }
export const ProvingAdversarialTestingFrameworkService = Object.freeze({ run: runProvingAdversarialTestingFramework, validate: validateProvingAdversarialTestingFramework, replay: replayProvingAdversarialTestingFramework });
