import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runWaveFiveProvingGround, validateWaveFiveProvingGround } from "@/services/wave-five-proprium-proving-ground";
import type { WaveFiveConnectorLifecycleState, WaveFivePlatformBridgeGatewayBundle, WaveFivePlatformBridgeGatewayDecision, WaveFivePlatformBridgeGatewayFailure, WaveFivePlatformBridgeGatewayInput, WaveFivePlatformBridgeGatewayResult, WaveFivePlatformBridgeGatewayScenario, WaveFivePlatformBridgeGatewayValidation } from "@/types/wave-five-platform-bridge-gateway";

const VERSION = "wave-five-platform-bridge-gateway/w5.15" as const;
const IDENTIFIER = "WaveFivePlatformBridgeGateway" as const;
const LIFECYCLE = Object.freeze<WaveFiveConnectorLifecycleState[]>(["PROPOSED", "REGISTERED", "CONFIGURED", "SANDBOX_TESTING", "QUALIFICATION_IN_PROGRESS", "INTEGRATION_QUALIFIED", "ACTIVE", "SUSPENDED", "REVOKED", "EXPIRED", "RETIRED", "ARCHIVED"]);
const UPSTREAM_REFS = Object.freeze(["wave-five-proprium-proving-ground/w5.14", "wave-five-apex/w5.13", "wave-five-aurora/w5.12", "wave-five-learning-stevn/w5.11", "wave-five-writing-publisher-os/w5.10", "wave-five-research/w5.9", "wave-five-health/w5.8", "wave-five-finance/w5.7", "wave-five-tasks-commitments/w5.5", "wave-five-calendar-time/w5.4", "wave-five-personal-knowledge/w5.3", "wave-five-unified-personal-context/w5.2", "wave-five-application-platform/w5.1"]);
const PROVIDES = Object.freeze(["external-connection-framework", "connector-registry", "integration-contracts", "integration-configuration", "integration-qualification", "integration-eligibility", "integration-lifecycle", "integration-evidence"]);
let proving = runWaveFiveProvingGround();

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly WaveFivePlatformBridgeGatewayFailure[], failure: WaveFivePlatformBridgeGatewayFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: WaveFivePlatformBridgeGatewayScenario): WaveFivePlatformBridgeGatewayFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly WaveFivePlatformBridgeGatewayFailure[], scenario?: WaveFivePlatformBridgeGatewayScenario): WaveFivePlatformBridgeGatewayDecision {
  const notQualified = new Set<WaveFivePlatformBridgeGatewayFailure>(["W5_PROVING_GROUND_INVALID", "UNMANAGED_EXTERNAL_CONNECTIVITY_ALLOWED", "TRANSPORT_CONFIGURATION_INVALID", "TENANT_SCOPE_INVALID", "CONTRACT_VALIDATION_FAILED", "CONTRACT_FIRST_REQUIREMENT_BYPASSED", "CONFIGURATION_VALIDATION_FAILED", "SECRETS_REFERENCED_INSECURELY", "QUALIFICATION_NONDETERMINISTIC", "ACTIVE_WITHOUT_QUALIFICATION", "ELIGIBILITY_NOT_INDEPENDENT", "ACTIVE_WITHOUT_ELIGIBILITY", "INVALID_LIFECYCLE_TRANSITION_ACCEPTED", "TERMINAL_STATE_MUTATED", "POLICY_EVALUATION_BYPASSED", "TENANT_ISOLATION_BREACH", "INTEGRATION_EVIDENCE_MUTABLE", "APPLICATION_LIFECYCLE_OWNERSHIP_ASSUMED", "APPLICATION_CERTIFICATION_OWNERSHIP_ASSUMED", "PROPRIUM_QUALIFICATION_OWNERSHIP_ASSUMED", "USER_AUTHENTICATION_OWNERSHIP_ASSUMED", "POLICY_AUTHORING_OWNERSHIP_ASSUMED"]);
  if (failures.some((failure) => notQualified.has(failure))) return "NOT_QUALIFIED";
  if (has(failures, "PLATFORM_BRIDGE_GATEWAY_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_QUALIFIED";
  return "QUALIFIED";
}
function resultReplayHash(result: Omit<WaveFivePlatformBridgeGatewayResult, "replay_hash" | "integrity_hash">): string { return hash({ connections: result.external_connections.integrity_hash, registry: result.registry_contracts.integrity_hash, qualification: result.configuration_qualification.integrity_hash, eligibility: result.eligibility_lifecycle_governance.integrity_hash, evidence: result.evidence_admin.integrity_hash, boundary: result.boundary.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<WaveFivePlatformBridgeGatewayResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runWaveFivePlatformBridgeGateway(input: WaveFivePlatformBridgeGatewayInput = {}): WaveFivePlatformBridgeGatewayResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  proving = runWaveFiveProvingGround();
  const failures = freezeArray([...new Set([...(direct ? [direct] : []), ...(!validateWaveFiveProvingGround(proving).valid ? ["W5_PROVING_GROUND_INVALID" as const] : [])])]);
  const connectionsOk = !has(failures, "EXTERNAL_CONNECTION_FRAMEWORK_MISSING") && !has(failures, "UNMANAGED_EXTERNAL_CONNECTIVITY_ALLOWED") && !has(failures, "SECURE_CREDENTIAL_REFERENCES_MISSING") && !has(failures, "TRANSPORT_CONFIGURATION_INVALID");
  const registryContractsOk = !has(failures, "CONNECTOR_REGISTRY_MISSING") && !has(failures, "CONNECTOR_METADATA_INCOMPLETE") && !has(failures, "CONNECTOR_HISTORY_MISSING") && !has(failures, "TENANT_SCOPE_INVALID") && !has(failures, "INTEGRATION_CONTRACTS_MISSING") && !has(failures, "CONTRACT_VERSIONING_INVALID") && !has(failures, "CONTRACT_VALIDATION_FAILED") && !has(failures, "CONTRACT_FIRST_REQUIREMENT_BYPASSED");
  const configurationQualificationOk = !has(failures, "INTEGRATION_CONFIGURATION_MISSING") && !has(failures, "CONFIGURATION_VALIDATION_FAILED") && !has(failures, "CONFIGURATION_HISTORY_MISSING") && !has(failures, "SECRETS_REFERENCED_INSECURELY") && !has(failures, "INTEGRATION_QUALIFICATION_MISSING") && !has(failures, "QUALIFICATION_NONDETERMINISTIC") && !has(failures, "QUALIFICATION_EVIDENCE_MISSING") && !has(failures, "ACTIVE_WITHOUT_QUALIFICATION");
  const eligibilityLifecycleOk = !has(failures, "ELIGIBILITY_ENGINE_MISSING") && !has(failures, "ELIGIBILITY_NOT_INDEPENDENT") && !has(failures, "ELIGIBILITY_HISTORY_MISSING") && !has(failures, "ACTIVE_WITHOUT_ELIGIBILITY") && !has(failures, "LIFECYCLE_ENGINE_MISSING") && !has(failures, "INVALID_LIFECYCLE_TRANSITION_ACCEPTED") && !has(failures, "TERMINAL_STATE_MUTATED") && !has(failures, "LIFECYCLE_EVIDENCE_MISSING") && !has(failures, "GOVERNANCE_ENFORCEMENT_MISSING") && !has(failures, "OWNERSHIP_VALIDATION_MISSING") && !has(failures, "POLICY_EVALUATION_BYPASSED") && !has(failures, "TENANT_ISOLATION_BREACH");
  const evidenceAdminOk = !has(failures, "INTEGRATION_EVIDENCE_MISSING") && !has(failures, "INTEGRATION_EVIDENCE_MUTABLE") && !has(failures, "AUDIT_RECORDS_MISSING") && !has(failures, "REPLAY_SUPPORT_MISSING") && !has(failures, "ADMIN_EXPERIENCE_MISSING") && !has(failures, "LIFECYCLE_VISIBILITY_INCOMPLETE");
  const boundaryOk = !has(failures, "APPLICATION_LIFECYCLE_OWNERSHIP_ASSUMED") && !has(failures, "APPLICATION_CERTIFICATION_OWNERSHIP_ASSUMED") && !has(failures, "PROPRIUM_QUALIFICATION_OWNERSHIP_ASSUMED") && !has(failures, "USER_AUTHENTICATION_OWNERSHIP_ASSUMED") && !has(failures, "POLICY_AUTHORING_OWNERSHIP_ASSUMED");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "QUALIFIED";
  const external_connections = nested({ connection_id: connectionsOk ? "W5.15-EXTERNAL-CONNECTIONS-001" : "", outbound_connections: connectionsOk, inbound_integrations: connectionsOk, protocol_abstraction: connectionsOk, authentication_adapters: connectionsOk, endpoint_definitions: connectionsOk, transport_configuration: connectionsOk, secure_credential_references: connectionsOk, connection_manager: connectionsOk, endpoint_registry: connectionsOk, transport_layer: connectionsOk, gateway_exclusive: connectionsOk, unmanaged_connectivity_blocked: connectionsOk });
  const registry_contracts = nested({ registry_contracts_id: registryContractsOk ? "W5.15-REGISTRY-CONTRACTS-001" : "", connector_registry: registryContractsOk, connector_metadata: registryContractsOk, connector_history: registryContractsOk, identifiers: registryContractsOk, owners: registryContractsOk, providers: registryContractsOk, tenant_scopes: registryContractsOk, supported_capabilities: registryContractsOk, contract_versions: registryContractsOk, lifecycle_states: freezeArray(LIFECYCLE), qualification_history: registryContractsOk, eligibility_history: registryContractsOk, integration_contracts: registryContractsOk, contract_registry: registryContractsOk, contract_validation: registryContractsOk, interface_schema_versioned: registryContractsOk, authentication_defined: registryContractsOk, authorization_requirements_defined: registryContractsOk, request_response_validation: registryContractsOk, failure_timeout_replay_audit_defined: registryContractsOk, contract_first: registryContractsOk });
  const configuration_qualification = nested({ configuration_qualification_id: configurationQualificationOk ? "W5.15-CONFIGURATION-QUALIFICATION-001" : "", configuration_service: configurationQualificationOk, endpoint_configuration: configurationQualificationOk, credentials: configurationQualificationOk, secret_references: configurationQualificationOk, protocol_settings: configurationQualificationOk, timeout_configuration: configurationQualificationOk, retry_configuration: configurationQualificationOk, feature_flags: configurationQualificationOk, tenant_overrides: configurationQualificationOk, configuration_validation: configurationQualificationOk, configuration_history: configurationQualificationOk, qualification_engine: configurationQualificationOk, connectivity_validation: configurationQualificationOk, authentication_validation: configurationQualificationOk, authorization_validation: configurationQualificationOk, contract_compliance: configurationQualificationOk, protocol_compatibility: configurationQualificationOk, schema_validation: configurationQualificationOk, failure_handling: configurationQualificationOk, timeout_handling: configurationQualificationOk, replay_capability: configurationQualificationOk, audit_generation: configurationQualificationOk, deterministic_qualification: configurationQualificationOk, qualification_reports: configurationQualificationOk, qualification_evidence: configurationQualificationOk });
  const eligibility_lifecycle_governance = nested({ eligibility_lifecycle_id: eligibilityLifecycleOk ? "W5.15-ELIGIBILITY-LIFECYCLE-GOVERNANCE-001" : "", eligibility_engine: eligibilityLifecycleOk, governance_approval: eligibilityLifecycleOk, tenant_authorization: eligibilityLifecycleOk, licensing: eligibilityLifecycleOk, environment_restrictions: eligibilityLifecycleOk, operational_readiness: eligibilityLifecycleOk, organizational_policy: eligibilityLifecycleOk, eligibility_decisions: eligibilityLifecycleOk, eligibility_history: eligibilityLifecycleOk, eligibility_independent_from_qualification: eligibilityLifecycleOk, lifecycle_engine: eligibilityLifecycleOk, transition_validator: eligibilityLifecycleOk, lifecycle_history: eligibilityLifecycleOk, canonical_states: freezeArray(LIFECYCLE), transitions_validated: eligibilityLifecycleOk, illegal_transitions_rejected: eligibilityLifecycleOk, terminal_states_immutable: eligibilityLifecycleOk, ownership_validation: eligibilityLifecycleOk, contract_validation: eligibilityLifecycleOk, qualification_verification: eligibilityLifecycleOk, eligibility_verification: eligibilityLifecycleOk, policy_evaluation: eligibilityLifecycleOk, tenant_isolation: eligibilityLifecycleOk, governance_evidence: eligibilityLifecycleOk });
  const evidence_admin = nested({ evidence_admin_id: evidenceAdminOk ? "W5.15-EVIDENCE-ADMIN-001" : "", registrations: evidenceAdminOk, configuration_changes: evidenceAdminOk, qualification_results: evidenceAdminOk, eligibility_decisions: evidenceAdminOk, lifecycle_transitions: evidenceAdminOk, activation_history: evidenceAdminOk, suspension_history: evidenceAdminOk, revocation_history: evidenceAdminOk, integration_evidence: evidenceAdminOk, audit_records: evidenceAdminOk, evidence_registry: evidenceAdminOk, immutable_evidence: evidenceAdminOk, deterministic_replay_support: evidenceAdminOk, connector_dashboard: evidenceAdminOk, lifecycle_timeline: evidenceAdminOk, qualification_dashboard: evidenceAdminOk, contract_review: evidenceAdminOk, transition_approvals: evidenceAdminOk, evidence_inspection: evidenceAdminOk, complete_visibility: evidenceAdminOk });
  const boundary = nested({ boundary_id: "W5.15-PBG-BOUNDARY-001", owns_external_connections: boundaryOk, owns_connector_registry: boundaryOk, owns_integration_contracts: boundaryOk, owns_integration_qualification: boundaryOk, owns_integration_eligibility: boundaryOk, owns_application_lifecycle: false as const, owns_application_certification: false as const, owns_proprium_qualification: false as const, owns_user_authentication: false as const, owns_internal_application_routing: false as const, owns_trust_standing: false as const, owns_policy_authoring: false as const, lifecycle_independent_from_application_lifecycle: boundaryOk, lifecycle_independent_from_application_certification: boundaryOk, lifecycle_independent_from_proprium_qualification: boundaryOk });
  const readiness = nested({ readiness_id: "W5.15-PBG-READINESS-001", decision, phase_ready: qualified, proving_ground_ready: !has(failures, "W5_PROVING_GROUND_INVALID"), gateway_exclusive: connectionsOk, registry_tracks_all_integrations: registryContractsOk, contracts_versioned_validated: registryContractsOk, configuration_governed_auditable: configurationQualificationOk, qualification_deterministic: configurationQualificationOk, eligibility_independent: eligibilityLifecycleOk, lifecycle_canonical: eligibilityLifecycleOk, invalid_transitions_rejected: eligibilityLifecycleOk, immutable_transition_evidence: evidenceAdminOk, lifecycle_independence_preserved: boundaryOk, administrative_visibility_complete: evidenceAdminOk, no_unowned_scope_assumed: boundaryOk, failures });
  const base: Omit<WaveFivePlatformBridgeGatewayResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, proving_ground_ref: "wave-five-proprium-proving-ground/w5.14", upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id: input.tenant_id ?? proving.tenant_id, principal_id: input.principal_id ?? "principal:w5.15:pbg-operator", external_connections, registry_contracts, configuration_qualification, eligibility_lifecycle_governance, evidence_admin, boundary, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateWaveFivePlatformBridgeGateway(result?: WaveFivePlatformBridgeGatewayResult): WaveFivePlatformBridgeGatewayValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, external_connections_valid: false, registry_contracts_valid: false, configuration_qualification_valid: false, eligibility_lifecycle_governance_valid: false, evidence_admin_valid: false, boundary_valid: false, readiness_valid: false, failures: freezeArray(["EXTERNAL_CONNECTION_FRAMEWORK_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const external_connections_valid = verifyHashed(result.external_connections) && result.external_connections.gateway_exclusive && result.external_connections.unmanaged_connectivity_blocked && result.external_connections.secure_credential_references;
  const registry_contracts_valid = verifyHashed(result.registry_contracts) && result.registry_contracts.connector_registry && result.registry_contracts.lifecycle_states.length === LIFECYCLE.length && result.registry_contracts.contract_validation && result.registry_contracts.contract_first;
  const configuration_qualification_valid = verifyHashed(result.configuration_qualification) && result.configuration_qualification.configuration_validation && result.configuration_qualification.configuration_history && result.configuration_qualification.deterministic_qualification && result.configuration_qualification.qualification_evidence;
  const eligibility_lifecycle_governance_valid = verifyHashed(result.eligibility_lifecycle_governance) && result.eligibility_lifecycle_governance.eligibility_independent_from_qualification && result.eligibility_lifecycle_governance.illegal_transitions_rejected && result.eligibility_lifecycle_governance.terminal_states_immutable && result.eligibility_lifecycle_governance.tenant_isolation;
  const evidence_admin_valid = verifyHashed(result.evidence_admin) && result.evidence_admin.immutable_evidence && result.evidence_admin.deterministic_replay_support && result.evidence_admin.complete_visibility;
  const boundary_valid = verifyHashed(result.boundary) && result.boundary.owns_external_connections && !result.boundary.owns_application_lifecycle && !result.boundary.owns_application_certification && !result.boundary.owns_proprium_qualification && !result.boundary.owns_policy_authoring && result.boundary.lifecycle_independent_from_application_lifecycle;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.proving_ground_ready && result.readiness.gateway_exclusive && result.readiness.eligibility_independent && result.readiness.lifecycle_independence_preserved && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && external_connections_valid && registry_contracts_valid && configuration_qualification_valid && eligibility_lifecycle_governance_valid && evidence_admin_valid && boundary_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, external_connections_valid, registry_contracts_valid, configuration_qualification_valid, eligibility_lifecycle_governance_valid, evidence_admin_valid, boundary_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayWaveFivePlatformBridgeGateway(result = runWaveFivePlatformBridgeGateway()): boolean { const replayed = runWaveFivePlatformBridgeGateway(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateWaveFivePlatformBridgeGateway(result).valid; }
export function getWaveFivePlatformBridgeGatewayBundle(): WaveFivePlatformBridgeGatewayBundle { const result = runWaveFivePlatformBridgeGateway(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, platform_bridge_gateway_exclusive: true, contract_first_integration_required: true, deterministic_qualification_required: true, eligibility_independent_from_qualification: true, immutable_transition_evidence_required: true, unmanaged_external_connectivity_prohibited: true, application_lifecycle_ownership_prohibited: true, qualification_gate: "W5.15 Platform Bridge Gateway Integration Qualification Gate" }), result, validation: validateWaveFivePlatformBridgeGateway(result) }); }
export const WaveFivePlatformBridgeGatewayService = Object.freeze({ run: runWaveFivePlatformBridgeGateway, validate: validateWaveFivePlatformBridgeGateway, replay: replayWaveFivePlatformBridgeGateway });
