export type EscalationAwareCoordinationErrorCode =
  | "ESCALATION_COORDINATION_EXECUTION_FORBIDDEN"
  | "ESCALATION_COORDINATION_ORCHESTRATION_FORBIDDEN"
  | "ESCALATION_COORDINATION_RUNTIME_MUTATION_FORBIDDEN"
  | "ESCALATION_COORDINATION_AUTHORITY_INHERITANCE_FORBIDDEN"
  | "ESCALATION_COORDINATION_GOVERNANCE_MISMATCH"
  | "ESCALATION_COORDINATION_APPROVAL_INCOMPLETE"
  | "ESCALATION_COORDINATION_REPLAY_AMBIGUITY"
  | "ESCALATION_COORDINATION_REPLAY_DRIFT"
  | "ESCALATION_COORDINATION_CONTAINMENT_BYPASS"
  | "ESCALATION_COORDINATION_RECURSIVE_ESCALATION"
  | "ESCALATION_COORDINATION_SYNTHETIC_CONTINUITY"
  | "ESCALATION_COORDINATION_UNKNOWN_STATE";

export type EscalationAwareCoordinationError = Readonly<{
  code: EscalationAwareCoordinationErrorCode;
  message: string;
  path?: string;
}>;
