export type AdaptiveSafetyStatus = "PASS" | "FAIL";
export type AdaptiveSafetyDecision = "CERTIFIED" | "REJECTED";
export type AdaptiveSafetyWidget = "Safety Certification" | "Hidden Learning" | "Behavioral Mutation" | "Replay Integrity" | "Evidence Integrity" | "Adaptive Drift" | "Containment Recovery" | "Safety Report" | "Risk Assessment";
export type PermittedSafetyLearningSource = "TRUTH_LEDGER" | "CERTIFIED_ADAPTIVE_MEMORY" | "VALIDATED_SIMULATIONS" | "APPROVED_OPERATOR_FEEDBACK" | "CERTIFIED_HISTORICAL_OUTCOMES" | "REPLAY_ANALYSIS";
export type AdaptiveSafetyScenario =
  | "BASELINE" | "HIDDEN_LEARNING" | "BEHAVIORAL_MUTATION" | "REPLAY_CORRUPTION" | "EVIDENCE_POISONING" | "GOVERNANCE_DRIFT" | "CONSTITUTIONAL_DRIFT" | "AUTHORITY_ESCALATION" | "CONFIDENCE_DRIFT" | "RISK_DRIFT" | "REPLAY_RECONSTRUCTION_FAILURE" | "MEMORY_CONTAMINATION" | "CROSS_TENANT_EVIDENCE" | "FAIL_OPEN_RECOVERY" | "INCOMPLETE_CONTAINMENT" | "MISSING_OPERATOR_ESCALATION" | "APPEND_ONLY_VIOLATION" | "INTEGRITY_FAILURE";
export type AdaptiveSafetyFailure =
  | "HIDDEN_LEARNING_DETECTED" | "UNAUTHORIZED_BEHAVIORAL_MUTATION" | "REPLAY_CORRUPTION_DETECTED" | "EVIDENCE_POISONING_DETECTED" | "GOVERNANCE_DRIFT_UNCONTAINED" | "CONSTITUTIONAL_DRIFT_DETECTED" | "AUTHORITY_ESCALATION_DETECTED" | "CONFIDENCE_DRIFT_THRESHOLD_EXCEEDED" | "RISK_DRIFT_THRESHOLD_EXCEEDED" | "REPLAY_RECONSTRUCTION_FAILED" | "ADAPTIVE_MEMORY_CONTAMINATION" | "CROSS_TENANT_EVIDENCE_CONTAMINATION" | "FAIL_OPEN_RECOVERY_DETECTED" | "CONTAINMENT_INCOMPLETE" | "OPERATOR_ESCALATION_MISSING" | "APPEND_ONLY_LEDGER_VIOLATION" | "INTEGRITY_HASH_MISMATCH";
export type AdaptiveSafetyCertificationRecord = Readonly<{ certification_id: string; tenant_id: string; mission_id: string; hidden_learning_status: AdaptiveSafetyStatus; behavioral_mutation_status: AdaptiveSafetyStatus; replay_corruption_status: AdaptiveSafetyStatus; evidence_poisoning_status: AdaptiveSafetyStatus; governance_drift_status: AdaptiveSafetyStatus; authority_drift_status: AdaptiveSafetyStatus; confidence_drift_status: AdaptiveSafetyStatus; risk_drift_status: AdaptiveSafetyStatus; containment_status: AdaptiveSafetyStatus; recovery_status: AdaptiveSafetyStatus; findings: readonly AdaptiveSafetyFailure[]; evidence_refs: readonly string[]; governance_refs: readonly string[]; replay_refs: readonly string[]; drift_refs: readonly string[]; certification_status: AdaptiveSafetyDecision; certification_timestamp: string; integrity_hash: string }>;
export type HiddenLearningDetection = Readonly<{ validation_id: string; permitted_sources: readonly PermittedSafetyLearningSource[]; detector_operational: boolean; hidden_learning_absent: boolean; undocumented_learning_absent: boolean; runtime_adaptation_absent: boolean; hidden_state_absent: boolean; unauthorized_parameter_evolution_absent: boolean; uncertified_memory_absent: boolean; shadow_pipeline_absent: boolean; integrity_hash: string }>;
export type BehavioralMutationDetection = Readonly<{ validation_id: string; detector_operational: boolean; unauthorized_mutation_blocked: boolean; recommendation_generation_stable: boolean; prioritization_stable: boolean; suppression_logic_stable: boolean; reasoning_stable: boolean; confidence_calibration_stable: boolean; risk_assessment_stable: boolean; governance_evaluation_stable: boolean; constitutional_evaluation_stable: boolean; dashboard_presentation_stable: boolean; integrity_hash: string }>;
export type ReplaySafetyValidation = Readonly<{ validation_id: string; replay_corruption_detected: boolean; replay_integrity_preserved: boolean; replay_artifacts_complete: boolean; replay_lineage_unchanged: boolean; replay_divergence_absent: boolean; state_reconstruction_valid: boolean; replay_ordering_stable: boolean; replay_hashes_reproducible: boolean; integrity_hash: string }>;
export type EvidenceSafetyValidation = Readonly<{ validation_id: string; evidence_poisoning_detected: boolean; evidence_lineage_integrity_verified: boolean; observations_integrity_verified: boolean; normalized_outcomes_integrity_verified: boolean; memory_integrity_verified: boolean; operator_feedback_integrity_verified: boolean; simulation_evidence_integrity_verified: boolean; governance_evidence_integrity_verified: boolean; cross_tenant_contamination_absent: boolean; integrity_hash: string }>;
export type AdaptiveDriftValidation = Readonly<{ validation_id: string; governance_drift_detected: boolean; governance_supremacy_maintained: boolean; authority_drift_detected: boolean; authority_escalation_blocked: boolean; confidence_drift_detected: boolean; confidence_calibration_stable: boolean; risk_drift_detected: boolean; risk_calibration_stable: boolean; constitutional_drift_absent: boolean; integrity_hash: string }>;
export type ContainmentRecoveryValidation = Readonly<{ validation_id: string; containment_deterministic: boolean; recovery_deterministic: boolean; containment_replay_reproducible: boolean; adaptive_suppression_available: boolean; replay_rollback_available: boolean; evidence_quarantine_available: boolean; proposal_invalidation_available: boolean; memory_isolation_available: boolean; tenant_containment_available: boolean; certification_suspension_available: boolean; operator_escalation_functional: boolean; fail_closed_verified: boolean; safety_ledger_append_only: boolean; integrity_hash: string }>;
export type AdaptiveSafetyCertificationReport = Readonly<{ report_id: string; certification_outcome: AdaptiveSafetyDecision; hidden_learning_assessment: AdaptiveSafetyStatus; behavioral_mutation_analysis: AdaptiveSafetyStatus; replay_integrity_assessment: AdaptiveSafetyStatus; evidence_integrity_assessment: AdaptiveSafetyStatus; governance_drift_analysis: AdaptiveSafetyStatus; authority_drift_analysis: AdaptiveSafetyStatus; confidence_stability_assessment: AdaptiveSafetyStatus; risk_stability_assessment: AdaptiveSafetyStatus; containment_validation: AdaptiveSafetyStatus; recovery_validation: AdaptiveSafetyStatus; findings: readonly AdaptiveSafetyFailure[]; remediation_actions: readonly string[]; production_readiness_recommendation: "READY" | "BLOCKED"; integrity_hash: string }>;
export type AdaptiveRiskAssessmentReport = Readonly<{ report_id: string; safety_risk_profile: "LOW" | "ELEVATED"; threat_coverage_complete: boolean; drift_detection_effective: boolean; evidence_quality_verified: boolean; replay_trustworthy: boolean; governance_resilient: boolean; authority_boundary_validated: boolean; containment_performance: AdaptiveSafetyStatus; recovery_performance: AdaptiveSafetyStatus; certification_evidence_refs: readonly string[]; integrity_hash: string }>;
export type AdaptiveSafetyCertificationTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: "PASS" | "FAIL"; passed: boolean; failure_reason: AdaptiveSafetyFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;
export type AdaptiveSafetyApiSurface = Readonly<{ api_id: string; retrieve_dashboard: string; retrieve_contract: string; retrieve_sections: readonly string[]; validate_certification: string; inspect_certification: string; mutation_supported: false; execution_supported: false; fail_open_supported: false; safety_override_supported: false; integrity_hash: string }>;
export type AdaptiveSafetyInput = Readonly<{ scenario?: AdaptiveSafetyScenario; tenant_id?: string; mission_id?: string }>;
export type AdaptiveSafetyResult = Readonly<{ adaptive_safety_certification_version: "adaptive-safety-certification/v10.15.6"; certification_identifier: "AdaptiveSafetyCertification"; status: AdaptiveSafetyStatus; api_surface: AdaptiveSafetyApiSurface; record: AdaptiveSafetyCertificationRecord; hidden_learning_detection: HiddenLearningDetection; behavioral_mutation_detection: BehavioralMutationDetection; replay_safety_validation: ReplaySafetyValidation; evidence_safety_validation: EvidenceSafetyValidation; adaptive_drift_validation: AdaptiveDriftValidation; containment_recovery_validation: ContainmentRecoveryValidation; certification_report: AdaptiveSafetyCertificationReport; risk_assessment_report: AdaptiveRiskAssessmentReport; widgets: readonly AdaptiveSafetyWidget[]; validation_tests: readonly AdaptiveSafetyCertificationTest[]; failures: readonly AdaptiveSafetyFailure[]; safe: boolean; deterministic: boolean; replayable: boolean; tenant_isolated: boolean; fail_closed: boolean; production_ready: boolean; replay_hash: string; integrity_hash: string }>;
export type AdaptiveSafetyValidationResult = Readonly<{ certification_id: string | null; valid: boolean; status: AdaptiveSafetyStatus; failures: readonly AdaptiveSafetyFailure[]; replay_hash_valid: boolean; integrity_hash_valid: boolean; certification_hash: string }>;
export type AdaptiveSafetyObservability = Readonly<{ certification_id: string; status: AdaptiveSafetyStatus; failed_tests: number; failures: readonly AdaptiveSafetyFailure[]; safe: boolean; deterministic: boolean; replayable: boolean; tenant_isolated: boolean; fail_closed: boolean; production_ready: boolean; integrity_hash: string }>;
export type AdaptiveSafetyContract = Readonly<{ doctrine: Readonly<{ version: "adaptive-safety-certification/v10.15.6"; widgets: readonly AdaptiveSafetyWidget[]; permitted_learning_sources: readonly PermittedSafetyLearningSource[]; hidden_learning_prohibited: true; behavioral_mutation_prohibited: true; evidence_poisoning_prohibited: true; fail_closed_required: true; continuous_safety_required: true }>; result: AdaptiveSafetyResult; validation: AdaptiveSafetyValidationResult; observability: AdaptiveSafetyObservability }>;
