export type AdaptiveGovernanceOutcome = "PASS" | "CONDITIONAL_PASS" | "FAIL";
export type GovernanceEvaluationLifecycleState = "OPERATIONAL_EVIDENCE" | "GOVERNANCE_EVALUATION" | "POLICY_ASSESSMENT" | "WORKLOAD_ASSESSMENT" | "LATENCY_ASSESSMENT" | "CONSTITUTIONAL_COMPLIANCE" | "RECOMMENDATION_GENERATION" | "RECOMMENDATION_QUALIFICATION" | "GOVERNANCE_REGISTRY" | "IMMUTABLE_LEDGER";
export type GovernanceRecommendationType = "POLICY_REFINEMENT" | "WORKFLOW_IMPROVEMENT" | "REVIEW_PRIORITIZATION" | "GOVERNANCE_OPTIMIZATION" | "APPROVAL_PROCESS_IMPROVEMENT" | "STAFFING_RECOMMENDATION" | "EVIDENCE_IMPROVEMENT";
export type GovernanceRecommendationPriority = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type AdaptiveGovernanceFailure =
  | "GOVERNANCE_EVALUATIONS_NOT_DETERMINISTIC"
  | "POLICY_EFFECTIVENESS_NOT_CONTINUOUSLY_EVALUATED"
  | "GOVERNANCE_WORKLOAD_NOT_CONTINUOUSLY_EVALUATED"
  | "APPROVAL_LATENCY_NOT_CONTINUOUSLY_EVALUATED"
  | "CONSTITUTIONAL_COMPLIANCE_NOT_CONTINUOUSLY_VERIFIED"
  | "RECOMMENDATIONS_NOT_ADVISORY_ONLY"
  | "AUTHORITY_SCOPING_NOT_PRESERVED"
  | "REPLAY_NOT_REPRODUCIBLE"
  | "EVIDENCE_INCOMPLETE"
  | "IMMUTABLE_LINEAGE_NOT_PRESERVED"
  | "TENANT_AUTHORITY_BOUNDARIES_NOT_MAINTAINED"
  | "FAIL_CLOSED_NOT_VERIFIED"
  | "ADAPTIVE_GOVERNANCE_NOT_CERTIFIED"
  | "POLICY_MODIFICATION_ATTEMPTED"
  | "UNGOVERNED_DATA_CONSUMED"
  | "RECOMMENDATION_QUALIFICATION_FAILED"
  | "PHASE_18_7_CERTIFICATION_NOT_VALID"
  | "NON_CONSTITUTIONAL_GOVERNANCE_WARNING";
export type AdaptiveGovernanceScenario = "BASELINE" | AdaptiveGovernanceFailure;
export type AdaptiveGovernanceInput = Readonly<{ scenario?: AdaptiveGovernanceScenario; tenant_id?: string; operator_id?: string; mission_id?: string; evaluation_id?: string }>;

export type AdaptiveGovernanceEngine = Readonly<{ engine_id: string; evaluation_scheduling: boolean; evidence_aggregation: boolean; recommendation_generation: boolean; governance_scoring: boolean; replay_coordination: boolean; lifecycle_management: boolean; deterministic: boolean; governed_inputs_only: boolean; advisory_only: boolean; policy_modified: boolean; implementation_authority: boolean; integrity_hash: string }>;
export type PolicyEffectivenessEvaluator = Readonly<{ evaluator_id: string; approval_quality: boolean; rejection_quality: boolean; operator_override_frequency: boolean; unnecessary_approvals: boolean; unnecessary_denials: boolean; policy_stability: boolean; policy_consistency: boolean; continuous_evaluation: boolean; policy_modified: boolean; effectiveness_score: number; integrity_hash: string }>;
export type GovernanceWorkloadAnalyzer = Readonly<{ analyzer_id: string; review_volume: boolean; approval_backlog: boolean; governance_utilization: boolean; reviewer_distribution: boolean; review_duration: boolean; governance_saturation: boolean; escalation_frequency: boolean; continuous_evaluation: boolean; workload_score: number; integrity_hash: string }>;
export type ApprovalLatencyAnalyzer = Readonly<{ analyzer_id: string; average_approval_latency: boolean; median_approval_latency: boolean; queue_latency: boolean; escalation_latency: boolean; qualification_latency: boolean; certification_latency: boolean; review_bottlenecks: boolean; continuous_evaluation: boolean; latency_influences_authority: boolean; latency_score: number; integrity_hash: string }>;
export type ConstitutionalComplianceEvaluator = Readonly<{ evaluator_id: string; authority_boundaries: boolean; governance_enforcement: boolean; approval_sequencing: boolean; evidence_completeness: boolean; immutable_lineage: boolean; replay_integrity: boolean; advisory_boundary_preservation: boolean; continuously_verified: boolean; failure_events_generated: boolean; integrity_hash: string }>;
export type GovernanceRecommendationRecord = Readonly<{ governance_recommendation_id: string; evaluation_id: string; tenant_scope: string; governance_scope: string; authority_scope: string; recommendation_type: GovernanceRecommendationType; recommendation_summary: string; recommendation_reason: string; recommendation_priority: GovernanceRecommendationPriority; policy_effectiveness_score: number; governance_workload_score: number; approval_latency_score: number; constitutional_compliance_score: number; supporting_evidence_refs: readonly string[]; simulation_refs: readonly string[]; qualification_refs: readonly string[]; certification_refs: readonly string[]; applicable_policy_refs: readonly string[]; constitutional_refs: readonly string[]; authority_model: string; recommendation_scope: string; lineage_refs: readonly string[]; replay_refs: readonly string[]; immutable: boolean; advisory_only: boolean; qualified: boolean; integrity_hash: string }>;
export type GovernanceRecommendationEngine = Readonly<{ engine_id: string; policy_refinements: boolean; workflow_improvements: boolean; review_prioritization: boolean; governance_optimization: boolean; approval_process_improvements: boolean; staffing_recommendations: boolean; evidence_improvements: boolean; advisory_only: boolean; deterministic_generation: boolean; recommendations: readonly GovernanceRecommendationRecord[]; integrity_hash: string }>;
export type GovernanceRecommendationRegistry = Readonly<{ registry_id: string; recommendations: readonly GovernanceRecommendationRecord[]; immutable_recommendations: boolean; authority_scoped: boolean; tenant_authority_informational_only: boolean; recommendation_qualification_complete: boolean; publication_blocked_on_fail_closed: boolean; integrity_hash: string }>;
export type GovernanceEvaluationLedger = Readonly<{ ledger_id: string; evaluations: readonly string[]; metrics: readonly string[]; evidence: readonly string[]; recommendations: readonly string[]; advisory_outcomes: readonly string[]; superseding_lineage: readonly string[]; replay_references: readonly string[]; additive_only: boolean; immutable: boolean; integrity_hash: string }>;
export type AdaptiveGovernanceCertificationPackage = Readonly<{ package_id: string; governance_evaluations_deterministic: boolean; policy_effectiveness_continuously_evaluated: boolean; governance_workload_continuously_evaluated: boolean; approval_latency_continuously_evaluated: boolean; constitutional_compliance_continuously_verified: boolean; recommendations_advisory_only: boolean; authority_scoping_preserved: boolean; replay_reproducible: boolean; evidence_complete: boolean; immutable_lineage_preserved: boolean; tenant_authority_boundaries_maintained: boolean; fail_closed_behavior_verified: boolean; adaptive_governance_certified: boolean; evidence_refs: readonly string[]; integrity_hash: string }>;
export type AdaptiveGovernanceTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: AdaptiveGovernanceOutcome; passed: boolean; failure_reason: AdaptiveGovernanceFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;

export type AdaptiveGovernanceResult = Readonly<{ phase_version: "adaptive-governance/v18.8"; phase_identifier: "AdaptiveGovernance"; continuous_operational_certification_ref: string; adaptive_governance_engine: AdaptiveGovernanceEngine; policy_effectiveness_evaluator: PolicyEffectivenessEvaluator; governance_workload_analyzer: GovernanceWorkloadAnalyzer; approval_latency_analyzer: ApprovalLatencyAnalyzer; constitutional_compliance_evaluator: ConstitutionalComplianceEvaluator; recommendation_engine: GovernanceRecommendationEngine; recommendation_registry: GovernanceRecommendationRegistry; evaluation_ledger: GovernanceEvaluationLedger; lifecycle: readonly GovernanceEvaluationLifecycleState[]; certification_package: AdaptiveGovernanceCertificationPackage; certification_tests: readonly AdaptiveGovernanceTest[]; failures: readonly AdaptiveGovernanceFailure[]; outcome: AdaptiveGovernanceOutcome; replay_hash: string; integrity_hash: string }>;
export type AdaptiveGovernanceValidation = Readonly<{ valid: boolean; outcome: AdaptiveGovernanceOutcome; engine_valid: boolean; policy_valid: boolean; workload_valid: boolean; latency_valid: boolean; compliance_valid: boolean; recommendation_valid: boolean; registry_valid: boolean; ledger_valid: boolean; lifecycle_valid: boolean; certification_package_valid: boolean; certification_valid: boolean; result_replay_valid: boolean; failures: readonly AdaptiveGovernanceFailure[]; integrity_hash: string }>;
export type AdaptiveGovernanceBundle = Readonly<{ doctrine: Readonly<{ version: "adaptive-governance/v18.8"; upstream_phase: "continuous-operational-certification-service/v18.7"; lifecycle_states: readonly GovernanceEvaluationLifecycleState[]; recommendation_types: readonly GovernanceRecommendationType[]; recommendation_priorities: readonly GovernanceRecommendationPriority[]; certification_outcomes: readonly AdaptiveGovernanceOutcome[] }>; result: AdaptiveGovernanceResult; validation: AdaptiveGovernanceValidation }>;
