export type AdaptivePipelineStatus = "PASS" | "FAIL";
export type AdaptivePipelineDecision = "CERTIFIED" | "REJECTED";
export type AdaptivePipelineWidget = "Pipeline Certification" | "Subsystem Certifications" | "Pipeline Integration" | "Lineage Validation" | "Readiness Validation" | "Certification Report" | "Adaptive Integration Report";
export type AdaptivePipelineSubsystem = "outcome_observation" | "outcome_normalization" | "recommendation_effectiveness" | "pattern_intelligence" | "strategy_evolution" | "confidence_adaptation" | "risk_adaptation" | "governance_adaptation" | "operator_feedback" | "adaptation_proposal" | "adaptive_simulation" | "replay_validation" | "drift_defense" | "adaptive_memory" | "adaptive_dashboard";
export type AdaptivePipelineScenario =
  | "BASELINE" | "OUTCOME_OBSERVATION_FAILED" | "OUTCOME_NORMALIZATION_FAILED" | "RECOMMENDATION_EFFECTIVENESS_FAILED" | "PATTERN_INTELLIGENCE_FAILED" | "STRATEGY_EVOLUTION_FAILED" | "CONFIDENCE_ADAPTATION_FAILED" | "RISK_ADAPTATION_FAILED" | "GOVERNANCE_ADAPTATION_FAILED" | "OPERATOR_FEEDBACK_FAILED" | "ADAPTATION_PROPOSAL_FAILED" | "ADAPTIVE_SIMULATION_FAILED" | "REPLAY_VALIDATION_FAILED" | "DRIFT_DEFENSE_FAILED" | "ADAPTIVE_MEMORY_FAILED" | "ADAPTIVE_DASHBOARD_FAILED" | "UNDOCUMENTED_DEPENDENCY" | "SEQUENCING_DIVERGENCE" | "EVIDENCE_LINEAGE_GAP" | "GOVERNANCE_CONTINUITY_FAILURE" | "CONSTITUTIONAL_CONTINUITY_FAILURE" | "REPLAY_DISCONTINUITY" | "TENANT_ISOLATION_BREACH" | "ADVISORY_BOUNDARY_VIOLATION" | "UNAUTHORIZED_EXECUTION" | "HIDDEN_SUBSYSTEM_STATE" | "MISSING_CERTIFICATION_ARTIFACTS" | "INTERFACE_INCONSISTENCY" | "DASHBOARD_VISIBILITY_INCOMPLETE" | "PRODUCTION_READINESS_UNMET" | "INTEGRITY_FAILURE";
export type AdaptivePipelineFailure =
  | "OUTCOME_OBSERVATION_CERTIFICATION_FAILED" | "OUTCOME_NORMALIZATION_CERTIFICATION_FAILED" | "RECOMMENDATION_EFFECTIVENESS_CERTIFICATION_FAILED" | "PATTERN_INTELLIGENCE_CERTIFICATION_FAILED" | "STRATEGY_EVOLUTION_CERTIFICATION_FAILED" | "CONFIDENCE_ADAPTATION_CERTIFICATION_FAILED" | "RISK_ADAPTATION_CERTIFICATION_FAILED" | "GOVERNANCE_ADAPTATION_CERTIFICATION_FAILED" | "OPERATOR_FEEDBACK_CERTIFICATION_FAILED" | "ADAPTATION_PROPOSAL_CERTIFICATION_FAILED" | "ADAPTIVE_SIMULATION_CERTIFICATION_FAILED" | "REPLAY_VALIDATION_CERTIFICATION_FAILED" | "DRIFT_DEFENSE_CERTIFICATION_FAILED" | "ADAPTIVE_MEMORY_CERTIFICATION_FAILED" | "ADAPTIVE_DASHBOARD_CERTIFICATION_FAILED" | "UNDOCUMENTED_SUBSYSTEM_DEPENDENCY" | "PIPELINE_SEQUENCING_DIVERGENCE" | "EVIDENCE_LINEAGE_DISCONTINUITY" | "GOVERNANCE_CONTINUITY_FAILURE" | "CONSTITUTIONAL_CONTINUITY_FAILURE" | "REPLAY_CONTINUITY_FAILURE" | "TENANT_ISOLATION_BREACH" | "ADVISORY_ONLY_BOUNDARY_VIOLATION" | "UNAUTHORIZED_ADAPTIVE_EXECUTION" | "HIDDEN_SUBSYSTEM_STATE_DETECTED" | "CERTIFICATION_ARTIFACTS_MISSING" | "SUBSYSTEM_INTERFACE_INCONSISTENCY" | "DASHBOARD_VISIBILITY_INCOMPLETE" | "PRODUCTION_READINESS_CRITERIA_UNMET" | "INTEGRITY_HASH_MISMATCH";
export type AdaptiveSubsystemCertificationResult = Readonly<{ subsystem: AdaptivePipelineSubsystem; status: AdaptivePipelineStatus; deterministic: boolean; replayable: boolean; explainable: boolean; governance_compliant: boolean; constitutional: boolean; advisory_only: boolean; tenant_isolated: boolean; evidence_backed: boolean; certification_ref: string; integrity_hash: string }>;
export type AdaptivePipelineSubsystemResults = Readonly<Record<AdaptivePipelineSubsystem, AdaptiveSubsystemCertificationResult>>;
export type AdaptivePipelineCertificationRecord = Readonly<{ certification_id: string; tenant_id: string; mission_id: string; subsystem_results: AdaptivePipelineSubsystemResults; pipeline_integration_status: AdaptivePipelineStatus; evidence_lineage_status: AdaptivePipelineStatus; governance_continuity_status: AdaptivePipelineStatus; constitutional_continuity_status: AdaptivePipelineStatus; replay_continuity_status: AdaptivePipelineStatus; tenant_isolation_status: AdaptivePipelineStatus; findings: readonly AdaptivePipelineFailure[]; evidence_refs: readonly string[]; governance_refs: readonly string[]; replay_refs: readonly string[]; certification_refs: readonly string[]; certification_status: AdaptivePipelineDecision; certification_timestamp: string; integrity_hash: string }>;
export type PipelineIntegrationValidation = Readonly<{ validation_id: string; subsystem_sequence_deterministic: boolean; immutable_transitions: boolean; subsystem_interfaces_consistent: boolean; dependencies_documented: boolean; hidden_state_absent: boolean; end_to_end_execution_flow_valid: boolean; advisory_only_boundaries_preserved: boolean; integrity_hash: string }>;
export type EndToEndLineageValidation = Readonly<{ validation_id: string; evidence_lineage_continuous: boolean; governance_lineage_continuous: boolean; constitutional_lineage_continuous: boolean; replay_lineage_continuous: boolean; certification_lineage_continuous: boolean; dashboard_visibility_complete: boolean; auditability_complete: boolean; integrity_hash: string }>;
export type PipelineReadinessValidation = Readonly<{ validation_id: string; all_subsystems_certified: boolean; pipeline_deterministic: boolean; end_to_end_replay_reproducible: boolean; governance_enforced: boolean; constitutional_compliant: boolean; tenant_isolation_preserved: boolean; advisory_only: boolean; production_readiness_validated: boolean; unauthorized_execution_absent: boolean; integrity_hash: string }>;
export type AdaptivePipelineCertificationReport = Readonly<{ report_id: string; certification_outcome: AdaptivePipelineDecision; subsystem_certification_results: AdaptivePipelineSubsystemResults; pipeline_integration_assessment: AdaptivePipelineStatus; determinism_validation: AdaptivePipelineStatus; governance_constitutional_compliance: AdaptivePipelineStatus; replay_continuity_analysis: AdaptivePipelineStatus; tenant_isolation_assessment: AdaptivePipelineStatus; production_readiness_recommendation: "READY" | "BLOCKED"; findings: readonly AdaptivePipelineFailure[]; remediation_actions: readonly string[]; integrity_hash: string }>;
export type AdaptiveIntegrationReport = Readonly<{ report_id: string; subsystem_dependency_validation: AdaptivePipelineStatus; interface_compatibility: AdaptivePipelineStatus; end_to_end_execution_flow: readonly AdaptivePipelineSubsystem[]; evidence_lineage_continuity: AdaptivePipelineStatus; governance_constitutional_continuity: AdaptivePipelineStatus; replay_path_verification: AdaptivePipelineStatus; dashboard_integration: AdaptivePipelineStatus; certification_lineage: readonly string[]; operational_health_score: number; integrity_hash: string }>;
export type AdaptivePipelineCertificationTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: "PASS" | "FAIL"; passed: boolean; failure_reason: AdaptivePipelineFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;
export type AdaptivePipelineApiSurface = Readonly<{ api_id: string; retrieve_dashboard: string; retrieve_contract: string; retrieve_sections: readonly string[]; validate_certification: string; inspect_certification: string; mutation_supported: false; execution_supported: false; production_promotion_supported: false; override_supported: false; integrity_hash: string }>;
export type AdaptivePipelineInput = Readonly<{ scenario?: AdaptivePipelineScenario; tenant_id?: string; mission_id?: string }>;
export type AdaptivePipelineResult = Readonly<{ adaptive_pipeline_certification_version: "adaptive-pipeline-certification/v10.15.5"; certification_identifier: "AdaptivePipelineCertification"; status: AdaptivePipelineStatus; api_surface: AdaptivePipelineApiSurface; record: AdaptivePipelineCertificationRecord; integration_validation: PipelineIntegrationValidation; lineage_validation: EndToEndLineageValidation; readiness_validation: PipelineReadinessValidation; certification_report: AdaptivePipelineCertificationReport; adaptive_integration_report: AdaptiveIntegrationReport; widgets: readonly AdaptivePipelineWidget[]; validation_tests: readonly AdaptivePipelineCertificationTest[]; failures: readonly AdaptivePipelineFailure[]; deterministic: boolean; replayable: boolean; governed: boolean; constitutional: boolean; advisory_only: boolean; tenant_isolated: boolean; production_ready: boolean; replay_hash: string; integrity_hash: string }>;
export type AdaptivePipelineValidationResult = Readonly<{ certification_id: string | null; valid: boolean; status: AdaptivePipelineStatus; failures: readonly AdaptivePipelineFailure[]; replay_hash_valid: boolean; integrity_hash_valid: boolean; certification_hash: string }>;
export type AdaptivePipelineObservability = Readonly<{ certification_id: string; status: AdaptivePipelineStatus; failed_subsystems: number; failed_tests: number; failures: readonly AdaptivePipelineFailure[]; deterministic: boolean; replayable: boolean; governed: boolean; constitutional: boolean; tenant_isolated: boolean; production_ready: boolean; integrity_hash: string }>;
export type AdaptivePipelineContract = Readonly<{ doctrine: Readonly<{ version: "adaptive-pipeline-certification/v10.15.5"; widgets: readonly AdaptivePipelineWidget[]; subsystems: readonly AdaptivePipelineSubsystem[]; deterministic_required: true; replay_required: true; governance_required: true; constitutional_required: true; tenant_isolation_required: true; advisory_only_required: true; certification_required: true }>; result: AdaptivePipelineResult; validation: AdaptivePipelineValidationResult; observability: AdaptivePipelineObservability }>;
