export type AdaptationQualificationOutcome = "PASS" | "CONDITIONAL_PASS" | "FAIL";
export type QualificationDecisionOutcome = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "REQUIRES_MORE_EVIDENCE" | "REQUIRES_GOVERNANCE_REVIEW" | "REJECTED";
export type QualificationWorkflowState = "SIMULATION_COMPLETED" | "EVIDENCE_COLLECTION" | "EVIDENCE_VALIDATION" | "CONSTITUTIONAL_EVALUATION" | "GOVERNANCE_EVALUATION" | "REPLAY_VERIFICATION" | "OPERATIONAL_IMPACT_EVALUATION" | "QUALIFICATION_DECISION" | "IMMUTABLE_QUALIFICATION_RECORD";
export type QualificationDomain = "CONSTITUTIONAL_COMPLIANCE" | "GOVERNANCE_COMPLIANCE" | "REPLAY_INTEGRITY" | "DETERMINISTIC_REPRODUCIBILITY" | "OPERATIONAL_BENEFIT" | "OPERATIONAL_SAFETY" | "OPTIMIZATION_VALIDITY" | "TENANT_ISOLATION" | "CERTIFICATION_COMPATIBILITY" | "EVIDENCE_COMPLETENESS";
export type AdaptationQualificationFailure =
  | "QUALIFICATION_NOT_DETERMINISTIC"
  | "EVIDENCE_INCOMPLETE"
  | "REPLAY_NOT_REPRODUCIBLE"
  | "QUALIFICATION_LINEAGE_NOT_PRESERVED"
  | "GOVERNANCE_VALIDATION_INCOMPLETE"
  | "CONSTITUTIONAL_COMPLIANCE_NOT_VERIFIED"
  | "TENANT_ISOLATION_NOT_PRESERVED"
  | "QUALIFICATION_AUDIT_INCOMPLETE"
  | "RECOMMENDATION_ELIGIBILITY_NOT_GOVERNED"
  | "IMPLEMENTATION_AUTHORITY_GRANTED"
  | "QUALIFICATION_RECORD_MUTABLE"
  | "UNKNOWN_RULE_NOT_FAIL_CLOSED"
  | "PHASE_18_5_SIMULATION_NOT_VALID"
  | "NON_CONSTITUTIONAL_QUALIFICATION_WARNING";
export type AdaptationQualificationScenario = "BASELINE" | AdaptationQualificationFailure;
export type AdaptationQualificationInput = Readonly<{ scenario?: AdaptationQualificationScenario; tenant_id?: string; operator_id?: string; mission_id?: string; qualification_id?: string; adaptation_id?: string }>;

export type AdaptationQualificationService = Readonly<{ service_id: string; completed_simulations_evaluated: boolean; constitutional_compliance_validated: boolean; governance_compliance_verified: boolean; replay_reproducibility_verified: boolean; evidence_completeness_verified: boolean; operational_impact_verified: boolean; tenant_isolation_preserved: boolean; qualification_outcome_determined: boolean; immutable_lineage_preserved: boolean; evidentiary_only: boolean; implementation_authority_granted: boolean; deterministic: boolean; integrity_hash: string }>;
export type QualificationPolicyEngine = Readonly<{ engine_id: string; domains: readonly QualificationDomain[]; constitutional_requirements: boolean; governance_requirements: boolean; replay_requirements: boolean; evidence_requirements: boolean; operational_policies: boolean; optimization_policies: boolean; deterministic_policy_evaluation: boolean; unknown_rules_fail_closed: boolean; integrity_hash: string }>;
export type QualificationRuleEvaluator = Readonly<{ evaluator_id: string; replay_validated: boolean; simulation_deterministic: boolean; evidence_complete: boolean; governance_satisfied: boolean; constitutional_compliance_verified: boolean; tenant_isolation_preserved: boolean; operational_impact_acceptable: boolean; unknown_rules_fail_closed: boolean; deterministic_execution: boolean; integrity_hash: string }>;
export type QualificationDecisionRecord = Readonly<{ qualification_id: string; adaptation_id: string; simulation_id: string; tenant_id: string; qualification_outcome: QualificationDecisionOutcome; constitutional_result: "PASS" | "FAIL"; governance_result: "PASS" | "FAIL"; replay_result: "PASS" | "FAIL"; operational_result: "PASS" | "FAIL"; evidence_refs: readonly string[]; simulation_refs: readonly string[]; decision_reason: string; qualification_timestamp: string; integrity_hash: string }>;
export type QualificationDecisionRegistry = Readonly<{ registry_id: string; decisions: readonly QualificationDecisionRecord[]; qualification_identity_tracked: boolean; adaptation_identity_tracked: boolean; simulation_references_tracked: boolean; evidence_lineage_tracked: boolean; replay_references_tracked: boolean; governance_references_tracked: boolean; supersession_history_tracked: boolean; immutable_records: boolean; integrity_hash: string }>;
export type QualificationEvidenceLedger = Readonly<{ ledger_id: string; simulation_evidence: readonly string[]; replay_evidence: readonly string[]; governance_evidence: readonly string[]; operational_evidence: readonly string[]; constitutional_evidence: readonly string[]; qualification_rationale: readonly string[]; audit_references: readonly string[]; integrity_verification: boolean; append_only: boolean; integrity_hash: string }>;
export type QualificationWorkflowManager = Readonly<{ workflow_id: string; states: readonly QualificationWorkflowState[]; transitions_deterministic: boolean; qualification_precedes_recommendation: boolean; evidence_collection_complete: boolean; validation_order_preserved: boolean; immutable_record_committed: boolean; integrity_hash: string }>;
export type QualificationReplayValidator = Readonly<{ validator_id: string; identical_evidence_selection: boolean; identical_rule_execution: boolean; identical_decision_path: boolean; identical_qualification_outcome: boolean; identical_audit_lineage: boolean; replay_divergence_fails_qualification: boolean; reproducible: boolean; integrity_hash: string }>;
export type QualificationLineage = Readonly<{ lineage_id: string; monitoring_observations: readonly string[]; learned_operational_patterns: readonly string[]; optimization_recommendations: readonly string[]; simulation_executions: readonly string[]; governance_decisions: readonly string[]; replay_evidence: readonly string[]; certification_evidence: readonly string[]; no_lineage_removed: boolean; integrity_hash: string }>;
export type QualificationAuditService = Readonly<{ audit_id: string; audit_complete: boolean; immutable_audit: boolean; decision_auditable: boolean; supersession_additive: boolean; tenant_boundary_audited: boolean; authority_boundary_audited: boolean; integrity_hash: string }>;
export type QualificationCertificationPackage = Readonly<{ package_id: string; qualification_deterministic: boolean; evidence_complete: boolean; replay_reproducible: boolean; qualification_lineage_preserved: boolean; governance_validation_complete: boolean; constitutional_compliance_verified: boolean; tenant_isolation_preserved: boolean; qualification_audit_complete: boolean; recommendation_eligibility_governed: boolean; adaptation_qualification_certified: boolean; evidence_refs: readonly string[]; integrity_hash: string }>;
export type AdaptationQualificationTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: AdaptationQualificationOutcome; passed: boolean; failure_reason: AdaptationQualificationFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;

export type AdaptationQualificationResult = Readonly<{ phase_version: "adaptation-qualification-service/v18.6"; phase_identifier: "AdaptationQualificationService"; adaptation_simulation_ref: string; qualification_service: AdaptationQualificationService; policy_engine: QualificationPolicyEngine; rule_evaluator: QualificationRuleEvaluator; decision_registry: QualificationDecisionRegistry; evidence_ledger: QualificationEvidenceLedger; workflow_manager: QualificationWorkflowManager; replay_validator: QualificationReplayValidator; qualification_lineage: QualificationLineage; audit_service: QualificationAuditService; certification_package: QualificationCertificationPackage; certification_tests: readonly AdaptationQualificationTest[]; failures: readonly AdaptationQualificationFailure[]; outcome: AdaptationQualificationOutcome; replay_hash: string; integrity_hash: string }>;
export type AdaptationQualificationValidation = Readonly<{ valid: boolean; outcome: AdaptationQualificationOutcome; service_valid: boolean; policy_valid: boolean; rule_valid: boolean; decision_valid: boolean; evidence_valid: boolean; workflow_valid: boolean; replay_valid: boolean; lineage_valid: boolean; audit_valid: boolean; certification_package_valid: boolean; certification_valid: boolean; result_replay_valid: boolean; failures: readonly AdaptationQualificationFailure[]; integrity_hash: string }>;
export type AdaptationQualificationBundle = Readonly<{ doctrine: Readonly<{ version: "adaptation-qualification-service/v18.6"; upstream_phase: "adaptation-simulation-engine/v18.5"; workflow_states: readonly QualificationWorkflowState[]; evaluation_domains: readonly QualificationDomain[]; decision_outcomes: readonly QualificationDecisionOutcome[]; certification_outcomes: readonly AdaptationQualificationOutcome[] }>; result: AdaptationQualificationResult; validation: AdaptationQualificationValidation }>;
