export type CertificationEngineDecision = "CERTIFICATION_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type CertificationState = "Draft" | "Pending Review" | "Under Qualification" | "Qualified" | "Certified" | "Conditionally Certified" | "Suspended" | "Revoked" | "Expired" | "Retired";
export type CertificationEngineFailure =
  | "W2_1_AGENT_REGISTRY_INVALID" | "W2_3_CAPABILITY_REGISTRY_INVALID" | "W2_4_SKILL_REGISTRY_INVALID" | "W2_5_AUTHORITY_VALIDATOR_INVALID" | "W2_6_POLICY_GATE_INVALID" | "W2_7_SAFETY_GATE_INVALID" | "W2_8_PLANNING_ENGINE_INVALID" | "W2_9_MEMORY_ENGINE_INVALID" | "W2_10_RUNTIME_ORCHESTRATOR_INVALID" | "W2_11_DELEGATION_ENGINE_INVALID" | "W2_12_COLLABORATION_ENGINE_INVALID" | "W2_13_EVIDENCE_ENGINE_INVALID" | "W2_14_REPLAY_ENGINE_INVALID"
  | "CERTIFICATION_SERVICE_MISSING" | "CERTIFICATION_WORKFLOW_NON_DETERMINISTIC" | "CERTIFICATE_NOT_SIGNED" | "CERTIFICATION_APPROVAL_MISSING"
  | "AGENT_CERTIFICATION_MISSING" | "AGENT_IDENTITY_VALIDATION_FAILED" | "AGENT_EVIDENCE_INCOMPLETE"
  | "CAPABILITY_CERTIFICATION_MISSING" | "CAPABILITY_DEPENDENCY_INVALID" | "CAPABILITY_REPLAY_INVALID"
  | "SKILL_CERTIFICATION_MISSING" | "SKILL_CONTRACT_INVALID" | "SKILL_VERSION_INCOMPATIBLE" | "SKILL_DETERMINISM_FAILED"
  | "RUNTIME_CERTIFICATION_MISSING" | "RUNTIME_CONFIGURATION_INVALID" | "RUNTIME_SECURITY_FAILED" | "RUNTIME_OBSERVABILITY_MISSING"
  | "QUALIFICATION_ENGINE_MISSING" | "QUALIFICATION_DECISION_NON_DETERMINISTIC" | "QUALIFICATION_SCORE_MISSING" | "OPERATIONAL_READINESS_FAILED"
  | "CERTIFICATION_REGISTRY_MISSING" | "CERTIFICATION_LINEAGE_MUTABLE" | "CERTIFICATION_VERSIONING_MISSING"
  | "CERTIFICATION_LIFECYCLE_MISSING" | "REVOCATION_NOT_ENFORCED" | "EXPIRATION_NOT_ENFORCED" | "RECERTIFICATION_MISSING"
  | "CERTIFICATION_EVIDENCE_MISSING" | "EVIDENCE_PACKAGE_NOT_LINKED" | "REPLAY_REPORT_NOT_LINKED"
  | "CERTIFICATION_GOVERNANCE_MISSING" | "SEPARATION_OF_DUTIES_FAILED" | "AUDIT_RECORDING_MISSING"
  | "CERTIFICATION_API_MISSING" | "CERTIFICATION_VIEW_MISSING" | "QUALIFICATION_REPORT_MISSING" | "CERTIFICATION_REPLAY_INVALID" | "CERTIFICATION_ENGINE_QUALIFICATION_FAILED";
export type CertificationEngineScenario = "BASELINE" | "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | CertificationEngineFailure;
export type CertificationEngineInput = Readonly<{ scenario?: CertificationEngineScenario; seed?: string }>;
export type CertificationService = Readonly<{ service_id: string; certification_requests: boolean; orchestration: boolean; evaluation_pipeline: boolean; evidence_verification: boolean; replay_verification: boolean; approval_workflow: boolean; issuance: boolean; renewal: boolean; suspension: boolean; revocation: boolean; signed_certificates: boolean; deterministic_workflows: boolean; integrity_hash: string }>;
export type AgentCertification = Readonly<{ certificate_id: string; identity: boolean; configuration: boolean; capabilities: boolean; authority: boolean; policy_compliance: boolean; safety_compliance: boolean; runtime_behavior: boolean; planning: boolean; collaboration: boolean; delegation: boolean; replay_determinism: boolean; evidence_completeness: boolean; integrity_hash: string }>;
export type CapabilityCertification = Readonly<{ certificate_id: string; dependency_validation: boolean; authority_validation: boolean; policy_validation: boolean; safety_validation: boolean; compatibility: boolean; replay_verification: boolean; evidence_validation: boolean; integrity_hash: string }>;
export type SkillCertification = Readonly<{ certificate_id: string; interface_contracts: boolean; version_compatibility: boolean; dependency_integrity: boolean; deterministic_execution: boolean; replay_verification: boolean; evidence_package: boolean; integrity_hash: string }>;
export type RuntimeCertification = Readonly<{ certificate_id: string; runtime_configuration: boolean; orchestration: boolean; context_assembly: boolean; restrictions: boolean; checkpointing: boolean; recovery: boolean; replay_validation: boolean; observability: boolean; security: boolean; integrity_hash: string }>;
export type QualificationEngine = Readonly<{ engine_id: string; constitutional_compliance: boolean; authority_compliance: boolean; policy_compliance: boolean; safety_compliance: boolean; deterministic_replay: boolean; evidence_completeness: boolean; runtime_stability: boolean; dependency_integrity: boolean; operational_readiness: boolean; qualification_decision: CertificationEngineDecision; qualification_score: number; deterministic_decisions: boolean; integrity_hash: string }>;
export type CertificationRegistry = Readonly<{ registry_id: string; certificates: boolean; qualification_history: boolean; renewal_history: boolean; revocations: boolean; suspensions: boolean; expiration: boolean; lineage: boolean; evidence_references: boolean; immutable_history: boolean; versioning: boolean; audit: boolean; integrity_hash: string }>;
export type CertificationLifecycle = Readonly<{ manager_id: string; states: readonly CertificationState[]; initial_certification: boolean; recertification: boolean; renewal: boolean; suspension: boolean; revocation: boolean; expiration: boolean; retirement: boolean; active_certificates: boolean; pending_reviews: boolean; failed_certifications: boolean; superseded_certificates: boolean; integrity_hash: string }>;
export type CertificationEvidenceIntegration = Readonly<{ integration_id: string; evidence_packages: boolean; replay_reports: boolean; decision_history: boolean; runtime_history: boolean; safety_reports: boolean; policy_reports: boolean; authority_reports: boolean; certification_evidence_package: boolean; immutable_links: boolean; integrity_hash: string }>;
export type CertificationGovernance = Readonly<{ governance_id: string; constitutional_compliance: boolean; governance_enforcement: boolean; approval_workflow: boolean; operator_review: boolean; audit_recording: boolean; separation_of_duties: boolean; authority_controls: boolean; policy_controls: boolean; safety_controls: boolean; integrity_hash: string }>;
export type CertificationApis = Readonly<{ api_id: string; submit_certification: boolean; retrieve_certificate: boolean; retrieve_qualification: boolean; renew_certificate: boolean; suspend_certificate: boolean; revoke_certificate: boolean; list_certifications: boolean; run_qualification: boolean; qualification_status: boolean; qualification_history: boolean; qualification_evidence: boolean; query_certificates: boolean; search_certificates: boolean; retrieve_lineage: boolean; retrieve_evidence: boolean; retrieve_replay_references: boolean; stable: boolean; integrity_hash: string }>;
export type CertificationView = Readonly<{ view_id: string; dashboard: boolean; qualification_status: boolean; certificate_lineage: boolean; renewal_status: boolean; revocation_history: boolean; compliance_summaries: boolean; secure_access: boolean; integrity_hash: string }>;
export type QualificationReports = Readonly<{ report_id: string; qualification_decision: boolean; compliance_summary: boolean; replay_verification: boolean; evidence_completeness: boolean; authority_validation: boolean; policy_validation: boolean; safety_validation: boolean; operational_readiness: boolean; certification_recommendations: boolean; automatic_generation: boolean; integrity_hash: string }>;
export type CertificationReadiness = Readonly<{ readiness_id: string; decision: CertificationEngineDecision; phase_ready: boolean; upstream_ready: boolean; service_ready: boolean; agent_ready: boolean; capability_ready: boolean; skill_ready: boolean; runtime_ready: boolean; qualification_ready: boolean; registry_ready: boolean; lifecycle_ready: boolean; evidence_ready: boolean; governance_ready: boolean; apis_ready: boolean; view_ready: boolean; reports_ready: boolean; replay_reproducible: boolean; evidence_linked: boolean; failures: readonly CertificationEngineFailure[]; integrity_hash: string }>;
export type CertificationEngineResult = Readonly<{ phase_version: "certification-engine/w2.15"; phase_identifier: "CertificationEngine"; upstream_refs: readonly string[]; service: CertificationService; agent_certification: AgentCertification; capability_certification: CapabilityCertification; skill_certification: SkillCertification; runtime_certification: RuntimeCertification; qualification: QualificationEngine; registry: CertificationRegistry; lifecycle: CertificationLifecycle; evidence_integration: CertificationEvidenceIntegration; governance: CertificationGovernance; apis: CertificationApis; view: CertificationView; reports: QualificationReports; readiness: CertificationReadiness; replay_hash: string; integrity_hash: string }>;
export type CertificationEngineValidation = Readonly<{ valid: boolean; decision: CertificationEngineDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; service_valid: boolean; agent_valid: boolean; capability_valid: boolean; skill_valid: boolean; runtime_valid: boolean; qualification_valid: boolean; registry_valid: boolean; lifecycle_valid: boolean; evidence_valid: boolean; governance_valid: boolean; apis_valid: boolean; view_valid: boolean; reports_valid: boolean; readiness_valid: boolean; failures: readonly CertificationEngineFailure[]; integrity_hash: string }>;
export type CertificationEngineBundle = Readonly<{ doctrine: Readonly<{ version: "certification-engine/w2.15"; owns_agent_certification: true; owns_capability_certification: true; owns_skill_certification: true; owns_runtime_certification: true; owns_qualification_framework: true; owns_certification_governance: true; owns_certification_evidence: true; owns_certification_lineage: true; owns_certification_lifecycle: true; qualification_gate: "Certification Engine Qualification Gate" }>; result: CertificationEngineResult; validation: CertificationEngineValidation }>;
