export type ContinuousOperationalCertificationOutcome = "PASS" | "CONDITIONAL_PASS" | "FAIL";
export type CertificationEvaluationOutcome = "QUALIFICATION_MAINTAINED" | "QUALIFICATION_SUPERSEDED" | "QUALIFICATION_SUSPENDED" | "QUALIFICATION_REVOKED" | "ADDITIONAL_EVIDENCE_REQUIRED" | "CERTIFICATION_DRIFT_DETECTED";
export type CertificationEventType = "QUALIFICATION_MAINTAINED" | "QUALIFICATION_GRANTED" | "QUALIFICATION_SUSPENDED" | "QUALIFICATION_REVOKED" | "QUALIFICATION_RESTORED" | "CERTIFICATION_SUPERSEDED" | "CERTIFICATION_DRIFT_DETECTED" | "EVIDENCE_INSUFFICIENT" | "ATTESTATION_INVALIDATED" | "SERVICE_FAIL_CLOSED";
export type CertificationLifecycleState = "OPERATIONAL_EVENT" | "EVIDENCE_COLLECTION" | "CERTIFICATION_EVALUATION" | "QUALIFICATION_DECISION" | "CERTIFICATION_EVENT" | "LINEAGE_UPDATE" | "CONTINUOUS_MONITORING";
export type CertificationDriftClass = "OPERATIONAL" | "GOVERNANCE" | "REPLAY" | "QUALIFICATION" | "EVIDENCE" | "LINEAGE" | "DEPENDENCY" | "IMPLEMENTATION";
export type OperationalChangeType = "CONFIGURATION" | "INFRASTRUCTURE" | "DEPENDENCY" | "GOVERNANCE" | "POLICY" | "REPLAY" | "CERTIFICATION" | "SECURITY";
export type ContinuousOperationalCertificationFailure =
  | "CERTIFICATION_NOT_CONTINUOUSLY_EVALUATED"
  | "CERTIFICATION_DECISIONS_NOT_DETERMINISTIC"
  | "CERTIFICATION_LINEAGE_INCOMPLETE"
  | "CERTIFICATION_HISTORY_MUTABLE"
  | "QUALIFICATION_LOSS_NOT_IMMEDIATELY_DETECTED"
  | "CONTINUOUS_EVIDENCE_COLLECTION_NOT_OPERATIONAL"
  | "CERTIFICATION_DRIFT_NOT_DETERMINISTIC"
  | "EXTERNAL_IMPLEMENTATION_ATTESTATIONS_NOT_VALIDATED"
  | "ATTESTATION_LINEAGE_NOT_ADDITIVE"
  | "SUPERSEDING_LINEAGE_NOT_VERIFIED"
  | "OPERATIONAL_CHANGE_PROCESSING_NOT_DETERMINISTIC"
  | "UNKNOWN_CHANGE_TYPES_NOT_FAIL_CLOSED"
  | "SECURITY_CHANGES_NOT_ROUTED_TO_EXISTING_PIPELINE"
  | "REPLAY_NOT_REPRODUCIBLE"
  | "SERVICE_FAIL_CLOSED_NOT_VERIFIED"
  | "CONTINUOUS_OPERATIONAL_CERTIFICATION_NOT_CERTIFIED"
  | "GOVERNANCE_AUTHORITY_INTERNALIZED"
  | "PHASE_18_6_QUALIFICATION_NOT_VALID"
  | "NON_CONSTITUTIONAL_CERTIFICATION_WARNING";
export type ContinuousOperationalCertificationScenario = "BASELINE" | ContinuousOperationalCertificationFailure;
export type ContinuousOperationalCertificationInput = Readonly<{ scenario?: ContinuousOperationalCertificationScenario; tenant_id?: string; operator_id?: string; mission_id?: string; certification_id?: string; operation_id?: string }>;

export type ContinuousCertificationEngine = Readonly<{ engine_id: string; standing_constitutional_service: boolean; lifecycle_independent: boolean; operational_integrity_evaluated: boolean; governance_compliance_evaluated: boolean; replay_integrity_evaluated: boolean; operational_qualification_evaluated: boolean; evidence_completeness_evaluated: boolean; lineage_consistency_evaluated: boolean; implementation_attestations_evaluated: boolean; operational_changes_evaluated: boolean; deterministic_evaluation: boolean; fail_closed: boolean; governance_authority_external: boolean; integrity_hash: string }>;
export type CertificationHealthMonitor = Readonly<{ monitor_id: string; certification_freshness: boolean; evaluation_latency: boolean; evidence_availability: boolean; replay_health: boolean; lineage_integrity: boolean; certification_backlog: boolean; evaluation_failures: boolean; service_availability: boolean; evidentiary_only: boolean; integrity_hash: string }>;
export type CertificationDriftDetector = Readonly<{ detector_id: string; drift_classes: readonly CertificationDriftClass[]; deterministic_detection: boolean; unknown_drift_fails_closed: boolean; drift_detected: boolean; drift_event_refs: readonly string[]; integrity_hash: string }>;
export type ContinuousEvidenceCollector = Readonly<{ collector_id: string; operational_evidence: readonly string[]; governance_evidence: readonly string[]; replay_evidence: readonly string[]; qualification_evidence: readonly string[]; implementation_evidence: readonly string[]; dependency_evidence: readonly string[]; health_evidence: readonly string[]; certification_evidence: readonly string[]; immutable_collection: boolean; operational: boolean; integrity_hash: string }>;
export type ExternalImplementationAttestation = Readonly<{ attestation_id: string; authority_identity: string; approval_reference: string; implementation_evidence: readonly string[]; timestamp: string; cryptographic_signature: string; replay_reference: string; signature_verified: boolean; immutable: boolean; disputed: boolean; invalidated: boolean; integrity_hash: string }>;
export type AttestationValidator = Readonly<{ validator_id: string; implementation_not_assumed: boolean; attestations: readonly ExternalImplementationAttestation[]; invalidation_additive_lineage: boolean; historical_attestations_preserved: boolean; superseding_lineage_events: readonly string[]; integrity_hash: string }>;
export type OperationalChangeRecord = Readonly<{ change_id: string; operation_id: string; tenant_id: string; change_type: OperationalChangeType | "UNKNOWN_REGISTERED"; registry_version: string; affected_component: string; originating_service: string; authorizing_reference: string; evidence_reference: string; replay_reference: string; security_pipeline_routed: boolean; fail_closed: boolean; integrity_hash: string }>;
export type OperationalChangeProcessor = Readonly<{ processor_id: string; registry_versioned: boolean; registry_immutable: boolean; registry_replayable: boolean; registry_lineage_preserving: boolean; deterministic_processing: boolean; unknown_changes_fail_closed: boolean; security_changes_route_existing_pipeline: boolean; changes: readonly OperationalChangeRecord[]; integrity_hash: string }>;
export type CertificationEvent = Readonly<{ event_id: string; event_type: CertificationEventType; evaluation_outcome: CertificationEvaluationOutcome; evidence_refs: readonly string[]; replay_refs: readonly string[]; governance_refs: readonly string[]; immutable: boolean; integrity_hash: string }>;
export type CertificationEventRegistry = Readonly<{ registry_id: string; events: readonly CertificationEvent[]; qualification_loss_immediate: boolean; immutable_events: boolean; governed_events: boolean; integrity_hash: string }>;
export type CertificationLineageManager = Readonly<{ manager_id: string; strictly_additive: boolean; history_immutable: boolean; lineage_complete: boolean; supersession_events: readonly string[]; attestation_lineage: readonly string[]; integrity_hash: string }>;
export type CertificationReplayService = Readonly<{ replay_id: string; evaluations_replayed: boolean; evidence_collection_replayed: boolean; events_replayed: boolean; lineage_evolution_replayed: boolean; drift_detection_replayed: boolean; attestation_validation_replayed: boolean; supersession_replayed: boolean; fail_closed_replayed: boolean; identical_outcomes: boolean; integrity_hash: string }>;
export type ContinuousCertificationLedger = Readonly<{ ledger_id: string; evaluations: readonly string[]; certification_decisions: readonly string[]; evidence_references: readonly string[]; drift_observations: readonly string[]; attestation_lineage: readonly string[]; supersession_events: readonly string[]; replay_references: readonly string[]; integrity_verification: boolean; immutable: boolean; integrity_hash: string }>;
export type CertificationObservability = Readonly<{ observability_id: string; certification_status: boolean; certification_health: boolean; drift_indicators: boolean; evidence_completeness: boolean; lineage_health: boolean; evaluation_latency: boolean; fail_closed_status: boolean; replay_verification: boolean; state_modified: boolean; integrity_hash: string }>;
export type ContinuousOperationalCertificationPackage = Readonly<{ package_id: string; certification_continuously_evaluated: boolean; certification_decisions_deterministic: boolean; certification_lineage_complete: boolean; certification_history_immutable: boolean; qualification_loss_immediately_detected: boolean; continuous_evidence_collection_operational: boolean; certification_drift_detected_deterministically: boolean; external_implementation_attestations_validated: boolean; attestation_lineage_additive: boolean; superseding_lineage_verified: boolean; operational_change_processing_deterministic: boolean; unknown_change_types_fail_closed: boolean; security_changes_routed_to_existing_pipeline: boolean; replay_reproducible: boolean; service_fail_closed_behavior_verified: boolean; continuous_operational_certification_certified: boolean; evidence_refs: readonly string[]; integrity_hash: string }>;
export type ContinuousOperationalCertificationTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: ContinuousOperationalCertificationOutcome; passed: boolean; failure_reason: ContinuousOperationalCertificationFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;

export type ContinuousOperationalCertificationResult = Readonly<{ phase_version: "continuous-operational-certification-service/v18.7"; phase_identifier: "ContinuousOperationalCertificationService"; adaptation_qualification_ref: string; certification_engine: ContinuousCertificationEngine; health_monitor: CertificationHealthMonitor; drift_detector: CertificationDriftDetector; evidence_collector: ContinuousEvidenceCollector; attestation_validator: AttestationValidator; change_processor: OperationalChangeProcessor; event_registry: CertificationEventRegistry; lineage_manager: CertificationLineageManager; replay_service: CertificationReplayService; ledger: ContinuousCertificationLedger; observability: CertificationObservability; certification_package: ContinuousOperationalCertificationPackage; certification_tests: readonly ContinuousOperationalCertificationTest[]; failures: readonly ContinuousOperationalCertificationFailure[]; outcome: ContinuousOperationalCertificationOutcome; replay_hash: string; integrity_hash: string }>;
export type ContinuousOperationalCertificationValidation = Readonly<{ valid: boolean; outcome: ContinuousOperationalCertificationOutcome; engine_valid: boolean; health_valid: boolean; drift_valid: boolean; evidence_valid: boolean; attestation_valid: boolean; change_valid: boolean; event_valid: boolean; lineage_valid: boolean; replay_valid: boolean; ledger_valid: boolean; observability_valid: boolean; certification_package_valid: boolean; certification_valid: boolean; result_replay_valid: boolean; failures: readonly ContinuousOperationalCertificationFailure[]; integrity_hash: string }>;
export type ContinuousOperationalCertificationBundle = Readonly<{ doctrine: Readonly<{ version: "continuous-operational-certification-service/v18.7"; upstream_phase: "adaptation-qualification-service/v18.6"; lifecycle_states: readonly CertificationLifecycleState[]; evaluation_outcomes: readonly CertificationEvaluationOutcome[]; event_types: readonly CertificationEventType[]; drift_classes: readonly CertificationDriftClass[]; change_types: readonly OperationalChangeType[]; certification_outcomes: readonly ContinuousOperationalCertificationOutcome[] }>; result: ContinuousOperationalCertificationResult; validation: ContinuousOperationalCertificationValidation }>;
