export type ContinuousOptimizationOutcome = "PASS" | "CONDITIONAL_PASS" | "FAIL";
export type OptimizationPublicationState = "GENERATED" | "VALIDATED" | "GOVERNED" | "PUBLISHED" | "REVIEWED" | "ACCEPTED" | "REJECTED" | "SUPERSEDED" | "ARCHIVED";
export type OptimizationClass = "OPERATIONAL" | "EFFICIENCY" | "RESILIENCE" | "GOVERNANCE" | "PERFORMANCE" | "CAPACITY" | "CERTIFICATION";
export type CandidateSource = "OPERATIONAL_HISTORY" | "MONITORING_RESULTS" | "OPERATIONAL_LEARNING" | "PERFORMANCE_INTELLIGENCE" | "CAPACITY_INTELLIGENCE" | "CHANGE_DETECTION" | "CERTIFICATION_OBSERVATIONS";
export type OptimizationPriorityFactor = "OPERATIONAL_BENEFIT" | "GOVERNANCE_IMPACT" | "IMPLEMENTATION_COMPLEXITY" | "OPERATIONAL_RISK" | "REPLAY_IMPACT" | "CERTIFICATION_IMPACT";
export type ContinuousOptimizationFailure =
  | "OPTIMIZATION_CONTRACT_NOT_APPROVED"
  | "CANDIDATE_GENERATION_NOT_DETERMINISTIC"
  | "PRIORITIZATION_NOT_REPRODUCIBLE"
  | "RECOMMENDATION_GENERATION_NOT_DETERMINISTIC"
  | "RECOMMENDATION_EXPLAINABILITY_INCOMPLETE"
  | "GOVERNANCE_VALIDATION_NOT_ENFORCED"
  | "ADVISORY_BOUNDARY_NOT_PRESERVED"
  | "OPERATIONAL_HISTORY_MUTABLE"
  | "RECOMMENDATION_LIFECYCLE_NOT_DETERMINISTIC"
  | "EVIDENCE_LINEAGE_INCOMPLETE"
  | "REPLAY_NOT_REPRODUCIBLE"
  | "TENANT_ISOLATION_NOT_PRESERVED"
  | "CERTIFICATION_LINEAGE_NOT_MAINTAINED"
  | "GOVERNANCE_VALIDATION_BYPASSED"
  | "PHASE_18_3_LEARNING_NOT_VALID"
  | "NON_CONSTITUTIONAL_OPTIMIZATION_WARNING";
export type ContinuousOptimizationScenario = "BASELINE" | ContinuousOptimizationFailure;
export type ContinuousOptimizationInput = Readonly<{ scenario?: ContinuousOptimizationScenario; tenant_id?: string; operator_id?: string; mission_id?: string; optimization_id?: string; recommendation_id?: string }>;

export type ContinuousOptimizationContract = Readonly<{ contract_id: string; optimization_lifecycle_defined: boolean; optimization_authority_defined: boolean; recommendation_boundaries_defined: boolean; optimization_eligibility_defined: boolean; constitutional_constraints_defined: boolean; advisory_only_optimization: boolean; contract_approved: boolean; deterministic_lifecycle: boolean; governance_enforced: boolean; integrity_hash: string }>;
export type OptimizationCandidate = Readonly<{ candidate_id: string; source: CandidateSource; optimization_class: OptimizationClass; opportunity: string; evidence_refs: readonly string[]; classification_reproducible: boolean; eligible: boolean; tenant_scope: string; integrity_hash: string }>;
export type OptimizationCandidateEngine = Readonly<{ engine_id: string; discovery_deterministic: boolean; classification_reproducible: boolean; registry_complete: boolean; sources: readonly CandidateSource[]; candidates: readonly OptimizationCandidate[]; integrity_hash: string }>;
export type PriorityEvaluation = Readonly<{ priority_id: string; candidate_id: string; factors: readonly OptimizationPriorityFactor[]; operational_benefit: number; governance_impact: number; implementation_complexity: number; operational_risk: number; replay_impact: number; certification_impact: number; priority_score: number; explanation: string; replayable: boolean; integrity_hash: string }>;
export type ImprovementPrioritizer = Readonly<{ prioritizer_id: string; deterministic_prioritization: boolean; explanations_complete: boolean; replay_reproducible: boolean; evaluations: readonly PriorityEvaluation[]; priority_ledger_refs: readonly string[]; integrity_hash: string }>;
export type OptimizationRecommendation = Readonly<{ recommendation_id: string; candidate_id: string; summary: string; supporting_evidence: readonly string[]; expected_operational_benefit: string; identified_risks: readonly string[]; implementation_considerations: readonly string[]; governance_considerations: readonly string[]; certification_implications: readonly string[]; deterministic: boolean; explainable: boolean; reproducible: boolean; integrity_hash: string }>;
export type RecommendationGenerator = Readonly<{ generator_id: string; deterministic_generation: boolean; recommendations_explainable: boolean; recommendations_reproducible: boolean; recommendations: readonly OptimizationRecommendation[]; registry_complete: boolean; integrity_hash: string }>;
export type RecommendationExplainability = Readonly<{ explainability_id: string; rationale_complete: boolean; supporting_evidence_complete: boolean; operational_observations_traceable: boolean; learned_patterns_traceable: boolean; prioritization_reasoning_complete: boolean; governance_decisions_traceable: boolean; evidence_lineage_preserved: boolean; hidden_reasoning_prevented: boolean; explanation_refs: readonly string[]; integrity_hash: string }>;
export type OptimizationGovernance = Readonly<{ governance_id: string; constitutional_compliance: boolean; policy_compliance: boolean; governance_constraints: boolean; tenant_isolation: boolean; replay_compliance: boolean; certification_requirements: boolean; validation_precedes_publication: boolean; failures_block_release: boolean; decisions_replayable: boolean; integrity_hash: string }>;
export type RecommendationPublication = Readonly<{ publication_id: string; publication_states: readonly OptimizationPublicationState[]; publication_deterministic: boolean; recommendation_history_preserved: boolean; publication_replayable: boolean; recommendation_catalog_complete: boolean; implementation_readiness_published: boolean; integrity_hash: string }>;
export type RecommendationLifecycle = Readonly<{ lifecycle_id: string; states: readonly OptimizationPublicationState[]; transitions_validated: boolean; deterministic_transitions: boolean; audit_complete: boolean; rejected_recommendations_auditable: boolean; history_modified: boolean; integrity_hash: string }>;
export type OptimizationObservability = Readonly<{ dashboard_id: string; recommendation_generation_visible: boolean; optimization_throughput_visible: boolean; candidate_backlog_visible: boolean; priority_distribution_visible: boolean; governance_failures_visible: boolean; recommendation_adoption_visible: boolean; superseded_recommendations_visible: boolean; analytics_reproducible: boolean; monitoring_operational: boolean; integrity_hash: string }>;
export type OptimizationCertificationPackage = Readonly<{ package_id: string; optimization_contract_approved: boolean; candidate_generation_deterministic: boolean; improvement_prioritization_reproducible: boolean; recommendation_generation_deterministic: boolean; recommendation_explainability_complete: boolean; governance_validation_enforced: boolean; advisory_boundary_preserved: boolean; operational_history_immutable: boolean; recommendation_lifecycle_deterministic: boolean; evidence_lineage_complete: boolean; replay_reproducible: boolean; tenant_isolation_preserved: boolean; certification_lineage_maintained: boolean; continuous_optimization_certified: boolean; evidence_refs: readonly string[]; integrity_hash: string }>;
export type ContinuousOptimizationTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: ContinuousOptimizationOutcome; passed: boolean; failure_reason: ContinuousOptimizationFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;

export type ContinuousOptimizationResult = Readonly<{ phase_version: "continuous-optimization-framework/v18.4"; phase_identifier: "ContinuousOptimizationFramework"; operational_learning_ref: string; optimization_contract: ContinuousOptimizationContract; candidate_engine: OptimizationCandidateEngine; prioritizer: ImprovementPrioritizer; recommendation_generator: RecommendationGenerator; explainability: RecommendationExplainability; governance: OptimizationGovernance; publication: RecommendationPublication; lifecycle: RecommendationLifecycle; observability: OptimizationObservability; certification_package: OptimizationCertificationPackage; certification_tests: readonly ContinuousOptimizationTest[]; failures: readonly ContinuousOptimizationFailure[]; outcome: ContinuousOptimizationOutcome; replay_hash: string; integrity_hash: string }>;
export type ContinuousOptimizationValidation = Readonly<{ valid: boolean; outcome: ContinuousOptimizationOutcome; contract_valid: boolean; candidate_valid: boolean; prioritizer_valid: boolean; recommendation_valid: boolean; explainability_valid: boolean; governance_valid: boolean; publication_valid: boolean; lifecycle_valid: boolean; observability_valid: boolean; certification_package_valid: boolean; certification_valid: boolean; result_replay_valid: boolean; failures: readonly ContinuousOptimizationFailure[]; integrity_hash: string }>;
export type ContinuousOptimizationBundle = Readonly<{ doctrine: Readonly<{ version: "continuous-optimization-framework/v18.4"; upstream_phase: "operational-learning-engine/v18.3"; publication_states: readonly OptimizationPublicationState[]; optimization_classes: readonly OptimizationClass[]; candidate_sources: readonly CandidateSource[]; priority_factors: readonly OptimizationPriorityFactor[]; certification_outcomes: readonly ContinuousOptimizationOutcome[] }>; result: ContinuousOptimizationResult; validation: ContinuousOptimizationValidation }>;
