export type DashboardObservabilityStatus = "AUTHORITATIVE" | "REJECTED";
export type DashboardObservabilityValidationOutcome = "VALID" | "INVALID";
export type DashboardHealthState = "HEALTHY" | "DEGRADED" | "STALE" | "INCOMPLETE" | "UNAVAILABLE" | "MISLEADING" | "SECURITY_RESTRICTED" | "OBSERVABILITY_DEGRADED" | "CRITICAL_FAILURE" | "UNKNOWN";
export type HealthDimension = "AVAILABILITY" | "PERFORMANCE" | "RENDERING" | "FRESHNESS" | "COMPLETENESS" | "LINEAGE" | "REPLAY" | "REFERENCE_INTEGRITY" | "APPROVAL_VISIBILITY" | "CERTIFICATION_VISIBILITY" | "SECURITY_VISIBILITY" | "DETERMINISM" | "USABILITY" | "AUDITABILITY";
export type VisibilityValidationOutcome = "COMPLETE" | "COMPLETE_WITH_AUTHORIZED_REDACTION" | "INCOMPLETE" | "OVEREXPOSED" | "MISLEADING" | "POLICY_CONFLICT" | "VALIDATION_FAILED";
export type FreshnessState = "CURRENT" | "NEAR_STALE" | "STALE" | "SEVERELY_STALE" | "SOURCE_DELAYED" | "CACHE_STALE" | "SYNCHRONIZATION_FAILED" | "UNKNOWN";
export type LineageState = "COMPLETE" | "PARTIAL" | "BROKEN" | "ORPHANED" | "VERSION_MISMATCH" | "CROSS_TENANT_VIOLATION" | "INTEGRITY_FAILURE";
export type ReplayAvailabilityState = "READY" | "PARTIAL" | "MISSING" | "DIVERGED" | "VERSION_MISMATCH" | "AUTHORIZATION_BLOCKED" | "ENGINE_UNAVAILABLE" | "INTEGRITY_FAILURE";
export type ReferenceState = "VALID" | "VALID_REDACTED" | "SUPERSEDED" | "BROKEN" | "UNAUTHORIZED" | "VERSION_MISMATCH" | "CROSS_TENANT" | "UNKNOWN";
export type ApprovalVisibilityState = "COMPLETE" | "CONDITIONALLY_COMPLETE" | "INCOMPLETE" | "MISREPRESENTED" | "AUTHORITY_INVALID" | "VERSION_INVALID" | "UNKNOWN";
export type CertificationVisibilityState = "COMPLETE" | "INCOMPLETE" | "MISREPRESENTED" | "EXPIRED" | "REVOKED" | "VERSION_MISMATCH" | "MISSING" | "UNKNOWN";
export type WidgetState = "HEALTHY" | "DEGRADED" | "STALE" | "PARTIAL" | "FAILED" | "UNAUTHORIZED" | "MISCONFIGURED" | "UNREGISTERED";
export type AlertSeverity = "INFORMATIONAL" | "LOW" | "MODERATE" | "HIGH" | "CRITICAL";
export type AlertLifecycleState = "DETECTED" | "OPEN" | "ACKNOWLEDGED" | "UNDER_INVESTIGATION" | "REMEDIATION_REQUIRED" | "RESOLVED" | "VERIFIED" | "SUPERSEDED";
export type IncidentType = "DASHBOARD_OUTAGE" | "RENDERING_OUTAGE" | "STALE_DATA" | "MISSING_GOVERNANCE_DATA" | "CERTIFICATION_VISIBILITY" | "REPLAY_LOSS" | "LINEAGE_INTEGRITY" | "SECURITY_EXPOSURE" | "CROSS_TENANT_VISIBILITY" | "MISLEADING_STATUS" | "OBSERVABILITY_SYSTEM";
export type ReportState = "HEALTHY" | "DEGRADED" | "ACTION_REQUIRED" | "CERTIFICATION_BLOCKED" | "GOVERNANCE_REVIEW_REQUIRED" | "CRITICAL";
export type DashboardObservabilityWidget = "Metrics" | "Usage Analytics" | "Visibility Validator" | "Performance Monitor" | "Freshness Monitor" | "Lineage Monitor" | "Replay Monitor" | "Reference Monitor" | "Approval Monitor" | "Certification Monitor" | "Widget Health" | "Navigation Health" | "Health Evaluator" | "Alert Manager" | "Incident Registry" | "Dashboard Ledger" | "Health Reports" | "Observability Console";

export type DashboardObservabilityScenario =
  | "BASELINE" | "METRICS_COLLECTION_FAILED" | "SOURCE_VALIDATION_FAILED" | "DASHBOARD_CAPTURE_FAILED" | "RENDERING_FAILED" | "LATENCY_DEGRADED" | "STALE_DASHBOARD" | "CACHE_STALE" | "MISSING_LINEAGE" | "BROKEN_LINEAGE" | "CROSS_TENANT_LINEAGE" | "MISSING_REPLAY" | "REPLAY_DIVERGED" | "REPLAY_ENGINE_UNAVAILABLE" | "BROKEN_REFERENCE" | "UNAUTHORIZED_REFERENCE" | "MISSING_APPROVAL" | "HIDDEN_REJECTION" | "EXPIRED_APPROVAL" | "MISSING_CERTIFICATION" | "CERTIFICATION_MISREPRESENTED" | "CONDITIONAL_PASS_AS_PASS" | "WIDGET_FAILED" | "NAVIGATION_BROKEN" | "SECURITY_VISIBILITY_FAILURE" | "ALERT_DELIVERY_FAILED" | "LEDGER_WRITE_FAILED" | "OBSERVABILITY_AUTH_FAILED" | "INTEGRITY_FAILURE" | "UNKNOWN_HEALTH";

export type DashboardObservabilityFailure =
  | "METRICS_COLLECTION_FAILED" | "SOURCE_STATE_VALIDATION_FAILED" | "DASHBOARD_STATE_CAPTURE_FAILED" | "RENDERING_FAILURE_DETECTED" | "LATENCY_THRESHOLD_EXCEEDED" | "DASHBOARD_STATE_STALE" | "CACHE_STATE_STALE" | "LINEAGE_REFERENCE_MISSING" | "LINEAGE_EDGE_BROKEN" | "CROSS_TENANT_LINEAGE_DETECTED" | "REPLAY_REFERENCE_MISSING" | "REPLAY_OUTPUT_DIVERGED" | "REPLAY_ENGINE_UNAVAILABLE" | "REFERENCE_BROKEN" | "REFERENCE_UNAUTHORIZED" | "APPROVAL_VISIBILITY_INCOMPLETE" | "APPROVAL_REJECTION_HIDDEN" | "APPROVAL_EXPIRED_MISSHOWN" | "CERTIFICATION_VISIBILITY_MISSING" | "CERTIFICATION_STATE_MISREPRESENTED" | "CONDITIONAL_PASS_MISREPRESENTED" | "MANDATORY_WIDGET_UNHEALTHY" | "NAVIGATION_HEALTH_BROKEN" | "SECURITY_VISIBILITY_FAILURE" | "ALERT_DELIVERY_FAILED" | "LEDGER_WRITE_FAILED" | "OBSERVABILITY_AUTHORIZATION_FAILED" | "INTEGRITY_VERIFICATION_FAILED" | "UNKNOWN_HEALTH_STATE";

export type DashboardObservabilityRecord = Readonly<{ observability_record_id: string; tenant_id: string; mission_scope: string; dashboard_view: string; dashboard_instance_id: string; dashboard_version: string; observation_timestamp: string; availability_status: DashboardHealthState; latency_metrics: readonly string[]; rendering_status: DashboardHealthState; freshness_status: FreshnessState; lineage_status: LineageState; replay_status: ReplayAvailabilityState; reference_status: ReferenceState; approval_visibility_status: ApprovalVisibilityState; certification_visibility_status: CertificationVisibilityState; security_visibility_status: DashboardHealthState; widget_health: readonly string[]; navigation_health: DashboardHealthState; source_state_refs: readonly string[]; dashboard_state_ref: string; detected_anomalies: readonly DashboardObservabilityFailure[]; alert_refs: readonly string[]; incident_refs: readonly string[]; replay_refs: readonly string[]; current_health_status: DashboardHealthState; integrity_hash: string }>;
export type DashboardMetricsService = Readonly<{ service_id: string; availability_rate: number; request_volume: number; successful_renders: number; failed_renders: number; partial_renders: number; p50_latency_ms: number; p95_latency_ms: number; p99_latency_ms: number; stale_data_count: number; broken_reference_count: number; missing_lineage_count: number; missing_replay_count: number; approval_incompleteness_count: number; certification_incompleteness_count: number; authorization_denial_count: number; integrity_failure_count: number; tenant_aware: boolean; mission_aware: boolean; deterministic: boolean; integrity_hash: string }>;
export type DashboardUsageAnalytics = Readonly<{ analytics_id: string; dashboard_views: number; replay_launches: number; lineage_navigation_count: number; evidence_inspections: number; approval_queue_interactions: number; certification_queue_interactions: number; time_to_required_information_ms: number; aggregate_privacy_preserved: boolean; behavioral_ranking_present: false; advisory_only: true; integrity_hash: string }>;
export type DashboardVisibilityValidator = Readonly<{ validator_id: string; outcome: VisibilityValidationOutcome; required_records_visible: boolean; required_blockers_visible: boolean; approvals_visible: boolean; certification_visible: boolean; rollback_visible: boolean; replay_refs_visible: boolean; lineage_paths_visible: boolean; unauthorized_overexposure_detected: boolean; misleading_summary_detected: boolean; integrity_hash: string }>;
export type DashboardPerformanceMonitor = Readonly<{ monitor_id: string; initial_load_latency_ms: number; full_render_latency_ms: number; widget_render_latency_ms: number; search_latency_ms: number; replay_navigation_latency_ms: number; lineage_graph_latency_ms: number; error_rate: number; timeout_rate: number; optimization_preserves_governed_data: boolean; integrity_hash: string }>;
export type DashboardFreshnessMonitor = Readonly<{ monitor_id: string; state: FreshnessState; source_record_timestamp: string; dashboard_refresh_timestamp: string; cache_timestamp: string; governance_update_timestamp: string; approval_update_timestamp: string; certification_update_timestamp: string; stale_status_visible: boolean; integrity_hash: string }>;
export type LineageIntegrityMonitor = Readonly<{ monitor_id: string; state: LineageState; missing_nodes: number; broken_edges: number; orphaned_records: number; cyclic_lineage_detected: boolean; cross_tenant_lineage_detected: boolean; version_mismatches: number; integrity_hash: string }>;
export type ReplayAvailabilityMonitor = Readonly<{ monitor_id: string; state: ReplayAvailabilityState; replay_refs_present: boolean; package_complete: boolean; engine_available: boolean; event_order_reproducible: boolean; output_hash_reproducible: boolean; authorization_compatible: boolean; integrity_hash: string }>;
export type ReferenceIntegrityMonitor = Readonly<{ monitor_id: string; state: ReferenceState; broken_links: number; unauthorized_targets: number; superseded_targets: number; malformed_references: number; circular_navigation: boolean; cross_tenant_links: number; integrity_hash: string }>;
export type ApprovalCompletenessMonitor = Readonly<{ monitor_id: string; state: ApprovalVisibilityState; required_approvals: number; completed_approvals: number; hidden_rejections: number; unmet_conditions: number; expired_approvals_shown_valid: number; revoked_approvals_shown_valid: number; authority_mismatches: number; integrity_hash: string }>;
export type CertificationCompletenessMonitor = Readonly<{ monitor_id: string; state: CertificationVisibilityState; required_gate_visible: boolean; completed_tests_visible: boolean; failed_tests_visible: boolean; conditional_findings_visible: boolean; conditional_pass_as_pass: boolean; expired_shown_current: boolean; revoked_omitted: boolean; evidence_package_visible: boolean; integrity_hash: string }>;
export type WidgetHealthMonitor = Readonly<{ monitor_id: string; mandatory_widget_states: readonly string[]; all_mandatory_healthy: boolean; accessibility_state_valid: boolean; replay_integration_valid: boolean; integrity_hash: string }>;
export type NavigationHealthMonitor = Readonly<{ monitor_id: string; route_resolution_valid: boolean; deep_links_valid: boolean; breadcrumb_accuracy: boolean; replay_position_preserved: boolean; filter_state_preserved: boolean; tenant_context_preserved: boolean; authorization_revalidated: boolean; integrity_hash: string }>;
export type DashboardHealthEvaluation = Readonly<{ evaluation_id: string; health: DashboardHealthState; dimensions: readonly string[]; most_severe_dimension: HealthDimension; unknown_treated_unhealthy: boolean; average_does_not_hide_critical: boolean; integrity_hash: string }>;
export type DashboardAlert = Readonly<{ alert_id: string; category: DashboardObservabilityFailure; severity: AlertSeverity; lifecycle_state: AlertLifecycleState; routed_to: readonly string[]; dedupe_key: string; critical_auto_closed: false; resolution_requires_verification: boolean; integrity_hash: string }>;
export type DashboardIncident = Readonly<{ incident_id: string; tenant_id: string; mission_scope: string; dashboard_view: string; incident_type: IncidentType; severity: AlertSeverity; detected_at: string; source_alert_refs: readonly string[]; affected_records: readonly string[]; affected_roles: readonly string[]; user_impact: string; governance_impact: string; certification_impact: string; containment_status: string; remediation_status: string; resolution_refs: readonly string[]; replay_refs: readonly string[]; closed_at: string | null; integrity_hash: string }>;
export type DashboardObservabilityLedger = Readonly<{ ledger_id: string; health_evaluation_refs: readonly string[]; metric_snapshot_refs: readonly string[]; alert_history_refs: readonly string[]; incident_history_refs: readonly string[]; append_only: true; immutable: true; tenant_isolated: boolean; replayable: boolean; hash_verified: boolean; governance_accessible: boolean; certification_accessible: boolean; integrity_hash: string }>;
export type DashboardHealthReport = Readonly<{ report_id: string; state: ReportState; summary: string; evidence_refs: readonly string[]; replay_refs: readonly string[]; reproducible: boolean; integrity_verified: boolean; integrity_hash: string }>;
export type DashboardObservabilityConsole = Readonly<{ console_id: string; health_summary_visible: boolean; current_incidents_visible: boolean; active_alerts_visible: boolean; filtering_supported: boolean; incident_inspection_supported: boolean; replay_launch_supported: boolean; lineage_inspection_supported: boolean; source_records_mutable: false; integrity_hash: string }>;
export type DashboardObservabilityApiSurface = Readonly<{ api_id: string; retrieve_dashboard: string; retrieve_contract: string; retrieve_sections: readonly string[]; validate_observability: string; inspect_observability: string; mutation_supported: false; source_repair_supported: false; approval_supported: false; certification_mutation_supported: false; incident_suppression_supported: false; production_adaptation_mutation_supported: false; integrity_hash: string }>;
export type DashboardObservabilityInput = Readonly<{ scenario?: DashboardObservabilityScenario; tenant_id?: string; mission_scope?: string; dashboard_view?: string }>;
export type DashboardObservabilityResult = Readonly<{ dashboard_observability_version: "dashboard-observability/v10.14.11"; observability_identifier: "DashboardObservability"; status: DashboardObservabilityStatus; api_surface: DashboardObservabilityApiSurface; record: DashboardObservabilityRecord; metrics_service: DashboardMetricsService; usage_analytics: DashboardUsageAnalytics; visibility_validator: DashboardVisibilityValidator; performance_monitor: DashboardPerformanceMonitor; freshness_monitor: DashboardFreshnessMonitor; lineage_monitor: LineageIntegrityMonitor; replay_monitor: ReplayAvailabilityMonitor; reference_monitor: ReferenceIntegrityMonitor; approval_monitor: ApprovalCompletenessMonitor; certification_monitor: CertificationCompletenessMonitor; widget_monitor: WidgetHealthMonitor; navigation_monitor: NavigationHealthMonitor; health_evaluation: DashboardHealthEvaluation; alerts: readonly DashboardAlert[]; incidents: readonly DashboardIncident[]; ledger: DashboardObservabilityLedger; health_report: DashboardHealthReport; console: DashboardObservabilityConsole; widgets: readonly DashboardObservabilityWidget[]; validation_tests: readonly DashboardObservabilityValidationTest[]; validation_outcome: DashboardObservabilityValidationOutcome; failures: readonly DashboardObservabilityFailure[]; deterministic: boolean; read_only: true; advisory_only: true; tenant_isolated: boolean; observability_degradation_visible: boolean; replay_hash: string; integrity_hash: string }>;
export type DashboardObservabilityValidationTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: "PASS" | "FAIL"; passed: boolean; failure_reason: DashboardObservabilityFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;
export type DashboardObservabilityValidationResult = Readonly<{ observability_id: string | null; valid: boolean; validation_outcome: DashboardObservabilityValidationOutcome; failures: readonly DashboardObservabilityFailure[]; replay_hash_valid: boolean; integrity_hash_valid: boolean; read_only: boolean; validation_hash: string }>;
export type DashboardObservabilitySurface = Readonly<{ observability_id: string; status: DashboardObservabilityStatus; validation_outcome: DashboardObservabilityValidationOutcome; health: DashboardHealthState; failed_tests: number; failures: readonly DashboardObservabilityFailure[]; tenant_isolated: boolean; observability_degradation_visible: boolean; integrity_hash: string }>;
export type DashboardObservabilityContract = Readonly<{ doctrine: Readonly<{ version: "dashboard-observability/v10.14.11"; widgets: readonly DashboardObservabilityWidget[]; health_states: readonly DashboardHealthState[]; health_dimensions: readonly HealthDimension[]; freshness_states: readonly FreshnessState[]; lineage_states: readonly LineageState[]; replay_states: readonly ReplayAvailabilityState[]; reference_states: readonly ReferenceState[]; approval_states: readonly ApprovalVisibilityState[]; certification_states: readonly CertificationVisibilityState[]; alert_lifecycle: readonly AlertLifecycleState[]; required_integrations: readonly string[]; read_only: true; advisory_only: true }>; result: DashboardObservabilityResult; validation: DashboardObservabilityValidationResult; observability: DashboardObservabilitySurface }>;
