export type DecisionSupportDecision = "MISSION_DECISION_SUPPORT_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type AdvisoryStatus = "DRAFT" | "GATE_PASSED" | "PUBLISHED" | "REJECTED";
export type DecisionSupportFailure =
  | "MC_1_MISSION_MANAGEMENT_INVALID" | "MC_2_SCENARIO_PLANNING_INVALID" | "W2_EVIDENCE_INVALID" | "W2_REPLAY_INVALID" | "W2_CERTIFICATION_INVALID" | "W2_POLICY_INVALID" | "W2_AUTHORITY_INVALID" | "W2_SAFETY_INVALID" | "W2_PLANNING_INVALID" | "W2_MEMORY_INVALID" | "W2_COLLABORATION_INVALID" | "W2_DELEGATION_INVALID" | "W2_RUNTIME_INVALID"
  | "DECISION_ENGINE_MISSING" | "RECOMMENDATION_GENERATION_MISSING" | "RECOMMENDATION_RANKING_NON_DETERMINISTIC" | "CONSTITUTIONAL_FILTERING_BYPASSED" | "TRADEOFF_ANALYSIS_MISSING" | "TRADEOFF_MATRIX_NON_DETERMINISTIC" | "MULTI_CRITERIA_EVALUATION_MISSING" | "WEIGHTED_SCORING_NON_DETERMINISTIC" | "MANDATORY_CONSTRAINTS_BYPASSED" | "EVIDENCE_AGGREGATION_MISSING" | "EVIDENCE_LINEAGE_INCOMPLETE" | "EVIDENCE_CONFIDENCE_MISSING" | "JUSTIFICATION_MISSING" | "RECOMMENDATION_NOT_EXPLAINABLE" | "REJECTED_ALTERNATIVES_MISSING" | "MISSION_ADVISORY_GATE_MISSING" | "MISSION_ADVISORY_GATE_FAILED" | "OUTPUT_PUBLISHED_WITHOUT_GATE" | "OPERATIONAL_DECISION_ATTEMPTED" | "MISSION_EXECUTION_ATTEMPTED" | "OPERATOR_SUPREMACY_BYPASSED" | "DECISION_PACKAGE_MISSING" | "RECOMMENDATION_REPORT_MISSING" | "TRADEOFF_REPORT_MISSING" | "EVIDENCE_BUNDLE_MISSING" | "JUSTIFICATION_REPORT_MISSING" | "AUDIT_EVIDENCE_MISSING" | "AUDIT_EVIDENCE_NOT_IMMUTABLE" | "DETERMINISTIC_REPLAY_FAILED" | "DECISION_SUPPORT_QUALIFICATION_FAILED";
export type DecisionSupportScenario = "BASELINE" | "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | DecisionSupportFailure;
export type DecisionSupportInput = Readonly<{ scenario?: DecisionSupportScenario; seed?: string; mission_id?: string; tenant_id?: string; decision_id?: string }>;
export type DecisionEngine = Readonly<{ engine_id: string; recommendation_generation: boolean; alternative_ranking: boolean; recommendation_scoring: boolean; decision_normalization: boolean; constitutional_filtering: boolean; objectives: boolean; constraints: boolean; scenarios: boolean; evidence: boolean; policy: boolean; authority: boolean; historical_outcomes: boolean; ranked_recommendations: boolean; deterministic: boolean; advisory_only: boolean; integrity_hash: string }>;
export type TradeoffAnalyzer = Readonly<{ analyzer_id: string; compare_alternatives: boolean; identify_compromises: boolean; sensitivity_analysis: boolean; objective_comparison: boolean; cost: boolean; schedule: boolean; risk: boolean; confidence: boolean; mission_value: boolean; operational_impact: boolean; resource_usage: boolean; probability_of_success: boolean; comparative_tradeoff_matrix: boolean; deterministic_matrix: boolean; integrity_hash: string }>;
export type MultiCriteriaEvaluator = Readonly<{ evaluator_id: string; weighted_objectives: boolean; mandatory_constraints: boolean; mission_priorities: boolean; policy_restrictions: boolean; authority_restrictions: boolean; weighted_scoring: boolean; objective_normalization: boolean; constraint_evaluation: boolean; ranking: boolean; normalized_scoring: boolean; deterministic_rankings: boolean; integrity_hash: string }>;
export type EvidenceAggregator = Readonly<{ aggregator_id: string; scenarios: boolean; simulations: boolean; execution_history: boolean; replay: boolean; certification: boolean; operational_evidence: boolean; external_evidence_sources: boolean; evidence_collection: boolean; lineage_validation: boolean; confidence_aggregation: boolean; evidence_completeness: boolean; unified_evidence_package: boolean; integrity_hash: string }>;
export type DecisionJustification = Readonly<{ service_id: string; recommendation_explanations: boolean; evidence_mapping: boolean; rationale_generation: boolean; traceability: boolean; supporting_evidence: boolean; rejected_alternatives: boolean; assumptions: boolean; constraints: boolean; constitutional_checks: boolean; confidence: boolean; risk_summary: boolean; justification_report: boolean; explainable: boolean; integrity_hash: string }>;
export type MissionAdvisoryGate = Readonly<{ gate_id: string; mission_constitutional_compliance: boolean; mission_lifecycle_validity: boolean; authority_validation: boolean; policy_compliance: boolean; safety_compliance: boolean; evidence_completeness: boolean; evidence_provenance: boolean; recommendation_explainability: boolean; justification_completeness: boolean; confidence_thresholds: boolean; traceability: boolean; audit_readiness: boolean; failed_outputs_not_published: boolean; gate_passed: boolean; integrity_hash: string }>;
export type DecisionArtifacts = Readonly<{ artifact_id: string; decision_package: boolean; recommendation_report: boolean; tradeoff_report: boolean; evidence_bundle: boolean; decision_justification_report: boolean; mission_id: string; decision_id: string; advisory_status: AdvisoryStatus; evidence_references: readonly string[]; confidence_score: number; tradeoff_summary: boolean; recommendation_ranking: boolean; constitutional_review: boolean; authority_review: boolean; policy_review: boolean; safety_review: boolean; mission_lifecycle_state: string; advisory_timestamp: string; immutable_lineage_id: string; integrity_hash: string }>;
export type DecisionSupportGovernance = Readonly<{ governance_id: string; recommendations_only: boolean; never_executes_mission_actions: boolean; preserves_operator_supremacy: boolean; deterministic_recommendations: boolean; explainable_recommendations: boolean; complete_evidence_lineage: boolean; immutable_audit_evidence: boolean; rejects_insufficient_evidence: boolean; rejects_constitutional_violations: boolean; requires_gate_before_publication: boolean; integrity_hash: string }>;
export type DecisionSupportReadiness = Readonly<{ readiness_id: string; decision: DecisionSupportDecision; phase_ready: boolean; upstream_ready: boolean; decision_engine_ready: boolean; tradeoff_ready: boolean; multi_criteria_ready: boolean; evidence_ready: boolean; justification_ready: boolean; advisory_gate_ready: boolean; artifacts_ready: boolean; governance_ready: boolean; replay_reproducible: boolean; advisory_only: boolean; operator_supremacy_preserved: boolean; qualification_ready: boolean; failures: readonly DecisionSupportFailure[]; integrity_hash: string }>;
export type DecisionSupportResult = Readonly<{ phase_version: "decision-support/mc-3"; phase_identifier: "DecisionSupport"; upstream_refs: readonly string[]; mission_id: string; tenant_id: string; decision_engine: DecisionEngine; tradeoff_analyzer: TradeoffAnalyzer; multi_criteria: MultiCriteriaEvaluator; evidence_aggregator: EvidenceAggregator; justification: DecisionJustification; advisory_gate: MissionAdvisoryGate; artifacts: DecisionArtifacts; governance: DecisionSupportGovernance; readiness: DecisionSupportReadiness; replay_hash: string; integrity_hash: string }>;
export type DecisionSupportValidation = Readonly<{ valid: boolean; decision: DecisionSupportDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; decision_engine_valid: boolean; tradeoff_valid: boolean; multi_criteria_valid: boolean; evidence_valid: boolean; justification_valid: boolean; advisory_gate_valid: boolean; artifacts_valid: boolean; governance_valid: boolean; readiness_valid: boolean; failures: readonly DecisionSupportFailure[]; integrity_hash: string }>;
export type DecisionSupportBundle = Readonly<{ doctrine: Readonly<{ version: "decision-support/mc-3"; owns_decision_engine: true; owns_tradeoff_analysis: true; owns_multi_criteria_evaluation: true; owns_evidence_aggregation: true; owns_decision_justification: true; owns_mission_advisory_gate: true; produces_advisory_outputs_only: true; never_makes_operational_decisions: true; qualification_gate: "Mission Advisory Gate" }>; result: DecisionSupportResult; validation: DecisionSupportValidation }>;
