export type DelegationEngineDecision = "DELEGATION_ENGINE_OPERATIONAL" | "CONDITIONALLY_OPERATIONAL" | "NOT_OPERATIONAL" | "FAIL_CLOSED";
export type DelegationLifecycleState = "Proposed" | "Validated" | "Approved" | "Active" | "Suspended" | "Revoked" | "Expired" | "Archived";
export type DelegationEngineFailure =
  | "W2_0_CAF_CONSTITUTION_INVALID" | "W2_1_AGENT_REGISTRY_INVALID" | "W2_2_LIFECYCLE_ENGINE_INVALID" | "W2_3_CAPABILITY_REGISTRY_INVALID" | "W2_4_SKILL_REGISTRY_INVALID" | "W2_5_AUTHORITY_VALIDATOR_INVALID" | "W2_6_POLICY_GATE_INVALID" | "W2_7_SAFETY_GATE_INVALID" | "W2_8_PLANNING_ENGINE_INVALID" | "W2_9_MEMORY_ENGINE_INVALID" | "W2_10_RUNTIME_ORCHESTRATOR_INVALID"
  | "DELEGATION_CONTRACTS_MISSING" | "DELEGATION_CONTRACT_INVALID" | "DELEGATION_SCOPE_AMBIGUOUS" | "DELEGATION_EVIDENCE_MISSING"
  | "AUTHORITY_INTERSECTION_MISSING" | "AUTHORITY_ELEVATION_ALLOWED" | "POLICY_RESTRICTION_BYPASSED" | "SAFETY_RESTRICTION_BYPASSED" | "RUNTIME_RESTRICTION_BYPASSED" | "TENANT_RESTRICTION_BYPASSED"
  | "DELEGATION_LIFECYCLE_MISSING" | "INVALID_LIFECYCLE_TRANSITION_ALLOWED" | "DELEGATION_VALIDATION_INCOMPLETE"
  | "REVOCATION_ENGINE_MISSING" | "REVOCATION_NOT_IMMEDIATE" | "CASCADE_REVOCATION_FAILED" | "REVOKED_DELEGATION_RETAINS_AUTHORITY"
  | "DELEGATION_MONITORING_MISSING" | "AUTHORITY_DRIFT_UNDETECTED" | "EXPIRED_DELEGATION_UNDETECTED" | "DELEGATION_CHAIN_DEPTH_UNDETECTED"
  | "DELEGATION_LINEAGE_MISSING" | "DELEGATION_LINEAGE_NOT_IMMUTABLE" | "DELEGATION_GOVERNANCE_MISSING" | "PRIVILEGE_ESCALATION_ALLOWED" | "CROSS_TENANT_DELEGATION_ALLOWED" | "POLICY_BYPASS_ALLOWED"
  | "RUNTIME_DELEGATION_INTEGRATION_MISSING" | "DELEGATED_ACTION_NOT_VALIDATED" | "DELEGATION_API_MISSING" | "DELEGATION_EVIDENCE_NOT_IMMUTABLE" | "DELEGATION_REPLAY_INVALID" | "DELEGATION_ENGINE_OPERATIONAL_GATE_FAILED";
export type DelegationEngineScenario = "BASELINE" | "OPERATIONAL_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | DelegationEngineFailure;
export type DelegationEngineInput = Readonly<{ scenario?: DelegationEngineScenario; seed?: string }>;
export type DelegationContracts = Readonly<{ registry_id: string; contract_schema: boolean; delegation_scope: boolean; constraints: boolean; duration: boolean; conditions: boolean; evidence: boolean; metadata: boolean; delegator: boolean; delegate: boolean; authority_granted: boolean; capabilities_granted: boolean; restrictions: boolean; expiration: boolean; revocation_policy: boolean; contract_validator: boolean; integrity_hash: string }>;
export type AuthorityIntersectionEngine = Readonly<{ engine_id: string; delegator_authority: boolean; delegate_eligibility: boolean; policy_restrictions: boolean; safety_restrictions: boolean; runtime_restrictions: boolean; tenant_restrictions: boolean; minimum_constitutional_authority: boolean; no_authority_elevation: boolean; effective_authority_evidence: boolean; deterministic_resolution: boolean; integrity_hash: string }>;
export type DelegationLifecycleManager = Readonly<{ manager_id: string; states: readonly DelegationLifecycleState[]; authority_verification: boolean; policy_verification: boolean; safety_verification: boolean; runtime_verification: boolean; capability_verification: boolean; transitions_enforced: boolean; lifecycle_history: boolean; auditable: boolean; integrity_hash: string }>;
export type RevocationEngine = Readonly<{ engine_id: string; operator_source: boolean; policy_source: boolean; safety_source: boolean; authority_source: boolean; runtime_source: boolean; lifecycle_source: boolean; expiration_source: boolean; trust_degradation_source: boolean; parent_revocation_source: boolean; immediate_termination: boolean; cascading_revocation: boolean; task_cancellation: boolean; capability_removal: boolean; runtime_notification: boolean; audit_recording: boolean; integrity_hash: string }>;
export type DelegationMonitoring = Readonly<{ monitor_id: string; authority_validity: boolean; policy_compliance: boolean; safety_compliance: boolean; runtime_compliance: boolean; expiration: boolean; capability_usage: boolean; abnormal_behavior: boolean; delegation_chains: boolean; authority_drift_alerts: boolean; expired_alerts: boolean; policy_violation_alerts: boolean; safety_violation_alerts: boolean; runtime_violation_alerts: boolean; depth_alerts: boolean; continuous: boolean; integrity_hash: string }>;
export type DelegationLineage = Readonly<{ graph_id: string; delegator: boolean; delegate: boolean; authority_changes: boolean; revocations: boolean; renewals: boolean; delegation_chain: boolean; execution_lineage: boolean; timeline: boolean; immutable_history: boolean; evidence: boolean; integrity_hash: string }>;
export type DelegationGovernance = Readonly<{ rules_id: string; no_authority_elevation: boolean; no_policy_bypass: boolean; no_safety_bypass: boolean; tenant_isolation: boolean; fully_auditable: boolean; immutable_evidence_required: boolean; explainable: boolean; revoked_authority_removed_immediately: boolean; compliance_report: boolean; integrity_hash: string }>;
export type RuntimeDelegationIntegration = Readonly<{ adapter_id: string; runtime_orchestrator_integration: boolean; planning_engine_integration: boolean; authority_validator_integration: boolean; policy_gate_integration: boolean; safety_gate_integration: boolean; verify_before_execution: boolean; enforce_restrictions: boolean; validate_expiration: boolean; validate_revocation_status: boolean; validate_runtime_eligibility: boolean; enforcement_api: boolean; integrity_hash: string }>;
export type DelegationApis = Readonly<{ api_id: string; create_delegation: boolean; validate_contract: boolean; resolve_authority: boolean; approve_delegation: boolean; suspend_delegation: boolean; revoke_delegation: boolean; list_delegations: boolean; inspect_lineage: boolean; monitor_delegation: boolean; verify_runtime_delegation: boolean; replay_delegation: boolean; stable: boolean; integrity_hash: string }>;
export type DelegationEvidence = Readonly<{ ledger_id: string; records: readonly string[]; contract_evidence: boolean; authority_resolution_evidence: boolean; lifecycle_evidence: boolean; revocation_evidence: boolean; monitoring_evidence: boolean; lineage_evidence: boolean; governance_evidence: boolean; runtime_enforcement_evidence: boolean; immutable: boolean; replayable: boolean; integrity_hash: string }>;
export type DelegationEngineReadiness = Readonly<{ readiness_id: string; decision: DelegationEngineDecision; phase_ready: boolean; constitution_ready: boolean; agent_registry_ready: boolean; lifecycle_engine_ready: boolean; capability_registry_ready: boolean; skill_registry_ready: boolean; authority_validator_ready: boolean; policy_gate_ready: boolean; safety_gate_ready: boolean; planning_engine_ready: boolean; memory_engine_ready: boolean; runtime_orchestrator_ready: boolean; contracts_ready: boolean; authority_intersection_ready: boolean; lifecycle_ready: boolean; revocation_ready: boolean; monitoring_ready: boolean; lineage_ready: boolean; governance_ready: boolean; runtime_integration_ready: boolean; apis_ready: boolean; evidence_ready: boolean; no_elevation: boolean; immediate_revocation: boolean; tenant_isolation_preserved: boolean; failures: readonly DelegationEngineFailure[]; integrity_hash: string }>;
export type DelegationEngineResult = Readonly<{ phase_version: "delegation-engine/w2.11"; phase_identifier: "DelegationEngine"; caf_constitution_ref: "caf-constitutional-foundation/w2.0"; agent_registry_ref: "agent-registry/w2.1"; lifecycle_engine_ref: "lifecycle-engine/w2.2"; capability_registry_ref: "capability-registry/w2.3"; skill_registry_ref: "skill-registry/w2.4"; authority_validator_ref: "authority-validator/w2.5"; policy_gate_ref: "policy-gate/w2.6"; safety_gate_ref: "safety-gate/w2.7"; planning_engine_ref: "planning-engine/w2.8"; memory_engine_ref: "memory-engine/w2.9"; runtime_orchestrator_ref: "runtime-orchestrator/w2.10"; contracts: DelegationContracts; authority_intersection: AuthorityIntersectionEngine; lifecycle: DelegationLifecycleManager; revocation: RevocationEngine; monitoring: DelegationMonitoring; lineage: DelegationLineage; governance: DelegationGovernance; runtime_integration: RuntimeDelegationIntegration; apis: DelegationApis; evidence: DelegationEvidence; readiness: DelegationEngineReadiness; replay_hash: string; integrity_hash: string }>;
export type DelegationEngineValidation = Readonly<{ valid: boolean; decision: DelegationEngineDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; contracts_valid: boolean; authority_intersection_valid: boolean; lifecycle_valid: boolean; revocation_valid: boolean; monitoring_valid: boolean; lineage_valid: boolean; governance_valid: boolean; runtime_integration_valid: boolean; apis_valid: boolean; evidence_valid: boolean; readiness_valid: boolean; failures: readonly DelegationEngineFailure[]; integrity_hash: string }>;
export type DelegationEngineBundle = Readonly<{ doctrine: Readonly<{ version: "delegation-engine/w2.11"; owns_delegation_contracts: true; owns_authority_intersection: true; owns_delegation_lifecycle: true; owns_revocation: true; owns_delegation_monitoring: true; owns_delegation_lineage: true; owns_delegation_governance: true; owns_runtime_delegation: true; owns_delegation_evidence: true; prevents_authority_elevation: true; operational_gate: "Delegation Engine Operational Gate" }>; result: DelegationEngineResult; validation: DelegationEngineValidation }>;
