export type DigitalTwinDecision = "DIGITAL_TWIN_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type TwinNodeKind = "MISSION" | "PORTFOLIO" | "OBJECTIVE" | "DECISION" | "RESOURCE" | "EVIDENCE" | "OPERATOR" | "DEPENDENCY";
export type TwinEdgeKind = "OWNERSHIP" | "DEPENDENCY" | "EXECUTION" | "LINEAGE" | "EVIDENCE" | "ASSIGNMENT" | "AUTHORITY";
export type SynchronizationStatus = "SYNCHRONIZED" | "DIVERGED" | "RECONCILING" | "FAILED";
export type DigitalTwinFailure =
  | "MC_1_MISSION_MANAGEMENT_INVALID" | "MC_2_SCENARIO_PLANNING_INVALID" | "MC_3_DECISION_SUPPORT_INVALID" | "MC_4_PORTFOLIO_MANAGEMENT_INVALID" | "MC_5_OPERATIONAL_EVIDENCE_REPLAY_INVALID"
  | "DIGITAL_TWIN_ENGINE_MISSING" | "CCI_EVENT_HISTORY_NOT_AUTHORITATIVE" | "TWIN_DIRECT_MUTATION_ALLOWED" | "TWIN_INDEPENDENT_SOURCE_OF_TRUTH" | "TWIN_STATE_NOT_REPLAYABLE" | "TWIN_TRANSITION_EVIDENCE_MISSING" | "PROJECTION_ENGINE_MISSING" | "PROJECTION_NON_DETERMINISTIC" | "TWIN_REPLACES_AUTHORITATIVE_RECORDS" | "SYNCHRONIZATION_ENGINE_MISSING" | "SYNCHRONIZATION_NON_DETERMINISTIC" | "REPLAY_TWIN_EQUIVALENCE_FAILED" | "TWIN_STATE_GRAPH_MISSING" | "TWIN_GRAPH_LINEAGE_INCOMPLETE" | "SNAPSHOT_MANAGER_MISSING" | "SNAPSHOTS_AUTHORITATIVE" | "SNAPSHOT_NOT_REPRODUCIBLE" | "TWIN_QUERY_SERVICE_MISSING" | "TWIN_QUERY_NOT_EVIDENCE_BACKED" | "HISTORICAL_RECONSTRUCTION_MISSING" | "HISTORICAL_RECONSTRUCTION_FAILED" | "DIVERGENCE_DETECTION_MISSING" | "DIVERGENCE_EVIDENCE_MISSING" | "VISUALIZATION_MODEL_MISSING" | "VISUALIZATION_MUTATES_TWIN" | "TWIN_EVIDENCE_MISSING" | "SYNCHRONIZATION_REPORTS_MISSING" | "SYNCHRONIZATION_REPORTS_NOT_EVIDENCE_BACKED" | "DIGITAL_TWIN_APIS_MISSING" | "DETERMINISTIC_REPLAY_VALIDATION_FAILED" | "OPERATIONAL_EVIDENCE_QUALIFICATION_FAILED" | "DIGITAL_TWIN_QUALIFICATION_FAILED";
export type DigitalTwinScenario = "BASELINE" | "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | DigitalTwinFailure;
export type DigitalTwinInput = Readonly<{ scenario?: DigitalTwinScenario; seed?: string; tenant_id?: string; twin_id?: string }>;
export type DigitalTwinEngine = Readonly<{ engine_id: string; event_ingestion: boolean; event_ordering: boolean; state_projection: boolean; aggregate_reconstruction: boolean; graph_maintenance: boolean; historical_reconstruction: boolean; snapshot_generation: boolean; derived_exclusively_from_cci_event_history: boolean; no_direct_mutation: boolean; not_source_of_truth: boolean; every_state_replayable: boolean; complete_lineage: boolean; integrity_hash: string }>;
export type TwinProjectionEngine = Readonly<{ projection_id: string; current_state: boolean; historical_state: boolean; point_in_time_reconstruction: boolean; incremental_updates: boolean; mission_projections: boolean; deterministic_projection: boolean; projections_do_not_replace_authoritative_records: boolean; integrity_hash: string }>;
export type StateSynchronizationEngine = Readonly<{ sync_id: string; event_history_alignment: boolean; operational_twin_alignment: boolean; replay_reconstruction_alignment: boolean; synchronization_validation: boolean; divergence_detection: boolean; recovery: boolean; reconciliation_reports: boolean; deterministic_synchronization: boolean; replay_twin_equivalence: boolean; integrity_hash: string }>;
export type TwinStateGraph = Readonly<{ graph_id: string; node_kinds: readonly TwinNodeKind[]; edge_kinds: readonly TwinEdgeKind[]; dependency_traversal: boolean; impact_analysis: boolean; relationship_discovery: boolean; lineage_exploration: boolean; evidence_relationships: boolean; complete_graph_lineage: boolean; integrity_hash: string }>;
export type TwinSnapshotManager = Readonly<{ manager_id: string; checkpoint_creation: boolean; historical_comparison: boolean; rollback_visualization: boolean; replay_optimization: boolean; snapshots_are_optimization_only: boolean; replay_remains_authoritative: boolean; reproducible_from_event_history: boolean; integrity_hash: string }>;
export type TwinQueryService = Readonly<{ service_id: string; current_state_queries: boolean; historical_state_queries: boolean; mission_evolution: boolean; decision_evolution: boolean; portfolio_evolution: boolean; evidence_relationships: boolean; dependency_graphs: boolean; graph_queries: boolean; timeline_queries: boolean; evidence_queries: boolean; replay_alignment: boolean; evidence_backed_results: boolean; integrity_hash: string }>;
export type HistoricalReconstructionService = Readonly<{ service_id: string; point_in_time_reconstruction: boolean; mission_history: boolean; decision_history: boolean; portfolio_history: boolean; resource_history: boolean; uses_only_cci_event_history: boolean; reconstructs_every_mission: boolean; integrity_hash: string }>;
export type TwinDivergenceDetection = Readonly<{ detector_id: string; continuous_validation: boolean; replay_derived_state_comparison: boolean; current_twin_state_comparison: boolean; divergence_reports: boolean; reconciliation_evidence: boolean; recovery_recommendations: boolean; operational_evidence_generated: boolean; integrity_hash: string }>;
export type OperationalVisualizationModel = Readonly<{ model_id: string; dashboards: boolean; replay_viewer: boolean; mission_explorer: boolean; portfolio_explorer: boolean; evidence_explorer: boolean; normalized_operational_model: boolean; consumes_twin_state: boolean; never_modifies_twin_state: boolean; integrity_hash: string }>;
export type TwinEvidenceGenerator = Readonly<{ generator_id: string; synchronization_evidence: boolean; transition_evidence: boolean; lineage_evidence: boolean; divergence_evidence: boolean; replay_validation_evidence: boolean; immutable_evidence_references: boolean; operational_evidence_qualification: boolean; integrity_hash: string }>;
export type TwinApis = Readonly<{ api_id: string; projection_api: boolean; query_api: boolean; synchronization_api: boolean; snapshot_api: boolean; historical_reconstruction_api: boolean; graph_relationships: boolean; replay_comparison: boolean; snapshot_comparison: boolean; stable: boolean; integrity_hash: string }>;
export type SynchronizationReports = Readonly<{ report_id: string; status: SynchronizationStatus; replay_position: string; twin_position: string; divergence_summary: boolean; validation_evidence: boolean; replay_comparison: boolean; reconciliation_evidence: boolean; evidence_backed: boolean; integrity_hash: string }>;
export type DigitalTwinReadiness = Readonly<{ readiness_id: string; decision: DigitalTwinDecision; phase_ready: boolean; upstream_ready: boolean; engine_ready: boolean; projection_ready: boolean; synchronization_ready: boolean; graph_ready: boolean; snapshots_ready: boolean; query_ready: boolean; historical_ready: boolean; divergence_ready: boolean; visualization_ready: boolean; evidence_ready: boolean; apis_ready: boolean; reports_ready: boolean; cci_event_history_exclusive: boolean; no_direct_mutation: boolean; replay_equivalent: boolean; qualification_ready: boolean; failures: readonly DigitalTwinFailure[]; integrity_hash: string }>;
export type DigitalTwinResult = Readonly<{ phase_version: "digital-twin/mc-6"; phase_identifier: "DigitalTwin"; upstream_refs: readonly string[]; tenant_id: string; twin_id: string; engine: DigitalTwinEngine; projection: TwinProjectionEngine; synchronization: StateSynchronizationEngine; graph: TwinStateGraph; snapshots: TwinSnapshotManager; query: TwinQueryService; historical: HistoricalReconstructionService; divergence: TwinDivergenceDetection; visualization: OperationalVisualizationModel; evidence: TwinEvidenceGenerator; apis: TwinApis; reports: SynchronizationReports; readiness: DigitalTwinReadiness; replay_hash: string; integrity_hash: string }>;
export type DigitalTwinValidation = Readonly<{ valid: boolean; decision: DigitalTwinDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; engine_valid: boolean; projection_valid: boolean; synchronization_valid: boolean; graph_valid: boolean; snapshots_valid: boolean; query_valid: boolean; historical_valid: boolean; divergence_valid: boolean; visualization_valid: boolean; evidence_valid: boolean; apis_valid: boolean; reports_valid: boolean; readiness_valid: boolean; failures: readonly DigitalTwinFailure[]; integrity_hash: string }>;
export type DigitalTwinBundle = Readonly<{ doctrine: Readonly<{ version: "digital-twin/mc-6"; owns_digital_twin_engine: true; owns_projection_engine: true; owns_state_synchronization: true; owns_twin_state_graph: true; owns_snapshot_manager: true; owns_historical_reconstruction: true; derives_exclusively_from_cci_event_history: true; twin_is_not_source_of_truth: true; direct_mutation_prohibited: true; qualification_gate: "Digital Twin Qualification Gate" }>; result: DigitalTwinResult; validation: DigitalTwinValidation }>;
