export type EvidenceEngineDecision = "EVIDENCE_ENGINE_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type EvidenceEngineFailure =
  | "W2_0_CAF_CONSTITUTION_INVALID" | "W2_1_AGENT_REGISTRY_INVALID" | "W2_2_LIFECYCLE_ENGINE_INVALID" | "W2_3_CAPABILITY_REGISTRY_INVALID" | "W2_4_SKILL_REGISTRY_INVALID" | "W2_5_AUTHORITY_VALIDATOR_INVALID" | "W2_6_POLICY_GATE_INVALID" | "W2_7_SAFETY_GATE_INVALID" | "W2_8_PLANNING_ENGINE_INVALID" | "W2_9_MEMORY_ENGINE_INVALID" | "W2_10_RUNTIME_ORCHESTRATOR_INVALID" | "W2_11_DELEGATION_ENGINE_INVALID" | "W2_12_COLLABORATION_ENGINE_INVALID"
  | "EVIDENCE_CAPTURE_MISSING" | "EVIDENCE_CAPTURE_NON_DETERMINISTIC" | "RUNTIME_EVENT_NOT_CAPTURED" | "EVIDENCE_PACKAGE_MISSING" | "PACKAGE_NOT_SIGNED" | "PACKAGE_NOT_IMMUTABLE" | "PACKAGE_NOT_VERSIONED" | "PACKAGE_GENERATION_NON_DETERMINISTIC" | "EVIDENCE_INDEX_MISSING" | "INDEX_RETRIEVAL_NON_DETERMINISTIC" | "LINEAGE_TRAVERSAL_INVALID" | "EVIDENCE_VALIDATION_MISSING" | "SCHEMA_VALIDATION_FAILED" | "SIGNATURE_VALIDATION_FAILED" | "HASH_VERIFICATION_FAILED" | "COMPLETENESS_VALIDATION_FAILED" | "REPLAY_COMPATIBILITY_FAILED" | "PROVENANCE_MISSING" | "PROVENANCE_INCOMPLETE" | "EVIDENCE_CONTRACTS_MISSING" | "CONTRACT_VERSIONING_MISSING" | "CONTRACT_ENFORCEMENT_FAILED" | "EVIDENCE_EXPLORER_MISSING" | "UNAUTHORIZED_EVIDENCE_ACCESS_ALLOWED" | "TENANT_ISOLATION_FAILED" | "NAMESPACE_ISOLATION_FAILED" | "EVIDENCE_RUNTIME_INTEGRATION_MISSING" | "EVIDENCE_API_MISSING" | "EVIDENCE_ENCRYPTION_MISSING" | "EVIDENCE_REPLAY_INVALID" | "EVIDENCE_ENGINE_QUALIFICATION_FAILED";
export type EvidenceEngineScenario = "BASELINE" | "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | EvidenceEngineFailure;
export type EvidenceEngineInput = Readonly<{ scenario?: EvidenceEngineScenario; seed?: string }>;
export type EvidenceCaptureFramework = Readonly<{ collector_id: string; agent_execution: boolean; planning_decisions: boolean; memory_operations: boolean; tool_execution: boolean; runtime_events: boolean; collaboration_events: boolean; delegation_events: boolean; policy_evaluations: boolean; authority_decisions: boolean; safety_decisions: boolean; lifecycle_transitions: boolean; operator_interactions: boolean; recovery_operations: boolean; capture_pipeline: boolean; runtime_hooks: boolean; capture_apis: boolean; deterministic_capture: boolean; complete_capture: boolean; integrity_hash: string }>;
export type EvidencePackageFramework = Readonly<{ service_id: string; metadata: boolean; event_sequence: boolean; runtime_context: boolean; agent_identity: boolean; capability_references: boolean; skill_references: boolean; decision_records: boolean; inputs: boolean; outputs: boolean; policies_evaluated: boolean; authority_evaluations: boolean; safety_evaluations: boolean; memory_references: boolean; provenance: boolean; digital_signatures: boolean; incremental_packages: boolean; session_packages: boolean; workflow_packages: boolean; mission_packages: boolean; qualification_packages: boolean; certification_packages: boolean; immutable: boolean; signed: boolean; versioned: boolean; deterministic_packages: boolean; integrity_hash: string }>;
export type EvidenceIndex = Readonly<{ index_id: string; agent: boolean; capability: boolean; skill: boolean; workflow: boolean; runtime: boolean; tenant: boolean; namespace: boolean; session: boolean; policy: boolean; authority: boolean; safety: boolean; time: boolean; event_type: boolean; correlation_id: boolean; fast_lookup: boolean; deterministic_retrieval: boolean; lineage_traversal: boolean; provenance_search: boolean; dependency_search: boolean; package_discovery: boolean; integrity_hash: string }>;
export type EvidenceValidationEngine = Readonly<{ engine_id: string; schema_validation: boolean; signature_validation: boolean; hash_verification: boolean; provenance_verification: boolean; lineage_validation: boolean; contract_validation: boolean; timestamp_verification: boolean; completeness_validation: boolean; replay_compatibility: boolean; cross_reference_validation: boolean; integrity_reports: boolean; corrupted_evidence_detection: boolean; integrity_hash: string }>;
export type EvidenceProvenance = Readonly<{ registry_id: string; source_service: boolean; runtime: boolean; agent: boolean; capability: boolean; skill: boolean; operator: boolean; policy: boolean; authority: boolean; delegation_chain: boolean; collaboration_chain: boolean; parent_evidence: boolean; child_evidence: boolean; lineage_graph: boolean; provenance_apis: boolean; complete_origin_tracking: boolean; integrity_hash: string }>;
export type EvidenceContracts = Readonly<{ registry_id: string; capture_contract: boolean; package_contract: boolean; validation_contract: boolean; search_contract: boolean; retrieval_contract: boolean; export_contract: boolean; replay_contract: boolean; schemas: boolean; versioning: boolean; compatibility: boolean; required_metadata: boolean; validation_rules: boolean; enforced: boolean; integrity_hash: string }>;
export type EvidenceExplorer = Readonly<{ explorer_id: string; package_explorer: boolean; timeline_visualization: boolean; lineage_viewer: boolean; validation_status: boolean; search: boolean; filtering: boolean; correlation_viewer: boolean; replay_links: boolean; provenance_graph: boolean; explorer_api: boolean; secure_access: boolean; tenant_isolated: boolean; integrity_hash: string }>;
export type EvidenceRuntimeIntegration = Readonly<{ integration_id: string; runtime_orchestrator: boolean; planning_engine: boolean; memory_engine: boolean; collaboration_engine: boolean; delegation_engine: boolean; policy_gate: boolean; safety_gate: boolean; authority_validator: boolean; lifecycle_engine: boolean; capability_registry: boolean; skill_registry: boolean; event_integration: boolean; evidence_pipeline: boolean; integrity_hash: string }>;
export type EvidenceApis = Readonly<{ api_id: string; submit_evidence: boolean; batch_capture: boolean; stream_capture: boolean; runtime_events: boolean; create_package: boolean; update_package: boolean; finalize_package: boolean; sign_package: boolean; validate_evidence: boolean; validate_package: boolean; verify_integrity: boolean; verify_lineage: boolean; search: boolean; filter: boolean; retrieve: boolean; correlation: boolean; lineage_queries: boolean; browse: boolean; timeline: boolean; graph: boolean; export: boolean; stable: boolean; integrity_hash: string }>;
export type EvidenceSecurity = Readonly<{ security_id: string; tenant_isolation: boolean; namespace_isolation: boolean; access_control: boolean; signed_packages: boolean; immutable_evidence: boolean; encryption_at_rest: boolean; encryption_in_transit: boolean; authorization_validation: boolean; tamper_evident: boolean; integrity_hash: string }>;
export type EvidenceEngineReadiness = Readonly<{ readiness_id: string; decision: EvidenceEngineDecision; phase_ready: boolean; upstream_ready: boolean; capture_ready: boolean; package_ready: boolean; index_ready: boolean; validation_ready: boolean; provenance_ready: boolean; contracts_ready: boolean; explorer_ready: boolean; runtime_integration_ready: boolean; apis_ready: boolean; security_ready: boolean; replay_ready: boolean; tenant_namespace_isolated: boolean; failures: readonly EvidenceEngineFailure[]; integrity_hash: string }>;
export type EvidenceEngineResult = Readonly<{ phase_version: "evidence-engine/w2.13"; phase_identifier: "EvidenceEngine"; upstream_refs: readonly string[]; capture: EvidenceCaptureFramework; packages: EvidencePackageFramework; index: EvidenceIndex; validation_engine: EvidenceValidationEngine; provenance: EvidenceProvenance; contracts: EvidenceContracts; explorer: EvidenceExplorer; runtime_integration: EvidenceRuntimeIntegration; apis: EvidenceApis; security: EvidenceSecurity; readiness: EvidenceEngineReadiness; replay_hash: string; integrity_hash: string }>;
export type EvidenceEngineValidation = Readonly<{ valid: boolean; decision: EvidenceEngineDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; capture_valid: boolean; packages_valid: boolean; index_valid: boolean; validation_engine_valid: boolean; provenance_valid: boolean; contracts_valid: boolean; explorer_valid: boolean; runtime_integration_valid: boolean; apis_valid: boolean; security_valid: boolean; readiness_valid: boolean; failures: readonly EvidenceEngineFailure[]; integrity_hash: string }>;
export type EvidenceEngineBundle = Readonly<{ doctrine: Readonly<{ version: "evidence-engine/w2.13"; owns_evidence_capture: true; owns_evidence_packages: true; owns_evidence_index: true; owns_evidence_validation: true; owns_provenance_management: true; owns_evidence_contracts: true; owns_evidence_explorer: true; owns_runtime_integration: true; owns_evidence_security: true; qualification_gate: "Evidence Engine Qualification Gate" }>; result: EvidenceEngineResult; validation: EvidenceEngineValidation }>;
