export type GlobalTenantRegistryRegionalAssignmentOutcome = "PASS" | "CONDITIONAL_PASS" | "FAIL";
export type AssignmentLifecycleState = "REQUESTED" | "VALIDATING" | "AUTHORIZED" | "COMPARE_AND_SET" | "COMMITTED" | "ACTIVE" | "SUPERSEDED" | "ARCHIVED";
export type RegistryState = "REGISTERED" | "ASSIGNED" | "ACTIVE" | "REASSIGNED" | "RETIRED";
export type AssignmentMutationOutcome = "ASSIGNMENT_COMMITTED" | "STALE_ASSIGNMENT_PROPOSAL" | "ASSIGNMENT_CONSTRAINT_VIOLATION" | "ASSIGNMENT_AUTHORITY_INVALID" | "ASSIGNMENT_INTEGRITY_FAILURE";
export type GlobalTenantRegistryRegionalAssignmentFailure =
  | "REGISTRY_NOT_DETERMINISTIC"
  | "COMPARE_AND_SET_NOT_ENFORCED"
  | "STALE_PROPOSALS_NOT_REJECTED"
  | "SILENT_OVERWRITE_POSSIBLE"
  | "IMMUTABLE_ASSIGNMENT_AUDIT_INCOMPLETE"
  | "REPLAY_NOT_PRESERVED"
  | "REGISTRY_NOT_CERTIFIED"
  | "GLOBAL_REGISTRY_NOT_AUTHORITATIVE"
  | "ASSIGNMENT_AUTHORITY_NOT_VALIDATED"
  | "ASSIGNMENT_INTEGRITY_NOT_VERIFIED"
  | "TIMESTAMP_USED_FOR_PRECEDENCE"
  | "MUTATION_ENVELOPE_INCOMPLETE"
  | "PHASE_17_2_LIFECYCLE_NOT_VALID"
  | "NON_CONSTITUTIONAL_REGISTRY_WARNING";
export type GlobalTenantRegistryRegionalAssignmentScenario = "BASELINE" | GlobalTenantRegistryRegionalAssignmentFailure;
export type GlobalTenantRegistryRegionalAssignmentInput = Readonly<{ scenario?: GlobalTenantRegistryRegionalAssignmentScenario; tenant_id?: string; operator_id?: string; mission_id?: string; request_id?: string; target_region?: string; expected_registry_version?: string; registry_version?: string }>;

export type AssignmentMutationEnvelope = Readonly<{ tenant_id: string; request_id: string; expected_registry_version: string; current_assignment_ref: string; proposed_assignment: string; assignment_reason: string; authorizing_decision_ref: string; requester_identity: string; request_timestamp: string; integrity_hash: string }>;
export type TenantRegistryRecord = Readonly<{ tenant_id: string; registry_version: string; tenant_owner: string; current_regional_assignment: string; assignment_history_ref: string; deployment_status: "REGISTERED" | "ASSIGNED" | "ACTIVE"; certification_status: "CERTIFIED" | "NOT_CERTIFIED"; resource_quotas: readonly string[]; lifecycle_status: RegistryState; integrity_state: "VALID" | "INVALID"; integrity_hash: string }>;
export type GlobalTenantRegistry = Readonly<{ registry_id: string; authoritative: boolean; tenant_records: readonly TenantRegistryRecord[]; registry_state_history: readonly RegistryState[]; deterministic: boolean; versioned: boolean; replayable: boolean; integrity_hash: string }>;
export type RegionalAssignmentRegistry = Readonly<{ registry_id: string; active_assignments: readonly string[]; pending_assignments: readonly string[]; reassignment_requests: readonly string[]; assignment_lineage: readonly string[]; assignment_authority: readonly string[]; assignment_validation: readonly string[]; registry_version_history: readonly string[]; single_source_of_truth: boolean; immutable_history: boolean; integrity_hash: string }>;
export type AssignmentMutationValidation = Readonly<{ validation_id: string; tenant_exists: boolean; requester_authorized: boolean; registry_version_matches: boolean; assignment_valid: boolean; target_region_eligible: boolean; certification_permits_assignment: boolean; quota_constraints_satisfied: boolean; integrity_verified: boolean; replay_preserved: boolean; envelope_complete: boolean; outcome: AssignmentMutationOutcome; integrity_hash: string }>;
export type AssignmentAuthorityValidation = Readonly<{ authority_id: string; governance_authorization: boolean; tenant_ownership: boolean; regional_policy: boolean; deployment_qualification: boolean; certification_authority: boolean; constitutional_compliance: boolean; precedes_registry_mutation: boolean; integrity_hash: string }>;
export type CompareAndSetConflictResolver = Readonly<{ resolver_id: string; validates_registry_version: boolean; validates_current_assignment: boolean; validates_mutation_authority: boolean; validates_integrity: boolean; validates_replay_consistency: boolean; rejects_stale_proposals: boolean; prohibits_last_writer_wins: boolean; ignores_arrival_order: boolean; ignores_processing_latency: boolean; ignores_wall_clock_ordering: boolean; ignores_timestamp_ordering: boolean; integrity_hash: string }>;
export type AssignmentLedgerEntry = Readonly<{ ledger_entry_id: string; sequence: number; registry_version: string; assignment_ref: string; authority_ref: string; mutation_evidence_ref: string; replay_ref: string; certification_ref: string; supersedes: string | null; append_only: boolean; immutable: boolean; integrity_hash: string }>;
export type AssignmentReplayService = Readonly<{ replay_id: string; reconstructs_registry_creation: boolean; reconstructs_assignment_requests: boolean; reconstructs_authority_validation: boolean; reconstructs_compare_and_set_decisions: boolean; reconstructs_rejected_mutations: boolean; reconstructs_committed_assignments: boolean; reconstructs_superseded_assignments: boolean; reconstructs_integrity_validation: boolean; reconstructs_registry_versions: boolean; reproduces_identical_registry_state: boolean; replay_refs: readonly string[]; integrity_hash: string }>;
export type RegistryIntegrityValidator = Readonly<{ validator_id: string; registry_integrity_valid: boolean; assignment_integrity_valid: boolean; ledger_integrity_valid: boolean; replay_integrity_valid: boolean; certification_integrity_valid: boolean; timestamp_metadata_only: boolean; no_implicit_overwrite_semantics: boolean; integrity_hash: string }>;
export type AssignmentAuditDashboard = Readonly<{ dashboard_id: string; registry_health_visible: boolean; assignment_activity_visible: boolean; regional_distribution_visible: boolean; mutation_throughput_visible: boolean; rejected_mutations_visible: boolean; stale_proposal_frequency_visible: boolean; authority_failures_visible: boolean; integrity_failures_visible: boolean; replay_verification_visible: boolean; certification_status_visible: boolean; operational: boolean; integrity_hash: string }>;
export type RegistryCertificationPackage = Readonly<{ package_id: string; deterministic_registry_behavior: boolean; compare_and_set_enforced: boolean; authority_validation_complete: boolean; immutable_assignment_history: boolean; replay_determinism: boolean; integrity_verification: boolean; conflict_resolution_correct: boolean; overwrite_prevention: boolean; audit_complete: boolean; constitutional_compliance: boolean; registry_certified: boolean; evidence_refs: readonly string[]; integrity_hash: string }>;
export type GlobalTenantRegistryRegionalAssignmentTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: GlobalTenantRegistryRegionalAssignmentOutcome; passed: boolean; failure_reason: GlobalTenantRegistryRegionalAssignmentFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;

export type GlobalTenantRegistryRegionalAssignmentResult = Readonly<{ phase_version: "global-tenant-registry-regional-assignment/v17.3"; phase_identifier: "GlobalTenantRegistryRegionalAssignment"; tenant_provisioning_lifecycle_ref: string; mutation_envelope: AssignmentMutationEnvelope; global_registry: GlobalTenantRegistry; regional_assignment_registry: RegionalAssignmentRegistry; mutation_validation: AssignmentMutationValidation; authority_validation: AssignmentAuthorityValidation; conflict_resolver: CompareAndSetConflictResolver; assignment_ledger: readonly AssignmentLedgerEntry[]; replay_service: AssignmentReplayService; integrity_validator: RegistryIntegrityValidator; dashboard: AssignmentAuditDashboard; certification_package: RegistryCertificationPackage; certification_tests: readonly GlobalTenantRegistryRegionalAssignmentTest[]; failures: readonly GlobalTenantRegistryRegionalAssignmentFailure[]; outcome: GlobalTenantRegistryRegionalAssignmentOutcome; replay_hash: string; integrity_hash: string }>;
export type GlobalTenantRegistryRegionalAssignmentValidation = Readonly<{ valid: boolean; outcome: GlobalTenantRegistryRegionalAssignmentOutcome; envelope_valid: boolean; global_registry_valid: boolean; regional_registry_valid: boolean; mutation_valid: boolean; authority_valid: boolean; resolver_valid: boolean; ledger_valid: boolean; replay_valid: boolean; integrity_valid: boolean; dashboard_valid: boolean; certification_package_valid: boolean; certification_valid: boolean; result_replay_valid: boolean; failures: readonly GlobalTenantRegistryRegionalAssignmentFailure[]; integrity_hash: string }>;
export type GlobalTenantRegistryRegionalAssignmentBundle = Readonly<{ doctrine: Readonly<{ version: "global-tenant-registry-regional-assignment/v17.3"; upstream_phase: "tenant-provisioning-lifecycle/v17.2"; assignment_lifecycle_states: readonly AssignmentLifecycleState[]; registry_states: readonly RegistryState[]; mutation_outcomes: readonly AssignmentMutationOutcome[]; certification_outcomes: readonly GlobalTenantRegistryRegionalAssignmentOutcome[] }>; result: GlobalTenantRegistryRegionalAssignmentResult; validation: GlobalTenantRegistryRegionalAssignmentValidation }>;
