export type GlobalWorkloadDistributionOutcome = "PASS" | "CONDITIONAL_PASS" | "FAIL";
export type WorkloadDistributionLifecycleState = "WORKLOAD_RECEIVED" | "CLASSIFIED" | "ROUTING_EVALUATED" | "DESTINATION_SELECTED" | "QUEUED" | "DISTRIBUTED" | "EXECUTING" | "COMPLETED" | "RETRY_PENDING" | "FAILOVER_PENDING" | "REJECTED";
export type WorkloadType = "ADVISORY" | "REPLAY" | "AUDIT" | "CERTIFICATION" | "OPERATOR_CONTROL";
export type RoutingDecision = "ROUTE" | "RETRY" | "FAILOVER" | "REJECT_CAPACITY" | "REJECT_GOVERNANCE" | "REJECT_POLICY";
export type GlobalWorkloadDistributionFailure =
  | "ROUTING_NOT_DETERMINISTIC"
  | "BALANCING_NOT_REPRODUCIBLE"
  | "RETRY_POLICY_NOT_DETERMINISTIC"
  | "WORKLOAD_DISTRIBUTION_NOT_REPLAYABLE"
  | "FAILOVER_NOT_DETERMINISTIC"
  | "ROUTING_EVIDENCE_MUTABLE"
  | "REPLAY_NOT_VALIDATED"
  | "TENANT_ISOLATION_VIOLATED"
  | "GOVERNANCE_NOT_ENFORCED"
  | "WORKLOAD_DISTRIBUTION_NOT_CERTIFIED"
  | "CAPACITY_GOVERNANCE_BYPASSED"
  | "QUEUE_ORDERING_NOT_DETERMINISTIC"
  | "ROUTING_DEPENDS_ON_TIMING"
  | "PHASE_17_4_CAPACITY_NOT_VALID"
  | "NON_CONSTITUTIONAL_DISTRIBUTION_WARNING";
export type GlobalWorkloadDistributionScenario = "BASELINE" | GlobalWorkloadDistributionFailure;
export type GlobalWorkloadDistributionInput = Readonly<{ scenario?: GlobalWorkloadDistributionScenario; tenant_id?: string; operator_id?: string; mission_id?: string; workload_id?: string; workload_type?: WorkloadType; routing_region?: string; requested_capacity?: number; quota_limit?: number; priority?: number }>;

export type WorkloadClassification = Readonly<{ classification_id: string; workload_id: string; tenant_id: string; workload_type: WorkloadType; capability: string; regional_affinity: string; priority: number; infrastructure_requirements: readonly string[]; replay_required: boolean; deterministic: boolean; integrity_hash: string }>;
export type WorkloadRouter = Readonly<{ router_id: string; routing_region: string; destination: string; routing_decision: RoutingDecision; tenant_aware_routing: boolean; regional_routing: boolean; infrastructure_routing: boolean; routing_validation: boolean; produces_routing_evidence: boolean; identical_inputs_identical_decisions: boolean; independent_of_arrival_order: boolean; independent_of_runtime_timing: boolean; integrity_hash: string }>;
export type QueueManager = Readonly<{ queue_manager_id: string; queue_identifier: string; queue_assignment: string; queue_order: readonly string[]; queue_isolation: boolean; replay_ordering: boolean; retry_preparation: boolean; deterministic_ordering: boolean; integrity_hash: string }>;
export type LoadDistributionEngine = Readonly<{ engine_id: string; balancing_policy: string; regional_balancing: boolean; infrastructure_balancing: boolean; capacity_aware_placement: boolean; tenant_aware_balancing: boolean; replay_validation: boolean; depends_on_runtime_conditions: boolean; reproducible_balancing: boolean; integrity_hash: string }>;
export type ElasticScalingCoordinator = Readonly<{ coordinator_id: string; capacity_growth_supported: boolean; workload_redistribution_supported: boolean; infrastructure_expansion_supported: boolean; scaling_validation: boolean; governed_by_resource_allocation: boolean; overrides_resource_constraints: boolean; integrity_hash: string }>;
export type RetryRecord = Readonly<{ retry_id: string; workload_id: string; tenant_id: string; retry_policy: string; retry_attempt: number; retry_reason: string; retry_decision: RoutingDecision; routing_reference: string; replay_reference: string; integrity_hash: string }>;
export type RetryPolicyEngine = Readonly<{ engine_id: string; retry_record: RetryRecord; retry_qualification: boolean; retry_scheduling: boolean; retry_replay: boolean; retry_evidence: boolean; identical_retry_sequences: boolean; independent_of_latency: boolean; independent_of_network_timing: boolean; independent_of_thread_scheduling: boolean; independent_of_wall_clock: boolean; integrity_hash: string }>;
export type FailoverRoutingEngine = Readonly<{ engine_id: string; failover_policy: string; destination_validation: boolean; regional_failover: boolean; infrastructure_failover: boolean; replay_validation: boolean; audit_evidence: boolean; deterministic_selection: boolean; preserves_workload_identity: boolean; preserves_routing_lineage: boolean; uses_arrival_order: boolean; uses_runtime_timing: boolean; uses_server_responsiveness: boolean; integrity_hash: string }>;
export type DistributionRecord = Readonly<{ distribution_id: string; workload_id: string; tenant_id: string; routing_region: string; destination: string; queue_identifier: string; balancing_policy: string; retry_policy: string; failover_policy: string; routing_result: RoutingDecision; replay_reference: string; integrity_hash: string }>;
export type DistributionLedgerEntry = Readonly<{ ledger_entry_id: string; sequence: number; distribution_ref: string; workload_id: string; lifecycle_state: WorkloadDistributionLifecycleState; routing_reference: string; queue_reference: string; retry_reference: string; failover_reference: string; replay_reference: string; append_only: boolean; immutable: boolean; integrity_hash: string }>;
export type RoutingReplayService = Readonly<{ replay_id: string; reconstructs_routing: boolean; reconstructs_queue_ordering: boolean; reconstructs_retries: boolean; reconstructs_failover: boolean; reconstructs_balancing: boolean; reconstructs_audit_evidence: boolean; validates_replay_health: boolean; identical_routing_decisions: boolean; replay_refs: readonly string[]; integrity_hash: string }>;
export type DistributionAuditService = Readonly<{ audit_id: string; routing_activity_visible: boolean; queue_depth_visible: boolean; balancing_efficiency_visible: boolean; retry_activity_visible: boolean; failover_frequency_visible: boolean; replay_health_visible: boolean; tenant_isolation_visible: boolean; constitutional_compliance_visible: boolean; monitoring_influences_routing: boolean; integrity_hash: string }>;
export type DistributionObservabilityDashboard = DistributionAuditService;
export type WorkloadDistributionCertificationPackage = Readonly<{ package_id: string; routing_deterministic: boolean; balancing_reproducible: boolean; retry_policy_deterministic: boolean; workload_distribution_replayable: boolean; failover_deterministic: boolean; routing_evidence_immutable: boolean; replay_validated: boolean; tenant_isolation: boolean; governance_enforced: boolean; workload_distribution_certified: boolean; evidence_refs: readonly string[]; integrity_hash: string }>;
export type GlobalWorkloadDistributionTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: GlobalWorkloadDistributionOutcome; passed: boolean; failure_reason: GlobalWorkloadDistributionFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;

export type GlobalWorkloadDistributionResult = Readonly<{ phase_version: "global-workload-distribution/v17.5"; phase_identifier: "GlobalWorkloadDistribution"; resource_scheduling_capacity_management_ref: string; classification: WorkloadClassification; router: WorkloadRouter; queue_manager: QueueManager; load_distribution_engine: LoadDistributionEngine; elastic_scaling_coordinator: ElasticScalingCoordinator; retry_policy_engine: RetryPolicyEngine; failover_routing_engine: FailoverRoutingEngine; distribution_record: DistributionRecord; distribution_ledger: readonly DistributionLedgerEntry[]; replay_service: RoutingReplayService; audit_service: DistributionAuditService; dashboard: DistributionObservabilityDashboard; certification_package: WorkloadDistributionCertificationPackage; certification_tests: readonly GlobalWorkloadDistributionTest[]; failures: readonly GlobalWorkloadDistributionFailure[]; outcome: GlobalWorkloadDistributionOutcome; replay_hash: string; integrity_hash: string }>;
export type GlobalWorkloadDistributionValidation = Readonly<{ valid: boolean; outcome: GlobalWorkloadDistributionOutcome; classification_valid: boolean; router_valid: boolean; queue_valid: boolean; load_valid: boolean; scaling_valid: boolean; retry_valid: boolean; failover_valid: boolean; distribution_record_valid: boolean; ledger_valid: boolean; replay_valid: boolean; audit_valid: boolean; dashboard_valid: boolean; certification_package_valid: boolean; certification_valid: boolean; result_replay_valid: boolean; failures: readonly GlobalWorkloadDistributionFailure[]; integrity_hash: string }>;
export type GlobalWorkloadDistributionBundle = Readonly<{ doctrine: Readonly<{ version: "global-workload-distribution/v17.5"; upstream_phase: "resource-scheduling-capacity-management/v17.4"; lifecycle_states: readonly WorkloadDistributionLifecycleState[]; workload_types: readonly WorkloadType[]; routing_decisions: readonly RoutingDecision[]; certification_outcomes: readonly GlobalWorkloadDistributionOutcome[] }>; result: GlobalWorkloadDistributionResult; validation: GlobalWorkloadDistributionValidation }>;
