export type GovernanceConstitutionalStatus = "PASS" | "FAIL";
export type GovernanceConstitutionalDecision = "CERTIFIED" | "REJECTED";
export type GovernanceConstitutionalWidget = "Governance Certification" | "Constitutional Certification" | "Authority Boundary" | "Tenant Isolation" | "Approval Enforcement" | "Bypass Detection" | "Certification Report" | "Authority Compliance Report";
export type PermittedAdaptiveAuthority = "OBSERVE" | "ANALYZE" | "CLASSIFY" | "FORECAST" | "SIMULATE" | "RECOMMEND" | "EXPLAIN" | "PRIORITIZE" | "ADVISE";
export type ProhibitedAdaptiveAuthority = "EXECUTE_PRODUCTION_ACTION" | "DEPLOY_CHANGE" | "MODIFY_GOVERNANCE" | "MODIFY_CONSTITUTION" | "APPROVE_PRODUCTION_MUTATION" | "SELF_CERTIFY" | "EXPAND_AUTHORITY" | "AUTHORIZE_EXCEPTION" | "REPLACE_OPERATOR_DECISION" | "MUTATE_TRUTH_LEDGER";

export type GovernanceConstitutionalScenario =
  | "BASELINE" | "GOVERNANCE_VALIDATION_OMITTED" | "GOVERNANCE_BYPASS" | "POLICY_NONDETERMINISM" | "GOVERNANCE_REPLAY_INCONSISTENT" | "CONSTITUTIONAL_VALIDATION_OMITTED" | "CONSTITUTIONAL_BYPASS" | "CONSTITUTIONAL_REPLAY_INCONSISTENT" | "AUTHORITY_ESCALATION" | "UNAUTHORIZED_EXECUTION_AUTHORITY" | "ADVISORY_BOUNDARY_BROKEN" | "SELF_CERTIFICATION" | "GOVERNANCE_MODIFICATION" | "CONSTITUTIONAL_MODIFICATION" | "TENANT_ISOLATION_BREACH" | "CROSS_TENANT_EVIDENCE" | "CROSS_TENANT_MEMORY" | "CROSS_TENANT_REPLAY" | "MISSING_OPERATOR_APPROVAL" | "APPROVAL_WORKFLOW_BYPASS" | "TRUTH_LEDGER_MUTATION" | "AUDIT_LINEAGE_INCOMPLETE" | "CONSTITUTIONAL_LINEAGE_INCOMPLETE" | "INTEGRITY_FAILURE" | "FAIL_OPEN_BEHAVIOR";

export type GovernanceConstitutionalFailure =
  | "GOVERNANCE_VALIDATION_OMITTED" | "GOVERNANCE_BYPASS_DETECTED" | "POLICY_EVALUATION_NONDETERMINISTIC" | "GOVERNANCE_REPLAY_INCONSISTENT" | "CONSTITUTIONAL_VALIDATION_OMITTED" | "CONSTITUTIONAL_BYPASS_DETECTED" | "CONSTITUTIONAL_REPLAY_INCONSISTENT" | "AUTHORITY_ESCALATION_DETECTED" | "UNAUTHORIZED_EXECUTION_AUTHORITY" | "ADVISORY_ONLY_BOUNDARY_BROKEN" | "SELF_CERTIFICATION_PERMITTED" | "GOVERNANCE_MODIFICATION_PERMITTED" | "CONSTITUTIONAL_MODIFICATION_PERMITTED" | "TENANT_ISOLATION_BREACH" | "CROSS_TENANT_EVIDENCE_ACCESS" | "CROSS_TENANT_ADAPTIVE_MEMORY_ACCESS" | "CROSS_TENANT_REPLAY_ACCESS" | "OPERATOR_APPROVAL_MISSING" | "APPROVAL_WORKFLOW_BYPASSED" | "TRUTH_LEDGER_MUTATION_PERMITTED" | "AUDIT_LINEAGE_INCOMPLETE" | "CONSTITUTIONAL_LINEAGE_INCOMPLETE" | "INTEGRITY_HASH_MISMATCH" | "FAIL_CLOSED_BEHAVIOR_ABSENT";

export type GovernanceConstitutionalCertificationRecord = Readonly<{ certification_id: string; tenant_id: string; mission_id: string; governance_supremacy_status: GovernanceConstitutionalStatus; constitutional_enforcement_status: GovernanceConstitutionalStatus; authority_restriction_status: GovernanceConstitutionalStatus; tenant_isolation_status: GovernanceConstitutionalStatus; approval_enforcement_status: GovernanceConstitutionalStatus; governance_bypass_detected: boolean; constitutional_bypass_detected: boolean; authority_escalation_detected: boolean; governance_replay_status: GovernanceConstitutionalStatus; constitutional_replay_status: GovernanceConstitutionalStatus; findings: readonly GovernanceConstitutionalFailure[]; policy_refs: readonly string[]; governance_refs: readonly string[]; constitutional_refs: readonly string[]; authority_refs: readonly string[]; replay_refs: readonly string[]; certification_status: GovernanceConstitutionalDecision; certification_timestamp: string; integrity_hash: string }>;
export type GovernanceSupremacyValidation = Readonly<{ validation_id: string; governance_validation_mandatory: boolean; governance_supremacy_enforced: boolean; policy_evaluation_deterministic: boolean; governance_approval_chains_enforced: boolean; policy_version_resolution_deterministic: boolean; governance_audit_generated: boolean; governance_replay_reproducible: boolean; bypass_impossible: boolean; fail_closed_on_failure: boolean; integrity_hash: string }>;
export type ConstitutionalEnforcementValidation = Readonly<{ validation_id: string; constitutional_validation_mandatory: boolean; constitutional_doctrine_enforced: boolean; authority_doctrine_compliant: boolean; constraint_framework_compliant: boolean; trust_evidence_doctrine_compliant: boolean; constitutional_security_enforced: boolean; constitutional_replay_reproducible: boolean; violations_fail_closed: boolean; doctrine_modification_prohibited: boolean; integrity_hash: string }>;
export type AuthorityRestrictionValidation = Readonly<{ validation_id: string; permitted_authority: readonly PermittedAdaptiveAuthority[]; prohibited_authority: readonly ProhibitedAdaptiveAuthority[]; authority_restrictions_enforced: boolean; advisory_only_boundary_preserved: boolean; autonomous_execution_blocked: boolean; self_certification_prohibited: boolean; governance_modification_prohibited: boolean; constitutional_modification_prohibited: boolean; truth_ledger_mutation_prohibited: boolean; operator_supremacy_preserved: boolean; integrity_hash: string }>;
export type TenantIsolationGovernanceValidation = Readonly<{ validation_id: string; tenant_isolation_deterministic: boolean; adaptive_memory_isolated: boolean; evidence_isolated: boolean; replay_artifacts_isolated: boolean; governance_decisions_isolated: boolean; certification_artifacts_isolated: boolean; simulations_isolated: boolean; dashboards_authorized_only: boolean; operator_workflows_isolated: boolean; integrity_hash: string }>;
export type ApprovalEnforcementValidation = Readonly<{ validation_id: string; approval_workflows_mandatory: boolean; adaptive_proposals_blocked_until_approved: boolean; production_recommendations_require_approval: boolean; governance_exceptions_require_approval: boolean; simulation_promotion_requires_approval: boolean; memory_promotion_requires_approval: boolean; strategic_recommendations_require_approval: boolean; certification_progression_requires_approval: boolean; approval_lineage_immutable: boolean; approvals_replayable: boolean; integrity_hash: string }>;
export type BypassEscalationDetection = Readonly<{ validation_id: string; governance_bypass_absent: boolean; constitutional_bypass_absent: boolean; authority_escalation_absent: boolean; audit_logging_bypass_absent: boolean; certification_bypass_absent: boolean; replay_recording_bypass_absent: boolean; privilege_elevation_blocked: boolean; exception_authorization_blocked: boolean; certification_state_alteration_blocked: boolean; fail_closed_verified: boolean; integrity_hash: string }>;
export type GovernanceConstitutionalCertificationReport = Readonly<{ report_id: string; certification_outcome: GovernanceConstitutionalDecision; governance_supremacy_assessment: GovernanceConstitutionalStatus; constitutional_enforcement_assessment: GovernanceConstitutionalStatus; authority_restriction_validation: GovernanceConstitutionalStatus; tenant_isolation_analysis: GovernanceConstitutionalStatus; approval_enforcement_result: GovernanceConstitutionalStatus; governance_replay_validation: GovernanceConstitutionalStatus; constitutional_replay_validation: GovernanceConstitutionalStatus; bypass_detection_findings: readonly GovernanceConstitutionalFailure[]; authority_escalation_analysis: GovernanceConstitutionalStatus; production_readiness_recommendation: "READY" | "BLOCKED"; remediation_actions: readonly string[]; integrity_hash: string }>;
export type AuthorityComplianceReport = Readonly<{ report_id: string; authority_boundary_verified: boolean; governance_policy_compliance: boolean; constitutional_doctrine_compliance: boolean; tenant_isolation_validated: boolean; approval_workflow_integrity: boolean; operator_authority_preserved: boolean; replay_audit_lineage_complete: boolean; certification_evidence_refs: readonly string[]; findings: readonly GovernanceConstitutionalFailure[]; remediation_actions: readonly string[]; integrity_hash: string }>;
export type GovernanceConstitutionalCertificationTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: "PASS" | "FAIL"; passed: boolean; failure_reason: GovernanceConstitutionalFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;
export type GovernanceConstitutionalApiSurface = Readonly<{ api_id: string; retrieve_dashboard: string; retrieve_contract: string; retrieve_sections: readonly string[]; validate_certification: string; inspect_certification: string; mutation_supported: false; authority_expansion_supported: false; governance_modification_supported: false; constitutional_modification_supported: false; self_certification_supported: false; integrity_hash: string }>;
export type GovernanceConstitutionalInput = Readonly<{ scenario?: GovernanceConstitutionalScenario; tenant_id?: string; mission_id?: string }>;
export type GovernanceConstitutionalResult = Readonly<{ governance_constitutional_certification_version: "governance-constitutional-certification/v10.15.4"; certification_identifier: "GovernanceConstitutionalCertification"; status: GovernanceConstitutionalStatus; api_surface: GovernanceConstitutionalApiSurface; record: GovernanceConstitutionalCertificationRecord; governance_supremacy: GovernanceSupremacyValidation; constitutional_enforcement: ConstitutionalEnforcementValidation; authority_restriction: AuthorityRestrictionValidation; tenant_isolation: TenantIsolationGovernanceValidation; approval_enforcement: ApprovalEnforcementValidation; bypass_escalation_detection: BypassEscalationDetection; certification_report: GovernanceConstitutionalCertificationReport; authority_compliance_report: AuthorityComplianceReport; widgets: readonly GovernanceConstitutionalWidget[]; validation_tests: readonly GovernanceConstitutionalCertificationTest[]; failures: readonly GovernanceConstitutionalFailure[]; governed: boolean; constitutional: boolean; advisory_only: boolean; tenant_safe: boolean; approval_enforced: boolean; production_ready: boolean; replay_hash: string; integrity_hash: string }>;
export type GovernanceConstitutionalValidationResult = Readonly<{ certification_id: string | null; valid: boolean; status: GovernanceConstitutionalStatus; failures: readonly GovernanceConstitutionalFailure[]; replay_hash_valid: boolean; integrity_hash_valid: boolean; certification_hash: string }>;
export type GovernanceConstitutionalObservability = Readonly<{ certification_id: string; status: GovernanceConstitutionalStatus; failed_tests: number; failures: readonly GovernanceConstitutionalFailure[]; governed: boolean; constitutional: boolean; advisory_only: boolean; tenant_safe: boolean; approval_enforced: boolean; production_ready: boolean; integrity_hash: string }>;
export type GovernanceConstitutionalContract = Readonly<{ doctrine: Readonly<{ version: "governance-constitutional-certification/v10.15.4"; widgets: readonly GovernanceConstitutionalWidget[]; permitted_authority: readonly PermittedAdaptiveAuthority[]; prohibited_authority: readonly ProhibitedAdaptiveAuthority[]; governance_supremacy_required: true; constitutional_supremacy_required: true; tenant_isolation_required: true; operator_supremacy_required: true; fail_closed_required: true }>; result: GovernanceConstitutionalResult; validation: GovernanceConstitutionalValidationResult; observability: GovernanceConstitutionalObservability }>;
