export type InstitutionalMemoryDecision = "INSTITUTIONAL_MEMORY_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type KnowledgeRelationshipKind = "MISSION" | "DECISION" | "EVIDENCE" | "RISK" | "RECOMMENDATION" | "OUTCOME" | "LESSON" | "PATTERN" | "KNOWLEDGE_ASSET";
export type LearnedPatternCategory = "OPERATIONAL" | "DECISION" | "RISK" | "RECOVERY" | "ESCALATION" | "MISSION" | "RESOURCE" | "GOVERNANCE" | "SIMULATION" | "ORGANIZATIONAL";
export type InstitutionalMemoryFailure =
  | "MC_1_MISSION_MANAGEMENT_INVALID" | "MC_2_SCENARIO_PLANNING_INVALID" | "MC_3_DECISION_SUPPORT_INVALID" | "MC_4_PORTFOLIO_MANAGEMENT_INVALID" | "MC_5_OPERATIONAL_EVIDENCE_REPLAY_INVALID" | "MC_6_DIGITAL_TWIN_INVALID" | "MC_7_SIMULATION_INVALID" | "MC_8_RISK_ASSESSMENT_INVALID" | "MC_9_RECOMMENDATION_INTELLIGENCE_INVALID" | "MC_10_OPERATOR_DASHBOARD_INVALID" | "CAF_MEMORY_ENGINE_INVALID" | "CAF_PLANNING_ENGINE_INVALID"
  | "KNOWLEDGE_CAPTURE_MISSING" | "LESSON_CAPTURE_MISSING" | "KNOWLEDGE_VALIDATION_MISSING" | "KNOWLEDGE_APPROVAL_MISSING" | "KNOWLEDGE_CLASSIFICATION_MISSING" | "KNOWLEDGE_PUBLICATION_MISSING" | "KNOWLEDGE_RETIREMENT_MISSING" | "MEMORY_REPOSITORY_MISSING" | "REPOSITORY_NOT_AUTHORITATIVE" | "KNOWLEDGE_GRAPH_MISSING" | "GRAPH_NODE_EVIDENCE_MISSING" | "PATTERN_CATALOG_MISSING" | "PATTERNS_NOT_EVIDENCE_BACKED" | "KNOWLEDGE_LINEAGE_MISSING" | "LINEAGE_NOT_REPRODUCIBLE" | "KNOWLEDGE_VALIDATION_ENGINE_MISSING" | "EVIDENCE_VERIFICATION_MISSING" | "DUPLICATE_DETECTION_MISSING" | "CONFLICT_ANALYSIS_MISSING" | "CONFIDENCE_EVALUATION_MISSING" | "GOVERNANCE_APPROVAL_MISSING" | "AUTHORITY_VERIFICATION_MISSING" | "LEARNING_ENGINE_MISSING" | "LEARNING_OUTPUTS_NOT_ADVISORY" | "KNOWLEDGE_SEARCH_MISSING" | "SEARCH_NON_DETERMINISTIC" | "KNOWLEDGE_GOVERNANCE_MISSING" | "LIFECYCLE_APPROVAL_MISSING" | "VERSIONING_MISSING" | "ACCESS_CONTROL_MISSING" | "KNOWLEDGE_REPORTS_MISSING" | "KNOWLEDGE_EVIDENCE_MISSING" | "KNOWLEDGE_WITHOUT_EVIDENCE_PUBLISHED" | "KNOWLEDGE_EVIDENCE_MUTATED" | "HISTORICAL_EVIDENCE_MUTATED" | "OPERATIONAL_DECISION_CREATED" | "EXECUTION_INITIATED" | "AUTONOMOUS_LEARNING_ATTEMPTED" | "GOVERNANCE_BYPASSED" | "TRACEABILITY_INCOMPLETE" | "INSTITUTIONAL_MEMORY_APIS_MISSING" | "INSTITUTIONAL_MEMORY_QUALIFICATION_FAILED";
export type InstitutionalMemoryScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | InstitutionalMemoryFailure;
export type InstitutionalMemoryInput = Readonly<{ scenario?: InstitutionalMemoryScenario; seed?: string; tenant_id?: string; knowledge_id?: string }>;
export type OrganizationalKnowledgeCapture = Readonly<{ capture_id: string; lesson_capture: boolean; knowledge_validation: boolean; knowledge_approval: boolean; knowledge_classification: boolean; knowledge_publication: boolean; knowledge_retirement: boolean; validated_operational_learning: boolean; integrity_hash: string }>;
export type InstitutionalMemoryRepository = Readonly<{ repository_id: string; lessons_learned: boolean; operational_practices: boolean; mission_outcomes: boolean; decision_outcomes: boolean; failure_analysis: boolean; recovery_procedures: boolean; governance_decisions: boolean; operational_policies: boolean; organizational_experience: boolean; authoritative_repository: boolean; integrity_hash: string }>;
export type KnowledgeGraph = Readonly<{ graph_id: string; relationships: readonly KnowledgeRelationshipKind[]; mission_to_knowledge_asset_path: boolean; evidence_backed_nodes: boolean; governed_relationships: boolean; enterprise_relationships: boolean; integrity_hash: string }>;
export type LearnedPatternCatalog = Readonly<{ catalog_id: string; categories: readonly LearnedPatternCategory[]; recurring_behaviors: boolean; reusable_patterns: boolean; evidence_backed_patterns: boolean; pattern_analysis_reports: boolean; integrity_hash: string }>;
export type KnowledgeLineage = Readonly<{ lineage_id: string; source_mission: boolean; evidence_references: boolean; replay_references: boolean; decision_package_references: boolean; simulation_references: boolean; validation_history: boolean; approval_history: boolean; retirement_history: boolean; reproducible_from_cci_event_history: boolean; integrity_hash: string }>;
export type KnowledgeValidation = Readonly<{ validation_id: string; evidence_verification: boolean; duplicate_detection: boolean; conflict_analysis: boolean; confidence_evaluation: boolean; governance_approval: boolean; constitution_compliance: boolean; authority_verification: boolean; prevents_unsupported_entries: boolean; integrity_hash: string }>;
export type OrganizationalLearningEngine = Readonly<{ learning_id: string; best_practices: boolean; operational_guidelines: boolean; failure_prevention_guidance: boolean; recovery_guidance: boolean; mission_templates: boolean; operational_checklists: boolean; risk_mitigation_practices: boolean; decision_heuristics: boolean; advisory_only: boolean; integrity_hash: string }>;
export type KnowledgeSearch = Readonly<{ search_id: string; semantic_search: boolean; evidence_search: boolean; mission_search: boolean; pattern_search: boolean; relationship_navigation: boolean; timeline_search: boolean; similarity_search: boolean; governance_search: boolean; deterministic_retrieval: boolean; integrity_hash: string }>;
export type KnowledgeGovernance = Readonly<{ governance_id: string; versioning: boolean; approval: boolean; publication: boolean; deprecation: boolean; retirement: boolean; supersession: boolean; audit: boolean; access_control: boolean; governed_lifecycle: boolean; integrity_hash: string }>;
export type KnowledgeReports = Readonly<{ report_id: string; organizational_learning_reports: boolean; best_practice_catalog: boolean; validation_reports: boolean; pattern_analysis_reports: boolean; audit_reports: boolean; reproducible_reports: boolean; integrity_hash: string }>;
export type KnowledgeEvidence = Readonly<{ evidence_id: string; knowledge_identifier: boolean; source_mission: boolean; evidence_references: boolean; replay_references: boolean; decision_references: boolean; validation_evidence: boolean; approval_evidence: boolean; version_history: boolean; confidence_assessment: boolean; constitutional_compliance_status: boolean; lineage_references: boolean; immutable: boolean; integrity_hash: string }>;
export type InstitutionalMemoryApis = Readonly<{ api_id: string; capture_api: boolean; repository_api: boolean; graph_api: boolean; pattern_api: boolean; lineage_api: boolean; validation_api: boolean; learning_api: boolean; search_api: boolean; governance_api: boolean; evidence_api: boolean; stable: boolean; integrity_hash: string }>;
export type InstitutionalMemoryReadiness = Readonly<{ readiness_id: string; decision: InstitutionalMemoryDecision; phase_ready: boolean; upstream_ready: boolean; capture_ready: boolean; repository_ready: boolean; graph_ready: boolean; patterns_ready: boolean; lineage_ready: boolean; validation_ready: boolean; learning_ready: boolean; search_ready: boolean; governance_ready: boolean; reports_ready: boolean; evidence_ready: boolean; apis_ready: boolean; advisory_only: boolean; no_operational_decisions: boolean; no_execution: boolean; immutable_history_preserved: boolean; evidence_first: boolean; governance_enforced: boolean; deterministic_provenance: boolean; no_autonomous_learning: boolean; qualification_ready: boolean; failures: readonly InstitutionalMemoryFailure[]; integrity_hash: string }>;
export type InstitutionalMemoryResult = Readonly<{ phase_version: "institutional-memory/mc-11"; phase_identifier: "InstitutionalMemory"; upstream_refs: readonly string[]; tenant_id: string; knowledge_id: string; capture: OrganizationalKnowledgeCapture; repository: InstitutionalMemoryRepository; graph: KnowledgeGraph; patterns: LearnedPatternCatalog; lineage: KnowledgeLineage; validation: KnowledgeValidation; learning: OrganizationalLearningEngine; search: KnowledgeSearch; governance: KnowledgeGovernance; reports: KnowledgeReports; evidence: KnowledgeEvidence; apis: InstitutionalMemoryApis; readiness: InstitutionalMemoryReadiness; replay_hash: string; integrity_hash: string }>;
export type InstitutionalMemoryValidation = Readonly<{ valid: boolean; decision: InstitutionalMemoryDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; capture_valid: boolean; repository_valid: boolean; graph_valid: boolean; patterns_valid: boolean; lineage_valid: boolean; validation_valid: boolean; learning_valid: boolean; search_valid: boolean; governance_valid: boolean; reports_valid: boolean; evidence_valid: boolean; apis_valid: boolean; readiness_valid: boolean; failures: readonly InstitutionalMemoryFailure[]; integrity_hash: string }>;
export type InstitutionalMemoryBundle = Readonly<{ doctrine: Readonly<{ version: "institutional-memory/mc-11"; owns_organizational_knowledge_capture: true; owns_institutional_memory_repository: true; owns_knowledge_graph_and_pattern_catalog: true; owns_knowledge_lineage_validation_search_governance: true; transforms_evidence_into_durable_knowledge: true; advisory_only: true; immutable_history_required: true; no_autonomous_learning: true; qualification_gate: "Institutional Memory Qualification Gate" }>; result: InstitutionalMemoryResult; validation: InstitutionalMemoryValidation }>;
