export type MissionRecommendationDecision = "MISSION_RECOMMENDATION_INTELLIGENCE_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type RecommendationLifecycleState = "GENERATED" | "VALIDATED" | "PUBLISHED" | "UPDATED" | "SUPERSEDED" | "WITHDRAWN" | "ARCHIVED";
export type RecommendationPriority = "LOW" | "MEDIUM" | "HIGH" | "URGENT";
export type MissionRecommendationFailure =
  | "MC_1_MISSION_MANAGEMENT_INVALID" | "MC_2_SCENARIO_PLANNING_INVALID" | "MC_3_DECISION_SUPPORT_INVALID" | "MC_4_PORTFOLIO_MANAGEMENT_INVALID" | "MC_5_OPERATIONAL_EVIDENCE_REPLAY_INVALID" | "MC_6_DIGITAL_TWIN_INVALID" | "MC_7_SIMULATION_INVALID" | "MC_8_RISK_ASSESSMENT_INVALID"
  | "RECOMMENDATION_ENGINE_MISSING" | "RECOMMENDATION_GENERATION_NON_DETERMINISTIC" | "RECOMMENDATION_PRIORITIZATION_MISSING" | "RECOMMENDATION_SCORING_MISSING" | "RECOMMENDATION_RANKING_MISSING" | "RECOMMENDATION_REFINEMENT_MISSING" | "RECOMMENDATION_SUPPRESSION_MISSING" | "RECOMMENDATION_LIFECYCLE_MISSING" | "RECOMMENDATION_ANALYSIS_MISSING" | "MISSION_OBJECTIVE_ANALYSIS_MISSING" | "RISK_REDUCTION_ANALYSIS_MISSING" | "RESOURCE_OPTIMIZATION_MISSING" | "TIMELINE_OPTIMIZATION_MISSING" | "DEPENDENCY_OPTIMIZATION_MISSING" | "EFFICIENCY_ANALYSIS_MISSING" | "CONFIDENCE_ESTIMATION_MISSING" | "RECOMMENDATION_EXPLANATION_MISSING" | "SUPPORTING_EVIDENCE_MISSING" | "ASSUMPTIONS_MISSING" | "CONSTRAINTS_MISSING" | "BENEFITS_MISSING" | "DRAWBACKS_MISSING" | "ALTERNATIVES_MISSING" | "CONFIDENCE_SCORE_MISSING" | "RECOMMENDATION_GOVERNANCE_MISSING" | "CONSTITUTIONAL_VALIDATION_FAILED" | "POLICY_VALIDATION_FAILED" | "AUTHORITY_VALIDATION_FAILED" | "SAFETY_VALIDATION_FAILED" | "EVIDENCE_COMPLETENESS_FAILED" | "EXPLAINABILITY_VALIDATION_FAILED" | "RECOMMENDATION_PRIORITIZATION_NOT_TRANSPARENT" | "RECOMMENDATION_CONFIDENCE_MISSING" | "CONFIDENCE_INPUTS_INCOMPLETE" | "RECOMMENDATION_LIFECYCLE_NOT_GOVERNED" | "RECOMMENDATION_FEED_MISSING" | "RECOMMENDATION_REPORTS_MISSING" | "RECOMMENDATION_EVIDENCE_MISSING" | "RECOMMENDATION_EVIDENCE_MUTABLE" | "RECOMMENDATION_LINEAGE_INCOMPLETE" | "AUTONOMOUS_EXECUTION_ATTEMPTED" | "MISSION_MUTATION_ATTEMPTED" | "OPERATOR_AUTHORITY_BYPASSED" | "GOVERNANCE_OVERRIDE_ATTEMPTED" | "UNCERTAINTY_CONCEALED" | "SUPPORTING_EVIDENCE_REMOVED" | "RECOMMENDATION_APIS_MISSING" | "MISSION_RECOMMENDATION_INTELLIGENCE_QUALIFICATION_FAILED";
export type MissionRecommendationScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | MissionRecommendationFailure;
export type MissionRecommendationInput = Readonly<{ scenario?: MissionRecommendationScenario; seed?: string; tenant_id?: string; recommendation_id?: string }>;
export type RecommendationEngine = Readonly<{ engine_id: string; generation: boolean; prioritization: boolean; scoring: boolean; ranking: boolean; refinement: boolean; suppression: boolean; lifecycle: boolean; deterministic_generation: boolean; advisory_only: boolean; no_action_execution: boolean; integrity_hash: string }>;
export type RecommendationAnalysis = Readonly<{ analysis_id: string; mission_objectives: boolean; risk_reduction: boolean; resource_optimization: boolean; timeline_optimization: boolean; dependency_optimization: boolean; operational_efficiency: boolean; confidence_estimation: boolean; integrity_hash: string }>;
export type RecommendationExplanation = Readonly<{ explanation_id: string; supporting_evidence: boolean; assumptions: boolean; constraints: boolean; expected_benefits: boolean; potential_drawbacks: boolean; alternative_recommendations: boolean; confidence_score: boolean; auditable: boolean; integrity_hash: string }>;
export type RecommendationGovernance = Readonly<{ governance_id: string; constitutional_validation: boolean; policy_evaluation: boolean; authority_validation: boolean; safety_verification: boolean; evidence_completeness: boolean; explainability_verification: boolean; publication_gate: boolean; failed_recommendations_suppressed: boolean; integrity_hash: string }>;
export type RecommendationPrioritization = Readonly<{ prioritization_id: string; mission_objectives: boolean; risk_exposure: boolean; resource_availability: boolean; mission_urgency: boolean; portfolio_priorities: boolean; organizational_policy: boolean; strategic_alignment: boolean; transparent_ranking: boolean; integrity_hash: string }>;
export type RecommendationConfidence = Readonly<{ confidence_id: string; evidence_quality: boolean; evidence_completeness: boolean; simulation_agreement: boolean; replay_agreement: boolean; digital_twin_consistency: boolean; risk_certainty: boolean; decision_support_confidence: boolean; confidence: number; integrity_hash: string }>;
export type RecommendationLifecycle = Readonly<{ lifecycle_id: string; states: readonly RecommendationLifecycleState[]; generated: boolean; validated: boolean; published: boolean; updated: boolean; superseded: boolean; withdrawn: boolean; archived: boolean; governed_state_transitions: boolean; integrity_hash: string }>;
export type RecommendationFeed = Readonly<{ feed_id: string; recommendation_id: string; mission: string; priority: RecommendationPriority; confidence: number; supporting_evidence: boolean; risk_summary: boolean; expected_impact: boolean; status: RecommendationLifecycleState; continuously_updated: boolean; advisory_only: boolean; integrity_hash: string }>;
export type RecommendationReports = Readonly<{ report_id: string; recommendation_summary: boolean; evidence_references: boolean; simulation_references: boolean; risk_analysis: boolean; decision_justification: boolean; expected_outcomes: boolean; alternative_options: boolean; immutable_audit_record: boolean; integrity_hash: string }>;
export type RecommendationEvidence = Readonly<{ evidence_id: string; recommendation_lineage: boolean; evidence_graph: boolean; supporting_artifacts: boolean; evaluation_history: boolean; governance_decisions: boolean; confidence_calculations: boolean; immutable: boolean; complete_lineage: boolean; integrity_hash: string }>;
export type RecommendationApis = Readonly<{ api_id: string; recommendation_api: boolean; analysis_api: boolean; explanation_api: boolean; governance_api: boolean; prioritization_api: boolean; confidence_api: boolean; lifecycle_api: boolean; feed_api: boolean; report_api: boolean; evidence_api: boolean; stable: boolean; integrity_hash: string }>;
export type MissionRecommendationReadiness = Readonly<{ readiness_id: string; decision: MissionRecommendationDecision; phase_ready: boolean; upstream_ready: boolean; engine_ready: boolean; analysis_ready: boolean; explanation_ready: boolean; governance_ready: boolean; prioritization_ready: boolean; confidence_ready: boolean; lifecycle_ready: boolean; feed_ready: boolean; reports_ready: boolean; evidence_ready: boolean; apis_ready: boolean; deterministic: boolean; advisory_only: boolean; no_execution: boolean; no_state_mutation: boolean; governance_enforced: boolean; evidence_lineage_complete: boolean; qualification_ready: boolean; failures: readonly MissionRecommendationFailure[]; integrity_hash: string }>;
export type MissionRecommendationResult = Readonly<{ phase_version: "mission-recommendation-intelligence/mc-9"; phase_identifier: "MissionRecommendationIntelligence"; upstream_refs: readonly string[]; tenant_id: string; recommendation_id: string; engine: RecommendationEngine; analysis: RecommendationAnalysis; explanation: RecommendationExplanation; governance: RecommendationGovernance; prioritization: RecommendationPrioritization; confidence: RecommendationConfidence; lifecycle: RecommendationLifecycle; feed: RecommendationFeed; reports: RecommendationReports; evidence: RecommendationEvidence; apis: RecommendationApis; readiness: MissionRecommendationReadiness; replay_hash: string; integrity_hash: string }>;
export type MissionRecommendationValidation = Readonly<{ valid: boolean; decision: MissionRecommendationDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; engine_valid: boolean; analysis_valid: boolean; explanation_valid: boolean; governance_valid: boolean; prioritization_valid: boolean; confidence_valid: boolean; lifecycle_valid: boolean; feed_valid: boolean; reports_valid: boolean; evidence_valid: boolean; apis_valid: boolean; readiness_valid: boolean; failures: readonly MissionRecommendationFailure[]; integrity_hash: string }>;
export type MissionRecommendationBundle = Readonly<{ doctrine: Readonly<{ version: "mission-recommendation-intelligence/mc-9"; owns_recommendation_engine: true; owns_recommendation_analysis: true; owns_recommendation_explanation: true; owns_recommendation_governance: true; owns_recommendation_prioritization_confidence_lifecycle: true; consumes_mc_1_through_mc_8: true; recommendations_are_advisory_only: true; autonomous_execution_prohibited: true; governance_validation_required_before_publication: true; qualification_gate: "Mission Recommendation Intelligence Qualification Gate" }>; result: MissionRecommendationResult; validation: MissionRecommendationValidation }>;
