export type MissionManagementDecision = "MISSION_MANAGEMENT_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type MissionLifecycleState = "DRAFT" | "REGISTERED" | "DEFINED" | "VALIDATING" | "APPROVED" | "SCHEDULED" | "READY" | "ACTIVE" | "PAUSED" | "BLOCKED" | "DEGRADED" | "RECOVERING" | "COMPLETING" | "COMPLETED" | "CANCELLED" | "RETIRED";
export type MissionProjectionPhase = "Definition" | "Validation" | "Planning" | "Readiness" | "Execution" | "Intervention" | "Completion" | "Closure";
export type MissionLineageStatus = "ROOT" | "DERIVED" | "BRANCHED" | "SUPERSEDED" | "RETIRED" | "HISTORICAL";
export type MissionManagementFailure =
  | "W1_IDENTITY_INVALID" | "W1_REGISTRY_INVALID" | "W1_CONFIGURATION_INVALID" | "W1_SECURITY_INVALID" | "W1_OBSERVABILITY_INVALID" | "W1_CAF_RUNTIME_INVALID" | "W2_LIFECYCLE_INVALID" | "W2_AUTHORITY_INVALID" | "W2_POLICY_INVALID" | "W2_SAFETY_INVALID" | "W2_PLANNING_INVALID" | "W2_MEMORY_INVALID" | "W2_RUNTIME_INVALID" | "W2_EVIDENCE_INVALID" | "W2_REPLAY_INVALID" | "W2_CERTIFICATION_INVALID" | "W2_OPERATOR_CONSOLE_INVALID"
  | "MISSION_REGISTRY_MISSING" | "MISSION_REGISTRY_TENANT_ISOLATION_FAILED" | "MISSION_IDENTIFIERS_MUTABLE" | "MISSION_LIFECYCLE_MISSING" | "MISSION_LIFECYCLE_STATE_COUNT_INVALID" | "MISSION_LIFECYCLE_ALTERNATE_TERMINOLOGY" | "MISSION_TRANSITION_NON_DETERMINISTIC" | "MISSION_TRANSITION_GOVERNANCE_BYPASSED" | "MISSION_TEMPLATES_MISSING" | "MISSION_TEMPLATE_GOVERNANCE_MISSING" | "MISSION_OBJECTIVES_MISSING" | "MISSION_OBJECTIVE_EVIDENCE_MISSING" | "MISSION_ASSIGNMENT_MISSING" | "MISSION_ASSIGNMENT_QUALIFICATION_BYPASSED" | "MISSION_DEPENDENCIES_MISSING" | "MISSION_DEPENDENCY_CYCLE_UNDETECTED" | "MISSION_TIMELINE_MISSING" | "MISSION_TIMELINE_REPLAY_INVALID" | "MISSION_EVIDENCE_MISSING" | "MISSION_EVIDENCE_NOT_IMMUTABLE" | "MISSION_RULES_MISSING" | "MISSION_RULES_BYPASSED" | "MISSION_LINEAGE_MISSING" | "MISSION_LINEAGE_MUTABLE" | "MISSION_PROJECTION_MISSING" | "MISSION_PROJECTION_PHASE_COUNT_INVALID" | "MISSION_APIS_MISSING" | "MISSION_QUERY_NON_DETERMINISTIC" | "MISSION_OBSERVABILITY_MISSING" | "MISSION_QUALIFICATION_FAILED";
export type MissionManagementScenario = "BASELINE" | "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | MissionManagementFailure;
export type MissionManagementInput = Readonly<{ scenario?: MissionManagementScenario; seed?: string; mission_id?: string; tenant_id?: string }>;
export type MissionRegistry = Readonly<{ registry_id: string; mission_registration: boolean; mission_discovery: boolean; mission_lookup: boolean; mission_ownership: boolean; version_history: boolean; metadata: boolean; tenant_isolation: boolean; namespace_support: boolean; immutable_identifiers: boolean; mission_catalog: boolean; registry_queries: boolean; integrity_hash: string }>;
export type MissionLifecycleEngine = Readonly<{ engine_id: string; states: readonly MissionLifecycleState[]; transition_validation: boolean; constitutional_enforcement: boolean; authority_verification: boolean; policy_verification: boolean; safety_verification: boolean; operator_approval: boolean; transition_evidence: boolean; replay_compatibility: boolean; deterministic_transitions: boolean; fail_closed_validation: boolean; immutable_transition_history: boolean; integrity_hash: string }>;
export type MissionProjection = Readonly<{ projection_id: string; phases: readonly MissionProjectionPhase[]; derived_from_lifecycle_only: boolean; dashboard_projection: boolean; operational_views: boolean; planning_projection: boolean; reporting_projection: boolean; lifecycle_authoritative: boolean; no_alternate_model: boolean; integrity_hash: string }>;
export type MissionLineage = Readonly<{ lineage_id: string; statuses: readonly MissionLineageStatus[]; ancestry: boolean; derivation: boolean; branching: boolean; supersession: boolean; retirement: boolean; historical_lineage: boolean; immutable_lineage: boolean; no_alternate_lineage: boolean; integrity_hash: string }>;
export type MissionTemplates = Readonly<{ template_registry_id: string; standard_definitions: boolean; parameterized_templates: boolean; template_inheritance: boolean; version_management: boolean; template_approval: boolean; template_governance: boolean; template_library: boolean; template_validator: boolean; integrity_hash: string }>;
export type MissionObjectives = Readonly<{ objective_registry_id: string; objective_definition: boolean; objective_hierarchy: boolean; success_criteria: boolean; completion_criteria: boolean; priority: boolean; objective_dependencies: boolean; objective_evidence: boolean; objective_graph: boolean; objective_validation: boolean; integrity_hash: string }>;
export type MissionAssignment = Readonly<{ assignment_service_id: string; operators: boolean; teams: boolean; caf_agents: boolean; capabilities: boolean; resources: boolean; organizations: boolean; authority_validation: boolean; policy_validation: boolean; availability_validation: boolean; qualification_validation: boolean; assignment_records: boolean; assignment_history: boolean; integrity_hash: string }>;
export type MissionDependencies = Readonly<{ dependency_service_id: string; predecessor_missions: boolean; successor_missions: boolean; blocking_missions: boolean; prerequisite_validation: boolean; dependency_graph: boolean; cycle_detection: boolean; dependency_evidence: boolean; dependency_reports: boolean; integrity_hash: string }>;
export type MissionTimeline = Readonly<{ timeline_service_id: string; scheduling: boolean; milestones: boolean; checkpoints: boolean; projected_timeline: boolean; historical_timeline: boolean; timeline_replay: boolean; execution_history: boolean; timeline_graph: boolean; timeline_records: boolean; integrity_hash: string }>;
export type MissionEvidenceIntegration = Readonly<{ integration_id: string; lifecycle_events: boolean; approvals: boolean; assignments: boolean; objective_completion: boolean; dependency_validation: boolean; constitutional_decisions: boolean; operator_actions: boolean; replay_references: boolean; immutable_event_evidence: boolean; evidence_packages: boolean; integrity_hash: string }>;
export type ConstitutionalMissionRules = Readonly<{ rules_id: string; lifecycle_validation: boolean; transition_legality: boolean; authority_validation: boolean; policy_validation: boolean; safety_validation: boolean; operator_supremacy: boolean; tenant_isolation: boolean; governance_compliance: boolean; bypass_prevention: boolean; integrity_hash: string }>;
export type MissionApis = Readonly<{ api_id: string; mission_api: boolean; registry_api: boolean; timeline_api: boolean; assignment_api: boolean; objective_api: boolean; template_api: boolean; dependency_api: boolean; lifecycle_api: boolean; query_api: boolean; deterministic_queries: boolean; stable: boolean; integrity_hash: string }>;
export type MissionObservability = Readonly<{ observability_id: string; lifecycle_metrics: boolean; assignment_metrics: boolean; objective_metrics: boolean; dependency_metrics: boolean; timeline_metrics: boolean; transition_latency: boolean; constitutional_violations: boolean; audit_metrics: boolean; health_metrics: boolean; integrity_hash: string }>;
export type MissionManagementReadiness = Readonly<{ readiness_id: string; decision: MissionManagementDecision; phase_ready: boolean; upstream_ready: boolean; registry_ready: boolean; lifecycle_ready: boolean; projection_ready: boolean; lineage_ready: boolean; templates_ready: boolean; objectives_ready: boolean; assignment_ready: boolean; dependencies_ready: boolean; timeline_ready: boolean; evidence_ready: boolean; rules_ready: boolean; apis_ready: boolean; observability_ready: boolean; qualification_ready: boolean; failures: readonly MissionManagementFailure[]; integrity_hash: string }>;
export type MissionManagementResult = Readonly<{ phase_version: "mission-management/mc-1"; phase_identifier: "MissionManagement"; upstream_refs: readonly string[]; mission_id: string; tenant_id: string; registry: MissionRegistry; lifecycle: MissionLifecycleEngine; projection: MissionProjection; lineage: MissionLineage; templates: MissionTemplates; objectives: MissionObjectives; assignment: MissionAssignment; dependencies: MissionDependencies; timeline: MissionTimeline; evidence: MissionEvidenceIntegration; rules: ConstitutionalMissionRules; apis: MissionApis; observability: MissionObservability; readiness: MissionManagementReadiness; replay_hash: string; integrity_hash: string }>;
export type MissionManagementValidation = Readonly<{ valid: boolean; decision: MissionManagementDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; registry_valid: boolean; lifecycle_valid: boolean; projection_valid: boolean; lineage_valid: boolean; templates_valid: boolean; objectives_valid: boolean; assignment_valid: boolean; dependencies_valid: boolean; timeline_valid: boolean; evidence_valid: boolean; rules_valid: boolean; apis_valid: boolean; observability_valid: boolean; readiness_valid: boolean; failures: readonly MissionManagementFailure[]; integrity_hash: string }>;
export type MissionManagementBundle = Readonly<{ doctrine: Readonly<{ version: "mission-management/mc-1"; owns_canonical_mission_model: true; owns_mission_registry: true; owns_mission_lifecycle: true; owns_mission_templates: true; owns_mission_objectives: true; owns_mission_assignment: true; owns_mission_dependencies: true; owns_mission_timeline: true; owns_mission_evidence_integration: true; no_additional_lifecycle_states: true; no_alternate_lifecycle_models: true; qualification_gate: "Mission Management Qualification Gate" }>; result: MissionManagementResult; validation: MissionManagementValidation }>;
