export type MonitoringExperienceDecision = "MONITORING_EXPERIENCE_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type AlertSeverity = "INFO" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type MonitoringExperienceFailure =
  | "MC_1_MISSION_MANAGEMENT_INVALID" | "MC_4_PORTFOLIO_MANAGEMENT_INVALID" | "MC_5_OPERATIONAL_EVIDENCE_INVALID" | "MC_6_DIGITAL_TWIN_INVALID" | "MC_8_RISK_ASSESSMENT_INVALID" | "MC_13A_MONITORING_PRIMITIVES_INVALID" | "MC_10_OPERATOR_DASHBOARD_INVALID" | "MC_12_OPERATIONAL_INTELLIGENCE_INVALID"
  | "MONITORING_AGGREGATOR_MISSING" | "MONITORING_PRIMITIVES_NOT_CONSUMED" | "SYNTHETIC_MONITORING_USED" | "UNQUALIFIED_MONITORING_DATA_USED"
  | "ALERT_ENGINE_MISSING" | "ALERT_REGISTRY_MISSING" | "ALERT_CATEGORIZATION_MISSING" | "SEVERITY_CLASSIFICATION_MISSING" | "ALERT_HISTORY_MISSING" | "ALERT_EVIDENCE_MISSING" | "DUPLICATE_DETECTION_MISSING" | "ADVISORY_ALERT_BEHAVIOR_MISSING"
  | "SLA_ENGINE_MISSING" | "SLA_DASHBOARD_MISSING" | "SLA_COMPLIANCE_RECORDS_MISSING" | "SLA_VIOLATION_DETECTION_MISSING" | "SLA_EVIDENCE_MISSING"
  | "ANALYTICS_ENGINE_MISSING" | "TREND_ANALYSIS_MISSING" | "OPERATIONAL_METRICS_MISSING" | "BOTTLENECK_IDENTIFICATION_MISSING" | "PERFORMANCE_SUMMARIES_MISSING"
  | "HEALTH_REPORTING_MISSING" | "HEALTH_EVIDENCE_MISSING" | "MISSION_HEALTH_MISSING" | "PORTFOLIO_HEALTH_MISSING" | "RUNTIME_HEALTH_MISSING"
  | "ALERT_CENTER_MISSING" | "ALERT_FILTERS_MISSING" | "EVIDENCE_NAVIGATION_MISSING" | "REPLAY_LINKAGE_MISSING"
  | "LIVE_DASHBOARD_MISSING" | "DASHBOARD_VIEWS_MISSING" | "DASHBOARD_EVIDENCE_MISSING" | "DASHBOARD_PERFORMANCE_FAILED"
  | "EXECUTION_ATTEMPTED" | "MISSION_MUTATION_ATTEMPTED" | "RUNTIME_COMMAND_ATTEMPTED" | "AUTOMATION_INVOKED" | "ALERT_SELF_ACKNOWLEDGED" | "GOVERNANCE_BYPASS_ATTEMPTED" | "MONITORING_EXPERIENCE_QUALIFICATION_FAILED";
export type MonitoringExperienceScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | MonitoringExperienceFailure;
export type MonitoringExperienceInput = Readonly<{ scenario?: MonitoringExperienceScenario; seed?: string; tenant_id?: string; experience_id?: string }>;
export type MonitoringAggregator = Readonly<{ aggregator_id: string; consumes_mc13a_primitives: boolean; consumes_mission_lifecycle: boolean; consumes_portfolio_registry: boolean; consumes_operational_evidence: boolean; consumes_digital_twin: boolean; consumes_risk_assessment: boolean; qualified_data_only: boolean; deterministic_aggregation: boolean; integrity_hash: string }>;
export type AlertManagementService = Readonly<{ alert_registry_id: string; severities: readonly AlertSeverity[]; alert_generation: boolean; alert_categorization: boolean; severity_classification: boolean; alert_acknowledgement_tracking: boolean; escalation_recommendations: boolean; alert_history: boolean; alert_evidence: boolean; suppression_policies: boolean; duplicate_detection: boolean; advisory_only: boolean; integrity_hash: string }>;
export type SlaMonitoringService = Readonly<{ sla_id: string; availability_monitoring: boolean; response_time_tracking: boolean; throughput_monitoring: boolean; error_rate_monitoring: boolean; compliance_evaluation: boolean; trend_analysis: boolean; violation_detection: boolean; compliance_evidence: boolean; dashboard: boolean; reports: boolean; integrity_hash: string }>;
export type OperationalAnalyticsService = Readonly<{ analytics_id: string; trend_analysis: boolean; capacity_utilization: boolean; resource_efficiency: boolean; mission_throughput: boolean; performance_summaries: boolean; bottleneck_identification: boolean; historical_comparison: boolean; operational_metrics: boolean; evidence_backed: boolean; integrity_hash: string }>;
export type HealthReportingService = Readonly<{ health_report_id: string; mission_health: boolean; runtime_health: boolean; infrastructure_health: boolean; service_health: boolean; portfolio_health: boolean; resource_health: boolean; health_history: boolean; health_evidence: boolean; integrity_hash: string }>;
export type AlertCenter = Readonly<{ center_id: string; active_alerts: boolean; alert_filters: boolean; severity_grouping: boolean; mission_grouping: boolean; portfolio_grouping: boolean; historical_alerts: boolean; evidence_navigation: boolean; replay_linkage: boolean; alert_search: boolean; integrity_hash: string }>;
export type LiveOperationsDashboard = Readonly<{ dashboard_id: string; active_missions: boolean; mission_health: boolean; runtime_health: boolean; resource_utilization: boolean; alert_summaries: boolean; sla_status: boolean; digital_twin_synchronization: boolean; risk_indicators: boolean; portfolio_status: boolean; service_availability: boolean; dashboard_performance: boolean; integrity_hash: string }>;
export type MonitoringExperienceEvidence = Readonly<{ evidence_id: string; alert_evidence: boolean; sla_evidence: boolean; analytics_evidence: boolean; health_evidence: boolean; dashboard_evidence: boolean; monitoring_timeline: boolean; monitoring_reports: boolean; deterministic_replay: boolean; immutable: boolean; integrity_hash: string }>;
export type MonitoringExperienceReadiness = Readonly<{ readiness_id: string; decision: MonitoringExperienceDecision; phase_ready: boolean; upstream_ready: boolean; downstream_ready: boolean; aggregator_ready: boolean; alerts_ready: boolean; sla_ready: boolean; analytics_ready: boolean; health_ready: boolean; alert_center_ready: boolean; dashboard_ready: boolean; evidence_ready: boolean; deterministic_replay: boolean; primitives_only: boolean; advisory_only_alerts: boolean; observational_only: boolean; no_execution: boolean; no_runtime_mutation: boolean; operator_authority_preserved: boolean; governance_preserved: boolean; qualification_ready: boolean; failures: readonly MonitoringExperienceFailure[]; integrity_hash: string }>;
export type MonitoringExperienceResult = Readonly<{ phase_version: "monitoring-experience/mc-13b"; phase_identifier: "MonitoringExperience"; upstream_refs: readonly string[]; downstream_refs: readonly string[]; tenant_id: string; experience_id: string; aggregator: MonitoringAggregator; alerts: AlertManagementService; sla: SlaMonitoringService; analytics: OperationalAnalyticsService; health: HealthReportingService; alert_center: AlertCenter; dashboard: LiveOperationsDashboard; evidence: MonitoringExperienceEvidence; readiness: MonitoringExperienceReadiness; replay_hash: string; integrity_hash: string }>;
export type MonitoringExperienceValidation = Readonly<{ valid: boolean; decision: MonitoringExperienceDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; aggregator_valid: boolean; alerts_valid: boolean; sla_valid: boolean; analytics_valid: boolean; health_valid: boolean; alert_center_valid: boolean; dashboard_valid: boolean; evidence_valid: boolean; readiness_valid: boolean; failures: readonly MonitoringExperienceFailure[]; integrity_hash: string }>;
export type MonitoringExperienceBundle = Readonly<{ doctrine: Readonly<{ version: "monitoring-experience/mc-13b"; capability_type: "Operational Visibility Layer"; consumes_monitoring_primitives: true; advisory_alerts_only: true; observational_only: true; no_execution_authority: true; operator_approval_required: true; qualification_gate: "MC-13B Monitoring Experience Qualification Gate" }>; result: MonitoringExperienceResult; validation: MonitoringExperienceValidation }>;
