export type OperatorConsoleDecision = "OPERATOR_CONSOLE_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type OperatorWorkspace = "Runtime Operations" | "Governance Review" | "Evidence Investigation" | "Replay Analysis" | "Certification Review" | "Collaboration Oversight" | "Delegation Management" | "Safety Monitoring" | "Policy Administration" | "Emergency Response";
export type OperatorConsoleFailure =
  | "W2_0_CONSTITUTIONAL_FOUNDATION_INVALID" | "W2_1_AGENT_REGISTRY_INVALID" | "W2_2_LIFECYCLE_ENGINE_INVALID" | "W2_3_CAPABILITY_REGISTRY_INVALID" | "W2_4_SKILL_REGISTRY_INVALID" | "W2_5_AUTHORITY_VALIDATOR_INVALID" | "W2_6_POLICY_GATE_INVALID" | "W2_7_SAFETY_GATE_INVALID" | "W2_8_PLANNING_ENGINE_INVALID" | "W2_9_MEMORY_ENGINE_INVALID" | "W2_10_RUNTIME_ORCHESTRATOR_INVALID" | "W2_11_DELEGATION_ENGINE_INVALID" | "W2_12_COLLABORATION_ENGINE_INVALID" | "W2_13_EVIDENCE_ENGINE_INVALID" | "W2_14_REPLAY_ENGINE_INVALID" | "W2_15_CERTIFICATION_ENGINE_INVALID"
  | "OPERATOR_CONSOLE_MISSING" | "DASHBOARD_MISSING" | "DASHBOARD_VISIBILITY_INCOMPLETE" | "APPROVAL_QUEUE_MISSING" | "APPROVAL_SIGNATURE_MISSING" | "APPROVAL_EVIDENCE_MISSING"
  | "EVIDENCE_EXPLORER_MISSING" | "EVIDENCE_LINEAGE_MISSING" | "REPLAY_EXPLORER_MISSING" | "REPLAY_EXECUTION_NOT_AUTHORIZED" | "REPLAY_READ_ONLY_BYPASSED"
  | "CERTIFICATION_EXPLORER_MISSING" | "CERTIFICATION_DRILLDOWN_MISSING" | "EMERGENCY_CONTROLS_MISSING" | "EMERGENCY_AUTHORITY_BYPASSED" | "EMERGENCY_POLICY_BYPASSED" | "EMERGENCY_SAFETY_BYPASSED" | "EMERGENCY_AUDIT_MISSING"
  | "GOVERNANCE_VIEW_MISSING" | "NOTIFICATION_SERVICE_MISSING" | "WORKSPACE_ISOLATION_MISSING" | "OPERATOR_AUTHENTICATION_MISSING" | "ROLE_AUTHORIZATION_MISSING" | "TENANT_ISOLATION_FAILED" | "SIGNED_ACTIONS_MISSING" | "AUDIT_LOGGING_MISSING"
  | "OPERATIONAL_EVIDENCE_MISSING" | "OPERATOR_REPLAY_ARTIFACTS_MISSING" | "OPERATOR_CONSOLE_QUALIFICATION_FAILED";
export type OperatorConsoleScenario = "BASELINE" | "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | OperatorConsoleFailure;
export type OperatorConsoleInput = Readonly<{ scenario?: OperatorConsoleScenario; seed?: string }>;
export type OperatorConsole = Readonly<{ console_id: string; dashboards: boolean; operator_workspaces: boolean; approval_workflows: boolean; replay_viewer: boolean; evidence_explorer: boolean; certification_explorer: boolean; advisory_supervisory_only: boolean; constitutional_bypass_prevented: boolean; integrity_hash: string }>;
export type OperationsDashboard = Readonly<{ dashboard_id: string; runtime_status: boolean; agent_status: boolean; active_missions: boolean; planning_status: boolean; memory_utilization: boolean; collaboration_sessions: boolean; delegation_graph: boolean; health_indicators: boolean; runtime_alerts: boolean; policy_violations: boolean; safety_events: boolean; certification_status: boolean; evidence_status: boolean; replay_availability: boolean; realtime_visibility: boolean; integrity_hash: string }>;
export type ApprovalQueue = Readonly<{ queue_id: string; pending_approvals: boolean; escalated_decisions: boolean; constitutional_overrides: boolean; policy_exceptions: boolean; safety_approvals: boolean; delegation_approvals: boolean; runtime_pause_requests: boolean; mission_approvals: boolean; certification_approvals: boolean; qualification_reviews: boolean; authority_source: boolean; justification: boolean; evidence_references: boolean; operator_identity: boolean; digital_signature: boolean; timestamp: boolean; integrity_hash: string }>;
export type EvidenceExplorer = Readonly<{ explorer_id: string; browsing: boolean; packages: boolean; lineage_visualization: boolean; validation: boolean; search: boolean; timelines: boolean; provenance_inspection: boolean; immutable_references: boolean; runtime_actions: boolean; plans: boolean; memories: boolean; certifications: boolean; replay_sessions: boolean; safety_events: boolean; policy_decisions: boolean; integrity_hash: string }>;
export type ReplayExplorerConsole = Readonly<{ explorer_id: string; replay_launch: boolean; execution_playback: boolean; timeline_navigation: boolean; divergence_visualization: boolean; decision_comparison: boolean; evidence_overlay: boolean; runtime_inspection: boolean; state_comparison: boolean; replay_reports: boolean; read_only_by_default: boolean; authorized_execution_only: boolean; integrity_hash: string }>;
export type CertificationExplorer = Readonly<{ explorer_id: string; agent_certifications: boolean; capability_certifications: boolean; skill_certifications: boolean; runtime_certifications: boolean; qualification_reports: boolean; certification_history: boolean; expiration_tracking: boolean; certification_evidence: boolean; certification_lineage: boolean; artifact_drilldown: boolean; integrity_hash: string }>;
export type EmergencyControlPanel = Readonly<{ panel_id: string; emergency_stop: boolean; runtime_suspension: boolean; runtime_isolation: boolean; mission_cancellation: boolean; delegation_revocation: boolean; operator_takeover: boolean; quarantine: boolean; safe_shutdown: boolean; recovery_initiation: boolean; constitutional_authority: boolean; policy_validation: boolean; safety_validation: boolean; immutable_audit: boolean; operator_authentication: boolean; mfa_confirmation: boolean; governance_bypass_prevented: boolean; integrity_hash: string }>;
export type UnifiedGovernanceViews = Readonly<{ view_id: string; authority_decisions: boolean; policy_decisions: boolean; safety_decisions: boolean; lifecycle_state: boolean; evidence: boolean; replay: boolean; certification: boolean; runtime_health: boolean; consolidated_visibility: boolean; integrity_hash: string }>;
export type NotificationService = Readonly<{ service_id: string; alerts: boolean; escalations: boolean; approval_requests: boolean; emergencies: boolean; certification_changes: boolean; deterministic_delivery: boolean; audit_recorded: boolean; integrity_hash: string }>;
export type OperatorWorkspaces = Readonly<{ workspace_id: string; workspaces: readonly OperatorWorkspace[]; runtime_operations: boolean; governance_review: boolean; evidence_investigation: boolean; replay_analysis: boolean; certification_review: boolean; collaboration_oversight: boolean; delegation_management: boolean; safety_monitoring: boolean; policy_administration: boolean; emergency_response: boolean; tenant_isolated: boolean; integrity_hash: string }>;
export type OperatorConsoleSecurity = Readonly<{ security_id: string; authenticated_operators: boolean; role_based_authorization: boolean; authority_validation: boolean; policy_validation: boolean; safety_validation: boolean; signed_actions: boolean; immutable_audit_logging: boolean; tenant_isolation: boolean; no_governance_bypass: boolean; integrity_hash: string }>;
export type OperatorConsoleEvidence = Readonly<{ ledger_id: string; records: readonly string[]; operator_actions: boolean; approval_decisions: boolean; emergency_actions: boolean; dashboard_snapshots: boolean; replay_sessions: boolean; certification_reviews: boolean; governance_reviews: boolean; audit_records: boolean; session_history: boolean; operational_evidence: boolean; immutable: boolean; lineage_tracked: boolean; replay_artifacts: boolean; integrity_hash: string }>;
export type OperatorConsoleReadiness = Readonly<{ readiness_id: string; decision: OperatorConsoleDecision; phase_ready: boolean; upstream_ready: boolean; console_ready: boolean; dashboard_ready: boolean; approval_ready: boolean; evidence_ready: boolean; replay_ready: boolean; certification_ready: boolean; emergency_ready: boolean; governance_ready: boolean; notification_ready: boolean; workspaces_ready: boolean; security_ready: boolean; operational_evidence_ready: boolean; qualification_ready: boolean; failures: readonly OperatorConsoleFailure[]; integrity_hash: string }>;
export type OperatorConsoleResult = Readonly<{ phase_version: "operator-console/w2.16"; phase_identifier: "OperatorConsole"; upstream_refs: readonly string[]; console: OperatorConsole; dashboard: OperationsDashboard; approval_queue: ApprovalQueue; evidence_explorer: EvidenceExplorer; replay_explorer: ReplayExplorerConsole; certification_explorer: CertificationExplorer; emergency_controls: EmergencyControlPanel; governance_views: UnifiedGovernanceViews; notifications: NotificationService; workspaces: OperatorWorkspaces; security: OperatorConsoleSecurity; evidence: OperatorConsoleEvidence; readiness: OperatorConsoleReadiness; replay_hash: string; integrity_hash: string }>;
export type OperatorConsoleValidation = Readonly<{ valid: boolean; decision: OperatorConsoleDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; console_valid: boolean; dashboard_valid: boolean; approval_valid: boolean; evidence_explorer_valid: boolean; replay_explorer_valid: boolean; certification_explorer_valid: boolean; emergency_valid: boolean; governance_valid: boolean; notification_valid: boolean; workspaces_valid: boolean; security_valid: boolean; evidence_valid: boolean; readiness_valid: boolean; failures: readonly OperatorConsoleFailure[]; integrity_hash: string }>;
export type OperatorConsoleBundle = Readonly<{ doctrine: Readonly<{ version: "operator-console/w2.16"; owns_human_control_surface: true; owns_operations_dashboard: true; owns_approval_queue: true; owns_evidence_explorer: true; owns_replay_explorer: true; owns_certification_explorer: true; owns_emergency_controls: true; advisory_supervisory_only: true; cannot_bypass_constitutional_governance: true; qualification_gate: "Operator Console Qualification Gate" }>; result: OperatorConsoleResult; validation: OperatorConsoleValidation }>;
