export type OperationalEvidenceReplayDecision = "OPERATIONAL_EVIDENCE_REPLAY_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type ReplayCompletionStatus = "REQUESTED" | "RUNNING" | "COMPLETED" | "FAILED" | "ARCHIVED";
export type OperationalEvidenceReplayFailure =
  | "MC_1_MISSION_MANAGEMENT_INVALID" | "MC_2_SCENARIO_PLANNING_INVALID" | "MC_3_DECISION_SUPPORT_INVALID" | "MC_4_PORTFOLIO_MANAGEMENT_INVALID" | "W2_REPLAY_ENGINE_INVALID" | "W2_EVIDENCE_ENGINE_INVALID" | "W2_OPERATOR_CONSOLE_INVALID" | "W1_REGISTRY_INVALID" | "W1_IDENTITY_INVALID"
  | "REPLAY_RECONSTRUCTION_ENGINE_MISSING" | "CCI_EVENT_HISTORY_NOT_AUTHORITATIVE" | "MISSION_CONTROL_EVENT_STREAM_CREATED" | "SYNTHETIC_EVENTS_USED" | "INFERRED_OPERATIONAL_HISTORY_USED" | "REPLAY_NON_DETERMINISTIC" | "REPLAY_SESSION_MANAGER_MISSING" | "REPLAY_GOVERNANCE_METADATA_MISSING" | "TIMELINE_RECONSTRUCTION_MISSING" | "TIMELINE_ORDERING_INVALID" | "STATE_RECONSTRUCTION_MISSING" | "STATE_RECONSTRUCTION_NON_REPRODUCIBLE" | "OPERATIONAL_EVIDENCE_INTEGRATION_MISSING" | "EVIDENCE_LINKAGE_INCOMPLETE" | "DIVERGENCE_DETECTION_MISSING" | "UNAUTHORIZED_DIVERGENCE_UNDETECTED" | "REPLAY_REPORTING_MISSING" | "REPLAY_REPORT_EVIDENCE_INCOMPLETE" | "REPLAY_VIEWER_BACKEND_MISSING" | "OPERATIONAL_EVIDENCE_INDEX_MISSING" | "EVIDENCE_LOOKUP_SLOW" | "AUTHORITY_VALIDATION_BYPASSED" | "EVIDENCE_ACCESS_CONTROL_BYPASSED" | "TENANT_ISOLATION_FAILED" | "MISSION_ISOLATION_FAILED" | "AUDIT_LOGGING_MISSING" | "REPLAY_AUTHORIZATION_MISSING" | "HISTORY_MUTATION_ATTEMPTED" | "PERFORMANCE_TARGETS_MISSED" | "CONCURRENT_HISTORY_TARGET_NOT_MET" | "OPERATIONAL_REPLAY_QUALIFICATION_FAILED";
export type OperationalEvidenceReplayScenario = "BASELINE" | "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | OperationalEvidenceReplayFailure;
export type OperationalEvidenceReplayInput = Readonly<{ scenario?: OperationalEvidenceReplayScenario; seed?: string; tenant_id?: string; replay_id?: string; concurrent_histories?: number }>;
export type ReplayReconstructionEngine = Readonly<{ engine_id: string; event_stream_loading: boolean; mission_reconstruction: boolean; timeline_rebuilding: boolean; state_reconstruction: boolean; dependency_replay: boolean; cross_service_reconstruction: boolean; historical_projection: boolean; source_exclusively_cci_event_history: boolean; no_independent_event_stream: boolean; no_synthetic_events: boolean; no_inferred_history: boolean; deterministic_reconstruction: boolean; read_only: boolean; integrity_hash: string }>;
export type ReplaySessionManager = Readonly<{ manager_id: string; replay_creation: boolean; session_persistence: boolean; replay_checkpoints: boolean; time_navigation: boolean; bookmarking: boolean; investigation_sessions: boolean; replay_identifier: boolean; replay_requestor: boolean; replay_authority: boolean; replay_scope: boolean; replay_timestamp: boolean; event_history_version: boolean; evidence_references: boolean; completion_status: ReplayCompletionStatus; integrity_hash: string }>;
export type TimelineReconstruction = Readonly<{ timeline_id: string; event_ordering: boolean; decision_ordering: boolean; approval_ordering: boolean; state_transitions: boolean; evidence_creation_timeline: boolean; mission_lifecycle_replay: boolean; canonical_ordering: boolean; integrity_hash: string }>;
export type MissionStateReconstruction = Readonly<{ state_id: string; mission_status: boolean; objectives: boolean; assignments: boolean; dependencies: boolean; approvals: boolean; governance_state: boolean; execution_progress: boolean; point_in_time_state: boolean; reproducible_state: boolean; integrity_hash: string }>;
export type OperationalEvidenceIntegration = Readonly<{ integration_id: string; evidence_lookup: boolean; evidence_attachment: boolean; decision_evidence: boolean; approval_evidence: boolean; mission_evidence: boolean; governance_evidence: boolean; authoritative_evidence_linkage: boolean; immutable_lineage: boolean; integrity_hash: string }>;
export type ReplayDivergenceDetection = Readonly<{ detector_id: string; replay_validation: boolean; state_validation: boolean; missing_events: boolean; duplicate_events: boolean; ordering_violations: boolean; dependency_violations: boolean; zero_unauthorized_divergence: boolean; integrity_hash: string }>;
export type ReplayReporting = Readonly<{ reporting_id: string; replay_summary: boolean; event_timeline: boolean; mission_reconstruction: boolean; evidence_references: boolean; governance_findings: boolean; replay_statistics: boolean; authoritative_reports: boolean; complete_evidence_linkage: boolean; integrity_hash: string }>;
export type ReplayViewerBackend = Readonly<{ backend_id: string; replay_navigation: boolean; timeline_browsing: boolean; event_inspection: boolean; state_comparison: boolean; evidence_viewing: boolean; mission_playback: boolean; decision_review: boolean; approval_visualization: boolean; integrity_hash: string }>;
export type OperationalEvidenceIndex = Readonly<{ index_id: string; evidence_lookup: boolean; mission_evidence: boolean; decision_evidence: boolean; approval_evidence: boolean; timeline_evidence: boolean; governance_evidence: boolean; lookup_latency_ms: number; indexed: boolean; integrity_hash: string }>;
export type ReplaySecurity = Readonly<{ security_id: string; authority_validation: boolean; evidence_access_control: boolean; tenant_isolation: boolean; mission_isolation: boolean; immutable_history: boolean; audit_logging: boolean; replay_authorization: boolean; read_only_enforcement: boolean; integrity_hash: string }>;
export type ReplayPerformance = Readonly<{ performance_id: string; startup_seconds: number; timeline_reconstruction_seconds: number; state_reconstruction_seconds: number; report_generation_seconds: number; evidence_lookup_ms: number; concurrent_history_target: 1000; concurrent_history_capacity: number; targets_met: boolean; integrity_hash: string }>;
export type OperationalEvidenceReplayReadiness = Readonly<{ readiness_id: string; decision: OperationalEvidenceReplayDecision; phase_ready: boolean; upstream_ready: boolean; reconstruction_ready: boolean; sessions_ready: boolean; timeline_ready: boolean; state_ready: boolean; evidence_ready: boolean; divergence_ready: boolean; reporting_ready: boolean; viewer_ready: boolean; index_ready: boolean; security_ready: boolean; performance_ready: boolean; cci_event_history_exclusive: boolean; read_only: boolean; qualification_ready: boolean; failures: readonly OperationalEvidenceReplayFailure[]; integrity_hash: string }>;
export type OperationalEvidenceReplayResult = Readonly<{ phase_version: "operational-evidence-replay/mc-5"; phase_identifier: "OperationalEvidenceReplay"; upstream_refs: readonly string[]; tenant_id: string; replay_id: string; reconstruction: ReplayReconstructionEngine; sessions: ReplaySessionManager; timeline: TimelineReconstruction; state: MissionStateReconstruction; evidence: OperationalEvidenceIntegration; divergence: ReplayDivergenceDetection; reporting: ReplayReporting; viewer: ReplayViewerBackend; index: OperationalEvidenceIndex; security: ReplaySecurity; performance: ReplayPerformance; readiness: OperationalEvidenceReplayReadiness; replay_hash: string; integrity_hash: string }>;
export type OperationalEvidenceReplayValidation = Readonly<{ valid: boolean; decision: OperationalEvidenceReplayDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; reconstruction_valid: boolean; sessions_valid: boolean; timeline_valid: boolean; state_valid: boolean; evidence_valid: boolean; divergence_valid: boolean; reporting_valid: boolean; viewer_valid: boolean; index_valid: boolean; security_valid: boolean; performance_valid: boolean; readiness_valid: boolean; failures: readonly OperationalEvidenceReplayFailure[]; integrity_hash: string }>;
export type OperationalEvidenceReplayBundle = Readonly<{ doctrine: Readonly<{ version: "operational-evidence-replay/mc-5"; owns_replay_reconstruction: true; owns_replay_sessions: true; owns_timeline_reconstruction: true; owns_state_reconstruction: true; owns_operational_evidence_index: true; owns_replay_reports: true; derives_exclusively_from_cci_event_history: true; read_only_replay: true; no_independent_replay_event_stream: true; concurrent_history_qualification_target: 1000; qualification_gate: "Operational Evidence Replay Qualification Gate" }>; result: OperationalEvidenceReplayResult; validation: OperationalEvidenceReplayValidation }>;
