export type OperationalResilienceRecoveryGovernanceOutcome = "PASS" | "CONDITIONAL_PASS" | "FAIL";
export type OperationalResilienceLifecycleState = "NORMAL_OPERATION" | "INCIDENT_DETECTED" | "CONTAINMENT" | "FAILURE_ANALYSIS" | "RECOVERY_PLANNING" | "RECOVERY_AUTHORIZED" | "RECOVERY_EXECUTING" | "RECOVERY_COMPLETED" | "POST_RECOVERY_VALIDATION" | "REQUALIFICATION" | "PRODUCTION_RESTORED";
export type RecoveryCategory = "TENANT_SERVICE_FAILURE" | "REGIONAL_INFRASTRUCTURE_FAILURE" | "INFRASTRUCTURE_DEPENDENCY_FAILURE" | "REPLAY_SUBSYSTEM_FAILURE" | "GOVERNANCE_SUBSYSTEM_FAILURE" | "CERTIFICATION_SUBSYSTEM_FAILURE" | "CONFIGURATION_CORRUPTION" | "OPERATIONAL_SERVICE_DEGRADATION" | "STORAGE_SUBSYSTEM_FAILURE" | "MESSAGING_SUBSYSTEM_FAILURE" | "OBSERVABILITY_FAILURE";
export type FailureSeverity = "INFORMATIONAL" | "MINOR" | "MAJOR" | "CRITICAL" | "PLATFORM_CRITICAL";
export type RecoveryStrategy = "SERVICE_RESTART" | "DEPENDENCY_RESTART" | "TENANT_ISOLATION" | "REGIONAL_FAILOVER" | "WORKLOAD_REDISTRIBUTION" | "CONFIGURATION_RESTORATION" | "REPLAY_RECONSTRUCTION" | "CERTIFICATION_SUSPENSION" | "STAGED_RECOVERY" | "CONTROLLED_SERVICE_RESTORATION";
export type RecoveryAuthorizationOutcome = "APPROVED" | "DENIED" | "REQUIRES_REVIEW" | "REQUIRES_GOVERNANCE" | "BLOCKED";
export type OperationalResilienceRecoveryGovernanceFailure =
  | "CONTAINMENT_NOT_DETERMINISTIC"
  | "RECOVERY_NOT_DETERMINISTIC"
  | "DEPENDENCY_AWARE_RECOVERY_NOT_VALIDATED"
  | "CONTAINMENT_VALIDATION_INCOMPLETE"
  | "POST_RECOVERY_VALIDATION_FAILED"
  | "REQUALIFICATION_NOT_VALIDATED"
  | "RESILIENCE_NOT_REPLAYABLE"
  | "INCIDENT_AUDIT_INCOMPLETE"
  | "RECOVERY_EVIDENCE_MUTABLE"
  | "TENANT_ISOLATION_VIOLATED"
  | "GOVERNANCE_NOT_MAINTAINED"
  | "OPERATIONAL_RESILIENCE_NOT_CERTIFIED"
  | "RECOVERY_STARTED_BEFORE_CONTAINMENT"
  | "REQUALIFICATION_STARTED_DURING_RECOVERY"
  | "UNAUTHORIZED_RECOVERY_APPROVED"
  | "PHASE_17_10_CERTIFICATION_NOT_VALID"
  | "NON_CONSTITUTIONAL_RESILIENCE_WARNING";
export type OperationalResilienceRecoveryGovernanceScenario = "BASELINE" | OperationalResilienceRecoveryGovernanceFailure;
export type OperationalResilienceRecoveryGovernanceInput = Readonly<{ scenario?: OperationalResilienceRecoveryGovernanceScenario; tenant_id?: string; operator_id?: string; mission_id?: string; region_id?: string; incident_id?: string; recovery_category?: RecoveryCategory; severity?: FailureSeverity }>;

export type RecoveryStateRecord = Readonly<{ recovery_id: string; incident_id: string; tenant_scope: string; regional_scope: string; recovery_category: RecoveryCategory; severity: FailureSeverity; containment_status: "CONTAINED" | "NOT_CONTAINED"; dependency_status: "SATISFIED" | "UNSATISFIED"; recovery_plan: readonly RecoveryStrategy[]; authorization_reference: string; execution_result: "RECOVERED" | "BLOCKED"; replay_reference: string; evidence_reference: string; validation_reference: string; requalification_reference: string; audit_reference: string; integrity_hash: string }>;
export type ResilienceOrchestrator = Readonly<{ orchestrator_id: string; lifecycle: readonly OperationalResilienceLifecycleState[]; containment_precedes_recovery: boolean; recovery_precedes_requalification: boolean; deterministic_coordination: boolean; prevents_failure_propagation: boolean; certification_continuity: boolean; integrity_hash: string }>;
export type FailureContainmentEngine = Readonly<{ engine_id: string; failure_isolated: boolean; propagation_stopped: boolean; tenant_isolation_preserved: boolean; governance_maintained: boolean; audit_preserved: boolean; replay_preserved: boolean; deterministic_containment: boolean; containment_validated: boolean; integrity_hash: string }>;
export type DependencyRecoveryPlanner = Readonly<{ planner_id: string; service_dependencies: boolean; infrastructure_dependencies: boolean; tenant_dependencies: boolean; regional_dependencies: boolean; certification_dependencies: boolean; governance_dependencies: boolean; deterministic_recovery_order: boolean; integrity_hash: string }>;
export type RecoveryAuthorizationService = Readonly<{ service_id: string; containment_complete: boolean; dependencies_satisfied: boolean; recovery_plan_approved: boolean; governance_constraints_satisfied: boolean; required_evidence_captured: boolean; recovery_replay_established: boolean; outcome: RecoveryAuthorizationOutcome; integrity_hash: string }>;
export type RecoveryCoordinator = Readonly<{ coordinator_id: string; strategies: readonly RecoveryStrategy[]; controlled_degradation: boolean; deterministic_recovery: boolean; dependency_aware_recovery: boolean; regional_recovery_coordination: boolean; recovery_started_after_containment: boolean; execution_result: "RECOVERED" | "BLOCKED"; integrity_hash: string }>;
export type OperationalRecoveryValidator = Readonly<{ validator_id: string; service_health: boolean; dependency_integrity: boolean; replay_consistency: boolean; audit_integrity: boolean; tenant_isolation: boolean; governance_enforcement: boolean; certification_integrity: boolean; operational_readiness: boolean; validation_successful: boolean; integrity_hash: string }>;
export type RecoveryReplayValidator = Readonly<{ replay_id: string; reconstructs_incident_detection: boolean; reconstructs_containment_actions: boolean; reconstructs_dependency_evaluations: boolean; reconstructs_authorization_decisions: boolean; reconstructs_recovery_execution: boolean; reconstructs_validation_activities: boolean; reconstructs_requalification: boolean; reconstructs_restoration_decisions: boolean; identical_outcomes: boolean; replay_refs: readonly string[]; integrity_hash: string }>;
export type RecoveryEvidenceService = Readonly<{ evidence_id: string; containment_evidence: boolean; recovery_evidence: boolean; validation_evidence: boolean; dependency_evidence: boolean; replay_evidence: boolean; authorization_evidence: boolean; audit_evidence: boolean; certification_evidence: boolean; immutable: boolean; integrity_hash: string }>;
export type PostRecoveryQualificationService = Readonly<{ service_id: string; constitutional_compliance: boolean; operational_health: boolean; replay_determinism: boolean; governance_enforcement: boolean; certification_integrity: boolean; dependency_consistency: boolean; production_readiness: boolean; requalification_validated: boolean; requalification_after_recovery: boolean; integrity_hash: string }>;
export type OperationalResilienceDashboard = Readonly<{ dashboard_id: string; active_incidents_visible: boolean; containment_status_visible: boolean; recovery_progress_visible: boolean; dependency_health_visible: boolean; validation_progress_visible: boolean; requalification_status_visible: boolean; replay_integrity_visible: boolean; regional_recovery_visible: boolean; certification_status_visible: boolean; replayable: boolean; integrity_hash: string }>;
export type IncidentLedgerEntry = Readonly<{ ledger_entry_id: string; sequence: number; lifecycle_state: OperationalResilienceLifecycleState; recovery_ref: string; containment_ref: string; authorization_ref: string; validation_ref: string; requalification_ref: string; replay_ref: string; audit_ref: string; append_only: boolean; immutable: boolean; integrity_hash: string }>;
export type OperationalResilienceCertificationPackage = Readonly<{ package_id: string; containment_deterministic: boolean; recovery_deterministic: boolean; dependency_aware_recovery_validated: boolean; containment_validation_complete: boolean; post_recovery_validation_successful: boolean; requalification_validated: boolean; resilience_replayable: boolean; incident_audit_complete: boolean; recovery_evidence_immutable: boolean; tenant_isolation_preserved: boolean; governance_maintained: boolean; operational_resilience_certified: boolean; evidence_refs: readonly string[]; integrity_hash: string }>;
export type OperationalResilienceRecoveryGovernanceTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: OperationalResilienceRecoveryGovernanceOutcome; passed: boolean; failure_reason: OperationalResilienceRecoveryGovernanceFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;

export type OperationalResilienceRecoveryGovernanceResult = Readonly<{ phase_version: "operational-resilience-recovery-governance/v17.11"; phase_identifier: "OperationalResilienceRecoveryGovernance"; continuous_multi_tenant_certification_ref: string; recovery_state: RecoveryStateRecord; orchestrator: ResilienceOrchestrator; containment_engine: FailureContainmentEngine; dependency_planner: DependencyRecoveryPlanner; authorization_service: RecoveryAuthorizationService; recovery_coordinator: RecoveryCoordinator; recovery_validator: OperationalRecoveryValidator; replay_validator: RecoveryReplayValidator; evidence_service: RecoveryEvidenceService; post_recovery_qualification: PostRecoveryQualificationService; dashboard: OperationalResilienceDashboard; incident_ledger: readonly IncidentLedgerEntry[]; certification_package: OperationalResilienceCertificationPackage; certification_tests: readonly OperationalResilienceRecoveryGovernanceTest[]; failures: readonly OperationalResilienceRecoveryGovernanceFailure[]; outcome: OperationalResilienceRecoveryGovernanceOutcome; replay_hash: string; integrity_hash: string }>;
export type OperationalResilienceRecoveryGovernanceValidation = Readonly<{ valid: boolean; outcome: OperationalResilienceRecoveryGovernanceOutcome; state_valid: boolean; orchestrator_valid: boolean; containment_valid: boolean; dependency_valid: boolean; authorization_valid: boolean; recovery_valid: boolean; validation_valid: boolean; replay_valid: boolean; evidence_valid: boolean; requalification_valid: boolean; dashboard_valid: boolean; ledger_valid: boolean; certification_package_valid: boolean; certification_valid: boolean; result_replay_valid: boolean; failures: readonly OperationalResilienceRecoveryGovernanceFailure[]; integrity_hash: string }>;
export type OperationalResilienceRecoveryGovernanceBundle = Readonly<{ doctrine: Readonly<{ version: "operational-resilience-recovery-governance/v17.11"; upstream_phase: "continuous-multi-tenant-certification/v17.10"; lifecycle_states: readonly OperationalResilienceLifecycleState[]; recovery_categories: readonly RecoveryCategory[]; severity_levels: readonly FailureSeverity[]; recovery_strategies: readonly RecoveryStrategy[]; authorization_outcomes: readonly RecoveryAuthorizationOutcome[]; certification_outcomes: readonly OperationalResilienceRecoveryGovernanceOutcome[] }>; result: OperationalResilienceRecoveryGovernanceResult; validation: OperationalResilienceRecoveryGovernanceValidation }>;
