export type OperatorDashboardDecision = "OPERATOR_DASHBOARD_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type DashboardViewKind = "MISSION" | "PORTFOLIO" | "RISK" | "REPLAY" | "RECOMMENDATION" | "DIGITAL_TWIN" | "ALERT" | "KPI" | "EVIDENCE";
export type OperatorDashboardFailure =
  | "MC_1_MISSION_MANAGEMENT_INVALID" | "MC_4_PORTFOLIO_MANAGEMENT_INVALID" | "MC_5_OPERATIONAL_EVIDENCE_REPLAY_INVALID" | "MC_6_DIGITAL_TWIN_INVALID" | "MC_7_SIMULATION_INVALID" | "MC_8_RISK_ASSESSMENT_INVALID" | "MC_9_RECOMMENDATION_INTELLIGENCE_INVALID"
  | "DASHBOARD_SERVICE_MISSING" | "PAGE_COMPOSITION_MISSING" | "LAYOUTS_MISSING" | "STATE_SYNCHRONIZATION_MISSING" | "WIDGET_ORCHESTRATION_MISSING" | "DASHBOARD_CONFIGURATION_MISSING" | "TENANT_ISOLATION_FAILED" | "MISSION_VIEW_MISSING" | "PORTFOLIO_VIEW_MISSING" | "RISK_VIEW_MISSING" | "REPLAY_VIEW_MISSING" | "RECOMMENDATION_VIEW_MISSING" | "DIGITAL_TWIN_VIEW_MISSING" | "ALERT_CENTER_MISSING" | "KPI_DASHBOARD_MISSING" | "EVIDENCE_EXPLORER_MISSING" | "SEARCH_SERVICE_MISSING" | "FILTERING_MISSING" | "VISUALIZATION_SERVICE_MISSING" | "OPERATOR_NAVIGATION_MISSING" | "DISPLAY_LINEAGE_MISSING" | "DISPLAY_EVIDENCE_REFERENCE_MISSING" | "DISPLAY_CONFIDENCE_MISSING" | "GOVERNING_AUTHORITY_MISSING" | "AUTHORIZATION_VALIDATION_MISSING" | "LEAST_PRIVILEGE_MISSING" | "EVIDENCE_VISIBILITY_RULES_MISSING" | "CONSTITUTIONAL_ACCESS_CONTROL_MISSING" | "DASHBOARD_API_MISSING" | "QUERY_API_MISSING" | "VISUALIZATION_API_MISSING" | "EVIDENCE_API_MISSING" | "DASHBOARD_EVIDENCE_MISSING" | "DASHBOARD_AUDIT_RECORDS_MISSING" | "QUERY_NON_DETERMINISTIC" | "CONFIGURATION_NOT_VERSIONED" | "EXECUTION_CAPABILITY_PRESENT" | "ACTION_APPROVAL_CAPABILITY_PRESENT" | "WORKLOAD_DISPATCH_CAPABILITY_PRESENT" | "MISSION_STATE_MUTATION_CAPABILITY_PRESENT" | "PORTFOLIO_STATE_MUTATION_CAPABILITY_PRESENT" | "AUTOMATION_INVOCATION_CAPABILITY_PRESENT" | "GOVERNANCE_BYPASS_CAPABILITY_PRESENT" | "OPERATOR_APPROVAL_BYPASS_CAPABILITY_PRESENT" | "OPERATOR_DASHBOARD_QUALIFICATION_FAILED";
export type OperatorDashboardScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | OperatorDashboardFailure;
export type OperatorDashboardInput = Readonly<{ scenario?: OperatorDashboardScenario; seed?: string; tenant_id?: string; dashboard_id?: string }>;
export type DashboardService = Readonly<{ service_id: string; page_composition: boolean; dashboard_layouts: boolean; state_synchronization: boolean; widget_orchestration: boolean; dashboard_configuration: boolean; tenant_isolation: boolean; read_only: boolean; integrity_hash: string }>;
export type MissionViewService = Readonly<{ view_id: string; active_missions: boolean; completed_missions: boolean; delayed_missions: boolean; blocked_missions: boolean; mission_evidence: boolean; mission_health: boolean; lifecycle_status: boolean; integrity_hash: string }>;
export type PortfolioViewService = Readonly<{ view_id: string; portfolio_health: boolean; concurrent_missions: boolean; resource_allocation: boolean; dependencies: boolean; completion_forecasts: boolean; integrity_hash: string }>;
export type RiskViewService = Readonly<{ view_id: string; operational_risk: boolean; portfolio_risk: boolean; trend_analysis: boolean; heat_maps: boolean; confidence_levels: boolean; consumes_mc_8: boolean; integrity_hash: string }>;
export type ReplayViewService = Readonly<{ view_id: string; replay_sessions: boolean; historical_timelines: boolean; evidence_navigation: boolean; divergence_summaries: boolean; consumes_mc_5: boolean; integrity_hash: string }>;
export type RecommendationViewService = Readonly<{ view_id: string; recommendations: boolean; recommendation_confidence: boolean; supporting_evidence: boolean; recommendation_rationale: boolean; recommendation_history: boolean; advisory_only: boolean; consumes_mc_9: boolean; integrity_hash: string }>;
export type DigitalTwinViewService = Readonly<{ view_id: string; operational_twin: boolean; system_topology: boolean; synchronization_health: boolean; state_visualization: boolean; dependency_graph: boolean; consumes_mc_6: boolean; integrity_hash: string }>;
export type AlertCenter = Readonly<{ alert_id: string; active_alerts: boolean; acknowledgements: boolean; priorities: boolean; alert_evidence: boolean; operational_notifications: boolean; observational_only: boolean; integrity_hash: string }>;
export type KpiDashboard = Readonly<{ kpi_id: string; mission_kpis: boolean; operational_kpis: boolean; portfolio_kpis: boolean; risk_kpis: boolean; availability_kpis: boolean; performance_kpis: boolean; governance_kpis: boolean; integrity_hash: string }>;
export type EvidenceExplorer = Readonly<{ explorer_id: string; evidence_packages: boolean; lineage: boolean; provenance: boolean; supporting_artifacts: boolean; qualification_evidence: boolean; integrity_hash: string }>;
export type DashboardSearch = Readonly<{ search_id: string; mission_search: boolean; replay_search: boolean; evidence_search: boolean; recommendation_search: boolean; portfolio_search: boolean; risk_search: boolean; deterministic_search: boolean; integrity_hash: string }>;
export type DashboardFilters = Readonly<{ filters_id: string; tenant: boolean; organization: boolean; portfolio: boolean; mission: boolean; lifecycle_state: boolean; recommendation_type: boolean; risk_level: boolean; timeframe: boolean; evidence_source: boolean; deterministic_filtering: boolean; integrity_hash: string }>;
export type DashboardVisualization = Readonly<{ visualization_id: string; timelines: boolean; dependency_graphs: boolean; heat_maps: boolean; trend_charts: boolean; evidence_trees: boolean; topology_graphs: boolean; mission_graphs: boolean; operational_summaries: boolean; integrity_hash: string }>;
export type OperatorNavigation = Readonly<{ navigation_id: string; unified_navigation: boolean; contextual_drill_down: boolean; evidence_first_exploration: boolean; historical_comparisons: boolean; synchronized_dashboards: boolean; cross_service_navigation: boolean; integrity_hash: string }>;
export type DashboardSecurity = Readonly<{ security_id: string; tenant_isolation: boolean; authorization_validation: boolean; least_privilege: boolean; evidence_visibility_rules: boolean; constitutional_access_controls: boolean; integrity_hash: string }>;
export type DashboardApis = Readonly<{ api_id: string; dashboard_api: boolean; query_api: boolean; visualization_api: boolean; evidence_api: boolean; operational_summaries: boolean; widget_configuration: boolean; lineage_retrieval: boolean; provenance_lookup: boolean; stable: boolean; integrity_hash: string }>;
export type DashboardEvidence = Readonly<{ evidence_id: string; dashboard_evidence: boolean; visualization_evidence: boolean; operator_activity_evidence: boolean; query_evidence: boolean; configuration_evidence: boolean; audit_records: boolean; immutable: boolean; complete_lineage: boolean; integrity_hash: string }>;
export type OperatorDashboardReadiness = Readonly<{ readiness_id: string; decision: OperatorDashboardDecision; phase_ready: boolean; upstream_ready: boolean; dashboard_ready: boolean; mission_ready: boolean; portfolio_ready: boolean; risk_ready: boolean; replay_ready: boolean; recommendation_ready: boolean; twin_ready: boolean; alerts_ready: boolean; kpis_ready: boolean; evidence_ready: boolean; search_ready: boolean; filters_ready: boolean; visualization_ready: boolean; navigation_ready: boolean; security_ready: boolean; apis_ready: boolean; deterministic_queries: boolean; read_only: boolean; observational_only: boolean; advisory_only: boolean; no_execution_authority: boolean; configuration_governed: boolean; audit_ready: boolean; qualification_ready: boolean; failures: readonly OperatorDashboardFailure[]; integrity_hash: string }>;
export type OperatorDashboardResult = Readonly<{ phase_version: "operator-dashboard/mc-10"; phase_identifier: "OperatorDashboard"; upstream_refs: readonly string[]; tenant_id: string; dashboard_id: string; view_kinds: readonly DashboardViewKind[]; dashboard: DashboardService; mission: MissionViewService; portfolio: PortfolioViewService; risk: RiskViewService; replay: ReplayViewService; recommendations: RecommendationViewService; digital_twin: DigitalTwinViewService; alerts: AlertCenter; kpis: KpiDashboard; evidence: EvidenceExplorer; search: DashboardSearch; filters: DashboardFilters; visualization: DashboardVisualization; navigation: OperatorNavigation; security: DashboardSecurity; apis: DashboardApis; audit: DashboardEvidence; readiness: OperatorDashboardReadiness; replay_hash: string; integrity_hash: string }>;
export type OperatorDashboardValidation = Readonly<{ valid: boolean; decision: OperatorDashboardDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; dashboard_valid: boolean; mission_valid: boolean; portfolio_valid: boolean; risk_valid: boolean; replay_valid: boolean; recommendation_valid: boolean; twin_valid: boolean; alerts_valid: boolean; kpis_valid: boolean; evidence_valid: boolean; search_valid: boolean; filters_valid: boolean; visualization_valid: boolean; navigation_valid: boolean; security_valid: boolean; apis_valid: boolean; audit_valid: boolean; readiness_valid: boolean; failures: readonly OperatorDashboardFailure[]; integrity_hash: string }>;
export type OperatorDashboardBundle = Readonly<{ doctrine: Readonly<{ version: "operator-dashboard/mc-10"; owns_unified_operator_workspace: true; aggregates_all_mission_control_services: true; read_only_dashboard: true; observational_only: true; advisory_only: true; execution_authority_outside_mc_10: true; evidence_lineage_required_for_every_displayed_object: true; qualification_gate: "Operator Dashboard Qualification Gate" }>; result: OperatorDashboardResult; validation: OperatorDashboardValidation }>;
