export type OperationalIntelligenceDecision = "OPERATIONAL_INTELLIGENCE_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type IntelligenceCategory = "MISSION" | "PORTFOLIO" | "ORGANIZATIONAL" | "CAPABILITY" | "RISK" | "EXECUTIVE";
export type OperationalIntelligenceFailure =
  | "MC_1_MISSION_MANAGEMENT_INVALID" | "MC_2_SCENARIO_PLANNING_INVALID" | "MC_3_DECISION_SUPPORT_INVALID" | "MC_4_PORTFOLIO_MANAGEMENT_INVALID" | "MC_5_OPERATIONAL_EVIDENCE_REPLAY_INVALID" | "MC_6_DIGITAL_TWIN_INVALID" | "MC_8_RISK_ASSESSMENT_INVALID" | "MC_9_RECOMMENDATION_INTELLIGENCE_INVALID" | "MC_10_OPERATOR_DASHBOARD_INVALID" | "MC_11_INSTITUTIONAL_MEMORY_INVALID"
  | "TEMPORAL_ANALYTICS_CONTRACT_MISSING" | "TEMPORAL_ANALYTICS_NON_COMPLIANT" | "STRATEGIC_INTELLIGENCE_ENGINE_MISSING" | "TREND_ANALYSIS_MISSING" | "STRATEGIC_ASSESSMENT_MISSING" | "OPERATIONAL_PATTERN_DETECTION_MISSING" | "LONG_TERM_PERFORMANCE_ANALYSIS_MISSING" | "ORGANIZATIONAL_HEALTH_ANALYSIS_MISSING" | "MISSION_SUCCESS_ANALYSIS_MISSING" | "INSIGHT_ENGINE_MISSING" | "EMERGING_ISSUES_MISSING" | "SUCCESS_PATTERNS_MISSING" | "DEGRADATION_INDICATORS_MISSING" | "BOTTLENECK_OBSERVATIONS_MISSING" | "GOVERNANCE_OBSERVATIONS_MISSING" | "EXECUTIVE_INTELLIGENCE_MISSING" | "EXECUTIVE_REPORTS_INCONSISTENT" | "TREND_ENGINE_MISSING" | "TREND_DETECTION_INACCURATE" | "FORECAST_ENGINE_MISSING" | "FORECASTS_NOT_REPRODUCIBLE" | "FORECASTS_NOT_ADVISORY" | "ORGANIZATIONAL_INTELLIGENCE_MISSING" | "PORTFOLIO_INTELLIGENCE_INVALID" | "MISSION_INTELLIGENCE_INVALID" | "CAPABILITY_INTELLIGENCE_MISSING" | "RISK_INTELLIGENCE_MISSING" | "INTELLIGENCE_REGISTRY_MISSING" | "INTELLIGENCE_REPORTS_MISSING" | "EXECUTIVE_BRIEFINGS_MISSING" | "INTELLIGENCE_EVIDENCE_MISSING" | "INTELLIGENCE_WITHOUT_EVIDENCE" | "EVIDENCE_TRACEABILITY_INCOMPLETE" | "REPLAY_TRACEABILITY_MISSING" | "INSTITUTIONAL_MEMORY_INTEGRATION_MISSING" | "DETERMINISTIC_GENERATION_FAILED" | "OPERATION_EXECUTION_ATTEMPTED" | "MISSION_APPROVAL_ATTEMPTED" | "OPERATIONAL_STATE_MUTATION_ATTEMPTED" | "MISSION_DATA_MUTATION_ATTEMPTED" | "GOVERNANCE_OVERRIDE_ATTEMPTED" | "AUTHORITY_VALIDATION_BYPASSED" | "POLICY_EVALUATION_BYPASSED" | "SAFETY_VALIDATION_BYPASSED" | "OPERATIONAL_INTELLIGENCE_APIS_MISSING" | "OPERATIONAL_INTELLIGENCE_QUALIFICATION_FAILED";
export type OperationalIntelligenceScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | OperationalIntelligenceFailure;
export type OperationalIntelligenceInput = Readonly<{ scenario?: OperationalIntelligenceScenario; seed?: string; tenant_id?: string; intelligence_id?: string }>;
export type TemporalAnalyticsInput = Readonly<{ contract_id: string; historical_evidence: boolean; operational_metrics: boolean; trend_inputs: boolean; portfolio_history: boolean; deterministic_inputs: boolean; evidence_backed: boolean; integrity_hash: string }>;
export type StrategicIntelligenceEngine = Readonly<{ engine_id: string; trend_analysis: boolean; strategic_assessment: boolean; operational_pattern_detection: boolean; long_term_performance_analysis: boolean; organizational_health_analysis: boolean; mission_success_analysis: boolean; deterministic_generation: boolean; integrity_hash: string }>;
export type OperationalInsightEngine = Readonly<{ insight_id: string; emerging_issues: boolean; recurring_success_patterns: boolean; degradation_indicators: boolean; operational_bottlenecks: boolean; governance_observations: boolean; evidence_backed_observations: boolean; integrity_hash: string }>;
export type ExecutiveIntelligenceService = Readonly<{ executive_id: string; executive_dashboards: boolean; executive_summaries: boolean; organizational_health_reports: boolean; strategic_status_reports: boolean; executive_briefings: boolean; consistent_reports: boolean; integrity_hash: string }>;
export type TrendAnalysisEngine = Readonly<{ trend_id: string; mission_trends: boolean; portfolio_trends: boolean; resource_trends: boolean; capability_trends: boolean; operational_trends: boolean; governance_trends: boolean; accurate_detection: boolean; integrity_hash: string }>;
export type StrategicForecastEngine = Readonly<{ forecast_id: string; temporal_analytics: boolean; historical_evidence: boolean; institutional_memory: boolean; portfolio_history: boolean; evidence_backed_projections: boolean; advisory_forecasts: boolean; reproducible_forecasts: boolean; integrity_hash: string }>;
export type OrganizationalIntelligenceEngine = Readonly<{ organization_id: string; organizational_maturity: boolean; operational_readiness: boolean; execution_efficiency: boolean; governance_effectiveness: boolean; policy_compliance: boolean; operational_stability: boolean; integrity_hash: string }>;
export type IntelligenceRegistry = Readonly<{ registry_id: string; categories: readonly IntelligenceCategory[]; intelligence_reports: boolean; operational_insights: boolean; executive_intelligence: boolean; trend_reports: boolean; strategic_forecasts: boolean; executive_briefings: boolean; governed_registry: boolean; integrity_hash: string }>;
export type IntelligenceReports = Readonly<{ report_id: string; mission_intelligence: boolean; portfolio_intelligence: boolean; organizational_intelligence: boolean; capability_intelligence: boolean; risk_intelligence: boolean; executive_intelligence: boolean; strategic_trend_reports: boolean; qualification_report: boolean; integrity_hash: string }>;
export type IntelligenceEvidence = Readonly<{ evidence_id: string; originating_evidence: boolean; supporting_reports: boolean; temporal_references: boolean; confidence_indicators: boolean; traceability: boolean; provenance: boolean; replay_references: boolean; institutional_memory_references: boolean; immutable: boolean; integrity_hash: string }>;
export type OperationalIntelligenceApis = Readonly<{ api_id: string; strategic_api: boolean; insight_api: boolean; executive_api: boolean; trend_api: boolean; forecast_api: boolean; organizational_api: boolean; registry_api: boolean; report_api: boolean; evidence_api: boolean; stable: boolean; integrity_hash: string }>;
export type OperationalIntelligenceReadiness = Readonly<{ readiness_id: string; decision: OperationalIntelligenceDecision; phase_ready: boolean; upstream_ready: boolean; temporal_ready: boolean; strategic_ready: boolean; insight_ready: boolean; executive_ready: boolean; trend_ready: boolean; forecast_ready: boolean; organizational_ready: boolean; registry_ready: boolean; reports_ready: boolean; evidence_ready: boolean; apis_ready: boolean; deterministic: boolean; advisory_only: boolean; no_execution: boolean; no_state_mutation: boolean; governance_preserved: boolean; temporal_analytics_compliant: boolean; replay_traceable: boolean; institutional_memory_integrated: boolean; qualification_ready: boolean; failures: readonly OperationalIntelligenceFailure[]; integrity_hash: string }>;
export type OperationalIntelligenceResult = Readonly<{ phase_version: "operational-intelligence/mc-12"; phase_identifier: "OperationalIntelligence"; upstream_refs: readonly string[]; tenant_id: string; intelligence_id: string; temporal: TemporalAnalyticsInput; strategic: StrategicIntelligenceEngine; insights: OperationalInsightEngine; executive: ExecutiveIntelligenceService; trends: TrendAnalysisEngine; forecast: StrategicForecastEngine; organization: OrganizationalIntelligenceEngine; registry: IntelligenceRegistry; reports: IntelligenceReports; evidence: IntelligenceEvidence; apis: OperationalIntelligenceApis; readiness: OperationalIntelligenceReadiness; replay_hash: string; integrity_hash: string }>;
export type OperationalIntelligenceValidation = Readonly<{ valid: boolean; decision: OperationalIntelligenceDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; temporal_valid: boolean; strategic_valid: boolean; insights_valid: boolean; executive_valid: boolean; trends_valid: boolean; forecast_valid: boolean; organization_valid: boolean; registry_valid: boolean; reports_valid: boolean; evidence_valid: boolean; apis_valid: boolean; readiness_valid: boolean; failures: readonly OperationalIntelligenceFailure[]; integrity_hash: string }>;
export type OperationalIntelligenceBundle = Readonly<{ doctrine: Readonly<{ version: "operational-intelligence/mc-12"; owns_strategic_intelligence_engine: true; owns_operational_insight_engine: true; owns_executive_intelligence_service: true; owns_trend_forecast_and_organizational_intelligence: true; consumes_temporal_analytics_contract: true; evidence_backed_executive_insight_required: true; advisory_only: true; no_operational_execution: true; qualification_gate: "Operational Intelligence Qualification Gate" }>; result: OperationalIntelligenceResult; validation: OperationalIntelligenceValidation }>;
