export type ProductionMonitoringDecision = "PRODUCTION_MONITORING_PRIMITIVES_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type MonitoringEntityKind = "SERVICE" | "MISSION" | "RUNTIME" | "AGENT" | "INFRASTRUCTURE" | "DEPENDENCY" | "TENANT";
export type MonitoringHealthStatus = "HEALTHY" | "DEGRADED" | "WARNING" | "FAILED" | "RECOVERING";
export type ProductionMonitoringFailure =
  | "MC_6_DIGITAL_TWIN_INVALID" | "MC_7_SIMULATION_INVALID" | "MC_8_RISK_ASSESSMENT_INVALID"
  | "PRODUCTION_TELEMETRY_MISSING" | "NON_PRODUCTION_TELEMETRY_USED" | "OPERATIONAL_STATE_COLLECTOR_MISSING" | "OPERATIONAL_REGISTRY_MISSING" | "STATE_TRANSITIONS_NOT_DETERMINISTIC"
  | "HEALTH_EVALUATION_ENGINE_MISSING" | "HEALTH_REGISTRY_MISSING" | "DEPENDENCY_HEALTH_MISSING" | "AVAILABILITY_STATUS_MISSING" | "DEGRADATION_DETECTION_MISSING"
  | "RESOURCE_METRICS_COLLECTOR_MISSING" | "RESOURCE_METRICS_INCOMPLETE" | "TENANT_RESOURCE_ISOLATION_MISSING" | "CAPACITY_METRICS_MISSING"
  | "EVENT_CORRELATION_ENGINE_MISSING" | "CORRELATION_GRAPH_MISSING" | "TIMELINE_ENGINE_MISSING" | "CAUSAL_MAPPING_INCOMPLETE" | "CROSS_SERVICE_CORRELATION_INACCURATE"
  | "MONITORING_EVIDENCE_MISSING" | "EVIDENCE_LINEAGE_INCOMPLETE" | "INTEGRITY_VERIFICATION_MISSING" | "REPLAY_COMPATIBILITY_MISSING"
  | "MONITORING_CONTRACTS_MISSING" | "DOWNSTREAM_CONSUMPTION_FAILED" | "MONITORING_APIS_UNSTABLE" | "MONITORING_QUALIFICATION_FAILED"
  | "OPERATIONAL_MUTATION_ATTEMPTED" | "MISSION_INTELLIGENCE_GENERATED" | "SYNTHETIC_MONITORING_SUBSTITUTED" | "INFRASTRUCTURE_COUPLING_DETECTED" | "GOVERNANCE_BYPASS_ATTEMPTED";
export type ProductionMonitoringScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | ProductionMonitoringFailure;
export type ProductionMonitoringInput = Readonly<{ scenario?: ProductionMonitoringScenario; seed?: string; tenant_id?: string; monitoring_id?: string }>;
export type MonitoringSourceRegistry = Readonly<{ source_id: string; production_only: boolean; cci_event_history: boolean; cci_observability_platform: boolean; caf_runtime_events: boolean; platform_health_services: boolean; infrastructure_metrics: boolean; no_synthetic_substitution: boolean; integrity_hash: string }>;
export type OperationalMonitoringRegistry = Readonly<{ registry_id: string; entities: readonly MonitoringEntityKind[]; service_status: boolean; mission_execution_state: boolean; runtime_activity: boolean; platform_utilization: boolean; operational_anomalies: boolean; state_transitions: boolean; deterministic_collection: boolean; integrity_hash: string }>;
export type HealthStatusRegistry = Readonly<{ registry_id: string; statuses: readonly MonitoringHealthStatus[]; service_health: boolean; runtime_health: boolean; agent_health: boolean; infrastructure_health: boolean; dependency_health: boolean; availability_status: boolean; degradation_detection: boolean; integrity_hash: string }>;
export type ResourceMetricsRegistry = Readonly<{ registry_id: string; cpu_utilization: boolean; memory_utilization: boolean; storage_utilization: boolean; network_utilization: boolean; queue_depth: boolean; thread_utilization: boolean; runtime_capacity: boolean; tenant_resource_isolation: boolean; deterministic_metrics: boolean; integrity_hash: string }>;
export type EventCorrelationGraph = Readonly<{ graph_id: string; cross_service_correlation: boolean; timeline_correlation: boolean; dependency_correlation: boolean; mission_correlation: boolean; runtime_correlation: boolean; infrastructure_correlation: boolean; causal_relationship_mapping: boolean; deterministic_timeline: boolean; integrity_hash: string }>;
export type MonitoringEvidence = Readonly<{ evidence_id: string; observation_source: boolean; collection_timestamp: string; immutable_evidence_identifier: boolean; correlation_identifier: boolean; collection_method: boolean; integrity_verification: boolean; replay_compatible: boolean; lineage_complete: boolean; integrity_hash: string }>;
export type MonitoringContracts = Readonly<{ contract_id: string; monitoring_primitive_service: boolean; operational_monitoring_api: boolean; health_monitoring_api: boolean; resource_monitoring_api: boolean; event_correlation_api: boolean; evidence_api: boolean; downstream_contracts: readonly string[]; stable: boolean; integrity_hash: string }>;
export type ProductionMonitoringReadiness = Readonly<{ readiness_id: string; decision: ProductionMonitoringDecision; phase_ready: boolean; upstream_ready: boolean; sources_ready: boolean; operational_ready: boolean; health_ready: boolean; resources_ready: boolean; correlation_ready: boolean; evidence_ready: boolean; contracts_ready: boolean; deterministic_monitoring: boolean; production_only_inputs: boolean; observational_only: boolean; no_mission_intelligence: boolean; no_state_mutation: boolean; tenant_isolation_preserved: boolean; digital_twin_consumption_ready: boolean; simulation_consumption_ready: boolean; risk_assessment_consumption_ready: boolean; qualification_ready: boolean; failures: readonly ProductionMonitoringFailure[]; integrity_hash: string }>;
export type ProductionMonitoringResult = Readonly<{ phase_version: "production-monitoring-primitives/mc-13a"; phase_identifier: "ProductionMonitoringPrimitives"; upstream_refs: readonly string[]; tenant_id: string; monitoring_id: string; sources: MonitoringSourceRegistry; operational: OperationalMonitoringRegistry; health: HealthStatusRegistry; resources: ResourceMetricsRegistry; correlation: EventCorrelationGraph; evidence: MonitoringEvidence; contracts: MonitoringContracts; readiness: ProductionMonitoringReadiness; replay_hash: string; integrity_hash: string }>;
export type ProductionMonitoringValidation = Readonly<{ valid: boolean; decision: ProductionMonitoringDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; sources_valid: boolean; operational_valid: boolean; health_valid: boolean; resources_valid: boolean; correlation_valid: boolean; evidence_valid: boolean; contracts_valid: boolean; readiness_valid: boolean; failures: readonly ProductionMonitoringFailure[]; integrity_hash: string }>;
export type ProductionMonitoringBundle = Readonly<{ doctrine: Readonly<{ version: "production-monitoring-primitives/mc-13a"; authoritative_operational_telemetry_layer: true; production_only_inputs: true; observational_only: true; no_platform_mutation_authority: true; no_mission_intelligence_generation: true; downstream_consumers: readonly ["digital-twin/mc-6", "simulation/mc-7", "risk-assessment/mc-8"]; qualification_gate: "Production Monitoring Primitive Qualification Gate" }>; result: ProductionMonitoringResult; validation: ProductionMonitoringValidation }>;
