import type { DashboardRole } from "@/types/adaptive-dashboard-foundation";

export type ProposedResponseDashboardStatus = "AUTHORITATIVE" | "REJECTED";
export type ProposedResponseValidationOutcome = "VALID" | "INVALID";
export type ResponseType = "NO_ACTION" | "OBSERVE" | "COLLECT_MORE_EVIDENCE" | "REQUEST_OPERATOR_REVIEW" | "REQUEST_GOVERNANCE_REVIEW" | "RUN_ADDITIONAL_SIMULATION" | "ADJUST_RECOMMENDATION_LOGIC" | "ADJUST_STRATEGY" | "ADJUST_CONFIDENCE_CALIBRATION" | "ADJUST_RISK_ASSESSMENT" | "UPDATE_GUIDANCE" | "UPDATE_OPERATOR_WORKFLOW" | "ADD_GOVERNANCE_CONTROL" | "ADD_MONITORING" | "CONTAIN_PATTERN_EFFECT" | "PREPARE_ROLLBACK" | "ESCALATE" | "INITIATE_CERTIFICATION_REVIEW";
export type ResponseStatus = "DRAFT" | "EVIDENCE_PENDING" | "READY_FOR_REVIEW" | "IN_REVIEW" | "SIMULATION_REQUIRED" | "SIMULATION_IN_PROGRESS" | "GOVERNANCE_REVIEW_REQUIRED" | "CONSTITUTIONAL_REVIEW_REQUIRED" | "OPERATOR_REVIEW_REQUIRED" | "ADDITIONAL_EVIDENCE_REQUIRED" | "BLOCKED" | "DEFERRED" | "REJECTED" | "APPROVED_FOR_CERTIFICATION" | "CERTIFICATION_PENDING" | "CERTIFIED" | "CONDITIONAL_PASS" | "FAIL" | "WITHDRAWN" | "SUPERSEDED" | "ROLLBACK_REQUIRED";
export type BenefitCategory = "MISSION_SUCCESS" | "RECOMMENDATION_EFFECTIVENESS" | "RISK_REDUCTION" | "CONFIDENCE_CALIBRATION" | "OPERATOR_USABILITY" | "REVIEW_LATENCY" | "WORKLOAD_BALANCE" | "GOVERNANCE_COMPLIANCE" | "REPLAY_RELIABILITY" | "RESILIENCE" | "EVIDENCE_QUALITY" | "CERTIFICATION_READINESS";
export type RiskCategory = "MISSION_RISK" | "OPERATIONAL_RISK" | "STRATEGIC_RISK" | "GOVERNANCE_RISK" | "CONSTITUTIONAL_RISK" | "AUTHORITY_RISK" | "TENANT_ISOLATION_RISK" | "EVIDENCE_RISK" | "REPLAY_RISK" | "ROLLBACK_RISK" | "OPERATOR_RISK" | "CERTIFICATION_RISK" | "IMPLEMENTATION_RISK" | "UNKNOWN_RISK";
export type ScopeState = "LOCAL" | "MISSION_SCOPED" | "ROLE_SCOPED" | "TENANT_SCOPED" | "CROSS_MISSION" | "CROSS_CAPABILITY" | "SYSTEM_WIDE" | "UNDETERMINED";
export type SimulationState = "NOT_ASSESSED" | "NOT_REQUIRED" | "REQUIRED" | "QUEUED" | "PREPARING" | "IN_PROGRESS" | "COMPLETED" | "FAILED" | "DIVERGED" | "BLOCKED" | "ADDITIONAL_SIMULATION_REQUIRED";
export type GovernanceOutcome = "NOT_ASSESSED" | "COMPLIANT" | "CONDITIONALLY_COMPLIANT" | "REVIEW_REQUIRED" | "ADDITIONAL_EVIDENCE_REQUIRED" | "ESCALATION_REQUIRED" | "NONCOMPLIANT" | "BLOCKED";
export type CertificationReadinessState = "NOT_ASSESSED" | "NOT_READY" | "EVIDENCE_PENDING" | "SIMULATION_PENDING" | "GOVERNANCE_PENDING" | "OPERATOR_REVIEW_PENDING" | "REPLAY_PENDING" | "ROLLBACK_PENDING" | "READY" | "CONDITIONALLY_READY" | "BLOCKED";
export type ReplayState = "READY" | "PARTIAL" | "MISSING_REFERENCES" | "VERSION_MISMATCH" | "DIVERGED" | "INTEGRITY_FAILURE" | "UNAVAILABLE" | "BLOCKED";
export type EvidenceState = "VERIFIED" | "RELIABLE" | "CONDITIONALLY_RELIABLE" | "INCOMPLETE" | "CONFLICTING" | "STALE" | "UNVERIFIED" | "REJECTED" | "SUSPECTED_TAMPERING";
export type NextPermittedResponseAction = "COLLECT_MORE_EVIDENCE" | "REVIEW_RATIONALE" | "COMPARE_RESPONSES" | "RUN_SIMULATION" | "REQUEST_GOVERNANCE_REVIEW" | "REQUEST_CONSTITUTIONAL_REVIEW" | "REQUEST_OPERATOR_REVIEW" | "REMEDIATE_BLOCKER" | "PREPARE_ROLLBACK" | "SUBMIT_FOR_CERTIFICATION" | "DEFER_RESPONSE" | "REJECT_RESPONSE" | "ESCALATE" | "NO_ACTION_PERMITTED";
export type ProposedResponseAlertSeverity = "INFORMATIONAL" | "LOW" | "MODERATE" | "HIGH" | "CRITICAL";
export type ProposedResponseWidget = "Proposed Responses" | "Response Rationale" | "Expected Benefit" | "Expected Risk" | "Affected Scope" | "Simulation Status" | "Governance Review" | "Certification Readiness" | "Proposal Lineage" | "Evidence Inspection" | "Replay Navigation" | "Response Comparison" | "Response Alerts" | "Next Permitted Action";

export type ProposedResponseDashboardScenario =
  | "BASELINE" | "MISSING_TENANT" | "MISSION_SCOPE_UNVERIFIED" | "SOURCE_PATTERN_MISSING" | "PROPOSAL_VERSION_UNVERIFIED" | "EVIDENCE_INTEGRITY_FAILURE" | "UNSUPPORTED_BENEFIT" | "MISSING_RISK" | "SIMULATION_UNVERIFIED" | "SIMULATION_FAILED" | "GOVERNANCE_UNAVAILABLE" | "CERTIFICATION_UNAVAILABLE" | "REPLAY_UNAVAILABLE" | "ROLLBACK_UNAVAILABLE" | "TENANT_LEAK" | "NONDETERMINISTIC_CALCULATION" | "HIDDEN_RESPONSE" | "REJECTED_RESPONSE_HIDDEN" | "CONDITIONAL_READY" | "UNDETERMINED_SCOPE" | "CROSS_TENANT_SCOPE" | "RESTRICTED_FIELD_LEAK" | "EXECUTION_AUTHORITY_EXPOSED" | "APPROVAL_BYPASS" | "CERTIFICATION_BYPASS" | "INTEGRITY_FAILURE";

export type ProposedResponseDashboardFailure =
  | "TENANT_CONTEXT_UNAVAILABLE" | "MISSION_SCOPE_UNVERIFIED" | "SOURCE_PATTERN_UNRESOLVED" | "PROPOSAL_VERSION_UNVERIFIED" | "EVIDENCE_INTEGRITY_FAILED" | "EXPECTED_BENEFIT_UNSUPPORTED" | "EXPECTED_RISK_MISSING" | "SIMULATION_STATUS_UNVERIFIED" | "SIMULATION_FAILED_OR_DIVERGED" | "GOVERNANCE_STATUS_UNAVAILABLE" | "CERTIFICATION_READINESS_UNAVAILABLE" | "REPLAY_READINESS_UNAVAILABLE" | "ROLLBACK_READINESS_UNAVAILABLE" | "TENANT_ISOLATION_VIOLATED" | "CALCULATION_NONDETERMINISTIC" | "RESPONSE_PROPOSAL_HIDDEN" | "REJECTED_OR_FAILED_RESPONSE_HIDDEN" | "CONDITIONAL_READINESS_MISREPRESENTED" | "AFFECTED_SCOPE_UNDETERMINED" | "CROSS_TENANT_SCOPE_BLOCKED" | "RESTRICTED_FIELD_EXPOSED" | "EXECUTION_AUTHORITY_EXPOSED" | "APPROVAL_BYPASS_EXPOSED" | "CERTIFICATION_BYPASS_EXPOSED" | "INTEGRITY_VERIFICATION_FAILED";

export type ProposedResponseDashboardRecord = Readonly<{ dashboard_record_id: string; tenant_id: string; mission_scope: string; response_proposal_id: string; response_version: string; response_type: ResponseType; response_status: ResponseStatus; response_summary: string; response_rationale: string; source_pattern_refs: readonly string[]; source_observation_refs: readonly string[]; source_outcome_refs: readonly string[]; source_recommendation_refs: readonly string[]; source_feedback_refs: readonly string[]; supporting_evidence_refs: readonly string[]; affected_mission_refs: readonly string[]; affected_operator_refs: readonly string[]; affected_capability_refs: readonly string[]; affected_policy_refs: readonly string[]; expected_benefit: string; expected_risk: string; confidence_assessment: number; governance_review_status: GovernanceOutcome; constitutional_review_status: GovernanceOutcome; authority_review_status: GovernanceOutcome; simulation_status: SimulationState; simulation_refs: readonly string[]; certification_readiness: CertificationReadinessState; certification_refs: readonly string[]; replay_readiness: ReplayState; replay_refs: readonly string[]; rollback_readiness: CertificationReadinessState; rollback_refs: readonly string[]; approval_status: "NOT_REQUESTED" | "PENDING" | "APPROVED" | "REJECTED" | "DEFERRED"; approval_refs: readonly string[]; visible_to_roles: readonly DashboardRole[]; restricted_fields: readonly string[]; alerts: readonly string[]; created_at: string; updated_at: string; integrity_hash: string }>;

export type ResponseProposalQueue = Readonly<{ queue_id: string; proposal_refs: readonly string[]; category_counts: readonly string[]; retained_terminal_states: readonly ResponseStatus[]; blocker_count: number; next_permitted_action: NextPermittedResponseAction; deterministic_ordering: boolean; integrity_hash: string }>;
export type ResponseDetailView = Readonly<{ view_id: string; proposal_ref: string; traceability_refs: readonly string[]; unresolved_blockers: readonly string[]; proposal_distinguished_from_authority: boolean; rejected_failed_superseded_retained: boolean; integrity_hash: string }>;
export type ResponseRationaleView = Readonly<{ view_id: string; triggering_patterns: readonly string[]; reason_codes: readonly string[]; causal_classification: "CORRELATION" | "SUSPECTED_CAUSATION" | "DEMONSTRATED_CAUSATION" | "POLICY_DRIVEN" | "PRECAUTIONARY" | "INSUFFICIENT_EVIDENCE_HYPOTHESIS"; alternatives_considered: readonly string[]; no_action_considered: boolean; consequence_of_inaction: string; uncertainty_statement: string; integrity_hash: string }>;
export type ExpectedBenefitView = Readonly<{ view_id: string; category: BenefitCategory; baseline: number; target: number; expected_improvement: number; unit: string; confidence_range: readonly number[]; supporting_evidence: readonly string[]; simulation_status: SimulationState; validation_period: string; state: "VERIFIED" | "UNVERIFIED"; paired_risk_ref: string; integrity_hash: string }>;
export type ExpectedRiskView = Readonly<{ view_id: string; category: RiskCategory; probability: number; severity: "LOW" | "MODERATE" | "HIGH" | "CRITICAL"; confidence: number; mitigation: string; residual_risk: string; governance_sensitive: boolean; rollback_required: boolean; unknown_risk_visible: boolean; integrity_hash: string }>;
export type AffectedScopeView = Readonly<{ view_id: string; scope_state: ScopeState; affected_tenants: readonly string[]; affected_missions: readonly string[]; affected_operators: readonly string[]; affected_capabilities: readonly string[]; affected_policies: readonly string[]; cross_tenant_blocked: boolean; progresses_beyond_preliminary_review: boolean; integrity_hash: string }>;
export type SimulationStatusView = Readonly<{ view_id: string; state: SimulationState; completed_scenarios: readonly string[]; remaining_scenarios: readonly string[]; expected_benefit_distinguished: boolean; simulated_benefit_distinguished: boolean; certified_benefit_distinguished: boolean; regressions: readonly string[]; progression_blocked: boolean; integrity_hash: string }>;
export type GovernanceReviewView = Readonly<{ view_id: string; governance_outcome: GovernanceOutcome; constitutional_outcome: GovernanceOutcome; authority_outcome: GovernanceOutcome; governance_blockers: readonly string[]; completed_controls: readonly string[]; approval_equals_certification: false; certification_equals_implementation: false; integrity_hash: string }>;
export type CertificationReadinessView = Readonly<{ view_id: string; state: CertificationReadinessState; evidence_complete: boolean; simulation_complete: boolean; governance_complete: boolean; replay_ready: boolean; rollback_ready: boolean; unresolved_blockers: readonly string[]; unmet_conditions: readonly string[]; ready_for_formal_certification: boolean; integrity_hash: string }>;
export type ProposalLineageExplorer = Readonly<{ explorer_id: string; lineage_flow: readonly string[]; source_referenced: boolean; versioned: boolean; replayable: boolean; tenant_isolated: boolean; integrity_verified: boolean; integrity_hash: string }>;
export type EvidenceInspectionWorkspace = Readonly<{ workspace_id: string; evidence_refs: readonly string[]; contradictory_evidence_refs: readonly string[]; rejected_evidence_refs: readonly string[]; evidence_state: EvidenceState; evidence_state_at_generation_preserved: boolean; integrity_failure_blocks_progression: boolean; integrity_hash: string }>;
export type ReplayNavigationView = Readonly<{ view_id: string; state: ReplayState; replay_steps: readonly string[]; event_ordering_verified: boolean; versions_verified: boolean; calculation_reproducible: boolean; decision_lineage_verified: boolean; integrity_hashes_verified: boolean; integrity_hash: string }>;
export type ResponseComparisonWorkspace = Readonly<{ workspace_id: string; dimensions: readonly string[]; sample_size: number; missing_data_visible: boolean; uncertainty_preserved: boolean; composite_scoring_present: boolean; automatic_ranking_present: boolean; source_values_preserved: boolean; normalization_explained: boolean; integrity_hash: string }>;
export type ResponseAlertCenter = Readonly<{ alert_id: string; alerts: readonly string[]; highest_severity: ProposedResponseAlertSeverity; critical_alerts_visible_until_resolved: boolean; integrity_hash: string }>;
export type NextPermittedActionPanel = Readonly<{ panel_id: string; action: NextPermittedResponseAction; rationale: string; mandatory_dependencies_evaluated: boolean; executes_action: false; integrity_hash: string }>;
export type ProposedResponseAuditRecord = Readonly<{ audit_id: string; actor: string; tenant_id: string; role: DashboardRole; mission_scope: string; response_proposal_id: string; response_version: string; source_pattern: string; dashboard_view: string; evidence_accessed: readonly string[]; comparison_performed: boolean; lineage_opened: boolean; replay_launched: boolean; filters_applied: readonly string[]; decision_submitted: false; authorization_result: "ALLOWED" | "DENIED"; integrity_result: "PASS" | "FAIL"; append_only: true; tenant_isolated: boolean; replayable: boolean; timestamp: string; integrity_hash: string }>;
export type ProposedResponseMetrics = Readonly<{ missing_response_proposals: number; orphaned_source_patterns: number; missing_rationale: number; missing_evidence_references: number; benefit_risk_mismatches: number; simulation_state_inconsistencies: number; governance_state_inconsistencies: number; certification_readiness_inconsistencies: number; replay_failures: number; rollback_state_inconsistencies: number; proposal_version_mismatches: number; cross_tenant_exposures: number; unauthorized_access_attempts: number; integrity_verification_failures: number; integrity_hash: string }>;
export type ProposedResponseValidationTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: "PASS" | "FAIL"; passed: boolean; failure_reason: ProposedResponseDashboardFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;

export type ProposedResponseDashboardApiSurface = Readonly<{ api_id: string; retrieve_dashboard: string; retrieve_contract: string; retrieve_sections: readonly string[]; validate_dashboard: string; inspect_dashboard: string; creation_supported: false; mutation_supported: false; execution_supported: false; production_modification_supported: false; policy_change_supported: false; strategy_change_supported: false; confidence_recalibration_supported: false; risk_recalibration_supported: false; automatic_approval_supported: false; governance_bypass_supported: false; certification_execution_supported: false; integrity_hash: string }>;
export type ProposedResponseDashboardInput = Readonly<{ scenario?: ProposedResponseDashboardScenario; tenant_id?: string; role?: DashboardRole }>;
export type ProposedResponseDashboardResult = Readonly<{ proposed_response_dashboard_version: "proposed-response-dashboard/v10.14.4.9"; dashboard_identifier: "ProposedResponseDashboard"; status: ProposedResponseDashboardStatus; api_surface: ProposedResponseDashboardApiSurface; records: readonly ProposedResponseDashboardRecord[]; proposal_queue: ResponseProposalQueue; detail_view: ResponseDetailView; rationale_view: ResponseRationaleView; benefit_view: ExpectedBenefitView; risk_view: ExpectedRiskView; affected_scope_view: AffectedScopeView; simulation_view: SimulationStatusView; governance_view: GovernanceReviewView; certification_view: CertificationReadinessView; lineage_explorer: ProposalLineageExplorer; evidence_workspace: EvidenceInspectionWorkspace; replay_view: ReplayNavigationView; comparison_workspace: ResponseComparisonWorkspace; alert_center: ResponseAlertCenter; next_action_panel: NextPermittedActionPanel; audit_records: readonly ProposedResponseAuditRecord[]; widgets: readonly ProposedResponseWidget[]; metrics: ProposedResponseMetrics; validation_tests: readonly ProposedResponseValidationTest[]; validation_outcome: ProposedResponseValidationOutcome; failures: readonly ProposedResponseDashboardFailure[]; deterministic: boolean; replayable: boolean; tenant_isolated: boolean; evidence_backed: boolean; read_only: true; advisory_only: true; write_authority_granted: false; replay_hash: string; integrity_hash: string }>;
export type ProposedResponseDashboardValidationResult = Readonly<{ dashboard_id: string | null; valid: boolean; validation_outcome: ProposedResponseValidationOutcome; failures: readonly ProposedResponseDashboardFailure[]; replay_hash_valid: boolean; integrity_hash_valid: boolean; read_only: boolean; validation_hash: string }>;
export type ProposedResponseDashboardObservabilitySurface = Readonly<{ dashboard_id: string; status: ProposedResponseDashboardStatus; validation_outcome: ProposedResponseValidationOutcome; records: number; failed_tests: number; failures: readonly ProposedResponseDashboardFailure[]; replayable: boolean; tenant_isolated: boolean; read_only: boolean; integrity_hash: string }>;
export type ProposedResponseDashboardContract = Readonly<{ doctrine: Readonly<{ version: "proposed-response-dashboard/v10.14.4.9"; widgets: readonly ProposedResponseWidget[]; response_types: readonly ResponseType[]; response_statuses: readonly ResponseStatus[]; benefit_categories: readonly BenefitCategory[]; risk_categories: readonly RiskCategory[]; scope_states: readonly ScopeState[]; simulation_states: readonly SimulationState[]; governance_outcomes: readonly GovernanceOutcome[]; certification_readiness_states: readonly CertificationReadinessState[]; replay_states: readonly ReplayState[]; required_data_sources: readonly string[]; advisory_only: true; read_only: true }>; result: ProposedResponseDashboardResult; validation: ProposedResponseDashboardValidationResult; observability: ProposedResponseDashboardObservabilitySurface }>;
