export type ReplayStabilityIntegrityOutcome = "PASS" | "CONDITIONAL_PASS" | "FAIL";
export type ReplayStabilityClassification = "STABLE" | "MINOR_VARIANCE" | "REGRESSION_DETECTED" | "INTEGRITY_FAILURE" | "GOVERNANCE_DIVERGENCE" | "DEPENDENCY_DIVERGENCE" | "INFRASTRUCTURE_DIVERGENCE" | "UNEXPLAINED_DIVERGENCE";
export type ReplayRegressionCategory = "EXECUTION" | "ORDERING" | "DEPENDENCY" | "INFRASTRUCTURE" | "GOVERNANCE" | "POLICY" | "OPTIMIZATION" | "LEARNING" | "CERTIFICATION" | "EVIDENCE";
export type ReplayDivergenceType = "INPUT" | "POLICY" | "GOVERNANCE" | "DEPENDENCY" | "INFRASTRUCTURE" | "EXECUTION_ORDER" | "OPTIMIZATION" | "LEARNING" | "CERTIFICATION" | "EVIDENCE" | "NONDETERMINISTIC" | "UNEXPLAINED";
export type ReplayStabilityIntegrityFailure =
  | "REPLAY_STABILITY_NOT_CONTINUOUSLY_VERIFIED"
  | "REPLAY_REGRESSIONS_NOT_DETERMINISTIC"
  | "REPLAY_BASELINES_MUTABLE"
  | "INTEGRITY_NOT_CONTINUOUSLY_VALIDATED"
  | "REPLAY_DIVERGENCE_NOT_CLASSIFIED"
  | "EVIDENCE_NOT_REPRODUCIBLE"
  | "REPLAY_LINEAGE_INCOMPLETE"
  | "SUPERSESSION_NOT_ADDITIVE"
  | "FAIL_CLOSED_NOT_VERIFIED"
  | "CONSTITUTIONAL_INTEGRITY_NOT_PRESERVED"
  | "REPLAY_STABILITY_NOT_CERTIFIED"
  | "HISTORICAL_RECORD_MUTATED"
  | "UNKNOWN_REPLAY_CONDITION_NOT_FAIL_CLOSED"
  | "PHASE_18_9_RISK_NOT_VALID"
  | "NON_CONSTITUTIONAL_REPLAY_WARNING";
export type ReplayStabilityIntegrityScenario = "BASELINE" | ReplayStabilityIntegrityFailure;
export type ReplayStabilityIntegrityInput = Readonly<{ scenario?: ReplayStabilityIntegrityScenario; tenant_id?: string; operator_id?: string; mission_id?: string; replay_validation_id?: string }>;

export type ReplayHealthRecord = Readonly<{ health_id: string; replay_success_rate: boolean; replay_latency: boolean; replay_consistency: boolean; replay_coverage: boolean; replay_failures: boolean; divergence_frequency: boolean; baseline_drift: boolean; integrity_violations: boolean; integrity_hash: string }>;
export type ReplayStabilityMonitor = Readonly<{ monitor_id: string; standing_constitutional_service: boolean; lifecycle_independent: boolean; continuous_verification: boolean; health_record: ReplayHealthRecord; integrity_hash: string }>;
export type ReplayRegressionEngine = Readonly<{ engine_id: string; certified_baselines_compared: boolean; previous_versions_compared: boolean; governance_revisions_compared: boolean; policy_revisions_compared: boolean; infrastructure_revisions_compared: boolean; dependency_revisions_compared: boolean; optimization_revisions_compared: boolean; deterministic_detection: boolean; regression_categories: readonly ReplayRegressionCategory[]; integrity_hash: string }>;
export type IntegrityValidator = Readonly<{ validator_id: string; immutable_lineage: boolean; cryptographic_integrity: boolean; evidence_references: boolean; replay_references: boolean; certification_references: boolean; governance_references: boolean; dependency_references: boolean; no_unauthorized_mutation: boolean; no_missing_evidence: boolean; no_orphaned_lineage: boolean; no_integrity_degradation: boolean; continuous_validation: boolean; integrity_hash: string }>;
export type ReplayBaselineRecord = Readonly<{ replay_identifier: string; certification_reference: string; operational_version: string; policy_version: string; governance_version: string; dependency_versions: readonly string[]; infrastructure_fingerprint: string; evidence_references: readonly string[]; replay_checksum: string; immutable: boolean; supersedes: string | null; integrity_hash: string }>;
export type ReplayBaselineRegistry = Readonly<{ registry_id: string; baselines: readonly ReplayBaselineRecord[]; immutable_baselines: boolean; additive_supersession: boolean; historical_baselines_preserved: boolean; integrity_hash: string }>;
export type ReplayStabilityRecord = Readonly<{ replay_validation_id: string; operational_event_reference: string; replay_reference: string; replay_baseline_reference: string; operational_version: string; governance_version: string; policy_version: string; dependency_versions: readonly string[]; infrastructure_version: string; replay_result: ReplayStabilityClassification; regression_category: ReplayRegressionCategory | null; divergence_summary: string; integrity_validation_result: "PASS" | "FAIL"; evidence_references: readonly string[]; certification_reference: string; timestamp: string; replay_hash: string; integrity_hash: string }>;
export type ReplayDivergenceAnalysis = Readonly<{ analysis_id: string; divergence_types: readonly ReplayDivergenceType[]; recognized_registry_version: string; unknown_conditions_fail_closed: boolean; deterministic_classification: boolean; unexplained_divergence_blocks_certification: boolean; integrity_hash: string }>;
export type ReplayStabilityEvidenceService = Readonly<{ service_id: string; replay_outputs: readonly string[]; execution_traces: readonly string[]; replay_hashes: readonly string[]; integrity_hashes: readonly string[]; divergence_analysis: readonly string[]; regression_reports: readonly string[]; certification_references: readonly string[]; governance_references: readonly string[]; dependency_snapshots: readonly string[]; infrastructure_fingerprints: readonly string[]; immutable_evidence: boolean; reproducible: boolean; integrity_hash: string }>;
export type ReplayStabilityLedger = Readonly<{ ledger_id: string; stability_records: readonly string[]; baseline_refs: readonly string[]; integrity_events: readonly string[]; divergence_records: readonly string[]; supersession_events: readonly string[]; replay_recommendations: readonly string[]; additive_only: boolean; immutable: boolean; integrity_hash: string }>;
export type ReplayStabilityCertificationPackage = Readonly<{ package_id: string; replay_stability_continuously_verified: boolean; replay_regressions_detected_deterministically: boolean; replay_baselines_immutable: boolean; integrity_continuously_validated: boolean; replay_divergence_classified: boolean; evidence_reproducible: boolean; replay_lineage_complete: boolean; supersession_additive: boolean; fail_closed_behavior_verified: boolean; constitutional_integrity_preserved: boolean; replay_stability_certified: boolean; evidence_refs: readonly string[]; integrity_hash: string }>;
export type ReplayStabilityIntegrityTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: ReplayStabilityIntegrityOutcome; passed: boolean; failure_reason: ReplayStabilityIntegrityFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;

export type ReplayStabilityIntegrityResult = Readonly<{ phase_version: "replay-stability-integrity/v18.10"; phase_identifier: "ReplayStabilityIntegrity"; continuous_risk_intelligence_ref: string; stability_monitor: ReplayStabilityMonitor; regression_engine: ReplayRegressionEngine; integrity_validator: IntegrityValidator; baseline_registry: ReplayBaselineRegistry; stability_record: ReplayStabilityRecord; divergence_analysis: ReplayDivergenceAnalysis; evidence_service: ReplayStabilityEvidenceService; stability_ledger: ReplayStabilityLedger; certification_package: ReplayStabilityCertificationPackage; certification_tests: readonly ReplayStabilityIntegrityTest[]; failures: readonly ReplayStabilityIntegrityFailure[]; outcome: ReplayStabilityIntegrityOutcome; replay_hash: string; integrity_hash: string }>;
export type ReplayStabilityIntegrityValidation = Readonly<{ valid: boolean; outcome: ReplayStabilityIntegrityOutcome; monitor_valid: boolean; regression_valid: boolean; integrity_valid: boolean; baseline_valid: boolean; stability_record_valid: boolean; divergence_valid: boolean; evidence_valid: boolean; ledger_valid: boolean; certification_package_valid: boolean; certification_valid: boolean; result_replay_valid: boolean; failures: readonly ReplayStabilityIntegrityFailure[]; integrity_hash: string }>;
export type ReplayStabilityIntegrityBundle = Readonly<{ doctrine: Readonly<{ version: "replay-stability-integrity/v18.10"; upstream_phase: "continuous-risk-intelligence/v18.9"; stability_classifications: readonly ReplayStabilityClassification[]; regression_categories: readonly ReplayRegressionCategory[]; divergence_types: readonly ReplayDivergenceType[]; certification_outcomes: readonly ReplayStabilityIntegrityOutcome[] }>; result: ReplayStabilityIntegrityResult; validation: ReplayStabilityIntegrityValidation }>;
