export type ReplayCertificationStatus = "PASS" | "FAIL";
export type ReplayValidationStatus = "PASS" | "FAIL";
export type ReplayCertificationDecision = "CERTIFIED" | "REJECTED";
export type ReplayCertificationWidget = "Replay Certification" | "Input Reconstruction" | "Evidence Reconstruction" | "Reasoning Equivalence" | "Output Reconstruction" | "Governance Replay" | "Constitutional Replay" | "Simulation Replay" | "Ledger Replay" | "Replay Integrity" | "Certification Report" | "Reconstruction Report";
export type AdaptiveReplaySubsystem = "Outcome Observation" | "Outcome Normalization" | "Recommendation Effectiveness" | "Pattern Intelligence" | "Strategy Evolution" | "Confidence Adaptation" | "Risk Adaptation" | "Governance-Aware Adaptation" | "Operator Feedback Integration" | "Adaptation Proposal Engine" | "Adaptive Simulation" | "Drift Defense" | "Adaptive Memory" | "Adaptive Dashboard" | "Adaptive Certification";
export type ReplayLedgerRef = "OutcomeObservationLedger" | "NormalizedOutcomeLedger" | "RecommendationEffectivenessLedger" | "PatternIntelligenceLedger" | "StrategyEvolutionLedger" | "ConfidenceAdaptationLedger" | "RiskAdaptationLedger" | "GovernanceAdaptationLedger" | "OperatorFeedbackLedger" | "AdaptationProposalLedger" | "AdaptationSimulationLedger" | "AdaptiveDriftLedger" | "AdaptiveMemoryLedger" | "AdaptiveDashboardLedger" | "AdaptiveCertificationLedger";

export type ReplayCertificationScenario =
  | "BASELINE" | "INCOMPLETE_RECONSTRUCTION" | "MISSING_INPUTS" | "MISSING_EVIDENCE" | "NORMALIZED_OUTCOME_DRIFT" | "REASONING_DIVERGENCE" | "RECOMMENDATION_REASONING_DIVERGENCE" | "CONFIDENCE_CALCULATION_DIVERGENCE" | "RISK_CALCULATION_DIVERGENCE" | "PROPOSAL_GENERATION_DIVERGENCE" | "OUTPUT_DIVERGENCE" | "GOVERNANCE_MISMATCH" | "CONSTITUTIONAL_MISMATCH" | "SUPPRESSION_DIVERGENCE" | "PRIORITIZATION_DIVERGENCE" | "SIMULATION_DIVERGENCE" | "COUNTERFACTUAL_DIVERGENCE" | "DASHBOARD_DIVERGENCE" | "CERTIFICATION_OUTCOME_DIVERGENCE" | "LEDGER_HISTORY_INCOMPLETE" | "REPLAY_REFERENCE_OMISSION" | "EVIDENCE_LINEAGE_GAP" | "INTEGRITY_FAILURE" | "APPEND_ONLY_VIOLATION" | "HIDDEN_RUNTIME_DEPENDENCY" | "REPLAY_NONDETERMINISM" | "EQUIVALENCE_BELOW_THRESHOLD";

export type ReplayCertificationFailure =
  | "INCOMPLETE_REPLAY_RECONSTRUCTION" | "INPUT_RECONSTRUCTION_INCOMPLETE" | "EVIDENCE_RECONSTRUCTION_INCOMPLETE" | "NORMALIZED_OUTCOME_REPLAY_DIVERGED" | "REASONING_REPLAY_DIVERGED" | "RECOMMENDATION_REASONING_REPLAY_DIVERGED" | "CONFIDENCE_CALCULATION_REPLAY_DIVERGED" | "RISK_CALCULATION_REPLAY_DIVERGED" | "PROPOSAL_GENERATION_REPLAY_DIVERGED" | "OUTPUT_REPLAY_DIVERGED" | "GOVERNANCE_REPLAY_MISMATCH" | "CONSTITUTIONAL_REPLAY_MISMATCH" | "SUPPRESSION_REPLAY_DIVERGED" | "PRIORITIZATION_REPLAY_DIVERGED" | "SIMULATION_REPLAY_DIVERGED" | "COUNTERFACTUAL_REPLAY_DIVERGED" | "DASHBOARD_REPLAY_DIVERGED" | "CERTIFICATION_OUTCOME_REPLAY_DIVERGED" | "LEDGER_HISTORY_INCOMPLETE" | "REPLAY_REFERENCE_OMITTED" | "EVIDENCE_LINEAGE_INCOMPLETE" | "INTEGRITY_HASH_MISMATCH" | "APPEND_ONLY_LEDGER_VIOLATION" | "HIDDEN_RUNTIME_DEPENDENCY_DETECTED" | "REPLAY_NONDETERMINISM_DETECTED" | "REPLAY_EQUIVALENCE_BELOW_THRESHOLD";

export type ReplayCertificationRecord = Readonly<{ certification_id: string; tenant_id: string; mission_id: string; original_execution_id: string; replay_execution_id: string; input_reconstruction_status: ReplayValidationStatus; evidence_reconstruction_status: ReplayValidationStatus; reasoning_reconstruction_status: ReplayValidationStatus; output_reconstruction_status: ReplayValidationStatus; governance_replay_status: ReplayValidationStatus; constitutional_replay_status: ReplayValidationStatus; simulation_replay_status: ReplayValidationStatus; replay_completeness_status: ReplayValidationStatus; replay_determinism_status: ReplayValidationStatus; replay_integrity_status: ReplayValidationStatus; replay_equivalence_score: number; findings: readonly ReplayCertificationFailure[]; evidence_refs: readonly string[]; governance_refs: readonly string[]; constitutional_refs: readonly string[]; replay_refs: readonly string[]; ledger_refs: readonly ReplayLedgerRef[]; certification_status: ReplayCertificationDecision; certification_timestamp: string; integrity_hash: string }>;
export type InputReconstructionCertification = Readonly<{ certification_id: string; mission_context_reconstructed: boolean; observation_records_reconstructed: boolean; normalized_outcomes_reconstructed: boolean; evidence_refs_reconstructed: boolean; governance_state_reconstructed: boolean; constitutional_state_reconstructed: boolean; operator_context_reconstructed: boolean; tenant_context_reconstructed: boolean; integrity_hash: string }>;
export type EvidenceReconstructionCertification = Readonly<{ certification_id: string; truth_ledger_refs_reconstructed: boolean; evidence_lineage_complete: boolean; historical_outcomes_reconstructed: boolean; operator_feedback_reconstructed: boolean; simulation_evidence_reconstructed: boolean; governance_evidence_reconstructed: boolean; adaptive_memory_refs_reconstructed: boolean; evidence_ordering_identical: boolean; evidence_immutable: boolean; integrity_hash: string }>;
export type ReasoningEquivalenceCertification = Readonly<{ certification_id: string; adaptive_reasoning_reproduced: boolean; recommendation_reasoning_reproduced: boolean; pattern_analysis_reproduced: boolean; confidence_analysis_reproduced: boolean; risk_analysis_reproduced: boolean; strategy_evolution_reproduced: boolean; suppression_rationale_reproduced: boolean; prioritization_rationale_reproduced: boolean; integrity_hash: string }>;
export type OutputReconstructionCertification = Readonly<{ certification_id: string; adaptive_proposals_reproduced: boolean; recommendation_scores_reproduced: boolean; confidence_scores_reproduced: boolean; risk_scores_reproduced: boolean; governance_decisions_reproduced: boolean; simulation_outputs_reproduced: boolean; certification_outcomes_reproduced: boolean; dashboard_artifacts_reproduced: boolean; integrity_hash: string }>;
export type GovernanceReplayCertification = Readonly<{ certification_id: string; policy_evaluations_reproduced: boolean; governance_decisions_reproduced: boolean; approval_workflows_reproduced: boolean; escalation_paths_reproduced: boolean; exception_handling_reproduced: boolean; audit_trails_reproduced: boolean; integrity_hash: string }>;
export type ConstitutionalReplayCertification = Readonly<{ certification_id: string; constitutional_evaluations_reproduced: boolean; authority_boundaries_reproduced: boolean; doctrine_enforcement_reproduced: boolean; constraint_validation_reproduced: boolean; human_authority_decisions_reproduced: boolean; integrity_hash: string }>;
export type SimulationReplayCertification = Readonly<{ certification_id: string; adaptive_simulations_reproduced: boolean; counterfactual_simulations_reproduced: boolean; rollback_simulations_reproduced: boolean; proposal_evaluations_reproduced: boolean; scenario_analysis_reproduced: boolean; state_transitions_identical: boolean; integrity_hash: string }>;
export type LedgerReplayCertification = Readonly<{ certification_id: string; required_ledgers: readonly ReplayLedgerRef[]; ledger_history_complete: boolean; append_only_history_verified: boolean; no_external_state_required: boolean; ledger_ordering_identical: boolean; ledger_hashes_verified: boolean; integrity_hash: string }>;
export type ReplayIntegrityCertification = Readonly<{ certification_id: string; immutable_timestamps_verified: boolean; cryptographic_hashes_verified: boolean; evidence_integrity_verified: boolean; replay_reference_integrity_verified: boolean; governance_reference_integrity_verified: boolean; constitutional_reference_integrity_verified: boolean; operator_reference_integrity_verified: boolean; certification_reference_integrity_verified: boolean; integrity_hash: string }>;
export type ReplayCertificationReport = Readonly<{ report_id: string; certification_outcome: ReplayCertificationDecision; replay_completeness_assessment: ReplayValidationStatus; determinism_assessment: ReplayValidationStatus; integrity_validation: ReplayValidationStatus; input_reconstruction_analysis: ReplayValidationStatus; evidence_reconstruction_analysis: ReplayValidationStatus; reasoning_equivalence_result: ReplayValidationStatus; output_equivalence_result: ReplayValidationStatus; governance_replay_validation: ReplayValidationStatus; constitutional_replay_validation: ReplayValidationStatus; simulation_replay_validation: ReplayValidationStatus; replay_equivalence_score: number; findings: readonly ReplayCertificationFailure[]; remediation_actions: readonly string[]; production_readiness_recommendation: "READY" | "BLOCKED"; integrity_hash: string }>;
export type ReplayReconstructionReport = Readonly<{ report_id: string; replay_coverage_by_subsystem: readonly AdaptiveReplaySubsystem[]; ledger_utilization: readonly ReplayLedgerRef[]; evidence_lineage_verified: boolean; reconstruction_timelines: readonly string[]; state_transition_comparisons: readonly string[]; replay_fidelity_score: number; integrity_verified: boolean; governance_consistency_verified: boolean; constitutional_consistency_verified: boolean; certification_evidence_refs: readonly string[]; integrity_hash: string }>;
export type ReplayCertificationTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: "PASS" | "FAIL"; passed: boolean; failure_reason: ReplayCertificationFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;
export type ReplayCertificationApiSurface = Readonly<{ api_id: string; retrieve_dashboard: string; retrieve_contract: string; retrieve_sections: readonly string[]; validate_certification: string; inspect_certification: string; mutation_supported: false; hidden_state_supported: false; production_advancement_supported: false; override_supported: false; integrity_hash: string }>;
export type ReplayCertificationInput = Readonly<{ scenario?: ReplayCertificationScenario; tenant_id?: string; mission_id?: string }>;
export type ReplayCertificationResult = Readonly<{ replay_certification_version: "replay-certification/v10.15.3"; certification_identifier: "ReplayCertification"; status: ReplayCertificationStatus; api_surface: ReplayCertificationApiSurface; record: ReplayCertificationRecord; input_reconstruction: InputReconstructionCertification; evidence_reconstruction: EvidenceReconstructionCertification; reasoning_equivalence: ReasoningEquivalenceCertification; output_reconstruction: OutputReconstructionCertification; governance_replay: GovernanceReplayCertification; constitutional_replay: ConstitutionalReplayCertification; simulation_replay: SimulationReplayCertification; ledger_replay: LedgerReplayCertification; replay_integrity: ReplayIntegrityCertification; certification_report: ReplayCertificationReport; reconstruction_report: ReplayReconstructionReport; widgets: readonly ReplayCertificationWidget[]; validation_tests: readonly ReplayCertificationTest[]; failures: readonly ReplayCertificationFailure[]; complete: boolean; deterministic: boolean; integrity_protected: boolean; ledger_only: boolean; production_ready: boolean; replay_hash: string; integrity_hash: string }>;
export type ReplayCertificationValidationResult = Readonly<{ certification_id: string | null; valid: boolean; status: ReplayCertificationStatus; failures: readonly ReplayCertificationFailure[]; replay_hash_valid: boolean; integrity_hash_valid: boolean; certification_hash: string }>;
export type ReplayCertificationObservability = Readonly<{ certification_id: string; status: ReplayCertificationStatus; equivalence_score: number; failed_tests: number; failures: readonly ReplayCertificationFailure[]; complete: boolean; deterministic: boolean; ledger_only: boolean; production_ready: boolean; integrity_hash: string }>;
export type ReplayCertificationContract = Readonly<{ doctrine: Readonly<{ version: "replay-certification/v10.15.3"; widgets: readonly ReplayCertificationWidget[]; subsystems: readonly AdaptiveReplaySubsystem[]; required_ledgers: readonly ReplayLedgerRef[]; required_equivalence_score: 1; ledger_only_replay_required: true; hidden_state_prohibited: true; certification_required: true }>; result: ReplayCertificationResult; validation: ReplayCertificationValidationResult; observability: ReplayCertificationObservability }>;
