export type ReplayEngineDecision = "REPLAY_ENGINE_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type ReplayEngineFailure =
  | "W2_9_MEMORY_ENGINE_INVALID" | "W2_10_RUNTIME_ORCHESTRATOR_INVALID" | "W2_11_DELEGATION_ENGINE_INVALID" | "W2_12_COLLABORATION_ENGINE_INVALID" | "W2_13_EVIDENCE_ENGINE_INVALID"
  | "RUNTIME_REPLAY_MISSING" | "RUNTIME_REPLAY_NON_DETERMINISTIC" | "RUNTIME_STATE_RECONSTRUCTION_FAILED" | "TIMELINE_RECONSTRUCTION_FAILED"
  | "DECISION_REPLAY_MISSING" | "DECISION_REPLAY_INACCURATE" | "AUTHORITY_POLICY_SAFETY_REPLAY_FAILED"
  | "EXECUTION_CONTROL_REPLAY_MISSING" | "CHECKPOINT_REPLAY_FAILED" | "RECOVERY_REPLAY_FAILED" | "LIFECYCLE_REPLAY_FAILED"
  | "DIVERGENCE_DETECTION_MISSING" | "DIVERGENCE_UNDETECTED" | "ROOT_CAUSE_ATTRIBUTION_MISSING" | "REPLAY_CONFIDENCE_MISSING"
  | "REPLAY_SERVICE_MISSING" | "REPLAY_API_MISSING" | "TIMELINE_API_MISSING" | "DIVERGENCE_API_MISSING"
  | "REPLAY_EXPLORER_MISSING" | "REPLAY_REPORTS_MISSING" | "REPLAY_REPORT_NOT_SIGNED" | "REPLAY_REPORT_NOT_IMMUTABLE"
  | "TENANT_ISOLATION_FAILED" | "REPLAY_AUTHORIZATION_MISSING" | "EVIDENCE_INTEGRITY_BYPASSED" | "REPLAY_AUDIT_LOGGING_MISSING"
  | "REPLAY_EVIDENCE_MISSING" | "REPLAY_EVIDENCE_NOT_PUBLISHED" | "REPLAY_EVIDENCE_NOT_IMMUTABLE" | "REPLAY_ENGINE_QUALIFICATION_FAILED";
export type ReplayEngineScenario = "BASELINE" | "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | ReplayEngineFailure;
export type ReplayEngineInput = Readonly<{ scenario?: ReplayEngineScenario; seed?: string }>;
export type RuntimeReplay = Readonly<{ service_id: string; snapshot_loader: boolean; timeline_builder: boolean; context_restoration: boolean; state_reconstruction: boolean; event_replay_engine: boolean; runtime_validation: boolean; time_navigation: boolean; session_management: boolean; complete_execution_reconstruction: boolean; deterministic_restoration: boolean; integrity_hash: string }>;
export type DecisionReplay = Readonly<{ service_id: string; decision_timeline: boolean; planning_replay: boolean; memory_retrieval_replay: boolean; tool_invocation_replay: boolean; capability_selection_replay: boolean; policy_decision_replay: boolean; safety_decision_replay: boolean; authority_decision_replay: boolean; approvals_replay: boolean; restrictions_replay: boolean; delegation_replay: boolean; collaboration_replay: boolean; accurate_reconstruction: boolean; integrity_hash: string }>;
export type ExecutionControlReplay = Readonly<{ service_id: string; task_replay: boolean; workflow_replay: boolean; checkpoint_replay: boolean; recovery_replay: boolean; suspension_replay: boolean; resume_replay: boolean; failure_replay: boolean; retry_replay: boolean; lifecycle_reconstruction: boolean; orchestration_replay: boolean; integrity_hash: string }>;
export type DivergenceDetection = Readonly<{ engine_id: string; timeline_comparison: boolean; decision_comparison: boolean; memory_comparison: boolean; tool_output_comparison: boolean; runtime_state_comparison: boolean; event_comparison: boolean; evidence_comparison: boolean; drift_identification: boolean; divergence_reports: boolean; replay_confidence: boolean; deterministic_validation: boolean; root_cause_attribution: boolean; integrity_hash: string }>;
export type ReplayServiceApis = Readonly<{ api_id: string; start_replay: boolean; resume_replay: boolean; pause_replay: boolean; stop_replay: boolean; compare_replay: boolean; validate_replay: boolean; get_timeline: boolean; get_execution: boolean; get_checkpoint: boolean; get_decision: boolean; get_evidence: boolean; compare_decision: boolean; compare_state: boolean; compare_runtime: boolean; compare_evidence: boolean; generate_report: boolean; stable: boolean; integrity_hash: string }>;
export type ReplayExplorer = Readonly<{ explorer_id: string; execution_timeline: boolean; decision_visualization: boolean; evidence_navigation: boolean; replay_inspection: boolean; state_visualization: boolean; divergence_visualization: boolean; secure_access: boolean; tenant_isolated: boolean; integrity_hash: string }>;
export type ReplayReports = Readonly<{ report_id: string; replay_reports: boolean; divergence_reports: boolean; deterministic_verification_reports: boolean; replay_evidence: boolean; certification_reports: boolean; signed: boolean; immutable: boolean; audit_ready: boolean; integrity_hash: string }>;
export type ReplaySecurity = Readonly<{ security_id: string; tenant_isolation: boolean; authority_validation: boolean; evidence_integrity: boolean; immutable_replay_records: boolean; replay_authorization: boolean; signed_reports: boolean; audit_logging: boolean; integrity_hash: string }>;
export type ReplayEvidence = Readonly<{ ledger_id: string; records: readonly string[]; replay_evidence: boolean; runtime_replay_evidence: boolean; decision_replay_evidence: boolean; divergence_evidence: boolean; deterministic_validation_evidence: boolean; audit_records: boolean; certification_evidence: boolean; published_to_evidence_service: boolean; immutable: boolean; integrity_hash: string }>;
export type ReplayEngineReadiness = Readonly<{ readiness_id: string; decision: ReplayEngineDecision; phase_ready: boolean; memory_ready: boolean; runtime_ready: boolean; delegation_ready: boolean; collaboration_ready: boolean; evidence_ready: boolean; runtime_replay_ready: boolean; decision_replay_ready: boolean; execution_control_ready: boolean; divergence_ready: boolean; apis_ready: boolean; explorer_ready: boolean; reports_ready: boolean; security_ready: boolean; replay_evidence_ready: boolean; no_unexplained_divergence: boolean; failures: readonly ReplayEngineFailure[]; integrity_hash: string }>;
export type ReplayEngineResult = Readonly<{ phase_version: "replay-engine/w2.14"; phase_identifier: "ReplayEngine"; memory_engine_ref: "memory-engine/w2.9"; runtime_orchestrator_ref: "runtime-orchestrator/w2.10"; delegation_engine_ref: "delegation-engine/w2.11"; collaboration_engine_ref: "collaboration-engine/w2.12"; evidence_engine_ref: "evidence-engine/w2.13"; runtime_replay: RuntimeReplay; decision_replay: DecisionReplay; execution_control: ExecutionControlReplay; divergence_detection: DivergenceDetection; apis: ReplayServiceApis; explorer: ReplayExplorer; reports: ReplayReports; security: ReplaySecurity; evidence: ReplayEvidence; readiness: ReplayEngineReadiness; replay_hash: string; integrity_hash: string }>;
export type ReplayEngineValidation = Readonly<{ valid: boolean; decision: ReplayEngineDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; runtime_replay_valid: boolean; decision_replay_valid: boolean; execution_control_valid: boolean; divergence_valid: boolean; apis_valid: boolean; explorer_valid: boolean; reports_valid: boolean; security_valid: boolean; evidence_valid: boolean; readiness_valid: boolean; failures: readonly ReplayEngineFailure[]; integrity_hash: string }>;
export type ReplayEngineBundle = Readonly<{ doctrine: Readonly<{ version: "replay-engine/w2.14"; owns_runtime_replay: true; owns_decision_replay: true; owns_execution_control_replay: true; owns_divergence_detection: true; owns_replay_apis: true; owns_replay_explorer: true; owns_replay_reports: true; owns_replay_security: true; owns_replay_evidence: true; verification_not_execution: true; qualification_gate: "Replay Engine Qualification Gate" }>; result: ReplayEngineResult; validation: ReplayEngineValidation }>;
