export type ResourceSchedulingCapacityOutcome = "PASS" | "CONDITIONAL_PASS" | "FAIL";
export type ResourceClass = "COMPUTE" | "MEMORY" | "STORAGE" | "NETWORK" | "INFERENCE" | "REPLAY" | "SYSTEM";
export type ResourceLifecycleState = "REQUESTED" | "VALIDATED" | "RESERVED" | "ALLOCATED" | "ACTIVE" | "MODIFIED" | "SUSPENDED" | "RELEASED" | "ARCHIVED";
export type CapacityState = "AVAILABLE" | "RESERVED" | "ALLOCATED" | "DEGRADED" | "EXHAUSTED" | "RETIRED";
export type ReservationState = "REQUESTED" | "APPROVED" | "RESERVED" | "EXPIRED" | "CONSUMED" | "CANCELLED";
export type SchedulerDecision = "ALLOCATE" | "REJECT_INSUFFICIENT_CAPACITY" | "REJECT_QUOTA_EXCEEDED" | "REJECT_INVALID_ASSIGNMENT" | "REJECT_POLICY_VIOLATION" | "REJECT_GOVERNANCE";
export type ResourceSchedulingCapacityFailure =
  | "ALLOCATION_NOT_DETERMINISTIC"
  | "CONCURRENT_ASSIGNMENTS_NOT_RESOLVED_DETERMINISTICALLY"
  | "STALE_ASSIGNMENT_PROPOSALS_NOT_REJECTED"
  | "ACCEPTED_ASSIGNMENTS_SILENTLY_OVERWRITTEN"
  | "QUOTAS_NOT_ENFORCED"
  | "REPLAY_NOT_PRESERVED"
  | "RESOURCE_SCHEDULING_NOT_CERTIFIED"
  | "TENANT_ISOLATION_VIOLATED"
  | "GOVERNANCE_BYPASSED"
  | "ALLOCATION_LEDGER_MUTABLE"
  | "FORECASTS_MODIFY_ALLOCATIONS"
  | "SCHEDULING_DEPENDS_ON_TIMING"
  | "REGIONAL_ASSIGNMENT_NOT_VALIDATED"
  | "PHASE_17_3_REGISTRY_NOT_VALID"
  | "NON_CONSTITUTIONAL_SCHEDULING_WARNING";
export type ResourceSchedulingCapacityScenario = "BASELINE" | ResourceSchedulingCapacityFailure;
export type ResourceSchedulingCapacityInput = Readonly<{ scenario?: ResourceSchedulingCapacityScenario; tenant_id?: string; operator_id?: string; mission_id?: string; request_id?: string; region?: string; requested_capacity?: number; quota_limit?: number }>;

export type ResourceAllocationRecord = Readonly<{ allocation_id: string; tenant_id: string; resource_class: ResourceClass; allocation_policy: string; requested_capacity: number; approved_capacity: number; regional_assignment: string; scheduler_decision: SchedulerDecision; quota_reference: string; governance_authority: string; replay_reference: string; integrity_hash: string }>;
export type ResourceScheduler = Readonly<{ scheduler_id: string; scheduled_requests: readonly string[]; validates_capacity: boolean; enforces_quotas: boolean; reserves_resources: boolean; allocates_resources: boolean; records_lineage: boolean; replay_supported: boolean; deterministic_ordering: boolean; independent_of_processing_latency: boolean; independent_of_wall_clock: boolean; independent_of_topology: boolean; independent_of_async_order: boolean; integrity_hash: string }>;
export type CapacityPlanner = Readonly<{ planner_id: string; utilization_forecast: readonly number[]; regional_capacity_planning: boolean; infrastructure_reservation: boolean; growth_analysis: boolean; exhaustion_prediction: boolean; capacity_certification: boolean; capacity_states: readonly CapacityState[]; never_overrides_constitutional_rules: boolean; integrity_hash: string }>;
export type QuotaManager = Readonly<{ quota_manager_id: string; quota_categories: readonly ResourceClass[]; quota_limit: number; requested_capacity: number; approved_capacity: number; quota_available: boolean; deterministic_decision: boolean; timing_independent: boolean; quota_changes_governed: boolean; integrity_hash: string }>;
export type ResourceReservationService = Readonly<{ reservation_id: string; reservation_states: readonly ReservationState[]; current_state: ReservationState; deterministic_guarantee: boolean; expiration_preserves_evidence: boolean; consumed_by_allocation_ref: string; integrity_hash: string }>;
export type ResourceClassificationRegistry = Readonly<{ registry_id: string; resource_classes: readonly ResourceClass[]; classifications_versioned: boolean; existing_classifications_not_reinterpreted: boolean; extensible_by_constitutional_amendment: boolean; integrity_hash: string }>;
export type SchedulingPolicyEngine = Readonly<{ policy_engine_id: string; policies: readonly string[]; policy_version: string; deterministic_evaluation: boolean; governance_authorized_changes: boolean; timing_independent: boolean; integrity_hash: string }>;
export type AllocationValidationService = Readonly<{ validation_id: string; tenant_qualification_valid: boolean; regional_assignment_valid: boolean; available_capacity: boolean; quota_available: boolean; governance_authorization: boolean; scheduler_policy_valid: boolean; replay_consistency: boolean; stale_assignment_rejected: boolean; silent_reassignment_prevented: boolean; validation_passed: boolean; integrity_hash: string }>;
export type CapacityForecastEngine = Readonly<{ forecast_id: string; supports_infrastructure_planning: boolean; supports_quota_analysis: boolean; supports_regional_expansion: boolean; supports_workload_balancing: boolean; supports_certification_readiness: boolean; advisory_only: boolean; modifies_allocation_decisions: boolean; integrity_hash: string }>;
export type AllocationLedgerEntry = Readonly<{ ledger_entry_id: string; sequence: number; allocation_ref: string; request_id: string; scheduler_decision: SchedulerDecision; allocated_resources: readonly string[]; regional_assignment_ref: string; quota_ref: string; lifecycle_state: ResourceLifecycleState; replay_ref: string; governance_ref: string; append_only: boolean; immutable: boolean; integrity_hash: string }>;
export type AllocationReplayService = Readonly<{ replay_id: string; reconstructs_scheduling_order: boolean; reconstructs_capacity_availability: boolean; reconstructs_quota_decisions: boolean; reconstructs_allocation_decisions: boolean; reconstructs_reservation_state: boolean; reconstructs_regional_assignments: boolean; reconstructs_governance_approvals: boolean; divergence_classified: boolean; identical_allocation_decisions: boolean; replay_refs: readonly string[]; integrity_hash: string }>;
export type CapacityMonitoringDashboard = Readonly<{ dashboard_id: string; resource_utilization_visible: boolean; allocation_activity_visible: boolean; quota_consumption_visible: boolean; reservation_status_visible: boolean; scheduler_health_visible: boolean; replay_status_visible: boolean; regional_capacity_visible: boolean; policy_compliance_visible: boolean; operational: boolean; integrity_hash: string }>;
export type ResourceSchedulingCertificationPackage = Readonly<{ package_id: string; deterministic_scheduling: boolean; quota_enforcement: boolean; replay_reproducibility: boolean; immutable_allocation_lineage: boolean; tenant_isolation: boolean; governance_compliance: boolean; regional_assignment_validation: boolean; scheduler_determinism: boolean; resource_scheduling_certified: boolean; evidence_refs: readonly string[]; integrity_hash: string }>;
export type ResourceSchedulingCapacityTest = Readonly<{ test_id: string; name: string; expected: "PASS"; actual: ResourceSchedulingCapacityOutcome; passed: boolean; failure_reason: ResourceSchedulingCapacityFailure | null; evidence_refs: readonly string[]; integrity_hash: string }>;

export type ResourceSchedulingCapacityResult = Readonly<{ phase_version: "resource-scheduling-capacity-management/v17.4"; phase_identifier: "ResourceSchedulingCapacityManagement"; global_tenant_registry_regional_assignment_ref: string; allocation_record: ResourceAllocationRecord; scheduler: ResourceScheduler; capacity_planner: CapacityPlanner; quota_manager: QuotaManager; reservation_service: ResourceReservationService; classification_registry: ResourceClassificationRegistry; policy_engine: SchedulingPolicyEngine; allocation_validation: AllocationValidationService; forecast_engine: CapacityForecastEngine; allocation_ledger: readonly AllocationLedgerEntry[]; replay_service: AllocationReplayService; dashboard: CapacityMonitoringDashboard; certification_package: ResourceSchedulingCertificationPackage; certification_tests: readonly ResourceSchedulingCapacityTest[]; failures: readonly ResourceSchedulingCapacityFailure[]; outcome: ResourceSchedulingCapacityOutcome; replay_hash: string; integrity_hash: string }>;
export type ResourceSchedulingCapacityValidation = Readonly<{ valid: boolean; outcome: ResourceSchedulingCapacityOutcome; allocation_valid: boolean; scheduler_valid: boolean; capacity_valid: boolean; quota_valid: boolean; reservation_valid: boolean; classification_valid: boolean; policy_valid: boolean; validation_valid: boolean; forecast_valid: boolean; ledger_valid: boolean; replay_valid: boolean; dashboard_valid: boolean; certification_package_valid: boolean; certification_valid: boolean; result_replay_valid: boolean; failures: readonly ResourceSchedulingCapacityFailure[]; integrity_hash: string }>;
export type ResourceSchedulingCapacityBundle = Readonly<{ doctrine: Readonly<{ version: "resource-scheduling-capacity-management/v17.4"; upstream_phase: "global-tenant-registry-regional-assignment/v17.3"; resource_classes: readonly ResourceClass[]; resource_lifecycle_states: readonly ResourceLifecycleState[]; capacity_states: readonly CapacityState[]; reservation_states: readonly ReservationState[]; scheduler_decisions: readonly SchedulerDecision[]; certification_outcomes: readonly ResourceSchedulingCapacityOutcome[] }>; result: ResourceSchedulingCapacityResult; validation: ResourceSchedulingCapacityValidation }>;
