export type RiskAssessmentDecision = "RISK_ASSESSMENT_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type OperationalRiskSeverity = "LOW" | "MODERATE" | "HIGH" | "CRITICAL";
export type OperationalRiskTrend = "IMPROVING" | "STABLE" | "DETERIORATING" | "ACCELERATING";
export type RiskAssessmentFailure =
  | "MC_2_SCENARIO_PLANNING_INVALID" | "MC_3_DECISION_SUPPORT_INVALID" | "MC_5_OPERATIONAL_EVIDENCE_REPLAY_INVALID" | "MC_6_DIGITAL_TWIN_INVALID" | "MC_7_SIMULATION_INVALID"
  | "TEMPORAL_ANALYTICS_CONTRACT_MISSING" | "TEMPORAL_ANALYTICS_NOT_AUTHORITATIVE" | "RISK_EVALUATION_ENGINE_MISSING" | "RISK_EVALUATION_NON_DETERMINISTIC" | "CONFIDENCE_EVALUATION_MISSING" | "SEVERITY_DETERMINATION_MISSING" | "EXPOSURE_ASSESSMENT_MISSING" | "RISK_REGISTRY_MISSING" | "RISK_RECORD_LINEAGE_MISSING" | "RISK_TREND_ENGINE_MISSING" | "TREND_EVIDENCE_MISSING" | "RISK_FORECAST_ENGINE_MISSING" | "FORECAST_EVIDENCE_MISSING" | "RISK_CORRELATION_ENGINE_MISSING" | "CASCADING_RISK_DETECTION_MISSING" | "CORRELATION_EVIDENCE_MISSING" | "RISK_PRIORITIZATION_ENGINE_MISSING" | "PRIORITIZATION_NOT_GOVERNED" | "RISK_EXPLAINABILITY_ENGINE_MISSING" | "OPAQUE_RISK_SCORING_DETECTED" | "EVIDENCE_BACKED_ASSESSMENTS_MISSING" | "RISK_VISUALIZATION_SERVICE_MISSING" | "DASHBOARD_EVIDENCE_MISSING" | "RISK_REPORTS_MISSING" | "RISK_HEAT_MAPS_MISSING" | "RISK_EVIDENCE_MISSING" | "RISK_EVIDENCE_MUTABLE" | "RISK_LINEAGE_INCOMPLETE" | "MISSION_STATE_MUTATION_ATTEMPTED" | "DIGITAL_TWIN_MUTATION_ATTEMPTED" | "SIMULATION_OUTCOME_MUTATION_ATTEMPTED" | "OPERATOR_DECISION_OVERRIDE_ATTEMPTED" | "RISK_APIS_MISSING" | "RISK_ASSESSMENT_QUALIFICATION_FAILED";
export type RiskAssessmentScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | RiskAssessmentFailure;
export type RiskAssessmentInput = Readonly<{ scenario?: RiskAssessmentScenario; seed?: string; tenant_id?: string; assessment_id?: string }>;
export type TemporalAnalyticsContract = Readonly<{ contract_id: string; historical_trends: boolean; current_conditions: boolean; projected_conditions: boolean; immutable_inputs: boolean; complete_lineage: boolean; deterministic_inputs: boolean; authoritative_for_risk: boolean; integrity_hash: string }>;
export type RiskEvaluationEngine = Readonly<{ engine_id: string; continuous_evaluation: boolean; risk_calculation: boolean; risk_aggregation: boolean; confidence_evaluation: boolean; severity_determination: boolean; exposure_assessment: boolean; deterministic_evaluation: boolean; integrity_hash: string }>;
export type RiskRegistry = Readonly<{ registry_id: string; risk_records: boolean; severity: boolean; probability: boolean; impact: boolean; mitigation_status: boolean; lineage: boolean; evidence: boolean; governed_records: boolean; integrity_hash: string }>;
export type RiskTrendEngine = Readonly<{ trend_id: string; trend_detection: boolean; acceleration_detection: boolean; deceleration_detection: boolean; historical_comparisons: boolean; risk_progression: boolean; trend_reports: boolean; trend_evidence: boolean; integrity_hash: string }>;
export type RiskForecastEngine = Readonly<{ forecast_id: string; near_term_forecasting: boolean; long_term_forecasting: boolean; expected_degradation: boolean; recovery_likelihood: boolean; risk_projection: boolean; forecast_reports: boolean; prediction_evidence: boolean; integrity_hash: string }>;
export type RiskCorrelationEngine = Readonly<{ correlation_id: string; dependency_analysis: boolean; cascading_failures: boolean; compound_risks: boolean; cross_mission_impacts: boolean; portfolio_correlations: boolean; correlation_graph: boolean; dependency_evidence: boolean; integrity_hash: string }>;
export type RiskPrioritizationEngine = Readonly<{ prioritization_id: string; severity_weighting: boolean; probability_weighting: boolean; mission_criticality: boolean; temporal_urgency: boolean; portfolio_impact: boolean; confidence_weighting: boolean; prioritized_risk_list: boolean; governed_criteria: boolean; integrity_hash: string }>;
export type RiskExplainabilityEngine = Readonly<{ explainability_id: string; risk_justification: boolean; supporting_analytics: boolean; evidence_references: boolean; historical_comparisons: boolean; no_opaque_scoring: boolean; advisory_only: boolean; integrity_hash: string }>;
export type RiskVisualizationService = Readonly<{ visualization_id: string; risk_dashboard: boolean; heat_maps: boolean; trend_graphs: boolean; severity_distribution: boolean; forecast_timeline: boolean; dashboard_evidence: boolean; visualization_evidence: boolean; integrity_hash: string }>;
export type RiskReports = Readonly<{ report_id: string; current_risk: boolean; historical_trend: boolean; forecast: boolean; supporting_evidence: boolean; recommended_attention_areas: boolean; heat_maps_generated: boolean; portfolio_awareness: boolean; integrity_hash: string }>;
export type RiskEvidence = Readonly<{ evidence_id: string; evaluation_evidence: boolean; trend_evidence: boolean; forecast_evidence: boolean; correlation_evidence: boolean; priority_evidence: boolean; explainability_evidence: boolean; dashboard_evidence: boolean; visualization_evidence: boolean; immutable: boolean; traceable_to_temporal_analytics: boolean; complete_lineage: boolean; integrity_hash: string }>;
export type RiskApis = Readonly<{ api_id: string; assessment_api: boolean; registry_api: boolean; trend_api: boolean; forecast_api: boolean; correlation_api: boolean; prioritization_api: boolean; explainability_api: boolean; visualization_api: boolean; report_api: boolean; stable: boolean; integrity_hash: string }>;
export type RiskAssessmentReadiness = Readonly<{ readiness_id: string; decision: RiskAssessmentDecision; phase_ready: boolean; upstream_ready: boolean; temporal_ready: boolean; evaluation_ready: boolean; registry_ready: boolean; trends_ready: boolean; forecast_ready: boolean; correlation_ready: boolean; prioritization_ready: boolean; explainability_ready: boolean; visualization_ready: boolean; reports_ready: boolean; evidence_ready: boolean; apis_ready: boolean; deterministic: boolean; advisory_only: boolean; no_state_mutation: boolean; temporal_analytics_exclusive: boolean; qualification_ready: boolean; failures: readonly RiskAssessmentFailure[]; integrity_hash: string }>;
export type RiskAssessmentResult = Readonly<{ phase_version: "risk-assessment/mc-8"; phase_identifier: "RiskAssessment"; upstream_refs: readonly string[]; tenant_id: string; assessment_id: string; risk_score: number; severity: OperationalRiskSeverity; trend: OperationalRiskTrend; temporal: TemporalAnalyticsContract; evaluation: RiskEvaluationEngine; registry: RiskRegistry; trends: RiskTrendEngine; forecast: RiskForecastEngine; correlation: RiskCorrelationEngine; prioritization: RiskPrioritizationEngine; explainability: RiskExplainabilityEngine; visualization: RiskVisualizationService; reports: RiskReports; evidence: RiskEvidence; apis: RiskApis; readiness: RiskAssessmentReadiness; replay_hash: string; integrity_hash: string }>;
export type RiskAssessmentValidation = Readonly<{ valid: boolean; decision: RiskAssessmentDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; temporal_valid: boolean; evaluation_valid: boolean; registry_valid: boolean; trends_valid: boolean; forecast_valid: boolean; correlation_valid: boolean; prioritization_valid: boolean; explainability_valid: boolean; visualization_valid: boolean; reports_valid: boolean; evidence_valid: boolean; apis_valid: boolean; readiness_valid: boolean; failures: readonly RiskAssessmentFailure[]; integrity_hash: string }>;
export type RiskAssessmentBundle = Readonly<{ doctrine: Readonly<{ version: "risk-assessment/mc-8"; owns_continuous_risk_evaluation: true; owns_risk_registry: true; owns_risk_trends_and_forecasts: true; owns_risk_correlation_and_prioritization: true; owns_risk_explainability_and_visualization: true; consumes_temporal_analytics_contract: true; recommendations_are_advisory_only: true; state_mutation_prohibited: true; evidence_backed_risk_required: true; qualification_gate: "Risk Assessment Qualification Gate" }>; result: RiskAssessmentResult; validation: RiskAssessmentValidation }>;
