export type RuntimeOrchestratorDecision = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type RuntimeDisposition = "accepted" | "ready" | "executing" | "completed" | "completed with restrictions" | "paused" | "suspended" | "escalated" | "denied" | "failed" | "terminated" | "revoked" | "fail-closed";
export type RuntimeRestrictionOutcome = "ALLOW" | "ALLOW_WITH_RESTRICTIONS" | "PAUSE" | "SUSPEND" | "ESCALATE" | "DENY" | "TERMINATE" | "FAIL_CLOSED";
export type RuntimeState = "REQUESTED" | "VALIDATING" | "READY" | "STARTING" | "RUNNING" | "PAUSING" | "PAUSED" | "RECOVERING" | "SUSPENDING" | "SUSPENDED" | "COMPLETING" | "COMPLETED" | "FAILING" | "FAILED" | "TERMINATING" | "TERMINATED" | "REVOKED";
export type RuntimeOrchestratorFailure =
  | "W2_0_CAF_CONSTITUTION_INVALID" | "W2_1_AGENT_REGISTRY_INVALID" | "W2_2_LIFECYCLE_ENGINE_INVALID" | "W2_3_CAPABILITY_REGISTRY_INVALID" | "W2_4_SKILL_REGISTRY_INVALID" | "W2_5_AUTHORITY_VALIDATOR_INVALID" | "W2_6_POLICY_GATE_INVALID" | "W2_7_SAFETY_GATE_INVALID" | "W2_8_PLANNING_ENGINE_INVALID" | "W2_9_MEMORY_ENGINE_INVALID"
  | "RUNTIME_CONTROL_PLANE_MISSING" | "LIFECYCLE_TRANSITION_INVALID_ALLOWED" | "DUPLICATE_EXECUTION_ALLOWED" | "TENANT_NAMESPACE_ISOLATION_FAILED" | "OPERATOR_SUPREMACY_WEAKENED"
  | "CONTEXT_ASSEMBLY_MISSING" | "CONTEXT_ASSEMBLY_NON_DETERMINISTIC" | "UNAUTHORIZED_MEMORY_INCLUDED" | "CONTEXT_PROVENANCE_MISSING" | "STALE_DECISION_REUSED"
  | "REASONING_RUNTIME_ADAPTER_MISSING" | "PROVIDER_SPECIFIC_BEHAVIOR_LEAKED" | "UNAPPROVED_TOOL_ADDED" | "INVALID_OUTPUT_ACCEPTED"
  | "RUNTIME_RESTRICTION_ENGINE_MISSING" | "RESTRICTION_CONFLICT_UNRESOLVED" | "RESTRICTION_WEAKENED_WITHOUT_APPROVAL" | "BUDGET_ENFORCEMENT_MISSING"
  | "TASK_EXECUTION_MISSING" | "TASK_DEPENDENCY_BYPASSED" | "SIDE_EFFECT_NOT_IDEMPOTENT" | "TASK_RESULT_SCHEMA_INVALID"
  | "CHECKPOINT_SERVICE_MISSING" | "CHECKPOINT_NOT_IMMUTABLE" | "CHECKPOINT_INTEGRITY_INVALID" | "INCOMPATIBLE_CHECKPOINT_RESTORED"
  | "RECOVERY_CONTROLLER_MISSING" | "RECOVERY_REUSED_INVALID_DECISION" | "SIDE_EFFECT_DUPLICATED_DURING_RECOVERY" | "REVOKED_RUNTIME_REVIVED"
  | "RUNTIME_API_MISSING" | "RUNTIME_API_NOT_AUTHORIZED" | "RUNTIME_API_NOT_IDEMPOTENT" | "STRUCTURED_ERRORS_MISSING"
  | "RUNTIME_EVIDENCE_MISSING" | "RUNTIME_EVIDENCE_NOT_IMMUTABLE" | "RUNTIME_REPLAY_INVALID" | "RUNTIME_SECURITY_ASSESSMENT_FAILED" | "RUNTIME_RESILIENCE_FAILED" | "RUNTIME_PERFORMANCE_FAILED" | "RUNTIME_ORCHESTRATOR_QUALIFICATION_FAILED";
export type RuntimeOrchestratorScenario = "BASELINE" | "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | RuntimeOrchestratorFailure;
export type RuntimeOrchestratorInput = Readonly<{ scenario?: RuntimeOrchestratorScenario; seed?: string }>;
export type RuntimeControlPlane = Readonly<{ plane_id: string; instance_creation: boolean; lifecycle_coordination: boolean; execution_admission: boolean; pause_resume_suspend_terminate: boolean; runtime_ownership: boolean; lease_management: boolean; concurrency_control: boolean; execution_supervision: boolean; health_coordination: boolean; command_processor: boolean; evidence_emitter: boolean; idempotent_creation: boolean; lifecycle_validated_by_w22: boolean; operator_controls_enforced: boolean; integrity_hash: string }>;
export type RuntimeContextAssembly = Readonly<{ service_id: string; execution_subject: boolean; approved_plan_loaded: boolean; authorized_memory_retrieved: boolean; capability_skill_tool_resolution: boolean; configuration_loaded: boolean; authority_policy_safety_attached: boolean; operator_disposition_attached: boolean; data_minimization: boolean; canonical_context_package: boolean; context_provenance: boolean; deterministic_package: boolean; integrity_protected: boolean; tenant_namespace_boundary: boolean; integrity_hash: string }>;
export type ReasoningRuntimeAdapter = Readonly<{ adapter_id: string; provider_neutral_request: boolean; provider_neutral_response: boolean; adapter_registry: boolean; runtime_selection_rules: boolean; compatibility_validation: boolean; structured_tool_interface: boolean; timeout_handling: boolean; streaming_normalization: boolean; output_validation: boolean; metadata_capture: boolean; health_checks: boolean; fallback_rules: boolean; provider_isolation: boolean; tool_interception: boolean; integrity_hash: string }>;
export type RuntimeRestrictionEngine = Readonly<{ engine_id: string; source_adapters: boolean; normalization: boolean; composition: boolean; precedence_resolver: boolean; conflict_detector: boolean; effective_limits: boolean; dynamic_evaluation: boolean; budget_enforcement: boolean; tool_boundaries: boolean; data_boundaries: boolean; destination_boundaries: boolean; kill_conditions: boolean; outcomes: readonly RuntimeRestrictionOutcome[]; more_restrictive_only: boolean; replayable_history: boolean; integrity_hash: string }>;
export type TaskExecutionService = Readonly<{ service_id: string; task_admission: boolean; queue_integration: boolean; dependency_resolver: boolean; dispatcher: boolean; worker_interface: boolean; tool_gateway: boolean; result_validator: boolean; timeout_controller: boolean; retry_controller: boolean; idempotency_service: boolean; compensation_hook: boolean; completion_service: boolean; evidence_emitter: boolean; valid_runtime_state_required: boolean; side_effect_controls: boolean; integrity_hash: string }>;
export type CheckpointService = Readonly<{ service_id: string; scheduler: boolean; persistence: boolean; registry: boolean; integrity_service: boolean; compatibility_validator: boolean; retention_policy: boolean; encryption: boolean; lineage: boolean; restoration_interface: boolean; evidence: boolean; immutable: boolean; version_aware: boolean; deterministic_resume: boolean; integrity_hash: string }>;
export type RecoveryController = Readonly<{ controller_id: string; failure_classification: boolean; retry_decisions: boolean; checkpoint_restoration: boolean; compensating_actions: boolean; runtime_restart: boolean; plan_revalidation: boolean; escalation: boolean; terminal_failure_handling: boolean; side_effect_reconciliation: boolean; bounded_attempts: boolean; deterministic_recovery: boolean; revoked_runtime_blocked: boolean; integrity_hash: string }>;
export type RuntimeApis = Readonly<{ api_id: string; runtime_management: boolean; task_endpoints: boolean; context_endpoints: boolean; restriction_endpoints: boolean; checkpoint_recovery_endpoints: boolean; administrative_endpoints: boolean; authenticated: boolean; authorized: boolean; idempotent_commands: boolean; versioned: boolean; structured_errors: boolean; evidence_references: boolean; deterministic_disposition: boolean; integrity_hash: string }>;
export type RuntimeEvidence = Readonly<{ ledger_id: string; records: readonly string[]; runtime_creation: boolean; admission_decisions: boolean; lifecycle_transitions: boolean; context_assembly: boolean; memory_retrieval: boolean; restriction_calculation: boolean; reasoning_invocation: boolean; tool_invocation: boolean; task_execution: boolean; checkpoints: boolean; recovery_attempts: boolean; operator_interventions: boolean; emergency_stops: boolean; runtime_termination: boolean; lineage_query: boolean; immutable: boolean; replayable: boolean; integrity_hash: string }>;
export type RuntimeOrchestratorReadiness = Readonly<{ readiness_id: string; decision: RuntimeOrchestratorDecision; phase_ready: boolean; constitution_ready: boolean; agent_registry_ready: boolean; lifecycle_engine_ready: boolean; capability_registry_ready: boolean; skill_registry_ready: boolean; authority_validator_ready: boolean; policy_gate_ready: boolean; safety_gate_ready: boolean; planning_engine_ready: boolean; memory_engine_ready: boolean; control_plane_ready: boolean; context_ready: boolean; adapter_ready: boolean; restrictions_ready: boolean; task_execution_ready: boolean; checkpoints_ready: boolean; recovery_ready: boolean; apis_ready: boolean; evidence_ready: boolean; lifecycle_authority_preserved: boolean; governance_sequence_preserved: boolean; tenant_namespace_isolated: boolean; failures: readonly RuntimeOrchestratorFailure[]; integrity_hash: string }>;
export type RuntimeOrchestratorResult = Readonly<{ phase_version: "runtime-orchestrator/w2.10"; phase_identifier: "RuntimeOrchestrator"; caf_constitution_ref: "caf-constitutional-foundation/w2.0"; agent_registry_ref: "agent-registry/w2.1"; lifecycle_engine_ref: "lifecycle-engine/w2.2"; capability_registry_ref: "capability-registry/w2.3"; skill_registry_ref: "skill-registry/w2.4"; authority_validator_ref: "authority-validator/w2.5"; policy_gate_ref: "policy-gate/w2.6"; safety_gate_ref: "safety-gate/w2.7"; planning_engine_ref: "planning-engine/w2.8"; memory_engine_ref: "memory-engine/w2.9"; runtime_states: readonly RuntimeState[]; dispositions: readonly RuntimeDisposition[]; control_plane: RuntimeControlPlane; context_assembly: RuntimeContextAssembly; reasoning_adapter: ReasoningRuntimeAdapter; restrictions: RuntimeRestrictionEngine; task_execution: TaskExecutionService; checkpoints: CheckpointService; recovery: RecoveryController; apis: RuntimeApis; evidence: RuntimeEvidence; readiness: RuntimeOrchestratorReadiness; replay_hash: string; integrity_hash: string }>;
export type RuntimeOrchestratorValidation = Readonly<{ valid: boolean; decision: RuntimeOrchestratorDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; control_plane_valid: boolean; context_valid: boolean; adapter_valid: boolean; restrictions_valid: boolean; task_execution_valid: boolean; checkpoints_valid: boolean; recovery_valid: boolean; apis_valid: boolean; evidence_valid: boolean; readiness_valid: boolean; failures: readonly RuntimeOrchestratorFailure[]; integrity_hash: string }>;
export type RuntimeOrchestratorBundle = Readonly<{ doctrine: Readonly<{ version: "runtime-orchestrator/w2.10"; owns_runtime_control_plane: true; owns_context_assembly: true; owns_reasoning_runtime_adapter: true; owns_runtime_restrictions: true; owns_task_execution: true; owns_checkpointing: true; owns_recovery: true; owns_runtime_api: true; owns_runtime_evidence: true; does_not_grant_authority: true; does_not_override_policy: true; does_not_override_safety: true; qualification_gate: "Runtime Orchestrator Qualification Gate" }>; result: RuntimeOrchestratorResult; validation: RuntimeOrchestratorValidation }>;
