export type MonitoringClassification = "HEALTHY" | "WATCH" | "DEGRADED" | "CRITICAL";
export type MonitoringEventSeverity = "INFO" | "WATCH" | "DEGRADATION" | "CRITICAL";
export type TrustContinuousMonitoringDecision = "CONTINUOUS_MONITORING_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type TrustContinuousMonitoringFailure =
  | "STAGE_1_TRUST_FOUNDATION_INVALID" | "STAGE_2_CONSTITUTIONAL_GATE_INVALID" | "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" | "STAGE_4_INDEPENDENT_EVALUATION_INVALID" | "STAGE_5_TRUST_RESOLUTION_INVALID" | "STAGE_6_EXPLAINABILITY_INVALID" | "STAGE_7_HUMAN_OVERSIGHT_INVALID"
  | "MONITORING_ENGINE_MISSING" | "MONITORING_SCHEDULER_MISSING" | "MONITORING_REGISTRY_MISSING" | "MONITORING_EVIDENCE_MISSING" | "MONITORING_CADENCE_NONDETERMINISTIC" | "ACTIVE_TRUST_ENTITIES_NOT_MONITORED" | "MONITORING_REPLAY_MISSING"
  | "TRUST_HEALTH_ENGINE_MISSING" | "HEALTH_SCORE_MISSING" | "STABILITY_INDICATORS_MISSING" | "OPERATIONAL_METRICS_MISSING" | "CONSTITUTIONAL_HEALTH_VALIDATION_MISSING" | "HEALTH_TRENDS_MISSING" | "HEALTH_EVIDENCE_MISSING" | "HEALTH_CALCULATION_NONDETERMINISTIC"
  | "STANDING_MONITOR_MISSING" | "STANDING_CONSISTENCY_MISSING" | "STANDING_AGING_MISSING" | "STANDING_TRANSITION_OBSERVATION_MISSING" | "STANDING_HISTORY_MISSING" | "STANDING_EVIDENCE_MISSING"
  | "EVIDENCE_FRESHNESS_SERVICE_MISSING" | "EVIDENCE_AGE_VALIDATION_MISSING" | "EXPIRATION_MONITORING_MISSING" | "MISSING_EVIDENCE_DETECTION_MISSING" | "STALE_EVIDENCE_IDENTIFICATION_MISSING" | "FRESHNESS_REPORTING_MISSING"
  | "BEHAVIORAL_MONITORING_ENGINE_MISSING" | "EXPECTED_BEHAVIOR_VALIDATION_MISSING" | "BEHAVIORAL_ANOMALY_DETECTION_MISSING" | "BEHAVIORAL_TREND_MONITORING_MISSING" | "BEHAVIORAL_EVIDENCE_MISSING" | "BEHAVIORAL_REPORTING_MISSING"
  | "MONITORING_EVENT_SERVICE_MISSING" | "EVENT_CLASSIFICATION_MISSING" | "EVENT_LINEAGE_MISSING" | "EVENT_TIMESTAMPING_MISSING" | "IMMUTABLE_EVENT_RECORDING_MISSING" | "EVENT_REPLAY_MISSING"
  | "MONITORING_ATTEMPTED_STANDING_CHANGE" | "MONITORING_PERFORMED_TRUST_EVALUATION" | "MONITORING_RESOLVED_TRUST_DECISION" | "MONITORING_OVERRIDDEN_CONSTITUTIONAL_DECISION" | "MONITORING_APPLIED_RESTRICTIONS" | "MONITORING_MADE_RECOVERY_DECISION" | "HEALTH_METRIC_OVERRIDES_DECISION" | "BEHAVIORAL_MONITORING_DETERMINED_OUTCOME"
  | "MONITORING_EVIDENCE_MUTABLE" | "MONITORING_EVENT_NOT_TRACEABLE" | "MONITORING_REPLAY_DIVERGED" | "CONTINUOUS_MONITORING_QUALIFICATION_FAILED";
export type TrustContinuousMonitoringScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | TrustContinuousMonitoringFailure;
export type TrustContinuousMonitoringInput = Readonly<{ scenario?: TrustContinuousMonitoringScenario; seed?: string; tenant_id?: string; monitoring_id?: string }>;
export type TrustMonitoring = Readonly<{ monitoring_id: string; trust_monitoring_engine: boolean; monitoring_scheduler: boolean; monitoring_registry: boolean; active_trust_entities_monitored: boolean; lifecycle_activity_observed: boolean; monitoring_intervals_tracked: boolean; monitoring_evidence_collected: boolean; monitoring_state_published: boolean; deterministic_cadence: boolean; replay_verified: boolean; integrity_hash: string }>;
export type TrustHealth = Readonly<{ health_id: string; health_score: number; classification: MonitoringClassification; trust_health_engine: boolean; health_score_computation: boolean; stability_indicators: boolean; operational_health_metrics: boolean; constitutional_health_validation: boolean; health_trend_analysis: boolean; health_evidence_generation: boolean; deterministic_calculation: boolean; trends_reproducible: boolean; integrity_hash: string }>;
export type StandingMonitoring = Readonly<{ standing_id: string; standing_observation: boolean; standing_consistency_checks: boolean; standing_aging: boolean; standing_transition_observation: boolean; standing_history: boolean; standing_metrics: boolean; standing_evidence: boolean; transition_history_complete: boolean; evidence_replay_validated: boolean; standing_modified: false; integrity_hash: string }>;
export type EvidenceFreshnessMonitoring = Readonly<{ freshness_id: string; evidence_age_validation: boolean; expiration_monitoring: boolean; evidence_lifecycle_observation: boolean; missing_evidence_detection: boolean; stale_evidence_identification: boolean; freshness_reporting: boolean; evidence_freshness_verified: boolean; expiration_detected: boolean; replay_deterministic: boolean; integrity_hash: string }>;
export type BehavioralMonitoring = Readonly<{ behavior_id: string; behavioral_monitoring_engine: boolean; behavioral_observation: boolean; expected_behavior_validation: boolean; behavioral_anomaly_detection: boolean; trend_monitoring: boolean; behavioral_evidence: boolean; behavioral_reporting: boolean; independently_determines_trust_outcome: false; monitoring_reproducible: boolean; integrity_hash: string }>;
export type MonitoringEvents = Readonly<{ event_id: string; event_severities: readonly MonitoringEventSeverity[]; monitoring_event_service: boolean; event_generation: boolean; event_classification: boolean; event_lineage: boolean; event_timestamping: boolean; immutable_event_recording: boolean; event_registry: boolean; event_log: boolean; replay_support: boolean; traceable: boolean; integrity_hash: string }>;
export type MonitoringEvidence = Readonly<{ evidence_id: string; monitoring_evidence: boolean; health_evidence: boolean; behavioral_evidence: boolean; standing_evidence: boolean; freshness_evidence: boolean; event_evidence: boolean; immutable_storage: boolean; evidence_hashing: boolean; replayable: boolean; certification_ready: boolean; integrity_hash: string }>;
export type TrustContinuousMonitoringReadiness = Readonly<{ readiness_id: string; decision: TrustContinuousMonitoringDecision; phase_ready: boolean; upstream_ready: boolean; monitoring_ready: boolean; health_ready: boolean; standing_ready: boolean; freshness_ready: boolean; behavioral_ready: boolean; events_ready: boolean; evidence_ready: boolean; observational_only: boolean; no_standing_modification: boolean; no_decision_override: boolean; no_restriction_application: boolean; no_recovery_decision: boolean; deterministic: boolean; replayable: boolean; immutable_evidence: boolean; traceable_events: boolean; certification_ready: boolean; failures: readonly TrustContinuousMonitoringFailure[]; integrity_hash: string }>;
export type TrustContinuousMonitoringResult = Readonly<{ phase_version: "trust-continuous-monitoring-stage-eight/stage-8"; phase_identifier: "TrustContinuousMonitoringStageEight"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; monitoring_id: string; monitoring: TrustMonitoring; health: TrustHealth; standing: StandingMonitoring; freshness: EvidenceFreshnessMonitoring; behavior: BehavioralMonitoring; events: MonitoringEvents; evidence: MonitoringEvidence; readiness: TrustContinuousMonitoringReadiness; replay_hash: string; integrity_hash: string }>;
export type TrustContinuousMonitoringValidation = Readonly<{ valid: boolean; decision: TrustContinuousMonitoringDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; monitoring_valid: boolean; health_valid: boolean; standing_valid: boolean; freshness_valid: boolean; behavior_valid: boolean; events_valid: boolean; evidence_valid: boolean; readiness_valid: boolean; failures: readonly TrustContinuousMonitoringFailure[]; integrity_hash: string }>;
export type TrustContinuousMonitoringBundle = Readonly<{ doctrine: Readonly<{ version: "trust-continuous-monitoring-stage-eight/stage-8"; observational_only: true; never_changes_trust_standing: true; immutable_monitoring_evidence_required: true; deterministic_replay_required: true; health_never_overrides_constitutional_decisions: true; behavioral_monitoring_never_decides_outcomes: true; qualification_gate: "Stage 8 Continuous Monitoring Qualification Gate" }>; result: TrustContinuousMonitoringResult; validation: TrustContinuousMonitoringValidation }>;
