export type FederationRelationship = "TENANT" | "ORGANIZATION" | "ECOSYSTEM";
export type FederationExchange = "TRUST_ASSERTION" | "EVIDENCE_PACKAGE" | "CERTIFICATION_RECORD" | "REVOCATION_NOTICE" | "MONITORING_SIGNAL";
export type TrustFederationDecision = "TRUST_FEDERATION_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type TrustFederationFailure =
  | "STAGE_1_TRUST_FOUNDATION_INVALID" | "STAGE_2_CONSTITUTIONAL_GATE_INVALID" | "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" | "STAGE_4_INDEPENDENT_EVALUATION_INVALID" | "STAGE_5_TRUST_RESOLUTION_INVALID" | "STAGE_6_EXPLAINABILITY_INVALID" | "STAGE_7_HUMAN_OVERSIGHT_INVALID" | "STAGE_8_CONTINUOUS_MONITORING_INVALID" | "STAGE_9_DRIFT_DETECTION_INVALID" | "STAGE_10_RECOVERY_REVOCATION_INVALID" | "STAGE_11_TRUST_CERTIFICATION_INVALID"
  | "FEDERATION_CONTRACT_MODEL_MISSING" | "TRUST_EXCHANGE_CONTRACTS_MISSING" | "FEDERATION_PROTOCOLS_MISSING" | "TRUST_ASSERTION_CONTRACTS_MISSING" | "EVIDENCE_EXCHANGE_CONTRACTS_MISSING" | "CONTRACT_VERSIONING_MISSING" | "COMPATIBILITY_RULES_MISSING" | "CAPABILITY_NEGOTIATION_MISSING" | "CONTRACT_VALIDATION_MISSING" | "CONTRACT_GOVERNANCE_MISSING"
  | "REMOTE_TRUST_VERIFICATION_MISSING" | "TRUST_ASSERTION_VALIDATION_MISSING" | "IDENTITY_VERIFICATION_MISSING" | "EVIDENCE_VERIFICATION_MISSING" | "SIGNATURE_VALIDATION_MISSING" | "CERTIFICATE_VALIDATION_MISSING" | "STANDING_VERIFICATION_MISSING" | "RESTRICTION_VERIFICATION_MISSING" | "TRUST_FRESHNESS_VALIDATION_MISSING" | "VERIFICATION_REPLAY_MISSING"
  | "FEDERATION_EVIDENCE_CAPTURE_MISSING" | "TRUST_EXCHANGE_EVIDENCE_MISSING" | "VERIFICATION_EVIDENCE_MISSING" | "CONTRACT_EVIDENCE_MISSING" | "BOUNDARY_EVIDENCE_MISSING" | "FEDERATION_AUDIT_RECORDS_MISSING" | "REPLAY_EVIDENCE_MISSING" | "SIGNATURE_EVIDENCE_MISSING" | "EVIDENCE_PACKAGING_MISSING" | "EVIDENCE_LINEAGE_MISSING"
  | "FEDERATION_AUTHORIZATION_POLICIES_MISSING" | "ALLOWED_RELATIONSHIPS_MISSING" | "RESTRICTED_RELATIONSHIPS_MISSING" | "TRUST_IMPORT_POLICIES_MISSING" | "TRUST_EXPORT_POLICIES_MISSING" | "POLICY_VERSIONING_MISSING" | "FEDERATION_APPROVAL_RULES_MISSING" | "FEDERATION_REVOCATION_POLICIES_MISSING" | "FEDERATION_GOVERNANCE_RULES_MISSING" | "POLICY_VALIDATION_MISSING"
  | "TENANT_BOUNDARY_ENFORCEMENT_MISSING" | "DOMAIN_ISOLATION_MISSING" | "ORGANIZATIONAL_ISOLATION_MISSING" | "TRUST_BOUNDARY_VALIDATION_MISSING" | "UNAUTHORIZED_ACCESS_PREVENTION_MISSING" | "FEDERATION_RESTRICTIONS_MISSING" | "DATA_ISOLATION_MISSING" | "CROSS_BOUNDARY_VALIDATION_MISSING" | "FAIL_CLOSED_ENFORCEMENT_MISSING" | "BOUNDARY_AUDITING_MISSING"
  | "FEDERATION_HEALTH_MONITORING_MISSING" | "CONTRACT_MONITORING_MISSING" | "VERIFICATION_MONITORING_MISSING" | "FEDERATION_PERFORMANCE_MISSING" | "FEDERATION_ERRORS_MISSING" | "FEDERATION_DRIFT_DETECTION_MISSING" | "CONTRACT_EXPIRATION_MONITORING_MISSING" | "POLICY_COMPLIANCE_MONITORING_MISSING" | "FEDERATION_ALERTS_MISSING" | "FEDERATION_METRICS_MISSING"
  | "FEDERATION_BYPASSED_CONSTITUTIONAL_EVALUATION" | "REMOTE_ASSERTION_TREATED_AS_DECISION" | "TENANT_ISOLATION_COMPROMISED" | "UNAUTHORIZED_TRUST_PROPAGATION" | "TENANT_DATA_LEAKAGE" | "POLICY_BYPASS" | "AUTHORITY_INHERITANCE_ALLOWED" | "STANDING_INHERITANCE_ALLOWED" | "FEDERATION_EVIDENCE_MUTABLE" | "FEDERATION_REPLAY_DIVERGED" | "TRUST_FEDERATION_QUALIFICATION_FAILED";
export type TrustFederationScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | TrustFederationFailure;
export type TrustFederationInput = Readonly<{ scenario?: TrustFederationScenario; seed?: string; tenant_id?: string; federation_id?: string }>;
export type FederationContracts = Readonly<{ contract_id: string; federation_contract_model: boolean; trust_exchange_contracts: boolean; federation_protocol_definitions: boolean; trust_assertion_contracts: boolean; evidence_exchange_contracts: boolean; contract_versioning: boolean; compatibility_rules: boolean; capability_negotiation: boolean; contract_validation: boolean; contract_governance: boolean; integrity_hash: string }>;
export type CrossTenantVerification = Readonly<{ verification_id: string; remote_trust_verification: boolean; trust_assertion_validation: boolean; identity_verification: boolean; evidence_verification: boolean; signature_validation: boolean; certificate_validation: boolean; standing_verification: boolean; restriction_verification: boolean; trust_freshness_validation: boolean; replay_validation: boolean; remote_assertions_are_evidence_only: boolean; local_evaluation_required: boolean; integrity_hash: string }>;
export type FederationEvidence = Readonly<{ evidence_id: string; federation_evidence_capture: boolean; trust_exchange_evidence: boolean; verification_evidence: boolean; contract_evidence: boolean; boundary_evidence: boolean; federation_audit_records: boolean; replay_evidence: boolean; signature_evidence: boolean; evidence_packaging: boolean; evidence_lineage: boolean; immutable: boolean; integrity_hash: string }>;
export type FederationPolicies = Readonly<{ policy_id: string; federation_authorization_policies: boolean; allowed_relationships: boolean; restricted_relationships: boolean; trust_import_policies: boolean; trust_export_policies: boolean; policy_versioning: boolean; federation_approval_rules: boolean; federation_revocation_policies: boolean; federation_governance_rules: boolean; policy_validation: boolean; governs_every_exchange: boolean; integrity_hash: string }>;
export type BoundaryEnforcement = Readonly<{ boundary_id: string; tenant_boundary_enforcement: boolean; domain_isolation: boolean; organizational_isolation: boolean; trust_boundary_validation: boolean; unauthorized_access_prevention: boolean; federation_restrictions: boolean; data_isolation: boolean; cross_boundary_validation: boolean; fail_closed_enforcement: boolean; boundary_auditing: boolean; tenant_sovereignty_preserved: boolean; integrity_hash: string }>;
export type FederationMonitoring = Readonly<{ monitoring_id: string; federation_health_monitoring: boolean; contract_monitoring: boolean; verification_monitoring: boolean; federation_performance: boolean; federation_errors: boolean; trust_drift_detection: boolean; contract_expiration_monitoring: boolean; policy_compliance_monitoring: boolean; federation_alerts: boolean; federation_metrics: boolean; deterministic_alerts: boolean; integrity_hash: string }>;
export type FederationRegistry = Readonly<{ registry_id: string; federation_registry: boolean; federation_contract_registry: boolean; federation_policy_registry: boolean; verification_registry: boolean; federation_evidence_registry: boolean; relationship_types: readonly FederationRelationship[]; exchange_types: readonly FederationExchange[]; searchable: boolean; replayable: boolean; lineage_aware: boolean; integrity_hash: string }>;
export type TrustFederationReadiness = Readonly<{ readiness_id: string; decision: TrustFederationDecision; phase_ready: boolean; upstream_ready: boolean; contracts_ready: boolean; verification_ready: boolean; evidence_ready: boolean; policies_ready: boolean; boundary_ready: boolean; monitoring_ready: boolean; registry_ready: boolean; constitutional_supremacy: boolean; tenant_sovereignty: boolean; independent_evaluation: boolean; least_trust: boolean; boundary_preservation: boolean; deterministic_federation: boolean; immutable_evidence: boolean; fail_closed: boolean; certification_ready: boolean; failures: readonly TrustFederationFailure[]; integrity_hash: string }>;
export type TrustFederationResult = Readonly<{ phase_version: "trust-federation-stage-twelve/stage-12"; phase_identifier: "TrustFederationStageTwelve"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; federation_id: string; contracts: FederationContracts; verification: CrossTenantVerification; evidence: FederationEvidence; policies: FederationPolicies; boundary: BoundaryEnforcement; monitoring: FederationMonitoring; registry: FederationRegistry; readiness: TrustFederationReadiness; replay_hash: string; integrity_hash: string }>;
export type TrustFederationValidation = Readonly<{ valid: boolean; decision: TrustFederationDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; contracts_valid: boolean; verification_valid: boolean; evidence_valid: boolean; policies_valid: boolean; boundary_valid: boolean; monitoring_valid: boolean; registry_valid: boolean; readiness_valid: boolean; failures: readonly TrustFederationFailure[]; integrity_hash: string }>;
export type TrustFederationBundle = Readonly<{ doctrine: Readonly<{ version: "trust-federation-stage-twelve/stage-12"; constitutional_supremacy: true; tenant_sovereignty_required: true; remote_assertions_are_evidence_not_decisions: true; least_trust_required: true; tenant_isolation_required: true; deterministic_replay_required: true; qualification_gate: "Stage 12 Trust Federation Qualification Gate" }>; result: TrustFederationResult; validation: TrustFederationValidation }>;
