export type DriftSeverity = "NONE" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type DriftDomain = "BEHAVIORAL" | "CONFIDENCE" | "ALIGNMENT" | "RISK";
export type TrustDriftDetectionDecision = "DRIFT_DETECTION_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type TrustDriftDetectionFailure =
  | "STAGE_1_TRUST_FOUNDATION_INVALID" | "STAGE_2_CONSTITUTIONAL_GATE_INVALID" | "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" | "STAGE_4_INDEPENDENT_EVALUATION_INVALID" | "STAGE_5_TRUST_RESOLUTION_INVALID" | "STAGE_6_EXPLAINABILITY_INVALID" | "STAGE_7_HUMAN_OVERSIGHT_INVALID" | "STAGE_8_CONTINUOUS_MONITORING_INVALID"
  | "DRIFT_ENGINE_MISSING" | "DRIFT_PIPELINE_MISSING" | "OBSERVATION_LIFECYCLE_MISSING" | "DRIFT_EVIDENCE_PIPELINE_MISSING" | "DRIFT_EVENT_MODEL_MISSING" | "DRIFT_REGISTRY_INTEGRATION_MISSING" | "MONITORING_INTEGRATION_MISSING"
  | "BEHAVIORAL_BASELINES_MISSING" | "HISTORICAL_BEHAVIOR_PROFILES_MISSING" | "BEHAVIOR_COMPARISON_ENGINE_MISSING" | "BEHAVIOR_TREND_ANALYSIS_MISSING" | "PATTERN_DEVIATION_DETECTION_MISSING" | "BEHAVIOR_STABILITY_METRICS_MISSING"
  | "CONFIDENCE_BASELINES_MISSING" | "CONFIDENCE_TREND_ANALYSIS_MISSING" | "CONFIDENCE_VARIANCE_DETECTION_MISSING" | "EVIDENCE_QUALITY_MONITORING_MISSING" | "CONFIDENCE_STABILITY_METRICS_MISSING" | "CONFIDENCE_DEGRADATION_DETECTION_MISSING"
  | "GOAL_ALIGNMENT_DRIFT_MISSING" | "BEHAVIORAL_ALIGNMENT_DRIFT_MISSING" | "CONSTITUTIONAL_ALIGNMENT_DRIFT_MISSING" | "POLICY_ALIGNMENT_DRIFT_MISSING" | "ALIGNMENT_TREND_ANALYSIS_MISSING" | "ALIGNMENT_STABILITY_EVALUATION_MISSING"
  | "RISK_TREND_MONITORING_MISSING" | "OPERATIONAL_RISK_DRIFT_MISSING" | "BEHAVIORAL_RISK_DRIFT_MISSING" | "POLICY_RISK_DRIFT_MISSING" | "CONSTITUTIONAL_RISK_DRIFT_MISSING" | "RISK_ESCALATION_DETECTION_MISSING"
  | "THRESHOLD_REGISTRY_MISSING" | "CONSTITUTIONAL_THRESHOLD_POLICIES_MISSING" | "THRESHOLD_VERSIONING_MISSING" | "THRESHOLD_VALIDATION_MISSING" | "THRESHOLD_GOVERNANCE_MISSING" | "THRESHOLD_EVIDENCE_MISSING"
  | "ALERT_GENERATION_MISSING" | "ALERT_SEVERITY_CLASSIFICATION_MISSING" | "ALERT_PRIORITIZATION_MISSING" | "ALERT_ROUTING_MISSING" | "ALERT_MONITORING_INTEGRATION_MISSING" | "ALERT_EVIDENCE_MISSING"
  | "OBSERVATION_EVIDENCE_MISSING" | "BASELINE_REFERENCES_MISSING" | "HISTORICAL_COMPARISONS_MISSING" | "DRIFT_EVALUATION_RECORDS_MISSING" | "IMMUTABLE_DRIFT_EVIDENCE_MISSING"
  | "DRIFT_NARRATIVES_MISSING" | "BASELINE_COMPARISONS_MISSING" | "THRESHOLD_JUSTIFICATION_MISSING" | "TREND_VISUALIZATION_CONTRACTS_MISSING" | "EVIDENCE_MAPPING_MISSING" | "HISTORICAL_TRACEABILITY_MISSING"
  | "DRIFT_REPLAY_ENGINE_MISSING" | "HISTORICAL_RECONSTRUCTION_MISSING" | "BASELINE_REPLAY_MISSING" | "THRESHOLD_REPLAY_MISSING" | "EVENT_REPLAY_MISSING" | "REPLAY_VALIDATION_MISSING"
  | "DRIFT_MODIFIED_TRUST_DECISION" | "DRIFT_CHANGED_TRUST_STANDING" | "DRIFT_APPLIED_RESTRICTION" | "DRIFT_TRIGGERED_RECOVERY_DIRECTLY" | "DRIFT_THRESHOLD_NOT_GOVERNED" | "DRIFT_ALERT_WITHOUT_EVIDENCE" | "DRIFT_EVIDENCE_MUTABLE" | "DRIFT_REPLAY_DIVERGED" | "DRIFT_DETECTION_QUALIFICATION_FAILED";
export type TrustDriftDetectionScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | TrustDriftDetectionFailure;
export type TrustDriftDetectionInput = Readonly<{ scenario?: TrustDriftDetectionScenario; seed?: string; tenant_id?: string; drift_id?: string }>;
export type DriftArchitecture = Readonly<{ architecture_id: string; drift_detection_engine: boolean; drift_evaluation_pipeline: boolean; drift_observation_lifecycle: boolean; drift_evidence_pipeline: boolean; drift_event_model: boolean; drift_registry_integration: boolean; trust_monitoring_integration: boolean; service_contracts: boolean; event_contracts: boolean; advisory_only: boolean; integrity_hash: string }>;
export type BehavioralDrift = Readonly<{ behavioral_id: string; behavioral_baselines: boolean; historical_behavior_profiles: boolean; behavioral_comparison_engine: boolean; behavioral_trend_analysis: boolean; pattern_deviation_detection: boolean; behavioral_stability_metrics: boolean; behavioral_drift_results: boolean; behavioral_trend_evidence: boolean; severity: DriftSeverity; integrity_hash: string }>;
export type ConfidenceDrift = Readonly<{ confidence_id: string; confidence_baselines: boolean; confidence_trend_analysis: boolean; confidence_variance_detection: boolean; evidence_quality_monitoring: boolean; confidence_stability_metrics: boolean; confidence_degradation_detection: boolean; confidence_drift_reports: boolean; confidence_drift_evidence: boolean; severity: DriftSeverity; integrity_hash: string }>;
export type AlignmentDrift = Readonly<{ alignment_id: string; goal_alignment_drift: boolean; behavioral_alignment_drift: boolean; constitutional_alignment_drift: boolean; policy_alignment_drift: boolean; alignment_trend_analysis: boolean; alignment_stability_evaluation: boolean; alignment_drift_reports: boolean; alignment_drift_evidence: boolean; severity: DriftSeverity; integrity_hash: string }>;
export type RiskDrift = Readonly<{ risk_id: string; risk_trend_monitoring: boolean; operational_risk_drift: boolean; behavioral_risk_drift: boolean; policy_risk_drift: boolean; constitutional_risk_drift: boolean; risk_escalation_detection: boolean; risk_drift_reports: boolean; risk_drift_evidence: boolean; severity: DriftSeverity; integrity_hash: string }>;
export type DriftThresholds = Readonly<{ threshold_id: string; drift_threshold_registry: boolean; constitutional_threshold_policies: boolean; threshold_versioning: boolean; threshold_validation: boolean; threshold_governance: boolean; threshold_evidence: boolean; deterministic_criteria: boolean; governed_thresholds: boolean; integrity_hash: string }>;
export type DriftAlerts = Readonly<{ alert_id: string; alert_generation: boolean; alert_severity_classification: boolean; alert_prioritization: boolean; alert_routing: boolean; monitoring_integration: boolean; alert_evidence: boolean; alert_records: boolean; alert_registry: boolean; evidence_backed: boolean; deterministic_generation: boolean; integrity_hash: string }>;
export type DriftEvidence = Readonly<{ evidence_id: string; observation_evidence: boolean; baseline_references: boolean; historical_comparisons: boolean; threshold_evidence: boolean; drift_evaluation_records: boolean; immutable_evidence_storage: boolean; evidence_packages: boolean; evidence_lineage_complete: boolean; replayable: boolean; integrity_hash: string }>;
export type DriftExplainability = Readonly<{ explainability_id: string; drift_narratives: boolean; baseline_comparisons: boolean; threshold_justification: boolean; trend_visualization_contracts: boolean; evidence_mapping: boolean; historical_traceability: boolean; explanation_packages: boolean; every_drift_explained: boolean; integrity_hash: string }>;
export type DriftReplay = Readonly<{ replay_id: string; drift_replay_engine: boolean; historical_reconstruction: boolean; baseline_replay: boolean; threshold_replay: boolean; event_replay: boolean; replay_validation: boolean; replay_reports: boolean; identical_results: boolean; integrity_hash: string }>;
export type TrustDriftDetectionReadiness = Readonly<{ readiness_id: string; decision: TrustDriftDetectionDecision; phase_ready: boolean; upstream_ready: boolean; architecture_ready: boolean; behavioral_ready: boolean; confidence_ready: boolean; alignment_ready: boolean; risk_ready: boolean; thresholds_ready: boolean; alerts_ready: boolean; evidence_ready: boolean; explainability_ready: boolean; replay_ready: boolean; advisory_only: boolean; no_direct_decision_change: boolean; no_direct_standing_change: boolean; no_direct_restriction: boolean; no_direct_recovery: boolean; deterministic: boolean; immutable_evidence: boolean; complete_lineage: boolean; certification_ready: boolean; failures: readonly TrustDriftDetectionFailure[]; integrity_hash: string }>;
export type TrustDriftDetectionResult = Readonly<{ phase_version: "trust-drift-detection-stage-nine/stage-9"; phase_identifier: "TrustDriftDetectionStageNine"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; drift_id: string; domains: readonly DriftDomain[]; architecture: DriftArchitecture; behavioral: BehavioralDrift; confidence: ConfidenceDrift; alignment: AlignmentDrift; risk: RiskDrift; thresholds: DriftThresholds; alerts: DriftAlerts; evidence: DriftEvidence; explainability: DriftExplainability; replay: DriftReplay; readiness: TrustDriftDetectionReadiness; replay_hash: string; integrity_hash: string }>;
export type TrustDriftDetectionValidation = Readonly<{ valid: boolean; decision: TrustDriftDetectionDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; architecture_valid: boolean; behavioral_valid: boolean; confidence_valid: boolean; alignment_valid: boolean; risk_valid: boolean; thresholds_valid: boolean; alerts_valid: boolean; evidence_valid: boolean; explainability_valid: boolean; replay_valid: boolean; readiness_valid: boolean; failures: readonly TrustDriftDetectionFailure[]; integrity_hash: string }>;
export type TrustDriftDetectionBundle = Readonly<{ doctrine: Readonly<{ version: "trust-drift-detection-stage-nine/stage-9"; advisory_only: true; never_changes_trust_decisions: true; immutable_drift_evidence_required: true; deterministic_replay_required: true; governed_thresholds_required: true; every_alert_evidence_backed: true; qualification_gate: "Stage 9 Drift Detection Qualification Gate" }>; result: TrustDriftDetectionResult; validation: TrustDriftDetectionValidation }>;
