export type TrustRegistryDomainsDecision = "TRUST_REGISTRY_DOMAINS_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type TrustEntityType = "EVALUATION" | "POLICY" | "CERTIFICATION" | "EVIDENCE" | "MONITORING" | "FEDERATION" | "DOMAIN" | "IDENTITY";
export type TrustStanding = "ACTIVE" | "PENDING" | "SUSPENDED" | "REVOKED" | "ARCHIVED";
export type TrustRelationshipKind = "PARENT" | "CHILD" | "DEPENDENCY" | "DELEGATION" | "AUTHORITY" | "CERTIFICATION" | "FEDERATION";
export type TrustRegistryDomainsFailure =
  | "STAGE_1_TRUST_FOUNDATION_INVALID" | "STAGE_2_CONSTITUTIONAL_GATE_INVALID" | "CAF_IDENTITY_SERVICES_INVALID" | "CCI_IDENTITY_INFRASTRUCTURE_INVALID" | "CCI_REGISTRY_SERVICES_INVALID" | "CCI_EVIDENCE_FRAMEWORK_INVALID" | "CCI_REPLAY_FRAMEWORK_INVALID"
  | "TRUST_REGISTRY_MISSING" | "TRUST_IDENTITY_RECORDS_MISSING" | "IMMUTABLE_TRUST_IDS_MISSING" | "REGISTRY_VERSIONING_MISSING" | "REGISTRY_LIFECYCLE_MISSING" | "TRUST_DISCOVERY_MISSING" | "REGISTRY_QUERIES_MISSING" | "REGISTRY_VALIDATION_MISSING"
  | "DOMAIN_REGISTRY_MISSING" | "DOMAIN_IDENTITY_MISSING" | "DOMAIN_OWNERSHIP_MISSING" | "DOMAIN_HIERARCHY_MISSING" | "DOMAIN_MEMBERSHIP_MISSING" | "DOMAIN_CLASSIFICATION_MISSING" | "DOMAIN_LIFECYCLE_MISSING"
  | "RELATIONSHIP_ENGINE_MISSING" | "RELATIONSHIPS_NOT_VERSIONED" | "RELATIONSHIPS_NOT_REPLAYABLE" | "RELATIONSHIP_GRAPH_INVALID" | "AUTHORITY_RELATIONSHIPS_INVALID"
  | "DOMAIN_BOUNDARY_MANAGER_MISSING" | "BOUNDARY_DEFINITIONS_MISSING" | "BOUNDARY_VALIDATION_MISSING" | "DOMAIN_ISOLATION_INVALID" | "CROSS_DOMAIN_ACCESS_ALLOWED" | "BOUNDARY_ENFORCEMENT_NOT_FAIL_CLOSED"
  | "DOMAIN_POLICY_SERVICE_MISSING" | "DOMAIN_POLICIES_MISSING" | "POLICY_INHERITANCE_NON_DETERMINISTIC" | "ADMISSION_POLICIES_MISSING" | "CERTIFICATION_POLICIES_MISSING"
  | "METADATA_SERVICE_MISSING" | "METADATA_REGISTRY_MISSING" | "METADATA_HISTORY_MUTABLE" | "PROVENANCE_MISSING" | "MODIFICATION_HISTORY_MISSING"
  | "DOMAIN_GOVERNANCE_MISSING" | "DOMAIN_AUTHORITY_INVALID" | "OWNERSHIP_NOT_ENFORCED" | "GOVERNANCE_APPROVAL_WORKFLOW_MISSING" | "GOVERNANCE_AUDIT_MISSING"
  | "REGISTRY_EVIDENCE_MISSING" | "EVIDENCE_NOT_SIGNED" | "EVIDENCE_NOT_REPLAYABLE" | "REGISTRY_REPLAY_NON_DETERMINISTIC" | "REGISTRY_STATE_NOT_RECONSTRUCTABLE" | "TRUST_REGISTRY_DOMAINS_QUALIFICATION_FAILED";
export type TrustRegistryDomainsScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | TrustRegistryDomainsFailure;
export type TrustRegistryDomainsInput = Readonly<{ scenario?: TrustRegistryDomainsScenario; seed?: string; tenant_id?: string; registry_id?: string }>;
export type TrustRegistry = Readonly<{ registry_id: string; identity_records: boolean; immutable_trust_ids: boolean; registry_versioning: boolean; registry_lifecycle: boolean; trust_discovery: boolean; registry_queries: boolean; registry_validation: boolean; registry_evidence: boolean; entity_types: readonly TrustEntityType[]; standings: readonly TrustStanding[]; integrity_hash: string }>;
export type TrustDomainRegistry = Readonly<{ domain_registry_id: string; domain_identity: boolean; domain_ownership: boolean; domain_hierarchy: boolean; domain_membership: boolean; domain_classification: boolean; domain_lifecycle: boolean; domain_discovery: boolean; independently_governed_boundaries: boolean; immutable_domain_records: boolean; integrity_hash: string }>;
export type TrustRelationshipEngine = Readonly<{ graph_id: string; relationship_kinds: readonly TrustRelationshipKind[]; parent_relationships: boolean; child_relationships: boolean; dependency_relationships: boolean; delegation_relationships: boolean; authority_relationships: boolean; certification_relationships: boolean; federation_relationships: boolean; immutable: boolean; versioned: boolean; replayable: boolean; integrity_hash: string }>;
export type DomainBoundaryManager = Readonly<{ boundary_id: string; boundary_definitions: boolean; boundary_validation: boolean; isolation_rules: boolean; cross_domain_validation: boolean; boundary_evidence: boolean; boundary_enforcement: boolean; fail_closed: boolean; explicit_constitutional_authorization_required: boolean; tenant_isolation: boolean; integrity_hash: string }>;
export type DomainPolicyService = Readonly<{ policy_id: string; domain_policies: boolean; domain_restrictions: boolean; admission_policies: boolean; evaluation_policies: boolean; monitoring_policies: boolean; certification_policies: boolean; recovery_policies: boolean; deterministic_inheritance: boolean; traceable_inheritance: boolean; integrity_hash: string }>;
export type TrustMetadataService = Readonly<{ metadata_id: string; metadata_registry: boolean; tags: boolean; labels: boolean; classification: boolean; attributes: boolean; provenance: boolean; creation_history: boolean; modification_history: boolean; immutable_version_history: boolean; integrity_hash: string }>;
export type DomainGovernanceService = Readonly<{ governance_id: string; domain_owners: boolean; domain_administrators: boolean; governance_rules: boolean; domain_authority: boolean; approval_workflow: boolean; governance_audit: boolean; governance_evidence: boolean; ownership_enforced: boolean; authority_verified: boolean; integrity_hash: string }>;
export type RegistryEvidenceLedger = Readonly<{ evidence_id: string; trust_registration: boolean; domain_registration: boolean; identity_creation: boolean; relationship_creation: boolean; boundary_validation: boolean; policy_assignment: boolean; governance_decisions: boolean; metadata_updates: boolean; lifecycle_changes: boolean; signed: boolean; timestamped: boolean; replayable: boolean; integrity_hash: string }>;
export type TrustRegistryDomainsReadiness = Readonly<{ readiness_id: string; decision: TrustRegistryDomainsDecision; phase_ready: boolean; upstream_ready: boolean; registry_ready: boolean; domains_ready: boolean; relationships_ready: boolean; boundaries_ready: boolean; policies_ready: boolean; metadata_ready: boolean; governance_ready: boolean; evidence_ready: boolean; replay_ready: boolean; immutable_identities: boolean; domain_isolation_enforced: boolean; cross_domain_fail_closed: boolean; ownership_governed: boolean; registry_state_reconstructable: boolean; qualification_ready: boolean; failures: readonly TrustRegistryDomainsFailure[]; integrity_hash: string }>;
export type TrustRegistryDomainsResult = Readonly<{ phase_version: "trust-registry-domains/stage-3"; phase_identifier: "TrustRegistryDomains"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; registry_id: string; registry: TrustRegistry; domains: TrustDomainRegistry; relationships: TrustRelationshipEngine; boundaries: DomainBoundaryManager; policies: DomainPolicyService; metadata: TrustMetadataService; governance: DomainGovernanceService; evidence: RegistryEvidenceLedger; readiness: TrustRegistryDomainsReadiness; replay_hash: string; integrity_hash: string }>;
export type TrustRegistryDomainsValidation = Readonly<{ valid: boolean; decision: TrustRegistryDomainsDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; registry_valid: boolean; domains_valid: boolean; relationships_valid: boolean; boundaries_valid: boolean; policies_valid: boolean; metadata_valid: boolean; governance_valid: boolean; evidence_valid: boolean; readiness_valid: boolean; failures: readonly TrustRegistryDomainsFailure[]; integrity_hash: string }>;
export type TrustRegistryDomainsBundle = Readonly<{ doctrine: Readonly<{ version: "trust-registry-domains/stage-3"; authoritative_trust_registry: true; canonical_domain_model: true; immutable_identities_required: true; domain_isolation_required: true; cross_domain_access_fail_closed: true; replay_reconstructable_registry: true; qualification_gate: "Stage 3 Trust Registry & Domains Qualification Gate" }>; result: TrustRegistryDomainsResult; validation: TrustRegistryDomainsValidation }>;
