export type TrustExplainabilityDecision = "TRUST_EXPLAINABILITY_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type ExplanationPackageSection = "REQUEST" | "DECISION" | "NARRATIVE" | "EVIDENCE_MAP" | "RULE_TRACE" | "CONSTITUTIONAL_JUSTIFICATION" | "CONFIDENCE_SUMMARY" | "RISK_SUMMARY" | "ALIGNMENT_SUMMARY" | "RESTRICTIONS" | "ESCALATIONS" | "FINAL_RESOLUTION";
export type TrustExplainabilityFailure =
  | "STAGE_1_TRUST_FOUNDATION_INVALID" | "STAGE_2_CONSTITUTIONAL_GATE_INVALID" | "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" | "STAGE_4_INDEPENDENT_EVALUATION_INVALID" | "STAGE_5_TRUST_RESOLUTION_INVALID"
  | "EXPLAINABILITY_SERVICE_MISSING" | "EXPLANATION_PIPELINE_MISSING" | "EXPLANATION_MODEL_MISSING" | "EXPLANATION_LIFECYCLE_MISSING" | "EXPLANATION_APIS_MISSING" | "REPLAY_INTEGRATION_MISSING" | "EVIDENCE_INTEGRATION_MISSING" | "CONSTITUTIONAL_INTEGRATION_MISSING"
  | "DECISION_NARRATIVE_MISSING" | "NARRATIVE_TIMELINE_MISSING" | "NARRATIVE_TEMPLATES_MISSING" | "NARRATIVE_NOT_DETERMINISTIC" | "NARRATIVE_REPLAY_FAILED"
  | "EVIDENCE_MAPPING_MISSING" | "EVIDENCE_REFERENCES_MISSING" | "EVIDENCE_LINEAGE_MISSING" | "EVIDENCE_PROVENANCE_MISSING" | "MISSING_EVIDENCE_NOT_IDENTIFIED" | "MUTABLE_EVIDENCE_REFERENCED"
  | "RULE_TRACE_MISSING" | "CONSTITUTIONAL_RULE_TRACE_MISSING" | "POLICY_RULE_TRACE_MISSING" | "RESTRICTION_RULE_TRACE_MISSING" | "RESOLUTION_RULE_TRACE_MISSING" | "RULE_ORDERING_NOT_DETERMINISTIC" | "RULE_REPLAY_FAILED"
  | "CONSTITUTIONAL_JUSTIFICATION_MISSING" | "CONSTITUTIONAL_REFERENCES_INVALID" | "AUTHORITY_MAPPING_MISSING" | "CONSTITUTIONAL_DECISION_CHAIN_MISSING"
  | "RESTRICTION_EXPLANATIONS_MISSING" | "RESTRICTION_AUTHORITY_MISSING" | "RESTRICTION_REMOVAL_CONDITIONS_MISSING"
  | "ESCALATION_EXPLANATIONS_MISSING" | "HUMAN_REVIEW_PACKAGE_MISSING" | "ESCALATION_CONTEXT_INCOMPLETE"
  | "EXPLANATION_PACKAGE_MISSING" | "PACKAGE_NOT_DETERMINISTIC" | "PACKAGE_NOT_REPLAYABLE" | "PACKAGE_IMMUTABILITY_MISSING"
  | "API_ACCESS_CONTROL_INVALID" | "TENANT_ISOLATION_INVALID" | "GOVERNANCE_BYPASS_ATTEMPTED" | "UNEXPLAINED_TRUST_DECISION_PRODUCED" | "TRUST_EXPLAINABILITY_QUALIFICATION_FAILED";
export type TrustExplainabilityScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | TrustExplainabilityFailure;
export type TrustExplainabilityInput = Readonly<{ scenario?: TrustExplainabilityScenario; seed?: string; tenant_id?: string; explanation_id?: string }>;
export type ExplainabilityArchitecture = Readonly<{ service_id: string; explainability_service: boolean; explanation_pipeline: boolean; explanation_model: boolean; explanation_lifecycle: boolean; explanation_apis: boolean; replay_integration: boolean; evidence_integration: boolean; constitutional_integration: boolean; service_boundaries: boolean; integrity_hash: string }>;
export type DecisionNarrative = Readonly<{ narrative_id: string; request: boolean; context: boolean; evidence: boolean; evaluation: boolean; resolution: boolean; restrictions: boolean; escalations: boolean; final_decision: boolean; decision_timeline: boolean; decision_summary: boolean; deterministic_wording: boolean; structured_narrative: boolean; replay_verified: boolean; integrity_hash: string }>;
export type EvidenceMap = Readonly<{ evidence_map_id: string; evidence_consumed: boolean; evidence_ignored: boolean; evidence_rejected: boolean; evidence_confidence: boolean; evidence_source: boolean; evidence_relationships: boolean; evidence_lineage: boolean; provenance: boolean; prioritization: boolean; supporting_evidence: boolean; contradictory_evidence: boolean; missing_evidence_identification: boolean; immutable_references: boolean; integrity_hash: string }>;
export type RuleTrace = Readonly<{ trace_id: string; constitutional_rule_trace: boolean; trust_rule_trace: boolean; policy_rule_trace: boolean; restriction_rule_trace: boolean; resolution_rule_trace: boolean; rule_ordering: boolean; rule_dependencies: boolean; rule_outcomes: boolean; reasons: boolean; supporting_evidence: boolean; rule_precedence: boolean; final_impact: boolean; replay_verified: boolean; integrity_hash: string }>;
export type ConstitutionalJustification = Readonly<{ justification_id: string; constitutional_references: boolean; constitutional_articles: boolean; constitutional_principles: boolean; constitutional_violations: boolean; constitutional_exceptions: boolean; authority_mapping: boolean; decision_chain: boolean; applicable_doctrine: boolean; governing_authority: boolean; constitutional_rationale: boolean; constitutional_evidence: boolean; constitutional_outcome: boolean; integrity_hash: string }>;
export type RestrictionExplanation = Readonly<{ restriction_id: string; restriction_reasoning: boolean; restriction_evidence: boolean; restriction_policies: boolean; restriction_duration: boolean; restriction_scope: boolean; restriction_authority: boolean; restriction_alternatives: boolean; removal_conditions: boolean; constitutional_basis: boolean; policy_basis: boolean; integrity_hash: string }>;
export type EscalationExplanation = Readonly<{ escalation_id: string; escalation_reasoning: boolean; escalation_evidence: boolean; trigger_mapping: boolean; human_oversight_requirements: boolean; outstanding_questions: boolean; reviewer_information: boolean; escalation_packages: boolean; automation_stop_reason: boolean; missing_evidence: boolean; conflicting_evidence: boolean; constitutional_ambiguity: boolean; policy_conflict: boolean; trust_uncertainty: boolean; risk_concerns: boolean; integrity_hash: string }>;
export type ExplanationPackage = Readonly<{ package_id: string; sections: readonly ExplanationPackageSection[]; composer: boolean; narrative_assembly: boolean; evidence_bundle: boolean; rule_bundle: boolean; constitutional_bundle: boolean; restriction_bundle: boolean; escalation_bundle: boolean; decision_summary: boolean; deterministic: boolean; replayable: boolean; immutable: boolean; exportable: boolean; integrity_hash: string }>;
export type ExplainabilityApis = Readonly<{ api_id: string; explanation_query_api: boolean; explanation_retrieval_api: boolean; narrative_api: boolean; evidence_api: boolean; rule_trace_api: boolean; constitutional_api: boolean; restriction_api: boolean; replay_api: boolean; access_control: boolean; tenant_isolation: boolean; governance_enforced: boolean; integrity_hash: string }>;
export type TrustExplainabilityReadiness = Readonly<{ readiness_id: string; decision: TrustExplainabilityDecision; phase_ready: boolean; upstream_ready: boolean; architecture_ready: boolean; narrative_ready: boolean; evidence_map_ready: boolean; rule_trace_ready: boolean; constitutional_ready: boolean; restrictions_ready: boolean; escalations_ready: boolean; package_ready: boolean; apis_ready: boolean; every_decision_explained: boolean; deterministic: boolean; replayable: boolean; immutable_package: boolean; evidence_backed_only: boolean; tenant_isolated: boolean; no_unexplained_decisions: boolean; qualification_ready: boolean; failures: readonly TrustExplainabilityFailure[]; integrity_hash: string }>;
export type TrustExplainabilityResult = Readonly<{ phase_version: "trust-explainability-stage-six/stage-6"; phase_identifier: "TrustExplainabilityStageSix"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; explanation_id: string; architecture: ExplainabilityArchitecture; narrative: DecisionNarrative; evidence_map: EvidenceMap; rule_trace: RuleTrace; constitutional: ConstitutionalJustification; restrictions: RestrictionExplanation; escalations: EscalationExplanation; package: ExplanationPackage; apis: ExplainabilityApis; readiness: TrustExplainabilityReadiness; replay_hash: string; integrity_hash: string }>;
export type TrustExplainabilityValidation = Readonly<{ valid: boolean; decision: TrustExplainabilityDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; architecture_valid: boolean; narrative_valid: boolean; evidence_map_valid: boolean; rule_trace_valid: boolean; constitutional_valid: boolean; restrictions_valid: boolean; escalations_valid: boolean; package_valid: boolean; apis_valid: boolean; readiness_valid: boolean; failures: readonly TrustExplainabilityFailure[]; integrity_hash: string }>;
export type TrustExplainabilityBundle = Readonly<{ doctrine: Readonly<{ version: "trust-explainability-stage-six/stage-6"; constitutional_requirement: true; not_ui_feature: true; immutable_evidence_only: true; deterministic_explanations_required: true; every_decision_explained: true; replay_required: true; qualification_gate: "Stage 6 Explainability Qualification Gate" }>; result: TrustExplainabilityResult; validation: TrustExplainabilityValidation }>;
