export type ProgramQualificationDecision = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type QualificationFindingSeverity = "NONE" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type ProgramQualificationArea = "CONSTITUTIONAL_COMPLIANCE" | "TRUST_DETERMINISM" | "RESOLUTION" | "EXPLAINABILITY" | "HUMAN_OVERSIGHT" | "CONTINUOUS_MONITORING" | "DRIFT_DETECTION" | "RECOVERY" | "CERTIFICATION" | "FEDERATION" | "REPLAY" | "EVIDENCE_INTEGRITY" | "IMMUTABLE_LINEAGE" | "TENANT_ISOLATION" | "CONSTITUTIONAL_INVARIANTS";
export type TrustProgramQualificationFailure =
  | "STAGE_1_TRUST_FOUNDATION_INVALID" | "STAGE_2_CONSTITUTIONAL_GATE_INVALID" | "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" | "STAGE_4_INDEPENDENT_EVALUATION_INVALID" | "STAGE_5_TRUST_RESOLUTION_INVALID" | "STAGE_6_EXPLAINABILITY_INVALID" | "STAGE_7_HUMAN_OVERSIGHT_INVALID" | "STAGE_8_CONTINUOUS_MONITORING_INVALID" | "STAGE_9_DRIFT_DETECTION_INVALID" | "STAGE_10_RECOVERY_REVOCATION_INVALID" | "STAGE_11_TRUST_CERTIFICATION_INVALID" | "STAGE_12_TRUST_FEDERATION_INVALID"
  | "CONSTITUTIONAL_COMPLIANCE_UNVERIFIED" | "TRUST_DETERMINISM_UNVERIFIED" | "RESOLUTION_CORRECTNESS_UNVERIFIED" | "EXPLAINABILITY_INCOMPLETE" | "HUMAN_OVERSIGHT_UNQUALIFIED" | "CONTINUOUS_MONITORING_UNQUALIFIED" | "DRIFT_DETECTION_UNQUALIFIED" | "RECOVERY_REVOCATION_UNQUALIFIED" | "TRUST_CERTIFICATION_UNQUALIFIED" | "TRUST_FEDERATION_UNQUALIFIED" | "REPLAY_QUALIFICATION_UNVERIFIED" | "EVIDENCE_INTEGRITY_UNVERIFIED" | "IMMUTABLE_LINEAGE_UNVERIFIED" | "TENANT_ISOLATION_UNVERIFIED" | "CONSTITUTIONAL_INVARIANTS_UNVERIFIED"
  | "PROGRAM_QUALIFICATION_REPORT_MISSING" | "QUALIFICATION_EVIDENCE_LEDGER_MISSING" | "TRUST_READINESS_ASSESSMENT_MISSING" | "FINAL_EVIDENCE_PACKAGE_MISSING" | "QUALIFICATION_DASHBOARD_MISSING"
  | "CONSTITUTIONAL_BYPASS_DETECTED" | "NONDETERMINISTIC_TRUST_DECISION_DETECTED" | "UNREPLAYABLE_DECISION_DETECTED" | "MUTABLE_EVIDENCE_DETECTED" | "INCOMPLETE_LINEAGE_DETECTED" | "TENANT_ISOLATION_BREACH_DETECTED" | "HIGH_OR_CRITICAL_FINDINGS_OPEN" | "FINAL_AUTHORITY_NOT_ISSUED" | "PROGRAM_QUALIFICATION_REPLAY_DIVERGED" | "TRUST_PROGRAM_QUALIFICATION_FAILED";
export type TrustProgramQualificationScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | TrustProgramQualificationFailure;
export type TrustProgramQualificationInput = Readonly<{ scenario?: TrustProgramQualificationScenario; seed?: string; tenant_id?: string; qualification_id?: string }>;
export type QualificationMatrix = Readonly<{ matrix_id: string; areas: readonly ProgramQualificationArea[]; constitutional_compliance: boolean; trust_determinism: boolean; resolution_correctness: boolean; explainability: boolean; human_oversight: boolean; continuous_monitoring: boolean; drift_detection: boolean; recovery_revocation: boolean; trust_certification: boolean; trust_federation: boolean; replay: boolean; evidence_integrity: boolean; immutable_lineage: boolean; tenant_isolation: boolean; constitutional_invariants: boolean; integrity_hash: string }>;
export type ProgramQualificationEvidence = Readonly<{ evidence_id: string; program_qualification_report: boolean; qualification_evidence_ledger: boolean; qualification_decision: boolean; trust_readiness_assessment: boolean; constitutional_compliance_report: boolean; deterministic_replay_report: boolean; evidence_integrity_report: boolean; trust_qualification_dashboard: boolean; final_qualification_evidence_package: boolean; immutable: boolean; complete: boolean; replayable: boolean; integrity_hash: string }>;
export type ProgramQualificationReplay = Readonly<{ replay_id: string; decision_replay: boolean; constitutional_replay: boolean; evidence_replay: boolean; oversight_replay: boolean; monitoring_replay: boolean; certification_replay: boolean; federation_replay: boolean; identical_outcomes: boolean; identical_evidence: boolean; identical_lineage: boolean; integrity_hash: string }>;
export type ProgramQualificationLineage = Readonly<{ lineage_id: string; decision_lineage: boolean; standing_lineage: boolean; evidence_lineage: boolean; oversight_lineage: boolean; certification_lineage: boolean; federation_lineage: boolean; immutable_lineage: boolean; complete_lineage: boolean; queryable_lineage: boolean; integrity_hash: string }>;
export type ProgramQualificationIsolation = Readonly<{ isolation_id: string; domain_isolation: boolean; tenant_boundaries: boolean; cross_domain_enforcement: boolean; federation_boundaries: boolean; trust_registry_isolation: boolean; evidence_isolation: boolean; no_cross_tenant_leakage: boolean; isolation_validated: boolean; integrity_hash: string }>;
export type ProgramQualificationFindings = Readonly<{ findings_id: string; highest_severity: QualificationFindingSeverity; critical_findings_open: number; high_findings_open: number; medium_findings_open: number; low_findings_open: number; unresolved_constitutional_findings: number; unresolved_governance_findings: number; unresolved_replay_findings: number; unresolved_evidence_findings: number; unresolved_trust_integrity_findings: number; no_blocking_findings: boolean; integrity_hash: string }>;
export type ProgramQualificationAuthority = Readonly<{ authority_id: string; final_decision: ProgramQualificationDecision; cata_trust_framework_qualified: boolean; constitutional_trust_authority_for_proprium: boolean; constitutional_trust_authority_for_civitas: boolean; autonomous_trust_governance_ready: boolean; formal_authority_issued: boolean; effective_authority: boolean; integrity_hash: string }>;
export type TrustProgramQualificationReadiness = Readonly<{ readiness_id: string; decision: ProgramQualificationDecision; phase_ready: boolean; upstream_ready: boolean; matrix_ready: boolean; evidence_ready: boolean; replay_ready: boolean; lineage_ready: boolean; isolation_ready: boolean; findings_clear: boolean; authority_ready: boolean; constitutional_supremacy: boolean; deterministic_trust: boolean; evidence_based_qualification: boolean; replayability: boolean; explainability: boolean; tenant_isolation: boolean; no_bypass: boolean; no_high_or_critical_findings: boolean; formally_qualified: boolean; failures: readonly TrustProgramQualificationFailure[]; integrity_hash: string }>;
export type TrustProgramQualificationResult = Readonly<{ phase_version: "trust-program-qualification-stage-thirteen/stage-13"; phase_identifier: "TrustProgramQualificationStageThirteen"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; qualification_id: string; matrix: QualificationMatrix; evidence: ProgramQualificationEvidence; replay: ProgramQualificationReplay; lineage: ProgramQualificationLineage; isolation: ProgramQualificationIsolation; findings: ProgramQualificationFindings; authority: ProgramQualificationAuthority; readiness: TrustProgramQualificationReadiness; replay_hash: string; integrity_hash: string }>;
export type TrustProgramQualificationValidation = Readonly<{ valid: boolean; decision: ProgramQualificationDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; matrix_valid: boolean; evidence_valid: boolean; replay_valid: boolean; lineage_valid: boolean; isolation_valid: boolean; findings_valid: boolean; authority_valid: boolean; readiness_valid: boolean; failures: readonly TrustProgramQualificationFailure[]; integrity_hash: string }>;
export type TrustProgramQualificationBundle = Readonly<{ doctrine: Readonly<{ version: "trust-program-qualification-stage-thirteen/stage-13"; final_constitutional_qualification_gate: true; cata_authority_requires_qualified_decision: true; no_component_may_rely_before_qualification: true; immutable_evidence_required: true; deterministic_replay_required: true; no_high_or_critical_findings_allowed: true; qualification_gate: "Stage 13 Program Qualification Gate" }>; result: TrustProgramQualificationResult; validation: TrustProgramQualificationValidation }>;
