export type TrustFoundationStageOneDecision = "FOUNDATION_ESTABLISHED" | "CONDITIONALLY_ESTABLISHED" | "NOT_ESTABLISHED" | "FAIL_CLOSED";
export type TrustServiceArea = "EVALUATION" | "REGISTRY" | "EVIDENCE" | "CERTIFICATION" | "MONITORING" | "EXPLAINABILITY" | "GOVERNANCE" | "FEDERATION" | "ADMINISTRATION";
export type TrustLifecycleState = "DRAFT" | "DEFINED" | "APPROVED" | "ACTIVE" | "UNDER_REVIEW" | "SUSPENDED" | "REVOKED" | "RECOVERING" | "ARCHIVED";
export type TrustFoundationStageOneFailure =
  | "P5_0_TRUST_CONSTITUTION_INVALID" | "P5_1_TRUST_ARCHITECTURE_INVALID" | "LAYER_0_CONSTITUTIONAL_FRAMEWORKS_INVALID" | "CCI_INFRASTRUCTURE_INVALID" | "CAF_CONSTITUTIONAL_FOUNDATION_INVALID" | "CAF_CATA_INTEGRATION_CONTRACTS_INVALID" | "TENANT_INTEGRATION_CONTRACT_INVALID"
  | "TRUST_CONSTITUTION_MISSING" | "TRUST_CONSTITUTION_NOT_APPROVED" | "CONSTITUTIONAL_RULES_MISSING" | "INVARIANT_REGISTRY_MISSING" | "FAIL_CLOSED_RULES_MISSING"
  | "TRUST_ARCHITECTURE_MISSING" | "SERVICE_DECOMPOSITION_MISSING" | "DEPENDENCY_MODEL_MISSING" | "INTEGRATION_ARCHITECTURE_MISSING" | "MULTI_TENANT_ARCHITECTURE_MISSING"
  | "TRUST_DOCTRINE_MISSING" | "INDEPENDENCE_DOCTRINE_MISSING" | "REPLAY_DOCTRINE_MISSING" | "CERTIFICATION_DOCTRINE_MISSING"
  | "TRUST_VOCABULARY_MISSING" | "ENUMERATION_REGISTRY_MISSING" | "CANONICAL_DEFINITIONS_MISSING" | "TERMINOLOGY_NOT_FROZEN"
  | "TRUST_LIFECYCLE_MISSING" | "LIFECYCLE_TRANSITION_RULES_MISSING" | "REVOCATION_LIFECYCLE_MISSING" | "ARCHIVAL_LIFECYCLE_MISSING"
  | "TRUST_APIS_MISSING" | "API_CONTRACTS_MISSING" | "ADMINISTRATIVE_APIS_MISSING"
  | "TRUST_CONTRACTS_MISSING" | "CONTRACT_CATALOG_MISSING" | "EVENT_CONTRACTS_MISSING" | "CONTRACT_VERSIONING_MISSING"
  | "TRUST_EVENT_MODEL_MISSING" | "EVENT_CATALOG_MISSING" | "EVENT_REPLAY_SEMANTICS_MISSING" | "EVENT_LINEAGE_MISSING" | "EVENT_ORDERING_NOT_DETERMINISTIC"
  | "TRUST_GOVERNANCE_MODEL_MISSING" | "AUTHORITY_MATRIX_MISSING" | "HUMAN_OVERSIGHT_GOVERNANCE_MISSING" | "CONSTITUTIONAL_PRECEDENCE_MISSING" | "EXCEPTION_GOVERNANCE_MISSING"
  | "DOWNSTREAM_DEPENDENCIES_NOT_BASELINED" | "STAGE_TWO_NOT_ENABLED" | "TRUST_AUTHORITY_CREATION_ATTEMPTED" | "GOVERNANCE_BYPASS_ATTEMPTED" | "NON_DETERMINISTIC_EVENT_MODEL";
export type TrustFoundationStageOneScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | TrustFoundationStageOneFailure;
export type TrustFoundationStageOneInput = Readonly<{ scenario?: TrustFoundationStageOneScenario; seed?: string; tenant_id?: string; foundation_id?: string }>;
export type TrustConstitutionBaseline = Readonly<{ constitution_id: string; constitutional_principles: boolean; authority_hierarchy: boolean; constitutional_invariants: boolean; separation_of_responsibilities: boolean; trust_admissibility: boolean; governance_supremacy: boolean; human_oversight_authority: boolean; deterministic_decision_requirements: boolean; explainability_requirements: boolean; evidence_requirements: boolean; fail_closed_rules: boolean; approved: boolean; integrity_hash: string }>;
export type TrustArchitectureBaseline = Readonly<{ architecture_id: string; architectural_layers: boolean; service_decomposition: boolean; internal_services: readonly TrustServiceArea[]; external_integration_points: boolean; dependency_model: boolean; service_ownership: boolean; deployment_boundaries: boolean; multi_tenant_architecture: boolean; trust_processing_pipeline: boolean; constitutional_evaluation_flow: boolean; integrity_hash: string }>;
export type TrustDoctrineBaseline = Readonly<{ doctrine_id: string; constitutional_principles: boolean; trust_philosophy: boolean; independent_evaluation: boolean; trust_separation: boolean; risk_independence: boolean; confidence_independence: boolean; alignment_independence: boolean; human_oversight: boolean; deterministic_replay: boolean; certification: boolean; integrity_hash: string }>;
export type TrustVocabularyBaseline = Readonly<{ vocabulary_id: string; terminology: readonly string[]; enumeration_registry: boolean; standard_identifiers: boolean; object_naming: boolean; lifecycle_terminology: boolean; governance_terminology: boolean; certification_terminology: boolean; frozen: boolean; versioned: boolean; integrity_hash: string }>;
export type TrustLifecycleBaseline = Readonly<{ lifecycle_id: string; states: readonly TrustLifecycleState[]; trust_object_lifecycle: boolean; evaluation_lifecycle: boolean; decision_lifecycle: boolean; evidence_lifecycle: boolean; certification_lifecycle: boolean; review_lifecycle: boolean; suspension_lifecycle: boolean; revocation_lifecycle: boolean; recovery_lifecycle: boolean; archival_lifecycle: boolean; transition_rules: boolean; integrity_hash: string }>;
export type TrustApiBaseline = Readonly<{ api_id: string; service_areas: readonly TrustServiceArea[]; evaluation_apis: boolean; registry_apis: boolean; evidence_apis: boolean; certification_apis: boolean; monitoring_apis: boolean; explainability_apis: boolean; governance_apis: boolean; federation_apis: boolean; administrative_apis: boolean; reviewed: boolean; integrity_hash: string }>;
export type TrustContractBaseline = Readonly<{ catalog_id: string; evaluation_contracts: boolean; evidence_contracts: boolean; registry_contracts: boolean; monitoring_contracts: boolean; explainability_contracts: boolean; governance_contracts: boolean; federation_contracts: boolean; certification_contracts: boolean; event_contracts: boolean; versioned: boolean; validated: boolean; integrity_hash: string }>;
export type TrustEventModelBaseline = Readonly<{ event_model_id: string; taxonomy: boolean; identifiers: boolean; schema: boolean; lineage: boolean; ordering: boolean; replay_semantics: boolean; correlation_identifiers: boolean; versioning: boolean; audit_events: boolean; governance_events: boolean; deterministic: boolean; integrity_hash: string }>;
export type TrustGovernanceBaseline = Readonly<{ governance_id: string; governance_authority: boolean; decision_ownership: boolean; constitutional_precedence: boolean; change_governance: boolean; policy_governance: boolean; version_governance: boolean; contract_governance: boolean; exception_governance: boolean; human_oversight_governance: boolean; certification_governance: boolean; authority_matrix: boolean; integrity_hash: string }>;
export type TrustFoundationStageOneReadiness = Readonly<{ readiness_id: string; decision: TrustFoundationStageOneDecision; phase_ready: boolean; upstream_ready: boolean; constitution_ready: boolean; architecture_ready: boolean; doctrine_ready: boolean; vocabulary_ready: boolean; lifecycle_ready: boolean; apis_ready: boolean; contracts_ready: boolean; events_ready: boolean; governance_ready: boolean; downstream_dependencies_baselined: boolean; stage_two_authorized: boolean; deterministic_event_model: boolean; constitutional_authority_preserved: boolean; governance_supremacy_preserved: boolean; human_oversight_preserved: boolean; tenant_integration_ready: boolean; failures: readonly TrustFoundationStageOneFailure[]; integrity_hash: string }>;
export type TrustFoundationStageOneResult = Readonly<{ phase_version: "trust-foundation-stage-one/stage-1"; phase_identifier: "TrustFoundationStageOne"; upstream_refs: readonly string[]; enables: readonly string[]; tenant_id: string; foundation_id: string; constitution: TrustConstitutionBaseline; architecture: TrustArchitectureBaseline; doctrine: TrustDoctrineBaseline; vocabulary: TrustVocabularyBaseline; lifecycle: TrustLifecycleBaseline; apis: TrustApiBaseline; contracts: TrustContractBaseline; events: TrustEventModelBaseline; governance: TrustGovernanceBaseline; readiness: TrustFoundationStageOneReadiness; replay_hash: string; integrity_hash: string }>;
export type TrustFoundationStageOneValidation = Readonly<{ valid: boolean; decision: TrustFoundationStageOneDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; constitution_valid: boolean; architecture_valid: boolean; doctrine_valid: boolean; vocabulary_valid: boolean; lifecycle_valid: boolean; apis_valid: boolean; contracts_valid: boolean; events_valid: boolean; governance_valid: boolean; readiness_valid: boolean; failures: readonly TrustFoundationStageOneFailure[]; integrity_hash: string }>;
export type TrustFoundationStageOneBundle = Readonly<{ doctrine: Readonly<{ version: "trust-foundation-stage-one/stage-1"; owns_cata_trust_baseline: true; establishes_constitutional_authority: true; freezes_canonical_vocabulary: true; defines_stage_contracts: true; defines_deterministic_event_model: true; authorizes_stage_two: true; qualification_gate: "Stage 1 Trust Foundation Qualification Gate" }>; result: TrustFoundationStageOneResult; validation: TrustFoundationStageOneValidation }>;
