export type OversightDisposition = "ALLOW" | "ALLOW_WITH_RESTRICTIONS" | "DENY" | "CANCELLED" | "SUPERSEDED";
export type OversightLifecycleState = "PENDING" | "UNDER_REVIEW" | "INFORMATION_REQUESTED" | "RESOLVED" | "CANCELLED" | "SUPERSEDED";
export type TrustHumanOversightDecision = "HUMAN_OVERSIGHT_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type TrustHumanOversightFailure =
  | "STAGE_1_TRUST_FOUNDATION_INVALID" | "STAGE_2_CONSTITUTIONAL_GATE_INVALID" | "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" | "STAGE_4_INDEPENDENT_EVALUATION_INVALID" | "STAGE_5_TRUST_RESOLUTION_INVALID" | "STAGE_6_EXPLAINABILITY_INVALID"
  | "OVERSIGHT_QUEUE_MISSING" | "QUEUE_PRIORITIZATION_MISSING" | "ROUTING_RULES_MISSING" | "REVIEWER_ASSIGNMENT_MISSING" | "QUEUE_TENANT_ISOLATION_MISSING" | "QUEUE_REPLAY_MISSING" | "QUEUE_AUDIT_MISSING" | "MULTIPLE_QUEUES_ASSIGNED"
  | "OVERSIGHT_WORKFLOW_MISSING" | "REVIEW_TASKS_MISSING" | "EVIDENCE_REVIEW_MISSING" | "RESTRICTION_REVIEW_MISSING" | "CONSTITUTIONAL_REVIEW_MISSING" | "REVIEW_COMPLETION_MISSING" | "WORKFLOW_REPLAY_MISSING"
  | "REVIEW_LIFECYCLE_MISSING" | "STATE_MACHINE_MISSING" | "TRANSITION_VALIDATION_MISSING" | "INVALID_LIFECYCLE_STATE_ALLOWED" | "LIFECYCLE_HISTORY_MISSING" | "LIFECYCLE_REPLAY_MISSING"
  | "DECISION_RECORDING_MISSING" | "REVIEWER_IDENTITY_MISSING" | "DECISION_SIGNATURE_MISSING" | "DECISION_RECORD_MUTABLE" | "DISPOSITION_RECORDING_MISSING"
  | "ESCALATION_RESOLUTION_MISSING" | "DISPOSITION_VALIDATION_MISSING" | "RESTRICTION_VALIDATION_MISSING" | "STANDING_VALIDATION_MISSING" | "CONSTITUTIONAL_VALIDATION_MISSING" | "CONSTITUTIONAL_DENY_OVERRIDDEN" | "FAIL_CLOSED_OVERRIDDEN" | "RESTRICTIONS_BYPASSED"
  | "OVERSIGHT_EVIDENCE_MISSING" | "REVIEWER_EVIDENCE_MISSING" | "WORKFLOW_EVIDENCE_MISSING" | "TIMELINE_EVIDENCE_MISSING" | "EVIDENCE_HASH_INVALID" | "EVIDENCE_REPLAY_MISSING"
  | "DECISION_LINEAGE_MISSING" | "ESCALATION_LINEAGE_MISSING" | "REVIEW_LINEAGE_MISSING" | "CONSTITUTIONAL_REFERENCES_MISSING" | "TRUST_REFERENCES_MISSING" | "LINEAGE_NOT_TRACEABLE"
  | "OVERSIGHT_BYPASSED_AUTOMATED_EVALUATION" | "HISTORICAL_DECISION_REWRITTEN" | "EVIDENCE_REMOVED" | "HUMAN_OVERSIGHT_QUALIFICATION_FAILED";
export type TrustHumanOversightScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | TrustHumanOversightFailure;
export type TrustHumanOversightInput = Readonly<{ scenario?: TrustHumanOversightScenario; seed?: string; tenant_id?: string; oversight_id?: string }>;
export type OversightQueue = Readonly<{ queue_id: string; receives_escalate_decisions: boolean; exactly_one_queue: boolean; queue_prioritization: boolean; routing_rules: boolean; reviewer_assignment: boolean; tenant_isolation: boolean; queue_replay: boolean; queue_recovery: boolean; queue_audit: boolean; ordering_maintained: boolean; ownership_tracked: boolean; integrity_hash: string }>;
export type OversightWorkflow = Readonly<{ workflow_id: string; review_workflow: boolean; review_tasks: boolean; evidence_review: boolean; restriction_review: boolean; constitutional_review: boolean; decision_preparation: boolean; review_completion: boolean; workflow_recovery: boolean; required_steps_enforced: boolean; deterministic: boolean; replay_verified: boolean; integrity_hash: string }>;
export type ReviewLifecycle = Readonly<{ lifecycle_id: string; states: readonly OversightLifecycleState[]; state_machine: boolean; transition_validation: boolean; lifecycle_events: boolean; timeout_handling: boolean; expiration: boolean; lifecycle_recovery: boolean; lifecycle_history: boolean; invalid_states_prevented: boolean; replay_identical: boolean; integrity_hash: string }>;
export type OversightDecisionRecord = Readonly<{ decision_id: string; dispositions: readonly OversightDisposition[]; disposition_recording: boolean; reviewer_identity: boolean; decision_timestamp: boolean; decision_metadata: boolean; restriction_recording: boolean; approval_conditions: boolean; decision_signatures: boolean; immutable_records: boolean; replay_support: boolean; integrity_hash: string }>;
export type OversightResolution = Readonly<{ resolution_id: string; resolution_logic: boolean; disposition_validation: boolean; restriction_validation: boolean; standing_validation: boolean; constitutional_validation: boolean; resolution_evidence: boolean; resolution_lineage: boolean; authority_verified: boolean; deny_not_relaxed: boolean; fail_closed_not_overridden: boolean; restrictions_preserved: boolean; deterministic_outcomes: boolean; integrity_hash: string }>;
export type OversightEvidence = Readonly<{ evidence_id: string; oversight_evidence: boolean; reviewer_evidence: boolean; decision_evidence: boolean; workflow_evidence: boolean; timeline_evidence: boolean; immutable_storage: boolean; evidence_hashing: boolean; evidence_replay: boolean; certification_ready: boolean; integrity_hash: string }>;
export type OversightLineage = Readonly<{ lineage_id: string; decision_lineage_graph: boolean; escalation_lineage: boolean; review_lineage: boolean; evidence_relationships: boolean; decision_relationships: boolean; constitutional_references: boolean; trust_references: boolean; replay_relationships: boolean; complete_lineage: boolean; traceability_validated: boolean; integrity_hash: string }>;
export type TrustHumanOversightReadiness = Readonly<{ readiness_id: string; decision: TrustHumanOversightDecision; phase_ready: boolean; upstream_ready: boolean; queue_ready: boolean; workflow_ready: boolean; lifecycle_ready: boolean; decision_recording_ready: boolean; resolution_ready: boolean; evidence_ready: boolean; lineage_ready: boolean; deterministic_routing: boolean; reviewer_assignment_validated: boolean; lifecycle_transitions_validated: boolean; constitutional_limits_preserved: boolean; no_constitutional_override: boolean; immutable_evidence: boolean; replayable: boolean; explainable: boolean; certification_ready: boolean; failures: readonly TrustHumanOversightFailure[]; integrity_hash: string }>;
export type TrustHumanOversightResult = Readonly<{ phase_version: "trust-human-oversight-stage-seven/stage-7"; phase_identifier: "TrustHumanOversightStageSeven"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; oversight_id: string; queue: OversightQueue; workflow: OversightWorkflow; lifecycle: ReviewLifecycle; decision_record: OversightDecisionRecord; resolution: OversightResolution; evidence: OversightEvidence; lineage: OversightLineage; readiness: TrustHumanOversightReadiness; replay_hash: string; integrity_hash: string }>;
export type TrustHumanOversightValidation = Readonly<{ valid: boolean; decision: TrustHumanOversightDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; queue_valid: boolean; workflow_valid: boolean; lifecycle_valid: boolean; decision_record_valid: boolean; resolution_valid: boolean; evidence_valid: boolean; lineage_valid: boolean; readiness_valid: boolean; failures: readonly TrustHumanOversightFailure[]; integrity_hash: string }>;
export type TrustHumanOversightBundle = Readonly<{ doctrine: Readonly<{ version: "trust-human-oversight-stage-seven/stage-7"; constitutional_authority: true; only_after_automated_trust_pipeline: true; cannot_override_deny_or_fail_closed: true; immutable_evidence_required: true; deterministic_replay_required: true; complete_lineage_required: true; qualification_gate: "Stage 7 Human Oversight Qualification Gate" }>; result: TrustHumanOversightResult; validation: TrustHumanOversightValidation }>;
