export type TrustStandingState = "UNKNOWN" | "TRUSTED" | "RESTRICTED" | "SUSPENDED" | "RECOVERED" | "REVOKED" | "EXPIRED";
export type StandingTransition = "SUSPENDED_TO_RESTRICTED" | "SUSPENDED_TO_TRUSTED" | "EXPIRED_TO_RESTRICTED" | "EXPIRED_TO_TRUSTED" | "TRUSTED_TO_RESTRICTED" | "TRUSTED_TO_SUSPENDED" | "TRUSTED_TO_REVOKED" | "TRUSTED_TO_EXPIRED" | "RESTRICTED_TO_TRUSTED" | "RESTRICTED_TO_SUSPENDED" | "RESTRICTED_TO_REVOKED" | "RESTRICTED_TO_EXPIRED";
export type TrustRecoveryRevocationDecision = "RECOVERY_REVOCATION_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type TrustRecoveryRevocationFailure =
  | "STAGE_1_TRUST_FOUNDATION_INVALID" | "STAGE_2_CONSTITUTIONAL_GATE_INVALID" | "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" | "STAGE_4_INDEPENDENT_EVALUATION_INVALID" | "STAGE_5_TRUST_RESOLUTION_INVALID" | "STAGE_6_EXPLAINABILITY_INVALID" | "STAGE_7_HUMAN_OVERSIGHT_INVALID" | "STAGE_8_CONTINUOUS_MONITORING_INVALID" | "STAGE_9_DRIFT_DETECTION_INVALID"
  | "RECOVERY_EVALUATION_ENGINE_MISSING" | "RECOVERY_ELIGIBILITY_RULES_MISSING" | "CONSTITUTIONAL_RECOVERY_VALIDATION_MISSING" | "EVIDENCE_SUFFICIENCY_EVALUATION_MISSING" | "RECOVERY_PRECONDITIONS_MISSING" | "RECOVERY_RISK_REVIEW_MISSING" | "ALIGNMENT_REVALIDATION_MISSING" | "POLICY_REVALIDATION_MISSING" | "SAFETY_REVALIDATION_MISSING" | "RECOVERY_DECISION_LOGIC_MISSING" | "RECOVERY_RECOMMENDATION_MISSING"
  | "RECOVERY_WORKFLOW_MISSING" | "STANDING_PROMOTION_RULES_MISSING" | "RECOVERY_AUTHORIZATION_MISSING" | "RECOVERY_QUALIFICATION_MISSING" | "RECOVERY_VERIFICATION_MISSING" | "RECOVERY_STATE_TRANSITION_MISSING" | "RECOVERY_EVIDENCE_COLLECTION_MISSING" | "STANDING_REINSTATEMENT_MISSING" | "RECOVERY_NOTIFICATIONS_MISSING"
  | "REVOCATION_EVALUATION_MISSING" | "REVOCATION_CRITERIA_MISSING" | "MANDATORY_REVOCATION_RULES_MISSING" | "REVOCATION_AUTHORIZATION_MISSING" | "REVOCATION_EVIDENCE_MISSING" | "REVOCATION_RECORDING_MISSING" | "DEPENDENCY_IMPACT_ANALYSIS_MISSING" | "REVOCATION_NOTIFICATIONS_MISSING" | "FEDERATION_REVOCATION_PROPAGATION_MISSING"
  | "SUSPENSION_EVALUATION_MISSING" | "SUSPENSION_CONDITIONS_MISSING" | "TEMPORARY_RESTRICTIONS_MISSING" | "SUSPENSION_DURATION_MISSING" | "SUSPENSION_REVIEW_MISSING" | "AUTOMATIC_REASSESSMENT_MISSING" | "SUSPENSION_EVIDENCE_MISSING" | "SUSPENSION_NOTIFICATIONS_MISSING"
  | "EXPIRATION_DETECTION_MISSING" | "SCHEDULED_EXPIRATION_MISSING" | "RENEWAL_ELIGIBILITY_MISSING" | "RENEWAL_EVALUATION_MISSING" | "AUTOMATIC_EXPIRATION_MISSING" | "EXPIRATION_NOTIFICATIONS_MISSING" | "EXPIRATION_EVIDENCE_MISSING" | "STANDING_TRANSITION_RULES_MISSING"
  | "RECOVERY_EVIDENCE_PACKAGES_MISSING" | "STANDING_TRANSITION_EVIDENCE_MISSING" | "CONSTITUTIONAL_VALIDATION_EVIDENCE_MISSING" | "RULE_EVALUATION_EVIDENCE_MISSING" | "HUMAN_OVERSIGHT_REFERENCES_MISSING" | "DECISION_LINEAGE_MISSING" | "REPLAY_METADATA_MISSING" | "AUDIT_RECORDS_MISSING"
  | "STANDING_TRANSITION_ENGINE_MISSING" | "TRANSITION_ELIGIBILITY_VALIDATION_MISSING" | "TRANSITION_RULE_ENFORCEMENT_MISSING" | "STANDING_EVENTS_MISSING" | "STANDING_HISTORY_MISSING" | "STANDING_LINEAGE_MISSING" | "STANDING_REPLAY_MISSING"
  | "RECOVERY_BYPASSED_CONSTITUTIONAL_EVALUATION" | "REVOKED_IDENTITY_REINSTATED" | "REVOCATION_REVERSED_WHEN_TERMINAL" | "HUMAN_OVERSIGHT_OVERRIDES_REVOCATION" | "STANDING_MODIFIED_OUTSIDE_GOVERNANCE" | "TRANSITION_EVIDENCE_MUTABLE" | "STANDING_HISTORY_REWRITTEN" | "RECOVERY_REPLAY_DIVERGED" | "RECOVERY_REVOCATION_QUALIFICATION_FAILED";
export type TrustRecoveryRevocationScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | TrustRecoveryRevocationFailure;
export type TrustRecoveryRevocationInput = Readonly<{ scenario?: TrustRecoveryRevocationScenario; seed?: string; tenant_id?: string; standing_id?: string }>;
export type RecoveryEvaluation = Readonly<{ evaluation_id: string; recovery_evaluation_engine: boolean; recovery_eligibility_rules: boolean; constitutional_recovery_validation: boolean; evidence_sufficiency_evaluation: boolean; recovery_preconditions: boolean; recovery_risk_review: boolean; alignment_revalidation: boolean; policy_revalidation: boolean; safety_revalidation: boolean; recovery_decision_logic: boolean; recovery_recommendation: boolean; deterministic: boolean; integrity_hash: string }>;
export type StandingRecovery = Readonly<{ recovery_id: string; supported_paths: readonly StandingTransition[]; non_recoverable_states: readonly TrustStandingState[]; recovery_workflow: boolean; standing_promotion_rules: boolean; recovery_authorization: boolean; recovery_qualification: boolean; recovery_verification: boolean; recovery_state_transition: boolean; recovery_evidence_collection: boolean; standing_reinstatement: boolean; recovery_notifications: boolean; constitutional_only: boolean; integrity_hash: string }>;
export type RevocationWorkflow = Readonly<{ revocation_id: string; revocation_evaluation: boolean; revocation_criteria: boolean; mandatory_revocation_rules: boolean; revocation_authorization: boolean; revocation_evidence: boolean; revocation_recording: boolean; dependency_impact_analysis: boolean; revocation_notifications: boolean; federation_revocation_propagation: boolean; deterministic: boolean; irreversible_when_mandated: boolean; integrity_hash: string }>;
export type SuspensionWorkflow = Readonly<{ suspension_id: string; suspension_evaluation: boolean; suspension_conditions: boolean; temporary_restrictions: boolean; suspension_duration: boolean; suspension_review: boolean; automatic_reassessment: boolean; suspension_evidence: boolean; suspension_notifications: boolean; recovery_eligibility_preserved: boolean; replayable: boolean; integrity_hash: string }>;
export type ExpirationProcessing = Readonly<{ expiration_id: string; expiration_detection: boolean; scheduled_expiration: boolean; renewal_eligibility: boolean; renewal_evaluation: boolean; automatic_expiration: boolean; expiration_notifications: boolean; expiration_evidence: boolean; standing_transition_rules: boolean; deterministic_processing: boolean; integrity_hash: string }>;
export type RecoveryEvidence = Readonly<{ evidence_id: string; recovery_evidence_packages: boolean; standing_transition_evidence: boolean; constitutional_validation_evidence: boolean; rule_evaluation_evidence: boolean; human_oversight_references: boolean; decision_lineage: boolean; replay_metadata: boolean; audit_records: boolean; immutable: boolean; integrity_hash: string }>;
export type StandingTransitionEngine = Readonly<{ engine_id: string; lifecycle_states: readonly TrustStandingState[]; transition_rules: readonly StandingTransition[]; validate_constitutional_eligibility: boolean; verify_recovery_requirements: boolean; enforce_transition_rules: boolean; generate_immutable_evidence: boolean; record_complete_lineage: boolean; update_standing_deterministically: boolean; publish_standing_events: boolean; deterministic_replay: boolean; integrity_hash: string }>;
export type TrustRecoveryRevocationReadiness = Readonly<{ readiness_id: string; decision: TrustRecoveryRevocationDecision; phase_ready: boolean; upstream_ready: boolean; recovery_evaluation_ready: boolean; standing_recovery_ready: boolean; revocation_ready: boolean; suspension_ready: boolean; expiration_ready: boolean; evidence_ready: boolean; transition_engine_ready: boolean; constitutional_governance: boolean; no_bypass: boolean; terminal_revocation_enforced: boolean; human_oversight_bounded: boolean; immutable_transitions: boolean; permanent_history: boolean; replayable: boolean; certification_ready: boolean; failures: readonly TrustRecoveryRevocationFailure[]; integrity_hash: string }>;
export type TrustRecoveryRevocationResult = Readonly<{ phase_version: "trust-recovery-revocation-stage-ten/stage-10"; phase_identifier: "TrustRecoveryRevocationStageTen"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; standing_id: string; recovery_evaluation: RecoveryEvaluation; standing_recovery: StandingRecovery; revocation: RevocationWorkflow; suspension: SuspensionWorkflow; expiration: ExpirationProcessing; evidence: RecoveryEvidence; transition_engine: StandingTransitionEngine; readiness: TrustRecoveryRevocationReadiness; replay_hash: string; integrity_hash: string }>;
export type TrustRecoveryRevocationValidation = Readonly<{ valid: boolean; decision: TrustRecoveryRevocationDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; recovery_evaluation_valid: boolean; standing_recovery_valid: boolean; revocation_valid: boolean; suspension_valid: boolean; expiration_valid: boolean; evidence_valid: boolean; transition_engine_valid: boolean; readiness_valid: boolean; failures: readonly TrustRecoveryRevocationFailure[]; integrity_hash: string }>;
export type TrustRecoveryRevocationBundle = Readonly<{ doctrine: Readonly<{ version: "trust-recovery-revocation-stage-ten/stage-10"; constitution_governs_all_standing_transitions: true; recovery_never_bypasses_constitutional_evaluation: true; revocation_irreversible_when_required: true; standing_history_permanent: true; immutable_transition_evidence_required: true; deterministic_replay_required: true; qualification_gate: "Stage 10 Recovery and Revocation Qualification Gate" }>; result: TrustRecoveryRevocationResult; validation: TrustRecoveryRevocationValidation }>;
