export type WaveSixDependencyReadinessState = "READY" | "DEGRADED_READY" | "WAITING" | "NOT_READY";
export type WaveSixDependencyState = "REGISTERED" | "AVAILABLE" | "DEGRADED" | "UNAVAILABLE" | "WAITING" | "FAILED" | "UNKNOWN";
export type WaveSixDependencyServiceCoordinationDecision = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED";
export type WaveSixDependencyServiceCoordinationFailure =
  | "W6_1_OPERATIONAL_ORCHESTRATION_INVALID"
  | "DEPENDENCY_REGISTRY_MISSING" | "DEPENDENCY_GRAPH_NONDETERMINISTIC" | "SERVICE_RELATIONSHIP_CATALOG_MISSING" | "UNMANAGED_DEPENDENCY_DISCOVERED"
  | "PROVIDER_AVAILABILITY_MONITOR_MISSING" | "MISSING_HEALTH_INFORMATION_ASSUMED_AVAILABLE" | "UNKNOWN_DEPENDENCY_NOT_FAIL_CLOSED" | "PROVIDER_STATUS_REGISTRY_MISSING"
  | "DEPENDENCY_OBSERVATION_ENGINE_MISSING" | "PROVIDER_TRANSITIONS_NOT_TRACKED" | "FAILURE_PROPAGATION_INVALID" | "RECOVERY_DETECTION_INVALID" | "DEPENDENCY_LATENCY_MISSING"
  | "ORCHESTRATION_READINESS_ENGINE_MISSING" | "READINESS_NONDETERMINISTIC" | "REQUIRED_DEPENDENCY_UNAVAILABLE_READY" | "GOVERNANCE_SERVICE_UNAVAILABLE_READY" | "TRUST_SERVICE_UNAVAILABLE_READY" | "MISSION_SERVICE_UNAVAILABLE_READY"
  | "DEPENDENCY_COORDINATION_ENGINE_MISSING" | "SERVICE_LIFECYCLE_MODIFIED" | "DEPENDENCY_SEQUENCING_INVALID" | "READINESS_PROPAGATION_INVALID"
  | "OPERATIONAL_READINESS_ASSESSMENT_MISSING" | "READINESS_REPORT_INCOMPLETE" | "PROVIDER_RESPONSIVENESS_MISSING" | "DEPENDENCY_CONSISTENCY_INVALID"
  | "DEPENDENCY_FAILURE_ANALYSIS_MISSING" | "MISSING_DEPENDENCY_NOT_DETECTED" | "VERSION_INCOMPATIBILITY_NOT_DETECTED" | "CIRCULAR_DEPENDENCY_NOT_DETECTED" | "DEPENDENCY_CASCADE_NOT_DETECTED" | "IMPACT_ASSESSMENT_NONDETERMINISTIC"
  | "READINESS_EVIDENCE_MISSING" | "READINESS_EVIDENCE_MUTABLE" | "DEPENDENCY_LINEAGE_INCOMPLETE" | "REPLAY_DIVERGED" | "W6_1_BYPASSES_READINESS_INTELLIGENCE"
  | "TENANT_ISOLATION_BREACH" | "DEPENDENCY_SERVICE_COORDINATION_QUALIFICATION_FAILED";
export type WaveSixDependencyServiceCoordinationScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | WaveSixDependencyServiceCoordinationFailure;
export type WaveSixDependencyServiceCoordinationInput = Readonly<{ scenario?: WaveSixDependencyServiceCoordinationScenario; seed?: string; tenant_id?: string; principal_id?: string }>;
export type WaveSixDependencyRegistry = Readonly<{ registry_id: string; dependency_identities: boolean; service_relationships: boolean; consumer_provider_mappings: boolean; runtime_dependency_graph: boolean; version_awareness: boolean; required_optional_classification: boolean; dependency_metadata: boolean; cci_service_registry_source: boolean; unmanaged_dependencies_blocked: boolean; graph_deterministic: boolean; states: readonly WaveSixDependencyState[]; integrity_hash: string }>;
export type WaveSixProviderObservation = Readonly<{ observation_id: string; availability_monitor: boolean; provider_status_registry: boolean; availability: boolean; connectivity: boolean; registration_status: boolean; runtime_heartbeat: boolean; capacity_status: boolean; health_endpoint_results: boolean; maintenance_state: boolean; dependency_state_tracking: boolean; provider_transitions: boolean; failure_propagation: boolean; recovery_detection: boolean; dependency_latency: boolean; registration_changes: boolean; dependency_events: boolean; dependency_timeline: boolean; observation_evidence: boolean; missing_health_fails_closed: boolean; unknown_state_not_ready: boolean; integrity_hash: string }>;
export type WaveSixReadinessCoordination = Readonly<{ readiness_coordination_id: string; readiness_engine: boolean; required_dependencies_available: boolean; required_services_healthy: boolean; runtime_reachable: boolean; governance_services_operational: boolean; trust_services_operational: boolean; mission_services_operational: boolean; readiness_state: WaveSixDependencyReadinessState; deterministic_evaluation: boolean; dependency_coordination_engine: boolean; startup_ordering: boolean; shutdown_ordering: boolean; dependency_stabilization: boolean; recovery_coordination: boolean; dependency_synchronization: boolean; readiness_propagation: boolean; observes_only: boolean; never_starts_services: boolean; never_stops_services: boolean; integrity_hash: string }>;
export type WaveSixOperationalReadinessFailureAnalysis = Readonly<{ analysis_id: string; operational_readiness_assessment: boolean; service_availability: boolean; dependency_health: boolean; runtime_stability: boolean; provider_responsiveness: boolean; required_capability_availability: boolean; dependency_consistency: boolean; operational_readiness_report: boolean; readiness_evidence: boolean; readiness_timeline: boolean; dependency_failure_analysis: boolean; provider_failure: boolean; missing_dependency: boolean; dependency_timeout: boolean; registration_inconsistency: boolean; version_incompatibility: boolean; circular_dependency: boolean; dependency_cascade: boolean; deterministic_impact_assessment: boolean; integrity_hash: string }>;
export type WaveSixDependencyEvidence = Readonly<{ evidence_id: string; dependency_snapshots: boolean; availability_snapshots: boolean; readiness_decisions: boolean; health_history: boolean; dependency_transitions: boolean; operational_evidence_lineage: boolean; dependency_evidence: boolean; availability_evidence: boolean; readiness_evidence: boolean; health_evidence: boolean; failure_evidence: boolean; recovery_evidence: boolean; dependency_lineage: boolean; operational_coordination_evidence: boolean; immutable: boolean; replayable: boolean; w6_1_consumes_readiness_decisions: boolean; w6_1_no_direct_dependency_inspection: boolean; integrity_hash: string }>;
export type WaveSixDependencyServiceCoordinationReadiness = Readonly<{ readiness_id: string; decision: WaveSixDependencyServiceCoordinationDecision; phase_ready: boolean; w6_1_ready: boolean; dependency_registry_operational: boolean; runtime_dependency_graph_deterministic: boolean; provider_availability_monitored: boolean; dependency_observation_validated: boolean; orchestration_readiness_deterministic: boolean; dependency_coordination_operational: boolean; readiness_reports_correct: boolean; failure_propagation_validated: boolean; recovery_detection_verified: boolean; immutable_operational_evidence_recorded: boolean; replay_identical_readiness_decisions: boolean; w6_1_consumes_readiness_without_direct_inspection: boolean; operational_awareness_only: boolean; failures: readonly WaveSixDependencyServiceCoordinationFailure[]; integrity_hash: string }>;
export type WaveSixDependencyServiceCoordinationResult = Readonly<{ phase_version: "wave-six-dependency-service-coordination/w6.2"; phase_identifier: "WaveSixDependencyServiceCoordination"; operational_orchestration_ref: "wave-six-operational-orchestration/w6.1"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; principal_id: string; dependency_registry: WaveSixDependencyRegistry; provider_observation: WaveSixProviderObservation; readiness_coordination: WaveSixReadinessCoordination; operational_readiness_failure_analysis: WaveSixOperationalReadinessFailureAnalysis; evidence: WaveSixDependencyEvidence; readiness: WaveSixDependencyServiceCoordinationReadiness; replay_hash: string; integrity_hash: string }>;
export type WaveSixDependencyServiceCoordinationValidation = Readonly<{ valid: boolean; decision: WaveSixDependencyServiceCoordinationDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; dependency_registry_valid: boolean; provider_observation_valid: boolean; readiness_coordination_valid: boolean; operational_readiness_failure_analysis_valid: boolean; evidence_valid: boolean; readiness_valid: boolean; failures: readonly WaveSixDependencyServiceCoordinationFailure[]; integrity_hash: string }>;
export type WaveSixDependencyServiceCoordinationBundle = Readonly<{ doctrine: Readonly<{ version: "wave-six-dependency-service-coordination/w6.2"; observes_never_executes: true; registry_driven_discovery_required: true; deterministic_readiness_required: true; fail_closed_unknown_state_required: true; immutable_dependency_evidence_required: true; service_lifecycle_modification_prohibited: true; w6_1_consumes_readiness_decisions: true; qualification_gate: "W6.2 Dependency and Service Coordination Qualification Gate" }>; result: WaveSixDependencyServiceCoordinationResult; validation: WaveSixDependencyServiceCoordinationValidation }>;
