export type WaveFiveAuroraDecision = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED";
export type WaveFiveAuroraFailure =
  | "AURORA_APPLICATION_INVALID" | "W5_LEARNING_STEVN_INVALID"
  | "CONVERSATION_INTERFACE_MISSING" | "VOICE_READY_ARCHITECTURE_MISSING" | "COMMAND_PARSING_MISSING" | "MULTITURN_CONTINUITY_INVALID" | "SESSION_AWARENESS_MISSING" | "ACCESSIBILITY_SUPPORT_MISSING"
  | "BRIEFING_ENGINE_MISSING" | "BRIEFING_EVIDENCE_MISSING" | "BRIEFING_PRIORITIZATION_INVALID" | "ACTION_SUGGESTIONS_UNGOVERNED"
  | "CONTEXT_ASSEMBLY_MISSING" | "UNAUTHORIZED_CONTEXT_ASSEMBLED" | "CONTEXT_FRESHNESS_INVALID" | "SOURCE_GOVERNANCE_BYPASSED" | "PERMISSION_FILTERING_MISSING" | "TENANT_CONTEXT_LEAK"
  | "INTENT_RESOLUTION_MISSING" | "INTENT_ROUTING_NONDETERMINISTIC" | "ACTION_ROUTER_MISSING" | "DIRECT_BUSINESS_LOGIC_EXECUTED" | "GOVERNED_API_ROUTING_BYPASSED" | "EXECUTION_MONITORING_MISSING" | "FAILURE_HANDLING_MISSING"
  | "EXPLANATION_ENGINE_MISSING" | "EXPLANATIONS_NOT_EVIDENCE_BACKED" | "POLICY_EXPLANATIONS_MISSING" | "RESTRICTION_EXPLANATIONS_MISSING" | "ACTION_LINEAGE_MISSING" | "CONFIDENCE_PRESENTATION_MISSING"
  | "GOVERNANCE_VALIDATION_MISSING" | "CONSTITUTIONAL_GOVERNANCE_BYPASSED" | "AUTHORIZATION_VALIDATION_MISSING" | "DIRECT_PRIVILEGE_ESCALATION" | "UNRESTRICTED_SUPERUSER_AUTHORITY" | "EVIDENCE_NOT_ATTACHED" | "EVIDENCE_VISIBILITY_UNAUTHORIZED" | "PRIVACY_DISCLOSURE_UNAUTHORIZED"
  | "CONVERSATIONAL_MEMORY_MISSING" | "MEMORY_POLICY_BYPASSED" | "GUIDED_WORKFLOWS_MISSING" | "RECOMMENDATIONS_NOT_ADVISORY" | "RECOMMENDATION_EVIDENCE_MISSING"
  | "AURORA_REPLAY_DIVERGED" | "AURORA_ORCHESTRATION_QUALIFICATION_FAILED";
export type WaveFiveAuroraScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | WaveFiveAuroraFailure;
export type WaveFiveAuroraInput = Readonly<{ scenario?: WaveFiveAuroraScenario; seed?: string; tenant_id?: string; principal_id?: string; session_id?: string }>;
export type WaveFiveAuroraConversation = Readonly<{ conversation_id: string; natural_language: boolean; voice_ready_architecture: boolean; structured_command_parsing: boolean; multi_turn_conversations: boolean; conversation_continuity: boolean; clarification_workflows: boolean; session_awareness: boolean; accessibility_support: boolean; conversation_service: boolean; session_manager: boolean; conversation_registry: boolean; operational: boolean; deterministic: boolean; integrity_hash: string }>;
export type WaveFiveAuroraBriefing = Readonly<{ briefing_id: string; daily_briefings: boolean; mission_summaries: boolean; task_summaries: boolean; calendar_briefings: boolean; health_summaries: boolean; financial_summaries: boolean; project_updates: boolean; research_digests: boolean; learning_progress: boolean; cross_domain_summaries: boolean; prioritization: boolean; evidence_backed_summaries: boolean; context_aware_sequencing: boolean; recommendation_generation: boolean; action_suggestions: boolean; governed_suggestions: boolean; operational: boolean; integrity_hash: string }>;
export type WaveFiveAuroraContextAssembly = Readonly<{ context_id: string; context_aggregation: boolean; cross_application_retrieval: boolean; identity_aware_context: boolean; time_context: boolean; mission_context: boolean; preference_context: boolean; permission_filtering: boolean; source_governance: boolean; context_validation: boolean; freshness_evaluation: boolean; unauthorized_context_blocked: boolean; tenant_isolation: boolean; sources: readonly string[]; deterministic: boolean; integrity_hash: string }>;
export type WaveFiveAuroraActionRouting = Readonly<{ routing_id: string; intent_resolution: boolean; questions: boolean; commands: boolean; requests: boolean; planning: boolean; analysis: boolean; summaries: boolean; search: boolean; recommendations: boolean; workflows: boolean; follow_up_conversations: boolean; service_discovery: boolean; capability_selection: boolean; request_transformation: boolean; authorization_validation: boolean; governance_enforcement: boolean; governed_application_apis_only: boolean; no_direct_business_logic: boolean; execution_monitoring: boolean; result_aggregation: boolean; failure_handling: boolean; retry_coordination: boolean; deterministic_routing: boolean; integrity_hash: string }>;
export type WaveFiveAuroraExplanation = Readonly<{ explanation_id: string; decision_explanations: boolean; evidence_references: boolean; policy_explanations: boolean; restriction_explanations: boolean; context_summaries: boolean; confidence_presentation: boolean; action_lineage: boolean; recommendation_rationale: boolean; governance_trace: boolean; human_readable_narratives: boolean; every_significant_action_explained: boolean; evidence_backed: boolean; integrity_hash: string }>;
export type WaveFiveAuroraGovernanceSecurity = Readonly<{ governance_security_id: string; constitutional_governance_enforced: boolean; mission_lifecycle_contract: boolean; policy_engine: boolean; safety_gate: boolean; evidence_services: boolean; replay_services: boolean; certification_services: boolean; cata_trust_framework: boolean; identity_validation: boolean; permissions_validation: boolean; delegated_authority_validation: boolean; tenant_boundary_validation: boolean; policy_restrictions: boolean; least_privilege: boolean; no_direct_privilege_escalation: boolean; no_unrestricted_superuser: boolean; evidence_visibility_authorized: boolean; privacy_preserved: boolean; integrity_hash: string }>;
export type WaveFiveAuroraMemoryWorkflows = Readonly<{ memory_workflow_id: string; conversation_state: boolean; active_objectives: boolean; clarification_history: boolean; referenced_entities: boolean; pending_actions: boolean; governed_by_context_policies: boolean; planning_workflows: boolean; writing_workflows: boolean; research_workflows: boolean; scheduling_workflows: boolean; review_workflows: boolean; learning_workflows: boolean; project_management_workflows: boolean; mission_execution_workflows: boolean; recommendations_advisory_only: boolean; recommendation_evidence: boolean; integrity_hash: string }>;
export type WaveFiveAuroraReadiness = Readonly<{ readiness_id: string; decision: WaveFiveAuroraDecision; phase_ready: boolean; aurora_application_ready: boolean; learning_stevn_ready: boolean; conversational_interface_operational: boolean; briefing_engine_operational: boolean; context_assembly_authorization_aware: boolean; governed_api_routing_only: boolean; every_response_explainable: boolean; evidence_attached_to_routed_actions: boolean; constitutional_governance_enforced: boolean; tenant_isolation_preserved: boolean; replay_reproduces_orchestration: boolean; orchestration_only: boolean; never_unrestricted_superuser: boolean; failures: readonly WaveFiveAuroraFailure[]; integrity_hash: string }>;
export type WaveFiveAuroraResult = Readonly<{ phase_version: "wave-five-aurora/w5.12"; phase_identifier: "WaveFiveAurora"; aurora_application_ref: "aurora/v4.15"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; principal_id: string; session_id: string; conversation: WaveFiveAuroraConversation; briefing: WaveFiveAuroraBriefing; context_assembly: WaveFiveAuroraContextAssembly; action_routing: WaveFiveAuroraActionRouting; explanation: WaveFiveAuroraExplanation; governance_security: WaveFiveAuroraGovernanceSecurity; memory_workflows: WaveFiveAuroraMemoryWorkflows; readiness: WaveFiveAuroraReadiness; replay_hash: string; integrity_hash: string }>;
export type WaveFiveAuroraValidation = Readonly<{ valid: boolean; decision: WaveFiveAuroraDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; conversation_valid: boolean; briefing_valid: boolean; context_assembly_valid: boolean; action_routing_valid: boolean; explanation_valid: boolean; governance_security_valid: boolean; memory_workflows_valid: boolean; readiness_valid: boolean; failures: readonly WaveFiveAuroraFailure[]; integrity_hash: string }>;
export type WaveFiveAuroraBundle = Readonly<{ doctrine: Readonly<{ version: "wave-five-aurora/w5.12"; aurora_remains_orchestrator: true; business_logic_delegated_to_applications: true; governed_api_routing_required: true; evidence_backed_explanations_required: true; least_privilege_required: true; unrestricted_superuser_prohibited: true; replay_required: true; qualification_gate: "W5.12 Aurora Conversational Orchestration Qualification Gate" }>; result: WaveFiveAuroraResult; validation: WaveFiveAuroraValidation }>;
