export type WaveSixOperationalMonitoringReactionDecision = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED";
export type WaveSixOperationalMonitoringReactionFailure =
  | "W6_1_OPERATIONAL_ORCHESTRATION_INVALID" | "W6_2_DEPENDENCY_COORDINATION_INVALID" | "W6_3_PERSONAL_OPERATIONAL_CONTEXT_INVALID" | "W6_4_OPERATIONAL_OPTIMIZATION_INVALID" | "W6_5_PROVIDER_CONSUMPTION_FRAMEWORK_INVALID" | "W6_6_OPERATIONAL_STATE_DISPOSITION_INVALID"
  | "OBSERVATION_SERVICE_MISSING" | "ORCHESTRATION_EVENTS_NOT_OBSERVED" | "DEPENDENCY_EVENTS_NOT_OBSERVED" | "PROVIDER_EVENTS_NOT_OBSERVED" | "LIFECYCLE_TRANSITIONS_NOT_OBSERVED" | "SCHEDULING_EVENTS_NOT_OBSERVED" | "TIMEOUT_EVENTS_NOT_OBSERVED" | "COMPLETION_EVENTS_NOT_OBSERVED" | "OBSERVATION_MUTABLE"
  | "CORRELATION_ENGINE_MISSING" | "RELATED_REQUESTS_NOT_CORRELATED" | "DEPENDENCY_FAILURES_NOT_CORRELATED" | "SCHEDULING_ACTIVITY_NOT_CORRELATED" | "PROVIDER_RESPONSES_NOT_CORRELATED" | "TIMEOUT_CHAINS_NOT_CORRELATED" | "SUPERSESSION_CHAINS_NOT_CORRELATED" | "CORRELATION_NONDETERMINISTIC"
  | "STATE_RECORDING_SERVICE_MISSING" | "STATE_HISTORY_INCOMPLETE" | "STATE_LINEAGE_MISSING" | "STATE_RECORDING_MUTABLE"
  | "DISPOSITION_RECORDING_SERVICE_MISSING" | "DISPOSITION_NOT_AUTHORITATIVE_PROVIDER" | "DISPOSITION_INVENTED" | "DISPOSITION_HISTORY_INCOMPLETE" | "DISPOSITION_RECORDING_MUTABLE"
  | "REACTION_AUTHORIZATION_ENGINE_MISSING" | "AUTHORIZING_PROVIDER_MISSING" | "AUTHORIZING_CONTRACT_MISSING" | "CONTRACT_VERSION_MISSING" | "AUTHORIZATION_RULE_MISSING" | "TRIGGERING_OBSERVATION_MISSING" | "PROVIDER_CONTRACT_NOT_VALIDATED" | "REQUEST_ELIGIBILITY_NOT_VALIDATED" | "REPLAY_CONSISTENCY_NOT_VALIDATED"
  | "REACTION_ENGINE_MISSING" | "UNAUTHORIZED_REACTION_EXECUTED" | "AUTHORIZED_REACTION_NOT_EVIDENCED" | "DEFERRED_EXECUTION_INVALID" | "OPERATOR_NOTIFICATION_INVALID" | "SUSPEND_SCHEDULING_INVALID" | "CANCEL_EXPIRED_REQUESTS_INVALID" | "SUPERSEDE_PENDING_REQUESTS_INVALID" | "AUTHORIZED_REQUEST_CREATION_INVALID"
  | "REACTION_AUDIT_SERVICE_MISSING" | "AUDIT_RECORD_MISSING" | "AUTHORIZATION_EVIDENCE_MISSING" | "REACTION_LINEAGE_MISSING" | "AUDIT_HISTORY_MUTABLE" | "AUDIT_REPLAY_DIVERGED"
  | "OPERATIONAL_DASHBOARD_MISSING" | "CORRELATION_REPORTS_MISSING" | "REACTION_REGISTRY_MISSING" | "REQUEST_TIMELINE_REPORTS_MISSING"
  | "AUTONOMOUS_DECISION_MADE" | "PROVIDER_BUSINESS_LOGIC_OWNED" | "CAF_OUTCOME_REINTERPRETED" | "TRUST_STANDING_MODIFIED" | "POLICY_MODIFIED" | "ADVISORY_AUTHORITY_EXERCISED" | "PROVIDER_CONTRACT_DEFINITION_OWNED" | "PROVIDER_RETRY_LOGIC_OWNED" | "CONSTITUTIONAL_AUTHORITY_EXERCISED"
  | "DENIED_REQUEST_RETRIED" | "PROVIDER_DECISION_MODIFIED" | "ADVISORY_DISPOSITION_ASSIGNED" | "PROVIDER_AUTHORITY_BYPASSED" | "PROVIDER_EVENT_FABRICATED" | "IMPLICIT_RETRY_GENERATED" | "UNAUTHORIZED_REQUEST_CREATED"
  | "MONITORING_REPLAY_DIVERGED" | "CORRELATION_REPLAY_DIVERGED" | "REACTION_REPLAY_DIVERGED" | "TENANT_ISOLATION_BREACH" | "OPERATIONAL_MONITORING_REACTION_QUALIFICATION_FAILED";
export type WaveSixOperationalMonitoringReactionScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | WaveSixOperationalMonitoringReactionFailure;
export type WaveSixOperationalMonitoringReactionInput = Readonly<{ scenario?: WaveSixOperationalMonitoringReactionScenario; seed?: string; tenant_id?: string; principal_id?: string; monitoring_id?: string }>;
export type WaveSixOperationalObservationCorrelation = Readonly<{ observation_correlation_id: string; continuous_monitoring: boolean; orchestration_events: boolean; dependency_events: boolean; provider_events: boolean; lifecycle_transitions: boolean; scheduling_events: boolean; timeout_events: boolean; completion_events: boolean; observation_records: boolean; observations_immutable: boolean; related_requests: boolean; dependency_failures: boolean; scheduling_activity: boolean; provider_responses: boolean; timeout_chains: boolean; supersession_chains: boolean; correlation_groups: boolean; correlation_evidence: boolean; deterministic_correlation: boolean; integrity_hash: string }>;
export type WaveSixStateDispositionRecording = Readonly<{ state_disposition_recording_id: string; request_state_changes: boolean; timestamps: boolean; originating_event: boolean; triggering_authority: boolean; causal_lineage: boolean; immutable_state_history: boolean; terminal_dispositions: boolean; completed: boolean; cancelled: boolean; failed: boolean; not_authorized: boolean; superseded: boolean; expired: boolean; authoritative_provider_origin: boolean; no_invented_dispositions: boolean; immutable_disposition_history: boolean; integrity_hash: string }>;
export type WaveSixReactionAuthorizationExecution = Readonly<{ reaction_authorization_execution_id: string; provider_contract: boolean; authorized_reaction: boolean; dependency_status: boolean; request_eligibility: boolean; replay_consistency: boolean; authorizing_provider: boolean; authorizing_contract: boolean; contract_version: boolean; authorization_rule: boolean; triggering_observation: boolean; authorized_reaction_decision: boolean; deferred_execution: boolean; operator_notification: boolean; suspend_scheduling: boolean; cancel_expired_requests: boolean; supersede_pending_requests: boolean; create_authorized_requests: boolean; reaction_evidence: boolean; unauthorized_reactions_fail_closed: boolean; integrity_hash: string }>;
export type WaveSixReactionAuditEvidenceReports = Readonly<{ audit_evidence_reports_id: string; triggering_event: boolean; authorization_evidence: boolean; executed_reaction: boolean; resulting_state: boolean; resulting_disposition: boolean; replay_identifiers: boolean; observation_reference: boolean; correlation_reference: boolean; state_before: boolean; state_after: boolean; disposition_before: boolean; disposition_after: boolean; audit_timestamp: boolean; immutable_audit_history: boolean; reaction_lineage: boolean; operational_dashboard: boolean; event_correlation_reports: boolean; reaction_audit_records: boolean; observation_registry: boolean; correlation_registry: boolean; operational_reaction_registry: boolean; monitoring_evidence: boolean; request_timeline_reports: boolean; audit_replayable: boolean; integrity_hash: string }>;
export type WaveSixMonitoringReactionBoundary = Readonly<{ boundary_id: string; provider_authority_required: boolean; deterministic_monitoring: boolean; immutable_recording: boolean; no_autonomous_operational_decisions: boolean; provider_business_logic_owned: false; caf_execution_outcomes_owned: false; trust_decisions_owned: false; policy_evaluation_owned: false; advisory_generation_owned: false; provider_contract_definitions_owned: false; provider_retry_logic_owned: false; constitutional_authority_owned: false; denied_requests_retried: false; caf_outcomes_reinterpreted: false; trust_standing_modified: false; policy_modified: false; advisory_dispositions_assigned: false; provider_authority_bypassed: false; provider_events_fabricated: false; implicit_retries_generated: false; unauthorized_requests_created: false; integrity_hash: string }>;
export type WaveSixOperationalMonitoringReactionReadiness = Readonly<{ readiness_id: string; decision: WaveSixOperationalMonitoringReactionDecision; phase_ready: boolean; w6_1_ready: boolean; w6_2_ready: boolean; w6_3_ready: boolean; w6_4_ready: boolean; w6_5_ready: boolean; w6_6_ready: boolean; continuous_monitoring_operational: boolean; event_correlation_deterministic: boolean; state_recording_immutable: boolean; disposition_recording_immutable: boolean; provider_authorized_reactions_execute: boolean; unauthorized_reactions_fail_closed: boolean; authorization_contract_validated: boolean; dashboards_authoritative: boolean; correlation_reports_lineage_accurate: boolean; audit_records_immutable_replayable: boolean; replay_identical_monitoring_behavior: boolean; provider_authorized_boundary_validated: boolean; failures: readonly WaveSixOperationalMonitoringReactionFailure[]; integrity_hash: string }>;
export type WaveSixOperationalMonitoringReactionResult = Readonly<{ phase_version: "wave-six-operational-monitoring-reaction/w6.7"; phase_identifier: "WaveSixOperationalMonitoringReaction"; operational_orchestration_ref: "wave-six-operational-orchestration/w6.1"; dependency_coordination_ref: "wave-six-dependency-service-coordination/w6.2"; personal_operational_context_ref: "wave-six-personal-operational-context/w6.3"; operational_optimization_ref: "wave-six-operational-optimization/w6.4"; provider_consumption_framework_ref: "wave-six-provider-consumption-framework/w6.5"; operational_state_disposition_ref: "wave-six-operational-state-disposition-management/w6.6"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; principal_id: string; monitoring_id: string; observation_correlation: WaveSixOperationalObservationCorrelation; state_disposition_recording: WaveSixStateDispositionRecording; reaction_authorization_execution: WaveSixReactionAuthorizationExecution; audit_evidence_reports: WaveSixReactionAuditEvidenceReports; monitoring_reaction_boundary: WaveSixMonitoringReactionBoundary; readiness: WaveSixOperationalMonitoringReactionReadiness; replay_hash: string; integrity_hash: string }>;
export type WaveSixOperationalMonitoringReactionValidation = Readonly<{ valid: boolean; decision: WaveSixOperationalMonitoringReactionDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; observation_correlation_valid: boolean; state_disposition_recording_valid: boolean; reaction_authorization_execution_valid: boolean; audit_evidence_reports_valid: boolean; monitoring_reaction_boundary_valid: boolean; readiness_valid: boolean; failures: readonly WaveSixOperationalMonitoringReactionFailure[]; integrity_hash: string }>;
export type WaveSixOperationalMonitoringReactionBundle = Readonly<{ doctrine: Readonly<{ version: "wave-six-operational-monitoring-reaction/w6.7"; provider_authority_required: true; deterministic_monitoring_required: true; immutable_recording_required: true; reaction_authorization_required: true; unauthorized_reactions_fail_closed: true; autonomous_decisions_prohibited: true; replay_identical_monitoring_required: true; qualification_gate: "W6.7 Operational Monitoring and Reaction Qualification Gate" }>; result: WaveSixOperationalMonitoringReactionResult; validation: WaveSixOperationalMonitoringReactionValidation }>;
