export type WaveFiveLearningStevnDecision = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED";
export type WaveFiveLearningStevnFailure =
  | "STEVN_APPLICATION_INVALID"
  | "LEARNING_FOUNDATION_MISSING" | "LEARNING_VOCABULARY_UNAPPROVED" | "LEARNING_LIFECYCLE_INVALID" | "LEARNING_GOVERNANCE_UNAPPROVED"
  | "LEARNING_REGISTRY_MISSING" | "LEARNING_RELATIONSHIPS_INVALID" | "LEARNING_METADATA_INCOMPLETE" | "LEARNING_REPLAY_DIVERGED"
  | "CURRICULUM_BUILDER_MISSING" | "CURRICULUM_DEPENDENCIES_INVALID" | "LEARNING_PATHS_NONDETERMINISTIC"
  | "ASSESSMENTS_MISSING" | "ASSESSMENTS_NONREPRODUCIBLE" | "COMPETENCIES_NOT_MEASURABLE" | "ASSESSMENT_EVIDENCE_INCOMPLETE"
  | "STUDY_PLANNER_MISSING" | "CALENDAR_INTEGRATION_INVALID" | "STUDY_PLANS_NONDETERMINISTIC"
  | "PROGRESS_TRACKING_MISSING" | "PROGRESS_INACCURATE" | "PROGRESS_TIMELINE_INVALID" | "PROGRESS_EVIDENCE_INCOMPLETE"
  | "KNOWLEDGE_INTEGRATION_MISSING" | "RESEARCH_SYNC_INVALID" | "LEARNING_GRAPH_INVALID"
  | "MISSION_PROJECT_LEARNING_MISSING" | "MISSION_LINKAGE_INVALID" | "COMPETENCY_MAPPING_INVALID" | "MISSION_RECOMMENDATIONS_NOT_EXPLAINABLE"
  | "STEVN_INTEGRATION_MISSING" | "STEVN_SYNC_INVALID" | "DUPLICATE_STEVN_IDENTITY_CREATED" | "DUPLICATE_LEARNER_PROFILE_CREATED" | "INDEPENDENT_CURRICULUM_SYSTEM_CREATED" | "ALTERNATIVE_LEARNING_AUTHORITY_CREATED"
  | "RECOMMENDATIONS_MISSING" | "RECOMMENDATIONS_NOT_EXPLAINABLE" | "RECOMMENDATIONS_NOT_ADVISORY" | "RECOMMENDATION_EVIDENCE_INCOMPLETE"
  | "LEARNING_ANALYTICS_MISSING" | "LEARNING_METRICS_INVALID" | "ANALYTICS_EVIDENCE_NOT_TRACEABLE"
  | "LEARNING_QUALIFICATION_MISSING" | "EVIDENCE_LINEAGE_INCOMPLETE" | "LEARNING_EVIDENCE_MUTABLE" | "TENANT_ISOLATION_BREACH"
  | "LEARNING_STEVN_QUALIFICATION_FAILED";
export type WaveFiveLearningStevnScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | WaveFiveLearningStevnFailure;
export type WaveFiveLearningStevnInput = Readonly<{ scenario?: WaveFiveLearningStevnScenario; seed?: string; tenant_id?: string; principal_id?: string; learner_profile_id?: string }>;
export type WaveFiveLearningFoundation = Readonly<{ foundation_id: string; learning_architecture: boolean; learning_vocabulary: boolean; learning_lifecycle: boolean; learning_policies: boolean; learning_apis: boolean; learning_contracts: boolean; learning_governance: boolean; learning_event_model: boolean; vocabulary_approved: boolean; architecture_complete: boolean; lifecycle_validated: boolean; governance_approved: boolean; integrity_hash: string }>;
export type WaveFiveLearningRegistryCurriculum = Readonly<{ registry_curriculum_id: string; learning_registry: boolean; course_registry: boolean; subject_registry: boolean; skill_registry: boolean; competency_registry: boolean; learning_metadata: boolean; learning_relationships: boolean; learning_classification: boolean; curriculum_builder: boolean; learning_paths: boolean; course_sequencing: boolean; prerequisites: boolean; milestones: boolean; competency_mapping: boolean; completion_rules: boolean; registry_operational: boolean; relationships_validated: boolean; metadata_complete: boolean; replay_verified: boolean; curricula_generated: boolean; dependencies_validated: boolean; learning_paths_deterministic: boolean; integrity_hash: string }>;
export type WaveFiveLearningAssessmentStudy = Readonly<{ assessment_study_id: string; assessment_registry: boolean; quiz_framework: boolean; exam_framework: boolean; practice_exercises: boolean; rubrics: boolean; competency_evaluation: boolean; assessment_evidence: boolean; feedback: boolean; study_planning: boolean; study_sessions: boolean; time_allocation: boolean; priority_planning: boolean; adaptive_scheduling: boolean; review_planning: boolean; study_calendar_integration: boolean; reminder_generation: boolean; assessments_reproducible: boolean; competencies_measurable: boolean; evidence_complete: boolean; schedules_generated: boolean; calendar_integration_validated: boolean; study_plans_deterministic: boolean; integrity_hash: string }>;
export type WaveFiveLearningProgressKnowledgeMission = Readonly<{ progress_knowledge_mission_id: string; progress_tracking: boolean; completion_tracking: boolean; competency_progress: boolean; milestone_tracking: boolean; learning_history: boolean; evidence_timeline: boolean; achievement_tracking: boolean; progress_metrics: boolean; knowledge_references: boolean; research_links: boolean; notes_integration: boolean; flashcards: boolean; knowledge_review: boolean; learning_graph: boolean; evidence_links: boolean; knowledge_synchronization: boolean; mission_learning: boolean; project_learning_plans: boolean; required_competencies: boolean; training_assignments: boolean; certification_preparation: boolean; learning_objectives: boolean; learning_recommendations: boolean; mission_readiness: boolean; progress_accurate: boolean; timeline_validated: boolean; knowledge_linked: boolean; research_synchronized: boolean; graph_validated: boolean; mission_linkage_operational: boolean; competencies_mapped: boolean; recommendations_explainable: boolean; integrity_hash: string }>;
export type WaveFiveStevnIntegration = Readonly<{ integration_id: string; stevn_application_ref: "stevn-application/v4.17"; stevn_remains_authoritative: boolean; stevn_integration_apis: boolean; learning_synchronization: boolean; curriculum_synchronization: boolean; assessment_synchronization: boolean; progress_synchronization: boolean; competency_synchronization: boolean; learning_event_integration: boolean; evidence_synchronization: boolean; no_new_stevn_identity: boolean; no_duplicate_learner_profile: boolean; no_independent_curriculum_system: boolean; no_alternative_learning_authority: boolean; evidence_preserved: boolean; replay_validated: boolean; integrity_hash: string }>;
export type WaveFiveLearningRecommendationsAnalyticsQualification = Readonly<{ qualification_id: string; learning_recommendations: boolean; study_recommendations: boolean; course_recommendations: boolean; gap_analysis: boolean; competency_suggestions: boolean; review_suggestions: boolean; readiness_evaluation: boolean; learning_forecasts: boolean; learning_dashboard: boolean; progress_analytics: boolean; completion_trends: boolean; competency_trends: boolean; study_efficiency: boolean; learning_heatmaps: boolean; time_analysis: boolean; performance_reports: boolean; learning_qualification_report: boolean; qualification_evidence: boolean; readiness_assessment: boolean; qualification_decision: boolean; recommendations_explainable: boolean; advisory_only: boolean; evidence_complete: boolean; analytics_operational: boolean; metrics_validated: boolean; evidence_traceable: boolean; evidence_lineage_complete: boolean; immutable_evidence: boolean; tenant_isolation: boolean; integrity_hash: string }>;
export type WaveFiveLearningStevnReadiness = Readonly<{ readiness_id: string; decision: WaveFiveLearningStevnDecision; phase_ready: boolean; stevn_ready: boolean; foundation_ready: boolean; registry_curriculum_ready: boolean; assessment_study_ready: boolean; progress_knowledge_mission_ready: boolean; stevn_integration_ready: boolean; recommendations_analytics_qualification_ready: boolean; learning_replay_verified: boolean; stevn_integration_operational: boolean; no_duplicate_identities_created: boolean; evidence_lineage_complete: boolean; recommendations_advisory_only: boolean; failures: readonly WaveFiveLearningStevnFailure[]; integrity_hash: string }>;
export type WaveFiveLearningStevnResult = Readonly<{ phase_version: "wave-five-learning-stevn/w5.11"; phase_identifier: "WaveFiveLearningStevn"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; principal_id: string; learner_profile_id: string; foundation: WaveFiveLearningFoundation; registry_curriculum: WaveFiveLearningRegistryCurriculum; assessment_study: WaveFiveLearningAssessmentStudy; progress_knowledge_mission: WaveFiveLearningProgressKnowledgeMission; stevn_integration: WaveFiveStevnIntegration; recommendations_analytics_qualification: WaveFiveLearningRecommendationsAnalyticsQualification; readiness: WaveFiveLearningStevnReadiness; replay_hash: string; integrity_hash: string }>;
export type WaveFiveLearningStevnValidation = Readonly<{ valid: boolean; decision: WaveFiveLearningStevnDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; foundation_valid: boolean; registry_curriculum_valid: boolean; assessment_study_valid: boolean; progress_knowledge_mission_valid: boolean; stevn_integration_valid: boolean; recommendations_analytics_qualification_valid: boolean; readiness_valid: boolean; failures: readonly WaveFiveLearningStevnFailure[]; integrity_hash: string }>;
export type WaveFiveLearningStevnBundle = Readonly<{ doctrine: Readonly<{ version: "wave-five-learning-stevn/w5.11"; stevn_remains_authoritative: true; no_duplicate_learning_identity: true; no_parallel_curriculum_authority: true; recommendations_advisory_only: true; immutable_learning_evidence_required: true; replay_required: true; qualification_gate: "W5.11 Learning and STEVN Qualification Gate" }>; result: WaveFiveLearningStevnResult; validation: WaveFiveLearningStevnValidation }>;
