export type WaveFiveCalendarTimeDecision = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED";
export type WaveFiveCalendarTimeFailure =
  | "W5_PERSONAL_KNOWLEDGE_INVALID"
  | "CALENDAR_PLATFORM_MISSING" | "CALENDAR_REGISTRY_MISSING" | "CALENDAR_IDENTITY_NONDETERMINISTIC" | "CALENDAR_PERMISSIONS_MISSING" | "CALENDAR_APIS_UNCERTIFIED"
  | "EVENT_SERVICE_MISSING" | "EVENT_LINEAGE_INCOMPLETE" | "EVENT_UPDATES_UNGOVERNED" | "RECURRING_EVENTS_UNSUPPORTED" | "EVENT_METADATA_INVALID"
  | "SCHEDULING_ENGINE_MISSING" | "SCHEDULING_NONDETERMINISTIC" | "CONSTRAINT_EVALUATION_MISSING" | "SCHEDULING_RULES_MISSING" | "RESERVATION_PROCESSING_MISSING"
  | "AVAILABILITY_MODEL_MISSING" | "AVAILABILITY_MANUALLY_INFERRED" | "TIMEZONE_HANDLING_MISSING" | "CAPACITY_WINDOWS_MISSING" | "AVAILABILITY_POLICIES_MISSING"
  | "CONFLICT_RESOLUTION_MISSING" | "CONFLICT_RESOLUTION_NONDETERMINISTIC" | "AUTHORITY_RESOLUTION_MISSING" | "POLICY_RESOLUTION_MISSING" | "ESCALATION_RULES_MISSING" | "ALTERNATIVE_SCHEDULING_MISSING"
  | "TIME_BUDGET_MISSING" | "TIME_BUDGETS_NOT_ENFORCED" | "CAPACITY_PLANNING_MISSING" | "WORKLOAD_DISTRIBUTION_MISSING" | "TIME_ACCOUNTING_INACCURATE"
  | "RESOURCE_SCHEDULING_MISSING" | "RESOURCE_RESERVATIONS_UNGOVERNED" | "RESOURCE_AVAILABILITY_MISSING" | "RESERVATION_POLICIES_MISSING"
  | "COORDINATION_SERVICE_MISSING" | "MULTI_ATTENDEE_SCHEDULING_MISSING" | "DELEGATED_SCHEDULING_UNGOVERNED" | "AGENT_COORDINATION_MISSING" | "SCHEDULE_NEGOTIATION_MISSING"
  | "CALENDAR_NOTIFICATIONS_MISSING" | "REMINDER_POLICIES_MISSING" | "NOTIFICATION_EVIDENCE_MISSING" | "ESCALATION_NOTIFICATIONS_MISSING"
  | "TIME_ANALYTICS_MISSING" | "UTILIZATION_ANALYTICS_INVALID" | "CAPACITY_ANALYSIS_MISSING" | "TIME_ALLOCATION_ANALYTICS_MISSING"
  | "SCHEDULING_EVIDENCE_MISSING" | "SCHEDULING_EVIDENCE_MUTABLE" | "REPLAY_DECISIONS_DIVERGED" | "RESERVATION_HISTORY_MISSING" | "AUDIT_LINEAGE_INCOMPLETE"
  | "GOVERNANCE_AUTHORITY_MISSING" | "AUTHORITY_BYPASS_DETECTED" | "TENANT_ISOLATION_BREACH" | "PRIVACY_CONTROLS_MISSING" | "RETENTION_POLICIES_MISSING"
  | "CALENDAR_TIME_QUALIFICATION_FAILED";
export type WaveFiveCalendarTimeScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | WaveFiveCalendarTimeFailure;
export type WaveFiveCalendarTimeInput = Readonly<{ scenario?: WaveFiveCalendarTimeScenario; seed?: string; tenant_id?: string; calendar_id?: string; principal_id?: string }>;
export type WaveFiveCalendarFoundation = Readonly<{ foundation_id: string; calendar_registry: boolean; calendar_identity: boolean; calendar_ownership: boolean; calendar_lifecycle: boolean; calendar_permissions: boolean; calendar_metadata: boolean; calendar_apis: boolean; canonical_authoritative_source: boolean; identities_deterministic: boolean; apis_certified: boolean; integrity_hash: string }>;
export type WaveFiveEventManagement = Readonly<{ event_id: string; event_creation: boolean; event_updates: boolean; event_cancellation: boolean; recurring_events: boolean; event_categories: boolean; event_priorities: boolean; event_status: boolean; event_metadata: boolean; governed_updates: boolean; lineage_complete: boolean; integrity_hash: string }>;
export type WaveFiveSchedulingEngine = Readonly<{ scheduling_id: string; intelligent_scheduling: boolean; constraint_evaluation: boolean; scheduling_rules: boolean; scheduling_optimization: boolean; priority_scheduling: boolean; reservation_processing: boolean; schedule_generation: boolean; deterministic: boolean; replayable: boolean; integrity_hash: string }>;
export type WaveFiveAvailabilityModel = Readonly<{ availability_id: string; personal_availability: boolean; agent_availability: boolean; resource_availability: boolean; organization_availability: boolean; working_hours: boolean; time_zones: boolean; capacity_windows: boolean; availability_policies: boolean; computed_not_inferred: boolean; consistent_across_subjects: boolean; integrity_hash: string }>;
export type WaveFiveConflictResolution = Readonly<{ conflict_id: string; conflict_detection: boolean; resource_conflicts: boolean; calendar_conflicts: boolean; priority_resolution: boolean; authority_based_resolution: boolean; policy_resolution: boolean; escalation_rules: boolean; alternative_scheduling: boolean; deterministic: boolean; replayable: boolean; integrity_hash: string }>;
export type WaveFiveTimeBudget = Readonly<{ budget_id: string; time_allocation: boolean; time_budgets: boolean; capacity_planning: boolean; workload_distribution: boolean; reserved_time: boolean; strategic_time: boolean; personal_time: boolean; organizational_time_accounting: boolean; budgets_enforced: boolean; accounting_accurate: boolean; integrity_hash: string }>;
export type WaveFiveResourceCoordination = Readonly<{ resource_id: string; meeting_rooms: boolean; equipment: boolean; virtual_resources: boolean; runtime_reservations: boolean; shared_assets: boolean; resource_calendars: boolean; reservation_policies: boolean; multi_attendee_scheduling: boolean; delegated_scheduling: boolean; agent_coordination: boolean; team_scheduling: boolean; cross_organization_coordination: boolean; schedule_negotiation: boolean; constitutionally_managed: boolean; integrity_hash: string }>;
export type WaveFiveCalendarNotificationsAnalytics = Readonly<{ operations_id: string; event_notifications: boolean; reminder_policies: boolean; schedule_updates: boolean; change_notifications: boolean; escalation_notifications: boolean; missed_event_alerts: boolean; calendar_utilization: boolean; meeting_analytics: boolean; capacity_analysis: boolean; schedule_efficiency: boolean; time_allocation_analytics: boolean; trend_analysis: boolean; notification_evidence: boolean; analytics_validated: boolean; integrity_hash: string }>;
export type WaveFiveSchedulingEvidenceGovernance = Readonly<{ governance_id: string; event_evidence: boolean; schedule_decisions: boolean; conflict_evidence: boolean; availability_evidence: boolean; reservation_history: boolean; replay_records: boolean; calendar_policies: boolean; scheduling_authority: boolean; permission_enforcement: boolean; privacy_controls: boolean; tenant_isolation: boolean; compliance_rules: boolean; retention_policies: boolean; immutable_evidence: boolean; audit_lineage_complete: boolean; authority_enforced: boolean; integrity_hash: string }>;
export type WaveFiveCalendarTimeReadiness = Readonly<{ readiness_id: string; decision: WaveFiveCalendarTimeDecision; phase_ready: boolean; upstream_ready: boolean; calendar_ready: boolean; events_ready: boolean; scheduling_ready: boolean; availability_ready: boolean; conflicts_ready: boolean; budgets_ready: boolean; resources_coordination_ready: boolean; notifications_analytics_ready: boolean; evidence_governance_ready: boolean; canonical_calendar_operational: boolean; deterministic_schedules: boolean; availability_validated: boolean; conflict_resolution_replayable: boolean; time_budgets_enforced: boolean; resource_reservations_governed: boolean; calendar_notifications_functioning: boolean; time_analytics_validated: boolean; scheduling_evidence_complete: boolean; replay_identical_scheduling_decisions: boolean; governance_authority_enforced: boolean; cross_tenant_isolation_validated: boolean; calendar_apis_certified: boolean; failures: readonly WaveFiveCalendarTimeFailure[]; integrity_hash: string }>;
export type WaveFiveCalendarTimeResult = Readonly<{ phase_version: "wave-five-calendar-time/w5.4"; phase_identifier: "WaveFiveCalendarTime"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; principal_id: string; calendar_id: string; calendar: WaveFiveCalendarFoundation; events: WaveFiveEventManagement; scheduling: WaveFiveSchedulingEngine; availability: WaveFiveAvailabilityModel; conflicts: WaveFiveConflictResolution; time_budget: WaveFiveTimeBudget; resources_coordination: WaveFiveResourceCoordination; notifications_analytics: WaveFiveCalendarNotificationsAnalytics; evidence_governance: WaveFiveSchedulingEvidenceGovernance; readiness: WaveFiveCalendarTimeReadiness; replay_hash: string; integrity_hash: string }>;
export type WaveFiveCalendarTimeValidation = Readonly<{ valid: boolean; decision: WaveFiveCalendarTimeDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; calendar_valid: boolean; events_valid: boolean; scheduling_valid: boolean; availability_valid: boolean; conflicts_valid: boolean; time_budget_valid: boolean; resources_coordination_valid: boolean; notifications_analytics_valid: boolean; evidence_governance_valid: boolean; readiness_valid: boolean; failures: readonly WaveFiveCalendarTimeFailure[]; integrity_hash: string }>;
export type WaveFiveCalendarTimeBundle = Readonly<{ doctrine: Readonly<{ version: "wave-five-calendar-time/w5.4"; time_is_governed_resource: true; calendar_is_authoritative_source: true; availability_is_computed: true; deterministic_conflict_resolution_required: true; immutable_scheduling_lineage_required: true; tenant_isolation_required: true; qualification_gate: "W5.4 Calendar and Time Qualification Gate" }>; result: WaveFiveCalendarTimeResult; validation: WaveFiveCalendarTimeValidation }>;
