export type WaveFiveResearchDecision = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED";
export type WaveFiveResearchFailure =
  | "W5_FINANCE_INVALID" | "W5_HEALTH_INVALID"
  | "RESEARCH_REGISTRY_MISSING" | "RESEARCH_METADATA_INVALID" | "RESEARCH_RELATIONSHIPS_INVALID" | "RESEARCH_VERSION_HISTORY_INCOMPLETE"
  | "SOURCE_GOVERNANCE_MISSING" | "SOURCES_UNCLASSIFIED" | "DUPLICATES_UNRESOLVED" | "SOURCE_GOVERNANCE_NONOPERATIONAL"
  | "EVIDENCE_COLLECTION_MISSING" | "EVIDENCE_PROVENANCE_MISSING" | "EVIDENCE_VALIDATION_INCOMPLETE" | "EVIDENCE_STORAGE_MISSING"
  | "EVIDENCE_MATRIX_MISSING" | "CLAIMS_UNMAPPED" | "SUPPORTING_EVIDENCE_UNLINKED" | "COVERAGE_NOT_MEASURABLE"
  | "CITATION_MANAGER_MISSING" | "CITATIONS_INVALID" | "BIBLIOGRAPHY_GENERATION_MISSING" | "REFERENCES_NOT_REUSABLE"
  | "RESEARCH_NOTEBOOK_MISSING" | "NOTES_NOT_VERSIONED" | "ANNOTATIONS_UNLINKED" | "NOTEBOOK_NOT_SEARCHABLE"
  | "SYNTHESIS_ENGINE_MISSING" | "SYNTHESIS_NONDETERMINISTIC" | "SYNTHESIS_NOT_EVIDENCE_BACKED" | "SYNTHESIS_CONFIDENCE_MISSING" | "UNSUPPORTED_AUTHORITATIVE_CONCLUSION"
  | "COLLABORATION_MISSING" | "REVIEWS_NOT_TRACKED" | "COLLABORATION_HISTORY_MUTABLE"
  | "SEARCH_RETRIEVAL_MISSING" | "SEARCH_NONDETERMINISTIC" | "SEARCH_RESULTS_NOT_EXPLAINABLE" | "RETRIEVAL_PERFORMANCE_INVALID"
  | "RESEARCH_GOVERNANCE_MISSING" | "POLICIES_NOT_ENFORCED" | "AUDIT_INCOMPLETE" | "COMPLIANCE_INVALID"
  | "PROVENANCE_LINEAGE_INCOMPLETE" | "REPLAY_DIVERGED" | "RESEARCH_DECISION_AUTHORITY_BYPASS" | "HEALTH_DIAGNOSIS_RESEARCH_OUTPUT" | "FINANCIAL_ACTION_RESEARCH_OUTPUT" | "TENANT_ISOLATION_BREACH"
  | "RESEARCH_QUALIFICATION_FAILED";
export type WaveFiveResearchScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | WaveFiveResearchFailure;
export type WaveFiveResearchInput = Readonly<{ scenario?: WaveFiveResearchScenario; seed?: string; tenant_id?: string; principal_id?: string; research_workspace_id?: string }>;
export type WaveFiveResearchRegistry = Readonly<{ registry_id: string; research_project_registry: boolean; research_topics: boolean; research_collections: boolean; research_categories: boolean; research_metadata: boolean; research_status: boolean; research_ownership: boolean; research_relationships: boolean; research_tags: boolean; research_versioning: boolean; operational: boolean; metadata_validated: boolean; relationships_operational: boolean; version_history_complete: boolean; integrity_hash: string }>;
export type WaveFiveResearchSourceGovernance = Readonly<{ source_id: string; source_registry: boolean; source_classification: boolean; source_trust_ratings: boolean; source_metadata: boolean; source_validation: boolean; source_freshness: boolean; source_version_tracking: boolean; duplicate_detection: boolean; sources_classified: boolean; duplicates_resolved: boolean; operational: boolean; integrity_hash: string }>;
export type WaveFiveResearchEvidence = Readonly<{ evidence_id: string; evidence_collection: boolean; evidence_normalization: boolean; evidence_metadata: boolean; evidence_provenance: boolean; evidence_validation: boolean; evidence_linking: boolean; evidence_storage: boolean; evidence_refresh: boolean; stored: boolean; provenance_preserved: boolean; validation_complete: boolean; lineage_complete: boolean; integrity_hash: string }>;
export type WaveFiveEvidenceMatrix = Readonly<{ matrix_id: string; claim_registry: boolean; supporting_evidence: boolean; contradictory_evidence: boolean; evidence_weighting: boolean; evidence_confidence: boolean; evidence_coverage: boolean; gap_analysis: boolean; evidence_relationships: boolean; claims_mapped: boolean; supporting_evidence_linked: boolean; coverage_measurable: boolean; integrity_hash: string }>;
export type WaveFiveCitationNotebook = Readonly<{ citation_notebook_id: string; citation_registry: boolean; citation_formatting: boolean; reference_library: boolean; citation_relationships: boolean; duplicate_detection: boolean; bibliography_generation: boolean; citation_validation: boolean; persistent_citation_ids: boolean; research_notes: boolean; observations: boolean; annotations: boolean; highlights: boolean; bookmarks: boolean; idea_capture: boolean; notebook_organization: boolean; notebook_versioning: boolean; cross_references: boolean; citations_validated: boolean; references_reusable: boolean; notes_versioned: boolean; annotations_linked: boolean; notebook_searchable: boolean; integrity_hash: string }>;
export type WaveFiveResearchSynthesis = Readonly<{ synthesis_id: string; finding_extraction: boolean; theme_identification: boolean; cross_source_comparison: boolean; conflict_resolution: boolean; summary_generation: boolean; research_narratives: boolean; insight_generation: boolean; confidence_scoring: boolean; recommendation_drafting: boolean; reproducible: boolean; evidence_linked: boolean; confidence_calculated: boolean; explainable: boolean; advisory_only: boolean; no_authoritative_unsupported_conclusions: boolean; no_decision_authority: boolean; no_health_diagnosis: boolean; no_financial_action: boolean; integrity_hash: string }>;
export type WaveFiveResearchCollaborationSearchGovernance = Readonly<{ governance_id: string; shared_research: boolean; review_workflow: boolean; comment_threads: boolean; research_assignments: boolean; approval_workflow: boolean; merge_support: boolean; conflict_detection: boolean; review_history: boolean; semantic_search: boolean; keyword_search: boolean; topic_search: boolean; citation_search: boolean; evidence_search: boolean; notebook_search: boolean; similarity_search: boolean; saved_searches: boolean; research_policies: boolean; evidence_requirements: boolean; citation_policies: boolean; retention_rules: boolean; access_controls: boolean; audit_trail: boolean; research_certification: boolean; compliance_monitoring: boolean; collaboration_operational: boolean; reviews_tracked: boolean; history_immutable: boolean; search_deterministic: boolean; results_explainable: boolean; policies_enforced: boolean; audit_complete: boolean; compliance_validated: boolean; tenant_isolation: boolean; integrity_hash: string }>;
export type WaveFiveResearchReadiness = Readonly<{ readiness_id: string; decision: WaveFiveResearchDecision; phase_ready: boolean; upstream_ready: boolean; registry_ready: boolean; source_governance_ready: boolean; evidence_ready: boolean; matrix_ready: boolean; citation_notebook_ready: boolean; synthesis_ready: boolean; collaboration_search_governance_ready: boolean; research_registry_operational: boolean; evidence_matrix_claims_linked: boolean; citations_validated_reusable: boolean; notebook_versioned_structured: boolean; synthesis_deterministic_evidence_backed: boolean; provenance_lineage_preserved: boolean; governance_policies_enforced: boolean; integrations_validated: boolean; conclusions_explainable: boolean; advisory_outputs_only: boolean; replay_reproducible: boolean; failures: readonly WaveFiveResearchFailure[]; integrity_hash: string }>;
export type WaveFiveResearchResult = Readonly<{ phase_version: "wave-five-research/w5.9"; phase_identifier: "WaveFiveResearch"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; principal_id: string; research_workspace_id: string; registry: WaveFiveResearchRegistry; source_governance: WaveFiveResearchSourceGovernance; evidence: WaveFiveResearchEvidence; matrix: WaveFiveEvidenceMatrix; citation_notebook: WaveFiveCitationNotebook; synthesis: WaveFiveResearchSynthesis; collaboration_search_governance: WaveFiveResearchCollaborationSearchGovernance; readiness: WaveFiveResearchReadiness; replay_hash: string; integrity_hash: string }>;
export type WaveFiveResearchValidation = Readonly<{ valid: boolean; decision: WaveFiveResearchDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; registry_valid: boolean; source_governance_valid: boolean; evidence_valid: boolean; matrix_valid: boolean; citation_notebook_valid: boolean; synthesis_valid: boolean; collaboration_search_governance_valid: boolean; readiness_valid: boolean; failures: readonly WaveFiveResearchFailure[]; integrity_hash: string }>;
export type WaveFiveResearchBundle = Readonly<{ doctrine: Readonly<{ version: "wave-five-research/w5.9"; research_is_evidence_based: true; provenance_required: true; deterministic_synthesis_required: true; research_does_not_make_decisions: true; explainability_required: true; unsupported_authority_prohibited: true; qualification_gate: "W5.9 Research Qualification Gate" }>; result: WaveFiveResearchResult; validation: WaveFiveResearchValidation }>;
