export type WaveSixProviderConsumptionFrameworkDecision = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED";
export type WaveSixProviderConsumptionFrameworkFailure =
  | "W6_1_OPERATIONAL_ORCHESTRATION_INVALID" | "W6_2_DEPENDENCY_COORDINATION_INVALID" | "W6_3_PERSONAL_OPERATIONAL_CONTEXT_INVALID" | "W6_4_OPERATIONAL_OPTIMIZATION_INVALID"
  | "PROVIDER_DISCOVERY_MISSING" | "PROVIDER_IDENTIFIER_MISSING" | "PROVIDER_METADATA_MISSING" | "CAPABILITY_OWNERSHIP_MISSING" | "PROVIDER_AVAILABILITY_MISSING" | "PROVIDER_LIFECYCLE_STATUS_MISSING"
  | "CONSUMER_CONTRACT_REGISTRY_MISSING" | "CONSUMED_CONTRACT_ENTRY_INCOMPLETE" | "CONTRACT_OWNER_MISSING" | "DEPENDENCY_CLASSIFICATION_MISSING" | "CONSUMPTION_MODE_MISSING" | "FAILURE_SEMANTICS_MISSING" | "REPLAY_REQUIREMENTS_MISSING" | "COMPATIBILITY_STATUS_MISSING"
  | "CANONICAL_CONTRACT_REFERENCE_MISSING" | "CONTRACT_REFERENCE_MUTABLE" | "PROVIDER_CONTRACT_DUPLICATED" | "PROVIDER_CONTRACT_REDEFINED" | "CONTRACT_LINEAGE_MISSING" | "DEPRECATION_TRACKING_MISSING"
  | "VERSION_REGISTRY_MISSING" | "CONTRACT_VERSION_UNAPPROVED" | "SUPPORTED_VERSIONS_MISSING" | "UPGRADE_PATH_MISSING" | "COMPATIBILITY_WINDOW_MISSING" | "VERSION_HISTORY_MISSING"
  | "COMPATIBILITY_MATRIX_MISSING" | "PROVIDER_COMPATIBILITY_FAILED" | "CONTRACT_COMPATIBILITY_FAILED" | "VERSION_COMPATIBILITY_FAILED" | "RUNTIME_COMPATIBILITY_FAILED" | "REPLAY_COMPATIBILITY_FAILED" | "BEHAVIORAL_COMPATIBILITY_FAILED" | "COMPATIBILITY_NONDETERMINISTIC"
  | "CONSUMPTION_POLICY_MISSING" | "MULTIPLE_CONSUMPTION_MODES_UNGOVERNED" | "CONSUMPTION_MODE_UNSUPPORTED" | "FAILURE_BEHAVIOR_CATALOG_MISSING" | "FAIL_OPEN_NOT_PERMITTED" | "FAILURE_BEHAVIOR_NONDETERMINISTIC"
  | "REPLAY_SPECIFICATION_MISSING" | "REPLAY_EVIDENCE_MISSING" | "EVENT_ORDERING_MISSING" | "IDEMPOTENCY_REQUIREMENTS_MISSING" | "REPLAY_VALIDATION_RULES_MISSING" | "REPLAY_DIVERGED"
  | "DEPENDENCY_METADATA_MISSING" | "CRITICALITY_MISSING" | "TIMEOUT_POLICY_MISSING" | "AUTHENTICATION_REQUIREMENTS_MISSING" | "AUTHORIZATION_REQUIREMENTS_MISSING" | "HEALTH_REQUIREMENTS_MISSING"
  | "DEPENDENCY_VALIDATION_MISSING" | "PROVIDER_NOT_FOUND" | "CONTRACT_NOT_FOUND" | "VERSION_NOT_SUPPORTED" | "COMPATIBILITY_NOT_SATISFIED" | "REPLAY_REQUIREMENTS_NOT_SATISFIED" | "FAILURE_SEMANTICS_NOT_DECLARED"
  | "CONSUMPTION_GOVERNANCE_MISSING" | "VERSION_APPROVAL_MISSING" | "COMPATIBILITY_REVIEW_MISSING" | "DEPENDENCY_APPROVAL_MISSING" | "PROVIDER_CHANGE_TRACKING_MISSING" | "BREAKING_CHANGE_NOT_DETECTED"
  | "PROVIDER_IMPLEMENTATION_OWNED" | "PROVIDER_API_OWNED" | "PROVIDER_LIFECYCLE_MANAGED" | "PROVIDER_GOVERNANCE_ASSUMED" | "PROVIDER_EXECUTION_PERFORMED" | "PROVIDER_AVAILABILITY_DECIDED" | "PROVIDER_VERSION_PUBLISHED"
  | "TENANT_ISOLATION_BREACH" | "PROVIDER_CONSUMPTION_FRAMEWORK_QUALIFICATION_FAILED";
export type WaveSixProviderConsumptionFrameworkScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | WaveSixProviderConsumptionFrameworkFailure;
export type WaveSixProviderConsumptionFrameworkInput = Readonly<{ scenario?: WaveSixProviderConsumptionFrameworkScenario; seed?: string; tenant_id?: string; principal_id?: string; framework_id?: string }>;
export type WaveSixProviderDiscoveryRegistry = Readonly<{ provider_discovery_id: string; cci_service_registry: boolean; canonical_provider_identities: boolean; provider_identifiers: boolean; provider_metadata: boolean; capability_ownership: boolean; provider_availability: boolean; provider_lifecycle_status: boolean; provider_metadata_consumed_not_owned: boolean; deterministic_discovery: boolean; integrity_hash: string }>;
export type WaveSixConsumerContractRegistry = Readonly<{ consumer_contract_registry_id: string; provider: boolean; contract_identifier: boolean; contract_owner: boolean; version: boolean; consumer: boolean; dependency_classification: boolean; consumption_mode: boolean; replay_requirements: boolean; failure_behavior: boolean; compatibility_status: boolean; authoritative_registry: boolean; deterministic_registry: boolean; integrity_hash: string }>;
export type WaveSixCanonicalVersionCompatibility = Readonly<{ canonical_version_compatibility_id: string; immutable_contract_references: boolean; contract_ids: boolean; version_references: boolean; provider_ownership: boolean; contract_lineage: boolean; deprecation_tracking: boolean; no_contract_definitions_duplicated: boolean; current_version: boolean; supported_versions: boolean; deprecated_versions: boolean; upgrade_path: boolean; compatibility_windows: boolean; version_history: boolean; provider_compatibility: boolean; contract_compatibility: boolean; version_compatibility: boolean; runtime_compatibility: boolean; replay_compatibility: boolean; behavioral_compatibility: boolean; deterministic_compatibility_matrix: boolean; integrity_hash: string }>;
export type WaveSixConsumptionPolicyFailureReplay = Readonly<{ consumption_policy_failure_replay_id: string; synchronous_mode: boolean; asynchronous_mode: boolean; event_driven_mode: boolean; streaming_mode: boolean; scheduled_mode: boolean; snapshot_based_mode: boolean; exactly_one_canonical_mode: boolean; fail_closed: boolean; fail_open_where_permitted: boolean; retry: boolean; retry_with_backoff: boolean; queue_until_available: boolean; escalate: boolean; degraded_operation: boolean; deterministic_failure_semantics: boolean; replay_eligibility: boolean; required_replay_evidence: boolean; deterministic_replay_guarantees: boolean; event_ordering: boolean; idempotency_requirements: boolean; replay_validation_rules: boolean; integrity_hash: string }>;
export type WaveSixDependencyValidationGovernance = Readonly<{ dependency_validation_governance_id: string; criticality: boolean; required_availability: boolean; optional_vs_mandatory: boolean; timeout_policy: boolean; authentication_requirements: boolean; authorization_requirements: boolean; health_requirements: boolean; startup_validation: boolean; deployment_validation: boolean; provider_exists: boolean; contract_exists: boolean; version_supported: boolean; compatibility_satisfied: boolean; replay_requirements_satisfied: boolean; failure_semantics_declared: boolean; version_approval: boolean; compatibility_review: boolean; dependency_approval: boolean; provider_change_tracking: boolean; breaking_change_detection: boolean; validation_reports: boolean; integrity_hash: string }>;
export type WaveSixProviderOwnershipBoundary = Readonly<{ boundary_id: string; consumes_provider_contracts_exactly_as_published: boolean; provider_contract_definitions_owned: false; provider_implementations_owned: false; provider_apis_owned: false; provider_lifecycle_management_owned: false; provider_governance_owned: false; provider_execution_owned: false; provider_availability_decisions_owned: false; provider_version_publishing_owned: false; no_provider_contract_redefinition: boolean; integrity_hash: string }>;
export type WaveSixProviderConsumptionFrameworkReadiness = Readonly<{ readiness_id: string; decision: WaveSixProviderConsumptionFrameworkDecision; phase_ready: boolean; w6_1_operational_orchestration_ready: boolean; w6_2_dependency_coordination_ready: boolean; w6_3_personal_operational_context_ready: boolean; w6_4_operational_optimization_ready: boolean; every_dependency_declares_provider: boolean; immutable_provider_contracts_referenced: boolean; approved_contract_versions_declared: boolean; canonical_consumption_modes_declared: boolean; deterministic_failure_semantics_declared: boolean; replay_requirements_defined: boolean; compatibility_validation_succeeds: boolean; no_provider_contracts_duplicated_or_redefined: boolean; version_governance_operational: boolean; registries_deterministic_replayable: boolean; provider_ownership_boundary_validated: boolean; failures: readonly WaveSixProviderConsumptionFrameworkFailure[]; integrity_hash: string }>;
export type WaveSixProviderConsumptionFrameworkResult = Readonly<{ phase_version: "wave-six-provider-consumption-framework/w6.5"; phase_identifier: "WaveSixProviderConsumptionFramework"; operational_orchestration_ref: "wave-six-operational-orchestration/w6.1"; dependency_coordination_ref: "wave-six-dependency-service-coordination/w6.2"; personal_operational_context_ref: "wave-six-personal-operational-context/w6.3"; operational_optimization_ref: "wave-six-operational-optimization/w6.4"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; principal_id: string; framework_id: string; provider_discovery_registry: WaveSixProviderDiscoveryRegistry; consumer_contract_registry: WaveSixConsumerContractRegistry; canonical_version_compatibility: WaveSixCanonicalVersionCompatibility; consumption_policy_failure_replay: WaveSixConsumptionPolicyFailureReplay; dependency_validation_governance: WaveSixDependencyValidationGovernance; provider_ownership_boundary: WaveSixProviderOwnershipBoundary; readiness: WaveSixProviderConsumptionFrameworkReadiness; replay_hash: string; integrity_hash: string }>;
export type WaveSixProviderConsumptionFrameworkValidation = Readonly<{ valid: boolean; decision: WaveSixProviderConsumptionFrameworkDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; provider_discovery_registry_valid: boolean; consumer_contract_registry_valid: boolean; canonical_version_compatibility_valid: boolean; consumption_policy_failure_replay_valid: boolean; dependency_validation_governance_valid: boolean; provider_ownership_boundary_valid: boolean; readiness_valid: boolean; failures: readonly WaveSixProviderConsumptionFrameworkFailure[]; integrity_hash: string }>;
export type WaveSixProviderConsumptionFrameworkBundle = Readonly<{ doctrine: Readonly<{ version: "wave-six-provider-consumption-framework/w6.5"; provider_contracts_consumed_not_redefined: true; canonical_provider_identity_required: true; immutable_contract_references_required: true; approved_version_required: true; deterministic_compatibility_required: true; explicit_failure_semantics_required: true; replay_requirements_required: true; provider_ownership_boundary_required: true; qualification_gate: "W6.5 Provider Consumption Framework Qualification Gate" }>; result: WaveSixProviderConsumptionFrameworkResult; validation: WaveSixProviderConsumptionFrameworkValidation }>;
