export type WaveSixOperationalStateDispositionDecision = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED";
export type WaveSixOperationalStateDispositionFailure =
  | "W6_1_OPERATIONAL_ORCHESTRATION_INVALID" | "W6_2_DEPENDENCY_COORDINATION_INVALID" | "W6_3_PERSONAL_OPERATIONAL_CONTEXT_INVALID" | "W6_5_PROVIDER_CONSUMPTION_FRAMEWORK_INVALID"
  | "LIFECYCLE_MANAGER_MISSING" | "REQUEST_CREATION_MISSING" | "LIFECYCLE_PROGRESSION_INVALID" | "TRANSITION_VALIDATION_MISSING" | "TERMINAL_DETECTION_MISSING" | "LIFECYCLE_COMPLETION_MISSING"
  | "STATE_REGISTRY_MISSING" | "STATE_DEFINITIONS_MISSING" | "MULTIPLE_ACTIVE_STATES" | "CURRENT_STATE_MISSING" | "STATE_VALIDATION_RULES_MISSING" | "DISPOSITION_USED_AS_RUNTIME_STATE"
  | "DISPOSITION_REGISTRY_MISSING" | "TERMINAL_DISPOSITION_MISSING" | "MULTIPLE_TERMINAL_DISPOSITIONS" | "DISPOSITION_MUTABLE" | "DISPOSITION_RECORDED_MORE_THAN_ONCE" | "DISPOSITION_EVIDENCE_MISSING"
  | "TRANSITION_MATRIX_MISSING" | "ILLEGAL_TRANSITION_ACCEPTED" | "TRANSITION_SEQUENCE_NONDETERMINISTIC" | "INVALID_TRANSITION_NOT_FAIL_CLOSED" | "DUPLICATE_TRANSITION_ACCEPTED" | "TERMINAL_STATE_NOT_ENFORCED"
  | "OPERATIONAL_LINEAGE_MISSING" | "REQUEST_IDENTIFIER_MISSING" | "WORKFLOW_IDENTIFIER_MISSING" | "ORCHESTRATION_IDENTIFIER_MISSING" | "PARENT_CHILD_RELATIONSHIP_MISSING" | "DEPENDENCY_REFERENCES_MISSING" | "EXECUTION_HISTORY_MISSING" | "TRANSITION_HISTORY_MISSING"
  | "LIFECYCLE_EVIDENCE_MISSING" | "EVIDENCE_MUTABLE" | "TIMESTAMPS_MISSING" | "ACTOR_MISSING" | "INITIATING_SERVICE_MISSING" | "LINEAGE_REFERENCES_MISSING" | "EVIDENCE_INDEX_MISSING"
  | "REPLAY_METADATA_MISSING" | "TRANSITION_REPLAY_DIVERGED" | "LINEAGE_RECONSTRUCTION_FAILED" | "STATE_REPLAY_VALIDATION_FAILED" | "REPLAY_RECORDS_MISSING"
  | "REQUEST_REGISTRY_MISSING" | "DISPOSITION_REGISTRY_INCOMPLETE" | "LIFECYCLE_REPORTS_MISSING" | "LIFECYCLE_DURATION_MISSING" | "TRANSITION_STATISTICS_MISSING" | "DISPOSITION_SUMMARIES_MISSING"
  | "WORKFLOW_SCHEDULING_OWNED" | "DEPENDENCY_COORDINATION_OWNED" | "PROVIDER_EXECUTION_OWNED" | "RECOMMENDATION_GENERATED" | "HUMAN_APPROVAL_OWNED" | "MISSION_EXECUTION_OWNED" | "TRUST_DECISION_MADE" | "CONSTITUTIONAL_POLICY_OWNED"
  | "TENANT_ISOLATION_BREACH" | "OPERATIONAL_STATE_DISPOSITION_QUALIFICATION_FAILED";
export type WaveSixOperationalStateDispositionScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | WaveSixOperationalStateDispositionFailure;
export type WaveSixOperationalStateDispositionInput = Readonly<{ scenario?: WaveSixOperationalStateDispositionScenario; seed?: string; tenant_id?: string; principal_id?: string; request_id?: string }>;
export type WaveSixRequestLifecycleManager = Readonly<{ lifecycle_manager_id: string; request_creation: boolean; lifecycle_progression: boolean; transition_validation: boolean; terminal_detection: boolean; lifecycle_completion: boolean; lifecycle_engine: boolean; transition_validator: boolean; lifecycle_coordinator: boolean; exactly_one_lifecycle: boolean; deterministic_progression: boolean; integrity_hash: string }>;
export type WaveSixRequestStateDispositionModel = Readonly<{ state_disposition_model_id: string; request_state_registry: boolean; state_definitions: readonly ["CREATED", "QUEUED", "READY", "EXECUTING", "WAITING", "TERMINAL"]; active_lifecycle_tracking: boolean; transition_validation_rules: boolean; scheduling_visibility: boolean; execution_visibility: boolean; exactly_one_current_state: boolean; terminal_state_enforced: boolean; disposition_registry: boolean; disposition_definitions: readonly ["COMPLETED", "FAILED", "CANCELLED", "REJECTED", "NOT_AUTHORIZED", "SUPERSEDED", "EXPIRED"]; exactly_one_terminal_disposition: boolean; disposition_recorded_once: boolean; disposition_immutable: boolean; dispositions_never_runtime_states: boolean; disposition_evidence: boolean; integrity_hash: string }>;
export type WaveSixTransitionLineageEvidence = Readonly<{ transition_lineage_evidence_id: string; transition_matrix: boolean; legal_transitions: boolean; illegal_transition_rejection: boolean; deterministic_sequencing: boolean; fail_closed_behavior: boolean; duplicate_transition_rejection: boolean; lifecycle_lineage: boolean; request_identifier: boolean; workflow_identifier: boolean; orchestration_identifier: boolean; parent_request: boolean; child_requests: boolean; dependency_references: boolean; execution_history: boolean; transition_history: boolean; completion: boolean; terminal_disposition: boolean; timestamps: boolean; actor: boolean; initiating_service: boolean; evidence_references: boolean; lineage_references: boolean; lifecycle_evidence_packages: boolean; evidence_index: boolean; immutable_lifecycle_history: boolean; transition_evidence: boolean; integrity_hash: string }>;
export type WaveSixLifecycleReplayReporting = Readonly<{ replay_reporting_id: string; replay_metadata: boolean; transition_replay: boolean; lineage_reconstruction: boolean; state_replay_validation: boolean; replay_records: boolean; lifecycle_replay: boolean; replay_validation_reports: boolean; request_registry: boolean; request_identities: boolean; current_state: boolean; lifecycle_metadata: boolean; ownership: boolean; scheduling_references: boolean; disposition_registry: boolean; lifecycle_reports: boolean; request_history: boolean; lifecycle_duration: boolean; state_progression: boolean; transition_statistics: boolean; disposition_summaries: boolean; lineage_visualization: boolean; deterministic_reconstruction: boolean; integrity_hash: string }>;
export type WaveSixStateDispositionBoundary = Readonly<{ boundary_id: string; owns_request_state: boolean; owns_terminal_disposition: boolean; owns_operational_lineage: boolean; owns_request_lifecycle: boolean; owns_transition_rules: boolean; owns_state_validation: boolean; owns_lifecycle_evidence: boolean; workflow_scheduling_owned: false; dependency_coordination_owned: false; personal_context_owned: false; operational_optimization_owned: false; provider_contract_definitions_owned: false; provider_execution_owned: false; recommendations_owned: false; human_approval_owned: false; mission_execution_owned: false; trust_decisions_owned: false; constitutional_policy_owned: false; independent_of_provider_execution_logic: boolean; integrity_hash: string }>;
export type WaveSixOperationalStateDispositionReadiness = Readonly<{ readiness_id: string; decision: WaveSixOperationalStateDispositionDecision; phase_ready: boolean; w6_1_operational_orchestration_ready: boolean; w6_2_dependency_coordination_ready: boolean; w6_3_personal_operational_context_ready: boolean; w6_5_provider_consumption_framework_ready: boolean; deterministic_lifecycle: boolean; exactly_one_active_state: boolean; exactly_one_immutable_terminal_disposition: boolean; transitions_validated_fail_closed: boolean; complete_operational_lineage_captured: boolean; lifecycle_evidence_immutable_replayable: boolean; deterministic_replay_reconstructs_lifecycle: boolean; request_registry_operational: boolean; disposition_registry_operational: boolean; lifecycle_reports_operational: boolean; ownership_boundary_validated: boolean; failures: readonly WaveSixOperationalStateDispositionFailure[]; integrity_hash: string }>;
export type WaveSixOperationalStateDispositionResult = Readonly<{ phase_version: "wave-six-operational-state-disposition-management/w6.6"; phase_identifier: "WaveSixOperationalStateDispositionManagement"; operational_orchestration_ref: "wave-six-operational-orchestration/w6.1"; dependency_coordination_ref: "wave-six-dependency-service-coordination/w6.2"; personal_operational_context_ref: "wave-six-personal-operational-context/w6.3"; provider_consumption_framework_ref: "wave-six-provider-consumption-framework/w6.5"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; principal_id: string; request_id: string; lifecycle_manager: WaveSixRequestLifecycleManager; state_disposition_model: WaveSixRequestStateDispositionModel; transition_lineage_evidence: WaveSixTransitionLineageEvidence; replay_reporting: WaveSixLifecycleReplayReporting; ownership_boundary: WaveSixStateDispositionBoundary; readiness: WaveSixOperationalStateDispositionReadiness; replay_hash: string; integrity_hash: string }>;
export type WaveSixOperationalStateDispositionValidation = Readonly<{ valid: boolean; decision: WaveSixOperationalStateDispositionDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; lifecycle_manager_valid: boolean; state_disposition_model_valid: boolean; transition_lineage_evidence_valid: boolean; replay_reporting_valid: boolean; ownership_boundary_valid: boolean; readiness_valid: boolean; failures: readonly WaveSixOperationalStateDispositionFailure[]; integrity_hash: string }>;
export type WaveSixOperationalStateDispositionBundle = Readonly<{ doctrine: Readonly<{ version: "wave-six-operational-state-disposition-management/w6.6"; exactly_one_lifecycle_required: true; exactly_one_current_state_required: true; exactly_one_terminal_disposition_required: true; immutable_lifecycle_history_required: true; deterministic_transition_required: true; fail_closed_invalid_transition_required: true; dispositions_never_runtime_states: true; provider_execution_independence_required: true; qualification_gate: "W6.6 Operational State and Disposition Management Qualification Gate" }>; result: WaveSixOperationalStateDispositionResult; validation: WaveSixOperationalStateDispositionValidation }>;
