export type WaveSixPersonalOperationalContextDecision = "QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED";
export type WaveSixPersonalOperationalContextFailure =
  | "W6_2_DEPENDENCY_COORDINATION_INVALID" | "W5_UNIFIED_PERSONAL_CONTEXT_INVALID"
  | "CONTEXT_MANAGER_MISSING" | "CONTEXT_ASSEMBLY_NONDETERMINISTIC" | "HIDDEN_AI_MEMORY_USED" | "CONTEXT_EXPIRATION_MISSING" | "CONTEXT_UPDATES_INVALID"
  | "GOAL_MANAGER_MISSING" | "GOAL_LIFECYCLE_INVALID" | "GOAL_PRIORITIES_NONDETERMINISTIC" | "GOAL_DEPENDENCIES_INVALID"
  | "PROJECT_MANAGER_MISSING" | "PROJECT_LIFECYCLE_INVALID" | "PROJECT_DEPENDENCIES_INVALID" | "PROJECT_MILESTONES_MISSING"
  | "ROUTINE_ENGINE_MISSING" | "ROUTINE_SCHEDULING_INVALID" | "ROUTINE_TRACKING_MISSING" | "HABIT_PROGRESS_INVALID"
  | "SCHEDULE_SERVICE_MISSING" | "CALENDAR_INTEGRATION_INVALID" | "AVAILABILITY_INVALID" | "TIME_BLOCKING_NONDETERMINISTIC"
  | "PRIORITY_ENGINE_MISSING" | "PRIORITY_RANKING_NONDETERMINISTIC" | "PRIORITY_EXPIRATION_MISSING" | "TEMPORARY_OVERRIDE_INVALID"
  | "WORKING_CONTEXT_MISSING" | "SESSION_CONTEXT_INVALID" | "RECENT_ACTIVITY_MISSING" | "WORKING_CONTEXT_EXPIRATION_MISSING"
  | "SNAPSHOT_SERVICE_MISSING" | "SNAPSHOT_MUTABLE" | "SNAPSHOT_REPLAY_DIVERGED" | "SESSION_RESTORE_DIVERGED" | "HISTORICAL_RECONSTRUCTION_FAILED"
  | "CONTEXT_HISTORY_MISSING" | "OPERATIONAL_HISTORY_OVERWRITTEN" | "CONTEXT_VERSIONING_MISSING" | "CHANGE_EVIDENCE_MISSING"
  | "CONSTITUTIONAL_POLICY_STORED" | "AUTHORITY_DECISION_MADE" | "TRUST_STANDING_MAINTAINED" | "RESTRICTION_EVALUATION_PERFORMED" | "IDENTITY_OWNERSHIP_ASSUMED" | "LONG_TERM_MEMORY_OWNERSHIP_ASSUMED" | "PCC_SEPARATION_BREACH"
  | "TENANT_ISOLATION_BREACH" | "PERSONAL_OPERATIONAL_CONTEXT_QUALIFICATION_FAILED";
export type WaveSixPersonalOperationalContextScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | WaveSixPersonalOperationalContextFailure;
export type WaveSixPersonalOperationalContextInput = Readonly<{ scenario?: WaveSixPersonalOperationalContextScenario; seed?: string; tenant_id?: string; principal_id?: string; context_id?: string }>;
export type WaveSixOperationalContextManager = Readonly<{ context_manager_id: string; runtime_context: boolean; context_assembly: boolean; context_expiration: boolean; context_updates: boolean; current_work_ref: boolean; today_plan_ref: boolean; recent_changes_ref: boolean; aurora_session_context: boolean; deterministic_assembly: boolean; no_hidden_ai_memory: boolean; mutable_operational_state: boolean; integrity_hash: string }>;
export type WaveSixGoalsProjects = Readonly<{ goals_projects_id: string; goal_registry: boolean; goal_lifecycle: boolean; goal_status: boolean; goal_priorities: boolean; goal_dependencies: boolean; goal_manager: boolean; goal_timeline: boolean; project_registry: boolean; project_status: boolean; milestones: boolean; deadlines: boolean; project_dependencies: boolean; project_dashboard: boolean; deterministic_updates: boolean; integrity_hash: string }>;
export type WaveSixRoutinesSchedulesPriorities = Readonly<{ routines_schedules_priorities_id: string; routine_registry: boolean; routine_scheduling: boolean; routine_tracking: boolean; habit_progress: boolean; routine_manager: boolean; daily_routines: boolean; weekly_routines: boolean; monthly_routines: boolean; schedule_registry: boolean; calendar_integration: boolean; availability: boolean; time_blocking: boolean; operational_schedule: boolean; priority_registry: boolean; priority_ranking: boolean; priority_expiration: boolean; temporary_overrides: boolean; active_priority_queue: boolean; deterministic_ranking: boolean; integrity_hash: string }>;
export type WaveSixWorkingContextSnapshotsHistory = Readonly<{ working_snapshot_history_id: string; working_memory: boolean; session_context: boolean; recent_activity: boolean; current_objective: boolean; focus_session: boolean; recent_decisions: boolean; working_context_store: boolean; working_context_expiration: boolean; context_snapshot_service: boolean; immutable_snapshots: boolean; replay_support: boolean; session_recovery: boolean; historical_reconstruction: boolean; context_history: boolean; previous_state: boolean; new_state: boolean; change_type: boolean; timestamps: boolean; source: boolean; change_evidence: boolean; versioning: boolean; no_overwrite_history: boolean; integrity_hash: string }>;
export type WaveSixOperationalConstitutionalBoundary = Readonly<{ boundary_id: string; owns_active_goals: boolean; owns_active_projects: boolean; owns_personal_routines: boolean; owns_schedules: boolean; owns_temporary_priorities: boolean; owns_working_context: boolean; owns_constitutional_policy: false; owns_authority: false; owns_standing: false; owns_restrictions: false; owns_identity: false; owns_long_term_memory: false; pcc_separation_verified: boolean; operational_not_constitutional: boolean; integrity_hash: string }>;
export type WaveSixPersonalOperationalContextReadiness = Readonly<{ readiness_id: string; decision: WaveSixPersonalOperationalContextDecision; phase_ready: boolean; dependency_coordination_ready: boolean; unified_personal_context_ready: boolean; authoritative_mutable_runtime_context: boolean; goals_projects_routines_schedules_priorities_managed: boolean; working_context_operational: boolean; snapshots_replayable: boolean; complete_history_preserved: boolean; no_constitutional_policy_stored: boolean; no_authority_decisions_made: boolean; no_trust_standing_maintained: boolean; no_restriction_evaluation_performed: boolean; pcc_separation_validated: boolean; replay_identical_runtime_state: boolean; failures: readonly WaveSixPersonalOperationalContextFailure[]; integrity_hash: string }>;
export type WaveSixPersonalOperationalContextResult = Readonly<{ phase_version: "wave-six-personal-operational-context/w6.3"; phase_identifier: "WaveSixPersonalOperationalContext"; dependency_coordination_ref: "wave-six-dependency-service-coordination/w6.2"; unified_personal_context_ref: "wave-five-unified-personal-context/w5.2"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; principal_id: string; context_id: string; context_manager: WaveSixOperationalContextManager; goals_projects: WaveSixGoalsProjects; routines_schedules_priorities: WaveSixRoutinesSchedulesPriorities; working_snapshot_history: WaveSixWorkingContextSnapshotsHistory; constitutional_boundary: WaveSixOperationalConstitutionalBoundary; readiness: WaveSixPersonalOperationalContextReadiness; replay_hash: string; integrity_hash: string }>;
export type WaveSixPersonalOperationalContextValidation = Readonly<{ valid: boolean; decision: WaveSixPersonalOperationalContextDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; context_manager_valid: boolean; goals_projects_valid: boolean; routines_schedules_priorities_valid: boolean; working_snapshot_history_valid: boolean; constitutional_boundary_valid: boolean; readiness_valid: boolean; failures: readonly WaveSixPersonalOperationalContextFailure[]; integrity_hash: string }>;
export type WaveSixPersonalOperationalContextBundle = Readonly<{ doctrine: Readonly<{ version: "wave-six-personal-operational-context/w6.3"; operational_not_constitutional: true; mutable_runtime_context_authoritative: true; deterministic_context_assembly_required: true; hidden_ai_memory_prohibited: true; immutable_snapshots_required: true; complete_history_required: true; pcc_boundary_required: true; qualification_gate: "W6.3 Personal Operational Context Qualification Gate" }>; result: WaveSixPersonalOperationalContextResult; validation: WaveSixPersonalOperationalContextValidation }>;
