export type WaveFiveApplicationLifecycleState = "PROPOSED" | "PLANNED" | "DEVELOPMENT" | "VALIDATION" | "CERTIFIED" | "OPERATIONAL" | "SUSPENDED" | "RETIRED" | "ARCHIVED";
export type WaveFiveCertificationDimension = "CONSTITUTIONAL_COMPLIANCE" | "ARCHITECTURE_COMPLIANCE" | "SECURITY" | "GOVERNANCE" | "TRUST" | "OPERATIONAL_READINESS" | "REPLAY_SUPPORT" | "EVIDENCE_INTEGRITY";
export type WaveFiveApplicationFoundationDecision = "WAVE_FIVE_FOUNDATION_QUALIFIED" | "CONDITIONALLY_QUALIFIED" | "NOT_QUALIFIED" | "FAIL_CLOSED";
export type WaveFiveApplicationFoundationFailure =
  | "CATA_PROGRAM_QUALIFICATION_INVALID" | "PROGRAM_4_APPLICATION_FOUNDATION_INVALID" | "PROGRAM_4_PORTFOLIO_GOVERNANCE_INVALID"
  | "APPLICATION_CONSTITUTION_MISSING" | "CONSTITUTIONAL_PRINCIPLES_MISSING" | "APPLICATION_INVARIANTS_MISSING" | "CONSTITUTIONAL_CONSTRAINTS_MISSING" | "CONSTITUTIONAL_RESPONSIBILITIES_MISSING" | "GOVERNANCE_PRINCIPLES_MISSING" | "SEPARATION_OF_RESPONSIBILITIES_MISSING" | "COMPLIANCE_REQUIREMENTS_MISSING"
  | "PORTFOLIO_REGISTRY_MISSING" | "APPLICATION_CATALOG_MISSING" | "PORTFOLIO_CLASSIFICATION_MISSING" | "PORTFOLIO_METADATA_MISSING" | "PORTFOLIO_RELATIONSHIPS_MISSING" | "PORTFOLIO_DISCOVERY_MISSING" | "PORTFOLIO_SEARCH_MISSING" | "PORTFOLIO_GOVERNANCE_MISSING"
  | "PRODUCT_OWNERSHIP_MISSING" | "TECHNICAL_OWNERSHIP_MISSING" | "GOVERNANCE_OWNERSHIP_MISSING" | "OPERATIONAL_OWNERSHIP_MISSING" | "STEWARDSHIP_MODEL_MISSING" | "AUTHORITY_ASSIGNMENTS_MISSING" | "OWNERSHIP_POLICIES_MISSING" | "OWNERSHIP_TRANSFERS_MISSING"
  | "DEPENDENCY_REGISTRY_MISSING" | "DEPENDENCY_GRAPH_MISSING" | "SERVICE_DEPENDENCIES_MISSING" | "PLATFORM_DEPENDENCIES_MISSING" | "CROSS_APPLICATION_DEPENDENCIES_MISSING" | "EXTERNAL_DEPENDENCIES_MISSING" | "DEPENDENCY_VALIDATION_MISSING" | "DEPENDENCY_GOVERNANCE_MISSING"
  | "APPLICATION_LIFECYCLE_MISSING" | "DEVELOPMENT_LIFECYCLE_MISSING" | "DEPLOYMENT_LIFECYCLE_MISSING" | "OPERATIONAL_LIFECYCLE_MISSING" | "RETIREMENT_LIFECYCLE_MISSING" | "SUSPENSION_WORKFLOW_MISSING" | "RECOVERY_WORKFLOW_MISSING" | "VERSION_LIFECYCLE_MISSING"
  | "CERTIFICATION_CATEGORIES_MISSING" | "CERTIFICATION_LEVELS_MISSING" | "CERTIFICATION_REQUIREMENTS_MISSING" | "CERTIFICATION_EVIDENCE_MISSING" | "CERTIFICATION_POLICIES_MISSING" | "CERTIFICATION_LIFECYCLE_MISSING" | "CERTIFICATION_GOVERNANCE_MISSING" | "CERTIFICATION_REFERENCES_MISSING"
  | "GOVERNANCE_ROLES_MISSING" | "GOVERNANCE_RESPONSIBILITIES_MISSING" | "GOVERNANCE_REVIEWS_MISSING" | "APPROVAL_AUTHORITIES_MISSING" | "GOVERNANCE_ESCALATIONS_MISSING" | "GOVERNANCE_EVIDENCE_MISSING" | "GOVERNANCE_REPORTING_MISSING" | "GOVERNANCE_METRICS_MISSING"
  | "CCI_INTEGRATION_CONTRACTS_MISSING" | "CAF_INTEGRATION_CONTRACTS_MISSING" | "CATA_INTEGRATION_CONTRACTS_MISSING" | "SERVICE_BOUNDARY_SPECIFICATIONS_MISSING" | "CROSS_PROGRAM_CONTRACT_VALIDATION_MISSING"
  | "APPLICATION_CONSTITUTION_UNAPPROVED" | "PORTFOLIO_GOVERNANCE_NONDETERMINISTIC" | "SERVICE_BOUNDARIES_UNAPPROVED" | "CONSTITUTIONAL_COMPLIANCE_FRAMEWORK_NOT_ADOPTED" | "APPLICATION_FUNCTIONALITY_IMPLEMENTED" | "AUTHORITY_OVERRIDE_ATTEMPTED" | "TENANT_ISOLATION_WEAKENED" | "EVIDENCE_MUTABLE" | "WAVE_FIVE_FOUNDATION_QUALIFICATION_FAILED";
export type WaveFiveApplicationFoundationScenario = "QUALIFIED_WITH_OBSERVATIONS" | "CONDITIONAL_FOLLOWUP" | WaveFiveApplicationFoundationFailure;
export type WaveFiveApplicationFoundationInput = Readonly<{ scenario?: WaveFiveApplicationFoundationScenario; seed?: string; tenant_id?: string; portfolio_id?: string }>;
export type WaveFiveApplicationConstitution = Readonly<{ constitution_id: string; application_constitution: boolean; constitutional_principles: boolean; application_invariants: boolean; constitutional_constraints: boolean; constitutional_responsibilities: boolean; governance_principles: boolean; separation_of_responsibilities: boolean; compliance_requirements: boolean; approved: boolean; implements_application_functionality: false; integrity_hash: string }>;
export type WaveFivePortfolioRegistry = Readonly<{ registry_id: string; portfolio_registry: boolean; application_catalog: boolean; portfolio_classification: boolean; portfolio_metadata: boolean; portfolio_relationships: boolean; portfolio_discovery: boolean; portfolio_search: boolean; portfolio_governance: boolean; deterministic: boolean; integrity_hash: string }>;
export type WaveFiveOwnershipModel = Readonly<{ ownership_id: string; product_ownership: boolean; technical_ownership: boolean; governance_ownership: boolean; operational_ownership: boolean; stewardship_model: boolean; authority_assignments: boolean; ownership_policies: boolean; ownership_transfers: boolean; responsibilities_assigned: boolean; integrity_hash: string }>;
export type WaveFiveDependencyRegistry = Readonly<{ dependency_id: string; dependency_registry: boolean; dependency_graph: boolean; service_dependencies: boolean; platform_dependencies: boolean; cross_application_dependencies: boolean; external_dependencies: boolean; dependency_validation: boolean; dependency_governance: boolean; deterministic: boolean; integrity_hash: string }>;
export type WaveFiveLifecycleModel = Readonly<{ lifecycle_id: string; states: readonly WaveFiveApplicationLifecycleState[]; application_lifecycle: boolean; development_lifecycle: boolean; deployment_lifecycle: boolean; operational_lifecycle: boolean; retirement_lifecycle: boolean; suspension_workflow: boolean; recovery_workflow: boolean; version_lifecycle: boolean; state_machine_finalized: boolean; integrity_hash: string }>;
export type WaveFiveCertificationModel = Readonly<{ certification_id: string; dimensions: readonly WaveFiveCertificationDimension[]; certification_categories: boolean; certification_levels: boolean; certification_requirements: boolean; certification_evidence: boolean; certification_policies: boolean; certification_lifecycle: boolean; certification_governance: boolean; certification_references: boolean; approved: boolean; integrity_hash: string }>;
export type WaveFiveGovernanceModel = Readonly<{ governance_id: string; governance_roles: boolean; governance_responsibilities: boolean; governance_reviews: boolean; approval_authorities: boolean; governance_escalations: boolean; governance_evidence: boolean; governance_reporting: boolean; governance_metrics: boolean; established: boolean; integrity_hash: string }>;
export type WaveFiveIntegrationContracts = Readonly<{ integration_id: string; cci_identity_registry_messaging_evidence_replay: boolean; caf_agent_capability_planning_runtime_memory: boolean; cata_trust_compliance_evidence_oversight_certification: boolean; dependency_contracts: boolean; service_boundary_specifications: boolean; cross_program_contract_validation: boolean; boundaries_approved: boolean; integrity_hash: string }>;
export type WaveFiveApplicationFoundationEvidence = Readonly<{ evidence_id: string; constitutional_specification: boolean; rule_set: boolean; invariant_registry: boolean; portfolio_registry_evidence: boolean; ownership_evidence: boolean; dependency_evidence: boolean; lifecycle_evidence: boolean; certification_evidence: boolean; governance_evidence: boolean; integration_evidence: boolean; immutable: boolean; replayable: boolean; integrity_hash: string }>;
export type WaveFiveApplicationFoundationReadiness = Readonly<{ readiness_id: string; decision: WaveFiveApplicationFoundationDecision; phase_ready: boolean; upstream_ready: boolean; constitution_ready: boolean; portfolio_ready: boolean; ownership_ready: boolean; dependency_ready: boolean; lifecycle_ready: boolean; certification_ready: boolean; governance_ready: boolean; integrations_ready: boolean; evidence_ready: boolean; portfolio_governance_deterministic: boolean; constitutional_compliance_adopted: boolean; service_boundaries_approved: boolean; tenant_isolation_preserved: boolean; no_authority_override: boolean; foundation_ready_for_implementations: boolean; failures: readonly WaveFiveApplicationFoundationFailure[]; integrity_hash: string }>;
export type WaveFiveApplicationFoundationResult = Readonly<{ phase_version: "wave-five-application-portfolio-foundation/w5.0"; phase_identifier: "WaveFiveApplicationPortfolioFoundation"; upstream_refs: readonly string[]; provides: readonly string[]; tenant_id: string; portfolio_id: string; constitution: WaveFiveApplicationConstitution; portfolio: WaveFivePortfolioRegistry; ownership: WaveFiveOwnershipModel; dependencies: WaveFiveDependencyRegistry; lifecycle: WaveFiveLifecycleModel; certification: WaveFiveCertificationModel; governance: WaveFiveGovernanceModel; integrations: WaveFiveIntegrationContracts; evidence: WaveFiveApplicationFoundationEvidence; readiness: WaveFiveApplicationFoundationReadiness; replay_hash: string; integrity_hash: string }>;
export type WaveFiveApplicationFoundationValidation = Readonly<{ valid: boolean; decision: WaveFiveApplicationFoundationDecision; replay_hash_valid: boolean; integrity_hash_valid: boolean; constitution_valid: boolean; portfolio_valid: boolean; ownership_valid: boolean; dependency_valid: boolean; lifecycle_valid: boolean; certification_valid: boolean; governance_valid: boolean; integrations_valid: boolean; evidence_valid: boolean; readiness_valid: boolean; failures: readonly WaveFiveApplicationFoundationFailure[]; integrity_hash: string }>;
export type WaveFiveApplicationFoundationBundle = Readonly<{ doctrine: Readonly<{ version: "wave-five-application-portfolio-foundation/w5.0"; constitutional_authority_for_wave_five: true; portfolio_governance_is_constitutional: true; application_functionality_prohibited: true; deterministic_portfolio_governance_required: true; cross_program_contracts_required: true; tenant_isolation_required: true; qualification_gate: "W5.0 Application Constitution and Portfolio Foundation Gate" }>; result: WaveFiveApplicationFoundationResult; validation: WaveFiveApplicationFoundationValidation }>;
