export type CoordinationBoundaryErrorCode =
  | "COORDINATION_BOUNDARY_EXECUTION_SEMANTICS"
  | "COORDINATION_BOUNDARY_RECURSIVE_ORCHESTRATION"
  | "COORDINATION_BOUNDARY_HIDDEN_SCHEDULING"
  | "COORDINATION_BOUNDARY_AUTHORITY_EXPANSION"
  | "COORDINATION_BOUNDARY_REPLAY_LINEAGE_BREAK"
  | "COORDINATION_BOUNDARY_GOVERNANCE_LINKAGE_MISSING"
  | "COORDINATION_BOUNDARY_ORCHESTRATION_DRIFT"
  | "COORDINATION_BOUNDARY_CONTAINMENT_BYPASS"
  | "COORDINATION_BOUNDARY_REPLAY_AMBIGUITY"
  | "COORDINATION_BOUNDARY_CHRONOLOGY_MUTATION"
  | "COORDINATION_BOUNDARY_ROUTING_RESTORATION"
  | "COORDINATION_BOUNDARY_TOPOLOGY_SYNTHESIS"
  | "COORDINATION_BOUNDARY_FAIL_CLOSED";

export type CoordinationBoundaryError = Readonly<{
  code: CoordinationBoundaryErrorCode;
  message: string;
  path?: string;
}>;
