export type ReadinessErrorCode =
  | "CONSTITUTIONAL_READINESS_REPLAY_DIVERGENCE"
  | "CONSTITUTIONAL_READINESS_REPLAY_INTEGRITY_FAILURE"
  | "CONSTITUTIONAL_READINESS_GOVERNANCE_DEGRADED"
  | "CONSTITUTIONAL_READINESS_GOVERNANCE_SUPREMACY_FAILURE"
  | "CONSTITUTIONAL_READINESS_APPROVAL_NONDETERMINISM"
  | "CONSTITUTIONAL_READINESS_APPROVAL_BOUNDARY_FAILURE"
  | "CONSTITUTIONAL_READINESS_ESCALATION_UNSTABLE"
  | "CONSTITUTIONAL_READINESS_ESCALATION_SUPPRESSION"
  | "CONSTITUTIONAL_READINESS_RECOMMENDATION_INTEGRITY_FAILURE"
  | "CONSTITUTIONAL_READINESS_RECOMMENDATION_ADVISORY_DRIFT"
  | "CONSTITUTIONAL_READINESS_DRIFT_RESISTANCE_DEGRADED"
  | "CONSTITUTIONAL_READINESS_DRIFT_INTEGRITY_FAILURE"
  | "CONSTITUTIONAL_READINESS_CONTAINMENT_PRESSURE_ELEVATED"
  | "CONSTITUTIONAL_READINESS_ANTI_EMERGENCE_FAILURE"
  | "CONSTITUTIONAL_READINESS_BOUNDARY_VIOLATION"
  | "CONSTITUTIONAL_READINESS_RECURSIVE_COORDINATION"
  | "CONSTITUTIONAL_READINESS_ISOLATION_VIOLATION"
  | "CONSTITUTIONAL_READINESS_PRIVILEGE_ESCALATION"
  | "CONSTITUTIONAL_READINESS_CONTAINMENT_DEGRADED"
  | "CONSTITUTIONAL_READINESS_CONTAINMENT_FREEZE_REQUIRED";

export type ReadinessError = Readonly<{
  code: ReadinessErrorCode;
  message: string;
  path: string;
}>;
