repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      - id: d2d-lint
        name: Day-to-Day Assistant lint
        entry: pwsh ./scripts/test/lint.ps1
        language: system
        pass_filenames: false
      - id: d2d-fast-tests
        name: Day-to-Day Assistant fast tests
        entry: pwsh ./scripts/test/test.ps1
        language: system
        pass_filenames: false
