import type { SamError, SamPipelineStage } from "./samTypes";

export const SAM_ERROR_CODES = {
  SAM_DISABLED: "SAM_DISABLED",
  SAM_PROPOSAL_INVALID: "SAM_PROPOSAL_INVALID",
  SAM_ACTION_UNKNOWN: "SAM_ACTION_UNKNOWN",
  SAM_PREFLIGHT_FAILED: "SAM_PREFLIGHT_FAILED",
  SAM_READ_MODEL_UNAVAILABLE: "SAM_READ_MODEL_UNAVAILABLE",
  SAM_OPERATOR_ACTION_BLOCKED: "SAM_OPERATOR_ACTION_BLOCKED",
  SAM_EVIDENCE_INVALID: "SAM_EVIDENCE_INVALID",
  SAM_TIMELINE_DISPUTED: "SAM_TIMELINE_DISPUTED",
  SAM_LOCK_INVALID: "SAM_LOCK_INVALID",
  SAM_APPROVAL_REQUIRED: "SAM_APPROVAL_REQUIRED",
  SAM_APPROVAL_DENIED: "SAM_APPROVAL_DENIED",
  SAM_REAL_EXECUTION_FORBIDDEN: "SAM_REAL_EXECUTION_FORBIDDEN",
  SAM_AUDIT_SKIPPED: "SAM_AUDIT_SKIPPED",
  SAM_ADAPTER_FAILED: "SAM_ADAPTER_FAILED",
  SAM_IDEMPOTENCY_INPUT_INVALID: "SAM_IDEMPOTENCY_INPUT_INVALID",
  SAM_IDEMPOTENCY_CONFLICT: "SAM_IDEMPOTENCY_CONFLICT",
  SAM_IDEMPOTENCY_AMBIGUOUS: "SAM_IDEMPOTENCY_AMBIGUOUS",
  SAM_UNSAFE_RETRY: "SAM_UNSAFE_RETRY",
  SAM_DUPLICATE_AUDIT_SUPPRESSED: "SAM_DUPLICATE_AUDIT_SUPPRESSED",
} as const;

export function createSamError(
  code: string,
  message: string,
  stage: SamPipelineStage,
  recoverable = false,
): SamError {
  return {
    code,
    message,
    stage,
    recoverable,
  };
}
