export const SAM_IDEMPOTENCY_ERROR_CODES = {
  SAM_IDEMPOTENCY_INPUT_INVALID: "SAM_IDEMPOTENCY_INPUT_INVALID",
  SAM_IDEMPOTENCY_CONFLICT: "SAM_IDEMPOTENCY_CONFLICT",
  SAM_IDEMPOTENCY_AMBIGUOUS: "SAM_IDEMPOTENCY_AMBIGUOUS",
  SAM_UNSAFE_RETRY: "SAM_UNSAFE_RETRY",
  SAM_DUPLICATE_AUDIT_SUPPRESSED: "SAM_DUPLICATE_AUDIT_SUPPRESSED",
} as const;
