import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runTrustDriftDetection, validateTrustDriftDetection } from "@/services/trust-drift-detection";
import type { RestorationDecision, TrustRecoveryBundle, TrustRecoveryFailure, TrustRecoveryInput, TrustRecoveryOutcome, TrustRecoveryResult, TrustRecoveryScenario, TrustRecoveryValidation } from "@/types/trust-recovery-revocation";

const VERSION = "trust-recovery-revocation/v5.15" as const;
const IDENTIFIER = "TrustRecoveryRevocation" as const;
let driftBaseline: ReturnType<typeof runTrustDriftDetection> | undefined;
function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly TrustRecoveryFailure[], failure: TrustRecoveryFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustRecoveryScenario): TrustRecoveryFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function outcome(failures: readonly TrustRecoveryFailure[]): TrustRecoveryOutcome { return has(failures, "GOVERNANCE_REVIEW_REQUIRED") ? "REQUIRES_GOVERNANCE_REVIEW" : failures.length ? "FAIL" : "PASS"; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function resultReplayHash(result: Omit<TrustRecoveryResult, "replay_hash" | "integrity_hash">): string { return hash({ framework: result.framework.integrity_hash, suspension: result.suspension.integrity_hash, revocation: result.revocation.integrity_hash, plan: result.plan.integrity_hash, evidence: result.evidence.integrity_hash, requalification: result.requalification.integrity_hash, approval: result.approval.integrity_hash, decision: result.decision.integrity_hash, observability: result.observability.integrity_hash, audit: result.audit.integrity_hash, certification: result.certification.integrity_hash }); }
function resultIntegrityHash(result: Omit<TrustRecoveryResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.certification.outcome, replay_hash: result.replay_hash }); }

export function runTrustRecoveryRevocation(input: TrustRecoveryInput = {}): TrustRecoveryResult {
  const direct = scenarioFailure(input.scenario ?? "BASELINE");
  const scenarioFailures = freezeArray<TrustRecoveryFailure>(direct ? [direct] : []);
  driftBaseline ??= runTrustDriftDetection();
  const dependencyFailures = freezeArray<TrustRecoveryFailure>(!validateTrustDriftDetection(driftBaseline).valid || has(scenarioFailures, "P5_14_DRIFT_DETECTION_INVALID") ? ["P5_14_DRIFT_DETECTION_INVALID"] : []);
  const failures = freezeArray([...new Set([...scenarioFailures, ...dependencyFailures])]);
  const trustId = input.trust_id ?? "trust-domain:civitas:root";
  const framework = nested({ framework_id: "framework:recovery-revocation:p5.15", recovery_lifecycle: !has(failures, "RECOVERY_FRAMEWORK_MISSING"), restoration_lifecycle: !has(failures, "RECOVERY_FRAMEWORK_MISSING"), suspension_model: !has(failures, "SUSPENSION_MANAGEMENT_MISSING"), revocation_model: !has(failures, "REVOCATION_MANAGEMENT_MISSING"), expiration_model: !has(failures, "RECOVERY_FRAMEWORK_MISSING"), recovery_contracts: !has(failures, "RECOVERY_FRAMEWORK_MISSING") });
  const baseEvidence = freezeArray(["constitutional:remediation:p5.15", "governance:approval:p5.12", "safety:validation:p5.10", "operational:remediation", "trust:evaluation-package", "alignment:verification:p5.8", "monitoring:report:p5.13", driftBaseline.report.report_id, "audit:recovery:p5.15"]);
  const badEvidence = has(failures, "RECOVERY_EVIDENCE_MISSING") || has(failures, "RECOVERY_EVIDENCE_STALE") || has(failures, "RECOVERY_EVIDENCE_CONFLICTING") || has(failures, "RECOVERY_EVIDENCE_UNVERIFIABLE");
  const evidenceRefs = badEvidence ? freezeArray<string>([]) : baseEvidence;
  const newEvidenceRefs = has(failures, "HISTORIC_EVIDENCE_ONLY") || has(failures, "NEW_EVIDENCE_MISSING") ? freezeArray<string>([]) : freezeArray(["new:constitutional-remediation", "new:safety-validation", "new:drift-resolution"]);
  const suspension = nested({ suspension_id: has(failures, "SUSPENSION_RECORD_MISSING") ? "" : "suspension:p5.15", trust_id: trustId, reason: "drift and governance remediation required", authority: "governance:safety:constitutional", evidence_refs: evidenceRefs, scope: "trust-standing", standing: "SUSPENDED" as const });
  const revocation = nested({ revocation_id: has(failures, "REVOCATION_RECORD_MISSING") ? "" : "revocation:p5.15", trust_id: trustId, authority: "governance:revocation-authority", permanent_removal: true, remediation_tracking: freezeArray(["control-remediation", "evidence-renewal", "full-requalification"]), lineage_refs: evidenceRefs.map((ref) => `lineage:${ref}`), standing: "REVOKED" as const });
  const plan = nested({ plan_id: has(failures, "RECOVERY_PLAN_MISSING") ? "" : "recovery-plan:p5.15", failed_controls: freezeArray(["confidence-drift", "evidence-quality", "governance-review"]), required_remediation: has(failures, "REMEDIATION_INCOMPLETE") ? freezeArray(["incomplete-remediation"]) : freezeArray(["complete-remediation"]), missing_evidence: badEvidence ? freezeArray(["restoration-evidence"]) : freezeArray<string>([]), governance_approvals: freezeArray(["operator-review", "governance-board"]), safety_requirements: freezeArray(["safety-validation", "safety-supremacy-check"]), verification_activities: freezeArray(["deterministic-replay", "alignment-verification", "policy-compliance"]), requalification_requirements: freezeArray(["p5.7", "p5.8", "p5.9", "p5.10"]), deterministic: !has(failures, "RECOVERY_REPLAY_FAILED") });
  const evidence = nested({ package_id: "restoration-evidence:p5.15", evidence_refs: evidenceRefs, new_evidence_refs: newEvidenceRefs, constitutional: !has(failures, "CONSTITUTIONAL_VIOLATION_UNRESOLVED"), governance: !has(failures, "GOVERNANCE_APPROVAL_ABSENT"), safety: !has(failures, "SAFETY_APPROVAL_ABSENT"), operational: true, trust: true, alignment: !has(failures, "DRIFT_UNRESOLVED"), monitoring: true, drift_resolution: !has(failures, "DRIFT_UNRESOLVED"), audit: !has(failures, "IMMUTABLE_AUDIT_MISSING"), verifiable: !badEvidence });
  const requalification = nested({ request_id: has(failures, "REQUALIFICATION_REQUEST_MISSING") ? "" : "requalification-request:p5.15", recovery_plan_ref: plan.plan_id, restoration_evidence_ref: evidence.package_id, trust_evaluation_required: true, alignment_verification_required: true, compliance_verification_required: true, safety_qualification_required: true, package_complete: plan.plan_id.length > 0 && evidence.verifiable && newEvidenceRefs.length > 0 });
  const approval = nested({ approval_id: "restoration-approval:p5.15", operator_review: !has(failures, "GOVERNANCE_APPROVAL_ABSENT"), governance_approval: !has(failures, "GOVERNANCE_APPROVAL_ABSENT"), constitutional_validation: evidence.constitutional, safety_validation: evidence.safety, automatic_restoration: has(failures, "TRUST_SELF_RESTORED") });
  const decisionValue: RestorationDecision = has(failures, "UNKNOWN_NOT_FAIL_CLOSED") || has(failures, "UNKNOWN_PERSISTED") ? "RESTORE" : badEvidence || has(failures, "NEW_EVIDENCE_MISSING") || has(failures, "HISTORIC_EVIDENCE_ONLY") ? "FAIL_CLOSED" : has(failures, "GOVERNANCE_APPROVAL_ABSENT") ? "REQUIRE_GOVERNANCE_REVIEW" : has(failures, "SAFETY_APPROVAL_ABSENT") ? "REQUIRE_SAFETY_REVIEW" : has(failures, "CONSTITUTIONAL_VIOLATION_UNRESOLVED") ? "DENY" : has(failures, "DRIFT_UNRESOLVED") ? "REQUIRE_REQUALIFICATION" : "RESTORE";
  const decision = nested({ decision_id: has(failures, "RESTORATION_DECISION_MISSING") ? "" : "restoration-decision:p5.15", decision: decisionValue, rationale: "Restoration requires new evidence, governance approval, safety validation, replay, audit lineage, and requalification package.", deterministic: !has(failures, "RECOVERY_REPLAY_FAILED"), explainable: true, reproducible: !has(failures, "RECOVERY_REPLAY_FAILED"), constitutionally_compliant: !has(failures, "CONSTITUTIONAL_VIOLATION_UNRESOLVED") });
  const observability = nested({ dashboard_id: has(failures, "RECOVERY_DASHBOARD_MISSING") ? "" : "dashboard:recovery:p5.15", suspended_trust_visible: true, revoked_trust_visible: true, expired_trust_visible: true, recovery_progress_visible: true, restoration_backlog_visible: true, pending_approvals_visible: true, requalification_latency_visible: true });
  const audit = nested({ audit_id: has(failures, "IMMUTABLE_AUDIT_MISSING") ? "" : "audit:recovery:p5.15", suspension_lineage: suspension.suspension_id ? freezeArray([suspension.suspension_id]) : freezeArray<string>([]), revocation_lineage: revocation.revocation_id ? freezeArray([revocation.revocation_id]) : freezeArray<string>([]), recovery_lineage: plan.plan_id ? freezeArray([plan.plan_id]) : freezeArray<string>([]), restoration_lineage: freezeArray([evidence.package_id, decision.decision_id].filter(Boolean)), requalification_lineage: requalification.request_id ? freezeArray([requalification.request_id]) : freezeArray<string>([]), approval_lineage: freezeArray([approval.approval_id]), immutable: !has(failures, "IMMUTABLE_AUDIT_MISSING"), replay_refs: has(failures, "RECOVERY_REPLAY_FAILED") ? freezeArray<string>([]) : freezeArray(["replay:p5.15:recovery", "program-3:recovery-replay"]) });
  const unknownRuntimeOnly = !has(failures, "UNKNOWN_PERSISTED");
  const invalidEvidenceFailClosed = !badEvidence || decision.decision === "FAIL_CLOSED";
  const traceable = audit.suspension_lineage.length > 0 && audit.recovery_lineage.length > 0 && audit.restoration_lineage.length > 0 && audit.replay_refs.length > 0;
  const derivedFailures = freezeArray([...new Set([...failures, ...(!framework.recovery_lifecycle ? ["RECOVERY_FRAMEWORK_MISSING" as const] : []), ...(!framework.suspension_model ? ["SUSPENSION_MANAGEMENT_MISSING" as const] : []), ...(!framework.revocation_model ? ["REVOCATION_MANAGEMENT_MISSING" as const] : []), ...(suspension.suspension_id.length === 0 ? ["SUSPENSION_RECORD_MISSING" as const] : []), ...(revocation.revocation_id.length === 0 ? ["REVOCATION_RECORD_MISSING" as const] : []), ...(plan.plan_id.length === 0 ? ["RECOVERY_PLAN_MISSING" as const] : []), ...(newEvidenceRefs.length === 0 ? ["NEW_EVIDENCE_MISSING" as const] : []), ...(!evidence.verifiable ? ["RECOVERY_EVIDENCE_UNVERIFIABLE" as const] : []), ...(evidence.evidence_refs.length === 0 ? ["RECOVERY_EVIDENCE_MISSING" as const] : []), ...(!approval.governance_approval ? ["GOVERNANCE_APPROVAL_ABSENT" as const] : []), ...(!approval.safety_validation ? ["SAFETY_APPROVAL_ABSENT" as const] : []), ...(!evidence.constitutional ? ["CONSTITUTIONAL_VIOLATION_UNRESOLVED" as const] : []), ...(!evidence.drift_resolution ? ["DRIFT_UNRESOLVED" as const] : []), ...(plan.required_remediation.includes("incomplete-remediation") ? ["REMEDIATION_INCOMPLETE" as const] : []), ...(!decision.reproducible ? ["RECOVERY_REPLAY_FAILED" as const] : []), ...(!unknownRuntimeOnly ? ["UNKNOWN_PERSISTED" as const] : []), ...(has(failures, "UNKNOWN_NOT_FAIL_CLOSED") ? ["UNKNOWN_NOT_FAIL_CLOSED" as const] : []), ...(requalification.request_id.length === 0 ? ["REQUALIFICATION_REQUEST_MISSING" as const] : []), ...(decision.decision_id.length === 0 ? ["RESTORATION_DECISION_MISSING" as const] : []), ...(observability.dashboard_id.length === 0 ? ["RECOVERY_DASHBOARD_MISSING" as const] : []), ...(!audit.immutable ? ["IMMUTABLE_AUDIT_MISSING" as const] : []), ...(!traceable ? ["TRACEABILITY_INCOMPLETE" as const] : []), ...(approval.automatic_restoration ? ["TRUST_SELF_RESTORED" as const] : []), ...(has(failures, "HISTORIC_EVIDENCE_ONLY") ? ["HISTORIC_EVIDENCE_ONLY" as const] : []), ...(!invalidEvidenceFailClosed ? ["UNKNOWN_NOT_FAIL_CLOSED" as const] : [])])]);
  const certification = nested({ certification_id: "P5.15-TRUST-RECOVERY-REVOCATION-CERTIFICATION-001", outcome: outcome(derivedFailures), phase_ready: outcome(derivedFailures) === "PASS", suspension_lifecycle_implemented: suspension.suspension_id.length > 0, revocation_lifecycle_auditable: revocation.revocation_id.length > 0 && audit.revocation_lineage.length > 0, expiration_handling_supported: framework.expiration_model, unknown_runtime_only: unknownRuntimeOnly, recovery_plans_deterministic: plan.deterministic, restoration_evidence_traceable: evidence.verifiable && evidence.new_evidence_refs.length > 0 && traceable, governance_approval_mandatory: approval.governance_approval && !approval.automatic_restoration, safety_validation_gates_restoration: approval.safety_validation, requalification_initiated: requalification.request_id.length > 0 && requalification.package_complete, replayable_with_audit_lineage: audit.replay_refs.length > 0 && audit.immutable && traceable, decisions_explainable_and_compliant: decision.explainable && decision.reproducible && decision.constitutionally_compliant, invalid_evidence_fail_closed: invalidEvidenceFailClosed, failures: derivedFailures });
  const base: Omit<TrustRecoveryResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, drift_detection_ref: "trust-drift-detection/v5.14", framework, suspension, revocation, plan, evidence, requalification, approval, decision, observability, audit, certification };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustRecoveryRevocation(result?: TrustRecoveryResult): TrustRecoveryValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, framework_valid: false, suspension_valid: false, revocation_valid: false, plan_valid: false, evidence_valid: false, requalification_valid: false, approval_valid: false, decision_valid: false, observability_valid: false, audit_valid: false, certification_valid: false, failures: freezeArray(["RECOVERY_FRAMEWORK_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const framework_valid = verifyHashed(result.framework) && result.framework.recovery_lifecycle && result.framework.restoration_lifecycle && result.framework.suspension_model && result.framework.revocation_model && result.framework.expiration_model && result.framework.recovery_contracts;
  const suspension_valid = verifyHashed(result.suspension) && result.suspension.suspension_id.length > 0 && result.suspension.standing === "SUSPENDED";
  const revocation_valid = verifyHashed(result.revocation) && result.revocation.revocation_id.length > 0 && result.revocation.permanent_removal && result.revocation.lineage_refs.length > 0;
  const plan_valid = verifyHashed(result.plan) && result.plan.plan_id.length > 0 && result.plan.deterministic && result.plan.required_remediation.includes("complete-remediation");
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.verifiable && result.evidence.new_evidence_refs.length > 0 && result.evidence.constitutional && result.evidence.governance && result.evidence.safety && result.evidence.drift_resolution;
  const requalification_valid = verifyHashed(result.requalification) && result.requalification.request_id.length > 0 && result.requalification.package_complete;
  const approval_valid = verifyHashed(result.approval) && result.approval.operator_review && result.approval.governance_approval && result.approval.constitutional_validation && result.approval.safety_validation && !result.approval.automatic_restoration;
  const decision_valid = verifyHashed(result.decision) && result.decision.decision === "RESTORE" && result.decision.deterministic && result.decision.explainable && result.decision.reproducible && result.decision.constitutionally_compliant;
  const observability_valid = verifyHashed(result.observability) && result.observability.dashboard_id.length > 0 && result.observability.suspended_trust_visible && result.observability.revoked_trust_visible && result.observability.expired_trust_visible;
  const audit_valid = verifyHashed(result.audit) && result.audit.immutable && result.audit.replay_refs.length > 0 && result.audit.restoration_lineage.length > 0;
  const certification_valid = verifyHashed(result.certification) && result.certification.outcome === "PASS" && result.certification.phase_ready && result.certification.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && framework_valid && suspension_valid && revocation_valid && plan_valid && evidence_valid && requalification_valid && approval_valid && decision_valid && observability_valid && audit_valid && certification_valid;
  return nested({ valid, outcome: result.certification.outcome, replay_hash_valid, integrity_hash_valid, framework_valid, suspension_valid, revocation_valid, plan_valid, evidence_valid, requalification_valid, approval_valid, decision_valid, observability_valid, audit_valid, certification_valid, failures: result.certification.failures });
}

export function replayTrustRecoveryRevocation(result = runTrustRecoveryRevocation()): boolean {
  const replayed = runTrustRecoveryRevocation();
  return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustRecoveryRevocation(result).valid;
}

export function getTrustRecoveryRevocationBundle(): TrustRecoveryBundle {
  const result = runTrustRecoveryRevocation();
  return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_trust_suspension: true, owns_trust_revocation: true, owns_trust_restoration: true, owns_trust_recovery: true, owns_requalification_initiation: true, self_restores_trust: false, persists_unknown: false }), result, validation: validateTrustRecoveryRevocation(result) });
}

export const TrustRecoveryRevocationService = Object.freeze({ run: runTrustRecoveryRevocation, validate: validateTrustRecoveryRevocation, replay: replayTrustRecoveryRevocation });
