import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runWaveSixDependencyServiceCoordination, validateWaveSixDependencyServiceCoordination } from "@/services/wave-six-dependency-service-coordination";
import { runWaveSixOperationalOrchestration, validateWaveSixOperationalOrchestration } from "@/services/wave-six-operational-orchestration";
import { runWaveSixPersonalOperationalContext, validateWaveSixPersonalOperationalContext } from "@/services/wave-six-personal-operational-context";
import type { WaveSixOperationalOptimizationBundle, WaveSixOperationalOptimizationDecision, WaveSixOperationalOptimizationFailure, WaveSixOperationalOptimizationInput, WaveSixOperationalOptimizationResult, WaveSixOperationalOptimizationScenario, WaveSixOperationalOptimizationValidation } from "@/types/wave-six-operational-optimization";

const VERSION = "wave-six-operational-optimization/w6.4" as const;
const IDENTIFIER = "WaveSixOperationalOptimization" as const;
const UPSTREAM_REFS = Object.freeze(["wave-six-operational-orchestration/w6.1", "wave-six-dependency-service-coordination/w6.2", "wave-six-personal-operational-context/w6.3", "cci-event-history", "caf-runtime-events", "mission-control-operational-data"]);
const PROVIDES = Object.freeze(["operational-observations", "bottleneck-findings", "resource-utilization-reports", "workflow-efficiency-reports", "performance-trend-findings", "optimization-evidence", "operational-analysis-reports"]);
let orchestration = runWaveSixOperationalOrchestration();
let dependency = runWaveSixDependencyServiceCoordination();
let poc = runWaveSixPersonalOperationalContext();

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly WaveSixOperationalOptimizationFailure[], failure: WaveSixOperationalOptimizationFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: WaveSixOperationalOptimizationScenario): WaveSixOperationalOptimizationFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly WaveSixOperationalOptimizationFailure[], scenario?: WaveSixOperationalOptimizationScenario): WaveSixOperationalOptimizationDecision {
  const notQualified = new Set<WaveSixOperationalOptimizationFailure>(["W6_1_OPERATIONAL_ORCHESTRATION_INVALID", "W6_2_DEPENDENCY_COORDINATION_INVALID", "W6_3_PERSONAL_OPERATIONAL_CONTEXT_INVALID", "OBSERVATION_REPLAY_DIVERGED", "CAPACITY_CALCULATION_NONDETERMINISTIC", "RESOURCE_METRICS_NOT_REPRODUCIBLE", "EFFICIENCY_NONDETERMINISTIC", "TREND_ANALYSIS_NONDETERMINISTIC", "TREND_REPLAY_DIVERGED", "FINDING_WITHOUT_EVIDENCE", "EVIDENCE_MUTABLE", "EVIDENCE_LINEAGE_INCOMPLETE", "METRIC_LINEAGE_MISSING", "REPLAY_REFERENCE_MISSING", "RECOMMENDATION_GENERATED", "RECOMMENDATION_PRIORITIZED", "DECISION_MADE", "APPROVAL_WORKFLOW_STARTED", "WORKFLOW_EXECUTED", "ORCHESTRATION_MODIFIED", "SCHEDULE_MODIFIED", "RESOURCE_ALLOCATED", "AUTONOMOUS_OPTIMIZATION_PERFORMED", "TENANT_ISOLATION_BREACH"]);
  if (failures.some((failure) => notQualified.has(failure))) return "NOT_QUALIFIED";
  if (has(failures, "OPERATIONAL_OPTIMIZATION_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_QUALIFIED";
  return "QUALIFIED";
}
function resultReplayHash(result: Omit<WaveSixOperationalOptimizationResult, "replay_hash" | "integrity_hash">): string { return hash({ observation: result.observation_engine.integrity_hash, bottleneck: result.bottleneck_detection.integrity_hash, analysis: result.resource_workflow_performance_analysis.integrity_hash, evidence: result.evidence_reports.integrity_hash, boundary: result.optimization_boundary.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<WaveSixOperationalOptimizationResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runWaveSixOperationalOptimization(input: WaveSixOperationalOptimizationInput = {}): WaveSixOperationalOptimizationResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  orchestration = runWaveSixOperationalOrchestration();
  dependency = runWaveSixDependencyServiceCoordination();
  poc = runWaveSixPersonalOperationalContext();
  const failures = freezeArray([...new Set([...(direct ? [direct] : []), ...(!validateWaveSixOperationalOrchestration(orchestration).valid ? ["W6_1_OPERATIONAL_ORCHESTRATION_INVALID" as const] : []), ...(!validateWaveSixDependencyServiceCoordination(dependency).valid ? ["W6_2_DEPENDENCY_COORDINATION_INVALID" as const] : []), ...(!validateWaveSixPersonalOperationalContext(poc).valid ? ["W6_3_PERSONAL_OPERATIONAL_CONTEXT_INVALID" as const] : [])])]);
  const observationOk = !has(failures, "OBSERVATION_ENGINE_MISSING") && !has(failures, "OBSERVATIONS_NOT_RECORDED") && !has(failures, "OBSERVATIONS_NOT_CORRELATED") && !has(failures, "OBSERVATION_TIMELINE_MISSING") && !has(failures, "OBSERVATION_REPLAY_DIVERGED");
  const bottleneckOk = !has(failures, "BOTTLENECK_ENGINE_MISSING") && !has(failures, "CONGESTION_NOT_DETECTED") && !has(failures, "QUEUE_DELAY_NOT_IDENTIFIED") && !has(failures, "DEPENDENCY_BLOCKING_NOT_IDENTIFIED") && !has(failures, "BOTTLENECK_EVIDENCE_MISSING");
  const analysisOk = !has(failures, "RESOURCE_ANALYZER_MISSING") && !has(failures, "UTILIZATION_NOT_MEASURED") && !has(failures, "CAPACITY_CALCULATION_NONDETERMINISTIC") && !has(failures, "RESOURCE_METRICS_NOT_REPRODUCIBLE") && !has(failures, "WORKFLOW_ANALYZER_MISSING") && !has(failures, "LATENCY_NOT_MEASURED") && !has(failures, "THROUGHPUT_NOT_MEASURED") && !has(failures, "EFFICIENCY_NONDETERMINISTIC") && !has(failures, "PERFORMANCE_TREND_ANALYZER_MISSING") && !has(failures, "TREND_ANALYSIS_NONDETERMINISTIC") && !has(failures, "OPERATIONAL_DRIFT_NOT_TRACKED") && !has(failures, "TREND_REPLAY_DIVERGED");
  const evidenceOk = !has(failures, "EVIDENCE_BUILDER_MISSING") && !has(failures, "FINDING_WITHOUT_EVIDENCE") && !has(failures, "EVIDENCE_MUTABLE") && !has(failures, "EVIDENCE_LINEAGE_INCOMPLETE") && !has(failures, "METRIC_LINEAGE_MISSING") && !has(failures, "REPLAY_REFERENCE_MISSING") && !has(failures, "CONFIDENCE_METADATA_MISSING") && !has(failures, "REPORTING_API_MISSING") && !has(failures, "ANALYSIS_REPORT_INCOMPLETE") && !has(failures, "PERFORMANCE_FINDINGS_MISSING");
  const boundaryOk = !has(failures, "RECOMMENDATION_GENERATED") && !has(failures, "RECOMMENDATION_PRIORITIZED") && !has(failures, "DECISION_MADE") && !has(failures, "APPROVAL_WORKFLOW_STARTED") && !has(failures, "WORKFLOW_EXECUTED") && !has(failures, "ORCHESTRATION_MODIFIED") && !has(failures, "SCHEDULE_MODIFIED") && !has(failures, "RESOURCE_ALLOCATED") && !has(failures, "AUTONOMOUS_OPTIMIZATION_PERFORMED") && !has(failures, "TENANT_ISOLATION_BREACH");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "QUALIFIED";
  const observation_engine = nested({ observation_engine_id: observationOk ? "W6.4-OBSERVATION-ENGINE-001" : "", consumes_operational_events: observationOk, observation_registry: observationOk, normalize_observations: observationOk, correlate_runtime_behavior: observationOk, aggregate_evidence: observationOk, observation_timeline: observationOk, observations_recorded: observationOk, observations_correlated: observationOk, observations_replayable: observationOk, deterministic_observation_generation: observationOk });
  const bottleneck_detection = nested({ bottleneck_engine_id: bottleneckOk ? "W6.4-BOTTLENECK-DETECTION-001" : "", workflow_congestion: bottleneckOk, recurring_delays: bottleneckOk, dependency_blocking: bottleneckOk, queue_saturation: bottleneckOk, execution_slowdowns: bottleneckOk, bottleneck_reports: bottleneckOk, bottleneck_evidence: bottleneckOk, replay_reference: bottleneckOk, deterministic_detection: bottleneckOk });
  const resource_workflow_performance_analysis = nested({ analysis_id: analysisOk ? "W6.4-RESOURCE-WORKFLOW-PERFORMANCE-001" : "", cpu_utilization: analysisOk, memory_utilization: analysisOk, storage_utilization: analysisOk, network_utilization: analysisOk, queue_depth: analysisOk, worker_utilization: analysisOk, service_capacity: analysisOk, capacity_findings: analysisOk, execution_duration: analysisOk, completion_latency: analysisOk, idle_periods: analysisOk, wait_times: analysisOk, queue_efficiency: analysisOk, throughput: analysisOk, processing_variance: analysisOk, workflow_efficiency_reports: analysisOk, historical_performance: analysisOk, recurring_degradation: analysisOk, recurring_improvements: analysisOk, trend_stability: analysisOk, operational_drift: analysisOk, trend_reports: analysisOk, performance_findings: analysisOk, deterministic_analysis: analysisOk, metrics_reproducible: analysisOk });
  const evidence_reports = nested({ evidence_reports_id: evidenceOk ? "W6.4-EVIDENCE-REPORTS-001" : "", source_observations: evidenceOk, timestamps: evidenceOk, operational_metrics: evidenceOk, correlation: evidenceOk, replay_references: evidenceOk, confidence_metadata: evidenceOk, metric_lineage: evidenceOk, observation_lineage: evidenceOk, immutable_evidence: evidenceOk, deterministic_replay_validation: evidenceOk, operational_analysis_reports: evidenceOk, workflow_observations: evidenceOk, bottlenecks: evidenceOk, utilization: evidenceOk, performance_trends: evidenceOk, evidence_references: evidenceOk, performance_findings: evidenceOk, report_generation: evidenceOk, findings_retrieval: evidenceOk, evidence_retrieval: evidenceOk });
  const optimization_boundary = nested({ boundary_id: "W6.4-OPTIMIZATION-BOUNDARY-001", produces_operational_observations: boundaryOk, mission_control_advisory_ready: boundaryOk, read_only_analysis: boundaryOk, recommendations_generated: false as const, recommendations_prioritized: false as const, decisions_made: false as const, approvals_started: false as const, workflows_executed: false as const, orchestration_modified: false as const, schedules_modified: false as const, resources_allocated: false as const, autonomous_optimization: false as const, consumes_recommendations: false as const });
  const readiness = nested({ readiness_id: "W6.4-OPERATIONAL-OPTIMIZATION-READINESS-001", decision, phase_ready: qualified, w6_1_operational_orchestration_ready: !has(failures, "W6_1_OPERATIONAL_ORCHESTRATION_INVALID"), w6_2_dependency_coordination_ready: !has(failures, "W6_2_DEPENDENCY_COORDINATION_INVALID"), w6_3_personal_operational_context_ready: !has(failures, "W6_3_PERSONAL_OPERATIONAL_CONTEXT_INVALID"), observations_deterministic: observationOk, bottlenecks_evidenced: bottleneckOk, resource_utilization_operational: analysisOk, workflow_efficiency_validated: analysisOk, performance_trends_replayable: analysisOk, evidence_immutable_complete: evidenceOk, analysis_reports_consistent: evidenceOk, mission_control_observations_available: boundaryOk, no_recommendations_or_execution: boundaryOk, read_only_boundary_validated: boundaryOk, failures });
  const base: Omit<WaveSixOperationalOptimizationResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, operational_orchestration_ref: "wave-six-operational-orchestration/w6.1", dependency_coordination_ref: "wave-six-dependency-service-coordination/w6.2", personal_operational_context_ref: "wave-six-personal-operational-context/w6.3", upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id: input.tenant_id ?? poc.tenant_id, principal_id: input.principal_id ?? "principal:w6.4:optimization-observer", optimization_id: input.optimization_id ?? "operational-optimization:w6.4:analysis", observation_engine, bottleneck_detection, resource_workflow_performance_analysis, evidence_reports, optimization_boundary, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateWaveSixOperationalOptimization(result?: WaveSixOperationalOptimizationResult): WaveSixOperationalOptimizationValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, observation_engine_valid: false, bottleneck_detection_valid: false, resource_workflow_performance_analysis_valid: false, evidence_reports_valid: false, optimization_boundary_valid: false, readiness_valid: false, failures: freezeArray(["OBSERVATION_ENGINE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const observation_engine_valid = verifyHashed(result.observation_engine) && result.observation_engine.observations_recorded && result.observation_engine.observations_correlated && result.observation_engine.observations_replayable && result.observation_engine.deterministic_observation_generation;
  const bottleneck_detection_valid = verifyHashed(result.bottleneck_detection) && result.bottleneck_detection.workflow_congestion && result.bottleneck_detection.queue_saturation && result.bottleneck_detection.bottleneck_evidence && result.bottleneck_detection.deterministic_detection;
  const resource_workflow_performance_analysis_valid = verifyHashed(result.resource_workflow_performance_analysis) && result.resource_workflow_performance_analysis.cpu_utilization && result.resource_workflow_performance_analysis.completion_latency && result.resource_workflow_performance_analysis.throughput && result.resource_workflow_performance_analysis.deterministic_analysis && result.resource_workflow_performance_analysis.metrics_reproducible;
  const evidence_reports_valid = verifyHashed(result.evidence_reports) && result.evidence_reports.source_observations && result.evidence_reports.immutable_evidence && result.evidence_reports.metric_lineage && result.evidence_reports.observation_lineage && result.evidence_reports.deterministic_replay_validation && result.evidence_reports.operational_analysis_reports;
  const optimization_boundary_valid = verifyHashed(result.optimization_boundary) && result.optimization_boundary.read_only_analysis && result.optimization_boundary.produces_operational_observations && !result.optimization_boundary.recommendations_generated && !result.optimization_boundary.decisions_made && !result.optimization_boundary.workflows_executed && !result.optimization_boundary.resources_allocated && !result.optimization_boundary.autonomous_optimization;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.w6_1_operational_orchestration_ready && result.readiness.w6_2_dependency_coordination_ready && result.readiness.w6_3_personal_operational_context_ready && result.readiness.evidence_immutable_complete && result.readiness.no_recommendations_or_execution && result.readiness.read_only_boundary_validated && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && observation_engine_valid && bottleneck_detection_valid && resource_workflow_performance_analysis_valid && evidence_reports_valid && optimization_boundary_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, observation_engine_valid, bottleneck_detection_valid, resource_workflow_performance_analysis_valid, evidence_reports_valid, optimization_boundary_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayWaveSixOperationalOptimization(result = runWaveSixOperationalOptimization()): boolean { const replayed = runWaveSixOperationalOptimization(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateWaveSixOperationalOptimization(result).valid; }
export function getWaveSixOperationalOptimizationBundle(): WaveSixOperationalOptimizationBundle { const result = runWaveSixOperationalOptimization(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, observation_before_recommendation: true, evidence_driven: true, read_only_analysis: true, deterministic_analysis_required: true, replayable_analysis_required: true, recommendations_prohibited: true, execution_prohibited: true, qualification_gate: "W6.4 Operational Optimization Qualification Gate" }), result, validation: validateWaveSixOperationalOptimization(result) }); }
export const WaveSixOperationalOptimizationService = Object.freeze({ run: runWaveSixOperationalOptimization, validate: validateWaveSixOperationalOptimization, replay: replayWaveSixOperationalOptimization });
