import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runWaveSixOperationalOrchestration, validateWaveSixOperationalOrchestration } from "@/services/wave-six-operational-orchestration";
import type { WaveSixDependencyServiceCoordinationBundle, WaveSixDependencyServiceCoordinationDecision, WaveSixDependencyServiceCoordinationFailure, WaveSixDependencyServiceCoordinationInput, WaveSixDependencyServiceCoordinationResult, WaveSixDependencyServiceCoordinationScenario, WaveSixDependencyServiceCoordinationValidation, WaveSixDependencyState } from "@/types/wave-six-dependency-service-coordination";

const VERSION = "wave-six-dependency-service-coordination/w6.2" as const;
const IDENTIFIER = "WaveSixDependencyServiceCoordination" as const;
const DEPENDENCY_STATES = Object.freeze<WaveSixDependencyState[]>(["REGISTERED", "AVAILABLE", "DEGRADED", "UNAVAILABLE", "WAITING", "FAILED", "UNKNOWN"]);
const UPSTREAM_REFS = Object.freeze(["wave-six-operational-orchestration/w6.1", "cci-service-registry", "caf-runtime", "mission-control-services", "cata-services"]);
const PROVIDES = Object.freeze(["dependency-registry", "dependency-observation-engine", "provider-availability-monitor", "orchestration-readiness-engine", "dependency-coordination-engine", "dependency-failure-analyzer", "operational-readiness-service", "dependency-evidence-repository"]);
let w61 = runWaveSixOperationalOrchestration();

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly WaveSixDependencyServiceCoordinationFailure[], failure: WaveSixDependencyServiceCoordinationFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: WaveSixDependencyServiceCoordinationScenario): WaveSixDependencyServiceCoordinationFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly WaveSixDependencyServiceCoordinationFailure[], scenario?: WaveSixDependencyServiceCoordinationScenario): WaveSixDependencyServiceCoordinationDecision {
  const notQualified = new Set<WaveSixDependencyServiceCoordinationFailure>(["W6_1_OPERATIONAL_ORCHESTRATION_INVALID", "DEPENDENCY_GRAPH_NONDETERMINISTIC", "UNMANAGED_DEPENDENCY_DISCOVERED", "MISSING_HEALTH_INFORMATION_ASSUMED_AVAILABLE", "UNKNOWN_DEPENDENCY_NOT_FAIL_CLOSED", "FAILURE_PROPAGATION_INVALID", "RECOVERY_DETECTION_INVALID", "READINESS_NONDETERMINISTIC", "REQUIRED_DEPENDENCY_UNAVAILABLE_READY", "GOVERNANCE_SERVICE_UNAVAILABLE_READY", "TRUST_SERVICE_UNAVAILABLE_READY", "MISSION_SERVICE_UNAVAILABLE_READY", "SERVICE_LIFECYCLE_MODIFIED", "DEPENDENCY_SEQUENCING_INVALID", "READINESS_PROPAGATION_INVALID", "DEPENDENCY_CONSISTENCY_INVALID", "MISSING_DEPENDENCY_NOT_DETECTED", "VERSION_INCOMPATIBILITY_NOT_DETECTED", "CIRCULAR_DEPENDENCY_NOT_DETECTED", "DEPENDENCY_CASCADE_NOT_DETECTED", "IMPACT_ASSESSMENT_NONDETERMINISTIC", "READINESS_EVIDENCE_MUTABLE", "DEPENDENCY_LINEAGE_INCOMPLETE", "REPLAY_DIVERGED", "W6_1_BYPASSES_READINESS_INTELLIGENCE", "TENANT_ISOLATION_BREACH"]);
  if (failures.some((failure) => notQualified.has(failure))) return "NOT_QUALIFIED";
  if (has(failures, "DEPENDENCY_SERVICE_COORDINATION_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_QUALIFIED";
  return "QUALIFIED";
}
function resultReplayHash(result: Omit<WaveSixDependencyServiceCoordinationResult, "replay_hash" | "integrity_hash">): string { return hash({ registry: result.dependency_registry.integrity_hash, observation: result.provider_observation.integrity_hash, readiness: result.readiness_coordination.integrity_hash, analysis: result.operational_readiness_failure_analysis.integrity_hash, evidence: result.evidence.integrity_hash, final: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<WaveSixDependencyServiceCoordinationResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runWaveSixDependencyServiceCoordination(input: WaveSixDependencyServiceCoordinationInput = {}): WaveSixDependencyServiceCoordinationResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  w61 = runWaveSixOperationalOrchestration();
  const failures = freezeArray([...new Set([...(direct ? [direct] : []), ...(!validateWaveSixOperationalOrchestration(w61).valid ? ["W6_1_OPERATIONAL_ORCHESTRATION_INVALID" as const] : [])])]);
  const registryOk = !has(failures, "DEPENDENCY_REGISTRY_MISSING") && !has(failures, "DEPENDENCY_GRAPH_NONDETERMINISTIC") && !has(failures, "SERVICE_RELATIONSHIP_CATALOG_MISSING") && !has(failures, "UNMANAGED_DEPENDENCY_DISCOVERED");
  const observationOk = !has(failures, "PROVIDER_AVAILABILITY_MONITOR_MISSING") && !has(failures, "MISSING_HEALTH_INFORMATION_ASSUMED_AVAILABLE") && !has(failures, "UNKNOWN_DEPENDENCY_NOT_FAIL_CLOSED") && !has(failures, "PROVIDER_STATUS_REGISTRY_MISSING") && !has(failures, "DEPENDENCY_OBSERVATION_ENGINE_MISSING") && !has(failures, "PROVIDER_TRANSITIONS_NOT_TRACKED") && !has(failures, "FAILURE_PROPAGATION_INVALID") && !has(failures, "RECOVERY_DETECTION_INVALID") && !has(failures, "DEPENDENCY_LATENCY_MISSING");
  const readinessCoordinationOk = !has(failures, "ORCHESTRATION_READINESS_ENGINE_MISSING") && !has(failures, "READINESS_NONDETERMINISTIC") && !has(failures, "REQUIRED_DEPENDENCY_UNAVAILABLE_READY") && !has(failures, "GOVERNANCE_SERVICE_UNAVAILABLE_READY") && !has(failures, "TRUST_SERVICE_UNAVAILABLE_READY") && !has(failures, "MISSION_SERVICE_UNAVAILABLE_READY") && !has(failures, "DEPENDENCY_COORDINATION_ENGINE_MISSING") && !has(failures, "SERVICE_LIFECYCLE_MODIFIED") && !has(failures, "DEPENDENCY_SEQUENCING_INVALID") && !has(failures, "READINESS_PROPAGATION_INVALID");
  const analysisOk = !has(failures, "OPERATIONAL_READINESS_ASSESSMENT_MISSING") && !has(failures, "READINESS_REPORT_INCOMPLETE") && !has(failures, "PROVIDER_RESPONSIVENESS_MISSING") && !has(failures, "DEPENDENCY_CONSISTENCY_INVALID") && !has(failures, "DEPENDENCY_FAILURE_ANALYSIS_MISSING") && !has(failures, "MISSING_DEPENDENCY_NOT_DETECTED") && !has(failures, "VERSION_INCOMPATIBILITY_NOT_DETECTED") && !has(failures, "CIRCULAR_DEPENDENCY_NOT_DETECTED") && !has(failures, "DEPENDENCY_CASCADE_NOT_DETECTED") && !has(failures, "IMPACT_ASSESSMENT_NONDETERMINISTIC");
  const evidenceOk = !has(failures, "READINESS_EVIDENCE_MISSING") && !has(failures, "READINESS_EVIDENCE_MUTABLE") && !has(failures, "DEPENDENCY_LINEAGE_INCOMPLETE") && !has(failures, "REPLAY_DIVERGED") && !has(failures, "W6_1_BYPASSES_READINESS_INTELLIGENCE") && !has(failures, "TENANT_ISOLATION_BREACH");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "QUALIFIED";
  const dependency_registry = nested({ registry_id: registryOk ? "W6.2-DEPENDENCY-REGISTRY-001" : "", dependency_identities: registryOk, service_relationships: registryOk, consumer_provider_mappings: registryOk, runtime_dependency_graph: registryOk, version_awareness: registryOk, required_optional_classification: registryOk, dependency_metadata: registryOk, cci_service_registry_source: registryOk, unmanaged_dependencies_blocked: registryOk, graph_deterministic: registryOk, states: freezeArray(DEPENDENCY_STATES) });
  const provider_observation = nested({ observation_id: observationOk ? "W6.2-PROVIDER-OBSERVATION-001" : "", availability_monitor: observationOk, provider_status_registry: observationOk, availability: observationOk, connectivity: observationOk, registration_status: observationOk, runtime_heartbeat: observationOk, capacity_status: observationOk, health_endpoint_results: observationOk, maintenance_state: observationOk, dependency_state_tracking: observationOk, provider_transitions: observationOk, failure_propagation: observationOk, recovery_detection: observationOk, dependency_latency: observationOk, registration_changes: observationOk, dependency_events: observationOk, dependency_timeline: observationOk, observation_evidence: observationOk, missing_health_fails_closed: observationOk, unknown_state_not_ready: observationOk });
  const readiness_coordination = nested({ readiness_coordination_id: readinessCoordinationOk ? "W6.2-READINESS-COORDINATION-001" : "", readiness_engine: readinessCoordinationOk, required_dependencies_available: readinessCoordinationOk, required_services_healthy: readinessCoordinationOk, runtime_reachable: readinessCoordinationOk, governance_services_operational: readinessCoordinationOk, trust_services_operational: readinessCoordinationOk, mission_services_operational: readinessCoordinationOk, readiness_state: readinessCoordinationOk ? "READY" as const : "NOT_READY" as const, deterministic_evaluation: readinessCoordinationOk, dependency_coordination_engine: readinessCoordinationOk, startup_ordering: readinessCoordinationOk, shutdown_ordering: readinessCoordinationOk, dependency_stabilization: readinessCoordinationOk, recovery_coordination: readinessCoordinationOk, dependency_synchronization: readinessCoordinationOk, readiness_propagation: readinessCoordinationOk, observes_only: readinessCoordinationOk, never_starts_services: readinessCoordinationOk, never_stops_services: readinessCoordinationOk });
  const operational_readiness_failure_analysis = nested({ analysis_id: analysisOk ? "W6.2-READINESS-FAILURE-ANALYSIS-001" : "", operational_readiness_assessment: analysisOk, service_availability: analysisOk, dependency_health: analysisOk, runtime_stability: analysisOk, provider_responsiveness: analysisOk, required_capability_availability: analysisOk, dependency_consistency: analysisOk, operational_readiness_report: analysisOk, readiness_evidence: analysisOk, readiness_timeline: analysisOk, dependency_failure_analysis: analysisOk, provider_failure: analysisOk, missing_dependency: analysisOk, dependency_timeout: analysisOk, registration_inconsistency: analysisOk, version_incompatibility: analysisOk, circular_dependency: analysisOk, dependency_cascade: analysisOk, deterministic_impact_assessment: analysisOk });
  const evidence = nested({ evidence_id: evidenceOk ? "W6.2-DEPENDENCY-EVIDENCE-001" : "", dependency_snapshots: evidenceOk, availability_snapshots: evidenceOk, readiness_decisions: evidenceOk, health_history: evidenceOk, dependency_transitions: evidenceOk, operational_evidence_lineage: evidenceOk, dependency_evidence: evidenceOk, availability_evidence: evidenceOk, readiness_evidence: evidenceOk, health_evidence: evidenceOk, failure_evidence: evidenceOk, recovery_evidence: evidenceOk, dependency_lineage: evidenceOk, operational_coordination_evidence: evidenceOk, immutable: evidenceOk, replayable: evidenceOk, w6_1_consumes_readiness_decisions: evidenceOk, w6_1_no_direct_dependency_inspection: evidenceOk });
  const readiness = nested({ readiness_id: "W6.2-DEPENDENCY-SERVICE-COORDINATION-READINESS-001", decision, phase_ready: qualified, w6_1_ready: !has(failures, "W6_1_OPERATIONAL_ORCHESTRATION_INVALID"), dependency_registry_operational: registryOk, runtime_dependency_graph_deterministic: registryOk, provider_availability_monitored: observationOk, dependency_observation_validated: observationOk, orchestration_readiness_deterministic: readinessCoordinationOk, dependency_coordination_operational: readinessCoordinationOk, readiness_reports_correct: analysisOk, failure_propagation_validated: observationOk && analysisOk, recovery_detection_verified: observationOk && analysisOk, immutable_operational_evidence_recorded: evidenceOk, replay_identical_readiness_decisions: !has(failures, "REPLAY_DIVERGED"), w6_1_consumes_readiness_without_direct_inspection: evidenceOk, operational_awareness_only: readinessCoordinationOk, failures });
  const base: Omit<WaveSixDependencyServiceCoordinationResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, operational_orchestration_ref: "wave-six-operational-orchestration/w6.1", upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id: input.tenant_id ?? w61.tenant_id, principal_id: input.principal_id ?? "principal:w6.2:dependency-coordinator", dependency_registry, provider_observation, readiness_coordination, operational_readiness_failure_analysis, evidence, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateWaveSixDependencyServiceCoordination(result?: WaveSixDependencyServiceCoordinationResult): WaveSixDependencyServiceCoordinationValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, dependency_registry_valid: false, provider_observation_valid: false, readiness_coordination_valid: false, operational_readiness_failure_analysis_valid: false, evidence_valid: false, readiness_valid: false, failures: freezeArray(["DEPENDENCY_REGISTRY_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const dependency_registry_valid = verifyHashed(result.dependency_registry) && result.dependency_registry.cci_service_registry_source && result.dependency_registry.unmanaged_dependencies_blocked && result.dependency_registry.graph_deterministic && result.dependency_registry.states.length === DEPENDENCY_STATES.length;
  const provider_observation_valid = verifyHashed(result.provider_observation) && result.provider_observation.availability_monitor && result.provider_observation.failure_propagation && result.provider_observation.recovery_detection && result.provider_observation.missing_health_fails_closed && result.provider_observation.unknown_state_not_ready;
  const readiness_coordination_valid = verifyHashed(result.readiness_coordination) && result.readiness_coordination.readiness_state === "READY" && result.readiness_coordination.deterministic_evaluation && result.readiness_coordination.observes_only && result.readiness_coordination.never_starts_services && result.readiness_coordination.never_stops_services;
  const operational_readiness_failure_analysis_valid = verifyHashed(result.operational_readiness_failure_analysis) && result.operational_readiness_failure_analysis.operational_readiness_report && result.operational_readiness_failure_analysis.dependency_consistency && result.operational_readiness_failure_analysis.version_incompatibility && result.operational_readiness_failure_analysis.circular_dependency && result.operational_readiness_failure_analysis.deterministic_impact_assessment;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.immutable && result.evidence.replayable && result.evidence.dependency_lineage && result.evidence.w6_1_consumes_readiness_decisions && result.evidence.w6_1_no_direct_dependency_inspection;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.w6_1_ready && result.readiness.orchestration_readiness_deterministic && result.readiness.w6_1_consumes_readiness_without_direct_inspection && result.readiness.operational_awareness_only && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && dependency_registry_valid && provider_observation_valid && readiness_coordination_valid && operational_readiness_failure_analysis_valid && evidence_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, dependency_registry_valid, provider_observation_valid, readiness_coordination_valid, operational_readiness_failure_analysis_valid, evidence_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayWaveSixDependencyServiceCoordination(result = runWaveSixDependencyServiceCoordination()): boolean { const replayed = runWaveSixDependencyServiceCoordination(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateWaveSixDependencyServiceCoordination(result).valid; }
export function getWaveSixDependencyServiceCoordinationBundle(): WaveSixDependencyServiceCoordinationBundle { const result = runWaveSixDependencyServiceCoordination(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, observes_never_executes: true, registry_driven_discovery_required: true, deterministic_readiness_required: true, fail_closed_unknown_state_required: true, immutable_dependency_evidence_required: true, service_lifecycle_modification_prohibited: true, w6_1_consumes_readiness_decisions: true, qualification_gate: "W6.2 Dependency and Service Coordination Qualification Gate" }), result, validation: validateWaveSixDependencyServiceCoordination(result) }); }
export const WaveSixDependencyServiceCoordinationService = Object.freeze({ run: runWaveSixDependencyServiceCoordination, validate: validateWaveSixDependencyServiceCoordination, replay: replayWaveSixDependencyServiceCoordination });
