import type { ContextBill, ContextInsight, ContextTask, HouseholdContext } from "./types";

export interface ContextRule { id: string; evaluate(context: HouseholdContext): ContextInsight[]; }
const expiresAt = (context: HouseholdContext) => new Date(new Date(context.timestamp).getTime() + 6 * 60 * 60 * 1000).toISOString();

export const billDueTomorrowRule: ContextRule = { id: "CTX-BILL-001", evaluate: (context) => context.bills.items.filter((bill) => bill.status === "UNPAID" && bill.attention === "NEEDS_ATTENTION").map((bill: ContextBill) => ({ id: `bill-due-${bill.id}`, type: "BILL_DUE_SOON", severity: "HIGH", title: `${bill.name} is due soon`, message: `$${bill.amount.toFixed(2)} is due tomorrow.`, reasons: bill.reasons, relatedEntities: [`bill:${bill.id}`], recommendedAction: "Review and pay this bill", expiresAt: expiresAt(context), triggeredRules: ["CTX-BILL-001"] })) };
export const billOverdueRule: ContextRule = { id: "CTX-BILL-002", evaluate: (context) => context.bills.items.filter((bill) => bill.status === "UNPAID" && bill.attention === "URGENT").map((bill: ContextBill) => ({ id: `bill-overdue-${bill.id}`, type: "BILL_OVERDUE", severity: "URGENT", title: `${bill.name} is overdue`, message: `$${bill.amount.toFixed(2)} needs attention now.`, reasons: bill.reasons, relatedEntities: [`bill:${bill.id}`], recommendedAction: "Pay or reschedule this bill", expiresAt: expiresAt(context), triggeredRules: ["CTX-BILL-002"] })) };
export const outdoorTaskWeatherRule: ContextRule = { id: "CTX-WEATHER-001", evaluate: (context) => context.tasks.items.filter((task) => task.weatherConflict).map((task: ContextTask) => ({ id: `weather-task-${task.id}`, type: "WEATHER_TASK_WINDOW", severity: "MEDIUM", title: `Plan ${task.title} before rain`, message: task.recommendedWindow ? `Rain is expected later today. The best weather window ends at ${new Intl.DateTimeFormat("en-US", { timeZone: context.time.timezone, hour: "numeric" }).format(new Date(task.recommendedWindow.end))}.` : "Rain may affect this outdoor task.", reasons: task.reasons, relatedEntities: [`task:${task.id}`], recommendedAction: task.recommendedWindow ? `Complete before ${new Intl.DateTimeFormat("en-US", { timeZone: context.time.timezone, hour: "numeric" }).format(new Date(task.recommendedWindow.end))}` : "Choose a dry weather window", expiresAt: expiresAt(context), triggeredRules: ["CTX-WEATHER-001", "CTX-CROSS-001"] })) };
export const contextRules: ContextRule[] = [billDueTomorrowRule, billOverdueRule, outdoorTaskWeatherRule];
