import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runTrustContinuousMonitoring, validateTrustContinuousMonitoring } from "@/services/trust-continuous-monitoring";
import type { DriftAlert, DriftCategory, DriftSeverity, TrustDriftBundle, TrustDriftFailure, TrustDriftInput, TrustDriftOutcome, TrustDriftResult, TrustDriftScenario, TrustDriftValidation } from "@/types/trust-drift-detection";

const VERSION = "trust-drift-detection/v5.14" as const;
const IDENTIFIER = "TrustDriftDetection" as const;
const NOW = "2026-07-19T00:00:00.000Z";
let monitoringBaseline: ReturnType<typeof runTrustContinuousMonitoring> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly TrustDriftFailure[], failure: TrustDriftFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustDriftScenario): TrustDriftFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function outcome(failures: readonly TrustDriftFailure[]): TrustDriftOutcome { return has(failures, "GOVERNANCE_REVIEW_REQUIRED") ? "REQUIRES_GOVERNANCE_REVIEW" : failures.length ? "FAIL" : "PASS"; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function resultReplayHash(result: Omit<TrustDriftResult, "replay_hash" | "integrity_hash">): string { return hash({ engine: result.engine.integrity_hash, classification: result.classification.integrity_hash, severity: result.severity.integrity_hash, trends: result.trends.integrity_hash, evidence: result.evidence.integrity_hash, record: result.record.integrity_hash, report: result.report.integrity_hash, alerts: result.alerts.map((item) => item.integrity_hash), boundary: result.boundary.integrity_hash, certification: result.certification.integrity_hash }); }
function resultIntegrityHash(result: Omit<TrustDriftResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.certification.outcome, replay_hash: result.replay_hash }); }

export function runTrustDriftDetection(input: TrustDriftInput = {}): TrustDriftResult {
  const direct = scenarioFailure(input.scenario ?? "BASELINE");
  const scenarioFailures = freezeArray<TrustDriftFailure>(direct ? [direct] : []);
  monitoringBaseline ??= runTrustContinuousMonitoring();
  const dependencyFailures = freezeArray<TrustDriftFailure>(!validateTrustContinuousMonitoring(monitoringBaseline).valid || has(scenarioFailures, "P5_13_MONITORING_INVALID") ? ["P5_13_MONITORING_INVALID"] : []);
  const failures = freezeArray([...new Set([...scenarioFailures, ...dependencyFailures])]);
  const trustIdentity = input.trust_identity ?? "trust-domain:civitas:root";
  const tenantId = has(failures, "TENANT_ISOLATION_VIOLATED") ? "tenant:external" : input.tenant_id ?? "tenant:civitas:primary";
  const engine = nested({ engine_id: "engine:trust-drift:p5.14", trust_drift_engine: !has(failures, "TRUST_DRIFT_ENGINE_MISSING"), alignment_drift_analyzer: !has(failures, "ALIGNMENT_DRIFT_ANALYZER_MISSING"), confidence_degradation_analyzer: !has(failures, "CONFIDENCE_DEGRADATION_ANALYZER_MISSING"), trust_degradation_analyzer: !has(failures, "TRUST_DEGRADATION_ANALYZER_MISSING"), drift_classification_framework: !has(failures, "DRIFT_CLASSIFICATION_MISSING"), drift_severity_engine: !has(failures, "DRIFT_SEVERITY_ENGINE_MISSING"), historical_trend_analyzer: !has(failures, "HISTORICAL_TREND_ANALYZER_MISSING"), root_cause_analysis_engine: !has(failures, "ROOT_CAUSE_ANALYSIS_MISSING"), drift_alert_engine: !has(failures, "DRIFT_ALERT_ENGINE_MISSING"), drift_evidence_registry: !has(failures, "DRIFT_EVIDENCE_REGISTRY_MISSING"), governance_integration_contracts: !has(failures, "GOVERNANCE_INTEGRATION_MISSING") });
  const evidenceRefs = has(failures, "DRIFT_EVIDENCE_MISSING") || has(failures, "DRIFT_EVIDENCE_UNVERIFIABLE") ? freezeArray<string>([]) : freezeArray(["evidence-registry:p5.5:trust", "confidence-report:p5.5:baseline", "risk-model:p5.6:baseline", "alignment-report:p5.8:baseline", "compliance-report:p5.9:baseline", "safety-findings:p5.10", "justification-report:p5.11", monitoringBaseline.report.report_id, monitoringBaseline.health.report_id]);
  const categories = freezeArray<DriftCategory>(["TRUST_DRIFT", "ALIGNMENT_DRIFT", "CONFIDENCE_DRIFT", "GOVERNANCE_DRIFT", "SAFETY_DRIFT", "OPERATIONAL_DRIFT", "EVIDENCE_DRIFT"]);
  const indicators = has(failures, "DRIFT_INDICATORS_MISSING") ? freezeArray<string>([]) : freezeArray(["decreasing-confidence", "declining-evidence-quality", "governance-escalations", "safety-incident-pressure", "mission-deviation", "replay-inconsistency", "trust-score-decline"]);
  const classification = nested({ classification_id: "classification:trust-drift:p5.14", categories: has(failures, "DRIFT_CLASSIFICATION_MISSING") ? freezeArray<DriftCategory>([]) : categories, indicators, deterministic: !has(failures, "DRIFT_DETECTION_NONDETERMINISTIC") });
  const severityValue: DriftSeverity = has(failures, "DRIFT_SEVERITY_NONDETERMINISTIC") ? "CRITICAL" : "MODERATE";
  const severity = nested({ severity_id: "severity:trust-drift:p5.14", severity: severityValue, threshold_model: "approved-thresholds:p5.14", deterministic_thresholds: !has(failures, "DRIFT_SEVERITY_NONDETERMINISTIC"), confidence_delta: -0.07, risk_delta: 0.06 });
  const trends = nested({ trend_id: "trend:trust-drift:p5.14", methods: freezeArray(["trend-analysis", "moving-average", "statistical-deviation", "threshold-analysis", "anomaly-detection", "historical-comparison", "replay-comparison", "evidence-freshness", "governance-frequency"]), historical_comparison: !has(failures, "HISTORICAL_BASELINE_MISSING"), replay_comparison: !has(failures, "DRIFT_REPLAY_FAILED"), trend_direction: "DETERIORATING" as const });
  const evidence = nested({ registry_id: "registry:drift-evidence:p5.14", evidence_refs: evidenceRefs, verifiable: evidenceRefs.length > 0 && !has(failures, "DRIFT_EVIDENCE_UNVERIFIABLE"), lineage_refs: has(failures, "TRACEABILITY_INCOMPLETE") ? freezeArray<string>([]) : evidenceRefs.map((ref) => `lineage:${ref}`), replay_refs: has(failures, "DRIFT_REPLAY_FAILED") ? freezeArray<string>([]) : freezeArray(["replay:p5.14:drift", "program-3:drift-replay"]) });
  const rootCauses = has(failures, "ROOT_CAUSE_ANALYSIS_MISSING") ? freezeArray<string>([]) : freezeArray(["evidence-degradation", "alignment-degradation", "operational-instability", "increased-uncertainty"]);
  const record = nested({ drift_id: "drift-record:p5.14", trust_identity: trustIdentity, tenant_id: tenantId, evaluation_time: NOW, historical_baseline: has(failures, "HISTORICAL_BASELINE_MISSING") ? "" : "baseline:trust-history:p5.13", current_state: has(failures, "CURRENT_STATE_MISSING") ? "" : monitoringBaseline.record.monitoring_id, drift_category: "TRUST_DRIFT" as const, drift_severity: severity.severity, confidence_delta: severity.confidence_delta, alignment_delta: -0.03, risk_delta: severity.risk_delta, governance_delta: 0.04, safety_delta: 0.02, supporting_evidence: evidence.evidence_refs, historical_trend: freezeArray(["t-3:stable", "t-2:stable", "t-1:minor-degradation", "t:moderate-degradation"]), root_cause_analysis: rootCauses, recommended_escalation: "notify monitoring services and require governance escalation review", drift_state: "DRIFT_DETECTED" as const });
  const report = nested({ report_id: has(failures, "DRIFT_REPORT_MISSING") ? "" : "report:trust-drift:p5.14", trust_identity: trustIdentity, summary: "Moderate longitudinal trust drift detected without modifying trust standing.", drift_records: freezeArray([record.drift_id]), degradation_findings: freezeArray(["confidence degradation", "evidence quality decline", "risk trend increase"]), explanation: has(failures, "DRIFT_EXPLANATION_INCOMPLETE") ? "" : "Confidence decreased and risk increased relative to the P5.13 monitoring baseline; evidence remains traceable and replayable.", evidence_refs: evidence.evidence_refs, governance_recommendations: has(failures, "GOVERNANCE_ESCALATION_RULES_MISSING") ? freezeArray<string>([]) : freezeArray(["escalate-to-p5.12-governance", "trigger-p5.7-reevaluation-workflow"]) });
  const alertItems: DriftAlert[] = has(failures, "DRIFT_ALERTS_MISSING") ? [] : [nested({ alert_id: "alert:trust-drift:p5.14", drift_type: record.drift_category, affected_trust_identity: trustIdentity, severity: record.drift_severity, priority: "MEDIUM" as const, evidence_summary: "Drift alert backed by P5.13 monitoring, confidence, risk, alignment, compliance, and safety evidence.", trend_history: record.historical_trend, recommended_response: "escalate for governance review without changing trust standing" })];
  const alerts = freezeArray(alertItems);
  const boundary = nested({ boundary_id: "boundary:trust-drift:p5.14", trust_standing_recalculated: has(failures, "TRUST_STANDING_RECALCULATED"), trust_standing_modified: has(failures, "TRUST_STANDING_MODIFIED"), trust_decision_issued: has(failures, "TRUST_DECISION_ISSUED"), trust_monitoring_dashboard_executed: has(failures, "TRUST_MONITORING_DASHBOARD_EXECUTED"), governance_review_executed: has(failures, "GOVERNANCE_REVIEW_EXECUTED"), safety_qualification_executed: has(failures, "SAFETY_QUALIFICATION_EXECUTED"), tenant_isolation_preserved: !has(failures, "TENANT_ISOLATION_VIOLATED") });
  const boundaryRespected = !boundary.trust_standing_recalculated && !boundary.trust_standing_modified && !boundary.trust_decision_issued && !boundary.trust_monitoring_dashboard_executed && !boundary.governance_review_executed && !boundary.safety_qualification_executed && boundary.tenant_isolation_preserved;
  const replayValid = evidence.replay_refs.length > 0 && classification.deterministic && severity.deterministic_thresholds;
  const traceable = evidence.lineage_refs.length > 0 && evidence.evidence_refs.length > 0;
  const derivedFailures = freezeArray([...new Set([...failures, ...(!engine.trust_drift_engine ? ["TRUST_DRIFT_ENGINE_MISSING" as const] : []), ...(!engine.alignment_drift_analyzer ? ["ALIGNMENT_DRIFT_ANALYZER_MISSING" as const] : []), ...(!engine.confidence_degradation_analyzer ? ["CONFIDENCE_DEGRADATION_ANALYZER_MISSING" as const] : []), ...(!engine.trust_degradation_analyzer ? ["TRUST_DEGRADATION_ANALYZER_MISSING" as const] : []), ...(!engine.drift_classification_framework ? ["DRIFT_CLASSIFICATION_MISSING" as const] : []), ...(!engine.drift_severity_engine ? ["DRIFT_SEVERITY_ENGINE_MISSING" as const] : []), ...(!engine.historical_trend_analyzer ? ["HISTORICAL_TREND_ANALYZER_MISSING" as const] : []), ...(!engine.root_cause_analysis_engine ? ["ROOT_CAUSE_ANALYSIS_MISSING" as const] : []), ...(!engine.drift_alert_engine ? ["DRIFT_ALERT_ENGINE_MISSING" as const] : []), ...(!engine.drift_evidence_registry ? ["DRIFT_EVIDENCE_REGISTRY_MISSING" as const] : []), ...(!engine.governance_integration_contracts ? ["GOVERNANCE_INTEGRATION_MISSING" as const] : []), ...(record.historical_baseline.length === 0 ? ["HISTORICAL_BASELINE_MISSING" as const] : []), ...(record.current_state.length === 0 ? ["CURRENT_STATE_MISSING" as const] : []), ...(classification.indicators.length === 0 ? ["DRIFT_INDICATORS_MISSING" as const] : []), ...(!severity.deterministic_thresholds ? ["DRIFT_SEVERITY_NONDETERMINISTIC" as const] : []), ...(!classification.deterministic ? ["DRIFT_DETECTION_NONDETERMINISTIC" as const] : []), ...(!replayValid ? ["DRIFT_REPLAY_FAILED" as const] : []), ...(evidence.evidence_refs.length === 0 ? ["DRIFT_EVIDENCE_MISSING" as const] : []), ...(!evidence.verifiable ? ["DRIFT_EVIDENCE_UNVERIFIABLE" as const] : []), ...(report.report_id.length === 0 ? ["DRIFT_REPORT_MISSING" as const] : []), ...(alerts.length === 0 ? ["DRIFT_ALERTS_MISSING" as const] : []), ...(report.explanation.length === 0 ? ["DRIFT_EXPLANATION_INCOMPLETE" as const] : []), ...(report.governance_recommendations.length === 0 ? ["GOVERNANCE_ESCALATION_RULES_MISSING" as const] : []), ...(!traceable ? ["TRACEABILITY_INCOMPLETE" as const] : []), ...(!boundaryRespected ? [scenarioFailures[0] as TrustDriftFailure] : [])])]);
  const certification = nested({ certification_id: "P5.14-TRUST-DRIFT-DETECTION-CERTIFICATION-001", outcome: outcome(derivedFailures), phase_ready: outcome(derivedFailures) === "PASS", trust_drift_detection_operational: engine.trust_drift_engine, alignment_drift_detection_operational: engine.alignment_drift_analyzer, confidence_degradation_operational: engine.confidence_degradation_analyzer, trust_degradation_operational: engine.trust_degradation_analyzer, classification_complete: classification.categories.length === categories.length && classification.indicators.length > 0, severity_deterministic: severity.deterministic_thresholds, trend_analysis_operational: trends.historical_comparison && trends.methods.length > 0, replay_validation_succeeds: replayValid, explainability_complete: report.explanation.length > 0, governance_escalation_rules_implemented: report.governance_recommendations.length > 0, alerts_generated_deterministically: alerts.length > 0 && classification.deterministic, outputs_traceable: traceable, boundary_respected: boundaryRespected, failures: derivedFailures });
  const base: Omit<TrustDriftResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, monitoring_ref: "trust-continuous-monitoring/v5.13", engine, classification, severity, trends, evidence, record, report, alerts, boundary, certification };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustDriftDetection(result?: TrustDriftResult): TrustDriftValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, engine_valid: false, classification_valid: false, severity_valid: false, trends_valid: false, evidence_valid: false, record_valid: false, report_valid: false, alerts_valid: false, boundary_valid: false, certification_valid: false, failures: freezeArray(["TRUST_DRIFT_ENGINE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const engine_valid = verifyHashed(result.engine) && result.engine.trust_drift_engine && result.engine.alignment_drift_analyzer && result.engine.confidence_degradation_analyzer && result.engine.trust_degradation_analyzer && result.engine.drift_classification_framework && result.engine.drift_severity_engine && result.engine.historical_trend_analyzer && result.engine.root_cause_analysis_engine && result.engine.drift_alert_engine && result.engine.drift_evidence_registry && result.engine.governance_integration_contracts;
  const classification_valid = verifyHashed(result.classification) && result.classification.categories.length === 7 && result.classification.indicators.length > 0 && result.classification.deterministic;
  const severity_valid = verifyHashed(result.severity) && result.severity.severity === "MODERATE" && result.severity.deterministic_thresholds;
  const trends_valid = verifyHashed(result.trends) && result.trends.methods.length === 9 && result.trends.historical_comparison && result.trends.replay_comparison;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.verifiable && result.evidence.evidence_refs.length > 0 && result.evidence.lineage_refs.length > 0 && result.evidence.replay_refs.length > 0;
  const record_valid = verifyHashed(result.record) && result.record.historical_baseline.length > 0 && result.record.current_state.length > 0 && result.record.supporting_evidence.length > 0 && result.record.root_cause_analysis.length > 0;
  const report_valid = verifyHashed(result.report) && result.report.report_id.length > 0 && result.report.explanation.length > 0 && result.report.governance_recommendations.length > 0;
  const alerts_valid = result.alerts.length > 0 && result.alerts.every((item) => verifyHashed(item) && item.alert_id.length > 0);
  const boundary_valid = verifyHashed(result.boundary) && !result.boundary.trust_standing_recalculated && !result.boundary.trust_standing_modified && !result.boundary.trust_decision_issued && !result.boundary.trust_monitoring_dashboard_executed && !result.boundary.governance_review_executed && !result.boundary.safety_qualification_executed && result.boundary.tenant_isolation_preserved;
  const certification_valid = verifyHashed(result.certification) && result.certification.outcome === "PASS" && result.certification.phase_ready && result.certification.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && engine_valid && classification_valid && severity_valid && trends_valid && evidence_valid && record_valid && report_valid && alerts_valid && boundary_valid && certification_valid;
  return nested({ valid, outcome: result.certification.outcome, replay_hash_valid, integrity_hash_valid, engine_valid, classification_valid, severity_valid, trends_valid, evidence_valid, record_valid, report_valid, alerts_valid, boundary_valid, certification_valid, failures: result.certification.failures });
}

export function replayTrustDriftDetection(result = runTrustDriftDetection()): boolean {
  const replayed = runTrustDriftDetection();
  return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustDriftDetection(result).valid;
}

export function getTrustDriftDetectionBundle(): TrustDriftBundle {
  const result = runTrustDriftDetection();
  return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_trust_drift: true, owns_alignment_drift: true, owns_confidence_degradation: true, owns_trust_degradation: true, recalculates_trust_standing: false, performs_monitoring_dashboards: false, executes_governance_reviews: false, qualifies_safety: false, issues_trust_decisions: false }), result, validation: validateTrustDriftDetection(result) });
}

export const TrustDriftDetectionService = Object.freeze({ run: runTrustDriftDetection, validate: validateTrustDriftDetection, replay: replayTrustDriftDetection });
