export type GovernanceDriftErrorCode =
  | "GOVERNANCE_DRIFT_POLICY_DIVERGENCE"
  | "GOVERNANCE_DRIFT_REPLAY_MISMATCH"
  | "GOVERNANCE_DRIFT_CONFIDENCE_CORRUPTION"
  | "GOVERNANCE_DRIFT_ESCALATION_SUPPRESSION"
  | "GOVERNANCE_DRIFT_DEPENDENCY_CORRUPTION"
  | "GOVERNANCE_DRIFT_RECOMMENDATION_DIVERGENCE"
  | "GOVERNANCE_DRIFT_VALIDATOR_MISMATCH"
  | "GOVERNANCE_DRIFT_TOPOLOGY_DRIFT"
  | "GOVERNANCE_DRIFT_ISOLATION_VIOLATION"
  | "GOVERNANCE_DRIFT_RUNTIME_MUTATION"
  | "GOVERNANCE_DRIFT_REPLAY_REPAIR"
  | "GOVERNANCE_DRIFT_CURRENT_STATE_SUBSTITUTION"
  | "GOVERNANCE_DRIFT_FAIL_CLOSED";

export type GovernanceDriftError = Readonly<{
  code: GovernanceDriftErrorCode;
  message: string;
  path?: string;
}>;
