import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runProvingAdversarialTestingFramework, validateProvingAdversarialTestingFramework } from "@/services/proving-adversarial-testing-framework";
import type { DegradationMode, DisasterScenario, RecoveryScenario, ResilienceBundle, ResilienceFailure, ResilienceInput, ResilienceOutcome, ResilienceResult, ResilienceValidation, ResilienceValidationScenario } from "@/types/proving-resilience-recovery-validation";

const VERSION = "proving-resilience-recovery-validation/v6.8" as const;
const IDENTIFIER = "ProvingResilienceRecoveryValidation" as const;
const RECOVERY_SCENARIOS = Object.freeze<RecoveryScenario[]>(["SERVICE_CRASH", "NODE_FAILURE", "CLUSTER_OUTAGE", "NETWORK_PARTITION", "STORAGE_CORRUPTION", "DATABASE_OUTAGE", "CONFIGURATION_CORRUPTION", "REGISTRY_CORRUPTION", "IDENTITY_FAILURE", "AUTHENTICATION_OUTAGE", "POLICY_CORRUPTION", "GOVERNANCE_INTERRUPTION", "TRUST_SUSPENSION", "REPLAY_INTERRUPTION", "ORCHESTRATION_FAILURE", "COMPLETE_ENVIRONMENT_LOSS"]);
const DISASTER_SCENARIOS = Object.freeze<DisasterScenario[]>(["DATA_CENTER_FAILURE", "REGIONAL_OUTAGE", "CLOUD_PROVIDER_OUTAGE", "STORAGE_LOSS", "REGISTRY_DESTRUCTION", "BACKUP_RECOVERY", "CONFIGURATION_RESTORATION", "TENANT_RESTORATION"]);
const DEGRADATION_MODES = Object.freeze<DegradationMode[]>(["READ_ONLY", "ADVISORY_ONLY", "GOVERNANCE_ONLY", "OPERATOR_ONLY", "REDUCED_AUTONOMY", "DEGRADED_TRUST", "PARTIAL_CAPABILITY"]);
let adversarialBaseline: ReturnType<typeof runProvingAdversarialTestingFramework> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly ResilienceFailure[], failure: ResilienceFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: ResilienceValidationScenario): ResilienceFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function outcome(failures: readonly ResilienceFailure[]): ResilienceOutcome { if ((has(failures, "ENVIRONMENT_RESTORATION_FAILED") || has(failures, "BACKUP_RESTORATION_FAILED") || has(failures, "RECOVERY_WORKFLOW_FAILED")) && !has(failures, "FAIL_SAFE_BEHAVIOR_FAILED")) return "FAIL_SAFE"; return failures.length ? "FAIL" : "PASS"; }
function resultReplayHash(result: Omit<ResilienceResult, "replay_hash" | "integrity_hash">): string { return hash({ framework: result.framework.integrity_hash, failure_injection: result.failure_injection.integrity_hash, recovery_engine: result.recovery_engine.integrity_hash, failover: result.failover_report.integrity_hash, disaster_recovery: result.disaster_recovery_report.integrity_hash, degradation: result.degradation_report.integrity_hash, recovery_replay: result.recovery_replay_report.integrity_hash, evidence: result.evidence.integrity_hash, gates: result.gates.integrity_hash, invariants: result.invariants.integrity_hash, boundaries: result.boundaries.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<ResilienceResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.readiness.outcome, replay_hash: result.replay_hash }); }

export function runProvingResilienceRecoveryValidation(input: ResilienceInput = {}): ResilienceResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<ResilienceFailure>(direct ? [direct] : []);
  adversarialBaseline ??= runProvingAdversarialTestingFramework();
  const adversarialInvalid = !validateProvingAdversarialTestingFramework(adversarialBaseline).valid || has(scenarioFailures, "P6_7_ADVERSARIAL_TESTING_INVALID");
  const dependencyFailures = freezeArray<ResilienceFailure>(adversarialInvalid ? ["P6_7_ADVERSARIAL_TESTING_INVALID"] : []);
  const failures = freezeArray([...new Set([...scenarioFailures, ...dependencyFailures])]);
  const frameworkOk = !has(failures, "RESILIENCE_FRAMEWORK_MISSING");
  const injectionOk = !has(failures, "FAILURE_INJECTION_LIBRARY_MISSING") && !has(failures, "FAILURE_INJECTION_NONDETERMINISTIC");
  const recoveryOk = !has(failures, "RECOVERY_VALIDATION_ENGINE_MISSING") && !has(failures, "RECOVERY_WORKFLOW_FAILED") && !has(failures, "DETERMINISTIC_RESTORATION_FAILED") && !has(failures, "STATE_PRESERVATION_FAILED") && !has(failures, "CONSISTENCY_VALIDATION_FAILED");
  const failoverOk = !has(failures, "FAILOVER_VALIDATION_MISSING") && !has(failures, "FAILOVER_EXECUTION_FAILED");
  const disasterOk = !has(failures, "DISASTER_RECOVERY_VALIDATION_MISSING") && !has(failures, "ENVIRONMENT_RESTORATION_FAILED") && !has(failures, "BACKUP_RESTORATION_FAILED") && !has(failures, "TRUST_RESTORATION_FAILED");
  const degradationOk = !has(failures, "DEGRADATION_TESTING_MISSING") && !has(failures, "GRACEFUL_DEGRADATION_FAILED") && !has(failures, "POLICY_ENFORCEMENT_DURING_DEGRADATION_FAILED") && !has(failures, "OPERATOR_VISIBILITY_FAILED");
  const replayOk = !has(failures, "RECOVERY_REPLAY_VALIDATION_MISSING") && !has(failures, "RECOVERY_REPLAY_DIVERGED") && !has(failures, "REPEATABLE_RECOVERY_FAILED") && !adversarialInvalid;
  const evidenceOk = !has(failures, "RECOVERY_EVIDENCE_MISSING") && !has(failures, "RECOVERY_EVIDENCE_MUTATED") && !has(failures, "RECOVERY_LINEAGE_INCOMPLETE");
  const governanceOk = !has(failures, "GOVERNANCE_PRESERVATION_FAILED");
  const trustOk = !has(failures, "TRUST_TRANSITION_NONCOMPLIANT");
  const failSafeOk = !has(failures, "FAIL_SAFE_BEHAVIOR_FAILED");
  const operationsOk = !has(failures, "OPERATIONS_NOT_MAINTAINED");
  const objectivesOk = !has(failures, "RESILIENCE_OBJECTIVES_NOT_MET");
  const certificationOk = !has(failures, "RECOVERY_CERTIFICATION_NOT_READY");
  const boundariesOk = !has(failures, "FUNCTIONAL_CORRECTNESS_OWNERSHIP_VIOLATION") && !has(failures, "PRODUCTION_INCIDENT_RESPONSE_OWNERSHIP_VIOLATION") && !has(failures, "TRUST_DECISION_OWNERSHIP_VIOLATION");
  const framework = nested({ framework_id: frameworkOk ? `framework:p6.8:${input.seed ?? "canonical"}` : "", test_engine: frameworkOk, orchestration: frameworkOk, scheduling: frameworkOk, policies: frameworkOk, execution: frameworkOk && operationsOk, deterministic: frameworkOk && injectionOk && replayOk });
  const failure_injection = nested({ library_id: injectionOk ? "failure-library:p6.8:deterministic" : "", service_failures: injectionOk, infrastructure_failures: injectionOk, dependency_failures: injectionOk, configuration_failures: injectionOk, storage_failures: injectionOk, network_failures: injectionOk, identity_failures: injectionOk, deterministic: injectionOk });
  const recovery_engine = nested({ engine_id: recoveryOk ? "recovery-engine:p6.8" : "", workflows: recoveryOk ? RECOVERY_SCENARIOS : freezeArray<RecoveryScenario>([]), workflow_execution: recoveryOk, deterministic_restoration: recoveryOk, state_preservation: recoveryOk, consistency_validation: recoveryOk, evidence_preservation: recoveryOk && evidenceOk, governance_preservation: recoveryOk && governanceOk, trust_transition_compliance: recoveryOk && trustOk });
  const failover_report = nested({ report_id: failoverOk ? "report:p6.8:failover" : "", active_active: failoverOk, active_passive: failoverOk, quorum_failover: failoverOk, orchestration_failover: failoverOk, tenant_failover: failoverOk, service_relocation: failoverOk, deterministic: failoverOk && injectionOk, evidence_refs: evidenceOk ? freezeArray(["evidence:p6.8:failover"]) : freezeArray<string>([]) });
  const disaster_recovery_report = nested({ report_id: disasterOk ? "report:p6.8:disaster-recovery" : "", scenarios: disasterOk ? DISASTER_SCENARIOS : freezeArray<DisasterScenario>([]), backup_restoration: disasterOk, infrastructure_recreation: disasterOk, environment_rebuild: disasterOk, registry_recovery: disasterOk, replay_restoration: disasterOk && replayOk, trust_restoration: disasterOk && trustOk, evidence_refs: evidenceOk ? freezeArray(["evidence:p6.8:disaster-recovery"]) : freezeArray<string>([]) });
  const degradation_report = nested({ report_id: degradationOk ? "report:p6.8:degradation" : "", modes: degradationOk ? DEGRADATION_MODES : freezeArray<DegradationMode>([]), reduced_capability: degradationOk, restricted_autonomy: degradationOk, operator_takeover: degradationOk, policy_restriction: degradationOk, degraded_trust: degradationOk, degraded_services: degradationOk, graceful: degradationOk && failSafeOk, evidence_refs: evidenceOk ? freezeArray(["evidence:p6.8:degradation"]) : freezeArray<string>([]) });
  const recovery_replay_report = nested({ report_id: replayOk ? "report:p6.8:recovery-replay" : "", replay_ref: "proving-replay-validation-framework/v6.6" as const, adversarial_ref: "proving-adversarial-testing-framework/v6.7" as const, identical_recovery_replay: replayOk, deterministic_restoration: replayOk && recoveryOk, repeatable_recovery: replayOk, divergence_analyzed: replayOk, evidence_refs: evidenceOk ? freezeArray([adversarialBaseline.replay_attack_report.report_id, "evidence:p6.8:recovery-replay"]) : freezeArray<string>([]) });
  const evidence = nested({ evidence_id: evidenceOk ? "evidence:p6.8:resilience-recovery" : "", resilience_execution: evidenceOk ? freezeArray([framework.framework_id]) : freezeArray<string>([]), recovery_execution: evidenceOk ? freezeArray([recovery_engine.engine_id]) : freezeArray<string>([]), failover: evidenceOk ? freezeArray([failover_report.report_id]) : freezeArray<string>([]), disaster_recovery: evidenceOk ? freezeArray([disaster_recovery_report.report_id]) : freezeArray<string>([]), degradation: evidenceOk ? freezeArray([degradation_report.report_id]) : freezeArray<string>([]), replay_validation: evidenceOk ? freezeArray([recovery_replay_report.report_id]) : freezeArray<string>([]), trust_restoration: evidenceOk ? freezeArray(["trust:p6.8:restored"]) : freezeArray<string>([]), governance_preservation: evidenceOk ? freezeArray(["governance:p6.8:preserved"]) : freezeArray<string>([]), immutable: evidenceOk, traceable: evidenceOk, replayable: evidenceOk, certification_ready: evidenceOk && certificationOk });
  const gates = nested({ gate_id: "P6.8-GATES", recovery_gate: recoveryOk && governanceOk && trustOk && evidenceOk, resilience_gate: frameworkOk && injectionOk && objectivesOk && operationsOk && degradationOk, disaster_recovery_gate: disasterOk && replayOk && evidenceOk && trustOk, degradation_gate: degradationOk && failSafeOk && governanceOk, replay_gate: replayOk && recoveryOk, evidence_gate: evidenceOk && certificationOk, phase_certification: frameworkOk && injectionOk && recoveryOk && failoverOk && disasterOk && degradationOk && replayOk && evidenceOk && governanceOk && trustOk && failSafeOk && operationsOk && objectivesOk && certificationOk && boundariesOk, passed: false });
  const finalGates = nested({ ...gates, passed: gates.recovery_gate && gates.resilience_gate && gates.disaster_recovery_gate && gates.degradation_gate && gates.replay_gate && gates.evidence_gate && gates.phase_certification });
  const invariants = nested({ deterministic_resilience_testing: frameworkOk && injectionOk, deterministic_recovery: recoveryOk && replayOk, governance_maintained: governanceOk, trust_preserved: trustOk, evidence_integrity: evidenceOk, fail_safe_when_unrecoverable: failSafeOk, recovery_replay_equivalence: replayOk });
  const boundaries = nested({ boundary_id: "boundaries:p6.8", owns_functional_correctness: false as const, owns_production_incident_response: false as const, owns_trust_decisions: false as const, owns_runtime_security_monitoring: false as const });
  const derivedFailures = freezeArray([...new Set([...failures, ...(!frameworkOk ? ["RESILIENCE_FRAMEWORK_MISSING" as const] : []), ...(!injectionOk ? ["FAILURE_INJECTION_LIBRARY_MISSING" as const] : []), ...(!recoveryOk ? ["RECOVERY_VALIDATION_ENGINE_MISSING" as const] : []), ...(!failoverOk ? ["FAILOVER_VALIDATION_MISSING" as const] : []), ...(!disasterOk ? ["DISASTER_RECOVERY_VALIDATION_MISSING" as const] : []), ...(!degradationOk ? ["DEGRADATION_TESTING_MISSING" as const] : []), ...(!replayOk ? ["RECOVERY_REPLAY_VALIDATION_MISSING" as const] : []), ...(!evidenceOk ? ["RECOVERY_EVIDENCE_MISSING" as const] : []), ...(!governanceOk ? ["GOVERNANCE_PRESERVATION_FAILED" as const] : []), ...(!trustOk ? ["TRUST_TRANSITION_NONCOMPLIANT" as const] : []), ...(!failSafeOk ? ["FAIL_SAFE_BEHAVIOR_FAILED" as const] : []), ...(!operationsOk ? ["OPERATIONS_NOT_MAINTAINED" as const] : []), ...(!objectivesOk ? ["RESILIENCE_OBJECTIVES_NOT_MET" as const] : []), ...(!certificationOk ? ["RECOVERY_CERTIFICATION_NOT_READY" as const] : []), ...(!boundariesOk ? ["FUNCTIONAL_CORRECTNESS_OWNERSHIP_VIOLATION" as const] : [])])]);
  const finalOutcome = outcome(derivedFailures);
  const readiness = nested({ readiness_id: "P6.8-RESILIENCE-RECOVERY-READINESS-001", outcome: finalOutcome, phase_ready: finalOutcome === "PASS", framework_ready: frameworkOk, failure_injection_ready: injectionOk, recovery_ready: recoveryOk, failover_ready: failoverOk, disaster_recovery_ready: disasterOk, degradation_ready: degradationOk, replay_ready: replayOk, evidence_ready: evidenceOk, gates_passed: finalGates.passed, invariants_satisfied: invariants.deterministic_resilience_testing && invariants.deterministic_recovery && invariants.governance_maintained && invariants.trust_preserved && invariants.evidence_integrity && invariants.fail_safe_when_unrecoverable && invariants.recovery_replay_equivalence, boundaries_respected: boundariesOk, failures: derivedFailures });
  const base: Omit<ResilienceResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, adversarial_testing_ref: "proving-adversarial-testing-framework/v6.7", framework, failure_injection, recovery_engine, failover_report, disaster_recovery_report, degradation_report, recovery_replay_report, evidence, gates: finalGates, invariants, boundaries, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateProvingResilienceRecoveryValidation(result?: ResilienceResult): ResilienceValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, framework_valid: false, failure_injection_valid: false, recovery_valid: false, failover_valid: false, disaster_recovery_valid: false, degradation_valid: false, replay_valid: false, evidence_valid: false, gates_valid: false, invariants_valid: false, boundaries_valid: false, readiness_valid: false, failures: freezeArray(["RESILIENCE_FRAMEWORK_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const framework_valid = verifyHashed(result.framework) && result.framework.test_engine && result.framework.execution && result.framework.deterministic;
  const failure_injection_valid = verifyHashed(result.failure_injection) && result.failure_injection.deterministic && result.failure_injection.identity_failures;
  const recovery_valid = verifyHashed(result.recovery_engine) && result.recovery_engine.workflows.length === RECOVERY_SCENARIOS.length && result.recovery_engine.deterministic_restoration && result.recovery_engine.governance_preservation && result.recovery_engine.trust_transition_compliance;
  const failover_valid = verifyHashed(result.failover_report) && result.failover_report.deterministic && result.failover_report.tenant_failover && result.failover_report.evidence_refs.length > 0;
  const disaster_recovery_valid = verifyHashed(result.disaster_recovery_report) && result.disaster_recovery_report.scenarios.length === DISASTER_SCENARIOS.length && result.disaster_recovery_report.environment_rebuild && result.disaster_recovery_report.trust_restoration;
  const degradation_valid = verifyHashed(result.degradation_report) && result.degradation_report.modes.length === DEGRADATION_MODES.length && result.degradation_report.graceful && result.degradation_report.operator_takeover && result.degradation_report.policy_restriction;
  const replay_valid = verifyHashed(result.recovery_replay_report) && result.recovery_replay_report.identical_recovery_replay && result.recovery_replay_report.repeatable_recovery && result.recovery_replay_report.divergence_analyzed;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.immutable && result.evidence.traceable && result.evidence.replayable && result.evidence.certification_ready;
  const gates_valid = verifyHashed(result.gates) && result.gates.passed;
  const invariants_valid = verifyHashed(result.invariants) && result.invariants.deterministic_resilience_testing && result.invariants.deterministic_recovery && result.invariants.governance_maintained && result.invariants.trust_preserved && result.invariants.evidence_integrity && result.invariants.fail_safe_when_unrecoverable && result.invariants.recovery_replay_equivalence;
  const boundaries_valid = verifyHashed(result.boundaries) && !result.boundaries.owns_functional_correctness && !result.boundaries.owns_production_incident_response && !result.boundaries.owns_trust_decisions && !result.boundaries.owns_runtime_security_monitoring;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && framework_valid && failure_injection_valid && recovery_valid && failover_valid && disaster_recovery_valid && degradation_valid && replay_valid && evidence_valid && gates_valid && invariants_valid && boundaries_valid && readiness_valid;
  return nested({ valid, outcome: result.readiness.outcome, replay_hash_valid, integrity_hash_valid, framework_valid, failure_injection_valid, recovery_valid, failover_valid, disaster_recovery_valid, degradation_valid, replay_valid, evidence_valid, gates_valid, invariants_valid, boundaries_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayProvingResilienceRecoveryValidation(result = runProvingResilienceRecoveryValidation()): boolean { const replayed = runProvingResilienceRecoveryValidation(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateProvingResilienceRecoveryValidation(result).valid; }
export function getProvingResilienceRecoveryValidationBundle(): ResilienceBundle { const result = runProvingResilienceRecoveryValidation(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_resilience_validation: true, owns_recovery_validation: true, owns_failover_testing: true, owns_disaster_recovery_validation: true, owns_degradation_testing: true, owns_recovery_replay_validation: true, owns_resilience_evidence: true, owns_functional_correctness: false, owns_production_incident_response: false, owns_trust_decisions: false, owns_runtime_security_monitoring: false }), result, validation: validateProvingResilienceRecoveryValidation(result) }); }
export const ProvingResilienceRecoveryValidationService = Object.freeze({ run: runProvingResilienceRecoveryValidation, validate: validateProvingResilienceRecoveryValidation, replay: replayProvingResilienceRecoveryValidation });
