export type EscalationErrorCode =
  | "ESCALATION_GOVERNANCE_MISMATCH"
  | "ESCALATION_REPLAY_AMBIGUITY"
  | "ESCALATION_LINEAGE_MISSING"
  | "ESCALATION_SYNTHETIC_REPLAY_REJECTED"
  | "ESCALATION_APPROVAL_AMBIGUITY"
  | "ESCALATION_POLICY_UNCERTAINTY"
  | "ESCALATION_UNKNOWN_STATE_FREEZE"
  | "ESCALATION_STALE_EVIDENCE"
  | "ESCALATION_EXECUTION_LEAK_REJECTED"
  | "ESCALATION_ORCHESTRATION_LEAK_REJECTED"
  | "ESCALATION_SCHEDULING_REJECTED"
  | "ESCALATION_RETRY_REJECTED"
  | "ESCALATION_REMEDIATION_FORBIDDEN"
  | "ESCALATION_FREEZE_MISMATCH"
  | "ESCALATION_PAUSE_RESUME_FORBIDDEN"
  | "ESCALATION_NON_DETERMINISTIC_OUTPUT";

export type EscalationError = Readonly<{
  code: EscalationErrorCode;
  message: string;
  path: string;
}>;
