import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runAgentRegistry, validateAgentRegistry } from "@/services/agent-registry";
import { runCafConstitutionalFoundation, validateCafConstitutionalFoundation } from "@/services/caf-constitutional-foundation";
import { runLifecycleEngine, validateLifecycleEngine } from "@/services/lifecycle-engine";
import type { CapabilityRegistryBundle, CapabilityRegistryDecision, CapabilityRegistryFailure, CapabilityRegistryInput, CapabilityRegistryResult, CapabilityRegistryScenario, CapabilityRegistryValidation, AuthorityClass, RiskLevel } from "@/types/capability-registry";

const VERSION = "capability-registry/w2.3" as const;
const IDENTIFIER = "CapabilityRegistry" as const;
const RISK_CATEGORIES = Object.freeze(["Constitutional", "Operational", "Security", "Privacy", "Safety", "Financial", "Infrastructure", "External Integration"]);
const RISK_LEVELS = Object.freeze<RiskLevel[]>(["Minimal", "Low", "Moderate", "High", "Critical"]);
const AUTHORITY_CLASSES = Object.freeze<AuthorityClass[]>(["System", "Platform", "Tenant", "Organization", "Operator", "Supervisor", "Autonomous", "External"]);
let constitutionBaseline: ReturnType<typeof runCafConstitutionalFoundation> | undefined;
let agentRegistryBaseline: ReturnType<typeof runAgentRegistry> | undefined;
let lifecycleBaseline: ReturnType<typeof runLifecycleEngine> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly CapabilityRegistryFailure[], failure: CapabilityRegistryFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: CapabilityRegistryScenario): CapabilityRegistryFailure | undefined { return scenario === "BASELINE" || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly CapabilityRegistryFailure[], scenario: CapabilityRegistryScenario): CapabilityRegistryDecision {
  if (has(failures, "W2_0_CAF_CONSTITUTION_INVALID") || has(failures, "W2_1_AGENT_REGISTRY_INVALID") || has(failures, "W2_2_LIFECYCLE_ENGINE_INVALID") || has(failures, "CAPABILITY_IDENTITY_NOT_UNIQUE") || has(failures, "CAPABILITY_IDENTITY_MUTABLE") || has(failures, "CAPABILITY_SCHEMA_INVALID") || has(failures, "CIRCULAR_COMPOSITION_ALLOWED") || has(failures, "DUPLICATE_COMPOSITION_ALLOWED") || has(failures, "UNSUPPORTED_COMPOSITION_ALLOWED") || has(failures, "COMPOSITION_AUTHORITY_INCOMPATIBLE") || has(failures, "COMPOSITION_LIFECYCLE_INCOMPATIBLE") || has(failures, "DEPENDENCY_GRAPH_NON_DETERMINISTIC") || has(failures, "DEPENDENCY_CYCLE_UNDETECTED") || has(failures, "RISK_INHERITANCE_INVALID") || has(failures, "COMPOSITION_RISK_AGGREGATION_FAILED") || has(failures, "AUTHORITY_BINDING_INVALID") || has(failures, "DELEGATION_VALIDATION_FAILED") || has(failures, "EXECUTION_ELIGIBILITY_INVALID") || has(failures, "UNAPPROVED_TOOL_BINDING_ALLOWED") || has(failures, "TOOL_SECURITY_APPROVAL_FAILED") || has(failures, "TOOL_TENANT_RESTRICTION_FAILED") || has(failures, "NON_COMPLIANT_CAPABILITY_ACCEPTED") || has(failures, "REGISTRY_API_NON_DETERMINISTIC") || has(failures, "GOVERNANCE_METADATA_AMBIGUOUS") || has(failures, "CAPABILITY_EVIDENCE_NOT_IMMUTABLE") || has(failures, "CAPABILITY_REPLAY_INVALID")) return "FAIL_CLOSED";
  if (has(failures, "CAPABILITY_REGISTRY_QUALIFICATION_GATE_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP" || scenario === "QUALIFIED_WITH_OBSERVATIONS") return "CONDITIONALLY_QUALIFIED";
  return "CAPABILITY_REGISTRY_QUALIFIED";
}
function resultReplayHash(result: Omit<CapabilityRegistryResult, "replay_hash" | "integrity_hash">): string { return hash({ definition: result.definition_system.integrity_hash, composition: result.composition_engine.integrity_hash, dependency: result.dependency_framework.integrity_hash, risk: result.risk_classification.integrity_hash, authority: result.authority_classification.integrity_hash, tool: result.tool_binding.integrity_hash, validation: result.validation_engine.integrity_hash, apis: result.apis_governance.integrity_hash, evidence: result.evidence.integrity_hash, qualification: result.qualification.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<CapabilityRegistryResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runCapabilityRegistry(input: CapabilityRegistryInput = {}): CapabilityRegistryResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<CapabilityRegistryFailure>(direct ? [direct] : []);
  constitutionBaseline ??= runCafConstitutionalFoundation();
  agentRegistryBaseline ??= runAgentRegistry();
  lifecycleBaseline ??= runLifecycleEngine();
  const constitutionInvalid = !validateCafConstitutionalFoundation(constitutionBaseline).valid || has(scenarioFailures, "W2_0_CAF_CONSTITUTION_INVALID");
  const agentRegistryInvalid = !validateAgentRegistry(agentRegistryBaseline).valid || has(scenarioFailures, "W2_1_AGENT_REGISTRY_INVALID");
  const lifecycleInvalid = !validateLifecycleEngine(lifecycleBaseline).valid || has(scenarioFailures, "W2_2_LIFECYCLE_ENGINE_INVALID");
  const failures = freezeArray([...new Set([...scenarioFailures, ...(constitutionInvalid ? ["W2_0_CAF_CONSTITUTION_INVALID" as const] : []), ...(agentRegistryInvalid ? ["W2_1_AGENT_REGISTRY_INVALID" as const] : []), ...(lifecycleInvalid ? ["W2_2_LIFECYCLE_ENGINE_INVALID" as const] : [])])]);
  const definitionOk = !has(failures, "CAPABILITY_DEFINITION_SYSTEM_MISSING") && !has(failures, "CAPABILITY_IDENTITY_NOT_UNIQUE") && !has(failures, "CAPABILITY_IDENTITY_MUTABLE") && !has(failures, "CAPABILITY_SCHEMA_INVALID") && !has(failures, "CAPABILITY_VERSION_REGISTRY_MISSING");
  const compositionOk = !has(failures, "COMPOSITION_ENGINE_MISSING") && !has(failures, "CIRCULAR_COMPOSITION_ALLOWED") && !has(failures, "DUPLICATE_COMPOSITION_ALLOWED") && !has(failures, "UNSUPPORTED_COMPOSITION_ALLOWED") && !has(failures, "COMPOSITION_AUTHORITY_INCOMPATIBLE") && !has(failures, "COMPOSITION_LIFECYCLE_INCOMPATIBLE");
  const dependencyOk = !has(failures, "DEPENDENCY_FRAMEWORK_MISSING") && !has(failures, "DEPENDENCY_GRAPH_NON_DETERMINISTIC") && !has(failures, "DEPENDENCY_CYCLE_UNDETECTED") && !has(failures, "DEPENDENCY_HEALTH_MISSING");
  const riskOk = !has(failures, "RISK_CLASSIFICATION_MISSING") && !has(failures, "RISK_INHERITANCE_INVALID") && !has(failures, "COMPOSITION_RISK_AGGREGATION_FAILED") && !has(failures, "MITIGATION_REQUIREMENTS_MISSING");
  const authorityOk = !has(failures, "AUTHORITY_CLASSIFICATION_MISSING") && !has(failures, "AUTHORITY_BINDING_INVALID") && !has(failures, "DELEGATION_VALIDATION_FAILED") && !has(failures, "EXECUTION_ELIGIBILITY_INVALID");
  const toolOk = !has(failures, "TOOL_BINDING_FRAMEWORK_MISSING") && !has(failures, "UNAPPROVED_TOOL_BINDING_ALLOWED") && !has(failures, "TOOL_SECURITY_APPROVAL_FAILED") && !has(failures, "TOOL_TENANT_RESTRICTION_FAILED") && !has(failures, "TOOL_TRUST_REQUIREMENT_MISSING");
  const validationOk = !has(failures, "VALIDATION_ENGINE_MISSING") && !has(failures, "NON_COMPLIANT_CAPABILITY_ACCEPTED") && !has(failures, "NAMESPACE_VALIDATION_FAILED");
  const apisOk = !has(failures, "REGISTRY_APIS_MISSING") && !has(failures, "REGISTRY_API_NON_DETERMINISTIC") && !has(failures, "GOVERNANCE_INTEGRATION_MISSING") && !has(failures, "GOVERNANCE_METADATA_AMBIGUOUS");
  const evidenceOk = !has(failures, "CAPABILITY_EVIDENCE_MISSING") && !has(failures, "CAPABILITY_EVIDENCE_NOT_IMMUTABLE") && !has(failures, "CAPABILITY_REPLAY_INVALID");
  const decision = decisionFor(failures, scenario);
  const qualified = decision === "CAPABILITY_REGISTRY_QUALIFIED";
  const definition_system = nested({ system_id: definitionOk ? `system:w2.3:capability-definition:${input.seed ?? "canonical"}` : "", capability_schema: definitionOk, metadata_repository: definitionOk, version_registry: definitionOk, immutable_identity: definitionOk, unique_identity: definitionOk, lifecycle_requirements: definitionOk, runtime_requirements: definitionOk, evidence_requirements: definitionOk });
  const composition_engine = nested({ engine_id: compositionOk ? "engine:w2.3:capability-composition" : "", hierarchical_composition: compositionOk, reusable_modules: compositionOk, inheritance: compositionOk, specialization: compositionOk, aggregation: compositionOk, orchestration: compositionOk, nested_graphs: compositionOk, circular_detection: compositionOk, duplicate_detection: compositionOk, unsupported_rejection: compositionOk, authority_compatibility: compositionOk, lifecycle_compatibility: compositionOk });
  const dependency_framework = nested({ framework_id: dependencyOk ? "framework:w2.3:capability-dependencies" : "", required_capabilities: dependencyOk, optional_capabilities: dependencyOk, runtime_services: dependencyOk, external_services: dependencyOk, registry_dependencies: dependencyOk, infrastructure_dependencies: dependencyOk, policy_dependencies: dependencyOk, security_dependencies: dependencyOk, dependency_lineage: dependencyOk, deterministic_graph: dependencyOk, cycle_free: dependencyOk, dependency_health: dependencyOk });
  const risk_classification = nested({ registry_id: riskOk ? "registry:w2.3:capability-risk" : "", categories: riskOk ? freezeArray(RISK_CATEGORIES) : freezeArray<string>([]), levels: riskOk ? freezeArray(RISK_LEVELS) : freezeArray<RiskLevel>([]), risk_inheritance: riskOk, composition_risk_aggregation: riskOk, policy_compatibility: riskOk, mitigation_requirements: riskOk, risk_matrix: riskOk });
  const authority_classification = nested({ registry_id: authorityOk ? "registry:w2.3:capability-authority" : "", authority_classes: authorityOk ? freezeArray(AUTHORITY_CLASSES) : freezeArray<AuthorityClass>([]), execution_authority: authorityOk, approval_authority: authorityOk, delegation_authority: authorityOk, escalation_authority: authorityOk, revocation_authority: authorityOk, constitutional_compliance: authorityOk, authority_inheritance: authorityOk, delegation_validation: authorityOk, execution_rules: authorityOk });
  const tool_binding = nested({ registry_id: toolOk ? "registry:w2.3:tool-bindings" : "", approved_tools: toolOk, apis: toolOk, services: toolOk, connectors: toolOk, runtimes: toolOk, models: toolOk, external_systems: toolOk, authority_compatibility: toolOk, security_approval: toolOk, tenant_restrictions: toolOk, version_compatibility: toolOk, trust_requirements: toolOk, invocation_policies: toolOk });
  const validation_engine = nested({ engine_id: validationOk ? "engine:w2.3:capability-validation" : "", schema_validation: validationOk, dependency_validation: validationOk, authority_validation: validationOk, lifecycle_validation: validationOk, composition_validation: validationOk, policy_validation: validationOk, tool_validation: validationOk, certification_validation: validationOk, namespace_validation: validationOk, non_compliant_rejection: validationOk });
  const apis_governance = nested({ api_id: apisOk ? "api:w2.3:capability-registry" : "", register_capability: apisOk, update_capability: apisOk, retrieve_capability: apisOk, search_capability: apisOk, validate_capability: apisOk, resolve_dependencies: apisOk, resolve_composition: apisOk, resolve_authority: apisOk, resolve_tool_bindings: apisOk, deterministic_results: apisOk, governance_events: apisOk, policy_engine_integration: apisOk, safety_gate_integration: apisOk, planning_engine_integration: apisOk, runtime_orchestrator_integration: apisOk, replay_integration: apisOk });
  const evidence = nested({ ledger_id: evidenceOk ? "ledger:w2.3:capability-evidence" : "", records: evidenceOk ? freezeArray(["capability:definition", "capability:composition", "capability:dependency", "capability:risk", "capability:authority", "capability:tool-binding", "capability:validation", "capability:governance"]) : freezeArray<string>([]), definition_evidence: evidenceOk, composition_evidence: evidenceOk, dependency_evidence: evidenceOk, risk_evidence: evidenceOk, authority_evidence: evidenceOk, tool_binding_evidence: evidenceOk, validation_evidence: evidenceOk, governance_evidence: evidenceOk, immutable: evidenceOk, replayable: evidenceOk });
  const qualification = nested({ report_id: "report:w2.3:capability-registry-qualification", unique_immutable_identity: qualified, schema_validation: qualified, composition_validation: qualified, deterministic_cycle_free_dependencies: qualified, risk_classification_complete: qualified, authority_classification_validated: qualified, tool_binding_policy_compliant: qualified, validation_engine_qualified: qualified, deterministic_apis: qualified, governance_integration_verified: qualified, evidence_integrity: qualified, gate_decision: decision });
  const readiness = nested({ readiness_id: "W2.3-CAPABILITY-REGISTRY-READINESS-001", decision, phase_ready: qualified, constitution_ready: !constitutionInvalid, agent_registry_ready: !agentRegistryInvalid, lifecycle_engine_ready: !lifecycleInvalid, definition_ready: definitionOk, composition_ready: compositionOk, dependency_ready: dependencyOk, risk_ready: riskOk, authority_ready: authorityOk, tool_binding_ready: toolOk, validation_ready: validationOk, apis_governance_ready: apisOk, evidence_ready: evidenceOk, qualification_ready: qualified, failures });
  const base: Omit<CapabilityRegistryResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, caf_constitution_ref: "caf-constitutional-foundation/w2.0", agent_registry_ref: "agent-registry/w2.1", lifecycle_engine_ref: "lifecycle-engine/w2.2", definition_system, composition_engine, dependency_framework, risk_classification, authority_classification, tool_binding, validation_engine, apis_governance, evidence, qualification, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateCapabilityRegistry(result?: CapabilityRegistryResult): CapabilityRegistryValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, definition_valid: false, composition_valid: false, dependency_valid: false, risk_valid: false, authority_valid: false, tool_binding_valid: false, validation_engine_valid: false, apis_governance_valid: false, evidence_valid: false, qualification_valid: false, readiness_valid: false, failures: freezeArray(["CAPABILITY_DEFINITION_SYSTEM_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const definition_valid = verifyHashed(result.definition_system) && result.definition_system.capability_schema && result.definition_system.unique_identity && result.definition_system.immutable_identity;
  const composition_valid = verifyHashed(result.composition_engine) && result.composition_engine.circular_detection && result.composition_engine.unsupported_rejection && result.composition_engine.authority_compatibility;
  const dependency_valid = verifyHashed(result.dependency_framework) && result.dependency_framework.deterministic_graph && result.dependency_framework.cycle_free && result.dependency_framework.dependency_health;
  const risk_valid = verifyHashed(result.risk_classification) && result.risk_classification.categories.length === 8 && result.risk_classification.levels.length === 5 && result.risk_classification.composition_risk_aggregation;
  const authority_valid = verifyHashed(result.authority_classification) && result.authority_classification.authority_classes.length === 8 && result.authority_classification.constitutional_compliance && result.authority_classification.execution_rules;
  const tool_binding_valid = verifyHashed(result.tool_binding) && result.tool_binding.approved_tools && result.tool_binding.security_approval && result.tool_binding.invocation_policies;
  const validation_engine_valid = verifyHashed(result.validation_engine) && result.validation_engine.schema_validation && result.validation_engine.non_compliant_rejection && result.validation_engine.namespace_validation;
  const apis_governance_valid = verifyHashed(result.apis_governance) && result.apis_governance.register_capability && result.apis_governance.deterministic_results && result.apis_governance.runtime_orchestrator_integration;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.records.length >= 8 && result.evidence.immutable && result.evidence.replayable;
  const qualification_valid = verifyHashed(result.qualification) && result.qualification.unique_immutable_identity && result.qualification.governance_integration_verified && result.qualification.gate_decision === "CAPABILITY_REGISTRY_QUALIFIED";
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && definition_valid && composition_valid && dependency_valid && risk_valid && authority_valid && tool_binding_valid && validation_engine_valid && apis_governance_valid && evidence_valid && qualification_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, definition_valid, composition_valid, dependency_valid, risk_valid, authority_valid, tool_binding_valid, validation_engine_valid, apis_governance_valid, evidence_valid, qualification_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayCapabilityRegistry(result = runCapabilityRegistry()): boolean { const replayed = runCapabilityRegistry(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateCapabilityRegistry(result).valid; }
export function getCapabilityRegistryBundle(): CapabilityRegistryBundle { const result = runCapabilityRegistry(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_capability_definitions: true, owns_capability_composition: true, owns_capability_dependencies: true, owns_risk_classification: true, owns_authority_classification: true, owns_tool_bindings: true, owns_capability_validation: true, owns_capability_apis: true, owns_governance_integration: true, owns_capability_evidence: true, qualification_gate: "Capability Registry Qualification Gate" }), result, validation: validateCapabilityRegistry(result) }); }
export const CapabilityRegistryService = Object.freeze({ run: runCapabilityRegistry, validate: validateCapabilityRegistry, replay: replayCapabilityRegistry });
