import { prisma } from "@/src/server/db/prisma";
import type { SkillEdge, SkillEvidence, SkillGraphRepository, SkillNode } from "@/types/learning-constitution";

const node = (value: { id: string; slug: string; name: string; description: string; status: string; modelVersion: string; createdAt: Date; updatedAt: Date }): SkillNode => ({ id: value.id, slug: value.slug, name: value.name, description: value.description, status: value.status as SkillNode["status"], prerequisites: [], mastery: null, confidence: 0, last_evaluated: null, retention_score: null, evidence: [], created_at: value.createdAt.toISOString(), updated_at: value.updatedAt.toISOString(), model_version: value.modelVersion });
const edge = (value: { id: string; fromSkillId: string; toSkillId: string; type: string; strength: number | null; rationale: string; createdAt: Date }): SkillEdge => ({ id: value.id, from_skill_id: value.fromSkillId, to_skill_id: value.toSkillId, type: value.type as SkillEdge["type"], ...(value.strength === null ? {} : { strength: value.strength }), rationale: value.rationale, created_at: value.createdAt.toISOString() });
const evidence = (value: { id: string; learnerId: string; skillId: string; kind: string; occurredAt: Date; score: number | null; outcome: string; evaluator: string; sourceRef: string | null; notes: string | null; rubricVersion: string | null; assessmentSessionId: string | null; assessmentItemId: string | null; evaluationType: string | null; competencyDimensions: string[] }): SkillEvidence => ({ id: value.id, learner_id: value.learnerId, skill_id: value.skillId, kind: value.kind as SkillEvidence["kind"], occurred_at: value.occurredAt.toISOString(), ...(value.score === null ? {} : { score: value.score }), outcome: value.outcome as SkillEvidence["outcome"], evaluator: value.evaluator as SkillEvidence["evaluator"], ...(value.sourceRef ? { source_ref: value.sourceRef } : {}), ...(value.notes ? { notes: value.notes } : {}), ...(value.rubricVersion ? { rubric_version: value.rubricVersion } : {}), ...(value.assessmentSessionId ? { assessment_session_id: value.assessmentSessionId } : {}), ...(value.assessmentItemId ? { assessment_item_id: value.assessmentItemId } : {}), ...(value.evaluationType ? { evaluation_type: value.evaluationType as SkillEvidence["evaluation_type"] } : {}), ...(value.competencyDimensions.length ? { competency_dimensions: value.competencyDimensions as SkillEvidence["competency_dimensions"] } : {}) });

export class PrismaSkillGraphRepository implements SkillGraphRepository {
  async createNode(item: SkillNode) { const record = await prisma.skillNode.upsert({ where: { id: item.id }, update: {}, create: { id: item.id, slug: item.slug, name: item.name, description: item.description, status: item.status, modelVersion: item.model_version } }); return node(record); }
  async createEdge(item: SkillEdge) { const record = await prisma.skillEdge.upsert({ where: { fromSkillId_toSkillId_type: { fromSkillId: item.from_skill_id, toSkillId: item.to_skill_id, type: item.type } }, update: {}, create: { id: item.id, fromSkillId: item.from_skill_id, toSkillId: item.to_skill_id, type: item.type, strength: item.strength, rationale: item.rationale } }); return edge(record); }
  async appendEvidence(item: SkillEvidence) { const record = await prisma.skillEvidence.upsert({ where: { id: item.id }, update: {}, create: { id: item.id, learnerId: item.learner_id, skillId: item.skill_id, kind: item.kind, occurredAt: new Date(item.occurred_at), score: item.score, outcome: item.outcome, evaluator: item.evaluator, sourceRef: item.source_ref, notes: item.notes, rubricVersion: item.rubric_version, assessmentSessionId: item.assessment_session_id, assessmentItemId: item.assessment_item_id, evaluationType: item.evaluation_type, competencyDimensions: item.competency_dimensions ? [...item.competency_dimensions] : [] } }); return evidence(record); }
  async getNode(id: string) { const record = await prisma.skillNode.findUnique({ where: { id } }); return record ? node(record) : undefined; }
  async findNodeBySlug(slug: string) { const record = await prisma.skillNode.findUnique({ where: { slug } }); return record ? node(record) : undefined; }
  async findAllNodes() { const [records, edges] = await Promise.all([prisma.skillNode.findMany(), prisma.skillEdge.findMany({ where: { type: "PREREQUISITE" } })]); const prerequisites = new Map<string, string[]>(); for (const item of edges) prerequisites.set(item.toSkillId, [...(prerequisites.get(item.toSkillId) ?? []), item.fromSkillId]); return records.map((item) => ({ ...node(item), prerequisites: prerequisites.get(item.id) ?? [] })); }
  async findAllEdges() { return (await prisma.skillEdge.findMany()).map(edge); }
  async findEvidenceBySkillId(skillId: string) { return (await prisma.skillEvidence.findMany({ where: { skillId }, orderBy: { occurredAt: "asc" } })).map(evidence); }
}
