import { runAgentRegistry, validateAgentRegistry } from "@/services/agent-registry";
import { runCafConstitutionalFoundation, validateCafConstitutionalFoundation } from "@/services/caf-constitutional-foundation";
import { runCapabilityRegistry, validateCapabilityRegistry } from "@/services/capability-registry";
import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runLifecycleEngine, validateLifecycleEngine } from "@/services/lifecycle-engine";
import type { CompatibilityOutcome, SkillRegistryBundle, SkillRegistryDecision, SkillRegistryFailure, SkillRegistryInput, SkillRegistryResult, SkillRegistryScenario, SkillRegistryValidation } from "@/types/skill-registry";

const VERSION = "skill-registry/w2.4" as const;
const IDENTIFIER = "SkillRegistry" as const;
const OUTCOMES = Object.freeze<CompatibilityOutcome[]>(["Compatible", "Compatible with Restrictions", "Upgrade Required", "Incompatible"]);
let constitutionBaseline: ReturnType<typeof runCafConstitutionalFoundation> | undefined;
let agentRegistryBaseline: ReturnType<typeof runAgentRegistry> | undefined;
let lifecycleBaseline: ReturnType<typeof runLifecycleEngine> | undefined;
let capabilityRegistryBaseline: ReturnType<typeof runCapabilityRegistry> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly SkillRegistryFailure[], failure: SkillRegistryFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: SkillRegistryScenario): SkillRegistryFailure | undefined { return scenario === "BASELINE" || scenario === "OPERATIONAL_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly SkillRegistryFailure[], scenario: SkillRegistryScenario): SkillRegistryDecision {
  if (has(failures, "W2_0_CAF_CONSTITUTION_INVALID") || has(failures, "W2_1_AGENT_REGISTRY_INVALID") || has(failures, "W2_2_LIFECYCLE_ENGINE_INVALID") || has(failures, "W2_3_CAPABILITY_REGISTRY_INVALID") || has(failures, "SKILL_IDENTITY_NOT_UNIQUE") || has(failures, "SKILL_OWNER_AMBIGUOUS") || has(failures, "UNSIGNED_PACKAGE_ALLOWED") || has(failures, "PACKAGE_INTEGRITY_INVALID") || has(failures, "PACKAGE_NOT_IMMUTABLE") || has(failures, "PACKAGE_NOT_REPRODUCIBLE") || has(failures, "DEPRECATED_SKILL_EXECUTABLE") || has(failures, "REVOKED_SKILL_EXECUTABLE") || has(failures, "RUNTIME_COMPATIBILITY_INVALID") || has(failures, "CAPABILITY_COMPATIBILITY_INVALID") || has(failures, "AUTHORITY_COMPATIBILITY_INVALID") || has(failures, "POLICY_COMPATIBILITY_INVALID") || has(failures, "DEPENDENCY_COMPATIBILITY_INVALID") || has(failures, "LIFECYCLE_COMPATIBILITY_INVALID") || has(failures, "CERTIFICATION_COMPATIBILITY_INVALID") || has(failures, "DEPENDENCY_GRAPH_NON_DETERMINISTIC") || has(failures, "DEPENDENCY_CYCLE_UNDETECTED") || has(failures, "MISSING_DEPENDENCY_ALLOWED") || has(failures, "UNCERTIFIED_SKILL_DEPLOYABLE") || has(failures, "CERTIFICATION_EXPIRATION_IGNORED") || has(failures, "CERTIFICATION_REVOCATION_IGNORED") || has(failures, "DISCOVERY_RESULTS_NON_DETERMINISTIC") || has(failures, "REPLAY_VALIDATION_MISSING") || has(failures, "SECURITY_VALIDATION_MISSING") || has(failures, "TENANT_ISOLATION_FAILED") || has(failures, "GOVERNANCE_POLICY_NOT_ENFORCED") || has(failures, "SKILL_EVIDENCE_NOT_IMMUTABLE") || has(failures, "SKILL_REGISTRY_REPLAY_INVALID")) return "FAIL_CLOSED";
  if (has(failures, "SKILL_REGISTRY_OPERATIONAL_GATE_FAILED")) return "NOT_OPERATIONAL";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP" || scenario === "OPERATIONAL_WITH_OBSERVATIONS") return "CONDITIONALLY_OPERATIONAL";
  return "SKILL_REGISTRY_OPERATIONAL";
}
function resultReplayHash(result: Omit<SkillRegistryResult, "replay_hash" | "integrity_hash">): string { return hash({ registry: result.registry.integrity_hash, packages: result.packages.integrity_hash, versions: result.versions.integrity_hash, dependencies: result.dependencies.integrity_hash, compatibility: result.compatibility.integrity_hash, certification: result.certification.integrity_hash, discovery: result.discovery.integrity_hash, harness: result.test_harness.integrity_hash, apis: result.governance_apis.integrity_hash, evidence: result.evidence.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<SkillRegistryResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runSkillRegistry(input: SkillRegistryInput = {}): SkillRegistryResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<SkillRegistryFailure>(direct ? [direct] : []);
  constitutionBaseline ??= runCafConstitutionalFoundation();
  agentRegistryBaseline ??= runAgentRegistry();
  lifecycleBaseline ??= runLifecycleEngine();
  capabilityRegistryBaseline ??= runCapabilityRegistry();
  const constitutionInvalid = !validateCafConstitutionalFoundation(constitutionBaseline).valid || has(scenarioFailures, "W2_0_CAF_CONSTITUTION_INVALID");
  const agentRegistryInvalid = !validateAgentRegistry(agentRegistryBaseline).valid || has(scenarioFailures, "W2_1_AGENT_REGISTRY_INVALID");
  const lifecycleInvalid = !validateLifecycleEngine(lifecycleBaseline).valid || has(scenarioFailures, "W2_2_LIFECYCLE_ENGINE_INVALID");
  const capabilityRegistryInvalid = !validateCapabilityRegistry(capabilityRegistryBaseline).valid || has(scenarioFailures, "W2_3_CAPABILITY_REGISTRY_INVALID");
  const failures = freezeArray([...new Set([...scenarioFailures, ...(constitutionInvalid ? ["W2_0_CAF_CONSTITUTION_INVALID" as const] : []), ...(agentRegistryInvalid ? ["W2_1_AGENT_REGISTRY_INVALID" as const] : []), ...(lifecycleInvalid ? ["W2_2_LIFECYCLE_ENGINE_INVALID" as const] : []), ...(capabilityRegistryInvalid ? ["W2_3_CAPABILITY_REGISTRY_INVALID" as const] : [])])]);
  const registryOk = !has(failures, "SKILL_REGISTRY_MISSING") && !has(failures, "SKILL_IDENTITY_NOT_UNIQUE") && !has(failures, "SKILL_OWNER_AMBIGUOUS") && !has(failures, "SKILL_CAPABILITY_MAPPING_MISSING") && !has(failures, "SKILL_METADATA_INVALID");
  const packageOk = !has(failures, "PACKAGE_REPOSITORY_MISSING") && !has(failures, "UNSIGNED_PACKAGE_ALLOWED") && !has(failures, "PACKAGE_INTEGRITY_INVALID") && !has(failures, "PACKAGE_NOT_IMMUTABLE") && !has(failures, "PACKAGE_NOT_REPRODUCIBLE");
  const versionOk = !has(failures, "VERSION_MANAGER_MISSING") && !has(failures, "VERSION_LINEAGE_MISSING") && !has(failures, "ROLLBACK_REFERENCES_MISSING") && !has(failures, "DEPRECATED_SKILL_EXECUTABLE") && !has(failures, "REVOKED_SKILL_EXECUTABLE");
  const dependencyOk = !has(failures, "DEPENDENCY_GRAPH_NON_DETERMINISTIC") && !has(failures, "DEPENDENCY_CYCLE_UNDETECTED") && !has(failures, "MISSING_DEPENDENCY_ALLOWED") && !has(failures, "DEPENDENCY_COMPATIBILITY_INVALID");
  const compatibilityOk = !has(failures, "COMPATIBILITY_ENGINE_MISSING") && !has(failures, "RUNTIME_COMPATIBILITY_INVALID") && !has(failures, "CAPABILITY_COMPATIBILITY_INVALID") && !has(failures, "AUTHORITY_COMPATIBILITY_INVALID") && !has(failures, "POLICY_COMPATIBILITY_INVALID") && !has(failures, "DEPENDENCY_COMPATIBILITY_INVALID") && !has(failures, "LIFECYCLE_COMPATIBILITY_INVALID") && !has(failures, "CERTIFICATION_COMPATIBILITY_INVALID");
  const certificationOk = !has(failures, "CERTIFICATION_MANAGER_MISSING") && !has(failures, "UNCERTIFIED_SKILL_DEPLOYABLE") && !has(failures, "CERTIFICATION_EVIDENCE_MISSING") && !has(failures, "CERTIFICATION_EXPIRATION_IGNORED") && !has(failures, "CERTIFICATION_REVOCATION_IGNORED");
  const discoveryOk = !has(failures, "DISCOVERY_ENGINE_MISSING") && !has(failures, "DISCOVERY_RESULTS_NON_DETERMINISTIC");
  const harnessOk = !has(failures, "SKILL_TEST_HARNESS_MISSING") && !has(failures, "REPLAY_VALIDATION_MISSING") && !has(failures, "SECURITY_VALIDATION_MISSING") && !has(failures, "TENANT_ISOLATION_FAILED");
  const governanceOk = !has(failures, "GOVERNANCE_API_MISSING") && !has(failures, "GOVERNANCE_POLICY_NOT_ENFORCED");
  const evidenceOk = !has(failures, "SKILL_EVIDENCE_MISSING") && !has(failures, "SKILL_EVIDENCE_NOT_IMMUTABLE") && !has(failures, "SKILL_REGISTRY_REPLAY_INVALID");
  const decision = decisionFor(failures, scenario);
  const operational = decision === "SKILL_REGISTRY_OPERATIONAL";
  const registry = nested({ registry_id: registryOk ? `registry:w2.4:skills:${input.seed ?? "canonical"}` : "", authoritative_catalog: registryOk, unique_skill_identity: registryOk, metadata_indexing: registryOk, discovery_indexing: registryOk, ownership_binding: registryOk, single_owner: registryOk, capability_mapping: registryOk, runtime_requirements: registryOk, supported_agents: registryOk, certification_status: registryOk, risk_classification: registryOk, authority_requirements: registryOk, tenant_scope: registryOk, lifecycle_state: operational ? "Published" as const : "Draft" as const });
  const packages = nested({ repository_id: packageOk ? "repository:w2.4:skill-packages" : "", executable_logic: packageOk, schemas: packageOk, manifests: packageOk, policies: packageOk, configuration: packageOk, documentation: packageOk, tests: packageOk, certification_artifacts: packageOk, replay_artifacts: packageOk, immutable_packages: packageOk, signed_packages: packageOk, reproducible_packages: packageOk, versioned_packages: packageOk, package_integrity: packageOk });
  const versions = nested({ manager_id: versionOk ? "manager:w2.4:skill-versions" : "", semantic_versions: versionOk, immutable_releases: versionOk, patch_tracking: versionOk, deprecation: versionOk, retirement: versionOk, compatibility_history: versionOk, upgrade_paths: versionOk, rollback_references: versionOk, release_dates: versionOk, lineage: versionOk, change_summary: versionOk, certification_linkage: versionOk });
  const dependencies = nested({ graph_id: dependencyOk ? "graph:w2.4:skill-dependencies" : "", deterministic_resolution: dependencyOk, dependency_existence: dependencyOk, dependency_versions: dependencyOk, circular_detection: dependencyOk, package_integrity: dependencyOk, capability_availability: dependencyOk, authority_compatibility: dependencyOk, certification_compatibility: dependencyOk, cycle_free: dependencyOk });
  const compatibility = nested({ engine_id: compatibilityOk ? "engine:w2.4:skill-compatibility" : "", runtime_compatibility: compatibilityOk, capability_compatibility: compatibilityOk, authority_compatibility: compatibilityOk, policy_compatibility: compatibilityOk, dependency_compatibility: compatibilityOk, package_compatibility: compatibilityOk, lifecycle_compatibility: compatibilityOk, certification_compatibility: compatibilityOk, outcomes: compatibilityOk ? freezeArray(OUTCOMES) : freezeArray<CompatibilityOutcome>([]), deterministic_reports: compatibilityOk });
  const certification = nested({ manager_id: certificationOk ? "manager:w2.4:skill-certification" : "", testing_status: certificationOk, qualification_evidence: certificationOk, replay_validation: certificationOk, security_validation: certificationOk, policy_validation: certificationOk, authority_validation: certificationOk, operational_approval: certificationOk, expiration_tracking: certificationOk, certification_history: certificationOk, revocation: certificationOk, production_blocks_uncertified: certificationOk });
  const discovery = nested({ explorer_id: discoveryOk ? "explorer:w2.4:skill-discovery" : "", search: discoveryOk, filtering: discoveryOk, capability_lookup: discoveryOk, authority_lookup: discoveryOk, certification_lookup: discoveryOk, version_lookup: discoveryOk, dependency_lookup: discoveryOk, dependency_visualization: discoveryOk, version_comparison: discoveryOk, package_browsing: discoveryOk, lineage_exploration: discoveryOk, deterministic_results: discoveryOk });
  const test_harness = nested({ harness_id: harnessOk ? "harness:w2.4:skill-tests" : "", unit_execution: harnessOk, integration_testing: harnessOk, policy_validation: harnessOk, authority_validation: harnessOk, replay_testing: harnessOk, compatibility_testing: harnessOk, regression_testing: harnessOk, certification_testing: harnessOk, functionality_validated: harnessOk, certification_readiness: harnessOk });
  const governance_apis = nested({ api_id: governanceOk ? "api:w2.4:skill-governance" : "", register_skill: governanceOk, update_metadata: governanceOk, retrieve_skill: governanceOk, search_skills: governanceOk, list_versions: governanceOk, view_dependencies: governanceOk, upload_package: governanceOk, retrieve_package: governanceOk, verify_package: governanceOk, download_package: governanceOk, compare_packages: governanceOk, validate_skill: governanceOk, validate_runtime: governanceOk, resolve_dependencies: governanceOk, compatibility_report: governanceOk, submit_certification: governanceOk, retrieve_certification: governanceOk, revoke_certification: governanceOk, certification_history: governanceOk, policy_enforcement: governanceOk, runtime_deployment_eligibility: governanceOk });
  const evidence = nested({ ledger_id: evidenceOk ? "ledger:w2.4:skill-evidence" : "", records: evidenceOk ? freezeArray(["skill:registration", "skill:package-manifest", "skill:version-history", "skill:compatibility-report", "skill:dependency-graph", "skill:certification", "skill:replay", "skill:security", "skill:governance", "skill:lifecycle"]) : freezeArray<string>([]), registration_records: evidenceOk, package_manifests: evidenceOk, version_history: evidenceOk, compatibility_reports: evidenceOk, dependency_graphs: evidenceOk, certification_evidence: evidenceOk, replay_evidence: evidenceOk, security_evidence: evidenceOk, governance_decisions: evidenceOk, lifecycle_records: evidenceOk, immutable: evidenceOk, replayable: evidenceOk });
  const readiness = nested({ readiness_id: "W2.4-SKILL-REGISTRY-READINESS-001", decision, phase_ready: operational, constitution_ready: !constitutionInvalid, agent_registry_ready: !agentRegistryInvalid, lifecycle_engine_ready: !lifecycleInvalid, capability_registry_ready: !capabilityRegistryInvalid, registry_ready: registryOk, package_ready: packageOk, version_ready: versionOk, dependency_ready: dependencyOk, compatibility_ready: compatibilityOk, certification_ready: certificationOk, discovery_ready: discoveryOk, harness_ready: harnessOk, governance_api_ready: governanceOk, evidence_ready: evidenceOk, production_deployment_eligible: operational, failures });
  const base: Omit<SkillRegistryResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, caf_constitution_ref: "caf-constitutional-foundation/w2.0", agent_registry_ref: "agent-registry/w2.1", lifecycle_engine_ref: "lifecycle-engine/w2.2", capability_registry_ref: "capability-registry/w2.3", registry, packages, versions, dependencies, compatibility, certification, discovery, test_harness, governance_apis, evidence, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateSkillRegistry(result?: SkillRegistryResult): SkillRegistryValidation {
  if (!result) return nested({ valid: false, decision: "NOT_OPERATIONAL" as const, replay_hash_valid: false, integrity_hash_valid: false, registry_valid: false, packages_valid: false, versions_valid: false, dependencies_valid: false, compatibility_valid: false, certification_valid: false, discovery_valid: false, harness_valid: false, governance_apis_valid: false, evidence_valid: false, readiness_valid: false, failures: freezeArray(["SKILL_REGISTRY_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const registry_valid = verifyHashed(result.registry) && result.registry.authoritative_catalog && result.registry.unique_skill_identity && result.registry.single_owner && result.registry.capability_mapping;
  const packages_valid = verifyHashed(result.packages) && result.packages.immutable_packages && result.packages.signed_packages && result.packages.reproducible_packages && result.packages.package_integrity;
  const versions_valid = verifyHashed(result.versions) && result.versions.semantic_versions && result.versions.lineage && result.versions.rollback_references && result.versions.certification_linkage;
  const dependencies_valid = verifyHashed(result.dependencies) && result.dependencies.deterministic_resolution && result.dependencies.circular_detection && result.dependencies.cycle_free && result.dependencies.certification_compatibility;
  const compatibility_valid = verifyHashed(result.compatibility) && result.compatibility.outcomes.length === 4 && result.compatibility.runtime_compatibility && result.compatibility.capability_compatibility && result.compatibility.deterministic_reports;
  const certification_valid = verifyHashed(result.certification) && result.certification.qualification_evidence && result.certification.replay_validation && result.certification.security_validation && result.certification.production_blocks_uncertified;
  const discovery_valid = verifyHashed(result.discovery) && result.discovery.search && result.discovery.capability_lookup && result.discovery.lineage_exploration && result.discovery.deterministic_results;
  const harness_valid = verifyHashed(result.test_harness) && result.test_harness.unit_execution && result.test_harness.replay_testing && result.test_harness.certification_testing;
  const governance_apis_valid = verifyHashed(result.governance_apis) && result.governance_apis.register_skill && result.governance_apis.verify_package && result.governance_apis.policy_enforcement && result.governance_apis.runtime_deployment_eligibility;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.records.length >= 10 && result.evidence.immutable && result.evidence.replayable;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.production_deployment_eligible && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && registry_valid && packages_valid && versions_valid && dependencies_valid && compatibility_valid && certification_valid && discovery_valid && harness_valid && governance_apis_valid && evidence_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, registry_valid, packages_valid, versions_valid, dependencies_valid, compatibility_valid, certification_valid, discovery_valid, harness_valid, governance_apis_valid, evidence_valid, readiness_valid, failures: result.readiness.failures });
}

export function replaySkillRegistry(result = runSkillRegistry()): boolean { const replayed = runSkillRegistry(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateSkillRegistry(result).valid; }
export function getSkillRegistryBundle(): SkillRegistryBundle { const result = runSkillRegistry(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_skill_registry: true, owns_skill_packages: true, owns_skill_versioning: true, owns_dependency_resolution: true, owns_compatibility_validation: true, owns_skill_certification: true, owns_skill_discovery: true, owns_skill_test_harness: true, owns_skill_governance_apis: true, owns_skill_evidence: true, operational_gate: "Skill Registry Operational Gate" }), result, validation: validateSkillRegistry(result) }); }
export const SkillRegistryService = Object.freeze({ run: runSkillRegistry, validate: validateSkillRegistry, replay: replaySkillRegistry });
