export const RECOVERY_VERIFICATION_ERROR_CODES = {
  RECOVERY_VERIFICATION_EVIDENCE_MISSING: "RECOVERY_VERIFICATION_EVIDENCE_MISSING",
  RECOVERY_VERIFICATION_CLASSIFICATION_REQUIRED: "RECOVERY_VERIFICATION_CLASSIFICATION_REQUIRED",
  RECOVERY_VERIFICATION_REPLAY_FAILED: "RECOVERY_VERIFICATION_REPLAY_FAILED",
  RECOVERY_VERIFICATION_GOVERNANCE_FAILED: "RECOVERY_VERIFICATION_GOVERNANCE_FAILED",
  RECOVERY_VERIFICATION_DISPUTED: "RECOVERY_VERIFICATION_DISPUTED",
} as const;
