import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runTrustComplianceVerification, validateTrustComplianceVerification } from "@/services/trust-compliance-verification";
import type { SafetyEvidenceStatus, TrustSafetyQualificationBundle, TrustSafetyQualificationFailure, TrustSafetyQualificationInput, TrustSafetyQualificationOutcome, TrustSafetyQualificationResult, TrustSafetyQualificationScenario, TrustSafetyQualificationValidation } from "@/types/trust-safety-qualification";

const VERSION = "trust-safety-qualification/v5.10" as const;
const IDENTIFIER = "TrustSafetyQualification" as const;
const NOW = "2026-07-19T00:00:00.000Z";
let complianceBaseline: ReturnType<typeof runTrustComplianceVerification> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly TrustSafetyQualificationFailure[], failure: TrustSafetyQualificationFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustSafetyQualificationScenario): TrustSafetyQualificationFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function outcome(failures: readonly TrustSafetyQualificationFailure[]): TrustSafetyQualificationOutcome { return has(failures, "GOVERNANCE_REVIEW_REQUIRED") ? "REQUIRES_GOVERNANCE_REVIEW" : failures.length ? "FAIL" : "PASS"; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function resultReplayHash(result: Omit<TrustSafetyQualificationResult, "replay_hash" | "integrity_hash">): string { return hash({ evidence: result.evidence.integrity_hash, safety: result.safety.integrity_hash, compliance: result.compliance.integrity_hash, qualification: result.qualification.integrity_hash, report: result.report.integrity_hash, lineage: result.lineage.integrity_hash, observability: result.observability.integrity_hash, governance: result.governance.integrity_hash, gate: result.gate.integrity_hash, certification: result.certification.integrity_hash }); }
function resultIntegrityHash(result: Omit<TrustSafetyQualificationResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.certification.outcome, replay_hash: result.replay_hash }); }

export function runTrustSafetyQualification(input: TrustSafetyQualificationInput = {}): TrustSafetyQualificationResult {
  const direct = scenarioFailure(input.scenario ?? "BASELINE");
  const scenarioFailures = freezeArray<TrustSafetyQualificationFailure>(direct ? [direct] : []);
  complianceBaseline ??= runTrustComplianceVerification();
  const dependencyFailures = freezeArray<TrustSafetyQualificationFailure>(!validateTrustComplianceVerification(complianceBaseline).valid || has(scenarioFailures, "P5_9_COMPLIANCE_INVALID") ? ["P5_9_COMPLIANCE_INVALID"] : []);
  const failures = freezeArray([...new Set([...scenarioFailures, ...dependencyFailures])]);
  const evidenceStatus: SafetyEvidenceStatus = has(failures, "PROGRAM_3_SAFETY_EVIDENCE_MISSING") || has(failures, "SAFETY_EVIDENCE_INCOMPLETE") ? "MISSING" : has(failures, "STALE_EVIDENCE_QUALIFIED") ? "STALE" : has(failures, "CONFLICTING_EVIDENCE_QUALIFIED") ? "CONFLICTING" : has(failures, "UNVERIFIABLE_EVIDENCE_QUALIFIED") ? "UNVERIFIABLE" : "COMPLETE";
  const failEvidence = evidenceStatus !== "COMPLETE";
  const evidence = nested({ assessment_id: "assessment:safety-evidence:p5.10", evidence_status: evidenceStatus, evidence_refs: failEvidence ? freezeArray<string>([]) : freezeArray(["program-3:safety-gate-evidence", "program-3:runtime-safety-evidence", "program-3:authority-safety-evidence", "program-3:policy-safety-evidence", "program-3:governance-safety-evidence", "program-3:deterministic-replay-evidence", "program-3:operational-safety-findings"]), authentic: !has(failures, "SAFETY_EVIDENCE_INAUTHENTIC"), complete: !failEvidence, deterministic: !has(failures, "SAFETY_EVIDENCE_NONDETERMINISTIC"), reproducible: !has(failures, "SAFETY_EVIDENCE_NOT_REPRODUCIBLE"), replayable: !has(failures, "SAFETY_EVIDENCE_NOT_REPLAYABLE"), immutable: !has(failures, "SAFETY_EVIDENCE_MUTABLE"), traceable: !has(failures, "LINEAGE_INCOMPLETE"), quality_score: failEvidence ? 0 : 0.94 });
  const safety = nested({ assessment_id: "assessment:trust-safety:p5.10", trust_safety: !has(failures, "TRUST_SAFETY_ASSESSMENT_INCOMPLETE"), autonomy_safety: !has(failures, "AUTONOMY_SAFETY_ASSESSMENT_INCOMPLETE"), mission_safety: !has(failures, "MISSION_SAFETY_ASSESSMENT_INCOMPLETE"), governance_safety: !has(failures, "GOVERNANCE_SAFETY_ASSESSMENT_INCOMPLETE"), authority_boundaries: true, operational_boundaries: true, mission_boundaries: true, constitutional_boundaries: true, trust_boundaries: true });
  const compliance = nested({ compliance_id: "compliance:safety:p5.10", constitutional_validation: !has(failures, "CONSTITUTIONAL_COMPLIANCE_INVALID"), authority_validation: !has(failures, "AUTHORITY_COMPLIANCE_INVALID"), policy_validation: !has(failures, "POLICY_COMPLIANCE_INVALID"), governance_validation: !has(failures, "GOVERNANCE_COMPLIANCE_INVALID"), fail_closed_behavior: !has(failures, "FAIL_CLOSED_INVALID"), evidence_refs: evidence.evidence_refs });
  const qualified = evidence.complete && evidence.authentic && evidence.deterministic && evidence.reproducible && evidence.replayable && evidence.immutable && evidence.traceable && safety.trust_safety && safety.autonomy_safety && safety.mission_safety && safety.governance_safety && compliance.constitutional_validation && compliance.authority_validation && compliance.policy_validation && compliance.governance_validation;
  const badEvidenceQualified = (has(failures, "MISSING_EVIDENCE_QUALIFIED") || has(failures, "STALE_EVIDENCE_QUALIFIED") || has(failures, "CONFLICTING_EVIDENCE_QUALIFIED") || has(failures, "UNVERIFIABLE_EVIDENCE_QUALIFIED"));
  const qualificationResult = badEvidenceQualified ? "QUALIFIED" as const : qualified ? "QUALIFIED_WITH_RESTRICTIONS" as const : "FAIL_CLOSED" as const;
  const finding = nested({ finding_id: has(failures, "SAFETY_FINDINGS_MISSING") ? "" : "finding:safety:p5.10", qualification_id: "qualification:safety:p5.10", finding_category: "trust-autonomy-safety", severity: qualified ? "LOW" as const : "HIGH" as const, affected_scope: input.safety_scope ?? "trust-enabled-autonomy", supporting_evidence: evidence.evidence_refs, constitutional_reference: "constitutional:safety:fail-closed", recommended_action: qualified ? "continue qualification path" : "block downstream qualification until evidence is valid" });
  const qualification = nested({ qualification_id: "qualification:safety:p5.10", trust_domain_id: input.trust_domain_id ?? "trust-domain:civitas:root", autonomy_classification: input.autonomy_classification ?? "autonomy-classification:caf:guided", safety_scope: input.safety_scope ?? "trust-enabled-autonomy", evidence_references: evidence.evidence_refs, constitutional_validation: compliance.constitutional_validation, authority_validation: compliance.authority_validation, policy_validation: compliance.policy_validation, governance_validation: compliance.governance_validation, safety_assessment: safety.integrity_hash, qualification_result: qualificationResult, findings: finding.finding_id.length ? freezeArray([finding]) : freezeArray([]), evaluator: "P5.10 Safety Qualification" as const, evaluation_timestamp: NOW });
  const report = nested({ report_id: has(failures, "QUALIFICATION_REPORT_MISSING") ? "" : "report:safety-qualification:p5.10", qualification_scope: qualification.safety_scope, evaluated_entities: freezeArray([qualification.trust_domain_id, qualification.autonomy_classification]), evidence_summary: evidence.complete ? "Program 3 safety evidence consumed and valid." : "Safety evidence invalid or incomplete.", constitutional_summary: compliance.constitutional_validation ? "Constitutional safety compliance verified." : "Constitutional safety compliance failed.", safety_summary: qualified ? "Safety supports trusted operation with restrictions." : "Safety does not support trusted operation.", qualification_result: qualification.qualification_result, findings: qualification.findings.map((item) => item.finding_id), recommendations: freezeArray([qualified ? "proceed to P5.11 readiness" : "require governance review and evidence remediation"]), lineage_reference: "lineage:safety-qualification:p5.10" });
  const lineage = nested({ lineage_id: "lineage:safety-qualification:p5.10", evidence_lineage: has(failures, "LINEAGE_INCOMPLETE") ? freezeArray<string>([]) : evidence.evidence_refs.map((ref) => `lineage:${ref}`), report_lineage: report.report_id.length ? freezeArray([report.report_id]) : freezeArray<string>([]), qualification_lineage: freezeArray([qualification.qualification_id]), complete: !has(failures, "LINEAGE_INCOMPLETE") && evidence.evidence_refs.length > 0 && report.report_id.length > 0, deterministic_replay_refs: freezeArray(["replay:program-3:safety", "replay:p5.10:qualification"]) });
  const observability = nested({ dashboard_id: "dashboard:safety-qualification:p5.10", metrics: has(failures, "OBSERVABILITY_MISSING") ? freezeArray<string>([]) : freezeArray(["safety_qualification_total", "safety_evidence_quality", "safety_fail_closed_total", "safety_replay_success_total"]), monitors_qualification: !has(failures, "OBSERVABILITY_MISSING"), monitors_evaluation: !has(failures, "OBSERVABILITY_MISSING"), monitors_evidence: !has(failures, "OBSERVABILITY_MISSING"), monitors_constitutional: !has(failures, "OBSERVABILITY_MISSING") });
  const governance = nested({ governance_id: "governance:safety-qualification:p5.10", constitutional_governance_integrated: !has(failures, "GOVERNANCE_INTEGRATION_MISSING"), trust_governance_integrated: !has(failures, "GOVERNANCE_INTEGRATION_MISSING"), qualification_governance_integrated: !has(failures, "GOVERNANCE_INTEGRATION_MISSING"), runtime_enforcement_executed: has(failures, "RUNTIME_SAFETY_ENFORCEMENT_EXECUTED"), policy_execution_executed: has(failures, "SAFETY_POLICY_EXECUTED"), evidence_generated: has(failures, "SAFETY_EVIDENCE_GENERATED"), operational_monitoring_owned: has(failures, "OPERATIONAL_MONITORING_OWNED") });
  const gate = nested({ gate_id: "gate:safety-qualification:p5.10", program_3_safety_evidence_consumed: evidence.evidence_refs.length > 0 && !has(failures, "PROGRAM_3_SAFETY_EVIDENCE_MISSING"), trust_safety_evaluation_completed: safety.trust_safety, autonomy_safety_evaluation_completed: safety.autonomy_safety, constitutional_compliance_verified: compliance.constitutional_validation, authority_compliance_verified: compliance.authority_validation, policy_compliance_verified: compliance.policy_validation, governance_compliance_verified: compliance.governance_validation, deterministic_results_produced: !has(failures, "QUALIFICATION_DECISION_NONDETERMINISTIC"), evidence_lineage_preserved: lineage.complete, reports_generated: report.report_id.length > 0, findings_replayable: !has(failures, "QUALIFICATION_DECISION_NONDETERMINISTIC") && evidence.replayable, fail_closed_demonstrated: !badEvidenceQualified && compliance.fail_closed_behavior });
  const boundaryRespected = !governance.runtime_enforcement_executed && !governance.policy_execution_executed && !governance.evidence_generated && !governance.operational_monitoring_owned;
  const derivedFailures = freezeArray([...new Set([...failures, ...(!gate.program_3_safety_evidence_consumed ? ["PROGRAM_3_SAFETY_EVIDENCE_MISSING" as const] : []), ...(!evidence.authentic ? ["SAFETY_EVIDENCE_INAUTHENTIC" as const] : []), ...(!evidence.complete ? ["SAFETY_EVIDENCE_INCOMPLETE" as const] : []), ...(!evidence.deterministic ? ["SAFETY_EVIDENCE_NONDETERMINISTIC" as const] : []), ...(!evidence.reproducible ? ["SAFETY_EVIDENCE_NOT_REPRODUCIBLE" as const] : []), ...(!evidence.replayable ? ["SAFETY_EVIDENCE_NOT_REPLAYABLE" as const] : []), ...(!evidence.immutable ? ["SAFETY_EVIDENCE_MUTABLE" as const] : []), ...(!safety.trust_safety ? ["TRUST_SAFETY_ASSESSMENT_INCOMPLETE" as const] : []), ...(!safety.autonomy_safety ? ["AUTONOMY_SAFETY_ASSESSMENT_INCOMPLETE" as const] : []), ...(!safety.mission_safety ? ["MISSION_SAFETY_ASSESSMENT_INCOMPLETE" as const] : []), ...(!safety.governance_safety ? ["GOVERNANCE_SAFETY_ASSESSMENT_INCOMPLETE" as const] : []), ...(!compliance.constitutional_validation ? ["CONSTITUTIONAL_COMPLIANCE_INVALID" as const] : []), ...(!compliance.authority_validation ? ["AUTHORITY_COMPLIANCE_INVALID" as const] : []), ...(!compliance.policy_validation ? ["POLICY_COMPLIANCE_INVALID" as const] : []), ...(!compliance.governance_validation ? ["GOVERNANCE_COMPLIANCE_INVALID" as const] : []), ...(!compliance.fail_closed_behavior ? ["FAIL_CLOSED_INVALID" as const] : []), ...(!gate.deterministic_results_produced ? ["QUALIFICATION_DECISION_NONDETERMINISTIC" as const] : []), ...(badEvidenceQualified ? [scenarioFailures[0] as TrustSafetyQualificationFailure] : []), ...(qualification.findings.length === 0 ? ["SAFETY_FINDINGS_MISSING" as const] : []), ...(report.report_id.length === 0 ? ["QUALIFICATION_REPORT_MISSING" as const] : []), ...(!lineage.complete ? ["LINEAGE_INCOMPLETE" as const] : []), ...(observability.metrics.length === 0 ? ["OBSERVABILITY_MISSING" as const] : []), ...(!governance.constitutional_governance_integrated ? ["GOVERNANCE_INTEGRATION_MISSING" as const] : []), ...(!boundaryRespected ? [scenarioFailures[0] as TrustSafetyQualificationFailure] : []), ...(!gate.fail_closed_demonstrated ? ["FAIL_CLOSED_INVALID" as const] : []), ...(has(failures, "SAFETY_QUALIFICATION_ARCHITECTURE_MISSING") ? ["SAFETY_QUALIFICATION_ARCHITECTURE_MISSING" as const] : []), ...(has(failures, "SAFETY_VOCABULARY_MISSING") ? ["SAFETY_VOCABULARY_MISSING" as const] : []), ...(has(failures, "EVIDENCE_ASSESSMENT_INCOMPLETE") ? ["EVIDENCE_ASSESSMENT_INCOMPLETE" as const] : []), ...(has(failures, "CERTIFICATION_GATE_INCOMPLETE") ? ["CERTIFICATION_GATE_INCOMPLETE" as const] : [])])]);
  const certification = nested({ certification_id: "P5.10-SAFETY-QUALIFICATION-CERTIFICATION-001", outcome: outcome(derivedFailures), phase_ready: outcome(derivedFailures) === "PASS", evidence_consumed: gate.program_3_safety_evidence_consumed, trust_safety_completed: gate.trust_safety_evaluation_completed, autonomy_safety_completed: gate.autonomy_safety_evaluation_completed, constitutional_compliance_verified: gate.constitutional_compliance_verified, authority_compliance_verified: gate.authority_compliance_verified, policy_compliance_verified: gate.policy_compliance_verified, governance_compliance_verified: gate.governance_compliance_verified, deterministic_qualification: gate.deterministic_results_produced, lineage_preserved: gate.evidence_lineage_preserved, reports_generated: gate.reports_generated, findings_replayable: gate.findings_replayable, fail_closed_verified: gate.fail_closed_demonstrated, boundary_respected: boundaryRespected, failures: derivedFailures });
  const base: Omit<TrustSafetyQualificationResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, trust_compliance_ref: "trust-compliance-verification/v5.9", evidence, safety, compliance, qualification, report, lineage, observability, governance, gate, certification };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustSafetyQualification(result?: TrustSafetyQualificationResult): TrustSafetyQualificationValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, evidence_valid: false, safety_valid: false, compliance_valid: false, qualification_valid: false, report_valid: false, lineage_valid: false, observability_valid: false, governance_valid: false, gate_valid: false, certification_valid: false, failures: freezeArray(["SAFETY_QUALIFICATION_ARCHITECTURE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.evidence_status === "COMPLETE" && result.evidence.authentic && result.evidence.complete && result.evidence.deterministic && result.evidence.reproducible && result.evidence.replayable && result.evidence.immutable && result.evidence.traceable;
  const safety_valid = verifyHashed(result.safety) && result.safety.trust_safety && result.safety.autonomy_safety && result.safety.mission_safety && result.safety.governance_safety;
  const compliance_valid = verifyHashed(result.compliance) && result.compliance.constitutional_validation && result.compliance.authority_validation && result.compliance.policy_validation && result.compliance.governance_validation && result.compliance.fail_closed_behavior;
  const qualification_valid = verifyHashed(result.qualification) && result.qualification.qualification_result === "QUALIFIED_WITH_RESTRICTIONS" && result.qualification.findings.length > 0;
  const report_valid = verifyHashed(result.report) && result.report.report_id.length > 0 && result.report.findings.length > 0 && result.report.lineage_reference.length > 0;
  const lineage_valid = verifyHashed(result.lineage) && result.lineage.complete && result.lineage.evidence_lineage.length > 0 && result.lineage.deterministic_replay_refs.length > 0;
  const observability_valid = verifyHashed(result.observability) && result.observability.metrics.length === 4 && result.observability.monitors_qualification;
  const governance_valid = verifyHashed(result.governance) && result.governance.constitutional_governance_integrated && result.governance.trust_governance_integrated && result.governance.qualification_governance_integrated && !result.governance.runtime_enforcement_executed && !result.governance.policy_execution_executed && !result.governance.evidence_generated && !result.governance.operational_monitoring_owned;
  const gate_valid = verifyHashed(result.gate) && result.gate.program_3_safety_evidence_consumed && result.gate.trust_safety_evaluation_completed && result.gate.autonomy_safety_evaluation_completed && result.gate.deterministic_results_produced && result.gate.fail_closed_demonstrated;
  const certification_valid = verifyHashed(result.certification) && result.certification.outcome === "PASS" && result.certification.phase_ready && result.certification.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && evidence_valid && safety_valid && compliance_valid && qualification_valid && report_valid && lineage_valid && observability_valid && governance_valid && gate_valid && certification_valid;
  return nested({ valid, outcome: result.certification.outcome, replay_hash_valid, integrity_hash_valid, evidence_valid, safety_valid, compliance_valid, qualification_valid, report_valid, lineage_valid, observability_valid, governance_valid, gate_valid, certification_valid, failures: result.certification.failures });
}

export function replayTrustSafetyQualification(result = runTrustSafetyQualification()): boolean {
  const replayed = runTrustSafetyQualification();
  return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustSafetyQualification(result).valid;
}

export function getTrustSafetyQualificationBundle(): TrustSafetyQualificationBundle {
  const result = runTrustSafetyQualification();
  return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_trust_safety: true, owns_autonomy_safety: true, owns_safety_qualification: true, executes_runtime_safety_enforcement: false, executes_safety_policy: false, generates_safety_evidence: false, owns_operational_safety_monitoring: false }), result, validation: validateTrustSafetyQualification(result) });
}

export const TrustSafetyQualificationService = Object.freeze({ run: runTrustSafetyQualification, validate: validateTrustSafetyQualification, replay: replayTrustSafetyQualification });
