<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../Proprium.Application/Proprium.Application.csproj" /><ProjectReference Include="../Proprium.Domain/Proprium.Domain.csproj" /><PackageReference Include="Microsoft.EntityFrameworkCore" /><PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" /><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" /><PackageReference Include="StackExchange.Redis" /></ItemGroup></Project>
