import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runWaveFiveUnifiedPersonalContext, validateWaveFiveUnifiedPersonalContext } from "@/services/wave-five-unified-personal-context";
import type { WaveFivePersonalKnowledgeBundle, WaveFivePersonalKnowledgeDecision, WaveFivePersonalKnowledgeFailure, WaveFivePersonalKnowledgeInput, WaveFivePersonalKnowledgeResult, WaveFivePersonalKnowledgeScenario, WaveFivePersonalKnowledgeValidation } from "@/types/wave-five-personal-knowledge";

const VERSION = "wave-five-personal-knowledge/w5.3" as const;
const IDENTIFIER = "WaveFivePersonalKnowledge" as const;
const UPSTREAM_REFS = Object.freeze(["wave-five-unified-personal-context/w5.2", "wave-five-application-platform/w5.1", "wave-five-application-portfolio-foundation/w5.0"]);
const ENABLES = Object.freeze(["w5.4-personal-intelligence", "w5.5-recommendations-decision-support", "w5.6-automation-workflow-intelligence", "w5.7-adaptive-experiences"]);
let context = runWaveFiveUnifiedPersonalContext();

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly WaveFivePersonalKnowledgeFailure[], failure: WaveFivePersonalKnowledgeFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: WaveFivePersonalKnowledgeScenario): WaveFivePersonalKnowledgeFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly WaveFivePersonalKnowledgeFailure[], scenario?: WaveFivePersonalKnowledgeScenario): WaveFivePersonalKnowledgeDecision {
  const notQualified = new Set<WaveFivePersonalKnowledgeFailure>(["W5_UNIFIED_CONTEXT_INVALID", "KNOWLEDGE_OBJECTS_UNREGISTERED", "KNOWLEDGE_IDENTITY_NONDETERMINISTIC", "KNOWLEDGE_LINEAGE_INCOMPLETE", "GRAPH_RELATIONSHIPS_INVALID", "GRAPH_TRAVERSAL_NONDETERMINISTIC", "GRAPH_INTEGRITY_INVALID", "CONTEXT_REFERENCES_MISSING", "RETRIEVAL_NONDETERMINISTIC", "RETRIEVAL_NOT_EXPLAINABLE", "PROVENANCE_AWARE_RETRIEVAL_MISSING", "RELIABILITY_NOT_CONTINUOUS", "CONFLICT_DETECTION_MISSING", "LOW_CONFIDENCE_NOT_QUEUED", "HUMAN_REVIEW_MISSING", "REVIEW_DECISIONS_NOT_RECORDED", "REVIEW_LINEAGE_MUTABLE", "REVIEW_REPLAY_DIVERGED", "CONTEXT_SYNC_INVALID", "COMPLETE_PROVENANCE_MISSING", "REPLAY_RETRIEVAL_DIVERGED", "REPLAY_REVIEW_DIVERGED"]);
  if (failures.some((failure) => notQualified.has(failure))) return "NOT_QUALIFIED";
  if (has(failures, "PERSONAL_KNOWLEDGE_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_QUALIFIED";
  return "QUALIFIED";
}
function resultReplayHash(result: Omit<WaveFivePersonalKnowledgeResult, "replay_hash" | "integrity_hash">): string { return hash({ registry: result.registry.integrity_hash, graph: result.graph.integrity_hash, retrieval: result.retrieval.integrity_hash, reliability: result.reliability.integrity_hash, review: result.review.integrity_hash, evidence_sync: result.evidence_sync.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<WaveFivePersonalKnowledgeResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runWaveFivePersonalKnowledge(input: WaveFivePersonalKnowledgeInput = {}): WaveFivePersonalKnowledgeResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  context = runWaveFiveUnifiedPersonalContext();
  const failures = freezeArray([...new Set([...(direct ? [direct] : []), ...(!validateWaveFiveUnifiedPersonalContext(context).valid ? ["W5_UNIFIED_CONTEXT_INVALID" as const] : [])])]);
  const registryOk = !has(failures, "KNOWLEDGE_REGISTRY_MISSING") && !has(failures, "KNOWLEDGE_OBJECTS_UNREGISTERED") && !has(failures, "KNOWLEDGE_IDENTITY_NONDETERMINISTIC") && !has(failures, "KNOWLEDGE_METADATA_INVALID") && !has(failures, "KNOWLEDGE_LINEAGE_INCOMPLETE") && !has(failures, "KNOWLEDGE_CLASSIFICATION_MISSING");
  const graphOk = !has(failures, "KNOWLEDGE_GRAPH_MISSING") && !has(failures, "GRAPH_RELATIONSHIPS_INVALID") && !has(failures, "SEMANTIC_LINKS_MISSING") && !has(failures, "GRAPH_TRAVERSAL_NONDETERMINISTIC") && !has(failures, "GRAPH_INTEGRITY_INVALID") && !has(failures, "CONTEXT_REFERENCES_MISSING");
  const retrievalOk = !has(failures, "RETRIEVAL_ENGINE_MISSING") && !has(failures, "RETRIEVAL_NONDETERMINISTIC") && !has(failures, "RETRIEVAL_NOT_EXPLAINABLE") && !has(failures, "PROVENANCE_AWARE_RETRIEVAL_MISSING") && !has(failures, "CONFIDENCE_AWARE_RETRIEVAL_MISSING") && !has(failures, "QUERY_PLANNING_MISSING");
  const reliabilityOk = !has(failures, "RELIABILITY_SCORING_MISSING") && !has(failures, "RELIABILITY_NOT_CONTINUOUS") && !has(failures, "CONFLICT_DETECTION_MISSING") && !has(failures, "EVIDENCE_FRESHNESS_MISSING") && !has(failures, "TRUST_INDICATORS_MISSING") && !has(failures, "RELIABILITY_HISTORY_MISSING");
  const reviewOk = !has(failures, "REVIEW_QUEUE_MISSING") && !has(failures, "LOW_CONFIDENCE_NOT_QUEUED") && !has(failures, "HUMAN_REVIEW_MISSING") && !has(failures, "REVIEW_DECISIONS_NOT_RECORDED") && !has(failures, "REVIEW_LINEAGE_MUTABLE") && !has(failures, "REVIEW_REPLAY_DIVERGED");
  const evidenceOk = !has(failures, "CONTEXT_SYNC_MISSING") && !has(failures, "CONTEXT_SYNC_INVALID") && !has(failures, "COMPLETE_PROVENANCE_MISSING") && !has(failures, "EVIDENCE_LEDGER_MISSING") && !has(failures, "REPLAY_RETRIEVAL_DIVERGED") && !has(failures, "REPLAY_REVIEW_DIVERGED");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "QUALIFIED";
  const registry = nested({ registry_id: registryOk ? "W5.3-KNOWLEDGE-REGISTRY-001" : "", knowledge_identity: registryOk, knowledge_types: registryOk, knowledge_metadata: registryOk, knowledge_ownership: registryOk, knowledge_lifecycle: registryOk, knowledge_versioning: registryOk, knowledge_lineage: registryOk, knowledge_classification: registryOk, every_object_registered: registryOk, identities_deterministic: registryOk, metadata_validated: registryOk, lineage_complete: registryOk });
  const graph = nested({ graph_id: graphOk ? "W5.3-KNOWLEDGE-GRAPH-001" : "", entity_relationships: graphOk, semantic_links: graphOk, temporal_relationships: graphOk, causal_relationships: graphOk, behavioral_relationships: graphOk, preference_relationships: graphOk, goal_relationships: graphOk, context_references: graphOk, graph_traversal: graphOk, dependency_discovery: graphOk, relationship_validation: graphOk, semantic_expansion: graphOk, graph_integrity_verified: graphOk, traversal_deterministic: graphOk });
  const retrieval = nested({ retrieval_id: retrievalOk ? "W5.3-RETRIEVAL-ENGINE-001" : "", knowledge_search: retrievalOk, semantic_retrieval: retrievalOk, context_aware_retrieval: retrievalOk, relevance_ranking: retrievalOk, multi_hop_traversal: retrievalOk, query_planning: retrievalOk, knowledge_assembly: retrievalOk, result_explanation: retrievalOk, deterministic_ranking: retrievalOk, provenance_aware: retrievalOk, source_filtering: retrievalOk, confidence_aware: retrievalOk, traversal_optimized: retrievalOk });
  const reliability = nested({ reliability_id: reliabilityOk ? "W5.3-RELIABILITY-001" : "", reliability_scoring: reliabilityOk, source_consistency: reliabilityOk, evidence_freshness: reliabilityOk, conflict_detection: reliabilityOk, confidence_aggregation: reliabilityOk, trust_indicators: reliabilityOk, verification_status: reliabilityOk, reliability_history: reliabilityOk, continuous_evaluation: reliabilityOk, conflicts_detected_automatically: reliabilityOk, health_metrics: reliabilityOk });
  const review = nested({ review_id: reviewOk ? "W5.3-REVIEW-QUEUE-001" : "", review_queue: reviewOk, human_review: reviewOk, verification_workflow: reviewOk, approval_workflow: reviewOk, rejection_workflow: reviewOk, merge_workflow: reviewOk, conflict_resolution: reviewOk, review_evidence: reviewOk, priority_ordering: reviewOk, reviewer_assignment: reviewOk, decision_recording: reviewOk, audit_lineage: reviewOk, replay_support: reviewOk, low_confidence_queued: reviewOk, immutable_lineage: reviewOk });
  const evidence_sync = nested({ evidence_id: evidenceOk ? "W5.3-KNOWLEDGE-EVIDENCE-SYNC-001" : "", context_synchronization: evidenceOk, unified_context_references: evidenceOk, complete_provenance: evidenceOk, originating_context_lineage: evidenceOk, originating_evidence_lineage: evidenceOk, review_evidence_ledger: evidenceOk, retrieval_replay: evidenceOk, review_replay: evidenceOk, identical_retrieval_outcomes: evidenceOk, identical_review_outcomes: evidenceOk, synchronized_with_unified_context: evidenceOk });
  const readiness = nested({ readiness_id: "W5.3-PERSONAL-KNOWLEDGE-READINESS-001", decision, phase_ready: qualified, upstream_ready: !has(failures, "W5_UNIFIED_CONTEXT_INVALID"), registry_ready: registryOk, graph_ready: graphOk, retrieval_ready: retrievalOk, reliability_ready: reliabilityOk, review_ready: reviewOk, evidence_sync_ready: evidenceOk, every_knowledge_object_registered: registryOk, graph_relationships_validated: graphOk, retrieval_deterministic_explainable: retrievalOk, provenance_complete: registryOk && evidenceOk, reliability_continuous: reliabilityOk, conflicts_detected: reliabilityOk, human_review_operational: reviewOk, review_lineage_immutable: reviewOk, unified_context_sync_validated: evidenceOk, replay_identical_retrieval_and_review: evidenceOk, failures });
  const base: Omit<WaveFivePersonalKnowledgeResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, upstream_refs: freezeArray(UPSTREAM_REFS), enables: freezeArray(ENABLES), tenant_id: input.tenant_id ?? context.tenant_id, principal_id: input.principal_id ?? context.principal_id, knowledge_profile_id: input.knowledge_profile_id ?? "knowledge-profile:w5.3:canonical", registry, graph, retrieval, reliability, review, evidence_sync, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateWaveFivePersonalKnowledge(result?: WaveFivePersonalKnowledgeResult): WaveFivePersonalKnowledgeValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, registry_valid: false, graph_valid: false, retrieval_valid: false, reliability_valid: false, review_valid: false, evidence_sync_valid: false, readiness_valid: false, failures: freezeArray(["KNOWLEDGE_REGISTRY_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const registry_valid = verifyHashed(result.registry) && result.registry.every_object_registered && result.registry.identities_deterministic && result.registry.lineage_complete;
  const graph_valid = verifyHashed(result.graph) && result.graph.relationship_validation && result.graph.graph_integrity_verified && result.graph.traversal_deterministic && result.graph.context_references;
  const retrieval_valid = verifyHashed(result.retrieval) && result.retrieval.deterministic_ranking && result.retrieval.result_explanation && result.retrieval.provenance_aware && result.retrieval.confidence_aware;
  const reliability_valid = verifyHashed(result.reliability) && result.reliability.reliability_scoring && result.reliability.continuous_evaluation && result.reliability.conflicts_detected_automatically;
  const review_valid = verifyHashed(result.review) && result.review.review_queue && result.review.human_review && result.review.decision_recording && result.review.low_confidence_queued && result.review.immutable_lineage;
  const evidence_sync_valid = verifyHashed(result.evidence_sync) && result.evidence_sync.complete_provenance && result.evidence_sync.synchronized_with_unified_context && result.evidence_sync.identical_retrieval_outcomes && result.evidence_sync.identical_review_outcomes;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.provenance_complete && result.readiness.reliability_continuous && result.readiness.human_review_operational && result.readiness.review_lineage_immutable && result.readiness.replay_identical_retrieval_and_review && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && registry_valid && graph_valid && retrieval_valid && reliability_valid && review_valid && evidence_sync_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, registry_valid, graph_valid, retrieval_valid, reliability_valid, review_valid, evidence_sync_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayWaveFivePersonalKnowledge(result = runWaveFivePersonalKnowledge()): boolean { const replayed = runWaveFivePersonalKnowledge(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateWaveFivePersonalKnowledge(result).valid; }
export function getWaveFivePersonalKnowledgeBundle(): WaveFivePersonalKnowledgeBundle { const result = runWaveFivePersonalKnowledge(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, knowledge_above_context: true, complete_provenance_required: true, deterministic_retrieval_required: true, reliability_review_required: true, unified_context_synchronization_required: true, replay_required: true, qualification_gate: "W5.3 Personal Knowledge Qualification Gate" }), result, validation: validateWaveFivePersonalKnowledge(result) }); }
export const WaveFivePersonalKnowledgeService = Object.freeze({ run: runWaveFivePersonalKnowledge, validate: validateWaveFivePersonalKnowledge, replay: replayWaveFivePersonalKnowledge });
