import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runMessagingCore, validateMessagingCore } from "@/services/messaging-core";
import type { MessagingFullBundle, MessagingFullDecision, MessagingFullFailure, MessagingFullInput, MessagingFullResult, MessagingFullScenario, MessagingFullValidation } from "@/types/messaging-full";

const VERSION = "messaging-full/w1.3b" as const;
const IDENTIFIER = "MessagingFull" as const;
let messagingCoreBaseline: ReturnType<typeof runMessagingCore> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly MessagingFullFailure[], failure: MessagingFullFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: MessagingFullScenario): MessagingFullFailure | undefined { return scenario === "BASELINE" || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly MessagingFullFailure[], scenario: MessagingFullScenario): MessagingFullDecision {
  if (has(failures, "W1_3A_MESSAGING_CORE_INVALID") || has(failures, "W1_3A_COMPATIBILITY_BROKEN") || has(failures, "ACK_DURABLE_MESSAGE_LOSS") || has(failures, "TENANT_ISOLATION_NOT_PROVEN") || has(failures, "UNAUTHORIZED_PUBLICATION_POSSIBLE") || has(failures, "UNAUTHORIZED_SUBSCRIPTION_POSSIBLE") || has(failures, "REPLAY_SIDE_EFFECT_UNCONTROLLED")) return "FAIL_CLOSED";
  if (has(failures, "MESSAGING_INFRASTRUCTURE_GATE_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_QUALIFIED";
  return scenario === "QUALIFIED_WITH_OBSERVATIONS" ? "CONDITIONALLY_QUALIFIED" : "QUALIFIED";
}
function resultReplayHash(result: Omit<MessagingFullResult, "replay_hash" | "integrity_hash">): string { return hash({ architecture: result.architecture.integrity_hash, envelope: result.envelope.integrity_hash, event: result.event_bus.integrity_hash, command: result.command_bus.integrity_hash, workflow: result.workflow_queue.integrity_hash, scheduler: result.scheduler.integrity_hash, notification: result.notification_bus.integrity_hash, replay: result.replay_queue.integrity_hash, lineage: result.lineage.integrity_hash, evidence: result.workflow_evidence.integrity_hash, contracts: result.contract_governance.integrity_hash, reliability: result.reliability.integrity_hash, security: result.security.integrity_hash, operations: result.operations.integrity_hash, administration: result.administration.integrity_hash, qualification: result.qualification.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<MessagingFullResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runMessagingFull(input: MessagingFullInput = {}): MessagingFullResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<MessagingFullFailure>(direct ? [direct] : []);
  messagingCoreBaseline ??= runMessagingCore();
  const coreInvalid = !validateMessagingCore(messagingCoreBaseline).valid || has(scenarioFailures, "W1_3A_MESSAGING_CORE_INVALID");
  const failures = freezeArray([...new Set([...scenarioFailures, ...(coreInvalid ? ["W1_3A_MESSAGING_CORE_INVALID" as const] : [])])]);
  const coreOk = !coreInvalid && !has(failures, "W1_3A_COMPATIBILITY_BROKEN");
  const architectureOk = !has(failures, "MESSAGING_FULL_ARCHITECTURE_MISSING") && !has(failures, "SERVICE_BOUNDARIES_UNAPPROVED") && coreOk;
  const envelopeOk = !has(failures, "CANONICAL_ENVELOPE_INVALID");
  const eventOk = !has(failures, "EVENT_BUS_MISSING") && !has(failures, "EVENT_CONTRACT_VALIDATION_FAILED") && !has(failures, "EVENT_CONSUMER_RECOVERY_FAILED");
  const commandOk = !has(failures, "COMMAND_BUS_MISSING") && !has(failures, "COMMAND_AUTHORIZATION_FAILED") && !has(failures, "COMMAND_IDEMPOTENCY_MISSING");
  const workflowOk = !has(failures, "WORKFLOW_QUEUE_MISSING") && !has(failures, "WORKFLOW_DURABILITY_FAILED") && !has(failures, "WORKER_LEASE_INVALID");
  const schedulerOk = !has(failures, "SCHEDULER_MISSING") && !has(failures, "SCHEDULE_MISFIRE_NON_DETERMINISTIC") && !has(failures, "SCHEDULE_DUPLICATE_DISPATCH");
  const notificationOk = !has(failures, "NOTIFICATION_BUS_MISSING") && !has(failures, "NOTIFICATION_ADAPTERS_UNREGISTERED") && !has(failures, "NOTIFICATION_DEDUPLICATION_MISSING");
  const replayOk = !has(failures, "REPLAY_QUEUE_MISSING") && !has(failures, "REPLAY_AUTHORIZATION_MISSING") && !has(failures, "REPLAY_SIDE_EFFECT_UNCONTROLLED");
  const lineageOk = !has(failures, "MESSAGE_LINEAGE_INCOMPLETE");
  const evidenceOk = !has(failures, "WORKFLOW_EVIDENCE_UNVERIFIABLE");
  const contractsOk = !has(failures, "CONTRACT_ENFORCEMENT_MISSING");
  const reliabilityOk = !has(failures, "RELIABILITY_CONTROLS_MISSING") && !has(failures, "ACK_DURABLE_MESSAGE_LOSS") && !has(failures, "DLQ_OPERATIONS_UNCONTROLLED") && !has(failures, "RECOVERY_PROCEDURES_UNTESTED");
  const securityOk = !has(failures, "SECURITY_CONTROLS_MISSING") && !has(failures, "TENANT_ISOLATION_NOT_PROVEN") && !has(failures, "UNAUTHORIZED_PUBLICATION_POSSIBLE") && !has(failures, "UNAUTHORIZED_SUBSCRIPTION_POSSIBLE");
  const operationsOk = !has(failures, "OBSERVABILITY_MISSING") && !has(failures, "CRITICAL_TELEMETRY_MISSING") && !has(failures, "PERFORMANCE_SCALABILITY_UNPROVEN");
  const adminOk = !has(failures, "ADMIN_CONTROLS_MISSING") && !has(failures, "HIGH_RISK_ADMIN_EVIDENCE_MISSING");
  const gateOk = !has(failures, "MESSAGING_INFRASTRUCTURE_GATE_FAILED");
  const decision = decisionFor(failures, scenario);
  const architecture = nested({ architecture_id: architectureOk ? `architecture:w1.3b:messaging-full:${input.seed ?? "canonical"}` : "", service_boundaries: architectureOk, logical_buses_separated: architectureOk, broker_topology: architectureOk, tenant_partitioning: architectureOk, delivery_semantics_standard: architectureOk, w13a_compatible: coreOk });
  const envelope = nested({ envelope_id: envelopeOk ? "envelope:w1.3b:canonical-message" : "", required_fields: envelopeOk ? freezeArray(["message_id", "message_type", "tenant_id", "namespace_id", "producer_id", "contract_id", "correlation_id", "causation_id", "partition_key", "payload_hash", "integrity_signature", "trace_id", "authority_context_reference", "evidence_reference"]) : freezeArray<string>([]), message_classes: envelopeOk ? freezeArray(["EVENT", "COMMAND", "WORKFLOW_TASK", "SCHEDULED_MESSAGE", "NOTIFICATION", "REPLAY_REQUEST", "REPLAY_MESSAGE", "CANCELLATION", "COMPENSATION", "CONTROL_MESSAGE"]) : freezeArray<string>([]), lifecycle_states: envelopeOk ? freezeArray(["CREATED", "VALIDATED", "ACCEPTED", "PERSISTED", "QUEUED", "DISPATCHED", "DELIVERED", "ACKNOWLEDGED", "RETRY_PENDING", "DEAD_LETTERED", "REPLAYED", "QUARANTINED"]) : freezeArray<string>([]), immutable: envelopeOk, tenant_bound: envelopeOk, integrity_signed: envelopeOk });
  const event_bus = nested({ service_id: eventOk ? "service:w1.3b:event-bus" : "", topics: eventOk ? freezeArray(["identity.events", "storage.events", "governance.events", "audit.events"]) : freezeArray<string>([]), durable_subscriptions: eventOk, consumer_groups: eventOk, partition_ordering: eventOk, contract_validation: eventOk, consumer_recovery: eventOk, lineage_evidence: eventOk });
  const command_bus = nested({ service_id: commandOk ? "service:w1.3b:command-bus" : "", routes: commandOk ? freezeArray(["platform.commands", "tenant.commands", "operator.commands"]) : freezeArray<string>([]), target_resolution: commandOk, authorization: commandOk, acknowledgements: commandOk, outcome_reporting: commandOk, cancellation: commandOk, idempotency: commandOk });
  const workflow_queue = nested({ service_id: workflowOk ? "service:w1.3b:workflow-queue" : "", queues: workflowOk ? freezeArray(["workflow.platform", "workflow.tenant", "workflow.recovery"]) : freezeArray<string>([]), durable_tasks: workflowOk, task_leases: workflowOk, lease_renewal: workflowOk, retry_backoff: workflowOk, crash_recovery: workflowOk, workflow_checkpoints: workflowOk });
  const scheduler = nested({ service_id: schedulerOk ? "service:w1.3b:scheduler" : "", schedule_types: schedulerOk ? freezeArray(["ONE_TIME", "RECURRING", "DELAYED"]) : freezeArray<string>([]), delayed_delivery: schedulerOk, recurring_delivery: schedulerOk, timezone_validated: schedulerOk, deterministic_misfires: schedulerOk, duplicate_dispatch_control: schedulerOk, failover: schedulerOk });
  const notification_bus = nested({ service_id: notificationOk ? "service:w1.3b:notification-bus" : "", categories: notificationOk ? freezeArray(["operational", "security", "governance", "workflow", "incident", "platform-health", "operator-action-required"]) : freezeArray<string>([]), registered_adapters: notificationOk, tenant_routing: notificationOk, suppression_deduplication: notificationOk, rate_limiting: notificationOk, escalation_routing: notificationOk, delivery_evidence: notificationOk });
  const replay_queue = nested({ service_id: replayOk ? "service:w1.3b:replay-queue" : "", modes: replayOk ? freezeArray(["DRY_RUN", "SIMULATION", "VALIDATION", "RECOVERY", "CONTROLLED_PRODUCTION"]) : freezeArray<string>([]), isolated_queue: replayOk, authorization_model: replayOk, original_message_reference: replayOk, replay_markers: replayOk, side_effect_suppression: replayOk, divergence_detection: replayOk });
  const lineage = nested({ store_id: lineageOk ? "store:w1.3b:message-lineage" : "", producer_identity: lineageOk, consumer_identity: lineageOk, correlation_causation: lineageOk, command_outcomes: lineageOk, workflow_links: lineageOk, queryable_lineage: lineageOk, complete: lineageOk });
  const workflow_evidence = nested({ service_id: evidenceOk ? "service:w1.3b:workflow-evidence" : "", append_only: evidenceOk, state_transitions: evidenceOk, task_evidence: evidenceOk, scheduler_evidence: evidenceOk, replay_evidence: evidenceOk, workflow_reconstruction: evidenceOk, verifiable: evidenceOk });
  const contract_governance = nested({ registry_id: contractsOk ? "registry:w1.3b:message-contracts" : "", contract_lifecycle: contractsOk, schema_validation: contractsOk, compatibility_evaluation: contractsOk, producer_consumer_matrix: contractsOk, deprecation_policy: contractsOk, production_enforcement: contractsOk });
  const reliability = nested({ profile_id: reliabilityOk ? "profile:w1.3b:messaging-reliability" : "", retry_profiles: reliabilityOk, circuit_breakers: reliabilityOk, poison_detection: reliabilityOk, dead_letter_management: reliabilityOk, authorized_redrive: reliabilityOk, recovery_runbooks: reliabilityOk, durable_ack_safety: reliabilityOk });
  const security = nested({ security_id: securityOk ? "security:w1.3b:messaging-full" : "", producer_authentication: securityOk, consumer_authentication: securityOk, publish_authorization: securityOk, subscribe_authorization: securityOk, replay_authorization: securityOk, encrypted_transport: securityOk, tenant_isolation_validated: securityOk });
  const operations = nested({ operations_id: operationsOk ? "ops:w1.3b:messaging" : "", telemetry_metrics: operationsOk ? freezeArray(["publication_rate", "delivery_rate", "acknowledgment_rate", "failure_rate", "retry_rate", "dead_letter_rate", "queue_depth", "consumer_lag", "message_latency", "workflow_task_latency", "schedule_execution_delay", "notification_delivery_success", "replay_throughput", "broker_availability", "tenant_quota_usage"]) : freezeArray<string>([]), distributed_tracing: operationsOk, tenant_dashboards: operationsOk, health_checks: operationsOk, alerts: operationsOk, capacity_model: operationsOk, incident_runbooks: operationsOk });
  const administration = nested({ administration_id: adminOk ? "admin:w1.3b:messaging" : "", queue_inspection: adminOk, dead_letter_inspection: adminOk, authorized_redrive: adminOk, replay_cancellation: adminOk, emergency_throttling: adminOk, dual_control: adminOk, operator_evidence: adminOk });
  const qualificationReady = decision === "QUALIFIED";
  const qualification = nested({ report_id: gateOk ? "report:w1.3b:messaging-infrastructure-gate" : "", functional_validation: qualificationReady, integration_validation: qualificationReady, reliability_validation: qualificationReady, security_validation: qualificationReady, performance_validation: qualificationReady, replay_validation: qualificationReady, evidence_review: qualificationReady, operational_readiness: qualificationReady, gate_decision: decision });
  const readiness = nested({ readiness_id: "W1.3B-MESSAGING-FULL-READINESS-001", decision, phase_ready: decision === "QUALIFIED", messaging_core_ready: coreOk, architecture_ready: architectureOk, envelope_ready: envelopeOk, event_bus_ready: eventOk, command_bus_ready: commandOk, workflow_queue_ready: workflowOk, scheduler_ready: schedulerOk, notification_bus_ready: notificationOk, replay_queue_ready: replayOk, lineage_ready: lineageOk, workflow_evidence_ready: evidenceOk, contracts_ready: contractsOk, reliability_ready: reliabilityOk, security_ready: securityOk, operations_ready: operationsOk, administration_ready: adminOk, qualification_ready: qualificationReady, failures });
  const base: Omit<MessagingFullResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, messaging_core_ref: "messaging-core/w1.3a", architecture, envelope, event_bus, command_bus, workflow_queue, scheduler, notification_bus, replay_queue, lineage, workflow_evidence, contract_governance, reliability, security, operations, administration, qualification, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateMessagingFull(result?: MessagingFullResult): MessagingFullValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, architecture_valid: false, envelope_valid: false, event_bus_valid: false, command_bus_valid: false, workflow_queue_valid: false, scheduler_valid: false, notification_bus_valid: false, replay_queue_valid: false, lineage_valid: false, workflow_evidence_valid: false, contracts_valid: false, reliability_valid: false, security_valid: false, operations_valid: false, administration_valid: false, qualification_valid: false, readiness_valid: false, failures: freezeArray(["MESSAGING_FULL_ARCHITECTURE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const architecture_valid = verifyHashed(result.architecture) && result.architecture.logical_buses_separated && result.architecture.w13a_compatible;
  const envelope_valid = verifyHashed(result.envelope) && result.envelope.required_fields.length >= 14 && result.envelope.message_classes.length >= 10 && result.envelope.immutable && result.envelope.tenant_bound;
  const event_bus_valid = verifyHashed(result.event_bus) && result.event_bus.topics.length >= 4 && result.event_bus.contract_validation && result.event_bus.consumer_recovery;
  const command_bus_valid = verifyHashed(result.command_bus) && result.command_bus.authorization && result.command_bus.outcome_reporting && result.command_bus.idempotency;
  const workflow_queue_valid = verifyHashed(result.workflow_queue) && result.workflow_queue.durable_tasks && result.workflow_queue.task_leases && result.workflow_queue.crash_recovery;
  const scheduler_valid = verifyHashed(result.scheduler) && result.scheduler.schedule_types.length >= 3 && result.scheduler.deterministic_misfires && result.scheduler.duplicate_dispatch_control;
  const notification_bus_valid = verifyHashed(result.notification_bus) && result.notification_bus.registered_adapters && result.notification_bus.suppression_deduplication && result.notification_bus.delivery_evidence;
  const replay_queue_valid = verifyHashed(result.replay_queue) && result.replay_queue.modes.length >= 5 && result.replay_queue.authorization_model && result.replay_queue.side_effect_suppression;
  const lineage_valid = verifyHashed(result.lineage) && result.lineage.producer_identity && result.lineage.consumer_identity && result.lineage.complete;
  const workflow_evidence_valid = verifyHashed(result.workflow_evidence) && result.workflow_evidence.append_only && result.workflow_evidence.workflow_reconstruction && result.workflow_evidence.verifiable;
  const contracts_valid = verifyHashed(result.contract_governance) && result.contract_governance.schema_validation && result.contract_governance.compatibility_evaluation && result.contract_governance.production_enforcement;
  const reliability_valid = verifyHashed(result.reliability) && result.reliability.dead_letter_management && result.reliability.authorized_redrive && result.reliability.durable_ack_safety;
  const security_valid = verifyHashed(result.security) && result.security.publish_authorization && result.security.subscribe_authorization && result.security.tenant_isolation_validated;
  const operations_valid = verifyHashed(result.operations) && result.operations.telemetry_metrics.length >= 15 && result.operations.distributed_tracing && result.operations.alerts;
  const administration_valid = verifyHashed(result.administration) && result.administration.authorized_redrive && result.administration.dual_control && result.administration.operator_evidence;
  const qualification_valid = verifyHashed(result.qualification) && result.qualification.functional_validation && result.qualification.reliability_validation && result.qualification.security_validation && result.qualification.gate_decision === "QUALIFIED";
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && architecture_valid && envelope_valid && event_bus_valid && command_bus_valid && workflow_queue_valid && scheduler_valid && notification_bus_valid && replay_queue_valid && lineage_valid && workflow_evidence_valid && contracts_valid && reliability_valid && security_valid && operations_valid && administration_valid && qualification_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, architecture_valid, envelope_valid, event_bus_valid, command_bus_valid, workflow_queue_valid, scheduler_valid, notification_bus_valid, replay_queue_valid, lineage_valid, workflow_evidence_valid, contracts_valid, reliability_valid, security_valid, operations_valid, administration_valid, qualification_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayMessagingFull(result = runMessagingFull()): boolean { const replayed = runMessagingFull(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateMessagingFull(result).valid; }
export function getMessagingFullBundle(): MessagingFullBundle { const result = runMessagingFull(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_event_bus: true, owns_command_bus: true, owns_workflow_queue: true, owns_scheduler: true, owns_notification_bus: true, owns_replay_queue: true, owns_message_lineage: true, owns_workflow_evidence: true, owns_contract_governance: true, owns_messaging_operations: true, owns_administration_controls: true, qualification_gate: "Messaging Infrastructure Gate" }), result, validation: validateMessagingFull(result) }); }
export const MessagingFullService = Object.freeze({ run: runMessagingFull, validate: validateMessagingFull, replay: replayMessagingFull });
