export type ConstitutionalAuditErrorCode =
  | "CONSTITUTIONAL_AUDIT_REPLAY_MISMATCH"
  | "CONSTITUTIONAL_AUDIT_GOVERNANCE_MISMATCH"
  | "CONSTITUTIONAL_AUDIT_APPROVAL_MISMATCH"
  | "CONSTITUTIONAL_AUDIT_ESCALATION_MISMATCH"
  | "CONSTITUTIONAL_AUDIT_LINEAGE_CORRUPTION"
  | "CONSTITUTIONAL_AUDIT_LINEAGE_MISSING"
  | "CONSTITUTIONAL_AUDIT_VALIDATOR_DRIFT"
  | "CONSTITUTIONAL_AUDIT_OPERATOR_AMBIGUITY"
  | "CONSTITUTIONAL_AUDIT_REPLAY_REPAIR_ATTEMPT"
  | "CONSTITUTIONAL_AUDIT_CURRENT_STATE_SUBSTITUTION"
  | "CONSTITUTIONAL_AUDIT_ISOLATION_VIOLATION"
  | "CONSTITUTIONAL_AUDIT_RUNTIME_CONTAMINATION"
  | "CONSTITUTIONAL_AUDIT_HIDDEN_ORCHESTRATION"
  | "CONSTITUTIONAL_AUDIT_PRIVILEGE_ESCALATION"
  | "CONSTITUTIONAL_AUDIT_SYNTHETIC_AUTHORITY"
  | "CONSTITUTIONAL_AUDIT_FAIL_CLOSED";

export type ConstitutionalAuditError = Readonly<{
  code: ConstitutionalAuditErrorCode;
  message: string;
  path?: string;
}>;
