export const READINESS_CONSTRAINTS = {
  READINESS_IS_ADVISORY_ONLY: true,
  READINESS_CANNOT_AUTHORIZE_RECOVERY: true,
  READINESS_CANNOT_MUTATE_RUNTIME: true,
  READINESS_CANNOT_OVERRIDE_CONSTITUTION: true,
  READINESS_CANNOT_REDUCE_RESTRICTIONS: true,
  READINESS_REQUIRES_OPERATOR_APPROVAL: true,
  READINESS_BLOCKED_BY_DISPUTED_TRUTH: true,
  READINESS_BLOCKED_BY_FREEZE: true,
  READINESS_BLOCKED_BY_MISSING_ROLLBACK: true,
  READINESS_BLOCKED_BY_UNTRUSTED_SIMULATION: true,
} as const;
