import { z } from "zod";
import { getSessionUser } from "@/src/lib/auth";
import { apiError, apiSuccess } from "@/src/server/api/response";
import { prisma } from "@/src/server/db/prisma";
import { ensureLinuxSkillGraphSeeded } from "@/src/server/learning/skill-graph-bootstrap";
import { calculateDerivedSkillState, SKILL_STATE_CALCULATION_V1 } from "@/services/learning-constitution";

const schema = z.object({ id: z.string().min(1), skill_id: z.string().min(1), kind: z.enum(["ASSESSMENT", "PRACTICAL_TASK", "SELF_REPORT", "INSTRUCTOR_REVIEW"]), occurred_at: z.string().datetime(), score: z.number().min(0).max(1).optional(), outcome: z.enum(["PASS", "PARTIAL", "FAIL", "OBSERVED"]), evaluator: z.enum(["SYSTEM", "HUMAN", "LEARNER"]), source_ref: z.string().optional(), notes: z.string().optional(), rubric_version: z.string().optional(), assessment_session_id: z.string().min(1).optional(), assessment_item_id: z.string().min(1).optional(), evaluation_type: z.enum(["RECALL", "EXPLANATION", "APPLICATION", "DIAGNOSIS", "SCENARIO", "PRACTICAL_TASK", "ADVERSARIAL_SCENARIO"]).optional(), competency_dimensions: z.array(z.enum(["KNOWLEDGE", "APPLICATION", "TROUBLESHOOTING", "RETENTION", "CALIBRATION"])).optional() });
export async function POST(request: Request) { try { const user = await getSessionUser(); if (!user) throw new Error("Authentication required."); const body = schema.parse(await request.json()); const repository = await ensureLinuxSkillGraphSeeded(); const observation = await repository.appendEvidence({ ...body, learner_id: user.id }); const state = calculateDerivedSkillState(user.id, body.skill_id, await repository.findEvidenceBySkillId(body.skill_id), { ...SKILL_STATE_CALCULATION_V1, asOf: new Date().toISOString() }); await prisma.skillLearnerState.upsert({ where: { learnerId_skillId: { learnerId: user.id, skillId: body.skill_id } }, update: { mastery: state.mastery, confidence: state.confidence, retentionScore: state.retention_score, lastEvaluated: state.last_evaluated ? new Date(state.last_evaluated) : null, displayState: state.display_state, calculationVersion: state.calculation_version, calculatedAt: new Date(state.calculated_at), evidenceIds: [...state.evidence_ids] }, create: { learnerId: user.id, skillId: body.skill_id, mastery: state.mastery, confidence: state.confidence, retentionScore: state.retention_score, lastEvaluated: state.last_evaluated ? new Date(state.last_evaluated) : null, displayState: state.display_state, calculationVersion: state.calculation_version, calculatedAt: new Date(state.calculated_at), evidenceIds: [...state.evidence_ids] } }); return apiSuccess({ evidence: observation, state }, { status: 201 }); } catch (error) { return apiError(error, "Unable to record learning evidence."); } }
