export type FutureAutonomyErrorCode =
  | "FUTURE_AUTONOMY_GOVERNANCE_AMBIGUITY"
  | "FUTURE_AUTONOMY_REPLAY_MISMATCH"
  | "FUTURE_AUTONOMY_VALIDATOR_DRIFT"
  | "FUTURE_AUTONOMY_CURRENT_STATE_SUBSTITUTION"
  | "FUTURE_AUTONOMY_HIDDEN_ORCHESTRATION"
  | "FUTURE_AUTONOMY_RECURSIVE_WORKFLOW"
  | "FUTURE_AUTONOMY_RUNTIME_CONTAMINATION"
  | "FUTURE_AUTONOMY_EXECUTION_IMPORT"
  | "FUTURE_AUTONOMY_APPROVAL_INHERITANCE"
  | "FUTURE_AUTONOMY_ESCALATION_SUPPRESSION"
  | "FUTURE_AUTONOMY_CONFIDENCE_AUTHORITY_COUPLING"
  | "FUTURE_AUTONOMY_PRIVILEGE_ESCALATION"
  | "FUTURE_AUTONOMY_ADAPTIVE_AUTONOMY"
  | "FUTURE_AUTONOMY_SIMULATION_RUNTIME_BRIDGE"
  | "FUTURE_AUTONOMY_ISOLATION_VIOLATION"
  | "FUTURE_AUTONOMY_FAIL_CLOSED";

export type FutureAutonomyError = Readonly<{
  code: FutureAutonomyErrorCode;
  message: string;
  path?: string;
}>;
