"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Check, Sparkles, Star } from "lucide-react";
import "../../nuru.css";
type Discovery = { id: string; title: string; meta: string; score: number; image: string; kind: string };
type Edition = { editionAt: string; items: Array<Discovery & { isFeatured: boolean }> };
export function DailyEditionStudio() {
  const [discoveries, setDiscoveries] = useState<Discovery[]>([]); const [selected, setSelected] = useState<string[]>([]); const [featured, setFeatured] = useState(""); const [edition, setEdition] = useState<Edition | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/nuru/studio/editions", { cache: "no-store" }).then((response) => response.json().then((payload) => ({ response, payload }))).then(({ response, payload }) => { if (!response.ok || !payload.ok) return setMessage(payload.error?.message ?? "Nuru couldn’t load today’s edition."); setDiscoveries(payload.data.discoveries); setEdition(payload.data.edition); if (payload.data.edition) { setSelected(payload.data.edition.items.map((item: Discovery) => item.id)); setFeatured(payload.data.edition.items.find((item: Edition["items"][number]) => item.isFeatured)?.id ?? ""); } }).catch(() => setMessage("Nuru couldn’t load today’s edition.")); }, []);
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : current.length === 7 ? current : [...current, id]); if (featured === id && selected.includes(id)) setFeatured(""); }
  async function publish() { const response = await fetch("/api/nuru/studio/editions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ discoveryIds: selected, featuredId: featured }) }); const payload = await response.json(); if (!response.ok || !payload.ok) return setMessage(payload.error?.message ?? "Nuru couldn’t publish today’s edition."); setEdition(payload.data as Edition); setMessage("Today’s seven discoveries are live."); }
  async function prepareTomorrow() { const response = await fetch("/api/nuru/studio/editions/prepare", { method: "POST" }); const payload = await response.json(); setMessage(response.ok && payload.ok ? payload.data.message : payload.error?.message ?? "Nuru couldn’t prepare tomorrow’s edition."); }
  return <main className="nuru-shell edition-shell"><header className="nuru-nav"><Link className="nuru-brand" href="/nuru"><span>NURU</span><small>Discover a deeper world</small></Link><nav><Link href="/nuru/studio">Studio</Link><Link className="active" href="/nuru/studio/editions">Daily edition</Link></nav></header><section className="edition-hero"><Link href="/nuru/studio" className="back-link"><ArrowLeft size={15} /> Nuru Studio</Link><p className="eyebrow"><Sparkles size={15} /> Finite by design</p><h1>Today’s edition</h1><p>Choose exactly seven published discoveries, then name the one Nuru should put first.</p></section><section className="edition-layout"><div><div className="edition-summary"><span>{selected.length} / 7 selected</span><span>{featured ? "Featured discovery chosen" : "Choose one featured discovery"}</span><button className="gold-button" disabled={selected.length !== 7 || !featured} onClick={() => void publish}><Check size={16} /> Publish today’s edition</button></div><button className="prepare-tomorrow" onClick={() => void prepareTomorrow()}>Prepare tomorrow’s candidates →</button><div className="edition-discovery-list">{discoveries.map((discovery) => <article key={discovery.id} className={selected.includes(discovery.id) ? "selected" : ""}><button className="select-discovery" onClick={() => toggle(discovery.id)} aria-pressed={selected.includes(discovery.id)}><span>{selected.includes(discovery.id) ? <Check size={15} /> : ""}</span><div><h2>{discovery.title}</h2><p>{discovery.meta} · {discovery.score}% match</p></div></button>{selected.includes(discovery.id) && <button className={`feature-choice ${featured === discovery.id ? "chosen" : ""}`} onClick={() => setFeatured(discovery.id)}><Star size={15} fill={featured === discovery.id ? "currentColor" : "none"} /> Feature</button>}</article>)}</div></div><aside className="edition-preview"><p className="eyebrow">Edition status</p><h2>{edition ? "Published today" : "Not yet published"}</h2><p>{edition ? `${edition.items.length} discoveries are forming today’s deliberate collection.` : "When it’s ready, this edition will replace the open discovery feed for the day."}</p>{edition?.items.map((item) => <div key={item.id}><span>{item.isFeatured ? "Featured" : "Discovery"}</span><b>{item.title}</b></div>)}</aside></section>{message && <div className="toast" role="status">{message}<button onClick={() => setMessage("")}>×</button></div>}</main>;
}
