export type LifecycleErrorCode =
  | "LIFECYCLE_INVALID_TRANSITION"
  | "LIFECYCLE_REPLAY_BINDING_MISSING"
  | "LIFECYCLE_REPLAY_MISMATCH"
  | "LIFECYCLE_REPLAY_GAP_REJECTED"
  | "LIFECYCLE_GOVERNANCE_MISMATCH"
  | "LIFECYCLE_ESCALATION_MISMATCH"
  | "LIFECYCLE_APPROVAL_MISMATCH"
  | "LIFECYCLE_BOUNDARY_VIOLATION"
  | "LIFECYCLE_EXECUTION_LEAK_REJECTED"
  | "LIFECYCLE_ORCHESTRATION_LEAK_REJECTED"
  | "LIFECYCLE_SCHEDULING_REJECTED"
  | "LIFECYCLE_DISPATCH_REJECTED"
  | "LIFECYCLE_AUTONOMOUS_REPAIR_REJECTED"
  | "LIFECYCLE_APPROVAL_INHERITANCE_REJECTED"
  | "LIFECYCLE_CORRELATION_DRIVEN_TRANSITION_REJECTED"
  | "LIFECYCLE_COORDINATION_INFERENCE_REJECTED"
  | "LIFECYCLE_HIDDEN_RETRY_REJECTED"
  | "LIFECYCLE_RUNTIME_MUTATION_REJECTED"
  | "LIFECYCLE_HANDOFF_AUTHORITY_REJECTED"
  | "LIFECYCLE_NON_DETERMINISTIC_OUTPUT";

export type LifecycleError = Readonly<{
  code: LifecycleErrorCode;
  message: string;
  path: string;
}>;
