import type { ObservabilityAlertRule } from "./alertTypes";

export const DEFAULT_ALERT_RULES: ObservabilityAlertRule[] = [
  {
    ruleId: "failed-recoveries-high",
    source: "recovery",
    severity: "HIGH",
    condition: { kind: "numeric", metricName: "failedRecoveries", comparator: "gt", threshold: 0 },
    reason: "Failed recoveries detected.",
    recommendedAction: "Inspect the recovery read model and operator state.",
  },
  {
    ruleId: "lock-contention-warning",
    source: "locks",
    severity: "WARNING",
    condition: { kind: "numeric", metricName: "lockContentionRate", comparator: "gt", threshold: 0.25 },
    reason: "Lock contention rate exceeds the warning threshold.",
    recommendedAction: "Inspect lock pressure and stale lock signals.",
  },
  {
    ruleId: "lock-contention-high",
    source: "locks",
    severity: "HIGH",
    condition: { kind: "numeric", metricName: "lockContentionRate", comparator: "gt", threshold: 0.5 },
    reason: "Lock contention rate exceeds the high threshold.",
    recommendedAction: "Escalate to operators and inspect blocked recovery flow.",
  },
  {
    ruleId: "verification-mismatches-high",
    source: "verification",
    severity: "HIGH",
    condition: { kind: "numeric", metricName: "verificationMismatches", comparator: "gt", threshold: 0 },
    reason: "Verification mismatches detected.",
    recommendedAction: "Inspect replay and evidence mismatch sources.",
  },
  {
    ruleId: "verification-mismatches-critical",
    source: "verification",
    severity: "CRITICAL",
    condition: { kind: "numeric", metricName: "verificationMismatches", comparator: "gt", threshold: 5 },
    reason: "Verification mismatches exceed the critical threshold.",
    recommendedAction: "Immediate operator intervention is recommended.",
  },
  {
    ruleId: "contract-compatibility-failures-high",
    source: "contracts",
    severity: "HIGH",
    condition: { kind: "numeric", metricName: "contractCompatibilityFailures", comparator: "gt", threshold: 0 },
    reason: "Contract compatibility failures detected.",
    recommendedAction: "Review compatibility alerts and migration readiness.",
  },
  {
    ruleId: "replay-validation-failures-high",
    source: "contracts",
    severity: "HIGH",
    condition: { kind: "numeric", metricName: "replayValidationFailures", comparator: "gt", threshold: 0 },
    reason: "Replay validation failures detected.",
    recommendedAction: "Inspect replay drift and historical payload compatibility.",
  },
  {
    ruleId: "readiness-gate-failures-high",
    source: "contracts",
    severity: "HIGH",
    condition: { kind: "numeric", metricName: "readinessGateFailures", comparator: "gt", threshold: 0 },
    reason: "Readiness gate failures detected.",
    recommendedAction: "Inspect governance approval and certification state.",
  },
  {
    ruleId: "system-health-unhealthy",
    source: "health",
    severity: "CRITICAL",
    condition: { kind: "status", metricName: "systemHealthStatus", equals: "UNHEALTHY" },
    reason: "System health is unhealthy.",
    recommendedAction: "Escalate to operators and inspect unhealthy components.",
  },
];
