import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runWaveFiveApplicationPlatform, validateWaveFiveApplicationPlatform } from "@/services/wave-five-application-platform";
import type { WaveFiveUnifiedPersonalContextBundle, WaveFiveUnifiedPersonalContextDecision, WaveFiveUnifiedPersonalContextFailure, WaveFiveUnifiedPersonalContextInput, WaveFiveUnifiedPersonalContextResult, WaveFiveUnifiedPersonalContextScenario, WaveFiveUnifiedPersonalContextValidation } from "@/types/wave-five-unified-personal-context";

const VERSION = "wave-five-unified-personal-context/w5.2" as const;
const IDENTIFIER = "WaveFiveUnifiedPersonalContext" as const;
const UPSTREAM_REFS = Object.freeze(["wave-five-application-platform/w5.1", "wave-five-application-portfolio-foundation/w5.0"]);
const ENABLES = Object.freeze(["personalized-application-experiences", "cross-application-personalization", "intelligent-recommendations", "user-preferences", "activity-history", "personal-knowledge", "adaptive-workflows", "context-aware-search", "context-aware-notifications", "digital-personal-assistants"]);
let platform = runWaveFiveApplicationPlatform();

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly WaveFiveUnifiedPersonalContextFailure[], failure: WaveFiveUnifiedPersonalContextFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: WaveFiveUnifiedPersonalContextScenario): WaveFiveUnifiedPersonalContextFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly WaveFiveUnifiedPersonalContextFailure[], scenario?: WaveFiveUnifiedPersonalContextScenario): WaveFiveUnifiedPersonalContextDecision {
  const notQualified = new Set<WaveFiveUnifiedPersonalContextFailure>(["W5_APPLICATION_PLATFORM_INVALID", "CONTEXT_IDENTITIES_NONDETERMINISTIC", "GRAPH_RELATIONSHIPS_NONDETERMINISTIC", "GRAPH_INTEGRITY_INVALID", "GRAPH_TRAVERSAL_NONDETERMINISTIC", "TIMELINE_MUTABLE", "HISTORICAL_RECONSTRUCTION_FAILED", "CONTEXT_REPLAY_DIVERGED", "SOURCES_UNCERTIFIED", "SOURCE_LINEAGE_INCOMPLETE", "SOURCE_GOVERNANCE_NONDETERMINISTIC", "CONFLICTS_UNRESOLVED", "RESOLUTION_NONDETERMINISTIC", "CONTEXT_APIS_UNSTABLE", "AUTHORIZATION_NOT_ENFORCED", "TENANT_ISOLATION_BREACH", "SDK_NOT_QUALIFIED", "IDENTITY_BINDING_MISSING", "EXPLAINABILITY_MISSING", "EVIDENCE_LINEAGE_INCOMPLETE", "TRUST_INTEGRATION_MISSING", "AUTHORITATIVE_PERSONALIZATION_NOT_DECLARED"]);
  if (failures.some((failure) => notQualified.has(failure))) return "NOT_QUALIFIED";
  if (has(failures, "UNIFIED_CONTEXT_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_QUALIFIED";
  return "QUALIFIED";
}
function resultReplayHash(result: Omit<WaveFiveUnifiedPersonalContextResult, "replay_hash" | "integrity_hash">): string { return hash({ registry: result.registry.integrity_hash, graph: result.graph.integrity_hash, timeline: result.timeline.integrity_hash, source_governance: result.source_governance.integrity_hash, resolution: result.resolution.integrity_hash, apis: result.apis.integrity_hash, evidence_trust: result.evidence_trust.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<WaveFiveUnifiedPersonalContextResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runWaveFiveUnifiedPersonalContext(input: WaveFiveUnifiedPersonalContextInput = {}): WaveFiveUnifiedPersonalContextResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  platform = runWaveFiveApplicationPlatform();
  const failures = freezeArray([...new Set([...(direct ? [direct] : []), ...(!validateWaveFiveApplicationPlatform(platform).valid ? ["W5_APPLICATION_PLATFORM_INVALID" as const] : [])])]);
  const registryOk = !has(failures, "CONTEXT_REGISTRY_MISSING") && !has(failures, "CONTEXT_IDENTITIES_NONDETERMINISTIC") && !has(failures, "CONTEXT_METADATA_INVALID") && !has(failures, "CONTEXT_VERSION_LINEAGE_INCOMPLETE") && !has(failures, "CONTEXT_OWNERSHIP_MISSING");
  const graphOk = !has(failures, "CONTEXT_GRAPH_MISSING") && !has(failures, "GRAPH_RELATIONSHIPS_NONDETERMINISTIC") && !has(failures, "GRAPH_INTEGRITY_INVALID") && !has(failures, "GRAPH_TRAVERSAL_NONDETERMINISTIC") && !has(failures, "RELATIONSHIP_GOVERNANCE_MISSING");
  const timelineOk = !has(failures, "TIMELINE_MISSING") && !has(failures, "TIMELINE_MUTABLE") && !has(failures, "HISTORICAL_RECONSTRUCTION_FAILED") && !has(failures, "CONTEXT_REPLAY_DIVERGED") && !has(failures, "TIMELINE_EVIDENCE_MISSING");
  const sourceOk = !has(failures, "SOURCE_REGISTRY_MISSING") && !has(failures, "SOURCES_UNCERTIFIED") && !has(failures, "SOURCE_LINEAGE_INCOMPLETE") && !has(failures, "SOURCE_GOVERNANCE_NONDETERMINISTIC") && !has(failures, "SOURCE_TRUST_MISSING") && !has(failures, "SOURCE_POLICIES_MISSING");
  const resolutionOk = !has(failures, "RESOLUTION_RULES_MISSING") && !has(failures, "CONFLICTS_UNRESOLVED") && !has(failures, "RESOLUTION_NONDETERMINISTIC") && !has(failures, "SOURCE_PRIORITY_MISSING") && !has(failures, "CONFIDENCE_EVALUATION_MISSING") && !has(failures, "RESOLUTION_EVIDENCE_MISSING");
  const apisOk = !has(failures, "CONTEXT_APIS_UNSTABLE") && !has(failures, "AUTHORIZATION_NOT_ENFORCED") && !has(failures, "TENANT_ISOLATION_BREACH") && !has(failures, "SDK_NOT_QUALIFIED") && !has(failures, "API_CONTRACTS_UNVERSIONED");
  const evidenceOk = !has(failures, "IDENTITY_BINDING_MISSING") && !has(failures, "EXPLAINABILITY_MISSING") && !has(failures, "EVIDENCE_LINEAGE_INCOMPLETE") && !has(failures, "TRUST_INTEGRATION_MISSING") && !has(failures, "OBSERVABILITY_MISSING") && !has(failures, "SECURITY_CONTROLS_MISSING");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "QUALIFIED";
  const registry = nested({ registry_id: registryOk ? "W5.2-CONTEXT-REGISTRY-001" : "", context_identity_model: registryOk, context_registry: registryOk, context_classification: registryOk, context_metadata: registryOk, context_ownership: registryOk, context_versioning: registryOk, context_lifecycle: registryOk, context_evidence_references: registryOk, deterministic_identities: registryOk, authoritative: registryOk, metadata_validated: registryOk, version_lineage_complete: registryOk });
  const graph = nested({ graph_id: graphOk ? "W5.2-CONTEXT-GRAPH-001" : "", context_nodes: graphOk, context_relationships: graphOk, identity_relationships: graphOk, preference_relationships: graphOk, behavioral_relationships: graphOk, organizational_relationships: graphOk, device_relationships: graphOk, graph_traversal: graphOk, relationship_governance: graphOk, relationships_deterministic: graphOk, graph_integrity_validated: graphOk, traversal_deterministic: graphOk });
  const timeline = nested({ timeline_id: timelineOk ? "W5.2-CONTEXT-TIMELINE-001" : "", context_events: timelineOk, timeline_entries: timelineOk, temporal_versioning: timelineOk, historical_reconstruction: timelineOk, context_snapshots: timelineOk, replay_support: timelineOk, time_navigation: timelineOk, timeline_evidence: timelineOk, immutable: timelineOk, reconstruction_verified: timelineOk, replay_deterministic: timelineOk });
  const source_governance = nested({ source_id: sourceOk ? "W5.2-SOURCE-GOVERNANCE-001" : "", source_registry: sourceOk, source_authority: sourceOk, source_trust: sourceOk, source_priority: sourceOk, source_certification: sourceOk, source_validation: sourceOk, source_health: sourceOk, source_policies: sourceOk, sources_certified: sourceOk, lineage_complete: sourceOk, governance_deterministic: sourceOk });
  const resolution = nested({ resolution_id: resolutionOk ? "W5.2-CONTEXT-RESOLUTION-001" : "", resolution_rules: resolutionOk, conflict_detection: resolutionOk, authority_resolution: resolutionOk, source_prioritization: resolutionOk, confidence_evaluation: resolutionOk, context_composition: resolutionOk, resolution_evidence: resolutionOk, resolution_replay: resolutionOk, single_authoritative_value: resolutionOk, deterministic: resolutionOk, conflicts_resolved_consistently: resolutionOk, replay_validated: resolutionOk });
  const apis = nested({ api_id: apisOk ? "W5.2-CONTEXT-APIS-001" : "", context_query_apis: apisOk, graph_apis: apisOk, timeline_apis: apisOk, search_apis: apisOk, subscription_apis: apisOk, authorization_enforcement: apisOk, tenant_isolation: apisOk, sdk_contracts: apisOk, stable: apisOk, sdk_qualified: apisOk, integration_contracts_versioned: apisOk });
  const evidence_trust = nested({ evidence_id: evidenceOk ? "W5.2-CONTEXT-EVIDENCE-TRUST-001" : "", identity_bound: evidenceOk, source_governed: evidenceOk, tenant_isolated: evidenceOk, time_aware: evidenceOk, replayable: evidenceOk, explainable: evidenceOk, constitutionally_governed: evidenceOk, evidence_packages: evidenceOk, lineage: evidenceOk, source_references: evidenceOk, resolution_history: evidenceOk, trust_integration: evidenceOk, observability: evidenceOk, security_controls: evidenceOk });
  const readiness = nested({ readiness_id: "W5.2-UNIFIED-PERSONAL-CONTEXT-READINESS-001", decision, phase_ready: qualified, upstream_ready: !has(failures, "W5_APPLICATION_PLATFORM_INVALID"), registry_ready: registryOk, graph_ready: graphOk, timeline_ready: timelineOk, source_governance_ready: sourceOk, resolution_ready: resolutionOk, apis_ready: apisOk, evidence_trust_ready: evidenceOk, every_context_item_registered: registryOk, graph_relationships_deterministic: graphOk, historical_timeline_immutable: timelineOk, source_governance_operational: sourceOk, conflicts_resolve_deterministically: resolutionOk, governed_api_access: apisOk, evidence_lineage_complete: evidenceOk, replay_identical_context_state: timelineOk && resolutionOk, tenant_isolation_verified: apisOk && evidenceOk, trust_integration_operational: evidenceOk, sdks_qualified: apisOk, authoritative_personalization_platform: qualified && !has(failures, "AUTHORITATIVE_PERSONALIZATION_NOT_DECLARED"), failures });
  const base: Omit<WaveFiveUnifiedPersonalContextResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, upstream_refs: freezeArray(UPSTREAM_REFS), enables: freezeArray(ENABLES), tenant_id: input.tenant_id ?? platform.tenant_id, principal_id: input.principal_id ?? "principal:w5.2:context-owner", context_profile_id: input.context_profile_id ?? "context-profile:w5.2:canonical", registry, graph, timeline, source_governance, resolution, apis, evidence_trust, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateWaveFiveUnifiedPersonalContext(result?: WaveFiveUnifiedPersonalContextResult): WaveFiveUnifiedPersonalContextValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, registry_valid: false, graph_valid: false, timeline_valid: false, source_governance_valid: false, resolution_valid: false, apis_valid: false, evidence_trust_valid: false, readiness_valid: false, failures: freezeArray(["CONTEXT_REGISTRY_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const registry_valid = verifyHashed(result.registry) && result.registry.authoritative && result.registry.deterministic_identities && result.registry.metadata_validated && result.registry.version_lineage_complete;
  const graph_valid = verifyHashed(result.graph) && result.graph.relationships_deterministic && result.graph.graph_integrity_validated && result.graph.traversal_deterministic;
  const timeline_valid = verifyHashed(result.timeline) && result.timeline.immutable && result.timeline.reconstruction_verified && result.timeline.replay_deterministic;
  const source_governance_valid = verifyHashed(result.source_governance) && result.source_governance.sources_certified && result.source_governance.lineage_complete && result.source_governance.governance_deterministic;
  const resolution_valid = verifyHashed(result.resolution) && result.resolution.single_authoritative_value && result.resolution.deterministic && result.resolution.conflicts_resolved_consistently && result.resolution.replay_validated;
  const apis_valid = verifyHashed(result.apis) && result.apis.stable && result.apis.authorization_enforcement && result.apis.tenant_isolation && result.apis.sdk_qualified;
  const evidence_trust_valid = verifyHashed(result.evidence_trust) && result.evidence_trust.identity_bound && result.evidence_trust.source_governed && result.evidence_trust.tenant_isolated && result.evidence_trust.time_aware && result.evidence_trust.replayable && result.evidence_trust.explainable && result.evidence_trust.trust_integration;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.evidence_lineage_complete && result.readiness.replay_identical_context_state && result.readiness.tenant_isolation_verified && result.readiness.trust_integration_operational && result.readiness.authoritative_personalization_platform && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && registry_valid && graph_valid && timeline_valid && source_governance_valid && resolution_valid && apis_valid && evidence_trust_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, registry_valid, graph_valid, timeline_valid, source_governance_valid, resolution_valid, apis_valid, evidence_trust_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayWaveFiveUnifiedPersonalContext(result = runWaveFiveUnifiedPersonalContext()): boolean { const replayed = runWaveFiveUnifiedPersonalContext(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateWaveFiveUnifiedPersonalContext(result).valid; }
export function getWaveFiveUnifiedPersonalContextBundle(): WaveFiveUnifiedPersonalContextBundle { const result = runWaveFiveUnifiedPersonalContext(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, single_source_of_context: true, source_provenance_required: true, time_aware_context_required: true, deterministic_resolution_required: true, tenant_isolation_required: true, explainability_required: true, qualification_gate: "W5.2 Unified Personal Context Qualification Gate" }), result, validation: validateWaveFiveUnifiedPersonalContext(result) }); }
export const WaveFiveUnifiedPersonalContextService = Object.freeze({ run: runWaveFiveUnifiedPersonalContext, validate: validateWaveFiveUnifiedPersonalContext, replay: replayWaveFiveUnifiedPersonalContext });
