import type { LearningExecutionLease } from "./selfDirectedLearning";
import type { ProvenanceActor } from "./provenance";

export type AdversarialAttackType = "MISLEADING_SCENARIO" | "INCOMPLETE_EVIDENCE" | "UNUSUAL_EDGE_CASE" | "CONFLICTING_SIGNALS" | "CHANGED_ASSUMPTION" | "NEAR_MISS" | "PLAUSIBLE_WRONG_SOLUTION" | "BOUNDARY_VIOLATION" | "EXCEPTION_PROBE" | "DISTRACTOR_INJECTION" | "CONTEXT_SHIFT" | "CONFIDENCE_TRAP";
export type AdversarialExamStatus = "READY" | "ACTIVE" | "SUSPENDED" | "HALTED" | "COMPLETED";
export type AdversarialOutcome = "ROBUST_PASS" | "PASS_WITH_RESERVATION" | "PARTIAL_FAILURE" | "SYSTEMATIC_FAILURE" | "CATASTROPHIC_FAILURE" | "INCONCLUSIVE";
export type ExaminerIsolation = "INDEPENDENT" | "PARTIAL" | "SHARED_CONTEXT" | "EXPOSED";
export type TestChallengeStatus = "NONE" | "CHALLENGED" | "VALIDATED" | "INVALIDATED" | "AMBIGUOUS";
export type MasteryReassessmentAction = "NO_CHANGE" | "FLAG_FOR_RETEST" | "LOWER_CONFIDENCE" | "NARROW_SCOPE" | "MARK_PARTIALLY_MASTERED" | "SUSPEND_MASTERY" | "REVOKE_MASTERY";
export type AdversarialAttackPlan = Readonly<{ hypothesisId: string; attackType: AdversarialAttackType; reason: string; informationGain: "HIGH" | "MEDIUM" | "LOW"; selectionEffect: "RECOMMENDATION_ONLY"; executionPermissionGranted: false }>;
export type AdversarialAttackProfile = Readonly<{ testId: string; attackType: AdversarialAttackType; boundary: string; structuralFingerprint: string; outcome: AdversarialOutcome }>;
export type AdversarialExaminationAuditType = "ADVERSARIAL_EXAM_STARTED" | "ADVERSARIAL_TEST_GENERATED" | "ADVERSARIAL_ATTEMPT_COMMITTED" | "ADVERSARIAL_FINDING_RECORDED" | "MASTERY_CHALLENGED" | "MASTERY_REASSESSMENT_REQUIRED" | "ADVERSARIAL_TEST_CHALLENGED" | "ADVERSARIAL_TEST_INVALIDATED" | "ADVERSARIAL_EXAM_HALTED" | "ADVERSARIAL_EVIDENCE_SUBMITTED";
export type AdversarialFindingRoute = Readonly<{ route: "REFLECTION" | "MASTERY_REASSESSMENT" | "NO_ACTION"; reason: string; executionPermissionGranted: false; durableKnowledgeEffect: "NONE" }>;

export type FalseMasteryHypothesis = Readonly<{ hypothesisId: string; skillId: string; competencyClaimId: string; suspectedMechanism: string; boundary: string; expectedFailureSignal: string; createdBy: ProvenanceActor; createdAt: string; immutable: true; executionPermissionGranted: false; durableKnowledgeEffect: "NONE" }>;
export type AdversarialExam = Readonly<{ examId: string; curriculumId: string; lease: LearningExecutionLease; skillId: string; competencyClaimId: string; maximumTests: number; testsUsed: number; status: AdversarialExamStatus; examinerContextHash: string; learnerContextHash: string; startedAt: string; createdBy: ProvenanceActor; executionPermissionGranted: false; durableKnowledgeEffect: "NONE" }>;
/** Learner-visible scenario only. Hidden premise, attack rationale, and rubric are stored separately. */
export type AdversarialTest = Readonly<{ testId: string; examId: string; attackType: AdversarialAttackType; hypothesisId: string; scenario: string; constraints: readonly string[]; targetDimensions: readonly string[]; learnerContextHash: string; examinerContextHash: string; rubricId: string; integrity: "VALID" | "SUSPENDED" | "INVALID" | "AMBIGUOUS"; createdAt: string; immutable: true; executionPermissionGranted: false; durableKnowledgeEffect: "NONE" }>;
export type ExaminerRubric = Readonly<{ rubricId: string; testId: string; hiddenDifference: string; expectedReasoning: readonly string[]; plausibleWrongSolutions: readonly string[]; scoringCriteria: readonly string[]; isolation: ExaminerIsolation; revealedAt: string | null; immutable: true; examinerOnly: true; executionPermissionGranted: false; durableKnowledgeEffect: "NONE" }>;
export type AdversarialAttempt = Readonly<{ attemptId: string; testId: string; learnerContextHash: string; response: unknown; confidence: number | null; committedAt: string; hiddenMaterialExposedBeforeCommit: boolean; committedBy: ProvenanceActor; immutable: true }>;
export type ExaminerFinding = Readonly<{ findingId: string; testId: string; attemptId: string; outcome: AdversarialOutcome; failureClasses: readonly string[]; diagnosticRationale: string; confidenceCalibrationConcern: boolean; challengeStatus: TestChallengeStatus; evaluatorIndependent: boolean; createdAt: string; immutable: true; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type AdversarialEvidence = Readonly<{ evidenceId: string; skillId: string; testId: string; attemptId: string; findingId: string; outcome: AdversarialOutcome; isolation: ExaminerIsolation; evaluatorIndependent: boolean; exposedBeforeCommit: boolean; evidenceQuality: "HIGH" | "MEDIUM" | "LOW" | "INVALID"; priorExposure: boolean; createdAt: string; skillRegistryEffect: "EVIDENCE_ONLY"; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type AdversarialTestChallenge = Readonly<{ challengeId: string; testId: string; kind: "CHALLENGE_SCOPE" | "CHALLENGE_EVIDENCE" | "CHALLENGE_CONTRADICTION" | "CHALLENGE_RUBRIC"; rationale: string; status: TestChallengeStatus; createdAt: string; createdBy: ProvenanceActor; immutable: true; executionPermissionGranted: false; durableKnowledgeEffect: "NONE" }>;
export type MasteryReassessmentRecommendation = Readonly<{ recommendationId: string; skillId: string; competencyClaimId: string; action: MasteryReassessmentAction; scope: readonly string[]; basisFindingIds: readonly string[]; requiresReview: true; createdAt: string; createdBy: ProvenanceActor; executionPermissionGranted: false; durableKnowledgeEffect: "NONE" }>;
export type AdversarialExaminationArtifactRecord = Readonly<{ artifactId: string; artifactType: "EXAM" | "HYPOTHESIS" | "TEST" | "RUBRIC" | "ATTEMPT" | "FINDING" | "EVIDENCE" | "CHALLENGE" | "REASSESSMENT" | "STOP"; subjectId: string; payload: unknown; createdAt: string }>;
export interface AdversarialExaminationArtifactStore { append(artifact: AdversarialExaminationArtifactRecord): Promise<AdversarialExaminationArtifactRecord>; listArtifacts(subjectId: string): Promise<readonly AdversarialExaminationArtifactRecord[]>; listWorkspaceArtifacts(): Promise<readonly AdversarialExaminationArtifactRecord[]>; }
