import type { LearningExecutionLease } from "./selfDirectedLearning";
import type { PracticeEvidenceStrength, PracticeTransferLevel } from "./practiceEngine";
import type { ProvenanceActor } from "./provenance";

export type AutonomousPracticeStatus = "READY" | "ACTIVE" | "SUSPENDED" | "HALTED" | "COMPLETED";
export type ExerciseIntegrityStatus = "VALID" | "INVALID" | "AMBIGUOUS" | "OUTDATED" | "INSUFFICIENT_EVIDENCE" | "CONFLICTED";
export type AnswerKeyIsolation = "INDEPENDENT" | "PARTIAL" | "SHARED_CONTEXT" | "EXPOSED";
export type AutonomousEvidenceQuality = "HIGH" | "MEDIUM" | "LOW" | "INVALID";
export type AutonomousPracticeStopReason = "TARGET_REACHED" | "ATTEMPT_LIMIT_REACHED" | "DIMINISHING_RETURNS" | "REPEATED_IDENTICAL_FAILURE" | "PREREQUISITE_GAP" | "RESEARCH_REQUIRED" | "KNOWLEDGE_CONFLICT" | "EXERCISE_INTEGRITY_COMPROMISED" | "ANSWER_LEAKAGE" | "LEASE_EXPIRED" | "LEASE_REVOKED" | "HUMAN_INTERVENTION_REQUIRED";
export type AutonomousPracticeTarget = Readonly<{ skillId: string; dimension: string; rationale: string; recommendedDifficulty: number; recommendedTransferLevel: PracticeTransferLevel; selectionEffect: "RECOMMENDATION_ONLY"; executionPermissionGranted: false }>;
export type AutonomousPracticeDiversityProfile = Readonly<{ snapshotId: string; domain: string; transferLevel: PracticeTransferLevel; structuralFingerprint: string; reasoningFingerprint: string; knowledgeBasisIds: readonly string[] }>;
export type AutonomousPracticeDiversityReport = Readonly<{ diverse: boolean; repeatedDimensions: readonly string[]; repeatedDomains: readonly string[]; repeatedKnowledgeBasisIds: readonly string[]; recommendation: "PROCEED" | "VARY_CONTEXT" | "HALT_FOR_DIVERSITY" }>;
export type AutonomousPracticeFailureRoute = Readonly<{ route: "REFLECTION" | "RESEARCH_CANDIDATE" | "HALT"; reason: string; executionPermissionGranted: false; durableKnowledgeEffect: "NONE" }>;
export type AutonomousPracticeAuditType = "PRACTICE_SESSION_STARTED" | "EXERCISE_GENERATED" | "ANSWER_KEY_SEALED" | "ATTEMPT_STARTED" | "ATTEMPT_COMMITTED" | "ATTEMPT_EVALUATED" | "ANSWER_KEY_REVEALED" | "PRACTICE_FAILURE_DIAGNOSED" | "REMEDIATION_GENERATED" | "RESEARCH_REQUESTED" | "EXERCISE_INVALIDATED" | "PRACTICE_SESSION_HALTED" | "PRACTICE_SESSION_COMPLETED" | "PRACTICE_EVIDENCE_SUBMITTED";

/** An approved, lease-bound practice session. Selecting a target does not grant authority beyond this lease. */
export type AutonomousPracticeSession = Readonly<{ sessionId: string; curriculumId: string; lease: LearningExecutionLease; skillId: string; targetDimensions: readonly string[]; maximumExercises: number; exercisesUsed: number; status: AutonomousPracticeStatus; startedAt: string; haltedAt: string | null; haltReason: AutonomousPracticeStopReason | null; createdBy: ProvenanceActor; executionPermissionGranted: false; durableKnowledgeEffect: "NONE" }>;
/** Frozen prompt-visible material, with all evaluator-only content held in a separate sealed-key artifact. */
export type AutonomousExerciseSnapshot = Readonly<{ snapshotId: string; sessionId: string; practiceExerciseId: string; skillId: string; difficulty: number; transferLevel: PracticeTransferLevel; knowledgeBasisIds: readonly string[]; learnerContextHash: string; evaluatorContextHash: string; answerKeyId: string; answerKeyHash: string; integrityStatus: ExerciseIntegrityStatus; createdAt: string; immutable: true; executionPermissionGranted: false; durableKnowledgeEffect: "NONE" }>;
export type SealedAnswerKey = Readonly<{ answerKeyId: string; snapshotId: string; expectedResult: string; rubric: readonly string[]; acceptableVariations: readonly string[]; commonErrors: readonly string[]; isolation: AnswerKeyIsolation; sealedAt: string; revealedAt: string | null; immutable: true; evaluatorOnly: true; executionPermissionGranted: false; durableKnowledgeEffect: "NONE" }>;
export type AutonomousPracticeAttempt = Readonly<{ attemptId: string; snapshotId: string; learnerContextHash: string; response: unknown; committedAt: string; answerExposureBeforeCommit: boolean; committedBy: ProvenanceActor; immutable: true }>;
export type AutonomousPracticeEvidence = Readonly<{ evidenceId: string; sessionId: string; snapshotId: string; attemptId: string; outcome: "PASS" | "PARTIAL" | "FAIL" | "UNCERTAIN"; evidenceQuality: AutonomousEvidenceQuality; practiceEvidenceStrength: PracticeEvidenceStrength; isolation: AnswerKeyIsolation; evaluatorIndependent: boolean; answerExposureBeforeCommit: boolean; createdAt: string; skillRegistryEffect: "EVIDENCE_ONLY"; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type AutonomousPracticeArtifactRecord = Readonly<{ artifactId: string; artifactType: "SESSION" | "EXERCISE_SNAPSHOT" | "SEALED_ANSWER_KEY" | "ATTEMPT" | "EVIDENCE" | "STOP" | "RESEARCH_HANDOFF" | "INTEGRITY_EVENT"; subjectId: string; payload: unknown; createdAt: string }>;
export interface AutonomousPracticeArtifactStore { append(artifact: AutonomousPracticeArtifactRecord): Promise<AutonomousPracticeArtifactRecord>; listArtifacts(subjectId: string): Promise<readonly AutonomousPracticeArtifactRecord[]>; listWorkspaceArtifacts(): Promise<readonly AutonomousPracticeArtifactRecord[]>; }
