import type { ProvenanceActor } from "./provenance";

export type CapabilityRequestStatus = "REQUESTED" | "UNDER_REVIEW" | "APPROVED" | "DENIED" | "DEFERRED";
export type CapabilityGrantStatus = "ACTIVE" | "SUSPENDED" | "EXPIRED" | "REVOKED" | "CLOSED";
export type CapabilityAuditType = "CAPABILITY_REQUESTED" | "CAPABILITY_APPROVED" | "CAPABILITY_DENIED" | "CAPABILITY_ACTIVATED" | "CAPABILITY_USED" | "CAPABILITY_BLOCKED" | "CAPABILITY_EXPIRED" | "CAPABILITY_SUSPENDED" | "CAPABILITY_REVOKED" | "CAPABILITY_SCOPE_VIOLATION" | "CAPABILITY_ESCALATION_ATTEMPT";
export type CapabilityRequest = Readonly<{ requestId: string; actor: ProvenanceActor; capability: string; operations: readonly string[]; resourceId: string; scope: readonly string[]; purpose: string; relatedTaskId: string | null; supportingCertificationIds: readonly string[]; requestedDurationMinutes: number; riskClass: "LOW" | "MODERATE" | "HIGH" | "CRITICAL"; constraints: readonly string[]; status: CapabilityRequestStatus; createdAt: string; immutable: true; learningEvidenceOnly: true; executionPermissionGranted: false }>;
export type CapabilityGrant = Readonly<{ grantId: string; requestId: string; actor: ProvenanceActor; capability: string; operations: readonly string[]; resourceId: string; scope: readonly string[]; constraints: readonly string[]; grantedBy: ProvenanceActor; grantedAt: string; expiresAt: string; status: CapabilityGrantStatus; revocable: true; immutable: true; certificationEvidenceOnly: true; executionPermissionGranted: true }>;
export type CapabilityGrantLifecycleEvent = Readonly<{ eventId: string; grantId: string; from: CapabilityGrantStatus; to: Exclude<CapabilityGrantStatus, "ACTIVE">; reason: string; actor: ProvenanceActor | null; occurredAt: string; immutable: true; executionPermissionGranted: false }>;
export type CapabilityPreflightRequest = Readonly<{ actor: ProvenanceActor; capability: string; operation: string; resourceId: string; scope: string; satisfiedConstraints: readonly string[]; requestedAt: string; availableTool: boolean }>;
export type CapabilityPreflightResult = Readonly<{ authorized: boolean; reason: "AUTHORIZED" | "NO_GRANT" | "TOOL_UNAVAILABLE" | "ACTOR_MISMATCH" | "CAPABILITY_MISMATCH" | "OPERATION_OUT_OF_SCOPE" | "RESOURCE_OUT_OF_SCOPE" | "SCOPE_OUT_OF_SCOPE" | "CONSTRAINT_UNSATISFIED" | "EXPIRED" | "REVOKED" | "SUSPENDED" | "AMBIGUOUS"; grantId: string | null; executionPermissionGranted: boolean }>;
export type CapabilityArtifactRecord = Readonly<{ artifactId: string; artifactType: "REQUEST" | "GRANT" | "LIFECYCLE" | "PREFLIGHT"; subjectId: string; payload: unknown; createdAt: string }>;
export interface CapabilityArtifactStore { append(artifact: CapabilityArtifactRecord): Promise<CapabilityArtifactRecord>; listArtifacts(subjectId: string): Promise<readonly CapabilityArtifactRecord[]>; listWorkspaceArtifacts(): Promise<readonly CapabilityArtifactRecord[]>; }
