export const CLASSIFICATION_PRECEDENCE_RULES = [
  "HYPOTHETICAL_CONTAINMENT",
  "CURRENT_EXPLICIT_CORRECTION",
  "CURRENT_EXPLICIT_EXCEPTION",
  "CURRENT_EXPLICIT_DECISION",
  "CURRENT_EXPLICIT_CATEGORY_MARKER",
  "QUESTION_FORM",
  "EXPLICIT_DIRECTIVE",
  "INHERITED_CONTEXT",
  "FALLBACK_REVIEW",
] as const;
export type ClassificationPrecedenceRule = (typeof CLASSIFICATION_PRECEDENCE_RULES)[number];

export type ClassificationCardinalityValidation = Readonly<{
  status: "VALID" | "INVALID";
  reasonCode?: "DUPLICATE_SEMANTIC_UNIT_ID" | "MISSING_SEMANTIC_UNIT_ID";
}>;
