export const LEARNING_PIPELINE_STAGES = [
  "OBSERVATION",
  "CLASSIFICATION",
  "SCOPE_DETERMINATION",
  "CONFLICT_DETECTION",
  "VALIDATION",
  "LEARNING_DECISION",
  "DURABLE_KNOWLEDGE",
] as const;

export type LearningPipelineStage = (typeof LEARNING_PIPELINE_STAGES)[number];

export const KNOWLEDGE_CLASSIFICATIONS = [
  "CONVERSATION",
  "BRAINSTORMING",
  "SUGGESTION",
  "FACT",
  "PREFERENCE",
  "INSTRUCTION",
  "PROJECT_DECISION",
  "PRINCIPLE",
  "PROCEDURE",
  "CORRECTION",
  "EXCEPTION",
  "AUTHORITATIVE_RULE",
] as const;

export type KnowledgeClassification = (typeof KNOWLEDGE_CLASSIFICATIONS)[number];

export const KNOWLEDGE_SCOPES = [
  "CONVERSATION",
  "SESSION",
  "USER",
  "AGENT",
  "PROJECT",
  "WORKSPACE",
  "ORGANIZATION",
  "DOMAIN",
  "COMPONENT",
  "TASK",
  "SYSTEM",
  "GLOBAL",
] as const;

export type KnowledgeScope = (typeof KNOWLEDGE_SCOPES)[number];

export const KNOWLEDGE_DISPOSITIONS = [
  "ACCEPT",
  "REJECT",
  "DEFER",
  "REQUIRE_VALIDATION",
  "REQUIRE_APPROVAL",
  "CONFLICT",
  "QUARANTINE",
] as const;

export type KnowledgeDisposition = (typeof KNOWLEDGE_DISPOSITIONS)[number];

export const VALIDATION_STATUSES = [
  "NOT_VALIDATED",
  "REQUIRES_VALIDATION",
  "VALID",
  "INVALID",
] as const;

export type ValidationStatus = (typeof VALIDATION_STATUSES)[number];

export const CONFLICT_RELATIONSHIPS = [
  "AGREES",
  "DUPLICATES",
  "REINFORCES",
  "EXTENDS",
  "REFINES",
  "QUALIFIES",
  "NARROWS",
  "CONTRADICTS",
  "CORRECTS",
  "CREATES_EXCEPTION",
  "UNRELATED",
  "UNCERTAIN",
] as const;

export type ConflictRelationship = (typeof CONFLICT_RELATIONSHIPS)[number];

export const AUTHORITY_RELATIONSHIPS = [
  "INFORMS_REASONING",
  "REQUIRES_SEPARATE_AUTHORIZATION",
  "DOES_NOT_GRANT_AUTHORITY",
] as const;

export type AuthorityRelationship = (typeof AUTHORITY_RELATIONSHIPS)[number];

export const CONSTITUTIONAL_INVARIANTS = [
  "CONVERSATION_IS_NOT_AUTOMATICALLY_LEARNING",
  "NON_LEARNING_IS_THE_DEFAULT",
  "CLASSIFICATION_IS_MANDATORY",
  "SCOPE_IS_MANDATORY",
  "CONFLICT_DETECTION_IS_MANDATORY",
  "VALIDATION_IS_INDEPENDENT",
  "PROVENANCE_IS_MANDATORY",
  "DURABLE_PROVENANCE_MUST_BE_RECONSTRUCTABLE",
  "PROVENANCE_HISTORY_IS_IMMUTABLE",
  "HISTORICAL_TRUTH_IS_DISTINCT_FROM_CURRENT_TRUTH",
  "FAILURE_IS_NON_LEARNING",
  "LEARNING_DOES_NOT_GRANT_AUTHORITY",
  "NORMAL_LEARNING_CANNOT_AMEND_THE_CONSTITUTION",
] as const;

export type ConstitutionalInvariant = (typeof CONSTITUTIONAL_INVARIANTS)[number];
