import type { ProvenanceActor } from "./provenance";

export type EpistemicStatus = "UNASSESSED" | "INSUFFICIENT_EVIDENCE" | "PROVISIONALLY_SUPPORTED" | "SUPPORTED" | "STRONGLY_SUPPORTED" | "MIXED" | "CONFLICTING" | "SUSPENDED_JUDGMENT" | "UNSUPPORTED" | "REJECTED" | "REFUTED" | "UNRESOLVED";
export type EpistemicConfidence = "VERY_LOW" | "LOW" | "MODERATE" | "HIGH" | "VERY_HIGH";
export type EpistemicRevisionTrigger = "NEW_STRONG_EVIDENCE" | "NEW_CONFLICT" | "SOURCE_REASSESSMENT" | "SOURCE_RETRACTION" | "TEMPORAL_CHANGE" | "SCOPE_CHANGE" | "HUMAN_CORRECTION" | "NEW_EXCEPTION" | "EVALUATION_FAILURE" | "PREDICTION_FAILURE";
export type AssumptionStatus = "UNVERIFIED" | "SUPPORTED" | "REJECTED" | "RETIRED";
export type EpistemicSynthesisAuditType = "EPISTEMIC_PROPOSITION_CREATED" | "BELIEF_ASSESSED" | "BELIEF_SUPPORTED" | "BELIEF_WEAKENED" | "BELIEF_STRENGTHENED" | "BELIEF_SUSPENDED" | "BELIEF_REJECTED" | "BELIEF_REFUTED" | "BELIEF_REVISED" | "ASSUMPTION_REGISTERED" | "EPISTEMIC_DEBT_CREATED" | "EPISTEMIC_DEBT_RESOLVED" | "BELIEF_CONFLICT_CREATED" | "BELIEF_DEPENDENCY_INVALIDATED" | "EPISTEMIC_REASSESSMENT_REQUIRED";
export type EpistemicGuardDecision = Readonly<{ allowed: boolean; disposition: "ALLOW" | "SUSPEND" | "REQUEST_MORE_EVIDENCE"; reason: string; unresolvedAlternatives: readonly string[] }>;

/** A normalized proposition is distinct from a source assertion and from a durable-knowledge record. */
export type EpistemicProposition = Readonly<{ propositionId: string; normalizedKey: string; statement: string; polarity: "AFFIRM" | "DENY"; scope: readonly string[]; validFrom: string | null; validTo: string | null; createdBy: ProvenanceActor; createdAt: string; immutable: true; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
/** Versioned, canonical inputs that make one synthesis replayable instead of a mutable confidence aggregate. */
export type SynthesisSnapshot = Readonly<{ snapshotId: string; propositionId: string; asOf: string; evidenceClusterIds: readonly string[]; sourceAssessmentIds: readonly string[]; conflictIds: readonly string[]; knowledgeGapIds: readonly string[]; exceptionIds: readonly string[]; assumptionIds: readonly string[]; policyVersion: string; inputHash: string; createdAt: string; immutable: true }>;
export type EpistemicPosition = Readonly<{ positionId: string; propositionId: string; snapshotId: string; status: EpistemicStatus; confidence: EpistemicConfidence; supportingClusterIds: readonly string[]; conflictingClusterIds: readonly string[]; strongestSupportingClusterId: string | null; strongestConflictingClusterId: string | null; uncertainties: readonly string[]; conditions: readonly string[]; whatWouldChange: readonly string[]; explanation: string; assessedBy: ProvenanceActor; assessedAt: string; durableStatus: "NOT_SUBMITTED" | "CANDIDATE" | "DEFERRED"; authorityEffect: "UNCHANGED"; executionPermissionGranted: false; immutable: true }>;
export type EpistemicAssumption = Readonly<{ assumptionId: string; statement: string; requiredByIds: readonly string[]; evidenceIds: readonly string[]; status: AssumptionStatus; createdBy: ProvenanceActor; createdAt: string; immutable: true; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type EpistemicDependency = Readonly<{ dependencyId: string; upstreamPropositionId: string; downstreamId: string; downstreamKind: "PROPOSITION" | "DECISION" | "PREDICTION" | "PRINCIPLE" | "PROCEDURE" | "CURRICULUM" | "SKILL"; createdAt: string; createdBy: ProvenanceActor; immutable: true }>;
export type EpistemicDebt = Readonly<{ debtId: string; propositionId: string; positionId: string; usedByIds: readonly string[]; weaknesses: readonly string[]; status: "OPEN" | "RESOLVED" | "RETIRED"; createdAt: string; createdBy: ProvenanceActor; immutable: true; executionPermissionGranted: false }>;
export type EpistemicRevision = Readonly<{ revisionId: string; propositionId: string; priorPositionId: string; nextPositionId: string; priorStatus: EpistemicStatus; nextStatus: EpistemicStatus; trigger: EpistemicRevisionTrigger; affectedDependencyIds: readonly string[]; reassessmentRequired: true; createdAt: string; createdBy: ProvenanceActor; immutable: true; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type EpistemicSynthesisArtifactRecord = Readonly<{ artifactId: string; artifactType: "PROPOSITION" | "SNAPSHOT" | "POSITION" | "ASSUMPTION" | "DEPENDENCY" | "DEBT" | "REVISION"; subjectId: string; payload: unknown; createdAt: string }>;
export interface EpistemicSynthesisArtifactStore { append(artifact: EpistemicSynthesisArtifactRecord): Promise<EpistemicSynthesisArtifactRecord>; listArtifacts(subjectId: string): Promise<readonly EpistemicSynthesisArtifactRecord[]>; listWorkspaceArtifacts(): Promise<readonly EpistemicSynthesisArtifactRecord[]>; }
