import type { LearningExecutionLease, LearningMethod } from "./selfDirectedLearning";
export type GovernedExecutionMechanism = "SOCRATIC_INTERVIEW" | "PRACTICE" | "EVALUATION" | "TEACH_BACK" | "DECISION_REVIEW" | "CORRECTION_REVIEW" | "REMEDIATION";
export type GovernedExecutionStatus = "PROPOSED" | "AUTHORIZED" | "READY" | "RUNNING" | "PAUSED" | "HALTED" | "COMPLETED";
export type ExecutionStopType = "LEASE_EXPIRED" | "LEASE_REVOKED" | "QUESTION_LIMIT_REACHED" | "ATTEMPT_LIMIT_REACHED" | "EVALUATION_LIMIT_REACHED" | "SCOPE_DRIFT" | "GOAL_COMPLETED" | "TIME_LIMIT_REACHED" | "DIMINISHING_RETURNS" | "REPEATED_FAILURE" | "PREREQUISITE_GAP_DISCOVERED" | "KNOWLEDGE_CONFLICT_DISCOVERED" | "HUMAN_CORRECTION_RECEIVED" | "SAFETY_OR_CONSTITUTIONAL_VIOLATION" | "TEACHER_STOP_REQUEST";
export type GovernedMechanismMethod = Readonly<Record<GovernedExecutionMechanism, LearningMethod>>;
export type GovernedExecutionAction = Readonly<{ actionId: string; curriculumId: string; lease: LearningExecutionLease; mechanism: GovernedExecutionMechanism; targetSkillId: string; scope: string; questionCost: number; attemptCost: number; evaluationCost: number; executedAt: string }>;
export type ExecutionBudget = Readonly<{ questionLimit: number; attemptLimit: number; evaluationLimit: number; questionsUsed: number; attemptsUsed: number; evaluationsUsed: number }>;
export type ExecutionAuthorization = Readonly<{ allowed: boolean; reason: "AUTHORIZED" | ExecutionStopType | "METHOD_NOT_AUTHORIZED"; remaining: ExecutionBudget }>;
export type LearningExecutionTimelineEvent = Readonly<{ eventId: string; curriculumId: string; leaseId: string; actionId: string | null; status: GovernedExecutionStatus; mechanism: GovernedExecutionMechanism | null; targetSkillId: string | null; reason: string; occurredAt: string }>;
export type ExecutionStopCondition = Readonly<{ conditionId: string; type: ExecutionStopType; threshold: number | null; triggered: boolean; requiredResponse: "HALT" | "PAUSE"; triggeredAt: string | null }>;
export type ExecutionOutcomeRoute = "TEACH_BACK" | "EVALUATION" | "REFLECTION" | "CORRECTION" | "DURABLE_LEARNING_GATE" | "KNOWLEDGE_GAP_REASSESSMENT" | "CURRICULUM_REPLAN";
export type GovernedExecutionOutcome = Readonly<{ outcomeId: string; sessionId: string; actionId: string; route: ExecutionOutcomeRoute; evidenceIds: readonly string[]; directDurableWrite: false; createdAt: string }>;
export type UnauthorizedGapCandidate = Readonly<{ candidateGapId: string; sessionId: string; actionId: string; subject: string; discoveredScope: string; evidenceIds: readonly string[]; pursued: false; requiresNewProposal: true; createdAt: string }>;
export type GovernedExecutionSummary = Readonly<{ summaryId: string; sessionId: string; curriculumId: string; leaseId: string; status: Extract<GovernedExecutionStatus, "HALTED" | "COMPLETED">; budget: ExecutionBudget; outcomeIds: readonly string[]; deferredGapIds: readonly string[]; durableKnowledgeEffect: "NONE"; furtherExecutionAuthorized: false; createdAt: string }>;
export type LearningExecutionSession = Readonly<{ sessionId: string; curriculumId: string; leaseId: string; status: GovernedExecutionStatus; startedAt: string; haltedAt: string | null; haltReason: ExecutionStopType | null; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type GovernedExecutionArtifactRecord = Readonly<{ artifactId: string; artifactType: "SESSION" | "TIMELINE" | "STOP_CONDITION" | "OUTCOME" | "CANDIDATE_GAP" | "SUMMARY"; subjectId: string; payload: unknown; createdAt: string }>;
export interface GovernedExecutionArtifactStore { append(artifact: GovernedExecutionArtifactRecord): Promise<GovernedExecutionArtifactRecord>; listArtifacts(subjectId: string): Promise<readonly GovernedExecutionArtifactRecord[]>; listWorkspaceArtifacts(): Promise<readonly GovernedExecutionArtifactRecord[]>; }
