import type { EpistemicState, KnowledgeGapSeverity } from "./knowledgeGapDetection";
import type { ProvenanceActor } from "./provenance";
export type LearningMethod = "SOCRATIC_INTERVIEW" | "DIRECT_TEACHING_REQUEST" | "EXAMPLE_COLLECTION" | "COUNTEREXAMPLE_COLLECTION" | "PRACTICE_SEQUENCE" | "TARGETED_EVALUATION" | "DECISION_REVIEW" | "CORRECTION_REVIEW";
export type LearningProposalStatus = "CANDIDATE" | "ANALYZED" | "AWAITING_HUMAN_APPROVAL" | "APPROVED" | "MODIFIED" | "DEFERRED" | "REJECTED" | "CANCELLED" | "EXPIRED";
export type LearningOpportunity = Readonly<{ opportunityId: string; sourceGapId: string; triggerIds: readonly string[]; subject: string; currentState: EpistemicState; scope: string; impact: KnowledgeGapSeverity; recurrence: number; expectedInformationGain: "LOW" | "MEDIUM" | "HIGH"; expectedImprovement: "LOW" | "MEDIUM" | "HIGH"; teacherEffort: "LOW" | "MODERATE" | "HIGH"; risks: readonly string[]; alternatives: readonly LearningMethod[]; priority: "LOW" | "MEDIUM" | "HIGH" | "VERY_HIGH"; recommendedMethod: LearningMethod; status: "CANDIDATE"; createdBy: ProvenanceActor; createdAt: string; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type LearningOpportunitySignal = Readonly<{ signalId: string; gapId: string; kind: "PREDICTION_CORRECTION" | "REFLECTION" | "EVALUATION_FAILURE" | "PRACTICE_FAILURE" | "CONFLICT" | "SOCRATIC_DISCOVERY"; indicates: "KNOWLEDGE" | "PRACTICE" | "EVALUATION"; recurrence: number; impact: KnowledgeGapSeverity; evidenceIds: readonly string[] }>;
export type LearningProposal = Readonly<{ proposalId: string; opportunityId: string; sourceGapIds: readonly string[]; objective: string; scope: string; whyLearnThis: string; evidenceIds: readonly string[]; missingUnderstanding: readonly string[]; method: LearningMethod; teacherEffortBudget: Readonly<{ estimatedQuestions: number; maximumQuestions: number; estimatedMinutes: number }>; risks: readonly string[]; successCriteria: readonly string[]; baselineEvidenceIds: readonly string[]; status: LearningProposalStatus; approvalRequired: true; createdBy: ProvenanceActor; createdAt: string; expiresAt: string; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type LearningProposalApproval = Readonly<{ approvalId: string; proposalId: string; decision: "APPROVE" | "MODIFY" | "DEFER" | "REJECT"; approvedScope: string; approvedMethod: LearningMethod; approvedBudget: Readonly<{ maximumQuestions: number }>; decidedBy: ProvenanceActor; decidedAt: string; executionLeaseId: string | null }>;
export type LearningExecutionLease = Readonly<{ leaseId: string; proposalId: string; approvalId: string; scope: string; method: LearningMethod; maximumQuestions: number; issuedBy: ProvenanceActor; issuedAt: string; expiresAt: string; status: "ACTIVE" | "REVOKED" | "EXPIRED" }>;
export type LearningBaseline = Readonly<{ baselineId: string; proposalId: string; gapId: string; knowledgeState: EpistemicState; predictionAccuracy: number | null; competenceScore: number | null; evidenceIds: readonly string[]; recordedAt: string; recordedBy: ProvenanceActor; immutable: true }>;
export type LearningOutcome = Readonly<{ outcomeId: string; proposalId: string; gapId: string; result: "IMPROVED" | "PARTIALLY_IMPROVED" | "NO_MEASURABLE_CHANGE" | "REGRESSED" | "INCONCLUSIVE"; predictionAccuracyBefore: number | null; predictionAccuracyAfter: number | null; competenceBefore: number | null; competenceAfter: number | null; evaluationEvidenceIds: readonly string[]; gapResolutionAuthorized: false; createdAt: string; createdBy: ProvenanceActor; immutable: true }>;
export type SelfDirectedLearningArtifactRecord = Readonly<{ artifactId: string; artifactType: "OPPORTUNITY" | "PROPOSAL" | "APPROVAL" | "LEASE" | "BASELINE" | "OUTCOME"; subjectId: string; payload: unknown; createdAt: string }>;
export interface SelfDirectedLearningArtifactStore { append(artifact: SelfDirectedLearningArtifactRecord): Promise<SelfDirectedLearningArtifactRecord>; listArtifacts(subjectId: string): Promise<readonly SelfDirectedLearningArtifactRecord[]>; listWorkspaceArtifacts(): Promise<readonly SelfDirectedLearningArtifactRecord[]>; }
