import type { ProvenanceActor } from "./provenance";
import type { TeachBackGenerationRequest } from "./teachBack";

export const SOCRATIC_KNOWLEDGE_STATES = ["KNOWN", "PARTIALLY_KNOWN", "AMBIGUOUS", "CONFLICTING", "INFERRED", "UNKNOWN"] as const;
export type SocraticKnowledgeState = (typeof SOCRATIC_KNOWLEDGE_STATES)[number];
export type LearningObjectiveScope = "GENERAL" | "WORKSPACE" | "PROJECT";
export type LearningObjectiveStatus = "ACTIVE" | "SATISFIED" | "PAUSED" | "CANCELLED";
export type SocraticSessionStatus = "ACTIVE" | "SATURATED" | "VALIDATING" | "TEACH_BACK_PENDING" | "COMPLETED" | "CANCELLED";
export const SOCRATIC_HYPOTHESIS_STATES = ["PROPOSED", "SUPPORTED", "STRONGLY_SUPPORTED", "VALIDATED", "WEAKENED", "CONTRADICTED", "SUPERSEDED", "REJECTED", "UNRESOLVED"] as const;
export type SocraticHypothesisState = (typeof SOCRATIC_HYPOTHESIS_STATES)[number];
export const SOCRATIC_QUESTION_TYPES = ["CLARIFICATION", "CONTRAST", "TRADEOFF", "COUNTERFACTUAL", "BOUNDARY", "EXCEPTION", "EXAMPLE", "COUNTEREXAMPLE", "PRIORITY", "PREDICTION"] as const;
export type SocraticQuestionType = (typeof SOCRATIC_QUESTION_TYPES)[number];
export type SocraticHumanEffort = "VERY_LOW" | "LOW" | "MODERATE" | "HIGH" | "VERY_HIGH";
/** Read-only discovery input. A source may inform a working model but never grants durable authority. */
export type SocraticKnowledgeObservation = Readonly<{ observationId: string; sourceType: "KNOWLEDGE" | "PRINCIPLE" | "PROCEDURE" | "PREFERENCE" | "DECISION" | "CORRECTION" | "EXAMPLE" | "SKILL" | "INTERVIEW"; sourceId: string; scope: LearningObjectiveScope; summary: string; confidence: number; createdAt: string }>;
export type LearningObjective = Readonly<{ objectiveId: string; objective: string; teacher: ProvenanceActor; scope: LearningObjectiveScope; scopeId: string | null; desiredDepth: "LOW" | "MEDIUM" | "HIGH"; successCriteria: readonly string[]; status: LearningObjectiveStatus; createdBy: ProvenanceActor; createdAt: string; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type SocraticKnowledgeMapNode = Readonly<{ nodeId: string; label: string; state: SocraticKnowledgeState; confidence: number; observationIds: readonly string[]; rationale: string }>;
export type SocraticKnowledgeMap = Readonly<{ mapId: string; objectiveId: string; nodes: readonly SocraticKnowledgeMapNode[]; sourceObservationIds: readonly string[]; createdAt: string; workingModelOnly: true }>;
export type SocraticKnowledgeGap = Readonly<{ gapId: string; sessionId: string; nodeId: string; state: Exclude<SocraticKnowledgeState, "KNOWN">; uncertainty: number; objectiveRelevance: number; priority: number; rationale: string; observationIds: readonly string[]; createdAt: string; workingModelOnly: true }>;
/** A competing interpretation is an inspectable, revisable explanation — never a durable claim. */
export type SocraticHypothesis = Readonly<{ hypothesisId: string; sessionId: string; nodeId: string; claim: string; state: SocraticHypothesisState; confidence: number; supportingObservationIds: readonly string[]; contradictingObservationIds: readonly string[]; rationale: string; version: number; createdBy: ProvenanceActor; createdAt: string; workingModelOnly: true; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
/** Candidates remain internal until selection; a question is not a claim about the teacher. */
export type SocraticQuestionCandidate = Readonly<{ candidateId: string; sessionId: string; question: string; questionType: SocraticQuestionType; targetNodeIds: readonly string[]; hypothesisIds: readonly string[]; uncertaintyReduction: number; objectiveRelevance: number; hypothesisSeparation: number; reuseValue: number; humanEffort: SocraticHumanEffort; leadingBiasRisk: number; redundancyRisk: number; informationGainScore: number; createdAt: string; workingModelOnly: true }>;
export type SocraticSelectedQuestion = Readonly<{ questionId: string; sessionId: string; candidateId: string; question: string; questionType: SocraticQuestionType; selectedAt: string; selectedBy: ProvenanceActor; questionBudgetPosition: number; workingModelOnly: true }>;
export type SocraticHumanAnswer = Readonly<{ answerId: string; sessionId: string; questionId: string; answer: string; answeredBy: ProvenanceActor; answeredAt: string; workingModelOnly: true; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type SocraticAnswerExtraction = Readonly<{ extractionId: string; answerId: string; kind: "EXPLICIT_CLAIM" | "PREFERENCE" | "PRINCIPLE_CANDIDATE" | "EXCEPTION" | "CORRECTION" | "UNCERTAINTY"; statement: string; confidence: number; provisional: true }>;
export type SocraticWorkingModelUpdate = Readonly<{ updateId: string; sessionId: string; previousMapId: string; nextMapId: string; answerId: string; affectedNodeIds: readonly string[]; uncertaintyBefore: number; uncertaintyAfter: number; createdAt: string; workingModelOnly: true }>;
export type SocraticSaturationDecision = Readonly<{ sessionId: string; saturated: boolean; reason: "LOW_MARGINAL_INFORMATION_GAIN" | "QUESTION_BUDGET_EXHAUSTED" | "OBJECTIVE_COVERAGE_SUFFICIENT" | "MORE_QUESTIONS_REQUIRED"; remainingGapPriority: number; questionsAsked: number; maximumQuestionBudget: number }>;
export type SocraticPrediction = Readonly<{ predictionId: string; sessionId: string; scenario: string; predictedJudgment: string; rationale: string; supportingHypothesisIds: readonly string[]; boundaryStatement: string; createdBy: ProvenanceActor; createdAt: string; workingModelOnly: true }>;
export type SocraticPredictionReview = Readonly<{ reviewId: string; predictionId: string; outcome: "CONFIRMED" | "CORRECTED"; feedback: string; reviewedBy: ProvenanceActor; reviewedAt: string; workingModelOnly: true }>;
/** Controlled handoff metadata only. The existing Teach-Back and learning-gate systems decide every subsequent admission. */
export type SocraticTeachBackHandoff = Readonly<{ handoffId: string; sessionId: string; teachBackRequest: TeachBackGenerationRequest; submittedAt: string; submittedBy: ProvenanceActor; durableLearningAuthorization: "GATE_REQUIRED"; workingModelOnly: true }>;
export type SocraticCorrectionReplan = Readonly<{ replanId: string; sessionId: string; predictionReviewId: string; affectedHypothesisIds: readonly string[]; recommendedQuestionType: "BOUNDARY" | "COUNTERFACTUAL" | "CLARIFICATION"; reason: string; createdAt: string; workingModelOnly: true }>;
/** Submission has evidence and lineage, but no classification, scope resolution, gate decision, or registry-write authority. */
export type SocraticCandidateKnowledgeSubmission = Readonly<{ submissionId: string; sessionId: string; candidateId: string; claim: string; sourceAnswerIds: readonly string[]; hypothesisIds: readonly string[]; predictionReviewId: string; teachBackHandoffId: string; submittedBy: ProvenanceActor; submittedAt: string; status: "GATE_SUBMISSION_REQUIRED"; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type SocraticSession = Readonly<{ sessionId: string; objectiveId: string; status: SocraticSessionStatus; knowledgeMapId: string; questionBudget: Readonly<{ preferred: number; maximum: number }>; questionsAsked: readonly string[]; uncertaintyBefore: number; uncertaintyCurrent: number; informationGain: number; createdBy: ProvenanceActor; createdAt: string; durableLearningStatus: "NOT_YET_EVALUATED"; durableKnowledgeEffect: "NONE"; executionPermissionGranted: false }>;
export type SocraticArtifactRecord = Readonly<{ artifactId: string; artifactType: "OBJECTIVE" | "KNOWLEDGE_SNAPSHOT" | "KNOWLEDGE_MAP" | "KNOWLEDGE_GAP" | "HYPOTHESIS" | "QUESTION_CANDIDATE" | "QUESTION_SELECTED" | "HUMAN_ANSWER" | "ANSWER_EXTRACTION" | "WORKING_MODEL_UPDATE" | "SATURATION" | "PREDICTION" | "PREDICTION_REVIEW" | "TEACH_BACK_HANDOFF" | "CORRECTION_REPLAN" | "CANDIDATE_SUBMISSION" | "SESSION" | "LIFECYCLE"; subjectId: string; payload: unknown; createdAt: string }>;
export interface SocraticArtifactStore { append(artifact: SocraticArtifactRecord): Promise<SocraticArtifactRecord>; listArtifacts(subjectId: string): Promise<readonly SocraticArtifactRecord[]>; listWorkspaceArtifacts(): Promise<readonly SocraticArtifactRecord[]>; }
export interface SocraticKnowledgeSource { retrieve(objective: LearningObjective): Promise<readonly SocraticKnowledgeObservation[]>; }
