import type { ProvenanceActor } from "./provenance";
import type { LearningExecutionLease } from "./selfDirectedLearning";

export const LEARNING_PRIMITIVES = ["PREREQUISITE_CHECK", "QUESTION", "EXPLAIN", "RESEARCH", "SOURCE_CRITICISM", "SYNTHESIZE", "EXAMPLE", "COUNTEREXAMPLE", "WORKED_EXAMPLE", "PARTIAL_EXAMPLE", "GUIDED_PRACTICE", "INDEPENDENT_PRACTICE", "NOVEL_PRACTICE", "TEACH_BACK", "REFLECTION", "RECALL", "EVALUATION", "ADVERSARIAL_TEST", "RETENTION_TEST", "REMEDIATION", "RETEST"] as const;
export type LearningPrimitive = typeof LEARNING_PRIMITIVES[number];
export type StrategyLifecycleStatus = "HYPOTHESIS" | "CANDIDATE" | "EXPERIMENTAL" | "VALIDATED" | "APPROVED" | "ACTIVE" | "REJECTED" | "SUPERSEDED" | "SUSPENDED" | "RETIRED";
export type StrategyPurpose = "ACQUISITION" | "DISCOVERY" | "PRACTICE" | "EVALUATION" | "REMEDIATION" | "RETENTION";
export type StrategyContext = "FACTUAL" | "CONCEPTUAL" | "PROCEDURAL" | "REASONING" | "JUDGMENT" | "COMPLEX_SKILL";
export type StrategyParameter = Readonly<{ name: string; value: number | boolean | string; minimum?: number; maximum?: number; required: boolean }>;
export type StrategyStep = Readonly<{ ordinal: number; primitive: LearningPrimitive; adaptiveBranch?: Readonly<{ condition: "PREREQUISITE_FAILURE" | "HIGH_EXISTING_MASTERY" | "REPEATED_FAILURE"; targetOrdinal: number }> }>;
export type StrategyDefinition = Readonly<{ strategyId: string; name: string; version: number; lifecycle: StrategyLifecycleStatus; purpose: readonly StrategyPurpose[]; applicableContexts: readonly StrategyContext[]; prerequisites: readonly string[]; steps: readonly StrategyStep[]; parameters: readonly StrategyParameter[]; stopConditions: readonly ("OBJECTIVE_SATISFIED" | "MAX_ATTEMPTS" | "PREREQUISITE_FAILURE" | "DIMINISHING_RETURNS" | "TEACHER_REQUIRED" | "SCOPE_DRIFT" | "LEASE_EXPIRED")[]; parentVersionId: string | null; evidenceIds: readonly string[]; knownExceptions: readonly string[]; createdBy: ProvenanceActor; createdAt: string; learningEffect: "NONE"; authorityEffect: "UNCHANGED"; executionPermissionGranted: false }>;
export type StrategyLifecycleEvent = Readonly<{ eventId: string; strategyId: string; version: number; from: StrategyLifecycleStatus | null; to: StrategyLifecycleStatus; reason: string; actor: ProvenanceActor; occurredAt: string; immutable: true; executionPermissionGranted: false; authorityEffect: "UNCHANGED" }>;
export type StrategyRunStatus = "READY" | "RUNNING" | "PAUSED" | "HALTED" | "COMPLETED";
export type StrategyRunStopReason = "OBJECTIVE_SATISFIED" | "MAX_ATTEMPTS" | "PREREQUISITE_FAILURE" | "DIMINISHING_RETURNS" | "TEACHER_REQUIRED" | "SCOPE_DRIFT" | "LEASE_EXPIRED";
export type StrategyRun = Readonly<{ runId: string; strategyId: string; strategyVersion: number; objectiveId: string; approvedPlanId: string; lease: LearningExecutionLease; scope: string; maxAttempts: number; maxQuestions: number; timeBudgetMinutes: number; tokenBudget: number; attemptsUsed: number; questionsUsed: number; tokensUsed: number; status: StrategyRunStatus; stopReason: StrategyRunStopReason | null; startedAt: string; completedAt: string | null; adaptiveBranchHistory: readonly Readonly<{ fromOrdinal: number; toOrdinal: number; condition: "PREREQUISITE_FAILURE" | "HIGH_EXISTING_MASTERY" | "REPEATED_FAILURE"; occurredAt: string }> []; durableKnowledgeEffect: "NONE"; authorityEffect: "UNCHANGED"; executionPermissionGranted: false }>;
export type StrategyRegistryArtifact = Readonly<{ artifactId: string; artifactType: "STRATEGY" | "LIFECYCLE" | "RUN" | "HYPOTHESIS" | "EXPERIMENT" | "EVALUATION" | "GOVERNANCE_DECISION" | "SELECTION_DECISION" | "RANKING" | "RUNTIME_HEALTH" | "PORTFOLIO" | "EXPLORATION" | "OBJECTIVE_PROFILE" | "PHASE40_SELECTION" | "SELECTION_OVERRIDE" | "STRATEGY_RESELECTION" | "STRATEGY_CURRICULUM_PROPOSAL" | "STRATEGY_APPROVAL_BRIDGE" | "STRATEGY_CURRICULUM_MATERIALIZATION" | "STRATEGY_SELECTION_OUTCOME"; subjectId: string; payload: unknown; createdAt: string }>;
export interface StrategyRegistryStore { append(artifact: StrategyRegistryArtifact): Promise<StrategyRegistryArtifact>; listArtifacts(strategyId: string): Promise<readonly StrategyRegistryArtifact[]>; listWorkspaceArtifacts(): Promise<readonly StrategyRegistryArtifact[]>; }
export type StrategyBudget = Readonly<{ timeMinutes: number; tokenBudget: number; teacherAvailability: "NONE" | "LOW" | "MODERATE" | "HIGH"; risk: "LOW" | "MEDIUM" | "HIGH"; requiredRetention: "LOW" | "MEDIUM" | "HIGH" }>;
export type StrategyEligibility = Readonly<{ strategyId: string; eligible: boolean; reasons: readonly string[]; unmetPrerequisites: readonly string[]; budgetFit: boolean; governanceFit: boolean; projectionOnly: true; executionPermissionGranted: false; authorityEffect: "UNCHANGED" }>;
export type StrategyRecommendation = Readonly<{ recommendationId: string; objectiveId: string; selectedStrategyId: string | null; alternatives: readonly Readonly<{ strategyId: string; rank: number; reasons: readonly string[] }> []; eligibility: readonly StrategyEligibility[]; explanation: readonly string[]; evidenceState: "INSUFFICIENT_DATA" | "EARLY_SIGNAL" | "EMERGING_PATTERN" | "SUPPORTED_PATTERN" | "STRONG_EVIDENCE"; status: "AWAITING_APPROVAL" | "NO_ELIGIBLE_STRATEGY"; createdAt: string; recommendationOnly: true; autonomousPlanChangeAuthorized: false; executionPermissionGranted: false; authorityEffect: "UNCHANGED" }>;
export type StrategyPerformanceMeasurement = Readonly<{ runId: string; strategyId: string; context: StrategyContext; immediateGain: number | null; retention: number | null; generalization: number | null; boundaryRecognition: number | null; adversarialPerformance: number | null; correctionCount: number; humanInterventionCount: number; tokenCost: number | null; timeMinutes: number | null; valid: boolean; observedAt: string }>;
export type StrategyPerformanceProfile = Readonly<{ profileId: string; strategyId: string; context: StrategyContext; sampleSize: number; meanImmediateGain: number | null; meanRetention: number | null; meanGeneralization: number | null; meanBoundaryRecognition: number | null; meanAdversarialPerformance: number | null; meanCorrections: number | null; meanHumanInterventions: number | null; meanTokenCost: number | null; evidenceState: StrategyRecommendation["evidenceState"]; sourceRunIds: readonly string[]; interpretation: "OBSERVED_ASSOCIATION"; causalClaim: false; createdAt: string; projectionOnly: true; authorityEffect: "UNCHANGED"; executionPermissionGranted: false }>;
export type StrategyFailureKind = "LOW_RETENTION" | "LOW_TRANSFER" | "FALSE_MASTERY" | "EXCESSIVE_TEACHER_DEPENDENCY" | "EXCESSIVE_TOKEN_COST" | "DIMINISHING_RETURNS" | "PREREQUISITE_MISMATCH";
export type StrategyFailure = Readonly<{ failureId: string; runId: string; strategyId: string; kind: StrategyFailureKind; evidenceIds: readonly string[]; explanation: string; status: "REQUIRES_REVIEW"; createdAt: string; recommendationOnly: true; executionPermissionGranted: false; authorityEffect: "UNCHANGED" }>;
export type StrategyRemediationRecommendation = Readonly<{ recommendationId: string; failureId: string; recommendedPrimitive: LearningPrimitive; rationale: string; status: "PROPOSED"; requiresApprovedPlan: true; executionPermissionGranted: false; authorityEffect: "UNCHANGED"; createdAt: string }>;
export type RegistryStrategyHypothesis = Readonly<{ hypothesisId: string; strategyId: string; proposedChange: string; sourceProfileIds: readonly string[]; evidenceState: StrategyRecommendation["evidenceState"]; status: "PROPOSED"; requiresGovernedReview: true; autonomousAdoptionAuthorized: false; createdAt: string; executionPermissionGranted: false; authorityEffect: "UNCHANGED" }>;
export type StrategyExperiment = Readonly<{ experimentId: string; hypothesisId: string; controlStrategyId: string; variantStrategyId: string; metrics: readonly ("IMMEDIATE_GAIN" | "RETENTION" | "GENERALIZATION" | "ADVERSARIAL_PERFORMANCE" | "CORRECTIONS" | "HUMAN_INTERVENTIONS" | "TOKENS" | "TIME")[]; independentEvaluatorId: string; status: "PROPOSED" | "AUTHORIZED" | "RUNNING" | "COMPLETED" | "REJECTED"; approvedBy: ProvenanceActor | null; createdAt: string; executionPermissionGranted: false; authorityEffect: "UNCHANGED" }>;
export type StrategyExperimentEvaluation = Readonly<{ evaluationId: string; experimentId: string; evaluator: ProvenanceActor; result: "INCONCLUSIVE" | "SUPPORTS_VARIANT" | "DOES_NOT_SUPPORT_VARIANT"; retentionMeasured: boolean; adversarialReviewPassed: boolean; limitations: readonly string[]; completedAt: string; independent: true; authorityEffect: "UNCHANGED"; executionPermissionGranted: false }>;
export type StrategyGovernanceDecision = Readonly<{ decisionId: string; strategyId: string; version: number; decision: "APPROVE" | "DEFER" | "REJECT" | "SUSPEND" | "ROLLBACK"; evidenceIds: readonly string[]; decidedBy: ProvenanceActor; reason: string; decidedAt: string; createsExecutionPermission: false; authorityEffect: "UNCHANGED" }>;
