import type { ProvenanceActor } from "./provenance";

export type StrategyEvaluationStatus = "COMPLETE" | "PARTIAL" | "INVALID" | "INSUFFICIENT_EVIDENCE";
export type StrategyEvaluationMetric = "TRAINING_ACCURACY" | "IMMEDIATE_ACCURACY" | "NOVEL_ACCURACY" | "ADVERSARIAL_ACCURACY" | "RETENTION_ACCURACY" | "CALIBRATION_ERROR" | "ERROR_RECURRENCE_RATE" | "HUMAN_CORRECTION_RATE" | "ELAPSED_TIME_MINUTES" | "TOKEN_COST" | "TOOL_COST" | "FAILURE_RATE";
export type MetricObservation = Readonly<{ metric: StrategyEvaluationMetric; value: number | null; unit: "PERCENT" | "RATE" | "MINUTES" | "TOKENS" | "COST"; evidenceIds: readonly string[]; availability: "OBSERVED" | "MISSING" | "INVALID" | "NOT_APPLICABLE"; observedAt: string; immutable: true }>;
export type StrategyEvaluation = Readonly<{ evaluationId: string; strategyId: string; strategyVersion: number; objectiveId: string; executionId: string; contextId: string; learnerStateSnapshotId: string; difficulty: "LOW" | "MEDIUM" | "HIGH"; risk: "LOW" | "MEDIUM" | "HIGH"; prerequisiteState: "SATISFIED" | "PARTIALLY_SATISFIED" | "UNCERTAIN" | "FAILED"; startedAt: string; completedAt: string; metrics: readonly MetricObservation[]; competencyAchieved: boolean | null; failureReasons: readonly string[]; practiceEvidenceIds: readonly string[]; evaluationEvidenceIds: readonly string[]; adversarialEvidenceIds: readonly string[]; retentionEvidenceIds: readonly string[]; correctionEvidenceIds: readonly string[]; status: StrategyEvaluationStatus; createdBy: ProvenanceActor; createdAt: string; immutable: true; strategyMutationAuthorized: false; executionPermissionGranted: false; authorityEffect: "UNCHANGED" }>;
export type StrategyEvaluationArtifact = Readonly<{ artifactId: string; artifactType: "EVALUATION"; subjectId: string; payload: unknown; createdAt: string }>;
export interface StrategyEvaluationStore { append(artifact: StrategyEvaluationArtifact): Promise<StrategyEvaluationArtifact>; listArtifacts(strategyId: string): Promise<readonly StrategyEvaluationArtifact[]>; listWorkspaceArtifacts(): Promise<readonly StrategyEvaluationArtifact[]>; }
export type StrategyComparisonCohort = Readonly<{ cohortId: string; domain: string; difficulty: StrategyEvaluation["difficulty"]; risk: StrategyEvaluation["risk"]; prerequisiteState: StrategyEvaluation["prerequisiteState"]; evaluationType: "NATURAL" | "BENCHMARK"; createdAt: string; immutable: true }>;
export type StrategyEvidenceConfidence = "UNTESTED" | "EXPERIMENTAL" | "PRELIMINARY" | "SUPPORTED" | "WELL_SUPPORTED" | "CONTEXT_SPECIALIZED";
export type StrategyEvaluationProfile = Readonly<{ profileId: string; strategyId: string; cohortId: string; evaluationIds: readonly string[]; sampleSize: number; metrics: Readonly<Partial<Record<StrategyEvaluationMetric, number>>>; confidence: StrategyEvidenceConfidence; confidenceReasons: readonly string[]; interpretation: "OBSERVED_ASSOCIATION"; causalClaim: false; createdAt: string; projectionOnly: true; strategyMutationAuthorized: false; executionPermissionGranted: false; authorityEffect: "UNCHANGED" }>;
export type StrategyFailureAttribution = Readonly<{ attributionId: string; evaluationId: string; strategyId: string; classification: "LEARNING_FAILURE" | "STRATEGY_FAILURE" | "SELECTION_FAILURE" | "EVALUATION_INVALID"; reasons: readonly string[]; requiresReflection: true; requiresGovernedReview: true; createdAt: string; recommendationOnly: true; strategyMutationAuthorized: false; executionPermissionGranted: false; authorityEffect: "UNCHANGED" }>;
export type StrategyDominanceAnalysis = Readonly<{ analysisId: string; cohortId: string; entries: readonly Readonly<{ strategyId: string; dominatedByStrategyIds: readonly string[]; paretoEfficient: boolean; specialization: "GENERAL" | "DURABILITY" | "TRANSFER" | "EFFICIENCY" | "INSUFFICIENT_EVIDENCE"; reasons: readonly string[] }> []; createdAt: string; projectionOnly: true; strategyMutationAuthorized: false; executionPermissionGranted: false; authorityEffect: "UNCHANGED" }>;
