export type ConstitutionalEscalationErrorCode =
  | "ESCALATION_REPLAY_MISMATCH"
  | "ESCALATION_STATE_INVALID"
  | "ESCALATION_GOVERNANCE_MISSING"
  | "ESCALATION_OVERRIDE_MISSING"
  | "ESCALATION_CONFIDENCE_MISSING"
  | "ESCALATION_TOPOLOGY_AMBIGUOUS"
  | "ESCALATION_RECURSIVE_TOPOLOGY"
  | "ESCALATION_HIDDEN_PATH"
  | "ESCALATION_AUTHORITY_DRIFT"
  | "ESCALATION_POLICY_MISMATCH"
  | "ESCALATION_MUTABLE_LINEAGE"
  | "ESCALATION_RUNTIME_METADATA_FORBIDDEN"
  | "ESCALATION_EXECUTION_METADATA_FORBIDDEN";

export type ConstitutionalEscalationError = Readonly<{
  code: ConstitutionalEscalationErrorCode;
  message: string;
  path?: string;
}>;
