import type { AdversarialAttackPlan, AdversarialAttackProfile, AdversarialAttempt, AdversarialEvidence, AdversarialExam, AdversarialExaminationArtifactStore, AdversarialExaminationAuditType, AdversarialFindingRoute, AdversarialTest, AdversarialTestChallenge, ExaminerFinding, ExaminerRubric, FalseMasteryHypothesis, MasteryReassessmentRecommendation } from "../../types/learning-constitution/adversarialExamination";
import type { LearningAuditLedger } from "../../types/learning-constitution/learningAuditLedger";
import type { ProvenanceActor } from "../../types/learning-constitution/provenance";

const activeEvaluationLease = (exam: AdversarialExam, now: string) => exam.lease.status === "ACTIVE" && exam.lease.method === "TARGETED_EVALUATION" && Date.parse(exam.lease.expiresAt) > Date.parse(now);
const qualityFor = (rubric: ExaminerRubric, exposed: boolean, independent: boolean, priorExposure: boolean): AdversarialEvidence["evidenceQuality"] => exposed || rubric.isolation === "EXPOSED" ? "INVALID" : priorExposure || rubric.isolation === "SHARED_CONTEXT" ? "LOW" : rubric.isolation === "INDEPENDENT" && independent ? "HIGH" : "MEDIUM";

/** Skeptical examiner: challenges a competency claim but has no authority to rewrite knowledge or mastery. */
export class AdversarialExaminerService {
  constructor(private readonly artifacts: AdversarialExaminationArtifactStore) {}
  async start(exam: AdversarialExam, now: string) { if (exam.status !== "ACTIVE" || exam.testsUsed !== 0 || exam.maximumTests < 1 || !exam.skillId.trim() || !exam.competencyClaimId.trim() || exam.examinerContextHash === exam.learnerContextHash || !activeEvaluationLease(exam, now)) throw new Error("adversarial examination requires an active unexpired TARGETED_EVALUATION lease and separate examiner context"); await this.artifacts.append({ artifactId: `ADVERSARIAL_EXAM:${exam.examId}`, artifactType: "EXAM", subjectId: exam.examId, payload: exam, createdAt: exam.startedAt }); return exam; }
  async registerHypothesis(hypothesis: FalseMasteryHypothesis) { if (!hypothesis.hypothesisId.trim() || !hypothesis.skillId.trim() || !hypothesis.competencyClaimId.trim() || !hypothesis.suspectedMechanism.trim() || !hypothesis.boundary.trim() || !hypothesis.expectedFailureSignal.trim() || !hypothesis.immutable) throw new Error("adversarial tests require an explicit falsifiable false-mastery hypothesis"); await this.artifacts.append({ artifactId: `FALSE_MASTERY_HYPOTHESIS:${hypothesis.hypothesisId}`, artifactType: "HYPOTHESIS", subjectId: hypothesis.skillId, payload: hypothesis, createdAt: hypothesis.createdAt }); return hypothesis; }
  async freeze(test: AdversarialTest, rubric: ExaminerRubric, exam: AdversarialExam, now: string) { if (!activeEvaluationLease(exam, now) || test.examId !== exam.examId || test.learnerContextHash !== exam.learnerContextHash || test.examinerContextHash !== exam.examinerContextHash || test.integrity !== "VALID" || !test.immutable || rubric.testId !== test.testId || rubric.rubricId !== test.rubricId || rubric.revealedAt || !rubric.examinerOnly || !rubric.immutable || rubric.isolation === "EXPOSED") throw new Error("adversarial tests require a valid frozen learner scenario and unrevealed examiner-only rubric"); await this.artifacts.append({ artifactId: `ADVERSARIAL_TEST:${test.testId}`, artifactType: "TEST", subjectId: exam.examId, payload: test, createdAt: test.createdAt }); await this.artifacts.append({ artifactId: `ADVERSARIAL_RUBRIC:${rubric.rubricId}`, artifactType: "RUBRIC", subjectId: test.testId, payload: rubric, createdAt: test.createdAt }); return { test, rubric }; }
  async commit(attempt: AdversarialAttempt, test: AdversarialTest, rubric: ExaminerRubric) { if (attempt.testId !== test.testId || attempt.learnerContextHash !== test.learnerContextHash || !attempt.immutable) throw new Error("adversarial attempts must commit the frozen learner context"); await this.artifacts.append({ artifactId: `ADVERSARIAL_ATTEMPT:${attempt.attemptId}`, artifactType: "ATTEMPT", subjectId: test.examId, payload: attempt, createdAt: attempt.committedAt }); return { attempt, evaluationPermitted: !attempt.hiddenMaterialExposedBeforeCommit && rubric.revealedAt === null && rubric.isolation !== "EXPOSED" }; }
  async recordFinding(finding: ExaminerFinding, test: AdversarialTest, attempt: AdversarialAttempt, rubric: ExaminerRubric, skillId: string, priorExposure: boolean) { if (finding.testId !== test.testId || finding.attemptId !== attempt.attemptId || !finding.diagnosticRationale.trim() || !finding.immutable) throw new Error("examiner findings must be tied to a committed test and explained"); await this.artifacts.append({ artifactId: `EXAMINER_FINDING:${finding.findingId}`, artifactType: "FINDING", subjectId: test.examId, payload: finding, createdAt: finding.createdAt }); const evidenceQuality = qualityFor(rubric, attempt.hiddenMaterialExposedBeforeCommit, finding.evaluatorIndependent, priorExposure); const evidence: AdversarialEvidence = { evidenceId: `adversarial:${finding.findingId}`, skillId, testId: test.testId, attemptId: attempt.attemptId, findingId: finding.findingId, outcome: finding.outcome, isolation: rubric.isolation, evaluatorIndependent: finding.evaluatorIndependent, exposedBeforeCommit: attempt.hiddenMaterialExposedBeforeCommit, evidenceQuality, priorExposure, createdAt: finding.createdAt, skillRegistryEffect: "EVIDENCE_ONLY", durableKnowledgeEffect: "NONE", executionPermissionGranted: false }; await this.artifacts.append({ artifactId: `ADVERSARIAL_EVIDENCE:${evidence.evidenceId}`, artifactType: "EVIDENCE", subjectId: test.examId, payload: evidence, createdAt: evidence.createdAt }); return evidence; }
  async recommendReassessment(recommendation: MasteryReassessmentRecommendation) { if (!recommendation.recommendationId.trim() || !recommendation.skillId.trim() || !recommendation.competencyClaimId.trim() || !recommendation.basisFindingIds.length || !recommendation.requiresReview || recommendation.executionPermissionGranted || recommendation.durableKnowledgeEffect !== "NONE") throw new Error("mastery reassessment is a review recommendation backed by findings, never an automatic mastery mutation"); await this.artifacts.append({ artifactId: `MASTERY_REASSESSMENT:${recommendation.recommendationId}`, artifactType: "REASSESSMENT", subjectId: recommendation.skillId, payload: recommendation, createdAt: recommendation.createdAt }); return recommendation; }
}

/** Varies attack families and boundaries so the examiner does not merely train the learner on one recurring trap. */
export class AdversarialAttackSelector {
  select(hypotheses: readonly FalseMasteryHypothesis[], prior: readonly AdversarialAttackProfile[]): AdversarialAttackPlan | null { const candidate = hypotheses.find((hypothesis) => !prior.some((profile) => profile.boundary === hypothesis.boundary && profile.outcome !== "INCONCLUSIVE")); if (!candidate) return null; const used = new Set(prior.map((profile) => profile.attackType)); const attackType = (['MISLEADING_SCENARIO', 'INCOMPLETE_EVIDENCE', 'UNUSUAL_EDGE_CASE', 'CONFLICTING_SIGNALS', 'CHANGED_ASSUMPTION', 'NEAR_MISS', 'PLAUSIBLE_WRONG_SOLUTION', 'BOUNDARY_VIOLATION', 'EXCEPTION_PROBE', 'DISTRACTOR_INJECTION', 'CONTEXT_SHIFT', 'CONFIDENCE_TRAP'] as const).find((type) => !used.has(type)) ?? "CHANGED_ASSUMPTION"; return { hypothesisId: candidate.hypothesisId, attackType, reason: `Probe the untested false-mastery boundary: ${candidate.boundary}.`, informationGain: used.has(attackType) ? "MEDIUM" : "HIGH", selectionEffect: "RECOMMENDATION_ONLY", executionPermissionGranted: false }; }
}

export class AdversarialExaminerDiversityService {
  assess(candidate: Readonly<{ attackType: AdversarialTest["attackType"]; boundary: string; structuralFingerprint: string }>, prior: readonly AdversarialAttackProfile[]) { const repeated = prior.filter((profile) => profile.attackType === candidate.attackType && (profile.boundary === candidate.boundary || profile.structuralFingerprint === candidate.structuralFingerprint)); return { diverse: repeated.length < 2, repeatedTestIds: repeated.map((profile) => profile.testId), recommendation: repeated.length >= 2 ? "CHANGE_ATTACK_FAMILY" as const : "PROCEED" as const }; }
}

/** Test challenges are first-class and can validate or invalidate the examiner, rather than assuming the examiner is always correct. */
export class AdversarialTestChallengeService {
  constructor(private readonly artifacts: AdversarialExaminationArtifactStore) {}
  async submit(challenge: AdversarialTestChallenge) { if (!challenge.challengeId.trim() || !challenge.testId.trim() || !challenge.rationale.trim() || challenge.status !== "CHALLENGED" || !challenge.immutable) throw new Error("test challenges require a specific immutable rationale and challenged state"); await this.artifacts.append({ artifactId: `ADVERSARIAL_TEST_CHALLENGE:${challenge.challengeId}`, artifactType: "CHALLENGE", subjectId: challenge.testId, payload: challenge, createdAt: challenge.createdAt }); return challenge; }
  async resolve(challenge: AdversarialTestChallenge, status: "VALIDATED" | "INVALIDATED" | "AMBIGUOUS", resolvedAt: string, actor: import("../../types/learning-constitution/provenance").ProvenanceActor) { if (challenge.status !== "CHALLENGED") throw new Error("only submitted challenges may be resolved"); const resolution = { ...challenge, status, resolvedAt, resolvedBy: actor, immutable: true as const }; await this.artifacts.append({ artifactId: `ADVERSARIAL_TEST_CHALLENGE_RESOLUTION:${challenge.challengeId}:${status}`, artifactType: "CHALLENGE", subjectId: challenge.testId, payload: resolution, createdAt: resolvedAt }); return resolution; }
}

/** A severe finding challenges mastery for human/governed review; an isolated non-catastrophic finding is routed to Reflection first. */
export class AdversarialFindingRouter {
  route(finding: ExaminerFinding): AdversarialFindingRoute { if (finding.challengeStatus === "INVALIDATED" || finding.challengeStatus === "AMBIGUOUS") return { route: "NO_ACTION", reason: "An invalid or ambiguous test cannot support a competency conclusion.", executionPermissionGranted: false, durableKnowledgeEffect: "NONE" }; if (finding.outcome === "SYSTEMATIC_FAILURE" || finding.outcome === "CATASTROPHIC_FAILURE") return { route: "MASTERY_REASSESSMENT", reason: "A systematic or catastrophic adversarial failure requires scoped mastery reassessment.", executionPermissionGranted: false, durableKnowledgeEffect: "NONE" }; if (finding.outcome === "PARTIAL_FAILURE" || finding.outcome === "PASS_WITH_RESERVATION") return { route: "REFLECTION", reason: "A localized weakness should be diagnosed by the Reflection Engine before new practice is selected.", executionPermissionGranted: false, durableKnowledgeEffect: "NONE" }; return { route: "NO_ACTION", reason: "No remediation or reassessment route is indicated by this finding.", executionPermissionGranted: false, durableKnowledgeEffect: "NONE" }; }
}

export class AdversarialExaminationAuditService {
  constructor(private readonly ledger: LearningAuditLedger) {}
  async record(input: Readonly<{ eventId: string; eventType: AdversarialExaminationAuditType; workspaceId: string; examId: string; occurredAt: string; actor: ProvenanceActor; correlationId: string; skillId: string; testId?: string; findingId?: string; payload: Readonly<Record<string, unknown>> }>) { return this.ledger.append({ eventId: input.eventId, eventType: input.eventType, workspaceId: input.workspaceId, occurredAt: input.occurredAt, actor: input.actor, correlationId: input.correlationId, schemaVersion: "10.0", references: {}, payload: { ...input.payload, examId: input.examId, skillId: input.skillId, testId: input.testId ?? null, findingId: input.findingId ?? null, durableKnowledgeEffect: "NONE", executionPermissionGranted: false } }); }
}
