import type { CorrectedKnowledgeCandidate, CorrectionAnalysis, CorrectionDependencyImpact, CorrectionIntakeResult, CorrectionRecord, CorrectionRegressionCase, CorrectionRepairPlan, CorrectionRepository, CorrectionRetestEvidence, CorrectionRootCauseAnalysis, CorrectionSignal, SystemImprovementCandidate } from "../../types/learning-constitution/correctionLearning";
import type { LearningAuditLedger } from "../../types/learning-constitution/learningAuditLedger";
import { canonicalizeAuditValue } from "./auditIntegrityHash";

/** Append-only in-memory reference implementation. There are intentionally no repair or delete methods. */
export class InMemoryCorrectionRepository implements CorrectionRepository {
  private readonly records = new Map<string, CorrectionRecord>(); private readonly analyses = new Map<string, CorrectionAnalysis[]>(); private readonly impacts = new Map<string, CorrectionDependencyImpact[]>(); private readonly candidates = new Map<string, CorrectedKnowledgeCandidate[]>(); private readonly plans = new Map<string, CorrectionRepairPlan[]>(); private readonly regressionCases = new Map<string, CorrectionRegressionCase[]>(); private readonly retests = new Map<string, CorrectionRetestEvidence[]>(); private readonly rootCauses = new Map<string, CorrectionRootCauseAnalysis[]>(); private readonly improvements = new Map<string, SystemImprovementCandidate>();
  async append(record: CorrectionRecord): Promise<CorrectionRecord> { const existing = this.records.get(record.correctionId); if (existing && canonicalizeAuditValue(existing) !== canonicalizeAuditValue(record)) throw new Error("correction id collision"); this.records.set(record.correctionId, existing ?? record); return existing ?? record; }
  async appendAnalysis(analysis: CorrectionAnalysis): Promise<CorrectionAnalysis> { const existing = this.analyses.get(analysis.correctionId) ?? []; const replay = existing.find((item) => canonicalizeAuditValue(item) === canonicalizeAuditValue(analysis)); if (!replay) this.analyses.set(analysis.correctionId, [...existing, analysis]); return replay ?? analysis; }
  async appendImpact(impact: CorrectionDependencyImpact): Promise<CorrectionDependencyImpact> { if (!this.records.has(impact.correctionId)) throw new Error("correction must exist before recording impact"); const existing = this.impacts.get(impact.correctionId) ?? []; const replay = existing.find((item) => item.impactId === impact.impactId); if (replay && canonicalizeAuditValue(replay) !== canonicalizeAuditValue(impact)) throw new Error("correction impact id collision"); if (!replay) this.impacts.set(impact.correctionId, [...existing, impact]); return replay ?? impact; }
  async appendCandidate(candidate: CorrectedKnowledgeCandidate): Promise<CorrectedKnowledgeCandidate> { if (!this.records.has(candidate.correctionId)) throw new Error("correction must exist before extracting candidate"); const existing = this.candidates.get(candidate.correctionId) ?? []; const replay = existing.find((item) => item.candidateId === candidate.candidateId); if (replay && canonicalizeAuditValue(replay) !== canonicalizeAuditValue(candidate)) throw new Error("corrected knowledge candidate id collision"); if (!replay) this.candidates.set(candidate.correctionId, [...existing, candidate]); return replay ?? candidate; }
  async appendPlan(plan: CorrectionRepairPlan): Promise<CorrectionRepairPlan> { if (!this.records.has(plan.correctionId)) throw new Error("correction must exist before planning repair"); const existing = this.plans.get(plan.correctionId) ?? []; const replay = existing.find((item) => item.planId === plan.planId); if (replay && canonicalizeAuditValue(replay) !== canonicalizeAuditValue(plan)) throw new Error("correction repair plan id collision"); if (!replay) this.plans.set(plan.correctionId, [...existing, plan]); return replay ?? plan; }
  async appendRegressionCase(regressionCase: CorrectionRegressionCase): Promise<CorrectionRegressionCase> { if (!this.records.has(regressionCase.correctionId)) throw new Error("correction must exist before creating a regression case"); const existing = this.regressionCases.get(regressionCase.correctionId) ?? []; const replay = existing.find((item) => item.regressionCaseId === regressionCase.regressionCaseId); if (replay && canonicalizeAuditValue(replay) !== canonicalizeAuditValue(regressionCase)) throw new Error("correction regression case id collision"); if (!replay) this.regressionCases.set(regressionCase.correctionId, [...existing, regressionCase]); return replay ?? regressionCase; }
  async appendRetest(retest: CorrectionRetestEvidence): Promise<CorrectionRetestEvidence> { if (!this.records.has(retest.correctionId)) throw new Error("correction must exist before retesting"); const existing = this.retests.get(retest.correctionId) ?? []; const replay = existing.find((item) => item.retestId === retest.retestId); if (replay && canonicalizeAuditValue(replay) !== canonicalizeAuditValue(retest)) throw new Error("correction retest id collision"); if (!replay) this.retests.set(retest.correctionId, [...existing, retest]); return replay ?? retest; }
  async appendRootCause(rootCause: CorrectionRootCauseAnalysis): Promise<CorrectionRootCauseAnalysis> { if (!this.records.has(rootCause.correctionId)) throw new Error("correction must exist before identifying root cause"); const existing = this.rootCauses.get(rootCause.correctionId) ?? []; const replay = existing.find((item) => item.rootCauseId === rootCause.rootCauseId); if (replay && canonicalizeAuditValue(replay) !== canonicalizeAuditValue(rootCause)) throw new Error("correction root-cause id collision"); if (!replay) this.rootCauses.set(rootCause.correctionId, [...existing, rootCause]); return replay ?? rootCause; }
  async appendImprovementCandidate(candidate: SystemImprovementCandidate): Promise<SystemImprovementCandidate> { const existing = this.improvements.get(candidate.improvementId); if (existing && canonicalizeAuditValue(existing) !== canonicalizeAuditValue(candidate)) throw new Error("system improvement candidate id collision"); this.improvements.set(candidate.improvementId, existing ?? candidate); return existing ?? candidate; }
  async get(correctionId: string): Promise<CorrectionRecord | null> { const record = this.records.get(correctionId); if (!record) return null; return { ...record, analyses: [...(this.analyses.get(correctionId) ?? [])], impacts: [...(this.impacts.get(correctionId) ?? [])], candidates: [...(this.candidates.get(correctionId) ?? [])], plans: [...(this.plans.get(correctionId) ?? [])], regressionCases: [...(this.regressionCases.get(correctionId) ?? [])], retests: [...(this.retests.get(correctionId) ?? [])], rootCauses: [...(this.rootCauses.get(correctionId) ?? [])] }; }
  async list(): Promise<readonly CorrectionRecord[]> { return Promise.all([...this.records.keys()].map((correctionId) => this.get(correctionId).then((record) => record!))); }
}

/** Phase 12A intake boundary: detects, persists, and audits corrections, but never mutates knowledge. */
export class CorrectionIntakeService {
  constructor(private readonly repository: CorrectionRepository, private readonly audit?: LearningAuditLedger) {}
  async intake(signal: CorrectionSignal, workspaceId: string, correlationId: string): Promise<CorrectionIntakeResult> {
    const existing = await this.repository.get(signal.correctionId);
    const record: CorrectionRecord = { correctionId: signal.correctionId, signal, status: "DETECTED", analyses: [], impacts: [], candidates: [], plans: [], regressionCases: [], retests: [], rootCauses: [], immutable: true };
    const stored = await this.repository.append(record);
    const duplicate = !!existing;
    if (this.audit) await this.audit.append({ eventId: `audit:${signal.correctionId}:${duplicate ? "deduplicated" : "detected"}`, eventType: duplicate ? "CORRECTION_DEDUPLICATED" : "CORRECTION_DETECTED", workspaceId, occurredAt: signal.timestamp, actor: signal.actor, correlationId, schemaVersion: "10.0", references: { correctionIds: [signal.correctionId] }, payload: { sourceEventId: signal.sourceEventId, explicitness: signal.explicitness, confidence: signal.confidence } });
    return { record: stored, duplicate, persistenceEffect: duplicate ? "IDEMPOTENT_REPLAY" : "CREATED", authorityEffect: "UNCHANGED", executionPermissionGranted: false };
  }
}
