import type { DecisionPredictionContradiction, DecisionPredictionEvidence, DecisionPredictionOption, DecisionPredictionOptionAssessment, DecisionPredictionSelection } from "../../types/learning-constitution/decisionPrediction";
import { DecisionPredictionScoringService } from "./decisionPredictionService";

const authority: Readonly<Record<DecisionPredictionEvidence["sourceType"], number>> = { HUMAN_DECISION: 1, HUMAN_CORRECTION: 0.95, APPROVED_PRINCIPLE: 0.85, SCOPED_PREFERENCE: 0.75, APPROVED_PROCEDURE: 0.65, DECISION_PATTERN: 0.55, EXAMPLE: 0.35, EXCEPTION: 0.9 };
const contribution = (item: DecisionPredictionEvidence) => authority[item.sourceType] * item.authorityWeight * item.contextualRelevance * item.recency * item.consistency * item.scopeCompatibility;
/** Makes the comparison set explicit: evidence for and against every plausible approach remains inspectable. */
export class DecisionPredictionOptionAnalysisService {
  assess(options: readonly DecisionPredictionOption[], evidence: readonly DecisionPredictionEvidence[]): readonly DecisionPredictionOptionAssessment[] {
    return options.map((option) => { const relevant = evidence.filter((item) => item.optionId === option.optionId); const support = relevant.filter((item) => item.supports); const against = relevant.filter((item) => !item.supports); const weightedSupport = support.reduce((total, item) => total + contribution(item), 0); const weightedContradiction = against.reduce((total, item) => total + contribution(item), 0); return { optionId: option.optionId, supportingEvidenceIds: support.map((item) => item.evidenceId), contradictingEvidenceIds: against.map((item) => item.evidenceId), weightedSupport, weightedContradiction, netScore: weightedSupport - weightedContradiction, evidenceDiversity: new Set(support.map((item) => item.sourceType)).size }; }).sort((left, right) => right.netScore - left.netScore || left.optionId.localeCompare(right.optionId));
  }
}
/** A close or contradictory result asks for the smallest discriminating clarification rather than emitting a weak personalization claim. */
export class DecisionPredictionSelectionService {
  select(input: Readonly<{ question: string; options: readonly DecisionPredictionOption[]; evidence: readonly DecisionPredictionEvidence[]; contradictions: readonly DecisionPredictionContradiction[] }>): DecisionPredictionSelection {
    const assessments = new DecisionPredictionOptionAnalysisService().assess(input.options, input.evidence); const base = new DecisionPredictionScoringService().score(input.options, input.evidence); const unresolved = input.contradictions.filter((item) => item.confidenceEffect === "REDUCE"); const close = assessments.length > 1 && Math.abs(assessments[0]!.netScore - assessments[1]!.netScore) < 0.15; const confidence = Math.max(0, base.confidence - unresolved.length * 0.18); const uncertaintyFactors = [...unresolved.map((item) => `Unresolved contradictory precedent: ${item.evidenceIds.join(", ")}.`), ...(close ? ["The leading approaches remain too close to distinguish safely."] : [])]; const needsClarification = base.status !== "INSUFFICIENT_EVIDENCE" && (close || unresolved.length > 0); const status = confidence < 0.4 || base.status === "INSUFFICIENT_EVIDENCE" ? "INSUFFICIENT_EVIDENCE" : needsClarification ? "NEEDS_SOCRATIC_CLARIFICATION" : "PREDICTION_NOT_HUMAN_INSTRUCTION"; const top = assessments[0]; return { recommendedOptionId: status === "PREDICTION_NOT_HUMAN_INSTRUCTION" ? top?.optionId ?? null : null, confidence, evidenceStrength: base.evidenceStrength, status, clarificationQuestion: status === "NEEDS_SOCRATIC_CLARIFICATION" ? `What constraint would determine the choice between ${assessments.slice(0, 2).map((item) => item.optionId).join(" and ")} in this situation?` : null, uncertaintyFactors, optionAssessments: assessments };
  }
}
