import type { DecisionPrediction, DecisionPredictionAnalytics, DecisionPredictionArtifactStore, DecisionPredictionHumanValidation } from "../../types/learning-constitution/decisionPrediction";

/** Accuracy is computed only from subsequent human validations, never self-reported or inferred from later predictions. */
export class DecisionPredictionAnalyticsService {
  async analyze(input: Readonly<{ analysisId: string; artifacts: DecisionPredictionArtifactStore; analyzedAt: string }>): Promise<DecisionPredictionAnalytics> {
    const artifacts = await input.artifacts.listWorkspaceArtifacts(); const predictions = artifacts.filter((artifact) => artifact.artifactType === "PREDICTION").map((artifact) => artifact.payload as DecisionPrediction); const validations = artifacts.filter((artifact) => artifact.artifactType === "VALIDATION").map((artifact) => artifact.payload as DecisionPredictionHumanValidation); const validated = predictions.map((prediction) => ({ prediction, validation: validations.find((validation) => validation.predictionId === prediction.predictionId) })).filter((item): item is { prediction: DecisionPrediction; validation: DecisionPredictionHumanValidation } => !!item.validation); const correct = validated.filter((item) => item.validation.outcome === "CORRECT").length; const partial = validated.filter((item) => item.validation.outcome === "PARTIAL").length; const incorrect = validated.filter((item) => item.validation.outcome === "INCORRECT").length; const observed = (outcome: DecisionPredictionHumanValidation["outcome"]) => outcome === "CORRECT" ? 1 : outcome === "PARTIAL" ? 0.5 : 0; return { analysisId: input.analysisId, totalPredictions: predictions.length, validatedPredictions: validated.length, correctPredictions: correct, partialPredictions: partial, incorrectPredictions: incorrect, accuracy: validated.length ? (correct + partial * 0.5) / validated.length : null, meanConfidence: validated.length ? validated.reduce((total, item) => total + item.prediction.confidence, 0) / validated.length : null, meanAbsoluteCalibrationError: validated.length ? validated.reduce((total, item) => total + Math.abs(item.prediction.confidence - observed(item.validation.outcome)), 0) / validated.length : null, abstentionCount: predictions.filter((prediction) => prediction.status === "INSUFFICIENT_EVIDENCE").length, clarificationCount: predictions.filter((prediction) => prediction.status === "NEEDS_SOCRATIC_CLARIFICATION").length, analyzedAt: input.analyzedAt, durableKnowledgeEffect: "NONE", executionPermissionGranted: false };
  }
  async record(artifacts: DecisionPredictionArtifactStore, analysis: DecisionPredictionAnalytics): Promise<DecisionPredictionAnalytics> { await artifacts.append({ artifactId: `DECISION_PREDICTION_ANALYSIS:${analysis.analysisId}`, artifactType: "ANALYSIS", subjectId: "workspace", payload: analysis, createdAt: analysis.analyzedAt }); return analysis; }
}
