import type { LearningAuditLedger } from "../../types/learning-constitution/learningAuditLedger";
import type { DecisionPrediction, DecisionPredictionArtifactStore, DecisionPredictionEvidence, DecisionPredictionOption, DecisionPredictionStatus } from "../../types/learning-constitution/decisionPrediction";

const bound = (value: number) => Math.max(0, Math.min(1, value));
const authority: Readonly<Record<DecisionPredictionEvidence["sourceType"], number>> = { HUMAN_DECISION: 1, HUMAN_CORRECTION: 0.95, APPROVED_PRINCIPLE: 0.85, SCOPED_PREFERENCE: 0.75, APPROVED_PROCEDURE: 0.65, DECISION_PATTERN: 0.55, EXAMPLE: 0.35, EXCEPTION: 0.9 };
/** Evidence score is explainable and deliberately excludes predictions, preventing recursive self-confirmation. */
export class DecisionPredictionScoringService {
  score(options: readonly DecisionPredictionOption[], evidence: readonly DecisionPredictionEvidence[]): Readonly<{ recommendedOptionId: string | null; confidence: number; evidenceStrength: number; status: DecisionPredictionStatus }> {
    if (options.length < 2 || evidence.some((item) => !options.some((option) => option.optionId === item.optionId) || (authority as Readonly<Record<string, number>>)[item.sourceType] === undefined || [item.authorityWeight, item.contextualRelevance, item.recency, item.consistency, item.scopeCompatibility].some((value) => !Number.isFinite(value) || value < 0 || value > 1))) throw new Error("prediction evidence must target known options with bounded factors");
    const scores = options.map((option) => ({ optionId: option.optionId, score: evidence.filter((item) => item.optionId === option.optionId).reduce((sum, item) => sum + (item.supports ? 1 : -1) * authority[item.sourceType] * item.authorityWeight * item.contextualRelevance * item.recency * item.consistency * item.scopeCompatibility, 0) })).sort((a, b) => b.score - a.score); const best = scores[0]!; const runnerUp = scores[1]!; const diversity = new Set(evidence.filter((item) => item.optionId === best.optionId && item.supports).map((item) => item.sourceType)).size; const direct = evidence.some((item) => item.optionId === best.optionId && item.supports && (item.sourceType === "HUMAN_DECISION" || item.sourceType === "HUMAN_CORRECTION")); const strength = bound(Math.max(0, best.score) / 2); const confidence = bound(strength * (0.65 + Math.min(diversity, 3) * 0.1) * (direct ? 1 : 0.8)); const close = Math.abs(best.score - runnerUp.score) < 0.1;
    const status: DecisionPredictionStatus = confidence < 0.4 || !direct || diversity < 2 ? "INSUFFICIENT_EVIDENCE" : close ? "NEEDS_SOCRATIC_CLARIFICATION" : "PREDICTION_NOT_HUMAN_INSTRUCTION"; return { recommendedOptionId: status === "PREDICTION_NOT_HUMAN_INSTRUCTION" ? best.optionId : null, confidence, evidenceStrength: strength, status };
  }
}
/** Constitutional validation for immutable prediction artifacts. */
export class DecisionPredictionService {
  constructor(private readonly artifacts: DecisionPredictionArtifactStore, private readonly audit?: LearningAuditLedger) {}
  async create(prediction: DecisionPrediction, workspaceId: string, correlationId: string): Promise<DecisionPrediction> {
    const score = new DecisionPredictionScoringService().score(prediction.options, prediction.evidence); const flagsValid = prediction.authority === "AGENT_INFERENCE" && !prediction.humanInstruction && !prediction.humanApproved && !prediction.mayCreateDirective && prediction.createdBy.actorType === "AGENT";
    if (!prediction.predictionId.trim() || !prediction.question.trim() || !prediction.context.trim() || !prediction.options.every((option) => option.optionId.trim() && option.label.trim()) || !prediction.reasoningSummary.trim() || !flagsValid || prediction.confidence !== score.confidence || prediction.evidenceStrength !== score.evidenceStrength || prediction.status !== score.status || prediction.recommendedOptionId !== score.recommendedOptionId || prediction.importantDifferences.some((difference) => !difference.description.trim() || !difference.affectedEvidenceIds.length)) throw new Error("invalid decision prediction: predictions are agent inference, not human instruction");
    await this.artifacts.append({ artifactId: `DECISION_PREDICTION:${prediction.predictionId}`, artifactType: "PREDICTION", subjectId: prediction.predictionId, payload: prediction, createdAt: prediction.createdAt }); if (this.audit) await this.audit.append({ eventId: `audit:decision-prediction:${prediction.predictionId}`, eventType: "DECISION_PREDICTION_CREATED", workspaceId, occurredAt: prediction.createdAt, actor: prediction.createdBy, correlationId, schemaVersion: "10.0", references: { provenanceIds: prediction.evidence.map((item) => item.sourceId) }, payload: { predictionId: prediction.predictionId, recommendedOptionId: prediction.recommendedOptionId, confidence: prediction.confidence, status: prediction.status, authority: "AGENT_INFERENCE", humanInstruction: false, humanApproved: false, mayCreateDirective: false } }); return prediction;
  }
}
