import type { ActivePreference, PreferenceArtifactStore, PreferenceCandidate, PreferenceHumanReview, PreferenceValidator } from "../../types/learning-constitution/preferenceLearning";
import type { LearningAuditLedger } from "../../types/learning-constitution/learningAuditLedger";
/** Human activation makes a preference eligible for resolver guidance only; it remains non-executable. */
export class PreferenceHumanReviewService {
  constructor(private readonly validator: PreferenceValidator, private readonly artifacts: PreferenceArtifactStore, private readonly audit?: LearningAuditLedger) {}
  async record(review: PreferenceHumanReview, candidate: PreferenceCandidate, workspaceId: string, correlationId: string): Promise<Readonly<{ review: PreferenceHumanReview; active?: ActivePreference; persistenceEffect: "CREATED"; authorityEffect: "UNCHANGED"; executionPermissionGranted: false }>> {
    if (review.actor.actorType !== "HUMAN" || !review.actor.actorId.trim()) throw new Error("preference review requires a human actor"); if (review.preferenceId !== candidate.preferenceId || !review.note.trim()) throw new Error("preference review must identify candidate and note"); if (review.action === "ACTIVATE" && this.validator.validate(candidate).status !== "VALID") throw new Error("only a valid preference candidate can be activated");
    await this.artifacts.append({ artifactId: `PREFERENCE_REVIEW:${review.reviewId}`, artifactType: "LIFECYCLE", subjectId: candidate.preferenceId, payload: review, createdAt: review.reviewedAt }); const active = review.action === "ACTIVATE" ? { preferenceId: candidate.preferenceId, candidate, status: "ACTIVE" as const, activatedAt: review.reviewedAt } : undefined; if (active) await this.artifacts.append({ artifactId: `PREFERENCE_ACTIVATION:${review.reviewId}`, artifactType: "LIFECYCLE", subjectId: candidate.preferenceId, payload: active, createdAt: review.reviewedAt });
    if (this.audit) await this.audit.append({ eventId: `audit:preference-review:${review.reviewId}`, eventType: review.action === "ACTIVATE" ? "PREFERENCE_ACCEPTED" : "PREFERENCE_REVOKED", workspaceId, occurredAt: review.reviewedAt, actor: review.actor, correlationId, schemaVersion: "10.0", references: { provenanceIds: candidate.provenanceIds }, payload: { preferenceId: candidate.preferenceId, action: review.action, executionPermissionGranted: false } }); return { review, active, persistenceEffect: "CREATED", authorityEffect: "UNCHANGED", executionPermissionGranted: false };
  }
}
