import type { ReflectionCase, ReflectionPrerequisiteDiagnosis, ReflectionRemediationPlan, ReflectionSelectedCause } from "../../types/learning-constitution/reflectionEngine";

const interventions: Readonly<Record<ReflectionCase["failureType"], ReflectionRemediationPlan["intervention"]>> = { KNOWLEDGE_GAP: "CONCEPT_REVIEW", MISUNDERSTANDING: "CONCEPT_REVIEW", PREREQUISITE_GAP: "PREREQUISITE_PRACTICE", PRINCIPLE_SELECTION_ERROR: "PRINCIPLE_DISCRIMINATION", PRINCIPLE_APPLICATION_ERROR: "APPLICATION_PRACTICE", EXCEPTION_RECOGNITION_ERROR: "EXCEPTION_PRACTICE", BOUNDARY_RECOGNITION_ERROR: "BOUNDARY_PRACTICE", PROCEDURAL_ERROR: "PROCEDURE_STEP_PRACTICE", REASONING_ERROR: "APPLICATION_PRACTICE", GENERALIZATION_ERROR: "TRANSFER_PRACTICE", OVERGENERALIZATION: "COUNTEREXAMPLE_PRACTICE", UNDERGENERALIZATION: "TRANSFER_PRACTICE", CONTEXT_INTERPRETATION_ERROR: "DIAGNOSTIC_EXERCISE", EVIDENCE_ERROR: "DIAGNOSTIC_EXERCISE", CONFIDENCE_CALIBRATION_ERROR: "CALIBRATION_FEEDBACK", INCONSISTENCY: "CONSISTENCY_PRACTICE", EVALUATION_DESIGN_ERROR: "DIAGNOSTIC_EXERCISE", UNKNOWN: "DIAGNOSTIC_EXERCISE" };
const intervention = (failureType: ReflectionCase["failureType"]): ReflectionRemediationPlan["intervention"] => interventions[failureType];
const levels = (value: ReflectionRemediationPlan["intervention"]): ReflectionRemediationPlan["practiceTransferLevels"] => value === "EXCEPTION_PRACTICE" ? ["MODIFIED", "EDGE", "AMBIGUOUS"] : value === "BOUNDARY_PRACTICE" || value === "COUNTEREXAMPLE_PRACTICE" ? ["MODIFIED", "EDGE", "ADVERSARIAL"] : value === "TRANSFER_PRACTICE" ? ["NOVEL", "AMBIGUOUS"] : value === "DIAGNOSTIC_EXERCISE" ? ["MODIFIED"] : ["EXACT", "MODIFIED"];

/** Plans the smallest demonstrated repair; it does not reteach unrelated material or create an exercise itself. */
export class ReflectionRemediationPlanner {
  plan(input: Readonly<{ planId: string; reflection: ReflectionCase; selected: ReflectionSelectedCause; prerequisite: ReflectionPrerequisiteDiagnosis; createdAt: string }>): ReflectionRemediationPlan {
    if (input.selected.reflectionId !== input.reflection.reflectionId || input.selected.status !== "SELECTED" || input.selected.failureType !== input.reflection.failureType) throw new Error("remediation requires a selected cause matching the reflection");
    const action = intervention(input.selected.failureType); const prerequisiteTarget = action === "PREREQUISITE_PRACTICE" ? input.prerequisite.targetSkillId : null;
    if (action === "PREREQUISITE_PRACTICE" && input.prerequisite.status !== "RECOMMENDED") throw new Error("prerequisite remediation requires an evidenced graph recommendation");
    const targetKnowledgeId = ["CONCEPT_REVIEW"].includes(action) ? input.reflection.relevantKnowledgeIds[0] ?? null : null; const targetPrincipleId = ["PRINCIPLE_DISCRIMINATION", "APPLICATION_PRACTICE", "BOUNDARY_PRACTICE", "COUNTEREXAMPLE_PRACTICE"].includes(action) ? input.reflection.relevantPrincipleIds[0] ?? null : null; const targetProcedureId = action === "PROCEDURE_STEP_PRACTICE" ? input.reflection.relevantProcedureIds[0] ?? null : null; const targetExceptionId = action === "EXCEPTION_PRACTICE" ? input.reflection.relevantExceptionIds[0] ?? null : null;
    return { planId: input.planId, reflectionId: input.reflection.reflectionId, selectedCauseId: input.selected.causeId, targetSkillId: prerequisiteTarget ?? input.reflection.skillId, targetKnowledgeId, targetPrincipleId, targetProcedureId, targetExceptionId, intervention: action, objective: action === "DIAGNOSTIC_EXERCISE" ? "Distinguish competing causes before remediation." : `Repair the localized ${input.selected.failureType} without reteaching unrelated material.`, practiceTransferLevels: levels(action), successCriteria: ["Meet the targeted evaluation criterion.", "Provide an appropriate rationale.", "Report calibrated confidence."], reevaluationStrategy: action === "DIAGNOSTIC_EXERCISE" ? "TARGETED" : "ORIGINAL_EVALUATION", maximumAttempts: 3, escalationConditions: ["No improvement after the maximum attempts.", "Targeted reevaluation fails with the same cause.", "New evidence contradicts the selected cause."], status: "PROPOSED", createdBy: input.reflection.createdBy, createdAt: input.createdAt, masteryEffect: "NONE", durableKnowledgeEffect: "NONE", executionPermissionGranted: false };
  }
}
