import type { LearningAuditLedger } from "../../types/learning-constitution/learningAuditLedger";
import type { ReflectionArtifactStore, ReflectionCandidateCause, ReflectionCase, ReflectionEvidenceRef, ReflectionLifecycleEvent, ReflectionRemediationPlan, ReflectionSelectedCause, ReflectionStatus } from "../../types/learning-constitution/reflectionEngine";

const transitions: Readonly<Record<ReflectionStatus | "NONE", readonly ReflectionStatus[]>> = { NONE: ["OPEN"], OPEN: ["DIAGNOSING", "INSUFFICIENT_EVIDENCE", "HUMAN_REVIEW_REQUIRED"], DIAGNOSING: ["CAUSE_IDENTIFIED", "INSUFFICIENT_EVIDENCE", "HUMAN_REVIEW_REQUIRED"], CAUSE_IDENTIFIED: ["REMEDIATION_PLANNED", "HUMAN_REVIEW_REQUIRED"], REMEDIATION_PLANNED: ["REMEDIATION_ACTIVE", "ESCALATED"], REMEDIATION_ACTIVE: ["REEVALUATION_PENDING", "ESCALATED"], REEVALUATION_PENDING: ["RESOLVED", "DIAGNOSING", "ESCALATED"], RESOLVED: [], ESCALATED: [], INSUFFICIENT_EVIDENCE: ["DIAGNOSING", "HUMAN_REVIEW_REQUIRED", "ESCALATED"], HUMAN_REVIEW_REQUIRED: ["DIAGNOSING", "ESCALATED", "SUPERSEDED"], SUPERSEDED: [] };

/** Immutable evidence-backed reflection record. It cannot modify knowledge, principles, procedures, or mastery. */
export class ReflectionArtifactService {
  constructor(private readonly artifacts: ReflectionArtifactStore, private readonly audit?: LearningAuditLedger) {}
  async createCase(caseRecord: ReflectionCase, workspaceId: string, correlationId: string): Promise<ReflectionCase> {
    if (!caseRecord.reflectionId.trim() || !caseRecord.evaluationId.trim() || !caseRecord.skillId.trim() || !caseRecord.expectedOutcome.trim() || !caseRecord.observedOutcome.trim() || caseRecord.status !== "OPEN") throw new Error("reflection case requires an open evaluation failure with identity and outcomes");
    await this.artifacts.append({ artifactId: `REFLECTION_CASE:${caseRecord.reflectionId}`, artifactType: "CASE", subjectId: caseRecord.skillId, payload: caseRecord, createdAt: caseRecord.createdAt }); await this.transition(caseRecord.reflectionId, null, "OPEN", caseRecord.createdBy, caseRecord.createdAt, "Reflection case created.", workspaceId, correlationId); if (this.audit) await this.audit.append({ eventId: `audit:reflection-case:${caseRecord.reflectionId}`, eventType: "REFLECTION_CASE_CREATED", workspaceId, occurredAt: caseRecord.createdAt, actor: caseRecord.createdBy, correlationId, schemaVersion: "10.0", references: {}, payload: { reflectionId: caseRecord.reflectionId, evaluationId: caseRecord.evaluationId, skillId: caseRecord.skillId, failureType: caseRecord.failureType, durableKnowledgeEffect: "NONE", executionPermissionGranted: false } }); return caseRecord;
  }
  async recordEvidence(reflectionId: string, evidence: readonly ReflectionEvidenceRef[]): Promise<readonly ReflectionEvidenceRef[]> { if (evidence.some((item) => !item.evidenceId.trim() || !item.sourceId.trim() || !item.note.trim())) throw new Error("reflection evidence requires identity, source, and note"); for (const item of evidence) await this.artifacts.append({ artifactId: `REFLECTION_EVIDENCE:${reflectionId}:${item.evidenceId}`, artifactType: "EVIDENCE", subjectId: reflectionId, payload: item, createdAt: new Date().toISOString() }); return evidence; }
  async addCandidateCause(cause: ReflectionCandidateCause): Promise<ReflectionCandidateCause> { if (!cause.causeId.trim() || !cause.reflectionId.trim() || !cause.rationale.trim() || !Number.isFinite(cause.confidence) || cause.confidence < 0 || cause.confidence > 1 || (!cause.supportingEvidenceIds.length && cause.failureType !== "UNKNOWN")) throw new Error("reflection cause requires bounded confidence and supporting evidence, or explicit UNKNOWN"); await this.artifacts.append({ artifactId: `REFLECTION_CANDIDATE_CAUSE:${cause.causeId}`, artifactType: "CANDIDATE_CAUSE", subjectId: cause.reflectionId, payload: cause, createdAt: cause.createdAt }); return cause; }
  async selectCause(selected: ReflectionSelectedCause, workspaceId: string, correlationId: string): Promise<ReflectionSelectedCause> { const artifacts = await this.artifacts.listArtifacts(selected.reflectionId); const candidate = selected.causeId ? artifacts.find((artifact) => artifact.artifactType === "CANDIDATE_CAUSE" && (artifact.payload as ReflectionCandidateCause).causeId === selected.causeId)?.payload as ReflectionCandidateCause | undefined : undefined; if (!selected.selectionReason.trim() || !Number.isFinite(selected.confidence) || selected.confidence < 0 || selected.confidence > 1 || (selected.status === "SELECTED" && (!candidate || candidate.failureType !== selected.failureType)) || (selected.status === "UNKNOWN" && selected.causeId !== null)) throw new Error("reflection selection must reference a matching candidate or explicitly select UNKNOWN"); await this.artifacts.append({ artifactId: `REFLECTION_SELECTED_CAUSE:${selected.reflectionId}`, artifactType: "SELECTED_CAUSE", subjectId: selected.reflectionId, payload: selected, createdAt: selected.selectedAt }); if (this.audit) await this.audit.append({ eventId: `audit:reflection-cause:${selected.reflectionId}`, eventType: "REFLECTION_CAUSE_IDENTIFIED", workspaceId, occurredAt: selected.selectedAt, actor: selected.selectedBy, correlationId, schemaVersion: "10.0", references: {}, payload: { reflectionId: selected.reflectionId, causeId: selected.causeId, failureType: selected.failureType, confidence: selected.confidence, status: selected.status, durableKnowledgeEffect: "NONE", executionPermissionGranted: false } }); return selected; }
  async recordRemediationPlan(plan: ReflectionRemediationPlan, workspaceId: string, correlationId: string): Promise<ReflectionRemediationPlan> { if (!plan.planId.trim() || !plan.reflectionId.trim() || !plan.objective.trim() || !plan.practiceTransferLevels.length || plan.maximumAttempts < 1) throw new Error("invalid reflection remediation plan"); await this.artifacts.append({ artifactId: `REFLECTION_REMEDIATION_PLAN:${plan.planId}`, artifactType: "REMEDIATION_PLAN", subjectId: plan.reflectionId, payload: plan, createdAt: plan.createdAt }); if (this.audit) await this.audit.append({ eventId: `audit:reflection-remediation:${plan.planId}`, eventType: "REFLECTION_REMEDIATION_PLANNED", workspaceId, occurredAt: plan.createdAt, actor: plan.createdBy, correlationId, schemaVersion: "10.0", references: {}, payload: { planId: plan.planId, reflectionId: plan.reflectionId, intervention: plan.intervention, targetSkillId: plan.targetSkillId, durableKnowledgeEffect: "NONE", executionPermissionGranted: false } }); return plan; }
  async transition(reflectionId: string, previousStatus: ReflectionStatus | null, nextStatus: ReflectionStatus, actor: ReflectionCase["createdBy"], occurredAt: string, reason: string, workspaceId: string, correlationId: string): Promise<ReflectionLifecycleEvent> { if (!transitions[previousStatus ?? "NONE"].includes(nextStatus) || !reason.trim()) throw new Error(`invalid reflection lifecycle transition: ${previousStatus ?? "NONE"} -> ${nextStatus}`); const event: ReflectionLifecycleEvent = { reflectionId, previousStatus, nextStatus, actor, occurredAt, reason }; await this.artifacts.append({ artifactId: `REFLECTION_LIFECYCLE:${reflectionId}:${nextStatus}`, artifactType: "LIFECYCLE", subjectId: reflectionId, payload: event, createdAt: occurredAt }); return event; }
}
