import type { ReflectionArtifactStore, ReflectionCase, ReflectionFailureProfile, ReflectionSelectedCause } from "../../types/learning-constitution/reflectionEngine";

/** Aggregates retained reflection facts into an inspectable weakness profile; counts never alter mastery by themselves. */
export class ReflectionHistoryAnalyticsService {
  constructor(private readonly artifacts: ReflectionArtifactStore) {}
  async profile(input: Readonly<{ profileId: string; skillId: string; analyzedAt: string; recurrenceThreshold?: number }>): Promise<ReflectionFailureProfile> {
    const records = await this.artifacts.listWorkspaceArtifacts(); const cases = records.filter((artifact) => artifact.artifactType === "CASE" && artifact.subjectId === input.skillId).map((artifact) => artifact.payload as ReflectionCase); const ids = new Set(cases.map((item) => item.reflectionId)); const selections = records.filter((artifact) => artifact.artifactType === "SELECTED_CAUSE" && ids.has((artifact.payload as ReflectionSelectedCause).reflectionId)).map((artifact) => artifact.payload as ReflectionSelectedCause); const selectedCauseCounts: Partial<Record<ReflectionCase["failureType"], number>> = {}; for (const selection of selections) if (selection.status === "SELECTED") selectedCauseCounts[selection.failureType] = (selectedCauseCounts[selection.failureType] ?? 0) + 1; const escalatedCases = records.filter((artifact) => artifact.artifactType === "ESCALATION" && ids.has((artifact.payload as { reflectionId: string }).reflectionId)).length; const threshold = input.recurrenceThreshold ?? 3; const recurringFailureTypes = Object.entries(selectedCauseCounts).filter(([, count]) => count >= threshold).map(([type]) => type as ReflectionCase["failureType"]);
    return { profileId: input.profileId, skillId: input.skillId, totalCases: cases.length, selectedCauseCounts, unresolvedCases: cases.filter((item) => !["RESOLVED", "SUPERSEDED"].includes(item.status)).length, escalatedCases, recurringFailureTypes, analyzedAt: input.analyzedAt, masteryEffect: "NONE", durableKnowledgeEffect: "NONE", executionPermissionGranted: false };
  }
  async record(profile: ReflectionFailureProfile): Promise<ReflectionFailureProfile> { await this.artifacts.append({ artifactId: `REFLECTION_ANALYSIS:${profile.profileId}`, artifactType: "ANALYSIS", subjectId: profile.skillId, payload: profile, createdAt: profile.analyzedAt }); return profile; }
}
