import type { LearningObjectiveProfile, SelectionOutcome, StrategyOverride, StrategySelectionRecord } from "../../types/learning-constitution/strategySelectionEngine";
import type { StrategyEvaluation } from "../../types/learning-constitution/strategyEvaluation";
const observations = (evaluation: StrategyEvaluation, names: readonly string[]) => evaluation.metrics.filter((metric) => names.includes(metric.metric));
const evidenceIds = (items: readonly StrategyEvaluation["metrics"][number][]) => items.flatMap((item) => item.evidenceIds);
/** Builds the Phase 40 feedback fact from a provenance-backed Phase 39 evaluation; it does not change policy or strategy. */
export class SelectionOutcomeService {
  record(input: Readonly<{ outcomeId: string; selection: StrategySelectionRecord; override?: StrategyOverride | null; objective: LearningObjectiveProfile; curriculumId: string; evaluation: StrategyEvaluation; createdAt: string }>): SelectionOutcome {
    const override = input.override ?? null; const effectiveStrategyId = override?.selectedStrategyId ?? input.selection.selectedStrategyId;
    if (input.selection.status !== "RECOMMENDED" || !effectiveStrategyId || input.evaluation.strategyId !== effectiveStrategyId || input.evaluation.objectiveId !== input.objective.objectiveId || (override && (override.selectionId !== input.selection.selectionId || !override.requiresApprovedPlan))) throw new Error("Outcome evaluation must match the selected strategy, override, and objective.");
    const immediate = observations(input.evaluation, ["TRAINING_ACCURACY", "IMMEDIATE_ACCURACY"]); const novel = observations(input.evaluation, ["NOVEL_ACCURACY", "ADVERSARIAL_ACCURACY"]); const retention = observations(input.evaluation, ["RETENTION_ACCURACY"]); const calibration = observations(input.evaluation, ["CALIBRATION_ERROR"]); const metrics = [...immediate, ...novel, ...retention, ...calibration, ...observations(input.evaluation, ["ELAPSED_TIME_MINUTES", "TOKEN_COST", "TOOL_COST", "FAILURE_RATE"])]; const invalid = metrics.filter((metric) => metric.availability === "INVALID").flatMap((metric) => metric.evidenceIds); const observed = (items: readonly StrategyEvaluation["metrics"][number][]) => items.some((metric) => metric.availability === "OBSERVED" && metric.evidenceIds.length);
    const complete = input.evaluation.status === "COMPLETE" && observed(immediate) && (input.objective.transferRequirement !== "HIGH" || observed(novel)) && (input.objective.retentionRequirement !== "HIGH" || observed(retention)) && (input.objective.risk === "LOW" || observed(calibration));
    return { outcomeId: input.outcomeId, selectionId: input.selection.selectionId, strategyId: effectiveStrategyId, overrideId: override?.overrideId ?? null, curriculumId: input.curriculumId, evaluationId: input.evaluation.evaluationId, executionId: input.evaluation.executionId, metrics, immediateEvidenceIds: evidenceIds(immediate), novelApplicationEvidenceIds: evidenceIds(novel), retentionEvidenceIds: evidenceIds(retention), calibrationEvidenceIds: evidenceIds(calibration), invalidEvidenceIds: invalid, status: input.evaluation.status === "INVALID" || invalid.length ? "INVALID" : complete ? "COMPLETE" : "PARTIAL", createdAt: input.createdAt, immutable: true, recommendationOnly: true, executionPermissionGranted: false, authorityEffect: "UNCHANGED" };
  }
}
