import type { LearningAuditLedger } from "../../types/learning-constitution/learningAuditLedger";
import type { LearningBaseline, LearningExecutionLease, LearningOpportunity, LearningOutcome, LearningProposal, LearningProposalApproval, SelfDirectedLearningArtifactStore } from "../../types/learning-constitution/selfDirectedLearning";
/** Proposals are analytical facts. Only a human approval issues an execution lease. */
export class SelfDirectedLearningPlannerService {
  constructor(private readonly artifacts: SelfDirectedLearningArtifactStore, private readonly audit?: LearningAuditLedger) {}
  async create(opportunity: LearningOpportunity, proposal: LearningProposal, workspaceId: string, correlationId: string): Promise<LearningProposal> { if (proposal.opportunityId !== opportunity.opportunityId || proposal.status !== "AWAITING_HUMAN_APPROVAL" || !proposal.approvalRequired || !proposal.objective.trim() || !proposal.scope.trim() || !proposal.sourceGapIds.length || !proposal.evidenceIds.length || proposal.teacherEffortBudget.maximumQuestions < proposal.teacherEffortBudget.estimatedQuestions || proposal.teacherEffortBudget.estimatedQuestions < 1) throw new Error("invalid governed learning proposal"); await this.artifacts.append({ artifactId: `LEARNING_OPPORTUNITY:${opportunity.opportunityId}`, artifactType: "OPPORTUNITY", subjectId: opportunity.sourceGapId, payload: opportunity, createdAt: opportunity.createdAt }); await this.artifacts.append({ artifactId: `LEARNING_PROPOSAL:${proposal.proposalId}`, artifactType: "PROPOSAL", subjectId: proposal.proposalId, payload: proposal, createdAt: proposal.createdAt }); if (this.audit) await this.audit.append({ eventId: `audit:learning-proposal:${proposal.proposalId}`, eventType: "LEARNING_PROPOSAL_CREATED", workspaceId, occurredAt: proposal.createdAt, actor: proposal.createdBy, correlationId, schemaVersion: "10.0", references: { provenanceIds: proposal.evidenceIds }, payload: { proposalId: proposal.proposalId, sourceGapIds: proposal.sourceGapIds, method: proposal.method, approvalRequired: true, executionPermissionGranted: false } }); return proposal; }
  async approve(input: Readonly<{ proposal: LearningProposal; approval: LearningProposalApproval; lease: LearningExecutionLease | null; workspaceId: string; correlationId: string }>): Promise<LearningExecutionLease | null> { const { proposal, approval, lease } = input; if (approval.proposalId !== proposal.proposalId || approval.decidedBy.actorType !== "HUMAN" || (approval.decision === "APPROVE" && (!lease || lease.approvalId !== approval.approvalId || lease.proposalId !== proposal.proposalId || lease.scope !== approval.approvedScope || lease.method !== approval.approvedMethod || lease.maximumQuestions !== approval.approvedBudget.maximumQuestions || lease.status !== "ACTIVE")) || (approval.decision !== "APPROVE" && lease !== null)) throw new Error("only explicit human approval may issue a matching learning execution lease"); await this.artifacts.append({ artifactId: `LEARNING_PROPOSAL_APPROVAL:${approval.approvalId}`, artifactType: "APPROVAL", subjectId: proposal.proposalId, payload: approval, createdAt: approval.decidedAt }); if (lease) await this.artifacts.append({ artifactId: `LEARNING_EXECUTION_LEASE:${lease.leaseId}`, artifactType: "LEASE", subjectId: proposal.proposalId, payload: lease, createdAt: lease.issuedAt }); if (this.audit) await this.audit.append({ eventId: `audit:learning-proposal-decision:${approval.approvalId}`, eventType: approval.decision === "APPROVE" ? "LEARNING_PROPOSAL_APPROVED" : approval.decision === "DEFER" ? "LEARNING_PROPOSAL_DEFERRED" : approval.decision === "MODIFY" ? "LEARNING_PROPOSAL_MODIFIED" : "LEARNING_PROPOSAL_REJECTED", workspaceId: input.workspaceId, occurredAt: approval.decidedAt, actor: approval.decidedBy, correlationId: input.correlationId, schemaVersion: "10.0", references: {}, payload: { proposalId: proposal.proposalId, decision: approval.decision, leaseId: lease?.leaseId ?? null } }); return lease; }
  canExecute(lease: LearningExecutionLease | null, now: string, method: LearningProposal["method"], scope: string): boolean { return !!lease && lease.status === "ACTIVE" && Date.parse(lease.expiresAt) > Date.parse(now) && lease.method === method && lease.scope === scope; }
}
/** Teaching is not success: outcomes compare retained baseline and independent post-learning evidence without resolving the gap. */
export class LearningEffectivenessService {
  constructor(private readonly artifacts: SelfDirectedLearningArtifactStore, private readonly audit?: LearningAuditLedger) {}
  async recordBaseline(baseline: LearningBaseline): Promise<LearningBaseline> { if (!baseline.baselineId.trim() || !baseline.proposalId.trim() || !baseline.gapId.trim() || !baseline.evidenceIds.length) throw new Error("learning baseline requires proposal, gap, and evidence"); await this.artifacts.append({ artifactId: `LEARNING_BASELINE:${baseline.baselineId}`, artifactType: "BASELINE", subjectId: baseline.proposalId, payload: baseline, createdAt: baseline.recordedAt }); return baseline; }
  async evaluate(input: Readonly<{ baseline: LearningBaseline; outcomeId: string; predictionAccuracyAfter: number | null; competenceAfter: number | null; evaluationEvidenceIds: readonly string[]; createdBy: LearningOutcome["createdBy"]; createdAt: string; workspaceId: string; correlationId: string }>): Promise<LearningOutcome> { const bounded = (value: number | null) => value === null || (Number.isFinite(value) && value >= 0 && value <= 1); if (!bounded(input.predictionAccuracyAfter) || !bounded(input.competenceAfter) || !input.evaluationEvidenceIds.length) throw new Error("post-learning evaluation requires bounded independent measurements and evidence"); const deltas = [input.predictionAccuracyAfter === null || input.baseline.predictionAccuracy === null ? null : input.predictionAccuracyAfter - input.baseline.predictionAccuracy, input.competenceAfter === null || input.baseline.competenceScore === null ? null : input.competenceAfter - input.baseline.competenceScore].filter((value): value is number => value !== null); const result = !deltas.length ? "INCONCLUSIVE" : Math.max(...deltas) >= 0.2 ? "IMPROVED" : Math.max(...deltas) > 0 ? "PARTIALLY_IMPROVED" : Math.min(...deltas) < 0 ? "REGRESSED" : "NO_MEASURABLE_CHANGE"; const outcome: LearningOutcome = { outcomeId: input.outcomeId, proposalId: input.baseline.proposalId, gapId: input.baseline.gapId, result, predictionAccuracyBefore: input.baseline.predictionAccuracy, predictionAccuracyAfter: input.predictionAccuracyAfter, competenceBefore: input.baseline.competenceScore, competenceAfter: input.competenceAfter, evaluationEvidenceIds: input.evaluationEvidenceIds, gapResolutionAuthorized: false, createdAt: input.createdAt, createdBy: input.createdBy, immutable: true }; await this.artifacts.append({ artifactId: `LEARNING_OUTCOME:${outcome.outcomeId}`, artifactType: "OUTCOME", subjectId: outcome.proposalId, payload: outcome, createdAt: outcome.createdAt }); if (this.audit) await this.audit.append({ eventId: `audit:learning-outcome:${outcome.outcomeId}`, eventType: result === "IMPROVED" || result === "PARTIALLY_IMPROVED" ? "LEARNING_IMPROVEMENT_DETECTED" : "LEARNING_NO_IMPROVEMENT", workspaceId: input.workspaceId, occurredAt: outcome.createdAt, actor: outcome.createdBy, correlationId: input.correlationId, schemaVersion: "10.0", references: { provenanceIds: outcome.evaluationEvidenceIds }, payload: { proposalId: outcome.proposalId, gapId: outcome.gapId, result, gapResolutionAuthorized: false } }); return outcome; }
}
