import type { LearningAuditLedger } from "../../types/learning-constitution/learningAuditLedger";
import type { Curriculum } from "../../types/learning-constitution/curriculumPlanner";
import type { ProvenanceActor } from "../../types/learning-constitution/provenance";
import type { StrategyRegistryStore } from "../../types/learning-constitution/strategyRegistry";
import type { LearningObjectiveProfile, SelectionOutcome, StrategyApprovalBridge, StrategyCurriculumMaterialization, StrategyCurriculumProposal, StrategyOverride, StrategyReselection, StrategySelectionRecord } from "../../types/learning-constitution/strategySelectionEngine";

/** Persists immutable Phase 40 decisions. These records are explanatory evidence, never execution authority. */
export class StrategySelectionRecordService {
  constructor(private readonly artifacts: StrategyRegistryStore, private readonly audit?: LearningAuditLedger) {}
  async profile(item: LearningObjectiveProfile, workspaceId: string, actor: ProvenanceActor, correlationId: string) { await this.persist(`OBJECTIVE_PROFILE:${item.profileId}`, "OBJECTIVE_PROFILE", item.objectiveId, item, item.createdAt, "LEARNING_OBJECTIVE_DEFINED", workspaceId, actor, correlationId); return item; }
  async selection(item: StrategySelectionRecord, workspaceId: string, actor: ProvenanceActor, correlationId: string) { await this.persist(`PHASE40_SELECTION:${item.selectionId}`, "PHASE40_SELECTION", item.objectiveProfileId, item, item.createdAt, "STRATEGY_RECOMMENDED", workspaceId, actor, correlationId); return item; }
  async override(item: StrategyOverride, workspaceId: string, correlationId: string) { await this.persist(`SELECTION_OVERRIDE:${item.overrideId}`, "SELECTION_OVERRIDE", item.selectionId, item, item.createdAt, "OPTIMIZATION_DECISION_RECORDED", workspaceId, item.actor, correlationId); return item; }
  async reselection(item: StrategyReselection, workspaceId: string, actor: ProvenanceActor, correlationId: string) { await this.persist(`STRATEGY_RESELECTION:${item.reselectionId}`, "STRATEGY_RESELECTION", item.priorSelectionId, item, item.createdAt, "STRATEGY_SWITCH_RECOMMENDED", workspaceId, actor, correlationId); return item; }
  async curriculumProposal(item: StrategyCurriculumProposal, workspaceId: string, actor: ProvenanceActor, correlationId: string) { await this.persist(`STRATEGY_CURRICULUM_PROPOSAL:${item.proposalId}`, "STRATEGY_CURRICULUM_PROPOSAL", item.selectionId, item, item.createdAt, "LEARNING_PROPOSAL_CREATED", workspaceId, actor, correlationId); return item; }
  async approvalBridge(item: StrategyApprovalBridge, workspaceId: string, correlationId: string) { await this.persist(`STRATEGY_APPROVAL_BRIDGE:${item.bridgeId}`, "STRATEGY_APPROVAL_BRIDGE", item.curriculumProposalId, item, item.approvedAt, "LEARNING_PROPOSAL_APPROVED", workspaceId, item.approvedBy, correlationId); return item; }
  async materialization(item: StrategyCurriculumMaterialization, curriculum: Curriculum, workspaceId: string, actor: ProvenanceActor, correlationId: string) { if (curriculum.curriculumId !== item.curriculumId || curriculum.executionAuthorized) throw new Error("Only the matching non-executing curriculum may be materialized."); await this.persist(`STRATEGY_CURRICULUM_MATERIALIZATION:${item.materializationId}`, "STRATEGY_CURRICULUM_MATERIALIZATION", item.bridgeId, { materialization: item, curriculum }, item.createdAt, "LEARNING_PROPOSAL_CREATED", workspaceId, actor, correlationId); return item; }
  async outcome(item: SelectionOutcome, workspaceId: string, actor: ProvenanceActor, correlationId: string) { await this.persist(`STRATEGY_SELECTION_OUTCOME:${item.outcomeId}`, "STRATEGY_SELECTION_OUTCOME", item.selectionId, item, item.createdAt, "STRATEGY_PERFORMANCE_UPDATED", workspaceId, actor, correlationId); return item; }
  private async persist(artifactId: string, artifactType: "OBJECTIVE_PROFILE" | "PHASE40_SELECTION" | "SELECTION_OVERRIDE" | "STRATEGY_RESELECTION" | "STRATEGY_CURRICULUM_PROPOSAL" | "STRATEGY_APPROVAL_BRIDGE" | "STRATEGY_CURRICULUM_MATERIALIZATION" | "STRATEGY_SELECTION_OUTCOME", subjectId: string, payload: unknown, occurredAt: string, eventType: "LEARNING_OBJECTIVE_DEFINED" | "STRATEGY_RECOMMENDED" | "OPTIMIZATION_DECISION_RECORDED" | "STRATEGY_SWITCH_RECOMMENDED" | "LEARNING_PROPOSAL_CREATED" | "LEARNING_PROPOSAL_APPROVED" | "STRATEGY_PERFORMANCE_UPDATED", workspaceId: string, actor: ProvenanceActor, correlationId: string) { await this.artifacts.append({ artifactId, artifactType, subjectId, payload, createdAt: occurredAt }); await this.audit?.append({ eventId: `audit:${artifactId}`, eventType, workspaceId, occurredAt, actor, correlationId, schemaVersion: "10.0", references: {}, payload: { artifactId, subjectId, recommendationOnly: true, executionPermissionGranted: false, authorityEffect: "UNCHANGED" } }); }
}
