import type { StrategyFailure, StrategyPerformanceMeasurement, StrategyPerformanceProfile, StrategyRemediationRecommendation } from "../../types/learning-constitution/strategyRegistry";
const mean = (values: readonly (number | null)[]) => { const observed = values.filter((value): value is number => value !== null); return observed.length ? observed.reduce((total, value) => total + value, 0) / observed.length : null; };
const evidence = (size: number): StrategyPerformanceProfile["evidenceState"] => size < 3 ? "INSUFFICIENT_DATA" : size < 6 ? "EARLY_SIGNAL" : size < 12 ? "EMERGING_PATTERN" : size < 24 ? "SUPPORTED_PATTERN" : "STRONG_EVIDENCE";
/** Aggregates observations and identifies reviewable failure signals. It never changes a strategy, plan, or lease. */
export class StrategyPerformanceService {
  profile(input: Readonly<{ profileId: string; strategyId: string; context: StrategyPerformanceProfile["context"]; measurements: readonly StrategyPerformanceMeasurement[]; createdAt: string }>): StrategyPerformanceProfile { const rows = input.measurements.filter((row) => row.strategyId === input.strategyId && row.context === input.context && row.valid); return { profileId: input.profileId, strategyId: input.strategyId, context: input.context, sampleSize: rows.length, meanImmediateGain: mean(rows.map((row) => row.immediateGain)), meanRetention: mean(rows.map((row) => row.retention)), meanGeneralization: mean(rows.map((row) => row.generalization)), meanBoundaryRecognition: mean(rows.map((row) => row.boundaryRecognition)), meanAdversarialPerformance: mean(rows.map((row) => row.adversarialPerformance)), meanCorrections: mean(rows.map((row) => row.correctionCount)), meanHumanInterventions: mean(rows.map((row) => row.humanInterventionCount)), meanTokenCost: mean(rows.map((row) => row.tokenCost)), evidenceState: evidence(rows.length), sourceRunIds: rows.map((row) => row.runId), interpretation: "OBSERVED_ASSOCIATION", causalClaim: false, createdAt: input.createdAt, projectionOnly: true, authorityEffect: "UNCHANGED", executionPermissionGranted: false }; }
  detect(input: Readonly<{ failureId: string; measurement: StrategyPerformanceMeasurement; evidenceIds: readonly string[]; createdAt: string }>): StrategyFailure | null { const row = input.measurement; const kind = row.retention !== null && row.immediateGain !== null && row.immediateGain >= 20 && row.retention < 50 ? "FALSE_MASTERY" : row.generalization !== null && row.generalization < 50 ? "LOW_TRANSFER" : row.retention !== null && row.retention < 50 ? "LOW_RETENTION" : row.humanInterventionCount >= 4 ? "EXCESSIVE_TEACHER_DEPENDENCY" : row.tokenCost !== null && row.tokenCost > 30000 ? "EXCESSIVE_TOKEN_COST" : null; if (!kind) return null; return { failureId: input.failureId, runId: row.runId, strategyId: row.strategyId, kind, evidenceIds: input.evidenceIds, explanation: `${kind} is an observed strategy-run signal that requires review.`, status: "REQUIRES_REVIEW", createdAt: input.createdAt, recommendationOnly: true, executionPermissionGranted: false, authorityEffect: "UNCHANGED" }; }
  remediate(input: Readonly<{ recommendationId: string; failure: StrategyFailure; createdAt: string }>): StrategyRemediationRecommendation { const primitive = input.failure.kind === "LOW_RETENTION" ? "RECALL" : input.failure.kind === "LOW_TRANSFER" ? "NOVEL_PRACTICE" : input.failure.kind === "FALSE_MASTERY" ? "ADVERSARIAL_TEST" : input.failure.kind === "PREREQUISITE_MISMATCH" ? "PREREQUISITE_CHECK" : "REFLECTION"; return { recommendationId: input.recommendationId, failureId: input.failure.failureId, recommendedPrimitive: primitive, rationale: `Address ${input.failure.kind} through a governed remediation plan.`, status: "PROPOSED", requiresApprovedPlan: true, executionPermissionGranted: false, authorityEffect: "UNCHANGED", createdAt: input.createdAt }; }
}
