import type { StrategyAdaptationRecommendation, StrategyRuntimeHealth, StrategySwitchRecommendation } from "../../types/learning-constitution/strategySelection";
import type { StrategyDefinition, StrategyRun } from "../../types/learning-constitution/strategyRegistry";

/** Detects runtime signals and proposes only bounded, already-governed adaptations or switches. */
export class StrategyRuntimeOptimizationService {
  health(input: Readonly<{ healthId: string; run: StrategyRun; recentGains: readonly number[]; consecutiveFailures: number; prerequisiteBlocked: boolean; observedAt: string }>): StrategyRuntimeHealth { const diminishingReturns = input.recentGains.length >= 3 && input.recentGains.slice(-3).every((gain) => gain <= 1); const state = input.prerequisiteBlocked || input.run.status === "HALTED" ? "BLOCKED" : input.consecutiveFailures >= 3 ? "FAILING" : input.consecutiveFailures >= 2 || diminishingReturns ? "DEGRADED" : input.recentGains.length >= 2 && input.recentGains.at(-1)! < input.recentGains.at(-2)! ? "WATCH" : "HEALTHY"; const reasons = [input.prerequisiteBlocked ? "PREREQUISITE_BLOCKED" : null, diminishingReturns ? "DIMINISHING_RETURNS" : null, input.consecutiveFailures ? `CONSECUTIVE_FAILURES:${input.consecutiveFailures}` : null, input.run.status === "HALTED" ? "RUN_HALTED" : null].filter((reason): reason is string => reason !== null); return { healthId: input.healthId, runId: input.run.runId, state, recentGains: input.recentGains, consecutiveFailures: input.consecutiveFailures, prerequisiteBlocked: input.prerequisiteBlocked, diminishingReturns, reasons, observedAt: input.observedAt, projectionOnly: true, executionPermissionGranted: false, authorityEffect: "UNCHANGED" }; }
  adapt(input: Readonly<{ adaptationId: string; run: StrategyRun; strategy: StrategyDefinition; fromOrdinal: number; condition: StrategyAdaptationRecommendation["condition"]; reason: string; createdAt: string }>): StrategyAdaptationRecommendation { const branch = input.strategy.steps.find((step) => step.ordinal === input.fromOrdinal)?.adaptiveBranch; const preauthorized = input.run.status === "RUNNING" && branch?.condition === input.condition; return { adaptationId: input.adaptationId, runId: input.run.runId, fromOrdinal: input.fromOrdinal, condition: input.condition, status: preauthorized ? "PREAUTHORIZED_BRANCH" : "REQUIRES_PLAN_APPROVAL", reason: input.reason, createdAt: input.createdAt, recommendationOnly: true, executionPermissionGranted: false, authorityEffect: "UNCHANGED" }; }
  switch(input: Readonly<{ recommendationId: string; run: StrategyRun; health: StrategyRuntimeHealth; eligibleAlternatives: readonly Readonly<{ strategyId: string; expectedBenefit: number; switchCost: number; uncertaintyMargin: number }>[]; minimumAttempts: number; createdAt: string }>): StrategySwitchRecommendation { const alternatives = input.eligibleAlternatives.filter((candidate) => candidate.expectedBenefit > candidate.switchCost + candidate.uncertaintyMargin).sort((left, right) => right.expectedBenefit - right.switchCost - right.uncertaintyMargin - (left.expectedBenefit - left.switchCost - left.uncertaintyMargin)); const selected = input.health.state === "FAILING" && input.run.attemptsUsed >= input.minimumAttempts ? alternatives[0] ?? null : null; const status = selected ? "RECOMMENDED" : input.health.state === "FAILING" && input.run.attemptsUsed >= input.minimumAttempts ? "NO_ELIGIBLE_ALTERNATIVE" : "INSUFFICIENT_EVIDENCE"; return { recommendationId: input.recommendationId, runId: input.run.runId, fromStrategyId: input.run.strategyId, toStrategyId: selected?.strategyId ?? null, status, expectedBenefit: selected?.expectedBenefit ?? null, switchCost: selected?.switchCost ?? 0, uncertaintyMargin: selected?.uncertaintyMargin ?? 0, reasons: selected ? ["Repeated failure meets the configured evidence threshold.", "Expected alternative benefit exceeds switch cost and uncertainty margin.", "A separate approved plan is required before switching."] : ["Do not switch on isolated failures or unproven alternatives."], requiresApprovedPlan: true, executionPermissionGranted: false, authorityEffect: "UNCHANGED", createdAt: input.createdAt }; }
}
