import type { LearningAuditLedger } from "../../types/learning-constitution/learningAuditLedger";
import type { RegistryStrategyHypothesis, StrategyExperiment, StrategyExperimentEvaluation, StrategyGovernanceDecision, StrategyRegistryStore } from "../../types/learning-constitution/strategyRegistry";
import type { ProvenanceActor } from "../../types/learning-constitution/provenance";
import type { StrategySelectionDecision } from "../../types/learning-constitution/strategySelection";
type Event = "STRATEGY_HYPOTHESIS_CREATED" | "STRATEGY_EXPERIMENT_STARTED" | "STRATEGY_EXPERIMENT_COMPLETED" | "STRATEGY_APPROVED" | "STRATEGY_REJECTED" | "STRATEGY_SUSPENDED" | "STRATEGY_ROLLED_BACK";
/** Append-only workflow persistence plus Phase 10 audit records for material strategy-governance decisions. */
export class StrategyRegistryWorkflowService {
  constructor(private readonly artifacts: StrategyRegistryStore, private readonly audit?: LearningAuditLedger) {}
  async recordHypothesis(item: RegistryStrategyHypothesis, workspaceId: string, actor: ProvenanceActor, correlationId: string) { await this.persist(`STRATEGY_HYPOTHESIS:${item.hypothesisId}`, "HYPOTHESIS", item.strategyId, item, item.createdAt, "STRATEGY_HYPOTHESIS_CREATED", workspaceId, actor, correlationId); return item; }
  async recordExperiment(item: StrategyExperiment, workspaceId: string, actor: ProvenanceActor, correlationId: string) { await this.persist(`STRATEGY_EXPERIMENT:${item.experimentId}`, "EXPERIMENT", item.controlStrategyId, item, item.createdAt, "STRATEGY_EXPERIMENT_STARTED", workspaceId, actor, correlationId); return item; }
  async recordEvaluation(item: StrategyExperimentEvaluation, strategyId: string, workspaceId: string, correlationId: string) { await this.persist(`STRATEGY_EVALUATION:${item.evaluationId}`, "EVALUATION", strategyId, item, item.completedAt, "STRATEGY_EXPERIMENT_COMPLETED", workspaceId, item.evaluator, correlationId); return item; }
  async recordDecision(item: StrategyGovernanceDecision, workspaceId: string, correlationId: string) { const event: Record<StrategyGovernanceDecision["decision"], Event> = { APPROVE: "STRATEGY_APPROVED", DEFER: "STRATEGY_REJECTED", REJECT: "STRATEGY_REJECTED", SUSPEND: "STRATEGY_SUSPENDED", ROLLBACK: "STRATEGY_ROLLED_BACK" }; await this.persist(`STRATEGY_GOVERNANCE:${item.decisionId}`, "GOVERNANCE_DECISION", item.strategyId, item, item.decidedAt, event[item.decision], workspaceId, item.decidedBy, correlationId); return item; }
  async recordSelection(item: StrategySelectionDecision, workspaceId: string, actor: ProvenanceActor, correlationId: string) { await this.selectionPersist(`STRATEGY_SELECTION:${item.decisionId}`, "SELECTION_DECISION", item.requestId, item, item.createdAt, "OPTIMIZATION_DECISION_RECORDED", workspaceId, actor, correlationId); return item; }
  private async persist(artifactId: string, artifactType: "HYPOTHESIS" | "EXPERIMENT" | "EVALUATION" | "GOVERNANCE_DECISION", subjectId: string, payload: unknown, occurredAt: string, eventType: Event, workspaceId: string, actor: ProvenanceActor, correlationId: string) { await this.artifacts.append({ artifactId, artifactType, subjectId, payload, createdAt: occurredAt }); if (this.audit) await this.audit.append({ eventId: `audit:${artifactId}`, eventType, workspaceId, occurredAt, actor, correlationId, schemaVersion: "10.0", references: {}, payload: { strategyId: subjectId, artifactId, authorityEffect: "UNCHANGED", executionPermissionGranted: false } }); }
  private async selectionPersist(artifactId: string, artifactType: "SELECTION_DECISION", subjectId: string, payload: unknown, occurredAt: string, eventType: "OPTIMIZATION_DECISION_RECORDED", workspaceId: string, actor: ProvenanceActor, correlationId: string) { await this.artifacts.append({ artifactId, artifactType, subjectId, payload, createdAt: occurredAt }); if (this.audit) await this.audit.append({ eventId: `audit:${artifactId}`, eventType, workspaceId, occurredAt, actor, correlationId, schemaVersion: "10.0", references: {}, payload: { requestId: subjectId, artifactId, authorityEffect: "UNCHANGED", executionPermissionGranted: false } }); }
}
