import type { LearningAuditLedger } from "../../types/learning-constitution/learningAuditLedger";
import type { LearningMethod, SelfDirectedLearningArtifactStore } from "../../types/learning-constitution/selfDirectedLearning";
import type { LearningObjectiveProfile, StrategyApprovalBridge, StrategyCurriculumProposal, StrategySelectionRecord } from "../../types/learning-constitution/strategySelectionEngine";
import { SelfDirectedLearningPlannerService } from "./selfDirectedLearningService";
const methodFor = (type: LearningObjectiveProfile["primaryType"]): LearningMethod => type === "PROCEDURAL" ? "PRACTICE_SEQUENCE" : type === "DECISION_JUDGMENT" ? "DECISION_REVIEW" : type === "DIAGNOSTIC" || type === "DISCRIMINATION" ? "TARGETED_EVALUATION" : "DIRECT_TEACHING_REQUEST";
/** Explicit human-only bridge from a Phase 40 proposal to the existing Phase 26 proposal/lease lifecycle. */
export class StrategyApprovalBridgeService {
  constructor(private readonly artifacts: SelfDirectedLearningArtifactStore, private readonly audit?: LearningAuditLedger) {}
  async approve(input: Readonly<{ bridgeId: string; proposal: StrategyCurriculumProposal; selection: StrategySelectionRecord; objective: LearningObjectiveProfile; actor: StrategyApprovalBridge["approvedBy"]; maximumQuestions: number; estimatedQuestions: number; estimatedMinutes: number; expiresAt: string; currentState: "KNOWN" | "PARTIALLY_KNOWN" | "UNCERTAIN" | "CONFLICTING" | "UNKNOWN" | "UNTESTED"; impact: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFORMATIONAL"; createdAt: string; workspaceId: string; correlationId: string }>) {
    if (input.actor.actorType !== "HUMAN") throw new Error("Only a human may approve a strategy curriculum proposal.");
    if (input.proposal.status !== "AWAITING_HUMAN_APPROVAL" || !input.proposal.immutable || input.proposal.executionAuthorized || input.proposal.selectionId !== input.selection.selectionId || input.selection.status !== "RECOMMENDED" || input.proposal.objectiveProfileId !== input.objective.profileId) throw new Error("Invalid strategy curriculum proposal lineage.");
    if (!input.objective.knowledgeGapIds.length) throw new Error("A strategy curriculum proposal needs a linked knowledge gap before approval.");
    if (input.estimatedQuestions < 1 || input.maximumQuestions < input.estimatedQuestions || input.estimatedMinutes < 1 || Date.parse(input.expiresAt) <= Date.parse(input.createdAt)) throw new Error("Approval requires a bounded future execution lease.");
    const proposalId = `phase40-learning-proposal:${input.bridgeId}`; const approvalId = `phase40-learning-approval:${input.bridgeId}`; const leaseId = `phase40-learning-lease:${input.bridgeId}`; const method = methodFor(input.objective.primaryType);
    const opportunity = { opportunityId: `phase40-opportunity:${input.bridgeId}`, sourceGapId: input.objective.knowledgeGapIds[0]!, triggerIds: [input.selection.selectionId, input.proposal.proposalId], subject: input.proposal.goal, currentState: input.currentState, scope: input.objective.domain, impact: input.impact, recurrence: 0, expectedInformationGain: input.objective.risk === "LOW" ? "MEDIUM" as const : "HIGH" as const, expectedImprovement: "MEDIUM" as const, teacherEffort: input.estimatedMinutes > 60 ? "HIGH" as const : "MODERATE" as const, risks: [input.objective.risk], alternatives: [method], priority: input.objective.risk === "SECURITY_CRITICAL" ? "VERY_HIGH" as const : input.objective.risk === "HIGH" ? "HIGH" as const : "MEDIUM" as const, recommendedMethod: method, status: "CANDIDATE" as const, createdBy: input.actor, createdAt: input.createdAt, durableKnowledgeEffect: "NONE" as const, executionPermissionGranted: false as const };
    const learningProposal = { proposalId, opportunityId: opportunity.opportunityId, sourceGapIds: input.objective.knowledgeGapIds, objective: input.proposal.goal, scope: input.objective.domain, whyLearnThis: `Phase 40 selected ${input.selection.selectedStrategyId} under ${input.selection.policyVersion}.`, evidenceIds: [`PHASE40_SELECTION:${input.selection.selectionId}`, `STRATEGY_CURRICULUM_PROPOSAL:${input.proposal.proposalId}`], missingUnderstanding: input.objective.knowledgeGapIds, method, teacherEffortBudget: { estimatedQuestions: input.estimatedQuestions, maximumQuestions: input.maximumQuestions, estimatedMinutes: input.estimatedMinutes }, risks: [input.objective.risk], successCriteria: input.proposal.requiredEvaluationDimensions.map((dimension) => `${dimension} evidence is required.`), baselineEvidenceIds: [`PHASE40_SELECTION:${input.selection.selectionId}`], status: "AWAITING_HUMAN_APPROVAL" as const, approvalRequired: true as const, createdBy: input.actor, createdAt: input.createdAt, expiresAt: input.expiresAt, durableKnowledgeEffect: "NONE" as const, executionPermissionGranted: false as const };
    const planner = new SelfDirectedLearningPlannerService(this.artifacts, this.audit); await planner.create(opportunity, learningProposal, input.workspaceId, input.correlationId); const lease = { leaseId, proposalId, approvalId, scope: learningProposal.scope, method, maximumQuestions: input.maximumQuestions, issuedBy: input.actor, issuedAt: input.createdAt, expiresAt: input.expiresAt, status: "ACTIVE" as const }; await planner.approve({ proposal: learningProposal, approval: { approvalId, proposalId, decision: "APPROVE", approvedScope: learningProposal.scope, approvedMethod: method, approvedBudget: { maximumQuestions: input.maximumQuestions }, decidedBy: input.actor, decidedAt: input.createdAt, executionLeaseId: leaseId }, lease, workspaceId: input.workspaceId, correlationId: input.correlationId }); const bridge: StrategyApprovalBridge = { bridgeId: input.bridgeId, curriculumProposalId: input.proposal.proposalId, selectionId: input.selection.selectionId, learningProposalId: proposalId, approvalId, leaseId, approvedBy: input.actor, approvedAt: input.createdAt, immutable: true, executionAuthorized: true, authorityEffect: "UNCHANGED" }; return { bridge, learningProposal, lease };
  }
}
