import { StrategyEligibilityService } from "./strategyEligibilityService";
import type { SelectionCandidate, StrategySelectionDecision, StrategySelectionRequest } from "../../types/learning-constitution/strategySelection";
import type { StrategyDefinition } from "../../types/learning-constitution/strategyRegistry";

/** Phase 38 hard gate: creates an inspectable selection candidate set before any optimization or execution consideration. */
export class StrategySelectionService {
  private readonly eligibility = new StrategyEligibilityService();
  candidates(request: StrategySelectionRequest, strategies: readonly StrategyDefinition[]): readonly SelectionCandidate[] { const contexts = request.context.strategyContexts; return strategies.map((strategy) => { const context = contexts.find((item) => strategy.applicableContexts.includes(item)); const eligibility = context ? this.eligibility.assess({ strategy, context, establishedPrerequisites: request.learner.satisfiedPrerequisites, budget: request.budget, requiredResources: request.requiredResources, availableResources: request.availableResources }) : { strategyId: strategy.strategyId, eligible: false, reasons: ["CONTEXT_INCOMPATIBLE"], unmetPrerequisites: [], budgetFit: true, governanceFit: true, projectionOnly: true as const, executionPermissionGranted: false as const, authorityEffect: "UNCHANGED" as const }; return { strategy, eligibility, excluded: !eligibility.eligible, exclusionReasons: eligibility.reasons }; }); }
  decide(input: Readonly<{ decisionId: string; request: StrategySelectionRequest; candidates: readonly SelectionCandidate[]; createdAt: string }>): StrategySelectionDecision { const prerequisiteBlocked = input.request.learner.failedPrerequisites.length > 0; const eligible = input.candidates.filter((candidate) => !candidate.excluded); const selected = prerequisiteBlocked ? null : eligible[0]?.strategy.strategyId ?? null; const status = prerequisiteBlocked ? "BLOCKED_BY_PREREQUISITES" : selected ? "RECOMMENDED" : "NO_ELIGIBLE_STRATEGY"; const explanation = prerequisiteBlocked ? [`Prerequisites failed: ${input.request.learner.failedPrerequisites.join(", ")}.`, "Pause the objective and use a governed prerequisite remediation plan before selection."] : selected ? [`${selected} is eligible; optimization may rank it only with other eligible candidates.`, "This decision is a recommendation, not plan approval or execution authorization."] : ["No strategy passed all hard context, prerequisite, resource, budget, risk, and governance constraints."]; return { decisionId: input.decisionId, requestId: input.request.requestId, selectedStrategyId: selected, candidates: input.candidates, status, explanation, createdAt: input.createdAt, immutable: true, recommendationOnly: true, autonomousPlanChangeAuthorized: false, executionPermissionGranted: false, authorityEffect: "UNCHANGED" }; }
}
