import type { StrategyDefinition, StrategyEligibility, StrategyRecommendation } from "../../types/learning-constitution/strategyRegistry";

/** Produces explainable, approval-gated recommendations only; execution remains owned by the governed learning-execution layer. */
export class StrategyRecommendationService {
  recommend(input: Readonly<{ recommendationId: string; objectiveId: string; candidates: readonly Readonly<{ strategy: StrategyDefinition; eligibility: StrategyEligibility; observedEvidenceState: StrategyRecommendation["evidenceState"]; observedStrengths: readonly string[]; knownCosts: readonly string[] }> []; createdAt: string }>): StrategyRecommendation {
    const eligible = input.candidates.filter((candidate) => candidate.eligibility.eligible).sort((left, right) => evidenceRank(right.observedEvidenceState) - evidenceRank(left.observedEvidenceState) || right.observedStrengths.length - left.observedStrengths.length || left.knownCosts.length - right.knownCosts.length);
    const selected = eligible[0] ?? null;
    return { recommendationId: input.recommendationId, objectiveId: input.objectiveId, selectedStrategyId: selected?.strategy.strategyId ?? null, alternatives: eligible.map((candidate, index) => ({ strategyId: candidate.strategy.strategyId, rank: index + 1, reasons: [...candidate.observedStrengths, ...candidate.knownCosts.map((cost) => `Known cost: ${cost}`)] })), eligibility: input.candidates.map((candidate) => candidate.eligibility), explanation: selected ? [`${selected.strategy.name} is eligible for this context.`, `Evidence state: ${selected.observedEvidenceState}.`, ...selected.observedStrengths, ...selected.knownCosts.map((cost) => `Tradeoff: ${cost}`), "Selection is advisory and requires an approved learning plan before execution."] : ["No candidate strategy satisfies the stated context, budget, resource, and governance constraints."], evidenceState: selected?.observedEvidenceState ?? "INSUFFICIENT_DATA", status: selected ? "AWAITING_APPROVAL" : "NO_ELIGIBLE_STRATEGY", createdAt: input.createdAt, recommendationOnly: true, autonomousPlanChangeAuthorized: false, executionPermissionGranted: false, authorityEffect: "UNCHANGED" };
  }
}
const evidenceRank = (state: StrategyRecommendation["evidenceState"]) => ["INSUFFICIENT_DATA", "EARLY_SIGNAL", "EMERGING_PATTERN", "SUPPORTED_PATTERN", "STRONG_EVIDENCE"].indexOf(state);
