import type { RegistryStrategyHypothesis, StrategyExperiment, StrategyExperimentEvaluation, StrategyGovernanceDecision, StrategyPerformanceProfile } from "../../types/learning-constitution/strategyRegistry";
/** Separates proposal, controlled experiment, independent evaluation, and human governance; no stage can self-adopt a strategy. */
export class StrategyExperimentService {
  hypothesize(input: Readonly<{ hypothesisId: string; strategyId: string; proposedChange: string; profiles: readonly StrategyPerformanceProfile[]; createdAt: string }>): RegistryStrategyHypothesis { const profiles = input.profiles.filter((profile) => profile.strategyId === input.strategyId && profile.sampleSize >= 3); if (!input.hypothesisId.trim() || !input.proposedChange.trim() || !profiles.length) throw new Error("strategy hypotheses require traceable observational profiles"); const strongest = profiles.sort((left, right) => rank(right.evidenceState) - rank(left.evidenceState))[0]; return { hypothesisId: input.hypothesisId, strategyId: input.strategyId, proposedChange: input.proposedChange, sourceProfileIds: profiles.map((profile) => profile.profileId), evidenceState: strongest.evidenceState, status: "PROPOSED", requiresGovernedReview: true, autonomousAdoptionAuthorized: false, createdAt: input.createdAt, executionPermissionGranted: false, authorityEffect: "UNCHANGED" }; }
  authorize(experiment: StrategyExperiment, approver: StrategyExperiment["approvedBy"]): StrategyExperiment { if (!approver || approver.actorType !== "HUMAN" || experiment.status !== "PROPOSED" || !experiment.independentEvaluatorId.trim() || !experiment.metrics.includes("RETENTION")) throw new Error("experiments require human authorization, independent evaluation, and retention measurement"); return { ...experiment, status: "AUTHORIZED", approvedBy: approver }; }
  evaluate(input: Readonly<{ evaluationId: string; experiment: StrategyExperiment; evaluator: StrategyExperimentEvaluation["evaluator"]; result: StrategyExperimentEvaluation["result"]; retentionMeasured: boolean; adversarialReviewPassed: boolean; limitations: readonly string[]; completedAt: string }>): StrategyExperimentEvaluation { if (input.experiment.status !== "COMPLETED" || input.evaluator.actorId !== input.experiment.independentEvaluatorId || input.evaluator.actorType === "AGENT" && input.evaluator.actorId === "agent:noesis") throw new Error("completed experiments require their designated independent evaluator"); return { evaluationId: input.evaluationId, experimentId: input.experiment.experimentId, evaluator: input.evaluator, result: input.result, retentionMeasured: input.retentionMeasured, adversarialReviewPassed: input.adversarialReviewPassed, limitations: input.limitations, completedAt: input.completedAt, independent: true, authorityEffect: "UNCHANGED", executionPermissionGranted: false }; }
  decide(input: Readonly<{ decisionId: string; strategyId: string; version: number; decision: StrategyGovernanceDecision["decision"]; evaluation: StrategyExperimentEvaluation; evidenceIds: readonly string[]; decidedBy: StrategyGovernanceDecision["decidedBy"]; reason: string; decidedAt: string }>): StrategyGovernanceDecision { if (input.decidedBy.actorType !== "HUMAN" || !input.reason.trim() || !input.evidenceIds.length) throw new Error("strategy governance decisions require a human and retained evidence"); if (input.decision === "APPROVE" && (input.evaluation.result !== "SUPPORTS_VARIANT" || !input.evaluation.retentionMeasured || !input.evaluation.adversarialReviewPassed)) throw new Error("approval requires independent support, retention evidence, and adversarial review"); return { decisionId: input.decisionId, strategyId: input.strategyId, version: input.version, decision: input.decision, evidenceIds: input.evidenceIds, decidedBy: input.decidedBy, reason: input.reason, decidedAt: input.decidedAt, createsExecutionPermission: false, authorityEffect: "UNCHANGED" }; }
}
const rank = (state: RegistryStrategyHypothesis["evidenceState"]) => ["INSUFFICIENT_DATA", "EARLY_SIGNAL", "EMERGING_PATTERN", "SUPPORTED_PATTERN", "STRONG_EVIDENCE"].indexOf(state);
