import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runTrustCertification, validateTrustCertification } from "@/services/trust-certification";
import type { FederationTrustDecision, TrustFederationBundle, TrustFederationFailure, TrustFederationInput, TrustFederationOutcome, TrustFederationResult, TrustFederationScenario, TrustFederationValidation } from "@/types/trust-ecosystem-federation";

const VERSION = "trust-ecosystem-federation/v5.17" as const;
const IDENTIFIER = "TrustEcosystemFederation" as const;
const NOW = "2026-07-19T00:00:00.000Z";
const EXPIRES = "2027-07-19T00:00:00.000Z";
let certificationBaseline: ReturnType<typeof runTrustCertification> | undefined;
function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly TrustFederationFailure[], failure: TrustFederationFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustFederationScenario): TrustFederationFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function outcome(failures: readonly TrustFederationFailure[]): TrustFederationOutcome { return has(failures, "GOVERNANCE_REVIEW_REQUIRED") ? "REQUIRES_GOVERNANCE_REVIEW" : failures.length ? "FAIL" : "PASS"; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function resultReplayHash(result: Omit<TrustFederationResult, "replay_hash" | "integrity_hash">): string { return hash({ architecture: result.architecture.integrity_hash, identity: result.identity.integrity_hash, record: result.record.integrity_hash, matrix: result.matrix.integrity_hash, evaluation: result.evaluation.integrity_hash, compatibility: result.compatibility.integrity_hash, governance: result.governance.integrity_hash, lineage: result.lineage.integrity_hash, invalidation: result.invalidation.integrity_hash, lifecycle: result.lifecycle.integrity_hash, observability: result.observability.integrity_hash, audit: result.audit.integrity_hash, security: result.security.integrity_hash, certification: result.certification.integrity_hash }); }
function resultIntegrityHash(result: Omit<TrustFederationResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.certification.outcome, replay_hash: result.replay_hash }); }

export function runTrustEcosystemFederation(input: TrustFederationInput = {}): TrustFederationResult {
  const direct = scenarioFailure(input.scenario ?? "BASELINE");
  const scenarioFailures = freezeArray<TrustFederationFailure>(direct ? [direct] : []);
  certificationBaseline ??= runTrustCertification();
  const dependencyFailures = freezeArray<TrustFederationFailure>(!validateTrustCertification(certificationBaseline).valid || has(scenarioFailures, "P5_16_CERTIFICATION_INVALID") ? ["P5_16_CERTIFICATION_INVALID"] : []);
  const failures = freezeArray([...new Set([...scenarioFailures, ...dependencyFailures])]);
  const federationId = input.federation_id ?? "federation:civitas:ecosystem";
  const participantId = input.participant_id ?? "program:5:cata";
  const trustDomain = input.trust_domain ?? "trust-domain:civitas:root";
  const badEvidence = has(failures, "FEDERATION_EVIDENCE_MISSING") || has(failures, "FEDERATION_EVIDENCE_STALE") || has(failures, "FEDERATION_EVIDENCE_CONFLICTING") || has(failures, "FEDERATION_EVIDENCE_UNVERIFIABLE");
  const evidenceRefs = badEvidence ? freezeArray<string>([]) : freezeArray(["program-2:governance-evidence", "program-3:qualification-evidence", "program-4:application-certification", certificationBaseline.certificate.certificate_id]);
  const architecture = nested({ architecture_id: "architecture:federation:p5.17", federation_model: !has(failures, "FEDERATION_ARCHITECTURE_MISSING"), trust_domains: !has(failures, "FEDERATION_ARCHITECTURE_MISSING"), federation_contracts: !has(failures, "FEDERATION_ARCHITECTURE_MISSING"), expands_visibility_not_authority: true });
  const identity = nested({ identity_registry_id: "identity-registry:federation:p5.17", program_identity: !has(failures, "FEDERATION_IDENTITY_MODEL_MISSING"), application_identity: !has(failures, "FEDERATION_IDENTITY_MODEL_MISSING"), trust_domain_identity: !has(failures, "FEDERATION_IDENTITY_MODEL_MISSING"), federation_membership: !has(failures, "FEDERATION_IDENTITY_MODEL_MISSING"), trust_relationship_identity: !has(failures, "FEDERATION_IDENTITY_MODEL_MISSING") });
  const matrix = nested({ matrix_id: "matrix:cross-program-trust:p5.17", program_program: !has(failures, "CROSS_PROGRAM_MATRIX_MISSING"), program_application: !has(failures, "CROSS_PROGRAM_MATRIX_MISSING"), application_application: !has(failures, "CROSS_PROGRAM_MATRIX_MISSING"), trust_domain_trust_domain: !has(failures, "CROSS_PROGRAM_MATRIX_MISSING"), tenant_trust_isolation: !has(failures, "TENANT_ISOLATION_FAILURE") });
  const compatibility = nested({ report_id: "compatibility:federation:p5.17", trust_exchange: !has(failures, "TRUST_INTEROPERABILITY_MISSING"), evidence_exchange: !has(failures, "TRUST_INTEROPERABILITY_MISSING"), qualification_interoperability: !has(failures, "INTEROPERABILITY_NOT_VERIFIED"), certification_compatibility: !has(failures, "INTEROPERABILITY_NOT_VERIFIED"), governance_compatibility: !has(failures, "INTEROPERABILITY_NOT_VERIFIED") });
  const governance = nested({ governance_id: "governance:federation:p5.17", governance_inheritance: !has(failures, "FEDERATION_GOVERNANCE_MISSING") && !has(failures, "GOVERNANCE_NOT_ENFORCED"), constitutional_compatibility: !has(failures, "CONSTITUTIONAL_COMPLIANCE_INVALID"), authority_boundaries: !has(failures, "UNAUTHORIZED_AUTHORITY_GRANTED"), trust_restrictions: !has(failures, "IMPLICIT_TRUST_PROPAGATED"), policy_compatibility: !has(failures, "GOVERNANCE_NOT_ENFORCED") });
  const lineage = nested({ validation_id: "P5-P4-VERIFY-001" as const, certification_lineage: !has(failures, "P5_P4_LINEAGE_COMPATIBILITY_FAILED") && !has(failures, "CERTIFICATION_LINEAGE_INCOMPATIBLE"), certificate_ancestry: !has(failures, "P5_P4_LINEAGE_COMPATIBILITY_FAILED"), qualification_compatibility: !has(failures, "P5_P4_LINEAGE_COMPATIBILITY_FAILED"), application_lineage: !has(failures, "P5_P4_LINEAGE_COMPATIBILITY_FAILED"), ecosystem_lineage: !has(failures, "P5_P4_LINEAGE_COMPATIBILITY_FAILED"), compatible: !has(failures, "P5_P4_LINEAGE_COMPATIBILITY_FAILED") && !has(failures, "CERTIFICATION_LINEAGE_INCOMPATIBLE") });
  const invalidation = nested({ invalidation_id: "invalidation:federation:p5.17", certification_revoked: true, certification_suspended: true, certification_expired: true, qualification_failure: true, governance_failure: true, lineage_verified_before_invalidation: lineage.compatible && !has(failures, "INVALIDATION_BEFORE_LINEAGE_VERIFICATION") && !has(failures, "CERTIFICATION_TRIGGERED_INVALIDATION_MISSING") });
  const trustDecision: FederationTrustDecision = badEvidence || !lineage.compatible || has(failures, "PROGRAM_3_QUALIFICATION_BYPASSED") || has(failures, "PROGRAM_4_CERTIFICATION_BYPASSED") ? "FAIL_CLOSED" : "CONDITIONALLY_TRUSTED";
  const record = nested({ federation_trust_id: has(failures, "FEDERATION_TRUST_REGISTRY_MISSING") ? "" : "federation-trust:p5.17", federation_id: federationId, participant_id: participantId, participant_type: "PROGRAM" as const, trust_domain: trustDomain, trust_relationship: "advisory-cross-program-visibility", trust_level: "ADVISORY" as const, trust_standing: trustDecision === "FAIL_CLOSED" ? "SUSPENDED" as const : "ACTIVE" as const, confidence_score: trustDecision === "FAIL_CLOSED" ? 0 : 0.86, alignment_score: trustDecision === "FAIL_CLOSED" ? 0 : 0.91, risk_score: trustDecision === "FAIL_CLOSED" ? 1 : 0.24, qualification_reference: "program-3:qualification", certification_reference: certificationBaseline.certificate.certificate_id, evidence_references: evidenceRefs, governance_references: freezeArray(["program-2:governance", "program-4:ecosystem-governance"]), policy_references: freezeArray(["policy:federation:advisory-only"]), lineage_reference: "lineage:federation:p5.17", evaluation_timestamp: NOW, expiration_timestamp: EXPIRES });
  const evaluation = nested({ evaluation_id: has(failures, "FEDERATION_TRUST_EVALUATION_MISSING") ? "" : "evaluation:federation:p5.17", federation_id: federationId, evaluation_scope: "ecosystem-trust-visibility", evaluation_inputs: evidenceRefs, trust_decision: trustDecision, standing: record.trust_standing, confidence: record.confidence_score, risk: record.risk_score, governance_result: governance.governance_inheritance, alignment_result: true, policy_result: governance.policy_compatibility, qualification_result: !has(failures, "PROGRAM_3_QUALIFICATION_BYPASSED"), certification_result: !has(failures, "PROGRAM_4_CERTIFICATION_BYPASSED"), fail_closed_reason: trustDecision === "FAIL_CLOSED" ? "federation prerequisite failed" : "", evaluation_timestamp: NOW });
  const lifecycle = nested({ lifecycle_id: has(failures, "FEDERATION_LIFECYCLE_MISSING") ? "" : "lifecycle:federation:p5.17", status: record.trust_standing, membership_registered: true, activation_allowed: trustDecision !== "FAIL_CLOSED", restricted_supported: true, suspension_supported: true, revocation_supported: true, termination_supported: true });
  const observability = nested({ dashboard_id: has(failures, "OBSERVABILITY_NOT_OPERATIONAL") || has(failures, "FEDERATION_OBSERVABILITY_MISSING") ? "" : "dashboard:federation:p5.17", federation_health: !has(failures, "FEDERATION_OBSERVABILITY_MISSING"), trust_propagation: !has(failures, "FEDERATION_OBSERVABILITY_MISSING"), interoperability_failures: !has(failures, "FEDERATION_OBSERVABILITY_MISSING"), governance_violations: !has(failures, "FEDERATION_OBSERVABILITY_MISSING"), evidence_freshness: !has(failures, "FEDERATION_OBSERVABILITY_MISSING"), certification_changes: !has(failures, "FEDERATION_OBSERVABILITY_MISSING") });
  const audit = nested({ audit_id: has(failures, "FEDERATION_AUDIT_LINEAGE_MISSING") ? "" : "audit:federation:p5.17", federation_decisions: evaluation.evaluation_id ? freezeArray([evaluation.evaluation_id]) : freezeArray<string>([]), trust_lineage: record.federation_trust_id ? freezeArray([record.federation_trust_id]) : freezeArray<string>([]), evidence_lineage: has(failures, "FEDERATION_LINEAGE_INCOMPLETE") ? freezeArray<string>([]) : evidenceRefs.map((ref) => `lineage:${ref}`), governance_lineage: freezeArray(["lineage:program-2-governance", "lineage:program-4-governance"]), certification_lineage: freezeArray([certificationBaseline.certificate.certificate_id]), immutable: true, replay_refs: has(failures, "FEDERATION_REPLAY_FAILED") ? freezeArray<string>([]) : freezeArray(["replay:p5.17:federation"]) });
  const security = nested({ security_id: "security:federation:p5.17", tenant_isolation: !has(failures, "TENANT_ISOLATION_FAILURE"), identity_separation: !has(failures, "TENANT_ISOLATION_FAILURE"), namespace_isolation: !has(failures, "TENANT_ISOLATION_FAILURE"), evidence_ownership: !has(failures, "TENANT_ISOLATION_FAILURE"), federation_boundaries: !has(failures, "TENANT_ISOLATION_FAILURE") });
  const advisoryOnly = !has(failures, "UNAUTHORIZED_AUTHORITY_GRANTED") && !has(failures, "PRIVILEGE_ELEVATED") && !has(failures, "EXECUTION_AUTHORIZED_BY_FEDERATION") && !has(failures, "IMPLICIT_TRUST_PROPAGATED");
  const failClosedVerified = !has(failures, "FAIL_CLOSED_NOT_VERIFIED") && (!badEvidence || trustDecision === "FAIL_CLOSED") && (!lineage.compatible ? trustDecision === "FAIL_CLOSED" : true);
  const traceable = audit.audit_id.length > 0 && audit.evidence_lineage.length > 0 && audit.replay_refs.length > 0;
  const derivedFailures = freezeArray([...new Set([...failures, ...(!architecture.federation_model ? ["FEDERATION_ARCHITECTURE_MISSING" as const] : []), ...(!identity.program_identity ? ["FEDERATION_IDENTITY_MODEL_MISSING" as const] : []), ...(record.federation_trust_id.length === 0 ? ["FEDERATION_TRUST_REGISTRY_MISSING" as const] : []), ...(!matrix.program_program ? ["CROSS_PROGRAM_MATRIX_MISSING" as const] : []), ...(evaluation.evaluation_id.length === 0 ? ["FEDERATION_TRUST_EVALUATION_MISSING" as const] : []), ...(!compatibility.trust_exchange ? ["TRUST_INTEROPERABILITY_MISSING" as const] : []), ...(!governance.governance_inheritance ? ["GOVERNANCE_NOT_ENFORCED" as const] : []), ...(!lineage.compatible ? ["P5_P4_LINEAGE_COMPATIBILITY_FAILED" as const] : []), ...(!invalidation.lineage_verified_before_invalidation ? ["CERTIFICATION_TRIGGERED_INVALIDATION_MISSING" as const] : []), ...(lifecycle.lifecycle_id.length === 0 ? ["FEDERATION_LIFECYCLE_MISSING" as const] : []), ...(observability.dashboard_id.length === 0 ? ["OBSERVABILITY_NOT_OPERATIONAL" as const] : []), ...(!traceable ? ["FEDERATION_AUDIT_LINEAGE_MISSING" as const] : []), ...(!security.tenant_isolation ? ["TENANT_ISOLATION_FAILURE" as const] : []), ...(badEvidence ? [has(failures, "FEDERATION_EVIDENCE_STALE") ? "FEDERATION_EVIDENCE_STALE" as const : has(failures, "FEDERATION_EVIDENCE_CONFLICTING") ? "FEDERATION_EVIDENCE_CONFLICTING" as const : has(failures, "FEDERATION_EVIDENCE_UNVERIFIABLE") ? "FEDERATION_EVIDENCE_UNVERIFIABLE" as const : "FEDERATION_EVIDENCE_MISSING" as const] : []), ...(audit.replay_refs.length === 0 ? ["FEDERATION_REPLAY_FAILED" as const] : []), ...(!compatibility.qualification_interoperability ? ["INTEROPERABILITY_NOT_VERIFIED" as const] : []), ...(!governance.constitutional_compatibility ? ["CONSTITUTIONAL_COMPLIANCE_INVALID" as const] : []), ...(has(failures, "INVALIDATION_BEFORE_LINEAGE_VERIFICATION") ? ["INVALIDATION_BEFORE_LINEAGE_VERIFICATION" as const] : []), ...(!failClosedVerified ? ["FAIL_CLOSED_NOT_VERIFIED" as const] : []), ...(!advisoryOnly ? [scenarioFailures[0] as TrustFederationFailure] : [])])]);
  const certification = nested({ certification_id: "P5.17-ECOSYSTEM-TRUST-FEDERATION-CERTIFICATION-001", outcome: outcome(derivedFailures), phase_ready: outcome(derivedFailures) === "PASS", architecture_complete: architecture.federation_model && architecture.federation_contracts, registry_operational: record.federation_trust_id.length > 0, interoperability_verified: compatibility.trust_exchange && compatibility.certification_compatibility && compatibility.governance_compatibility, trust_evaluation_deterministic: evaluation.evaluation_id.length > 0, governance_enforced: governance.governance_inheritance && governance.authority_boundaries, constitutional_compliance_verified: governance.constitutional_compatibility, certification_lineage_compatible: lineage.compatible, p5_p4_verify_001_satisfied: lineage.compatible, tenant_isolation_maintained: security.tenant_isolation && matrix.tenant_trust_isolation, replay_reproducible: audit.replay_refs.length > 0, audit_lineage_complete: traceable, observability_operational: observability.dashboard_id.length > 0, fail_closed_verified: failClosedVerified, advisory_only: advisoryOnly, failures: derivedFailures });
  const base: Omit<TrustFederationResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, certification_ref: "trust-certification/v5.16", architecture, identity, record, matrix, evaluation, compatibility, governance, lineage, invalidation, lifecycle, observability, audit, security, certification };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustEcosystemFederation(result?: TrustFederationResult): TrustFederationValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, architecture_valid: false, identity_valid: false, record_valid: false, matrix_valid: false, evaluation_valid: false, compatibility_valid: false, governance_valid: false, lineage_valid: false, invalidation_valid: false, lifecycle_valid: false, observability_valid: false, audit_valid: false, security_valid: false, certification_valid: false, failures: freezeArray(["FEDERATION_ARCHITECTURE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const architecture_valid = verifyHashed(result.architecture) && result.architecture.federation_model && result.architecture.expands_visibility_not_authority;
  const identity_valid = verifyHashed(result.identity) && result.identity.program_identity && result.identity.application_identity && result.identity.federation_membership;
  const record_valid = verifyHashed(result.record) && result.record.federation_trust_id.length > 0 && result.record.trust_level === "ADVISORY" && result.record.evidence_references.length > 0;
  const matrix_valid = verifyHashed(result.matrix) && result.matrix.program_program && result.matrix.program_application && result.matrix.application_application && result.matrix.tenant_trust_isolation;
  const evaluation_valid = verifyHashed(result.evaluation) && result.evaluation.trust_decision === "CONDITIONALLY_TRUSTED" && result.evaluation.qualification_result && result.evaluation.certification_result;
  const compatibility_valid = verifyHashed(result.compatibility) && result.compatibility.trust_exchange && result.compatibility.evidence_exchange && result.compatibility.qualification_interoperability && result.compatibility.certification_compatibility;
  const governance_valid = verifyHashed(result.governance) && result.governance.governance_inheritance && result.governance.constitutional_compatibility && result.governance.authority_boundaries;
  const lineage_valid = verifyHashed(result.lineage) && result.lineage.compatible && result.lineage.validation_id === "P5-P4-VERIFY-001";
  const invalidation_valid = verifyHashed(result.invalidation) && result.invalidation.lineage_verified_before_invalidation;
  const lifecycle_valid = verifyHashed(result.lifecycle) && result.lifecycle.lifecycle_id.length > 0 && result.lifecycle.status === "ACTIVE" && result.lifecycle.activation_allowed;
  const observability_valid = verifyHashed(result.observability) && result.observability.dashboard_id.length > 0 && result.observability.federation_health;
  const audit_valid = verifyHashed(result.audit) && result.audit.audit_id.length > 0 && result.audit.evidence_lineage.length > 0 && result.audit.replay_refs.length > 0;
  const security_valid = verifyHashed(result.security) && result.security.tenant_isolation && result.security.identity_separation && result.security.namespace_isolation;
  const certification_valid = verifyHashed(result.certification) && result.certification.outcome === "PASS" && result.certification.phase_ready && result.certification.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && architecture_valid && identity_valid && record_valid && matrix_valid && evaluation_valid && compatibility_valid && governance_valid && lineage_valid && invalidation_valid && lifecycle_valid && observability_valid && audit_valid && security_valid && certification_valid;
  return nested({ valid, outcome: result.certification.outcome, replay_hash_valid, integrity_hash_valid, architecture_valid, identity_valid, record_valid, matrix_valid, evaluation_valid, compatibility_valid, governance_valid, lineage_valid, invalidation_valid, lifecycle_valid, observability_valid, audit_valid, security_valid, certification_valid, failures: result.certification.failures });
}

export function replayTrustEcosystemFederation(result = runTrustEcosystemFederation()): boolean {
  const replayed = runTrustEcosystemFederation();
  return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustEcosystemFederation(result).valid;
}

export function getTrustEcosystemFederationBundle(): TrustFederationBundle {
  const result = runTrustEcosystemFederation();
  return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_cross_program_trust_federation: true, owns_federation_governance: true, owns_trust_interoperability: true, owns_federation_trust_evaluation: true, grants_authority: false, elevates_privilege: false, authorizes_execution: false, bypasses_constitutional_governance: false, replaces_originating_trust_evaluations: false }), result, validation: validateTrustEcosystemFederation(result) });
}

export const TrustEcosystemFederationService = Object.freeze({ run: runTrustEcosystemFederation, validate: validateTrustEcosystemFederation, replay: replayTrustEcosystemFederation });
