import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runProvingPerformanceScalabilityQualification, validateProvingPerformanceScalabilityQualification } from "@/services/proving-performance-scalability-qualification";
import type { EcosystemScenario, IntegrationBundle, IntegrationFailure, IntegrationInput, IntegrationOutcome, IntegrationResult, IntegrationScenario, IntegrationValidation, ProgramIdentifier } from "@/types/proving-cross-program-integration-validation";

const VERSION = "proving-cross-program-integration-validation/v6.10" as const;
const IDENTIFIER = "ProvingCrossProgramIntegrationValidation" as const;
const PROGRAMS = Object.freeze<ProgramIdentifier[]>(["PROGRAM_1_CAPABILITY_ATLAS", "PROGRAM_2_CORE_INFRASTRUCTURE", "PROGRAM_3_CAF_LEGION", "PROGRAM_4_ECOSYSTEM_APPLICATIONS", "PROGRAM_5_CATA_TRUST_FRAMEWORK"]);
const ECOSYSTEM_SCENARIOS = Object.freeze<EcosystemScenario[]>(["MISSION_EXECUTION", "OPERATOR_INTERVENTION", "TRUST_DEGRADATION", "CERTIFICATION_REVOCATION", "DEPENDENCY_FAILURES", "REGIONAL_FAILOVER", "TENANT_ISOLATION_BREACH_ATTEMPT", "POLICY_UPDATES", "GOVERNANCE_ESCALATION", "DISASTER_RECOVERY", "LARGE_SCALE_DEPLOYMENTS", "FEDERATION_OPERATIONS"]);
let performanceBaseline: ReturnType<typeof runProvingPerformanceScalabilityQualification> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly IntegrationFailure[], failure: IntegrationFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: IntegrationScenario): IntegrationFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function outcome(failures: readonly IntegrationFailure[]): IntegrationOutcome { if (has(failures, "GOVERNANCE_REVIEW_REQUIRED")) return "REQUIRES_REVIEW"; return failures.length ? "FAIL" : "PASS"; }
function refs(ok: boolean, name: string): readonly string[] { return ok ? freezeArray([`evidence:p6.10:${name}`]) : freezeArray<string>([]); }
function resultReplayHash(result: Omit<IntegrationResult, "replay_hash" | "integrity_hash">): string { return hash({ dependency: result.dependency_report.integrity_hash, interface: result.interface_report.integrity_hash, workflow: result.workflow_report.integrity_hash, event: result.event_report.integrity_hash, data: result.data_report.integrity_hash, governance: result.governance_report.integrity_hash, trust: result.trust_report.integrity_hash, replay: result.replay_report.integrity_hash, ecosystem: result.ecosystem_report.integrity_hash, matrix: result.compatibility_matrix.integrity_hash, evidence: result.evidence.integrity_hash, gates: result.gates.integrity_hash, boundaries: result.boundaries.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<IntegrationResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.readiness.outcome, replay_hash: result.replay_hash }); }

export function runProvingCrossProgramIntegrationValidation(input: IntegrationInput = {}): IntegrationResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<IntegrationFailure>(direct ? [direct] : []);
  performanceBaseline ??= runProvingPerformanceScalabilityQualification();
  const performanceInvalid = !validateProvingPerformanceScalabilityQualification(performanceBaseline).valid || has(scenarioFailures, "P6_9_PERFORMANCE_QUALIFICATION_INVALID");
  const failures = freezeArray([...new Set([...scenarioFailures, ...(performanceInvalid ? ["P6_9_PERFORMANCE_QUALIFICATION_INVALID" as const] : [])])]);
  const dependencyOk = !has(failures, "DEPENDENCY_ENGINE_MISSING") && !has(failures, "DEPENDENCY_GRAPH_INCOMPLETE") && !has(failures, "DEPENDENCY_INCORRECT") && !has(failures, "CIRCULAR_DEPENDENCY_DETECTED") && !has(failures, "VERSION_COMPATIBILITY_FAILED") && !has(failures, "OWNERSHIP_VERIFICATION_FAILED") && !has(failures, "NAMESPACE_VALIDATION_FAILED") && !has(failures, "LIFECYCLE_COMPATIBILITY_FAILED");
  const interfaceOk = !has(failures, "INTERFACE_VALIDATION_MISSING") && !has(failures, "API_COMPATIBILITY_FAILED") && !has(failures, "EVENT_COMPATIBILITY_FAILED") && !has(failures, "MESSAGE_COMPATIBILITY_FAILED") && !has(failures, "SCHEMA_COMPATIBILITY_FAILED") && !has(failures, "SERIALIZATION_COMPATIBILITY_FAILED") && !has(failures, "PROTOCOL_COMPATIBILITY_FAILED") && !has(failures, "CONTRACT_EVOLUTION_FAILED") && !has(failures, "BACKWARD_COMPATIBILITY_FAILED");
  const workflowOk = !has(failures, "INTEGRATION_TESTING_MISSING") && !has(failures, "WORKFLOW_EXECUTION_FAILED") && !has(failures, "IDENTITY_PROPAGATION_FAILED") && !has(failures, "AUTHORITY_PROPAGATION_FAILED") && !has(failures, "TRUST_PROPAGATION_FAILED") && !has(failures, "GOVERNANCE_PROPAGATION_FAILED") && !has(failures, "EVIDENCE_PROPAGATION_FAILED") && !has(failures, "REPLAY_PROPAGATION_FAILED");
  const eventOk = !has(failures, "EVENT_COMPATIBILITY_FAILED");
  const dataOk = !has(failures, "DATA_INTEROPERABILITY_FAILED");
  const governanceOk = !has(failures, "GOVERNANCE_INTEGRATION_FAILED") && !has(failures, "TENANT_ISOLATION_FAILED") && !has(failures, "FAIL_CLOSED_BEHAVIOR_FAILED") && !has(failures, "CONSTITUTIONAL_BOUNDARY_VIOLATED");
  const trustOk = !has(failures, "TRUST_INTEGRATION_FAILED");
  const replayOk = !has(failures, "REPLAY_COMPATIBILITY_FAILED") && !performanceInvalid;
  const ecosystemOk = !has(failures, "ECOSYSTEM_SCENARIO_FAILED");
  const matrixOk = !has(failures, "COMPATIBILITY_MATRIX_MISSING") && !has(failures, "COMPATIBILITY_MATRIX_INCOMPLETE");
  const evidenceOk = !has(failures, "INTEGRATION_EVIDENCE_MISSING") && !has(failures, "INTEGRATION_EVIDENCE_MUTATED") && !has(failures, "INTEGRATION_LINEAGE_INCOMPLETE");
  const boundariesOk = !has(failures, "INDIVIDUAL_PROGRAM_CERTIFICATION_ATTEMPTED") && !has(failures, "PROGRAM_ARCHITECTURE_MODIFICATION_ATTEMPTED") && !has(failures, "PROGRAM_CERTIFICATION_REPLACEMENT_ATTEMPTED") && !has(failures, "INTERFACE_REDEFINITION_ATTEMPTED") && !has(failures, "CONSTITUTIONAL_OWNERSHIP_REDEFINITION_ATTEMPTED");
  const dependency_report = nested({ report_id: dependencyOk ? "report:p6.10:dependencies" : "", programs: dependencyOk ? PROGRAMS : freezeArray<ProgramIdentifier>([]), graph_complete: dependencyOk, dependencies_correct: dependencyOk, circular_dependencies_absent: dependencyOk, version_compatible: dependencyOk, ownership_preserved: dependencyOk, namespaces_valid: dependencyOk, lifecycle_compatible: dependencyOk, evidence_refs: refs(evidenceOk, "dependencies") });
  const interface_report = nested({ report_id: interfaceOk ? "report:p6.10:interfaces" : "", api_compatible: interfaceOk, events_compatible: interfaceOk && eventOk, messages_compatible: interfaceOk, schemas_compatible: interfaceOk, serialization_compatible: interfaceOk, protocols_compatible: interfaceOk, contract_evolution_valid: interfaceOk, backward_compatible: interfaceOk, evidence_refs: refs(evidenceOk, "interfaces") });
  const workflow_report = nested({ report_id: workflowOk ? "report:p6.10:workflow" : "", workflow: workflowOk ? freezeArray(["PROGRAM_1_CAPABILITY_ATLAS", "PROGRAM_2_CORE_INFRASTRUCTURE", "PROGRAM_3_CAF_LEGION", "PROGRAM_5_CATA_TRUST_FRAMEWORK", "PROGRAM_4_ECOSYSTEM_APPLICATIONS"] as const) : freezeArray<ProgramIdentifier>([]), mission_execution: workflowOk, identity_propagation: workflowOk, authority_propagation: workflowOk, trust_propagation: workflowOk, governance_propagation: workflowOk, evidence_propagation: workflowOk, replay_propagation: workflowOk, deterministic: workflowOk && replayOk, evidence_refs: refs(evidenceOk, "workflow") });
  const event_report = nested({ report_id: eventOk ? "report:p6.10:events" : "", event_production: eventOk, event_delivery: eventOk, event_ordering: eventOk, event_replay: eventOk && replayOk, idempotency: eventOk, version_compatibility: eventOk, routing_validation: eventOk, subscription_validation: eventOk, compatibility_matrix_ref: matrixOk ? "matrix:p6.10:compatibility" : "", evidence_refs: refs(evidenceOk, "events") });
  const data_report = nested({ report_id: dataOk ? "report:p6.10:data" : "", identity_consistency: dataOk, registry_consistency: dataOk, evidence_consistency: dataOk, trust_consistency: dataOk, audit_consistency: dataOk, lineage_consistency: dataOk, schema_consistency: dataOk, serialization_compatibility: dataOk && interfaceOk, evidence_refs: refs(evidenceOk, "data") });
  const governance_report = nested({ report_id: governanceOk ? "report:p6.10:governance" : "", constitutional_inheritance: governanceOk, authority_precedence: governanceOk, policy_enforcement: governanceOk, tenant_isolation: governanceOk, governance_escalation: governanceOk, human_oversight: governanceOk, certification_dependencies: governanceOk, fail_closed_behavior: governanceOk, evidence_refs: refs(evidenceOk, "governance") });
  const trust_report = nested({ report_id: trustOk ? "report:p6.10:trust" : "", trust_decisions_compatible: trustOk, trust_standing_propagation: trustOk, trust_restrictions: trustOk, trust_recovery: trustOk, certification_compatibility: trustOk, federation_compatibility: trustOk, authorization_behavior: trustOk, evidence_refs: refs(evidenceOk, "trust") });
  const replay_report = nested({ report_id: replayOk ? "report:p6.10:replay" : "", replay_fidelity: replayOk, evidence_consistency: replayOk && dataOk, deterministic_execution: replayOk && workflowOk, replay_lineage: replayOk, replay_compatibility: replayOk, replay_interoperability: replayOk, evidence_refs: refs(evidenceOk, "replay") });
  const ecosystem_report = nested({ report_id: ecosystemOk ? "report:p6.10:ecosystem" : "", scenarios: ecosystemOk ? ECOSYSTEM_SCENARIOS : freezeArray<EcosystemScenario>([]), normal_conditions: ecosystemOk, degraded_conditions: ecosystemOk, recovery_conditions: ecosystemOk, adversarial_conditions: ecosystemOk, exercises_complete: ecosystemOk, evidence_refs: refs(evidenceOk, "ecosystem") });
  const compatibility_matrix = nested({ matrix_id: matrixOk ? "matrix:p6.10:compatibility" : "", version_compatibility: matrixOk && dependencyOk, dependency_compatibility: matrixOk && dependencyOk, interface_compatibility: matrixOk && interfaceOk, trust_compatibility: matrixOk && trustOk, governance_compatibility: matrixOk && governanceOk, replay_compatibility: matrixOk && replayOk, certification_compatibility: matrixOk && trustOk && governanceOk, programs: matrixOk ? PROGRAMS : freezeArray<ProgramIdentifier>([]) });
  const evidence = nested({ evidence_id: evidenceOk ? "evidence:p6.10:integration" : "", dependency_evidence: refs(evidenceOk, "dependencies"), interface_evidence: refs(evidenceOk, "interfaces"), integration_evidence: refs(evidenceOk, "workflow"), event_evidence: refs(evidenceOk, "events"), data_evidence: refs(evidenceOk, "data"), governance_evidence: refs(evidenceOk, "governance"), trust_evidence: refs(evidenceOk, "trust"), replay_evidence: refs(evidenceOk, "replay"), ecosystem_evidence: refs(evidenceOk, "ecosystem"), compatibility_evidence: refs(evidenceOk, "matrix"), immutable: evidenceOk, traceable: evidenceOk, replayable: evidenceOk && replayOk, lineage_complete: evidenceOk });
  const gates = nested({ gate_id: "P6.10-GATES", dependency_integrity: dependencyOk, interface_compatibility: interfaceOk, integration_success: workflowOk && eventOk && dataOk, trust_compatibility: trustOk, replay_compatibility: replayOk, governance_validation: governanceOk, ecosystem_readiness: ecosystemOk && matrixOk && evidenceOk && boundariesOk, passed: false });
  const finalGates = nested({ ...gates, passed: gates.dependency_integrity && gates.interface_compatibility && gates.integration_success && gates.trust_compatibility && gates.replay_compatibility && gates.governance_validation && gates.ecosystem_readiness });
  const boundaries = nested({ boundary_id: "boundaries:p6.10", owns_individual_program_certification: false as const, owns_program_architecture_modification: false as const, owns_program_certification_replacement: false as const, owns_interface_redefinition: false as const, owns_constitutional_ownership_redefinition: false as const });
  const derivedFailures = freezeArray([...new Set([...failures, ...(!dependencyOk ? ["DEPENDENCY_ENGINE_MISSING" as const] : []), ...(!interfaceOk ? ["INTERFACE_VALIDATION_MISSING" as const] : []), ...(!workflowOk ? ["INTEGRATION_TESTING_MISSING" as const] : []), ...(!dataOk ? ["DATA_INTEROPERABILITY_FAILED" as const] : []), ...(!governanceOk ? ["GOVERNANCE_INTEGRATION_FAILED" as const] : []), ...(!trustOk ? ["TRUST_INTEGRATION_FAILED" as const] : []), ...(!replayOk ? ["REPLAY_COMPATIBILITY_FAILED" as const] : []), ...(!ecosystemOk ? ["ECOSYSTEM_SCENARIO_FAILED" as const] : []), ...(!matrixOk ? ["COMPATIBILITY_MATRIX_MISSING" as const] : []), ...(!evidenceOk ? ["INTEGRATION_EVIDENCE_MISSING" as const] : []), ...(!boundariesOk ? ["INDIVIDUAL_PROGRAM_CERTIFICATION_ATTEMPTED" as const] : [])])]);
  const finalOutcome = outcome(derivedFailures);
  const readiness = nested({ readiness_id: "P6.10-CROSS-PROGRAM-INTEGRATION-READINESS-001", outcome: finalOutcome, phase_ready: finalOutcome === "PASS", dependencies_ready: dependencyOk, interfaces_ready: interfaceOk, workflows_ready: workflowOk, events_ready: eventOk, data_ready: dataOk, governance_ready: governanceOk, trust_ready: trustOk, replay_ready: replayOk, ecosystem_ready: ecosystemOk, matrix_ready: matrixOk, evidence_ready: evidenceOk, gates_passed: finalGates.passed, boundaries_respected: boundariesOk, failures: derivedFailures });
  const base: Omit<IntegrationResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, performance_qualification_ref: "proving-performance-scalability-qualification/v6.9", dependency_report, interface_report, workflow_report, event_report, data_report, governance_report, trust_report, replay_report, ecosystem_report, compatibility_matrix, evidence, gates: finalGates, boundaries, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateProvingCrossProgramIntegrationValidation(result?: IntegrationResult): IntegrationValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, dependency_valid: false, interface_valid: false, workflow_valid: false, event_valid: false, data_valid: false, governance_valid: false, trust_valid: false, replay_valid: false, ecosystem_valid: false, matrix_valid: false, evidence_valid: false, gates_valid: false, boundaries_valid: false, readiness_valid: false, failures: freezeArray(["DEPENDENCY_ENGINE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const dependency_valid = verifyHashed(result.dependency_report) && result.dependency_report.programs.length === PROGRAMS.length && result.dependency_report.graph_complete && result.dependency_report.ownership_preserved;
  const interface_valid = verifyHashed(result.interface_report) && result.interface_report.api_compatible && result.interface_report.schemas_compatible && result.interface_report.backward_compatible;
  const workflow_valid = verifyHashed(result.workflow_report) && result.workflow_report.workflow.length === PROGRAMS.length && result.workflow_report.mission_execution && result.workflow_report.trust_propagation && result.workflow_report.deterministic;
  const event_valid = verifyHashed(result.event_report) && result.event_report.event_delivery && result.event_report.event_replay && result.event_report.idempotency;
  const data_valid = verifyHashed(result.data_report) && result.data_report.identity_consistency && result.data_report.lineage_consistency && result.data_report.serialization_compatibility;
  const governance_valid = verifyHashed(result.governance_report) && result.governance_report.tenant_isolation && result.governance_report.fail_closed_behavior && result.governance_report.policy_enforcement;
  const trust_valid = verifyHashed(result.trust_report) && result.trust_report.trust_standing_propagation && result.trust_report.authorization_behavior && result.trust_report.federation_compatibility;
  const replay_valid = verifyHashed(result.replay_report) && result.replay_report.replay_fidelity && result.replay_report.deterministic_execution && result.replay_report.replay_interoperability;
  const ecosystem_valid = verifyHashed(result.ecosystem_report) && result.ecosystem_report.scenarios.length === ECOSYSTEM_SCENARIOS.length && result.ecosystem_report.exercises_complete;
  const matrix_valid = verifyHashed(result.compatibility_matrix) && result.compatibility_matrix.programs.length === PROGRAMS.length && result.compatibility_matrix.dependency_compatibility && result.compatibility_matrix.replay_compatibility;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.immutable && result.evidence.traceable && result.evidence.replayable && result.evidence.lineage_complete;
  const gates_valid = verifyHashed(result.gates) && result.gates.passed;
  const boundaries_valid = verifyHashed(result.boundaries) && !result.boundaries.owns_individual_program_certification && !result.boundaries.owns_program_architecture_modification && !result.boundaries.owns_program_certification_replacement && !result.boundaries.owns_interface_redefinition && !result.boundaries.owns_constitutional_ownership_redefinition;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && dependency_valid && interface_valid && workflow_valid && event_valid && data_valid && governance_valid && trust_valid && replay_valid && ecosystem_valid && matrix_valid && evidence_valid && gates_valid && boundaries_valid && readiness_valid;
  return nested({ valid, outcome: result.readiness.outcome, replay_hash_valid, integrity_hash_valid, dependency_valid, interface_valid, workflow_valid, event_valid, data_valid, governance_valid, trust_valid, replay_valid, ecosystem_valid, matrix_valid, evidence_valid, gates_valid, boundaries_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayProvingCrossProgramIntegrationValidation(result = runProvingCrossProgramIntegrationValidation()): boolean { const replayed = runProvingCrossProgramIntegrationValidation(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateProvingCrossProgramIntegrationValidation(result).valid; }
export function getProvingCrossProgramIntegrationValidationBundle(): IntegrationBundle { const result = runProvingCrossProgramIntegrationValidation(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_interoperability: true, owns_dependency_validation: true, owns_integration_testing: true, owns_ecosystem_validation: true, owns_individual_program_certification: false, owns_program_architecture_modification: false, owns_program_certification_replacement: false, owns_interface_redefinition: false, owns_constitutional_ownership_redefinition: false }), result, validation: validateProvingCrossProgramIntegrationValidation(result) }); }
export const ProvingCrossProgramIntegrationValidationService = Object.freeze({ run: runProvingCrossProgramIntegrationValidation, validate: validateProvingCrossProgramIntegrationValidation, replay: replayProvingCrossProgramIntegrationValidation });
