export const RECOVERY_VERIFICATION_ORCHESTRATOR_ERRORS = {
  RECOVERY_VERIFICATION_FAILED: "RECOVERY_VERIFICATION_FAILED",
  RECOVERY_TRUTH_UNVERIFIABLE: "RECOVERY_TRUTH_UNVERIFIABLE",
  RECOVERY_TRUTH_DIVERGED: "RECOVERY_TRUTH_DIVERGED",
  RECOVERY_TRUTH_DISPUTED: "RECOVERY_TRUTH_DISPUTED",
  RECOVERY_CERTIFICATION_REJECTED: "RECOVERY_CERTIFICATION_REJECTED",
  RECOVERY_CERTIFICATION_QUARANTINED: "RECOVERY_CERTIFICATION_QUARANTINED",
  CONTINUITY_DASHBOARD_READ_FAILED: "CONTINUITY_DASHBOARD_READ_FAILED",
  RECOVERY_VERIFICATION_EVIDENCE_MISSING: "RECOVERY_VERIFICATION_EVIDENCE_MISSING",
  RECOVERY_SIMULATION_EVIDENCE_MISSING: "RECOVERY_SIMULATION_EVIDENCE_MISSING",
  RECOVERY_GOVERNANCE_CONFLICT: "RECOVERY_GOVERNANCE_CONFLICT",
  RECOVERY_REPLAY_DIVERGENCE_DETECTED: "RECOVERY_REPLAY_DIVERGENCE_DETECTED",
} as const;
