import { z } from "zod";
import { type CodexBuildPackage, type GovernanceDecision, type ProjectDecision, type ProjectRequirement, type VaultAuditEvent, type VaultCandidate, type VaultRecord, codexBuildPackageSchema, vaultAuditEventSchema } from "@/src/nuru/vault-contracts";

const lines = z.array(z.string().trim().min(1).max(2_000));
export const codexBuildPackageInputSchema = z.object({ project: z.string().trim().min(1).max(160), objective: z.string().trim().min(1).max(10_000), requirementIds: z.array(z.string().trim().min(1).max(160)).min(1).max(100), expectedFiles: lines.max(200).default([]), interfaces: lines.max(100).default([]), testRefs: lines.min(1).max(100), migrationNotes: lines.max(50).default([]), dependencies: lines.max(100).default([]), exitCriteria: lines.min(1).max(100), verificationCommands: z.array(z.string().trim().min(1).max(500)).min(1).max(50), status: z.enum(["PLANNED", "IN_PROGRESS", "QUALIFIED", "BLOCKED", "RETIRED"]).default("PLANNED"), candidateId: z.string().trim().min(1).max(160), governanceDecisionId: z.string().trim().min(1).max(160), supersedesPackageId: z.string().trim().min(1).max(160).optional() });
export interface CodexBuildPackageStore { readVaultRecords(): Promise<VaultRecord[]>; appendBuildPackage(record: CodexBuildPackage, auditEvent: VaultAuditEvent): Promise<void>; }
export class CodexBuildPackageError extends Error { constructor(public readonly code: "CANDIDATE_NOT_FOUND" | "GOVERNANCE_NOT_APPROVED" | "GOVERNANCE_CANDIDATE_MISMATCH" | "REQUIREMENT_NOT_FOUND" | "PROJECT_MISMATCH" | "ARCHITECTURE_DECISION_NOT_FOUND", message: string) { super(message); this.name = "CodexBuildPackageError"; } }

/** Creates a constrained implementation unit only from governed, current project-memory records. */
export const NuruCodexBuildPackageService = {
  async create(rawInput: z.input<typeof codexBuildPackageInputSchema>, store: CodexBuildPackageStore): Promise<CodexBuildPackage> {
    const input = codexBuildPackageInputSchema.parse(rawInput); const records = await store.readVaultRecords();
    const candidate = records.find((record): record is VaultCandidate => record.kind === "CANDIDATE" && record.id === input.candidateId); if (!candidate) throw new CodexBuildPackageError("CANDIDATE_NOT_FOUND", "The package candidate was not found.");
    const governance = records.find((record): record is GovernanceDecision => record.kind === "GOVERNANCE_DECISION" && record.id === input.governanceDecisionId); if (!governance || governance.outcome !== "APPROVED" || !governance.humanApprovalId) throw new CodexBuildPackageError("GOVERNANCE_NOT_APPROVED", "A build package requires retained human governance approval."); if (governance.candidateId !== candidate.id) throw new CodexBuildPackageError("GOVERNANCE_CANDIDATE_MISMATCH", "The governance decision must approve the package candidate.");
    const requirements = input.requirementIds.map((id) => records.find((record): record is ProjectRequirement => record.kind === "PROJECT_REQUIREMENT" && record.id === id && record.status === "CURRENT")); if (requirements.some((record) => !record)) throw new CodexBuildPackageError("REQUIREMENT_NOT_FOUND", "Every build-package requirement must be current and available."); if (requirements.some((record) => record?.project !== input.project)) throw new CodexBuildPackageError("PROJECT_MISMATCH", "Every package requirement must belong to the package project.");
    const architectureDecisionIds = [...new Set(requirements.flatMap((record) => record?.projectDecisionId ?? []))]; const decisions = architectureDecisionIds.map((id) => records.find((record): record is ProjectDecision => record.kind === "PROJECT_DECISION" && record.id === id && record.status === "CURRENT")); if (decisions.some((record) => !record)) throw new CodexBuildPackageError("ARCHITECTURE_DECISION_NOT_FOUND", "Every linked architecture decision must be current and available.");
    const previous = input.supersedesPackageId ? records.filter((record): record is CodexBuildPackage => record.kind === "CODEX_BUILD_PACKAGE" && record.id === input.supersedesPackageId).at(-1) : undefined; if (previous && previous.project !== input.project) throw new CodexBuildPackageError("PROJECT_MISMATCH", "A package may supersede only a package in the same project.");
    const record = codexBuildPackageSchema.parse({ schemaVersion: candidate.schemaVersion, id: `codex-build-package:${crypto.randomUUID()}`, kind: "CODEX_BUILD_PACKAGE", classification: candidate.classification, createdAt: governance.decidedAt, correlationId: candidate.correlationId, project: input.project, objective: input.objective, requirementIds: input.requirementIds, architectureDecisionIds, expectedFiles: input.expectedFiles, interfaces: input.interfaces, testRefs: input.testRefs, migrationNotes: input.migrationNotes, dependencies: input.dependencies, exitCriteria: input.exitCriteria, verificationCommands: input.verificationCommands, status: input.status, candidateId: candidate.id, governanceDecisionId: governance.id, version: (previous?.version ?? 0) + 1, ...(previous ? { supersedesPackageId: previous.id } : {}) });
    const audit = vaultAuditEventSchema.parse({ schemaVersion: record.schemaVersion, id: `audit:${record.id}:build-package`, kind: "AUDIT_EVENT", classification: record.classification, createdAt: record.createdAt, correlationId: record.correlationId, eventType: "DECISION_RECORDED", actor: "nuru.codex-packages.v1", resourceId: record.id, occurredAt: record.createdAt, reason: previous ? `Recorded successor to build package ${previous.id}.` : "Recorded human-approved Codex build package." }); await store.appendBuildPackage(record, audit); return record;
  },
  async list(project: string | undefined, store: Pick<CodexBuildPackageStore, "readVaultRecords">) { return (await store.readVaultRecords()).filter((record): record is CodexBuildPackage => record.kind === "CODEX_BUILD_PACKAGE" && (!project || record.project === project)).sort((left, right) => right.createdAt.localeCompare(left.createdAt)); },
};
