import { z } from "zod";
import { type CodexBuildPackage, type CodexImplementationLedger, type VaultAuditEvent, type VaultRecord, codexImplementationLedgerSchema, vaultAuditEventSchema } from "@/src/nuru/vault-contracts";

export const implementationLedgerInputSchema = z.object({ buildPackageId: z.string().trim().min(1).max(160), branch: z.string().trim().min(1).max(500), commit: z.string().trim().min(1).max(160).optional(), filesChanged: z.array(z.string().trim().min(1).max(2_000)).max(1_000).default([]), commandsExecuted: z.array(z.string().trim().min(1).max(2_000)).min(1).max(500), testsExecuted: z.array(z.string().trim().min(1).max(2_000)).max(500).default([]), migrationStatus: z.enum(["NOT_REQUIRED", "APPLIED", "PENDING", "FAILED"]), qualificationStatus: z.enum(["QUALIFIED", "PARTIAL", "BLOCKED", "FAILED"]), knownLimitations: z.array(z.string().trim().min(1).max(2_000)).max(100).default([]), recordedBy: z.string().trim().min(1).max(160) });
export interface ImplementationLedgerStore { readVaultRecords(): Promise<VaultRecord[]>; appendImplementationLedger(record: CodexImplementationLedger, auditEvent: VaultAuditEvent): Promise<void>; }
export class ImplementationLedgerError extends Error { constructor(message: string) { super(message); this.name = "ImplementationLedgerError"; } }
export const NuruImplementationLedgerService = {
  async record(raw: z.input<typeof implementationLedgerInputSchema>, store: ImplementationLedgerStore) {
    const input = implementationLedgerInputSchema.parse(raw); const records = await store.readVaultRecords(); const packageRecord = records.find((record): record is CodexBuildPackage => record.kind === "CODEX_BUILD_PACKAGE" && record.id === input.buildPackageId); if (!packageRecord) throw new ImplementationLedgerError("The governed build package was not found.");
    const record = codexImplementationLedgerSchema.parse({ schemaVersion: packageRecord.schemaVersion, id: `implementation-ledger:${crypto.randomUUID()}`, kind: "CODEX_IMPLEMENTATION_LEDGER", classification: packageRecord.classification, createdAt: new Date().toISOString(), correlationId: packageRecord.correlationId, ...input }); const audit = vaultAuditEventSchema.parse({ schemaVersion: record.schemaVersion, id: `audit:${record.id}:implementation`, kind: "AUDIT_EVENT", classification: record.classification, createdAt: record.createdAt, correlationId: record.correlationId, eventType: "DECISION_RECORDED", actor: record.recordedBy, resourceId: record.id, occurredAt: record.createdAt, reason: `Recorded ${record.qualificationStatus.toLowerCase()} implementation evidence for ${packageRecord.id}.` }); await store.appendImplementationLedger(record, audit); return record;
  },
  async list(buildPackageId: string | undefined, store: Pick<ImplementationLedgerStore, "readVaultRecords">) { return (await store.readVaultRecords()).filter((record): record is CodexImplementationLedger => record.kind === "CODEX_IMPLEMENTATION_LEDGER" && (!buildPackageId || record.buildPackageId === buildPackageId)).sort((left, right) => right.createdAt.localeCompare(left.createdAt)); },
};
