import { z } from "zod";
import { nuruKnowledgeRepository } from "@/src/server/repositories/nuru-knowledge-repository";
import { NuruCurationPipeline } from "@/src/server/services/nuru-curation-pipeline";
import { sourceSchema } from "@/src/nuru/domain";
import { AppError } from "@/src/server/api/errors";
export const nuruCurationSubmissionSchema = z.object({ title: z.string().trim().min(3).max(180), content: z.string().trim().min(20).max(12000), project: z.string().trim().max(120).optional(), source: sourceSchema, idempotencyKey: z.string().uuid() }); export type NuruCurationSubmission = z.infer<typeof nuruCurationSubmissionSchema>;
type Receipt = { id: string; actorId: string; idempotencyKey: string; status: string; request: unknown; correlationId: string | null; proposalId: string | null; queueId: string | null; result: unknown; error: string | null; createdAt: Date; updatedAt: Date };
const receiptRepository = nuruKnowledgeRepository.nuruCurationSubmissionReceipt as unknown as { create(args: unknown): Promise<Receipt>; findUnique(args: unknown): Promise<Receipt | null>; update(args: unknown): Promise<Receipt> };
const duplicate = (error: unknown) => typeof error === "object" && error !== null && "code" in error && (error as { code?: string }).code === "P2002";
function recoveryView(receipt: Receipt) { return { id: receipt.id, status: receipt.status, actorId: receipt.actorId, correlationId: receipt.correlationId, proposalId: receipt.proposalId, queueId: receipt.queueId, error: receipt.error, canResumeAutomatically: false, reason: receipt.status !== "REQUIRES_RECOVERY" ? "This submission is not awaiting recovery." : receipt.proposalId || receipt.queueId ? "Durable workflow references exist; reconcile them before retrying." : "No durable workflow references were recorded; operator review is required before a retry.", createdAt: receipt.createdAt, updatedAt: receipt.updatedAt }; }
/** Claims a caller key before orchestration, making sequential and concurrent retries return one durable submission. */
export const NuruCurationSubmissionService = { async submit(raw: NuruCurationSubmission, actorId: string) { const input = nuruCurationSubmissionSchema.parse(raw), correlationId = `nuru-submission:${crypto.randomUUID()}`; let receipt: Receipt; try { receipt = await receiptRepository.create({ data: { actorId, idempotencyKey: input.idempotencyKey, status: "PROCESSING", request: input, correlationId } }); } catch (error) { if (!duplicate(error)) throw error; const existing = await receiptRepository.findUnique({ where: { actorId_idempotencyKey: { actorId, idempotencyKey: input.idempotencyKey } } }); if (!existing) throw error; return { replayed: true, receipt: existing, result: existing.result }; }
  try { const result = await NuruCurationPipeline.run({ title: input.title, content: input.content, project: input.project, source: input.source, correlationId, humanApproved: false, approvedBy: actorId }); const updated = await receiptRepository.update({ where: { id: receipt.id }, data: { status: result.status === "HUMAN_REVIEW_REQUIRED" ? "COMPLETE" : "REQUIRES_RECOVERY", proposalId: "proposal" in result && result.proposal ? result.proposal.id : null, queueId: "queue" in result && result.queue && typeof result.queue === "object" && result.queue !== null && "id" in result.queue ? String(result.queue.id) : null, result } }); return { replayed: false, receipt: updated, result }; } catch (error) { const updated = await receiptRepository.update({ where: { id: receipt.id }, data: { status: "REQUIRES_RECOVERY", error: error instanceof Error ? error.message : "Unknown submission failure" } }); return { replayed: false, receipt: updated, result: null }; }
}, async inspect(receiptId: string, actorId: string) { const receipt = await receiptRepository.findUnique({ where: { id: receiptId } }); if (!receipt) throw new AppError(404, "submission_not_found", "Nuru submission receipt not found."); if (receipt.actorId !== actorId) throw new AppError(403, "forbidden", "Only the submitting governor may inspect this receipt."); return { receipt: recoveryView(receipt), request: nuruCurationSubmissionSchema.parse(receipt.request) }; } };
