import { describe, expect, it } from "vitest";

import { evaluateRuntimeConstitutionalResilience } from "@/services/resilience/runtimeConstitutionalResilience";

describe("evaluateRuntimeConstitutionalResilience", () => {
  it("freezes when convergence and replay evidence collapse", () => {
    const result = evaluateRuntimeConstitutionalResilience({
      runtimeContinuityState: "UNVERIFIABLE",
      continuityConfidence: 0.2,
      operationalStability: "critical",
      degradedSystems: ["replay"],
      activeRecoveries: [{ executionId: "exec_1" }],
      pendingApprovals: [],
      blockedRecoveries: [],
      quarantinedExecutions: [],
      replayVerificationState: "DIVERGED",
      replayDivergenceCount: 2,
      leaseConflicts: [],
      auditHistory: [{ id: "audit_1" }],
      governanceDisputes: [],
      certificationState: "REJECTED",
      simulationOutcomes: [],
      continuityRiskScore: 88,
      stewardship: {
        state: "DISPUTED",
        confidence: 0.3,
        shouldFreeze: true,
        shouldContain: true,
        shouldEscalate: true,
        governanceBlocked: true,
        verificationBlocked: true,
        stabilizationStatus: "degrading",
        survivabilityScore: 0.2,
        collapseRisk: "critical",
        reasoning: [],
        evidence: ["audit_1"],
      },
      operationalStabilityAssessment: {
        operationalState: "CRITICAL",
        survivabilityScore: 0.18,
        degradationRate: 0.81,
        recoveryPressure: 0.72,
        escalationPressure: 0.76,
        continuityConfidence: 0.22,
        unstableSubsystems: ["replay"],
        stabilizationRequired: true,
        containmentRecommended: true,
        lockdownRecommended: true,
        replayInstabilityScore: 0.9,
        staleExecutionSpread: 0.3,
        dependencyInstabilityScore: 0.5,
        operatorInterventionPressure: 0.4,
        recoverySuccessConfidence: 0.1,
        trend: "COLLAPSING",
        confidence: 0.25,
        reasons: [],
        disputed: true,
        timestamp: "2026-05-09T00:00:00.000Z",
      },
      escalationCoordination: {
        escalationId: "esc_1",
        escalationType: "emergency",
        escalationState: "FROZEN",
        escalationSeverity: "CATASTROPHIC",
        escalationLineageId: "lineage_1",
        conflictingEscalations: [],
        requiresContainment: true,
        requiresOperatorVisibility: true,
        frozen: true,
        blocked: false,
        recommendedActions: [],
        confidence: 0.2,
        evidenceCount: 1,
        reason: "emergency",
        source: "ops",
        timestamp: "2026-05-09T00:00:00.000Z",
      },
      continuityConvergence: {
        converged: false,
        state: "FAILED",
        divergenceScore: 0.9,
        divergenceReasons: ["replay_divergence"],
        requiresContainment: true,
        requiresEscalation: true,
        requiresFreeze: true,
        continuityConfidence: 0.15,
        replayConfidence: 0.1,
        survivabilityConfidence: 0.12,
        escalationStabilityConfidence: 0.2,
        affectedExecutions: ["exec_1"],
        affectedSubsystems: ["replay"],
        orphanedOperations: ["orphan_1"],
        staleOwnershipClaims: ["claim_1"],
        unresolvedDisputes: [],
        unstableDependencies: ["replay"],
        evidence: ["audit_1"],
        timestamp: "2026-05-09T00:00:00.000Z",
      },
      recoveryPrioritization: null,
      generatedAt: "2026-05-09T00:00:00.000Z",
    } as never);

    expect(result.assessment.requiresFreeze).toBe(true);
    expect(result.assessment.resilienceState).toMatch(/FROZEN|DISPUTED/);
  });
});
