import { getSessionUser } from "@/src/lib/auth";
import { AppError } from "@/src/server/api/errors";
import { apiError, apiSuccess } from "@/src/server/api/response";
import { requireWorkspaceManager } from "@/src/server/auth/permissions";
import { EvaluationArtifactService, EvaluationLifecycleService, PrismaEvaluationArtifactRepository, PrismaLearningAuditLedger } from "@/services/learning-constitution";
import type { Evaluation, EvaluationLifecycleEvent, EvaluationLifecycleState } from "@/types/learning-constitution";
export const dynamic = "force-dynamic";
const states = new Set<EvaluationLifecycleState>(["READY", "RUNNING", "SCORING", "VALIDATING", "COMPLETED"]);
export async function POST(request: Request, context: { params: Promise<{ evaluationId: string }> }) { try { const user = await getSessionUser(); if (!user) throw new AppError(401, "unauthorized", "Authentication required."); if (!user.workspaceId || user.workspaceId === "default") throw new AppError(403, "workspace_required", "Workspace membership is required."); await requireWorkspaceManager({ userId: user.id, userRole: user.role, workspaceId: user.workspaceId }); const { evaluationId } = await context.params; const { nextState } = await request.json() as { nextState?: EvaluationLifecycleState }; if (!nextState || !states.has(nextState)) throw new AppError(400, "evaluation_state_invalid", "A valid next evaluation state is required."); const repo = new PrismaEvaluationArtifactRepository(user.workspaceId); const artifacts = await repo.listWorkspaceArtifacts(); const evaluation = artifacts.find((artifact) => artifact.artifactType === "EVALUATION" && (artifact.payload as Evaluation).evaluationId === evaluationId)?.payload as Evaluation | undefined; if (!evaluation) throw new AppError(404, "evaluation_missing", "Evaluation was not found."); const events = artifacts.filter((artifact) => artifact.artifactType === "LIFECYCLE" && artifact.subjectId === evaluationId).map((artifact) => artifact.payload as EvaluationLifecycleEvent); const previousState = events.at(-1)?.nextState ?? null; new EvaluationLifecycleService().transition(previousState, nextState); const event = await new EvaluationArtifactService(repo, new PrismaLearningAuditLedger(user.workspaceId)).transition(evaluationId, previousState, nextState, { actorId: `user:${user.id}`, actorType: "HUMAN" }, new Date().toISOString(), user.workspaceId, `evaluation:${evaluationId}`); return apiSuccess({ lifecycle: event }); } catch (error) { return apiError(error, "Unable to transition evaluation."); } }
