import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runProvingEcosystemReadinessAssessment, validateProvingEcosystemReadinessAssessment } from "@/services/proving-ecosystem-readiness-assessment";
import type { FederationBundle, FederationExerciseType, FederationFailure, FederationInput, FederationMetric, FederationOutcome, FederationResult, FederationScenario, FederationValidation } from "@/types/proving-ecosystem-validation-federation";

const VERSION = "proving-ecosystem-validation-federation/v6.17" as const;
const IDENTIFIER = "ProvingEcosystemValidationFederation" as const;
const EXERCISES = Object.freeze<FederationExerciseType[]>(["ECOSYSTEM_EXERCISE", "FEDERATION_REHEARSAL", "DISTRIBUTED_SIMULATION", "MULTI_REGION_PROVING", "MULTI_TENANT_PROVING", "CROSS_PROGRAM_PROVING", "CONSTITUTIONAL_VALIDATION", "TRUST_FEDERATION_VALIDATION", "OPERATIONAL_FEDERATION_DRILL", "ECOSYSTEM_RECOVERY_EXERCISE"]);
const METRICS = Object.freeze<FederationMetric[]>(["FEDERATION_HEALTH", "SYNCHRONIZATION_LATENCY", "FEDERATION_AVAILABILITY", "REPLAY_DETERMINISM", "TENANT_ISOLATION_SUCCESS", "GOVERNANCE_CONSISTENCY", "EVIDENCE_SYNCHRONIZATION", "INTEROPERABILITY_SUCCESS", "DISTRIBUTED_EXECUTION_ACCURACY", "CONSTITUTIONAL_COMPLIANCE"]);
let readinessBaseline: ReturnType<typeof runProvingEcosystemReadinessAssessment> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly FederationFailure[], failure: FederationFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: FederationScenario): FederationFailure | undefined { return scenario === "BASELINE" || scenario === "READY_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function finalOutcome(failures: readonly FederationFailure[], scenario: FederationScenario): FederationOutcome {
  if (has(failures, "TENANT_ISOLATION_VIOLATED") || has(failures, "FEDERATED_EVIDENCE_INTEGRITY_INVALID") || has(failures, "GOVERNANCE_CONSISTENCY_INVALID") || has(failures, "AUTHORITY_ENFORCEMENT_INVALID") || has(failures, "POLICY_ENFORCEMENT_INVALID") || has(failures, "OPERATOR_SUPREMACY_VIOLATED") || has(failures, "FAIL_CLOSED_NOT_ENFORCED") || has(failures, "TRUST_AUTHORITY_SUPERSEDED")) return "FAIL_CLOSED";
  if (has(failures, "P6_16_READINESS_INVALID") || has(failures, "FEDERATION_REPLAY_INVALID") || has(failures, "FEDERATION_QUALIFICATION_PACKAGE_INCOMPLETE") || has(failures, "ECOSYSTEM_QUALIFICATION_READINESS_FAILED")) return "NOT_READY";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_READY";
  if (scenario === "READY_WITH_OBSERVATIONS") return "READY_WITH_OBSERVATIONS";
  return "FEDERATION_READY";
}
function resultReplayHash(result: Omit<FederationResult, "replay_hash" | "integrity_hash">): string { return hash({ architecture: result.architecture.integrity_hash, registry: result.registry.integrity_hash, tenant: result.multi_tenant_report.integrity_hash, matrix: result.cross_program_matrix.integrity_hash, exercise: result.exercise_report.integrity_hash, distributed: result.distributed_scenario_report.integrity_hash, replay: result.replay_report.integrity_hash, evidence: result.evidence.integrity_hash, governance: result.governance_report.integrity_hash, trust: result.trust_report.integrity_hash, resilience: result.resilience_report.integrity_hash, qualification: result.qualification_package.integrity_hash, metrics: result.metrics_report.integrity_hash, decision: result.decision.integrity_hash, gates: result.gates.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<FederationResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.readiness.outcome, replay_hash: result.replay_hash }); }

export function runProvingEcosystemValidationFederation(input: FederationInput = {}): FederationResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<FederationFailure>(direct ? [direct] : []);
  readinessBaseline ??= runProvingEcosystemReadinessAssessment();
  const readinessInvalid = !validateProvingEcosystemReadinessAssessment(readinessBaseline).valid || has(scenarioFailures, "P6_16_READINESS_INVALID");
  const failures = freezeArray([...new Set([...scenarioFailures, ...(readinessInvalid ? ["P6_16_READINESS_INVALID" as const] : [])])]);
  const architectureOk = !has(failures, "FEDERATION_ARCHITECTURE_MISSING") && !has(failures, "FEDERATION_TOPOLOGY_INVALID") && !readinessInvalid;
  const registryOk = !has(failures, "FEDERATION_REGISTRY_MISSING") && !has(failures, "FEDERATION_PARTICIPANT_IDENTITY_UNVERIFIED") && !has(failures, "FEDERATION_AUTHORIZATION_MISSING");
  const tenantOk = !has(failures, "TENANT_ISOLATION_VIOLATED") && !has(failures, "CROSS_TENANT_AUTHORIZATION_INVALID");
  const crossProgramOk = !has(failures, "CROSS_PROGRAM_COMPATIBILITY_INVALID") && !has(failures, "QUALIFIED_INTERFACE_MISSING");
  const exerciseOk = !has(failures, "FEDERATION_EXERCISE_FRAMEWORK_MISSING");
  const distributedOk = !has(failures, "DISTRIBUTED_SCENARIO_EXECUTION_FAILED") && !has(failures, "SCENARIO_SYNCHRONIZATION_FAILED");
  const replayOk = !has(failures, "FEDERATION_REPLAY_INVALID") && !has(failures, "REPLAY_LINEAGE_INCOMPLETE");
  const evidenceOk = !has(failures, "EVIDENCE_SYNCHRONIZATION_FAILED") && !has(failures, "FEDERATED_EVIDENCE_INTEGRITY_INVALID");
  const governanceOk = !has(failures, "GOVERNANCE_CONSISTENCY_INVALID") && !has(failures, "AUTHORITY_ENFORCEMENT_INVALID") && !has(failures, "POLICY_ENFORCEMENT_INVALID") && !has(failures, "OPERATOR_SUPREMACY_VIOLATED") && !has(failures, "FAIL_CLOSED_NOT_ENFORCED");
  const trustOk = !has(failures, "TRUST_FEDERATION_COMPATIBILITY_INVALID") && !has(failures, "TRUST_AUTHORITY_SUPERSEDED");
  const resilienceOk = !has(failures, "FEDERATION_RESILIENCE_VALIDATION_FAILED") && !has(failures, "PARTITION_HANDLING_FAILED");
  const qualificationOk = !has(failures, "FEDERATION_QUALIFICATION_PACKAGE_INCOMPLETE") && !has(failures, "ECOSYSTEM_QUALIFICATION_READINESS_FAILED");
  const outcome = finalOutcome(failures, scenario);
  const architecture = nested({ architecture_id: architectureOk ? `architecture:p6.17:federation:${input.seed ?? "canonical"}` : "", topology_defined: architectureOk, proving_federation: architectureOk, execution_federation: architectureOk, environment_federation: architectureOk, deterministic: architectureOk });
  const registry = nested({ registry_id: registryOk ? "registry:p6.17:federation-environments" : "", members: registryOk ? freezeArray(["tenant:alpha:us-east", "tenant:beta:us-west", "program:1", "program:2", "program:3", "program:4", "program:5", "program:6"]) : freezeArray<string>([]), federation_identities_verified: registryOk, topology_registered: registryOk, constitutional_authorization: registryOk, environment_catalog_complete: registryOk });
  const multi_tenant_report = nested({ report_id: tenantOk ? "report:p6.17:multi-tenant" : "", tenants: tenantOk ? freezeArray(["tenant:alpha", "tenant:beta"]) : freezeArray<string>([]), tenant_isolation: tenantOk, tenant_independence: tenantOk, shared_infrastructure_validated: tenantOk, identity_isolation: tenantOk, cross_tenant_proving_authorized: tenantOk });
  const cross_program_matrix = nested({ matrix_id: crossProgramOk ? "matrix:p6.17:cross-program" : "", programs: crossProgramOk ? freezeArray(["P1", "P2", "P3", "P4", "P5", "P6"]) : freezeArray<string>([]), capability_interoperability: crossProgramOk, dependency_correctness: crossProgramOk, interface_compatibility: crossProgramOk, evidence_compatibility: crossProgramOk, qualified_contracts_only: crossProgramOk });
  const exercise_report = nested({ report_id: exerciseOk ? "report:p6.17:federation-exercises" : "", exercise_types: exerciseOk ? EXERCISES : freezeArray<FederationExerciseType>([]), ecosystem_drills: exerciseOk, distributed_rehearsals: exerciseOk, coordinated_proving: exerciseOk, operational_federation_drills: exerciseOk });
  const distributed_scenario_report = nested({ report_id: distributedOk ? "report:p6.17:distributed-scenarios" : "", synchronized_execution: distributedOk, distributed_coordination: distributedOk, coordinated_missions: distributedOk, scenario_federation: distributedOk, execution_accuracy: distributedOk ? 0.99 : 0 });
  const replay_report = nested({ report_id: replayOk ? "report:p6.17:federation-replay" : "", distributed_replay: replayOk, replay_synchronization: replayOk, replay_lineage_complete: replayOk, deterministic_replay: replayOk && architectureOk, reproducible_outcomes: replayOk });
  const evidence = nested({ evidence_id: evidenceOk ? "evidence:p6.17:federated-proving" : "", immutable: evidenceOk, cryptographically_verifiable: evidenceOk, synchronized_across_members: evidenceOk, traceable_to_originating_exercise: evidenceOk && exerciseOk, lineage_federated: evidenceOk && replayOk, reconciled: evidenceOk });
  const governance_report = nested({ report_id: governanceOk ? "report:p6.17:governance-validation" : "", constitutional_compliance: governanceOk, authority_enforcement: governanceOk, policy_enforcement: governanceOk, governance_consistency: governanceOk, operator_supremacy: governanceOk, fail_closed_behavior: governanceOk });
  const trust_report = nested({ report_id: trustOk ? "report:p6.17:trust-federation-compatibility" : "", trust_federation_consumed: trustOk, trust_standing_validated: trustOk, trust_decisions_respected: trustOk, trust_authority_preserved: trustOk, proving_validates_behavior_only: trustOk });
  const resilience_report = nested({ report_id: resilienceOk ? "report:p6.17:federation-resilience" : "", node_failure_resilience: resilienceOk, partition_handling: resilienceOk, degraded_federation: resilienceOk, recovery_continuity: resilienceOk, operational_resilience: resilienceOk });
  const qualification_package = nested({ package_id: qualificationOk ? "package:p6.17:federation-qualification" : "", interoperability_complete: qualificationOk && crossProgramOk, governance_complete: qualificationOk && governanceOk, replay_complete: qualificationOk && replayOk, evidence_complete: qualificationOk && evidenceOk, resilience_complete: qualificationOk && resilienceOk, cross_program_validation_complete: qualificationOk && crossProgramOk, qualification_ready: qualificationOk && outcome !== "NOT_READY" && outcome !== "FAIL_CLOSED" });
  const metrics_report = nested({ report_id: "metrics:p6.17:federation", metrics: METRICS, federation_health: architectureOk ? 0.98 : 0.4, synchronization_latency_ms: distributedOk ? 42 : 999, federation_availability: resilienceOk ? 0.999 : 0.5, replay_determinism: replayOk ? 1 : 0, tenant_isolation_success: tenantOk ? 1 : 0, governance_consistency: governanceOk ? 1 : 0, evidence_synchronization: evidenceOk ? 1 : 0, interoperability_success: crossProgramOk ? 1 : 0, distributed_execution_accuracy: distributedOk ? 0.99 : 0, constitutional_compliance: governanceOk ? 1 : 0 });
  const decision = nested({ decision_id: "decision:p6.17:federation", outcome, qualification_authorized: outcome === "FEDERATION_READY" || outcome === "READY_WITH_OBSERVATIONS", federation_execution_authorized: outcome === "FEDERATION_READY" || outcome === "READY_WITH_OBSERVATIONS" || outcome === "CONDITIONALLY_READY", trust_authority_preserved: trustOk, fail_closed: outcome === "FAIL_CLOSED" || outcome === "NOT_READY", rationale: freezeArray(outcome === "FEDERATION_READY" ? ["ecosystem proving federation validated"] : outcome === "READY_WITH_OBSERVATIONS" ? ["federation validated with nonblocking observations"] : outcome === "CONDITIONALLY_READY" ? ["federation follow-up controls required"] : outcome === "FAIL_CLOSED" ? ["constitutional, isolation, evidence, governance, or trust authority failure"] : ["federation qualification readiness blocked"]) });
  const gates = nested({ gate_id: "P6.17-FED-GATES", registration_gate: registryOk, tenant_isolation_gate: tenantOk, cross_program_gate: crossProgramOk, replay_gate: replayOk, evidence_gate: evidenceOk, governance_gate: governanceOk, trust_gate: trustOk, qualification_gate: qualificationOk, resilience_gate: resilienceOk, passed: false });
  const finalGates = nested({ ...gates, passed: gates.registration_gate && gates.tenant_isolation_gate && gates.cross_program_gate && gates.replay_gate && gates.evidence_gate && gates.governance_gate && gates.trust_gate && gates.qualification_gate && gates.resilience_gate });
  const derivedFailures = freezeArray([...new Set([...failures, ...(!architectureOk ? ["FEDERATION_ARCHITECTURE_MISSING" as const] : []), ...(!registryOk ? ["FEDERATION_REGISTRY_MISSING" as const] : []), ...(!tenantOk ? ["TENANT_ISOLATION_VIOLATED" as const] : []), ...(!crossProgramOk ? ["CROSS_PROGRAM_COMPATIBILITY_INVALID" as const] : []), ...(!exerciseOk ? ["FEDERATION_EXERCISE_FRAMEWORK_MISSING" as const] : []), ...(!distributedOk ? ["DISTRIBUTED_SCENARIO_EXECUTION_FAILED" as const] : []), ...(!replayOk ? ["FEDERATION_REPLAY_INVALID" as const] : []), ...(!evidenceOk ? ["EVIDENCE_SYNCHRONIZATION_FAILED" as const] : []), ...(!governanceOk ? ["GOVERNANCE_CONSISTENCY_INVALID" as const] : []), ...(!trustOk ? ["TRUST_FEDERATION_COMPATIBILITY_INVALID" as const] : []), ...(!resilienceOk ? ["FEDERATION_RESILIENCE_VALIDATION_FAILED" as const] : []), ...(!qualificationOk ? ["FEDERATION_QUALIFICATION_PACKAGE_INCOMPLETE" as const] : [])])]);
  const readiness = nested({ readiness_id: "P6.17-ECOSYSTEM-VALIDATION-FEDERATION-001", outcome, phase_ready: outcome === "FEDERATION_READY" || outcome === "READY_WITH_OBSERVATIONS", architecture_ready: architectureOk, registry_ready: registryOk, multi_tenant_ready: tenantOk, cross_program_ready: crossProgramOk, exercise_ready: exerciseOk, distributed_execution_ready: distributedOk, replay_ready: replayOk, evidence_ready: evidenceOk, governance_ready: governanceOk, trust_ready: trustOk, resilience_ready: resilienceOk, qualification_ready: qualification_package.qualification_ready, metrics_ready: metrics_report.metrics.length === METRICS.length, gates_passed: finalGates.passed, failures: derivedFailures });
  const base: Omit<FederationResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, ecosystem_readiness_ref: "proving-ecosystem-readiness-assessment/v6.16", architecture, registry, multi_tenant_report, cross_program_matrix, exercise_report, distributed_scenario_report, replay_report, evidence, governance_report, trust_report, resilience_report, qualification_package, metrics_report, decision, gates: finalGates, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateProvingEcosystemValidationFederation(result?: FederationResult): FederationValidation {
  if (!result) return nested({ valid: false, outcome: "NOT_READY" as const, replay_hash_valid: false, integrity_hash_valid: false, architecture_valid: false, registry_valid: false, multi_tenant_valid: false, cross_program_valid: false, exercise_valid: false, distributed_execution_valid: false, replay_valid: false, evidence_valid: false, governance_valid: false, trust_valid: false, resilience_valid: false, qualification_valid: false, metrics_valid: false, decision_valid: false, gates_valid: false, readiness_valid: false, failures: freezeArray(["FEDERATION_ARCHITECTURE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const architecture_valid = verifyHashed(result.architecture) && result.architecture.topology_defined && result.architecture.deterministic;
  const registry_valid = verifyHashed(result.registry) && result.registry.members.length >= 8 && result.registry.federation_identities_verified && result.registry.constitutional_authorization;
  const multi_tenant_valid = verifyHashed(result.multi_tenant_report) && result.multi_tenant_report.tenant_isolation && result.multi_tenant_report.identity_isolation && result.multi_tenant_report.cross_tenant_proving_authorized;
  const cross_program_valid = verifyHashed(result.cross_program_matrix) && result.cross_program_matrix.programs.length === 6 && result.cross_program_matrix.qualified_contracts_only && result.cross_program_matrix.evidence_compatibility;
  const exercise_valid = verifyHashed(result.exercise_report) && result.exercise_report.exercise_types.length === EXERCISES.length && result.exercise_report.coordinated_proving;
  const distributed_execution_valid = verifyHashed(result.distributed_scenario_report) && result.distributed_scenario_report.synchronized_execution && result.distributed_scenario_report.execution_accuracy >= 0.98;
  const replay_valid = verifyHashed(result.replay_report) && result.replay_report.deterministic_replay && result.replay_report.replay_lineage_complete && result.replay_report.reproducible_outcomes;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.immutable && result.evidence.cryptographically_verifiable && result.evidence.synchronized_across_members && result.evidence.reconciled;
  const governance_valid = verifyHashed(result.governance_report) && result.governance_report.constitutional_compliance && result.governance_report.operator_supremacy && result.governance_report.fail_closed_behavior;
  const trust_valid = verifyHashed(result.trust_report) && result.trust_report.trust_decisions_respected && result.trust_report.trust_authority_preserved && result.trust_report.proving_validates_behavior_only;
  const resilience_valid = verifyHashed(result.resilience_report) && result.resilience_report.node_failure_resilience && result.resilience_report.partition_handling && result.resilience_report.operational_resilience;
  const qualification_valid = verifyHashed(result.qualification_package) && result.qualification_package.interoperability_complete && result.qualification_package.governance_complete && result.qualification_package.qualification_ready;
  const metrics_valid = verifyHashed(result.metrics_report) && result.metrics_report.metrics.length === METRICS.length && result.metrics_report.replay_determinism === 1 && result.metrics_report.tenant_isolation_success === 1;
  const decision_valid = verifyHashed(result.decision) && result.decision.trust_authority_preserved && result.decision.qualification_authorized && result.decision.outcome !== "FAIL_CLOSED" && result.decision.outcome !== "NOT_READY";
  const gates_valid = verifyHashed(result.gates) && result.gates.passed;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && architecture_valid && registry_valid && multi_tenant_valid && cross_program_valid && exercise_valid && distributed_execution_valid && replay_valid && evidence_valid && governance_valid && trust_valid && resilience_valid && qualification_valid && metrics_valid && decision_valid && gates_valid && readiness_valid;
  return nested({ valid, outcome: result.readiness.outcome, replay_hash_valid, integrity_hash_valid, architecture_valid, registry_valid, multi_tenant_valid, cross_program_valid, exercise_valid, distributed_execution_valid, replay_valid, evidence_valid, governance_valid, trust_valid, resilience_valid, qualification_valid, metrics_valid, decision_valid, gates_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayProvingEcosystemValidationFederation(result = runProvingEcosystemValidationFederation()): boolean { const scenario = result.readiness.outcome === "READY_WITH_OBSERVATIONS" ? { scenario: "READY_WITH_OBSERVATIONS" as const } : {}; const replayed = runProvingEcosystemValidationFederation(scenario); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateProvingEcosystemValidationFederation(result).valid; }
export function getProvingEcosystemValidationFederationBundle(): FederationBundle { const result = runProvingEcosystemValidationFederation(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_federation_proving: true, owns_multi_tenant_proving: true, owns_ecosystem_federation: true, owns_cross_program_validation: true, owns_federation_exercises: true, preserves_trust_authority: true }), result, validation: validateProvingEcosystemValidationFederation(result) }); }
export const ProvingEcosystemValidationFederationService = Object.freeze({ run: runProvingEcosystemValidationFederation, validate: validateProvingEcosystemValidationFederation, replay: replayProvingEcosystemValidationFederation });
