import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runEcosystemPortfolioGovernance, validateEcosystemPortfolioGovernance } from "@/services/ecosystem-portfolio-governance";
import { runTrustConstitutionalFoundation, validateTrustConstitutionalFoundation } from "@/services/trust-constitutional-foundation";
import type { TrustArchitectureAlignmentBundle, TrustArchitectureAlignmentFailure, TrustArchitectureAlignmentInput, TrustArchitectureAlignmentOutcome, TrustArchitectureAlignmentRecord, TrustArchitectureAlignmentResult, TrustArchitectureAlignmentScenario, TrustArchitectureAlignmentValidation, TrustLayer, TrustLifecycleState, TrustOperatingStep } from "@/types/trust-architecture-alignment-foundation";

const VERSION = "trust-architecture-alignment-foundation/v5.1" as const;
const IDENTIFIER = "TrustArchitectureAlignmentFoundation" as const;
let baselinePortfolio: ReturnType<typeof runEcosystemPortfolioGovernance> | undefined;
let baselineTrustConstitution: ReturnType<typeof runTrustConstitutionalFoundation> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly TrustArchitectureAlignmentFailure[], failure: TrustArchitectureAlignmentFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustArchitectureAlignmentScenario): TrustArchitectureAlignmentFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function outcome(failures: readonly TrustArchitectureAlignmentFailure[]): TrustArchitectureAlignmentOutcome { if (has(failures, "CERTIFICATION_PRUNED")) return "PRUNED"; return failures.length ? "FAIL" : "PASS"; }
function verifyHashedRecord(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function getPortfolio() { baselinePortfolio ??= runEcosystemPortfolioGovernance(); return baselinePortfolio; }
function getTrustConstitution() { baselineTrustConstitution ??= runTrustConstitutionalFoundation(); return baselineTrustConstitution; }
function record(architectureId: string, tenantId: string, id: string, refs: readonly string[], failures: readonly TrustArchitectureAlignmentFailure[], missing: TrustArchitectureAlignmentFailure): TrustArchitectureAlignmentRecord {
  return nested({ record_id: has(failures, missing) ? "" : id, architecture_id: architectureId, tenant_id: tenantId, version: VERSION, refs: freezeArray(refs), governance_refs: freezeArray(["governance:trust-architecture"]), replay_refs: freezeArray(["replay:trust-architecture"]), operational: !has(failures, missing), deterministic: !has(failures, "DETERMINISM_INVALID") });
}
function resultReplayHash(result: Omit<TrustArchitectureAlignmentResult, "replay_hash" | "integrity_hash">): string {
  return hash({ architecture: result.architecture.integrity_hash, alignment: result.alignment.integrity_hash, services: result.services.integrity_hash, integration: result.integration.integrity_hash, governance: result.governance.integrity_hash, observability: result.observability.integrity_hash, lifecycle: result.lifecycle.integrity_hash, dependencies: result.dependencies.integrity_hash, boundary: result.boundary.integrity_hash, certification: result.certification.integrity_hash });
}
function resultIntegrityHash(result: Omit<TrustArchitectureAlignmentResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.certification.outcome, replay_hash: result.replay_hash }); }

export function runTrustArchitectureAlignmentFoundation(input: TrustArchitectureAlignmentInput = {}): TrustArchitectureAlignmentResult {
  const direct = scenarioFailure(input.scenario ?? "BASELINE");
  const scenarioFailures = freezeArray<TrustArchitectureAlignmentFailure>(direct ? [direct] : []);
  const portfolio = getPortfolio();
  const trustConstitution = getTrustConstitution();
  const dependencyFailures = freezeArray<TrustArchitectureAlignmentFailure>([
    ...(!validateEcosystemPortfolioGovernance(portfolio).valid || has(scenarioFailures, "P4_20_PORTFOLIO_GOVERNANCE_INVALID") ? ["P4_20_PORTFOLIO_GOVERNANCE_INVALID" as const] : []),
    ...(!validateTrustConstitutionalFoundation(trustConstitution).valid || has(scenarioFailures, "P5_0_TRUST_CONSTITUTION_MISSING") ? ["P5_0_TRUST_CONSTITUTION_MISSING" as const] : []),
  ]);
  const failures = freezeArray([...new Set([...scenarioFailures, ...dependencyFailures])]);
  const architectureId = input.architecture_id ?? "trust-architecture:civitas";
  const tenantId = input.tenant_id ?? "tenant:qualified:primary";
  const lifecycleStates = freezeArray<TrustLifecycleState>(["DEFINED", "DESIGNED", "IMPLEMENTED", "VALIDATED", "ACTIVE", "MONITORING", "UNDER_REVIEW", "SUSPENDED", "RETIRED", "ARCHIVED"]);
  const operatingSteps = freezeArray<TrustOperatingStep>(["Initialize", "Configure", "Validate", "Activate", "Monitor", "Assess", "Update", "Suspend", "Retire", "Archive"]);
  const layerStack = freezeArray<TrustLayer>(["Constitution Layer", "Doctrine Layer", "Architecture Layer", "Alignment Layer", "Service Layer", "Capability Layer", "Runtime Layer"]);
  const trustConstitutionRef = has(failures, "P5_0_TRUST_CONSTITUTION_MISSING") ? "" : "trust-constitution/v5.0";
  const architecture = nested({ ...record(architectureId, tenantId, "P5.1-TRUST-ARCHITECTURE-001", ["trust-domain", "alignment-domain", "trust-services", "integration-layer", "governance-layer", "observability-layer"], failures, "TRUST_ARCHITECTURE_MISSING"), trust_constitution_ref: trustConstitutionRef, trust_domain_ref: has(failures, "TRUST_DOMAIN_MODEL_MISSING") ? "" : "domain:trust", alignment_domain_ref: has(failures, "ALIGNMENT_DOMAIN_MODEL_MISSING") ? "" : "domain:alignment", trust_services_ref: has(failures, "TRUST_SERVICE_MODEL_MISSING") ? "" : "services:trust", integration_layer_ref: has(failures, "TRUST_INTEGRATION_ARCHITECTURE_MISSING") ? "" : "integration:trust", governance_layer_ref: has(failures, "TRUST_GOVERNANCE_INTEGRATION_MISSING") ? "" : "governance:trust", observability_layer_ref: has(failures, "TRUST_OBSERVABILITY_ARCHITECTURE_MISSING") ? "" : "observability:trust", advisory_by_default: true, claims_execution_authority: has(failures, "EXECUTION_AUTHORITY_CLAIMED") });
  const alignment = nested({ ...record(architectureId, tenantId, "P5.1-ALIGNMENT-ARCHITECTURE-001", ["constitution", "trust-principles", "trust-architecture", "alignment-architecture", "trust-services", "applications", "operators"], failures, "ALIGNMENT_ARCHITECTURE_MISSING"), alignment_flow: has(failures, "ALIGNMENT_FLOW_INVALID") ? freezeArray(["Operators", "Applications", "Trust Services"]) : freezeArray(["Constitution", "Trust Principles", "Trust Architecture", "Alignment Architecture", "Trust Services", "Applications", "Operators"]), constitutional_alignment_ref: "alignment:constitutional", governance_alignment_ref: "alignment:governance", operational_alignment_ref: "alignment:operational", mission_alignment_ref: "alignment:mission", behavioral_alignment_ref: "alignment:behavioral", authority_flows_upward: has(failures, "AUTHORITY_FLOW_UPWARD") });
  const services = nested({ ...record(architectureId, tenantId, "P5.1-TRUST-SERVICE-MODEL-001", ["trust-registry", "trust-resolution", "trust-validation", "trust-queries", "trust-lineage", "trust-context"], failures, "TRUST_SERVICE_MODEL_MISSING"), service_refs: freezeArray(["Trust Registry", "Trust Resolution", "Trust Validation", "Trust Queries", "Trust Lineage", "Trust Context"]), contract_obligations: has(failures, "SERVICE_CONTRACTS_MISSING") ? freezeArray<string>([]) : freezeArray(["purpose", "responsibilities", "inputs", "outputs", "dependencies", "constitutional obligations", "governance obligations", "replay obligations"]), has_identity: true, has_authority: true, has_dependencies: true, has_interfaces: true, has_lifecycle: true, has_observability: true, has_governance_bindings: true, has_replay_bindings: true });
  const integration = nested({ ...record(architectureId, tenantId, "P5.1-TRUST-INTEGRATION-ARCHITECTURE-001", ["program-1", "program-2", "program-3", "program-4", "program-6"], failures, "TRUST_INTEGRATION_ARCHITECTURE_MISSING"), program_interface_refs: has(failures, "CROSS_PROGRAM_INTERFACES_MISSING") ? freezeArray<string>([]) : freezeArray(["program-1:capability-ownership", "program-2:constitutional-infrastructure", "program-3:agent-trust-consumption", "program-4:application-trust-integration", "program-6:trust-validation-environments"]), cci_interface_ref: "program-2:cci:trust-platform-services", caf_interface_ref: "program-3:caf:alignment-consumption", mission_control_interface_ref: "program-4:mission-control:trust-integration", application_interface_ref: "program-4:applications:trust-aware-behavior", future_program_interface_ref: "program-6:trust-validation", implements_cross_program_behavior: false });
  const governance = nested({ ...record(architectureId, tenantId, "P5.1-TRUST-GOVERNANCE-ARCHITECTURE-001", ["constitutional-validation", "policy-integration", "authority-integration", "safety-integration"], failures, "TRUST_GOVERNANCE_INTEGRATION_MISSING"), constitutional_validation_ref: has(failures, "GOVERNANCE_INTEGRATION_UNSPECIFIED") ? "" : "governance:constitutional-validation", policy_integration_ref: "governance:policy-integration", authority_integration_ref: "governance:authority-integration", safety_integration_ref: "governance:safety-integration", governance_controlled: true, defines_trust_policy: has(failures, "TRUST_POLICY_IMPLEMENTED") });
  const observability = nested({ ...record(architectureId, tenantId, "P5.1-TRUST-OBSERVABILITY-ARCHITECTURE-001", ["monitoring", "diagnostics", "replay-hooks", "lineage", "audit-interfaces"], failures, "TRUST_OBSERVABILITY_ARCHITECTURE_MISSING"), monitoring_ref: "observability:trust-monitoring", diagnostics_ref: "observability:trust-diagnostics", replay_hook_refs: has(failures, "REPLAY_COMPATIBILITY_MISSING") ? freezeArray<string>([]) : freezeArray(["replay-hook:trust-architecture", "replay-hook:trust-lifecycle"]), lineage_ref: has(failures, "LIFECYCLE_LINEAGE_MISSING") ? "" : "lineage:trust-architecture", audit_interface_ref: "audit:trust-architecture", replay_compatible: !has(failures, "REPLAY_COMPATIBILITY_MISSING"), implements_trust_evidence: has(failures, "TRUST_EVIDENCE_IMPLEMENTED") });
  const lifecycle = nested({ ...record(architectureId, tenantId, "P5.1-TRUST-LIFECYCLE-001", ["defined", "designed", "implemented", "validated", "active", "monitoring", "under-review", "suspended", "retired", "archived"], failures, "TRUST_LIFECYCLE_MISSING"), states: lifecycleStates, operating_steps: operatingSteps, cannot_skip_states: !has(failures, "LIFECYCLE_TRANSITION_INVALID"), no_regression_without_governance: !has(failures, "LIFECYCLE_TRANSITION_INVALID"), preserves_lineage: !has(failures, "LIFECYCLE_LINEAGE_MISSING"), preserves_evidence: true, supports_replay: !has(failures, "REPLAY_COMPATIBILITY_MISSING") });
  const dependencies = nested({ ...record(architectureId, tenantId, "P5.1-TRUST-DEPENDENCY-ARCHITECTURE-001", ["trust-constitution", "trust-principles", "trust-architecture", "alignment-architecture", "trust-services", "trust-components"], failures, "DEPENDENCY_MODEL_INVALID"), dependency_stack: has(failures, "DEPENDENCY_MODEL_INVALID") ? freezeArray<string>([]) : freezeArray(["Trust Constitution", "Trust Principles", "Trust Architecture", "Alignment Architecture", "Trust Services", "Trust Components"]), layer_stack: has(failures, "LAYER_STACK_INVALID") ? freezeArray<TrustLayer>(["Runtime Layer", "Constitution Layer"]) : layerStack, circular_dependencies: has(failures, "CIRCULAR_DEPENDENCY_DETECTED"), layers_depend_only_on_higher_layers: !has(failures, "LAYER_STACK_INVALID") });
  const boundary = nested({ implements_trust_evaluation: has(failures, "TRUST_EVALUATION_IMPLEMENTED"), implements_trust_scoring: has(failures, "TRUST_SCORING_IMPLEMENTED"), implements_trust_evidence: has(failures, "TRUST_EVIDENCE_IMPLEMENTED"), implements_trust_policies: has(failures, "TRUST_POLICY_IMPLEMENTED"), implements_runtime_trust_decisions: has(failures, "RUNTIME_TRUST_DECISION_IMPLEMENTED"), claims_execution_authority: has(failures, "EXECUTION_AUTHORITY_CLAIMED") });
  const noOutOfScope = !boundary.implements_trust_evaluation && !boundary.implements_trust_scoring && !boundary.implements_trust_evidence && !boundary.implements_trust_policies && !boundary.implements_runtime_trust_decisions && !boundary.claims_execution_authority && !architecture.claims_execution_authority && !governance.defines_trust_policy && !observability.implements_trust_evidence;
  const derivedFailures = freezeArray([...new Set([
    ...failures,
    ...(architecture.trust_constitution_ref.length === 0 ? ["P5_0_TRUST_CONSTITUTION_MISSING" as const] : []),
    ...(architecture.trust_domain_ref.length === 0 ? ["TRUST_DOMAIN_MODEL_MISSING" as const] : []),
    ...(architecture.alignment_domain_ref.length === 0 ? ["ALIGNMENT_DOMAIN_MODEL_MISSING" as const] : []),
    ...(architecture.trust_services_ref.length === 0 ? ["TRUST_SERVICE_MODEL_MISSING" as const] : []),
    ...(alignment.alignment_flow[0] !== "Constitution" ? ["ALIGNMENT_FLOW_INVALID" as const] : []),
    ...(alignment.authority_flows_upward ? ["AUTHORITY_FLOW_UPWARD" as const] : []),
    ...(services.contract_obligations.length === 0 ? ["SERVICE_CONTRACTS_MISSING" as const] : []),
    ...(integration.program_interface_refs.length === 0 ? ["CROSS_PROGRAM_INTERFACES_MISSING" as const] : []),
    ...(governance.constitutional_validation_ref.length === 0 ? ["GOVERNANCE_INTEGRATION_UNSPECIFIED" as const] : []),
    ...(observability.replay_hook_refs.length === 0 || !observability.replay_compatible ? ["REPLAY_COMPATIBILITY_MISSING" as const] : []),
    ...(observability.lineage_ref.length === 0 || !lifecycle.preserves_lineage ? ["LIFECYCLE_LINEAGE_MISSING" as const] : []),
    ...(!lifecycle.cannot_skip_states ? ["LIFECYCLE_TRANSITION_INVALID" as const] : []),
    ...(dependencies.dependency_stack.length === 0 ? ["DEPENDENCY_MODEL_INVALID" as const] : []),
    ...(dependencies.circular_dependencies ? ["CIRCULAR_DEPENDENCY_DETECTED" as const] : []),
    ...(!dependencies.layers_depend_only_on_higher_layers ? ["LAYER_STACK_INVALID" as const] : []),
    ...(has(failures, "TENANT_ISOLATION_INVALID") ? ["TENANT_ISOLATION_INVALID" as const] : []),
    ...(has(failures, "CONSTITUTIONAL_COMPLIANCE_INVALID") ? ["CONSTITUTIONAL_COMPLIANCE_INVALID" as const] : []),
    ...(!architecture.deterministic ? ["DETERMINISM_INVALID" as const] : []),
    ...(has(failures, "DOWNSTREAM_APPROVAL_MISSING") ? ["DOWNSTREAM_APPROVAL_MISSING" as const] : []),
    ...(!noOutOfScope ? ["TRUST_EVALUATION_IMPLEMENTED" as const] : []),
  ])]);
  const certification = nested({ certification_id: "P5.1-TRUST-ARCHITECTURE-ALIGNMENT-CERTIFICATION-001", outcome: outcome(derivedFailures), phase_ready: outcome(derivedFailures) === "PASS", architecture_specified: architecture.operational && architecture.trust_constitution_ref.length > 0 && architecture.trust_domain_ref.length > 0, alignment_defined: alignment.operational && alignment.alignment_flow[0] === "Constitution" && !alignment.authority_flows_upward, service_model_complete: services.operational && services.service_refs.length === 6 && services.contract_obligations.length > 0, lifecycle_specified: lifecycle.operational && lifecycle.states.length === 10 && lifecycle.cannot_skip_states && lifecycle.preserves_lineage, boundaries_documented: noOutOfScope, service_contracts_defined: services.contract_obligations.length > 0, governance_integration_specified: governance.operational && governance.constitutional_validation_ref.length > 0 && governance.governance_controlled, cross_program_interfaces_documented: integration.program_interface_refs.length === 5, dependency_architecture_validated: dependencies.dependency_stack.length === 6 && !dependencies.circular_dependencies && dependencies.layers_depend_only_on_higher_layers, deterministic_rules_verified: architecture.deterministic && lifecycle.deterministic && dependencies.deterministic, replay_compatible: observability.replay_compatible && lifecycle.supports_replay, tenant_isolation_preserved: !has(derivedFailures, "TENANT_ISOLATION_INVALID"), constitutional_compliance_verified: !has(derivedFailures, "CONSTITUTIONAL_COMPLIANCE_INVALID"), downstream_implementation_approved: !has(derivedFailures, "DOWNSTREAM_APPROVAL_MISSING"), no_out_of_scope_implementation: noOutOfScope, failures: derivedFailures });
  const base: Omit<TrustArchitectureAlignmentResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, portfolio_governance_ref: "ecosystem-portfolio-governance/v4.20", architecture, alignment, services, integration, governance, observability, lifecycle, dependencies, boundary, certification };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustArchitectureAlignmentFoundation(result?: TrustArchitectureAlignmentResult): TrustArchitectureAlignmentValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, architecture_valid: false, alignment_valid: false, services_valid: false, integration_valid: false, governance_valid: false, observability_valid: false, lifecycle_valid: false, dependencies_valid: false, boundary_valid: false, certification_valid: false, failures: freezeArray(["CERTIFICATION_PRUNED" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const architecture_valid = verifyHashedRecord(result.architecture) && result.architecture.operational && result.architecture.trust_constitution_ref.length > 0 && result.architecture.trust_domain_ref.length > 0 && result.architecture.advisory_by_default && !result.architecture.claims_execution_authority;
  const alignment_valid = verifyHashedRecord(result.alignment) && result.alignment.operational && result.alignment.alignment_flow[0] === "Constitution" && result.alignment.alignment_flow.at(-1) === "Operators" && !result.alignment.authority_flows_upward;
  const services_valid = verifyHashedRecord(result.services) && result.services.operational && result.services.service_refs.length === 6 && result.services.contract_obligations.length > 0 && result.services.has_identity && result.services.has_replay_bindings;
  const integration_valid = verifyHashedRecord(result.integration) && result.integration.operational && result.integration.program_interface_refs.length === 5 && !result.integration.implements_cross_program_behavior;
  const governance_valid = verifyHashedRecord(result.governance) && result.governance.operational && result.governance.constitutional_validation_ref.length > 0 && result.governance.governance_controlled && !result.governance.defines_trust_policy;
  const observability_valid = verifyHashedRecord(result.observability) && result.observability.operational && result.observability.replay_compatible && result.observability.replay_hook_refs.length > 0 && result.observability.lineage_ref.length > 0 && !result.observability.implements_trust_evidence;
  const lifecycle_valid = verifyHashedRecord(result.lifecycle) && result.lifecycle.operational && result.lifecycle.states.length === 10 && result.lifecycle.operating_steps.length === 10 && result.lifecycle.cannot_skip_states && result.lifecycle.no_regression_without_governance && result.lifecycle.preserves_lineage && result.lifecycle.supports_replay;
  const dependencies_valid = verifyHashedRecord(result.dependencies) && result.dependencies.operational && result.dependencies.dependency_stack.length === 6 && result.dependencies.layer_stack[0] === "Constitution Layer" && !result.dependencies.circular_dependencies && result.dependencies.layers_depend_only_on_higher_layers;
  const boundary_valid = verifyHashedRecord(result.boundary) && !result.boundary.implements_trust_evaluation && !result.boundary.implements_trust_scoring && !result.boundary.implements_trust_evidence && !result.boundary.implements_trust_policies && !result.boundary.implements_runtime_trust_decisions && !result.boundary.claims_execution_authority;
  const certification_valid = verifyHashedRecord(result.certification) && result.certification.outcome === "PASS" && result.certification.phase_ready && result.certification.failures.length === 0 && result.certification.no_out_of_scope_implementation;
  const valid = replay_hash_valid && integrity_hash_valid && architecture_valid && alignment_valid && services_valid && integration_valid && governance_valid && observability_valid && lifecycle_valid && dependencies_valid && boundary_valid && certification_valid;
  return nested({ valid, outcome: result.certification.outcome, replay_hash_valid, integrity_hash_valid, architecture_valid, alignment_valid, services_valid, integration_valid, governance_valid, observability_valid, lifecycle_valid, dependencies_valid, boundary_valid, certification_valid, failures: result.certification.failures });
}

export function replayTrustArchitectureAlignmentFoundation(result = runTrustArchitectureAlignmentFoundation()): boolean {
  const replayed = runTrustArchitectureAlignmentFoundation();
  return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustArchitectureAlignmentFoundation(result).valid;
}

export function getTrustArchitectureAlignmentFoundationBundle(): TrustArchitectureAlignmentBundle {
  const result = runTrustArchitectureAlignmentFoundation();
  return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_trust_architecture: true, owns_alignment_architecture: true, owns_trust_lifecycle: true, owns_trust_services: true, owns_trust_operating_model: true, implements_trust_evaluation: false, implements_trust_scoring: false, implements_trust_evidence: false, implements_trust_policies: false, implements_runtime_trust_decisions: false, claims_execution_authority: false }), result, validation: validateTrustArchitectureAlignmentFoundation(result) });
}

export const TrustArchitectureAlignmentFoundationService = Object.freeze({ run: runTrustArchitectureAlignmentFoundation, validate: validateTrustArchitectureAlignmentFoundation, replay: replayTrustArchitectureAlignmentFoundation });
