import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runWaveFiveUnifiedPersonalContext, validateWaveFiveUnifiedPersonalContext } from "@/services/wave-five-unified-personal-context";
import { runWaveSixDependencyServiceCoordination, validateWaveSixDependencyServiceCoordination } from "@/services/wave-six-dependency-service-coordination";
import type { WaveSixPersonalOperationalContextBundle, WaveSixPersonalOperationalContextDecision, WaveSixPersonalOperationalContextFailure, WaveSixPersonalOperationalContextInput, WaveSixPersonalOperationalContextResult, WaveSixPersonalOperationalContextScenario, WaveSixPersonalOperationalContextValidation } from "@/types/wave-six-personal-operational-context";

const VERSION = "wave-six-personal-operational-context/w6.3" as const;
const IDENTIFIER = "WaveSixPersonalOperationalContext" as const;
const UPSTREAM_REFS = Object.freeze(["wave-six-dependency-service-coordination/w6.2", "wave-five-unified-personal-context/w5.2", "identity-services", "calendar-integrations", "task-management-services", "knowledge-services", "aurora-orchestration", "mission-control-scheduling"]);
const PROVIDES = Object.freeze(["personal-operational-context", "context-snapshot-registry", "context-history", "current-priorities", "active-project-state", "runtime-context-for-aurora"]);
let dependency = runWaveSixDependencyServiceCoordination();
let unified = runWaveFiveUnifiedPersonalContext();

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly WaveSixPersonalOperationalContextFailure[], failure: WaveSixPersonalOperationalContextFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: WaveSixPersonalOperationalContextScenario): WaveSixPersonalOperationalContextFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly WaveSixPersonalOperationalContextFailure[], scenario?: WaveSixPersonalOperationalContextScenario): WaveSixPersonalOperationalContextDecision {
  const notQualified = new Set<WaveSixPersonalOperationalContextFailure>(["W6_2_DEPENDENCY_COORDINATION_INVALID", "W5_UNIFIED_PERSONAL_CONTEXT_INVALID", "CONTEXT_ASSEMBLY_NONDETERMINISTIC", "HIDDEN_AI_MEMORY_USED", "GOAL_LIFECYCLE_INVALID", "GOAL_PRIORITIES_NONDETERMINISTIC", "PROJECT_LIFECYCLE_INVALID", "PROJECT_DEPENDENCIES_INVALID", "ROUTINE_SCHEDULING_INVALID", "HABIT_PROGRESS_INVALID", "CALENDAR_INTEGRATION_INVALID", "AVAILABILITY_INVALID", "TIME_BLOCKING_NONDETERMINISTIC", "PRIORITY_RANKING_NONDETERMINISTIC", "TEMPORARY_OVERRIDE_INVALID", "SESSION_CONTEXT_INVALID", "SNAPSHOT_MUTABLE", "SNAPSHOT_REPLAY_DIVERGED", "SESSION_RESTORE_DIVERGED", "HISTORICAL_RECONSTRUCTION_FAILED", "OPERATIONAL_HISTORY_OVERWRITTEN", "CONSTITUTIONAL_POLICY_STORED", "AUTHORITY_DECISION_MADE", "TRUST_STANDING_MAINTAINED", "RESTRICTION_EVALUATION_PERFORMED", "IDENTITY_OWNERSHIP_ASSUMED", "LONG_TERM_MEMORY_OWNERSHIP_ASSUMED", "PCC_SEPARATION_BREACH", "TENANT_ISOLATION_BREACH"]);
  if (failures.some((failure) => notQualified.has(failure))) return "NOT_QUALIFIED";
  if (has(failures, "PERSONAL_OPERATIONAL_CONTEXT_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_QUALIFIED";
  return "QUALIFIED";
}
function resultReplayHash(result: Omit<WaveSixPersonalOperationalContextResult, "replay_hash" | "integrity_hash">): string { return hash({ context: result.context_manager.integrity_hash, goals: result.goals_projects.integrity_hash, routines: result.routines_schedules_priorities.integrity_hash, working: result.working_snapshot_history.integrity_hash, boundary: result.constitutional_boundary.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<WaveSixPersonalOperationalContextResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runWaveSixPersonalOperationalContext(input: WaveSixPersonalOperationalContextInput = {}): WaveSixPersonalOperationalContextResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  dependency = runWaveSixDependencyServiceCoordination();
  unified = runWaveFiveUnifiedPersonalContext();
  const failures = freezeArray([...new Set([...(direct ? [direct] : []), ...(!validateWaveSixDependencyServiceCoordination(dependency).valid ? ["W6_2_DEPENDENCY_COORDINATION_INVALID" as const] : []), ...(!validateWaveFiveUnifiedPersonalContext(unified).valid ? ["W5_UNIFIED_PERSONAL_CONTEXT_INVALID" as const] : [])])]);
  const contextOk = !has(failures, "CONTEXT_MANAGER_MISSING") && !has(failures, "CONTEXT_ASSEMBLY_NONDETERMINISTIC") && !has(failures, "HIDDEN_AI_MEMORY_USED") && !has(failures, "CONTEXT_EXPIRATION_MISSING") && !has(failures, "CONTEXT_UPDATES_INVALID");
  const goalsProjectsOk = !has(failures, "GOAL_MANAGER_MISSING") && !has(failures, "GOAL_LIFECYCLE_INVALID") && !has(failures, "GOAL_PRIORITIES_NONDETERMINISTIC") && !has(failures, "GOAL_DEPENDENCIES_INVALID") && !has(failures, "PROJECT_MANAGER_MISSING") && !has(failures, "PROJECT_LIFECYCLE_INVALID") && !has(failures, "PROJECT_DEPENDENCIES_INVALID") && !has(failures, "PROJECT_MILESTONES_MISSING");
  const routinesOk = !has(failures, "ROUTINE_ENGINE_MISSING") && !has(failures, "ROUTINE_SCHEDULING_INVALID") && !has(failures, "ROUTINE_TRACKING_MISSING") && !has(failures, "HABIT_PROGRESS_INVALID") && !has(failures, "SCHEDULE_SERVICE_MISSING") && !has(failures, "CALENDAR_INTEGRATION_INVALID") && !has(failures, "AVAILABILITY_INVALID") && !has(failures, "TIME_BLOCKING_NONDETERMINISTIC") && !has(failures, "PRIORITY_ENGINE_MISSING") && !has(failures, "PRIORITY_RANKING_NONDETERMINISTIC") && !has(failures, "PRIORITY_EXPIRATION_MISSING") && !has(failures, "TEMPORARY_OVERRIDE_INVALID");
  const workingOk = !has(failures, "WORKING_CONTEXT_MISSING") && !has(failures, "SESSION_CONTEXT_INVALID") && !has(failures, "RECENT_ACTIVITY_MISSING") && !has(failures, "WORKING_CONTEXT_EXPIRATION_MISSING") && !has(failures, "SNAPSHOT_SERVICE_MISSING") && !has(failures, "SNAPSHOT_MUTABLE") && !has(failures, "SNAPSHOT_REPLAY_DIVERGED") && !has(failures, "SESSION_RESTORE_DIVERGED") && !has(failures, "HISTORICAL_RECONSTRUCTION_FAILED") && !has(failures, "CONTEXT_HISTORY_MISSING") && !has(failures, "OPERATIONAL_HISTORY_OVERWRITTEN") && !has(failures, "CONTEXT_VERSIONING_MISSING") && !has(failures, "CHANGE_EVIDENCE_MISSING");
  const boundaryOk = !has(failures, "CONSTITUTIONAL_POLICY_STORED") && !has(failures, "AUTHORITY_DECISION_MADE") && !has(failures, "TRUST_STANDING_MAINTAINED") && !has(failures, "RESTRICTION_EVALUATION_PERFORMED") && !has(failures, "IDENTITY_OWNERSHIP_ASSUMED") && !has(failures, "LONG_TERM_MEMORY_OWNERSHIP_ASSUMED") && !has(failures, "PCC_SEPARATION_BREACH") && !has(failures, "TENANT_ISOLATION_BREACH");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "QUALIFIED";
  const context_manager = nested({ context_manager_id: contextOk ? "W6.3-CONTEXT-MANAGER-001" : "", runtime_context: contextOk, context_assembly: contextOk, context_expiration: contextOk, context_updates: contextOk, current_work_ref: contextOk, today_plan_ref: contextOk, recent_changes_ref: contextOk, aurora_session_context: contextOk, deterministic_assembly: contextOk, no_hidden_ai_memory: contextOk, mutable_operational_state: contextOk });
  const goals_projects = nested({ goals_projects_id: goalsProjectsOk ? "W6.3-GOALS-PROJECTS-001" : "", goal_registry: goalsProjectsOk, goal_lifecycle: goalsProjectsOk, goal_status: goalsProjectsOk, goal_priorities: goalsProjectsOk, goal_dependencies: goalsProjectsOk, goal_manager: goalsProjectsOk, goal_timeline: goalsProjectsOk, project_registry: goalsProjectsOk, project_status: goalsProjectsOk, milestones: goalsProjectsOk, deadlines: goalsProjectsOk, project_dependencies: goalsProjectsOk, project_dashboard: goalsProjectsOk, deterministic_updates: goalsProjectsOk });
  const routines_schedules_priorities = nested({ routines_schedules_priorities_id: routinesOk ? "W6.3-ROUTINES-SCHEDULES-PRIORITIES-001" : "", routine_registry: routinesOk, routine_scheduling: routinesOk, routine_tracking: routinesOk, habit_progress: routinesOk, routine_manager: routinesOk, daily_routines: routinesOk, weekly_routines: routinesOk, monthly_routines: routinesOk, schedule_registry: routinesOk, calendar_integration: routinesOk, availability: routinesOk, time_blocking: routinesOk, operational_schedule: routinesOk, priority_registry: routinesOk, priority_ranking: routinesOk, priority_expiration: routinesOk, temporary_overrides: routinesOk, active_priority_queue: routinesOk, deterministic_ranking: routinesOk });
  const working_snapshot_history = nested({ working_snapshot_history_id: workingOk ? "W6.3-WORKING-SNAPSHOT-HISTORY-001" : "", working_memory: workingOk, session_context: workingOk, recent_activity: workingOk, current_objective: workingOk, focus_session: workingOk, recent_decisions: workingOk, working_context_store: workingOk, working_context_expiration: workingOk, context_snapshot_service: workingOk, immutable_snapshots: workingOk, replay_support: workingOk, session_recovery: workingOk, historical_reconstruction: workingOk, context_history: workingOk, previous_state: workingOk, new_state: workingOk, change_type: workingOk, timestamps: workingOk, source: workingOk, change_evidence: workingOk, versioning: workingOk, no_overwrite_history: workingOk });
  const constitutional_boundary = nested({ boundary_id: "W6.3-OPERATIONAL-CONSTITUTIONAL-BOUNDARY-001", owns_active_goals: boundaryOk, owns_active_projects: boundaryOk, owns_personal_routines: boundaryOk, owns_schedules: boundaryOk, owns_temporary_priorities: boundaryOk, owns_working_context: boundaryOk, owns_constitutional_policy: false as const, owns_authority: false as const, owns_standing: false as const, owns_restrictions: false as const, owns_identity: false as const, owns_long_term_memory: false as const, pcc_separation_verified: boundaryOk, operational_not_constitutional: boundaryOk });
  const readiness = nested({ readiness_id: "W6.3-PERSONAL-OPERATIONAL-CONTEXT-READINESS-001", decision, phase_ready: qualified, dependency_coordination_ready: !has(failures, "W6_2_DEPENDENCY_COORDINATION_INVALID"), unified_personal_context_ready: !has(failures, "W5_UNIFIED_PERSONAL_CONTEXT_INVALID"), authoritative_mutable_runtime_context: contextOk, goals_projects_routines_schedules_priorities_managed: goalsProjectsOk && routinesOk, working_context_operational: workingOk, snapshots_replayable: workingOk, complete_history_preserved: workingOk, no_constitutional_policy_stored: boundaryOk, no_authority_decisions_made: boundaryOk, no_trust_standing_maintained: boundaryOk, no_restriction_evaluation_performed: boundaryOk, pcc_separation_validated: boundaryOk, replay_identical_runtime_state: workingOk && contextOk, failures });
  const base: Omit<WaveSixPersonalOperationalContextResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, dependency_coordination_ref: "wave-six-dependency-service-coordination/w6.2", unified_personal_context_ref: "wave-five-unified-personal-context/w5.2", upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id: input.tenant_id ?? dependency.tenant_id, principal_id: input.principal_id ?? "principal:w6.3:context-owner", context_id: input.context_id ?? "personal-operational-context:w6.3:current", context_manager, goals_projects, routines_schedules_priorities, working_snapshot_history, constitutional_boundary, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateWaveSixPersonalOperationalContext(result?: WaveSixPersonalOperationalContextResult): WaveSixPersonalOperationalContextValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, context_manager_valid: false, goals_projects_valid: false, routines_schedules_priorities_valid: false, working_snapshot_history_valid: false, constitutional_boundary_valid: false, readiness_valid: false, failures: freezeArray(["CONTEXT_MANAGER_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const context_manager_valid = verifyHashed(result.context_manager) && result.context_manager.deterministic_assembly && result.context_manager.no_hidden_ai_memory && result.context_manager.mutable_operational_state;
  const goals_projects_valid = verifyHashed(result.goals_projects) && result.goals_projects.goal_lifecycle && result.goals_projects.goal_priorities && result.goals_projects.project_registry && result.goals_projects.deterministic_updates;
  const routines_schedules_priorities_valid = verifyHashed(result.routines_schedules_priorities) && result.routines_schedules_priorities.routine_scheduling && result.routines_schedules_priorities.calendar_integration && result.routines_schedules_priorities.priority_expiration && result.routines_schedules_priorities.deterministic_ranking;
  const working_snapshot_history_valid = verifyHashed(result.working_snapshot_history) && result.working_snapshot_history.session_context && result.working_snapshot_history.immutable_snapshots && result.working_snapshot_history.replay_support && result.working_snapshot_history.no_overwrite_history;
  const constitutional_boundary_valid = verifyHashed(result.constitutional_boundary) && result.constitutional_boundary.operational_not_constitutional && result.constitutional_boundary.pcc_separation_verified && !result.constitutional_boundary.owns_constitutional_policy && !result.constitutional_boundary.owns_authority && !result.constitutional_boundary.owns_long_term_memory;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.dependency_coordination_ready && result.readiness.unified_personal_context_ready && result.readiness.pcc_separation_validated && result.readiness.replay_identical_runtime_state && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && context_manager_valid && goals_projects_valid && routines_schedules_priorities_valid && working_snapshot_history_valid && constitutional_boundary_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, context_manager_valid, goals_projects_valid, routines_schedules_priorities_valid, working_snapshot_history_valid, constitutional_boundary_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayWaveSixPersonalOperationalContext(result = runWaveSixPersonalOperationalContext()): boolean { const replayed = runWaveSixPersonalOperationalContext(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateWaveSixPersonalOperationalContext(result).valid; }
export function getWaveSixPersonalOperationalContextBundle(): WaveSixPersonalOperationalContextBundle { const result = runWaveSixPersonalOperationalContext(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, operational_not_constitutional: true, mutable_runtime_context_authoritative: true, deterministic_context_assembly_required: true, hidden_ai_memory_prohibited: true, immutable_snapshots_required: true, complete_history_required: true, pcc_boundary_required: true, qualification_gate: "W6.3 Personal Operational Context Qualification Gate" }), result, validation: validateWaveSixPersonalOperationalContext(result) }); }
export const WaveSixPersonalOperationalContextService = Object.freeze({ run: runWaveSixPersonalOperationalContext, validate: validateWaveSixPersonalOperationalContext, replay: replayWaveSixPersonalOperationalContext });
