import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runTrustHumanOversightGovernance, validateTrustHumanOversightGovernance } from "@/services/trust-human-oversight-governance";
import type { MonitoringAlert, MonitoringResult, TrendDirection, TrustHealthStatus, TrustMonitoringBundle, TrustMonitoringFailure, TrustMonitoringInput, TrustMonitoringOutcome, TrustMonitoringResult, TrustMonitoringScenario, TrustMonitoringValidation, TrustStanding } from "@/types/trust-continuous-monitoring";

const VERSION = "trust-continuous-monitoring/v5.13" as const;
const IDENTIFIER = "TrustContinuousMonitoring" as const;
const NOW = "2026-07-19T00:00:00.000Z";
let oversightBaseline: ReturnType<typeof runTrustHumanOversightGovernance> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly TrustMonitoringFailure[], failure: TrustMonitoringFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustMonitoringScenario): TrustMonitoringFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function outcome(failures: readonly TrustMonitoringFailure[]): TrustMonitoringOutcome { return has(failures, "GOVERNANCE_REVIEW_REQUIRED") ? "REQUIRES_GOVERNANCE_REVIEW" : failures.length ? "FAIL" : "PASS"; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function resultReplayHash(result: Omit<TrustMonitoringResult, "replay_hash" | "integrity_hash">): string { return hash({ pipeline: result.pipeline.integrity_hash, record: result.record.integrity_hash, health: result.health.integrity_hash, standing: result.standing.integrity_hash, report: result.report.integrity_hash, alerts: result.alerts.map((item) => item.integrity_hash), dashboard: result.dashboard.integrity_hash, ledger: result.ledger.integrity_hash, boundary: result.boundary.integrity_hash, certification: result.certification.integrity_hash }); }
function resultIntegrityHash(result: Omit<TrustMonitoringResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.certification.outcome, replay_hash: result.replay_hash }); }

export function runTrustContinuousMonitoring(input: TrustMonitoringInput = {}): TrustMonitoringResult {
  const direct = scenarioFailure(input.scenario ?? "BASELINE");
  const scenarioFailures = freezeArray<TrustMonitoringFailure>(direct ? [direct] : []);
  oversightBaseline ??= runTrustHumanOversightGovernance();
  const dependencyFailures = freezeArray<TrustMonitoringFailure>(!validateTrustHumanOversightGovernance(oversightBaseline).valid || has(scenarioFailures, "P5_12_HUMAN_OVERSIGHT_INVALID") ? ["P5_12_HUMAN_OVERSIGHT_INVALID"] : []);
  const failures = freezeArray([...new Set([...scenarioFailures, ...dependencyFailures])]);
  const trustId = input.trust_id ?? "trust-domain:civitas:root";
  const tenantId = has(failures, "TENANT_ISOLATION_VIOLATED") ? "tenant:external" : input.tenant_id ?? "tenant:civitas:primary";
  const evidenceFreshness = has(failures, "MONITORING_EVIDENCE_MISSING") ? "MISSING" as const : has(failures, "MONITORING_EVIDENCE_STALE") ? "STALE" as const : has(failures, "MONITORING_EVIDENCE_CONFLICTING") ? "CONFLICTING" as const : has(failures, "MONITORING_EVIDENCE_UNVERIFIABLE") ? "UNVERIFIABLE" as const : "FRESH" as const;
  const evidenceRefs = evidenceFreshness === "FRESH" ? freezeArray(["evidence-registry:p5.5:trust", "monitoring:event:trust-health", oversightBaseline.record.oversight_id, "program-3:operational-event"]) : freezeArray<string>([]);
  const monitoringFailure = evidenceFreshness !== "FRESH" || has(failures, "MONITORING_OUTPUT_NOT_REPLAYABLE") || has(failures, "MONITORING_NONDETERMINISTIC");
  const healthStatus: TrustHealthStatus = monitoringFailure ? "UNKNOWN" : "STABLE";
  const monitoringResult: MonitoringResult = monitoringFailure ? "MONITORING_FAILURE" : "NORMAL";
  const trend: TrendDirection = monitoringFailure ? "UNKNOWN" : "STABLE";
  const trustStanding: TrustStanding = has(failures, "MONITORING_FAILURE_IMPROVED_STANDING") ? "QUALIFIED" : "QUALIFIED_WITH_RESTRICTIONS";
  const observedTrustStanding: TrustStanding = has(failures, "TRUST_STANDING_CHANGED_DIRECTLY") ? "QUALIFIED" : trustStanding;
  const pipeline = nested({ pipeline_id: "pipeline:trust-monitoring:p5.13", continuous_monitor: !has(failures, "CONTINUOUS_MONITOR_MISSING"), trust_health_engine: !has(failures, "TRUST_HEALTH_ENGINE_MISSING"), standing_observation_service: !has(failures, "STANDING_OBSERVATION_MISSING"), monitoring_rules_engine: !has(failures, "MONITORING_RULES_ENGINE_MISSING"), operational_monitoring_service: !has(failures, "OPERATIONAL_MONITORING_MISSING"), trend_analysis_engine: !has(failures, "TREND_ANALYSIS_MISSING"), alert_service: !has(failures, "ALERT_SERVICE_MISSING"), trust_dashboard: !has(failures, "TRUST_DASHBOARD_MISSING"), monitoring_ledger: !has(failures, "MONITORING_LEDGER_MISSING"), certification_gate: !has(failures, "CERTIFICATION_GATE_MISSING") });
  const alertItems: MonitoringAlert[] = monitoringFailure || has(failures, "ALERTS_NOT_GENERATED") ? [nested({ alert_id: has(failures, "ALERTS_NOT_GENERATED") ? "" : "alert:monitoring:p5.13", alert_type: evidenceFreshness === "STALE" ? "EVIDENCE_STALE" as const : "MONITORING_FAILURE" as const, severity: "HIGH" as const, evidence_refs: evidenceRefs, action: "MAINTAIN_FAIL_CLOSED" as const })] : [nested({ alert_id: "alert:monitoring:p5.13:normal", alert_type: "TRUST_DEGRADATION" as const, severity: "INFO" as const, evidence_refs: evidenceRefs, action: "OBSERVE" as const })];
  const alerts = freezeArray(alertItems);
  const record = nested({ monitoring_id: "monitoring-record:p5.13", trust_id: trustId, tenant_id: tenantId, monitoring_timestamp: NOW, trust_standing: trustStanding, observed_trust_standing: observedTrustStanding, trust_health: healthStatus, operational_status: monitoringFailure ? "UNKNOWN" as const : "NOMINAL" as const, evidence_freshness: evidenceFreshness, confidence_score: monitoringFailure ? 0 : 0.91, risk_score: monitoringFailure ? 1 : 0.21, observation_summary: monitoringFailure ? "Monitoring evidence is unavailable or invalid; posture cannot improve." : "Trust standing remains observable and stable.", monitoring_result: monitoringResult, generated_alerts: alerts.map((item) => item.alert_id).filter(Boolean), lineage_refs: has(failures, "MONITORING_LINEAGE_INCOMPLETE") ? freezeArray<string>([]) : evidenceRefs.map((ref) => `lineage:${ref}`) });
  const health = nested({ report_id: has(failures, "HEALTH_NOT_CALCULATED") ? "" : "health-report:p5.13", trust_id: trustId, health_score: monitoringFailure ? 0 : 0.88, health_status: healthStatus, trend, evidence_quality: monitoringFailure ? 0 : 0.93, confidence_stability: monitoringFailure ? 0 : 0.89, operational_health: monitoringFailure ? 0 : 0.9, recommendations: freezeArray([monitoringFailure ? "maintain fail-closed posture and require re-evaluation" : "continue monitoring"]), generated_at: NOW });
  const standing = nested({ history_id: has(failures, "STANDING_HISTORY_MISSING") ? "" : "standing-history:p5.13", standing_transitions: freezeArray([`previous:${trustStanding}`, `observed:${observedTrustStanding}`]), standing_stability: trustStanding === observedTrustStanding, observation_history: freezeArray([record.monitoring_id]) });
  const report = nested({ report_id: "monitoring-report:p5.13", monitoring_scope: input.monitoring_scope ?? "trust-operational-posture", findings: has(failures, "RULES_NOT_EXECUTED") ? freezeArray<string>([]) : freezeArray([monitoringFailure ? "monitoring failure requires fail-closed handling" : "trust posture stable"]), anomalies: has(failures, "OPERATIONAL_CONDITIONS_NOT_CAPTURED") ? freezeArray<string>([]) : freezeArray(monitoringFailure ? ["monitoring-integrity-loss"] : []), alerts: record.generated_alerts, trend_summary: has(failures, "TREND_REPORT_MISSING") ? "" : `trend:${trend}`, evidence_refs: evidenceRefs });
  const dashboard = nested({ dashboard_id: "dashboard:trust-monitoring:p5.13", standing_visible: !has(failures, "DASHBOARD_INCOMPLETE"), health_visible: !has(failures, "DASHBOARD_INCOMPLETE"), alerts_visible: !has(failures, "DASHBOARD_INCOMPLETE"), evidence_freshness_visible: !has(failures, "DASHBOARD_INCOMPLETE"), operational_status_visible: !has(failures, "DASHBOARD_INCOMPLETE"), historical_trends_visible: !has(failures, "DASHBOARD_INCOMPLETE") });
  const ledger = nested({ ledger_id: "ledger:trust-monitoring:p5.13", monitoring_events: freezeArray([record.monitoring_id]), health_calculations: health.report_id ? freezeArray([health.report_id]) : freezeArray<string>([]), alerts: record.generated_alerts, observations: record.lineage_refs, trend_analyses: report.trend_summary ? freezeArray([report.trend_summary]) : freezeArray<string>([]), immutable: !has(failures, "MONITORING_LEDGER_MUTABLE"), lineage_complete: record.lineage_refs.length > 0 && !has(failures, "MONITORING_LINEAGE_INCOMPLETE"), replay_refs: has(failures, "MONITORING_OUTPUT_NOT_REPLAYABLE") ? freezeArray<string>([]) : freezeArray(["replay:p5.13:monitoring", "program-3:operational-replay"]) });
  const boundary = nested({ boundary_id: "boundary:trust-monitoring:p5.13", trust_standing_changed_directly: has(failures, "TRUST_STANDING_CHANGED_DIRECTLY"), trust_evaluation_executed: has(failures, "TRUST_EVALUATION_EXECUTED"), trust_decision_created: has(failures, "TRUST_DECISION_CREATED"), trust_qualification_executed: has(failures, "TRUST_QUALIFICATION_EXECUTED"), governance_decision_created: has(failures, "GOVERNANCE_DECISION_CREATED"), operator_approval_created: has(failures, "OPERATOR_APPROVAL_CREATED"), safety_qualification_executed: has(failures, "SAFETY_QUALIFICATION_EXECUTED"), tenant_isolation_preserved: !has(failures, "TENANT_ISOLATION_VIOLATED") });
  const boundaryRespected = !boundary.trust_standing_changed_directly && !boundary.trust_evaluation_executed && !boundary.trust_decision_created && !boundary.trust_qualification_executed && !boundary.governance_decision_created && !boundary.operator_approval_created && !boundary.safety_qualification_executed && boundary.tenant_isolation_preserved;
  const replayable = ledger.replay_refs.length > 0 && !has(failures, "MONITORING_NONDETERMINISTIC");
  const failClosed = !has(failures, "FAIL_CLOSED_NOT_ENFORCED") && (!monitoringFailure || alerts.some((item) => item.action === "MAINTAIN_FAIL_CLOSED"));
  const noImprovementOnFailure = !(monitoringFailure && trustStanding === "QUALIFIED");
  const derivedFailures = freezeArray([...new Set([...failures, ...(!pipeline.continuous_monitor ? ["CONTINUOUS_MONITOR_MISSING" as const] : []), ...(!pipeline.trust_health_engine ? ["TRUST_HEALTH_ENGINE_MISSING" as const] : []), ...(!pipeline.standing_observation_service ? ["STANDING_OBSERVATION_MISSING" as const] : []), ...(!pipeline.monitoring_rules_engine ? ["MONITORING_RULES_ENGINE_MISSING" as const] : []), ...(!pipeline.operational_monitoring_service ? ["OPERATIONAL_MONITORING_MISSING" as const] : []), ...(!pipeline.trend_analysis_engine ? ["TREND_ANALYSIS_MISSING" as const] : []), ...(!pipeline.alert_service ? ["ALERT_SERVICE_MISSING" as const] : []), ...(!pipeline.trust_dashboard ? ["TRUST_DASHBOARD_MISSING" as const] : []), ...(!pipeline.monitoring_ledger ? ["MONITORING_LEDGER_MISSING" as const] : []), ...(!pipeline.certification_gate ? ["CERTIFICATION_GATE_MISSING" as const] : []), ...(evidenceFreshness === "MISSING" ? ["MONITORING_EVIDENCE_MISSING" as const] : []), ...(evidenceFreshness === "STALE" ? ["MONITORING_EVIDENCE_STALE" as const] : []), ...(evidenceFreshness === "CONFLICTING" ? ["MONITORING_EVIDENCE_CONFLICTING" as const] : []), ...(evidenceFreshness === "UNVERIFIABLE" ? ["MONITORING_EVIDENCE_UNVERIFIABLE" as const] : []), ...(!replayable ? ["MONITORING_OUTPUT_NOT_REPLAYABLE" as const] : []), ...(has(failures, "MONITORING_NONDETERMINISTIC") ? ["MONITORING_NONDETERMINISTIC" as const] : []), ...(!ledger.lineage_complete ? ["MONITORING_LINEAGE_INCOMPLETE" as const] : []), ...(!ledger.immutable ? ["MONITORING_LEDGER_MUTABLE" as const] : []), ...(health.report_id.length === 0 ? ["HEALTH_NOT_CALCULATED" as const] : []), ...(standing.history_id.length === 0 ? ["STANDING_HISTORY_MISSING" as const] : []), ...(report.findings.length === 0 ? ["RULES_NOT_EXECUTED" as const] : []), ...(report.anomalies.length === 0 && has(failures, "OPERATIONAL_CONDITIONS_NOT_CAPTURED") ? ["OPERATIONAL_CONDITIONS_NOT_CAPTURED" as const] : []), ...(report.trend_summary.length === 0 ? ["TREND_REPORT_MISSING" as const] : []), ...(record.generated_alerts.length === 0 ? ["ALERTS_NOT_GENERATED" as const] : []), ...(!dashboard.standing_visible ? ["DASHBOARD_INCOMPLETE" as const] : []), ...(!noImprovementOnFailure ? ["MONITORING_FAILURE_IMPROVED_STANDING" as const] : []), ...(!boundaryRespected ? [scenarioFailures[0] as TrustMonitoringFailure] : []), ...(!failClosed ? ["FAIL_CLOSED_NOT_ENFORCED" as const] : [])])]);
  const certification = nested({ certification_id: "P5.13-CONTINUOUS-TRUST-MONITORING-CERTIFICATION-001", outcome: outcome(derivedFailures), phase_ready: outcome(derivedFailures) === "PASS", continuous_monitoring_operational: pipeline.continuous_monitor, health_calculated: health.report_id.length > 0, standing_observation_operational: standing.history_id.length > 0 && standing.standing_stability, rules_deterministic: pipeline.monitoring_rules_engine && !has(failures, "MONITORING_NONDETERMINISTIC"), operational_conditions_captured: pipeline.operational_monitoring_service && !has(failures, "OPERATIONAL_CONDITIONS_NOT_CAPTURED"), trend_analysis_operational: pipeline.trend_analysis_engine && report.trend_summary.length > 0, alerts_generated: record.generated_alerts.length > 0, dashboard_complete: dashboard.standing_visible && dashboard.health_visible && dashboard.alerts_visible && dashboard.evidence_freshness_visible && dashboard.operational_status_visible && dashboard.historical_trends_visible, ledger_immutable: ledger.immutable && ledger.lineage_complete, replayable, monitoring_failures_fail_closed: failClosed && noImprovementOnFailure, boundary_respected: boundaryRespected, failures: derivedFailures });
  const base: Omit<TrustMonitoringResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, human_oversight_ref: "trust-human-oversight-governance/v5.12", pipeline, record, health, standing, report, alerts, dashboard, ledger, boundary, certification };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustContinuousMonitoring(result?: TrustMonitoringResult): TrustMonitoringValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, pipeline_valid: false, record_valid: false, health_valid: false, standing_valid: false, report_valid: false, alerts_valid: false, dashboard_valid: false, ledger_valid: false, boundary_valid: false, certification_valid: false, failures: freezeArray(["CONTINUOUS_MONITOR_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const pipeline_valid = verifyHashed(result.pipeline) && result.pipeline.continuous_monitor && result.pipeline.trust_health_engine && result.pipeline.standing_observation_service && result.pipeline.monitoring_rules_engine && result.pipeline.operational_monitoring_service && result.pipeline.trend_analysis_engine && result.pipeline.alert_service && result.pipeline.trust_dashboard && result.pipeline.monitoring_ledger && result.pipeline.certification_gate;
  const record_valid = verifyHashed(result.record) && result.record.evidence_freshness === "FRESH" && result.record.monitoring_result === "NORMAL" && result.record.lineage_refs.length > 0 && result.record.trust_standing === result.record.observed_trust_standing;
  const health_valid = verifyHashed(result.health) && result.health.report_id.length > 0 && result.health.health_status === "STABLE" && result.health.trend === "STABLE" && result.health.health_score > 0;
  const standing_valid = verifyHashed(result.standing) && result.standing.history_id.length > 0 && result.standing.standing_stability && result.standing.observation_history.length > 0;
  const report_valid = verifyHashed(result.report) && result.report.report_id.length > 0 && result.report.findings.length > 0 && result.report.trend_summary.length > 0 && result.report.evidence_refs.length > 0;
  const alerts_valid = result.alerts.length > 0 && result.alerts.every((item) => verifyHashed(item) && item.alert_id.length > 0);
  const dashboard_valid = verifyHashed(result.dashboard) && result.dashboard.standing_visible && result.dashboard.health_visible && result.dashboard.alerts_visible && result.dashboard.evidence_freshness_visible && result.dashboard.operational_status_visible && result.dashboard.historical_trends_visible;
  const ledger_valid = verifyHashed(result.ledger) && result.ledger.immutable && result.ledger.lineage_complete && result.ledger.replay_refs.length > 0;
  const boundary_valid = verifyHashed(result.boundary) && !result.boundary.trust_standing_changed_directly && !result.boundary.trust_evaluation_executed && !result.boundary.trust_decision_created && !result.boundary.trust_qualification_executed && !result.boundary.governance_decision_created && !result.boundary.operator_approval_created && !result.boundary.safety_qualification_executed && result.boundary.tenant_isolation_preserved;
  const certification_valid = verifyHashed(result.certification) && result.certification.outcome === "PASS" && result.certification.phase_ready && result.certification.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && pipeline_valid && record_valid && health_valid && standing_valid && report_valid && alerts_valid && dashboard_valid && ledger_valid && boundary_valid && certification_valid;
  return nested({ valid, outcome: result.certification.outcome, replay_hash_valid, integrity_hash_valid, pipeline_valid, record_valid, health_valid, standing_valid, report_valid, alerts_valid, dashboard_valid, ledger_valid, boundary_valid, certification_valid, failures: result.certification.failures });
}

export function replayTrustContinuousMonitoring(result = runTrustContinuousMonitoring()): boolean {
  const replayed = runTrustContinuousMonitoring();
  return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustContinuousMonitoring(result).valid;
}

export function getTrustContinuousMonitoringBundle(): TrustMonitoringBundle {
  const result = runTrustContinuousMonitoring();
  return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_trust_monitoring: true, owns_operational_monitoring: true, owns_trust_health: true, owns_standing_observation: true, changes_trust_standing: false, evaluates_trust: false, creates_trust_decisions: false, qualifies_trust: false, creates_governance_decisions: false, creates_operator_approvals: false, qualifies_safety: false }), result, validation: validateTrustContinuousMonitoring(result) });
}

export const TrustContinuousMonitoringService = Object.freeze({ run: runTrustContinuousMonitoring, validate: validateTrustContinuousMonitoring, replay: replayTrustContinuousMonitoring });
