export const RUNTIME_VALIDATION_ERROR_CODES = {
  TOOL_RUNTIME_UNKNOWN: "TOOL_RUNTIME_UNKNOWN",
  TOOL_RUNTIME_UNSUPPORTED: "TOOL_RUNTIME_UNSUPPORTED",
  TOOL_ADAPTER_INCOMPATIBLE: "TOOL_ADAPTER_INCOMPATIBLE",
  TOOL_SCHEMA_INCOMPATIBLE: "TOOL_SCHEMA_INCOMPATIBLE",
  TOOL_ROLLBACK_UNSUPPORTED: "TOOL_ROLLBACK_UNSUPPORTED",
  TOOL_REPLAY_UNSUPPORTED: "TOOL_REPLAY_UNSUPPORTED",
  RUNTIME_BINDING_MISMATCH: "RUNTIME_BINDING_MISMATCH",
  RUNTIME_POLICY_DRIFT: "RUNTIME_POLICY_DRIFT",
  RUNTIME_SANDBOX_DRIFT: "RUNTIME_SANDBOX_DRIFT",
  RUNTIME_AUTHORITY_DRIFT: "RUNTIME_AUTHORITY_DRIFT",
  RUNTIME_REPLAY_CONTAINMENT_DRIFT: "RUNTIME_REPLAY_CONTAINMENT_DRIFT",
  RUNTIME_GOVERNANCE_DRIFT: "RUNTIME_GOVERNANCE_DRIFT",
  RUNTIME_BINDING_INVALIDATED: "RUNTIME_BINDING_INVALIDATED",
  RUNTIME_CERTIFICATION_INVALID: "RUNTIME_CERTIFICATION_INVALID",
  RUNTIME_ATTESTATION_INVALID: "RUNTIME_ATTESTATION_INVALID",
  RUNTIME_UNCERTIFIED: "RUNTIME_UNCERTIFIED",
  RUNTIME_PROVENANCE_INVALID: "RUNTIME_PROVENANCE_INVALID",
  RUNTIME_ISOLATION_UNVERIFIED: "RUNTIME_ISOLATION_UNVERIFIED",
  ADAPTER_PROVENANCE_INVALID: "ADAPTER_PROVENANCE_INVALID",
} as const;

export type RuntimeValidationErrorCode = typeof RUNTIME_VALIDATION_ERROR_CODES[keyof typeof RUNTIME_VALIDATION_ERROR_CODES];
