export type CoordinationGovernanceErrorCode =
  | "COORDINATION_SCOPE_EXCEEDED"
  | "COORDINATION_RECURSION_DETECTED"
  | "COORDINATION_TOPOLOGY_INVALID"
  | "COORDINATION_REPLAY_MISMATCH"
  | "COORDINATION_GOVERNANCE_MISMATCH"
  | "COORDINATION_CONTAINMENT_VIOLATION"
  | "COORDINATION_EXECUTION_LEAK"
  | "INVALID_COORDINATION_TRANSITION"
  | "ESCALATION_CONTAINMENT_VIOLATION"
  | "READINESS_BINDING_MISSING";

export type CoordinationGovernanceError = Readonly<{
  code: CoordinationGovernanceErrorCode;
  message: string;
  path?: string;
}>;
