import { getSessionUser } from "@/src/lib/auth";
import { AppError } from "@/src/server/api/errors";
import { apiError, apiSuccess } from "@/src/server/api/response";
import { requireWorkspaceManager } from "@/src/server/auth/permissions";
import { PrismaLearningAuditLedger, PrismaSelfDirectedLearningArtifactRepository, SelfDirectedLearningPlannerService } from "@/services/learning-constitution";
import type { LearningProposal } from "@/types/learning-constitution";
export const dynamic = "force-dynamic";
const userFor = async () => { const user = await getSessionUser(); if (!user) throw new AppError(401, "unauthorized", "Authentication required."); if (!user.workspaceId || user.workspaceId === "default") throw new AppError(403, "workspace_required", "Workspace membership is required."); await requireWorkspaceManager({ userId: user.id, userRole: user.role, workspaceId: user.workspaceId }); return user; };
export async function GET() { try { const user = await userFor(); const records = await new PrismaSelfDirectedLearningArtifactRepository(user.workspaceId!).listWorkspaceArtifacts(); return apiSuccess({ proposals: records.filter((record) => record.artifactType === "PROPOSAL").map((record) => record.payload as LearningProposal), approvals: records.filter((record) => record.artifactType === "APPROVAL").map((record) => record.payload) }); } catch (error) { return apiError(error, "Unable to load learning proposals."); } }
/** A human approval is explicit and creates the sole execution capability; agents cannot invoke this authority. */
export async function POST(request: Request) { try { const user = await userFor(); const { proposalId, decision } = await request.json() as { proposalId?: string; decision?: "APPROVE" | "DEFER" | "REJECT" }; if (!proposalId?.trim() || !decision || !["APPROVE", "DEFER", "REJECT"].includes(decision)) throw new AppError(400, "proposal_invalid", "A proposal ID and APPROVE, DEFER, or REJECT decision are required."); const store = new PrismaSelfDirectedLearningArtifactRepository(user.workspaceId!); const proposal = (await store.listArtifacts(proposalId)).find((record) => record.artifactType === "PROPOSAL")?.payload as LearningProposal | undefined; if (!proposal || proposal.status !== "AWAITING_HUMAN_APPROVAL") throw new AppError(409, "proposal_unavailable", "Only awaiting proposals may be reviewed."); const now = new Date().toISOString(); const approvalId = `learning-approval:${proposalId}:${now}`; const lease = decision === "APPROVE" ? { leaseId: `learning-lease:${proposalId}:${now}`, proposalId, approvalId, scope: proposal.scope, method: proposal.method, maximumQuestions: proposal.teacherEffortBudget.maximumQuestions, issuedBy: { actorId: `user:${user.id}`, actorType: "HUMAN" as const }, issuedAt: now, expiresAt: proposal.expiresAt, status: "ACTIVE" as const } : null; await new SelfDirectedLearningPlannerService(store, new PrismaLearningAuditLedger(user.workspaceId!)).approve({ proposal, approval: { approvalId, proposalId, decision, approvedScope: proposal.scope, approvedMethod: proposal.method, approvedBudget: { maximumQuestions: proposal.teacherEffortBudget.maximumQuestions }, decidedBy: { actorId: `user:${user.id}`, actorType: "HUMAN" }, decidedAt: now, executionLeaseId: lease?.leaseId ?? null }, lease, workspaceId: user.workspaceId!, correlationId: approvalId }); return apiSuccess({ proposalId, decision, lease }); } catch (error) { return apiError(error, "Unable to review learning proposal."); } }
