export type IntakeFailureType =
  | "INVALID_SOURCE"
  | "MALFORMED_PAYLOAD"
  | "UNSUPPORTED_ENCODING"
  | "PAYLOAD_TOO_LARGE"
  | "RECURSION_LIMIT_EXCEEDED"
  | "SAFETY_REJECTION"
  | "NORMALIZATION_FAILURE"
  | "VALIDATION_FAILURE";
