import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runConstitutionalComplianceGate, validateConstitutionalComplianceGate } from "@/services/trust-constitutional-compliance-gate";
import { runTrustExplainabilityStageSix, validateTrustExplainabilityStageSix } from "@/services/trust-explainability-stage-six";
import { runTrustFoundationStageOne, validateTrustFoundationStageOne } from "@/services/trust-foundation-stage-one";
import { runTrustHumanOversightStageSeven, validateTrustHumanOversightStageSeven } from "@/services/trust-human-oversight-stage-seven";
import { runTrustIndependentEvaluation, validateTrustIndependentEvaluation } from "@/services/trust-independent-evaluation";
import { runTrustRegistryDomains, validateTrustRegistryDomains } from "@/services/trust-registry-domains";
import { runTrustResolutionEngine, validateTrustResolutionEngine } from "@/services/trust-resolution-engine";
import type { MonitoringEventSeverity, TrustContinuousMonitoringBundle, TrustContinuousMonitoringDecision, TrustContinuousMonitoringFailure, TrustContinuousMonitoringInput, TrustContinuousMonitoringResult, TrustContinuousMonitoringScenario, TrustContinuousMonitoringValidation } from "@/types/trust-continuous-monitoring-stage-eight";

const VERSION = "trust-continuous-monitoring-stage-eight/stage-8" as const;
const IDENTIFIER = "TrustContinuousMonitoringStageEight" as const;
const EVENT_SEVERITIES = Object.freeze<MonitoringEventSeverity[]>(["INFO", "WATCH", "DEGRADATION", "CRITICAL"]);
const UPSTREAM_REFS = Object.freeze(["trust-foundation-stage-one/stage-1", "trust-constitutional-compliance-gate/stage-2", "trust-registry-domains/stage-3", "trust-independent-evaluation/stage-4", "trust-resolution-engine/stage-5", "trust-explainability-stage-six/stage-6", "trust-human-oversight-stage-seven/stage-7"]);
const PROVIDES = Object.freeze(["monitoring-service", "trust-health-reports", "monitoring-dashboard", "monitoring-evidence", "monitoring-events", "health-metrics", "standing-metrics", "behavioral-reports", "evidence-freshness-reports"]);
let baselines: ReturnType<typeof makeBaselines> | undefined;

function makeBaselines() { return { foundation: runTrustFoundationStageOne(), gate: runConstitutionalComplianceGate(), registry: runTrustRegistryDomains(), evaluation: runTrustIndependentEvaluation(), resolution: runTrustResolutionEngine(), explainability: runTrustExplainabilityStageSix(), oversight: runTrustHumanOversightStageSeven() }; }
function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly TrustContinuousMonitoringFailure[], failure: TrustContinuousMonitoringFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustContinuousMonitoringScenario): TrustContinuousMonitoringFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly TrustContinuousMonitoringFailure[], scenario?: TrustContinuousMonitoringScenario): TrustContinuousMonitoringDecision {
  const failClosed = new Set<TrustContinuousMonitoringFailure>(["STAGE_1_TRUST_FOUNDATION_INVALID", "STAGE_2_CONSTITUTIONAL_GATE_INVALID", "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID", "STAGE_4_INDEPENDENT_EVALUATION_INVALID", "STAGE_5_TRUST_RESOLUTION_INVALID", "STAGE_6_EXPLAINABILITY_INVALID", "STAGE_7_HUMAN_OVERSIGHT_INVALID", "MONITORING_CADENCE_NONDETERMINISTIC", "HEALTH_CALCULATION_NONDETERMINISTIC", "MONITORING_ATTEMPTED_STANDING_CHANGE", "MONITORING_PERFORMED_TRUST_EVALUATION", "MONITORING_RESOLVED_TRUST_DECISION", "MONITORING_OVERRIDDEN_CONSTITUTIONAL_DECISION", "MONITORING_APPLIED_RESTRICTIONS", "MONITORING_MADE_RECOVERY_DECISION", "HEALTH_METRIC_OVERRIDES_DECISION", "BEHAVIORAL_MONITORING_DETERMINED_OUTCOME", "MONITORING_EVIDENCE_MUTABLE", "MONITORING_EVENT_NOT_TRACEABLE", "MONITORING_REPLAY_DIVERGED"]);
  if (failures.some((failure) => failClosed.has(failure))) return "FAIL_CLOSED";
  if (has(failures, "CONTINUOUS_MONITORING_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP" || scenario === "QUALIFIED_WITH_OBSERVATIONS") return "CONDITIONALLY_QUALIFIED";
  return "CONTINUOUS_MONITORING_QUALIFIED";
}
function resultReplayHash(result: Omit<TrustContinuousMonitoringResult, "replay_hash" | "integrity_hash">): string { return hash({ monitoring: result.monitoring.integrity_hash, health: result.health.integrity_hash, standing: result.standing.integrity_hash, freshness: result.freshness.integrity_hash, behavior: result.behavior.integrity_hash, events: result.events.integrity_hash, evidence: result.evidence.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<TrustContinuousMonitoringResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runTrustContinuousMonitoringStageEight(input: TrustContinuousMonitoringInput = {}): TrustContinuousMonitoringResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  const scenarioFailures = freezeArray<TrustContinuousMonitoringFailure>(direct ? [direct] : []);
  baselines ??= makeBaselines();
  const failures = freezeArray([...new Set([...scenarioFailures, ...(!validateTrustFoundationStageOne(baselines.foundation).valid ? ["STAGE_1_TRUST_FOUNDATION_INVALID" as const] : []), ...(!validateConstitutionalComplianceGate(baselines.gate).valid ? ["STAGE_2_CONSTITUTIONAL_GATE_INVALID" as const] : []), ...(!validateTrustRegistryDomains(baselines.registry).valid ? ["STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" as const] : []), ...(!validateTrustIndependentEvaluation(baselines.evaluation).valid ? ["STAGE_4_INDEPENDENT_EVALUATION_INVALID" as const] : []), ...(!validateTrustResolutionEngine(baselines.resolution).valid ? ["STAGE_5_TRUST_RESOLUTION_INVALID" as const] : []), ...(!validateTrustExplainabilityStageSix(baselines.explainability).valid ? ["STAGE_6_EXPLAINABILITY_INVALID" as const] : []), ...(!validateTrustHumanOversightStageSeven(baselines.oversight).valid ? ["STAGE_7_HUMAN_OVERSIGHT_INVALID" as const] : [])])]);
  const monitoringOk = !has(failures, "MONITORING_ENGINE_MISSING") && !has(failures, "MONITORING_SCHEDULER_MISSING") && !has(failures, "MONITORING_REGISTRY_MISSING") && !has(failures, "MONITORING_EVIDENCE_MISSING") && !has(failures, "MONITORING_CADENCE_NONDETERMINISTIC") && !has(failures, "ACTIVE_TRUST_ENTITIES_NOT_MONITORED") && !has(failures, "MONITORING_REPLAY_MISSING");
  const healthOk = !has(failures, "TRUST_HEALTH_ENGINE_MISSING") && !has(failures, "HEALTH_SCORE_MISSING") && !has(failures, "STABILITY_INDICATORS_MISSING") && !has(failures, "OPERATIONAL_METRICS_MISSING") && !has(failures, "CONSTITUTIONAL_HEALTH_VALIDATION_MISSING") && !has(failures, "HEALTH_TRENDS_MISSING") && !has(failures, "HEALTH_EVIDENCE_MISSING") && !has(failures, "HEALTH_CALCULATION_NONDETERMINISTIC");
  const standingOk = !has(failures, "STANDING_MONITOR_MISSING") && !has(failures, "STANDING_CONSISTENCY_MISSING") && !has(failures, "STANDING_AGING_MISSING") && !has(failures, "STANDING_TRANSITION_OBSERVATION_MISSING") && !has(failures, "STANDING_HISTORY_MISSING") && !has(failures, "STANDING_EVIDENCE_MISSING") && !has(failures, "MONITORING_ATTEMPTED_STANDING_CHANGE");
  const freshnessOk = !has(failures, "EVIDENCE_FRESHNESS_SERVICE_MISSING") && !has(failures, "EVIDENCE_AGE_VALIDATION_MISSING") && !has(failures, "EXPIRATION_MONITORING_MISSING") && !has(failures, "MISSING_EVIDENCE_DETECTION_MISSING") && !has(failures, "STALE_EVIDENCE_IDENTIFICATION_MISSING") && !has(failures, "FRESHNESS_REPORTING_MISSING");
  const behaviorOk = !has(failures, "BEHAVIORAL_MONITORING_ENGINE_MISSING") && !has(failures, "EXPECTED_BEHAVIOR_VALIDATION_MISSING") && !has(failures, "BEHAVIORAL_ANOMALY_DETECTION_MISSING") && !has(failures, "BEHAVIORAL_TREND_MONITORING_MISSING") && !has(failures, "BEHAVIORAL_EVIDENCE_MISSING") && !has(failures, "BEHAVIORAL_REPORTING_MISSING") && !has(failures, "BEHAVIORAL_MONITORING_DETERMINED_OUTCOME");
  const eventsOk = !has(failures, "MONITORING_EVENT_SERVICE_MISSING") && !has(failures, "EVENT_CLASSIFICATION_MISSING") && !has(failures, "EVENT_LINEAGE_MISSING") && !has(failures, "EVENT_TIMESTAMPING_MISSING") && !has(failures, "IMMUTABLE_EVENT_RECORDING_MISSING") && !has(failures, "EVENT_REPLAY_MISSING") && !has(failures, "MONITORING_EVENT_NOT_TRACEABLE");
  const evidenceOk = !has(failures, "MONITORING_EVIDENCE_MUTABLE") && monitoringOk && healthOk && standingOk && freshnessOk && behaviorOk && eventsOk;
  const observationalOk = !has(failures, "MONITORING_PERFORMED_TRUST_EVALUATION") && !has(failures, "MONITORING_RESOLVED_TRUST_DECISION") && !has(failures, "MONITORING_OVERRIDDEN_CONSTITUTIONAL_DECISION") && !has(failures, "MONITORING_APPLIED_RESTRICTIONS") && !has(failures, "MONITORING_MADE_RECOVERY_DECISION") && !has(failures, "HEALTH_METRIC_OVERRIDES_DECISION");
  const deterministicOk = monitoringOk && healthOk && !has(failures, "MONITORING_REPLAY_DIVERGED");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "CONTINUOUS_MONITORING_QUALIFIED";
  const tenant_id = input.tenant_id ?? baselines.oversight.tenant_id;
  const monitoring_id = input.monitoring_id ?? `continuous-monitoring:stage-8:${input.seed ?? "canonical"}`;
  const monitoring = nested({ monitoring_id: monitoringOk ? "monitoring:stage-8:continuous" : "", trust_monitoring_engine: monitoringOk, monitoring_scheduler: monitoringOk, monitoring_registry: monitoringOk, active_trust_entities_monitored: monitoringOk, lifecycle_activity_observed: monitoringOk, monitoring_intervals_tracked: monitoringOk, monitoring_evidence_collected: monitoringOk, monitoring_state_published: monitoringOk, deterministic_cadence: monitoringOk, replay_verified: monitoringOk });
  const health = nested({ health_id: healthOk ? "health:stage-8:trust" : "", health_score: healthOk ? 100 : 0, classification: healthOk ? "HEALTHY" as const : "CRITICAL" as const, trust_health_engine: healthOk, health_score_computation: healthOk, stability_indicators: healthOk, operational_health_metrics: healthOk, constitutional_health_validation: healthOk, health_trend_analysis: healthOk, health_evidence_generation: healthOk, deterministic_calculation: healthOk, trends_reproducible: healthOk });
  const standing = nested({ standing_id: standingOk ? "standing:stage-8:monitor" : "", standing_observation: standingOk, standing_consistency_checks: standingOk, standing_aging: standingOk, standing_transition_observation: standingOk, standing_history: standingOk, standing_metrics: standingOk, standing_evidence: standingOk, transition_history_complete: standingOk, evidence_replay_validated: standingOk, standing_modified: false as const });
  const freshness = nested({ freshness_id: freshnessOk ? "freshness:stage-8:evidence" : "", evidence_age_validation: freshnessOk, expiration_monitoring: freshnessOk, evidence_lifecycle_observation: freshnessOk, missing_evidence_detection: freshnessOk, stale_evidence_identification: freshnessOk, freshness_reporting: freshnessOk, evidence_freshness_verified: freshnessOk, expiration_detected: freshnessOk, replay_deterministic: freshnessOk });
  const behavior = nested({ behavior_id: behaviorOk ? "behavior:stage-8:monitor" : "", behavioral_monitoring_engine: behaviorOk, behavioral_observation: behaviorOk, expected_behavior_validation: behaviorOk, behavioral_anomaly_detection: behaviorOk, trend_monitoring: behaviorOk, behavioral_evidence: behaviorOk, behavioral_reporting: behaviorOk, independently_determines_trust_outcome: false as const, monitoring_reproducible: behaviorOk });
  const events = nested({ event_id: eventsOk ? "events:stage-8:monitoring" : "", event_severities: eventsOk ? freezeArray(EVENT_SEVERITIES) : freezeArray<MonitoringEventSeverity>([]), monitoring_event_service: eventsOk, event_generation: eventsOk, event_classification: eventsOk, event_lineage: eventsOk, event_timestamping: eventsOk, immutable_event_recording: eventsOk, event_registry: eventsOk, event_log: eventsOk, replay_support: eventsOk, traceable: eventsOk });
  const evidence = nested({ evidence_id: evidenceOk ? "evidence:stage-8:monitoring" : "", monitoring_evidence: evidenceOk, health_evidence: evidenceOk, behavioral_evidence: evidenceOk, standing_evidence: evidenceOk, freshness_evidence: evidenceOk, event_evidence: evidenceOk, immutable_storage: evidenceOk, evidence_hashing: evidenceOk, replayable: evidenceOk, certification_ready: evidenceOk });
  const readiness = nested({ readiness_id: "STAGE-8-CONTINUOUS-MONITORING-READINESS-001", decision, phase_ready: qualified, upstream_ready: failures.every((failure) => !failure.startsWith("STAGE_")), monitoring_ready: monitoringOk, health_ready: healthOk, standing_ready: standingOk, freshness_ready: freshnessOk, behavioral_ready: behaviorOk, events_ready: eventsOk, evidence_ready: evidenceOk, observational_only: observationalOk, no_standing_modification: standing.standing_modified === false, no_decision_override: !has(failures, "MONITORING_OVERRIDDEN_CONSTITUTIONAL_DECISION") && !has(failures, "HEALTH_METRIC_OVERRIDES_DECISION"), no_restriction_application: !has(failures, "MONITORING_APPLIED_RESTRICTIONS"), no_recovery_decision: !has(failures, "MONITORING_MADE_RECOVERY_DECISION"), deterministic: deterministicOk, replayable: evidenceOk && eventsOk && !has(failures, "MONITORING_REPLAY_DIVERGED"), immutable_evidence: evidenceOk, traceable_events: eventsOk, certification_ready: evidenceOk && observationalOk, failures });
  const base: Omit<TrustContinuousMonitoringResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id, monitoring_id, monitoring, health, standing, freshness, behavior, events, evidence, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustContinuousMonitoringStageEight(result?: TrustContinuousMonitoringResult): TrustContinuousMonitoringValidation {
  if (!result) return nested({ valid: false, decision: "FAIL_CLOSED" as const, replay_hash_valid: false, integrity_hash_valid: false, monitoring_valid: false, health_valid: false, standing_valid: false, freshness_valid: false, behavior_valid: false, events_valid: false, evidence_valid: false, readiness_valid: false, failures: freezeArray(["MONITORING_ENGINE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const monitoring_valid = verifyHashed(result.monitoring) && result.monitoring.trust_monitoring_engine && result.monitoring.active_trust_entities_monitored && result.monitoring.deterministic_cadence && result.monitoring.replay_verified;
  const health_valid = verifyHashed(result.health) && result.health.health_score_computation && result.health.constitutional_health_validation && result.health.deterministic_calculation && result.health.trends_reproducible && result.health.health_score >= 0;
  const standing_valid = verifyHashed(result.standing) && result.standing.standing_observation && result.standing.transition_history_complete && result.standing.evidence_replay_validated && result.standing.standing_modified === false;
  const freshness_valid = verifyHashed(result.freshness) && result.freshness.evidence_age_validation && result.freshness.expiration_monitoring && result.freshness.evidence_freshness_verified && result.freshness.replay_deterministic;
  const behavior_valid = verifyHashed(result.behavior) && result.behavior.behavioral_monitoring_engine && result.behavior.behavioral_anomaly_detection && result.behavior.monitoring_reproducible && result.behavior.independently_determines_trust_outcome === false;
  const events_valid = verifyHashed(result.events) && result.events.event_severities.length === 4 && result.events.event_classification && result.events.immutable_event_recording && result.events.traceable;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.monitoring_evidence && result.evidence.health_evidence && result.evidence.immutable_storage && result.evidence.replayable;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.observational_only && result.readiness.no_standing_modification && result.readiness.no_decision_override && result.readiness.no_restriction_application && result.readiness.no_recovery_decision && result.readiness.deterministic && result.readiness.replayable && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && monitoring_valid && health_valid && standing_valid && freshness_valid && behavior_valid && events_valid && evidence_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, monitoring_valid, health_valid, standing_valid, freshness_valid, behavior_valid, events_valid, evidence_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayTrustContinuousMonitoringStageEight(result = runTrustContinuousMonitoringStageEight()): boolean { const replayed = runTrustContinuousMonitoringStageEight(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustContinuousMonitoringStageEight(result).valid; }
export function getTrustContinuousMonitoringStageEightBundle(): TrustContinuousMonitoringBundle { const result = runTrustContinuousMonitoringStageEight(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, observational_only: true, never_changes_trust_standing: true, immutable_monitoring_evidence_required: true, deterministic_replay_required: true, health_never_overrides_constitutional_decisions: true, behavioral_monitoring_never_decides_outcomes: true, qualification_gate: "Stage 8 Continuous Monitoring Qualification Gate" }), result, validation: validateTrustContinuousMonitoringStageEight(result) }); }
export const TrustContinuousMonitoringStageEightService = Object.freeze({ run: runTrustContinuousMonitoringStageEight, validate: validateTrustContinuousMonitoringStageEight, replay: replayTrustContinuousMonitoringStageEight });
