import { randomUUID } from "node:crypto";
import { z } from "zod";
import { getSessionUser } from "@/src/lib/auth";
import { AppError } from "@/src/server/api/errors";
import { apiError, apiSuccess } from "@/src/server/api/response";
import { requireWorkspaceManager } from "@/src/server/auth/permissions";
import { PrismaLearningAuditLedger, PrismaSelfDirectedLearningArtifactRepository, PrismaStrategyRegistryRepository, StrategyApprovalBridgeService, StrategySelectionRecordService } from "@/services/learning-constitution";
import type { LearningObjectiveProfile, StrategyCurriculumProposal, StrategySelectionRecord } from "@/types/learning-constitution";
export const dynamic = "force-dynamic";
const schema = z.object({ curriculumProposalId: z.string().min(1).max(200), maximumQuestions: z.number().int().min(1).max(1000), estimatedQuestions: z.number().int().min(1).max(1000), estimatedMinutes: z.number().int().min(1).max(10080), expiresAt: z.string().datetime(), currentState: z.enum(["KNOWN", "PARTIALLY_KNOWN", "UNCERTAIN", "CONFLICTING", "UNKNOWN", "UNTESTED"]), impact: z.enum(["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"]) });
/** Explicit human approval only. This records the Phase 26 proposal and matching Phase 28 lease; it does not itself execute the curriculum. */
export async function POST(request: Request) { try { const user = await getSessionUser(); if (!user) throw new AppError(401, "unauthorized", "Authentication required."); if (!user.workspaceId || user.workspaceId === "default") throw new AppError(403, "workspace_required", "Workspace membership is required."); await requireWorkspaceManager({ userId: user.id, userRole: user.role, workspaceId: user.workspaceId }); const body = schema.parse(await request.json()); const registry = new PrismaStrategyRegistryRepository(user.workspaceId); const artifacts = await registry.listWorkspaceArtifacts(); const proposalArtifact = artifacts.find((item) => item.artifactType === "STRATEGY_CURRICULUM_PROPOSAL" && (item.payload as StrategyCurriculumProposal).proposalId === body.curriculumProposalId); if (!proposalArtifact) throw new AppError(404, "curriculum_proposal_not_found", "Strategy curriculum proposal not found."); const proposal = proposalArtifact.payload as StrategyCurriculumProposal; const selectionArtifact = artifacts.find((item) => item.artifactType === "PHASE40_SELECTION" && (item.payload as StrategySelectionRecord).selectionId === proposal.selectionId); const objectiveArtifact = artifacts.find((item) => item.artifactType === "OBJECTIVE_PROFILE" && (item.payload as LearningObjectiveProfile).profileId === proposal.objectiveProfileId); if (!selectionArtifact || !objectiveArtifact) throw new AppError(409, "proposal_lineage_incomplete", "Strategy proposal lineage is incomplete."); const now = new Date().toISOString(); const actor = { actorId: `human:${user.id}`, actorType: "HUMAN" as const }; const correlationId = `strategy-approval:${body.curriculumProposalId}:${randomUUID()}`; const result = await new StrategyApprovalBridgeService(new PrismaSelfDirectedLearningArtifactRepository(user.workspaceId), new PrismaLearningAuditLedger(user.workspaceId)).approve({ bridgeId: `SAB-${randomUUID()}`, proposal, selection: selectionArtifact.payload as StrategySelectionRecord, objective: objectiveArtifact.payload as LearningObjectiveProfile, actor, maximumQuestions: body.maximumQuestions, estimatedQuestions: body.estimatedQuestions, estimatedMinutes: body.estimatedMinutes, expiresAt: body.expiresAt, currentState: body.currentState, impact: body.impact, createdAt: now, workspaceId: user.workspaceId, correlationId }); await new StrategySelectionRecordService(registry, new PrismaLearningAuditLedger(user.workspaceId)).approvalBridge(result.bridge, user.workspaceId, correlationId); return apiSuccess({ bridge: result.bridge, learningProposal: result.learningProposal, lease: result.lease, next: "The approved lease may now be consumed only by the existing governed execution and Curriculum Planner workflows." }, { status: 201 }); } catch (error) { return apiError(error, "Unable to approve strategy curriculum proposal."); } }
