export type PolicyDecisionExplainerErrorCode =
  | "POLICY_EXPLAINER_REPO_CONTEXT_MISSING"
  | "POLICY_DECISION_NOT_FOUND"
  | "POLICY_REASONING_UNAVAILABLE"
  | "POLICY_ACTIVATION_MISSING"
  | "POLICY_APPROVAL_REASONING_MISSING"
  | "POLICY_CONSTRAINT_UNAVAILABLE"
  | "POLICY_RISK_REASONING_UNAVAILABLE"
  | "POLICY_EXPLANATION_NONDETERMINISTIC"
  | "POLICY_REPLAY_REASONING_UNAVAILABLE"
  | "POLICY_ENFORCEMENT_CHAIN_INVALID"
  | "POLICY_EXPLANATION_HASH_INVALID"
  | "POLICY_SOURCE_TRACE_MISSING"
  | "POLICY_SOURCE_TRUTH_MISSING"
  | "POLICY_MUTATION_FORBIDDEN"
  | "POLICY_UNSUPPORTED_SOURCE_ARTIFACT";

export type PolicyDecisionExplainerError = Readonly<{
  code: PolicyDecisionExplainerErrorCode;
  message: string;
  path?: string;
  expected?: unknown;
  actual?: unknown;
}>;
