import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runWaveFiveCalendarTime, validateWaveFiveCalendarTime } from "@/services/wave-five-calendar-time";
import type { WaveFiveTasksCommitmentsBundle, WaveFiveTasksCommitmentsDecision, WaveFiveTasksCommitmentsFailure, WaveFiveTasksCommitmentsInput, WaveFiveTasksCommitmentsResult, WaveFiveTasksCommitmentsScenario, WaveFiveTasksCommitmentsValidation } from "@/types/wave-five-tasks-commitments";

const VERSION = "wave-five-tasks-commitments/w5.5" as const;
const IDENTIFIER = "WaveFiveTasksCommitments" as const;
const UPSTREAM_REFS = Object.freeze(["wave-five-calendar-time/w5.4", "wave-five-personal-knowledge/w5.3", "wave-five-unified-personal-context/w5.2"]);
const PROVIDES = Object.freeze(["task-registry", "commitment-registry", "planning-engine", "plan-generator", "priority-engine", "scheduling-engine", "lifecycle-engine", "work-queue", "dependency-graph", "weekly-review", "audit-service", "evidence-registry"]);
let calendar = runWaveFiveCalendarTime();

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly WaveFiveTasksCommitmentsFailure[], failure: WaveFiveTasksCommitmentsFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: WaveFiveTasksCommitmentsScenario): WaveFiveTasksCommitmentsFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly WaveFiveTasksCommitmentsFailure[], scenario?: WaveFiveTasksCommitmentsScenario): WaveFiveTasksCommitmentsDecision {
  const notQualified = new Set<WaveFiveTasksCommitmentsFailure>(["W5_CALENDAR_TIME_INVALID", "TASK_IDENTITIES_NONDETERMINISTIC", "TASK_RELATIONSHIPS_INVALID", "COMMITMENTS_NOT_INDEPENDENT", "COMMITMENT_LIFECYCLE_NONDETERMINISTIC", "PLANS_NONREPRODUCIBLE", "PLAN_DEPENDENCIES_INVALID", "CAPACITY_NOT_RESPECTED", "TASK_STATE_TRANSITIONS_INVALID", "TASK_REPLAY_DIVERGED", "PRIORITIES_NONREPRODUCIBLE", "SCHEDULING_NONDETERMINISTIC", "CAPACITY_NOT_ENFORCED", "REVIEWS_NONREPRODUCIBLE", "CIRCULAR_DEPENDENCIES_ALLOWED", "SYNCHRONIZATION_INVALID", "EVIDENCE_MUTABLE", "TASK_LINEAGE_INCOMPLETE", "COMMITMENT_LINEAGE_INCOMPLETE", "GOVERNANCE_BYPASS_DETECTED", "TENANT_ISOLATION_BREACH"]);
  if (failures.some((failure) => notQualified.has(failure))) return "NOT_QUALIFIED";
  if (has(failures, "TASKS_COMMITMENTS_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_QUALIFIED";
  return "QUALIFIED";
}
function resultReplayHash(result: Omit<WaveFiveTasksCommitmentsResult, "replay_hash" | "integrity_hash">): string { return hash({ tasks: result.tasks.integrity_hash, commitments: result.commitments.integrity_hash, planning: result.planning.integrity_hash, lifecycle: result.lifecycle.integrity_hash, prioritization_scheduling: result.prioritization_scheduling.integrity_hash, weekly_review: result.weekly_review.integrity_hash, dependencies: result.dependencies.integrity_hash, integration_governance: result.integration_governance.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<WaveFiveTasksCommitmentsResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runWaveFiveTasksCommitments(input: WaveFiveTasksCommitmentsInput = {}): WaveFiveTasksCommitmentsResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  calendar = runWaveFiveCalendarTime();
  const failures = freezeArray([...new Set([...(direct ? [direct] : []), ...(!validateWaveFiveCalendarTime(calendar).valid ? ["W5_CALENDAR_TIME_INVALID" as const] : [])])]);
  const tasksOk = !has(failures, "TASK_REGISTRY_MISSING") && !has(failures, "TASK_IDENTITIES_NONDETERMINISTIC") && !has(failures, "TASK_RELATIONSHIPS_INVALID") && !has(failures, "TASK_APIS_UNCERTIFIED") && !has(failures, "TASK_OWNERSHIP_MISSING");
  const commitmentsOk = !has(failures, "COMMITMENT_REGISTRY_MISSING") && !has(failures, "COMMITMENTS_NOT_INDEPENDENT") && !has(failures, "COMMITMENT_LIFECYCLE_NONDETERMINISTIC") && !has(failures, "COMMITMENT_OWNERSHIP_INVALID") && !has(failures, "COMMITMENT_HISTORY_INCOMPLETE");
  const planningOk = !has(failures, "PLANNING_ENGINE_MISSING") && !has(failures, "PLANS_NONREPRODUCIBLE") && !has(failures, "PLAN_DEPENDENCIES_INVALID") && !has(failures, "CAPACITY_NOT_RESPECTED") && !has(failures, "PLAN_VALIDATION_MISSING");
  const lifecycleOk = !has(failures, "TASK_LIFECYCLE_MISSING") && !has(failures, "TASK_STATE_TRANSITIONS_INVALID") && !has(failures, "TASK_HISTORY_INCOMPLETE") && !has(failures, "TASK_REPLAY_DIVERGED");
  const priorityOk = !has(failures, "PRIORITY_ENGINE_MISSING") && !has(failures, "PRIORITIES_NONREPRODUCIBLE") && !has(failures, "SCHEDULING_NONDETERMINISTIC") && !has(failures, "CONFLICT_DETECTION_MISSING") && !has(failures, "CAPACITY_NOT_ENFORCED");
  const reviewOk = !has(failures, "WEEKLY_REVIEW_MISSING") && !has(failures, "REVIEWS_NONREPRODUCIBLE") && !has(failures, "CARRY_FORWARD_INVALID") && !has(failures, "HISTORICAL_REVIEWS_MISSING");
  const dependenciesOk = !has(failures, "DEPENDENCY_GRAPH_MISSING") && !has(failures, "CIRCULAR_DEPENDENCIES_ALLOWED") && !has(failures, "READINESS_NOT_VALIDATED") && !has(failures, "CRITICAL_PATH_MISSING");
  const governanceOk = !has(failures, "CROSS_APPLICATION_INTEGRATION_MISSING") && !has(failures, "INTEGRATION_EVENTS_NONDETERMINISTIC") && !has(failures, "SYNCHRONIZATION_INVALID") && !has(failures, "INTEGRATION_CONTRACTS_UNCERTIFIED") && !has(failures, "AUDIT_TRAIL_MISSING") && !has(failures, "EVIDENCE_MUTABLE") && !has(failures, "TASK_LINEAGE_INCOMPLETE") && !has(failures, "COMMITMENT_LINEAGE_INCOMPLETE") && !has(failures, "GOVERNANCE_BYPASS_DETECTED") && !has(failures, "TENANT_ISOLATION_BREACH");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "QUALIFIED";
  const tasks = nested({ task_id: tasksOk ? "W5.5-TASK-FOUNDATION-001" : "", task_identity: tasksOk, task_registry: tasksOk, task_metadata: tasksOk, task_categories: tasksOk, task_templates: tasksOk, task_relationships: tasksOk, parent_child_tasks: tasksOk, dependency_tracking: tasksOk, task_tags: tasksOk, task_ownership: tasksOk, identities_deterministic: tasksOk, relationships_validated: tasksOk, registry_operational: tasksOk, apis_certified: tasksOk });
  const commitments = nested({ commitment_id: commitmentsOk ? "W5.5-COMMITMENT-MANAGEMENT-001" : "", commitment_registry: commitmentsOk, personal_commitments: commitmentsOk, organizational_commitments: commitmentsOk, delegated_commitments: commitmentsOk, commitment_lifecycle: commitmentsOk, due_date_management: commitmentsOk, commitment_priorities: commitmentsOk, commitment_status: commitmentsOk, commitment_ownership: commitmentsOk, commitment_history: commitmentsOk, independently_managed: commitmentsOk, lifecycle_deterministic: commitmentsOk, ownership_validated: commitmentsOk, history_complete: commitmentsOk });
  const planning = nested({ planning_id: planningOk ? "W5.5-PLANNING-ENGINE-001" : "", goal_breakdown: planningOk, task_generation: planningOk, milestone_planning: planningOk, dependency_planning: planningOk, work_sequencing: planningOk, priority_calculation: planningOk, capacity_planning: planningOk, time_estimation: planningOk, plan_optimization: planningOk, plan_validation: planningOk, plans_reproducible: planningOk, dependencies_validated: planningOk, capacity_respected: planningOk, deterministic: planningOk });
  const lifecycle = nested({ lifecycle_id: lifecycleOk ? "W5.5-TASK-LIFECYCLE-001" : "", task_creation: lifecycleOk, assignment: lifecycleOk, scheduling: lifecycleOk, progress_tracking: lifecycleOk, status_changes: lifecycleOk, blocked_states: lifecycleOk, waiting_states: lifecycleOk, completion_processing: lifecycleOk, cancellation: lifecycleOk, archiving: lifecycleOk, deterministic: lifecycleOk, transitions_validated: lifecycleOk, history_complete: lifecycleOk, replay_identical: lifecycleOk });
  const prioritization_scheduling = nested({ priority_id: priorityOk ? "W5.5-PRIORITY-SCHEDULING-001" : "", priority_engine: priorityOk, importance_scoring: priorityOk, urgency_scoring: priorityOk, deadline_evaluation: priorityOk, capacity_allocation: priorityOk, daily_planning: priorityOk, weekly_planning: priorityOk, work_queue: priorityOk, scheduling_rules: priorityOk, conflict_detection: priorityOk, priorities_reproducible: priorityOk, scheduling_deterministic: priorityOk, conflicts_detected: priorityOk, capacity_enforced: priorityOk });
  const weekly_review = nested({ review_id: reviewOk ? "W5.5-WEEKLY-REVIEW-001" : "", weekly_dashboard: reviewOk, completed_tasks: reviewOk, outstanding_commitments: reviewOk, deferred_work: reviewOk, carry_forward: reviewOk, wins: reviewOk, lessons_learned: reviewOk, planning_review: reviewOk, capacity_review: reviewOk, goal_alignment_review: reviewOk, reviews_reproducible: reviewOk, reports_generated: reviewOk, carry_forward_validated: reviewOk, historical_reviews_retained: reviewOk });
  const dependencies = nested({ dependency_id: dependenciesOk ? "W5.5-DEPENDENCY-GRAPH-001" : "", dependency_graph: dependenciesOk, blocking_relationships: dependenciesOk, sequential_tasks: dependenciesOk, parallel_tasks: dependenciesOk, milestone_dependencies: dependenciesOk, critical_path: dependenciesOk, automatic_readiness: dependenciesOk, dependency_validation: dependenciesOk, circular_dependency_detection: dependenciesOk, graph_complete: dependenciesOk, circular_dependencies_prevented: dependenciesOk, readiness_validated: dependenciesOk, critical_path_generated: dependenciesOk });
  const integration_governance = nested({ governance_id: governanceOk ? "W5.5-INTEGRATION-GOVERNANCE-001" : "", calendar_integration: governanceOk, context_integration: governanceOk, knowledge_integration: governanceOk, notification_integration: governanceOk, collaboration_integration: governanceOk, cross_application_events: governanceOk, integration_contracts: governanceOk, audit_trail: governanceOk, evidence_capture: governanceOk, task_lineage: governanceOk, commitment_lineage: governanceOk, change_history: governanceOk, policy_enforcement: governanceOk, permissions: governanceOk, replay_support: governanceOk, reporting: governanceOk, tenant_isolation: governanceOk, evidence_immutable: governanceOk, governance_operational: governanceOk, synchronization_validated: governanceOk });
  const readiness = nested({ readiness_id: "W5.5-TASKS-COMMITMENTS-READINESS-001", decision, phase_ready: qualified, upstream_ready: !has(failures, "W5_CALENDAR_TIME_INVALID"), tasks_ready: tasksOk, commitments_ready: commitmentsOk, planning_ready: planningOk, lifecycle_ready: lifecycleOk, prioritization_scheduling_ready: priorityOk, weekly_review_ready: reviewOk, dependencies_ready: dependenciesOk, integration_governance_ready: governanceOk, every_task_registered: tasksOk, every_commitment_tracked: commitmentsOk, planning_deterministic: planningOk, lifecycle_replayable_auditable_governed: lifecycleOk && governanceOk, weekly_review_actionable: reviewOk, dependencies_priorities_schedules_validated: dependenciesOk && priorityOk, cross_application_integrations_operational: governanceOk, lineage_audit_governance_complete: governanceOk, constitutional_replay_evidence_tenant_isolation_satisfied: governanceOk, failures });
  const base: Omit<WaveFiveTasksCommitmentsResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id: input.tenant_id ?? calendar.tenant_id, principal_id: input.principal_id ?? calendar.principal_id, workspace_id: input.workspace_id ?? "tasks-workspace:w5.5:canonical", tasks, commitments, planning, lifecycle, prioritization_scheduling, weekly_review, dependencies, integration_governance, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateWaveFiveTasksCommitments(result?: WaveFiveTasksCommitmentsResult): WaveFiveTasksCommitmentsValidation {
  if (!result) return nested({ valid: false, decision: "NOT_QUALIFIED" as const, replay_hash_valid: false, integrity_hash_valid: false, tasks_valid: false, commitments_valid: false, planning_valid: false, lifecycle_valid: false, prioritization_scheduling_valid: false, weekly_review_valid: false, dependencies_valid: false, integration_governance_valid: false, readiness_valid: false, failures: freezeArray(["TASK_REGISTRY_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const tasks_valid = verifyHashed(result.tasks) && result.tasks.identities_deterministic && result.tasks.relationships_validated && result.tasks.registry_operational && result.tasks.apis_certified;
  const commitments_valid = verifyHashed(result.commitments) && result.commitments.independently_managed && result.commitments.lifecycle_deterministic && result.commitments.ownership_validated && result.commitments.history_complete;
  const planning_valid = verifyHashed(result.planning) && result.planning.plans_reproducible && result.planning.dependencies_validated && result.planning.capacity_respected && result.planning.deterministic;
  const lifecycle_valid = verifyHashed(result.lifecycle) && result.lifecycle.deterministic && result.lifecycle.transitions_validated && result.lifecycle.history_complete && result.lifecycle.replay_identical;
  const prioritization_scheduling_valid = verifyHashed(result.prioritization_scheduling) && result.prioritization_scheduling.priorities_reproducible && result.prioritization_scheduling.scheduling_deterministic && result.prioritization_scheduling.conflicts_detected && result.prioritization_scheduling.capacity_enforced;
  const weekly_review_valid = verifyHashed(result.weekly_review) && result.weekly_review.reviews_reproducible && result.weekly_review.reports_generated && result.weekly_review.carry_forward_validated && result.weekly_review.historical_reviews_retained;
  const dependencies_valid = verifyHashed(result.dependencies) && result.dependencies.graph_complete && result.dependencies.circular_dependencies_prevented && result.dependencies.readiness_validated && result.dependencies.critical_path_generated;
  const integration_governance_valid = verifyHashed(result.integration_governance) && result.integration_governance.calendar_integration && result.integration_governance.context_integration && result.integration_governance.knowledge_integration && result.integration_governance.evidence_immutable && result.integration_governance.governance_operational && result.integration_governance.tenant_isolation;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.every_task_registered && result.readiness.every_commitment_tracked && result.readiness.planning_deterministic && result.readiness.constitutional_replay_evidence_tenant_isolation_satisfied && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && tasks_valid && commitments_valid && planning_valid && lifecycle_valid && prioritization_scheduling_valid && weekly_review_valid && dependencies_valid && integration_governance_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, tasks_valid, commitments_valid, planning_valid, lifecycle_valid, prioritization_scheduling_valid, weekly_review_valid, dependencies_valid, integration_governance_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayWaveFiveTasksCommitments(result = runWaveFiveTasksCommitments()): boolean { const replayed = runWaveFiveTasksCommitments(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateWaveFiveTasksCommitments(result).valid; }
export function getWaveFiveTasksCommitmentsBundle(): WaveFiveTasksCommitmentsBundle { const result = runWaveFiveTasksCommitments(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, commitments_are_first_class: true, tasks_require_deterministic_lifecycle: true, planning_must_be_replayable: true, evidence_lineage_required: true, tenant_isolation_required: true, governance_required: true, qualification_gate: "W5.5 Tasks and Commitments Qualification Gate" }), result, validation: validateWaveFiveTasksCommitments(result) }); }
export const WaveFiveTasksCommitmentsService = Object.freeze({ run: runWaveFiveTasksCommitments, validate: validateWaveFiveTasksCommitments, replay: replayWaveFiveTasksCommitments });
