import type { ValidationError } from "./validationContracts";

export const VALIDATION_ERROR_CODES = {
  PLAN_SCHEMA_INVALID: "PLAN_SCHEMA_INVALID",
  PLAN_ID_MISSING: "PLAN_ID_MISSING",
  PLAN_STEPS_MISSING: "PLAN_STEPS_MISSING",
  PLAN_EMPTY: "PLAN_EMPTY",
  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",
  TOOL_DISABLED: "TOOL_DISABLED",
  TOOL_SCHEMA_INVALID: "TOOL_SCHEMA_INVALID",
  TOOL_RISK_UNDECLARED: "TOOL_RISK_UNDECLARED",
  TOOL_APPROVAL_UNDECLARED: "TOOL_APPROVAL_UNDECLARED",
  GOVERNANCE_VALIDATION_FAILED: "GOVERNANCE_VALIDATION_FAILED",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  UNKNOWN_RISK_CLASS: "UNKNOWN_RISK_CLASS",
  INVALID_STEP_TYPE: "INVALID_STEP_TYPE",
  DUPLICATE_STEP_ID: "DUPLICATE_STEP_ID",
  EXECUTION_PATH_DETECTED: "EXECUTION_PATH_DETECTED",
  NON_DETERMINISTIC_VALIDATION: "NON_DETERMINISTIC_VALIDATION",
  VALIDATION_POLICY_VIOLATION: "VALIDATION_POLICY_VIOLATION",
  VALIDATION_RUNTIME_FAILURE: "VALIDATION_RUNTIME_FAILURE",
  VALIDATION_SNAPSHOT_CREATED: "VALIDATION_SNAPSHOT_CREATED",
  VALIDATION_SNAPSHOT_MISSING: "VALIDATION_SNAPSHOT_MISSING",
  VALIDATION_PLAN_HASH_MISMATCH: "VALIDATION_PLAN_HASH_MISMATCH",
  VALIDATION_GOVERNANCE_HASH_MISMATCH: "VALIDATION_GOVERNANCE_HASH_MISMATCH",
  VALIDATION_REPLAY_DRIFT_DETECTED: "VALIDATION_REPLAY_DRIFT_DETECTED",
  VALIDATION_REPLAY_FAILED: "VALIDATION_REPLAY_FAILED",
  VALIDATION_VERSION_MISMATCH: "VALIDATION_VERSION_MISMATCH",
  VALIDATION_EXECUTION_NOT_ELIGIBLE: "VALIDATION_EXECUTION_NOT_ELIGIBLE",
  VALIDATION_FREEZE_PROPAGATED: "VALIDATION_FREEZE_PROPAGATED",
  VALIDATION_CUMULATIVE_RISK_ESCALATED: "VALIDATION_CUMULATIVE_RISK_ESCALATED",
  VALIDATION_AUDIT_LINEAGE_MISSING: "VALIDATION_AUDIT_LINEAGE_MISSING",
  VALIDATION_CONSTITUTIONAL_FREEZE: "VALIDATION_CONSTITUTIONAL_FREEZE",
  VALIDATION_SNAPSHOT_IMMUTABILITY_VIOLATION: "VALIDATION_SNAPSHOT_IMMUTABILITY_VIOLATION",
} as const;

export function makeValidationError(input: ValidationError): ValidationError {
  return {
    ...input,
  };
}
