import { getSessionUser } from "@/src/lib/auth";
import { AppError } from "@/src/server/api/errors";
import { apiError, apiSuccess } from "@/src/server/api/response";
import { requireWorkspaceManager } from "@/src/server/auth/permissions";
import { EvaluationReflectionEvidenceCollector, PrismaEvaluationArtifactRepository, PrismaLearningAuditLedger, PrismaReflectionArtifactRepository, ReflectionArtifactService, ReflectionFailureLocalizationService } from "@/services/learning-constitution";
import type { Evaluation, ReflectionCase } from "@/types/learning-constitution";
export const dynamic = "force-dynamic";
const userFor = async () => { const user = await getSessionUser(); if (!user) throw new AppError(401, "unauthorized", "Authentication required."); if (!user.workspaceId || user.workspaceId === "default") throw new AppError(403, "workspace_required", "Workspace membership is required."); await requireWorkspaceManager({ userId: user.id, userRole: user.role, workspaceId: user.workspaceId }); return user; };
export async function GET() { try { const user = await userFor(); const artifacts = await new PrismaReflectionArtifactRepository(user.workspaceId!).listWorkspaceArtifacts(); return apiSuccess({ reflections: artifacts.filter((artifact) => artifact.artifactType === "CASE").map((artifact) => artifact.payload as ReflectionCase) }); } catch (error) { return apiError(error, "Unable to load reflection cases."); } }
export async function POST(request: Request) { try { const user = await userFor(); const { reflectionId, evaluationId } = await request.json() as { reflectionId?: string; evaluationId?: string }; if (!reflectionId?.trim() || !evaluationId?.trim()) throw new AppError(400, "reflection_invalid", "A reflection ID and failed evaluation ID are required."); const evaluations = new PrismaEvaluationArtifactRepository(user.workspaceId!); const artifacts = await evaluations.listWorkspaceArtifacts(); const evaluation = artifacts.find((artifact) => artifact.artifactType === "EVALUATION" && (artifact.payload as Evaluation).evaluationId === evaluationId)?.payload as Evaluation | undefined; if (!evaluation) throw new AppError(404, "evaluation_missing", "Evaluation was not found."); const collected = await new EvaluationReflectionEvidenceCollector(evaluations).collect(evaluationId); if (collected.validity.status !== "VALID" || (collected.score.outcome !== "FAIL" && collected.score.outcome !== "PARTIAL")) throw new AppError(409, "reflection_not_eligible", "Only valid failed or partial evaluations can create a reflection case."); const localized = new ReflectionFailureLocalizationService().localize(collected.failures); const now = new Date().toISOString(); const reflection: ReflectionCase = { reflectionId, trigger: "EVALUATION_FAILURE", evaluationId, skillId: evaluation.skillId, expectedOutcome: evaluation.expectedBehavior.join(" ") || "Expected evaluation behavior.", observedOutcome: evaluation.actualBehavior.join(" ") || "Observed evaluation behavior.", failureType: localized.failureType, failureLocation: localized.location, relevantKnowledgeIds: evaluation.context.allowedKnowledgeIds, relevantPrincipleIds: [], relevantProcedureIds: [], relevantExampleIds: evaluation.context.exposedExampleIds, relevantExceptionIds: [], prerequisiteSkillIds: [], status: "OPEN", createdBy: { actorId: `user:${user.id}`, actorType: "HUMAN" }, createdAt: now, resolvedAt: null, masteryEffect: "NONE", durableKnowledgeEffect: "NONE", executionPermissionGranted: false }; const service = new ReflectionArtifactService(new PrismaReflectionArtifactRepository(user.workspaceId!), new PrismaLearningAuditLedger(user.workspaceId!)); await service.createCase(reflection, user.workspaceId!, `reflection:${reflectionId}`); await service.recordEvidence(reflectionId, collected.evidence); return apiSuccess({ reflection, localized, evidence: collected.evidence }, { status: 201 }); } catch (error) { return apiError(error, "Unable to create reflection case."); } }
