import { z } from "zod";

import { createContractDefinition, getRegisteredContract, registerContract } from "./contractRegistry";
import { registerCompatibility } from "./compatibilityMatrix";

export function ensureDefaultContractsRegistered() {
  const contracts = [
    createContractDefinition({
      id: "api.v1.sam.proposal.request",
      version: "1.0.0",
      kind: "request",
      owner: "mission-control",
      schema: z.object({
        proposal: z.object({
          proposalId: z.string(),
          executionId: z.string(),
          attemptId: z.string(),
          actionType: z.enum([
            "recover_execution",
            "pause_execution",
            "resume_execution",
            "cancel_execution",
            "export_evidence",
            "add_operator_note",
            "inspect_state",
            "unknown",
          ]),
          requestedBy: z.enum(["ai", "operator", "system"]),
          reason: z.string(),
          riskLevel: z.enum(["low", "medium", "high", "critical"]),
          confidence: z.number().min(0).max(1),
          params: z.record(z.string(), z.unknown()),
          createdAt: z.string(),
        }).strict(),
        approval: z.object({
          status: z.enum(["required", "granted", "denied", "not_applicable"]),
          approvedBy: z.string().optional(),
          reason: z.string().optional(),
        }).strict().optional(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "high",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.execution.status.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        executionId: z.string(),
        status: z.string(),
        operatorAttention: z.boolean(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "medium",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.mission.state.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        mode: z.enum(["NORMAL", "ELEVATED", "THROTTLED", "DEGRADED", "RESTRICTED", "FROZEN"]),
        queueDepth: z.number(),
        degraded: z.boolean(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "medium",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.recovery.run.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        executionId: z.string(),
        dryRun: z.literal(true),
        timelineMatchesReadModel: z.boolean(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "high",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.backup.create.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        snapshotId: z.string(),
        status: z.enum(["ready", "partial", "corrupted", "missing"]),
        generatedAt: z.string().optional(),
        contractVersion: z.literal("v1"),
        contractHash: z.string(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "high",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.backup.status.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        snapshotId: z.string(),
        status: z.enum(["ready", "partial", "corrupted", "missing"]),
        generatedAt: z.string().optional(),
        contractVersion: z.literal("v1"),
        contractHash: z.string(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "medium",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.backup.validate.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        ready: z.boolean(),
        issues: z.array(z.string()),
        contractVersion: z.literal("v1"),
        contractHash: z.string(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "high",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.restore.dry_run.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        dryRun: z.literal(true),
        executed: z.literal(false),
        readiness: z.enum(["verified", "blocked"]),
        issues: z.array(z.string()).optional(),
        contractVersion: z.literal("v1"),
        contractHash: z.string(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "critical",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.restore.status.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        status: z.enum(["idle", "verified", "blocked"]),
        dryRun: z.literal(true),
        executed: z.literal(false),
        issues: z.array(z.string()).optional(),
        contractVersion: z.literal("v1"),
        contractHash: z.string(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "critical",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.integrity.report.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        ready: z.boolean(),
        issues: z.array(z.string()),
        contractVersion: z.literal("v1"),
        contractHash: z.string(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "high",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.observability.health.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        status: z.enum(["HEALTHY", "DEGRADED", "UNHEALTHY", "UNKNOWN"]),
        generatedAt: z.string(),
        components: z.array(z.object({
          name: z.enum(["contracts", "apiV1", "sam", "recovery", "verification", "locks", "telemetry"]),
          status: z.enum(["HEALTHY", "DEGRADED", "UNHEALTHY", "UNKNOWN"]),
          summary: z.string(),
          recommendedAction: z.string(),
          signals: z.array(z.string()),
        }).strict()),
        summary: z.string(),
        recommendedAction: z.string(),
        contractVersion: z.literal("v1"),
        contractHash: z.string(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "medium",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.observability.metrics.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        snapshotId: z.string(),
        generatedAt: z.string(),
        healthStatus: z.enum(["HEALTHY", "DEGRADED", "UNHEALTHY", "UNKNOWN"]),
        metrics: z.array(z.object({
          name: z.string(),
          value: z.union([z.number(), z.string(), z.null()]),
          unit: z.enum(["count", "ratio", "status", "ms"]),
          status: z.enum(["OK", "WARNING", "CRITICAL", "UNKNOWN"]),
          source: z.string(),
          measuredAt: z.string(),
          component: z.enum(["contracts", "apiV1", "sam", "recovery", "verification", "locks", "telemetry"]),
        }).strict()),
        sources: z.array(z.object({
          name: z.string(),
          status: z.enum(["AVAILABLE", "DEGRADED", "UNAVAILABLE"]),
          reason: z.string().optional(),
        }).strict()),
        degradedSignals: z.array(z.string()),
        unknownSignals: z.array(z.string()),
        contractVersion: z.literal("v1"),
        contractHash: z.string(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "medium",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
    createContractDefinition({
      id: "api.v1.observability.alerts.response",
      version: "1.0.0",
      kind: "response",
      owner: "mission-control",
      schema: z.object({
        generatedAt: z.string(),
        healthStatus: z.enum(["HEALTHY", "DEGRADED", "UNHEALTHY", "UNKNOWN"]),
        alerts: z.array(z.object({
          alertId: z.string(),
          ruleId: z.string(),
          severity: z.enum(["INFO", "WARNING", "HIGH", "CRITICAL", "EMERGENCY"]),
          status: z.enum(["ACTIVE", "ACKNOWLEDGED", "RESOLVED", "SUPPRESSED"]),
          reason: z.string(),
          metricName: z.string(),
          observedValue: z.union([z.number(), z.string(), z.boolean(), z.null()]),
          threshold: z.union([z.number(), z.string(), z.boolean(), z.null()]),
          triggeredAt: z.string(),
          correlationId: z.string(),
          source: z.string(),
          recommendedAction: z.string(),
        }).strict()),
        contractVersion: z.literal("v1"),
        contractHash: z.string(),
      }).strict(),
      governance: {
        approved: true,
        approvedBy: "codex",
        riskLevel: "medium",
        replayVerified: true,
        compatibilityVerified: true,
      },
    }),
  ];

  for (const contract of contracts) {
    if (!getRegisteredContract(contract.id, contract.version)) {
      registerContract(contract);
      registerCompatibility(contract.id, contract.version, [contract.version]);
    }
  }
}
