export type TelemetryErrorCode =
  | "ADVERSARIAL_TELEMETRY_REPLAY_DIVERGENCE"
  | "ADVERSARIAL_TELEMETRY_GOVERNANCE_MISMATCH"
  | "ADVERSARIAL_TELEMETRY_RECOMMENDATION_ANOMALY"
  | "ADVERSARIAL_TELEMETRY_APPROVAL_MISMATCH"
  | "ADVERSARIAL_TELEMETRY_ESCALATION_FAILURE"
  | "ADVERSARIAL_TELEMETRY_CONFIDENCE_VOLATILITY"
  | "ADVERSARIAL_TELEMETRY_CONTAINMENT_PRESSURE"
  | "ADVERSARIAL_TELEMETRY_VALIDATOR_DRIFT"
  | "ADVERSARIAL_TELEMETRY_MISSING_LINEAGE"
  | "ADVERSARIAL_TELEMETRY_FORENSIC_CORRUPTION"
  | "ADVERSARIAL_TELEMETRY_HIDDEN_ORCHESTRATION"
  | "ADVERSARIAL_TELEMETRY_PRIVILEGE_ESCALATION"
  | "ADVERSARIAL_TELEMETRY_RUNTIME_CONTAMINATION"
  | "ADVERSARIAL_TELEMETRY_SYNTHETIC_AUTHORITY"
  | "ADVERSARIAL_TELEMETRY_ISOLATION_VIOLATION"
  | "ADVERSARIAL_TELEMETRY_FAIL_CLOSED";

export type TelemetryError = Readonly<{
  code: TelemetryErrorCode;
  message: string;
  path?: string;
}>;
