export type MissionConsoleErrorCode =
  | "MISSION_CONSOLE_REPO_CONTEXT_MISSING"
  | "MISSION_CONSOLE_SOURCE_AUTHORITY_MISSING"
  | "MISSION_CONSOLE_UPSTREAM_DISPUTED"
  | "MISSION_CONSOLE_TIMELINE_UNAVAILABLE"
  | "MISSION_CONSOLE_REPLAY_UNAVAILABLE"
  | "MISSION_CONSOLE_DRIFT_UNAVAILABLE"
  | "MISSION_CONSOLE_GOVERNANCE_UNAVAILABLE"
  | "MISSION_CONSOLE_SNAPSHOT_UNAVAILABLE"
  | "MISSION_CONSOLE_DEPENDENCY_UNAVAILABLE"
  | "MISSION_CONSOLE_SIMULATION_UNAVAILABLE"
  | "MISSION_CONSOLE_RECOVERY_UNAVAILABLE"
  | "MISSION_CONSOLE_APPROVAL_UNAVAILABLE"
  | "MISSION_CONSOLE_UNKNOWN_STATE"
  | "MISSION_CONSOLE_MUTATION_FORBIDDEN"
  | "MISSION_CONSOLE_EXECUTION_FORBIDDEN"
  | "MISSION_CONSOLE_AUTONOMY_BYPASS_FORBIDDEN";

export type MissionConsoleError = Readonly<{
  code: MissionConsoleErrorCode;
  message: string;
  path?: string;
}>;
