import { describe, expect, it } from "vitest";
import { type CodexExecutionEvent, type CodexImplementationLedger, type VaultAuditEvent, type VaultRecord, vaultSchemaVersion } from "@/src/nuru/vault-contracts";
import { NuruBuildPackageExecutionService, type BuildPackageExecutionStore } from "@/src/server/services/nuru-build-package-execution-service";
import { NuruImplementationLedgerService, type ImplementationLedgerStore } from "@/src/server/services/nuru-implementation-ledger-service";

const at = "2026-10-01T12:00:00.000Z"; const correlationId = "c8d1df9a-ae91-4ea3-8718-9df8d6e9bc36";
const candidate = { schemaVersion: vaultSchemaVersion, id: "candidate", kind: "CANDIDATE" as const, classification: "PUBLIC" as const, createdAt: at, correlationId, evidenceIds: ["evidence"], interpretation: "fixture", confidence: .9, producedBy: "fixture", status: "APPROVED" as const };
const governance = { schemaVersion: vaultSchemaVersion, id: "governance", kind: "GOVERNANCE_DECISION" as const, classification: "PUBLIC" as const, createdAt: at, correlationId, candidateId: candidate.id, outcome: "APPROVED" as const, decidedBy: "human", decidedAt: at, rationale: "fixture", requiredHumanReview: true, humanApprovalId: "approval" };
const decision = { schemaVersion: vaultSchemaVersion, id: "decision", kind: "PROJECT_DECISION" as const, classification: "PUBLIC" as const, createdAt: at, correlationId, project: "NURU", question: "Question", decision: "Decision", rationale: "Fixture", alternatives: [], candidateId: candidate.id, governanceDecisionId: governance.id, decidedAt: at, version: 1, status: "CURRENT" as const };
const requirement = { schemaVersion: vaultSchemaVersion, id: "requirement", kind: "PROJECT_REQUIREMENT" as const, classification: "PUBLIC" as const, createdAt: at, correlationId, project: "NURU", title: "Requirement", description: "Traceable", priority: "HIGH" as const, acceptanceCriteria: ["Pass"], projectDecisionId: decision.id, implementationRefs: [], testRefs: ["test"], implementationStatus: "IN_PROGRESS" as const, candidateId: candidate.id, governanceDecisionId: governance.id, version: 1, status: "CURRENT" as const };
const buildPackage = { schemaVersion: vaultSchemaVersion, id: "package", kind: "CODEX_BUILD_PACKAGE" as const, classification: "PUBLIC" as const, createdAt: at, correlationId, project: "NURU", objective: "Implement lifecycle", requirementIds: [requirement.id], architectureDecisionIds: [decision.id], expectedFiles: [], interfaces: [], testRefs: ["test"], migrationNotes: [], dependencies: [], exitCriteria: ["Pass"], verificationCommands: ["test"], status: "PLANNED" as const, candidateId: candidate.id, governanceDecisionId: governance.id, version: 1 };
function memory(): BuildPackageExecutionStore & ImplementationLedgerStore & { records: VaultRecord[] } { const records: VaultRecord[] = [candidate, governance, decision, requirement, buildPackage]; return { records, readVaultRecords: async () => records, appendExecutionEvent: async (entry: CodexExecutionEvent) => { records.push(entry); }, appendImplementationLedger: async (entry: CodexImplementationLedger, audit: VaultAuditEvent) => { records.push(entry, audit); } }; }
describe("Nuru build lifecycle qualification", () => { it("carries a ready package from start work to qualified execution evidence", async () => { const store = memory(); const started = await NuruBuildPackageExecutionService.start(buildPackage.id, { branch: "codex/qualification" }, "human:owner", store); expect(started.branch).toBe("codex/qualification"); const ledger = await NuruImplementationLedgerService.record({ buildPackageId: buildPackage.id, branch: started.branch, commandsExecuted: ["npx vitest run"], testsExecuted: ["qualification scenario"], migrationStatus: "NOT_REQUIRED", qualificationStatus: "QUALIFIED", knownLimitations: [], recordedBy: "human:owner" }, store); expect(ledger.qualificationStatus).toBe("QUALIFIED"); expect(store.records.map((record) => record.kind)).toEqual(expect.arrayContaining(["CODEX_EXECUTION_EVENT", "CODEX_IMPLEMENTATION_LEDGER"])); }); });
