import { describe, expect, it } from "vitest";
import { type CodexBuildPackage, type VaultAuditEvent, type VaultRecord, vaultSchemaVersion } from "@/src/nuru/vault-contracts";
import { NuruCodexBuildPackageService, type CodexBuildPackageStore } from "@/src/server/services/nuru-codex-build-package-service";

const at = "2026-09-30T12:00:00.000Z"; const correlationId = "c8d1df9a-ae91-4ea3-8718-9df8d6e9bc36";
const candidate = { schemaVersion: vaultSchemaVersion, id: "candidate-package", kind: "CANDIDATE" as const, classification: "PUBLIC" as const, createdAt: at, correlationId, evidenceIds: ["evidence-package"], interpretation: "Build packages must be bounded by governed requirements.", confidence: 0.9, producedBy: "nuru.fixture", status: "APPROVED" as const };
const governance = { schemaVersion: vaultSchemaVersion, id: "governance-package", kind: "GOVERNANCE_DECISION" as const, classification: "PUBLIC" as const, createdAt: at, correlationId, candidateId: candidate.id, outcome: "APPROVED" as const, decidedBy: "human:owner", decidedAt: at, rationale: "Implementation needs traceability.", requiredHumanReview: true, humanApprovalId: "approval-package" };
const decision = { schemaVersion: vaultSchemaVersion, id: "project-decision-package", kind: "PROJECT_DECISION" as const, classification: "PUBLIC" as const, createdAt: at, correlationId, project: "NURU", question: "How are build packages bounded?", decision: "By current governed requirements.", rationale: "Bounded work.", alternatives: [], candidateId: candidate.id, governanceDecisionId: governance.id, decidedAt: at, version: 1, status: "CURRENT" as const };
const requirement = { schemaVersion: vaultSchemaVersion, id: "project-requirement-package", kind: "PROJECT_REQUIREMENT" as const, classification: "PUBLIC" as const, createdAt: at, correlationId, project: "NURU", title: "Build package generation", description: "Generate bounded implementation packages.", priority: "HIGH" as const, acceptanceCriteria: ["Package cites a requirement."], projectDecisionId: decision.id, implementationRefs: [], testRefs: ["tests/unit/nuru-codex-build-package-service.test.ts"], implementationStatus: "IMPLEMENTED" as const, candidateId: candidate.id, governanceDecisionId: governance.id, version: 1, status: "CURRENT" as const };
function memory(): CodexBuildPackageStore & { records: VaultRecord[] } { const records: VaultRecord[] = [candidate, governance, decision, requirement]; return { records, readVaultRecords: async () => records, appendBuildPackage: async (record: CodexBuildPackage, audit: VaultAuditEvent) => { records.push(record, audit); } }; }
const input = { project: "NURU", objective: "Implement governed Codex build packages.", requirementIds: [requirement.id], expectedFiles: ["src/server/services/nuru-codex-build-package-service.ts"], interfaces: ["POST /api/nuru/codex-build-packages"], testRefs: ["tests/unit/nuru-codex-build-package-service.test.ts"], migrationNotes: [], dependencies: [decision.id], exitCriteria: ["Contract tests pass."], verificationCommands: ["npx vitest run --config vitest.config.mjs tests/unit/nuru-codex-build-package-service.test.ts"], candidateId: candidate.id, governanceDecisionId: governance.id };
describe("Nuru Codex build package service", () => {
  it("creates a bounded package with requirement and architecture context", async () => { const result = await NuruCodexBuildPackageService.create(input, memory()); expect(result).toMatchObject({ project: "NURU", requirementIds: [requirement.id], architectureDecisionIds: [decision.id], version: 1, status: "PLANNED" }); });
  it("refuses a package when a referenced requirement is not current", async () => { await expect(NuruCodexBuildPackageService.create({ ...input, requirementIds: ["missing"] }, memory())).rejects.toMatchObject({ code: "REQUIREMENT_NOT_FOUND" }); });
});
