<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../Proprium.Api/Proprium.Api.csproj" /><ProjectReference Include="../Proprium.Application/Proprium.Application.csproj" /><ProjectReference Include="../Proprium.Domain/Proprium.Domain.csproj" /><ProjectReference Include="../Proprium.Infrastructure/Proprium.Infrastructure.csproj" /><ProjectReference Include="../Proprium.Contracts.V1/Proprium.Contracts.V1.csproj" /><ProjectReference Include="../Proprium.IntegrationTests/Proprium.IntegrationTests.csproj" /><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="NetArchTest.eNhancedEdition" /><PackageReference Include="xunit" /><PackageReference Include="xunit.runner.visualstudio"><PrivateAssets>all</PrivateAssets></PackageReference></ItemGroup></Project>
