import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runStorageCore, validateStorageCore } from "@/services/storage-core";
import type { StorageFullBundle, StorageFullDecision, StorageFullFailure, StorageFullInput, StorageFullResult, StorageFullScenario, StorageFullValidation } from "@/types/storage-full";

const VERSION = "storage-full/w1.2b" as const;
const IDENTIFIER = "StorageFull" as const;
let storageCoreBaseline: ReturnType<typeof runStorageCore> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly StorageFullFailure[], failure: StorageFullFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: StorageFullScenario): StorageFullFailure | undefined { return scenario === "BASELINE" || scenario === "READY_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly StorageFullFailure[], scenario: StorageFullScenario): StorageFullDecision {
  if (has(failures, "W1_2A_STORAGE_CORE_INVALID") || has(failures, "TENANT_ISOLATION_VIOLATED") || has(failures, "EVENT_IMMUTABILITY_FAILED") || has(failures, "LEDGER_APPEND_ONLY_VIOLATED") || has(failures, "LEDGER_CRYPTOGRAPHIC_CHAIN_INVALID") || has(failures, "LEDGER_TIMESTAMP_VALIDATION_FAILED") || has(failures, "STORAGE_INTEGRITY_VALIDATION_FAILED") || has(failures, "REPLICATION_CONSISTENCY_FAILED")) return "FAIL_CLOSED";
  if (has(failures, "SECURITY_FULL_MISSING") || has(failures, "STORAGE_INFRASTRUCTURE_GATE_FAILED")) return "NOT_READY";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONALLY_READY";
  if (scenario === "READY_WITH_OBSERVATIONS") return "READY_WITH_OBSERVATIONS";
  return "STORAGE_INFRASTRUCTURE_READY";
}
function resultReplayHash(result: Omit<StorageFullResult, "replay_hash" | "integrity_hash">): string { return hash({ foundation: result.foundation.integrity_hash, document: result.document_store.integrity_hash, object: result.object_store.integrity_hash, event: result.event_store.integrity_hash, ledger: result.immutable_ledger.integrity_hash, snapshot: result.snapshot_store.integrity_hash, search: result.search_index.integrity_hash, backup: result.backup_services.integrity_hash, restore: result.restore_services.integrity_hash, retention: result.retention_management.integrity_hash, integrity: result.integrity_validation.integrity_hash, qualification: result.qualification.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<StorageFullResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runStorageFull(input: StorageFullInput = {}): StorageFullResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<StorageFullFailure>(direct ? [direct] : []);
  storageCoreBaseline ??= runStorageCore();
  const coreInvalid = !validateStorageCore(storageCoreBaseline).valid || has(scenarioFailures, "W1_2A_STORAGE_CORE_INVALID");
  const failures = freezeArray([...new Set([...scenarioFailures, ...(coreInvalid ? ["W1_2A_STORAGE_CORE_INVALID" as const] : [])])]);
  const entryOk = !coreInvalid && !has(failures, "SECURITY_FULL_MISSING");
  const foundationOk = !has(failures, "STORAGE_PLATFORM_FOUNDATION_MISSING") && !has(failures, "STORAGE_CLUSTER_UNAVAILABLE") && !has(failures, "TENANT_ISOLATION_VIOLATED") && !has(failures, "REPLICATION_INVALID") && !has(failures, "ENCRYPTION_MISSING") && !has(failures, "CAPACITY_VALIDATION_FAILED") && !has(failures, "PERFORMANCE_VALIDATION_FAILED");
  const documentOk = !has(failures, "DOCUMENT_STORE_MISSING") && !has(failures, "DOCUMENT_SCHEMA_INVALID") && !has(failures, "DOCUMENT_INDEXING_FAILED") && !has(failures, "DOCUMENT_VERSIONING_FAILED") && !has(failures, "DOCUMENT_CONSISTENCY_FAILED");
  const objectOk = !has(failures, "OBJECT_STORE_MISSING") && !has(failures, "OBJECT_BUCKETS_INVALID") && !has(failures, "OBJECT_INTEGRITY_FAILED");
  const eventOk = !has(failures, "EVENT_STORE_MISSING") && !has(failures, "EVENT_ORDERING_FAILED") && !has(failures, "EVENT_IMMUTABILITY_FAILED") && !has(failures, "EVENT_REPLAY_SUPPORT_MISSING");
  const ledgerOk = !has(failures, "IMMUTABLE_LEDGER_MISSING") && !has(failures, "LEDGER_APPEND_ONLY_VIOLATED") && !has(failures, "LEDGER_CRYPTOGRAPHIC_CHAIN_INVALID") && !has(failures, "LEDGER_TIMESTAMP_VALIDATION_FAILED");
  const snapshotOk = !has(failures, "SNAPSHOT_STORE_MISSING") && !has(failures, "SNAPSHOT_RECOVERY_FAILED") && !has(failures, "SNAPSHOT_INTEGRITY_FAILED");
  const searchOk = !has(failures, "SEARCH_INDEX_MISSING") && !has(failures, "SEARCH_ACCURACY_FAILED") && !has(failures, "SEARCH_CONSISTENCY_FAILED");
  const backupOk = !has(failures, "BACKUP_SERVICES_MISSING") && !has(failures, "BACKUP_VERIFICATION_FAILED") && !has(failures, "BACKUP_RECOVERABILITY_FAILED");
  const restoreOk = !has(failures, "RESTORE_SERVICES_MISSING") && !has(failures, "POINT_IN_TIME_RECOVERY_FAILED") && !has(failures, "DISASTER_RECOVERY_FAILED") && !has(failures, "TENANT_RESTORATION_FAILED");
  const retentionOk = !has(failures, "RETENTION_MANAGEMENT_MISSING") && !has(failures, "RETENTION_POLICY_ENFORCEMENT_FAILED") && !has(failures, "LEGAL_HOLD_FAILED") && !has(failures, "GOVERNANCE_OVERRIDE_FAILED");
  const integrityOk = !has(failures, "STORAGE_INTEGRITY_VALIDATION_FAILED") && !has(failures, "REPLICATION_CONSISTENCY_FAILED");
  const qualificationOk = !has(failures, "QUALIFICATION_EVIDENCE_MISSING") && !has(failures, "STORAGE_QUALIFICATION_FAILED") && !has(failures, "STORAGE_INFRASTRUCTURE_GATE_FAILED");
  const decision = decisionFor(failures, scenario);
  const foundation = nested({ foundation_id: foundationOk ? `foundation:w1.2b:storage:${input.seed ?? "canonical"}` : "", clusters: foundationOk ? freezeArray(["cluster:primary", "cluster:replica"]) : freezeArray<string>([]), storage_pools: foundationOk ? freezeArray(["pool:documents", "pool:objects", "pool:events", "pool:ledger"]) : freezeArray<string>([]), namespaces_configured: foundationOk, tenant_isolation: foundationOk, replication: foundationOk, encryption: foundationOk, capacity_validated: foundationOk, performance_validated: foundationOk });
  const document_store = nested({ store_id: documentOk ? "store:w1.2b:documents" : "", document_database: documentOk, collections: documentOk ? freezeArray(["specifications", "governance", "manifests", "policies", "evidence", "registry"]) : freezeArray<string>([]), schemas_configured: documentOk, indexing: documentOk, versioning: documentOk, consistency_validated: documentOk, replication_validated: documentOk });
  const object_store = nested({ store_id: objectOk ? "store:w1.2b:objects" : "", buckets: objectOk ? freezeArray(["artifacts", "evidence", "backups", "snapshots"]) : freezeArray<string>([]), encryption: objectOk, lifecycle_rules: objectOk, replication: objectOk, object_integrity_validated: objectOk, catalog: objectOk ? "catalog:w1.2b:objects" : "" });
  const event_store = nested({ store_id: eventOk ? "store:w1.2b:events" : "", append_only: eventOk, streams: eventOk ? freezeArray(["identity", "storage", "governance", "security"]) : freezeArray<string>([]), partitions: eventOk, replay_support: eventOk, event_retention: eventOk, ordering_validated: eventOk, immutable: eventOk });
  const immutable_ledger = nested({ ledger_id: ledgerOk ? "ledger:w1.2b:immutable" : "", append_only: ledgerOk, cryptographic_chaining: ledgerOk, integrity_hashes: ledgerOk, timestamp_validation: ledgerOk, immutability_validated: ledgerOk, evidence_recorded: ledgerOk });
  const snapshot_store = nested({ store_id: snapshotOk ? "store:w1.2b:snapshots" : "", snapshot_policies: snapshotOk, schedules: snapshotOk, consistency_groups: snapshotOk, point_in_time_recovery: snapshotOk, snapshot_integrity: snapshotOk, catalog: snapshotOk ? freezeArray(["snapshot:documents", "snapshot:objects", "snapshot:events", "snapshot:ledger"]) : freezeArray<string>([]) });
  const search_index = nested({ index_id: searchOk ? "index:w1.2b:search" : "", indexing_platform: searchOk, indexing_pipelines: searchOk, metadata_indexing: searchOk, full_text_indexing: searchOk, lineage_indexing: searchOk, search_accuracy: searchOk, deterministic_results: searchOk });
  const backup_services = nested({ repository_id: backupOk ? "repository:w1.2b:backup" : "", scheduled_backups: backupOk, incremental_backups: backupOk, full_backups: backupOk, offsite_replication: backupOk, backup_verification: backupOk, recoverability_validated: backupOk });
  const restore_services = nested({ service_id: restoreOk ? "service:w1.2b:restore" : "", restore_workflows: restoreOk, point_in_time_recovery: restoreOk, disaster_recovery: restoreOk, tenant_restoration: restoreOk, evidence_restoration: restoreOk, validation_reports: restoreOk ? freezeArray(["restore:point-in-time", "restore:disaster", "restore:tenant", "restore:evidence"]) : freezeArray<string>([]) });
  const retention_management = nested({ policy_id: retentionOk ? "policy:w1.2b:retention" : "", retention_rules: retentionOk, archival_policies: retentionOk, expiration_policies: retentionOk, legal_hold: retentionOk, governance_overrides: retentionOk, policy_enforcement: retentionOk });
  const integrity_validation = nested({ report_id: integrityOk ? "report:w1.2b:integrity" : "", cryptographic_hashes: integrityOk, replication_consistency: integrityOk, object_integrity: integrityOk && objectOk, ledger_integrity: integrityOk && ledgerOk, snapshot_integrity: integrityOk && snapshotOk, search_consistency: integrityOk && searchOk, tenant_isolation_verified: integrityOk && foundationOk });
  const qualification = nested({ report_id: qualificationOk ? "report:w1.2b:qualification" : "", functional: qualificationOk && documentOk && objectOk && eventOk && ledgerOk && snapshotOk && searchOk, durability: qualificationOk && backupOk && restoreOk, recovery: qualificationOk && restoreOk, integrity: qualificationOk && integrityOk, governance: qualificationOk && retentionOk && ledgerOk, performance: qualificationOk && foundationOk, qualification_evidence: qualificationOk ? freezeArray([immutable_ledger.ledger_id, integrity_validation.report_id, backup_services.repository_id]) : freezeArray<string>([]), gate_approved: qualificationOk && entryOk && foundationOk && integrityOk });
  const readiness = nested({ readiness_id: "W1.2B-STORAGE-FULL-READINESS-001", decision, phase_ready: decision === "STORAGE_INFRASTRUCTURE_READY" || decision === "READY_WITH_OBSERVATIONS", entry_criteria_ready: entryOk, foundation_ready: foundationOk, document_ready: documentOk, object_ready: objectOk, event_ready: eventOk, ledger_ready: ledgerOk, snapshot_ready: snapshotOk, search_ready: searchOk, backup_ready: backupOk, restore_ready: restoreOk, retention_ready: retentionOk, integrity_ready: integrityOk, qualification_ready: qualification.gate_approved, failures });
  const base: Omit<StorageFullResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, storage_core_ref: "storage-core/w1.2a", foundation, document_store, object_store, event_store, immutable_ledger, snapshot_store, search_index, backup_services, restore_services, retention_management, integrity_validation, qualification, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateStorageFull(result?: StorageFullResult): StorageFullValidation {
  if (!result) return nested({ valid: false, decision: "NOT_READY" as const, replay_hash_valid: false, integrity_hash_valid: false, foundation_valid: false, document_valid: false, object_valid: false, event_valid: false, ledger_valid: false, snapshot_valid: false, search_valid: false, backup_valid: false, restore_valid: false, retention_valid: false, integrity_validation_valid: false, qualification_valid: false, readiness_valid: false, failures: freezeArray(["STORAGE_PLATFORM_FOUNDATION_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const foundation_valid = verifyHashed(result.foundation) && result.foundation.clusters.length >= 2 && result.foundation.tenant_isolation && result.foundation.encryption && result.foundation.performance_validated;
  const document_valid = verifyHashed(result.document_store) && result.document_store.collections.length >= 6 && result.document_store.schemas_configured && result.document_store.versioning && result.document_store.consistency_validated;
  const object_valid = verifyHashed(result.object_store) && result.object_store.buckets.length >= 4 && result.object_store.encryption && result.object_store.object_integrity_validated;
  const event_valid = verifyHashed(result.event_store) && result.event_store.append_only && result.event_store.replay_support && result.event_store.ordering_validated && result.event_store.immutable;
  const ledger_valid = verifyHashed(result.immutable_ledger) && result.immutable_ledger.append_only && result.immutable_ledger.cryptographic_chaining && result.immutable_ledger.timestamp_validation && result.immutable_ledger.immutability_validated;
  const snapshot_valid = verifyHashed(result.snapshot_store) && result.snapshot_store.point_in_time_recovery && result.snapshot_store.snapshot_integrity && result.snapshot_store.catalog.length >= 4;
  const search_valid = verifyHashed(result.search_index) && result.search_index.metadata_indexing && result.search_index.full_text_indexing && result.search_index.lineage_indexing && result.search_index.deterministic_results;
  const backup_valid = verifyHashed(result.backup_services) && result.backup_services.scheduled_backups && result.backup_services.incremental_backups && result.backup_services.full_backups && result.backup_services.recoverability_validated;
  const restore_valid = verifyHashed(result.restore_services) && result.restore_services.point_in_time_recovery && result.restore_services.disaster_recovery && result.restore_services.tenant_restoration && result.restore_services.evidence_restoration;
  const retention_valid = verifyHashed(result.retention_management) && result.retention_management.retention_rules && result.retention_management.legal_hold && result.retention_management.governance_overrides && result.retention_management.policy_enforcement;
  const integrity_validation_valid = verifyHashed(result.integrity_validation) && result.integrity_validation.cryptographic_hashes && result.integrity_validation.replication_consistency && result.integrity_validation.ledger_integrity && result.integrity_validation.tenant_isolation_verified;
  const qualification_valid = verifyHashed(result.qualification) && result.qualification.functional && result.qualification.durability && result.qualification.recovery && result.qualification.integrity && result.qualification.governance && result.qualification.gate_approved;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && foundation_valid && document_valid && object_valid && event_valid && ledger_valid && snapshot_valid && search_valid && backup_valid && restore_valid && retention_valid && integrity_validation_valid && qualification_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, foundation_valid, document_valid, object_valid, event_valid, ledger_valid, snapshot_valid, search_valid, backup_valid, restore_valid, retention_valid, integrity_validation_valid, qualification_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayStorageFull(result = runStorageFull()): boolean { const scenario = result.readiness.decision === "READY_WITH_OBSERVATIONS" ? { scenario: "READY_WITH_OBSERVATIONS" as const } : {}; const replayed = runStorageFull(scenario); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateStorageFull(result).valid; }
export function getStorageFullBundle(): StorageFullBundle { const result = runStorageFull(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_document_store: true, owns_object_store: true, owns_event_store: true, owns_immutable_ledger: true, owns_snapshot_store: true, owns_search_index: true, owns_backup_restore: true, owns_retention_management: true, owns_storage_qualification: true }), result, validation: validateStorageFull(result) }); }
export const StorageFullService = Object.freeze({ run: runStorageFull, validate: validateStorageFull, replay: replayStorageFull });
