import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runProvingBenchmarkingComparativeAnalysis, validateProvingBenchmarkingComparativeAnalysis } from "@/services/proving-benchmarking-comparative-analysis";
import type { ChangeTrigger, ContinuousBundle, ContinuousFailure, ContinuousInput, ContinuousOutcome, ContinuousResult, ContinuousScenario, ContinuousValidation, RegressionCategory } from "@/types/proving-continuous-proving-regression-validation";

const VERSION = "proving-continuous-proving-regression-validation/v6.14" as const;
const IDENTIFIER = "ProvingContinuousProvingRegressionValidation" as const;
const TRIGGERS = Object.freeze<ChangeTrigger[]>(["PLATFORM", "SOFTWARE", "GOVERNANCE", "TRUST", "AI", "DATA", "CONFIGURATION", "SECURITY"]);
const REGRESSIONS = Object.freeze<RegressionCategory[]>(["FUNCTIONAL", "GOVERNANCE", "TRUST", "REPLAY", "PERFORMANCE", "SECURITY", "INTEGRATION", "CERTIFICATION"]);
let benchmarkBaseline: ReturnType<typeof runProvingBenchmarkingComparativeAnalysis> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly ContinuousFailure[], failure: ContinuousFailure): boolean { return failures.includes(failure); }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function scenarioFailure(scenario: ContinuousScenario): ContinuousFailure | undefined { return scenario === "BASELINE" || scenario === "PASS_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function finalOutcome(failures: readonly ContinuousFailure[], scenario: ContinuousScenario): ContinuousOutcome {
  if (has(failures, "VALIDATION_EVIDENCE_INCOMPLETE") || has(failures, "VALIDATION_EVIDENCE_STALE") || has(failures, "VALIDATION_EVIDENCE_CONFLICTING") || has(failures, "VALIDATION_EVIDENCE_UNVERIFIABLE") || has(failures, "FAIL_CLOSED_NOT_ENFORCED")) return "FAIL_CLOSED";
  if (has(failures, "GOVERNANCE_REVIEW_REQUIRED")) return "REQUIRES_REVIEW";
  if (failures.length) return "FAIL";
  if (scenario === "CONDITIONAL_FOLLOWUP") return "CONDITIONAL_PASS";
  if (scenario === "PASS_WITH_OBSERVATIONS") return "PASS_WITH_OBSERVATIONS";
  return "PASS";
}
function resultReplayHash(result: Omit<ContinuousResult, "replay_hash" | "integrity_hash">): string { return hash({ engine: result.engine.integrity_hash, triggers: result.triggers.integrity_hash, impact: result.impact_report.integrity_hash, pipeline: result.pipeline.integrity_hash, regression: result.regression_report.integrity_hash, evidence: result.evidence.integrity_hash, qualification: result.qualification.integrity_hash, decision: result.decision.integrity_hash, dashboard: result.dashboard.integrity_hash, gates: result.gates.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<ContinuousResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.readiness.outcome, replay_hash: result.replay_hash }); }

export function runProvingContinuousProvingRegressionValidation(input: ContinuousInput = {}): ContinuousResult {
  const scenario = input.scenario ?? "BASELINE";
  const direct = scenarioFailure(scenario);
  const scenarioFailures = freezeArray<ContinuousFailure>(direct ? [direct] : []);
  benchmarkBaseline ??= runProvingBenchmarkingComparativeAnalysis();
  const benchmarkInvalid = !validateProvingBenchmarkingComparativeAnalysis(benchmarkBaseline).valid || has(scenarioFailures, "P6_13_BENCHMARKING_INVALID");
  const failures = freezeArray([...new Set([...scenarioFailures, ...(benchmarkInvalid ? ["P6_13_BENCHMARKING_INVALID" as const] : [])])]);
  const engineOk = !has(failures, "CONTINUOUS_PROVING_ENGINE_MISSING") && !has(failures, "VALIDATION_ORCHESTRATOR_MISSING");
  const triggersOk = !has(failures, "TRIGGER_REGISTRY_MISSING") && !has(failures, "CICD_INTEGRATION_MISSING") && !has(failures, "RELEASE_VALIDATION_MISSING");
  const impactOk = !has(failures, "CHANGE_IMPACT_ANALYZER_MISSING") && !has(failures, "IMPACT_ANALYSIS_INCOMPLETE");
  const pipelineOk = !has(failures, "SCENARIO_SELECTION_FAILED") && !has(failures, "ENVIRONMENT_PROVISIONING_FAILED") && !has(failures, "CONTINUOUS_SIMULATION_FAILED") && !has(failures, "CONTINUOUS_REPLAY_FAILED") && !has(failures, "BENCHMARK_COMPARISON_FAILED");
  const regressionOk = !has(failures, "REGRESSION_VALIDATION_ENGINE_MISSING") && !has(failures, "FUNCTIONAL_REGRESSION_DETECTED") && !has(failures, "GOVERNANCE_REGRESSION_DETECTED") && !has(failures, "TRUST_REGRESSION_DETECTED") && !has(failures, "REPLAY_REGRESSION_DETECTED") && !has(failures, "PERFORMANCE_REGRESSION_DETECTED") && !has(failures, "SECURITY_REGRESSION_DETECTED") && !has(failures, "INTEGRATION_REGRESSION_DETECTED") && !has(failures, "CERTIFICATION_REGRESSION_DETECTED");
  const evidenceOk = !has(failures, "EVIDENCE_COLLECTION_FAILED") && !has(failures, "VALIDATION_EVIDENCE_INCOMPLETE") && !has(failures, "VALIDATION_EVIDENCE_STALE") && !has(failures, "VALIDATION_EVIDENCE_CONFLICTING") && !has(failures, "VALIDATION_EVIDENCE_UNVERIFIABLE") && !has(failures, "EVIDENCE_LINEAGE_INCOMPLETE");
  const qualificationOk = !has(failures, "CONTINUOUS_QUALIFICATION_ENGINE_MISSING") && !has(failures, "QUALIFICATION_CONFIDENCE_DEGRADED");
  const decisionOk = !has(failures, "VALIDATION_DECISION_MISSING") && !has(failures, "FAIL_CLOSED_NOT_ENFORCED") && !has(failures, "OPERATOR_SUPREMACY_VIOLATED") && !has(failures, "GOVERNANCE_SUPREMACY_VIOLATED");
  const outcome = finalOutcome(failures, scenario);
  const engine = nested({ engine_id: engineOk ? `engine:p6.14:${input.seed ?? "canonical"}` : "", automatic_execution: engineOk, event_driven_validation: engineOk, scheduled_proving: engineOk, on_demand_proving: engineOk, continuous_qualification: engineOk && qualificationOk, deterministic: engineOk && pipelineOk && !benchmarkInvalid });
  const triggers = nested({ registry_id: triggersOk ? "registry:p6.14:triggers" : "", triggers: triggersOk ? TRIGGERS : freezeArray<ChangeTrigger>([]), cicd_integration: triggersOk, release_validation: triggersOk, nightly_proving: triggersOk, pre_release_proving: triggersOk, post_release_validation: triggersOk });
  const impact_report = nested({ report_id: impactOk ? "report:p6.14:impact" : "", severity: scenario === "CONDITIONAL_FOLLOWUP" ? "MODERATE" as const : "LOW" as const, strategy: scenario === "CONDITIONAL_FOLLOWUP" ? "DEPENDENCY" as const : "INCREMENTAL" as const, capabilities: impactOk, services: impactOk, tenants: impactOk, applications: impactOk, caf_agents: impactOk, trust_services: impactOk, governance: impactOk, operational_workflows: impactOk, certification_lineage: impactOk, replay_lineage: impactOk, evidence_lineage: impactOk, complete: impactOk });
  const pipeline = nested({ pipeline_id: pipelineOk ? "pipeline:p6.14:continuous-validation" : "", change_detected: pipelineOk, impact_analysis: pipelineOk && impactOk, scenario_selection: pipelineOk, environment_provisioning: pipelineOk, simulation_execution: pipelineOk, replay_validation: pipelineOk && !benchmarkInvalid, regression_testing: pipelineOk && regressionOk, benchmark_comparison: pipelineOk && !benchmarkInvalid, evidence_collection: pipelineOk && evidenceOk, qualification_assessment: pipelineOk && qualificationOk, validation_decision: pipelineOk && decisionOk, deterministic: pipelineOk && !benchmarkInvalid });
  const regression_report = nested({ report_id: regressionOk ? "report:p6.14:regression" : "", categories: regressionOk ? REGRESSIONS : freezeArray<RegressionCategory>([]), functional: regressionOk, governance: regressionOk, trust: regressionOk, replay: regressionOk, performance: regressionOk, security: regressionOk, integration: regressionOk, certification: regressionOk, findings: scenario === "PASS_WITH_OBSERVATIONS" ? freezeArray(["observation:minor-nonblocking-drift"]) : freezeArray<string>([]) });
  const evidence = nested({ evidence_id: evidenceOk ? "evidence:p6.14:continuous-validation" : "", validation_ledger: evidenceOk ? freezeArray(["ledger:p6.14:validation"]) : freezeArray<string>([]), regression_evidence: evidenceOk ? freezeArray([regression_report.report_id]) : freezeArray<string>([]), replay_evidence: evidenceOk ? freezeArray(["proving-replay-validation-framework/v6.6"]) : freezeArray<string>([]), simulation_evidence: evidenceOk ? freezeArray(["proving-simulation-framework/v6.5"]) : freezeArray<string>([]), benchmark_evidence: evidenceOk ? freezeArray([benchmarkBaseline.evidence_package.package_id]) : freezeArray<string>([]), qualification_evidence: evidenceOk ? freezeArray(["qualification:p6.14:continuous"]) : freezeArray<string>([]), impact_evidence: evidenceOk ? freezeArray([impact_report.report_id]) : freezeArray<string>([]), certification_evidence: evidenceOk ? freezeArray(["certification:p6.14:readiness"]) : freezeArray<string>([]), immutable: evidenceOk, replay_compatible: evidenceOk && !benchmarkInvalid, lineage_complete: evidenceOk, verifiable: evidenceOk, fresh: evidenceOk, non_conflicting: evidenceOk });
  const qualification = nested({ qualification_id: qualificationOk ? "qualification:p6.14:continuous" : "", qualification_readiness: qualificationOk, validation_health: qualificationOk && regressionOk, proving_readiness: qualificationOk && engineOk, regression_status: qualificationOk && regressionOk, certification_readiness: qualificationOk, continuous_qualification_score: qualificationOk ? 96 : 0, validation_confidence: qualificationOk ? (scenario === "CONDITIONAL_FOLLOWUP" ? 0.82 : 0.96) : 0, operational_readiness: qualificationOk ? 95 : 0 });
  const failClosed = outcome === "FAIL_CLOSED";
  const decision = nested({ decision_id: decisionOk ? "decision:p6.14:validation" : "", outcome, deployment_authorized: outcome === "PASS" || outcome === "PASS_WITH_OBSERVATIONS" || outcome === "CONDITIONAL_PASS", certification_progression_authorized: outcome === "PASS" || outcome === "PASS_WITH_OBSERVATIONS", operational_promotion_authorized: outcome === "PASS" || outcome === "PASS_WITH_OBSERVATIONS", fail_closed: failClosed || outcome === "FAIL" || outcome === "REQUIRES_REVIEW", operator_supremacy: decisionOk, governance_supremacy: decisionOk, rationale: freezeArray(outcome === "PASS" ? ["validation successful"] : outcome === "PASS_WITH_OBSERVATIONS" ? ["minor observations recorded"] : outcome === "CONDITIONAL_PASS" ? ["follow-up controls required"] : outcome === "FAIL_CLOSED" ? ["unverifiable evidence prohibits promotion"] : ["review or corrective action required"]) });
  const dashboard = nested({ dashboard_id: "dashboard:p6.14:continuous-proving", validation_runs: engineOk ? freezeArray(["run:p6.14:continuous"]) : freezeArray<string>([]), proving_sessions: engineOk ? freezeArray([engine.engine_id]) : freezeArray<string>([]), regression_reports: regressionOk ? freezeArray([regression_report.report_id]) : freezeArray<string>([]), impact_reports: impactOk ? freezeArray([impact_report.report_id]) : freezeArray<string>([]), qualification_reports: qualificationOk ? freezeArray([qualification.qualification_id]) : freezeArray<string>([]), decisions: decisionOk ? freezeArray([decision.decision_id]) : freezeArray<string>([]) });
  const gates = nested({ gate_id: "P6.14-GATES", trigger_gate: triggersOk, impact_gate: impactOk, simulation_replay_gate: pipelineOk && !benchmarkInvalid, regression_gate: regressionOk, benchmark_gate: !benchmarkInvalid, evidence_gate: evidenceOk, qualification_gate: qualificationOk, decision_gate: decisionOk && (outcome !== "FAIL_CLOSED" || decision.fail_closed), automation_gate: engineOk && triggersOk, passed: false });
  const finalGates = nested({ ...gates, passed: gates.trigger_gate && gates.impact_gate && gates.simulation_replay_gate && gates.regression_gate && gates.benchmark_gate && gates.evidence_gate && gates.qualification_gate && gates.decision_gate && gates.automation_gate });
  const derivedFailures = freezeArray([...new Set([...failures, ...(!engineOk ? ["CONTINUOUS_PROVING_ENGINE_MISSING" as const] : []), ...(!triggersOk ? ["TRIGGER_REGISTRY_MISSING" as const] : []), ...(!impactOk ? ["CHANGE_IMPACT_ANALYZER_MISSING" as const] : []), ...(!pipelineOk ? ["SCENARIO_SELECTION_FAILED" as const] : []), ...(!regressionOk ? ["REGRESSION_VALIDATION_ENGINE_MISSING" as const] : []), ...(!evidenceOk ? ["EVIDENCE_COLLECTION_FAILED" as const] : []), ...(!qualificationOk ? ["CONTINUOUS_QUALIFICATION_ENGINE_MISSING" as const] : []), ...(!decisionOk ? ["VALIDATION_DECISION_MISSING" as const] : [])])]);
  const readiness = nested({ readiness_id: "P6.14-CONTINUOUS-PROVING-READINESS-001", outcome, phase_ready: outcome === "PASS" || outcome === "PASS_WITH_OBSERVATIONS", engine_ready: engineOk, triggers_ready: triggersOk, impact_ready: impactOk, pipeline_ready: pipelineOk, regression_ready: regressionOk, evidence_ready: evidenceOk, qualification_ready: qualificationOk, decision_ready: decisionOk, dashboard_ready: dashboard.validation_runs.length > 0, gates_passed: finalGates.passed, failures: derivedFailures });
  const base: Omit<ContinuousResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, benchmarking_ref: "proving-benchmarking-comparative-analysis/v6.13", engine, triggers, impact_report, pipeline, regression_report, evidence, qualification, decision, dashboard, gates: finalGates, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateProvingContinuousProvingRegressionValidation(result?: ContinuousResult): ContinuousValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, engine_valid: false, triggers_valid: false, impact_valid: false, pipeline_valid: false, regression_valid: false, evidence_valid: false, qualification_valid: false, decision_valid: false, dashboard_valid: false, gates_valid: false, readiness_valid: false, failures: freezeArray(["CONTINUOUS_PROVING_ENGINE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const engine_valid = verifyHashed(result.engine) && result.engine.automatic_execution && result.engine.deterministic;
  const triggers_valid = verifyHashed(result.triggers) && result.triggers.triggers.length === TRIGGERS.length && result.triggers.cicd_integration;
  const impact_valid = verifyHashed(result.impact_report) && result.impact_report.complete && result.impact_report.evidence_lineage;
  const pipeline_valid = verifyHashed(result.pipeline) && result.pipeline.deterministic && result.pipeline.validation_decision;
  const regression_valid = verifyHashed(result.regression_report) && result.regression_report.categories.length === REGRESSIONS.length && result.regression_report.functional && result.regression_report.certification;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.immutable && result.evidence.replay_compatible && result.evidence.lineage_complete && result.evidence.verifiable && result.evidence.fresh && result.evidence.non_conflicting;
  const qualification_valid = verifyHashed(result.qualification) && result.qualification.continuous_qualification_score >= 90 && result.qualification.validation_confidence >= 0.9;
  const decision_valid = verifyHashed(result.decision) && result.decision.operator_supremacy && result.decision.governance_supremacy && result.decision.outcome !== "FAIL_CLOSED";
  const dashboard_valid = verifyHashed(result.dashboard) && result.dashboard.validation_runs.length > 0 && result.dashboard.decisions.length > 0;
  const gates_valid = verifyHashed(result.gates) && result.gates.passed;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && engine_valid && triggers_valid && impact_valid && pipeline_valid && regression_valid && evidence_valid && qualification_valid && decision_valid && dashboard_valid && gates_valid && readiness_valid;
  return nested({ valid, outcome: result.readiness.outcome, replay_hash_valid, integrity_hash_valid, engine_valid, triggers_valid, impact_valid, pipeline_valid, regression_valid, evidence_valid, qualification_valid, decision_valid, dashboard_valid, gates_valid, readiness_valid, failures: result.readiness.failures });
}

export function replayProvingContinuousProvingRegressionValidation(result = runProvingContinuousProvingRegressionValidation()): boolean { const scenario = result.readiness.outcome === "PASS_WITH_OBSERVATIONS" ? { scenario: "PASS_WITH_OBSERVATIONS" as const } : {}; const replayed = runProvingContinuousProvingRegressionValidation(scenario); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateProvingContinuousProvingRegressionValidation(result).valid; }
export function getProvingContinuousProvingRegressionValidationBundle(): ContinuousBundle { const result = runProvingContinuousProvingRegressionValidation(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_continuous_proving: true, owns_regression_validation: true, owns_continuous_simulation: true, owns_change_impact_validation: true }), result, validation: validateProvingContinuousProvingRegressionValidation(result) }); }
export const ProvingContinuousProvingRegressionValidationService = Object.freeze({ run: runProvingContinuousProvingRegressionValidation, validate: validateProvingContinuousProvingRegressionValidation, replay: replayProvingContinuousProvingRegressionValidation });
