import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runConstitutionalComplianceGate, validateConstitutionalComplianceGate } from "@/services/trust-constitutional-compliance-gate";
import { runTrustContinuousMonitoringStageEight, validateTrustContinuousMonitoringStageEight } from "@/services/trust-continuous-monitoring-stage-eight";
import { runTrustDriftDetectionStageNine, validateTrustDriftDetectionStageNine } from "@/services/trust-drift-detection-stage-nine";
import { runTrustExplainabilityStageSix, validateTrustExplainabilityStageSix } from "@/services/trust-explainability-stage-six";
import { runTrustFoundationStageOne, validateTrustFoundationStageOne } from "@/services/trust-foundation-stage-one";
import { runTrustHumanOversightStageSeven, validateTrustHumanOversightStageSeven } from "@/services/trust-human-oversight-stage-seven";
import { runTrustIndependentEvaluation, validateTrustIndependentEvaluation } from "@/services/trust-independent-evaluation";
import { runTrustRegistryDomains, validateTrustRegistryDomains } from "@/services/trust-registry-domains";
import { runTrustResolutionEngine, validateTrustResolutionEngine } from "@/services/trust-resolution-engine";
import type { StandingTransition, TrustRecoveryRevocationBundle, TrustRecoveryRevocationDecision, TrustRecoveryRevocationFailure, TrustRecoveryRevocationInput, TrustRecoveryRevocationResult, TrustRecoveryRevocationScenario, TrustRecoveryRevocationValidation, TrustStandingState } from "@/types/trust-recovery-revocation-stage-ten";

const VERSION = "trust-recovery-revocation-stage-ten/stage-10" as const;
const IDENTIFIER = "TrustRecoveryRevocationStageTen" as const;
const STATES = Object.freeze<TrustStandingState[]>(["UNKNOWN", "TRUSTED", "RESTRICTED", "SUSPENDED", "RECOVERED", "REVOKED", "EXPIRED"]);
const TRANSITIONS = Object.freeze<StandingTransition[]>(["SUSPENDED_TO_RESTRICTED", "SUSPENDED_TO_TRUSTED", "EXPIRED_TO_RESTRICTED", "EXPIRED_TO_TRUSTED", "TRUSTED_TO_RESTRICTED", "TRUSTED_TO_SUSPENDED", "TRUSTED_TO_REVOKED", "TRUSTED_TO_EXPIRED", "RESTRICTED_TO_TRUSTED", "RESTRICTED_TO_SUSPENDED", "RESTRICTED_TO_REVOKED", "RESTRICTED_TO_EXPIRED"]);
const UPSTREAM_REFS = Object.freeze(["trust-foundation-stage-one/stage-1", "trust-constitutional-compliance-gate/stage-2", "trust-registry-domains/stage-3", "trust-independent-evaluation/stage-4", "trust-resolution-engine/stage-5", "trust-explainability-stage-six/stage-6", "trust-human-oversight-stage-seven/stage-7", "trust-continuous-monitoring-stage-eight/stage-8", "trust-drift-detection-stage-nine/stage-9"]);
const PROVIDES = Object.freeze(["recovery-evaluation-engine", "standing-recovery-service", "revocation-service", "suspension-service", "expiration-service", "recovery-evidence-packages", "standing-lineage-records", "standing-history"]);
let baselines: ReturnType<typeof makeBaselines> | undefined;

function makeBaselines() { return { foundation: runTrustFoundationStageOne(), gate: runConstitutionalComplianceGate(), registry: runTrustRegistryDomains(), evaluation: runTrustIndependentEvaluation(), resolution: runTrustResolutionEngine(), explainability: runTrustExplainabilityStageSix(), oversight: runTrustHumanOversightStageSeven(), monitoring: runTrustContinuousMonitoringStageEight(), drift: runTrustDriftDetectionStageNine() }; }
function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function has(failures: readonly TrustRecoveryRevocationFailure[], failure: TrustRecoveryRevocationFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustRecoveryRevocationScenario): TrustRecoveryRevocationFailure | undefined { return scenario === "QUALIFIED_WITH_OBSERVATIONS" || scenario === "CONDITIONAL_FOLLOWUP" ? undefined : scenario; }
function decisionFor(failures: readonly TrustRecoveryRevocationFailure[], scenario?: TrustRecoveryRevocationScenario): TrustRecoveryRevocationDecision {
  const failClosed = new Set<TrustRecoveryRevocationFailure>(["STAGE_1_TRUST_FOUNDATION_INVALID", "STAGE_2_CONSTITUTIONAL_GATE_INVALID", "STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID", "STAGE_4_INDEPENDENT_EVALUATION_INVALID", "STAGE_5_TRUST_RESOLUTION_INVALID", "STAGE_6_EXPLAINABILITY_INVALID", "STAGE_7_HUMAN_OVERSIGHT_INVALID", "STAGE_8_CONTINUOUS_MONITORING_INVALID", "STAGE_9_DRIFT_DETECTION_INVALID", "RECOVERY_BYPASSED_CONSTITUTIONAL_EVALUATION", "REVOKED_IDENTITY_REINSTATED", "REVOCATION_REVERSED_WHEN_TERMINAL", "HUMAN_OVERSIGHT_OVERRIDES_REVOCATION", "STANDING_MODIFIED_OUTSIDE_GOVERNANCE", "TRANSITION_EVIDENCE_MUTABLE", "STANDING_HISTORY_REWRITTEN", "RECOVERY_REPLAY_DIVERGED"]);
  if (failures.some((failure) => failClosed.has(failure))) return "FAIL_CLOSED";
  if (has(failures, "RECOVERY_REVOCATION_QUALIFICATION_FAILED")) return "NOT_QUALIFIED";
  if (failures.length || scenario === "CONDITIONAL_FOLLOWUP" || scenario === "QUALIFIED_WITH_OBSERVATIONS") return "CONDITIONALLY_QUALIFIED";
  return "RECOVERY_REVOCATION_QUALIFIED";
}
function resultReplayHash(result: Omit<TrustRecoveryRevocationResult, "replay_hash" | "integrity_hash">): string { return hash({ recovery_evaluation: result.recovery_evaluation.integrity_hash, standing_recovery: result.standing_recovery.integrity_hash, revocation: result.revocation.integrity_hash, suspension: result.suspension.integrity_hash, expiration: result.expiration.integrity_hash, evidence: result.evidence.integrity_hash, transition_engine: result.transition_engine.integrity_hash, readiness: result.readiness.integrity_hash }); }
function resultIntegrityHash(result: Omit<TrustRecoveryRevocationResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, decision: result.readiness.decision, replay_hash: result.replay_hash }); }

export function runTrustRecoveryRevocationStageTen(input: TrustRecoveryRevocationInput = {}): TrustRecoveryRevocationResult {
  const direct = input.scenario ? scenarioFailure(input.scenario) : undefined;
  const scenarioFailures = freezeArray<TrustRecoveryRevocationFailure>(direct ? [direct] : []);
  baselines ??= makeBaselines();
  const failures = freezeArray([...new Set([...scenarioFailures, ...(!validateTrustFoundationStageOne(baselines.foundation).valid ? ["STAGE_1_TRUST_FOUNDATION_INVALID" as const] : []), ...(!validateConstitutionalComplianceGate(baselines.gate).valid ? ["STAGE_2_CONSTITUTIONAL_GATE_INVALID" as const] : []), ...(!validateTrustRegistryDomains(baselines.registry).valid ? ["STAGE_3_TRUST_REGISTRY_DOMAINS_INVALID" as const] : []), ...(!validateTrustIndependentEvaluation(baselines.evaluation).valid ? ["STAGE_4_INDEPENDENT_EVALUATION_INVALID" as const] : []), ...(!validateTrustResolutionEngine(baselines.resolution).valid ? ["STAGE_5_TRUST_RESOLUTION_INVALID" as const] : []), ...(!validateTrustExplainabilityStageSix(baselines.explainability).valid ? ["STAGE_6_EXPLAINABILITY_INVALID" as const] : []), ...(!validateTrustHumanOversightStageSeven(baselines.oversight).valid ? ["STAGE_7_HUMAN_OVERSIGHT_INVALID" as const] : []), ...(!validateTrustContinuousMonitoringStageEight(baselines.monitoring).valid ? ["STAGE_8_CONTINUOUS_MONITORING_INVALID" as const] : []), ...(!validateTrustDriftDetectionStageNine(baselines.drift).valid ? ["STAGE_9_DRIFT_DETECTION_INVALID" as const] : [])])]);
  const evalOk = !has(failures, "RECOVERY_EVALUATION_ENGINE_MISSING") && !has(failures, "RECOVERY_ELIGIBILITY_RULES_MISSING") && !has(failures, "CONSTITUTIONAL_RECOVERY_VALIDATION_MISSING") && !has(failures, "EVIDENCE_SUFFICIENCY_EVALUATION_MISSING") && !has(failures, "RECOVERY_PRECONDITIONS_MISSING") && !has(failures, "RECOVERY_RISK_REVIEW_MISSING") && !has(failures, "ALIGNMENT_REVALIDATION_MISSING") && !has(failures, "POLICY_REVALIDATION_MISSING") && !has(failures, "SAFETY_REVALIDATION_MISSING") && !has(failures, "RECOVERY_DECISION_LOGIC_MISSING") && !has(failures, "RECOVERY_RECOMMENDATION_MISSING") && !has(failures, "RECOVERY_BYPASSED_CONSTITUTIONAL_EVALUATION");
  const recoveryOk = !has(failures, "RECOVERY_WORKFLOW_MISSING") && !has(failures, "STANDING_PROMOTION_RULES_MISSING") && !has(failures, "RECOVERY_AUTHORIZATION_MISSING") && !has(failures, "RECOVERY_QUALIFICATION_MISSING") && !has(failures, "RECOVERY_VERIFICATION_MISSING") && !has(failures, "RECOVERY_STATE_TRANSITION_MISSING") && !has(failures, "RECOVERY_EVIDENCE_COLLECTION_MISSING") && !has(failures, "STANDING_REINSTATEMENT_MISSING") && !has(failures, "RECOVERY_NOTIFICATIONS_MISSING") && !has(failures, "REVOKED_IDENTITY_REINSTATED");
  const revocationOk = !has(failures, "REVOCATION_EVALUATION_MISSING") && !has(failures, "REVOCATION_CRITERIA_MISSING") && !has(failures, "MANDATORY_REVOCATION_RULES_MISSING") && !has(failures, "REVOCATION_AUTHORIZATION_MISSING") && !has(failures, "REVOCATION_EVIDENCE_MISSING") && !has(failures, "REVOCATION_RECORDING_MISSING") && !has(failures, "DEPENDENCY_IMPACT_ANALYSIS_MISSING") && !has(failures, "REVOCATION_NOTIFICATIONS_MISSING") && !has(failures, "FEDERATION_REVOCATION_PROPAGATION_MISSING") && !has(failures, "REVOCATION_REVERSED_WHEN_TERMINAL") && !has(failures, "HUMAN_OVERSIGHT_OVERRIDES_REVOCATION");
  const suspensionOk = !has(failures, "SUSPENSION_EVALUATION_MISSING") && !has(failures, "SUSPENSION_CONDITIONS_MISSING") && !has(failures, "TEMPORARY_RESTRICTIONS_MISSING") && !has(failures, "SUSPENSION_DURATION_MISSING") && !has(failures, "SUSPENSION_REVIEW_MISSING") && !has(failures, "AUTOMATIC_REASSESSMENT_MISSING") && !has(failures, "SUSPENSION_EVIDENCE_MISSING") && !has(failures, "SUSPENSION_NOTIFICATIONS_MISSING");
  const expirationOk = !has(failures, "EXPIRATION_DETECTION_MISSING") && !has(failures, "SCHEDULED_EXPIRATION_MISSING") && !has(failures, "RENEWAL_ELIGIBILITY_MISSING") && !has(failures, "RENEWAL_EVALUATION_MISSING") && !has(failures, "AUTOMATIC_EXPIRATION_MISSING") && !has(failures, "EXPIRATION_NOTIFICATIONS_MISSING") && !has(failures, "EXPIRATION_EVIDENCE_MISSING") && !has(failures, "STANDING_TRANSITION_RULES_MISSING");
  const evidenceOk = !has(failures, "RECOVERY_EVIDENCE_PACKAGES_MISSING") && !has(failures, "STANDING_TRANSITION_EVIDENCE_MISSING") && !has(failures, "CONSTITUTIONAL_VALIDATION_EVIDENCE_MISSING") && !has(failures, "RULE_EVALUATION_EVIDENCE_MISSING") && !has(failures, "HUMAN_OVERSIGHT_REFERENCES_MISSING") && !has(failures, "DECISION_LINEAGE_MISSING") && !has(failures, "REPLAY_METADATA_MISSING") && !has(failures, "AUDIT_RECORDS_MISSING") && !has(failures, "TRANSITION_EVIDENCE_MUTABLE");
  const engineOk = !has(failures, "STANDING_TRANSITION_ENGINE_MISSING") && !has(failures, "TRANSITION_ELIGIBILITY_VALIDATION_MISSING") && !has(failures, "TRANSITION_RULE_ENFORCEMENT_MISSING") && !has(failures, "STANDING_EVENTS_MISSING") && !has(failures, "STANDING_HISTORY_MISSING") && !has(failures, "STANDING_LINEAGE_MISSING") && !has(failures, "STANDING_REPLAY_MISSING") && !has(failures, "STANDING_MODIFIED_OUTSIDE_GOVERNANCE") && !has(failures, "STANDING_HISTORY_REWRITTEN") && !has(failures, "RECOVERY_REPLAY_DIVERGED");
  const decision = decisionFor(failures, input.scenario);
  const qualified = decision === "RECOVERY_REVOCATION_QUALIFIED";
  const tenant_id = input.tenant_id ?? baselines.drift.tenant_id;
  const standing_id = input.standing_id ?? `standing:stage-10:${input.seed ?? "canonical"}`;
  const recovery_evaluation = nested({ evaluation_id: evalOk ? "recovery-evaluation:stage-10" : "", recovery_evaluation_engine: evalOk, recovery_eligibility_rules: evalOk, constitutional_recovery_validation: evalOk, evidence_sufficiency_evaluation: evalOk, recovery_preconditions: evalOk, recovery_risk_review: evalOk, alignment_revalidation: evalOk, policy_revalidation: evalOk, safety_revalidation: evalOk, recovery_decision_logic: evalOk, recovery_recommendation: evalOk, deterministic: evalOk });
  const standing_recovery = nested({ recovery_id: recoveryOk ? "standing-recovery:stage-10" : "", supported_paths: recoveryOk ? freezeArray(TRANSITIONS.slice(0, 4)) : freezeArray<StandingTransition>([]), non_recoverable_states: freezeArray<TrustStandingState>(["REVOKED"]), recovery_workflow: recoveryOk, standing_promotion_rules: recoveryOk, recovery_authorization: recoveryOk, recovery_qualification: recoveryOk, recovery_verification: recoveryOk, recovery_state_transition: recoveryOk, recovery_evidence_collection: recoveryOk, standing_reinstatement: recoveryOk, recovery_notifications: recoveryOk, constitutional_only: recoveryOk && evalOk });
  const revocation = nested({ revocation_id: revocationOk ? "revocation:stage-10" : "", revocation_evaluation: revocationOk, revocation_criteria: revocationOk, mandatory_revocation_rules: revocationOk, revocation_authorization: revocationOk, revocation_evidence: revocationOk, revocation_recording: revocationOk, dependency_impact_analysis: revocationOk, revocation_notifications: revocationOk, federation_revocation_propagation: revocationOk, deterministic: revocationOk, irreversible_when_mandated: revocationOk });
  const suspension = nested({ suspension_id: suspensionOk ? "suspension:stage-10" : "", suspension_evaluation: suspensionOk, suspension_conditions: suspensionOk, temporary_restrictions: suspensionOk, suspension_duration: suspensionOk, suspension_review: suspensionOk, automatic_reassessment: suspensionOk, suspension_evidence: suspensionOk, suspension_notifications: suspensionOk, recovery_eligibility_preserved: suspensionOk, replayable: suspensionOk });
  const expiration = nested({ expiration_id: expirationOk ? "expiration:stage-10" : "", expiration_detection: expirationOk, scheduled_expiration: expirationOk, renewal_eligibility: expirationOk, renewal_evaluation: expirationOk, automatic_expiration: expirationOk, expiration_notifications: expirationOk, expiration_evidence: expirationOk, standing_transition_rules: expirationOk, deterministic_processing: expirationOk });
  const evidence = nested({ evidence_id: evidenceOk ? "evidence:stage-10:recovery" : "", recovery_evidence_packages: evidenceOk, standing_transition_evidence: evidenceOk, constitutional_validation_evidence: evidenceOk, rule_evaluation_evidence: evidenceOk, human_oversight_references: evidenceOk, decision_lineage: evidenceOk, replay_metadata: evidenceOk, audit_records: evidenceOk, immutable: evidenceOk });
  const transition_engine = nested({ engine_id: engineOk ? "standing-transition:stage-10" : "", lifecycle_states: engineOk ? freezeArray(STATES) : freezeArray<TrustStandingState>([]), transition_rules: engineOk ? freezeArray(TRANSITIONS) : freezeArray<StandingTransition>([]), validate_constitutional_eligibility: engineOk, verify_recovery_requirements: engineOk, enforce_transition_rules: engineOk, generate_immutable_evidence: engineOk, record_complete_lineage: engineOk, update_standing_deterministically: engineOk, publish_standing_events: engineOk, deterministic_replay: engineOk });
  const readiness = nested({ readiness_id: "STAGE-10-RECOVERY-REVOCATION-READINESS-001", decision, phase_ready: qualified, upstream_ready: failures.every((failure) => !failure.startsWith("STAGE_")), recovery_evaluation_ready: evalOk, standing_recovery_ready: recoveryOk, revocation_ready: revocationOk, suspension_ready: suspensionOk, expiration_ready: expirationOk, evidence_ready: evidenceOk, transition_engine_ready: engineOk, constitutional_governance: evalOk && engineOk, no_bypass: !has(failures, "RECOVERY_BYPASSED_CONSTITUTIONAL_EVALUATION") && !has(failures, "STANDING_MODIFIED_OUTSIDE_GOVERNANCE"), terminal_revocation_enforced: revocationOk && !has(failures, "REVOKED_IDENTITY_REINSTATED"), human_oversight_bounded: !has(failures, "HUMAN_OVERSIGHT_OVERRIDES_REVOCATION"), immutable_transitions: evidenceOk && engineOk, permanent_history: engineOk && !has(failures, "STANDING_HISTORY_REWRITTEN"), replayable: engineOk && !has(failures, "RECOVERY_REPLAY_DIVERGED"), certification_ready: evidenceOk && engineOk && revocationOk, failures });
  const base: Omit<TrustRecoveryRevocationResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, upstream_refs: freezeArray(UPSTREAM_REFS), provides: freezeArray(PROVIDES), tenant_id, standing_id, recovery_evaluation, standing_recovery, revocation, suspension, expiration, evidence, transition_engine, readiness };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustRecoveryRevocationStageTen(result?: TrustRecoveryRevocationResult): TrustRecoveryRevocationValidation {
  if (!result) return nested({ valid: false, decision: "FAIL_CLOSED" as const, replay_hash_valid: false, integrity_hash_valid: false, recovery_evaluation_valid: false, standing_recovery_valid: false, revocation_valid: false, suspension_valid: false, expiration_valid: false, evidence_valid: false, transition_engine_valid: false, readiness_valid: false, failures: freezeArray(["RECOVERY_EVALUATION_ENGINE_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const recovery_evaluation_valid = verifyHashed(result.recovery_evaluation) && result.recovery_evaluation.constitutional_recovery_validation && result.recovery_evaluation.recovery_decision_logic && result.recovery_evaluation.deterministic;
  const standing_recovery_valid = verifyHashed(result.standing_recovery) && result.standing_recovery.supported_paths.length === 4 && result.standing_recovery.non_recoverable_states.includes("REVOKED") && result.standing_recovery.constitutional_only;
  const revocation_valid = verifyHashed(result.revocation) && result.revocation.revocation_evaluation && result.revocation.revocation_recording && result.revocation.deterministic && result.revocation.irreversible_when_mandated;
  const suspension_valid = verifyHashed(result.suspension) && result.suspension.suspension_evaluation && result.suspension.temporary_restrictions && result.suspension.recovery_eligibility_preserved && result.suspension.replayable;
  const expiration_valid = verifyHashed(result.expiration) && result.expiration.expiration_detection && result.expiration.renewal_evaluation && result.expiration.automatic_expiration && result.expiration.deterministic_processing;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.recovery_evidence_packages && result.evidence.standing_transition_evidence && result.evidence.decision_lineage && result.evidence.immutable;
  const transition_engine_valid = verifyHashed(result.transition_engine) && result.transition_engine.lifecycle_states.length === 7 && result.transition_engine.transition_rules.length === 12 && result.transition_engine.enforce_transition_rules && result.transition_engine.deterministic_replay;
  const readiness_valid = verifyHashed(result.readiness) && result.readiness.phase_ready && result.readiness.constitutional_governance && result.readiness.no_bypass && result.readiness.terminal_revocation_enforced && result.readiness.human_oversight_bounded && result.readiness.immutable_transitions && result.readiness.permanent_history && result.readiness.replayable && result.readiness.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && recovery_evaluation_valid && standing_recovery_valid && revocation_valid && suspension_valid && expiration_valid && evidence_valid && transition_engine_valid && readiness_valid;
  return nested({ valid, decision: result.readiness.decision, replay_hash_valid, integrity_hash_valid, recovery_evaluation_valid, standing_recovery_valid, revocation_valid, suspension_valid, expiration_valid, evidence_valid, transition_engine_valid, readiness_valid, failures: result.readiness.failures });
}
export function replayTrustRecoveryRevocationStageTen(result = runTrustRecoveryRevocationStageTen()): boolean { const replayed = runTrustRecoveryRevocationStageTen(); return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustRecoveryRevocationStageTen(result).valid; }
export function getTrustRecoveryRevocationStageTenBundle(): TrustRecoveryRevocationBundle { const result = runTrustRecoveryRevocationStageTen(); return Object.freeze({ doctrine: Object.freeze({ version: VERSION, constitution_governs_all_standing_transitions: true, recovery_never_bypasses_constitutional_evaluation: true, revocation_irreversible_when_required: true, standing_history_permanent: true, immutable_transition_evidence_required: true, deterministic_replay_required: true, qualification_gate: "Stage 10 Recovery and Revocation Qualification Gate" }), result, validation: validateTrustRecoveryRevocationStageTen(result) }); }
export const TrustRecoveryRevocationStageTenService = Object.freeze({ run: runTrustRecoveryRevocationStageTen, validate: validateTrustRecoveryRevocationStageTen, replay: replayTrustRecoveryRevocationStageTen });
