"use client";

import { useEffect, useState } from "react";
import { Button } from "@/src/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/src/components/ui/card";

type Lesson = { id: string; position: number; target_skill_id: string; objective: string; estimated_minutes: number; why_this_lesson: string; evidence_references: string[]; next_step: string; activity_type: "DIAGNOSTIC" | "GUIDED_PRACTICE" | "SCENARIO_PRACTICE" | "REASSESSMENT" };
type Plan = { id: string; status: string; goal_summary: string; rationale: string; assumptions: string[]; lessons: Lesson[] };
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { cache: "no-store", ...init }); const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error(payload.error?.message ?? "Learning-plan request failed."); return payload.data as T; }

export function LearningPlanPanel() {
  const [plan, setPlan] = useState<Plan | null>(null); const [goal, setGoal] = useState("Diagnose systemd service failures"); const [minutes, setMinutes] = useState(90); const [sessionMinutes, setSessionMinutes] = useState(30); const [excludedTopics, setExcludedTopics] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void request<{ plan: Plan | null }>("/api/learning/plans/current").then((result) => setPlan(result.plan)).catch(() => undefined); }, []);
  const body = () => ({ goal: { skill_id: "linux.systemd.troubleshooting", free_text: goal, target_level: "TROUBLESHOOTING" }, constraints: { available_minutes_per_week: minutes, preferred_session_minutes: sessionMinutes, excluded_topics: excludedTopics.split(",").map((value) => value.trim()).filter(Boolean) } });
  const generate = async () => { setBusy(true); setError(null); try { const url = plan ? `/api/learning/plans/${encodeURIComponent(plan.id)}/replan` : "/api/learning/plans"; const result = await request<{ plan: Plan }>(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body()) }); setPlan(result.plan); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create learning plan."); } finally { setBusy(false); } };
  const record = async (lesson: Lesson, type: "STARTED" | "COMPLETED" | "SKIPPED") => { if (!plan) return; setBusy(true); setError(null); try { await request(`/api/learning/plans/${encodeURIComponent(plan.id)}/lessons/${encodeURIComponent(lesson.id)}/events`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type }) }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update lesson progress."); } finally { setBusy(false); } };
  return <Card>
    <CardHeader><CardTitle>Your learning plan</CardTitle><CardDescription>Evidence-backed recommendations only. Completing a lesson records progress; only an assessment updates your skill state.</CardDescription></CardHeader>
    <CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-3"><input aria-label="Learning goal" value={goal} onChange={(event) => setGoal(event.target.value)} className="sm:col-span-3 rounded-xl border border-white/15 bg-slate-950/50 px-3 py-2 text-sm text-white" /><input aria-label="Minutes available per week" type="number" min="1" value={minutes} onChange={(event) => setMinutes(Number(event.target.value))} className="rounded-xl border border-white/15 bg-slate-950/50 px-3 py-2 text-sm text-white" /><input aria-label="Preferred session minutes" type="number" min="1" value={sessionMinutes} onChange={(event) => setSessionMinutes(Number(event.target.value))} className="rounded-xl border border-white/15 bg-slate-950/50 px-3 py-2 text-sm text-white" /><input aria-label="Excluded topics" value={excludedTopics} onChange={(event) => setExcludedTopics(event.target.value)} placeholder="Excluded topics (comma-separated)" className="rounded-xl border border-white/15 bg-slate-950/50 px-3 py-2 text-sm text-white" /></div><Button onClick={generate} disabled={busy || !goal.trim()}>{busy ? "Planning…" : plan ? "Recalculate plan" : "Create plan"}</Button>
      {plan && <div className="space-y-3"><p className="text-sm text-slate-300">{plan.goal_summary} <span className="text-sky-200">({plan.status.replaceAll("_", " ")})</span></p>{plan.lessons.map((lesson) => <article key={lesson.id} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><p className="text-xs uppercase tracking-[.16em] text-sky-200">Lesson {lesson.position} · {lesson.estimated_minutes} minutes</p><h3 className="mt-1 font-medium text-white">{lesson.objective}</h3><p className="mt-2 text-sm text-slate-300"><span className="font-medium text-white">Why this lesson:</span> {lesson.why_this_lesson}</p><p className="mt-2 text-sm text-slate-400">Then: {lesson.next_step}. Evidence used: {lesson.evidence_references.length ? lesson.evidence_references.join(", ") : "focused diagnostic required"}.</p><div className="mt-3 flex gap-2">{lesson.activity_type === "REASSESSMENT" ? <a className="text-sm text-sky-200 underline" href="#systemd-diagnostic">Start reassessment</a> : <><Button onClick={() => record(lesson, "STARTED")} disabled={busy}>Start</Button><Button onClick={() => record(lesson, "COMPLETED")} disabled={busy}>Complete</Button><Button variant="outline" onClick={() => record(lesson, "SKIPPED")} disabled={busy}>Skip</Button></>}</div></article>)}<p className="text-xs text-slate-500">{plan.assumptions.join(" ")}</p></div>}
      {error && <p role="alert" className="text-sm text-rose-200">{error}</p>}
    </CardContent>
  </Card>;
}
