import { generateDecisionIntegrityHash, serializeDecisionCanonically } from "@/services/decision-integrity";
import { runTrustArchitectureAlignmentFoundation, validateTrustArchitectureAlignmentFoundation } from "@/services/trust-architecture-alignment-foundation";
import { runTrustConstitutionalFoundation, validateTrustConstitutionalFoundation } from "@/services/trust-constitutional-foundation";
import type { TrustBoundaryRecord, TrustDomainRecord, TrustIdentityClass, TrustIdentityDomainBoundaryBundle, TrustIdentityDomainBoundaryFailure, TrustIdentityDomainBoundaryInput, TrustIdentityDomainBoundaryOutcome, TrustIdentityDomainBoundaryResult, TrustIdentityDomainBoundaryScenario, TrustIdentityDomainBoundaryValidation, TrustIdentityRecord, TrustRegistryRecord } from "@/types/trust-identity-domains-boundaries";

const VERSION = "trust-identity-domains-boundaries/v5.2" as const;
const IDENTIFIER = "TrustIdentityDomainsBoundaries" as const;
const TRUST_CONSTITUTION_REF = "trust-constitutional-foundation/v5.0" as const;
const TRUST_ARCHITECTURE_REF = "trust-architecture-alignment-foundation/v5.1" as const;
const NOW = "2026-07-18T00:00:00.000Z";
let baselineConstitution: ReturnType<typeof runTrustConstitutionalFoundation> | undefined;
let baselineArchitecture: ReturnType<typeof runTrustArchitectureAlignmentFoundation> | undefined;

function freezeArray<T>(values: readonly T[]): readonly T[] { return Object.freeze([...values]); }
function hash(value: unknown): string { return generateDecisionIntegrityHash(value); }
function hashWithoutIntegrity<T extends object>(value: T): string { const copy = { ...value } as Record<string, unknown>; delete copy.integrity_hash; return hash(JSON.parse(serializeDecisionCanonically(copy)) as unknown); }
function nested<T extends object>(value: T): T & { integrity_hash: string } { return Object.freeze({ ...value, integrity_hash: hashWithoutIntegrity(value) }) as T & { integrity_hash: string }; }
function has(failures: readonly TrustIdentityDomainBoundaryFailure[], failure: TrustIdentityDomainBoundaryFailure): boolean { return failures.includes(failure); }
function scenarioFailure(scenario: TrustIdentityDomainBoundaryScenario): TrustIdentityDomainBoundaryFailure | undefined { return scenario === "BASELINE" ? undefined : scenario; }
function getConstitution() { baselineConstitution ??= runTrustConstitutionalFoundation(); return baselineConstitution; }
function getArchitecture() { baselineArchitecture ??= runTrustArchitectureAlignmentFoundation(); return baselineArchitecture; }
function outcome(failures: readonly TrustIdentityDomainBoundaryFailure[]): TrustIdentityDomainBoundaryOutcome { if (failures.some((failure) => failure.includes("CONTAINMENT") || failure.includes("TENANT") || failure.includes("LEAKAGE"))) return "FAIL"; if (has(failures, "GOVERNANCE_REVIEW_REQUIRED")) return "REQUIRES_GOVERNANCE_REVIEW"; if (has(failures, "OPERATOR_REVIEW_REQUIRED")) return "REQUIRES_OPERATOR_REVIEW"; return failures.length ? "FAIL" : "PASS"; }
function verifyHashed(value: { integrity_hash: string }): boolean { return hashWithoutIntegrity(value) === value.integrity_hash; }
function baseRecord(tenantId: string, id: string, refs: readonly string[], failures: readonly TrustIdentityDomainBoundaryFailure[], missing: TrustIdentityDomainBoundaryFailure): TrustRegistryRecord {
  return nested({ record_id: has(failures, missing) ? "" : id, tenant_id: has(failures, "TRUST_IDENTITY_AMBIGUOUS_TENANT") ? "" : tenantId, version: VERSION, refs: freezeArray(refs), immutable: !has(failures, "REGISTRY_HISTORY_REWRITABLE"), deterministic: !has(failures, "CONTAINMENT_VALIDATION_NONDETERMINISTIC") && !has(failures, "TRUST_IDENTITY_NOT_DETERMINISTIC") });
}
function resultReplayHash(result: Omit<TrustIdentityDomainBoundaryResult, "replay_hash" | "integrity_hash">): string {
  return hash({ trust_registry: result.trust_registry.integrity_hash, domain_registry: result.trust_domain_registry.integrity_hash, boundary_registry: result.trust_boundary_registry.integrity_hash, tenant_isolation: result.tenant_isolation.integrity_hash, resolution: result.resolution.integrity_hash, governance: result.governance.integrity_hash, evidence: result.evidence.integrity_hash, security: result.security.integrity_hash, observability: result.observability.integrity_hash, certification: result.certification.integrity_hash });
}
function resultIntegrityHash(result: Omit<TrustIdentityDomainBoundaryResult, "integrity_hash">): string { return hash({ version: result.phase_version, identifier: result.phase_identifier, outcome: result.certification.outcome, replay_hash: result.replay_hash }); }

export function runTrustIdentityDomainsBoundaries(input: TrustIdentityDomainBoundaryInput = {}): TrustIdentityDomainBoundaryResult {
  const direct = scenarioFailure(input.scenario ?? "BASELINE");
  const scenarioFailures = freezeArray<TrustIdentityDomainBoundaryFailure>(direct ? [direct] : []);
  const dependencyFailures = freezeArray<TrustIdentityDomainBoundaryFailure>([
    ...(!validateTrustConstitutionalFoundation(getConstitution()).valid || has(scenarioFailures, "P5_0_TRUST_CONSTITUTION_INVALID") ? ["P5_0_TRUST_CONSTITUTION_INVALID" as const] : []),
    ...(!validateTrustArchitectureAlignmentFoundation(getArchitecture()).valid || has(scenarioFailures, "P5_1_TRUST_ARCHITECTURE_INVALID") ? ["P5_1_TRUST_ARCHITECTURE_INVALID" as const] : []),
  ]);
  const failures = freezeArray([...new Set([...scenarioFailures, ...dependencyFailures])]);
  const tenantId = input.tenant_id ?? "tenant:constitutional";
  const identityId = input.trust_identity_id ?? "trust-identity:civitas:operator";
  const domainId = input.trust_domain_id ?? "trust-domain:civitas:root";
  const boundaryId = input.trust_boundary_id ?? "trust-boundary:civitas:root";
  const identityClasses = freezeArray<TrustIdentityClass>(["TRUST_SUBJECT", "TRUST_OPERATOR", "TRUST_DOMAIN_AUTHORITY"]);
  const identity: TrustIdentityRecord = nested({ ...baseRecord(tenantId, "P5.2-TRUST-IDENTITY-001", ["trust-identity-taxonomy", "tenant-boundary", "domain-membership"], failures, "TRUST_IDENTITY_MISSING"), trust_identity_id: has(failures, "TRUST_IDENTITY_NOT_UNIQUE") ? "duplicate:trust-identity" : identityId, identity_type: "CIVITAS_TRUST_IDENTITY" as const, canonical_entity_id: "civitas:operator:primary", trust_domain_ids: has(failures, "TRUST_IDENTITY_NOT_DOMAIN_RESOLVABLE") ? freezeArray<string>([]) : freezeArray([domainId]), trust_boundary_ids: freezeArray([boundaryId]), owner_identity_ref: "owner:constitutional", authority_identity_refs: freezeArray(["authority:governance", "authority:operator"]), namespace: has(failures, "NAMESPACE_CONFLICT_UNRESOLVED") ? "ambiguous" : "trust/tenant/constitutional/operator", display_name: "Constitutional Trust Operator", identity_classes: identityClasses, identity_version: "1", lifecycle_status: has(failures, "REVOKED_IDENTITY_CAN_INITIATE_RELATIONSHIP") ? "REVOKED" as const : "ACTIVE" as const, registration_status: has(failures, "REGISTRATION_OUTCOME_STORED_AS_LIFECYCLE") ? "REQUIRES_OPERATOR_REVIEW" as const : "ACCEPT" as const, source_registry_refs: freezeArray(["program-1:identity-taxonomy", "program-2:tenant-identity"]), constitutional_scope: "tenant-contained trust identity", permitted_trust_roles: freezeArray(["identify", "register", "govern-domain"]), prohibited_trust_roles: freezeArray(["authorize-execution", "override-governance", "cross-tenant-inheritance"]), delegation_allowed: false, cross_domain_participation_allowed: false, created_at: NOW, activated_at: NOW, suspended_at: "", revoked_at: has(failures, "REVOKED_IDENTITY_CAN_INITIATE_RELATIONSHIP") ? NOW : "", expired_at: "", superseded_by: "", lineage_refs: has(failures, "REGISTRY_MUTATION_WITHOUT_EVIDENCE") ? freezeArray<string>([]) : freezeArray(["lineage:trust-identity:genesis"]), evidence_refs: has(failures, "EVIDENCE_MODEL_INCOMPLETE") ? freezeArray<string>([]) : freezeArray(["evidence:identity-registration"]), trusted_by_registration: has(failures, "IDENTITY_SILENTLY_TRUSTED"), can_initiate_new_relationships: !has(failures, "REVOKED_IDENTITY_CAN_INITIATE_RELATIONSHIP") });
  const domainTenantIds = has(failures, "DOMAIN_SPANS_MULTIPLE_TENANTS") ? freezeArray([tenantId, "tenant:foreign"]) : freezeArray([tenantId]);
  const domain: TrustDomainRecord = nested({ ...baseRecord(tenantId, "P5.2-TRUST-DOMAIN-001", ["TrustDomain subset TenantBoundary", "domain-taxonomy", "domain-lifecycle"], failures, "TRUST_DOMAIN_MISSING"), trust_domain_id: domainId, parent_domain_id: has(failures, "DOMAIN_PARENT_TENANT_MISMATCH") ? "trust-domain:foreign:parent" : "", domain_type: "TENANT_ROOT" as const, domain_name: "Civitas Constitutional Trust Domain", namespace: has(failures, "NAMESPACE_CONFLICT_UNRESOLVED") ? "ambiguous" : "trust.domain.tenant.constitutional", owning_identity_ref: identityId, governing_authority_refs: freezeArray(["authority:governance", "authority:operator"]), trust_boundary_id: has(failures, "DOMAIN_BOUNDARY_MISSING") ? "" : boundaryId, constitutional_scope: "TrustDomain subset TenantBoundary", permitted_identity_types: identityClasses, permitted_trust_relationship_types: freezeArray(["governed-domain-membership", "governed-boundary-resolution"]), prohibited_relationship_types: has(failures, "BOUNDARY_RULES_INCOMPLETE") ? freezeArray<string>([]) : freezeArray(["cross-tenant-inheritance", "implicit-propagation", "foreign-authoritative-evidence"]), inherited_policy_refs: freezeArray(["policy:tenant-isolation"]), domain_policy_refs: freezeArray(["policy:trust-domain-containment"]), domain_status: has(failures, "SUSPENDED_DOMAIN_ALLOWS_NEW_RELATIONSHIP") ? "SUSPENDED" as const : "ACTIVE" as const, registration_status: "ACCEPT" as const, isolation_class: "TENANT_CONTAINED" as const, cross_domain_rules: freezeArray(["explicit-governance-required", "tenant-isolation-preserved"]), evidence_scope: "tenant-local", replay_scope: "tenant-local", created_at: NOW, activated_at: NOW, suspended_at: has(failures, "SUSPENDED_DOMAIN_ALLOWS_NEW_RELATIONSHIP") ? NOW : "", retired_at: "", superseded_by: "", lineage_refs: has(failures, "REGISTRY_MUTATION_WITHOUT_EVIDENCE") ? freezeArray<string>([]) : freezeArray(["lineage:trust-domain:genesis"]), tenant_boundary_ids: domainTenantIds, allows_new_relationships: !has(failures, "SUSPENDED_DOMAIN_ALLOWS_NEW_RELATIONSHIP"), expands_parent_scope: has(failures, "DOMAIN_HIERARCHY_EXPANDS_SCOPE") });
  const boundaryTenantIds = has(failures, "BOUNDARY_TENANT_AMBIGUOUS") ? freezeArray([tenantId, "tenant:foreign"]) : freezeArray([tenantId]);
  const boundary: TrustBoundaryRecord = nested({ ...baseRecord(tenantId, "P5.2-TRUST-BOUNDARY-001", ["tenant-scope", "domain-scope", "identity-scope", "ingress-egress", "prohibited-crossings"], failures, "TRUST_BOUNDARY_MISSING"), trust_boundary_id: boundaryId, trust_domain_id: domainId, boundary_type: "TENANT_BOUNDARY" as const, boundary_name: "Civitas Tenant Trust Boundary", parent_boundary_id: "", owning_identity_ref: identityId, governing_authority_refs: freezeArray(["authority:governance"]), included_identity_refs: has(failures, "CROSS_TENANT_MEMBERSHIP_ALLOWED") ? freezeArray([identityId, "trust-identity:foreign"]) : freezeArray([identityId]), included_service_refs: freezeArray(["trust-registry", "trust-domain-registry", "trust-boundary-registry"]), included_resource_refs: freezeArray(["trust-records"]), included_namespace_refs: freezeArray(["trust/tenant/constitutional"]), permitted_ingress_types: freezeArray(["governed-registration-request"]), permitted_egress_types: freezeArray(["authorized-tenant-scoped-query"]), prohibited_crossings: has(failures, "BOUNDARY_RULES_INCOMPLETE") ? freezeArray<string>([]) : freezeArray(["cross-tenant-trust-inheritance", "implicit-trust-propagation", "authority-transfer"]), evidence_visibility_rules: has(failures, "FOREIGN_EVIDENCE_AUTHORITATIVE") ? freezeArray(["foreign-evidence-authoritative"]) : freezeArray(["tenant-local-by-default", "foreign-evidence-requires-governance"]), trust_propagation_rules: has(failures, "TRUST_PROPAGATION_IMPLICIT") ? freezeArray(["implicit-domain-propagation"]) : freezeArray(["no-implicit-propagation"]), delegation_rules: has(failures, "DELEGATION_BYPASSES_ISOLATION") ? freezeArray(["cross-tenant-delegation-allowed"]) : freezeArray(["delegation-cannot-cross-tenant-boundary"]), federation_endpoint_rules: has(failures, "FEDERATION_MERGES_DOMAINS") ? freezeArray(["merge-tenant-domains"]) : freezeArray(["endpoint-only", "no-domain-merge", "local-governance-preserved"]), temporal_constraints: freezeArray(["active-window-required"]), jurisdictional_constraints: freezeArray(["tenant-policy-jurisdiction"]), isolation_requirements: freezeArray(["requesting=subject=domain=boundary=evidence tenant"]), enforcement_refs: freezeArray(["enforcement:fail-closed", "enforcement:tenant-authorization"]), boundary_status: "ACTIVE" as const, created_at: NOW, activated_at: NOW, suspended_at: "", retired_at: "", superseded_by: "", lineage_refs: has(failures, "REGISTRY_MUTATION_WITHOUT_EVIDENCE") ? freezeArray<string>([]) : freezeArray(["lineage:trust-boundary:genesis"]), tenant_boundary_ids: boundaryTenantIds, conflicts_silently_ignored: has(failures, "BOUNDARY_CONFLICT_SILENTLY_IGNORED") });
  const trust_registry = nested({ ...baseRecord(tenantId, "P5.2-TRUST-REGISTRY-001", ["identity-registration", "identity-discovery", "identity-lineage"], failures, "TRUST_REGISTRY_MISSING"), registry_id: "registry:trust-identities", registry_kind: "TRUST_REGISTRY" as const, canonical_for: freezeArray(["trust identity", "trust roles", "identity ownership", "domain membership", "lineage"]), identities: freezeArray([identity]), tenant_scoped: !has(failures, "TENANT_ISOLATION_INVALID"), rejects_ambiguous_registration: !has(failures, "NAMESPACE_CONFLICT_UNRESOLVED"), preserves_history: !has(failures, "REGISTRY_HISTORY_REWRITABLE"), separates_identity_from_trust_status: !has(failures, "IDENTITY_SILENTLY_TRUSTED"), separates_lifecycle_from_registration_decision: !has(failures, "REGISTRATION_OUTCOME_STORED_AS_LIFECYCLE"), fail_closed_resolution: !has(failures, "CONFLICTS_DO_NOT_FAIL_CLOSED"), prevents_cross_tenant_discovery: !has(failures, "CROSS_TENANT_DISCOVERY_LEAKAGE") });
  const trust_domain_registry = nested({ ...baseRecord(tenantId, "P5.2-TRUST-DOMAIN-REGISTRY-001", ["domain-registration", "tenant-containment", "domain-lineage"], failures, "TRUST_DOMAIN_REGISTRY_MISSING"), registry_id: "registry:trust-domains", registry_kind: "TRUST_DOMAIN_REGISTRY" as const, canonical_for: freezeArray(["trust domains", "tenant containment", "domain hierarchy", "governing authority"]), domains: freezeArray([domain]), tenant_containment_validated: !has(failures, "DOMAIN_TENANT_CONTAINMENT_INVALID") && domain.tenant_boundary_ids.length === 1, hierarchy_validated: !has(failures, "DOMAIN_PARENT_TENANT_MISMATCH") && !domain.expands_parent_scope, membership_queries_tenant_scoped: !has(failures, "CROSS_TENANT_DISCOVERY_LEAKAGE"), deterministic_historical_replay: !has(failures, "REPLAY_DIVERGENCE") });
  const trust_boundary_registry = nested({ ...baseRecord(tenantId, "P5.2-TRUST-BOUNDARY-REGISTRY-001", ["boundary-registration", "boundary-resolution", "boundary-lineage"], failures, "TRUST_BOUNDARY_REGISTRY_MISSING"), registry_id: "registry:trust-boundaries", registry_kind: "TRUST_BOUNDARY_REGISTRY" as const, canonical_for: freezeArray(["trust boundaries", "ingress", "egress", "propagation", "delegation", "evidence visibility"]), boundaries: freezeArray([boundary]), boundary_to_domain_resolution: boundary.trust_domain_id.length > 0, boundary_to_tenant_resolution: boundary.tenant_boundary_ids.length === 1, conflict_detection: !has(failures, "BOUNDARY_CONFLICT_SILENTLY_IGNORED"), lifecycle_managed: true, deterministic_historical_reconstruction: !has(failures, "REPLAY_DIVERGENCE") });
  const allTenantRefsEqual = !has(failures, "TENANT_ISOLATION_INVALID") && tenantId === identity.tenant_id && tenantId === domain.tenant_id && tenantId === boundary.tenant_id && domain.tenant_boundary_ids.length === 1 && boundary.tenant_boundary_ids.length === 1;
  const tenant_isolation = nested({ requesting_tenant_id: tenantId, subject_tenant_id: identity.tenant_id, trust_domain_tenant_id: domain.tenant_id, trust_boundary_tenant_id: boundary.tenant_id, evidence_tenant_id: has(failures, "FOREIGN_EVIDENCE_AUTHORITATIVE") ? "tenant:foreign" : tenantId, all_tenant_refs_equal: allTenantRefsEqual && !has(failures, "FOREIGN_EVIDENCE_AUTHORITATIVE"), foreign_evidence_authoritative_by_default: has(failures, "FOREIGN_EVIDENCE_AUTHORITATIVE"), delegation_bypasses_isolation: has(failures, "DELEGATION_BYPASSES_ISOLATION"), federation_merges_domains: has(failures, "FEDERATION_MERGES_DOMAINS"), registry_queries_tenant_scoped: !has(failures, "CROSS_TENANT_DISCOVERY_LEAKAGE") });
  const resolution = nested({ path: ["TrustIdentity", "TrustDomain", "TrustBoundary", "TenantBoundary"] as const, terminates_in_exactly_one_tenant_boundary: domain.tenant_boundary_ids.length === 1 && boundary.tenant_boundary_ids.length === 1, identity_to_domain_resolved: identity.trust_domain_ids.includes(domainId), domain_to_boundary_resolved: domain.trust_boundary_id === boundaryId, boundary_to_tenant_resolved: boundary.tenant_boundary_ids.length === 1, trust_domain_subset_tenant_boundary: domain.tenant_boundary_ids.length === 1 && domain.tenant_boundary_ids[0] === domain.tenant_id && domain.tenant_id === boundary.tenant_id && !has(failures, "DOMAIN_TENANT_CONTAINMENT_INVALID"), deterministic_containment_validation: !has(failures, "CONTAINMENT_VALIDATION_NONDETERMINISTIC"), fail_closed_on_ambiguity: !has(failures, "CONFLICTS_DO_NOT_FAIL_CLOSED") });
  const governance = nested({ registration_authorities_defined: !has(failures, "GOVERNANCE_REVIEW_REQUIRED"), mutation_permissions_defined: true, conflict_escalation_defined: true, no_self_approval_unless_governed: true, no_cross_tenant_mutation: !has(failures, "TENANT_ISOLATION_INVALID"), exceptional_cross_domain_interaction_requires_governance: true });
  const evidence = nested({ evidence_refs: freezeArray(["TrustIdentityRegistrationEvidence", "TrustDomainRegistrationEvidence", "TrustBoundaryRegistrationEvidence", "TrustRegistryMutationEvidence", "TrustDomainContainmentEvidence", "TenantTrustIsolationEvidence", "TrustRegistryConflictEvidence", "TrustRegistryReplayEvidence"]), captures_previous_state: true, captures_proposed_state: true, captures_validation_results: true, captures_conflicts_detected: true, emits_audit_records: true, immutable_lineage_preserved: !has(failures, "REGISTRY_HISTORY_REWRITABLE"), replayable_history: !has(failures, "REPLAY_DIVERGENCE") });
  const security = nested({ tenant_scoped_authorization: !has(failures, "SECURITY_MODEL_MISSING") && !has(failures, "TENANT_ISOLATION_INVALID"), role_based_field_visibility: !has(failures, "SECURITY_MODEL_MISSING"), anti_enumeration_controls: !has(failures, "CROSS_TENANT_DISCOVERY_LEAKAGE"), namespace_protection: !has(failures, "NAMESPACE_CONFLICT_UNRESOLVED"), mutation_authorization: !has(failures, "SECURITY_MODEL_MISSING"), stale_write_prevention: !has(failures, "SECURITY_MODEL_MISSING"), suspension_revocation_enforced: !has(failures, "REVOKED_IDENTITY_CAN_INITIATE_RELATIONSHIP") && !has(failures, "SUSPENDED_DOMAIN_ALLOWS_NEW_RELATIONSHIP"), fail_closed_resolution: !has(failures, "CONFLICTS_DO_NOT_FAIL_CLOSED") });
  const observability = nested({ metric_refs: freezeArray(["trust_identity_registration_total", "trust_domain_registration_total", "trust_boundary_registration_total", "trust_registration_rejection_total", "trust_domain_containment_violation_total", "tenant_trust_isolation_violation_total", "trust_namespace_conflict_total", "trust_registry_integrity_failure_total", "trust_registry_replay_divergence_total", "trust_domain_quarantine_total", "trust_identity_revocation_total"]), monitors_containment_violations: !has(failures, "OBSERVABILITY_MODEL_MISSING"), monitors_isolation_violations: !has(failures, "OBSERVABILITY_MODEL_MISSING"), monitors_namespace_conflicts: !has(failures, "OBSERVABILITY_MODEL_MISSING"), monitors_integrity_failures: !has(failures, "OBSERVABILITY_MODEL_MISSING"), monitors_replay_divergence: !has(failures, "OBSERVABILITY_MODEL_MISSING"), monitors_unauthorized_queries: !has(failures, "OBSERVABILITY_MODEL_MISSING") });
  const registrySeparation = !has(failures, "REGISTRY_SEPARATION_INVALID") && new Set([trust_registry.registry_kind, trust_domain_registry.registry_kind, trust_boundary_registry.registry_kind]).size === 3;
  const registryIntegrity = !has(failures, "REGISTRY_INTEGRITY_INVALID") && [identity, domain, boundary, trust_registry, trust_domain_registry, trust_boundary_registry].every(verifyHashed);
  const derivedFailures = freezeArray([...new Set([
    ...failures,
    ...(trust_registry.record_id.length === 0 ? ["TRUST_REGISTRY_MISSING" as const] : []),
    ...(trust_domain_registry.record_id.length === 0 ? ["TRUST_DOMAIN_REGISTRY_MISSING" as const] : []),
    ...(trust_boundary_registry.record_id.length === 0 ? ["TRUST_BOUNDARY_REGISTRY_MISSING" as const] : []),
    ...(identity.record_id.length === 0 ? ["TRUST_IDENTITY_MISSING" as const] : []),
    ...(!identity.deterministic ? ["TRUST_IDENTITY_NOT_DETERMINISTIC" as const] : []),
    ...(!identity.trust_domain_ids.includes(domainId) ? ["TRUST_IDENTITY_NOT_DOMAIN_RESOLVABLE" as const] : []),
    ...(!trust_registry.separates_identity_from_trust_status ? ["IDENTITY_SILENTLY_TRUSTED" as const] : []),
    ...(!identity.can_initiate_new_relationships ? ["REVOKED_IDENTITY_CAN_INITIATE_RELATIONSHIP" as const] : []),
    ...(domain.record_id.length === 0 ? ["TRUST_DOMAIN_MISSING" as const] : []),
    ...(!resolution.trust_domain_subset_tenant_boundary ? ["DOMAIN_TENANT_CONTAINMENT_INVALID" as const] : []),
    ...(domain.tenant_boundary_ids.length > 1 ? ["DOMAIN_SPANS_MULTIPLE_TENANTS" as const] : []),
    ...(!trust_domain_registry.hierarchy_validated ? ["DOMAIN_PARENT_TENANT_MISMATCH" as const] : []),
    ...(domain.trust_boundary_id.length === 0 ? ["DOMAIN_BOUNDARY_MISSING" as const] : []),
    ...(domain.expands_parent_scope ? ["DOMAIN_HIERARCHY_EXPANDS_SCOPE" as const] : []),
    ...(!domain.allows_new_relationships ? ["SUSPENDED_DOMAIN_ALLOWS_NEW_RELATIONSHIP" as const] : []),
    ...(boundary.record_id.length === 0 ? ["TRUST_BOUNDARY_MISSING" as const] : []),
    ...(boundary.tenant_boundary_ids.length !== 1 ? ["BOUNDARY_TENANT_AMBIGUOUS" as const] : []),
    ...(boundary.conflicts_silently_ignored ? ["BOUNDARY_CONFLICT_SILENTLY_IGNORED" as const] : []),
    ...(boundary.prohibited_crossings.length === 0 ? ["BOUNDARY_RULES_INCOMPLETE" as const] : []),
    ...(!tenant_isolation.all_tenant_refs_equal ? ["TENANT_ISOLATION_INVALID" as const] : []),
    ...(boundary.included_identity_refs.some((ref) => ref.includes("foreign")) ? ["CROSS_TENANT_MEMBERSHIP_ALLOWED" as const] : []),
    ...(!tenant_isolation.registry_queries_tenant_scoped ? ["CROSS_TENANT_DISCOVERY_LEAKAGE" as const] : []),
    ...(tenant_isolation.foreign_evidence_authoritative_by_default ? ["FOREIGN_EVIDENCE_AUTHORITATIVE" as const] : []),
    ...(tenant_isolation.delegation_bypasses_isolation ? ["DELEGATION_BYPASSES_ISOLATION" as const] : []),
    ...(tenant_isolation.federation_merges_domains ? ["FEDERATION_MERGES_DOMAINS" as const] : []),
    ...(!registrySeparation ? ["REGISTRY_SEPARATION_INVALID" as const] : []),
    ...(!registryIntegrity ? ["REGISTRY_INTEGRITY_INVALID" as const] : []),
    ...(!evidence.immutable_lineage_preserved ? ["REGISTRY_HISTORY_REWRITABLE" as const] : []),
    ...(identity.lineage_refs.length === 0 || domain.lineage_refs.length === 0 || boundary.lineage_refs.length === 0 ? ["REGISTRY_MUTATION_WITHOUT_EVIDENCE" as const] : []),
    ...(!trust_registry.rejects_ambiguous_registration ? ["NAMESPACE_CONFLICT_UNRESOLVED" as const] : []),
    ...(!resolution.fail_closed_on_ambiguity ? ["CONFLICTS_DO_NOT_FAIL_CLOSED" as const] : []),
    ...(!resolution.deterministic_containment_validation ? ["CONTAINMENT_VALIDATION_NONDETERMINISTIC" as const] : []),
    ...(!evidence.replayable_history ? ["REPLAY_DIVERGENCE" as const] : []),
    ...(!security.tenant_scoped_authorization ? ["SECURITY_MODEL_MISSING" as const] : []),
    ...(!observability.monitors_containment_violations ? ["OBSERVABILITY_MODEL_MISSING" as const] : []),
    ...(evidence.evidence_refs.length !== 8 || !evidence.captures_previous_state ? ["EVIDENCE_MODEL_INCOMPLETE" as const] : []),
  ])]);
  const certification = nested({ certification_id: "P5.2-TRUST-IDENTITY-DOMAINS-BOUNDARIES-QUALIFICATION-001", outcome: outcome(derivedFailures), phase_ready: outcome(derivedFailures) === "PASS", trust_identity_uniqueness: !has(derivedFailures, "TRUST_IDENTITY_NOT_UNIQUE"), trust_identity_determinism: identity.deterministic, trust_domain_containment: resolution.trust_domain_subset_tenant_boundary, tenant_trust_isolation: tenant_isolation.all_tenant_refs_equal, domain_hierarchy_validity: trust_domain_registry.hierarchy_validated, trust_boundary_completeness: domain.trust_boundary_id.length > 0 && boundary.prohibited_crossings.length > 0, registry_separation: registrySeparation, registry_integrity: registryIntegrity, namespace_conflict_handling: trust_registry.rejects_ambiguous_registration, lifecycle_correctness: String(identity.lifecycle_status) !== String(identity.registration_status) && security.suspension_revocation_enforced, decision_status_separation: trust_registry.separates_lifecycle_from_registration_decision, governance_authority_enforcement: governance.registration_authorities_defined && governance.no_cross_tenant_mutation, evidence_completeness: evidence.evidence_refs.length === 8 && evidence.immutable_lineage_preserved, deterministic_replay: resolution.deterministic_containment_validation && evidence.replayable_history, cross_tenant_leakage_prevention: trust_registry.prevents_cross_tenant_discovery && security.anti_enumeration_controls, fail_closed_resolution: trust_registry.fail_closed_resolution && security.fail_closed_resolution, failures: derivedFailures });
  const base: Omit<TrustIdentityDomainBoundaryResult, "replay_hash" | "integrity_hash"> = { phase_version: VERSION, phase_identifier: IDENTIFIER, trust_constitution_ref: TRUST_CONSTITUTION_REF, trust_architecture_ref: TRUST_ARCHITECTURE_REF, trust_registry, trust_domain_registry, trust_boundary_registry, tenant_isolation, resolution, governance, evidence, security, observability, certification };
  const replay_hash = resultReplayHash(base);
  return Object.freeze({ ...base, replay_hash, integrity_hash: resultIntegrityHash({ ...base, replay_hash }) });
}

export function validateTrustIdentityDomainsBoundaries(result?: TrustIdentityDomainBoundaryResult): TrustIdentityDomainBoundaryValidation {
  if (!result) return nested({ valid: false, outcome: "FAIL" as const, replay_hash_valid: false, integrity_hash_valid: false, trust_registry_valid: false, domain_registry_valid: false, boundary_registry_valid: false, tenant_isolation_valid: false, resolution_valid: false, governance_valid: false, evidence_valid: false, security_valid: false, observability_valid: false, certification_valid: false, failures: freezeArray(["TRUST_REGISTRY_MISSING" as const]) });
  const replay_hash_valid = resultReplayHash(result) === result.replay_hash;
  const integrity_hash_valid = resultIntegrityHash(result) === result.integrity_hash;
  const trust_registry_valid = verifyHashed(result.trust_registry) && result.trust_registry.identities.length > 0 && result.trust_registry.tenant_scoped && result.trust_registry.rejects_ambiguous_registration && result.trust_registry.preserves_history && result.trust_registry.separates_identity_from_trust_status && result.trust_registry.separates_lifecycle_from_registration_decision && result.trust_registry.fail_closed_resolution && result.trust_registry.prevents_cross_tenant_discovery;
  const domain_registry_valid = verifyHashed(result.trust_domain_registry) && result.trust_domain_registry.domains.length > 0 && result.trust_domain_registry.tenant_containment_validated && result.trust_domain_registry.hierarchy_validated && result.trust_domain_registry.membership_queries_tenant_scoped && result.trust_domain_registry.deterministic_historical_replay;
  const boundary_registry_valid = verifyHashed(result.trust_boundary_registry) && result.trust_boundary_registry.boundaries.length > 0 && result.trust_boundary_registry.boundary_to_domain_resolution && result.trust_boundary_registry.boundary_to_tenant_resolution && result.trust_boundary_registry.conflict_detection && result.trust_boundary_registry.deterministic_historical_reconstruction;
  const tenant_isolation_valid = verifyHashed(result.tenant_isolation) && result.tenant_isolation.all_tenant_refs_equal && !result.tenant_isolation.foreign_evidence_authoritative_by_default && !result.tenant_isolation.delegation_bypasses_isolation && !result.tenant_isolation.federation_merges_domains && result.tenant_isolation.registry_queries_tenant_scoped;
  const resolution_valid = verifyHashed(result.resolution) && result.resolution.terminates_in_exactly_one_tenant_boundary && result.resolution.identity_to_domain_resolved && result.resolution.domain_to_boundary_resolved && result.resolution.boundary_to_tenant_resolved && result.resolution.trust_domain_subset_tenant_boundary && result.resolution.deterministic_containment_validation && result.resolution.fail_closed_on_ambiguity;
  const governance_valid = verifyHashed(result.governance) && result.governance.registration_authorities_defined && result.governance.mutation_permissions_defined && result.governance.conflict_escalation_defined && result.governance.no_self_approval_unless_governed && result.governance.no_cross_tenant_mutation && result.governance.exceptional_cross_domain_interaction_requires_governance;
  const evidence_valid = verifyHashed(result.evidence) && result.evidence.evidence_refs.length === 8 && result.evidence.captures_previous_state && result.evidence.captures_proposed_state && result.evidence.captures_validation_results && result.evidence.captures_conflicts_detected && result.evidence.emits_audit_records && result.evidence.immutable_lineage_preserved && result.evidence.replayable_history;
  const security_valid = verifyHashed(result.security) && result.security.tenant_scoped_authorization && result.security.role_based_field_visibility && result.security.anti_enumeration_controls && result.security.namespace_protection && result.security.mutation_authorization && result.security.stale_write_prevention && result.security.suspension_revocation_enforced && result.security.fail_closed_resolution;
  const observability_valid = verifyHashed(result.observability) && result.observability.metric_refs.length === 11 && result.observability.monitors_containment_violations && result.observability.monitors_isolation_violations && result.observability.monitors_namespace_conflicts && result.observability.monitors_integrity_failures && result.observability.monitors_replay_divergence && result.observability.monitors_unauthorized_queries;
  const certification_valid = verifyHashed(result.certification) && result.certification.outcome === "PASS" && result.certification.phase_ready && result.certification.failures.length === 0;
  const valid = replay_hash_valid && integrity_hash_valid && trust_registry_valid && domain_registry_valid && boundary_registry_valid && tenant_isolation_valid && resolution_valid && governance_valid && evidence_valid && security_valid && observability_valid && certification_valid;
  return nested({ valid, outcome: result.certification.outcome, replay_hash_valid, integrity_hash_valid, trust_registry_valid, domain_registry_valid, boundary_registry_valid, tenant_isolation_valid, resolution_valid, governance_valid, evidence_valid, security_valid, observability_valid, certification_valid, failures: result.certification.failures });
}

export function replayTrustIdentityDomainsBoundaries(result = runTrustIdentityDomainsBoundaries()): boolean {
  const replayed = runTrustIdentityDomainsBoundaries();
  return result.replay_hash === replayed.replay_hash && result.integrity_hash === replayed.integrity_hash && validateTrustIdentityDomainsBoundaries(result).valid;
}

export function getTrustIdentityDomainsBoundariesBundle(): TrustIdentityDomainBoundaryBundle {
  const result = runTrustIdentityDomainsBoundaries();
  return Object.freeze({ doctrine: Object.freeze({ version: VERSION, owns_trust_identities: true, owns_trust_domains: true, owns_trust_boundaries: true, owns_tenant_trust_isolation: true, owns_trust_registries: true, implements_trust_scoring: false, implements_trust_evaluation: false, issues_credentials: false, executes_federation: false, authorizes_execution: false }), result, validation: validateTrustIdentityDomainsBoundaries(result) });
}

export const TrustIdentityDomainsBoundariesService = Object.freeze({ run: runTrustIdentityDomainsBoundaries, validate: validateTrustIdentityDomainsBoundaries, replay: replayTrustIdentityDomainsBoundaries });
