"use client";

import Link from "next/link";
import { ChangeEvent, useEffect, useState } from "react";

type Health = { storage: string; chores: number; shoppingItems: number; members: number; completedChores: number; };

export default function SettingsPage() {
  const [health, setHealth] = useState<Health | null>(null);
  const [message, setMessage] = useState("Checking your household storage…");
  const refresh = async () => { const response = await fetch("/api/household?resource=health"); const data = await response.json() as Health & { error?: string }; if (!response.ok) throw new Error(data.error ?? "Unable to check storage."); setHealth(data); };
  useEffect(() => { void refresh().then(() => setMessage("Your household data is ready.")) .catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Unable to check storage.")); }, []);
  async function downloadBackup() { const response = await fetch("/api/household?resource=backup"); if (!response.ok) { setMessage("Unable to create a backup."); return; } const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `household-manager-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); setMessage("Backup downloaded. Keep it somewhere safe."); }
  async function restoreBackup(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!window.confirm("Restore this backup? It will replace the current household location, tasks, chores, shopping list, and completion history.")) { event.target.value = ""; return; } try { const snapshot = JSON.parse(await file.text()); const response = await fetch("/api/household", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resource: "backup", action: "restore", snapshot }) }); const result = await response.json() as Health & { error?: string }; if (!response.ok) throw new Error(result.error ?? "Unable to restore backup."); setHealth({ storage: "SQLite", chores: result.chores, shoppingItems: result.shoppingItems, members: result.members, completedChores: result.completedChores }); setMessage("Backup restored successfully."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to restore backup."); } finally { event.target.value = ""; } }
  return <main><nav className="top-nav"><Link className="brand" href="/">Household Manager</Link><Link href="/household">Chores &amp; shopping</Link></nav><section className="settings-hero"><p className="eyebrow">Data &amp; reliability</p><h1>Your household,<br />kept safe.</h1><p className="lede">Export a portable snapshot whenever you want, or restore the household from a previous backup.</p></section><section className="settings-grid"><article className="settings-card"><p className="eyebrow">Export</p><h2>Take a snapshot.</h2><p className="meta">A JSON backup includes location, weather tasks, chores, household members, shopping items, and completion history.</p><button type="button" onClick={() => void downloadBackup()}>Download backup</button></article><article className="settings-card danger-card"><p className="eyebrow">Restore</p><h2>Bring data back.</h2><p className="meta">Restoring replaces the current household data. Export the current state first if you may need it again.</p><label className="file-button">Choose backup file<input type="file" accept="application/json,.json" onChange={restoreBackup} /></label></article></section><section className="health-card"><div><p className="eyebrow">Storage status</p><h2>{health ? `${health.storage} is healthy` : "Checking storage"}</h2><p className="meta">{message}</p></div>{health && <div className="health-stats"><span><strong>{health.members}</strong> members</span><span><strong>{health.chores}</strong> chores</span><span><strong>{health.shoppingItems}</strong> shopping items</span><span><strong>{health.completedChores}</strong> completions</span></div>}</section></main>;
}
