import { randomUUID } from "node:crypto";
import { z } from "zod";
import { getSessionUser } from "@/src/lib/auth";
import { AppError } from "@/src/server/api/errors";
import { apiError, apiSuccess } from "@/src/server/api/response";
import { requireWorkspaceManager } from "@/src/server/auth/permissions";
import { PrismaLearningAuditLedger, PrismaStrategyEvaluationRepository, PrismaStrategyRegistryRepository, SelectionOutcomeDiagnosisService, StrategySelectionEngineService, StrategySelectionRecordService } from "@/services/learning-constitution";
import type { SelectionOutcome, StrategyEvaluation } from "@/types/learning-constitution";
export const dynamic = "force-dynamic";
const schema = z.object({ outcomeId: z.string().min(1).max(200) });
/** Diagnoses an immutable outcome and records an advisory reselection only; it cannot switch an active plan or lease. */
export async function POST(request: Request) { try { const user = await getSessionUser(); if (!user) throw new AppError(401, "unauthorized", "Authentication required."); if (!user.workspaceId || user.workspaceId === "default") throw new AppError(403, "workspace_required", "Workspace membership is required."); await requireWorkspaceManager({ userId: user.id, userRole: user.role, workspaceId: user.workspaceId }); const body = schema.parse(await request.json()); const registry = new PrismaStrategyRegistryRepository(user.workspaceId); const artifacts = await registry.listWorkspaceArtifacts(); const outcomeArtifact = artifacts.find((item) => item.artifactType === "STRATEGY_SELECTION_OUTCOME" && (item.payload as SelectionOutcome).outcomeId === body.outcomeId); if (!outcomeArtifact) throw new AppError(404, "selection_outcome_not_found", "Strategy selection outcome not found."); const outcome = outcomeArtifact.payload as SelectionOutcome; const evaluationArtifact = (await new PrismaStrategyEvaluationRepository(user.workspaceId).listWorkspaceArtifacts()).find((item) => (item.payload as StrategyEvaluation).evaluationId === outcome.evaluationId); if (!evaluationArtifact) throw new AppError(409, "outcome_evaluation_unavailable", "Outcome evaluation is unavailable."); const now = new Date().toISOString(); const diagnosis = new SelectionOutcomeDiagnosisService().diagnose({ outcome, evaluation: evaluationArtifact.payload as StrategyEvaluation, createdAt: now }); if (!diagnosis.failure) return apiSuccess({ diagnosis, reselection: null, next: "No reselection is recommended from this outcome." }); const reselection = new StrategySelectionEngineService().reselect({ reselectionId: `SSR-${randomUUID()}`, priorSelectionId: outcome.selectionId, failureAttributionId: outcome.outcomeId, failure: diagnosis.failure, createdAt: now }); const actor = { actorId: `human:${user.id}`, actorType: "HUMAN" as const }; await new StrategySelectionRecordService(registry, new PrismaLearningAuditLedger(user.workspaceId)).reselection(reselection, user.workspaceId, actor, `strategy-reselection:${reselection.reselectionId}`); return apiSuccess({ diagnosis, reselection, next: "Reselection is advisory. A new approved plan and lease are required before any strategy can change." }, { status: 201 }); } catch (error) { return apiError(error, "Unable to diagnose strategy selection outcome."); } }
